.github/workflows/lint.yml

The `import/no-unresolved` rule will fail if you depend on another module in the monorepo which hasn't yet been built. Thus; we need to actually build all modules before running the linter.
eslints `import/no-unresolved` fails when depending on sibling module, since it points to a compiled version which is not yet available.
This PR makes sure we build the modules prior to running the linter. Not ideal, but can't see a good workaround right now.
**Checklist**

[chore] Build modules before running lint

---

packages/@sanity/base/src/components/Document.js

Currently, self-hosted studios might be indexed by crawlers/search engines, unless they send the correct headers. While this is not _necessarily_ a problem, I think it's fairly uncommon that anyone would want their studio to be indexed. In the future we can probably make this configurable, but I think it's more work than necessary at the moment.
This PR adds a new meta tag that tells robots not to index the page.
- Prevent crawlers/search engines from indexing studio
**Checklist**

[base] Prevent robots from crawling/indexing studios

---

.github/workflows/lint.yml

Files like `LICENSE` and `.css`-files are being included in the `eslint` run in CI if they changed and would cause a failure.
This change includes an extra `sed` step which filters out all files that don't need to be run `eslint` on. Files that will be linted are:
* `.mjs`
* `.jsx`
* `.tsx`
* `.js`
* `.ts`
**Checklist**

[chore] Fix bug where CI tried to lint non-js files

---

packages/@sanity/components/src/selects/SearchableSelect.css

The top part of the searchable select scrollbar is unusable with the mouse because of an overlaying hidden div with the 'no results' message. 
The hidden text should either be made unusable with `pointer-events: none` or completely hidden and out of the way (other than with opacity), for example with a `transform: scale(0)`. 
Fixed a bug where the top part of the searchable select dropdown scrollbar was being blocked by a hidden div.
**Checklist**

[selects/searchable-style] add `pointer-events: none` to noResultTextHidden to fix it blocking the scrollbar

---

packages/@sanity/core/src/actions/start/startAction.js

This PR prevents using dataset aliases in studios, as it will fail to perform mutations, asset uploads and connect to the presence layer.
**Checklist**

[core] Disallow using aliases for studios

---

packages/@sanity/client/src/validators.js
packages/@sanity/client/test/client.test.js

The Sanity JS client currently crashes when using an alias in the `dataset` field.
This PR let's the alias format through the dataset validator. Aliases starts with the `~` character, and isn't currently allowed.
Add support for using aliases in the Sanity JS client
**Checklist**

[client] Add dataset alias support in client

---

packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js

Without this users have no way of knowing which dataset is prompted for
in interactive mode.
There is no difference between the interactive prompts for source and target dataset when initiating a Cloud Copy.
This fix customises the prompt so they're different.
**Checklist**

[core] Specify target/source dataset in copy prompt

---

.github/workflows/lint.yml

For cases where there are many hundred changed files in a PR the shell will break because of too long a command.
This change alters the behaviour of the lint CI action to lint each file individually. This will take longer, however in most cases the slowdown won't be noticed.
If it's a problem over time we can look into chunking.
**Checklist**

[chore] Make linting in CI handle changes with many files better

---

packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js

No option for skipping history when copying datasets.
This change adds an option to the dataset copy command to skip history during copy.
Should update docs.
**Checklist**

[core] Add --skip-history flag to dataset copy

---

package.json
packages/@sanity/base/src/__legacy/@sanity/components/previews/DefaultPreview.tsx
packages/@sanity/base/src/datastores/document/document-pair/checkoutPair.ts
packages/@sanity/core/src/actions/graphql/SchemaError.js
packages/@sanity/preview/src/components/ObserveForPreview.tsx

Since we clamp the prettier version in `package.json` with `^2.1.2` we will automatically pull in all upgrades as long as the major version is 2. However this might produce different formatting conventions depending on "when" you ran `npm install`. CI always being the one running the newest since they always run install before running format.
This change clamps the version on `2.1.2`. Producing consistent formatting. However we should make sure to update `prettier` now and then by upping the version in the string. Although that might mean changes to the whole code base so it's nice to have control over.
This could also be solved by having a more …

Make sure all environments use the same version of prettier

---

packages/@sanity/form-builder/src/sanity/inputResolver/resolveArrayInput.ts

Currently fails to build when attempting to infer return type for `resolveArrayInput`
This PR introduces proper typings for the  `resolveArrayInput` module. Also replaces lodash.get usage with optional chaining syntax.
**Checklist**

[form-builder] Fix typings for resolveArrayInput

---

gulpfile.js
scripts/runTsc.js

Currently `npm run build` doesn't fail on TypeScript compile errors.
This PR makes sure "npm run build" fails on TypeScript compile errors. Also runs tsc after babel to make sure the path aliases actually gets resolved, And improves console output of TS compile errors.

[chore] Fail build script on TS compile errors + smaller improvements

---

packages/@sanity/server/package.json

When upgrading sanity packages released from `next` you'll get an error saying that the `tsconfig` and `find-config` modules cannot be found.
This adds `tsconfig` and `find-config` as dependencies to `@sanity/server`
N/A

[server] Add missing dependencies

---

packages/@sanity/core/src/actions/dataset/alias/datasetAliasNamePrompt.js
packages/@sanity/core/src/actions/dataset/alias/validateDatasetAliasName.js
packages/@sanity/core/src/commands/dataset/alias/aliasCommands.js
packages/@sanity/core/src/commands/dataset/alias/createAliasHandler.js
packages/@sanity/core/src/commands/dataset/alias/datasetAliasesClient.js
packages/@sanity/core/src/commands/dataset/alias/deleteAliasHandler.js
packages/@sanity/core/src/commands/dataset/alias/linkAliasHandler.js
packages/@sanity/core/src/commands/dataset/alias/listAliasesHandler.js
packages/@sanity/core/src/commands/dataset/alias/unlinkAliasHandler.js
packages/@sanity/core/src/commands/dataset/listDatasetsCommand.js
packages/@sanity/core/src/commands/index.js

This PR adds support for `dataset` `alias` in the sanity CLI. It provides the interface to interact and manage `dataset` `alias`
Added support for the following sub commands to dataset
```bash
$ sanity dataset alias create <alias-name> <target-dataset>
$ sanity dataset alias delete <alias-name>
$ sanity dataset alias link <alias-name> <target-dataset>
$ sanity dataset alias unlink <alias-name>
```
**Checklist**

[core] Add dataset alias support

---

packages/@sanity/base/types/parts.d.ts

The PR #2150 accidentally removed a file that studios using TypeScript relies on and that our official docs refers to. This patch restores it.
- Fixed an issue causing part imports to produce a compile error in studios using TypeScript

[base] Restore typing stubs

---

packages/@sanity/language-filter/src/SelectLanguage.js

The language filter doesn't show a label for the available options in the dropdown:
This PR fixes the use of the `Checkbox` component so the labels are rendered:
Ideally we'd migrate this to `@sanity/ui`, but will leave that for another time.
- Fixed language labels not appearing in the language-filter plugin
**Checklist**

[language-filter] Add missing labels for languages

---

packages/@sanity/base/src/__legacy/@sanity/components/fieldsets/DefaultFieldset.tsx

When opening fieldsets, the editor scrolls to the top (of the form, not the fieldset), focusing the first input.
This PR attempts to address the issue, but I'm not 100% sure it's the right approach since I don't know the focus subsystem all too well. I had another approach where I instead passed a custom `onFocus` to the fieldset, which checked for a terminator path and instead focused the first field within the fieldset. This _felt_ right, but it was inconsistent with how collapsed objects functioned. In other words: please let me know if there is a better solution to this.
Fixes #2094
- Fix issue where opening fieldsets would …

[base] Don't call onFocus when toggling fieldsets

---

examples/design-studio/package.json
package.json
packages/@sanity/base/src/__legacy/@sanity/components/snackbar/SnackbarItem.tsx
packages/@sanity/base/src/__legacy/@sanity/components/snackbar/SnackbarProvider.tsx
packages/@sanity/base/src/__legacy/@sanity/components/tabs/Tab.tsx
packages/@sanity/diff/package.json
packages/@sanity/field/package.json
packages/@sanity/google-maps-input/package.json
packages/@sanity/google-maps-input/src/input/GeopointSelect.tsx
packages/@sanity/google-maps-input/src/map/Arrow.tsx
packages/@sanity/google-maps-input/src/map/Map.tsx
packages/@sanity/google-maps-input/src/map/Marker.tsx
packages/@sanity/initial-value-templates/package.json
packages/@sanity/react-hooks/package.json
packages/@sanity/structure/package.json
packages/@sanity/transaction-collator/package.json

This adds three commits that can be reviewed individually:
There was suddenly build errors on setTimeout return values which I suspect was due to a new minor/patch release of TypeScript. This fixes the issue by using `ReturnType<typeof setTimeout>` as type for timer id where applicable.
Looks like there has been some changes to the type definitions in @types/googlemaps recently that broke the google-maps-input package
This upgrades typescript in the monorepo to latest (4.1.3) and at the same time removes typescript as dev dependency from some individual packages that still had it around)

Fix a few TS issues

---

packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/views/editForm.tsx

Scrolls to _top_ of the element containing the first segment of the focus path.
When you have a portable text field at the bottom of object and have not yet focused any element in the form, then click the "activate" handler on it, it scrolls to the top of the form. This is caused by the editor attempting to scroll to the top of the first segment in the focus path (the object). Previously we scrolled to the _center_, which meant we sometime scrolled _past_ the field (such as with a large form and clicking the first field). This PR scrolls to the _nearest_ point, which seems more correct at least.
I'm still not sure I feel this is the right solution, …

[desk-tool] Scroll to nearest block if on focus path change

---

packages/@sanity/import/src/validateAssetDocuments.js

https://github.com/sanity-io/sanity/issues/2206
See issue.
**Checklist**

[import] Honor the --allow-failing-assets flag

---

packages/@sanity/form-builder/src/inputs/common/Details.css
packages/@sanity/form-builder/src/inputs/common/Details.tsx

Currently the root element of the `Details`-component that we use to support expandable/collapsable content in the form builder is a button element. This causes several issues, but the most notable one is that any click inside it will collapse it. For example, the "unknown field" warning no longer accepts clicks on it's content, and instead collapses when clicking on anything inside:
(reproducible at the bottom of the page here: https://test-studio-git-current.sanity-io.vercel.app/test/desk/book;f4d76e3b-1d8b-4321-b79a-87f7e6b84446%2Ctemplate%3Dbook)
In cases where it was used to contain buttons and other interactive elements it also produced a console warning …

[form-builder] Don't wrap Details content in a button

---

packages/@sanity/base/package.json
packages/@sanity/base/scripts/writeRequiredUIVersion.js
packages/@sanity/base/src/components/SanityRoot.tsx
packages/@sanity/base/src/requiredSanityUiVersion.ts

Since `@sanity/base` depends on `@sanity/ui`, users who install `@sanity/ui` themselves may end up with multiple versions of `@sanity/ui` in their project. This causes the application to throw the error:
```
Error: useRootTheme(): missing context value
```
- This change includes calling `useRootTheme` in the application root, and catching it if it fails.
- When `useRootTheme` fails, we instead render a helpful message.
- Renders an improved error message when experiencing issues with multiple versions of `@sanity/ui`.

[chore] Fix issues with multiple versions of Sanity UI

---

packages/@sanity/schema/src/sanity/validation/types/common.ts
packages/@sanity/schema/src/sanity/validation/utils/validateNonObjectFieldsProp.ts
packages/@sanity/validation/src/inferFromSchemaType.js

If you make a schema type that is not of type `object` (or a type that inherits from it, eg `image`, `document`), providing a  `fields` property will silently be ignored, until you add a `validation` property - at which point the validation code will crash.
This PR fixes these two issues separately:
- Skips the `fields` validation iteration if operating on a non-object type
- Validates that `fields` is only used on object types
Reported [in the community](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1610841717279900)
- Added check to ensure that `fields` is only used on object types
**Checklist**

[schema] Ensure "fields" property is not used on non-object types

---

packages/@sanity/form-builder/src/components/Details.tsx

The `Details` component is used by:
- `inputs/Warning.tsx`
- `inputs/arrays/ArrayOfObjectsInput.tsx`
- `inputs/ObjectInput/UnknownFields.tsx`

[form-builder] Migrate Details component to Sanity UI

---

packages/@sanity/base/src/components/formField/FormField.tsx
packages/@sanity/base/src/components/formField/FormFieldHeader.tsx
packages/@sanity/base/src/components/formField/FormFieldHeaderText.tsx
packages/@sanity/base/src/components/formField/FormFieldSet.tsx
packages/@sanity/base/src/components/formField/FormFieldSetLegend.tsx
packages/@sanity/base/src/components/formField/FormFieldValidationStatus.tsx
packages/@sanity/base/src/components/formField/helpers.ts
packages/@sanity/base/src/components/formField/index.ts
packages/@sanity/base/src/components/formField/styles.ts
packages/@sanity/base/src/components/formField/types.ts
packages/@sanity/base/src/components/index.ts
packages/@sanity/base/src/theme/index.ts

This change introduces 4 new public components for building form field components:
```tsx
import {
FormField,
FormFieldHeaderText,
FormFieldSet,
FormFieldValidationStatus,
} from '@sanity/base/components'
```
- New building blocks for composing form fields, that will be used by `@sanity/form-builder` and to create custom input components.

[base] New form field components

---

packages/@sanity/server/package.json
packages/@sanity/server/src/configs/getModulePath.js
packages/@sanity/server/src/configs/webpack.config.dev.js
packages/@sanity/server/src/configs/webpack.config.js

When attempting to import say `react-dom/server`, the webpack alias prevents this as we're resolving it to a specific file. 
This PR changes the resolving of the react/react-dom aliases: it first resolves using `require.resolve`, then looks up the directory tree for the closest `package.json` and uses that folder as the alias target. This ensures both the entry/root will resolve correctly, _and_ subpaths.
- Fix bug where importing `react-dom/server` would not work 
**Checklist**

[server] Make react/react-dom alias to folders, not files

---

packages/@sanity/base/src/theme/color/index.ts
packages/@sanity/base/src/theme/color/input.ts
packages/@sanity/base/src/theme/index.ts

This change adds mapping of color values from the legacy theming to the Sanity UI theme object, so that input elements get the correct colors.
1. Open `examples/design-studio/themes/dev.css`
2. Change the `@import` to use `dark.css`
3. Start the Design Studio using `npm run design-studio`
4. Make sure all inputs have the expected color (defined in `dark.css`)

[base] Use legacy theming for Sanity UI inputs

---

packages/@sanity/form-builder/src/inputs/PortableText/Objects/EditObject.tsx

It's currently impossible to set the annotation editing modal in the Portable Text Editor to `dialog`. Only `fullscreen` and `popover` will work.
Fix bug where PTE didn't respect editModal option from schema.
**Checklist**

[form-builder] Fix bug where PTE didn't respect editModal option from schema.

---

packages/@sanity/form-builder/src/inputs/SelectInput.tsx

* Fixed a typo in the value where we should have used `-` instead of `+`. Other than that the idea is the same - use index to map between value and item
* Added `value` to the select so that it'll have the right value selected on for example undo from review changes

[form-builder] Fix bug where SelectInput sent the wrong update patch

---

packages/@sanity/form-builder/src/inputs/SelectInput.tsx

This change should fix the warning in console complaining about that you can't have a `checked` prop without having `onChange`.
* Rename `onClick` to `onChange` in the usage of `Radio` from `Sanity-UI` (the `onChange` as far as I can see should work since we send the item itself)
* Send `inputId` which is sent to `FormField` to `RadioInput` as well to give the radios a name which should fix tabbed navigation

[form-builder] Fix bug where radio was missing onChange

---

packages/@sanity/form-builder/src/inputs/SelectInput.tsx
packages/@sanity/form-builder/src/inputs/types.ts

This makes sure we emit onFocus from Select Input (including radio select). Had to modify the signature of Input component Props type to better reflect the reality (in the future, allowing `React.FocusEvent<any>` should go into a convenience wrapper for custom inputs so we can avoid having to verify/normalized the passed event at different steps).

[form-builder] Emit onFocus from select + radio select inputs

---

packages/@sanity/form-builder/src/inputs/TextInput.tsx

- Fixes issue with the `rows` property’s default value being different than before.
- Fixes issue with the `textarea` missing its resize affordance.

[form-builder] Text inputs should be resizable and have a larger default height

---

packages/@sanity/cli/src/util/parseArguments.js
packages/@sanity/core/package.json
packages/@sanity/core/src/actions/graphql/deployApiAction.js
packages/@sanity/core/src/actions/graphql/extractFromSanitySchema.js
packages/@sanity/core/src/commands/graphql/deployGraphQLAPICommand.js

In a previous release, we set the document interface fields (`_id`, `_type`, `_createdAt` and such) to be nullable, because you can use a document type as an (unreferenced) object in a document field or array. In these situations, `_createdAt` would not be present - so flagging it as non-nullable was incorrect.
In many cases this is not something that you actually use, however - you usually create objects for things you want to inline and documents for things you want to reference. Having these fields be non-null can greatly enhance the development experience.
This PR adds a flag you can use to opt-in for non-nullable document fields. This way the …

[core] GraphQL: Add --non-null-document-fields flag

---

examples/test-studio/schemas/validation.js
examples/test-studio/src/components/CustomObjectSelectInput.tsx
packages/@sanity/validation/package.json
packages/@sanity/validation/src/inferFromSchemaType.js
packages/@sanity/validation/src/validators/arrayValidator.js
packages/@sanity/validation/src/validators/genericValidator.js
packages/@sanity/validation/test/infer.test.js

Note: This is quite an edge-case, but be patient with me:
If you...
1. Have an object type that defines the field `value`
2. Add the (non-standard) `options.list` configuration (generally seen in `string` and `number` types) on the field/type
3. Set a (valid) value on the field 
... when the validation inference runs on the schema types, it will incorrectly grab the value of the `value` field, instead of the object itself. When comparing the value of the object field (`{value: 'foo', other: 'props'}`) against the "allowed" values, it will never find a match, since it's comparing the nested value of the `value` prop instead of the root object.
This results in a …

[validation] Fix bug on object type with "value" field + "list" option

---

examples/test-studio/schemas/arrays.js
packages/@sanity/base/src/components/formField/FormField.tsx

This change makes the new `FormField` component behave the same way as the legacy `DefaultFormField` component with regards to the `title` (previously `label`) property.
The `DefaultFormField` hides the entire form field header when no `title` is provided. Although this is not ideal in all scenarios, this is something we will continue to do for backwards compatibility.
This change affects mainly arrays with primitive types, but may affect all fields using the new `FormField` component.
**How to test:**
- Start the test studio: `npm run test-studio`
- Open the arrays test: http://localhost:3333/test/desk/arraysTest
- Make sure the items in **Array with primitive types** have a header title
- Make sure the items in **Array of strings** have no header title
- Fixes a visual regression that …

[base] Fix: make the new FormField behave the same way as DefaultFormField

---

packages/@sanity/form-builder/src/inputs/TextInput.tsx

Fixes #2258
Fixed an issue with text areas getting default (10) rows when using `rows: 0` on the schema type

[form-builder] TextInput: Only apply default when type.rows is not a number

---

examples/test-studio/schemas/strings.js
packages/@sanity/types/src/schema/asserters.ts

As #2088 describes - if you have additional attributes aside from `value` and `title` in the `options.list` configuration, we'll incorrectly try to use the entire object as the title, which results in a dropdown of `[object Object]`.
The validation seems a little over-eager to me. There isn't really any good reason (that I can see) why we have to enforce that `value` and `title` are the only two properties in the object. 
I've removed the check for `Object.keys(item).length === 2`, but we still check that both `value` and `title` is present.  Also added an example schema that reproduces the error. 
Fixes #2088
- Fix error where …

[types] Relax titled list option check, allow additional attributes

---

packages/@sanity/form-builder/src/inputs/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx

If the array of primitives input contains an unknown type that is not renderable (say, an object), it will crash when React attempts to render the item/object.
This PR checks if the value is a string or a number, and if not just renders "Unset" instead of "Unset <X>".
**Checklist**

[form-builder] Fix crash on rendering unknown value warning for objects

---

examples/test-studio/schemas/poppers.js
examples/test-studio/schemas/schema.js
packages/@sanity/base/src/__legacy/@sanity/components/selects/StatelessSearchableSelect.tsx

Code changes:
- The `SearchableSelect` now calls `popper.forceUpdate` whenever the height of the result items change.
- Replaces the [`altAxis`](https://popper.js.org/docs/v2/modifiers/prevent-overflow/#altaxis) and [`tether`](https://popper.js.org/docs/v2/modifiers/prevent-overflow/#tether) options in the `preventOverflow` modifier with using the `flip` modifier to fix situations in which the popper has insufficient room to expand below the reference element.
These changes solves the issue when a reference input is placed at the bottom of an array item, and the results box was cut off by the pane's scrollable element.
- Make sure the reference input's search result box is placed correctly in all situations.
- Fixes an issue with reference search results being cut off by the editor’s …

[base] Fix placement of SearchableSelect's result box

---

packages/@sanity/form-builder/src/inputs/BooleanInput.tsx

A bug was reported where `BooleanInput` had too much bottom padding. It's not supposed to look like that.
* Move the `BooleanInput` padding from the surrounding `Card` to the individual boxes making up the component in order to reduce the padding around the `Presence` field which has a certain height and what was caused the whitespace
* Move a `line-height` css prop to a styled component
​
​
This is very visual so shouldn't require too much reviewing.
1. Remove `readonly: true` from `switchIndeterminate2` in `examples/test-studio/schemas/booleans.js`
1. Navigate to `http://localhost:3333/test/desk/booleansTest;bd99e58a-845f-4d52-b54a-56a9b7af3be1` and look at the check box
​
​
* Fixed a bug where `BooleanInput`s without description text had unwanted bottom whitespace

Fix bug where BooleanInput had too much padding-bottom

---

packages/@sanity/cli/src/actions/versions/findSanityModuleVersions.js

We've had a lot of these:
```
useRootTheme(): missing context value
```
Which were caused by the `sanity upgrade` command also upgrading `@sanity/ui` for those few who've already installed it manually.
Problem is if a different version than the one `@sanity/base` is using is installed Studio will crash with that error.
* Add a hardcoded array of package names to ignore when upgrading
* Add `@sanity/ui` to the array
This will make sure the upgrade command doesn't upgrade `@sanity/ui`.
​
This is a very small change so shouldn't need a lot of review.
1. Build the repo `npm run build`
2. `cd examples/test-studio`
3. `npm install`
4. Install an old version of Sanity UI: `npm install @sanity/ui@0.32.8`
5. Make sure it shows up in `package.json`
6. Make sure you run the built version of CLI: …

[cli] Add array of packages excluded from update

---

examples/test-studio/sanity.json
examples/test-studio/src/tools/test-ui-error/tool.js
packages/@sanity/base/scripts/writeRequiredUIVersion.js
packages/@sanity/base/src/components/ErrorHandler.js
packages/@sanity/base/src/components/SanityRoot.tsx
packages/@sanity/base/src/requiredSanityUiVersion.ts
packages/@sanity/base/src/util/uncaughtErrorHandler.js

- Test Studio: Adds a tool called `Test UI error` (http://localhost:3333/test/test-ui-error)
- Removes the `^` from the version string written by `packages/@sanity/base/scripts/writeRequiredUIVersion.js`
- Ignore errors containing `useRootTheme():` in the global error handler `packages/@sanity/base/src/util/uncaughtErrorHandler.js`
- Introduces a `onUIError` callback in `ErrorHandler`, so that the theme error is caught and stored in `SanityRoot`’s react state.
- Now renders the theme error message when the error was uncaught.
- Renders the install command as `npm install @sanity/ui@0.32.8` instead of `npm install @sanity/ui@"^0.32.8"` (which was causing issues, and would actually set `"@sanity/ui": "^0.32.9"` in the user’s package.json)
- Make sure uncaught exceptions containing …

[base] Improve theme errors originating in @sanity/ui

---

packages/@sanity/desk-tool/package.json
packages/@sanity/desk-tool/src/panes/documentPane/statusBar/actionMenu.tsx

- Fixes #2275: a bug where the document actions menu closed before accepting click event.
- Bug fix (non-breaking change which fixes an issue)

[desk-tool] Fix document actions (onClickOutside behavior)

---

packages/@sanity/base/src/__legacy/@sanity/components/selects/StatelessSearchableSelect.tsx

Fixes a bug where the dropdown would get hidden within the dialog if
if the input is used with an array.

Fix bug where autocomplete dropdown was wrapped within dialog

---

packages/@sanity/base/src/__legacy/@sanity/components/selects/StatelessSearchableSelect.tsx

Tiny change to disable native auto complete for searchable selects.
- Disabled native `autoComplete` for searchable selects used in studio search and reference search.

[base] Always disable native autocomplete on searchable selects

---

.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/test_e2e.yml
.github/workflows/verify_format.yml

When installing dependencies for our GitHub actions to run, we download a chromium build through puppeteer, which is currently only necessary for the perf suite to run (as far as I can tell). This provides another point of failure (tests in a PR of mine stopped because the download server was giving a 503) and slows down the runs.
This PR sets the `PUPPETEER_SKIP_DOWNLOAD` environment variable to `true` on non-perf workflows, which should apparently stop the download from happening.
**Checklist**

[chore] CI: Skip puppeteer download on non-perf workflows

---

packages/@sanity/core/src/actions/graphql/getSanitySchema.js

This is an odd one, so hang tight:
- In order to evaluate and get hold of the Sanity schema within a Node.js context, we have to provide a fake browser environment. This is because of input components and such that are imported and assume a browser environment, which tends to crash. We use JSDom for this.
- That's not always enough. JSDom is missing a few globals, such as `requestAnimationFrame`, `InputEvent` and a few other oddities that some plugins feature detect or call. So we explicitly put these things onto the global, if not already there, and remove them again once  the schema is resolved. Pain.
- Some components add _events_ or event set _timers_ - …

[core] Close JSDOM window after schema is resolved

---

packages/@sanity/core/src/actions/graphql/deployApiAction.js

When you run `sanity graphql deploy` in a CI or non-interactive prompt (eg `sanity graphql deploy | grep foo`), it will stall because of prompts waiting for an answer (do you want a playground? do you want to proceed despite dangerous changes?).
This PR checks for CI/non-interactive environments and skips the prompts if true:
- The playground prompt defaults to the current state (if there is one currently deployed) and falls back to `true` otherwise
- Mismatch in GraphQL generation throws an error (unless `--force`)
- Dangerous/breaking changes throws an error  (unless `--force`)
There's a slight change in behavior for interactive environments, too: …

[core] GraphQL: Skip prompts in non-interactive/CI environment

---

cypress/integration/datetimeInput.js
packages/@sanity/form-builder/src/inputs/DateInputs/BaseDateTimeInput.tsx

​
We use `react-datepicker`, it let's us specify the component that should wrap the datepicker. Previously we used `React.usePortal` directly to do this. But that doesn't work optimally with the new `Layer`-system of Sanity UI.
Change it to be wrapped inside a `Layer` so it's put on top.
This also adds an e2e-test which makes sure the datepicker is visible both on top of a dialog and without a dialog.
​
Can we use `Layer` "naively" in this way or should we specify the z-index directly?
I also believe this changes where the datepicker is put into the DOM. Does that create some consequences for other inputs that I haven't noticed while testing?
​
​
* Fixed a bug where datepicker was hidden behind dialogs

[form-builder] Fix bug where datetime popper would be hidden behind dialogs

---

packages/@sanity/base/src/__legacy/@sanity/components/utilities/ActivateOnFocus.tsx
packages/@sanity/form-builder/src/inputs/PortableText/BlockExtras.css
packages/@sanity/form-builder/src/inputs/PortableText/BlockExtras.tsx

This bug was caused by using `Layer` within the dialogs (in `ActivateOnFocus` and `BlockExtras`), causing the `isTopLayer` property of the layer context of `Dialog` to be false (and hence blocking closing dialogs on ESC).
Report:
> The esc key doesn’t close dialogs/modals reliably on the new version. E.g. when nesting in multiple levels, it’s frequently not possible to dismiss them all back to the document with escape key on v2.2.6/2.3.2.

[form-builder] Fix ESC key behavior in nested dialogs

---

examples/test-studio/schemas/urls.js
packages/@sanity/form-builder/src/inputs/UrlInput.tsx

- Fixes a bug where the URLInput was erroneously showing as `:invalid` when `allowRelative: true` was set in the URI validation.
Report:
> I have a standard URL field that is rather angry on the new version, but the same field with the same data is fine on the previous version. There are no validation errors on it in either version.
- Go to the URLs test: http://localhost:3333/test/desk/urlsTest
- Check that plain URL fields and URL fields with `allowRelative` behave correctly.

[form-builder] Fix wrong invalid state in UrlInput

---

packages/@sanity/form-builder/src/inputs/SelectInput.tsx

Report:
> Radio options have increased in size significantly. The former size was much more practical for presenting many options in a reasonable amount of space.

[form-builder] Fix spacing and font-size of RadioSelect

---

package.json

The config package we were using was very old and did not correspond to the newly published one.

[chore] Update sanity-eslint-config

---

packages/@sanity/base/src/components/ZIndexProvider.tsx

This change prevents console warnings from being printed when importing `ZIndexProvider`, by wrapping the conversion in a function.

[base] Prevent printing warnings when importing ZIndexProvider

---

packages/@sanity/util/src/pathUtils.ts

In studio forms we use arrays to denote paths within documents. We do quite a lot of passing paths props where paths hardly ever change, and most of the times these path arrays are created inline in render functions, and even though they hardly ever change, they will break React.memo's shallow compare. This PR adds a small util named `pathFor()` that, for any given path, always returns the same array instance, so that `pathFor(['some', 'property']) === pathFor(['some', 'property'])` holds true. This provides us with a handy utility to avoid unnecessary re-renders.
Considerations: Currently there's no invalidation and the memo array will hold an ever-growing array of path references. I'm not sure how big issue this will be in practice, but it sure def is a memory leak. We could consider …

perf(utils): introduce a memoized pathFor function that always resolves to the same path instance

---

packages/@sanity/util/src/pathUtils.ts

This builds on the utility introduced in #2307 and makes the trimLeft/trimRight utility functions pass the returned paths via the pathFor function to ensure referential equality with equal paths that has already been instantiated.
- Various performance optimizations

perf(util): optimize path utils functions to return memoized paths

---

packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.tsx
packages/@sanity/form-builder/src/sanity/inputs/SanityImageInput.tsx

Previously the ImageInput was wrapped by the `withDocument` HOC that provided it with the current document as a prop. This was then passed to the asset source plugin for convenience. This meant that whenever the document changed the image input would then receive a new `document` prop. Since it only forwarded the document to the asset source plugin, this patch instead wraps the asset source plugin in `withDocument`.
This should improve the render performance of the ImageInput since it no longer receives the enclosing `document` as a prop, which changes on every keystroke.
- Skip uneccessary re-rendring of image input when the edited document is changed

perf(form-builder): wrap the asset source plugin components in withDocument instead of the image input

---

packages/@sanity/server/src/configs/webpack.config.js

There is a build error when Sanity tries to render components that use react-native because there is no webpack alias resolving the import to react-native-web
We share many React components between web and native by leveraging react-native-web for web and are looking at rendering those inside of Sanity as part of a preview for content. 
This adds a Webpack alias that transforms imports made from `react-native` to import from `react-native-web`. This approach seems to be pretty common and has been advocated by projects like NextJS and create-react-app:
https://github.com/vercel/next.js/blob/f06c58911515d980e25c33874c5f18ade5ac99df/examples/with-react- …

[server] Alias react-native to react-native-web

---

packages/@sanity/default-layout/src/navbar/Navbar.css

When using a custom logo, the navbar got a bit taller, which ended up looking bad:
This PR simply centers the items vertically inside the navbar:
**Checklist**

[default-layout] Center navbar items vertically

---

packages/@sanity/form-builder/src/FormBuilderInput.tsx

This includes a shallow equality check of `path` and `focusPath` in the FormBuilderInput. These props rarely change, and doing this check should be fairly cheap (especially when using the pathFor utility introduced in #2307 for the passed `path`/`focusPath` props)
- Various performance optimizations

perf(form-builder): include path and focusPath in FormBuilderInput's shouldComponentUpdate check

---

packages/@sanity/base/src/__legacy/@sanity/components/fieldsets/DefaultFieldset.tsx

- Fixed an issue that caused clicks on labels within fieldsets to set focus in the wrong field

fix(form-builder): fix an issue that caused focus handler to be triggered by unfocusable fieldsets

---

packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.tsx

closes #2316
- Fixed a regression introduced in `v2.3.8` that didn't pass the document to imported asset source components

fix(form-builder): make sure document prop is passed to imported asset source components

---

packages/@sanity/default-layout/src/DefaultLayout.tsx

The global search is visible (flash) on the loading screen.
This change fixes the issue by increasing the `z-index` of the loading screen to be larger than the navbar’s `z-index`.

fix(default-layout): adjust the z-index of `AppLoadingScreen`

---

packages/@sanity/cli/package.json
packages/@sanity/cli/src/cli.js
packages/@sanity/cli/src/util/clientWrapper.js

When running CLI commands, any environment variables set in `.env`-files are not respected. For instance, running `sanity graphql deploy`, `sanity deploy` and `sanity users list` uses the values defined in `sanity.json` instead of respecting any `.env` file overrides.
This PR ensures any `.env`-file is read and used before running any CLI commands.
Fixes #2318
- `.env` files will now be loaded before running any Sanity CLI command
**Checklist**

feat(cli): load `.env` files before running any command

---

packages/@sanity/base/src/change-indicators/ChangeBar.tsx
packages/@sanity/base/src/change-indicators/ChangeIndicator.tsx
packages/@sanity/base/src/change-indicators/noop-tracker.tsx

Currently a different DOM tree is returned when toggling the change indicator for a field: https://github.com/sanity-io/sanity/blob/9f38c5a26652a2ad7f1aa69405c724e23a1d60c6/packages/%40sanity/base/src/change-indicators/ChangeIndicator.tsx#L240-L242
As a consequence the react reconciler will destroy the child nodes entirely and recreate when it is toggled. This is especially noticable when opening array items for editing in which the preview will be destroyed and recreated when opening/closing for edit, often triggering a reload of images etc.
This patch makes sure we maintain the same dom structure when toggling change indicators for a field.
- Prevent reloading/re-mounting of array items after open/close for edit

chore(form-builder): avoid destroying dom tree when enabling/disabling change indicator for a field

---

packages/@sanity/desk-tool/package.json
packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/views/editForm.tsx
packages/@sanity/form-builder/package.json
packages/@sanity/form-builder/src/hooks/useDidUpdate.ts
packages/@sanity/form-builder/src/hooks/usePrevious.ts
packages/@sanity/form-builder/src/hooks/useScrollIntoViewOnFocusWithin.ts
packages/@sanity/form-builder/src/inputs/ArrayInput/item/ArrayInputGridItem.css
packages/@sanity/form-builder/src/inputs/ArrayInput/item/ArrayInputGridItem.tsx
packages/@sanity/form-builder/src/inputs/ArrayInput/item/ArrayInputItem.tsx
packages/@sanity/form-builder/src/inputs/ArrayInput/item/ArrayInputListItem.css
packages/@sanity/form-builder/src/inputs/ArrayInput/item/ArrayInputListItem.tsx
packages/@sanity/form-builder/src/inputs/ArrayInput/item/helpers.ts
packages/@sanity/form-builder/src/inputs/PortableText/Input.tsx
packages/@sanity/form-builder/src/inputs/PortableText/Objects/BlockObject.tsx
packages/@sanity/form-builder/src/utils/focusUtils.ts

When a document node value is beeing edited in a dialog we want to make sure the input/preview of the parent/enclosing is scrolled into view in the background. Originally we solved this by responding to changes in the first element of the focus path (e.g. the top most document field name). Whenever the first element in the focus path changed, we'd then scroll to the dom element that had this as the value for `data-focus-path`. As a consequence, opening an item for edit would scroll the editor to the path of the _parent input_ into view, and this would sometimes trigger a scroll jump actually scrolling the field out of view because scrollIntoView would ensure the top edge of the parent input was in view. Instead, what we really wanted was to have the edited _item_ in view.
Fixes: #2280 …

fix(form-builder): move handling of ensuring parent item visibility inputs

---

packages/@sanity/base/src/index.ts
packages/@sanity/storybook/.babelrc
packages/@sanity/storybook/package.json
packages/@sanity/storybook/src/decorators/root.js
packages/@sanity/storybook/src/index.js
packages/@sanity/storybook/src/server/fork.js
packages/@sanity/storybook/src/server/server.js

Storybook crashes on boot, because it’s using `undefined` as theme object.
This change makes `@sanity/base` export its `theme` object, as well as adding some code style updates to `@sanity/storybook`.

fix(base): export `theme` so Storybook can import it and run

---

packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx
packages/@sanity/types/src/schema/types.ts

This PR adds support `initialValue` to all schema types
```typescript
export interface BooleanSchemaType {
...
initialValue?: ((arg?: any) => Promise<booleean> | boolean) | boolean | undefined
...
}
```

[types] support initial value fields

---

packages/@sanity/base/src/components/DevServerStatus.js
packages/@sanity/base/src/components/ErrorHandler.js
packages/@sanity/base/src/components/SanityRoot.tsx
packages/@sanity/base/src/components/transitional/ImperativeToast.ts
packages/@sanity/base/src/components/transitional/index.ts
packages/@sanity/base/src/components/zOffsets/defaults.ts
packages/@sanity/base/src/components/zOffsets/legacyZIndexes.ts
packages/@sanity/base/src/components/zOffsets/types.ts
packages/@sanity/desk-tool/src/panes/documentPane/documentOperationResults.tsx
packages/@sanity/desk-tool/src/panes/documentPane/statusBar/actionStateDialog.tsx
packages/@sanity/desk-tool/src/panes/documentsListPane/DocumentsListPane.js

Builds on #2345
This PR adds support for Sanity UI based toasts in the studio, and also replaces a few snackbars that relied on them.
Snackbars in the studio.
​
Added support for using [Sanity UI](https://www.sanity.io/ui/) based [Toasts](https://www.sanity.io/ui/docs/component/toast) in the Studio.

Add support for Sanity UI toasts in studio

---

packages/@sanity/webpack-integration/test/fixtures/broken.css

It looks like the postcss parser has become more lenient/accepting of invalid CSS. This caused one of our tests to fail, as it was expecting postcss to throw an error, where it instead gave a warning. This PR makes the test fixture even more broken, making the tests pass again.

test(webpack-integration): make 'broken css' fixture more broken

---

packages/@sanity/base/package.json
packages/@sanity/default-layout/package.json
packages/@sanity/desk-tool/package.json
packages/@sanity/form-builder/package.json

The old version we were depending on did not specify that it allowed react 17 as a peer dependency.
Also added it as a dependency to a few packages that were implicitly depending on it 😬 
Does not seem to have been any meaningful changes to the module apart from that.

chore(deps): upgrade @reach/auto-id

---

cypress/integration/default-layout/navbar.test.js
packages/@sanity/default-layout/src/actionModal/ActionModal.tsx
packages/@sanity/default-layout/src/navbar/Navbar.tsx
packages/@sanity/desk-tool/src/panes/listPane/ListPane.js

This changes the attribute we use to target elements in e2e tests from `data-test` to `data-testid`, which seems like the more widespread convention.

test: use data-testid instead of data-test

---

cypress/support/commands.js
packages/@sanity/form-builder/src/FormBuilderInput.tsx
perf/typingSpeed/typingSpeed.ts

This adds a `data-test-id` attribute around every input component in the sanity studio in order to provide a stable way of selecting inputs in e2e tests.
In addition, this PR also removes the `data-focus-path` attribute that we no longer use after merging #2329.
Based on #2367

test(form-builder): give all inputs a data-testid with their given path

---

.babelrc
gulpfile.js
packages/@sanity/desk-tool/src/panes/documentPane/documentHistory/history/controller.ts

This fixes an issue that would sometimes make the studio crash with an error saying "start required". This would in some rare cases happen when history controller's selectionState was in a loading state. This patch fixes this by instead checking against `selectionState=="range"`, which is the only state where we are guaranteed to have the start document.
- Fixes an issue that could cause an error saying "start required" during review changes

fix(desk-tool): make sure there's a valid selection state before opening the review changes panel

---

packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/constants.ts
packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/documentPanel.css
packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/documentPanel.tsx

- Fixes an issue that made the document pane header not have `position: sticky`. 
- Fixes the positioning of the presence avatars on narrow screens.

fix(desk-tool): fix position of pane header and presence avatars

---

examples/blog-studio/config/@sanity/google-maps-input.json
examples/design-studio/config/@sanity/google-maps-input.json
examples/movies-studio/config/@sanity/google-maps-input.json
examples/test-studio/config/@sanity/google-maps-input.json
packages/@sanity/google-maps-input/src/input/GeopointSelect.css

The search results for the google maps input falls behind the modal because of z-index changes. This PR adds a high number to the z-index in order to fix it - the rationale behind simply increasing the z-index is mentioned in the CSS file.
Also replaces the API key used in examples to allow it to work on `*.sanity.build`

fix(google-maps-input): make search results visible by raising z-index

---

examples/test-studio/schemas/slugs.js
packages/@sanity/form-builder/src/inputs/Slug/SlugInput.tsx

If a slug field has no `source` option, it shouldn't show a "Generate" button. Currently it does, and shows an error.

fix(form-builder): hide slug generate button if field has no source

---

packages/@sanity/form-builder/sanity.json

Related to https://github.com/sanity-io/sanity/issues/2376
Uses approach documented in the [parts docs](https://www.sanity.io/docs/parts#de2ed8f04eba).
> This allows other plugins to compose from the original implementation, extending it as need be.
```tsx
import ArrayInput from 'part:@sanity/form-builder/input/array-default';
```

Add default ArrayInput implementation

---

packages/@sanity/base/src/search/common/tokenize.js
packages/@sanity/base/test/search-tokenize.test.js

Previously we'd only strip whitespace, comma and dash. This PR makes sure we ignore more special characters from the search string when doing a search from the Studio.
*Note for release*
Studio search will now strip special characters from the search string before searching

fix: strip special characters from studio search

---

packages/@sanity/form-builder/src/inputs/DateInputs/CommonDateTimeInput.tsx
packages/@sanity/form-builder/src/inputs/DateInputs/DateInput.tsx
packages/@sanity/form-builder/src/inputs/DateInputs/DateTimeInput.tsx
packages/@sanity/form-builder/src/inputs/DateInputs/types.ts

This fixes an accidental breaking change we shipped with the new date inputs released in [v2.6.3](https://github.com/sanity-io/sanity/releases/tag/v2.6.3) that made the input for `date` fields emit the full ISO string instead of an `YYYY-MM-DD`-formatted string. We should ship this as soon as possible.
Fix a regression introduced in v2.6.3 that caused values coming from `date` inputs to be stored on the same format as `datetime` fields.

fix: date input emit value on right format

---

packages/@sanity/base/src/schema/types/fileAsset.js
packages/@sanity/base/src/schema/types/imageAsset.js

The [media plugin](https://github.com/robinpyon/sanity-plugin-media) defines a new "altText" field on the image and file assets, which we agree should be an option, but wasn't currently included in the schema. With this change, GraphQL schemas and such will have access to the field.

feat(base): add `altText` field to asset types

---

packages/@sanity/base/src/search/index.js

Search doesn't work at all.
This PR fixes a problem in an import path in the `search` module in the `base` package.
Fix incorrect import path to the versionedClient in the `search` module in the `base` package
**Checklist**

[base] fix incorrect import path to the versionedClient

---

packages/@sanity/base/package.json
packages/@sanity/base/src/datastores/document/listenQuery.ts

Currently, if a list fetch takes > 1 second and receive mutation events in the meantime, the request would be cancelled and a new one re-initated. In cases where you'd have many ongoing mutations happening while loading a list this could make the list load forever (or until the mutations stops from arriving).
This patch fixes the issue by instead using an rxjs operator that will ignore received mutation events during ongoing fetces, and issue a new one at the trailing end for any mutation event received during the preceding fetch.
- Fixes an issue that could in some cases cause loading of document lists in the studio to take a long time.

fix(base): prevent cancellation of list fetching while receiving mutation events

---

packages/@sanity/base/src/@types/css.d.ts
packages/@sanity/base/src/components/DevServerStatus.ts
packages/@sanity/base/src/components/ErrorHandler.ts
packages/@sanity/base/src/datastores/history/createHistoryStore.ts
packages/@sanity/base/src/datastores/project/createProjectStore.js
packages/@sanity/base/src/datastores/utils/Location.ts
packages/@sanity/base/src/schema/createSchema.ts
packages/@sanity/base/src/search/weighted/applyWeights.ts
packages/@sanity/base/tsconfig.json
packages/@sanity/types/parts/config:sanity/index.d.ts

Note: this builds on changes in #2405
This enables the `checkJs` TypeScript compiler option in @sanity/base, giving us improved type checking on `.js`-files as well, and ease the migration path towards better ts coverage.
I had to do some minor code changes and cleanup to pass the type checker, but they shouldn't change any actual code behavior.
N/A

chore(base): enable TypeScript's checkJs

---

packages/@sanity/base/src/components/UserAvatar.tsx

When trying to find a user's initials and the name contains symbols (eg `Espen "Hooverdam"`), we can end up with initials like  `E"`. This PR removes symbols from the name before trying to find the first character of the last word, which would change the previous examples initials into `EH`. 
Couldn't find any regex class or similar that would catch _all_ cases, for instance we can't use `\w` as we want to Make `Albert Åberg` into `AÅ`, not `AB`. Better than nothing?

fix(base): strip symbols from user initials

---

packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/header/validationMenu.tsx

This PR makes the validation menu open in a portal, fixes an issue where it got hidden behind the fullscreen Portable Text Editor.
​
​Open or create a document that has a portable text editor and also validation errors. Open portable text editor in fullscreen. See that the validation menu is displayed on top and doesn't get layered behind the portable text editor.
- ​Fixes issue where the validation menu got hidden behind the fullscreen Portable Text Editor​

fix: use portal for validation menu

---

packages/@sanity/form-builder/src/inputs/files/common/FileInputButton/FileInputButton.tsx
packages/@sanity/server/package.json
packages/@sanity/server/src/configs/webpack.config.js
packages/@sanity/storybook/package.json
packages/@sanity/storybook/src/config/config.js

Our inclusion of normalize.css in the studio css bundle is occasionally causing hard-to-debug issues with rendering (see 5eb2905 for an example). I think removing it is a good idea, and also something that is in more in line with the direction we're currently going in (less assumptions about the global environment, etc.).
If we absolutely need to normalize browser styles, we should probably consider something more up-to-date like [sindresorhus/modern-normalize](https://github.com/sindresorhus/modern-normalize) instead.
Thoughts?

Remove normalize css from Studio CSS bundle

---

packages/@sanity/base/src/search/index.ts
packages/@sanity/base/src/search/weighted/createWeightedSearch.ts
packages/@sanity/base/src/search/weighted/types.ts
packages/@sanity/schema/src/legacy/resolveSearchConfig.ts
packages/@sanity/schema/src/legacy/types/object.ts
packages/@sanity/types/src/schema/types.ts

This PR allows users to search for a term mentioned in portable documents portable text field in the global search. 
- Use the `v2021-03-25` API version for the studio search
- Allow a `mapWith` property on the experimental search (primarily for internal use) - wraps the field in the GROQ-function given. Not sure about the naming on this.
- Detect portable text fields and include them in the automatically resolved search configuration
- Try searching the [test studio](https://test-studio-git-feat-pt-text-search.sanity.build/test/desk) for strings that appear in portable text fields
- Technical implementation (and naming)
- Add support for searching portable text fields

feat(search): apply pt::text() when searching portable text fields

---

packages/@sanity/base/src/search/weighted/createWeightedSearch.ts
packages/@sanity/base/src/search/weighted/types.ts

Fixes #2440
Check that drafts no longer appears when searching for references.
- Fixes a bug that accidentally permitted referencing drafts

fix(base): fix regression causing drafts to be included as results in reference search

---

packages/@sanity/base/package.json
packages/@sanity/default-layout/package.json
packages/@sanity/desk-tool/package.json
packages/@sanity/field/package.json
packages/@sanity/field/src/diff/components/ChangeList.tsx
packages/@sanity/field/src/diff/components/DiffTooltip.tsx
packages/@sanity/field/src/diff/components/FieldChange.tsx
packages/@sanity/field/src/diff/components/GroupChange.tsx
packages/@sanity/form-builder/package.json
packages/@sanity/storybook/package.json
packages/@sanity/vision/package.json

- The poppers (dialog and tooltip) in `@sanity/field` now use the `LegacyLayerProvider` to set the z-offset to a higher number than the poppers in the `@sanity/form-builder`.
- This fixes the issues by making sure that the revert changes dialog is always on top of the form builder, even when viewing a deeply nested array item.
- Open a document with deeply nested array items (2 level or deeper).
- Edit a field in a deeply nested array item.
- Click the `Revert changes` button below the changed field, and make sure the dialog is available (on both wide and narrow screens).
- Fixes a z-index issue with revert changes dialogs.

fix(field): fix z-index issues of tooltip and revert dialog

---

packages/@sanity/base/src/change-indicators/ChangeIndicator.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/ArrayItem.tsx
packages/@sanity/form-builder/src/inputs/common/fileTarget/fileTarget.tsx

Some low hanging performance optimizations after seeing regressions from #2350.
Comparison of typing A-Z in a text field inside an object in an array of 100 items:
*base branch*: Average of 4 samples: **5799ms**
*this branch*: Average of 4 samples: **1588ms**
Edit an array of objects and verify that presence/markers works as before, but faster.
- Improved performance of editing array items

perf(form-builder): improve array input performance

---

examples/design-studio/package.json
packages/@sanity/base/package.json
packages/@sanity/base/src/__legacy/@sanity/components/avatar/stories/stack.tsx
packages/@sanity/base/src/components/formField/FormFieldValidationStatus.tsx
packages/@sanity/base/src/theme/color.ts
packages/@sanity/base/src/user-color/manager.ts
packages/@sanity/form-builder/package.json
packages/@sanity/types/package.json

- This change updates `@sanity/color` from 1.0.0 to 2.0.15 in `@sanity/base` (required updating code in the user color manager + form validation component).
- This change adds `@sanity/color` as dependency where it was missing.
- The studio builds and runs using the new version of `@sanity/color`.
- Look especially at presence avatars (if the studio doesn’t crash when rendering user avatars, it works)

build: update `@sanity/color` dependency

---

packages/@sanity/form-builder/src/inputs/files/ImageToolInput/ImageToolInput.tsx
packages/@sanity/imagetool/src/ImageTool.js

This fixes an issue introduced in 38644082ff7053449b849ea533f43b9d13449826 that caused image fields to emit out of bounds values for hotspot/crop fields.
- Open an image with hotspot tool enabled
- Drag the hotspot ellipse or crop rect out of bounds
- Verify that it get's "corrected" and doesn't stay out of bounds after drag ends
- Fixes bug that caused out of bounds values for hotspot/crop to be saved to the data store

fix issue causing image input to emit hotspot/crop out of bounds values for hotspot/crop

---

packages/@sanity/form-builder/src/inputs/PortableText/Toolbar/OverflowMenu.css

Using the deprecated -webkit-box on display causes a different behaviour
in the blink-engine ([1], [2]). With a less strict Browserslist configuration the
-webkit vendor-prefixes are removed, but not the display: -webkit-box
then again causing unexpected behaviour where the Actionmenu gets
completely hidden
The changes was introduced here, https://github.com/sanity-io/sanity/commit/f8fb3ef54ac61ffa2d57b2865c7b77a628c36218, to facilitate support on linux, but should no longer be needed
Fixes issue where the editor ActionMenu gets hidden when the Studio is built with a custom Browserslist configuration
[1]: https://chromium.googlesource.com/chromium/src/third_party/+/main/blink/renderer/core/style/computed_style.h#1149
[2]: https://chromium.googlesource.com/chromium/src/third_party/+/main/bl …

fix(form-builder): Removes display: -webkit-box;

---

packages/@sanity/desk-tool/src/panes/documentPane/timeline/timeline.tsx

Show a message when there's no history available for a document
* Is the use of the `timeline.chunkCount` correct? 🤔

feature(desk-tool): No history message

---

packages/@sanity/cli/scripts/pack.js

When building the Sanity CLI to a single file using webpack, we were using `mode: 'production'`, which by default defines `process.env.NODE_ENV` as `production`. This created some interesting issues - several CLI commands that use environment variables from `.env` files might resolve to the wrong environment because they used `process.env.SANITY_ACTIVE_ENV || process.env.NODE_ENV || 'development'` or similar.
This PR unsets the `NODE_ENV` environment variable from the webpack bundle, which should respect the `NODE_ENV` set by the system host.
It's tempting to remove the fallback to `NODE_ENV`, but that would be a breaking change.
To review, build the Sanity CLI using `npm run package-cli` from the monorepo root, and use it when running commands, eg: `node …

fix(cli): unset NODE_ENV for built CLI bundle (don't assume production)

---

packages/@sanity/cli/src/scripts/package-yarn.js

Upgrades the bundled version of yarn from `1.6.0` to `1.22.10`. This fixes some of the weird errors users see where running `sanity install <plugin>` sometimes mangles `node_modules` in weird ways.
This is a stopgap measure, until we fork out to yarn/npm instead, obviously.
Run `npm run package-yarn` in the monorepo, then run `node /path/to/monorepo/packages/@sanity/cli/bin/sanity-cli.js install` and `node /path/to/monorepo/packages/@sanity/cli/bin/sanity-cli.js install media` or similar.
- Upgraded bundled version of yarn

feat(cli): upgrade to yarn v1.22.10

---

packages/@sanity/client/sanityClient.d.ts

Updates the types for the config object in the client to work with environment vars (e.g. `process.env.EXAMPLE_SANITY_PROJECT_ID`). This is common in tools like next.js.
See here: https://github.com/sanity-io/sanity/issues/2508#issuecomment-848283281
Closes #2508
Take a look at the types and check to see if there are any breaking changes.
Allow `projectId` to be optional in all cases to prevent typescript DX issues. See #2508.

fix(client): make projectId optional; combine config types

---

examples/test-studio/schemas/poppers.js
packages/@sanity/form-builder/src/inputs/arrays/common/ArrayFunctions.tsx

- Added test cases in Test Studio for showing an array menu with more than 1 object type
- Use the `constrainSize` and `portal` properties on Sanity UI’s `Popover` to make sure the popover renders in a portal element, and that the popover has a `maxHeight`.
- Open https://test-studio-8pv11zpc4.sanity.build/test/desk/poppers;7ab62dbe-d336-4b05-9245-b61c608449f9
- Add an item under "Arrays in arrays"
- Click the "Add item…" in the nested "Arrays in arrays"
- Make sure the popover menu works as expected – even on small screens.
- Fixes overflow issues with the array item menu.

fix(form-builder): render array item menu in a portal

---

packages/@sanity/default-layout/src/DefaultLayout.tsx
packages/@sanity/default-layout/src/navbar/Navbar.tsx

Fix a bug where the desk tool crashes when opened from a link in the studio.
This was difficult to reproduce on dev versions of the studio. A production build is required.
Fixed issue where opening internal links in a new tab causes the studio to crash

fix(default-layout): protect against undefined state tool

---

packages/@sanity/code-input/src/CodeInput.tsx

This passes on the `focusPath` to the ChangeIndicatorProvider (which provides data needed by the FormField/Fieldset components to properly render change indicators). Also wraps the "field-less" render mode with a `ChangeIndicatorProvider`.

fix(code-input): ensure change indicators get correct focus path

---

packages/@sanity/block-tools/package.json
packages/@sanity/block-tools/src/HtmlDeserializer/index.ts
packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild5/index.ts
packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild5/input.html
packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild5/output.json
packages/@sanity/block-tools/test/tests/HtmlDeserializer/index.test.ts

This will fix an issue when combining several HTML serializers on the same time.
Using this global temp var here to store the serialized markDefs while we deserialize, will not support running multiple HTML-deserializers at the same time, which the test will show (fails before the fix commit).
I have a vague memory that it was a reason I used this a var like that and not put it on the class itself, but I can't seem to remember it now. :facepalm: 
However all the tests pass. And I can't really see why it needs to be a global var. There are no other matches on that used by other files.
Fix issue with combining multiple block-tools HTML deserializers.

fix(block-tools) global/class var issue

---

packages/@sanity/form-builder/src/FormBuilderInput.tsx

If you have a rich text editor inside of an object alongside an image, and the editor has a ton of items in the toolbar, this causes an overflow issue where the modal content is clipped.
We have a smart `OverflowMenu` component that normally is supposed to prevent overflows in the toolbar.
The overflow in this case happens because of the content, in this case the toolbar, defines the width of the parent wrapper.
Each column inside the CSS grid wrapper by default has a width of `auto` instead of `0`.
More details here: https://css-tricks.com/preventing-a-grid-blowout/
Screenshot of the problem:
- Fixed a problem where a rich text editor with too many toolbar items inside of a object inside of a modal caused the content to overflow and be clipped

fix(form-builder): Fix overflowing PT toolbar menu inside of dialog

---

packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/permissionCheckBanner.tsx

This can happen in the case of third-party login (eg SSO). Working on addressing it at a deeper level, but this should at least prevent it from crashing.

fix(desk-tool): prevent crash if roles property does not exist on current user

---

packages/@sanity/cli/src/util/noSuchCommandText.js
packages/@sanity/core/src/commands/users/inviteUserCommand.js

Updates the `sanity users invite` command to use the new roles and invitations API in order to support new and custom roles.
Also found a few commands/command groups that weren't picked up when running `sanity <command>` outside of a sanity studio directory, so they gave a more generic error message than they should have.

feat(core): support new roles api in user invite command

---

packages/@sanity/form-builder/src/inputs/ObjectInput/Field.ts

v2.12.0 released a refactored default object input, where some of the internals were rewritten. This caused unintended breakage in one of our plugins that relied on this internal code path (https://github.com/LiamMartens/sanity-plugin-intl-input/issues/56). This PR adds back a file with the old name, which should have the same API as before.
- Added back an internal API that accidentally broke the sanity-plugin-intl-input

fix(form-builder): bring back old internal Field API

---

packages/@sanity/form-builder/src/sanity/legacyPartImplementations/patch-event.ts

So apparently `export * from …` does not reexport the `default` export (TIL), which is likely to cause the issue described in #2576.
- Fixes an issue that caused some plugins to error with the message "Cannot read property 'from' of undefined".

fix(form-builder): reexport PatchEvent default export

---

packages/@sanity/cli/package.json

`@sanity/cli` was implicitly depending on `@sanity/generate-help-url` in `clientWrapper`, but did not declare it as a dependency. This only works because other modules depend on it and the CLI bundles dependencies to a single file on publish. This PR adds the missing dependency.

fix(cli): add missing undeclared dependency

---

packages/@sanity/field/src/schema/helpers.ts
packages/@sanity/field/src/types/reference/preview/ReferencePreview.tsx

The preview component seems to handle reference types just fine without us having to look up the individual type ahead of time. In fact, it might technically be incorrect to pass the target schema type along with a reference value. I'm not sure why I implemented it this way in the first place, but it seems to have started crashing when showing a diff of a schema type that can be of multiple different types.
Diffs for references - both those of a single type and of those targeting multiple types.
- Fixed bug where review changes might crash when showing change in a reference that could target more than one schema type

fix(field): prevent crash when unable to resolve reference type

---

packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx
packages/@sanity/form-builder/src/inputs/ObjectInput/__tests__/ObjectInput.test.tsx
packages/@sanity/types/src/schema/types.ts

The refactor of Object Input in v2.12.0 accidentally removed support for hidden object fields/field filtering. This adds it back, along with a unit test to catch future regressions.
Verify that it looks ok implementation wise, and that hidden fields actually gets hidden
- Fixes a bug introduced in v2.12.0 that made hidden fields appear visible

fix(form-builder): make sure hidden/filtered fields are actually hidden

---

examples/test-studio/schemas/fieldValidationInferRepro.js
examples/test-studio/schemas/schema.js
packages/@sanity/validation/src/inferFromSchemaType.js
packages/@sanity/validation/src/validateDocument.js
packages/@sanity/validation/test/infer.test.js

This fixes the issue documented in https://github.com/sanity-io/sanity/issues/2257 by not assigning field rules to the individual fields. Instead of constructing the field validation at the time it gets inferred from the schema, this PR will call the rule creator at _validation_ time, which may be suboptimal in some cases. I don't know this code well enough to find a better way, but this solution may be good enough for now. Thoughts?
- All things related to validation, especially field validations on object types.
- Fixes an issue that caused field validations on object types to be written on individual field types, causing unintentional re-use of validation rules.

fix(validation): fix issue causing field validations on object types to be unintentionally re-used across contexts

---

.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/verify_format.yml

Like with puppeteer, let's skip downloading the cypress binary on non-e2e github workflows

build(ci): skip cypress binary install on non-cypress workflows

---

packages/@sanity/client/README.md

Fixed typo on `client.asset`
Examples below this line contain the correct method name
Corrected assets method name in `@sanity/client` readme.

fix typo on method

---

packages/@sanity/validation/src/Rule.js
packages/@sanity/validation/src/ValidationError.js
packages/@sanity/validation/src/getClient.js
packages/@sanity/validation/src/index.js
packages/@sanity/validation/src/inferFromSchema.js
packages/@sanity/validation/src/inferFromSchemaType.js
packages/@sanity/validation/src/util/deepEquals.js
packages/@sanity/validation/src/util/escapeRegex.js
packages/@sanity/validation/src/util/handleValidationResult.js
packages/@sanity/validation/src/util/pathToString.js
packages/@sanity/validation/src/util/prefixPaths.js
packages/@sanity/validation/src/validate.js
packages/@sanity/validation/src/validateDocument.js
packages/@sanity/validation/src/validators/arrayValidator.js
packages/@sanity/validation/src/validators/blockValidator.js
packages/@sanity/validation/src/validators/booleanValidator.js
packages/@sanity/validation/src/validators/dateValidator.js
packages/@sanity/validation/src/validators/genericValidator.js
packages/@sanity/validation/src/validators/numberValidator.js
packages/@sanity/validation/src/validators/objectValidator.js
packages/@sanity/validation/src/validators/slugValidator.js
packages/@sanity/validation/src/validators/stringValidator.js
packages/@sanity/validation/test/array.test.js
packages/@sanity/validation/test/children.test.js
packages/@sanity/validation/test/generics.test.js
packages/@sanity/validation/test/infer.test.js
packages/@sanity/validation/test/numbers.test.js
packages/@sanity/validation/test/strings.test.js

- Replaced `const ... = require(...)` with from `import ... from ...` throughout `@sanity/validation`. This change will make it possible to tree-shake `@sanity/validation`, and makes it easier to migrate to TypeScript later on.
- That nothing breaks as a consequence of this refactor.

refactor(validation): convert to ES modules

---

packages/@sanity/desk-tool/src/panes/documentPane/documentPane.tsx

If you change the document to another revision, the "Inspect document" dialog would still be displaying the latest version. This is very confusing.
This is fixed by using the `displayed` value from the history provider as prop for `InspectDialog` and not the `value` which will always be the latest (current version).
Is there is anything we didn't think of doing this change? We do have support to fallback to `initialValue` if there currently isn't anything in the`displayed` value. For instance if you select the "create" (first) revision. 
Fix issue where the inspected document version is always the latest version and not the current selected version.

fix(desk-tool): use the selected document revision as value for inspect document

---

packages/@sanity/schema/src/legacy/types/object.ts

Currently, given the `marks` configuration below, Sanity Studio won't apply the custom icons to the `color` annotation. It'll display the Sanity Logo:
<details>
<summary>Click to see the configuration</summary>
```
marks: {
annotations: [
{
title: 'URL',
name: 'link',
fields: [
{
title: 'URL',
name: 'href',
type: 'url',
},
],
blockEditor: {
icon: () => '🔗',
},
},
{
title: 'Color',
name: 'color',
type: 'color',
blockEditor: {
icon: () => '🎨',
},
},
],
},
```
</details>
With the changes in this PR, the annotation will have the provided icon:
This PR closes #1917.
**Checklist**

[schema] Add blockEditor to list of overridable fields

---

packages/@sanity/form-builder/src/inputs/PortableText/Toolbar/helpers.tsx

Currently, given the `marks` configuration below, Sanity Studio won't apply the custom icons to the `code` decorator. It'll display its default icon:
<details>
<summary>Click to see the configuration</summary>
```
marks: {
decorators: [
{
title: 'Code',
value: 'code',
blockEditor: {
icon: () => '💻',
},
},
{
title: 'Highlight',
value: 'highlight',
blockEditor: {
icon: () => '✨',
},
},
],
},
```
</details>
With the changes in this PR, the decoration will have the provided icon:
This PR closes #1536.
**Checklist**

[form-builder] Always use custom icon for decorators if provided

---

packages/@sanity/base/src/datastores/grants/createGrantsStore.ts
packages/@sanity/base/src/datastores/grants/highlevel.ts
packages/@sanity/base/src/datastores/grants/hooks.ts
packages/@sanity/base/src/datastores/grants/types.ts

To support more advanced ACL where users have access to edit their own
documents we need to inject the user id when evaluating the grant
filters
* Is this the idiomatic way of getting the current user?
add support for validating built-in $identity param

feature(grants): add support for validating built-in $identity param

---

examples/test-studio/schemas/objects.js
packages/@sanity/field/src/diff/changes/buildChangeList.ts
packages/@sanity/field/src/diff/components/ChangeList.tsx
packages/@sanity/field/src/diff/components/ChangeResolver.tsx
packages/@sanity/field/src/diff/components/FieldChange.tsx
packages/@sanity/field/src/diff/components/GroupChange.tsx
packages/@sanity/field/src/types.ts
packages/@sanity/types/src/schema/types.ts

Currently, if a field or document is read-only, the review changes panel still lets you revert their changes (and thus editing them), and the same goes for whole documents that are read-only. Also, if a field is hidden in the document, it still shows up in the review changes panel. 
This PR will disable the revert changes buttons based on the `readOnly` value in the schema for fields and parents of fields. It will also hide fields if the schema has `hidden: true`.
Make sure that the review changes panel still work as expected, and that adding `readOnly: true` and `hidden: true` to fields disables the correct buttons and hides the correct fields.
- Fixed an issue where readOnly fields and documents would still be editable in the review changes panel
- Fixed an issue where hidden fields …

fix(field): disable revert changes on read-only fields and documents and hide fields from review changes if `hidden: true`

---

examples/test-studio/schemas/arrays.js
packages/@sanity/base/src/preview/prepareForPreview.ts

When a string field with predefined options is the first field in an object in an array, the preview renders using the value of the field, instead of the title defined in the list option (fixes #769).
I've added some logic to make sure the `title` and not the `value` is used when preparing the preview in these special cases, however I'm not sure if this is done in the right place and that it's too far up and should be done someplace else. However, with this approach the previews in document lists also use the `title` instead of the `value` if the first field in the document is a string field with predefined list options, which is nicer.
I've added some test cases in the `arrays.js` schema in the test studio, please test it there and if possible with other combinations you can think of. …

fix(base): use title, not value in prepare preview when field has predefined string options

---

packages/@sanity/base/src/datastores/grants/highlevel.ts

Currently we check for update permission by stubbing the drafts document (a stub only includes _id and _type). In cases where a document is published and you have a grants check that requires certain conditions to be met on the document itself, we then end up running the grants check on the stubbed version, which may miss the fact that the published version meet the conditions specified in the grants rule. This PR changes it so we run the check against the published version (if exists) instead of the stub.
- Fixes an issue that could prevent drafts from being edited even in cases where a grant rule would permit it

fix(base): fallback to published version if no draft exists

---

packages/sanity/README.md

Small change that makes the `sanity` package README sound less scary.

docs(sanity): improve placeholder package readme text

---

packages/@sanity/form-builder/src/inputs/PortableText/PortableTextInput.css

Thin 1px gap above fullscreen PTE shows the form underneath.
Go to a blocks test document and open a pt editor in fullscreen mode, and make sure the form below isn't visible.
Not sure why it had `top: 1px;`, maybe for a specific reason.
- Fixed the form being visible above the PTE toolbar in fullscreen mode

fix(form-builder): remove 1px gap above pte in fullscreen mode

---

packages/@sanity/base/src/preview/components/ObserveForPreview.tsx
packages/@sanity/base/src/preview/constants.ts
packages/@sanity/base/src/preview/constants.tsx
packages/@sanity/base/src/preview/createPreviewObserver.ts
packages/@sanity/base/src/preview/prepareForPreview.ts
packages/@sanity/base/src/preview/utils/resolveRefType.ts
packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx
packages/@sanity/form-builder/src/inputs/ReferenceInput/usePreviewSnapshot.ts

This implements a notice for insufficient permissions for references. This approach augments the `resolveRefType` implementation that goes downstream to the `ObserveForPreview` component. This is a particularly nice spot since it's already attempting to query the ref and it has access to the type resolving the ref. If a ref could not be resolved while the related type says the reference is not `weak` then we can assume the user has insufficient permissions and return a Symbol.
Similar to the `INVALID_PREVIEW_FALLBACK`, we can catch this symbol in `ObserveForPreview` and return a similar fallback for insufficient permissions.
Questions/Notes on the approach:
~1. As a result of handling this at such a low level, the snapshot value can sometimes be a Symbol. I'm not sure if this will affect …

feat(base): add preview override for references permissions

---

packages/@sanity/server/src/configs/webpack.config.js

An unconstrained regex in our webpack config is leading to any files containing `.js`, `.jsx`, `.ts` and `.tsx` to be passed through the babel loader. This is a problem when loading `.json` files, as they match the regex.
This PR makes sure we only run files _ending_ with these extensions through babel.
Fixes #2494
- `import data from './data.json'` will fail currently but will work with this fix.
- Check that the regex makes sense (the `?` matcher is because of module loaders having the ability to append query string options)
- Fixes issue where importing JSON files would crash the studio build process

fix(server): prevent json imports from passing through babel

---

examples/example-studio/schemas/blogpost.js
packages/@sanity/form-builder/src/inputs/DateInputs/DateTimeInput.tsx

If a datetime is configured with `timeStep=60` the user is not able to select minutes because there's only one option `00` and onSelect doesn't trigger on a "non-change". This PR adds an effect that ensures that the value for date time minutes are compatible with the configured `timeStep`-value
Enforce that DateInput value is constrained to timeStep

fix(form-builder): enforce that DateInput value is constrained to timeStep

---

packages/@sanity/base/src/__legacy/@sanity/components/previews/MediaPreview.tsx

I noticed that sending a `title` node that's a react node (vs a string)` will make the browser tooltip say `[object object]` instead of the correct title.
This PR fixes that by adding a ref callback + `el.innerText`
Ensure I didn't change the API of one and it works as intended. If the one looks good to you, feel free to merge it. 😄

fix(base): fix [object Object] for title value

---

packages/@sanity/desk-tool/src/panes/documentPane/documentHistory/history/chunker.ts
packages/@sanity/desk-tool/src/panes/documentPane/timeline/helpers.ts
packages/@sanity/desk-tool/src/panes/documentPane/timeline/timelineItem.css
packages/@sanity/field/src/types.ts

This will differentiate between when when a document is edited through
the api and edited as a draft. Fixes a bug where the studio shows that
there are changes when there are none
Are we comparing chunk types anywhere else in the codebase that I have missed?
fixes #2599

feat(desk-tool): add timeline event for live edits

---

packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx

The reference was marked as missing when the document existed because of a missing conditional clause.
For cross reference: https://github.com/sanity-io/sanity/pull/2585/files#diff-0419dde3aa4b7ffa09d19c960d248addc8fe46dd8955042a28018f8df203d444L114

fix(base): fixes a bug where isMissing was triggered when the reference exists

---

examples/test-studio/schemas/author.js
packages/@sanity/base/src/preview/prepareForPreview.ts

Resolves issue #2631.
Modifies the return from `targetKeys.reduce()` in base/src/preview/prepareForPreview.ts. This solves the empty return encountered when using options.list and a prepare function (issue #2631 and https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1626976557089000).
This code was compiled and tested against the [test studio](https://github.com/sanity-io/sanity/commit/d23ec5d0b3bb311b4b92653e206f15e3097ee3c1).
Resolves issue #2631.

fix(base): render list items in object previews (#2631)

---

packages/@sanity/form-builder/src/utils/withDocument.tsx

If the component passed to `withDocument()` doesn't expose a `.focus()` instance method or forwards it's ref to a component that implements a .focus() method, the studio will crash with an error saying "Cannot read property 'focus' of undefined". This PR adds a safeguard against it and also issues a console warning that should make it easier to pinpoint the issue.
Review and see if the code/message makes sense
- Adds safeguard against missing `.focus()` method on components used with the `withDocument()` higher order component.

fix(form-builder): prevent studio crash when component passed to `withDocument()` is missing a focus() method

---

packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/uploadTarget/styles.ts
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/uploadTarget/uploadTarget.tsx
packages/@sanity/form-builder/src/inputs/files/FileInput/FileInput.tsx
packages/@sanity/form-builder/src/inputs/files/ImageInput/ImageInput.tsx
packages/@sanity/form-builder/src/inputs/files/common/DropMessage.tsx
packages/@sanity/form-builder/src/inputs/files/common/styles.ts
packages/@sanity/form-builder/src/sanity/inputs/SanityArrayInput.tsx
packages/@sanity/form-builder/src/sanity/uploads/resolveUploader.ts
packages/@sanity/form-builder/src/sanity/uploads/types.ts

This refactors the resolveUploader interface so it takes a "file-like" argument (an object that has a mime type and a  name) instead of an actual `File` instance. This allows us to check the data transfer items we get from the drag event when files are dragged over the drop target, and allows us to show instant feedback about what files (if any) will be uploaded when dropped. See screenshots below.
This PR also includes a commit that factors in the `directUploads` studio configuration into the `resolveUploader` function instead of having a separate code path to handle this.
(note: the wrong pluralization in the above screenshot has been fixed)
- Drag some files of various types from disk over to the drop area in a file/image input and see that it works as expected
- Give better feedback …

Use check for direct uploads support in resolveUploader + improve feedback on dragging over drop targets

---

packages/@sanity/form-builder/src/inputs/DateInputs/base/calendar/CalendarDay.tsx

This adds a visible indicator on the focused day when using arrow keys to navigate through the calendar days in the date picker
Open the date picker in a datetime/date input field, change date by using the arrow keys and verify that there's a focus ring around the focused date.
- Adds a visible indicator on the focused day when using arrow keys to navigate through the calendar days in the date input

fix(form-builder): fix missing focus ring on focused day

---

examples/test-studio/schemas/previewSelectBugRepro.js
examples/test-studio/schemas/schema.js
packages/@sanity/base/src/preview/createPathObserver.ts

This PR fixes an issue that makes the following preview selection result in an invalid groq query, which again will make the studio error with a 400.
https://github.com/sanity-io/sanity/blob/a02a45cbca906d422ffa805cd3330c923a3274ce/examples/test-studio/schemas/previewSelectBugRepro.js#L16-L22
Open the studio at https://test-studio-git-fix-preview-select-causing-400.sanity.build/test/desk/previewSelectBugRepro;9fe0d4ac-58aa-4dd7-b181-85ade1b7b34f and verify that there's no errors and that previews works as expected.
- Fixes an issue that in some rare cases could make the preview selection result in an invalid query

fix(base): fix invalid query when preview selection targets both a reference field and a field on the referenced document

---

packages/@sanity/client/sanityClient.d.ts
packages/@sanity/client/src/http/requestOptions.js

This adds support for configuring a single client and/or request to use a proxy.
Fixes #2652.
I was not able to write a test for this since it doesn't seem like Nock supports retrieving the proxy of a request:
```js
test('can be configured with proxy', (t) => {
// TODO: How to check that example.com is being used?
nock(projectHost()).get('/v1/ping').reply(200, {pong: true})
getClient({proxy: 'http://example.com'})
.request({uri: '/ping'})
.then((res) => t.equal(res.pong, true))
.catch(t.ifError)
.then(t.end)
})
```
Would like feedback on suggestions to verify that this works as expected.
* Support `proxy`-option in `@sanity/client`.

feat(client): support `proxy` in config + options

---

packages/@sanity/base/sanity.json

Fixes #2558
I identified the duplicate definitions with the following command:
cat packages/@sanity/base/sanity.json | groq '(parts[].implements)[defined(@)]' -o ndjson | sort | uniq -c | sort -n
* Double check that the removed lines actually are present another place in the file.

Remove duplicate parts definition

---

packages/@sanity/core/src/actions/exec/pluginLoader.js

`sanity exec` assumed that it would be executed in the project directory, but it is possible run it in a subdirectory. This changes the pluginLoader to use the determined Sanity base path instead.
Fixes #2525
I haven't been able to actually test it since I'm not quite sure how to do it…
* Make it possible to run `sanity exec` inside sub-directories.

Determine correct base path for `sanity exec`

---

packages/@sanity/base/_internal.js
packages/@sanity/base/_interopReexport.js
packages/@sanity/base/change-indicators.js
packages/@sanity/base/components.js
packages/@sanity/base/hooks.js
packages/@sanity/base/initial-value-template-builder.js
packages/@sanity/base/initial-value-templates.js
packages/@sanity/base/presence.js
packages/@sanity/base/preview.js
packages/@sanity/base/structure-builder.js
packages/@sanity/base/user-color.js

Fixes #2680
The (legacy) package export entries in `@sanity/base` have up until now been doing:
```js
module.exports = require('./<path-to-module>')
```
... this caused an issue with an internal _default_ import that got reexported this way (#2680).  For better interoperability with ESM consumers, this PR makes sure the package export entries now writes the exports to `module.exports` the same way as babel are doing when transpiling ESM => CommonJS:
```js
export * from './<path-to-module>'
export {default} from './<path-to-module>'
```
Note: I'm not exactly sure _why_ this change fixes the linked issue, but suspect is has something to do with circular imports, and that the getter approach solves it.
Fixes a regression in 2.15.0 causing an error with boolean fields

fix(base): ensure esm interoperability in root package reexports

---

packages/@sanity/google-maps-input/config.dist.json
packages/@sanity/google-maps-input/src/loader/loadGoogleMapsApi.ts

What changes are introduced?
ADD new config variable than can be used to set locale
Why are these changes introduced?
ADD possibilty to set your own locale in the Google Maps input plugin
What issue(s) does this solve? (with link, if possible)
None that i found.
What steps should the reviewer take in order to review?
Just see if the variable names are ok
What parts/flows of the application/packages/tooling is affected?
@sanity/google-maps-input
You can now add a default locale for Google Maps, it will make the search prioritize places/addresses in that locale.

Add defaultLocale to @sanity/google-maps-input config

---

.webpack-aliases.json5
packages/@sanity/desk-tool/_interopReexport.js
packages/@sanity/desk-tool/package.json
packages/@sanity/desk-tool/src/_exports/index.ts
packages/@sanity/desk-tool/src/_exports/structure-builder.ts
packages/@sanity/desk-tool/src/defaultStructure.js
packages/@sanity/desk-tool/src/index.js
packages/@sanity/desk-tool/src/structure-builder.ts
packages/@sanity/desk-tool/structure-builder.js
packages/@sanity/desk-tool/test/resolvePanes.test.js

This exports proper TS types from both `@sanity/desk-tool` and `@sanity/desk-tool/structure-builder`
n/a

Add proper type exports to desk-tool

---

packages/@sanity/desk-tool/src/panes/documentPane/statusBar/sparkline/documentSparkline.styled.tsx
packages/@sanity/desk-tool/src/panes/documentPane/statusBar/sparkline/documentSparkline.tsx

- With this change, the document sparkline uses the `editState` to find out if a document is published or not (instead of looking at the history events and finding the last `publish` or `unpublish` event).
- Test both live document and regular published/draft documents, and make sure the publish state is accurate in the document status bar.
n/a

fix(desk-tool): use `editState` as source for publish status

---

packages/@sanity/portable-text-editor/package.json

Fixes focus bugs in upstream dependency when you have multiple portable text editors in the same DOM with the same value.

chore(portable-text-editor): upgrade @sanity/slate-react

---

packages/@sanity/portable-text-editor/src/utils/values.ts

This bug was introduced when the editor was moved into the monorepo in order to fix TS warnings/errors with the monorepo setup. It went a little wrong.
Fix bug introduced in v2.16.0 where inline Sanity references in Portable Text would not be saved properly.

fix(portable-text-editor): fix bug in value conversion

---

packages/@sanity/form-builder/src/components/ActivateOnFocus/ActivateOnFocus.styles.tsx

Increased the `z-index` for the contents within the `ActivateOnFocus` overlay to appear above the change indicator and so show the content regardless of which direction the content is hovered.
1. Go to the blocks tests
2. Find one with the change indicator active (the first one should do it)

Fix activate on focus when used in combination with change indicator

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/utils/weakMaps.ts

When moving the PTE into the monorepo some refactoring was done to please typescript. It went wrong here obviously making block re-render themselves even though they weren't changed. This is a regression since v2.16.0.
I have fixed the regression.
It should also be added a test for this in the test branch we are working on.
Fix regression in portable text editor since 2.16.0 where blocks are re-rendered when they should not be.

fix(portable-text-editor): fix re-render regression from v2.16.0

---

examples/test-studio/package.json
packages/@sanity/base/package.json
packages/@sanity/dashboard/package.json
packages/@sanity/field/package.json

Upgrades the image library to the latest version, which solves a (small) annoyance where passing a dpr property of `1` would result in `dpr=1` to be added to the URL (which is unnecessary, given that is the default). Also - a more logical semver range - yay!
That things still work

chore: upgrade image-url library

---

packages/@sanity/client/package.json
packages/@sanity/core/.depcheckignore.json
packages/@sanity/core/package.json
packages/@sanity/core/src/actions/build/compressJavascript.js

There were some issue around the minification step in `sanity build` around `resolve-bin` so I removed it and opted for the Terser JS API.
See if `sanity build` still works with no regression. Also affects the `@sanity/client` build since that was also using an older version of terser.
N/A

chore: upgrade terser

---

packages/@sanity/base/src/__legacy/@sanity/components/validation/ValidationList.tsx
packages/@sanity/base/src/__legacy/@sanity/components/validation/ValidationListItem.css
packages/@sanity/base/src/__legacy/@sanity/components/validation/ValidationListItem.tsx

This add breadcrumbs to the validation list.
Updated CSS to match the review changes breadcrumbs
I would just review the idea and see if you like it. I fully expect this PR to be superseded by #2610
This is related to #2718. I thought it would be a good idea to include breadcrumbs if we start showing validation errors for nested items more often.
Edit: I'm not sure where #2718 stands. Should this wait for that? @mariuslundgard 
Validation markers now show breadcrumbs

feat(base): add breadcrumbs to validation markers

---

package.json

I had to run the build prior to running publish tag and that might be a missed step in the future so this may help.
notice that `npm run publish` runs the build prior too
Check the logic; try the command

build: run build before publish-tag

---

examples/test-studio/schemas/validation.js
gulpfile.js
packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx
packages/@sanity/form-builder/src/utils/getValidationRule.ts
packages/@sanity/types/src/schema/types.ts
packages/@sanity/types/src/validation/types.ts
packages/@sanity/validation/src/Rule.ts
packages/@sanity/validation/src/validateDocument.test.ts
packages/@sanity/validation/src/validateDocument.ts
packages/@sanity/validation/src/validators/blockValidator.ts

> currently if the value is undefined or null, it won't run any nested validation at all. even if required.
> I think we should run nested validation if the field is required — even if that value is undefined.
See here: https://github.com/sanity-io/sanity/issues/1713#issuecomment-907546288
Closes #1713
Closes #2630
See the changes to the example validation schema for more info.
- Ensure this change doesn't break any of the current expectations in validation
- Try it out in the studio and see if it behaves the way you'd expect it to or if it's a regression.
- Validation markers will appear on nested fields if the containing field is marked as `Rule.required()`.<br />Fixes #1713
- Objects and arrays are now unset if they are empty.<br />Fixes #2630

fix(validation): run nested validation in nested fields if required

---

packages/@sanity/base/package.json
packages/@sanity/base/src/__legacy/@sanity/components/previews/types.ts
packages/@sanity/base/src/components/previews/defaultPreview.tsx
packages/@sanity/base/src/components/previews/types.ts
packages/@sanity/base/src/preview/components/SanityDefaultPreview.tsx

Recently we changed the default previews to be a bit smaller (35px vs 40px). The thumbnail _image_ that we are fetching is however still 80px, which creates a slightly unclear thumbnail when scaled down, since it's not a factor of 2 larger.
This changes the dimensions to 35 pixels which is the actually correct size, and passes a `dpr` property to the image URL library based on what the device reports as it's DPR (through the `window.devicePixelRatio` property, rounded down and capped at 3). 
This makes the thumbnails clearer on regular screens (because the size is correct - 35px vs 40px) and clearer on high-DPI monitors such as Mac retina displays and mobile phone displays.
Current (1 DPR display):
With this change  (1 DPR display):
- Does the change in default media size have any …

fix: use correct width/height for preview images, scale by dpr

---

.eslintrc.js
gulpfile.js
jest.config.base.js
packages/@sanity/form-builder/src/utils/getValidationRule.ts
packages/@sanity/types/src/schema/types.ts
packages/@sanity/types/src/validation/types.ts
packages/@sanity/validation/src/inferFromSchema.ts
packages/@sanity/validation/src/inferFromSchemaType.ts
packages/@sanity/validation/src/util/normalizeValidationRules.test.ts
packages/@sanity/validation/src/util/normalizeValidationRules.ts
packages/@sanity/validation/src/validateDocument.test.ts
packages/@sanity/validation/src/validateDocument.ts
packages/@sanity/validation/src/validators/blockValidator.ts

The following PR fixes a few bugs and ups test coverage for the validation lib:
- fixes a bug where item paths were not being properly propagated in `validateItem`
- fixes an existing/older bug where reference validation was not running. this fix involves recursively pulling the type chain from the schema. see the function `getTypeChain`
- refactors parts of `inferFromSchema` into a new function `normalizeValidationRules` that runs all schema validation functions without the assumption of `inferFromSchema` mutation. this fixes another existing/older bug where `Rule.fields({})` would not give the correct rule context of the nested field type. this also greatly simplified the `inferTypeFromSchema` function
- the previous change required de-duping `Rule.fields` validation results. see the …

misc validation fixes

---

packages/@sanity/default-login/src/util/getProviders.js

With the introduction of SSO we need a way to determine if we should allow sso prompts on studio login. The `/auth/providers` endpoint has been updated to include an `sso` object which contains the keys of enabled `sso` types. This PR checks if any of those flags are set and if so, allow custom entities in `default-login.json`.
This will be a silent release until after the beta period.

feat(default-login): add support for sso login providers

---

packages/@sanity/import-cli/package.json
packages/@sanity/import-cli/src/sanity-import.js

Upgrades the meow dependency to the latest version that still supports node.js 10. This fixes a security issue that Snyk reported: https://github.com/sanity-io/sanity/pull/2735
Closes #2735
- Run the CLI tool and make sure it parses the flags correctly (it should, from my testing)
```
packages/@sanity/import-cli$ node src/sanity-import.js -p abc123 -d dataset --token=foo --replace --allow-failing-assets some-source.ndjson
```
None (invisible for end-user)

chore(import-cli): upgrade meow dependency

---

packages/@sanity/default-layout/src/main/ErrorScreen.tsx
packages/@sanity/default-layout/src/main/RenderTool.tsx

Fixes an issue where (for some reason) components can crash during rendering
without emitting an Error instance. This leads to the error screen crashing
when attempting to extract the stack trace from it.
With this change, we render a generic unknown error if we don't receive any
error instance, and check for a stack property before attempting to use it.
For additional safety, we also check for the info property and the component
stack being present before attempting to use it.
Reproducing this is a bit hard - the example I have found was using `react-player` in a preview component and passing it a valid youtube URL. I think something about the lazy loading approach it takes makes the component crash in some unexpected way.
- Fixed an error where components causing errors during rendering …

fix(default-layout): handle render errors with no Error instance

---

packages/@sanity/server/src/configs/webpack.config.js

This PR aliases `styled-components` to the version installed in the studio (or a hoisted copy, potentially) within the webpack config. This is done to prevent the error where multiple versions of `styled-components` are used in the same app unintentionally. Ideally we wouldn't need this, but it seems npm/yarn hoisting isn't always perfect, so this at least provides some way to alleviate that pain. 
- Does it make sense?

fix(server): alias styled-components in webpack config

---

packages/@sanity/core/package.json
packages/@sanity/core/src/commands/documents/queryDocumentsCommand.ts
packages/@sanity/core/src/types.ts

Adds a `--api-version` flag to the `sanity documents query` command that... allows you to specify the API version to use!
For now we'll default to `v1` as before so as not to break any potential workflows depending on this command, but in the future (in an upcoming breaking version change) we might force the user to specify an API version either as a flag or as a stored CLI configuration somewhere.
If you don't specify the API version, we'll warn (to stderr):
```
➜ blog-studio ✗ sanity documents query '*[0]{_id}'
--api-version not specified, using `v1`
{
"_id": "08353495-d4c9-43fc-8ea1-71e502a626fb"
}
➜ blog-studio ✗ sanity documents query '*[0]{"text": pt::text(body)}' --apiVersion=2021-03-25
{
"text": "Nana"
}
```
Also expanded on the CLI typings slightly, adding the things needed for …

feat(core): add --api-version flag for documents query command

---

packages/@sanity/base/src/components/previews/defaultPreview.tsx
packages/@sanity/base/src/components/previews/mediaPreview.styled.tsx

This reverts the usage of `inset` css property instead of `left/right/top/bottom: 0`. The property is only [supported in Safari 14.1](https://caniuse.com/?search=inset) and up, which was released this year, so we should hold off on using it until support improves.

fix(base): fix usage of inset property

---

packages/@sanity/cli/src/actions/init-project/promptForDatasetName.js
packages/@sanity/core/src/actions/dataset/alias/validateDatasetAliasName.js
packages/@sanity/core/src/actions/dataset/validateDatasetName.js

Increase the dataset name character limit to 64
Dataset name limit increased to 64 characters

feat(datasets): increase max dataset name length

---

.babelrc
packages/@sanity/diff/package.json
packages/@sanity/export/package.json
packages/@sanity/field/package.json
packages/@sanity/import-cli/package.json
packages/@sanity/import/package.json
packages/@sanity/initial-value-templates/package.json
packages/@sanity/plugin-loader/package.json
packages/@sanity/portable-text-editor/package.json
packages/@sanity/react-hooks/package.json
packages/@sanity/resolver/package.json
packages/@sanity/server/package.json
packages/@sanity/structure/package.json
packages/@sanity/transaction-collator/package.json
packages/@sanity/util/package.json
packages/@sanity/webpack-integration/package.json
packages/@sanity/webpack-loader/package.json
packages/create-sanity/package.json
packages/sanity/package.json
scripts/normalizePackageFields.js

- Node.js 10 is out of LTS since April - we should be safe to require node 12 for our modules. 
- Ran the normalization script which yielded some smaller changes/fixes to the portable text package.json
- Changed minimum node.js version to v12 or higher

chore: require node 12

---

packages/@sanity/form-builder/src/FormBuilderInput.tsx
packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx
packages/@sanity/form-builder/src/inputs/files/FileInput/FileInput.tsx

- Adds missing TS types to various things.
- Removes unused `compareValue` from `FileInput` and `ReferenceInput` (earlier, these passed `compareValue` on to `ChangeIndicatorWithProvidedFullPath` which doesn’t use it).

refactor(form-builder): clean up

---

packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx

This fixes an issue introduced in v2.18.0 that would in some rare cases trigger an unset patch on the document itself, which again would trigger studio error. The fix is to not do the empty check if we're on root level (e.g. the object input is used for the document itself).
The proposed code change to see if it makes sense.
Fixes a bug that could in some rare cases trigger an error saying "Cannot read properties of null (reading 'expr')"

fix(form-builder): don't unset empty objects if on root level

---

packages/@sanity/dashboard/src/widgets/projectUsers/ProjectUsers.js

This uses the new `DefaultPreview` component in the `ProjectUsers` widget.
That the widget looks and behaves the same in the test studio dashboard.
- Us new `DefaultPreview` component in the `ProjectUsers` widget.

refactor(dashboard): update `DefaultPreview` in `ProjectUsers` widget

---

packages/@sanity/state-router/src/RouterContext.ts
packages/@sanity/state-router/src/index.ts
packages/@sanity/state-router/src/useRouter.ts
packages/@sanity/state-router/src/useRouterState.ts

- Moves `useRouter` and `useRouterState` to separate files.
- Removes opaque `deps` logic from `useRouterState` (it was not in use).

refactor(state-router): move hooks to separate files and simplify

---

packages/@sanity/base/src/client/versionedClient.ts
packages/@sanity/base/src/datastores/document/listenQuery.ts
packages/@sanity/desk-tool/src/panes/documentsListPane/DocumentsListPane.js
packages/@sanity/desk-tool/test/mocks/client.js
packages/@sanity/structure/src/DocumentList.ts
packages/@sanity/structure/src/parts/Client.ts
packages/@sanity/structure/test/DocumentList.test.ts
packages/@sanity/structure/test/DocumentTypeList.test.ts
packages/@sanity/structure/test/__snapshots__/DocumentList.test.ts.snap
packages/@sanity/structure/test/__snapshots__/DocumentListItem.test.ts.snap
packages/@sanity/structure/test/__snapshots__/DocumentTypeList.test.ts.snap
packages/@sanity/structure/test/__snapshots__/ListItem.test.ts.snap

This PR introduces two new methods on `DocumentList` and friends:
- `apiVersion(someApiVersion)` - sets the API version to use for the given filter
- `getApiVersion()` - retrieves the set API version
This allows the user to use new GROQ functions, as well as getting faster queries in some cases.
To allow for this, we also expand the `listenQuery` utility to allow specifying API version, and try to re-use studio clients where possible.
The default API version is still `v1` for most lists, since we can't guarantee that the previous filter will work with newer API versions. Simply document type lists however will default to `v2021-06-07`, since we can guarantee that those work.
- Does the API version get passed on correctly?
- Does the API align with current APIs?
**Highlight**: Added …

feat(structure): allow specifying API version for document lists

---

packages/@sanity/server/package.json
packages/@sanity/server/src/devServer.js

This works arounds a deprecation warning on node 16 caused by an incorrect "main" field in the original module:
```
❯ sanity start
(node:66158) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/espenh/webdev/studio/node_modules/webpack-dev-middleware/package.json' of 'middleware.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```
That the studio still works in development mode
- Fixed a deprecation warning being printed when running `sanity start` on node.js 16 or higher

chore(server): use forked webpack-dev-middleware

---

packages/@sanity/cli/.depcheckignore.json
packages/@sanity/cli/templates/moviedb/schemas/person.js

This migrates the schema icon in `packages/@sanity/cli/templates/moviedb/schemas/person.js` to `@sanity/icons`.
None. Transparent to the user.

refactor(cli): migrate schema icon to `@sanity/icons`

---

packages/@sanity/base/src/components/previews/defaultPreview.tsx

This adds back support for passing a `styles` prop to the `DefaultPreview` component. These styles isn't actually passed anywhere in the monorepo, but for someone using the component directly we still want to support it.
Note: Some styles values like `inner` doesn't make sense anymore since we removed the corresponding element.
That the `DefaultPreview` component renders with the passed class names.
n/a

fix(base): make sure the old `styles` properly for previews still work

---

packages/@sanity/language-filter/src/SelectLanguage.tsx

This fixes an overflowing popover and its placement when list of languages to filter is long.
| before | after |  
|--------|-------|
|![image](https://user-images.githubusercontent.com/10508/134487634-738bfea6-a8a2-4082-84ea-a31201ea96c3.png)|![image](https://user-images.githubusercontent.com/10508/134487765-008e93c9-4f42-4fdd-8182-5aca912ae607.png)|
Run the example studio `npm run example-studio` and review a document of type `Blogpost`. You will find the filter menu in the right top corner.
That the popover is placed correctly when the list of languages is long, and that it is scrollable.
- Fixes overflowing popover placement when list of languages to filter is long

fix(language-filter): fixes popover placement issue when language list is long

---

packages/@sanity/cli/.npmignore
packages/@sanity/cli/templates/blog/.gitignore
packages/@sanity/cli/templates/clean/.gitignore
packages/@sanity/cli/templates/ecommerce/.gitignore
packages/@sanity/cli/templates/moviedb/.gitignore

This PR fixes a (fairly old) regression where bootstrapped studios would not include a gitignore, often leading to the inclusion of `node_modules` and such in version control. The issue was simply that `.gitignore` would be ignored when packing by npm. We now explicitly lists gitignore files within the `templates` directory to _not_ be ignored, which fixes this.
Also tweaked the gitignores included a bit with some comments and less wide patterns.
That the change makes sense, and that the `init` command includes the gitignore file.
- New studios now include a `.gitignore` file by default

fix(cli): include gitignore in bootstrapped studios

---

packages/@sanity/desk-tool/src/panes/document/timeline/timelineItem.styled.tsx

Fix issue where the line between timeline items looked wrong when within two separate selections
| before | after |  
|--------|-------|
| ![image](https://user-images.githubusercontent.com/6951139/135093228-57bb5170-2e58-4367-b6f4-403e4bd2870d.png) | ![image](https://user-images.githubusercontent.com/6951139/135093504-594c456a-a05b-4366-acca-61a00db842e3.png)
Make sure that the colours of the lines work with the different cases.
You can test it out on the test-studio on the document-actions
Fix visual issue with the connecting line between timeline items.

fix(desk-tool): fix line when withinSelection

---

packages/@sanity/field/package.json
packages/@sanity/import-cli/.babelrc
packages/@sanity/import/.babelrc
packages/@sanity/import/package.json
packages/@sanity/import/src/uploadAssets.js

When checking whether or not an asset exists, we were doing a HEAD-request against the image asset URL, which triggers a transformation in order to output the correct content-length and such. Because we only care about the _presence_ of the asset, this PR introduces a change that (if an asset URL is a sanity image url) append `?fm=json` to the URL, resulting in a cheaper check.
Also took the liberty of updating the babel config to compile for node 12, as that is our current minimally supported version.
- Speed up asset imports from `sanity dataset import` in certain cases

fix(import): use json format for checking image assets

---

packages/@sanity/cli/src/actions/login/login.js

SSO login should be versioned under `v2021-10-01`
```
sg-sanity :: github.com/sanity-io/sanity ‹fix/vx-sso-version› » ./packages/@sanity/cli/bin/sanity login --sso sanity                                                                                                                                                                                                                                                130 ↵
This is an experimental API version, which will change without warning and may have serious bugs.
Opening browser at https://api.sanity.io/v2021-10-01/auth/saml/login/a9fd8216?type=listen&uuid=xxx&source=cli
Login successful
sg-sanity :: github.com/sanity-io/sanity ‹fix/vx-sso-version› » ./packages/@sanity/cli/bin/sanity login --sso sanity
```
* Build CLI
* Test to login with SSO …

fix(cli): version SAML login under non-experimental version

---

packages/@sanity/base/src/components/UserAvatar.tsx
packages/@sanity/desk-tool/src/panes/document/timeline/timelineItem.styled.tsx
packages/@sanity/desk-tool/src/panes/document/timeline/userAvatarStack.tsx

Added a tooltip with the `displayName` to the timeline section
Also fixed a smaller visual bug when you used the keyboard keys up and down in the timeline
Before
https://user-images.githubusercontent.com/6951139/135309179-78cd832f-96c9-4388-acba-d38da3dfdcd5.mov
After
https://user-images.githubusercontent.com/6951139/135309195-9c3c4339-312f-41f1-a1ef-2f52c251f4bc.mov
The situations mentioned above ☝️ 
Add tooltip to the avatars in the timeline so it's easier to check who made changes in the document.
Fix visual bug in the timeline when using keyboard.

fix(base): Add new prop called withtooltip & fix visual navigation in timeline

---

packages/@sanity/initial-value-templates/package.json
packages/@sanity/initial-value-templates/src/parts/Icon.ts
packages/@sanity/structure/package.json
packages/@sanity/structure/src/ChildResolver.ts
packages/@sanity/structure/src/Component.ts
packages/@sanity/structure/src/ListItem.ts
packages/@sanity/structure/src/MenuItem.ts
packages/@sanity/structure/src/parts/Icon.ts
packages/@sanity/structure/src/parts/Schema.ts
packages/@sanity/structure/src/types.ts
packages/@sanity/structure/src/views/ComponentView.ts
packages/@sanity/structure/src/views/View.ts
packages/@sanity/structure/src/views/index.ts
packages/@sanity/structure/test/__snapshots__/DocumentTypeList.test.ts.snap

This migrates the icons used in @sanity/structure to use `@sanity/icons`.
This also caused a series of linting/type issues in structure because the types currently use legacy types like `Function` that isn't allowed in newer lint rules. The test snapshots does not match either since the icons is wrapped in `React.forwardRef`.
I have worked around/fixed this by:
- mapped a custom type `FixMe` to `Function` with a comment explaining why we lint ignore it and replaced all instances with the new `FixMe` type
- updated types where I think it made sense, like replacing `{}` with `Record<string, unknown>`, replacing `any` with `unknown` etc.
- updating the test snapshots.
[sc-11466] [sc-11467]
- That all the type fixes looks fine.
- That the test snapshot change is okay
n/a

refactor(structure): replace icons with icons from `@sanity/icons`

---

packages/@sanity/base/src/components/IntentButton.tsx
packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx

This fixes a problem with IntentLinks that is passed the disabled prop or in other ways isn't "ready", as with the link in the reference input.
Before this fix you could click the intent link, and it just sent you to a non-existing url `/intent/edit//`, which in turn gave you an error screen.
- Make sure that you cannot click on the link (no navigation) when the reference input is empty
- Make sure that the title anchor (even when empty) shows the right text (should be empty when the anchor is empty)
Fixed JS error when clicking intent links in empty reference inputs

fix(form-builder): add fix for reference input when it's disabled

---

packages/@sanity/base/src/components/MissingProjectConfig.tsx

Migrate `missingProjectConfig` to `@sanity/ui`.
**Before**
**After**
n/a

refactor(base): migrate missingProjectConfig to `@sanity/ui`

---

packages/@sanity/form-builder/src/inputs/PortableText/PortableTextInput.tsx

After #2814 it became an issue in the editor with the readOnly state of things. We need to make sure the editor is re-rendered whenever readOnly changes.
This will be dealt with more gracefully in another branch in a PR at a later time.
Also I have discovered a prop that is not memoized and triggers unnecessary re-renders. This is now fixed in it's own commit.
That you can edit Portable Text after reloading the page with an PT editor on that page.
Not needed as the problem is solely in `next`.

Fix issue with readOnly state in the PTE

---

packages/@sanity/base/src/datastores/grants/highlevel.ts

When checking whether the current user has update access to the draft of a published document we currently check the access rules against the published document (if it exists) _as is_. This gives false negatives for access rules that requires the id to be in the drafts path e.g. `_id in path("drafts.**")`. This patch fixes the issue by checking against the published document _with the draft id_ instead.
Publish any document in the test studio, then add `#_debug_roles=contributor` to the url and verify that you can still edit the document ([see the access rules for the `contributor` debug role](https://github.com/sanity-io/sanity/blob/5280c51937e7987e50a96767f7f5e2e59aab22eb/packages/@sanity/base/src/datastores/grants/debug/exampleGrants.ts#L24-L33))
- fixes an issue that in some cases …

fix(base): fix issue that disallowed editing the draft of a document that has been published

---

packages/@sanity/dashboard/README.md

This replaces the mention of CSS parts with the `DashboardWidget` component introduced in `@sanity/dashboard:2.13.0`.
- Check that the widget example makes sense
- CSS parts for Custom widget example in `@sanity/dashboard` was replaced with the `DashboardWidget` component

refactor(dashboard): remove css parts from readme

---

packages/@sanity/client/src/util/getSelection.js
packages/@sanity/client/test/client.test.js

The javascript client getSelection (used in patch and delete) accepts an object with a query, but not params for that query
I've added the option to pass params in adition to the query that was already accepted. I added a test for this as well, but I'm not 100% sure if the test is helpful?
Running the tests works fine, and testing this feature in my own project also worked fine 
(This example isn't extremely useful since I could have just used the document id, but the intention is to use the query to check the author for example)
```
sanity
.delete({
query: `*[_type == 'submission' && _id == $submissionId]`,
params: { submissionId: id },
}) …
```

feat(client): add support for patch/delete with query and params

---

packages/@sanity/code-input/README.md

I spent quite some time researching a good way to display this in my frontend-app, thought an example usage in the docs might be useful for the next user ;-)
Example usage of data from the code-input in a React app
**Checklist**

docs(code-input): example usage in react frontend

---

packages/@sanity/cli/package.json
packages/@sanity/import-cli/package.json
packages/@sanity/server/package.json

- Upgrades ora and strip-ansi to latest non-esm versions to fix security vulnerabilities
Supersedes #2766 and #2767
That the code runs and works as expected.
`ora` is used in the CLI for all spinners, and `strip-ansi` is used for hot module reloading in development mode of the server.
None, transparent to the end-user.

chore(deps): upgrade dependencies

---

packages/@sanity/language-filter/README.md

Adds guidance for installing the languages filter plugin, ensuring it's in `sanity.json`
Readme
Additional guidance for installing languages filter plugin

add note about ensuring the plugin is listed in sanity.json

---

packages/@sanity/form-builder/src/inputs/DateInputs/__tests__/CommonDateTimeInput.test.tsx
packages/@sanity/form-builder/src/inputs/DateInputs/__tests__/DateInput.test.tsx
packages/@sanity/form-builder/src/inputs/DateInputs/__tests__/DateTimeInput.test.tsx

Did you know that `getTimezoneOffset()` returns different things during DST? I did not. TIL lol
Do the tests pass now?
N/A

fix(form-builder): update tests for DST

---

packages/@sanity/desk-tool/src/getIntentState.ts
packages/@sanity/desk-tool/src/utils/resolveIntent.test.ts
packages/@sanity/desk-tool/src/utils/resolveIntent.ts

This is a small follow up to the new (unreleased as of now) intent resolver. This PR:
- limits default resolution to the default filter (e.g. `_type == $type`). This is to prevent false positive matches where the user may not want an intent match.
- refactors the breadth depth search into a concurrent search using `Promise.all` for structure that use promises
See the changes to `resolveIntent.ts` and that all intents resolve as expected.
N/A

fix: intent resolver follow up

---

packages/@sanity/desk-tool/src/DeskTool.test.tsx
packages/@sanity/desk-tool/src/defaultStructure.tsx
packages/@sanity/desk-tool/src/utils/resolvePanes.ts

This PR makes the fallback editor utilize `getDefaultDocumentNode` so that configured views in there will still show up when the intent can't be resolved.
Implement getDefaultDocumentNode and then use an intent link that resolves to the fallback editor. Views configured there should be visible in the fallback editor now.
- Fixes an issue where document views would not appear in certain cases when implementing `getDefaultDocumentNode`

fix(desk-tool): use `getDefaultDocumentNode` in fallback editor

---

packages/@sanity/core/src/actions/exec/execScript.js
packages/@sanity/core/src/actions/exec/requireContext.js

I forgot to delete a thing! This should fix the `sanity exec` issue related to `require.context`.
Closes #2923

fix(core): remove require.context in execScript

---

packages/@sanity/cli/src/actions/init-project/initProject.js
packages/@sanity/cli/src/commands/init/initCommand.js

Updates the CLI to take in a parameter (`--project-plan`) to allow a user to choose a plan from the cli. If a plan is invalid (for whatever reason) it just blows up!
```
? Select project to use Create new project
? Your project name: will-definitely-fail
ClientError: Plan "not-a-plan" does not exist
at onResponse (~/projects/sanity/sanity/packages/@sanity/client/lib/http/request.js:27:13)
at applyMiddleware (~/projects/sanity/sanity/node_modules/get-it/lib-node/util/middlewareReducer.js:14:23)
at onResponse (~/projects/sanity/sanity/node_modules/get-it/lib-node/index.js:81:22)
at ~/projects/sanity/sanity/node_modules/get-it/lib-node/index.js:48:55
at callback (~/projects/sanity/sanity/node_modules/get-it/lib-node/request/node-request.js:57:46)
at …
```

feat(cli): allow plan selection through CLI flag

---

packages/@sanity/core/src/commands/documents/queryDocumentsCommand.ts
packages/@sanity/core/src/util/colorizeJson.js

`--api-version` didn't work because the code looks for `--apiVersion`. I also wonder if we shouldn't support setting it as an environment variable or something? Having the warning appear just because you didn't care to specify it, is pretty annoying.
Check if
```sh
sanity documents query --apiVersion 2021-11-03 '*[]' 
```
works.
Fixes help text and warning for `sanity documents query` when the API version isn't set

docs(core): fix typo in help text and error message

---

examples/test-studio/schema/debug/conditionalFields.js
packages/@sanity/base/src/_exports/hooks.ts
packages/@sanity/base/src/conditional-property/__tests__/useResolveConditionalProperty.test.tsx
packages/@sanity/base/src/conditional-property/index.ts
packages/@sanity/base/src/conditional-property/useConditionalProperty.tsx
packages/@sanity/desk-tool/src/panes/document/changesPanel/ChangesPanel.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/documentViews/FormView.tsx
packages/@sanity/field/src/diff/components/ChangeList.tsx
packages/@sanity/field/src/diff/components/ChangeResolver.tsx
packages/@sanity/field/src/diff/components/ConditionalPropertyResolver.tsx
packages/@sanity/field/src/diff/components/DocumentChangeContext.tsx
packages/@sanity/field/src/diff/components/FieldChange.tsx
packages/@sanity/field/src/diff/components/GroupChange.tsx
packages/@sanity/form-builder/src/FormBuilderInput.tsx
packages/@sanity/form-builder/src/inputs/common/ConditionalHiddenField.tsx
packages/@sanity/form-builder/src/inputs/common/ConditionalReadOnlyField.tsx
packages/@sanity/form-builder/src/inputs/types.ts
packages/@sanity/types/src/schema/types.ts

- Fixes a problem where the form view would not know that a whole document is read-only and it also accepts a callback, so now the resolved readOnly value is passed down through the document
- Updates the context the changes panel uses to include the document value so that FieldChange and GroupChange can resolve their readOnly callbacks if any.
- Updates the change components to resolve the hidden property if it's a function

fix(conditional-fields): resolve readOnly in changes panel

---

packages/@sanity/form-builder/src/inputs/PortableText/Editor.styles.tsx
packages/@sanity/form-builder/src/inputs/PortableText/object/BlockObject.tsx
packages/@sanity/form-builder/src/inputs/PortableText/text/Annotation.tsx
packages/@sanity/form-builder/src/inputs/PortableText/text/AnnotationToolbarPopover.tsx
packages/@sanity/form-builder/src/inputs/PortableText/text/Decorator.tsx
packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.styles.ts
packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.tsx
packages/@sanity/form-builder/src/inputs/PortableText/text/constants.ts
packages/@sanity/form-builder/src/inputs/PortableText/text/helpers.ts
packages/@sanity/form-builder/src/inputs/PortableText/text/index.ts

This refactors `TextBlock` and `Decorator`:
- Removes unused `data-*` attributes.
- Uses `data-*` attributes instead of conditional CSS.
- Moves styles to a separate file – `TextBlock.styles.ts`.
- Moves constants to a separate file – `constants.ts`.
- Moves helpers to a separate file – `helpers.ts`.
- Replaces `switch` statements with constant config objects.
- Uses CSS variables to colorize marker backgrounds.
And `BlockObject`:
- Add missing bottom padding.
- That markers work as they have been.
- That blocks render and function as they have been.

refactor(form-builder): simplify block components

---

packages/@sanity/types/src/validation/types.ts

Makes `cloneWithMessage` optional so the `ValidationError` type is more usable
This change is very minor so I would say it's good to go if the typechecking CI passes
Improves usability of `ValidationError` by making `cloneWithMessage` optional

fix(validation): make cloneWithMessage optional

---

packages/@sanity/form-builder/src/inputs/PortableText/object/renderers/PopoverObjectEditing.tsx

Safari would blink and cause layout issues when editing through popover modals in the PTE.
This is probably because we set `display: none` on the refElement and Safari can't compute the dimensions correctly. 
Instead of display, we now use `visibility: hidden` so that element keeps its dimensions.

fix(form-builder): fix Safari issue with PTE popovers

---

packages/@sanity/state-router/src/components/RouterProvider.tsx

Fixes a small bug that causes URLs to flash while resolving intent IDs.
Try creating a new document via intent links and ensure there is no URL flashing.
Fixes a bug that caused the URL to flash different IDs while resolving create intents.

fix(state-router): prevent ID flashing when resolving intents

---

packages/@sanity/form-builder/src/inputs/DateInputs/CommonDateTimeInput.tsx
packages/@sanity/form-builder/src/inputs/DateInputs/base/LazyTextInput.tsx

This fixes an issue where you weren't able to clear an invalid date in a date field if the field `value` was empty/`undefined`.
Normally this would be handled by the `useEffect` triggering on `value` changing, but in this case `value` is always `undefined` since the invalid date is saved in local state.
- That you are able to enter a invalid date like `this is invalid`, then able to clear it again
- Fixes an issue that prevents clearing a invalid date value when the field is empty

fix(form-builder): fix clearing invalid date values

---

packages/@sanity/client/src/data/dataMethods.js
packages/@sanity/client/src/sanityClient.js
packages/@sanity/client/test/client.test.js

`useCdn: true` only applied to GET/HEAD requests sent to the /data-endpoint. However, in the case of a huge query then we send the query as a POST request and this is still supported and cached by the API CDN. This PR makes sure that these requests also gets sent to the API CDN.
This implements it by introducing an internal `canUseCdn`-option to the `_requestObservable` method. (A potential improvement in the future would be to also use this explicitly in the code base instead of having a magical `if (uri.startsWith("/data"))` deep inside a core method, but I decided against to keep the diff small).
- Check that adding this functionality into the `_requestObservable` method doesn't cause any problems elsewhere.
- Calling `fetch` with huge queries will now respect `useCdn: true`.

feat(client): respect useCdn when queries are sent with POST

---

packages/@sanity/base/src/change-indicators/ChangeBar.styled.tsx
packages/@sanity/base/src/change-indicators/ChangeBar.tsx
packages/@sanity/base/src/change-indicators/ChangeIndicator.tsx
packages/@sanity/base/src/change-indicators/ElementWithChangeBar.styled.tsx
packages/@sanity/base/src/change-indicators/ElementWithChangeBar.tsx
packages/@sanity/base/src/change-indicators/__workshop__/example.tsx
packages/@sanity/base/src/change-indicators/overlay/Connector.styled.tsx
packages/@sanity/base/src/change-indicators/overlay/Connector.tsx
packages/@sanity/base/src/change-indicators/overlay/ConnectorsOverlay.tsx
packages/@sanity/base/src/components/formField/__workshop__/example.tsx
packages/@sanity/form-builder/src/inputs/PortableText/object/BlockObject.tsx
packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.styles.ts
packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.tsx
packages/@sanity/form-builder/src/inputs/arrays/common/list.tsx

A small redesign of change indicators (yellow lines suggesting that input has changed since last published)
- indicators are now moved outside of the inputs, 2px to the right
- the hover effect is much simpler now, icon and tooltip are removed
- indicators (and therefore connectors) are always yellow, don't turn blue when a field is focused
- indicators are not recognised when navigating a form with a keyboard (when you tab from a field, the focus jumps directly to the next input, ignoring the indicator. it makes it inaccessible for keyboard users but this is acceptable as we have other ways of opening review changes that keyboard users can exploit. whereas this behaviour is annoying and breaks patterns regarding what is usually expected from web forms)
- spacing between array items in …

feat(base): improve change indicators

---

packages/@sanity/client/sanityClient.d.ts

Transaction visibility doesn't support the defer keyword, so deprecate the old in case someone is using it, and add deferred.
See https://www.sanity.io/docs/transactions#80cd6d6bd47b
Note that sending `visibility=defer` will cause:
```
{"error":{"description":"Could not decode query string parameter \"visibility\" value \"defer\": Invalid visibility value","type":"httpBadRequest"}}
```
* Implementation 
* 
Fixes `deferred` mutations

fix(client): deprecate defer and add deferred visibility

---

dev/test-studio/schema/standard/portableText/simpleBlock.js
packages/@sanity/form-builder/src/inputs/PortableText/Editor.tsx
packages/@sanity/form-builder/src/inputs/PortableText/Input.tsx
packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.tsx
packages/@sanity/schema/src/sanity/validation/types/block.ts

Latest Chromium has some serious performance issues when it comes to spellchecking via the browsers default spellchecking.
This is really noticable on larger documents, and it seems that almost everyone doing text editing online is being hit by this regardless of editor.
https://bugs.chromium.org/p/chromium/issues/detail?id=1271918
To work around this let's finally make spellchecking configurable via the schema for the `block` type:
```
{
type: 'block',
options: {
spellCheck: true,
},
},
```
Spellchecking is off by default with this change which should probably be the default anyway.
That this option does the default and is configurable.
Disabled default-on spellchecking for the Portable Text Input, and introduced schema option to configure this via `options.spellCheck`

Configure PT spellchecking via the schema

---

packages/@sanity/desk-tool/src/DeskTool.test.tsx

This PR improves the reliability of the desk-tool tests by using a proxy instead of an object spread.
@sjelfull showed me [a run](https://github.com/sanity-io/sanity/runs/4369598916?check_suite_focus=true) where this test broke to a very strange error `TypeError: Cannot read property 'unstable_useConditionalProperty' of undefined`. This PR fixes that issue by preserving the module and intercepting property calls instead of creating a new object.
N/A

test(desk-tool): proxy module instead of spread

---

packages/@sanity/default-layout/src/createDocumentDialog/CreateDocumentDialog.tsx

Fixes a bug that disabled all options in the global 'create document'-menu due to insufficient permissions
Verify that the global create document menu display correct disabled state based on current user's permission
- Fixes a bug that disabled all options in the global 'create document'-menu due to insufficient permissions

fix(default-layout): fix permissions bug in global "create document" menu

---

packages/@sanity/desk-tool/package.json
packages/@sanity/desk-tool/src/panes/document/documentPanel/ReferenceChangedBanner.test.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/ReferenceChangedBanner.tsx

This PR re-works the reference changed banner a bit to fix some bugs + updates the copy. I noticed that if you quickly switch templates, you'll get the reference changed banner flash.
Try replacing an existing reference with a new document created in-place. In the current branch, you should see the reference banner flash but in this version, it's fixed.

fix(desk-tool): fix flashing reference changed banner; update copy

---

cypress/integration/form-builder/conditionalFieldset.test.js

This PR fixes the failing e2e tests for conditional fields by hard-coding a specific test document ID and moving some async logic around. I also removed the clean up phase so concurrent runs shouldn't fail
Do the e2e test pass now? Do the changes break any existing assumptions?

test: update document creation and navigation

---

packages/@sanity/desk-tool/src/panes/document/statusBar/sparkline/PublishStatus.tsx
packages/@sanity/desk-tool/src/panes/document/statusBar/sparkline/ReviewChangesButton.tsx

Fix visual bug where the tooltip width was tied to the width of the publish and review changes buttons
| before | after |
|--------|-------|
|    ![image](https://user-images.githubusercontent.com/6951139/144823084-fd88fd6a-8d2f-4138-9b13-9c9dcf7a417b.png)  |    ![image](https://user-images.githubusercontent.com/6951139/144823381-de689792-7628-4745-b2c8-14077eaee70d.png) |
- Make the panel window small
- Hover over the publish & the review changes buttons at the bottom
Fix visual bug where the tooltip width was tied to the width of the publish and review changes buttons

fix(desk-tool): fix width issue on publish and review changes button tooltip

---

packages/@sanity/desk-tool/src/utils/createPaneResolver.ts
packages/@sanity/desk-tool/src/utils/createResolvedPaneNodeStream.test.ts

Fix a pane resolution bug where new subscribers of an observable would not get an emission causing a stuck loading pane.
I'll have a loom internally with more info.
Fixes an issue where desk structures with observables would be stuck loading.

fix(desk-tool): wrap with publishReplay(1)

---

packages/@sanity/default-layout/src/createDocumentDialog/CreateDocumentItem.tsx

The  "new document" dialog seems to have lost its "template" parameter, which means only the schema type is respected. This PR adds the missing ID. It does however need tests to prevent regressions.
- Fixed issue where the "new documents" dialog would not use the selected template

fix(default-layout): missing template id in new document dialog

---

dev/workshop/package.json

The CI started failing due to a new update to depcheck so this should fix it.
Does the CI pass? Does the workshop still run?

chore(workshop): remove unused dep

---

packages/@sanity/eventsource/browser.js

In our eventsource polyfill module, we are "branching" the environments based on the `package.json` [`browser` field](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/eventsource/package.json#L5-L6).
This has worked fine up until now, but we're starting to see some browser-like environments use the browser path even though they don't have a global `window` object. The result is that this crashes when we attempt to check `window.EventSource`.
With this PR, we explicitly check whether or not `window` is `undefined` before attempting to use it. A bit of an edge case, but technically more correct way of doing things anyway.
That the code still makes sense
- Fix a bug where importing the `@sanity/eventsource` module (or `@sanity/client`) in non-browser environments could …

fix(eventsource): check for window before using it

---

packages/@sanity/core/src/actions/graphql/deployApiAction.js

Every once in a while, we hear cases from users where after the GraphQL API deployment succeeds, the command does not. Most likely this is caused by some side-effect of loading the schema - often this can lead to pulling in React components, requesting animation frames, setting up timers/intervals and similar.
While it would be ideal that things would naturally close their handles and exit normally, this PR is a compromise which exits explicitly when deployment is successful. In a future version we might instead do the schema collection part as a forked child process, where we can exit only the schema collection process when complete, but I'll leave that for: the future.
- Fixed a case where the `sanity graphql deploy` command would not exit after a successful deploy

fix(core): explicitly exit on successful graphql deploy

---

dev/test-studio/schema/debug/validation.js
packages/@sanity/base/src/components/formField/FormFieldValidationStatus.tsx
packages/@sanity/base/src/components/formField/helpers.ts
packages/@sanity/base/src/components/formField/types.ts
packages/@sanity/base/src/components/validation/listItem.tsx
packages/@sanity/base/src/components/validation/validationList.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/header/ValidationMenu.tsx
packages/@sanity/form-builder/src/inputs/PortableText/_legacyDefaultParts/Markers.tsx
packages/@sanity/form-builder/src/inputs/PortableText/object/BlockObject.tsx
packages/@sanity/types/src/markers/asserters.ts
packages/@sanity/types/src/markers/types.ts
packages/@sanity/types/src/validation/types.ts
packages/@sanity/validation/src/Rule.ts
packages/@sanity/validation/src/util/convertToValidationMarker.ts
packages/@sanity/validation/test/__snapshots__/generics.test.ts.snap
packages/@sanity/validation/test/generics.test.ts

This PR introduces a new `info` validation rule. The rule works like the `warning` rule, that is, it does not block the ability to publish a document.
##
```
{
name: 'myString',
title: 'My string',
validation: (rule) => rule.min(5).info('Info validation message'),
}
```
##
```
{
name: 'myString',
title: 'My string',
validation: (rule) => [
rule.min(5).error('Error validation message'),
rule.min(5).warning('Warning validation message'),
rule.min(5).info('Info validation message'),
]
}
```
- The rule should not block the ability to publish a document
- General code review
Add info validation rule

feat: info level validation

---

packages/@sanity/cli/src/actions/login/login.js

When attempting to log in, if the CLI already has an auth token it will be used for requests to endpoints such as `/providers`. These requests might be rejected if the session is timed out or invalid, which is unfortunate - it might be the reason why the user is attempting to log in, after all.
This PR:
- Uses an unauthenticated client for requesting these routes, to prevent them from being rejected
- Attempts to log out any existing session upon successful login
- (Unrelated) Sets a stable API version for the SAML providers endpoint instead of using `vX`
- Fixes a bug where the CLI would not be able to log a user in an existing invalid/expired session was present

fix(cli): use authless requests when logging in

---

packages/@sanity/cli/src/actions/yarn/yarnWithProgress.js
packages/@sanity/cli/src/scripts/package-yarn.js

- Upgrades yarn to the latest 1.x version, and uses the non-legacy version (eg the one that only works on node 8 and up) for less transpiled code
- Bumps the network timeout when running yarn commands to 1 minute instead of the default (30 seconds). This _might_ help the issues we're seeing on CI where windows builds fail to install dependencies during the init step

feat(cli): use non-legacy yarn v1.22.17 under the hood

---

cypress/integration/form-builder/validation.test.js
dev/test-studio/parts/deskStructure.js
dev/test-studio/schema/ci/validationCI.js
dev/test-studio/schema/index.js
packages/@sanity/base/src/components/formField/FormFieldValidationStatus.tsx

This test focuses on the visibility of the validation icons displayed in each field, and whether the publish button is enabled or disabled depending on the validation of a document.
- The test in general and how it is authored
- Should more scenarios be tested?
Add form validation test

test: add form validation test

---

packages/@sanity/desk-tool/src/components/paneHeaderActions/PaneHeaderCreateButton.tsx

Partially addresses #2977.
This fixes a bug that caused items created from create intents to not appear in the menu potentially causing an empty menu like so:
Try creating custom create intents in menu items [(see here)](https://github.com/sanity-io/sanity/blob/561daac611da830d1cc0c61b2f74424983060b2a/dev/test-studio/parts/deskStructure.js#L209-L214). They should show up in the menu.
Fixes an issue where create intents would not appear in pane headers.

fix(desk-tool): fix create intents not appearing in pane headers

---

packages/@sanity/form-builder/src/inputs/PortableText/Input.tsx
packages/@sanity/form-builder/src/inputs/PortableText/object/renderers/DefaultObjectEditing.tsx
packages/@sanity/form-builder/src/inputs/PortableText/object/renderers/PopoverObjectEditing.tsx

- Disables click-outside-to-close for dialogs in the PTE.
- Wraps `editObjectNode` with the correct boundary element in the PTE.
- Passes a `boundaryElement` (the third argument) to `useClickOutside` to prevent popovers from closing when clicking outside of the boundary element (the current pane content).

fix(form-builder): the PTE dialogs should not close when clicking outside

---

packages/@sanity/base/src/preview/availability.ts
packages/@sanity/base/src/preview/utils/debounceCollect.ts

When requesting document availability we're collecting all requests within the same event loop tick and batches them into a single request to the endpoint that checks for availability reason. In cases where a document had a lot of references this could produce a request that was above the max request size. This commit splits the list of ids to check into chunks of 300 documents and fetches their availability in parallel, at most 10 requests at a time. These numbers are merely guesses about what would be reasonable limits.
Also includes a fixed typing issue with `debounceCollect` that didn't reflect real world behavior.
- Fixes an issue that could cause a max request size exceeded error for documents with many references.

fix(base): uniq and chunk availability requests

---

packages/@sanity/base/src/datastores/grants/documentPairPermissions.ts

This PR prevents a crash from the newer `unstable_useDocumentPermissions` API.
This comes from an internal bug report where the reporter was trying to create an `S.documentList()` with a `.filter('...')` and no `.schemaType('...')` in attempt to have the document list return more than one type.
Prior to this API, this was not supported and resulted in this: 
However, with the new API, you'll get a "the Desk Tool crashed" error which is much less clear.
You can reproduce the error by creating a structure with `S.documentList().filter("_type in ['post', 'author']")`. When you try to load an item from that list in `next`, it will throw. With this patch, you should get an error similar to the screenshot above.
- Fixes an issue that caused a crash instead of a warning screen when omitting …

fix(base): prevent crash if type `*` is provided to structure

---

cypress/helpers/createUniqueDocument.js
cypress/integration/form-builder/conditionalFieldset.test.js

This is a second pass of #3021 after it turned out tests were still flaky.
The most important improvement over #3021 is that I discovered two things:
- Most of the test time was spent waiting for the studio to reload before each test.
- All tests in a test group could be tested against the same version of the DOM, so there was no reason to reload the studio
The test speed went from a consistently 2+ minutes to running at around 16 seconds, or from 4 to 2 minutes for all tests.
- That all tests runs as expected
N/a

fix(cypress): improve e2e test speed

---

packages/@sanity/cli/package.json
packages/@sanity/cli/src/actions/versions/findSanityModuleVersions.js
packages/@sanity/cli/src/commands/debug/printDebugInfo.js
packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js
packages/@sanity/cli/src/commands/versions/printVersionResult.js
scripts/validateMonorepoDependencies.js

When running `sanity upgrade`, we would previously resolve the `latest` tag for
each installed `@sanity` module and blindly upgrade them to this version.
This is confusing, as it breaks with how npm/yarn handles upgrades. With this
PR, we instead find the maximum version compatible with the specified range for
a dependency. This also means that modules with pinned version numbers will
stay on their given version.
In addition to these improvements, this PR fixes an old pet peeve of mine where
the command would also upgrade dependencies like `@sanity/block-tools`, which
might be used in import tooling or similar. It _should_ only upgrade studio
dependencies, but we don't have an explicit list of these modules, so we use
an exclude list instead for now.
Most important change of this PR is to …

feat(cli): respect specified ranges when upgrading

---

packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx

Adds a small  change to the array of objects input that allows for passing the array item component. Potentially something we could provide as part of an official API in the future, but I'd consider it internal for now.
N/A (internal only)

fix(form-builder): add prop for passing the item component to array of objects input

---

dev/test-studio/parts/deskStructure.js
dev/test-studio/parts/panes/debug/DebugPane.tsx
packages/@sanity/desk-tool/src/panes/userComponent/UserComponentPane.tsx
packages/@sanity/desk-tool/src/types/types.ts

This PR allows serialized panes to pass the option `__preserveInstance` in order to tell the desk tool to preserve the instance (and not add the key).
Try the option with a custom pane component. Add a child. The custom component instance should not re-render.
N/A (keep it more hidden)

feat(desk-tool): experimental `__preserveInstance` prop

---

packages/@sanity/desk-tool/src/panes/document/DocumentPane.tsx

Fixes the root cause of #3011.
This issue was occurring because the `isLoaded` boolean was never being set to true causing 
Try the current broken singleton case in the test-studio with this branch. It should load now.
i.e. `/test/desk/custom;foo-bar`
Fixes an issue that caused singleton documents to never load if no schemaType was provided.

fix(desk-tool): fix issue with singletons with no type not loading

---

packages/@sanity/util/src/reduceConfig.ts
packages/@sanity/util/test/envConfig.test.ts

This PR adds `SANITY_STUDIO_PROJECT_NAME` env variable for setting the configured Studio project name via environment variables. It also adds previously missing tests for env variable config overrides.
Tests and the changed logic of util reduceConfig. I moved some env handling from the global scope of this file into the exported function. This change should affect all usages involving running, building or otherwise using the Studio config.
Added `SANITY_STUDIO_PROJECT_NAME` environment config variable

feat(util): add SANITY_STUDIO_PROJECT_NAME env variable

---

packages/@sanity/base/src/search/weighted/createWeightedSearch.ts
packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.ts

This fixes a couple of oversights/unintentional changes from the references in place release:
1) the default limit on studio searches were reduced from 1000 to 100. Since the search results comes unranked from the API this could cause better matches to disappear from the result list in cases where you had a lot of documents.
2) when fetching for existence of draft/published counterparts from hits returned from the reference search we used a `debug` request tag. Also, upping the amount of displayed search results in the reference input from 50 to 100 (after ranking)
That studio search works as expected, both global document search and reference search.
- Fixed an issue that could in some cases cause matching documents to be excluded from the search results

fix search limit issues

---

packages/@sanity/schema/src/legacy/types/reference.ts

When no title is given for a referenced document type, we currently default to the type name as-is, which makes the UI less user friendly (as pointed out in #3046).
This PR fixes it so that we display the referenced type in this order:
- The title defined for the referenced type at the reference field/array item, if any
- The title specified for the referenced document type, if any
- A [startCase](https://lodash.com/docs/3.10.1#startCase)'d version of the referenced document's type name (note: this follows from how we already resolve the default title for object types)
Verify that the UI displays titles of reference fields and array items in a user friendly way
- Made the default title of referenced document types more user friendly
Fixes #3046

fix(schema): improve default title resolution for references

---

packages/@sanity/form-builder/src/inputs/PortableText/toolbar/Toolbar.tsx

This PR fixes an issue where the toolbar sometimes gets double borders, and the expand button was incorrectly positioned when there were no action / insert items.

fix(form-builder): fix ui issues in PTE toolbar

---

packages/@sanity/form-builder/src/inputs/ReferenceInput/ArrayItemReferenceInput.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/InsertMenu.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/ArrayItem.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/CellItem.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/ItemForm.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/ItemLayoutProps.ts
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/RowItem.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/types.ts
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfPrimitivesInput/ItemRow.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfPrimitivesInput/types.ts
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfPrimitivesInput/utils/nearestIndex.test.ts
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfPrimitivesInput/utils/nearestIndex.ts
packages/@sanity/form-builder/src/sanity/inputs/reference/SanityArrayItemReferenceInput.tsx

This adds "add before"/"add after" menu items to the array input
The commit 8393ece6e7e141b2e51af348b14dbdcb5fad01d1 is a "best effort fix" to an existing issue that is made worse by this feature: when editing a string value in an array of primitive values and someone else simultaneously adds or remove a value above, your cursor/selection will stay at the same _array index_, which makes it appear as if your cursor is jumping to the input above (if added) or below (if deleted).
Make sure it works as expected for
- Arrays with primitive values (strings, numbers, booleans)
- Arrays of object values
- Arrays of references
- Supports adding new items before/after existing array items
Note: the depcheck CI failure is a false positive. Looking into it now.

support adding a new item before/after existing array items

---

packages/@sanity/cli/src/actions/init-project/initProject.js
packages/@sanity/cli/src/commands/init/initCommand.js

We'd like to expose coupon selection on the cli, similar to `--project-plan` to allow users to more easily create plans with different subscription plans.
`sanity init` is affected, please review project creation and using `--project-plan` and the new `--coupon`
Select a coupon code using `--coupon` for new projects with `sanity init`

feat: allow --coupon for sanity init

---

packages/@sanity/base/src/datastores/grants/createGrantsStore.ts
packages/@sanity/base/src/datastores/grants/documentPairPermissions.test.ts
packages/@sanity/base/src/datastores/grants/documentPairPermissions.ts
packages/@sanity/base/src/datastores/grants/types.ts

Fixes incorrect permissions in certain permissions cases + adds failing tests to cover this case in the future. Details in the comments of the code.
Review the changes and the new tests.
Fixes a bug that caused some false warnings with `duplicate` and `update` permissions.

fix(base): fix permissions bugs by fallbacking back to published variant

---

packages/@sanity/code-input/src/editorSupport.ts

During development of #3056 I hit a bug that was apparently fixed by importing the webpack resolver, but this import turned out to break the `graphql deploy` command (#3069). I tried removing it now, and everything seems to still work 🤷🏼 
- Check that the code input still works as expected
- Fixed an issue causing graphql deploy to error with the message "TypeError: Cannot read property 'setModuleUrl' of undefined"
Closes #3069

fix(code-input): remove webpack-resolver-import

---

dev/test-studio/schema/plugins/code.js
packages/@sanity/code-input/src/CodeInput.tsx

Address the following issue of the changes from #3056.  Due to JavaScript [Operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR#operator_precedence), the mode variable is interpreted wrongly, 
When the ace mode name is different from the language name, the following issue occurred. The mode is `c_cpp` while the language value is `cpp`.
Before:
After:
Note: This issue is not visible if the ace mode and language value is the same.
- Check that the code input work with an alternative language that has a different ace mode name to the language value name.
- Check that the code input work with default supported languages
- See file `dev/test-studio/schema/plugins/code.js`
- Fixed an issue causing the code-input plugin to wrongly assign the …

fix(code-input): ace mode variable is interpreted wrongly

---

packages/@sanity/core/src/util/mockBrowserEnvironment.js

It seems the code input is still breaking GraphQL deployments (at least I can reproduce this when adding the input to a studio and having a code field). It is likely that the way we are mocking a browser environment might lead ace to be somewhat confused, and attempting to use a global `ace` instance, which does not exist.
This PR attempts to find the `ace-builds` dependency as a studio dependency, and if it does, import it and set it to an `ace` global when mocking the environment. It's pretty hacky, but it's the best I could come up with short term.
- Add `@sanity/code-input` to a studios `package.json` dependencies
- Add `@sanity/code-input` to `plugins` in `sanity.json`
- Add a field of type `code` to any document/object schema type
- Run `sanity graphql deploy`
- Ensure that it does …

fix(core): provide ace globals when mocking browser env

---

packages/@sanity/desk-tool/src/panes/userComponent/UserComponentPane.tsx

Refactors `UserComponentPane` to `useState` instead of `useRef` so that `UserComponentPaneHeader` can re-render when the component does.
Closes #3025
Try out a custom component pane and see if it still works. Then try changing the component instance with a different set of action handlers. It should re-render.
Fixes a bug that caused some action handlers to never bind.

fix(desk-tool): prevent stale `actionHandlers`

---

packages/@sanity/cli/src/actions/versions/findSanityModuleVersions.js
packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js
packages/@sanity/cli/src/commands/versions/printVersionResult.js

This PR fixes two issues with the `sanity upgrade` command: 
1. #3009 introduced a bug where if you are missing (eg not installed) any of the declared `@sanity` modules, the CLI would crash when running `sanity upgrade`, `sanity versions` or `sanity debug` (since these all tried to fetch the installed and latest versions of a module, and a change was made in #3009 where it returned `<missing>`, which would fail for semver utility functions). Fixed this by returning `undefined` instead, and manually using `<missing>` where we wanted to print the version number. 
2. Fixes a super obscure bug where yarn would crash when upgrading `@sanity/code-input` to the latest version, as the `react-ace` dependency has a `react-ace.min.js` file in `<= 8.x` that has in `>=9.x` turned into a _folder_ …

fix(cli): handle missing dependencies on upgrade/versions

---

packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithInsertData.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPatches.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPortableTextMarkModel.ts
packages/@sanity/portable-text-editor/src/editor/withPortableText.ts
packages/@sanity/portable-text-editor/src/types/slate.ts
packages/@sanity/portable-text-editor/src/utils/__tests__/operationToPatches.test.ts
packages/@sanity/portable-text-editor/src/utils/__tests__/values.test.ts
packages/@sanity/portable-text-editor/src/utils/operationToPatches.ts
packages/@sanity/portable-text-editor/src/utils/values.ts

Fixed a bug where splitting lines in the Portable Text Editor including a inline object would corrupt the inline object data.
This turned out to be a bug in the `operationToPatches` where we would not convert between the formats properly when a void node was involved.
Added a test for this as well.
Also fixed some type issues and removed obsolete code as part of this fix.
Fixes issue #2522
That the issue described in #2522 is solved and the example operation succeeds.
Fixed a bug where splitting lines in the Portable Text Editor including a inline object would corrupt the inline object data.

Fix bug with splitting lines including inline objects

---

packages/@sanity/language-filter/README.md

Update the @sanity/language-filter readme to be more like the new [@sanity/document-internationalization readme](https://www.npmjs.com/package/@sanity/document-internationalization)
- Adding a gif
- Adding a “what this plugin solves” section at the start
The new readme, comparing it to [@sanity/document-internationalization readme](https://www.npmjs.com/package/@sanity/document-internationalization)
- Updated `@sanity/language-filter` readme with more explanation about internationalization patterns in Sanity

update readme for consistency with @sanity/document-internationalization

---

packages/@sanity/desk-tool/package.json
packages/@sanity/desk-tool/src/panes/document/DocumentPane.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/DocumentPanel.tsx
packages/@sanity/desk-tool/src/panes/document/inspectDialog/InspectDialog.tsx

Move the inspect dialog to be pane specific and allow for a user to use the actions in the footer
- Open references in place and try to open the inspect dialog in both
- Change the tabs between the two
- Try to publish changes / revert changes / duplicate actions in the footer
- Make inspect dialog pane specific and allow footer actions to be used when it is open

feat(desk-tool): make inspect dialog pane specific

---

packages/@sanity/desk-tool/src/panes/document/documentPanel/DocumentPanel.tsx

Fix an [issue](https://sanity-io.slack.com/archives/CL088LK3K/p1642514167011200) where a user with a role and rule wasn't being allowed to edit a document when they should.
I've also added an updated version of the `community-studio` to the examples. My plan would have been to add this in a separate PR but it does make testing this fix much easier. So if we want (and likely should), I can drop the commit before pushing the fix so that it's just itself. Especially since there seems to be a lot of things failing because of it.
I don't know if there's a reason / situation where we needed the dummy in this situation. 🤔 
1. install dependencies + run `npm run community-studio`
2. use `#_debug_roles=editor` in the url (this is to be able to go to a grant rule where you can edit your own …

Fix permission issue panel

---

packages/@sanity/vision/package.json
packages/@sanity/vision/src/components/ParamsEditor.styled.js
packages/@sanity/vision/src/components/ResultView.styled.js
packages/@sanity/vision/src/components/VisionGui.js
packages/@sanity/vision/src/components/VisionGui.styled.js
packages/@sanity/vision/src/util/resizeObserver.js

This improves the pane resizing by setting better min/max boundaries for all panes (current version of library doesn't support percentages).
It also fixes a padding issue that prevented users from getting to the bottom of results.
https://user-images.githubusercontent.com/10508/150348812-7b88d6b5-0745-46aa-9b17-a879bedf1c0a.mp4
**Results**
- That panes resizes well
- That min and max size for panes looks good
- That results bottom is not cut off
- That disabling resize when container is lower than 550px behaves fine
- Improves the panes in Vision so controls or result never is cut off when there isn't enough room

fix(vision): fix min and max pane sizes so controls or results is never cut off

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx

Check that the leaf text is really empty before displaying the placeholder as the decoration array is lagging behind typing.

Fix glitch in placeholder rendering

---

packages/@sanity/portable-text-editor/src/utils/__tests__/operationToPatches.test.ts
packages/@sanity/portable-text-editor/src/utils/operationToPatches.ts

Fixes a bug introduced in d4705d406f52bea868ede20b3a48416f5de3770d where an error would be thrown when producing a insertNode patch.
Also added tests for this.

fix(portable-text-editor): fix bug with insertNodePatch

---

dev/test-studio/schema/standard/arrays.js
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx

This PR fixes a race condition where required array input with primitives some times crashes while a document is being published/deleted.
Theory is that the code is assuming `value` is always an array, but in this particular case it is temporarily undefined while the prop is being updated.
- That it makes sense to fallback to a empty array in this particular case
- Fix a race condition where required arrays with primitive values some times crashes while a document is being published/deleted.

fix(form-builder): prevent race condition crashing the studio in arrays

---

packages/@sanity/portable-text-editor/src/utils/__tests__/operationToPatches.test.ts
packages/@sanity/portable-text-editor/src/utils/operationToPatches.ts

This will add more tests for the `operationToPatches` functions.
Also, refactor two block determinators to be more spesific (test that it's actually text blocks we are dealing with).
Doesn't need to be mentioned as this doesn't really change anything.

Add more tests and fix bug in insert blocks into empty editor

---

packages/@sanity/form-builder/src/inputs/PortableText/hooks/useObjectEditFormBuilderFocus.tsx

There was an issue where if the input of a inline object in the Portable Text Editor set an empty focusPath,
it would close the object editing interface as the editor would interpret that as focus on the editor node itself.
In these cases, make sure we end the focusPath with the focus terminator symbol.
That editing inline objects of type Reference is possible.
Create a inline object of type reference and set it to an actual reference. Close the editing interface and try to open it again. 
Fixes a bug in the Portable Text Editor where opening inline objects of type reference would not open the editing interface if set already.

fix(form-builder): fix issue with editing inline object references in PTE

---

dev/test-studio/schema/standard/arrays.js
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx

When duplicating an array item, an item's initialValues currently take precedence over the duplicated data. This wasn't  intentional and this patch fixes it.
There's an example of an array of items with initial values here: https://test-studio-git-bug-sc-13780array-of-objects-initial-val-9183e9.sanity.build/test/desk/input-standard;arraysTest;8135c43b-9f28-46bb-8d87-3207901dced4%2Cpath%3DarrayWithInitialValue
- Make sure initial value is *not* inserted when duplicating an item
- Make sure initial value is still used when adding new items
- Fixes a bug that caused "duplicate array item" to insert the initial value instead of a duplicate of the chosen item

fix(form-builder): skip initial value resolution when inserting non-empty array items

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditor.test.tsx

The placeholder in the PTE should not take any pointer events. On Webkit this manifested as an issue setting focus in the editor  with some pointer events.
Even though it has `user-select: none;` it was still possible in Webkit to select this text for some weird reason, making it troublesome to set focus in the editor and start typing afterwards.
That you always get focus and can type when using the mouse to set focus in an empty editor.
Fixed an issue where the empty editor placeholder text sometimes would cause focus problems in Webkit.

fix(portable-text-editor): disallow pointer events on placeholder

---

packages/@sanity/form-builder/src/inputs/PortableText/hooks/useHotKeys.tsx

There will be issues if hotkeys from props are defined inline and is always a new object (they are set up at every render).
Ensure that we only read this prop initially, and warn if the hotkeys are different across renderers.
It doesn't need to be mentioned.

Guard that hotkeys for the PTE is a stable object

---

packages/@sanity/base/src/change-indicators/ChangeIndicator.tsx
packages/@sanity/base/src/change-indicators/ElementWithChangeBar.styled.tsx
packages/@sanity/base/src/change-indicators/ElementWithChangeBar.tsx
packages/@sanity/form-builder/src/inputs/PortableText/Editor.tsx
packages/@sanity/form-builder/src/inputs/PortableText/_common/ReviewChangesHighlightBlock.tsx
packages/@sanity/form-builder/src/inputs/PortableText/_common/StyledChangeIndicatorWithProvidedFullPath.tsx
packages/@sanity/form-builder/src/inputs/PortableText/_common/index.ts
packages/@sanity/form-builder/src/inputs/PortableText/object/BlockObject.styles.ts
packages/@sanity/form-builder/src/inputs/PortableText/object/BlockObject.tsx
packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.styles.ts
packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.tsx

This PR adds a design update in the PTE where a block in the editor gets a background color when hovering on the changes indicator. See screenshot below.
- The block should only be highlighted on hover when there are changes
- Does the `onHasChanges` callback make sense? We need to know if the block has changes in order to be able to determine if the hover effect should be disabled or enabled inside `TextBlock` and` BlockObject`. Could this be approached differently?
Add background color to blocks in Portable Text Editor when hovering the changes indicator

feat: portable text review changes design update

---

packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/InsertMenu.tsx

Added `constrainSize` to the MenuGroup popover to limit the overflow of type options that the array input can have
- Add schema that adds a lot of different types
- example in `array.js` schema:
```
{
name: 'arrayOfALLTypesPopover',
title: 'Array of ALL the types',
type: 'array',
of: range(0, 60).map((value) => {
return {
type: 'image',
name: value,
}
}),
},
```
- Go to any of the array tests 
- Make sure that regardless of how many types are available, that the menu is readable and scrollable
Fix bug where when there were multiple types available in the array input "add before / add after" the options didn't scroll

fix(form-builder): fix overflow when there are many types

---

packages/@sanity/desk-tool/src/components/MissingDocumentTypesMessage.tsx

This PR updates the design of the `MissingDocumentTypesMessage` component that is displayed if the schema is empty.
Before/after:
**How to make this screen render:**
Remove the schema part in `sanity.json`:
```
{
"name": "part:@sanity/base/schema",
"path": "schema"
}
```
Return empty array in `createSchema`:
```
export default createSchema({
name: 'test-examples',
types: schemaTypes.concat([]),
})
```
- Review the design
Update design of empty schema message

feat(desk-tool): update `MissingDocumentTypesMessage` design

---

dev/test-studio/schema/standard/images.js
packages/@sanity/form-builder/src/inputs/files/FileInput/FileInput.tsx
packages/@sanity/form-builder/src/inputs/files/ImageInput/ImageInput.tsx

When an image has a field on it (e.g., an alt text string field), a certain sequence of events causes the image not to be unset. This poses a problem when that field is required, as it will prevent the document from being published even when the user deletes the field's contents.
The fix is a bit verbose, but leans on the same logic that the asset removal logic uses - eg if an asset is removed and it is the last non-crop/hotspot field with a value, unset the entire object. In this case we check if the patch being emitted from the field is an unset patch (eg the `alt` field wants to unset itself) and if so, whether or not there are any other non-empty values left in the object.
Fixes [sc-12411]
Schema example:
```
export default {
name: 'imageTest',
title: 'Image Test', …
```

fix(form-builder): unset image/file field when last subfield is cleared

---

packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js

After running sanity upgrade
> The following modules has new major versions
Text updated to check the number of module updates and write either
* “The following modules have new major versions”
* “The following module has a new major version”
First line of upgrade text
Fixed grammar in major version upgrade text

Change upgrade text depending on number of modules

---

packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withPortableTextMarkModelNormalization.test.tsx
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPortableTextMarkModel.ts

Fixed a bug where adding marks to a portable text block child would  be normalized wrong, and loosing existing marks in some situations. 
Basically the same fix as this commit: a8918d5fed325a639ea4f26cd84486ebc6cb29ec only for `addMark` as well.
Added test for this.
Fixed a bug where adding marks to a portable text block would cause loosing existing marks in some situations.

fix(portable-text-editor): fix normalization bug in adding marks + test

---

dev/test-studio/config/@sanity/vision.json
packages/@sanity/vision/README.md
packages/@sanity/vision/config.dist.json
packages/@sanity/vision/src/apiVersions.js
packages/@sanity/vision/src/components/VisionGui.js
packages/@sanity/vision/src/util/prefixApiVersion.js

This increases the default API version in Vision to `v2021-10-21`, and makes it configurable via config file `config/@sanity/vision.json`.
- ~That the config convention is the one we prefer (`config:` vs `part:` import)~
- That the readme update on how to configure Vision reads okay
- Set default API version in Vision to `v2021-10-21`
- Made default API version in Vision configurable

feat(vision): make default api version configurable

---

dev/test-studio/parts/tools/test-conditional-tool.tsx
dev/test-studio/sanity.json
packages/@sanity/default-layout/src/main/RenderTool.tsx
packages/@sanity/default-layout/src/router.tsx
packages/@sanity/default-layout/src/types.ts
packages/@sanity/default-layout/src/util/getOrderedTools.tsx
packages/@sanity/default-layout/src/util/getRegisteredTools.tsx

This ended up being _more_ than a one liner so I understand if it gets rejected / requires more discussion for a better approach!
Allows for Tools to be 
1. Conditionally rendered and 
2. Conditionally registered to the Router. 
3. 
4. This way a Tool may only appear in the Navbar and loaded if it satisfies a particular condition like current Dataset or a User's Role. 
For example:
```js
export default isTestDataset
? {
title: 'Conditional Tool',
name: 'test-conditional-tool',
component: ConditionalTool,
}
: null
```
Changes have been made to no longer assume all registered Tools are objects and will filter out any _falsy_ Tools.
In the test studio, `private` dataset:
* http://localhost:3333/playground/conditional-tool
* Should not render component
* "Conditional Tool" should not be in …

Allow `null` Tools for conditional rendering

---

dev/test-studio/parts/assetSources/noop.tsx
packages/@sanity/form-builder/src/sanity/DefaultAssetSource/DefaultSource.tsx
packages/@sanity/form-builder/src/sanity/inputs/SanityFileInput.tsx
packages/@sanity/form-builder/src/sanity/inputs/SanityImageInput.tsx

The part names and export shapes are easy to get wrong, eg the distinction between `part:@sanity/form-builder/input/file/asset-source` and `part:@sanity/form-builder/input/file/asset-sources` is very subtle. If you happen to implement `part:@sanity/form-builder/input/file/asset-sources` and it exports a single asset source, the studio crashes in spectacular ways.
This PR checks that the part exports an array, and if not warns and uses the default asset sources instead. 
I also took the liberty of fixing a ref warning/error that was being thrown when opening the default asset source while I was at it, sorry for the slightly unrelated commit.
- Added validation and warnings on incorrectly implemented asset sources part

fix(form-builder): ensure asset sources is array before usage

---

packages/@sanity/portable-text-editor/src/editor/Element.tsx

If a block is a `listItem` but doens't have a `level` set, then default the render attributes to level 1. The element itself should not be changed.
Though listItem blocks should not miss the level property, it can still happen as we have no control over the underlaying raw data.
One could discuss if this should cause a validation error with the editor and a way to resolve it (like with missing keys etc), but it makes sense to have default render attributes like this anyway.
The origin of this particular bug report seems to be an error within the Word-HTML-serializer in `@sanity/block-tools`, which fails to set level in some circumstances when pasting Word list items from Windows Word. It should be followed up in a separate patch.
Fixed a bug where list items in Portable Text without a …

Fix missing render defaults for list block elements

---

packages/@sanity/base/src/components/__workshop__/CollapseMenuStory.tsx
packages/@sanity/base/src/components/collapseMenu/CollapseMenu.tsx

The refactored `CollapseMenu` had a minor issue with the `collapseText` option. The `collapseText` option controls whether the text is to be hidden or displayed when the menu is "collapsed". In the PTE toolbar we do not want to collapse the text for the `InsertMenu` – which did not work after the refactor work. This PR adds a fix to this!
The `InsertMenu` in PTE toolbar should always show the text on buttons.
Fix `collapseText` option in `CollapseMenu`

fix(base): fix collapse text option in `CollapseMenu`

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithHotKeys.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithInsertData.ts
packages/@sanity/portable-text-editor/src/utils/__tests__/valueNormalization.test.tsx
packages/@sanity/portable-text-editor/src/utils/__tests__/values.test.ts
packages/@sanity/portable-text-editor/src/utils/patchToOperations.ts
packages/@sanity/portable-text-editor/src/utils/values.ts

When a PT value is loaded into the editor, the blocks should be normalized with a style
property. This prop is not required in the TS type or PT spec, but we should put the default
style on the in-memory value so that it's initialized and set when editing that block
with the editor (the editor should not leave it unset after the fact).
I have changed the internal util function (for converting values) to have better options in order to safely be able to set the default style (which is previously was unaware of).
Also added tests and changed an existing test to better test this.
* Fixed a bug where Portable Text block values without a style property defined would throw an error when editing that block with the PT editor.

Make sure editor content has normalized style prop

---

packages/@sanity/form-builder/src/inputs/ReferenceInput/types.ts
packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.ts

This rewrites the query we use to fetch "counterpart" ids, which makes the query run a lot faster.
Make sure that we get correct draft/published status icons when searching for keywords that only yields hits in either the draft or the published document, but not both.
Note: during development I observed the original query to be faster, but that does not seem to be the case anymore (or maybe my conclusion was wrong). Local testing revealed that for some queries it went all the way from ~850ms to ~30ms.
- Made searching for references significantly faster.

fix(form-builder): rewrite missing ids query

---

packages/@sanity/cli/package.json
packages/@sanity/cli/src/actions/versions/findSanityModuleVersions.js
packages/@sanity/cli/src/commands/upgrade/upgradeCommand.js
packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js

This PR attempts to address a number of annoyances/bugs with the `sanity upgrade` command:
1. The command currently fails when using `--tag` altogether.
- Fixed by upgrading `get-latest-version` and returning `undefined` instead of `'unknown'` when a package is not found with the given range. If we can't find it, we stick with the version as-is.
2. When using `--tag`, we incorrectly add a `^` prefix to the tag in `package.json`, unless `--save-exact` is specified.
- Fixed by using the tag or range given as-is. When using `--save-exact`, we store the actual, resolved version numbers - otherwise we just store the tag/range.
3. The command currently fails if any of the declared packages are not installed when running `sanity upgrade`
- Fixed by additional checks, try/catching and adding …

fix(cli): improve `sanity upgrade` tag/range handling

---

packages/@sanity/base/src/datastores/presence/mock-events.ts
packages/@sanity/base/src/datastores/presence/presence-store.ts

When a user profile does not exist or cannot be fetched due to insufficient permissions, we should handle the case gracefully by removing the presence session altogether. Currently, the studio crashes.
- I removed a few unused rxjs imports while I was in these files. Gardening and all that.
- Included a non-existent user ID in the mock debug presence data to make it easier to test
- Fixes a bug where the studio could crash if a user had insufficient permissions to fetch user profiles while collaborating with others

fix(base): ignore presence sessions with no user profile

---

packages/@sanity/desk-tool/package.json
packages/@sanity/desk-tool/src/panes/documentList/DocumentListPane.tsx
packages/@sanity/desk-tool/src/panes/documentList/__tests__/helpers.test.ts
packages/@sanity/desk-tool/src/panes/documentList/helpers.ts
packages/@sanity/desk-tool/src/panes/documentList/types.ts
packages/@sanity/desk-tool/src/panes/documentList/useDocumentList.ts

TL;DR: This fixes an issue where the initial load of the document list does not respect the ordering if more than 100 items are present in the list, as well as improving the ordering of datetime fields.
Long version:
We previously had a bit of an odd ordering implementation because of some internal inconsistencies and the lacking ability to order items in a case-insensitive manner. Since then, we've resolved these issues, which now means we can utilize the correct ordering.
To do so, we have to know whether or not a field that is being sorted is a string, since applying `lower()` to other types will yield `null` and break ordering of those. Since I already put this logic in place, a similar approach was implemented for datetime fields - we apply the `dateTime()` method for those (this …

fix(desk-tool): correct document list ordering on first load

---

packages/@sanity/schema/src/sanity/validation/types/image.ts

The properties `isOpaque`, `hasAlpha` and `dimensions` are automatically extracted and populated for any image asset. Specifying these will make the backend reject the request, as they are not user configurable.
Because they are listed as part of the image metadata, it is likely that users _will_ provide these, and have the upload requests fail.
This PR warns when specifying these properties, and removes them from the array of metadata before returning the compiled schema type.
That the warning makes sense from a user perspective, and that the code looks correct.
- Added a check for superfluous image metadata properties being specified

feat(schema): warn when providing superfluous image metadata props

---

packages/@sanity/export/src/export.js

Add the possibility to reference a writable stream as 'outputPath'

feat(export): allow `outputPath` to be a writable stream

---

packages/@sanity/form-builder/src/inputs/common/fileTarget/fileTarget.tsx

- I've added a test studio which allows you to directly test the use case (`dev/sanity-drag-handler-bug-14502`) which will be removed before merging into `next`
The issue was when moving items around in a PTE (adding an item to an array input), it was triggering the hovering of the array items beneath and preventing users from making any additional changes afterwards. Check video:
https://user-images.githubusercontent.com/6951139/158134688-f874f712-7974-498e-a6d5-f600793f4d84.mov
Follow the same path as shown in the video and make sure that the behavior is no longer happening. 
Also try to drag an image on the image input (inside of the PTE) and make sure that it still doesn't trigger the same bug mentioned before.
Fix drag issue with the array input with PTE items (not super sure about …

Fix dragging issue in PTE with array input

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/editor/withPortableText.ts
packages/@sanity/portable-text-editor/test/web-server/components/Editor.tsx

I noticed that the call order of the PTE plugin stack is in the reverse order of what I intended. The idea is to have the most core ones being called first and the selection emitter plugin last (as plugins may manipulate the selection).
Also updated a test with the correct prop for the placeholder (was refactored a while ago).

Change plugin callstack

---

packages/@sanity/import/src/util/ensureUniqueIds.js
packages/@sanity/import/test/import.test.js

There was confusion about duplicate IDs and the `--replace` script in the community. I added a bit more context in the error message copy when there are documents with duplicate IDs in the source file in the CLI import script. 
It's just a small change to the copy, so shouldn't be too much to test.
Improved error message for the import script when there are documents with duplicate IDs in the source file.

refactor(import): improve error message on duplicate IDs

---

packages/@sanity/language-filter/src/SelectLanguageProvider.tsx
packages/@sanity/types/parts/part.@sanity/language-filter/language-filter.d.ts

This change was already made in the i18n plugin so it can fallback to other language select implementations if i18n is not enabled for the selected schema type. This PR introduces the same behavior for the field level localization. 
When the plugin `@sanity/language-filter` is below `@sanity/document-internationalization` both implementations should still work. The language filter should show for object level translation schemas and the language switch dropdown should show for document level translations.
This change introduces support to fallback to different language select implementations when the current is not relevant

feat: Implemented fallback component for language-filter

---

packages/@sanity/form-builder/src/inputs/NumberInput.tsx
packages/@sanity/form-builder/src/inputs/__tests__/NumberInput.test.tsx

Fix issue where the number input wasn't allowing for decimal numbers (when the input is active)
Check that you can add any decimal number on a basic number schema
Fix issue where the number input wasn't allowing for decimal numbers (when the input is active)

fix(form-builder): fix the number input to accept decimal values when default

---

packages/@sanity/default-layout/src/update/changelog/ChangelogDialog.tsx
packages/@sanity/default-layout/src/update/changelog/ChangelogList.tsx

- The changelog crashes when a changelog entry is passed to the `ChangelogList` without any `changeItems` data. This PR fixes this issue by filtering out all the changelog entries that does not contain any `changeItems` before the changelog is passed to the `ChangelogList`.
- Add missing `href` to the "See full changelog on Github" link
n/a
Prevent changelog crash by filtering out entries without data to display

fix(default-layout): prevent changelog crash by filtering out entries without data to display

---

packages/@sanity/form-builder/src/inputs/files/ImageInput/ImageInput.tsx
packages/@sanity/form-builder/src/inputs/files/ImageInput/ImagePreview.styled.tsx
packages/@sanity/form-builder/src/inputs/files/ImageInput/ImagePreview.tsx
packages/@sanity/form-builder/src/inputs/files/common/ActionsMenu.tsx
packages/@sanity/form-builder/src/sanity/inputs/SanityImageInput.tsx

When loading a document that has an image input and that image is a smaller one, then the input should be of the height of the image. 
If the image is large, then it should be set to a max height that we have set.
After some discussion with Design, it was also decided to remove the resizing of the input for keeping consistency with how we do other inputs
These following states are meant to be like that when you first open a document (especially for smaller images)
| default | small image | big image (max) |
|---------|-------------|-----------|
|   <img width="600" alt="image" src="https://user-images.githubusercontent.com/6951139/158384901-483a5b1b-ef3f-4a85-8257-74019c7b42fb.png">      |       <img width="600" alt="image" src="https://user-images.githubusercontent.com/6951139/158385200-d …

fix(form-builder) fix image resizing on initial load

---

packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js

1. Dataset copy job listener hits network related timeouts for long running jobs. Today, CLI prints `There was an error copying the dataset` even when copying is in progress. This PR adds a reconnection logic non-channel error.
2. It seems event type for channel error is `channel_error` and not `channelError`, which caused CLI to skip the actual error from console.

fix(core): emit reconnect on non-channel error in dataset copy job listener

---

packages/@sanity/cli/package.json
packages/@sanity/cli/src/actions/init-project/initProject.js
packages/@sanity/cli/src/commands/init/initCommand.js

When creating new projects using the `sanity init` command, this PR will allow you to attach it directly to an organization - either using the `--organization` flag or by prompting the user. It does require an organization to already exist and that the user has "attach project" grants to it. If no organizations are found with these permissions, it skips the prompt.
Closes [sc-13493]
Supersedes #2271
That the behavior, messaging and code looks right
- Allow selecting an organization to attach new projects to during `sanity init`

feat(cli): allow selecting organization during project creation

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx

`withReact` must be the inner plugin here, as insertData and insertFragmentData are defined here and should be overwritten by the insertData plugin.
* Fix regression from ` v2.29.3` where formatting was lost when pasting HTML into the Portable Text editor.

fix(portable-text-editor): fix order of outer plugin stack

---

packages/@sanity/portable-text-editor/src/editor/plugins/createWithInsertData.ts

There was a rare bug when pasting plain texti into the PTE where it sometimes would error with "Children for text block with _key '659301731a2e' is empty".
The reason is we are normalizing the wrong value. We must normalize the portableText value here, as this is the one being validated and cause the error further down in the code.
That plain text pasting works as expected. We haven't found a way of reproducing this bug though (which content actually triggers it), only got reports. But it's very obvious what is causing it. 
Fix issue with pasting plain text into the Portable Text editor where it in some rare circumstances would error with "Children for text block is empty"

fix(portable-text-editor): fix pasted plain text normalization issue

---

packages/@sanity/core/src/actions/graphql/deployApiAction.js
packages/@sanity/core/src/commands/graphql/deployGraphQLAPICommand.js

Add `dry-run` flag as an option when running `sanity graphql deploy` 
To test:
- Running `sanity graphql deploy --dry-run` will not deploy anything
- It won't ask for the playground and, if there are conflicts, will not confirm that you want to deploy
- Running `sanity graphql deploy` will work exactly as before
- Do breaking changes to the schema. When running with the dry-run flag you should have a list of the changes and you won't be prompted about deploying with breaking changes
Add `dry-run` flag as an option when running `sanity graphql deploy`

feat(core): add `dry-run` flag

---

packages/@sanity/form-builder/src/inputs/files/common/PlaceholderText.tsx

allow for upload of items when dropping over text
Drag image over the "drop to upload image" text in an empty image input and see that it uploads the image instead of opening a new tab.
**old behavior:**
https://user-images.githubusercontent.com/6951139/161958840-0bb6dce5-533b-4698-80d3-92c34cb9f833.mov
Allow for upload of items when dropping over placeholder text

fix(form-builder): allow for upload of items when dropping over text

---

packages/@sanity/desk-tool/src/components/MissingDocumentTypesMessage.tsx

Add test-id to MissingDocumentTypesMessage. The objective of this addition is to make sure that it can be accessible from the template side.
Nothing, this is the same change as [this](https://github.com/sanity-io/sanity/pull/3209/commits/cb8cac5d7fe4b3af2ea07604ed273baa4f68feb9) commit from the main feature branch
Add test-id to MissingDocumentTypesMessage

refactor(desk-tool): add test-id to missing document type schema

---

packages/@sanity/cli/src/commands/login/loginCommand.js

Update `sanity login` docs to reflect `--sso` option.
That the help text is displayed correctly and the CLI command works.
Update docs for the `sanity login` CLI command.

chore(cli): Update login docs

---

packages/@sanity/form-builder/src/inputs/PortableText/__workshop__/editObjects/EditObjectsStory.tsx
packages/@sanity/form-builder/src/inputs/PortableText/hooks/useObjectEditData.tsx
packages/@sanity/form-builder/src/inputs/PortableText/hooks/useObjectEditFormBuilderFocus.tsx
packages/@sanity/form-builder/src/inputs/PortableText/object/EditObject.tsx
packages/@sanity/form-builder/src/inputs/PortableText/types.tsx

They way this was implemented the objectEditData object was changing on every focusPath change causing unnecessary re-renderes.
I have optimized it so that it keeps a stable object when something is edited, and null otherwise.
Also `returnToSelection` in this object is no longer needed as the selection now is kept in the editor in the background.
That object editing works as expected.
* Blocks objects
* Inline objects
* Annotations

refactor(form-builder): stabilize objectEditData object

---

packages/@sanity/cli/src/util/clientWrapper.js

The client should not send up a token when the request is specifically required to be unauthenticated.

fix: do not send in token to apiClient specifically during unauthenticated requests

---

packages/@sanity/base/src/components/Document.tsx
packages/@sanity/base/src/preview/components/SanityDefaultPreview.tsx
packages/@sanity/default-layout/src/update/PortableTextContent/PortableTextContent.tsx
packages/@sanity/default-login/src/util/getProviderLogo.js
packages/@sanity/form-builder/src/inputs/CrossDatasetReferenceInput/CrossDatasetReferencePreview.tsx
packages/@sanity/form-builder/src/inputs/common/fileTarget/utils/imageUrlToBlob.ts
packages/@sanity/form-builder/src/inputs/files/ImageInput/ImagePreview.tsx
packages/@sanity/form-builder/src/sanity/DefaultAssetSource/ConfirmMessage.tsx
packages/@sanity/imagetool/src/ImageLoader.js

This PR adds the `same-origin` referrer policy on the studio level, while opting for `strict-origin-when-cross-origin` on requests to the image CDN (`cdn.sanity.io`).
Rationale:
- When sending requests for user avatars to third-parties such as Google (`googleusercontent.com`) and GitHub (`avatars.githubusercontent.com`), we don't want to include a referrer, as this is leaking information. It can apparently also cause Google to return 403s if they get enough requests from the same origin.
- My initial thought was to add a referrer policy for these requests explicitly, but the avatars are rendered using the SVG `<image>` tag, which for some reason does not support setting a referrer policy.
- For requests to our image CDN, we want to include the origin (but not the full path) in order to …

fix(base): use same-origin referrer policy

---

packages/@sanity/default-layout/src/update/changelog/ChangelogDialog.tsx

Changes "Your Sanity Studio version 2.29.29" to "Your Sanity Studio version is 2.29.29"
Added a missing word in the current version paragraph

fix(default-layout): Add a missing word to the current version text

---

packages/@sanity/cli/src/actions/init-project/initProject.js

If the project name is for instance brown-bee, the output path would exclude the dash.
Test that running init with a project that includes a dash in the name also includes the dash in the output name. 
Fixed a bug that would not include dash in the output path when initializing a new project.

fix(cli): don't remove dash from output path

---

packages/@sanity/core/src/actions/deploy/deployAction.js

When a user with the role as "Editor" tried to run `sanity deploy`, an error message of "Hostname already taken" would be provided, even if the hostname was available. Link to issue: https://github.com/sanity-io/sanity/issues/2665. 
This commit improves the error messages provided to the user.
Instead of a hardcoded "Hostname already taken" for any `sanity deploy` error, a correct error message belonging to the error will be shown.
Run `sanity deploy` with the role as "Editor, or when providing a Studio hostname that is already taken. Make sure that correct and appropriate error message is given. 
Fixed an issue where `sanity deploy` would give "Hostname already taken" for all errors

fix(cli): show correct error msg for sanity deploy errors

---

packages/@sanity/desk-tool/src/panes/documentList/useDocumentList.ts

Restores the ability to implement a default document order in the desk structure via `S.documentList().documentOrdering()`.
Fixes #2947.
The desk structure should respect `.defaultOrdering()` when specified or fall back on the default if one is omitted.
- Restores the ability to specify a default ordering in the desk structure.

fix(desk-tool): Restore S.documentList().defaultOrdering() functionality

---

packages/@sanity/cli/src/actions/init-project/initProject.js
packages/@sanity/cli/src/actions/login/login.js
packages/@sanity/cli/src/commands/debug/printDebugInfo.js
packages/@sanity/cli/src/commands/logout/logoutCommand.js
packages/@sanity/cli/src/util/clientWrapper.js
packages/@sanity/cli/src/util/getProjectDefaults.js

PR #3250 introduced some unintended behavior changes, as parts of the CLI depended on
being able to say `requireUser: false` when using the `clientWrapper` utility, and then
checking for a `token` in its config to do conditional logic.
With the token not being part of the config after #3250, this broke. This commit changes
the checks to use a `getCliToken()` utility instead, which does not depend on the client
configuration per se, but rather the stored CLI config, as well as any environment
variable.
That the CLI still works, and that the change appears to be correct. In particular, the `sanity login`, `sanity logout`, `sanity debug` and `sanity init` commands should be tested.
- Fixed an issue where `sanity debug` would give "unauthorized" errors when used
- Fixed an issue where `sanity …

fix(cli): correct checks for cli auth token

---

packages/@sanity/core/src/commands/exec/execCommand.js

Arbitrary arguments can be added to scripts in the `sanity exec` command. This was not informed about in `sanity exec --help`. An explanation of how to add arbitrary arguments is now included in the helptext, together with an example. 
Link to issue: https://github.com/sanity-io/sanity/issues/2765
Test by running `sanity exec --help`. 
Make sure that the helptext is correct and understandable. 
Added explanation in `sanity exec --help` on how to add arbitrary arguments to the script.

fix(cli): include explanation in exec helptext of how to pass arbitrary arguments

---

packages/@sanity/base/src/presence/FieldPresence.tsx
packages/@sanity/base/src/presence/PresenceTooltip.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/DocumentPanel.tsx

This PR fixes z-index issues in `PresenceTooltip`. In order to solve these issues without adding specific z-index values – the `PresenceTooltip` is now using the `portal` attribute. However,  the positioning of the `Tooltip` was not behaving correctly when using the default portal element provided by the `PortalProvider` in `DocumentPanel`. To solve this, I added another portal element with the `__unstable_elements` to be used by the `PresenceTooltip`.
- Does the use of `__unstable_elements` make sense, or could this be solved in another way?
Fix field presence tooltip z-index issues

fix: field presence tooltip issues

---

packages/@sanity/default-layout/src/defaultLayout/DefaultLayout.tsx
packages/@sanity/default-layout/src/navbar/Navbar.tsx
packages/@sanity/default-layout/src/navbar/changelog/ChangelogContainer.tsx

This PR fixes so that focus is restored on the buttons that opens the create document and changelog dialogs when closing the dialogs. Currently, focus is lost when these dialogs are closed.
Open and close the dialogs using the keyboard, and the focus should be set back on the buttons. To make the changelog dialog button visible – set the `fakeOutdatedModule` boolean to true in `moduleStatus.ts`.
Fix focus issue on dialog buttons in navbar

fix(default-layout): restore focus on buttons when closing dialogs in navbar

---

packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js

Clean up the copy dataset out to always print the underlying job id.
https://app.shortcut.com/sanity-io/story/18215/copy-dataset-always-print-job-id-to-console
Copy output makes sense
Normal copy:
```
% sanity dataset copy foo bar
Copying dataset foo to bar...
Job jahrirhbil created
✔ Copy finished.
%
```
Detached copy:
```
% sanity dataset copy foo bar --detach
Copying dataset foo to bar...
Job jahrirhbil created
%
```
CLI copy dataset command now always prints a job id to make it easier to resume watching running jobs.

feat(cli): print copy dataset job id

---

packages/@sanity/desk-tool/src/components/DraftStatus.tsx
packages/@sanity/desk-tool/src/components/PublishedStatus.tsx
packages/@sanity/desk-tool/src/components/ReferencePreviewLink.tsx
packages/@sanity/desk-tool/src/components/confirmDeleteDialog/ConfirmDeleteDialog.tsx
packages/@sanity/desk-tool/src/components/confirmDeleteDialog/ConfirmDeleteDialogBody.styles.tsx
packages/@sanity/desk-tool/src/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx
packages/@sanity/desk-tool/src/components/confirmDeleteDialog/__tests__/index.test.tsx

This PR makes it possible to navigate to a document from the dialog that lists all referring documents to the document you are trying to delete. When you click on a document in the list, the dialog closes and the document opens in a new pane. Aside from that, this PR also adds:
- Presence + published/edited status icons to the document previews
- Some design improvements to `ConfirmDeleteDialogBody`
**How to test**
1. Navigate to a document that other documents refer to
2. Try to delete that document
3. Navigate to a document in the list of documents by clicking on it
**Implementation questions**
- I am passing an empty array to `ReferenceChildLink`:s `parentRefPath` prop. Can this cause any problems?
Make it possible to navigate to a referring document from the 'delete dialog'

feat: improve delete dialog with references

---

README.md

Two occurrences of links to https://www.sanity.io/create are changed to https://www.sanity.io/get-started + removes a link to soon to be deprecated introduction

feat: changes links for Hello Sanity

---

packages/@sanity/form-builder/src/inputs/ReferenceInput/CreateButton.tsx

The type selector list when adding a new reference did not have a size constraint. A size constraint was therefore added to aid for scrolling.
Link to issue: https://github.com/sanity-io/sanity/issues/2997 
Add a new reference and check that the list is scrollable when screensize is smaller than the list. 
Add scrolling to the list of types when adding a new reference.

fix(base): add scrolling to dropdown when adding new reference

---

dev/test-studio/schema/standard/datetime.js
packages/@sanity/validation/src/validators/dateValidator.ts

This PR fixes an issue with the date formatting in `dateValidator`, which caused the validation message shown in the tooltip to be incorrect. The format function from `date-fns` got an invalid time value. 
**Before and after**
**Schema**
```js
{
name: 'startDate',
type: 'datetime',
title: 'Start date',
validation: (Rule) => Rule.required(),
},
{
name: 'endTime',
type: 'datetime',
title: 'End date',
validation: (Rule) => Rule.min(Rule.valueOfField('startDate')).error('My error msg'),
}
```
- Review the code
- Try out the schema above 
Fix broken date validation message

fix(validation): fix broken date validation message

---

packages/@sanity/form-builder/src/inputs/common/fileTarget/fileTarget.tsx

There was a bug where when you had an array input that had a pte block with parts that could be dragged up and down where the FileTarget warning appeared when it didn't make sense.
before
https://user-images.githubusercontent.com/6951139/167607108-0d1d9a90-e37a-4738-b08c-fd859cb1102f.mov
after
https://user-images.githubusercontent.com/6951139/168052659-561c0007-361c-410a-9774-fb7dbcda0a69.mov
**Array:**
1. Go to the array test and pick Rita Test
2. Scroll all the way down to `Array of Objects in PTE`
3. Try to drag items up and down and trigger the same affect as before.
3.1. I noticed that it was easier to trigger the error when you created a new "sensory organ" and then tried to drag it up or down
Because the fix happens in a component that is affecting the image and file input, it is …

Fix(form-builder): fix hovering issue in array input with PTE block

---

packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js

Allow API to determine if the target dataset exists or if a copy job is currently in progress.
New functionality in API to determine the difference between existing dataset and running job.
Stops confusion when a copy job is in progress but the UI says "dataset name already exists".
Simply removing a check against local storage.
New functionality in API to determine the difference between existing dataset and running job.
CLI will now let the API determine the state of the target dataset.

feat(copy dataset): Allow API to determine if target dataset exists

---

packages/@sanity/cli/src/outputters/cliOutputter.js
packages/@sanity/core/package.json
packages/@sanity/core/src/actions/dataset/listDatasetCopyJobs.js
packages/@sanity/core/src/commands/dataset/listCopyDatasetJobs.js
packages/@sanity/core/src/commands/index.js
packages/@sanity/core/src/types.ts

Introduce a new cli command `sanity dataset jobs list` which prints out information about the dataset copy jobs related to the project.
This new command will help users find out the status of copy jobs without needing the job id.
[Story 18247](https://app.shortcut.com/sanity-io/story/18247/list-job-history-sanity-cli) 
This PR introduces a new outputter function `printTable` and a new dataset action `listDatasetCopyJob`.
You can test it locally by running `sanity dataset jobs list` in `/dev/test-studio` for example. 
New CLI command `sanity dataset jobs list`.

feat(cli): list dataset copy jobs

---

packages/@sanity/core/package.json
packages/@sanity/core/src/actions/dataset/listDatasetCopyJobs.js

Change the formatting of the `dataset jobs list` output.
Introduces a new npm dependency [console-table-printer](https://www.npmjs.com/package/console-table-printer)
With this library we are able to get rid of the index column and the quotes around the values in the table, which are present in the solution with `console.table()`

feat(cli): format dataset copy output with console-table-printer

---

packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js

The error method receives an event object, which doesn't have an error property nor a message property.
The message is changed to print the event data in case of a failed job.

fix(cli): throw a better error message in case of a failed dataset copy job

---

packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js

This has been added after investigations into long processing times. Copying with history is slow.
This information is an alternative to changing the default settings and breaking backwards compatibility.
New output. Run copy process with and without flag to see output.
```sanity dataset copy production backup-1```
```sanity dataset copy production backup-2 --skip-history```
N/A

chore(cli): add output to inform that `--skip-history` flag exists

---

packages/sanity/src/presence/DocumentPreviewPresence.tsx
packages/sanity/src/studio/components/navbar/Navbar.tsx

This PR adds some UI improvements.
**Fix Tooltip scheme on document presence**
**Close NavDrawer when changing workspace**
**Add tooltip to workspace menu button**

feat: ui issues

---

packages/@sanity/types/src/schema/types.ts

`calendarTodayLabel` appears inconsistently in the date and datetime documentation. Not sure it truly does anything #3354 but adding it to types regardless.
https://www.sanity.io/docs/date-type
https://www.sanity.io/docs/datetime-type

adding calendarTodayLabel

---

packages/@sanity/types/src/schema/types.ts

`name` should be in the sort ordering: https://www.sanity.io/docs/sort-orders

adding name to SortOrdering type

---

packages/sanity/src/form/inputs/PortableText/Compositor.tsx
packages/sanity/src/form/inputs/PortableText/PortableTextInput.tsx
packages/sanity/src/form/inputs/PortableText/_helpers.ts
packages/sanity/src/form/inputs/PortableText/hooks/useMemberValidation.tsx
packages/sanity/src/form/inputs/PortableText/hooks/useScrollToFocusFromOutside.tsx
packages/sanity/src/form/inputs/PortableText/object/BlockObject.tsx
packages/sanity/src/form/inputs/PortableText/object/InlineObject.tsx
packages/sanity/src/form/inputs/PortableText/object/helpers.ts
packages/sanity/src/form/inputs/PortableText/object/renderers/ObjectEditModal.tsx
packages/sanity/src/form/inputs/PortableText/text/Annotation.tsx
packages/sanity/src/form/inputs/PortableText/text/TextBlock.tsx

This PR makes it so the Portable Text input treats inline objects, annotations, and custom block objects differently:
- Inline objects open in a popover by default.
- Annotations open in a popover by default.
- Custom block objects open in a dialog by default,
Make sure opening and closing of inline objects, annotations and custom block objects works as expected.

refactor(sanity): make inline objects and annotations open in popover by default

---

packages/sanity/src/form/inputs/PortableText/Editor.tsx
packages/sanity/src/form/inputs/PortableText/PortableTextInput.tsx
packages/sanity/src/form/inputs/PortableText/hooks/useScrollToFocusFromOutside.tsx
packages/sanity/src/form/inputs/PortableText/object/renderers/ObjectEditModal.tsx
packages/sanity/src/form/inputs/PortableText/text/TextBlock.styles.ts
packages/sanity/src/form/inputs/PortableText/toolbar/Toolbar.tsx

Various smaller fixes for the PT input. Most importantly [simplify scrollToFocus hook](https://github.com/sanity-io/sanity/pull/3363/commits/97b72acd4449e085b8680c0fd5546e5f412de62a), which will make this hook more reliable and simpler after we got the pt member kind property.

Smaller PT-input improvements

---

packages/@sanity/cli/src/types.ts
packages/sanity/src/cli/actions/graphql/deployApiAction.ts
packages/sanity/src/cli/commands/graphql/deployGraphQLAPICommand.ts

When defining multiple GraphQL APIs, you might want to only deploy certain defined APIs instead of all of them (see https://github.com/sanity-io/sanity/discussions/3344)
This PR allows you to specify an `id` for each API, and then reference it using the `--api <api-id>` flag when running `sanity graphql deploy`.
It also updates the help text for this command, which didn't match the command in v3.
- That the changes makes sense
- That it works. Example `sanity.cli.ts`:
```ts
import {createCliConfig} from 'sanity/cli'
export default createCliConfig({
api: {
projectId: 'ppsg7ml5',
dataset: 'blog',
},
graphql: [
{id: 'ancient', tag: 'ancient', generation: 'gen1'},
{id: 'default', tag: 'default', generation: 'gen3'},
],
})
```
- Allow specifying a specific GraphQL API to deploy using the new …

feat(cli): allow specifying --api to filter which APIs to deploy

---

packages/sanity/bin/sanity

Fixing [#3336](https://github.com/sanity-io/sanity/issues/3336)!
[PNPM creates a shim .bin file of its own](https://dev.to/elpddev/debug-jest-spec-in-vscode-error-missing-after-argument-list-1p3b) to work around symlink issues. This results in a deeply nested set of directories like so: `node_modules/.pnpm/sanity@3.0.0-dev-preview.9_xxoq2orp2zssb7i4726r2xjrpu/node_modules/sanity/node_modules/.bin/sanity`;
The file in node_modules/.bin/sanity seems to not work from inside this deeply nested folder, we want to run the one that's a few directories up. 
- Not sure if you prefer a different syntax on path.join (no trailing slash, separate `'..', '..'` etc).
- Wondering if there's a better way than hard-coding in the .pnpm check?
- Standard package testing works for me!
Fix issue …

Add .pnpm conditional to expectedPath

---

packages/sanity/src/studio/AuthBoundary.tsx
packages/sanity/src/studio/StudioProvider.tsx
packages/sanity/src/studio/screens/AuthenticateScreen.tsx
packages/sanity/src/studio/screens/NotAuthenticatedScreen.tsx
packages/sanity/src/studio/screens/index.ts

This PR adds a screen that is displayed when a user is signed in to a studio without any roles (i.e. is unauthorized). 
The previous `NotAuthenticatedScreen`, which handled authorization, has been renamed to `AuthenticateScreen` – and the new screen added in this PR is now called `NotAuthenticatedScreen` instead.

feat(studio): add not authenticated screen

---

packages/@sanity/portable-text-editor/package.json

Previous used version of slate-react had problems with Cromium > 100, reporting no beforeInput support.
Upgrade dependencies for the Portable Text Editor, fixing issues where Chrome would be reported as missing `beforeInput`- support after Chrome went above version 100. This broke spellchecking in Chrome and degraded performance.

chore(portable-text-editor): upgrade to latest slate and slate-react

---

packages/@sanity/portable-text-editor/src/editor/PortableTextEditor.tsx
packages/@sanity/portable-text-editor/src/editor/plugins/createWithMaxBlocks.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPatches.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithUndoRedo.ts
packages/@sanity/portable-text-editor/src/editor/withPortableText.ts
packages/@sanity/portable-text-editor/src/types/editor.ts

There was a undetected bug where the `readOnly` and `maxBlocks` properties of the editor were only set at contruction time on the slate editor instance. This will add support for the editor's plugin chain to have always use current values from the outside props.
This was the cause of the heisen-bug where the patch plugin suddenly stopped producing patches. It got stuck with an old `readOnly` value. With the roles support of the studio, the change of these props have become more common and the problem has surfaced to some users. Some of those clients have been running this branch for a while reporting that they no longer see this issue.
This will also fix https://github.com/sanity-io/sanity/issues/3184 which is related.
Fix a rare occurring bug in the Portable Text Editor where it would …

fix(portable-text-editor): fix instance props support for readOnly and maxBlocks

---

dev/test-studio/parts/dashboardConfig.js
packages/@sanity/dashboard/src/dashboardConfig.js
packages/@sanity/dashboard/src/widgets/sanityTutorials/SanityTutorials.js
packages/@sanity/dashboard/src/widgets/sanityTutorials/Tutorial.js

- Adds support for sections of videos in dashboard feeds, and changes the layout from a horizontally scrollable dashboard widget to a full width grid.
- Make sure layout is working and feeds are rendered without breakage.
- Updated UI of dashboard feeds

feat(dashboard): add sections to dashboard feed

---

packages/@sanity/base/src/components/formField/FormFieldHeaderText.tsx
packages/@sanity/base/src/components/formField/FormFieldSet.tsx

Link to [shortcut task](https://app.shortcut.com/sanity-io/story/21725/cropped-text-in-validation-tooltips) 
The tooltip component for the formfields did not have a proper placement. By adding the `portal` prop to the two formfield components, the tooltip appears at the front of all other components on the page. 
Add validation to a form field and include a warning/error/info. Validate that the UI for the tooltip is as expected. 
Fixed UI for tooltip component for validation of fields.

Added portal prop to the formfield

---

packages/sanity/src/datastores/authStore/createAuthStore.ts

Fixes an issue where the v3 studio did not specify a request tag prefix, so requests would not have the `sanity.studio` prefix for tags.
That requests from the studio have the `sanity.studio` prefix on their `tag` query parameter.
- Fixed an issue where requests from the studio would not have the `sanity.studio` prefix

fix(datastores): add missing request tag prefix

---

packages/@sanity/export/src/AssetHandler.js

Swap the logic for validating assets to prefer sha1 validation. This is to address an issue where the md5 of an asset is being misreported.
Dataset export works

feat(export): check sha1 hash first

---

packages/@sanity/export/src/AssetHandler.js

Allows export hash check to succeed if either sha1 or md5 are the same.
Dataset export works

fix(export): allow either hash check

---

package.json
packages/@sanity/util/package.json
packages/@sanity/vision/package.json
packages/@sanity/vision/src/util/calendarDate.js

- Upgrades moment dependency to latest version to silence reports of [this vulnerability](https://security.snyk.io/vuln/SNYK-JS-MOMENT-2944238). To be clear: unless developers of a sanity studio manually craft really long expressions and put into their datetime field formatting configuration, this is not an issue, but this will help prevent noise.
- Removes unused moment dependency from `@sanity/vision`
- Normalizes `@sanity/client` version to a single version across the monorepo to suppress a warning from lerna
- That studio still works, and in particular: date/datetime fields with custom format specified
- Upgraded moment.js dependency to latest version

chore: upgrade moment to latest version

---

packages/@sanity/core/package.json

Upgrade terser to the latest version to work around a reported [vulnerability](https://security.snyk.io/vuln/SNYK-JS-TERSER-2806366).
That `sanity deploy` works as expected and still minifies the bundle.
- Upgraded terser dependency

chore(core): upgrade terser

---

packages/sanity/src/desk/panes/document/statusBar/sparkline/ReviewChangesButton/AnimatedStatusIcon.tsx

Framer motion gives a warning saying it cannot animate string values (`strokeDashoffset`). This PR changes the prop from a string to a number, which prevents this warning from being printed.
- That the animated syncing/saved indicator still looks as it is supposed to
- Silenced a warning about animating a string property

fix(desk): silence warning about animating stroke dash offset

---

packages/sanity/package.json

Projects that uses ES Modules and typescript (eg declares `type: 'module'` in `package.json`), as well as has typescript settings of `"module": "ESNext"` and `"moduleResolution": "Node16"` (not sure if _all_ of these are needed, but you get the point) will currently fail to resolve type definitions when importing from the `sanity` package. This is because the `exports` field is used, and resolves to the ESM build, which does not have a sibling `.d.ts` file. By declaring a `types` entry for each export, it is able to resolve it as expected.  
Note that the types entry must be first, as noted here: https://www.typescriptlang.org/docs/handbook/esm-node.html
That the included patch does not have unintended side effects.
- Make typescript definitions for the `sanity` package work in TypeScript …

fix: define types path for exports

---

packages/@sanity/desk-tool/src/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx

This fixes the message in the confirm delete dialog when unpublishing.
1. Go to any published document
2. Select the Unpublish action
3. It should read _Are you sure you want to unpublish <document title>?_
- Fixed the message in the confirm delete dialog when unpublishing

fix(desk-tool): show correct action message in unpublish dialog

---

dev/test-studio/package.json
packages/@sanity/portable-text-editor/package.json
packages/@sanity/portable-text-editor/src/editor/Element.tsx
packages/@sanity/portable-text-editor/src/editor/Leaf.tsx
packages/@sanity/server/package.json
yarn.lock

This PR upgrades vite to v3. While there are not necessarily any _critical_ changes, I feel it is best to keep up to date as often as we can with core dependencies.
Mostly it was a drop-in replacement, but esbuild gave me some hard to understand warnings that seems to be caused by the JSX transformer:
```
warning: Top - level "this" will be replaced with undefined since this file is an ECMAScript module
223|      key: element._key,
224|      className: className,
225|      __self: this,
|              ^
226|      __source: {
227|        fileName: _jsxFileName,
```
I eventually tracked it down to being statements like this:
```tsx
<span {...attributes} key={key}>
```
...which for some reason went away when doing it like this (key before spread):
```tsx
<span key={key} {...attributes}>
``` …

chore: upgrade vite to v3

---

packages/@sanity/dashboard/src/widgets/sanityTutorials/SanityTutorials.js

This adds a banner at the top of the sanity tutorials videos with a CTA to our docs site.
- Start the test studio and make sure everything works as it should in the dashboard with the banner/
n/a

feat(dashboard): add docs banner to sanity tutorials widget

---

packages/@sanity/cli/templates/getting-started-pets/components/views/HumanPreview.jsx
packages/@sanity/cli/templates/getting-started-pets/components/views/ProductPreview.jsx
packages/@sanity/cli/templates/getting-started-pets/style.css

I noticed a couple spelling issues within the documentation when going through the getting started steps!

fix: `getting-started-pets` package spelling corrections

---

packages/@sanity/dashboard/src/widgets/sanityTutorials/SanityTutorials.js
packages/@sanity/dashboard/src/widgets/sanityTutorials/Tutorial.js

The tutorials dashboard widget prints two warnings currently - one caused by missing keys for feed items (it was using `.id` instead of `._id`, and one about a required proptype that was missing.
The widget seems to work just fine without the prop, and as we're moving away from the prop-types module I figured I might as well just remove it from use in this component.
- Fixed a few warnings being emitted from the tutorials dashboard widget

fix(dashboard): use correct property for feed item keys

---

packages/@sanity/structure/src/DocumentList.ts

When resolving the child of a document pane, it tries to either use the defined schema type for that pane to open a document pane as a child, or falls back to inferring it from the query. However, in some cases a type is not inferable from the query, in which case we fall back to resolving the type from the document ID. This can  _still_ fail however, in the case where you are creating a _new_ document - the document does not exist and as such you don't know which type to use, and will get an error. In many cases however, we explicitly tell the pane which _template_ to use - and a template has an associated schema type.
This PR checks for the presence of a template parameter, looks it up and uses its schema type.
That document panes still work - both single-document type panes, panes with …

fix(structure): resolve schema type from template if possible

---

packages/@sanity/desk-tool/src/components/confirmDeleteDialog/useReferringDocuments.ts
packages/@sanity/desk-tool/src/panes/document/DocumentPaneProvider.tsx

Shortcut link: https://app.shortcut.com/sanity-io/story/22548/v2-30-3-new-reference-check-throws-repeated-404s-on-draft-docs-without-published-version-new-docs 
In order to avoid firing `404s `every 5 seconds, a prop was added to the `useReferringDocuments` hook.
The default is now 5 seconds.  
When the hook is used for a document pane, the interval is set to 1 minute. This means that the `404` will be thrown every minute. The error is still valid - the document that is not published should get this error. Once the document is published, the error will disappear. 
Create a new reference without publishing. 
Reference this unpublished document from another document. Open the unpublished document and check the console for errors. 
bug(desk-tool): add a pollInterval in useReferringDocuments …

bug(desk-tool): add a pollInterval in useReferringDocuments hook to avoid spamming 404 in documentPane

---

package.json
packages/@sanity/cli/package.json
packages/@sanity/import-cli/package.json
packages/@sanity/import/package.json
packages/@sanity/types/package.json
packages/@sanity/validation/package.json
packages/sanity/package.json
packages/sanity/src/datastores/document/document-pair/operations/commit.ts
packages/sanity/src/datastores/document/document-pair/operations/delete.ts
packages/sanity/src/datastores/document/document-pair/operations/discardChanges.ts
packages/sanity/src/datastores/document/document-pair/operations/duplicate.ts
packages/sanity/src/datastores/document/document-pair/operations/patch.ts
packages/sanity/src/datastores/document/document-pair/operations/publish.test.ts
packages/sanity/src/datastores/document/document-pair/operations/publish.ts
packages/sanity/src/datastores/document/document-pair/operations/restore.ts
packages/sanity/src/datastores/document/document-pair/operations/unpublish.ts
yarn.lock

Upgrades the client to the latest version, and fixes a few typing errors that were indicating a promise was returned when in actuality an observable was produced.
That the studio still works - in particular all the document actions.
- Upgraded the Sanity client to v3.3.3

chore: upgrade `@sanity/client` to v3.3.3

---

packages/@sanity/dashboard/src/widgets/sanityTutorials/SanityTutorials.js

Fixed typos in the dashboard banner. 
The link to docs now open in a new pane. 
Check the link to the docs and the text in the banner. 
- Fixed typo in dashboard banner

bug(dashboard): fix typo in banner, open link in new pane

---

packages/sanity/src/form/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx

This PR fixes so that the array items are rendered in a grid layout when the schema type has `options: { layout: 'grid'}`.
fix(form): fix broken array grid layout

fix(form): broken array grid layout

---

packages/@sanity/server/src/renderDocument.ts

When using a custom `_document.js` file, the esbuild loader did not handle JSX. This was made worse by the importer silently swallowing all errors, instead of just the "not found" ones.
This PR tells esbuild to use the tsx loader even for .js files, and will throw an error on any error that is not "module not found" - eg syntax errors and such.
- Custom `_document.js`/`_document.tsx` files work as expected
- Fixed a bug where a custom `_document.js` with JSX would not work, and syntax errors would silently be swallowed

fix(server): handle jsx in `.js` files

---

packages/@sanity/desk-tool/src/actions/PublishAction.tsx
packages/@sanity/desk-tool/src/components/pane/PaneHeader.tsx
packages/@sanity/desk-tool/src/components/paneItem/ReferencedDocHeading.tsx
packages/@sanity/desk-tool/src/components/paneItem/ReferencedDocTooltip.tsx
packages/@sanity/desk-tool/src/panes/document/DocumentPane.tsx
packages/@sanity/desk-tool/src/panes/document/DocumentPaneContext.ts
packages/@sanity/desk-tool/src/panes/document/DocumentPaneProvider.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/header/DocumentPanelHeader.tsx
packages/@sanity/desk-tool/src/panes/document/statusBar/DocumentStatusBarActions.tsx

Implemented references indicator design changes. 
Link to story: https://app.shortcut.com/sanity-io/story/22638/indicate-a-referenced-document-part-2 
The tooltip now include a reference count, stating how many documents reference the document that is viewed. The reference count is also shown in the one-time popover, stating how many documents will be affected if the document is edited.
The dialog for the PublishAction button that appeared when publishing a referenced document is also removed after user feedback. 
A referenced document - the tooltip on link icon next to text and the popover text and "Learn more"-button.
feat(base): Reference indicators now include a reference count for affected documents

feat(desk): add reference count and learn more link to references indication

---

packages/sanity/src/form/inputs/files/ImageInput/ImageActionsMenu.tsx

Enable keyboard navigation on image actions menu + restore focus on button when closing on escape
Use the image actions menu with keyboard
fix(form): a11y issues with image actions menu

fix(form): a11y issues with image actions menu

---

packages/@sanity/types/src/mutations/types.ts

According to [documentation](https://www.sanity.io/docs/js-client#delete-documents), a `params` property is supported when deleting documents by query: 
```
client.delete({ query: "GROQ query", params: { key: value } })
```
I assume the same holds for patching/updating documents by query?
This PR adds the property to the `MutationSelection` type, so that TypeScript will also acknowledge it.
* Check that deleting documents by query with params work as intended: `client.delete({
query: "*[ _type == $testType ]",
params: { testType: "test" }
})
`
* Check that patching documents by query with params work as intended: `client.patch({
query: "*[ _type == $testType ]",
params: { testType: "test" }
}).set('test', 'test').commit()
`
* chore(types): add params property to MutationSelection …

Add `params` property to `MutationSelection` interface

---

packages/sanity/src/form/studio/inputResolver/helpers.ts
packages/sanity/src/form/studio/inputResolver/inputResolver.tsx

This PR adds logic to determine when a field should have the "level UI" (that is, padding to left + border). 
Do the level UI appear on places where it is expected? (Tip: compare with v2)
feat(form): add correct field level UI

 feat(form): add correct field level UI

---

packages/@sanity/desk-tool/src/components/paneItem/ReferencedDocHeading.tsx
packages/@sanity/desk-tool/src/components/paneItem/ReferencedDocTooltip.tsx

Shortcut link: https://app.shortcut.com/sanity-io/story/22722/document-title-ellipsis-broken
Fixed the bug where the document title ellipsis did not work for referenced documents.
Write a long title for a document. Make sure the title and icons in the header works as expected.
fix(desk): add ellipsis for referenced document title

fix(desk): referenced document title ellipsis

---

packages/@sanity/schema/src/legacy/types/blocks/block.ts
packages/@sanity/schema/src/legacy/types/blocks/span.ts
packages/@sanity/schema/src/legacy/types/boolean.ts
packages/@sanity/schema/src/legacy/types/document.ts
packages/@sanity/schema/src/legacy/types/file.ts
packages/@sanity/schema/src/legacy/types/image.ts
packages/@sanity/schema/src/legacy/types/number.ts
packages/@sanity/schema/src/legacy/types/object.ts
packages/@sanity/schema/src/legacy/types/reference.ts
packages/@sanity/schema/src/legacy/types/string.ts
packages/@sanity/schema/src/legacy/types/text.ts
packages/sanity/src/form/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx
packages/sanity/src/schema/helpers.ts

When the schema type used for array members did not have a title, it displayed `Edit undefined` in the header. This PR makes it look up the most specific title in the schema type chain, falling back to the schema type name when unable to go any further. 
I also investigated a bit and it looks like `file` and `image` etc never had a title. Was this intentional? I've added titles to all the base schema types - maybe _that_ is the real fix here? Let me know if that is a bad idea, or if we should drop the title lookup helper and just stick with the titles in the schema definitions 👍  
Before:
After:
- Fixed a bug where object modals would sometimes display "Edit undefined" in the header

fix(form): use most specific title for schema type in modal header

---

packages/@sanity/import/package.json
packages/sanity/package.json
packages/sanity/src/form/inputs/files/FileInput/FileInput.tsx
packages/sanity/src/form/inputs/files/FileInput/InvalidFileWarning.tsx
packages/sanity/src/form/inputs/files/ImageInput/ImageInput.tsx
packages/sanity/src/form/inputs/files/ImageInput/InvalidImageWarning.tsx
packages/sanity/src/form/inputs/files/common/ActionsMenu.tsx
yarn.lock

When an incorrect value is set for an image/file `asset` field, the inputs crash because it expects the shape to be correct. This PR upgrades the asset utils in order to use some looser type checks, and uses these to ensure the image asset is correct. If not, it will show a warning with a reset option, which unset the `asset` field. On images, it will also unset `crop` and `hotspot` since they are likely invalid for whatever image is selected next.
I also made the action menu for file/images more forgiving of a missing `copyUrl`/`downloadUrl` - automatically hiding these options if the values are undefined.
Screenshot:
- Change an image field to an object, and include an `asset` field which is a reference to something that is not an image
- Use the input to select a non-image reference
- …

fix(form): check for invalid image/file values, provide reset option

---

.gitignore
packages/@sanity/block-tools/src/HtmlDeserializer/rules/html.ts
packages/@sanity/block-tools/test/tests/HtmlDeserializer/lists/input.html
packages/@sanity/block-tools/test/tests/HtmlDeserializer/lists/output.json

This fixes a bug where p-tags (and other block elements) inside li elements where incorrectly hoisted out of the li element.
With this change blocks are ignored, and block children are added directly to the listItem instead.
Testcase should cover the changes introduced; from the code comment it seems like this usecase was already accounted for, but was checking element tag name instead of parent tag name.
[@sanity/block-tools] Blocks inside list items are now ignored. Child element will be added directly to the list item instead.

fix: ignore blocks inside list items

---

packages/sanity/src/form/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx
packages/sanity/src/form/inputs/arrays/ArrayOfObjectsInput/item/ArrayItem.tsx

This change introduces an layout option to the array item component and passes it from the array schema type where it's configured
Make sure arrays configured with grid layout still works, and that the regression introduced by the previous change is fixed
N/A

fix(form): pass layout option from array input

---

packages/@sanity/cli/templates/getting-started-dashboard/components/views/components/gridList.jsx
packages/@sanity/cli/templates/getting-started-pets/components/views/components/gridList.jsx

This fixes an issue where human previews will crash when a referenced pet has a draft with no picture attached.
n/a

fix(cli): fix asset check in human previews

---

packages/sanity/src/form/inputs/ObjectInput/fieldGroups/FieldGroupTabs.tsx
packages/sanity/src/form/inputs/ObjectInput/fieldGroups/GroupTab.tsx
packages/sanity/src/form/store/formState.ts

This PR fixes so that the icon configured in the schema for a field group is displayed. Example:
```js
groups: [
{
name: 'group',
title: 'Group',
icon: CogIcon
},
]
```
Make sure that the icon configured for a field group is displayed on the group tab.
fix(form): missing icon in field group

fix(form): missing icon in field group

---

dev/test-studio/schema/standard/arrays.tsx
packages/@sanity/types/src/schema/types.ts
packages/sanity/src/form/inputs/arrays/OptionsArrayInput/OptionsArrayInput.tsx
packages/sanity/src/form/studio/inputResolver/helpers.ts

This PR fixes:
- Render tags input when an array has `options: {layout: 'tags'}`
- Update form field UI for tags array (no border or padding to the left of the field)
- Make it possible to have strings in addition to an object with `title` and `value` in `options.list`. E.g:
```
options: {
list: [{title: 'Title', value: 'value'}, 'Hello'],
}
```
Test that the above mentioned fixes works
fix: string array issues

fix: string array issues

---

packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx
packages/@sanity/form-builder/src/inputs/ObjectInput/fieldGroups/FieldGroupTabs.tsx

This change fixes the console warning _The input component for type "fieldGroups" has no associated ref element..._ for document types with field groups.
The bug is that that all inputs need to set the ref to an actual element, but in the case of field groups we didn't forward the ref anywhere. The ref is now set on the tab list.
- Go to test studio and document type with field groups
- See that console warning _The input component for type "fieldGroups" has no associated ref element...._ is not triggered any more
- Fixed a bug where we didn't forward the ref for object input with tabs, causing console warnings

fix(form-builder): make sure to forward ref for object input with tabs

---

packages/@sanity/schema/src/sanity/validation/types/array.ts
packages/sanity/src/form/studio/inputResolver/resolveArrayInput.ts

This PR adds:
- Schema validation when using `layout: 'tags'` together with a `list` with predefined values
- Renders the `TagsArrayInput` before `OptionsArray`. I think this is more expected behaviour.
- Configure an array with tags layout + a list in `options` and the warning should appear in the list of configuration issues 
- Does the copy make sense?
feat: add array schema validation when using tags layout with list

feat: add array schema validation when using tags layout with list

---

packages/@sanity/server/src/vite/plugin-sanity-build-entries.ts

Fixes a bug that is preventing the usage of URL imports atm.
Link to reproduction: https://github.com/sanity-io/themer/pull/37
If you add an URL import to `sanity.config.ts`:
```ts
import { createConfig } from 'sanity'
import { theme } from 'https://themer.sanity.build/api/hues?preset=verdant'
export default createConfig({
// ...
theme,
})
```
You'll get this error:
```bash
TypeError: Cannot read properties of undefined (reading 'viteMetadata')
--
at Object.generateBundle (/node_modules/@sanity/server/lib/vite/plugin-sanity-build-entries.js:78:35)
at /node_modules/rollup/dist/es/shared/rollup.js:22695:37
```
The reason it happens is Vite doesn't populate `viteMetadata` on its `entryFiles.imports` for URL imports. 
This makes sense, as they're evaluated at runtime instead of at build time …

fix: allow URL imports in `sanity.config.ts`

---

package.json
packages/@sanity/portable-text-editor/tsconfig.json
scripts/pkg-utils/bundle/rollup/options.ts
yarn.lock

`pkg-utils bundle` will now respect the `target` defined in `tsconfig.json`. If not defined, it will default to `ESNext`.
- Make sure that `@sanity/portable-text-editor` bundles files compatible with ES2019.
- Make sure that other packages build with the desired ES target.
n/a

chore(pkg-utils): support tsconfig build target

---

packages/@sanity/structure/src/DocumentList.ts

Before you could chain more methods after calling `initialValueTemplates()` on `S.documentList()`, but this seems to have broken at some point.
Example:
```js
S.documentList()
.title("Docs")
.menuItems([])
.menuItemGroups([])
.initialValueTemplates([])
.defaultOrdering([{ field: "title", direction: "asc" }])
```
Here `.defaultOrdering()` would reset `initialValueTemplates` because `.clone()` was called under the hood, and a new `DocumentListBuilder` instance was created. However `initialValueTemplatesSpecified` was only set in the constructor, and at that point the spec was not passed yet.
This fixes the 
- `initialValueTemplatesSpecified` is protected. Is the change in this PR the best way to do it? We could pass the spec in the constructor instead, but the current typing doesn't allow …

fix(structure): fix regression with initialValueTemplates being overridden

---

packages/sanity/src/desk/structureBuilder/ListItem.ts

This PR fixes a problem where a default structure does not show any icons.
1. Start the `clean-studio` with `yarn dev:clean-studio`
2. Go to `examples/clean-studio` and add a schema to `sanity.config.ts`:
```js
schema: {
types: [
{
title: 'Document',
name: 'doc',
icon: CogIcon,
fields: [
{
name: 'string',
title: 'String',
},
],
},
],
}
```
3. The icon should be displayed.
fix(desk): missing icon in default structure

fix(desk): missing icon in default structure

---

packages/sanity/src/config/prepareConfig.ts

The `logo` config property was not getting passed on when resolving the configuration. This PR fixes this, and pre-renders (well... computes) it at the config level, so it is ever so slightly faster to render.
That the `logo` property can be configured and is respected by the studio. The test-studio should now show "Test Studio™" instead of just "Test Studio", but in theory you should be able to put something else here. An SVG or an image etc.
- Fixed an issue where a configured `logo` component for a workspace would not be respected

fix(config): include logo in resolved studio config

---

packages/sanity/src/form/studio/defaults.ts
packages/sanity/src/form/studio/inputResolver/inputResolver.tsx

This PR fixes so that `SanityPreview` is always returned from `defaultResolvePreviewComponent` in `inputResolver`. This change is made because `SanityPreview` [takes care of resolving what preview component to render](https://github.com/sanity-io/sanity/blob/v3/packages/sanity/src/preview/components/SanityPreview.tsx#L25), but also performs some logic that is important for a preview component, logic that was missed before when we conditionally returned `components.preview`.
n/a
fix(form): update resolving of preview component

fix(form): update resolving of preview component

---

packages/@sanity/base/src/components/previews/general/MediaPreview.tsx
packages/@sanity/cli/templates/getting-started-dashboard/components/views/components/metadataList.jsx
packages/@sanity/cli/templates/getting-started-pets/components/views/components/metadataList.jsx
packages/@sanity/desk-tool/src/components/paneItem/ReferencedDocTooltip.tsx
packages/@sanity/desk-tool/src/panes/document/statusBar/sparkline/PublishStatus.tsx
packages/@sanity/desk-tool/src/panes/document/statusBar/sparkline/ReviewChangesButton/ReviewChangesButton.tsx
packages/@sanity/field/src/diff/components/DiffTooltip.tsx
packages/@sanity/form-builder/src/inputs/CrossDatasetReferenceInput/CrossDatasetReferencePreview.tsx
packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/RowItem.tsx
packages/@sanity/form-builder/src/inputs/arrays/common/ArrayFunctions.tsx

Link to shortcut ticket: https://app.shortcut.com/sanity-io/story/22481/sanity-ui-tooltip-text-contrast-not-matching-a11y-requirements
Removed the muted prop in text in every tooltip in the studio to increase contrast of text in a tooltip
Test all the tooltips and make sure that the text is no longer black.
As stated in the shortcut ticket: the hotkeys will **not** be black and this is intentional 
fix: change text color in tooltips from gray to black

fix: remove muted prop from text inside every tooltip in the studio

---

packages/@sanity/base/package.json
packages/@sanity/base/src/preview/components/SanityDefaultPreview.tsx
packages/@sanity/default-layout/package.json
packages/@sanity/field/package.json
packages/@sanity/field/src/types/file/diff/FileFieldDiff.tsx
packages/@sanity/field/src/types/image/diff/ImagePreview.tsx
packages/@sanity/form-builder/package.json
packages/@sanity/form-builder/src/inputs/files/FileInput/FileInput.tsx
packages/@sanity/form-builder/src/inputs/files/FileInput/InvalidFileWarning.tsx
packages/@sanity/form-builder/src/inputs/files/ImageInput/ImageInput.tsx
packages/@sanity/form-builder/src/inputs/files/ImageInput/InvalidImageWarning.tsx
packages/@sanity/import/package.json

(Backport of v3 fix in [#3502](https://github.com/sanity-io/sanity/pull/3502))
> When an incorrect value is set for an image/file `asset` field, the inputs crash because it expects the shape to be correct. This PR upgrades the asset utils in order to use some looser type checks, and uses these to ensure the image asset is correct. If not, it will show a warning with a reset option, which unset the `asset` field. On images, it will also unset `crop` and `hotspot` since they are likely invalid for whatever image is selected next.
> I also made the action menu for file/images more forgiving of a missing `copyUrl`/`downloadUrl` - automatically hiding these options if the values are undefined.
In addition to the v3 fix I have updated the diff previews to handle invalid values.
Updated image …

fix(form-builder): check for invalid image/file values, provide reset option

---

packages/sanity/src/preview/utils/prepareForPreview.ts

Consider the following type:
```
{
name: 'tone',
title: 'Tone',
options: {
list: [
{value: 'default', title: 'Default'},
{value: 'primary', title: 'Primary'},
{value: 'positive', title: 'Positive'},
{value: 'caution', title: 'Caution'},
{value: 'critical', title: 'Critical'},
],
},
}
```
With the current code, the `options.list.title` is selected as value for the preview, which seems like a bug.
This will return the value instead, as it is in the actual data.

String of options must return option value for the preview

---

packages/sanity/src/form/store/formState.ts

This PR fixes an issue with read only in fieldsets. Looking at the schema example below – `myString` should be read only.
```ts
{
name: 'myDocument',
fieldsets: [
{
name: 'myFieldset',
readOnly: true,
}
],
fields: [
{
name: 'myString',
fieldset: 'myFieldset'
}
]
}
```
Make sure that fields inside a fieldset respect the fieldsets `readOnly` value.
fix(form): read only fieldsets

fix(form): read only fieldsets

---

packages/@sanity/cli/src/actions/init-project/initProject.js
packages/@sanity/cli/src/commands/codemod/codemodCommand.js
packages/@sanity/cli/src/commands/debug/debugCommand.js
packages/@sanity/cli/src/commands/init/initCommand.js
packages/@sanity/cli/src/commands/login/loginCommand.js
packages/@sanity/cli/src/commands/projects/listProjectsCommand.js
packages/@sanity/cli/src/commands/upgrade/upgradeCommand.js
packages/@sanity/cli/src/util/generateCommandsDocumentation.js
packages/@sanity/cli/src/util/isNpx.js

This adds `npx` detection to the CLI, so all the help text will show the correct version of commands based on if you are using npx or not.
If running with npx it will look like this:
If running the `sanity` command as normal, it will look like this:
After doing research on the canonical way to detect `npx`, I ended up with a naive approach that checks if the folder that npx uses (`_npx`) is listed in `process.argv` or `process.env.npm_lifecycle_event` is `npx`. I have observed either when when testing.
- Test that all the commands display either versions depending on if you use `npx` or not
- CLI help text will now prefix commands with `npx @sanity/cli` instead of `sanity` if you are using `npx`

feat(cli): prefix commands if using npx

---

packages/@sanity/desk-tool/src/components/pane/PaneHeader.tsx

There is no reason for that title to be focusable. It’s not an interactive element and should not have a `tabindex` attribute.
If it needs to be focused programmatically (which it shouldn’t but we never know), `tabindex="-1"` should be used instead so it remains focusable via `.focus()`. Let me know if I should update the PR. :)

Remove unnecessary tabindex attribute

---

packages/@sanity/default-layout/src/navbar/presence/PresenceMenu.tsx

The button that opens the presence menu (where one can see who else is interacting with the current document) does not have any accessible name. This is a problem for people using screen-readers. This pull-request addresses this issue by adding a customizable label.
Related WCAG 2.1 SC: [4.1.2 Name, Role and Value](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1#name-role-value)

Add an accessible name to the presence menu button

---

packages/@sanity/desk-tool/src/panes/document/statusBar/sparkline/ReviewChangesButton/ReviewChangesButton.tsx

At the moment, the “review changes” button which indicates the edit status of the open document, is not semantically connected to the tooltip it triggers. This pull-request intends to address this by creating a relationship between both nodes using `aria-describedby`. 
**However**, this is not a perfect fix, because the tooltip is being added and removed from the DOM, but the `aria-describedby` attribute is not. This causes the toggle to reference an unknown ID with `aria-describedby` when the tooltip is not visible (since it’s the only time it’s actually in the DOM).
A simple fix for that would be for the toggle to be able to know if the tooltip is currently visible, but that doesn’t appear to be possible with the current tooltip component. I feel like the latter would benefit from a …

Connect the review changes button and its tooltip

---

packages/@sanity/base/src/preview/components/SanityDefaultPreview.tsx

Editors can add images to portable text content. If they don’t add an alternative text to these images, these are rendered without an `alt` attribute. A missing `alt` attribute will trigger some screen-readers to read out the full URL of the image asset, which is undesired.
Related WCAG 2.1 criterion: [1.1.1: Non-text Content](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1#non-text-content)
---
I _think_ I found the right place, but it wasn’t easy because I have no idea how the Portable Text editor works under the hood. If I did hit the target, the problem occurs because we set `undefined` as a value for the `alt` prop, instead of an empty string. This causes React not to render the attribute at all.

Ensure image previews in PT have an `alt` attribute

---

packages/@sanity/base/src/components/Document.tsx
packages/@sanity/core/src/actions/start/startAction.js
packages/@sanity/server/src/baseServer.js

The Sanity Studio currently does not define a language via the `lang` attribute on the `<html>` element. This is a violation of [Success Criterion 3.1.1](https://www.w3.org/WAI/WCAG21/Understanding/language-of-page.html) of the Web Content Accessibility Guidelines, which requires the language to be programmatically determinable. 
The Sanity interface is hard-coded in English. Everything that is not user-defined from the login form, to generic error messages, to the default actions and badges is authored in English directly within the codebase. I discussed it with @hidde and we agreed that setting English as a default value — at the risk of being partly incorrect for people configuring their schema to use non-English content — is worth it.
This pull-request therefore sets English (`en`) as …

Add missing document language to Sanity Studio

---

packages/sanity/src/hooks/useTimeAgo.ts

In some cases we're sending an empty or invalid string to the `useTimeAgo` hook - usually because of the rule of invocation on hooks - we can't conditionally call it, so if we don't have a date to pass it, we still need to call it. 
The result of this is that we would return "just now" as the timestamp, and every 5 seconds would update the value with... the same value. This is not ideal, since it causes more re-renders than necessary.
This PR instead returns an empty string (could debate whether or not this is the right choice, but showing "just now" also seems incorrect in my opinion), and an infinite refresh interval, meaning no timer will be set to update it while the date is invalid.
None. Transparent for end users.

fix(hooks): short-circuit invalid dates in `useTimeAgo` hook

---

packages/sanity/src/form/inputs/BooleanInput.tsx
packages/sanity/src/form/members/fields/PrimitiveField.tsx
packages/sanity/src/form/members/items/ArrayOfPrimitivesItem.tsx
packages/sanity/test/form/renderInput.tsx

The `onChange` handler of `elementProps` did not account for non-string types, emitting patches that used strings instead of number/boolean. This PR makes the change handler check the schema type for the item in question and emits patches of the corresponding type, using `valueAsNumber` for numbers and `checked` for booleans. Empty strings and `NaN` values are treated as "unset this field".
Also removes the custom `onChange` handler from the boolean input, which seems like a win?
That all primitive inputs work as expected (numbers, strings, booleans)
None, since the `elementProps` change has yet to be released.

fix(form): handle number and boolean changes in `elementProps`

---

packages/sanity/src/datastores/document/document-pair/editState.ts
packages/sanity/src/datastores/document/document-store.ts

There is some global memoization going on in the document pair datastore utils. This isn't great:
1. Global state is a side effect. It can be hard to test these utils properly, and it could lead to memory leaks.
2. The keys used in the memoization is insufficient. For the edit state, it does not take into account changes in the schema - for instance `liveEdit`. It also does not take the source into account (projectId/dataset), which could lead to trouble in cases where document IDs and type names are shared (think production vs staging).
I want us to clean up all of these globally memoized things, but I figured I would open this initially so we could discuss/verify the approach.
The document store is already memoized with a key on `client, documentPreviewStore, historyStore, schema`, and …

fix(datastores): memoize edit state in document store instance

---

packages/@sanity/base/src/client/bifur.ts
packages/@sanity/base/src/datastores/connection-status/connection-status-store.ts
packages/@sanity/base/src/datastores/presence/message-transports/bifurTransport.ts
packages/@sanity/base/src/datastores/presence/presence-store.ts

Hi all 👋 
Bjorge was kind enough to help me with a bug  regarding presence when people are in different datasets and go through the parts of the code that would be affected.
A project has two datasets: staging and production
User A is in a document in the production dataset and user B is in a document in the staging dataset.
User A goes to the presence menu, finds user B and attempts to travel to the document where they are only to be met with an error
To fix the actual navigation would be a large piece of work since the navigation/resolution of the document don't consider the dataset that the user is in. 
So, the solution for now is to hide users that are not in the same dataset and this way they won't appear on the list or be allowed to be navigated to if you are not on the same dataset …

fix(base): defer connection to presence client

---

packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx
packages/@sanity/form-builder/src/inputs/ObjectInput/utils.ts

This optimizes field rendering by not passing the parent value to fields that has no conditional callbacks. In certain cases this improves rerendering speed with about 20%.
- Verify that conditional fields works like before
- Don't pass parent object to fields with no conditional callbacks

perf(form-builder): skip passing parent for schema types with no conditional fields

---

packages/@sanity/base/src/components/formField/FormFieldSet.tsx
packages/@sanity/base/src/components/formField/styles.ts

Add styling to the alignment of a columnar fieldset. 
Issue: https://github.com/sanity-io/sanity/issues/3032 
**Before and after** 
The styling of items in the `Grid` with several columns are now aligned as `flex-end`. 
Add a fieldset with more than one column and see the alignment. 
Fix styling of alignment to a columnar fieldset

fix(base): add alignment styling to a columnar fieldset

---

packages/@sanity/desk-tool/src/components/paneItem/ReferencedDocHeading.tsx

We implemented a hack in order to trigger the "this document is referenced" popover to move properly on DOM changes that causes the parent to reposition. Unfortunately, I did not test this properly on older versions of Safari, which apparently doesn't work. This PR checks for the presence of the property before attempting to use it.
Fixes #3587
- That the popover still repositions as expected
- Fixed an issue where older versions of Safari might crash when opening a referenced document

fix(desk-tool): check for valid resize observer entry before use

---

packages/sanity/src/form/inputs/PortableText/object/renderers/PopoverEditDialog.tsx

There seemed to be an old hack laying around causing problems for the PT-input popovers now that we upgraded Sanity-UI. Removing this custom CSS solves the problem, and I can't see anything behaving differently otherwise.

fix(form): fix issue with popover content not displaying

---

packages/sanity/src/studio/components/navbar/Navbar.tsx

This is done because the number of people present changes over time, causing occasional "jumping" when people enter/exit. With the changelog/warning button to the left of the presence menu, you can end up in situations where you click on the wrong thing by accident, since the layout shifts. It also causes less of a layout shift on update.
That things still look alright, and that you agree that this makes sense.
Probably not worth mentioning.

fix: move presence menu to leftmost position in navbar

---

packages/@sanity/types/src/schema/types.ts

Adds a typescript interface for the `Geopoint` data type that is represented by the [geopoint](https://www.sanity.io/docs/geopoint-type) schema type.
- Comments and shape seems correct and does not contain typos
- Add and export `Geopoint` typescript interface

feat(types): add missing `Geopoint` data type

---

dev/test-studio/schema/index.ts
dev/test-studio/schema/standard/references.ts
dev/test-studio/schema/standard/slugs.ts
packages/sanity/src/form/store/formState.ts
packages/sanity/src/form/studio/inputResolver/helpers.test.ts
packages/sanity/src/form/studio/inputResolver/helpers.ts
packages/sanity/src/form/studio/inputResolver/inputResolver.tsx

Slug had level indentation. This is now removed.
The code that handled level indentation for objects did not account for recursive alias types. This is now added.
Moved the resolution of levels into formState so that this behaves equally in all components.
Should also be a tiny pref boost, since we dont have to recalculate level every render.
Added a test-suit to try to account for most codepaths.
Evaluate the tests-cases.
Is the move from components to formState ok?
Can be tested in the studio: added alias for slug and reference. 
Slug no longer has indentation next to the input.

fix: corrected object level indentation for slug and alias types

---

packages/@sanity/form-builder/src/inputs/PortableText/Compositor.styles.tsx
packages/@sanity/form-builder/src/inputs/PortableText/Compositor.tsx

This will fix an issue when closing modals from PT that contains a nested PT-editor when pressing `ESC`.
There was an attempt to always render the ExtendedLayer wrapped around the fullscreen version of the PT-input in order to optimize rendering. This seems not to actually give any particular performance wins though.
By only including the ExtendedLayer when in fullscreen fixes the issue described above as the `isTopLayer` get's the correct value now.
That everything closes as expected using `ESC` on modals and fullscreen mode in the PT-input.
* Fix an issue where Portable Text Input modals including a nested PT-input didn't close properly when pressing `ESC`.

Fix PT-input fullscreen issue

---

packages/sanity/src/form/inputs/CrossDatasetReferenceInput/__tests__/CrossDatasetReferenceInput.test.tsx
packages/sanity/src/form/inputs/DateInputs/__tests__/__snapshots__/DateInput.test.tsx.snap
packages/sanity/src/form/inputs/DateInputs/__tests__/__snapshots__/DateTimeInput.test.tsx.snap
packages/sanity/src/form/patch/patch.ts
packages/sanity/src/form/patch/types.ts
packages/sanity/src/form/utils/mutationPatch.ts

We might want to provide alternative ways of specifying patches in the future. By adding a `patchType` symbol to the patches returned by our patch helpers, we can future-proof that we can differentiate between a "patch helper generated" patch and an arbitrary value.
Wasn't quite sure about the naming on this one - open to suggestions.
Probably not worth mentioning.

feat(form): future-proof patch types

---

dev/test-studio/structure/resolveStructure.ts
packages/sanity/src/desk/panes/userComponent/UserComponentPane.tsx
packages/sanity/src/desk/types.ts

This PR introduces two breaking changes on custom user panes, since we've been wanting to get rid of these since v2. This has to be done before a GA v3 release so as not to cause another breaking change that could easily have been done in this release.
**BREAKING CHANGE**: we've been wanting to make `preserveInstance` the default behavior for custom panes for a while, but it has been a breaking change. Now that we have the ability to do so, lets reduce the complexity of things. User component panes should use `componentDidUpdate` or a `useEffect` with a dependency on the `itemId`/`childItemId` prop to react to updates.
**BREAKING CHANGE**: `urlParams` has been available through the `usePaneRouter()` hook as `params` since version 2.2.0. This commit drops this prop from being passed, since …

feat(desk)!: drop `preserveInstance`, `urlParams` options on custom user panes

---

packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.styles.ts

There seem to be a bug in Chrome related to flex layout and spellchecking. By using a div with 'display: flex' here the spellcheck would use around 20% cpu idle. By using a Box with the same display value, the bug isn't introduced for some reason.
That everything works as before and that the CPU idle use is gone.
* Workaround Chrome bug related to spellcheck and flex layout.

Workaround weird Chrome bug related to flex layout

---

packages/@sanity/cli/src/actions/login/login.js
packages/@sanity/cli/src/commands/login/loginCommand.js

Adds a new `--no-open` flag (technically also `--open`, but that is the default behavior) to the `sanity login` command, which is useful in certain situations such as automation. Also documents the `--provider <id>` option, which is also useful for automation.
- That `sanity login` still opens a browser by default
- That `sanity login --no-open` does not open browser, but prints login URL to screen
- Added a new `--no-open` flag to the `sanity login` command in order to suppress the opening of browser automatically

feat(cli): add `--no-open` flag to login command

---

packages/@sanity/core/src/commands/dataset/deleteDatasetCommand.js

Adds a new `--force` flag to the dataset delete command, in order to aid automation.
The reparsing of the CLI args is done to work around an issue where `sanity dataset delete --force foo` would treat the `force` flag as a string flag instead of a boolean flag and fail.
- That `sanity dataset delete my-dataset` still works and prompts for the name
- That `sanity dataset delete my-dataset --force` skips the prompt and deletes
- Added a new `--force` flag to the `sanity dataset delete` command

feat(cli): add `--force` flag to `sanity dataset delete` command

---

packages/@sanity/core/src/commands/dataset/alias/aliasCommands.js
packages/@sanity/core/src/commands/dataset/alias/unlinkAliasHandler.js

Adds a new `--force` flag to the unlink command. Helps with automation.
- `sanity dataset alias unlink :aliasName` still works and prompts for confirmation
- `sanity dataset alias unlink :aliasName --force` works and skips confirmation prompt
- Added `--force` flag to the `sanity dataset alias unlink` command to skip confirmation prompt

feat(cli): add `--force` flag for dataset alias unlink command

---

packages/@sanity/base/src/time/useTimeAgo.ts

Our `useTimeago` hook currently uses a combo of `useEffect` and `setState` to keep the value. This lead to a cases where we would re-render the hook twice (render => args change => useEffect => setState => render). Depending on the usage context, re-renders might be expensive.
I also changed from setInterval to a setTimeout continuation to avoid pile up (if the next render takes long, we end up waiting less than the actual desired delay, which, in principle (but probably only in extreme cases) could lead to a pile-up of invocations.
Also, to my surprise, passing `Infinity` as delay argument to `setInterval/setTimeout` is equivalent with a delay of `0`) and invokes it immediately, so I've changed the logic here slightly.
This PR refactors the `useTimeAgo` hook to address the above issues. …

perf(desk-tool): optimize useTimeAgo

---

packages/@sanity/desk-tool/src/actions/PublishAction.tsx
packages/@sanity/desk-tool/src/panes/document/DocumentPaneContext.ts
packages/@sanity/desk-tool/src/panes/document/DocumentPaneProvider.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/DocumentPanel.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/documentViews/FormView.tsx
packages/@sanity/desk-tool/src/panes/document/keyboardShortcuts/DocumentActionShortcuts.tsx
packages/@sanity/desk-tool/src/panes/document/statusBar/DocumentStatusBarActions.tsx
packages/@sanity/desk-tool/src/panes/document/statusBar/sparkline/DocumentBadges.tsx
packages/@sanity/desk-tool/src/panes/document/statusBar/sparkline/DocumentSparkline.tsx
packages/@sanity/react-hooks/src/useEditState.ts

This will optimize the DocumentPaneProvider to use low priority editStates. Also optimized hook dependencies. Removed editState from the context, and added initialValue.
Stuff that previously got editState from the useDocumentPane hook, is now using useEditState directly instead.
This is using the low priority version most of the places, while FormView is still using the immediate one.
This refactor saves us quite a few re-renders, and makes editing a lot snappier.
Here's a sample measurement of typing speed inside a regular string field:
```
Before:
Average of 3 samples: 2975ms
Total lag: 8565ms
Sample #1: 2929ms
Sample #2: 3033ms
Sample #3: 2964ms
Average of 3 samples: 2783ms
Total lag: 8120ms
Sample #1: 2865ms
Sample #2: 2653ms
Sample #3: 2832ms
After:
Average of 3 samples: 1928ms …
```

Refactor DocumentPaneProvider

---

packages/@sanity/default-layout/src/navbar/search/components/SearchHeader.tsx

Ensures that the spinner within the search header offsets the wrapping element and not the containing SVG.
This is to counter a recent update in `@sanity/ui` that now animates the spinner's wrapping element.

fix(default-layout): apply offset on search spinner wrapping element

---

packages/@sanity/vision/src/components/VisionGui.tsx

Mistakenly forgot that the client passed to vision from the studio now has a frozen config, but we're attempting to mutate it when changing API versions. Since we're using `withConfig()` (which clones and applies a new config) on the passed client, it is okay to un-freeze the config of this _particular_ instance of the client.
- That vision works inside the studio when switching between API versions
- Fixes an issue where the vision plugin would fail to run queries

fix(vision): allow reconfiguration of vision client

---

packages/@sanity/desk-tool/src/panes/document/documentPanel/header/DocumentHeaderTitle.tsx
packages/@sanity/react-hooks/src/useEditState.ts

This will fix an issue where the documentPane would render its Title preview for the document before it's ready in the Pane.
This bug has probably not been seen before because it has always been rendered synchronous with editState in DocumentPaneProvider. 
That the header preview for the document renders correctly and no longer is displaying a "Untitled" over the ghost title rendering.
Doesn't need to mentioned as this bug is not yet released

Fix document pane title bug

---

dev/design-studio/package.json
dev/example-studio/package.json
dev/test-studio/package.json
dev/workshop/package.json
examples/ecommerce-studio/package.json
packages/@sanity/base/package.json
packages/@sanity/code-input/package.json
packages/@sanity/color-input/package.json
packages/@sanity/dashboard/package.json
packages/@sanity/dashboard/src/widgets/projectUsers/ProjectUsers.js
packages/@sanity/default-layout/package.json
packages/@sanity/default-layout/src/navbar/search/components/SearchHeader.tsx
packages/@sanity/default-login/package.json
packages/@sanity/default-login/src/CorsCheck.js
packages/@sanity/desk-tool/package.json
packages/@sanity/field/package.json
packages/@sanity/form-builder/package.json
packages/@sanity/google-maps-input/package.json
packages/@sanity/language-filter/package.json
packages/@sanity/studio-hints/package.json
packages/@sanity/studio-hints/src/components/HintsPackage.js
packages/@sanity/vision/package.json

This will upgrade `@sanity/ui` to ` 0.37.22` and take care of some Spinner issues.
With the current performance optimization  done in `@sanity/ui` for Spinner animations, some spinners in the Studio code aligned wrong when animated. This was due to them being wrapped in a Text node.
I have updated all occurrences of this (I think) by implementing them according to the updated documentation at https://www.sanity.io/ui/docs/primitive/spinner#examples
For the ProjectUser dashboard widget I have used the Spinner Sanity-part to better align them with plugin code elsewhere.
For the Seach bar spinner I have used the spinner icon from `@sanity/icons` as the TextInput from `@sanity/ui` is expecting an icon and not a component. Then put on the same animation as `@sanity/ui` uses for its spinner. …

Fix Spinner misalignments

---

packages/sanity/src/form/store/formState.ts

We have some logic for hiding fields which are hidden, but there is a conditional check that is missing so this logic also applies in some incorrect cases with array members.
One example is when a block object inside the PT-input have a type with one single hidden field (imagine some special use case where this makes sense - this actually came from a client implementation).
Then it should still be possible to see the array member item, even though all of it's fields are null.
By checking for `enableHiddenCheck` like in the rest of that code, the logic works as expected.

Fix null items bug

---

packages/sanity/src/form/inputs/PortableText/Compositor.styles.tsx
packages/sanity/src/form/inputs/PortableText/Compositor.tsx
packages/sanity/src/form/inputs/PortableText/Editor.tsx
packages/sanity/src/form/inputs/PortableText/PortableTextInput.tsx
packages/sanity/src/form/inputs/PortableText/object/BlockObject.styles.ts
packages/sanity/src/form/inputs/PortableText/object/BlockObject.tsx
packages/sanity/src/form/inputs/PortableText/object/InlineObject.tsx
packages/sanity/src/form/inputs/PortableText/object/InlineObjectToolbarPopover.tsx
packages/sanity/src/form/inputs/PortableText/object/renderers/DefaultEditDialog.tsx
packages/sanity/src/form/inputs/PortableText/object/renderers/ObjectEditModal.tsx
packages/sanity/src/form/inputs/PortableText/text/Annotation.tsx
packages/sanity/src/form/inputs/PortableText/text/AnnotationToolbarPopover.tsx
packages/sanity/src/form/inputs/PortableText/text/TextBlock.styles.ts
packages/sanity/src/form/inputs/PortableText/text/TextBlock.tsx

Lifted over the improvements of the PT-input in read only mode from `v2` and other improvements.
Basically these:
https://github.com/sanity-io/sanity/pull/3619
https://github.com/sanity-io/sanity/pull/3641
https://github.com/sanity-io/sanity/pull/3633
https://github.com/sanity-io/sanity/pull/3649

Improve PT-input readOnly mode

---

packages/sanity/src/form/inputs/PortableText/PortableTextInput.tsx

Is seems like the PortableTextInput with React 18 is able to receive events from the PortableTextEditor even though it is unmounted and cleaned up at the time we receive the event inside PortableTextInput.
By checking the editorRef there before sending the patches, we can avoid that DocumentPane crashes at least when it receives the mutation.
I am however not sure if this is symtom of that something else is wrong, or it is just some of the things to expect with React 18.

Fix React 18 issue with PT-input

---

dev/test-studio/schema/standard/slugs.ts
packages/@sanity/types/src/slug/types.ts
packages/@sanity/types/src/validation/types.ts
packages/@sanity/validation/src/validators/slugValidator.ts
packages/sanity/src/form/inputs/Slug/SlugInput.tsx
packages/sanity/src/form/inputs/Slug/utils/slugify.ts
packages/sanity/src/form/inputs/Slug/utils/useSlugContext.ts

Extends the context object passed to `options.source` and `options.slugify` with getClient, schema, currentUser (and projectId and dataset for consistency with initial value context).
Also fixes the context type for `options.isUnique` which was duplicated in the definition, and missing some properties (they where available at runtime already though, via validation context).
This is primarily to make it possible to use the client when using these options; a common thing in v2.
All the code.
Slug options `source` and `slugify` are now passed a `context` parameter as the last argument. It contains `getClient`, `schema` and `currentUser`.

fix: added context with client and schema to slugify and source options

---

packages/sanity/src/_exports/form.ts
packages/sanity/src/form/inputs/files/ImageToolInput/imagetool/HotspotImage.tsx
packages/sanity/src/form/inputs/files/ImageToolInput/imagetool/ImageLoader.tsx
packages/sanity/src/form/inputs/files/ImageToolInput/imagetool/Resize.tsx
packages/sanity/src/form/studio/focusManagers/HashFocusManager.ts

Converts problematic class components to function components with hooks to make them ready for React 18 concurrent features. With this PR there's no longer any components left in our codebase that uses `UNSAFE_` prefixed legacy lifecycle hooks.

fix: migrate class components to functions+hooks

---

.github/workflows/etl.yml
.github/workflows/lintChanged.yml
.github/workflows/test.yml

Our PRs are a bit noisy atm as most CI tasks run double checks. With this it'll only run its CI things once per PR (without breaking fork PRs).

chore(ci): reduce PR builds

---

dev/test-studio/.env.example
dev/test-studio/.gitignore
dev/test-studio/sanity.cli.ts
packages/@sanity/cli/src/types.ts
packages/@sanity/server/src/buildStaticFiles.ts
packages/@sanity/server/src/devServer.ts
packages/@sanity/server/src/getEntryModule.ts
packages/@sanity/server/src/runtime.ts
packages/@sanity/server/test/devServer.test.ts
packages/sanity/src/_internal/cli/actions/start/startAction.ts
packages/sanity/src/core/studio/renderStudio.tsx

Adds an option to `sanity.cli.js` that controls wether strict mode is enabled. It was previously always-on. Now it's opt-in. The test studio enables it by default.
Prior art: https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode
Either run the dev command with an env var override:
```bash
SANITY_STUDIO_REACT_STRICT_MODE=false yarn dev
```
Or run this once and carry on as usual:
```bash
cp dev/test-studio/.env.example dev/test-studio/.env.development
```
If you're seeing double console logs after enabling strict mode, check the `Hide logs during second render in Strict Mode` option in the React Devtools Components Settings modal:
In studios that have a `sanity.cli.ts` file, add `reactStrictMode: true` to enable it.
In studios without, it should be possible to opt-in by …

feature(cli): add `reactStrictMode` option

---

packages/sanity/src/core/studio/GlobalStyle.tsx
packages/sanity/src/core/studio/Studio.tsx
packages/sanity/src/core/studio/StudioThemeProvider.tsx
packages/sanity/src/core/studio/colorScheme.tsx
packages/sanity/src/core/studio/renderStudio.tsx

This change introduces an internal component named `<GlobalStyle />` that uses `createGlobalStyle` from `styled-components` to render global CSS that sets a background color to the `<html>` element and a `font-family` to the `#sanity` element.
This fixes the problem of incorrect font-family in the cases where you don't use `<Text>` from `@sanity/ui`.
NOTE: global styles will only be applied by default in a context where you use `sanity start` or `sanity build`. If you embed the `<Studio />` in e.g. Next.js, you'll have to enable global styles specifically:
```tsx
<Studio
config={config}
// tell the studio to render global styles
unstable_globalStyles
/>
```
- That this works in a Next.js app.
- That this works as intended in the default Studio runtime.
- The Studio will now render a …

feat(sanity): studio default global styles

---

packages/sanity/src/core/form/store/utils/__tests__/immutableReconcile.test.ts
packages/sanity/src/core/form/store/utils/immutableReconcile.ts

Form state now correctly updates members when hidden state changes.
Underlying issue: immutableReconcile did not account for changes in number of keys in objects,
which resulted in it considering next object unchanged when a key had been removed.
This made the code retain the previous value incorrectly.
This had the effect of associating wrong schemaTypes with member fields, when hidden function
changed state (as one observed effect).
Evaluate the code.
This was verified in the test-studio by reproducing a reported issue related to this (observed as wrong schema passed as props to renderInput) and confirming that it fixed.

fix: object reconciler

---

packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
packages/sanity/src/desk/panes/document/documentPanel/documentViews/FormView.tsx

We had a bug where the FormView would throw errors when calling onChange from the PT-input while switching documents. This was quick fixed by this commit: https://github.com/sanity-io/sanity/pull/3700/commits/6f3f6ff1cfabc384f0e65e45d1eb9fd2add98bde
However, the real problem seems to be that handleChange is called for a a FormView in which the DocumentPane isn't ready yet, so checking for this inside DocumentPaneProvider seems to be the correct place to fix this with the current codebase.
I have also reverted the quick fix I did.

Fix handle change exception

---

dev/test-studio/sanity.config.ts
dev/test-studio/themes/google.ts
dev/test-studio/themes/vercel.ts
packages/sanity/package.json
packages/sanity/src/core/studio/StudioThemeProvider.tsx
packages/sanity/src/core/studio/colorScheme.tsx
packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
packages/sanity/src/core/studio/components/navbar/userMenu/UserMenu.tsx
packages/sanity/src/core/theme/_legacy/color.ts
packages/sanity/src/core/theme/_legacy/fonts.ts
packages/sanity/src/core/theme/_legacy/helpers.ts
packages/sanity/src/core/theme/_legacy/index.ts
packages/sanity/src/core/theme/_legacy/palette.ts
packages/sanity/src/core/theme/_legacy/theme.ts
packages/sanity/src/core/theme/_legacy/tones.ts
packages/sanity/src/core/theme/_legacy/types.ts
packages/sanity/src/core/theme/index.ts
packages/sanity/src/core/theme/types.ts
yarn.lock

Move logic from v2 for creating a Sanity UI theme object based on a record of CSS variables.
You can now use `buildLegacyTheme` to generate a Sanity UI theme:
```ts
import {buildLegacyTheme, createConfig} from 'sanity'
export default createConfig({
// project configuration ...
// Customize theming
theme: buildLegacyTheme({
'--black': '#000',
'--gray': '#777',
'--focus-color': '#00f',
})
})
```
- Open the [Test Studio](https://test-studio-git-feat-legacy-theme.sanity.build/test/content)
- Open the Google workspace
- Open the Vercel workspace
- Check that colors and contrasts look reasonable and good enough
- Check that light/dark mode switching is NOT supported for legacy themes
- Use `buildLegacyTheme()` to migrate your theme from v2 => v3. NOTE: this will disable light/dark mode …

feat: legacy theming

---

dev/test-studio/package.json
dev/test-studio/schema/standard/portableText/customMarkers/CustomContentInput.tsx
dev/test-studio/schema/standard/portableText/customMarkers/schemaTypes.tsx
packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/types/editor.ts

Fixes an issue causing content to be inserted twice when using custom paste handler
Refactored the code slightly to use a guard and early return to make the flow a bit easier to follow
- Fixes an issue causing content to be inserted twice when using custom paste handler

fix(portable-text-editor): fix double paste event bug

---

packages/@sanity/vision/README.md
packages/@sanity/vision/package.config.ts

When using `@sanity/vision` outside the monorepo it throws this error and crashes:
Running it on localhost also throws this warning:
```
next-dev.js:28 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```
This is due to `@sanity/vision` bundling react instead of treating it as an external.
Related PR in `@sanity/pkg-utils` that changes `config.external: string[]` to merge in `pkg.dependencies` and …

fix: `@sanity/vision` includes `react` in bundle

---

packages/sanity/src/desk/panes/document/DocumentOperationResults.tsx

Prevents toasts that have already been fired from being fired again.
See if push toasts work as they should.
Toast notifications no longer fire more than once for the same event.

fix: only show "document published" toast once

---

packages/@sanity/desk-tool/src/DeskTool.tsx

Backport from #3750
Fixes a long standing bug where if you reload the page when in split view the extra panes are closed
Before: https://test-studio.sanity.build/test/desk/author;grrm%7C%2Cview%3Dpreview
After: https://test-studio-git-bug-sc-25678split-pane-urls-v2.sanity.build/test/desk/author;grrm%7C%2Cview%3Dpreview
- Split panes persists on page reloads. And can be linked to.

fix: persist split panes on reload

---

packages/sanity/src/router/RouterProvider.tsx

Whichever URL Studio v3 is mounted with can't be navigated back to.
This is due to `stateRef.current` never being updated inside `RouterProvider`.
This PR refactors it to pass down the router state as is, as its parent router is already doing the `isEqual` checks needed.
The `useEffect` + `useState` loop in `RouterProvider` creates extra rerender cycles and slows down route changes to no benefit.
1. Open [workshop](https://test-studio-git-v3.sanity.build/test/workshop?scheme=dark&value=eJyrrgUAAXUA%2BQ%3D%3D).
2. Click Content.
3. Click on Workshop.
4. You're still seeing the `Content` tool, even though the URL pathname is now `/test/workshop`.
1. Open [workshop](https://test-studio-git-v3-fix-sticky-routing.sanity.build/test/workshop?scheme=dark&value=eJyrrgUAAXUA%2BQ%3D%3D).
2. Click …

fix: unable to navigate back to mounted url

---

packages/sanity/src/desk/components/pane/PaneHeader.tsx

This PR fixes the focus ring on the timeline button which was partially hidden.
n/a
fix(desk): timeline button focus ring

fix(desk): timeline button focus ring

---

packages/sanity/src/core/form/form-components-hooks/components.ts

This PR fixes so that the schemaType passed to `renderDefault` in a schema is used when resolving the form component. This makes it possible to do stuff like below – which currently don't work:
```js
// Render string input as <select /> by adding `options.list` to the `schemaType`
{
name: 'title',
components: {
input: (props) => {
return props.renderDefault({
...props,
schemaType: {
...props.schemaType,
options: {
list: ['Option 1', 'Option 2', 'Option 3'],
},
},
})
},
},
}
```
- Review the code
- Do you see any risks with this update?
fix(sanity): use schemaType passed to `renderDefault` in schema when resolving the form component

fix(sanity): use schemaType passed to `renderDefault` in schema when resolving the form component

---

packages/@sanity/desk-tool/src/panes/document/DocumentPaneContext.ts
packages/@sanity/desk-tool/src/panes/document/DocumentPaneProvider.tsx
packages/@sanity/desk-tool/src/panes/document/documentPanel/documentViews/FormView.tsx

Fixes a regression introduced in [v2.34.2](https://github.com/sanity-io/sanity/releases/tag/v2.34.2) that broke the revision history selector by making it always show the current version of the document.
- Make sure navigating throuigh revision history will display the selected revision
- Fixes a bug causing revision history selector to always display the current version instead of the selected revision

fix(desk-tool): fix issue with history pane not showing the earlier version

---

packages/@sanity/default-layout/src/navbar/search/components/SearchResults.tsx

One-liner to re-enable sort menu in search results! (Now clear to display)
Order search results by relevance, created and last updated date.

chore(default-layout): re-enable search sorting

---

packages/sanity/src/core/studio/screens/CorsOriginErrorScreen.tsx

Simplifies the CORS error dialog to reduce technical language, and adds a "Add origin" CTA that takes you to a [new flow in manage](https://github.com/sanity-io/manage/pull/291). The new flow prefills the CORS information for you and gives the user a "Confirm" CTA at the end. Pressing it closes the popup window.
Upon return a `winow.onfocus` handler automatically retries.
This means that the happy path for resolving a CORS problem becomes:
1. User sees the CORS error dialog, and clicks on CTA.
2. A new window opens in manage, explaining what is about to happen, and the user clicks "Confirm".
3. The origin is added and the window closes, and the Studio loads automatically.
Try the flow on origins we don't allow: `cd dev/test-studio && yarn sanity:dev --port 3030`.
You should see the error, …

fix: direct link to add cors origin

---

dev/test-studio/schema/standard/arrays.tsx
packages/@sanity/schema/src/sanity/validation/createValidationResult.ts
packages/@sanity/schema/src/sanity/validation/types/array.ts

This adds strict validation of list of predefined options provided for array types. This means you will now get a schema error if you provide list options that are not allowed by the array declaration.
This also _removes_ support for predefined choices on the shape of `{title: 'Some title', value: {_type: 'someObjectType', ...}}` since preview is better handled by delgating to the studio preview for the type. You can still provide display title for primitive values, as explained in the [help article](https://www.sanity.io/help/schema-predefined-choices-invalid) linked to the schema compile error.
Example:
- Verify that the validation makes sense
- Verify that the errors are sensible and the information provided by the help url makes sense
- Added strict validation of predefined list …

Add strict runtime validation of array choices

---

packages/sanity/src/core/form/inputs/ObjectInput/ObjectInput.tsx
packages/sanity/src/core/form/inputs/ObjectInput/fieldGroups/FieldGroupTabs.tsx
packages/sanity/src/core/form/store/formState.ts
packages/sanity/src/core/form/store/types/nodes.ts
packages/sanity/src/core/form/store/useFormState.ts
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx

The document group tabs should be disabled when the review changes pane is open.
- Code review
- Should work for nested tabs
fix(sanity): disable group tabs when review changes pane is open

fix(sanity): disable group tabs when review changes pane is open

---

packages/sanity/src/core/preview/components/SanityPreview.tsx

This fixes rendering of icons from schema in `SanityPreview` by making sure the icon is pulled out from the schema type.
- Does the change catch all schema types? Before we had [a special case for references](https://github.com/sanity-io/sanity/blob/817abbdf31e28180fea477070f6b96387cec751f/packages/@sanity/base/src/preview/components/RenderPreviewSnapshot.tsx#L31), do we still need that?
- Fixed icons from schema in block previews

fix(sanity): fix icon from schema in block previews

---

packages/@sanity/portable-text-editor/package.json
packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditor.test.tsx
packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withEditableAPIDelete.test.tsx
packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withPortableTextMarkModelNormalization.test.tsx
packages/@sanity/portable-text-editor/src/utils/__tests__/valueNormalization.test.tsx
packages/@sanity/portable-text-editor/test/__tests__/selectionAdjustment.collaborative.test.ts
packages/@sanity/portable-text-editor/test/__tests__/writingTogether.collaborative.test.ts
packages/@sanity/portable-text-editor/test/serve.ts
packages/@sanity/portable-text-editor/test/setup/collaborative.jest.env.ts
packages/@sanity/portable-text-editor/test/tsconfig.json
packages/@sanity/portable-text-editor/test/web-server/app.tsx

After upgrading to React 18, and other dependencies (i.e. new packing system) the portable-text-editor's tests have been needing some improvements.
I have done the following to better support their async nature:
* Refactor some of the tests to use `waitFor` instead of `act` from react testing library. This get rid of those warnings we have been seeing which potentially also can be a source to instability in test results.
* Run the individual tests in sync. Though each collaborative editing test websocket payload is tagged with the instance of the test and it's value is mapped to that id on the server (in order to support running in parallell), running these in parallel still seems to somehow yield different results than running them in serial mode (`jest --runInBand`). This is proven by …

Improve PTE test stability

---

cypress/integration/config/formComponentsApi.test.js
dev/test-studio/schema/docs/v3/form-components-api/components.tsx
dev/test-studio/schema/docs/v3/form-components-api/schema.tsx
packages/sanity/src/core/config/types.ts
packages/sanity/src/core/form/FormBuilderContext.ts
packages/sanity/src/core/form/FormBuilderProvider.tsx
packages/sanity/src/core/form/inputs/TagsArrayInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/ArrayOfObjectsFunctions.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridArrayInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesFunctions.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx
packages/sanity/src/core/form/inputs/index.ts
packages/sanity/src/core/form/types/_transitional.ts
packages/sanity/src/core/form/types/inputProps.ts

This pull request makes it possible to configure custom array functions with an `arrayFunctions` prop. The component passed to `arrayFunctions` receives all the necessary props required to implement array functions.
Config example:
```tsx
import {createConfig, isArrayOfPrimitivesInputProps} from 'sanity'
export default createConfig({
...,
form: {
components: {
input: (props) => {
const {renderDefault}  = props
if (isArrayOfPrimitivesInputProps(props)) {
return renderDefault({...props, arrayFunctions: MyArrayFunctions})
}
return renderDefault(props)
},
},
},
})
```
Schema example:
```tsx
import {ArrayOfPrimitivesInputProps} from 'sanity'
function CustomArrayInput(props: ArrayOfPrimitivesInputProps) {
return props.renderDefault({...props, arrayFunctions: MyArrayFunctions})
}
const …
```

feat(form): implement custom array functions

---

packages/@sanity/server/src/getViteConfig.ts

Set `viteConfig.cacheDir` to a location that is different from Vite's default location: `node_modules/.vite`. This makes sure that there will not be Vite cache conflicts if you happen to use Vite for something else than `sanity` in your project.
- Remove any `node_modules/.vite` directories.
- Run `sanity dev` & `sanity build` and make sure the cache is stored in `node_modules/.sanity/vite`.
- Fix an issue where Vite cache could be overwritten/corrupted.

fix(server): configure `cacheDir` to avoid cache conflicts

---

dev/test-studio/sanity.config.ts
packages/sanity/src/core/studio/StudioErrorBoundary.tsx
packages/sanity/src/core/studio/workspaceLoader/WorkspaceLoader.tsx

This PR removes the temporary config error screen, and instead uses the default error screen. 
Add an invalid config and the error screen should appear. E.g:
```ts
export default createConfig({
...,
schema: {
....,
templates: [
{
id: `whatever`,
title: `Title`,
schemaType: `doesNotExist`,
value: () => {
return {}
},
},
],
},
})
```
fix(core): use the default error screen when there are configuration errors

fix(core): use the default error screen when there are configuration errors

---

packages/sanity/src/core/form/store/useFormState.ts
packages/sanity/src/desk/panes/document/DocumentPaneContext.ts
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx
packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
packages/sanity/src/desk/panes/document/documentPanel/documentViews/FormView.tsx

This is a cherry pick of https://github.com/sanity-io/sanity/pull/3759 into `v3`, plus a fix for a v3-only issue with forms not becoming `readOnly` based on external factors like "viewing an older revision", or "current user has no access to edit".

fix(desk-tool): fix: earlier revision not appearing in form

---

packages/@sanity/cli/src/actions/init-project/initProject.ts
packages/@sanity/cli/src/actions/init-project/prompts.ts
packages/@sanity/cli/src/commands/init/initCommand.ts

After a lot of discussion, we've decided that we should be encouraging the use of typescript for new projects. This PR changes the default from javascript to typescript. People will still be prompted, but the default choice is to use typescript. You can use `--no-typescript` to explicitly opt out, should you want to (`--typescript` still works as before, skipping the prompt).
- Initializing new projects works as before, but the default in the typescript prompt is "yes"
- `--no-typescript` works as expected
- New projects now use TypeScript by default

feat(cli): use typescript by default for new projects

---

packages/sanity/src/core/studio/StudioLayout.tsx

This PR fixes the error screen UI in `StudioLayout`.
n/a
Fix error screen UI

fix(core): broken error screen ui

---

dev/test-studio/components/workspaceLogos.tsx
dev/test-studio/sanity.config.ts
packages/sanity/src/core/studio/components/navbar/__workshop__/WorkspacePreviewStory.tsx
packages/sanity/src/core/studio/components/navbar/__workshop__/index.ts
packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceAuth/WorkspaceAuth.tsx
packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx

This PR enables adding a `subtitle` to a workspace and removes the dataset name as the default subtitle. The subtitle is displayed in the workspace preview component which is used in the workspace menu and on the login screen.
```tsx
export default defineConfig([
{
..., 
subtitle: 'Subtitle 1',
plugins: [...],
schema: {...}
},
{
..., 
subtitle: 'Subtitle 2',
plugins: [...],
schema: {...}
}
])
```
n/a
feat(core): enable workspace subtitle configuration

feat(core): enable workspace subtitle configuration

---

packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts

This change disables cross dataset validation on mutations in the studio. This is mainly done to prevent the studio crashing because the mutation fails when 1) There is a cross dataset in the document being mutated 2) The document referenced has been deleted in the target dataset.
- That a document with a cross dataset reference where the document has been deleted won't crash the studio anymore
- Fix a edge case where a cross dataset reference to a deleted document would prevent you changing the document with the reference

fix(core): skip cross dataset validation on mutations

---

packages/@sanity/base/src/datastores/document/document-pair/checkoutPair.ts

This change disables cross dataset validation on mutations in the studio. This is mainly done to prevent the studio crashing because the mutation fails when 1) There is a cross dataset in the document being mutated 2) The document referenced has been deleted in the target dataset.
- That a document with a cross dataset reference where the document has been deleted won't crash the studio anymore
- Fix a edge case where a cross dataset reference to a deleted document would prevent you changing the document with the reference
_This is a port from v3 of PR #3846_

fix(base): skip cross dataset validation on mutations

---

packages/@sanity/server/src/buildStaticFiles.ts
packages/@sanity/server/src/devServer.ts
packages/@sanity/server/src/previewServer.ts
packages/@sanity/server/src/renderDocument.ts
packages/@sanity/server/src/runtime.ts
packages/@sanity/server/src/sanityConfig.ts

Basically just adds more logging using the `debug` module, in order to more easily probe what is going wrong or is slow in certain cases. Should be fairly uncontroversial.
- `sanity build`, `sanity dev`, `sanity preview` works

chore(server): add more debug logging

---

dev/test-studio/documentActions/actions/TestConfirmDialogAction.tsx
dev/test-studio/documentActions/actions/TestModalDialogAction.tsx
dev/test-studio/documentActions/actions/TestPopoverDialogAction.tsx
packages/sanity/src/core/config/document/actions.ts
packages/sanity/src/desk/__workshop__/DocumentStateStory.tsx
packages/sanity/src/desk/documentActions/DeleteAction.tsx
packages/sanity/src/desk/documentActions/DiscardChangesAction.tsx
packages/sanity/src/desk/documentActions/HistoryRestoreAction.tsx
packages/sanity/src/desk/documentActions/UnpublishAction.tsx
packages/sanity/src/desk/panes/document/keyboardShortcuts/DocumentActionShortcuts.tsx
packages/sanity/src/desk/panes/document/statusBar/ActionMenuButton.tsx
packages/sanity/src/desk/panes/document/statusBar/ActionStateDialog.tsx
packages/sanity/src/desk/panes/document/statusBar/DocumentStatusBarActions.tsx
packages/sanity/src/desk/panes/document/statusBar/dialogs/ConfirmDialog.tsx
packages/sanity/src/desk/panes/document/statusBar/dialogs/ModalDialog.tsx
packages/sanity/src/desk/panes/document/statusBar/dialogs/PopoverDialog.tsx

**BREAKING CHANGE**: Document actions has a `modal` prop which in v2 was named `dialog`. In this version, we are reverting this back to `dialog`, since it is a more correct term for the feature. To align with this change, we are also renaming types that are coupled to it.
For now, this is a backwards compatible change, but before we launch v3 into General Availability (GA), the support for `modal` will be removed.
- That document actions still work as expected (default + custom)
- That the names of types and props make sense
- **BREAKING CHANGE:** Renamed the `modal` property to `dialog` for document actions. This makes them backwards compatible with v2 document actions, and is a more correct term for the feature.

refactor(core)!: rename document action `modal` prop to `dialog`

---

packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialog.tsx
packages/sanity/src/desk/components/confirmDeleteDialog/index.tsx
packages/sanity/src/desk/panes/document/DocumentPane.tsx
packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
packages/sanity/src/desk/panes/document/statusBar/dialogs/ModalDialog.tsx

Currently, document specific dialogs are rendered full screen. This PR updates so that a document's dialogs are scoped to the document's pane.
Make sure that a document's dialogs are scoped to its pane.
feat(desk): scope document footer dialogs to the current pane

feat(desk): scope document footer dialogs to the current pane

---

packages/sanity/src/core/config/types.ts
packages/sanity/src/core/config/useConfigContextFromSource.ts

**BREAKING CHANGE**: As warned in previous releases through deprecation warnings, the `client` provided through the config context was to be removed. This release pulls the trigger on that.
Studio still works :)
- BREAKING CHANGE: Dropped `client` from configuration context - use `getClient({apiVersion: '2022-06-07'})` or similar instead

refactor(config)!: drop `client` from config context

---

packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx
packages/sanity/src/core/form/inputs/PortableText/Editor.tsx
packages/sanity/src/core/form/inputs/PortableText/hooks/useScrollToOpenedMember.tsx
packages/sanity/src/core/form/inputs/PortableText/object/renderers/ObjectEditModal.tsx
packages/sanity/src/core/form/inputs/PortableText/text/Annotation.tsx
packages/sanity/src/core/form/inputs/PortableText/toolbar/Toolbar.tsx
packages/sanity/src/core/form/inputs/PortableText/toolbar/hooks.ts

When there is a Popover element opened in the editor, wait for the editor reference element to be set before we open it. Currently there is an issue with @sanity/ui and Floating.ui that will not open the popover properly if the reference element is given at a later time.
Also, improve `useScrollToOpenenedMember` to actually test if the form has focus, and not only the editor itself. The form value is what we want here as the editor in transition could have focus, but not form state focus (focusPath).
Also fixed an related issue where the toolbar popover for PT annotations would not properly show on newly created annotations.
Also moved some common editor blur logic to a more central place and renamed toolbar prop `onExpand` to `onOpenItem` to make it clearer what it does and easier to …

refactor(inputs): refactor PT-input annotation popover

---

packages/@sanity/mutator/src/patch/ImmutableAccessor.ts
packages/sanity/src/core/form/inputs/NumberInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ErrorItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ItemRow.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/getEmptyValue.ts
packages/sanity/src/core/form/members/array/items/ArrayOfPrimitivesItem.tsx
packages/sanity/src/core/form/members/object/fields/ArrayOfPrimitivesField.tsx

Sorry for bundling several things into one PR. The commits can be reviewed one by one.
1. Fixes a bug preventing array items with an invalid type from being deleted
2. Changes from triple-equals to Object.is equality check in @sanity/mutator when checking if a patch needs applying or not (needed in next step)
3. Using a signed zero (`-0`) trick to mark number input as "empty" and render the number input with an empty string instead of a zero you can't get rid of. If the value is `-0` we pass an empty string to the number input. This allows us to retain the type information even when the field is empty. Closes #1694
4. Set the number input range to `[Number.MIN_SAFE_INTEGER, Number.MAX_SAFE_INTEGER]`. Rationale:
If you store numbers larger than what can fit in 32 bits you are likely going …

Various fixes related to number input when used inside arrays

---

packages/sanity/src/core/presence/FieldPresence.tsx

There is an issue with Vercel/Next where after they've made changes to their configuration keys (specifically `swcMinify` is now set to default to true) that causes issues with some parts of the code. 
This change came after a bug report came over the `FieldPresenceWithOverlay` was not found when running `start` but was fine when running the `dev` command). 
After speaking with @stipsan , he realised - from other bugs exactly like this one - that this is Next recognises that the method `FieldPresenceWithOverlay` is not being called anywhere so it can remove it completely. Changing the order of the methods should help reduce the amount of times that we run into this issue in the future.
Vercel/Next have also been made aware that this is happening.
The code is exactly the same, I've only …

refactor: re-order methods in fieldpresence to reduce deadcode removal on next

---

packages/sanity/src/core/error/ErrorLogger.tsx
packages/sanity/src/core/studio/StudioErrorBoundary.tsx
packages/sanity/src/core/studio/StudioLayout.tsx
packages/sanity/src/core/studio/StudioProvider.tsx

We currently have two error boundaries - one on the studio level and one on the tool level. This _sorta_ makes sense, since by having a separate tool-level boundary, we can still move to different tools if one of them crashes (the global error boundary doesn't render any navigation bar). However, the two error boundaries look and behave differently, which isn't great.
This PR refactors things a bit:
- Moves the error logging bit (`console.error()` + pushing a toast) out of the error boundary and into its own little component (doesn't render anything, but attaches a listener using a `useEffect`). Could have been just a hook, but needs to be rendered below the toast provider in the tree, so might as well make it a component.
- Makes the studio error boundary slightly more reusable by …

fix(errors): unify error boundaries, prevent duplicate toasts

---

packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx

Removed the `distinctUntilChanged` function call from the `handleQueryChange` in the `ReferenceInput` to fix the issue of filtering not being updated when the parent component is changed. 
Link to issue: https://github.com/sanity-io/sanity/issues/3217
The book reference dropdown is updated when the decade is changed without the need of a hard refresh. 
ie try to go from 1980 to 10 (there are actual books for these decades to show) 
fix(form-build): Fix reference filtering updas

fix(form-builder): remove distinctUntilChanged function from handleQueryChange in referenceInput

---

packages/sanity/src/desk/documentActions/DiscardChangesAction.tsx
packages/sanity/src/desk/panes/document/keyboardShortcuts/DocumentActionShortcuts.tsx
packages/sanity/src/desk/panes/document/statusBar/ActionMenuButton.tsx
packages/sanity/src/desk/panes/document/statusBar/DocumentStatusBarActions.tsx

This will remove support for `.modal` in documentActions and only use `.dialog`.
See commit 24fb475bbc225a740bb2e8dcb553659d5b3afeb5

refactor(desk): remove support for documentAction.modal

---

packages/@sanity/schema/src/sanity/validation/types/common.ts
packages/@sanity/schema/src/sanity/validation/types/deprecated.ts

This PR adds warnings when using deprecated schema configs.
- Are there any other warnings that should be added?
Add warnings when using deprecated schema config

feat(core): add warnings when using deprecated schema config

---

packages/sanity/src/core/studio/components/navbar/userMenu/UserMenu.tsx

This pull request fixes the position of the user menu popover. For some reason, the `UserAvatar` component inside the popover causes the popover to be positioned incorrectly. It seems like the issue is that the `UserAvatarLoader` component that loads the user and passes it to `UserAvatar` sometimes returns `null` when there's no user data. The fix here is to "reserve" the space for the `UserAvatar` by setting a fixed width and height on the component that wraps the `UserAvatar`.
I have investigated this in Sanity UI to ensure that the popover position is updated correctly when the content changes. And everything seems to work fine in Sanity UI. 
- Make sure that the user menu is positioned correctly 
Fix user menu position

fix(core): user menu popover position

---

packages/sanity/src/core/form/inputs/PortableText/toolbar/Toolbar.tsx

This PR fixes so that the block style select in PTE is only visible when there is more than one option.
Make sure that the block style select is visible when there is more than one option and hidden when there is only one option.
Only show the block style select in the portable text editor when there is more than one option

fix(core): hide style select when there is only one option

---

packages/sanity/package.json
packages/sanity/src/core/form/hooks/useScrollIntoViewOnFocusWithin.ts

Help with native ESM support, `scroll-into-view-if-needed@v3` implements `pkg.exports`.

fix: bump `scroll-into-view-if-needed` for better ESM support

---

packages/@sanity/cli/src/commands/init/initCommand.ts
packages/sanity/src/_internal/cli/commands/dev/devCommand.ts
packages/sanity/src/_internal/cli/commands/start/startCommand.ts

`npm run start`
`npm run init`

Allow 'dev' to be started from failed 'start' command

---

packages/@sanity/block-tools/src/HtmlDeserializer/helpers.ts
packages/@sanity/block-tools/src/HtmlDeserializer/index.ts
packages/@sanity/block-tools/src/index.ts
packages/@sanity/block-tools/src/types.ts
packages/@sanity/block-tools/src/util/blockContentTypeFeatures.ts
packages/@sanity/block-tools/src/util/normalizeBlock.ts
packages/@sanity/block-tools/test/tests/util/__snapshots__/blockContentTypeFeatures.test.ts.snap

This will make the `block-tools` package use the updated porable text types from `@sanity/types`.
No functional changes.

Refactor block-tools package to use new PT-types

---

packages/sanity/package.json

This change adds `bin` to the `files` array in `package.json`.

build: add `bin` directory to distribution

---

packages/sanity/src/core/studio/colorScheme.tsx
packages/sanity/src/core/studio/components/navbar/userMenu/UserMenu.tsx
packages/sanity/src/core/studio/components/navbar/workspace/WorkspacePreview.tsx

This PR implements so that the selected color scheme is saved in local storage and reused on the next visit. The default color scheme is based on system settings until the user chooses otherwise.
This PR also makes some small UI updates the user menu component (see image).
Make sure that you get the expected color scheme based on what you have selected after reloading the studio.
The studio now saves the selected color scheme in local storage and uses it on next visit

feat(core): store selected color scheme in local storage

---

packages/sanity/src/core/config/prepareConfig.ts
packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts

Brings back support for `unstable_clientFactory`:
```ts
import {defineConfig} from 'sanity'
import {createFakeClient} from './fake/sanityClient'
const sanityConfig = defineConfig({
unstable_clientFactory: () => createFakeClient(),
projectId: 'test',
dataset: 'test',
})
```
This makes the Config API support mocking the client without using a test framework like `jest` – but instead through simple dependency injection. This means we can test rendering of Sanity components in UI Workshop (and similar) without having to rely on a connection to the Sanity backend.

fix(config): respect `unstable_clientFactory`

---

.babelrc
package.json
packages/sanity/package.config.ts
packages/sanity/package.json
packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx
yarn.lock

The `babel-plugin-lodash` optimization appears to no longer be working. Look at the output of [`lib/router.esm.js` for example](https://unpkg.com/browse/sanity@3.0.6/lib/router.esm.js) and how it have this output:
```js
import { intersection, difference, pick, isPlainObject, flatten, identity } from 'lodash';
```
This PR fixes it so that it generates this output:
```js
import flatten from 'lodash/flatten.js';
import difference from 'lodash/difference.js';
import intersection from 'lodash/intersection.js';
import isPlainObject from 'lodash/isPlainObject.js';
import pick from 'lodash/pick.js';
import identity from 'lodash/identity.js';
```
This also fixes the ESM URL use case:
```js
const {renderStudio} = await import('https://esm.sh/sanity') // Use `https://esm.sh/sanity@3.0.6` to …
```

fix: optimize lodash imports

---

packages/sanity/src/_internal/cli/threads/getGraphQLAPIs.ts

When you want to deploy a GraphQL API, we should only require you to define a workspace name if you have multiple defined. There was a check for this, but it mistakenly checks for more than zero instead of more than one. This PR fixes this check.
- `sanity graphql deploy` with a single workspace does not throw an error
- `sanity graphql deploy` with multiple workspaces throws an error if no `workspace` name is given in GraphQL config
- Fix issue where you had to provide a workspace name to deploy GraphQL APIs, even if only a single workspace was defined

fix(cli): only require workspace name if more than 1 workspace

---

.gitignore
packages/@sanity/block-tools/src/HtmlDeserializer/rules/html.ts
packages/@sanity/block-tools/test/tests/HtmlDeserializer/lists/input.html
packages/@sanity/block-tools/test/tests/HtmlDeserializer/lists/output.json

This fix has [previously been released in v2](https://github.com/sanity-io/sanity/pull/3492). There's some work to add it to v3 in the [chore/sc-21163/cherry-pick-changes-for-v3-on-next](https://github.com/sanity-io/sanity/compare/chore/sc-21163/cherry-pick-changes-for-v3-on-next) branch, but it has not yet been merged.
***
This fixes a bug where p-tags (and other block elements) inside li elements where incorrectly hoisted out of the li element.
With this change blocks are ignored, and block children are added directly to the listItem instead.

fix(block-tools): ignore blocks inside list items (#3492)

---

packages/sanity/src/core/util/draftUtils.test.ts
packages/sanity/src/core/util/draftUtils.ts

Quite often I find myself needing to see if two documents/document IDs are the same, if you disregard their draft status. While you can use `getPublishedId()` manually and compare the two, it is _just_ a bit too repetetive for my taste. This PR adds a new `documentIdEquals()` method which does this comparison. I'm not sure on naming. Other alternatives could be:
- `documentIdsAreEqual()`
- `documentIdsEqual()`
- `documentIdsRepresentSameDocument()`
- `documentIdsAreEqualIfYouDisregardTheirPublishedStatus` (yes that was a joke)
Another alternative would be to just live with having to do the `getPublishedId()` calls manually, but in this case we should at least make the method public (it is currently set as internal).
- Naming
- Implementation
- Tests
- Added a new `documentIdEquals` …

feat(core): add new `documentIdEquals` utility method

---

dev/test-studio/package.json
packages/@sanity/vision/package.json
packages/@sanity/vision/src/components/VisionGui.tsx
yarn.lock

Two `@sanity/vision` related changes:
- Currently has `@sanity/client` and `rxjs` listed as peer dependencies. We are importing types using `import type`, and otherwise not using these modules directly. It is therefore not correct to flag them as peer dependencies. Additionally, studios don't install these dependencies directly, so they will give off warnings about missing dependencies, which is very unfortunate.
- `react-split-pane` does not seem to be maintained anymore, and has react 16 as its supported peer dependency range. This leads to peer dependency warnings when installing the vision plugin. It works just fine with React 18 however, so I have forked the module and updated the peer dependency range to `^18`. Ideally we should replace the library with something different, but I …

chore(vision): use react 18 compatible dependencies

---

packages/sanity/src/core/config/__tests__/resolveConfig.test.ts
packages/sanity/src/core/config/prepareConfig.ts

We were attempting to collect/batch as many errors as possible before showing them. However, when resolving tools and templates, we try to access the resolved `tools` property as if we could guarantee it was a valid array. This would fail if (for instance) the `tools` property was an object instead of an array.
This PR changes to throwing early - which I don't think should be a huge step back in any way, and will fix cases where users instead got an error with message `cannot read properties of undefined (reading 'some')` and similar.
- Resolving configuration still works as expected
- Defining an object or non-array property for `tools` will give the intended error
- Fixed error where providing an invalid `tools` configuration property would not provide a readable error

fix(config): throw error early if tools/template resolution fails

---

packages/sanity/src/core/config/components/useMiddlewareComponents.ts

This PR fixes an issue in the components API. Since middleware chain in the components API is executed backwards, we need to reverse the list of configs before passing it to the middleware creator. This is important because we want the order of the components API to be consistent with the order of the other APIs.
Make sure that the order of the components API is consistent with other APIs and that it works as expected. 
Fix components API execution order

fix(core): components API execution order

---

packages/sanity/src/desk/panes/documentList/DocumentListPane.tsx
packages/sanity/src/desk/panes/documentList/constants.ts
packages/sanity/src/desk/panes/documentList/useDocumentList.ts

Custom sorts were broken and document list would not update with the correct sort order when changing sort order from the pane menu. 
Make sure that ordering works as expected
- Fixed an issue where custom sort orders were broken

fix(desk): use custom sort order by default and only use defaultOrdering as fallback

---

dev/test-studio/components/Branding.tsx
packages/sanity/src/core/studio/components/navbar/LogoButton.tsx
packages/sanity/src/core/studio/components/navbar/StudioLogo.tsx

This pull request moves the padding from the button that wraps the logo in the navbar to the default logo component. 
**Why?**
Today, if you configure a custom logo component, the navbar often becomes unnecessarily large because you have to render the logo inside a button with padding. By removing the padding from the button that wraps the logo, it is up to the implementation of the custom logo to decide how big the logo/button should be.
n/a
The default button padding surrounding the logo component is now gone. This means that the custom logo component now fully controls the size of the navbar button. Therefore, it may be necessary to update the custom logo component with padding. Below is an example of how to reproduce the same result as before:
```tsx
import {defineConfig} from …
```

fix(core): update logo 

---

packages/sanity/src/core/form/inputs/SelectInput.tsx

Pass on `readOnly` property to the `Select` element.
Check that read only works as intended for string input with select layout.
Bugfix: pass `readOnly` to select element

fix: pass `readOnly` to select element

---

packages/@sanity/cli/src/actions/init-project/bootstrapTemplate.js
packages/@sanity/cli/src/versionRanges.js

When bootstrapping new studios using the Sanity v2 CLI, you currently get the following error:
> Error: No "sanity.json" file found in plugin "@sanity/vision"
This is caused by the CLI installing the v3 version of `@sanity/vision`, because we specify that we want `latest`. Theoretically all the other dependencies have the same issue - the only reason they work is because we no longer use these modules in v3, and so `latest` still points to the v2 version.
This PR changes to use version ranges (`^2.0.0`) for everything (and drops resolving the latest version, since it is irrelevant), which should ensure that even if we _do_ release new versions of these packages, it won't break anything in v2 studios.
[sc-28222]
- You are able to bootstrap new v2 studios with v2 dependencies
To test:
- …

fix(cli): specify 2.x version ranges for dependencies

---

package.config.ts
package.json
packages/@sanity/block-tools/.depcheckignore.json
packages/@sanity/cli/.depcheckignore.json
packages/@sanity/diff/.depcheckignore.json
packages/@sanity/mutator/.depcheckignore.json
packages/@sanity/portable-text-editor/.depcheckignore.json
packages/@sanity/schema/.depcheckignore.json
packages/@sanity/server/.depcheckignore.json
packages/@sanity/types/.depcheckignore.json
packages/@sanity/util/.depcheckignore.json
packages/@sanity/validation/.depcheckignore.json
packages/@sanity/vision/.depcheckignore.json
packages/groq/.depcheckignore.json
packages/sanity/.depcheckignore.json
packages/sanity/package.config.ts
packages/sanity/package.json

The fix in #3974 were not sufficient. 
Running this:
```js
const {renderStudio} = await import('https://esm.sh/sanity@3.1.0')
```
Throws:
```js
Uncaught SyntaxError: The requested module '/v99/lodash@4.17.21/es2022/lodash.js' does not provide an export named 'flatMap' (at schema.js:formatted:2:178)
```
This is because only `sanity` is optimizing lodash imports, and other packages [like `@sanity/schema` aren't](https://unpkg.com/browse/@sanity/schema@3.1.0/lib/_exports/index.esm.js).
Since it's just an optimisation step it shouldn't break any existing behaviour or introduce new behaviour, beyond a smaller bundle size.
- fix: optimize lodash imports in the rest of the monorepo packages (`@sanity/schema` and more)

fix: ensure lodash is optimized in every monorepo package

---

packages/sanity/src/core/config/prepareConfig.ts

The official [Custom Asset Sources guide for turning off file uploads and only use external sources doesn't work](https://www.sanity.io/docs/custom-asset-sources#8a7448076430:~:text=directUploads%3A%20false%2C). It's because internally we have a typo causing `config.form.file.directUploads` to apply for `image` while it should only apply to `file`.
A config like:
```js
import {defineConfig} from 'sanity'
import {deskTool} from 'sanity/desk'
import {unsplashAssetSource} from 'sanity-plugin-asset-source-unsplash'
import {schemaTypes} from './schemas'
name: 'default',
projectId: '<projectId>',
dataset: 'production',
plugins: [deskTool()],
form: {
image: {
assetSources: () => [unsplashAssetSource],
directUploads: false,
},
},
schema: {
types: schemaTypes,
},
}) …
```

fix: apply `config.form.image.directUploads`

---

packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts

There was a regression in 3.1.0 where `clientFactory` was added to the `createAuthStore` options. This option should be optional. Addresses and closes https://github.com/sanity-io/sanity/issues/4007.

fix: `clientFactory` should be optional

---

packages/sanity/src/core/form/inputs/PortableText/text/Style.tsx
packages/sanity/src/core/form/types/definitionExtensions.ts

We recently introduced a regression where a custom style in the PT-input  would error if no render component was defined for that custom style. 
Before (v3.0.6) we rendered the Normal style in that case, and we should continue to do that in order to no break this behaviour unnecessary.
Also there was a goof which removed the optionality of the `.component?` schema prop for that style (also relevant for decorators and list items).
Regression commits:
https://github.com/sanity-io/sanity/commit/0902fa59ab0b2648ad1e80a01ba86cfc7e000820
https://github.com/sanity-io/sanity/commit/f1152f740a3427cb4eaeb731402d031dd0377437
Fixed a regression where a custom style in the portable text input would not fallback to be rendered as the normal style without defining a rendering-component for that style.

Fix fallback render issue with custom PT-styles

---

packages/@sanity/base/src/preview/availability.ts

Our previous approach of chunking document availability requests did not wait for all the chunks to finish before returning the results. The `debounceCollect` utility expects an observable that returns all results in one go, but because we returned a stream that would emit the chunks one-by-one as they arrived, we would only handle the first emission, which would not include the whole result set, breaking assumptions further down the line.
This patch fixes the issue by reducing over each emission, successively add them to an array. (the `reduce` operator will wait for the stream to finish before emitting a single reduced value).
- Check that code looks ok
- Make sure existence validation works as before
- Make sure chunked existence requests are handled properly (this is rather tricky to …

fix(base): wait for all chunked requests to arrive before continuing

---

packages/sanity/src/desk/documentActions/HistoryRestoreAction.tsx

This PR removes the restore document action when the revision is the latest version. Currently, the restore action is always available, even when the document cannot be restored.
Make sure that the restore action is not visible when revision id is the latest version
n/a

fix(desk): remove restore action when revision is latest version

---

CONTRIBUTING.md

This PR modifies `CONTRIBUTING.md`, fixing some typos and updating references from npm script commands to yarn commands.
See if the changes from npm to yarn are appropriate. I assumed they were, especially since `yarn.lock` is present in the repo.
Probably won't need a release. It's just internal documentation changes.

docs: fix typos and update npm->yarn in CONTRIBUTING

---

packages/sanity/src/core/form/store/useFormState.ts
packages/sanity/src/core/hooks/useConnectionState.ts
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx

This PR makes the form read-only when reconnecting to avoid unexpected behavior. Since the Studio is not fully functional when offline yet, this ensures that the connection is ready before allowing changes to be made.
This PR also adds missing dependencies in the `useFormState` and `useConnectionState` hooks.
- Review the code
- Make sure that it works as expected
n/a

fix(desk): set the form to read-only when reconnecting

---

packages/sanity/src/core/studio/components/navbar/NewDocumentButton.tsx

This PR adds a default icon to the items in the new document dialog. This is a regression in v3.
n/a
n/a

fix(core): add default media to new document dialog previews

---

packages/@sanity/cli/test/graphql.test.ts
packages/sanity/src/_internal/cli/actions/graphql/deployApiAction.ts
packages/sanity/src/_internal/cli/actions/graphql/getGraphQLAPIs.ts
packages/sanity/src/_internal/cli/commands/graphql/deployGraphQLAPICommand.ts

This PR reintroduces the `--playground`, `--generation` and `--non-null-document-fields` flags for the `sanity graphql deploy` command. While they ideally should still be configured in `sanity.cli.ts`, it seemed somewhat arbitrary which flags we allowed and did not allow.
With a hopefully clear message during deployment, we will allow using these flags, but indicate that they apply to _all_ defined GraphQL APIs.
While researching this, I also discovered that we were requiring a `projectId` and `dataset` to be defined in the CLI configuration, which is unnecessary as we are extracting this from the studio source configuration anyway. I have thus removed this requirement, which also means you can run `sanity graphql deploy` without a CLI configuration file present - same as in v2.
- `sanity …

fix(cli): reintroduce deprecated graphql deployment flags

---

packages/@sanity/types/src/schema/definition/type/array.ts
packages/@sanity/types/src/schema/definition/type/date.ts
packages/@sanity/types/src/schema/definition/type/datetime.ts
packages/@sanity/types/src/schema/definition/type/geopoint.ts
packages/@sanity/types/src/schema/definition/type/number.ts
packages/@sanity/types/src/schema/definition/type/string.ts
packages/@sanity/types/src/schema/test/array.test.ts
packages/@sanity/types/src/schema/test/date.test.ts
packages/@sanity/types/src/schema/test/datetime.test.ts
packages/@sanity/types/src/schema/test/number.test.ts
packages/@sanity/types/src/schema/test/string.test.ts
packages/@sanity/types/src/validation/types.ts

Currently, the following schema definition is allowed by TypeScript:
```ts
const product = defineType({
name: "product",
type: "document",
fields: [
{
name: "compareAtPrice",
type: "number",
validation: (Rule) => Rule.greaterThan(Rule.valueOfField("price")),
},
// ...
],
})
```
But the following, with only the addition of the `defineField` call, is not allowed*:
```ts
const product = defineType({
name: "product",
type: "document",
fields: [
defineField({
name: "compareAtPrice",
type: "number",
validation: (Rule) => Rule.greaterThan(Rule.valueOfField("price")),
}),
// ...
],
})
```
<details><summary><i>* There are cases where that same call is allowed, such as under a `defineConfig` or `definePlugin` call</i></summary>
```ts
const config = defineConfig({
// ...
schema: {
types: [
{
type: …
```

fix: allow use of `Rule.valueOfField` inside fields using `defineField`

---

packages/sanity/src/core/form/studio/assetSource/AssetThumb.tsx

There was a bug with the dropdown of uploaded images. It wasn't possible to access the dropdown to delete uploaded images. 
https://user-images.githubusercontent.com/44635000/210981806-110dca30-4c52-4c62-9199-af5e33c12279.mp4
Try to delete an uploaded image. Make sure the dropdown works as intended. 
Fix(core): uploaded images popover accessibility

fix(core): uploaded images popover display

---

dev/test-studio/package.json
package.json
packages/@sanity/cli/package.json
packages/@sanity/import-cli/package.json
packages/@sanity/import/package.json
packages/@sanity/portable-text-editor/package.json
packages/@sanity/types/package.json
packages/@sanity/validation/package.json
packages/@sanity/validation/src/validateDocument.ts
packages/@sanity/vision/package.json
packages/sanity/package.json
packages/sanity/src/_internal/cli/util/getStudioConfig.ts
packages/sanity/src/core/config/__tests__/resolveConfig.test.ts
packages/sanity/src/core/config/prepareConfig.ts
packages/sanity/src/core/config/resolveConfig.ts
packages/sanity/src/core/preview/observeFields.ts
packages/sanity/src/core/preview/utils/props.ts
packages/sanity/src/core/search/weighted/createWeightedSearch.test.ts
packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts
packages/sanity/src/core/store/_legacy/document/document-pair/validation.test.ts
packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts
packages/sanity/src/core/store/_legacy/grants/__tests__/createGrantsStore.test.ts
packages/sanity/src/core/store/_legacy/grants/__tests__/templatePermissions.test.ts
packages/sanity/src/core/studio/components/navbar/changelog/module-status/moduleStatus.test.ts
packages/sanity/src/desk/components/deskTool/intentResolver/utils.ts
packages/sanity/src/desk/structureResolvers/createPaneResolver.ts
packages/sanity/src/desk/structureResolvers/resolveIntent.ts
packages/sanity/src/desk/types.ts
yarn.lock

This PR upgrades RxJS in various packages from v6 to v7. I think we can feel reasonably confident that everything works as before given that we know of several clients that have already been using the Studio with rxjs@7 in production. I've also done a fair share of manual testing and haven't found any issues. Also, all tests are passing.
The code modifications are done mainly to pass the type checker and to remove usage of methods that's been deprecated in rxjs@7
Note: This branch is using tagged releases of `@sanity/client` and `@sanity/bifur-client`. I will promote these to relases for on monday and update the package.json's here accordingly.
- Make sure Studio works exactly as before 😅 
- Upgrade RxJS to v7
This can in some cases cause build errors due to the Observable interface …

chore: upgrade rxjs to v7

---

dev/test-studio/schema/debug/fieldGroups.js
dev/test-studio/structure/resolveStructure.ts
packages/sanity/src/desk/panes/document/DocumentPane.tsx

This supersedes #4038 and fixes the root cause of the issue described in https://github.com/sanity-io/sanity/discussions/3794
Background: when switching between documents, form state like expanded/collapsed state, field group selection etc. is preserved. This means that e.g. the field groups you have selected in one document will be kept selected if you switch to another document of the same type. This is argueably a _feature_ and makes it easier to edit a field that is normally hidden behind field groups across many documents without having to drill down into the field group every time you go to the next document (That said, I can see that it is can also be a bit _unexpected_ behavior).
In any case, when switching between two documents of _different_ types, this can in some cases trigger …

fix(desk-tool) invalidate form state between different document types

---

packages/@sanity/schema/src/sanity/validation/types/file.ts
packages/@sanity/schema/src/sanity/validation/types/image.ts

Link to story: https://app.shortcut.com/sanity-io/story/22859/schema-validation-disallow-already-defined-fields-on-image-file 
Schema validation: Disallows field names `'asset', 'hotspot', 'crop'` for type `Image`, and `'asset'` for type `File`. 
Add invalid field names for the type `Image` or `File` in the schema to see the error message. 
Fix(schema): Schema validation: Disallow already defined fields on `image`, `file`

fix(schema): Disallows fieldnames that are already defined

---

packages/sanity/src/desk/panes/document/statusBar/sparkline/DocumentSparkline.tsx

This PR fixes so that the "saved" status in the document footer can only be set when the document is not syncing. This is done by using the boolean returned from the `useSyncState` hook when deciding whether to allow the state to be set to "saved". There have been reports of the "saved" status being displayed even though the document was not actually saved due to poor network connectivity.
- Make sure that the document status indicator works as before
n/a

fix(desk): improve saving indicator

---

packages/sanity/src/core/form/useFormValue.ts

This PR simplifies and fixes an issue with `useFormValue` hook lagging one iteration behind
Test the hook and make sure you get value that is up to date
Fix issue with `useFormValue` lagging one iteration behind

fix(core): `useFormValue` lagging one iteration behind

---

packages/groq/node/groq.mjs
packages/groq/package.json

The `3.2.0` release of `groq` yesterday introduced a regression bug that breaks Node.js ESM runtimes that makes calls like these:
```js
import groq from 'groq'
// throws `TypeError: groq__WEBPACK_IMPORTED_MODULE_1__.default is not a function` in Next.js apps at runtime
```
It's because `@sanity/pkg-utils` are only able to generate re-exports that are named, default exports aren't handled:
https://unpkg.com/browse/groq@3.2.0/lib/groq.cjs.mjs
Projects that use `import {groq} from 'next-sanity'` are unaffected as `next-sanity` is shipping its own ESM to CJS Node.js wrapper.
- fix: regression in `groq@3.2.0` that is missing a default export affecting Node.js ESM runtimes.

fix: add missing default export to `groq` for the `node` ESM wrapper

---

packages/groq/package.json

The #4085 doesn't work because I forgot to add `node` to the `pkg.files` list, so the fix isn't included in the published package on npm 😭 
- fix: the `groq` hotfix in `v3.2.1` is missing from npm as since it's not declared in the `pkg.files` allowlist. It's included now in `v3.2.2`. But since publishing JS is a bit like quantum physics it might still be missing. If that's the case then by the time you read this message we'll already be working on a `v3.2.3` release 🫣

fix: add the node folder to the npm publish allowlist

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/editor/PortableTextEditor.tsx
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPatches.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPlaceholderBlock.ts
packages/@sanity/portable-text-editor/src/utils/patchToOperations.ts
packages/@sanity/portable-text-editor/test/__tests__/writingTogether.collaborative.test.ts

There is an issue in the PTE where if you have editor A and editor B, and A deletes all the content, a raise condition may occur:
If client B receives the deletion, and afterwards client A writes in new content - this initial block is duplicated in client B's editor and we risk a duplicate keys error in all clients as the duplicated blocks are already propagated to the document store through patching being done by client B.
The reason this happens is because we had an invalid test for equality between the server value and the editor state in the case where the editor value is longer (array) than the server value. To add to the problem there are also side effects by creating the placeholder block (a non existing block for the user to type into in an empty editor) by text operations which …

Fix duplication of initial block in empty PTE

---

packages/@sanity/portable-text-editor/src/editor/PortableTextEditor.tsx
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPatches.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPlaceholderBlock.ts
packages/@sanity/portable-text-editor/src/utils/patchToOperations.ts
packages/@sanity/portable-text-editor/test/__tests__/writingTogether.collaborative.test.ts

This is a backporting of the fix that was done for v3 (https://github.com/sanity-io/sanity/pull/4049) 
There is an issue in the PTE where if you have editor A and editor B, and A deletes all the content, a raise condition may occur:
If client B receives the deletion, and afterwards client A writes in new content - this initial block is duplicated in client B's editor and we risk a duplicate keys error in all clients as the duplicated blocks are already propagated to the document store through patching being done by client B.
The reason this happens is because we had an invalid test for equality between the server value and the editor state in the case where the editor value is longer (array) than the server value. To add to the problem there are also side effects by creating the …

fix(pte): duplication in pte, backport to v2 from v3 fix

---

packages/groq/node/groq.mjs
packages/groq/package.json
packages/groq/test/groq.test.cjs
packages/groq/test/groq.test.mjs

Third time's the charm.
- fix: issue in the Node.js runtime wrapper causing the `groq` tagged template literal to sometimes be undefined

fix: actually fix the `groq` bug and include tests that prove it

---

packages/sanity/src/core/form/inputs/PortableText/text/Style.tsx
packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.styles.ts
packages/sanity/src/core/form/inputs/PortableText/text/textStyles.tsx

The background for this PR is that we needed to wrap all text content inside the Portable Text Editor as @sanity/ui text for them to render properly in the editor. When a Sanity/UI Text element was missing, the text would be impossible to put the cursor in by the mouse, and the text were hidden behind the error/warning overlay when those were displayed.
We can not require that the implementor of a custom style component knows about, or should need to care about using Sanity/UI texts in their custom components. Currently we have worked our way around t his by wrapping the custom component in a Text. But this causes issues the moment you would like to use like a Sanity/UI `Heading` in your custom component (`Text` takes presedence).
The problem turned out to be an issue with the z-index on …

fix(form/inputs): fix issues with custom style component rendering 

---

packages/sanity/src/_internal/cli/server/getStudioEnvVars.ts
packages/sanity/src/_internal/cli/server/getViteConfig.ts

Supersedes #3620 - the previous approach warned when using `process.env`, this one actually defines the environment variables as `process.env.SANITY_STUDIO_X`.
Rationale:
- There is no standard for environment variables across environments.
- Node.js uses `process.env`.
- Vite uses `import.meta.env`.
- Deno uses `Deno.env`.
- Cloudflare workers uses global variables.
- Sanitys tooling runs on Node.js. It is difficult/annoying to write things like configuration files, where they need to work on both the server/cli and on the client side.
- By defining these as `process.env.SANITY_STUDIO_X`, they are both accessible as `import.meta.env.SANITY_STUDIO_X` _and_ under `process.env`. This means that you can use the `process.env` approach in configuration files and (if you want/need to) use …

feat(server): support studio env vars through `process.env`

---

packages/sanity/src/core/form/inputs/files/FileInput/FileActionsMenu.tsx
packages/sanity/src/core/form/inputs/files/FileInput/FileInput.tsx
packages/sanity/src/core/form/inputs/files/ImageInput/ImageActionsMenu.tsx
packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx

Fixed issue where when an image was uploaded, it was not possible to upload a new image to replace the existing one. This had to do with the popover disappearing after clicking on `Upload` in the dropdown menu, resulting in a `No file chosen` error. 
Also renamed `FileDetails` to `FileActionsMenu` to match the similar file used for `Image` uploads, as these files have similar functions for uploading files/images.  
Go to an `Image` field and try to upload a new image, overwriting an existing image that is uploaded. 
Fixed issue with replacing an image in an `Image` field.

fix(core): popover wrap button to allow replacing uploaded image

---

packages/sanity/src/desk/panes/document/timeline/__workshop__/DefaultStory.tsx
packages/sanity/src/desk/panes/document/timeline/__workshop__/index.ts
packages/sanity/src/desk/panes/document/timeline/timelineItem.styled.tsx
packages/sanity/src/desk/panes/document/timeline/timelineItem.tsx
packages/sanity/src/desk/panes/document/timeline/timelineMenu.tsx

V3 port of #3628 with a few minor differences:
- Tooltips are now correctly nested inside (and not around) `MenuItem` components
- This was previously causing an issue where tooltips were appearing immediately when the Menu was opened, and other odd side-effects (tooltip not appearing on hover)
- History timeline menu can now be dismissed with ESC
- Added workshop story
- The document history timeline now displays full dates in tooltips on hover

fix(desk): add full timestamp tooltip to timeline items

---

packages/@sanity/cli/src/commands/init/initCommand.ts

When running `sanity init` with the v3 CLI, you will be prompted with a warning indicating you're following v2 installation instructions, and a confirmation prompt will ask the user whether or not to continue initing with a v3 studio. When answering "no" on this dialog, the CLI still continues the init process as if answering yes, however.
This PR fixes this issue, and also adjusts the border look of the message/warning dialog to match branding guideline. Also reduces the amount of nested code - apologies for hard to read diff, but code shouldn't be too hard to follow.
- `sanity init` will show prompt
- answering no will exit
- answering yes will continue
- Fixed an issue where answering "no" when being asked whether or not to create a new v3 project would not actually stop the init …

fix(cli): exit if user does not confirm v3 init continuation

---

packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx

Dragging image lead to unexpected behaviors. 
When dragging an uploaded image, an unexpected error message occurred (see video). 
https://user-images.githubusercontent.com/44635000/213460396-2f1e8dc9-083f-4151-b4c4-04cf528ea6ce.mov
By removing the file kind of `string` from the `hoveringFiles` array, the current image that is uploaded is excluded and does not trigger the error message when hovering. 
- Add an image to an image input.
- Drag the same image over the image input.
Fixes error message triggering when hovering already uploaded image.

fix(core): remove uploaded image from hoveringFiles

---

packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx

The action dialog should say "unpublish" and not "delete" when you unpublish a document. 
Changed to use `action` instead of hardcoded `delete`.
https://github.com/sanity-io/sanity/issues/4063
Try to unpublish/delete document and see that the text is correct.

fix(desk): Change hardcoded delete word in action dialog to the correct action

---

dev/test-studio/schema/standard/references.ts
packages/sanity/src/core/form/inputs/ReferenceInput/CreateButton.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx

An empty read-only reference field should not show the dropdown and be able to set a reference. It should be read-only for an empty field as well.
https://user-images.githubusercontent.com/44635000/214015457-2dda9a5c-74e2-479c-83db-7f590629afb1.mov
https://github.com/sanity-io/sanity/issues/3947
Added `readOnly` field for the `ReferenceAutocomplete`.
- Make sure that it truly is read-only for the field - both when empty and when there is a reference
Fixes bug where the read-only reference field was not read-only for empty field

fix(core): add readonly prop to RefenceInput

---

packages/sanity/src/core/studio/screens/ConfigErrorsScreen.tsx
packages/sanity/src/core/studio/workspaceLoader/WorkspaceLoader.tsx

Cleaning up unused code that was related to a error config message.
This no longer happens as the studio lets you know what has gone wrong. Since we don't use it and the code is commented, I think it's best that we remove it!
Double check that the removal of the code is clean and won't affect other parts of the studio

refactor(core): remove commented code and deal with "todo" config error screen

---

packages/sanity/src/core/studio/components/navbar/search/definitions/operators/dateOperators.test.ts

This PR adds mocks all `new Date()` calls across all dateOperator tests
(None)

chore: use fake timers in dateOperator tests

---

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx

- Fixes an issue where clicking the **Open in new tab** button in reference inputs would crash the studio
- Previously, this was using `EditReferenceLink` (`ReferenceChildLink`) which is used to handle creating links that open to the right
- It now uses a regular `IntentLink` (similar to v2)
- Fixes an issue where clicking **Replace** in reference inputs would still retain the search query in the `ReferenceAutocomplete` component
- `ReferenceAutocomplete` now no longer receives a `value` prop, which I believe makes sense given that the autocomplete component isn't rendered when the field has a patched value (this is also the case in v2)
- Also removed unreachable states in the reference context menu (e.g. `value?._ref && isEditing`) as this menu will never be rendered if `isEditing = …

fix(core): clear reference fields when replacing links, fix open in new tab links

---

packages/@sanity/cli/test/shared/globalSetup.ts

Running the @sanity/cli tests locally without a `SANITY_CI_CLI_AUTH_TOKEN` specified currently triggers a bunch of test failures due to a missing tempdir, for example:
```
● Test suite failed to run
ENOENT: no such file or directory, open '/var/folders/0f/4jx7p3354q7f86_z629rjf440000gn/T/sanity-cli-test/test-id.txt'
3 |
4 | describeCliTest('CLI: `sanity dataset`', () => {
> 5 |   describe.each(studioVersions)('%s', (version) => {
|                                ^
6 |     const testRunArgs = getTestRunArgs(version)
7 |
8 |     testConcurrent('dataset create', async () => {
at test/dataset.test.ts:5:32
at Object.<anonymous> (test/dataset.test.ts:4:16)
```
This PR addresses it by making sure we create the tempdir before returning from the globalSetup. It seems to fixes it, but there might …

fix(tests): make sure cli tests don't crash if no token specified

---

packages/sanity/src/core/components/popoverDialog/PopoverContainer.tsx
packages/sanity/src/core/components/popoverDialog/PopoverDialog.tsx
packages/sanity/src/core/form/components/EditPortal.tsx

This pull request addresses several problems with the popover editing feature for array items.
**Context**
It is possible to configure an array field to use a popover instead of a dialog for editing items, as shown in the following code example:
```js
{
type: 'array',
name: 'myArray',
options: {
modal: {type: 'popover', width: 2}, // <-- 👈 edit inside a popover instead of a dialog
},
of: [
// fields...
]
}
```
**List of fixes:**
- Ensures that the width property functions as intended (currently the popover does not respect `width`)
- Restores focus on the array item upon closing the popover
- Traps focus within the popover content
- Includes a sticky header in the popover + header UI fixes
- Constrains the popover's size to the boundary element (i.e the form view)
- Makes the popover …

fix(core): array popover editing improvements

---

packages/sanity/src/desk/panes/document/statusBar/DocumentStatusBarActions.tsx

This PR fixes an issue with document actions dialog staying open after navigating to another document.
1. Go to a document
2. Open e.g the delete document dialog
3. Navigate to a another document
4. The dialog should close
n/a

fix(desk): close document actions dialog when changing document

---

dev/test-studio/sanity.config.ts
packages/sanity/src/core/config/prepareConfig.ts
packages/sanity/src/core/config/types.ts
packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts

This PR allows users to configure a custom API host for each source (usually for the entire studio, but it makes sense to do it on a source level, which workspaces inherit from). Enables the use of custom CNAMEs, which some of our customers have, as well as for testing purposes.
- Specifying API host makes studio use the configured host. Prefixes with project ID.
- Code makes sense
- A custom API hostname can now be configured for the studio through the `apiHost` configuration parameter. Note that the  configured API host must behave the same as Sanity's API, thus this is mostly useful for CNAMEs.

feat(config): allow specifying `apiHost` for source

---

package.json
scripts/setLatestForV2OnlyModules.js

When we run a v2 release, we now set the npm dist tag to `v2`. This is fine for the modules that are present in both v2 and v3, such as `@sanity/cli`, but it is unfortunate that new versions of 2.x modules are not set as `latest`.
This PR introduces a script which loops through all the modules in the `@sanity` packages folder, runs `npm view <pkgName> version` on them to see what the `latest` tag is set to on npm, and if that version is in the 2.x range, _and_ a _newer_ version is available locally (and is on the 2.x range) - it will set the `latest` tag on the npm module to the local version.
Kind of hacky, but think it should do the trick.
Also set this up as a post-publish task. 
Nothing. Transparent for the end user.

chore: add script for setting npm `latest` tag on v2 modules

---

packages/@sanity/block-tools/README.md
packages/@sanity/block-tools/test/fixtures/customSchema.ts
packages/@sanity/block-tools/test/fixtures/defaultSchema.ts
packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditorTester.tsx
packages/@sanity/portable-text-editor/src/utils/schema.ts
packages/@sanity/schema/example/test.js
packages/@sanity/schema/src/_exports/index.ts
packages/@sanity/schema/src/legacy/Schema.ts
packages/@sanity/schema/test/legacy/schemas.test.ts
packages/@sanity/validation/test/createSchema.ts
packages/@sanity/validation/test/infer.test.ts
packages/sanity/src/_internal/cli/actions/graphql/extractFromSanitySchema.ts
packages/sanity/src/core/form/__workshop__/_common/data.ts
packages/sanity/src/core/form/inputs/ReferenceInput/__tests__/ReferenceInput.test.tsx
packages/sanity/src/core/form/store/__tests__/collapsible.test.ts
packages/sanity/src/core/form/store/__tests__/equality.test.ts
packages/sanity/src/core/form/store/__tests__/members.hidden.test.ts
packages/sanity/src/core/schema/createSchema.ts
packages/sanity/src/core/search/weighted/createWeightedSearch.test.ts
packages/sanity/src/core/studio/components/navbar/search/datastores/recentSearches.test.ts
packages/sanity/src/core/studio/components/navbar/search/utils/createFieldDefinitions.test.tsx
packages/sanity/src/core/studio/components/navbar/search/utils/filterUtils.test.ts
packages/sanity/src/core/templates/__tests__/schema.ts
packages/sanity/src/desk/panes/documentList/__tests__/helpers.test.ts
packages/sanity/test/cli/graphql/fixtures/test-studio.ts

We want to move away from default exports, as they are hard to work with in a dual CommonJS/ESM environment. The schema package currently only exposes the `Schema` class on the default export. This PR moves the default Schema class export to a _named_ export (`Schema`), _and_ introduces a "deprecated" class for the default export, which only exists to warn about the deprecated default export.
I decided to warn with a stack trace to make it easier to find where the warning is appearing from.
- Use named export for the `@sanity/schema` module - the default export is now deprecated and will give a warning when used

refactor: use named export for schema package

---

packages/@sanity/schema/src/legacy/types/crossDatasetReference.ts
packages/sanity/src/_internal/cli/actions/graphql/extractFromSanitySchema.ts
packages/sanity/test/cli/graphql/__snapshots__/extract.test.ts.snap
packages/sanity/test/cli/graphql/__snapshots__/gen2.test.ts.snap
packages/sanity/test/cli/graphql/__snapshots__/gen3.test.ts.snap

While we do not currently support _resolving_ cross-dataset references in the GraphQL API, there is still a case to be made for retrieving the reference value so users may manually fetch the content. This also unblocks deploying APIs for schemas that uses cross-dataset references.
- Specifying dataset/project fields do not have any negative side effects on the studio side
- Allow fetching unresolved cross-dataset references through GraphQL API

feat(cli): provide unresolved cross-dataset references for GraphQL APIs

---

packages/sanity/src/core/form/components/tagInput/tagInput.tsx
packages/sanity/src/core/form/inputs/__workshop__/TagInputStory.tsx
packages/sanity/src/core/form/inputs/__workshop__/index.ts

This PR improves the read only visibility of the tags input array.
- Does the UI look good?
Improve read only visibility of tags array input

fix(core): improve read only visibility of tags array

---

packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts

This PR addresses an issue discovered when two browser windows are open in the same studio at the same time, where reloading one causes the other to re-render. The solution implemented in this PR is to only notify subscribers of the authentication stream when there is a change in the `currentUser` object by using the `distinctUntilChanged` operator to compare previous and next states.
1. Open the same studio in two different browser windows
2. Reload one of the browser windows
3. The studio in the other browser window should not re-render.
n/a

fix(core): only notify subscribers when `currentUser` value changes in `createAuthStore`

---

.github/workflows/test.yml
packages/@sanity/portable-text-editor/package.json
packages/@sanity/portable-text-editor/test/setup/collaborative.jest.env.ts
packages/@sanity/portable-text-editor/test/setup/globals.jest.ts
packages/@sanity/portable-text-editor/test/ws-server/index.ts
yarn.lock

This will replace Puppeteer with Playwright for doing the PTE collaboration tests as we are moving on to Playwright now anyway.
* Added Playwright as dep. removed Puppeteer.
* Added Github Action step to install Playwright deps on CI.
* Re-wrote the collaborative test Jest environment to use Puppeteer.
Please note that this PR is not targeting the `next` branch, but the `refactor/pte-various` - a working branch for a larger refactoring where I'll merge PR's limited in scope for easier reviewing - like this one.
Doesn't need to mentioned. Internal dev stuff.

Replace Puppeteer with Playwright for PTE-tests

---

.gitignore
package.json
playwright.config.ts
playwright/README.md
playwright/global-setup.ts
playwright/helpers/constants.ts
playwright/helpers/createUniqueDocument.ts
playwright/helpers/index.ts
playwright/helpers/sanityClient.ts
playwright/tests/default-layout/navbar.spec.ts
yarn.lock

Adds Playwright for e2e tests in the studio. A new PR will be created to remove Cypress and migrate existing tests if useful.
Make sure the config looks good.
- n/a

chore: configure playwright

---

packages/sanity/src/core/components/UserAvatar.tsx
packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx
packages/sanity/src/core/studio/components/navbar/presence/PresenceMenuItem.tsx

The LinkIcon for clickable users in the presence menu has been replaced with a new design. The users that are not clickable are now greyed out and has text under. Users that can be clicked on, are not. 
Click on the presence menu and make sure users that have a presence can be clicked on. 
Design change of the presence menu where non-clickable users are greyed out

fix(core): change design for clickable present users in dropdown

---

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/PreviewItem.tsx

It was possible to sort arrays and publish even when `readOnly` was set. Fixed by adding the prop `readOnly` to `sortable`. 
Add `readOnly` prop to an array and make sure it is not sortable. 
Disables sorting of arrays when `readOnly` is set.

fix(core): add readOnly prop to sortable array items

---

packages/sanity/src/_internal/cli/actions/graphql/gen1/generateTypeQueries.ts

We upgraded the `pluralize` module from v7 to v8 in studio v3 (technically speaking we replaced it with pluralize-esm, but the implementation mirrors pluralize v8), which seems to have changed a somewhat odd behavior where numbers would be suffixed with an uppercase S instead of the expected lowercase s.
To maintain backwards compatibility, we should make sure we match this old behavior. This PR addresses this. We do encourage moving to newer GraphQL API generations, since they are more featureful and do not make assumptions about pluralization, but we should still try to maintain gen1 as long as it is still in use.
- That code change makes sense (replace any digit followed by a lowercase S at the end of the string with the same digit, followed by a capital S)
- Fixed a bug where GraphQL …

fix(cli): maintain old pluralization behavior on graphql gen1 schemas

---

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceLinkCard.tsx

This PR fixes an issue where an error is thrown if a reference link is clicked while it is loading.
Click a reference link when it is loading. An error should not be thrown.
n/a

fix(core): invalid reference link

---

packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx
packages/sanity/src/desk/panes/document/documentPanel/documentViews/FormView.tsx

Adds focus to the first field when opening a document. This will be the case even if the field is `readOnly`. 
This also fixes the issue of a dialog in an array being open even after switching documents. It will also make the presence update when a user navigates to a document. 
- Open a document and see that the first field is focused. 
Also: 
- Open an array item popover in an array with `modal.type popover`
- Open another document from the document list
- Reopen the original document from the document list
- The popover is should not still be open
Adds focus to the first field in a document, close dialog when navigating documents

fix(desk): focusFirst in document and dialog behavior

---

packages/sanity/src/core/studio/screens/NoToolsScreen.tsx
packages/sanity/src/desk/components/deskTool/NoDocumentTypesScreen.tsx

This PR adds links to docs when there are no **schema** types or **tools** configured.
Are the links correct?
n/a

fix(desk): update tools and schema help links

---

packages/@sanity/cli/src/cli.ts

The `open` module tries to use the `SYSTEMROOT` environment variable on Windows, which seems to (sometimes?) not exist. Some backgrounds here: https://github.com/sindresorhus/open/pull/299
Sindre seems unwilling to fix in the `open` module, so I figure we might as well implement a workaround for it since it currently causes issues for onboarding of new users on Windows (the `login` action will fail when attempting to open a browser).
Fixes #4195
Fixes #4194
[sc-30570]
- Code looks reasonable (I haven't been able to reproduce/test this on Windows)
- Fixes an issue where opening a browser from the CLI tool on Windows might crash

fix(cli): patch missing `SYSTEMROOT` env var on windows

---

packages/sanity/src/core/studio/components/navbar/NavDrawer.tsx

This pull request fixes an issue where elements in the `NavDrawer` were focusable even though it was closed. The problem was caused by the `useRovingFocus` hook taking control of `tabIndex` which led to our own logic to set `tabIndex` to `-1` on elements being overridden by that hook.
The problem is fixed by using `AnimatePresence` so that the `NavDrawer` is only in the DOM when it is open, and replacing `useRovingFocus` with `FocusLock` (which is an already existing dependency).
- Make sure that the elements in `NavDrawer` is not focusable when it is closed
- Make sure that the `NavDrawer` works as before
n/a

fix(core): focus issue in nav drawer

---

packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
packages/sanity/src/core/store/_legacy/authStore/sessionId.ts

When configuring a custom API hostname to use for the studio, the current user and token exchange requests would fail, as they were not using the configured API hostname. This PR ensures all auth-related requests also use the configured API hostname.
Also did a small change to the session ID handling, in that the constant `sessionId` is no longer exported - it is now only available for consumption _once_ (using `getSessionId()`), since we should never rely on it outside of exchanging it for a token (which only happens once).
- Fixed authentication when using a custom API hostname

fix(auth): use configured api hostname for auth checks

---

packages/@sanity/base/src/datastores/user/createUserStore.ts
packages/@sanity/cli/package.json
packages/@sanity/cli/patches/webpack++terser-webpack-plugin+1.4.5.patch
packages/@sanity/cli/patches/webpack+4.46.0.patch
packages/@sanity/import/package.json

This PR fixes a few build issue in the v2 branch:
- The CLI cannot be built on recent versions of node because of webpack using md4, which has been removed from OpenSSL in later versions. I've added the `patch-package` dependency and patches needed to replace the hashes with md5. We only use it for building the CLI, so it is a devtooling issue only.
- The dataloader dependency has fixed their typings, so a `ts-expect-error` comment was now giving errors, as it no longer produced an error
- Node 18 was complaining when running tests, with the error "The "stream" argument must be an instance of Stream. Received an instance of Socket". I eventually managed to narrow it down to the `nock` dependency, which I've upgraded. This fixed the issue, and it is still compatible with node 12 (the …

chore: fix v2 build

---

packages/@sanity/structure/src/Document.ts
packages/@sanity/structure/src/DocumentList.ts
packages/@sanity/structure/src/util/resolveTypeForDocument.ts

This is a 2.x backport of #4244 that fixes the same issue
Builds on #4246 because the failing tests were driving me mad.
[sc-30793]
- Example URL that fails in `next`: https://test-studio-git-2x-next.sanity.build/test/desk/author;grrm;fed42f93-66c5-4a47-a4dd-2a03c965a021%2CparentRefPath%3DfavoriteBooks%5B_key%3D%3D%2297724180be7c%22%5D
- Should now resolve in preview build: https://test-studio-git-fix-structure-auto-resolve-type-2x.sanity.build/test/desk/author;grrm;fed42f93-66c5-4a47-a4dd-2a03c965a021%2CparentRefPath%3DfavoriteBooks%5B_key%3D%3D%2297724180be7c%22%5D
- Fixes an issue where the desk tool might crash if expanding a referenced document before its type was resolved

[v2] fix(desk): attempt to resolve missing document type automatically

---

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx

Previously, when a reference field with a filter function was opened, the function would only be triggered on the first occasion. However, with this fix, the filter function will be executed every time the select menu is opened.
Ensures that the filter function of a reference field is always executed upon opening of the select menu.

fix(core): ensure filter function on reference field is always fired when menu is opened

---

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx

The "Open in new tab" menu item on reference arrays is currently broken. It creates a link without a document ID, which fails in interesting ways. Judging by the `ReferenceField`, the intention is to use an intent link. This PR copies the code used in `ReferenceField` to restore the functionality of this item.
[sc-30793]
- Code makes sense
- Open in new tab button works as expected
Can be tested by going to the author type in the test studio, on some author that has an array of books.
- Fixed an issue where the "Open in new tab" menu item would not work on arrays of references

fix(core): restore "open in new tab" function for reference arrays

---

packages/sanity/src/desk/structureBuilder/Document.ts
packages/sanity/src/desk/structureBuilder/DocumentList.ts
packages/sanity/src/desk/structureBuilder/util/resolveTypeForDocument.ts

In some cases, a link will be generated that does not include a document type (because only the document ID is loaded until the document type has been resolved, for instance). When following the link, if the default document child resolver was used, it would throw an error. This PR improves on the situation by attempting to resolve the document type. If we're unable to find the document, we still throw - but otherwise we can recover from this state.
[sc-30793]
- Example URL that fails in `next`: https://test-studio.sanity.build/test/content/author;grrm;fed42f93-66c5-4a47-a4dd-2a03c965a021%2CparentRefPath%3DfavoriteBooks%5B_key%3D%3D%2297724180be7c%22%5D
- Should now resolve in preview build: https://test-studio-git-fix-structure-auto-resolve-type.sanity.build/test/content/author;grrm;fed42 …

fix(desk): attempt to resolve missing document type automatically

---

packages/sanity/src/core/store/_legacy/document/document-pair/consistencyStatus.ts
packages/sanity/src/core/store/_legacy/document/document-pair/documentEvents.ts
packages/sanity/src/core/store/_legacy/document/document-pair/editOperations.ts
packages/sanity/src/core/store/_legacy/document/document-pair/editState.ts
packages/sanity/src/core/store/_legacy/document/document-pair/memoizeKeyGen.ts
packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts
packages/sanity/src/core/store/_legacy/document/document-pair/operationArgs.ts
packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts
packages/sanity/src/core/store/_legacy/document/document-pair/remoteSnapshots.ts
packages/sanity/src/core/store/_legacy/document/document-pair/snapshotPair.ts
packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts
packages/sanity/src/core/store/_legacy/document/document-store.ts

Fixes issue where switching workspaces and navigating to document that shares the same id causes an error and didn't show document history
Fixes #3992
1. Fix issue where the memoizedPair did not account for sanity client config changing
2. Fix multiple levels of memoization for the `remoteSnapshots`
- Fix issue when changing workspaces on documents that have same id didn't show document history

fix(core): changing workspace with same document id causes error

---

packages/sanity/src/core/store/_legacy/user/userStore.ts

When a dataset is copied without history it stores userId as `<system>` which is not a valid userId. This change fixes studio to show a dummy user information when invalid ids are present.
- Does the logic make sense? Can it be simplified? 
-  I created a new variable for storing invalid userIds, it might be a little over engineered for now but it allows flexibility to handle similar cases in the future.
Fix crash in studio when viewing history for dataset that is copied without history

fix(core): fix crash when history does not include valid user information

---

dev/test-studio/schema/standard/references.ts
packages/@sanity/types/src/reference/types.ts
packages/sanity/src/core/form/inputs/ReferenceInput/useReferenceInput.tsx
packages/sanity/src/core/form/studio/inputs/crossDatasetReference/StudioCrossDatasetReferenceInput.tsx
packages/sanity/src/core/form/studio/inputs/reference/StudioReferenceInput.tsx

This PR adds the `getClient()` method to the context passed to reference filter resolvers.
Brings back functionality that was possible to do in v2, and does so in a way that is compatible with other v3 contexts.
[sc-25303]
[sc-25082]
- Changes makes sense
- Client can be retrieved (try asyncFilter example on reference test type - it might not return any results, but should not crash)
- Added `getClient()` method to reference filter context

feat(core): provide `getClient()` method to reference filter context

---

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx

Clears unused references in an array on blur and pressing escape key, this works in v2 so copied the same functionality
Copies the functionality from v2 not sure if this is the way to go about fixing the issue https://github.com/sanity-io/sanity/blob/f0eff1356962f376f1dd059e268d7d2b0aff7157/packages/%40sanity/form-builder/src/inputs/ReferenceInput/ArrayItemReferenceInput.tsx#L403-L414 
Fixes an issue where unused references get cleared on clicking outside the array input or pressing escape key

fix(core): clear unused references in an array

---

packages/@sanity/validation/src/validators/objectValidator.ts
packages/@sanity/validation/test/infer.test.ts

Shows validation error when missing `_ref` 
Reverts https://github.com/sanity-io/sanity/pull/2893/commits/e31d0c23248474228797d239e36c049f203edc62
Show validation error when missing `_ref` in array of items

fix(validation): show validation error for missing _ref

---

packages/sanity/src/core/store/_legacy/document/document-pair/operations/patch.ts
packages/sanity/src/core/store/_legacy/document/document-pair/operations/types.ts

As per the types it currently looks like providing a second argument to `patch.execute` is required when it isn't (passing `undefined` works because `{...undefined}` is valid)
This PR fixes modifies the typings to reflect this.
- Changed typings of `patch.execute()` to reflect that the second argument is optional

fix(core): fix typings to reflect that the second argument to patch.execute is optional

---

packages/sanity/src/core/form/inputs/InvalidValueInput/InvalidValueInput.tsx

When converting from array of references to a singular reference convert to reference would show which would convert it incorrectly making the document invalid
~I still kept `typeof value === 'object'` check to keep typescript happy~
Remove convert to reference button when converting array of references to singular reference

fix(core): remove button to convert to reference for arrays

---

packages/sanity/src/core/store/_legacy/user/__tests__/userStore.test.ts
packages/sanity/src/core/store/_legacy/user/userStore.ts

This PR ensures that `userStore.getUser()` catches 403 responses - needed when trying to fetch users when your current role doesn't have access to _project members_. Previously, this was crashing the studio when opening document history changes.
This only really affects `<UserAvatar>`, and the reason why presence doesn't crash in these instances is that it uses `DataLoader.loadMany()` under the hood, which handles responses containing errors a little differently ([they always resolve](https://github.com/graphql/dataloader#loadmanykeys)).
This is a quick fix, and in future we could potentially look to obviate these requests entirely if your role doesn't have sufficient access.
Opening document history shouldn't crash the studio when accessing the studio with a role that does not have read …

fix(core): handle 403 responses when calling `userStore.getUser()`

---

packages/sanity/src/desk/components/deskTool/DeskTool.tsx

On small screens, and when in a "split pane" mode, like an editor pane next to a preview pane, the Desk Tool will attempt to close the "preview" pane.
It fails, and it will instead close all panes as demonstrated in this Loom: https://www.loom.com/share/ab5675cf50d0427d9eefa9d722966ae6
I assume that the original idea was that on small screens we wanted you to end up on a view like:
As we don't support a "split pane" view on small screens, it's only ever 1 pane open and this is what a phone would see on the same URL as in the above Loom:
The above screenshot is what this PR will get you, instead of losing the state.
It's not super ideal, but it's better than window resizing potentially being a destructive action (as the pane collapsing is done as a URL redirect with `replace: true`, so you …

fix: preserve preview panes on small screens

---

packages/@sanity/types/src/schema/definition/type/common.ts

When building out _siteSettings.tsx_ and adding `hidden` to `groups` a TypeScript error is introduced:
> Type '{ title: string; name: string; hidden: () => boolean; }' is not assignable to type 'FieldGroupDefinition'.
Object literal may only specify known properties, and 'hidden' does not exist in type 'FieldGroupDefinition'.ts(2322
Screenshot:
Code example:
```
import { defineField, defineType } from 'sanity';
export default defineType({
name: 'siteSettings',
title: 'Site Settings',
groups: [
{ title: 'General', name: 'general', default: true },
{ title: 'Menu', name: 'menu' },
{ title: 'Footer', name: 'footer-settings' },
{ title: 'Default Meta Data', name: 'default-meta-data' },
{
title: 'foo bar',
name: 'foobar',
hidden: () => {
return …
```

fix(types): add `hidden` property to `FieldGroupDefinition`

---

packages/@sanity/portable-text-editor/src/editor/components/Element.tsx
packages/@sanity/portable-text-editor/src/editor/components/Leaf.tsx

These deprecated properties must be non-enumerable or the warning will be triggered when spreading props.

fix(portable-text-editor): make deprecated property non-enumerable

---

packages/sanity/package.json
packages/sanity/typings/eventsource.d.ts
yarn.lock

Upgrades the `@sanity/eventsource` version to `v5`, matching the version now used by `@sanity/client`.
In doing so we properly dedupe `eventsource`:
And it bumps `event-source-polyfill` to the latest stable.
Also, it now ships with typings so no need for the `eventsource.d.ts` file anymore.
The `npx @sanity/cli dataset copy` command is using `@sanity/eventsource` directly to measure progress. It should continue working. The remaining usage is by `@sanity/client` and `client.listen`. This PR updates `yarn.lock` with that version of the client (it's [`5.3.1`](https://github.com/sanity-io/client/releases/tag/v5.3.1)) so that we can test that `client.listen` related logic works fine.
fix: updated `EventSource` polyfills to latest stable versions

fix: upgrade `@sanity/eventsource`

---

packages/@sanity/portable-text-editor/src/editor/hooks/useSyncValue.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPatches.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithPlaceholderBlock.ts
packages/@sanity/portable-text-editor/test/__tests__/pasting.collaborative.test.ts
packages/@sanity/portable-text-editor/test/__tests__/writingTogether.collaborative.test.ts
packages/@sanity/portable-text-editor/test/setup/collaborative.jest.env.ts
packages/@sanity/portable-text-editor/test/setup/globals.jest.ts

This will fix an regression in the PT-input when pasting content into an empty editor.
This happened because a `set` patch was sent targeting a block before a `setIfMissing` and `insert` patch was made when inserting the fragment into the content. I have rewritten the patch creation logic a bit to be both safer (remove use of `unset`) and made sure that we avoid the premature patch problem.
I have also finally found a way to test native pasting into the editors, so I have added some basic tests for pasting also.
This will test that the user can successfully paste into the editor and the content is successfully updated elsewhere.
* That you can paste into an empty editor.
* That you can write into an empty editor.
* That yo can select all and paste over the existing content.
* That the …

Fix issue with pasting into empty PT-input

---

packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx

There is a regression introduced in `3.8.0` for Safari that hides the annotation edit popover when clicking to edit it. This is because Safari creates a new text range that isn't created by other browsers when clicking inside the popover on the button. This range is without focusNode and anchorNode and the popover is closed.
Fix this by requiring a focusNode to be set in the range before hiding the popover.
I also got rid of some tabbing logic that seems to no longer be needed as the content for the popovers are now rendered inside the node itself as opposed to earlier when it was rendered in a portal outside the editor.
* That you can edit annotations in all browsers.
* That you in all the supported browsers can tab to the edit button expect for Safari (which treats tabbing order …

fix(form/inputs): fix Safari issue with annotation edit popovers

---

packages/@sanity/cli/typings/getIt.d.ts

The `get-it` package is now shipping with typings, so it shouldn't be necessary to provide them here.
If TypeScript builds then we're in the clear.
N/A - internals only

chore(typings): remove `get-it` overrides

---

packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx
packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx

This fixes a recent regression where annotations within nested content (inside array items or simiar) was unable to be edited (it would not open the popover toolbar).
This happened because the path created for the `block.markDefs` object was sliced incorrectly, and it the member item with the element reference for the popovers could not be resolved, neither could the item be opened correctly by using said path.
* That objects can be properly edited within a PT-input that is nested inside other content (like array items).
* Fix issue where Portable Text annotations within nested content could not be properly edited.

fix(form/inputs): fix issues with opening annotations in the PT-input

---

dev/test-studio/structure/resolveStructure.ts
packages/@sanity/cli/typings/getIt.d.ts
packages/sanity/src/desk/panes/document/documentPanel/header/DocumentHeaderTitle.test.tsx
packages/sanity/src/desk/panes/document/documentPanel/header/DocumentHeaderTitle.tsx
perf/queries.ts
perf/tests/arrayOf1kReferenceItems.test.ts

Fixes an issue where the document title was not displaying when defined in the desk structure.
fixes #4079
fixes #4261 
Mimics logic from v2 https://github.com/sanity-io/sanity/blob/d57c92d0c00f70666234391fb9625ce6352ef05e/packages/%40sanity/desk-tool/src/panes/document/documentPanel/header/DocumentHeaderTitle.tsx#L22-L24
- Fixes an issue where the document title was not displaying when defined in the desk structure.

fix(core): fix document title not working

---

packages/@sanity/cli/test/basics.test.ts
packages/@sanity/cli/test/exec.test.ts
packages/@sanity/cli/test/shared/environment.ts

Current, the tests rely on running them with a specific test user token. With this change, the tests can be run as any admin user for the project. At some point we may want to make this even more configurable so external users can utilize their own projects here too, but will leave that for a separate PR.
None - internal change.

test(cli): resolve user email for configured test token

---

packages/@sanity/cli/test/datasetCopy.test.ts

Small change - dataset copying is one of the slower things we can test, but logically the only thing we want to test is that the commands can be run and spawns their tasks - not that the actual dataset copying completes. This changes to use the `--detach` flag, which immediately returns once the job has been registered with the backend.
Tests pass, that we cant think of any side effects
None

test(cli): use `--detach` for dataset copy for faster runs

---

packages/sanity/src/core/templates/__tests__/resolve.test.ts
packages/sanity/src/core/templates/resolve.ts

Adds `_type` when the initialValue is empty object when statically or in a function
Migrates https://github.com/sanity-io/sanity/pull/4346 to v3 as well as adds tests for it. Let me know if the test structure makes sense
Fixes permission issue when initialValue is set to empty object

fix(core): fix permissions when initialValue is empty object

---

packages/@sanity/cli/src/types.ts
packages/@sanity/cli/typings/vite.d.ts
packages/sanity/src/_internal/cli/server/buildStaticFiles.ts
packages/sanity/src/_internal/cli/server/devServer.ts
packages/sanity/src/_internal/cli/server/getViteConfig.ts
packages/sanity/src/_internal/cli/server/previewServer.ts

- (Fix?) Respect user configuration when running `sanity preview`
- Allow user to pass configuration object that will be merged into default Vite configuration
- Align user configuration function with Vite's API by [passing context as second argument](https://vitejs.dev/config/#conditional-config) and accept a Promise:
```ts
import {defineCliConfig} from 'sanity/cli'
import {mergeConfig} from 'vite'
export default defineCliConfig({
// ...rest of config
async vite(config, {command, mode}){
const target = await getProxyTarget()
return mergeConfig(config, {
server: {
proxy: {
"/api": {
target,
changeOrigin: true,
secure: false,
rewrite: (path) => path.replace(/^\/api/, ""),
},
},
},
})
}
})
```
1. Bootstrap a new Sanity Studio v3 project, with TypeScript
2. In `sanity.config.ts` add a `vite` …

feat(cli): merge user vite config object

---

packages/@sanity/portable-text-editor/src/utils/__tests__/patchToOperations.test.ts
packages/@sanity/portable-text-editor/src/utils/operationToPatches.ts
packages/@sanity/portable-text-editor/src/utils/patchToOperations.ts

Values inside void objects (block objects or inline blocks) are not the editor's responsibility to deal with, and the data doesn't interfere with the editor's selection state.
Just ignore these kind of patches. They are not edited by the editor.
`useSyncValue` will make sure to update this content when it's changed anyway.
Started out by making a failing test for this which is now passing.
There are no issues with this with normal usage of the editor, however if you send external patches to the document, the editor might crash because how it acts these patches.
* That all regular text editing operations works as they should (should be covered by tests pretty good).
Doesn't need to be mentioned I think. Doesn't affect normal/expected usage.

refactor(portable-text-editor): ignore void edits

---

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItemRefProvider.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/useReferenceItemRef.ts

This PR fixes issue where unused references don't clear when clicked outside which works in v2. This second attempt makes sure that the options menu works as intended and does not trigger cancel when clicking on actions like duplicate, etc.
https://user-images.githubusercontent.com/6476108/231271452-62208359-e99e-40c4-abd5-624e919b5cfe.mov
The solution to fix this isn't ideal IMO but it is the only way I can think this could work. Since the ReferenceInput and ReferenceItem don't necessarily have a strict parent child relation and the menu popover is located in the ReferenceItem the only way for ReferenceInput to know if that is being clicked is when a ref is shared using context.
Fixes issue where unused references in array were not cleared when clicking outside

fix(core): clear unused references in an array when clicked outside

---

packages/@sanity/cli/test/build.test.ts

I was reading the css file from wrong directory so based on if v2 test run first or not it would fail. Now that it is reading the files from correct directory it should not fail flakily 
N/A

chore(cli): fix basePath test flakiness

---

packages/sanity/src/core/store/user/hooks.ts

Adding a catch + console.error log when failing to fetch user information. This situation happens when using `unstable_noAuthBoundary` as the studio is trying to get avatars for users (for viewing document diffs and history) but there is no valid session and the backend returns a 401. Rather than crash the studio this will log the error and return `null` for the user which was already written as a potential return type.
Try using `unstable_noAuthBoundary` in the studio and verify the studio doesn't unexpectedly stop when viewing document history/diffs.
Gracefully handle when user data is unavailable for document history/diffing

fix: log inability to fetch user for avatars, prevent studio crash

---

dev/test-studio/schema/standard/numbers.ts
packages/sanity/src/desk/panes/documentList/DocumentListPane.tsx

When adding selected state based on `extendedProjection`, it could cause several sort orderings to be selected, as these are not unique. Two sort orderings can have the same `extendedProjection` if they are sorting by the same field. 
This PR removes selected state based on `extendedProjection` and is only based on `sortOrderRaw` instead of `sortOrder`. 
This is necessary as a `sortOrder` based on type `string` field includes a `mapWith` prop, while the `item.params` does not add the `mapWith` prop, hence the `isEqual` check will fail and a sort option by a `string` will never be selected. 
Make sure the correct sorting option is highlighted in the dropdown menu for sorting document lists. 
Fixes issue where several sorting options could be selected concurrently in dropdown.

fix(desk): compare selected on sortOrderRaw instead of sortOrder

---

.github/workflows/prettier-if-needed.yml
.github/workflows/yarn-if-needed.yml

On this `prettier-if-needed.yml` PR: https://github.com/sanity-io/sanity/pull/4369
I noticed it committed a change to `yarn.lock`, which is odd. It shouldn't. 
I ran `yarn` myself on `git checkout origin next` and can confirm the lockfile is currently out of sync. 
This can happen due to PR queues and how merge conflicts or ordering happens.
In any case this PR introduces an action that will create a PR that fixes `yarn.lock` whenever needed.
The benefit of this is to avoid multiple PRs now changing `yarn.lock` as authors run `yarn` locally and the lockfile is currently stale in `next`.
I didn't commit a fixed `yarn.lock` on purpose so that we can test if the bot works and is able to fix the currently stale `yarn.lock` on `next`.
Merging this PR should also trigger the prettier bot to …

chore(CI): create yarn lockfile maintenance action

---

perf/cli.ts
perf/queries.ts

Small change that adds support for running perf tests against --count recent tags (typically releases).
For example, to run the perf tests against the 5 most recent tags: `yarn perf:test --tagsOnly --count=5`
Note: The copy edits are mainly to make the output more accurate (it's no longer just "branch" or "branches))
Check that the code makes change
n/a: internal tooling

fix(perf-runner): add support for running tests against recent tags only

---

packages/sanity/src/core/form/inputs/PortableText/toolbar/InsertMenu.tsx

In schema, when a field only has a `name` the `title` is automatically generated and should be uppercase in the PTE. 
Before: 
Make sure that if a field in PTE does not have a `title` field, the automatically generated title is uppercase. 
Fixes automatically generated title in PTE to be uppercase.

fix(core): capitalize type name if item type lacks title in pte

---

dev/test-studio/package.json

Enables source maps for test studio in vercel, helpful for debugging issues.
Debugger in vercel 🙌 
Does it make sense to make source-maps an env variable and add it to vercel as a build env. Or is that too much effort for little gain? 
N/A (internal)

chore(test-studio): enable source-maps

---

packages/@sanity/cli/src/studioDependencies.ts

_Note: This is not a complete fix, but will _mitigate_ problems until we can properly fix it._
pnpm 8 has switched resolution to use the _lowest_ matching version when installing dependencies. This is apparently done for performance reasons, but creates problems for us since it means pnpm users will get Sanity 3.0.0 instead of the latest. The same goes for other root-level dependencies.
There is no flag to set resolution mode, and installing a pnpmrc seems a little invasive, so I think the real solution is to resolve the latest (compatible) version of dependencies upon install and write that to the project `package.json`. Until we can get around to that, this will at least bring versions up to a much more recent version of Sanity, and avoids a number of react hooks warning on the dev …

fix(cli): use more recent version ranges for new projects

---

packages/@sanity/validation/src/validateDocument.ts

During the v3 work, the type for annotations were changed to be arrays. 
The check where validation is added to arrays will therefore include annotations as well now, and a separate check for annotations are not necessary. By removing this check for annotations, the validation messages are now only shown once. 
That validation for annotations work as expected and are now duplicated anymore. 
Fixes bug where validation messages on annotations were shown twice.

fix(validation): Remove recursive validation check for annotations in PTE

---

.github/CODEOWNERS

Add code owners to specific parts of the monorepo in the `next` branch, this is just a beginning stage and more owners will be added as we go along.
the owners
n/a (internal only)

chore(.github): add code owners

---

packages/@sanity/portable-text-editor/src/utils/patchToOperations.ts
packages/@sanity/portable-text-editor/test/__tests__/writingTogether.collaborative.test.ts
packages/@sanity/portable-text-editor/test/setup/collaborative.jest.env.ts

There is an issue in the PTE where if several users are typing and one editor deletes all the content, a set selection in another editor is nullified in a non-clear way and as observed in the CI will randomly fail on these kind of tests.
Not a big real world problem probably, but very disruptive when these tests randomly fails unrelated to anyone's changes and there are unexpected things happening.
The symptom was that the test framework's `waitForNewSelection` would timeout while waiting for a new selection that never came. The reason it doesn't fail (on a fast computer) is that the safety-mechanism in `useSyncValue` will later make this happen anyway (though a tad bit later) making it just in time for the test to be true at that particular time. I think this is why it's never been a …

Restore PTE selection in placeholder block

---

packages/sanity/src/core/form/hooks/__tests__/useDidUpdate.test.ts
packages/sanity/src/core/form/hooks/__tests__/useOnClickOutside.test.tsx
packages/sanity/src/core/form/hooks/__tests__/usePrevious.test.ts
packages/sanity/src/core/form/hooks/__tests__/useScrollIntoViewOnFocusWithin.test.ts
packages/sanity/src/core/form/hooks/useDidUpdate.ts

The issues are related to when an application is not running in strict mode. This is important because in [StrictMode](https://react.dev/reference/react/StrictMode#strictmode) every effect gets runs twice but when not using strict mode, i.e in production the hook only gets called once. 
Issue 1: When a new reference item is created the focus is not set into the AutoComplete
Issue 2: In a virtualized list if there is a validation error clicking on the error on top of the document panel does not scroll to the validation error
The way to review this PR is looking at the tests first and if the assertions makes sense.
I have added tests for `usePrevious`, `useOnClickOutside` and `useScrollIntoViewOnFocusWithin` hooks while I was in the folder without any change to the existing hooks. …

fix(core): fix focus issues when a new reference field is added

---

packages/@sanity/portable-text-editor/src/editor/plugins/createWithPatches.ts
packages/@sanity/portable-text-editor/test/__tests__/writingTogether.collaborative.test.ts
packages/@sanity/portable-text-editor/test/setup/collaborative.jest.env.ts

There is a bug in the Portable Text Editor, where if you write only one sentence in the editor, mark half of it bold, then select all and (over)write something, it will produce two duplicate blocks as a result giving a "duplicate key error".
The reason is that `merge_node` isn't included in the list of operations that potentially can make the editor empty and should lead to a unset patch being produced.
In detail:
The follow operations are done:
1. The text is set to empty in both of the spans.
2. The mark is removed from the second span.
3. The now empty identical spans are merged into one single empty span, that equals to an empty editor.
4. The merge_node operation made the editor "empty", and a unset patch should be produced.
Since the unset patch is never produced, the insert patch …

Fix issue with PTE merge operation not producing unset patch

---

packages/sanity/src/core/store/_legacy/history/useTimelineSelector.ts

Follows up on an issue that were flagged in https://github.com/sanity-io/sanity/pull/4347#discussion_r1166149559 but were merged without being fixed.
We shouldn't implement our own selector pattern on top of `useSyncExternalStore`.
Documentation from the React core team is still sparse, but the official docs talks about the importance of the stability of `getSnapshot` here: https://react.dev/reference/react/useSyncExternalStore#im-getting-an-error-the-result-of-getsnapshot-should-be-cached
This is further elaborated in the PR that introduces the hook used in this PR `use-sync-external-store/with-selector`: https://github.com/reactwg/react-18/discussions/86
Even though all the callsites of `useTimelineSelector` is currently safe, as they just select a state slice like `(state) => …

refactor(timeline): use official external store with selector API

---

packages/sanity/src/core/components/popoverDialog/PopoverDialog.tsx
packages/sanity/src/core/form/components/EditPortal.tsx

fixes #4396 
When virtualized list is inside the modal it does not render all the content
Before
After
Since the virtualized list always looks for the scroll element that is on the DocumentPanel, when it is inside it is still using the DocumentPanel to get the offset. The change that is made is to wrap the EditPortal in BoundaryElement, since that would be the closet parent it would use the scroll reference from it to set the correct top offset.
❓Are there other instances that you can think of that would have similar issues where arrays are not rendered inside DocumentPanel and have their own scroll positioning?
Fixes virtualized list not rendering properly when inside a modal

fix(core): list virtualization is broken inside modals

---

packages/@sanity/portable-text-editor/src/utils/__tests__/patchToOperations.test.ts
packages/@sanity/portable-text-editor/src/utils/patchToOperations.ts

There was a problem where creating and inserting a value into a text annotation object would error on a listening editor.
Values inside `markDefs` (void) objects of regular text blocks are not the editor's responsibility to deal with here. So if a nested path inside a text block is anything else than `children` in the second segment, just ignore it.
`useSyncValue` will make sure to update this content when it's changed.
* That adding a text annotation with a value (link with href val.) will not crash an editor that have the same document and editor opened.
* Fix an issue where creating a text annotation and inserting a value inside it, would make a listening text editor crash.

fix(portable-text-editor): ignore void edits inside markDefs

---

packages/sanity/src/core/field/types/portableText/diff/components/Block.tsx

When block styles are changed, show both from and to style in the history diff:
They are not 1:1 represented in the diff preview in visual size, so it's hard to know what it changed to.
* Show name of block style a block changed into in review changes panel.

feature(core): show to-blockstyle in pt-diff

---

dev/test-studio/schema/debug/scrollBug.tsx
dev/test-studio/schema/index.ts
dev/test-studio/structure/constants.ts
packages/sanity/src/core/form/inputs/ReferenceInput/PreviewReferenceValue.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/PreviewItem.tsx

Fixes an issue where the document would automatically scroll when a user is not scrolling. From investigation, the reason that happens is when the element first measured it gets stored in a cache but if the element's height changes then there is a code in react-virtual that is to fix the delta by doing a scroll.
https://github.com/TanStack/virtual/blob/623ac63988f16e6ea6755d8b2e190c123134501c/packages/virtual-core/src/index.ts#L653-L672
To fix the issue we are making sure that the preview items in the virtualized list are not hidden when outside of the scroll window so it doesn't keep changing heights based on scrolling. There is still an issue if you have a new reference autocomplete and you get to a specific height it would do a scroll, we will probably fix that in future PR and …

fix(core): fix scrolling issue with documents

---

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx

Clicking a validation error for - or following a deep link to - a reference field that _has_ a value doesn't trigger focus/scroll to the field currently. This PR should fix the issue by forwarding the ref to the preview element. This ref was not being forwarded to any element, which most certainly must have been an oversight.
Go for example to [this document](https://test-studio-git-feature-sc-32690clicking-validation-erro-7859b4.sanity.build/test/content/input-debug;scrollBug;5010321f-a700-41bb-af9d-c2c35944e361) and click on the validation error for the reference, and see that it scrolls to the reference field
For comparison: Here's the [same document](https://test-studio.sanity.build/test/content/input-debug;scrollBug;5010321f-a700-41bb-af9d-c2c35944e361) in `next`
- Fixes a bug with …

fix(form): fix focus issue with reference fields

---

packages/@sanity/cli/src/actions/init-project/initProject.ts

We have mostly supported unattended mode when you provide project name and -y flag to the cli, but a quirk in the `getOrCreateDataset` implementation required a login for this step, even if a dataset name was provided on the cli params.
This change skips verifying dataset name through API if provided as a parameter option to the CLI and in unattended mode, reflecting the behaviour already there for "CI mode" and also the existing behaviuor of `getOrCreateProject`
That the behaviour is as expected through the cli with -y, --project and --dataset while logged out
Enable fully unattended Studio init through cli when`project`, `dataset` and `y` flag is set

fix(cli): skip dataset validation in unattended mode when provided

---

dev/test-studio/schema/debug/fieldGroupsWithFieldsetsAndValidation.js
dev/test-studio/schema/index.ts
dev/test-studio/schema/standard/objects.tsx
dev/test-studio/structure/constants.ts
packages/sanity/src/core/form/store/formState.ts
packages/sanity/src/core/form/store/types/asserters.ts
packages/sanity/src/core/form/store/types/nodes.ts
packages/sanity/src/core/form/store/utils/getExpandOperations.ts
packages/sanity/src/core/form/studio/FormBuilder.tsx
packages/sanity/src/core/form/types/inputProps.ts

Validation error would not focus fields in collapsed fieldsets that existed within a field. 
This was due to the fieldset not being found and expanded within the `getExpandOperations.ts`. 
By adding a fieldset within a field to the expand operation, the field can get focused when clicking the validation error. 
Make sure that all validation error links works as expected, especially within a field and a fieldset within a field. 
Fixes bug where validation error would not focus on collapsed fieldset

fix(core): add fieldset within field to expandOperation

---

packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx

This makes sure we set the correct focus path initially (and when params.path changes) and also makes sure the required fieldsets and collapsible objects are expanded, and field groups selected so that the right inputs can be focused when deep linking to a field
- Make sure deep linking to a field works even if the field is contained within one or more a collapsed fieldset(s) or object(s)
- Made sure deep linking to a field/input expands the right fieldsets/collapsed objects along the way

fix(desk): set collapsed/fieldgroup/open path based on router path

---

packages/sanity/src/core/form/components/EditPortal.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/PreviewItem.tsx
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx

This will skip autofocus on first interactive descendant when opening dialogs to edit array objects unless focus is on  the object itself. Prevents an issue causing focus to be set on the close button even if the focus path mandated focus to be set at a node deeper down in the hierarchy.
Open 
http://test-studio-git-bug-sc-32395fix-array-dialog-autofocus.sanity.build/test/content/input-debug;focusTest;b99a1ee9-c8be-4248-9104-259b9fade2a3%2Cpath%3DsomeArray%5B_key%3D%3D"ee65a8923ed5"%5D.focusTest.someArray%5B_key%3D%3D"3c9e353346e4"%5D.focusTest.someObject.first and observe that the right field inside the dialog gets focused
Here's `next` for comparison: 
https://test-studio.sanity.build/test/content/input-debug;focusTest;b99a1ee9-c8be-4248-9104-259b9fade2a3%2Cpath%3DsomeArray%5B_key%3D%3D" …

fix(form): prevent autofocus on array dialogs where focus is on a deeper value

---

packages/sanity/src/core/form/inputs/ObjectInput/ObjectInput.tsx
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx

Since focus is Studio forms are managed by the focus path (or, in some cases, by calling focusFirstDescendant on the container element), we can skip autofocus for field groups, preventing it from stealing focus in cases where focusPath mandates that focus should be set elsewhere.
When deep linking to a field contained inside a field group, make sure that the field group button itself doesn't steal focus
- Fixed an issue that caused field group buttons to steal focus when deep linking into a Studio value

fix(form): skip autofocus on field groups

---

packages/@sanity/util/src/paths.ts
packages/@sanity/util/test/PathUtils.test.ts
packages/sanity/src/core/form/components/EditPortal.tsx
packages/sanity/src/core/form/inputs/ObjectInput/ObjectInput.tsx
packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/PreviewItem.tsx
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx
packages/sanity/src/desk/panes/document/documentPanel/documentViews/FormView.tsx

Intent links do not focus on the correct path, this is because the FormView is automatically focusing on the first child regardless of what the intent link has set, this means even thought the focusPath gets set correctly from the path but when the form loads, it overrides the focusPath from where it should be to the first element in the form.
Testing different scenarios, like inputs, arrays, objects. Note that currently it does not open up Dialogs if the focus is nested inside a Dialog, not sure if it should?
https://test-studio-git-bug-sc-32395intent-link-errors-edit-mode-dep.sanity.build/test/content/input-standard;textsTest;32f38606-26f2-4df9-be97-10754ae5d45a%2Cpath%3Drows15
✅ https://test-studio-git-bug-sc-32395intent-link-errors-edit-mode-dep.sanity.build/test/content/input-standard …

fix(core): intent links not focusing correctly

---

packages/sanity/src/core/form/inputs/files/FileInput/FileActionsMenu.tsx
packages/sanity/src/core/form/inputs/files/FileInput/FileInput.tsx
packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx

This includes a couple of improvements for image and file inputs with regards to focus handling:
- Makes sure image and file fields support deep linking + scroll to through focus path (fixes deep linking + validation)
- Fixes a bug breaking the ability to paste a file into a file field that has a value (we currently had two focusable elements in a file field that had a value (the preview wrapper + the FileTarget)
Make sure deep linking (either via intent link w/path, from presence menu or validation menu) works
- Deep linking to file field from intent link: https://test-studio-git-fix-improve-asset-inputs-focus.sanity.build/test/intent/edit/id=66890ca9-0354-4a16-9ec0-e25ff5679295;path=FileWithTwoAccept/
- Deep linking to image field from intent link: …

fix(form): improve focus handling for image and file inputs

---

.github/workflows/test.yml

Node 14 went [EOL](https://nodejs.dev/en/about/releases/) 2023-04-30 so let's drop it form our test matrix. We should probably add v19 or v20 once adoption starts picking up.
- Drop Node 14.x from CI test matrix

ci(github): drop node 14 from test matrix

---

packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentButton.tsx

This PR adds a small fix to the create new button works on smaller breakpoints.
The issue was that the `useClickOutside` hook wasn't adding the create new dialog element (present on smaller breakpoints) to its ignore list – effectively meaning every 'click' on mobile was triggering the `useClickOutside` callback and in turn, closing the modal without any effect.
You could be able to create a new document via the new document button on mobile!
Fixes an issue where the create new document dialog wasn't working on smaller breakpoints.

fix(core): ensure the create new button dialog is functional on smaller breakpoints

---

dev/design-studio/package.json
dev/test-studio/package.json
examples/ecommerce-studio/package.json
packages/@sanity/cli/templates/shopify/components/media/ColorTheme.tsx
packages/@sanity/portable-text-editor/package.json
packages/@sanity/vision/package.json
packages/@sanity/vision/src/codemirror/VisionCodeMirror.styled.tsx
packages/sanity/package.json
packages/sanity/src/core/components/previews/_common/Media.styled.ts
packages/sanity/src/core/components/previews/general/DetailPreview.styled.ts
packages/sanity/src/core/components/previews/portableText/InlinePreview.styled.tsx
packages/sanity/src/core/components/progress/LinearProgress.tsx
packages/sanity/src/core/form/inputs/PortableText/Compositor.styles.tsx
packages/sanity/src/core/form/inputs/PortableText/Editor.styles.tsx
packages/sanity/src/core/form/inputs/PortableText/object/modals/PopoverModal.styles.ts
packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.styled.tsx
packages/sanity/src/core/form/inputs/files/common/FileInputButton/styles.ts
packages/sanity/src/core/form/inputs/files/common/FileInputMenuItem/FileInputMenuItem.styled.tsx
packages/sanity/src/core/form/inputs/files/common/UploadProgress.styled.tsx
packages/sanity/src/core/presence/overlay/RegionsWithIntersections.styled.tsx
packages/sanity/src/core/studio/StudioLayout.tsx
packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentButton.style.ts
packages/sanity/src/core/studio/components/navbar/search/SearchDialog.tsx
packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/FilterPopoverContent.tsx
packages/sanity/src/core/studio/screens/CorsOriginErrorScreen.tsx
packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialogBody.styles.tsx
packages/sanity/src/desk/components/pane/PaneHeader.styles.tsx
packages/sanity/src/desk/panes/document/documentPanel/ReferenceChangedBanner.tsx
packages/sanity/src/desk/panes/document/timeline/timelineMenu.tsx
yarn.lock

When `overflow: hidden` browsers turn off scrollbars and the user can no longer scroll. But it can still be scrolled if the APIs `.focus()` and `.scrollIntoView`, as well as with other native browser behaviour as browsers still consider them scrolling boxes.
This video demonstrates how `overflow: hidden` is being scrolled into breaking the Studio layout when opening an edit intent link on iOS Safari that ends up in a field inside a dialog. 
https://user-images.githubusercontent.com/81981/236252831-515d3752-6957-465d-9e25-84b7544ace06.mp4
What makes matters worse is that since `overflow: hidden` disables user scroll the user can't recover from this broken state in a lot of cases. And there are many other ways it can break the layout and UI.
The new `overflow: clip` fixes this and turns of …

fix: avoid scroll on `overflow: hidden`

---

packages/@sanity/cli/test/shared/cleanupDangling.ts
packages/@sanity/cli/test/shared/environment.ts
packages/@sanity/cli/test/shared/globalSetup.ts
packages/@sanity/cli/test/shared/globalTeardown.ts

There are a few dangling entities left by the tests, mainly dataset copy jobs. To increase the likelyhood of these getting cleaned up, this PR makes sure that the dangling cleanup is _always_ run, instead of 70% of the time. In addition, the threshold for deleting old entities is lowered from 48h to 16h. To have the required precision for this, I needed to change the format from using dates (`20220131` to rounded unix timestamps (`168262061`). 
Note: This may interrupt ongoing CI jobs - but feel like a workaround for that case was not worth it.
Cleanup logic looks sane.
None.

test(cli): reduce dangling entity cleanup threhold to 16 hours

---

dev/test-studio/schema/debug/fieldGroups.js
packages/sanity/src/core/form/store/formState.ts

Fixes  #4471 
Repro case here: https://test-studio-1pw7fq0uj.sanity.build/test/content/input-debug;field-groups;fieldGroups;d2e9132c-81d3-4cfd-a380-4b49ab88a2b6
Note that two fields without any group config appears in all groups:
- This field has no group and shall only show up in "All fields"
- Array With Field Groups
With fix applied: https://test-studio-git-fix-first-field-group-bug.sanity.build/test/content/input-debug;field-groups;fieldGroups;d2e9132c-81d3-4cfd-a380-4b49ab88a2b6
Note that the two fields now only appear in "All fields"
- Fixes a bug that made fields without a group appear in all groups

fix(form): show fields without groups only when 'All fields' is selected

---

packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx

When following a intent link or a link to a field/input at a specific path in the Studio (e.g from presence menu or through Visual Editing), the path remains in the url. This means that if you reload the page, you are taken (likely surprisingly) back to the path you arrived at initially. This PR fixes that by clearing the path parameter from the URL after it's been set as the initial focus path.
- Go to https://test-studio.sanity.build/test/content/input-standard;objectsTest;cc5c90bd-1184-44ae-9a94-d3395ac7ebec%2Cpath%3Drecursive.recursive.events%255B_key%253D%253D%25220123f5fdca78%2522%255D.where
- Move around in the document, make some edits
- Reload page
- You're back to the field you arrived at earlier
- Go to https://test-studio-git-fix-remove-initial-path-param.sanity.build/test/cont …

fix(desk): remove path param from url after initially read

---

dev/test-studio/schema/debug/fieldGroupsWithFieldsets.js
dev/test-studio/schema/index.ts
dev/test-studio/structure/constants.ts
packages/sanity/src/core/form/inputs/ObjectInput/__tests__/ObjectInput.test.tsx
packages/sanity/src/core/form/members/object/fields/PrimitiveField.test.tsx
packages/sanity/src/core/form/store/formState.ts
packages/sanity/src/core/form/store/types/members.ts
packages/sanity/src/core/form/store/types/nodes.ts
packages/sanity/src/core/form/store/utils/getExpandOperations.ts

As described in #4432, when a field group only has fieldsets, the group becomes hidden.
When a field group has fieldsets only, it disappears. Reproducible here: https://test-studio-cbwgkvfea.sanity.build/test/content/input-debug;field-groups;fieldGroupsWithFieldsets;96fcdb05-ed51-41b7-a189-94eae745eae2%2Ctemplate%3DfieldGroupsWithFieldsets
The same case as above with the fix from this PR applied: https://test-studio-git-fix-fieldset-field-group-bug.sanity.build/test/content/input-debug;field-groups;fieldGroupsWithFieldsets;96fcdb05-ed51-41b7-a189-94eae745eae2
In particular, the following cases should hold true after these changes:
- Fields inside fieldsets should be filtered based on the currently active field group
- A field group should be selectable even if it consists entirely of …

refactor(form): fix issue with hiding a field group that only have fieldsets

---

packages/sanity/src/core/form/members/object/fields/ObjectField.tsx

A bug was reported (like #4285) where objects weren't being unset when the values were removed. Now the object input will remove itself completely from a patch if it identifies that it should
- [On simple object (Obj Name), removing the value unsets the object input](https://test-studio-git-bug-sc-32671.sanity.build/test/content/input-debug;empty;85909e44-4e17-4dd1-adf3-117681e59a7e)
- [On object with multiple values (Object with columns), removing one value unsets only the removed value](https://test-studio-git-bug-sc-32671.sanity.build/test/content/input-standard;objectsTest;91476f47-f035-47d7-8577-eba51f33964f%2Cpath%3DobjectWithColumns.string1)
- [On object with multiple values (Object with columns), removing all values unsets the whole …

fix(core):  unset objects when no values in patch when empty value

---

packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx
packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.tsx
packages/sanity/src/core/form/members/object/fields/ArrayOfObjectsField.tsx
packages/sanity/src/core/form/store/formState.ts

Both `onChange` and `onItemRemove` sent in to an `arrayOfObjects` input will be a new object every time an array item changes because it's callback is dependent on the field value.
Use a `ref` for this dependency instead. This also fixes the instability of `onItemRemove` which again is dependent on the `onChange` callback.
I have also fixed a snag with presence causing re-rendering for the PT-input as they are new empty arrays each time presence is returned back. Use the same empty array object in this case.
* [Set this constant](https://github.com/sanity-io/sanity/blob/fix/re-rendering-issue/packages/sanity/src/core/form/inputs/PortableText/debugRender.ts#L1) to true then write some Portable Text. The only colour that should change is the current block you're typing in, or where a new …

Fix re-rendering issues

---

dev/test-studio/schema/debug/ptReference.ts
dev/test-studio/schema/index.ts
dev/test-studio/structure/constants.ts
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx

This reverts the change in #4105 where it fixes an issue where clicking Replace in reference inputs would still retain the search query. This is because the change broke reference inputs in PTE. 
Following scenario work
1. Editing reference field in PTE shows correct value
2. ~In an array list clicking on replace removes the current value from the input~ We will tackle this in future iteration as fixing the above issue is more critical
Does the code change make sense?
- Fixes an issue where editing reference inputs in Portable Text Editor does not show current value

fix(core): editing reference input in PTE does not show value

---

packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx

There was a rendering regression from v3.11.2 in 75dfb9ca1bbb6bc21cad9c8139e4a9d87f9522ad where nested PT-inputs (PT in PT) would not properly update their form inputs. It was probably a bit naive to use refs like that. 😔 
This will revert the use of refs for the input in the PT node components, and let the PortableTextInput figure out if we need to re-render their inputs instead.
I have added a condition that will only re-render the input if the member is open _or_ it's value has changed.
This way we keep the intended performance optimisations by not render all the object inputs with every cycle,
but making sure we do so initially, when the object is open, or it's value has changed.
* [Set this constant](https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/core/form/inputs/Po …

fix(core/form/inputs): fix rendering regression for PT-input

---

packages/@sanity/block-tools/README.md
packages/@sanity/block-tools/src/HtmlDeserializer/rules/html.ts
packages/@sanity/block-tools/src/constants.ts
packages/@sanity/block-tools/test/fixtures/customSchema.ts
packages/@sanity/block-tools/test/tests/HtmlDeserializer/customSchema/input.html
packages/@sanity/block-tools/test/tests/HtmlDeserializer/customSchema/output.json
packages/@sanity/block-tools/test/tests/util/__snapshots__/blockContentTypeFeatures.test.ts.snap

This updates the whitelist of block-tools to allow highly requested decorators like `sup/sub`, as well as any other similar HTML elements that will "just work": `mark, ins, small` (we already had `del` in there).
It also updates the README to be more specific that we only will convert a subset of HTML elements, and adds a link to the internal whitelist.
- Review that the docs update makes sense to you and makes it clearer what tags we whitelist
- Review the list of whitelisted decorators: Any objects to the additions?
- Added support for `<sup>`, `<sub>`, `<ins>` and `<mark>` in `@sanity/block-tools`

fix: whitelist all standard text decorators in block-tools

---

packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx

The determination of using image preview for object blocks in the PT-input is a bit naive and doesn't take custom named image types into account.
Use the `isImage` type asserter from `sanity` instead to determine this which is the correct way.
That the correct image preview is made inside the PT-input for image blocks.
Custom named image types like this should be asserted correctly too: `{type: 'myBigImageType', name: 'Big image'}`
* Improve how image blocks in the Portable Text Input is rendered for custom named image types.

fix(core/form/inputs): use isImage asserter to determine image preview

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/editor/hooks/useSyncValue.ts
packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts
packages/@sanity/portable-text-editor/src/types/editor.ts
packages/sanity/src/core/form/inputs/PortableText/BlockActions.tsx
packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx
packages/sanity/src/core/form/inputs/PortableText/Editor.tsx
packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
packages/sanity/src/core/form/inputs/PortableText/hooks/useTrackFocusPath.tsx
packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx
packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
packages/sanity/src/core/form/inputs/PortableText/object/BlockObjectActionsMenu.tsx
packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx
packages/sanity/src/core/form/inputs/PortableText/object/InlineObjectToolbarPopover.tsx
packages/sanity/src/core/form/inputs/PortableText/object/modals/DialogModal.tsx
packages/sanity/src/core/form/inputs/PortableText/object/modals/ObjectEditModal.tsx
packages/sanity/src/core/form/inputs/PortableText/object/modals/PopoverModal.tsx
packages/sanity/src/core/form/inputs/PortableText/toolbar/InsertMenu.tsx
packages/sanity/src/core/form/inputs/PortableText/toolbar/hooks.ts
packages/sanity/src/core/form/types/blockProps.ts

The PT-input is doing focusPath tracking in some situations when it should not, which can cause issues when editing embedded objects inside through the dialogs. There was a recent regression where the selection was not handled well when creating new links in particular.
Also when deleting block objects or inline objects with the mouse through menus, the focus was lost and not properly put back into the editor after the element was deleted. This is now fixed by preventing the default on that menu item click.
There is also an issue with autofocus on the embedded data forms. This is now following the same pattern as elsewhere in the studio (using `autofocus` with React). Autofocus will be triggered when the `focusPath` matches exact with the node in question (so pointing directly to, but not …

Improve PT-input focus tracking

---

packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx
packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.tsx
packages/sanity/src/core/form/studio/contexts/Presence.tsx

When using `useChildPresence` it will return a new object even though the presence data is equal.
Keep stable child presence by using immutableReconcile on them.
I have also updated the PT-input nodes to get their presence from this hook, rather than getting them from the array member item. This is also how the Array Input does it, and we get the added performance there as well.
* That there is a new presence list only when something actually changed in the list.
* Improved presence rendering performance

Keep stable child presence

---

packages/@sanity/block-tools/src/HtmlDeserializer/helpers.ts
packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/index.ts
packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/whitespace.ts
packages/@sanity/block-tools/src/HtmlDeserializer/rules/html.ts
packages/@sanity/block-tools/src/constants.ts
packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild2/output.json
packages/@sanity/block-tools/test/tests/HtmlDeserializer/whitespaceInPreTags/index.ts
packages/@sanity/block-tools/test/tests/HtmlDeserializer/whitespaceInPreTags/input.html
packages/@sanity/block-tools/test/tests/HtmlDeserializer/whitespaceInPreTags/output.json

This fixes an issue in `@sanity/block-tools` where whitespace was removed from content within certain HTML tags like `<pre>`, where whitespace should be preserved.
Before this change, whitespace in the whole document was normalized before passing the html to be processed.
In this PR we replace that approach with another preprocessor that loops over the DOM tree and process each text node as long as its not inside a HTML tag that should preserve whitespace.
While this fix was focused on `<pre>` tags, I think it makes sense to  include `<textarea>` and `<code>` tags in the whitelist, even though we don't process these in any special way currently.
- That whitespace in `<pre>` tags is now preserved (there is tests for this now)
- Fixed an issue where `@sanity/block-tools` would remove …

fix(block-tools): preserve whitespace in preprocess for certain html tags

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/types/editor.ts

This will improve the DX a bit on the `PortableTextEditor` `onPaste` prop which is reused by the `PortableTextInput`
First I noticed this function is being called with the wrong path value.  This is supposed to be a keyed PortableText path (and not a Slate path)
Then there was a too strictly typed property on the callback function, it was typed to `PortableTextBlock` which will require a `_key` which isn't needed here. Use `TypedObject` which is the correct one.
* That the path is called with the correct relative keyed path where the focus is at.
* That one are able to write this without TS-error:
```ts
const onPaste: PortableTextInputProps['onPaste'] = ({event, schemaTypes}) => {
return {
// Only a type is required here
insert: [
{
_type: 'myType',
foo: 'bar',
},
],
}
}
```
* Improve …

refactor(portable-text-editor): improve onPaste typings

---

packages/sanity/src/core/form/store/formState.ts

Currently, conditional fields on fields contained inside fieldsets doesn't get passed the correct arguments. Instead of getting the current field value, it receives the parent's field values.
- Make sure fields + field groups and conditional fields works as they should
- Fixes a bug that made conditional field callbacks inside fieldsets to get passed a wrong parent value

fix(form): pass the correct data to conditional fields contained inside fieldsets

---

packages/sanity/src/core/form/store/formState.ts

This fixes what looks to have been a regression in v3.11.1 that broke document-level readOnly
Make sure the editor makes documents of the following type readOnly:
```js
{
name: 'test',
fields: [
{
name: 'title',
}
],
readOnly: true
}
```
- Fixes a regression from v3.11.1 that broke document-level readOnly

fix(form): fix bug making fields not inherit document level readOnly state

---

packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx

This fixes a regression in [this commit](https://github.com/sanity-io/sanity/commit/ef9e762ec14df3ff0ff86aff20ed96cf2c46ec08) that broke documents being set to readOnly while there is transactions pending.
This can lead to pending patches being discarded if a user makes a change while the document is being synced
- To simulate pending patches, go into `getPairListener.ts`, find line 114 and change it to `if (false && allPendingTransactionEventsReceived(nextBuffer)) {`
- Make any changes to a document
- Click publish
- The syncing toast should show, and the document should be read only
- Fixes a issue where documents wasn't locked while a document was being synced

fix(desk): fix readOnly document state while document is syncing

---

dev/test-studio/inspectors/custom/index.ts
packages/sanity/src/core/config/document/inspector.ts
packages/sanity/src/desk/panes/document/DocumentInspectorMenuItemsResolver.tsx
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx
packages/sanity/src/desk/panes/document/documentInspector/DocumentInspectorPanel.tsx
packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
packages/sanity/src/desk/panes/document/inspectors/changes/index.ts
packages/sanity/src/desk/panes/document/inspectors/validation/index.ts
packages/sanity/src/desk/panes/document/menuItems.ts

This pull request updates the document inspector API so that the menu item is configured with a React hook (`useMenuItem`). The pull request also moves the `showAsAction` property to be part of the menu item value. This update opens up possibilities to perform custom logic in `useMenuItem` and return a dynamic menu item object (see the validation inspector for example).
Before:
```ts
const inspector = defineDocumentInspector({
// ...
menuItem: {
title: 'Inspector',
},
showAsAction: true,
})
```
After:
```ts
const inspector = defineDocumentInspector({
// ...
useMenuItem: () => {
// ...
return {
showAsAction: true,
title: 'Inspector',
}
},
})
```

feat(desk): add `useMenuItem` to document inspector API

---

packages/sanity/src/core/form/inputs/files/common/ActionsMenu.tsx

Fixes casing for "URL" on toast popup when copying an asset's URL to the clipboard
That you agree URL should be uppercase?
Fixes casing for "URL" on toast popup when copying an asset's URL to the clipboard

chore: correct toast text for copied URL

---

package.json
yarn.lock

Updating `@sanity/pkg-utils`, either explicitly as in #4546, or as a side-effect of refreshing `yarn.lock` as seen in #4549, result in this error being thrown:
```bash
yarn depcheck
yarn run v1.22.19
$ lerna exec \$LERNA_ROOT_PATH/scripts/depcheck.js --no-bail --parallel
/home/runner/work/sanity/sanity/node_modules/wide-align/align.js:2
var stringWidth = require('string-width')
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/sanity/sanity/node_modules/string-width/index.js from /home/runner/work/sanity/sanity/node_modules/wide-align/align.js not supported.
Instead change the require of index.js in /home/runner/work/sanity/sanity/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> …
```

chore(deps): unblock update to @sanity/pkg-utils to v2.3.1

---

packages/@sanity/portable-text-editor/src/editor/components/Synchronizer.tsx
packages/@sanity/portable-text-editor/src/types/editor.ts

This will add a snapshot of the current editor value with the mutation change that is emitted when the user edits something.
The PortableTextEditor only emits a value change when the props.value is changed, so this snapshot can be used to set the outside value without needing to perform any patching.
* That the snapshot is provided in the mutation event is enabling what is needed to simply set the value on the outside and sending it in through `props.value` again.
* Added  `snapshot` of the editor value to the mutation changes the Portable Text Editor is emitting.

feat(portable-text-editor): add value snapshot to mutation change

---

packages/sanity/src/_internal/cli/actions/graphql/extractFromSanitySchema.ts

When creating a GraphQL union that combines multiple references in an array field type, the union name was not being created correctly.
The `flattened` array could end up containing an item that matched the follow signature: 
```
{
kind: 'Type',
name: 'Carousel',
type: 'Object',
description: undefined,
fields: [Array],
originalName: 'carousel'
},
// problem object
{
description: undefined,
isReference: true,
originalName: 'reference'
},
{
kind: 'Type',
name: 'Gallery',
type: 'Object',
description: undefined,
fields: [Array],
originalName: 'gallery'
},
```
This means that when the `allTypeNames` is created, it could contain the value `undefined` because neither `type` nor `name` exists on that object. The next step tries to create a union name using that array that contains an `undefined` …

Fixed: case where empty references where passed for union generation

---

packages/@sanity/cli/templates/shopify/desk/productStructure.ts

This fixes intents in the Shopify Studio which meant product document restore actions failed, and both product and variant restoring jumped out of the desk structure.
Intents in the Shopify Studio work as expected, especially in association with document restore actions.
```
yarn && yarn build
./packages/@sanity/cli/bin/sanity init --template shopify
```

fix(cli): shopify studio intent fixes

---

packages/sanity/src/core/config/prepareConfig.ts

Adds a `tag=sanity.studio` query parameter to the `/socket` request used for presence, to align with other studio requests. Ask me for background on Slack if you need more details on why :)
- Socket request work as expected
None.

fix(core): include request tag prefix for websocket

---

packages/sanity/src/core/form/components/formField/FormFieldValidationStatus.tsx

The validation popover was cropped inside pte due to a lacking `portal` prop in the `FormFieldValidationStatus`. 
This pr sets the `portal` prop to `true` for all validation tooltips and removes the `muted` prop for the validation text. 
That the validation tooltips behave as expected and is not clipped, e.g. for links in the pte. 
Fixes issue where validation tooltips were clipped

fix(core): use portal prop on validation tooltip, remove muted text

---

packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx
packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
packages/sanity/src/core/form/inputs/PortableText/hooks/useTrackFocusPath.tsx
packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx
packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx
packages/sanity/src/core/form/inputs/PortableText/object/InlineObjectToolbarPopover.tsx
packages/sanity/src/core/form/inputs/PortableText/object/modals/ObjectEditModal.tsx
packages/sanity/src/core/form/inputs/PortableText/object/modals/PopoverModal.styles.ts
packages/sanity/src/core/form/inputs/PortableText/object/modals/PopoverModal.tsx
packages/sanity/src/core/form/inputs/PortableText/object/modals/types.ts
packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/CreateButton.tsx
packages/sanity/src/core/form/types/blockProps.ts

This PR updates how popovers are rendered and behave, making use of the new props in`@sanity/ui`'s `Popover`: `floatingBoundary` and `referenceBoundary`.
- `referenceBoundary` is the HTML element that is used as boundary for the element which the popover points to. The annotation or inline object in the case of PTE. Specifying this boundary will make the popover disappear when an annotation or inline object is scrolled out of view (i.e. out the scrollable editable area).
- `floatingBoundary` is the HTML element that is used as boundary for the popover itself. When this is set to the document pane's scrollable area, the popover will grow outside of the PTE when needed (which is good!).
Before:
After:
- That PTE popovers are accessible.
- That PTE popovers respect the `options.width` …

fix(core): improve PTE popover behavior

---

playwright.config.ts

When the end to end tests fail, it can be hard to debug what is actually causing it to fail - especially when it fails only on CI but not locally. This PR adds retrying on failures, and when that happens - also enables tracing and video recording.
- Config looks correct
None

test(e2e): retry once on failures, record video on retry

---

packages/sanity/src/core/studio/Studio.test.tsx
yarn.lock

Follows up on @binoy14 [from](https://github.com/sanity-io/sanity/pull/4599#issuecomment-1607597138):
> the tests are failing. From looking at it, it seems like it's due to @sanity/icons version change. stroke-linejoin="round" is added to the svgs
This PR fixes that. Looks like it's a result from when @mariuslundgard updated `@sanity/icons` but it appears it the lockfile introduced a duplicate of `@sanity/icons`, which is why it didn't break the snapshot test at the time https://github.com/sanity-io/sanity/commit/0b2c40e9697f2712d541ab4f05c99e25b4094940

chore: dedupe `@sanity/icons` and update snapshot

---

perf/cli.ts
perf/runner/runner.ts

Adds support for excluding one or more tests, and fails the test runner if an unknown test-id is given for either `--testIds` or 
`--excludeTestIds`
N/A internal tooling

chore(perf): add support for --excludeTestIds and fail hard on unknown test-id

---

dev/test-studio/package.json
dev/test-studio/sanity.cli.ts
dev/test-studio/sanity.config.ts
yarn.lock

Adds the @sanity/assist plugin to the test-studio. 
Adds a new workspace where it is enabled.
Did _not_ do any schema tailoring, which means assist field actions will be enabled for most types and fields in that workspace.
Feel free to take it for a spin. 
Let me know if yet another workspace is too much.

chore: add @sanity/assist to test-studio workspace

---

dev/test-studio/package.json
package.json
packages/sanity/package.json
yarn.lock

Version bumps tsdoc, notable changes include fixing playground to work in the monorepo
Fixes `yarn tsdoc:dev` Instructions 
1. `yarn build` at the root
2. `yarn etl sanity` at the root
3. `yarn tsdoc:dev` at the root
Check if the playground shows the docs
N/A

chore(deps): version bump @sanity/tsdoc

---

packages/sanity/src/core/form/components/formField/FormFieldSetLegend.tsx

The hit area for the collapsable field appears tiny with the little arrow (even though you can press the text as well). This PR increases this area. 
Expanding the fieldset has an increased hit area without affecting the design. 
Fixes issue with small hit area for collapsible fieldsets.

fix(core): increase button hit area of collapsible fieldset

---

packages/@sanity/cli/src/actions/init-project/initProject.ts

Fixes a problem where new validation in the latest version of `@sanity/client` throws an error if you're not using the latest version of `next-sanity`
Test `sanity init` on a Next.js project that queries data from Content Lake, and chose 'yes' to embedding Studio. It should no longer throw an error.
- fix: upgrade `next-sanity` to `v5` when using `sanity init` in a Next.js project

fix: upgrade `next-sanity` in `init` to `v5`

---

package.json
scripts/etl.ts
yarn.lock

When an ETL token was present, we did not output data to the `etc` folder, but the output _said it did_. This was very confusing to me. 
Given that outputting to filesystem takes ~15ms on my computer, I didn't think it was worth doing the either/or approach, and instead we just do both. Open to changing this if there's a reason though.
Additionally, I added some progress indicators with timings.
- ETL still runs
- If token is present, outputs to filesystem _and_ remote
- If token is _not_ present, gives a warning to let developer know it is an option
None.

build(etl): improve output of etl command

---

packages/sanity/src/core/studio/components/navbar/resources/ResourcesButton.tsx

The `Help and resources` button was missing an `aria-label` for accessibility.

fix(core): add aria-label to resources button

---

packages/@sanity/cli/src/actions/init-project/initProject.ts

Add missing dependency (`styled-components@5.2`) to dependency array when initializing a Sanity project. This fixes a missing dependency issue when running `npm create sanity@latest` in a Next.js project folder.
With the current build, the following error is thrown when opening the embedded Studio:
1. Create a new Next.js project with `npx create-next-app@latest`
2. From within the project folder, run `npm create sanity@latest`
3. Run `npm install` to install the new Sanity dependencies
4. Run `npm run dev`
5. Navigate to `localhost:3000/studio` and ensure that the Studio loads correctly
Add missing dependency (`styled-components@5.2`) to dependency array when initializing a Sanity project.

fix: add missing styled components dependency

---

packages/sanity/src/desk/documentActions/HistoryRestoreAction.tsx

When an item is restored in a nested pane or in a filtered view it does not actually restore after the confirmation and reverts back to the original state. 
I am not sure if this is the correct fix honestly but from my testing this seems to fix the issue where we run the complete actions first before navigating to an intent. Please let me know if this makes sense or if there is some better way to solve this
- Fixes an issue where restore document does not work in nested pane view

fix(core): restore not working on nested panes

---

packages/sanity/src/desk/structureResolvers/createResolvedPaneNodeStream.ts

Currently, if you navigate to an intent that does not resolve to a fully qualified structure node, it renders a fallback editor. This editor had an override for the document title, which resulted in the title always being simply "Editor", which is less than ideal.
This PR fixes that issue by simply removing the override for the title. I believe it was required previously because we did not  use the document title, so it was shown "empty". 
To reproduce, you need a structure that does not fully resolve - the easiest way to do this is to create an empty structure:
```ts
deskTool({
// ...
structure: S => S.list().title('Content')
})
```
Then head to an edit intent (with a document ID you know exists):
http://localhost:3333/test/intent/edit/id=grrm;type=author/
Verify that the title of the …

fix(desk): prevent fallback editor node from getting 'Editor' as title

---

packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceAuth/Layout.tsx
packages/sanity/src/core/studio/screens/AuthenticateScreen.tsx

Added scrolling to the list of workspaces on the login screen. 
That the login screen can be scrolled. 
Fixes issue with scrolling of workspaces on login screen

fix(core): add scrolling to workspace login screen 

---

packages/sanity/src/core/field/diff/components/DiffTooltip.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/ArrayOfObjectsFunctions.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesFunctions.tsx
packages/sanity/src/desk/panes/document/statusBar/sparkline/PublishStatus.tsx

Some tooltip content had a `muted` prop, leading to potential accessibility issues. It should be darker. 
That all the tooltips in the studio does not have a muted prop. 
Note: there are a lot of muted props in the tooltips in the search component. I have not changed this component, as this seems to be intentional. 
Fixes accessibility issues in tooltip text color contrast

fix(core/desk): remove muted prop in tooltip content

---

dev/test-studio/schema/debug/allNativeInputComponents.ts
dev/test-studio/schema/debug/circularCrossDatasetReference.js
dev/test-studio/schema/standard/crossDatasetReference.ts
packages/@sanity/import-cli/README.md
packages/@sanity/import-cli/src/sanity-import.js
packages/@sanity/import/README.md
packages/@sanity/import/src/importFromArray.js
packages/@sanity/import/src/references.js
packages/@sanity/import/src/validateAssetDocuments.js
packages/@sanity/import/src/validateCdrDatasets.js
packages/@sanity/import/src/validateOptions.js
packages/@sanity/import/test/fixtures/references.ndjson
packages/@sanity/import/test/import.test.js
packages/@sanity/schema/src/legacy/types/crossDatasetReference.ts
packages/@sanity/types/src/schema/definition/type/crossDatasetReference.ts
packages/sanity/src/_internal/cli/commands/dataset/importDatasetCommand.ts
packages/sanity/src/core/form/inputs/CrossDatasetReferenceInput/__tests__/CrossDatasetReferenceInput.test.tsx
packages/sanity/src/core/form/types/definitionExtensions.test.ts
packages/sanity/src/core/preview/createPathObserver.ts

Cross-dataset references no longer allow referencing other projects, which means when we are importing a previous export to a different project, the import will fail with a mutation error.
There are two possible fixes here:
1. Assume the new project has datasets with the same names. This is the new default behavior - any project IDs found during import and rewritten to the new. We then check if all the referenced datasets actually exist in the project, and throw an error if they do not.
2. Skip the cross-dataset references altogether. New options have been added:
- `@sanity/import`: `skipCrossDatasetReferences: true`
- `@sanity/import-cli`: `--skip-cross-dataset-references`
- `@sanity/cli`: `--skip-cross-dataset-references` (`sanity dataset import …`)
Along with this change, 05aeed4 also …

fix(import): rewrite cross-dataset references, add option to skip

---

packages/sanity/src/core/config/prepareConfig.ts
packages/sanity/src/desk/panes/document/DocumentPane.tsx

This pull request implements the 'document' creation context to the `document.newDocumentOptions` API. The 'document' creation context has been available in the Typescript definition, but it has not been fully implemented.
Currently, there are two different creation contexts:
1. Global creation context: The template options available in the global create menu.
2. Structure creation context: The template options in the desk structure (in the list pane headers).
The addition of the new 'document' creation context allows for filtering of document types that can be created from within another document (currently, it is only possible to create a new document with the "create new" button in reference inputs).
Example usage scenarios:
1. Removing the ability to create an "author" document from …

feat(core): implement document creation context in `document.newDocumentOptions`

---

packages/sanity/src/core/config/configPropertyReducers.ts
packages/sanity/src/core/util/getPrintableType.ts

Cherry-picked from an unrelated branch; this PR adds a `getPrintableType()` method, which introduces slightly more descriptive type names. Prior to this, we for instance said "object" instead of "array" or "null". I figure it can be nice to use for error messages throughout the studio, and we can keep adding more specific checks/names to it - for instance React types etc.
- Improved error messages from configuration errors slightly

refactor(config): use human-readable types for config error messages

---

dev/test-studio/schema/debug/fieldGroupsWithValidation.js
packages/@sanity/schema/src/legacy/types/object.ts
packages/@sanity/schema/src/sanity/validation/types/rootType.ts
packages/@sanity/types/src/schema/definition/type/common.ts

We've discussed this internally quite a while ago, and agreed that since we automatically generate a title for schema types that are missing it, it doesn't make sense to also warn about it (in the case you're happy with the automatic title, you have to explicitly define the same title as it generated to avoid the warning).
This PR drops this warning, and also introduces automatic titles for field groups and fieldsets, which was missing this functionality. Going forward, we want to always apply titles where we can instead of warning.
While adding types to the fieldset/group functionality, I noticed a few incorrect/missing properties, so also went ahead and fixed those - apologies for the slight scope creep.
- Changes make sense, and function as expected
- You should see a reduction in …

feat(schema): do not warn on missing title for schema type

---

dev/test-studio/schema/docs/v3/async-functions/schemaType.ts
packages/sanity/src/core/form/inputs/BooleanInput.tsx

Add input validation for boolean inputs.
Before it wasn't showing in the document that the boolean had missing / breaking validations.
**Boolean**
- Go to V3 APIs -> V3 validations
- Pick any document or create a new one
- Check that the validation works for booleans once those are set.
- Boolean inputs will now show validation errors at the input level (in document)

fix(core): add missing validation at input level validation (boolean)

---

packages/@sanity/base/src/_exports/_internal.ts
packages/@sanity/base/src/search/index.ts
packages/@sanity/base/src/search/weighted/applyWeights.test.ts
packages/@sanity/base/src/search/weighted/applyWeights.ts
packages/@sanity/base/src/search/weighted/createSearchQuery.test.ts
packages/@sanity/base/src/search/weighted/createSearchQuery.ts
packages/@sanity/base/src/search/weighted/createWeightedSearch.test.ts
packages/@sanity/base/src/search/weighted/index.ts
packages/@sanity/base/src/search/weighted/types.ts
packages/@sanity/default-layout/src/navbar/search/components/searchResultItem/DebugOverlay.tsx
packages/@sanity/schema/package.json
packages/@sanity/schema/src/legacy/searchConfig/normalize.test.ts
packages/@sanity/schema/src/legacy/searchConfig/normalize.ts
packages/@sanity/schema/src/legacy/searchConfig/resolve.test.ts
packages/@sanity/schema/src/legacy/searchConfig/resolve.ts
packages/@sanity/schema/src/legacy/types/object.ts
packages/@sanity/types/src/schema/types.ts

This PR brings a number of fixes and minor improvements to studio search in v2. Please refer to the internal slack thread for more context.
- The maximum traversal depth (`SEARCH_DEPTH_LIMIT`) has increased significantly (now 15, up from 4)
- To compensate for this, we've introduced a maximum cap on search paths (`SEARCH_PATH_LIMIT`) generated _per root-level object_ (defaults to 500)
- When sorting paths for truncation, we sort by path length (shortest to longest) and then by name (alphabetically), meaning longer paths will be removed first.
These changes help ensure that deeper fields are more easily searchable, whilst the path limit per object ensures a reasonable cap when dealing with recursive structures, preventing the client from hanging when generating these on studio …

fix(core): various fixes and improvements to studio search [v2]

---

packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialog.tsx
packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialogBody.styles.tsx
packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx

Alignment was off in the unpublish/delete dialog when listing cross-references and internal reference referring to the document. 
The list of references has also had some smaller fixes: the external references is now also a link and there is now one scrollbar for all references. 
The delete/unpublish dialog of document with referring documents. 
Test scrolling 
Fixes alignment/scrolling issues of references in delete/unpublish dialog

fix(desk): minor style change of references in delete/unpublish dialog

---

packages/sanity/src/core/components/userAvatar/UserAvatar.tsx
packages/sanity/src/core/presence/DocumentPreviewPresence.tsx
packages/sanity/src/desk/components/PublishedStatus.tsx
packages/sanity/src/desk/panes/document/inspectors/changes/ChangesInspector.tsx
packages/sanity/src/desk/panes/document/statusBar/sparkline/PublishStatus.tsx
packages/sanity/src/desk/panes/document/statusBar/sparkline/ReviewChangesButton/ReviewChangesButton.tsx

Currently when a screen reader is using Sanity, no labels are read out about presence indicators, or understandable document status timestamps. This fixes that to some extent.
Test the with a screen reader where possible.
1. Navigate to a document
2. Use the document sparkline or pane header to get information about the document
Fixed various accessibility label issues in the desk tool

fix(core, desk): add accessible labels to presence indicators, publish status, and review changes

---

packages/sanity/src/core/form/inputs/files/FileInput/FileActionsMenu.tsx
packages/sanity/src/core/form/inputs/files/ImageInput/ImageActionsMenu.tsx
packages/sanity/src/core/form/inputs/files/common/FileInputMenuItem/FileInputMenuItem.styled.tsx
packages/sanity/src/core/form/inputs/files/common/FileInputMenuItem/FileInputMenuItem.tsx

There was a bug with the focus in the dropdown menu. Focus on hover would jump back to the first item when hovering over the dividers for dropdown menu for file/image. 
https://github.com/sanity-io/sanity/assets/44635000/43709138-4573-4912-b507-9f1830167d09
This pr adds logic to focus on first element only when the menu is closed, preventing the focus to be on the first element when hovering over the dividers. 
The dropdown menu for the file and image. 
Fixes issue where focus would jump to first element when hovering divider in menu

fix(core): add logic to focusFirst in customised popover

---

packages/sanity/src/core/components/commandList/CommandList.tsx

Small change: sets the mouse wheel listener on the virtual list element to be passive ([background](https://chromestatus.com/feature/5745543795965952)). This potentially speeds up the scrolling, and should be safe since we never call `preventDefault()` in the attached listener.
- Lists work as before
None.

fix(core): optimize wheel event on CommandList virtual element

---

packages/sanity/src/core/form/inputs/CrossDatasetReferenceInput/CrossDatasetReferencePreview.tsx

The cross dataset reference tooltip text was changed to avoid any confusion and to be consistent with the icon and text that is used in other places, for example in arrays (see screenshot)
The tooltip text for CDR 
Tooltip text for CDR was changed

fix(core): change cdr tooltip text

---

packages/@sanity/types/src/slug/asserters.ts
packages/@sanity/types/src/slug/index.ts
packages/@sanity/types/src/slug/types.ts

Will be used in the upcoming validation changes, for instance. Figured it was worth a separate PR for easier reviewing.
- Assertion looks okay (I don't think we need to go deeper - this matches the overall shape we need) 
- Added `isSlug()` method to `@sanity/types` for type-safe asserting of a slug object

feat(types): add `isSlug` asserter method

---

packages/sanity/src/desk/deskTool.ts

When multiple desks are configured for a studio, you ended up with duplicate change and validation inspectors.
This PR addresses this with the same approach as the badges/actions: it only adds those plugin elements if not already present, as part of the plugin configuration.
Also refactored the duplication checks to use a Set instead, as it is a little less verbose.
Supersedes #4743 if approved (will give credit to author as part of release notes, even though we didn't specifically use their code)
- No duplicate document inspectors, badges, or actions exists
- Fixed an issue where using multiple desk tools in the same studio would cause duplicate "review changes" actions and validation lists to appear. Thanks @andparsons!

fix(desk): prevent duplicate validation/change inspectors

---

packages/sanity/src/core/util/userHasRole.test.ts
packages/sanity/src/core/util/userHasRole.ts

This allows it to be used directly from a conditional property callback, where `null` is valid since a studio may not require authenticated users. In addition, the conditional property callback context have dropped the legacy `user` property, which meant the signature did not match.
- Made the `userHasRole` function more relaxed on user value, allowing easier use in places such as conditional callbacks

fix(core): allow `null` and `role`-less user in `userHasRole` fn

---

packages/sanity/src/desk/structureBuilder/DocumentList.ts
packages/sanity/src/desk/structureBuilder/GenericList.ts
packages/sanity/src/desk/structureBuilder/Intent.ts

Fixes 404 links for docs. Here are the the fixes and some current caveats
- `SchemaType` and `SortOrderingItem` are imported from `@sanity/types` whose docs are not exported yet
- `InitialValueTemplateItem` is in the core package, currently we don't have the ability to link from sub package to root package. i.e `desk` -> `core` linking is not currently possible
- `IntentJsonParams` and `BaseIntentParams` are duplicated in `desk` and `router` package but on docs we dedupe them and only one is shown, as a stopgap  we are linking to the `router` package which shows those interfaces but we will follow up with deduping the interfaces and fixing the links properly in the future
Everything still works
N/A

docs(desk): fix 404 links

---

packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
packages/sanity/src/core/store/_legacy/authStore/createLoginComponent.tsx
packages/sanity/src/core/store/_legacy/authStore/sessionId.ts

In certain rare cases, such as browsers inconsistently serving cookies, it may be helpful to explicitly turn off cookie-based authentication. This PR adds a new `token` option to the `loginMethod` property, which enables this.
I had to rewrite the flow in the auth store a bit to allow reuse between the `dual` and `token` options, but I think it reads slightly better now anyway. 
- Authentication works as before in Chrome/Firefox/Safari
- Setting the `loginMethod` to `token` and `cookie` works (`cookie` _may_ not work in some browsers, but you should be seeing the same behavior as _before this change_)
You can do so by using `createAuthStore()` - `sanity.config.ts`:
```ts
import {defineConfig, createAuthStore} from 'sanity'
// ...
auth: createAuthStore({ …
```

feat(auth): allow using explicit `token` mode for authentication

---

package.json
packages/@sanity/cli/package.json
packages/@sanity/cli/src/actions/init-project/initProject.ts
packages/@sanity/cli/src/actions/init-project/reconfigureV2Project.ts
packages/@sanity/import-cli/package.json
packages/@sanity/import/package.json
packages/@sanity/types/package.json
packages/@sanity/vision/package.json
packages/sanity/package.json
perf/package.json
yarn.lock

When a user has a large number of projects, and/or those projects have a large number of members, the API request might take a second to respond. Because we in many cases do not need the member list, we can speed up this request by omitting it. This PR does this for the request performed when initializing a new project, making for a slightly snappier experience for some users.
- `sanity init` works as before
- Improved performance when fetching projects list as part of the `sanity init` CLI command

fix(cli): improve performance of projects list

---

packages/sanity/src/core/validation/validators/stringValidator.ts

A regex validation rule using the global flag currently give intermittent validation errors, even for completely valid values:
https://github.com/sanity-io/sanity/assets/876086/4beccc45-1f4b-4a12-bc4b-01281e731687
This PR fixes the issue by resetting the regex state before testing input against it.
- Make sure validation works as intended with regexes with global (and sticky flags - which doesn't really make much sense to use for validation?). Here's an example of a field definition that currently give intermittent validation errors for valid values:
```ts
defineField({
name: 'fielda',
title: 'Field A',
description: 'Only letters, numbers and -_',
validation: (Rule) => Rule.required().regex(/^[A-Za-z0-9_-]*$/g),
}),
```
Props to @pauloborges for pointing straight at the …

fix(validation): reset regex state between validation checks

---

dev/test-studio/sanity.config.ts
packages/sanity/src/core/config/auth/types.ts
packages/sanity/src/core/config/prepareConfig.ts
packages/sanity/src/core/config/types.ts
packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
packages/sanity/src/core/store/_legacy/authStore/createLoginComponent.tsx
packages/sanity/src/core/store/_legacy/authStore/providerLogos.tsx
packages/sanity/src/core/store/_legacy/authStore/types.ts

~**Note**: builds on #4772 - please only review [this commit](https://github.com/sanity-io/sanity/commit/d0fab5cf4ebf4659f7c594eaaf00d52d91c9c448).~
When configuring the authentication aspects, you currently have to give it an `AuthStore`. This is not very ergonomic/developer friendly, and made worse by the fact that it requires you to duplicate project ID and dataset, as well as `createAuthStore` actually being marked as `@internal`.
With this change, I propose that we instead take a partial object of configuration parameters, such as `loginMethod`, `providers` etc, and merge these into the default options and internally call `createAuthStore()`. I left the `AuthStore` as an option because it can be useful for mocking and backwards compatibility, but we should discourage people from …

feat(auth): allow specifying options without createAuthStore()

---

packages/sanity/src/_internal/cli/actions/graphql/gen1/generateTypeFilters.ts
packages/sanity/src/_internal/cli/actions/graphql/gen2/filters/booleanFilters.ts
packages/sanity/src/_internal/cli/actions/graphql/gen2/filters/dateFilters.ts
packages/sanity/src/_internal/cli/actions/graphql/gen2/filters/dateTimeFilters.ts
packages/sanity/src/_internal/cli/actions/graphql/gen2/filters/floatFilters.ts
packages/sanity/src/_internal/cli/actions/graphql/gen2/filters/integerFilters.ts
packages/sanity/src/_internal/cli/actions/graphql/gen2/filters/stringFilters.ts
packages/sanity/test/cli/graphql/__snapshots__/gen2.test.ts.snap
packages/sanity/test/cli/graphql/__snapshots__/gen3.test.ts.snap

Adds a `is_defined` field filter for all generations, which can be used to remove null values from responses.
Are we happy for this to be backported to all schema generations?
- GraphQL APIs now have a new `is_defined` filter, mirroring the `defined()` function in GROQ. GraphQL APIs will have to be re-deployed to enable the new filter.

feat(cli): add `is_defined` filter to GraphQL APIs

---

packages/sanity/src/_internal/cli/actions/graphql/deleteApiAction.ts
packages/sanity/src/_internal/cli/actions/graphql/deployApiAction.ts
packages/sanity/src/_internal/cli/actions/graphql/listApisAction.ts

New version of GraphQL is being released, this defaults to using the new version for all GraphQL commands.
This does affect the output as it will now display the new version.

chore(cli): use latest API version for GraphQL API calls

---

packages/@sanity/cli/src/commands/manage/manageCommand.ts

`manage.sanity.io` has not been used for a while - we should use the new URL to prevent redirects.
- Code change looks good
- Fixed the URL generated by the `sanity manage` CLI command
[sc-35955]

fix(cli): correct URL for the `sanity manage` command

---

packages/sanity/src/desk/panes/document/documentPanel/documentViews/FormView.tsx
packages/sanity/src/desk/panes/document/documentPanel/documentViews/styles.ts
packages/sanity/src/desk/panes/document/documentPanel/header/DocumentHeaderTitle.tsx
packages/sanity/src/desk/panes/document/index.ts
packages/sanity/src/desk/panes/document/useDocumentTitle.ts

Adds a document title to the document panel. Note this does not include the title treatment when editing just shows the title. 
1. Does the hook makes sense
2. Does the location of the hook make sense
N/A (Part of bigger release announcement)

feat(core): adds title to document panel

---

package.json
packages/@sanity/portable-text-editor/package.json
packages/@sanity/types/src/schema/test/alias.test.ts
packages/@sanity/types/src/schema/test/document.test.ts
packages/@sanity/types/src/schema/test/file.test.ts
perf/package.json
yarn.lock

This upgrades TypeScript to latest 5.x. Very few changes needed to be done to the code base except from adjusting and adding few expect-error directives (kept in a separate commit 909b93fc26367e3cd8671cb8638f789c99f47f58).
- Can this have unintended consequences? From what I can tell by reading the [release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#breaking-changes-and-deprecations) there doesn't seem to be any breaking changes with the declaration output, so types generated by 5.x should still work in projects using 4.x
N/A - transparent to end users/devs

chore: upgrade typescript to 5.x

---

packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx
packages/sanity/src/desk/panes/document/documentPanel/DeletedDocumentBanner.tsx
packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
packages/sanity/src/desk/panes/document/timeline/timelineItem.tsx
packages/sanity/src/desk/panes/document/timeline/timelineMenu.tsx

This PR handles primarily addresses two issues:
1. An edge case where the timeline menu wouldn't be accessible:
- User 1 selects an older document revision
- User 2 deletes the document
- User 1 is able to restore the document (to the most recent version), but is then unable to access the timeline menu
2. Review changes' dropdowns not working (due to the timeline menu being disabled) in deleted documents 
Other changes have been outlined as comments!
Finally, a video demonstrating some of the paths that were tested:
https://github.com/sanity-io/sanity/assets/209129/f028ead1-3203-46bf-b6a6-63c5fc1682a2

fix(desk): handle edge cases when documents are deleted on a specific revision

---

package.json
packages/@sanity/cli/package.json
packages/@sanity/export/package.json
packages/@sanity/import-cli/package.json
packages/@sanity/import/package.json
packages/@sanity/types/package.json
packages/@sanity/vision/package.json
packages/sanity/package.json
perf/package.json
renovate.json
yarn.lock

Fixes #4808, which is caused by package managers (npm, yarn, pnpm) very lazily bumping dependencies over time. More information in #4808. 
Also tunes renovatebot to create PRs that bump `@sanity/client` and `get-it` to reduce the risk for this to happen to our users in the future.
If it builds it works.
fix: ensure package managers pulls in the `get-it` version that `@sanity/client` needs

fix: ensure `@sanity/client` pulls in the right `get-it` version

---

packages/sanity/src/core/store/_legacy/document/listenQuery.ts
packages/sanity/src/core/store/_legacy/document/types.ts
packages/sanity/src/desk/panes/documentList/listenSearchQuery.ts

The listener requests we use for document lists are set up with visibility=query, however, this does not guarantee that the listener events arrive after their mutations have been made visible to queries.
From our docs about [listener visibility](https://www.sanity.io/docs/listening#visibility-c4786e55c3ff):
> (...) listeners with `query` may in certain cases (notably with deferred transactions) receive events that are not yet visible to queries. The visibility event field will indicate the actual visibility.
This will often enough lead to document lists in the Studio not reflecting the actual reality of the data store. One fairly consistent way of reproducing the issue is to create a new document, make a single change (e.g. type a single character in a text field) and watch the newly …

fix: delay refetching for listener events arriving with visibility != query

---

packages/sanity/package.json
yarn.lock

Supersedes #4817 which only updates the lockfile. We want to force the new version.
Upgrades `groq-js` to fix an issue where parenthesis around a GROQ-filter (used in access control rules) would crash the studio. Eg:
```
_type == 'article' // Fine
(_type == 'article') // Crash
```
Actual fix is here: https://github.com/sanity-io/groq-js/pull/133/files
- ACL checks still works as expected in studio
- Fixes an issue where certain GROQ-filters used for access control rules would crash the studio

fix(core): parenthesis around GROQ-filters crashing ACL checks

---

packages/sanity/src/desk/components/breadcrumbs/BreadcrumbItem.tsx
packages/sanity/src/desk/components/breadcrumbs/Breadcrumbs.tsx
packages/sanity/src/desk/components/breadcrumbs/__workshop__/BreadcrumbsStory.tsx
packages/sanity/src/desk/components/breadcrumbs/__workshop__/index.ts
packages/sanity/src/desk/components/breadcrumbs/breadcrumbs.styles.ts
packages/sanity/src/desk/components/breadcrumbs/index.ts
packages/sanity/src/desk/components/pane/PaneHeader.tsx
packages/sanity/src/desk/panes/document/documentPanel/header/DocumentHeaderTitle.test.tsx
packages/sanity/src/desk/panes/document/documentPanel/header/DocumentHeaderTitle.tsx

This is the first pass at implementing the breadcrumbs on the title document header. This is not the complete solution but getting the pieces to iterate on improving this in future tickets. 
- Show tooltip if text is overflowing
- Clicking on the breadcrumb item navigates to the correct pane
- Dynamic adjustment of breadcrumb size
- Mobile styles
- Opening Reference item in sidebar should show it's structure
Note: The test is skipped and I will come back to it when everything is finalized
- Check the breadcrumb in the [workshop](https://test-studio-git-feature-sc-35253.sanity.build/test/workshop/desk;components;Breadcrumbs;normal?scheme=dark&value=eJyrrgUAAXUA%2BQ%3D%3D) 
- The breadcrumb component is somewhat copied from [sanity/ui](https://github.com/sanity-io/ui/blob/main/src/components …

feat(core): add breadcrumbs to document header

---

packages/sanity/package.json

Adding `"sideEffects": false` helps bundlers shake out more dead code resulting in smaller bundles of anything library consuming the base `sanity` package. 
Fixes #4711 
Confirm no dependent packages were depending on `sideEffect` code.
Add sideEffects: false to package.json for smaller bundles

chore(sanity): :zap: add sideEffects: false to package.json for smaller bundles

---

packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts
packages/sanity/src/desk/components/paneRouter/PaneRouterContext.tsx
packages/sanity/src/desk/components/paneRouter/PaneRouterProvider.tsx
packages/sanity/src/desk/components/paneRouter/types.ts
packages/sanity/src/desk/documentActions/DeleteAction.tsx
packages/sanity/src/desk/panes/document/DocumentOperationResults.tsx
packages/sanity/src/desk/panes/document/DocumentPaneContext.ts
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx
packages/sanity/src/desk/panes/document/documentPanel/DeletedDocumentBanner.tsx
packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
packages/sanity/src/desk/panes/document/timeline/timeline.tsx
packages/sanity/src/desk/panes/document/timeline/timelineItem.styled.tsx
packages/sanity/src/desk/panes/document/timeline/timelineItem.tsx
packages/sanity/src/desk/panes/document/timeline/timelineMenu.tsx
packages/sanity/src/desk/types.ts

This fixes an issue where the document pane of the deleted document was left open after the document was deleted, including any open panes to the right.
After this change, all open panes to the right including the deleted one will close.
We will also show a banner similar to the permissions banner that includes a restore button if another user has the document open.
Example video:
https://github.com/sanity-io/sanity/assets/209129/1276151f-dad4-48db-87c9-bcbc6fc52504
- That all panes to the right including the deleted document pane closes when you delete the document
- That the delete confirmation toast shows
- Another user has the deleted document open: That the Deleted document banner shows for the user
- Another user has the deleted document open: That the user is able to restore the …

fix(desk): close document panes when document is deleted

---

packages/sanity/README.md

Add helpful links to header of README:
- Get Started (`sanity.io/get-started`)
- Docs (`sanity.io/docs`)
- Website (`sanity.io`)

docs: add ctas to readme header

---

.github/workflows/lint-fix-if-needed.yml

When I added the `lint-fix-if-needed.yml` GitHub action I forgot to take into account that ESLint is also setup to run Prettier.
And so if code lands on `next` that needs prettier you get two identical PRs:
- https://github.com/sanity-io/sanity/pull/4840
- https://github.com/sanity-io/sanity/pull/4839
We already have a `prettier-if-needed.yml`, which runs Prettier also on files that ESLint usually ignores. Like `.yml`, `.html`, `.md` and `.json` files and more.
This PR changes the linter GitHub action to ignore the prettier rule and instead let the prettier action handle that. So we don't get doubly noise.
If it builds it works, and the actual test won't happen until this PR is merged.
N/A

chore(CI): remove double PRs on prettier fixes

---

packages/sanity/src/core/components/previews/_common/Media.styled.ts

This pull request addresses an issue where media for list previews wouldn't always be visible in Safari when a custom SVG element is configured (as reported in [#4074](https://github.com/sanity-io/sanity/issues/4074)). Currently, the media is visible only if the SVG element has both width and height attributes. This pull request ensures that the SVG is visible even when these attributes are absent.
```ts
const myDocument = defineType({
name: 'myDocument',
title: 'My document',
icon: () => <svg>...</svg>,
})
```
- Make sure that media is rendered as expected
Fixes media visibility issue in Safari for list previews with custom SVG element

fix(core): svg preview issue in safari

---

packages/sanity/src/desk/components/pane/PaneHeader.tsx

The action icons (the icons to the right) in the pane header were not centered and did not match the back button and the header. 
The pane header for mobile and desktop. Make sure alignment is not off for any elements. 
Fixes alignment of action items in pane header.

fix(desk): center align pane header action icons

---

packages/sanity/src/core/studio/components/navbar/NavDrawer.tsx
packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
packages/sanity/src/core/studio/components/navbar/resources/ResourcesButton.tsx
packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx

Tooltips remained on screen after opening a `MenuButton`  (most notably on both the Workspaces + Help navbar buttons) in the navbar. 
To prevent the tooltip from showing underneath the `MenuButton` when it is open, the `tooltip` is `disabled` when the `MenuButton` is open. 
The `Workspaces` and the `Help and Resources` dropdowns - make sure that they work as expected. 
Fixes annoyance where tooltip was showing under menubutton.

fix(core): close navbar tooltips when menubutton is open

---

packages/sanity/src/core/form/studio/inputResolver/fieldResolver.tsx

Cross dataset references had the wrong level/depth. There was no check for cdr schematype in the `fieldResolver.tsx`, which resulted in the field type for cdr to be `ObjectOrArrayField`. This PR adds a check for `isCrossDatasetReferenceSchemaType` and rendering a `PrimitiveField` in that case, removing the indent for a cdr.  
Make sure that the `PrimitiveField` works as intended for a cross dataset reference. 
Fixes indent bug for cross dataset references

fix(core): add check for cdr schematype and use PrimitiveField

---

packages/sanity/playwright-ct/tests/formBuilder/ArrayInput.spec.tsx
packages/sanity/playwright-ct/tests/formBuilder/PortableTextInput.spec.tsx
packages/sanity/playwright-ct/tests/utils/testHelpers.tsx

This will fix the Playwright form tests to work on Linux (and CI). There were two issues:
* Platform name was returned incorrectly sometimes (confirmed on local Linux)
* To trigger hotkeys (at least on the PT-input), you have to do that on Linux with a combination of metaDown + hotkeyPress + metaUp (`playwright.page.press('Meta+b')` will not work on Linux). I suspect it's either the way the hotkey event listeners are implemented in the PTE, or it could be a Linux-specific behavior in how keyboard events are handled in the browser.
I have moved the 'focusPTE' method into two separate functions that can target either the PortableTextInput element as a whole (`getFocusedPortableTextInput`), and another that targets the Portable Text Editor within the input (`getFocusedPortableTextEditor`). …

test(playwright): fix hotkey activation + helper method

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditor.test.tsx

On WebKit the 'Empty' placeholder for the Portable Text Editor is oddly placed. Changing the container from a `div` to a `span` will fix that.
Before:
Now:
That it looks the same on the supported browsers.
* Fixed odd placement of "Empty" placeholder in the Portable Text Editor on WebKit browsers.

fix(portable-text-editor): fix empty placeholder placement for webkit

---

dev/test-studio/structure/resolveStructure.ts
packages/sanity/src/desk/panes/documentList/useDocumentList.ts
packages/sanity/src/desk/structureBuilder/DocumentList.ts
packages/sanity/src/desk/structureBuilder/SerializeError.ts

Currently, specifying `apiVersion` on either `documentList()` or `documentTypeList()` has no effect. This PR fixes it by forwarding the option to the `useClient()`-call in `useDocumentList()`
Make sure specifying `apiVersion(<version>)` on documentList and documentTypeList results in `<version>` actually being used when fetching documents
- Fixed a bug that made specifying `apiVersion` on `documentList()` and `documentTypeList()` not work

fix(desk): use configured api version when fetching document lists

---

packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts

When the validation machinery is validating the existence/publish state of referenced documents, we subscribe to existence state and keep a local map of `<documentId, existenceStatus>`. However, if the validation asks for existence status before it's loaded, it will get back `undefined`, which is taken to mean "document doesn't exist". This again, causes the UI to render the reference field as invalid for a brief moment until the reference status actually arrives. This PR fixes the issue by waiting until the `documentId` is present in the `<documentId, existenceStatus>`, which means we have actually received the existence status.
- Observe initial flashes of validation errors in the following test document in [next](https://test-studio.sanity.build/test/content/input-standard;arraysTest;bf …

fix(core): wait for availability status to arrive before passing on document existence status

---

packages/@sanity/portable-text-editor/src/editor/plugins/createWithPortableTextMarkModel.ts
packages/@sanity/portable-text-editor/test/__tests__/selectionAdjustment.collaborative.test.ts
packages/@sanity/portable-text-editor/test/__tests__/writingTogether.collaborative.test.ts
packages/@sanity/portable-text-editor/test/setup/collaborative.jest.env.ts
packages/@sanity/portable-text-editor/test/setup/globals.jest.ts

Found a bug where if you toggle different decorators in sequence while
typing along, it can sometimes reset your applied decorator when reconciling with
the server value.
This was happening because we didn't specify the `_type` when splitting text
nodes with a new mark, and the new node would miss the span type.
The normalizer function would then assign the 'span' type to it however,
but it is not setting the marks (it's not the responsibility of that normalization).
This will make sure we don't need to normalize in this situation in the first place,
and that the type is correctly set in the split operation when toggling the mark.
That you can perform the following sequence and keep the marks intact:
* Empty editor
* Press hotkey `cmd+b`
* Write a word
* Press hotkey `cmd+b`
* Press …

fix(portable-text-editor): fix issue with sequencing mark toggles

---

packages/@sanity/cli/package.json
packages/@sanity/cli/src/actions/init-project/initProject.ts
packages/@sanity/cli/src/commands/init/initCommand.ts

The CLI is currently built to a compiled bundle for a speedier installation. This means the `@vercel/fs-detectors` and `@vercel/frameworks` modules both become part of the bundle, and do not need to be runtime dependencies. By moving them to dev dependencies, we both reduce installation time and (as a side effect) reduce noise about [a vulnerability](https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795) that does not impact the CLI.
- Building the CLI and running the `sanity init` command works, even without the `@vercel` dependencies in your node modules resolution tree
None.

chore(cli): move vercel dependencies to dev dependencies

---

packages/sanity/src/core/form/studio/inputResolver/fieldResolver.tsx

There was no check for the `slug` schematype, resulting in it rendering an `ObjectOrArrayField`. Hence it was lacking a `<label>` for the `title`. This PR adds a check for `slug` schematype and renders a `PrimitiveField` instead. 
The `slug` schematype - that it works as expected and that the title is wrapped in a `label`
Change field type of slug from `ObjectOrArrayField` to `PrimitiveField`

fix(core): use primitiveField for slug schema type

---

packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts

This fixes a regression in #4860 that would sometimes prevent document existence check from being run at page load.
- Make sure validation of unpublished references works as intended both when creating and after reload (the referenced document needs to be published)
- Make sure the "initial flash of validation error" fixed by #4860 is still fixed
- Fixes a regression in v3.16.0 that prevented reference validation errors from appearing in certain cases

fix(core): preserve earlier document availability status

---

packages/sanity/playwright-ct.config.ts
packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Annotations.spec.tsx
packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Decorators.spec.tsx
packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/DecoratorsStory.tsx
packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Input.spec.tsx
packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ObjectBlock.spec.tsx
packages/sanity/playwright-ct/tests/utils/testHelpers.tsx
packages/sanity/src/core/form/inputs/PortableText/toolbar/ActionMenu.tsx

Refactor PT-input overlay activation to reuse code, and get around an issue on Webkit/Linux where tests would randomly
fail.
* Test decorator default icons and customizing decorators with your own icon.
* Enable previously skipped decorator tests for Webkit on Linux (issues resolved).
* Simplify an assert statement
* Simplify some locator queries
* Await text when `insertPortableText`
* Test toggling of decorator buttons (should be rendered active)

test(playwright-ct): add to tests

---

.github/workflows/e2e-ct.yml
.github/workflows/e2e.yml
.github/workflows/etl.yml
.github/workflows/perf.yml
.github/workflows/test.yml

Remote caching in turborepo is working everywhere but GH Actions, turns out it's because of an expired token.
GH Actions should now report "Cache hit" on `yarn build` a lot of the time, and if re-running the action and its previous build didn't error then it should have "Cache hit" 100% of the time.
N/A

chore(ci): fix remote caching on gh actions

---

packages/@sanity/schema/src/sanity/coreTypes.ts
packages/@sanity/schema/src/sanity/validation/types/block.ts
packages/@sanity/schema/test/validation/validation.test.ts

Block members can not be given a type that is not an object-like type, but nothing is stopping you today and can lead to strange errors.
For instance, a type like `{type: 'string'}` doesn't make sense inside block children, as they have to be wrapped in an object. We do however have core types that are object-like, like image, file, and reference that should be
supported.
We also have the core type 'span', which I have included in the core types in this PR (I think it was an oversight). This should however not be supported here (as it's injected automatically into the schema). Thus we also need
an allow list for those core object types that actually are supported.
I have identified the following supported core types for the block schema type `of`:
```
['file', 'image', 'object', …
```

feature(schema): improve validation of block members

---

packages/sanity/src/core/config/types.ts
packages/sanity/src/core/studio/StudioLayout.tsx
packages/sanity/src/desk/components/deskTool/DeskTitle.test.tsx
packages/sanity/src/desk/components/deskTool/DeskTitle.tsx
packages/sanity/src/desk/components/deskTool/DeskTool.tsx
packages/sanity/src/desk/deskTool.ts
packages/sanity/src/desk/structureResolvers/useResolvedPanes.ts

When the user is moving through documents and panes, update the title property to be  more specific to the current route
Update the `<title>` element to be more specific to the current route every time a user follows a link in the studio.
Changes titles to use pipes as divider, in the title structure, mention first the most unique thing.
- Previously: `Test Studio - Content`
- Updated:  `Content | Test Studio`
Uses the following pattern:
- Desk root: `{{tool}} | {{desktoolTitle}}`
- Document list: `{{paneTitle}} | {{desktoolTitle}}`
- Document: `{{documentTitle}} | {{desktoolTitle}}`
- Document (new): `New {{schemaTitle}} | {{desktoolTitle}}`
Titles inside the studio, navigating through documents in the desk and also navigating between tools.
Update the <title> element to be more specific …

feat(titles): Update titles inside desk tool

---

packages/sanity/src/desk/panes/document/inspectors/validation/ValidationInspector.tsx

The validation document inspector currently uses the path as react key, assuming only one validation marker per path, which is not always the case. Couldn't find any unique value on the validation markers, so this fixes it by using index as key instead.
- Make sure validation inspector can handle multiple validation errors for the same field/node
- Fixes a react key error when having multiple validation errors for the same document node

fix(desk): use index as key instead of path

---

packages/sanity/src/core/form/inputs/Slug/SlugInput.tsx
packages/sanity/src/core/i18n/bundles/studio.ts

Convert slug input strings to use i18n primitives 
That all items/strings within the vision are not broken and work as expected.
N/A

feat(core): convert slug input to use i18n primitives 

---

packages/sanity/src/desk/components/deskTool/DeskTool.tsx
packages/sanity/src/desk/components/pane/__workshop__/ChangeConnectorsStory.tsx
packages/sanity/src/desk/components/pane/__workshop__/SplitPanesStory/SplitPanesStory.tsx
packages/sanity/src/desk/panes/document/DocumentPane.tsx

This PR ensures that object dialogs are correctly positioned at smaller breakpoints (when the desk collapses into a single pane layout).
There was previously a mismatch between theme breakpoints (used by `<DialogProvider>`) and the `minWidth` value in `<StyledPaneLayout>`. Desk would collapse into a single pane at `512px` whilst dialogs would only use `fixed` positioning at `< 360px`. 
This PR ensures the desk tool will collapse at a theme media breakpoint instead of a hardcoded value, so it should be in lock-step with `<DialogProvider>` moving forward.
Collapse your viewport enough so that the studio desk collapses into a single column layout.
In the following examples, scroll to the bottom of the page and click either the 'Sydney' or 'Melbourne' events
- …

fix(desk): use correct dialog positioning at smaller breakpoints

---

.github/workflows/docReport.yml
.github/workflows/docReportTeardown.yml
scripts/doc-report/docReportCleanup.ts

- add more logging in delete script
- use PR numbers as dataset names instead of github ref
- fixes turbo token in docs actions 
Seems like when the PR is closed the ref actually points to the next branch so it ends up deleting the next dataset. It seems like the `github.event.number` should be more consistent. [Reference](https://shipit.dev/posts/trigger-github-actions-on-pr-close.html) 
N/A

chore(docs): fix dataset delete script

---

packages/sanity/src/core/form/components/formField/FormFieldValidationStatus.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferencePreview.tsx
packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx
packages/sanity/src/desk/components/NotPublishedStatus.tsx

Adding some aria-labels for accessibility.

fix(core): add aria-label to reference publish icons

---

packages/@sanity/import/test/import.test.js

One of the tests in the `@sanity/import` package cufrently fails in node v20 due to JSON parse errors having a slightly different error message. This fixes it by using a regex that verifies the first part of the error message, which is unchanged between node v18 and v20.
Change looks ok, tests are passing
N/A

test(import): fix test failure caused by error message update in node v20

---

packages/sanity/src/desk/components/breadcrumbs/BreadcrumbItem.tsx
packages/sanity/src/desk/components/breadcrumbs/Breadcrumbs.tsx
packages/sanity/src/desk/components/breadcrumbs/breadcrumbs.styles.ts

Hides the breadcrumbs on mobile screen and shows only the title
Code makes sense
N/A

feat(core): add mobile styles for breadcrumbs

---

packages/sanity/src/desk/panes/document/documentPanel/documentViews/FormTitle.tsx
packages/sanity/src/desk/panes/document/documentPanel/documentViews/FormView.tsx
packages/sanity/src/desk/panes/document/documentPanel/documentViews/styles.ts

This PR enables so that when you are editing the form the title does not do a layout shift. It only changes it's height when any of the form fields are not focused.
FIXES SDX-672
~This was a little complicated to implement, the way this works if there are two elements created. One is the actual display and the other one is a `visibility:hidden` element, the reason to keep visibility is so it still occupies the height so we can calculate it. When you focus on the form it changes hidden title's style to text overflow and then uses it's `scrollWidth` and `clientWidth` to calculate the height. This height is then set to the title that is displayed and it has an overflow of hidden so it does not cause a layout shift when the content is greater then the height.~
~I would love to know if there …

feat(core): avoid layout shift when editing title

---

.github/workflows/test.yml

Node 16 goes out of maintenance [LTS](https://nodejs.dev/en/about/releases/) today, so let's drop it form our test matrix. Also, probably a good idea to add v20 now.
- Tests are passing
- Drop Node 16.x from CI test matrix

chore(ci): drop Node v16 from test matrix, add Node v20

---

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditor.test.tsx
packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditorTester.tsx
packages/sanity/src/core/form/components/formField/FormFieldHeaderText.tsx
packages/sanity/src/core/form/components/formField/FormFieldSet.tsx
packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx
packages/sanity/src/core/form/inputs/PortableText/Editor.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx
packages/sanity/src/core/form/members/array/items/ArrayOfObjectsItem.tsx
packages/sanity/src/core/form/members/array/items/ArrayOfPrimitivesItem.tsx
packages/sanity/src/core/form/members/common/constructDescriptionId.ts
packages/sanity/src/core/form/members/common/createDescriptionId.ts
packages/sanity/src/core/form/members/object/MemberFieldset.tsx
packages/sanity/src/core/form/members/object/fields/ArrayOfObjectsField.tsx
packages/sanity/src/core/form/members/object/fields/ArrayOfPrimitivesField.tsx
packages/sanity/src/core/form/members/object/fields/ObjectField.tsx
packages/sanity/src/core/form/members/object/fields/PrimitiveField.tsx
packages/sanity/src/core/form/studio/FormBuilder.tsx
packages/sanity/src/core/form/studio/inputResolver/fieldResolver.tsx
packages/sanity/src/core/form/types/inputProps.ts

In the editor, some fields have a description in addition to just a label. This description is not associated with the field in code. This makes it harder to discover for some users, including screenreader users.
With this changes, when fields have a description, this description will be associated to the input by using `aria-describedby`. This is discoverable by screen readers.
**Note**: Couldn't make it work in portable text editor correctly, as the focused element in PTE is not the same one that receives the aria-describedby value when passing the prop , a follow up ticket will be created for this.
Is there any missing field type to consider?
To trigger the descriptions using voice over functionality you have to:
1) Focus on the field, voiceover will let you know it has more …

feat(WCAG): Associate field descriptions to inputs

---

packages/sanity/src/desk/documentActions/HistoryRestoreAction.tsx

This PR fixes the hacky workaround in https://github.com/sanity-io/sanity/pull/4668 in a more predictable way where it only navigates to the intent when the operation is successfully completed.
The solution makes sense and there would be no side effects of this change. 
- Fixes issue with restoring document history in nested panes

fix(core): fixes issue with restoring document in nested panes

---

packages/@sanity/import/src/importBatches.js
packages/@sanity/import/src/references.js
packages/@sanity/import/src/uploadAssets.js

We had some concurrency issues when strengthening references in parallel, but this hasn't been the case for years now. This improves the performance of the import by doing more strengthening in parallel.
- Importing still works as expected
- Improved performance of dataset imports using the `sanity dataset import` command/`@sanity/import` module

fix(import): increase concurrency of patching, document creation

---

dev/test-studio/components/TranslateExample.tsx
dev/test-studio/locales/index.ts
dev/test-studio/structure/resolveStructure.ts
packages/sanity/src/core/i18n/LocaleContext.ts
packages/sanity/src/core/i18n/Translate.tsx
packages/sanity/src/core/i18n/__tests__/Translate.test.tsx
packages/sanity/src/core/i18n/__tests__/simpleParser.test.ts
packages/sanity/src/core/i18n/components/LocaleProvider.tsx
packages/sanity/src/core/i18n/hooks/useLocale.ts
packages/sanity/src/core/i18n/index.ts
packages/sanity/src/core/i18n/simpleParser.ts
packages/sanity/src/core/studio/screens/schemaErrors/SchemaProblemGroups.tsx

Implements a simple tags/components (not html!) parser for use with i18n, plus a <Translate component that takes a translation key and a component map, looks up the a translation string associated with the key, and replaces any `<Component>` parts of the translation string with the matching component provided through the `componentMap`.
- See unit tests for the [parser](https://github.com/sanity-io/sanity/blob/13dcc260cf483f194e5b53c22ae2c08d5c07540e/packages/sanity/src/core/i18n/__tests__/simpleParser.test.ts) or the [Translate](https://github.com/sanity-io/sanity/blob/13dcc260cf483f194e5b53c22ae2c08d5c07540e/packages/sanity/src/core/i18n/__tests__/Translate.test.tsx) component for more details
- Example usage [here](https://github.com/sanity-io/sanity/blob/de9a406d58a7314b11c640011c7cda9 …

feat(i18n): implement a very simple tags/components parser to use in a Translate component

---

packages/sanity/src/core/field/diff/changes/undoChange.ts

There was an issue with reverting changes in arrays of primitives. The list would not be cleared when trying to revert all changes. 
This had to do with shifting indices of the items, but not on the patch operations, so that triggering this operation 
```
{
unset: ['arrayOfStrings[0]', 'arrayOfStrings[1]', 'arrayOfStrings[2]']
}
```
will remove the first and last item, but the `arrayOfStrings[1]` will be left out of the patch operation. 
By reversing the order of the items in the `unset` operations, the issue with shifted indices will not cause problems. 
`{ unset: ['arrayOfStrings[2]', 'arrayOfStrings[1]', 'arrayOfStrings[0]'] }`
Reverting changes, especially for arrays, are working as expected. 
Fixed issue where reverting all changes did not clear the list

fix(core): unset changes in reverse order in patch operation

---

packages/@sanity/cli/src/actions/init-project/templates/nextjs/schemas/blog.ts

This PR corrects schema errors that were previously present when initializing a new project inside of a Next app using the default blog template without Typescript.
In [packages/@sanity/cli/src/actions/init-project/templates/nextjs/schemas/blog.ts](https://github.com/sanity-io/sanity/compare/feat/fix-no-ts-nextjs-blog-template?expand=1#diff-b9fdd7bd4e02ade67fa60e59aa6aa13457fe000faa58f91fc352923ad1c10ccf), the following changes have been made:
1. All schemas ending in JS have been changed from `export default <name>` to `export const <name>`
2. `blogSchemaJS` has been changed to use named imports where they previously use default imports.
3. Removes errant `)` in postJS
Fixes syntax errors in schema files when initializing a blog template without Typescript in a Next.js app.

fix: syntax issues in next.js JS blog template

---

dev/test-studio/schema/debug/virtualizationDebug.tsx
packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx

This PR adds a debug schema, the issue is when you have an array of items in a field group which is smaller then the height of the window which does not provide a scroll bar the virtualizer does not trigger a re-render causing items to not be recalculated and missing items in the array. 
The fix adds a key to the scroll element which will cause it to change when the field group changes. This change in the scrollbar should trigger a recalculation in the virtualization library according to this lines of [code](https://github.com/TanStack/virtual/blob/beta/packages/virtual-core/src/index.ts#L376)   
Fixes an issues with array items not showing all items inside a field group under specific conditions

fix(core): fix array items not showing in field groups

---

packages/sanity/src/core/form/inputs/CrossDatasetReferenceInput/ReferenceAutocomplete.tsx
packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceAutocomplete.tsx
packages/sanity/src/core/studio/components/navbar/search/components/filters/documentTypes/DocumentTypesButton.tsx

The new default fallback  placements for popovers released in Sanity UI v1.8.2 are good for most use cases, but in the Studio it has been causing issues for popovers used by the reference input, cross dataset reference input and the document type selector used by the array input.
This PR fixes these issues by explicitly choosing better fallback placements.
Make popovers used by the following components places themselves where they should and renders nicely:
- reference input,
- cross dataset reference input
- the document type selector used by the array input.
- Fixed rendering issues with certain popovers being caused by wrong placement

fix(core): set default placements for certain studio popovers

---

packages/sanity/src/core/components/commandList/CommandList.tsx

Items in document lists were marked up as `div` elements, but semantically, they are lists. The list items are now `li`, while the wrapper is a `ul`. 
Make sure that document lists work as intended and that semantically, they are correct. 
Improves accessibility for document lists

fix(core): accessibility improvements on document lists

---

packages/sanity/src/core/config/prepareConfig.ts

Currently, when using `<Studio config={[workspaceOptions1, workspaceOptions2]}>` each workspace will still be setup/prepared at each render, even if they're unchanged, causing the studio to reload. This PR fixes this by keeping a weakmap between each given workspace options and the prepared workspace summary, and using the previously prepared one where there's no change between renders.
- Is this a sound approach?
- N/A

fix(core): re-use previously prepared workspace configs

---

examples/clean-studio/README.md

* Fixed link to "Getting started" in clean readme (which is used when creating a new project).
* Validate if the new link is correct.
fix(docs): fixed broken getting started link in clean readme

fix(docs): fixed broken getting started link in clean readme

---

packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts

This fixes an issue that currently happens when editing a document that has a reference to an unpublished document, switching to another document and then switching back. Sometimes this could lead to the validation error for unpublished document reference being ignored.
Steps to reproduce:
1. Go to https://test-studio.sanity.build/test/content
2. Navigate to `Standard Inputs`  > `Reference Test` > `REPRO SDX-736 #1`" and observe that the reference field has the correct validation error
3. Switch to `REPRO SDX-736 #2`
4. Switch back to `REPRO SDX-736 #1`" and notice that the validation error has disappeared.
Go to the branch deployment (https://test-studio-git-sdx-736.sanity.build/test/content) and make sure the above steps does not cause the validation error to disappear
I also took the …

fix(core): make sure to re-emit current edit state when re-subscribing to document validation

---

packages/sanity/src/core/form/inputs/files/common/ActionsMenu.tsx
packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx

Replaces the `ClipboardIcon` for "copy" events to the `CopyIcon`
That this icon makes sense?
Updated icon for copy buttons

chore: change clipboard icon to copy icon

---

dev/test-studio/schema/debug/comments.ts
packages/sanity/src/core/comments/__workshop__/CommentDeleteDialogStory.tsx
packages/sanity/src/core/comments/__workshop__/CommentsListStory.tsx
packages/sanity/src/core/comments/__workshop__/CommentsProviderStory.tsx
packages/sanity/src/core/comments/__workshop__/index.ts
packages/sanity/src/core/comments/components/CommentDeleteDialog.tsx
packages/sanity/src/core/comments/components/avatars/SpacerAvatar.tsx
packages/sanity/src/core/comments/components/list/CommentThreadLayout.tsx
packages/sanity/src/core/comments/components/list/CommentsList.tsx
packages/sanity/src/core/comments/components/list/CommentsListItem.tsx
packages/sanity/src/core/comments/components/list/CommentsListItemLayout.tsx
packages/sanity/src/core/comments/components/pte/comment-input/CommentInput.tsx
packages/sanity/src/core/comments/components/pte/comment-input/Editable.tsx
packages/sanity/src/core/comments/context/CommentsProvider.tsx
packages/sanity/src/core/comments/hooks/useCommentOperations.ts
packages/sanity/src/core/comments/store/reducer.ts
packages/sanity/src/core/comments/store/useCommentsStore.ts
packages/sanity/src/core/comments/types.ts
packages/sanity/src/desk/comments/inspector/CommentsInspector.tsx

feat: comments create error handling

---

packages/sanity/src/core/i18n/Translate.tsx
packages/sanity/src/core/i18n/__tests__/Translate.test.tsx
packages/sanity/src/core/i18n/hooks/useLocale.ts

Three minor changes:
- Drop some unused imports from `useLocale` hook
- Make `components` prop required for `<Translate />` component in order to discourage using it when not needed (can always bypass with `components={{}}` if necessary)
- Allow string arrays as values to `<Translate />`. This allows us to use the [list formatting function](https://www.i18next.com/translation-function/formatting#list).

refactor(i18n): couple of tweaks

---

packages/@sanity/vision/src/components/VisionGui.tsx

This PR makes the Vision plugin somewhat more responsive for narrow(er) screens by:
- Tuning the responsive grid column values so the 3-4 option boxes collapse more neatly
- Adjust the vertical/horizontal props and sizing to the split panes so they change direction beneath the narrowest breakpoint (600px).
This is useful when you want to test a query on mobile or with a narrow studio in a browser‘s split pane. The balance between the query/param/results panes could probably be tuned a tiny bit more, but it's at least functional.
I did try to see if there was a way to reuse the Sanity UI logic to get the breakpoints but ended up doing a simple `window.innerWidth < 600` wrapped in the `narrowBreakpoint()` function. 
Responsive improvements to the Vision plugin to accommodate narrower …

feat: make splitpanes responsive for minimal breakpoint

---

dev/test-studio/plugins/locale-no-nb/bundles/studio.ts
packages/sanity/src/core/form/inputs/DateInputs/CommonDateTimeInput.tsx
packages/sanity/src/core/form/inputs/DateInputs/DateInput.tsx
packages/sanity/src/core/form/inputs/DateInputs/DateTimeInput.tsx
packages/sanity/src/core/form/inputs/DateInputs/__tests__/CommonDateTimeInput.test.tsx
packages/sanity/src/core/form/inputs/DateInputs/base/DatePicker.tsx
packages/sanity/src/core/form/inputs/DateInputs/base/DateTimeInput.tsx
packages/sanity/src/core/form/inputs/DateInputs/base/calendar/Calendar.tsx
packages/sanity/src/core/form/inputs/DateInputs/base/calendar/CalendarMonth.tsx
packages/sanity/src/core/form/inputs/DateInputs/base/calendar/constants.ts
packages/sanity/src/core/form/inputs/DateInputs/base/calendar/types.ts
packages/sanity/src/core/form/inputs/DateInputs/utils.ts
packages/sanity/src/core/i18n/bundles/studio.ts

Adds internationalization capabilities to Date and DateTime inputs. Tried to keep as much as the i18n framework itself apart from the base datetime-picker, so limited the use of `useTranslation()` to the form input components.

feat(i18n): convert date/datetime input strings to use i18n primitives

---

packages/sanity/src/desk/structureBuilder/GenericList.ts

`getCanHandleIntent` can return `undefined`, but `canHandleIntent` cannot received `undefined`.
In all of our examples, we pass the result of `getCanHandleIntent` directly into `canHandleIntent`.
This fixes the types for `canHandleIntent` to take undefined as everywhere else the params are optional so this changes matches the other interfaces. Adding the below structure still works and does not show TS error
```
S.listItem()
.title('Custom books list')
.child(
S.documentList()
.title('Unspecified books list')
.filter('_type == $type')
.params({type: 'book'})
.menuItems(S.documentTypeList('book').getMenuItems())
.canHandleIntent(S.documentTypeList('book').getCanHandleIntent()),
)
```
- Fixes type for `canHandleIntent` to allow passing undefined

fix(desk): fixes type for canHandleIntent in documentList

---

packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/ArrayOfObjectsFunctions.tsx

Follow-up from #4963, which missed a fix for the popover that appears when adding an item to an array input that can hold several diferent types.
**Before**:
**After**:
- Make sure long lists of possible types are placed either above or below the "Add item…" button in array inputs
- Fixed placement of "Add item…" popover in array inputs

fix(form): set fallback placement for type-select popover in array input

---

packages/sanity/src/core/comments/hooks/useCommentsClient.ts

Re-use the authentication configured for the default client. Authentication method vary if the browser supports cookies or not.

fix(core/comments): ensure authentication config on comment client

---

dev/test-studio/plugins/locale-no-nb/bundles/studio.ts
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/ArrayOfObjectsFunctions.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/ErrorItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridArrayInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/IncompatibleItemType.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/InsertMenu.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ErrorItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/IncompatibleItemType.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/PreviewItem.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesFunctions.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx
packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ItemRow.tsx
packages/sanity/src/core/form/inputs/arrays/common/uploadTarget/uploadTarget.tsx
packages/sanity/src/core/form/members/array/IncompatibleItemType.tsx
packages/sanity/src/core/form/members/array/MemberItemError.tsx
packages/sanity/src/core/form/members/array/items/ArrayOfObjectsItem.tsx
packages/sanity/src/core/i18n/bundles/studio.ts
packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentList.tsx
packages/sanity/src/core/studio/components/navbar/search/components/Instructions.tsx
packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/reference/ReferenceAutocomplete.tsx

Convert array input strings to use i18n primitives
~~TO DO still in PR:~~
~~ArrayOfPrimitivesInput~~
- ~~ArrayOfPrimitivesInput (class, can’t use the hook, not sure where to send in the prop from)~~
- ~~getEmptyValue (tried sending the t in through params, but used in ArrayOfPrimitives which is a class)~~

feat(core): convert array input actions strings to use i18n primitives 

---

packages/sanity/src/core/studio/screens/schemaErrors/SchemaProblemGroups.tsx

Adds a text overflow with title to the breadcrumbs so it still provides the user with the full name on hover
- Fixes an issue with text overlapping in error message

fix(core): fixes issue with overlapping text in error message

---

dev/test-studio/plugins/locale-no-nb/bundles/desk.ts
packages/sanity/src/desk/documentActions/DeleteAction.tsx
packages/sanity/src/desk/documentActions/DiscardChangesAction.tsx
packages/sanity/src/desk/documentActions/DuplicateAction.tsx
packages/sanity/src/desk/documentActions/HistoryRestoreAction.tsx
packages/sanity/src/desk/documentActions/PublishAction.tsx
packages/sanity/src/desk/documentActions/UnpublishAction.tsx
packages/sanity/src/desk/i18n/resources.ts

This converts various document action strings into 18n-keys
Also includes some minor cleanup. Commits can be reviewed one-by-one.

feat(i18n): convert document actions strings to use i18n primitives

---

dev/test-studio/plugins/locale-no-nb/bundles/studio.ts
packages/sanity/src/core/form/inputs/files/FileInput/__tests__/fileInput.test.tsx
packages/sanity/src/core/form/inputs/files/ImageInput/ImageActionsMenu.tsx
packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.tsx
packages/sanity/src/core/form/inputs/files/ImageInput/InvalidImageWarning.tsx
packages/sanity/src/core/form/inputs/files/ImageToolInput/ImageToolInput.tsx
packages/sanity/src/core/form/inputs/files/common/ActionsMenu.tsx
packages/sanity/src/core/form/inputs/files/common/DropMessage.tsx
packages/sanity/src/core/form/inputs/files/common/PlaceholderText.tsx
packages/sanity/src/core/form/inputs/files/common/UploadPlaceholder.tsx
packages/sanity/src/core/form/inputs/files/common/UploadProgress.tsx
packages/sanity/src/core/form/inputs/files/common/UploadWarning.tsx
packages/sanity/src/core/form/inputs/files/constants.ts
packages/sanity/src/core/form/studio/inputs/StudioImageInput.tsx
packages/sanity/src/core/i18n/bundles/studio.ts
packages/sanity/test/form/renderImageInput.tsx

Adds internationalization capabilities to Image and File inputs and common supporting components. 
- n/a

feat(i18n): convert file, image and imagetool input strings to use i18n primitives

---

packages/sanity/src/desk/comments/src/hooks/useCommentOperations.ts
packages/sanity/src/desk/comments/src/hooks/useNotificationTarget.ts
packages/sanity/src/desk/comments/src/types.ts

This PR ensures that workspace titles are saved to comments (in `context.notification`). This workspace title is needed since email notifications display this title to highlight which Studio the comment may have originated from.
`notification.title` has also been renamed to `notification.documentTitle`
(If approved, please don't merge until upstream changes have been made to handle this new payload)

fix: attach workspace title to comments notification context

---

packages/sanity/src/desk/documentActions/PublishAction.tsx
packages/sanity/src/desk/i18n/resources.ts
packages/sanity/src/desk/panes/document/statusBar/sparkline/ReviewChangesButton/ReviewChangesButton.tsx

This PR adds i18n support for the ReviewChangesButton

feat(i18n): convert review changes button to use i18n primitives

---

packages/sanity/src/desk/documentActions/DeleteAction.tsx
packages/sanity/src/desk/documentActions/DiscardChangesAction.tsx
packages/sanity/src/desk/documentActions/DuplicateAction.tsx
packages/sanity/src/desk/documentActions/PublishAction.tsx
packages/sanity/src/desk/documentActions/UnpublishAction.tsx

Fixes some resource ids that were changed from camelCase to kebab-case but usages were not changed accordingly.

fix(i18n): camelCase to kebab-case for resource ids

---

packages/sanity/src/_internal/cli/actions/graphql/extractFromSanitySchema.ts
packages/sanity/src/_internal/cli/actions/graphql/types.ts
packages/sanity/test/cli/graphql/__snapshots__/extract.test.ts.snap
packages/sanity/test/cli/graphql/__snapshots__/gen2.test.ts.snap
packages/sanity/test/cli/graphql/__snapshots__/gen3.test.ts.snap
packages/sanity/test/cli/graphql/fixtures/test-studio.ts

The following PR adds CDR metadata to the GraphQL json schema to enable CDR support in the `gatsby-source-sanity` plugin.
There's a new key under the `ConvertedType` interface labeled `crossDatasetReferenceMetadata` that includes the dataset name and the type names.
Important note: Our graphql service _must_ be updated before this gets merged else all GraphQL deployments with crossDatasetReferences will fail because of the extra key.
Fixes SDX-768 
Fixes SDX-765
See the updated types and tests to see how the GraphQL JSON schema will change. 
N/A (more of an internal add for the time being)

feat(cli): add CDR metadata to GraphQL json schema

---

dev/test-studio/plugins/locale-no-nb/bundles/desk.ts
dev/test-studio/plugins/locale-no-nb/bundles/studio.ts
dev/test-studio/plugins/locale-no-nb/bundles/validation.ts
packages/sanity/src/core/i18n/bundles/studio.ts
packages/sanity/src/core/i18n/bundles/validation.ts
packages/sanity/src/core/studio/components/navbar/resources/ResourcesButton.tsx
packages/sanity/src/core/studio/components/navbar/resources/ResourcesMenuItems.tsx
packages/sanity/src/core/studio/components/navbar/search/components/SearchHeader.tsx
packages/sanity/src/desk/i18n/resources.ts
packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx
packages/sanity/src/desk/panes/document/inspectDialog/InspectDialog.tsx
packages/sanity/src/desk/panes/document/inspectDialog/constants.ts
packages/sanity/src/desk/panes/document/inspectors/changes/index.ts
packages/sanity/src/desk/panes/document/inspectors/validation/ValidationInspector.tsx
packages/sanity/src/desk/panes/document/inspectors/validation/index.ts
packages/sanity/src/desk/panes/document/menuItems.ts
packages/sanity/src/desk/panes/document/statusBar/sparkline/PublishStatus.tsx
packages/sanity/src/desk/panes/document/timeline/timelineItem.styled.tsx
packages/sanity/src/desk/panes/document/timeline/timelineItem.tsx

Bit of a mixed bag here, apologies for not splitting up into separate PRs, but seems a bit excessive. Bit of a whack-a-mole at this point ;) 
1. Adds a large number of missing Norwegian translations to easier get overview of missing surfaces (also sorted in same order as english resource file)
2. Added i18n primitives for:
- Publish status button
- Review changes (panel title etc)
- Validation panel
- Inspect dialog
- Document pane menu items (Inspect, Open preview)

feat(i18n): more translated surfaces
