packages/@sanity/client/package.json, packages/@sanity/client/src/assets/assetsClient.js, packages/@sanity/client/src/data/dataMethods.js, packages/@sanity/client/src/http/request.js, packages/@sanity/client/src/sanityClient.js, packages/@sanity/client/src/util/omit.js, packages/@sanity/client/src/validators.js, packages/@sanity/client/test/client.test.js, packages/@sanity/form-builder/src/sanity/inputs/File.js, packages/@sanity/form-builder/src/sanity/inputs/Image.js
This makes the default sanity client strictly promise based, and instead exposes an Observable-based API on `client.observable`.
This leaves current API *mostly* intact, with a few exceptions:
-  `client.assets.upload()` now returns a promise that resolves with the response body (and thus provides no way to track progress). If progress tracking is needed, the observable is available on `client.observable.assets.upload()`
- A data request without a configured dataset will throw a sync error and no longer propagate the error through the returned promise. This is (as far as I could assert) the behavior of other validation errors too.
=> [client] Expose observable API on client.observable

packages/@sanity/base/src/styles/typography/forms.css, packages/@sanity/components/src/fieldsets/styles/DefaultFieldset.css, packages/@sanity/components/src/formfields/styles/DefaultFormField.css, packages/@sanity/components/src/imageinput/styles/ImageInputFieldset.css, packages/@sanity/components/src/labels/styles/DefaultLabel.css, packages/@sanity/form-builder/src/inputs/Array/Array.js, packages/@sanity/form-builder/src/inputs/Object/Object.js, packages/example-studio/schemas/block-array.js, packages/example-studio/schemas/schema.js
Fixes a bug that caused nested objects to not render their headings properly.
As an added bonus, the code that increases nesting levels in the Object input should now be a bit easier to reason about.
=> [form-builder] Fix nesting level on forms

packages/@sanity/desk-tool/src/pane/Editor.js
The keyboard shortcut for the inspect view has never worked on Linux+Chrome.
After some debugging, it seems `keypress` is never fired when I press ctrl+alt+i.
`keyup` works as expected, but the `charCode` property is a non-standard and deprecated property, so I replaced it with the `key` property. This also makes the code slightly more readable, in my opinion.
Please test on Mac and ensure it still works as expected.
=> [desk-tool] Fix keyboard shortcut for inspect view on Linux

packages/@sanity/cli/src/CommandRunner.js, packages/@sanity/cli/src/commands/help/showHelp.js, packages/@sanity/core/src/commands/documents/queryDocumentsCommand.js
Group roots currently do not list it's subcommands. This PR fixes this issue and also adds an example on how to add help text to subcommands.
=> [cli] Fix issue where command group roots would not list commands

packages/@sanity/base/src/styles/layout/helpers.css, packages/@sanity/base/src/styles/variables/layers.css, packages/@sanity/base/src/styles/variables/selectable-item.css, packages/@sanity/form-builder/src/inputs/Array/Array.js, packages/@sanity/form-builder/src/inputs/Array/styles/Array.css, packages/@sanity/form-builder/src/inputs/Array/styles/ItemValue.css
It was caused by `useDragHandle` being set on list
Also includes minor style changes
Should be safe to merge straight into master
=> [form-builder] Fix: grid items was not draggable

packages/@sanity/client/src/data/listen.js, packages/@sanity/client/src/http/requestOptions.js
Currently, the client is credentialed by default - that is, if the user has a session, every request from the client will include a cookie or authorization header, unless `withCredentials` is explicitly set to `false`.
This PR inverts this behaviour; all requests are uncredentialed (sent without Authorization/Cookie) by default, unless the `token` or `withCredentials` options are set to `true`.
Since server-side uses of the client usually includes a token, this mainly affects front-ends. For instance, the sanity studio needs to specify `withCredentials` when instantiating the client. Front-end applications that previews drafts and implicitly depend on the user being authenticated also needs to include the `withCredentials` option (set to true).
The rationale behind this change is that …
=> [client] Uncredentialed requests if `withCredentials` + `token` is undefined

packages/@sanity/base/src/client/index.js
Follow-up to #114  - we now need to specify that we want credentialed requests in the studio.
=> [base] Use credentialed requests in studio

packages/@sanity/form-builder/src/FormBuilderInput.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/Syncer.js, packages/@sanity/form-builder/src/inputs/Slug/SlugInput.js, packages/@sanity/form-builder/src/inputs/Slug/createSlugInput.js, packages/@sanity/form-builder/src/utils/ValueSync.js, packages/@sanity/form-builder/src/utils/withDocument.js, packages/@sanity/form-builder/src/utils/withPatchSubscriber.js
This sets up a subscriber to document snapshots instead of relying on props/component updates, which will can be broken by pure components.
This removes the `passDocument` option on inputs.
Added the `withDocument` HOC that sets up the subscription and passes document snapshots to the composed component as it changes.
I've also renamed the existing _SubscribePatchHOC_  so their naming conventions match.
This should go into master and be released asap.
=> [form-builder] Fix: Subscribe to current document instead of relying on document being passed down

packages/@sanity/core/src/commands/dataset/exportDatasetCommand.js, packages/@sanity/core/src/util/skipSystemDocuments.js
Currently, when you export a dataset, both system groups and listeners are included.
When you try to import this into a new dataset, you get permission errors since these kind of documents cannot be inserted by a regular user without the `manage` flag.
The best solution would be if we could filter these documents on the server side, but as of now we can't do this. This PR filters them on the client side when you run `sanity dataset export`.
=> [core] Skip system documents when exporting a dataset

packages/@sanity/base/src/preview/createPreviewObserver.js, packages/@sanity/base/src/preview/observeForPreview.js, packages/example-studio/schemas/blocks.js, packages/example-studio/schemas/referenceTest.js
This fixes an issue with previews that broke when you had named reference types in arrays / block editor, and adds a few examples of named reference types to the example-studio schema, see:
https://github.com/sanity-io/sanity/blob/b26fafff070ebf4bcbb1c99866029af3a5225747/packages/example-studio/schemas/referenceTest.js#L8-L24
and
https://github.com/sanity-io/sanity/blob/b26fafff070ebf4bcbb1c99866029af3a5225747/packages/example-studio/schemas/blocks.js#L17-L27
(cc @skogsmaskin, @simen)
=> [base] A fix + example schema demonstrating named reference types

packages/@sanity/observable/src/SanityObservable.js, packages/@sanity/observable/test/exposed-api.test.js
This operator in combination with `refCount()` is super useful when we want to share a value represented by a single underlying resource between multiple subscribers.
Pseudo-ish example:
```js
const snapshots = new Observable(observer => {
// will be called when first observer subscribes
const connection = server.listen('someDocument', currentSnapshot => {
observer.next(currentSnapshot)
})
return () => {
// will be called when last subscriber unsubscribes
connection.close()
}
})
.publishReplay(1)
.refCount()
const first = snapshots.subscribe(snapshot => console.log(snapshot))
// later
const second = snapshots.subscribe(snapshot => console.log(snapshot))
```
Here, both subscribers will immediately receive the most recent snapshot, but only one connection to the server will be kept open …
=> [observable] Add publishReplay operator

packages/@sanity/form-builder/src/sanity/SanityFormBuilder.js
This exposes a higher order component that makes the current document available for any component in a form-builder context. By default, input components are *not* given the document, but there are cases you might want it, e.g. if you are a slug input that depends on another document field.
Example usage:
```jsx
import {withDocument} from 'part:@sanity/form-builder'
function MyInput(props) {
return (
<div>
Document title: {props.document.title}
{/* ... */}
</div>
)
}
export default withDocument(MyInput)
```
=> [form-builder] Expose the withDocument HOC

packages/@sanity/client/package.json, packages/@sanity/client/src/http/errors.js, packages/@sanity/client/src/http/request.js, packages/@sanity/client/test/client.test.js
When ClientError or ServerError is created, the client currently does not pass on the message to the super constructor, which causes stacks to be unhelpful:
```
ServerError
at onResponse (~/webdev/test/node_modules/@sanity/client/lib/http/request.js:31:13)
at middleware.(anonymous function).reduce (~/webdev/test/node_modules/get-it/lib-node/util/middlewareReducer.js:10:22)
at Array.reduce (native)
```
With this change, the stack traces are more helpful:
```
ServerError: The mutation(s) failed: Insufficient permissions; permission "create" required
at onResponse (~/webdev/test/node_modules/@sanity/client/lib/http/request.js:31:13)
at middleware.(anonymous function).reduce (~/webdev/test/node_modules/get-it/lib-node/util/middlewareReducer.js:10:22)
at Array.reduce (native)
```
=> [client] Include error message in stack

packages/@sanity/schema/src/preview/createPreviewGetter.js, packages/@sanity/schema/src/preview/guessPreviewConfig.js, packages/@sanity/schema/src/types/blocks/block.js, packages/@sanity/schema/src/types/blocks/span.js, packages/@sanity/schema/src/types/file.js, packages/@sanity/schema/src/types/image.js, packages/@sanity/schema/src/types/image/fieldDefs.js, packages/@sanity/schema/src/types/object.js, packages/example-studio/schemas/myImage.js
This guesses preview fields based on the raw schema definition for an object instead of the parsed/compiled version.
It also re-enables a heuristic for guessing image asset url for a type.
=> [schema] Guess preview config based on raw schema def instead of parsed

packages/@sanity/plugin-loader/loader.js, packages/@sanity/plugin-loader/test/loader.test.js
The plugin loader allows overriding parts, which is useful when you are running tests.
It doesn't currently let you override config parts, however, which is a bit of a shortcoming. This PR addresses this issue and also fixes a bunch of old `role`-references in the tests.
=> [plugin-loader] Allow overriding config parts

packages/@sanity/core/package.json, packages/@sanity/core/src/actions/exec/babel.js, packages/@sanity/core/src/actions/exec/execScript.js, packages/@sanity/core/src/commands/exec/execCommand.js, packages/@sanity/core/src/commands/index.js
This adds a new command to the Sanity CLI: `exec`.
Basically, if you have a studio and have some scripts associated with it that you want to run, it would be nice to be able to use the parts system as you would otherwise, and preferably also be able to use ES6-features.
This is now possible with `sanity exec <script.js>`. It registers babel with the `es2015-node4` and `stage-2` presets, and registers the Sanity plugin loader.
For instance, you can now make a script like this:
```js
import client from 'part:@sanity/base/client'
const products = await client.fetch('*[_type == "product"]')
console.log(products)
```
=> [core] Add `sanity exec` command that registers part loader + babel

packages/@sanity/components/src/previews/BlockPreview.js
Instead of rendering an empty line, we should render the type name etc.
=> [components] Fix BlockPreview rendering

packages/@sanity/form-builder/src/inputs/Array/Array.js, packages/@sanity/form-builder/src/inputs/Array/ItemValue.js, packages/test-studio/schemas/arrays.js
This fixes an issue with arrays that includes unnamed objects, e.g.:
https://github.com/sanity-io/sanity/blob/8cc2a596d45512049316d17890e008575fdd942c/packages/test-studio/schemas/arrays.js#L62-L77
cc @evenwestvang
=> Fix/arrays can't handle anonymous objects

gulpfile.js
On windows, the `npm start` tasks would not be able to start the sanity cli tool because of a missing shell.
=> [infrastructure] Fix spawning gulptasks on windows

packages/@sanity/webpack-loader/src/multiImplementationHandler.js
Paths are currently naively put into a string, which results in things like:
```js
module.exports = [
require('C:\Webdev\Some Project\Blah.js')
]
```
Because the Windows path delimiter is the same character as the escape character for strings, basically the paths won't contain slashes. A basic, embarrassing oversight.
This PR switches to using JSON.stringify to ensure valid strings are used.
=> [webpack-loader] Fix invalid paths on Windows when using `all:`-parts

packages/@sanity/server/src/configs/webpack.config.js
The babel loader was excluding `node_modules`, but only in unixy paths. This PR changes it to be platform-agnostic.
=> [server] Fix invalid paths being ignored for babel loader on windows

packages/@sanity/desk-tool/sanity.json, packages/@sanity/desk-tool/src/pane/Editor.js
This PR adds a part that can be used to inject components below the editor in the desk tool. 
We don't want to encourage using the main editor pane for functionality such as this, and as such I've marked the part as deprecated already. It will be removed once we get a meta pane or similar.
Also fixes a few lint errors that were present in the editor component.
=> Add temporary part to inject components below the editor

packages/@sanity/client/README.md, packages/@sanity/client/package.json, packages/@sanity/client/src/config.js, packages/@sanity/client/src/sanityClient.js, packages/@sanity/client/test/client.test.js
This PR will make the client aware of our new API CDN.
If no `useCdn` option is specified when constructing, a warning is presented to the user (once), prompting them to take a stand and set it to true or false.
Even if a user has set `useCdn` to true, the client will fall back to using the live API for:
- Listeners
- Authenticated requests (tokens, cookies)
- Mutations
- Non-data requests
Also snuck in documentation for `createOrReplace()` / `createIfNotExists()`, which was missing. Sorry about that.
=> Make client API CDN aware

packages/@sanity/base/src/client/index.js
The Sanity client within the studio shouldn't use the CDN, and as such we should explicitly opt out to avoid the warning being logged.
=> [base] Opt-out of CDN usage

packages/@sanity/client/src/assets/assetsClient.js
This PR checks whether a File instance is passed to the asset uploader, and if so, includes the original filename and mime type when uploading.
A user can opt-out of this behavior by specifying `preserveFilename: false` in the options, and can also specify a specific filename for the file with `filename: 'my-filename.ext'`.
The filename is stored as metadata on the asset (`originalFilename` property).
=> [client] Retrieve original filename and content type from File instances

packages/@sanity/cli/src/actions/yarn/yarnWithProgress.js
Encountered a weird case where the yarn executable did not have the executable bit set, which caused a spawn error. In this case, `stdout`/`stderr` was not set, and because the promise rejects asyncronously, node crashed because we tried to pipe on stderr/stdout.
With this PR, instead of executing the yarn executable directly, we launch node and specify yarns path as the first argument. This works around the executable bit issue.
I've also addressed potential other problems with spawning by verifying that `stdout` actually exists on process before trying to use it.
=> [cli] Fix potential yarn spawn problems

packages/@sanity/client/src/config.js, packages/@sanity/core/src/commands/dataset/importDatasetCommand.js
There were a couple of issues with the "please use the cdn"-warning when a client is cloned or a new configuration is passed to an existing client.
This PR ensures it now checks the merged result of the configuration instead of just the new configuration options.
Also made the dataset import command explicitly set `useCdn` to `false`.
=> CLI CDN fixes

packages/@sanity/client/src/http/request.js, packages/@sanity/client/test/client.test.js
We're not allowed to override the user agent in browsers, but in Node, we want to include a user agent to help track down potential issues and get a general feel of client usage.
=> [client] Set User-Agent in non-browser environments

packages/@sanity/state-router/demo-server/components/Main.js, packages/@sanity/state-router/demo-server/components/ProductCounter.js, packages/@sanity/state-router/demo-server/components/SomeChild.js, packages/@sanity/state-router/demo-server/components/User.js, packages/@sanity/state-router/demo-server/entry.js, packages/@sanity/state-router/src/components/IntentLink.js, packages/@sanity/state-router/src/components/Link.js, packages/@sanity/state-router/src/components/RouteScope.js, packages/@sanity/state-router/src/components/RouterProvider.js, packages/@sanity/state-router/src/components/StateLink.js, packages/@sanity/state-router/src/components/WithRouter.js, packages/@sanity/state-router/src/components/internalRouterContextTypeCheck.js, packages/@sanity/state-router/src/components/types.js, packages/@sanity/state-router/src/components/withRouterHOC.js
Any component that relied on the router (e.g. LinkState, IntentLink) would fail hard if they were rendred outside of a `<RouterProvider ..>` context. Usually you should provide a context, but sometimes it makes sense to not, e.g. when testing. (In my case, testing components that used `<StateLink` in Storybook)
Also includes a few additional flowtype annotations and minor tweaks.
=> [state-router] Tolerate (but warn) on missing router context

packages/@sanity/client/package.json, packages/@sanity/client/src/http/browserMiddleware.js, packages/@sanity/client/src/http/nodeMiddleware.js, packages/@sanity/client/src/http/request.js
The `headers` and `debug` middleware were being included in browser bundles. Tried to find a clean solution, but using the `browser` field is the most reliable method I came up with which works both with browserify and with webpack.
=> [client] Make node-specific middleware be excluded from bundles

packages/@sanity/base/package.json, packages/@sanity/components/package.json, packages/@sanity/default-layout/package.json, packages/@sanity/desk-tool/package.json, packages/@sanity/form-builder/package.json, packages/@sanity/google-maps-input/package.json, packages/@sanity/imagetool/package.json, packages/@sanity/server/package.json, packages/@sanity/state-router/package.json, packages/example-studio/package.json, packages/example-studio/parts/AuthorPreview.js, packages/sanity-plugin-vision/package.json, packages/sanity-plugin-vision/src/Vision.js, packages/sanity-plugin-vision/src/components/DelayedSpinner.js, packages/sanity-plugin-vision/src/components/Dropdown.js, packages/sanity-plugin-vision/src/components/ErrorDialog.js, packages/sanity-plugin-vision/src/components/JsonDump.js, packages/sanity-plugin-vision/src/components/NoResultsDialog.js, packages/sanity-plugin-vision/src/components/ParamsEditor.js, packages/sanity-plugin-vision/src/components/QueryEditor.js, packages/sanity-plugin-vision/src/components/QueryErrorDetails.js, packages/sanity-plugin-vision/src/components/QueryErrorDialog.js, packages/sanity-plugin-vision/src/components/ResultCollection.js, packages/sanity-plugin-vision/src/components/ResultTable.js, packages/sanity-plugin-vision/src/components/ResultView.js, packages/sanity-plugin-vision/src/components/VisionGui.js, packages/sanity-plugin-vision/src/containers/LoadingContainer.js, packages/sanity-plugin-vision/src/css/visionGui.css, packages/storybook/package.json, packages/test-studio/package.json
This also upgrades React to 16.0.0-rc.2 in _test studio_ and _example studio_.
Ran into a few issues along the way:
- I had to switch from the official `react-json-inspector` to @rexxars'  react-15 branch [here](https://github.com/rexxars/react-json-inspector/tree/react-15), which fixes the deprecation warnings in React 15 that are hard errors in 16. (we should probably look for an alternative, since react-json-inspector doesn't seem like its actively maintained anymore).
- Switched to react-codemirror2, since [JedWatson/react-codemirror](https://github.com/JedWatson/react-codemirror) looks pretty much abandoned.
- The storybook tool is currently broken. I've started the process of upgrading to the latest @storybook packages in #165 . (If we want to merge this immediately we should …
=> [chore] Support React 16.0.0-rc.2 as peer dependency

packages/@sanity/client/src/assets/assetsClient.js
Just a minor nitpick; where rest of the client uses `uri`, the assets part use `url`.
=> [client] Use URI-parameter for asset requests

packages/@sanity/schema/src/preview/JSONStringifyHuman.js, packages/@sanity/schema/src/preview/fallbackPrepare.js, packages/@sanity/schema/src/preview/guessPreviewConfig.js, packages/test-studio/schemas/notitle.js, packages/test-studio/schemas/schema.js
If we're unable to guess any sane preview config, we have to fallback to something.
Previously we just did a simple `JSON.stringfy` of the value, and that resulted in pretty ugly output:
This patch makes the output less ugly and a bit more human friendly:
Note that these screenshots are from a contrived example. The fallback preview will only be used for types that has no string fields.
=> [schema] Make the output from the fallback preview.prepare more human friendly

packages/@sanity/form-builder/src/inputs/Object/Object.js, packages/test-studio/schemas/book.js
Warning: Totally new to the form builder internals, so might be overlooking something.
PR is an attempt to introduce new `isHidden` property on schema which will prevent a field from being rendered. The use case is where you have properties which are populated by scripts and are part of the content model, but should not be editable/shown to the editors in the studio.
=> [form-builder] Feature: Hide fields by specifying `hidden` in schema

packages/@sanity/cli/src/actions/login/login.js
There's an issue on MacOS where after logging in, there process doesn't exit. This is caused by node waiting for the browser process to exit. This small change resolves the promise right away and lets the process exit cleanly. Fixes #21
=> [cli] Fix issue where CLI stalls after login on MacOS

packages/@sanity/core/src/commands/dataset/deleteDatasetCommand.js
We are currently blindly deleting datasets when you type `sanity dataset delete <name>`. This is... dangerous. This PR takes some inspiration from Github and makes the user confirm the delete by typing the dataset name. Closes #81
=> [core] Add confirmation dialog before deleting dataset

packages/@sanity/cli/src/commands/init/gatherInput.js
This PR makes it possible to use bash-like shortcuts such as `~/some/path` and `~+/foo/bar` during the init process and thus fixes a small but long-time annoyance.
=> [cli] Expand bash-like homedir shortcuts

packages/@sanity/base/src/schema/createSchema.js
Being able to use CommonJS when defining your schemas is a feature I've wanted without doing the `.default`-dance.
=> [base] Expose schema creator as CommonJS

packages/@sanity/client/package.json, packages/@sanity/client/src/http/nodeMiddleware.js, packages/@sanity/import/package.json
This PR reintroduces retrying of GET and HEAD requests to the client.
Currently only enabled for node since browsers has it's own retrying logic that we need to experiment with a bit with before enabling retries there.
=> [client] Retry failed GET/HEAD-requests

packages/@sanity/cli/src/actions/yarn/yarnWithProgress.js, packages/@sanity/cli/src/commands/init/bootstrapTemplate.js, packages/@sanity/cli/src/commands/init/initCommand.js, packages/@sanity/cli/src/commands/init/initPlugin.js, packages/@sanity/cli/src/commands/init/initSanity.js, packages/@sanity/cli/src/util/getProjectDefaults.js
This PR adds a new unattended mode to the `sanity init` command.
By doing `sanity init -y --project abc123 --dataset staging --output-path=/some/path`, a new studio project will be created in the directory specified, optionally with a given template.
It will (by design and main purpose) not ask any questions along the way, instead throwing on anything that cannot be resolved without user interaction.
This will help us integrate the init process into other tools, as well as making testing and CI easier.
Another step was also added to the yarn install process to make up for the time spent between spawning yarn and the time it first emits progress events. This is to prevent people from thinking lack of output means the process has stalled.
=> [cli] Add unattended init mode

packages/@sanity/form-builder/src/inputs/File/FileInput.js, packages/test-studio/schemas/files.js
Fixes a bug where the asset file were overwritten and lost its `_type`. In addition, the `asset.originalFilename` is now displayed in the file input
=> Misc. file input improvements

packages/@sanity/schema/src/preview/guessPreviewConfig.js
This is a small rewrite of how we identify image asset and file assets on object types. This will also pick `asset.originalFilename` as the default value for `preview.title` for files.
This also fixes a minor issue that would fail to infer image asset field for custom reference types.
=> [schema] Improve default preview config for image/file assets

packages/@sanity/base/package.json, packages/@sanity/base/src/schema/types/deprecatedDate.js, packages/@sanity/schema/package.json, packages/@sanity/schema/src/Schema.js
The deprecation warning for the `date` was implemented in a getter for `type.name`. The type name is used as a key in an internal registry, so the warning was triggered even if there were no fields with `type: date` in the schema. This fix makes sure the deprecation warning is issued only if we actually encounter a field that uses `type: date`.
=> [schema] Fix: too eager deprecation warning for the deprecated date-type

packages/@sanity/schema/src/types/object.js, packages/test-studio/schemas/objects.js
This is a quickfix. Will be better safeguarded with schema validation.
=> [schema] Tolerate object with missing fields. Fixes #196

packages/@sanity/form-builder/examples/schema-testbed/schemas/blocks.js, packages/@sanity/form-builder/src/index.js, packages/@sanity/form-builder/src/sanity/SanityFormBuilder.js
This is strictly speaking a breaking change, but I really doubt anyone is using the `SlateInput` export here.
=> [form-builder] Rename SlateInput export => BlockEditor

packages/@sanity/client/src/assets/assetsClient.js, packages/@sanity/client/test/client.test.js, packages/@sanity/import/src/uploadAssets.js
According to current docs, the promise returned from `client.assets.upload(...)` resolves with the asset document. However, it was resolved to the http response body, which had the asset document on the `document` key.
Note: this is a breaking change. I doubt this api is very much used, but just to be sure, we could add a non-enumerable getter on the `assetDocument.document` that console logs a warning and returns the asset document. What do you think?
=> [client] Resolve the asset upload promise with the asset document, not the response

packages/example-studio/components/FunkyEditor/FunkyEditor.js, packages/example-studio/components/FunkyEditor/index.js, packages/example-studio/parts/inputResolver.js, packages/example-studio/sanity.json, packages/example-studio/schemas/localeSlug.js
A working example on how to wrap and customise inputs would be nice to have in the example studio right?
=> Add example on how to wrap and customize the block editor

packages/@sanity/client/README.md, packages/@sanity/client/src/assets/assetsClient.js, packages/@sanity/client/test/client.test.js, packages/@sanity/form-builder/examples/schema-testbed/schemas/blocks.js, packages/@sanity/form-builder/src/index.js, packages/@sanity/form-builder/src/sanity/SanityFormBuilder.js, packages/@sanity/import/src/uploadAssets.js, packages/example-studio/components/FunkyEditor/FunkyEditor.js, packages/example-studio/components/FunkyEditor/index.js, packages/example-studio/parts/inputResolver.js, packages/example-studio/sanity.json, packages/example-studio/schemas/localeSlug.js
Author | Message | Commit
------------ | ------------- | -------------
Bjørge Næss | [form-builder] Rename SlateInput export => BlockEditor (#210) | c63b40c16
Bjørge Næss | [client] Resolve the asset upload promise with the asset document, not the response (#208) | 69b7d2eee
Bjørge Næss | [client] Add docs for asset uploads to README (#207) | 8ad48b39f
Bjørge Næss | [client] Minor: Remove invalid parameter from assets.upload(...) example | 0a7488a65
Per-Kristian Nordnes | [example-studio] Add example on how to wrap and customize the block editor (#209) | b8c730157
=> Release 0.114.0

packages/@sanity/client/package.json, packages/@sanity/import/package.json
get-it v4 fixes an issue where certain streams and other objects (those with a `toJSON()` method) would be serialized to JSON. This was preventing image uploads in @sanity/client from those kinds of streams.
=> [chore] Upgrade get-it to v4

packages/sanity-plugin-vision/src/components/VisionGui.js, packages/sanity-plugin-vision/src/css/visionGui.css, packages/sanity-plugin-vision/src/util/encodeQueryString.js
Sometimes you may want to link someone to a query result in order to debug a problem or prototype an idea. Instead of opening the browsers devtools and inspecting the outgoing requests, this PR shows the query/listen URL in an input field with a copy button next to it which will copy the URL to the clipboard.
It also overrides the default behavior of the client to force longer queries to a POST, which makes "all" queries linkable. It doesn't look all that good, so a brush-up on the styling front would probably be smart - I'll leave that to @kristofferj 
While adding the functionality I also encountered a bug where a non-existing dataset might be chosen upon startup, without the possibility to switch. Rolled a fix for that into this PR for good measure.
=> [vision] Show query URL with copy functionality

packages/sanity-plugin-vision/src/components/JsonDump.js
When documents are created within the same transaction, `_rev` is set to the same value. Since we have used the revision as key, only the first item is rendered. This PR changes to use the document ID as the key if present and falls back to just using the array index.
=> [vision] Use document ID as key instead of revision

packages/@sanity/form-builder/src/FormBuilder.js, packages/@sanity/form-builder/src/FormBuilderContext.js, packages/@sanity/form-builder/src/index.js, packages/@sanity/form-builder/src/sanity/SanityFormBuilder.js, packages/@sanity/form-builder/src/sanity/WithFormBuilderValue.js
This extracts all the context stuff from the `FormBuilder` component into a separate `FormBuilderContext`.
In addition to better separation of concerns, it also fixes an issue with the `WithFormBuilderValue` component that we're using in Vega.
This is a backwards compatible change.
=> [form-builder] Extract FormBuilderContext  and let WithFormBuilder take schema as prop

packages/@sanity/desk-tool/src/pane/Editor.js, packages/@sanity/form-builder/sanity.json, packages/@sanity/form-builder/src/FormBuilder.js, packages/@sanity/form-builder/src/FormBuilderContext.js, packages/@sanity/form-builder/src/sanity/SanityFormBuilder.js, packages/@sanity/form-builder/src/sanity/SanityFormBuilderContext.js, packages/@sanity/form-builder/src/sanity/WithFormBuilderValue.js, packages/@sanity/form-builder/src/sanity/index.js, packages/@sanity/form-builder/src/sanity/inputResolver/inputResolver.js, packages/@sanity/form-builder/src/utils/withDocument.js
This expands on #213, and provides more cleanup of the form-builder part API. This rewrite was triggered by an issue with a circular import that I ran into yesterday and had to work around it with this (rather ugly) hack:
https://github.com/sanity-io/sanity/blob/06b9dcc25754ca5ec28e54dd2a5cb3c210e34000/packages/%40sanity/form-builder/src/sanity/inputResolver/inputResolver.js#L40-L53
[We should probably put some more energy into figuring out how to avoid future circular import issues like this, but for now, this hack will do the trick]
There's technically a breaking change in here, in that the FormBuilder now must be passed the schema as a prop (so you'll have to import it wherever the `<FormBuilder` is used), but AFAIK the only place we use the form builder today is a few places in Vega …
=> [form-builder] More form-builder public api cleanup

packages/@sanity/cli/src/commands/init/bootstrapTemplate.js, packages/@sanity/cli/src/versionRanges.js
Currently we are resolving all dependencies to their latest versions on bootstrap. This isn't the intended behaviour, as it installs React 16 which isn't fully compatible yet.
With this change, only Sanity dependencies will be resolved to the latest version, and once we move to a better semver strategy we should instead resolve packages to the latest satisfying version within the given range.
=> [cli] Resolve only 1st-party dependencies to their latest versions

packages/@sanity/import/src/documentHasErrors.js, packages/@sanity/import/test/__snapshots__/uploadAssets.test.js.snap, packages/@sanity/import/test/fixtures/invalid-id.ndjson, packages/@sanity/import/test/import.test.js
Not sure how I missed this one. Imported documents shouldn't _require_ an `_id` property, as the API generates one for you if you don't specify one.
=> [import] Don't require `_id` property

packages/@sanity/import/README.md, packages/@sanity/import/src/documentHasErrors.js, packages/@sanity/import/src/import.js, packages/@sanity/import/src/validateOptions.js, packages/@sanity/import/test/__snapshots__/import.test.js.snap, packages/@sanity/import/test/helpers/helpers.js, packages/@sanity/import/test/helpers/index.js, packages/@sanity/import/test/import.test.js, packages/@sanity/import/test/uploadAssets.test.js
Currently the import module only accepts a stream. Having to wrap an array of documents in a stream feels weird and unnecessary. This PR ensures that you can call the import with either a stream or an array of documents.
=> [import] Allow importing from array

packages/@sanity/base/src/schema/types/fileAsset.js, packages/@sanity/base/src/schema/types/imageAsset.js, packages/@sanity/data-aspects/src/DataAspectsResolver.js, packages/@sanity/schema/src/preview/guessPreviewConfig.js, packages/@sanity/schema/src/types/file.js, packages/@sanity/schema/src/types/image/fieldDefs.js
I noticed that we are prefixing the type of asset documents with `sanity.`. Found a few places that did not follow this convention.
This patch:
- Prefixes the imageAsset and fileAsset schema types with `sanity.`
- Renames invalid schema type name from `fileAsset` to `sanity.sanityAsset`
- Adds the `originalFilename` to the internal schema definition for imageAssets and fileAssets
- Uses `asset.originalFilename` as default preview title on images
=>  [schema] Fix wrong asset type names and use asset.originalFilename as default preview title for images

.travis.yml, gulpfile.js, package.json, packages/@sanity/cli/bin/sanity
In time, we should run tests for individual tests, but we need to clean up a bit before that is doable. For now, I think it's important that we ensure:
- The repo is always in a buildable state
- The CLI tool is runnable and can build the test-studio
- The CLI tool can run an (unattended, for now) init proceedure and build the resulting project
Will squash the commits when approved.
=> Basic continuous integration setup

packages/@sanity/components/src/previews/MediaPreview.js
We have a plan for replacing all of these hardcoded sizes with a richer sourceset based solution, but for now let's bump the default image size up to 160px as this is what the grid component uses. Makes images sharp again! :+1:
=> [components] Bump default media preview to 160px

packages/@sanity/core/src/actions/build/compressJavascript.js
This PR makes the minifying process use the uglify-js API instead of spawning the binary. It should be more reliable and fixes a cross-platform issue where spawning the binary wouldn't work on windows.
Based this on master since it would be nice to get a fix out for our windows users ASAP.
=> [core] Use Uglify-JS API to compress files

packages/@sanity/cli/src/cli.js
Currently, if the error thrown from a CLI command has a `code` property that is truthy but non-numeric, the process exits with code `0`.
This PR ensures that it always exits with a positive numbered error code (we've never used a custom error code in any commands, so I didn't see the need for any smarter logic than simply using `1`).
=> [cli] Ensure CLI exits with positive error code on error

packages/@sanity/base/src/preview/SanityDefaultPreview.js, packages/@sanity/base/src/preview/UploadProgressBar.js, packages/@sanity/form-builder/src/sanity/uploads/typedefs.js, packages/@sanity/form-builder/src/sanity/uploads/uploadFile.js, packages/@sanity/form-builder/src/sanity/uploads/uploadImage.js, packages/@sanity/form-builder/src/sanity/uploads/uploadQueue.js, packages/@sanity/form-builder/src/sanity/uploads/uploaders.js, packages/@sanity/form-builder/src/sanity/uploads/utils.js, packages/@sanity/form-builder/src/typedefs/index.js, packages/@sanity/form-builder/src/typedefs/observable.js
This adds the file name and the mime type to the `_upload` key on values that are currently being uploaded and renames the progress key from `percent` to `progress` (a number between 0 and 100).
Also includes a few flow type tweaks
=> Misc uploader infrastructure tweaks

packages/@sanity/client/README.md, packages/@sanity/client/src/assets/assetsClient.js, packages/@sanity/client/src/data/encodeQueryString.js, packages/@sanity/client/src/sanityClient.js, packages/@sanity/client/test/client.test.js
This PR allows specifying a `extract` option when uploading images that allows you to define what type of metadata to extract for the image.
Also fixed a bunch of code style issues after the latest eslint upgrade and removed a now disallowed option to specify the asset document ID.
=> [client] Specify metadata to extract with `extract`-option

packages/@sanity/base/src/preview/PreviewSubscriber.js
This fixes a bug that in some cases prevented a preview component from being refreshed.
=> [base] Wrap PreviewSubscriber in element

packages/@sanity/base/src/preview/PreviewSubscriber.js
Unfortunately, wrapping the PreviewSubscriber in a div ( #247) introduced a few UI bugs in a few places that we used it do display document fields inline, e.g:
This fix it by wrapping it in a span instead.
=> [base] Use span instead of div as wrapper element in PreviewSubscriber

.travis.yml
When testing on travis, when initialize a new project, the latest _published_ dependencies are used, which isn't really testing the checked-in code. This PR uses the new `symlinkDependencies`-script in order to use the checked-in code instead.
=> [chore] CI: Symlink dependencies of newly created project

packages/@sanity/cli/package.json
This currently causes an error on `sanity init` so should be released immediately.
=> [cli] Add missing dependency: latest-version

packages/@sanity/default-layout/src/components/Search.js, packages/@sanity/form-builder/src/sanity/SanityFormBuilder.js
This closes the search suggestions on Escape and when clicking an element. It also fixes a bug causing focus not being set on first field when editing document.
=> [default-layout] Close search on select and escape

packages/@sanity/import/src/references.js
We don't want to overwrite `_type: "someCustomRefType"`, only set `_type: "reference"` on objects that are missing the property. This PR fixes that.
=> [import] Do not overwrite `_type` on references

packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.js, packages/test-studio/schemas/author.js, packages/test-studio/schemas/references.js, packages/test-studio/schemas/schema.js, packages/test-studio/schemas/typeWithNoToplevelStrings.js
This is a bit of a dirty hack to ensure we target string fields at deeper levels when searching for references (currently, only root level string fields were included in search, causing weird behavior for e.g. localized strings, which are modelled as objects).
=>  [form-builder] Include deeper string fields in reference search

packages/@sanity/base/src/schema/types/fileAsset.js, packages/@sanity/base/src/schema/types/imageAsset.js
Moves `mimeType` and `extension` to `system` fieldset and makes them read only. It also includes a few preview config improvements.
=> [base] More asset schema tweaks

packages/@sanity/default-login/README.md, packages/@sanity/default-login/package.json, packages/@sanity/default-login/src/LoginDialog.js, packages/@sanity/default-login/src/LoginWrapper.js, packages/@sanity/default-login/src/styles/LoginDialog.css
This makes it possible to reuse the default-login plugin in other contexts which deals with global users (like the new manage-app).
Bonus: make it possible to ``npm link`` the module from the mono-repo (add missing dev-dependency ``babel-preset-env``) for development purposes.
=> Feature: allow global logins with the default-login

packages/@sanity/base/src/styles/forms/text-input.css, packages/@sanity/base/src/styles/forms/textarea.css, packages/@sanity/components/src/radiobutton/styles/RadioButtonDefault.css, packages/@sanity/components/src/selects/DefaultSelect.js, packages/@sanity/components/src/selects/SearchableSelect.js, packages/@sanity/components/src/selects/StatelessSearchableSelect.js, packages/@sanity/components/src/selects/story.js, packages/@sanity/components/src/selects/styles/DefaultSelect.css, packages/@sanity/components/src/selects/styles/SearchableSelect.css, packages/@sanity/components/src/textareas/DefaultTextArea.js, packages/@sanity/components/src/textareas/story.js, packages/@sanity/components/src/textareas/styles/DefaultTextArea.css, packages/@sanity/components/src/textinputs/TextInput.js, packages/@sanity/components/src/textinputs/story.js, packages/@sanity/components/src/textinputs/styles/DefaultTextInput.css, packages/@sanity/form-builder/src/inputs/Slug/SlugInput.js
- Removing hasFocus, error etc that is no longer in use (yet)
- fixing isSelected on searchable select
- Proper use of :disabled pseudo class where available
=> [components] Respect disabled prop on input components and cleanup

packages/@sanity/default-layout/src/components/DefaultLayoutContainer.js, packages/@sanity/default-layout/src/components/NotFound.js, packages/@sanity/desk-tool/src/DeskTool.js, packages/@sanity/desk-tool/src/SchemaPaneResolver.js, packages/@sanity/desk-tool/src/index.js
This makes desk-tool handle intent links for edit documents without specifying a type. Useful for creating links to e.g. "edit a document" when you don't have the document type at hand.
=> [desk-tool] Make desk tool handle edit intents without type

packages/@sanity/default-layout/src/components/Search.js, packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.js, packages/@sanity/schema/src/legacy/resolveSearchFields.js, packages/@sanity/schema/src/legacy/types/object.js, packages/@sanity/schema/src/legacy/types/utils.js
The previous workaround for targeting string fields at deeper levels than root (#279) was implemented for reference search only. This moves the traversal to look for string fields on an object type to the `@sanity/schema` and exposes the field paths on `type. __unstable_searchFields`, so that the list of fields can be shared between the reference search and the global studio search. We may consider standardizing the search config in the future, but I think its a good idea to keep it "hidden" for now.
=> [schema] Resolve search fields at schema parse time

packages/@sanity/rich-date-input/src/RichDate.js
Instead support placeholder as type config. The placeholder can optionally be a function, e.g. if you want to format using current date/time.
=> [rich-date-input] Remove default placeholder

packages/@sanity/webpack-integration/package.json, packages/@sanity/webpack-integration/src/v3/resolveStyleImport.js
When changing files that are imported through CSS which point to symlinks, webpack doesn't pick up the changes. This change resolves the symlinks before returning the path, which fixes that issue. It introduces a new penalty however, so I've added a cache with a short TTL that should prevent it from hammering the filesystem for the same file. Hopefully we'll find a way to invalidate and prime the cache on each compilation instead of doing this ad-hoc.
=> [webpack-integration] Resolve symlinks, cache imports

packages/@sanity/base/src/styles/variables/forms.css, packages/@sanity/components/src/buttons/styles/DefaultButton.css, packages/@sanity/components/src/dialogs/styles/DefaultDialog.css, packages/@sanity/components/src/edititem/styles/FoldOut.css, packages/@sanity/components/src/edititem/styles/PopOver.css, packages/@sanity/components/src/fieldsets/styles/DefaultFieldset.css, packages/@sanity/components/src/fileinput/styles/FileInputDropZone.css, packages/@sanity/components/src/tags/styles/TextField.css
Chrome has added border-radius to its browser style-sheet, making all our buttons to have rounded border. Using this opportunity to respect the --border-radius-base variable on most components. Default on sanity is 0.
=> Respecting border-radius variable where needed

packages/@sanity/cli/src/commands/init/bootstrapPlugin.js
Fix for `sanity.json` ending up with `[object Object]` :blush:
=> [cli] Fix plugin init not serializing sanity.json

packages/@sanity/cli/src/commands/init/templates/moviedb.js
Shorter, simpler URL that we can purge from CDN when necessary.
=> [cli] Use new moviedb dataset URL

packages/@sanity/form-builder/sanity.json, packages/example-studio/components/CustomObjectInput.js, packages/example-studio/components/Slider/Slider.js, packages/example-studio/components/VideoEmbedInput/VideoEmbedInput.js, packages/example-studio/schemas/author.js, packages/example-studio/schemas/blogpost.js, packages/example-studio/schemas/customObject.js, packages/example-studio/schemas/localeString.js, packages/example-studio/schemas/protein.js
This adds a separate part for patch-events, so that you can do:
```
import PatchEvent, {set, unset} from 'part:@sanity/form-builder/patch-event'
```
Also updates example-studio
=> [form-builder] Add a separate part for patch-event

packages/@sanity/core/src/actions/build/compressJavascript.js
Previously:
```
espenh@plumm ~/webdev/some-studio $ sanity build
✔ Clearing output folder (161ms)
✔ Building Sanity (40934ms)
✔ Building index document (1360ms)
✖ Minifying Javascript bundles
Unexpected token keyword «function», expected punc «,»
```
With this PR:
```
espenh@plumm ~/webdev/some-studio $ sanity build
✔ Clearing output folder (221ms)
✔ Building Sanity (33110ms)
✔ Building index document (451ms)
✖ Minifying Javascript bundles
Parse error at /home/espenh/webdev/some-studio/dist/static/js/app.bundle.js:225035,17
value: async function fetchData() {
^
```
=> [core] Improve minification error messages

packages/@sanity/cli/src/actions/yarn/yarnWithProgress.js
This fixes #301 - when encountering non-JSON output from yarn, skip it.
It also adds some logic to prevent duplicate steps from appearing in the output, which is often the case with the `Linking dependencies`-step.
=> [cli] Filter yarn output

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/BlockEditor.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderBlock.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderInline.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/Syncer.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/createBlockNode.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/createInlineNode.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/preview/Normal.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/util/prepareSlateForBlockEditor.js, packages/test-studio/schemas/uploads.js
This fixes a race condition that caused an error if several patches were applied quickly after each other, e.g. in the case of a batch upload on a value in the the block editor.
(cc @simen)
=> [form-builder] Fix race condition when patching block node values

packages/@sanity/components/src/edititem/PopOver.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderBlock.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/styles/FormBuilderBlock.css
Respect editModal option in schema options (like on array), and choose proper edit modal when not set, based on number of fields in the type.
=> [form-builder] Respect editModal schema option on Block Editor

packages/@sanity/client/README.md, packages/@sanity/client/src/assets/assetsClient.js, packages/@sanity/client/test/client.test.js
The `client.assets.delete()` method should no longer be used, as the operation is now handled by deleting the associated asset document.
This PR deprecates the method - we'll remove the method entirely in an upcoming release.
=> [client] Deprecate asset delete method

package.json, packages/@sanity/core/src/actions/start/startAction.js, packages/@sanity/resolver/.babelrc, packages/@sanity/resolver/src/resolvePlugins.js, packages/@sanity/resolver/src/resolver.js, yarn.lock
When encountering missing plugins, this PR will make sure that we check `package.json` to see if the plugin is defined there. If it is, it hints about perhaps running `sanity install` (basically, yarn). If it is not defined there, we suggest `sanity install <plugin-name>`. It also cleans up the resolving order a bit to prevent some really ugly CLI output when this situation occurs.
Closes #18.
=> [core] Hint about installing plugins on plugin resolve failure

packages/@sanity/base/sanity.json, packages/@sanity/cli/src/commands/init/templates/schema, packages/@sanity/cli/templates/clean/schemas/schema.js, packages/@sanity/cli/templates/moviedb/schemas/schema.js, packages/example-studio/schemas/schema.js, packages/storybook/schema.js, packages/test-studio/config/@sanity/data-aspects.json, packages/test-studio/sanity.json, packages/test-studio/schemas/customInputs.js, packages/test-studio/schemas/schema.js, packages/test-studio/src/components/PertEstimate.js, packages/test-studio/src/components/PertEstimateInput.js, packages/test-studio/src/components/PertEstimateSchema.js
We talked about this briefly back in August, but I thought I would take an initial stab at it;
By having a designated schema type part that plugins can implement, you are able to import schema types without explicitly defining each and every one. By having it simple by an array, you can still do operations such as filtering or mapping to remove or customize certain types, and you can also choose not to use the part at all and stick with explicit imports.
What's lacking currently is some sort of neat way to hint that an input component can be used for the type, without hard-wiring it. I'd be interested in hearing if @bjoerge has any suggestions or ideas here.
=> [base] Define schema type part for better plugin support

packages/@sanity/core/src/actions/deploy/deployAction.js
The `/projects/<projectId>/host` endpoint is deprecated and will be removed in the future.
This PR changes to use the `PATCH` endpoint.
=> [core] Use PATCH-endpoint for setting studio host

packages/@sanity/block-tools/src/converters/blocksToSlateState.js, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/decorators/index.js, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/decorators/input.json, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/decorators/output.json, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/index.test.js, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/markDefs/index.js, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/markDefs/input.json, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/markDefs/output.json
There was an issue where marksDefs were written to the Slate block's data props when they really shouldn't.
=> [block-tools] Fix bug when annotations were converted to a Slate state 

packages/@sanity/cli/src/commands/docs/docsCommand.js, packages/@sanity/cli/src/commands/index.js, packages/@sanity/cli/src/commands/init/initSanity.js, packages/@sanity/cli/src/commands/manage/manageCommand.js
This PR adds two new CLI commands:
`sanity docs` opens a browser and points it at https://www.sanity.io/docs/content-studio
`sanity manage` opens a browser and points it at https://manage.sanity.io/, or if you are in a project context, https://manage.sanity.io/projects/<projectId>
=> [cli] Add CLI methods for manage and docs

packages/@sanity/observable/.gitignore, packages/@sanity/observable/.npmignore, packages/@sanity/observable/.travis.yml
Looks like the React native packager reads .babelrc from dependencies. Since babel-preset-es2105 is a devDependency for `@sanity/observable`, and .babelrc was included in the published package, the React Native packager errored when it could not resolve the babel-preset-es2105 dependency.
This should fix it.
I also removed an old .travis.yml and did some minor housekeeping.
=>  [observable] Add .babelrc to .npmignore + some dotfiles cleanup

package.json, scripts/printReleaseNotesTemplate.js
This adds a script that outputs a starting point for release notes on `npm run release-notes`
=> [chore] Add a release-notes script that outputs a release notes template

packages/@sanity/base/src/components/VersionChecker.js
The `outdated` array returned by the backend includes name and version numbers. We were simply joining the array, which results in a bunch of `[object Object]` :man_facepalming:
=> [base] Fix outdated modules message

packages/@sanity/base/src/preview/observeForPreview.js, packages/@sanity/base/src/preview/resolveRefType.js, packages/@sanity/desk-tool/package.json, packages/@sanity/desk-tool/src/components/ConfirmDelete.js, packages/@sanity/desk-tool/src/components/ConfirmDiscard.js, packages/@sanity/desk-tool/src/components/ConfirmPublish.js, packages/@sanity/desk-tool/src/components/ConfirmUnpublish.js, packages/@sanity/desk-tool/src/pane/Editor.js, packages/@sanity/desk-tool/src/pane/EditorWrapper.js, packages/@sanity/form-builder/src/inputs/Reference/ReferenceInput.js, packages/@sanity/form-builder/src/inputs/Reference/styles/ReferenceInput.css, packages/@sanity/form-builder/src/sanity/inputs/SanityReference.js, packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.js, packages/test-studio/schemas/references.js
This adds support for marking references as weak in the schema, e.g.:
```js
{
type: 'reference',
to: [{type: 'author'}],
weak: true
}
```
Since there's currently no way to know if a referring document is referring by a weak or strong reference, the desk tool UI needs to support "attempt to delete/unpublish". However, if delete/unpublish fails, we now display an error explaining that the reason is most likely due to strong references.
=> Add support for weak references

packages/@sanity/form-builder/src/inputs/Array/ConfirmButton.js, packages/@sanity/form-builder/src/inputs/Array/ItemValue.js, packages/@sanity/form-builder/src/inputs/Array/styles/ConfirmButton.css, packages/@sanity/form-builder/src/inputs/Array/styles/ItemValue.css
Minor cleanup: Moves confirm button popover visibility state out of `ItemValue` and back into `ConfirmButton`
=> [form-builder] Move item remove logic to ConfirmButton

packages/@sanity/cli/.gitignore, packages/@sanity/cli/scripts/pack.js
`xdg-open` is used to open things (like a URL) on Linux. The new "pack the whole CLI into one big file" change broke a bit because opn tries to find the xdg-open binary next to itself. This PR copies the binary over to the bin directory.
=> [cli] Copy xdg-open binary to bin directory on pack

packages/@sanity/cli/src/actions/init-plugin/bootstrapFromTemplate.js, packages/@sanity/cli/src/commands/init/initPlugin.js, packages/@sanity/cli/src/debug.js
This PR allows plugin templates to define dependencies and prompts the user to install them if the user is in a project context.
I also snuck in a feature to allow specifying a minimum CLI version, so new features like this one can be added in a backwards "compatible" way.
=> [cli] Support specifying dependencies in plugin templates

packages/@sanity/presence-store/package.json, packages/@sanity/reflector-client/package.json
Two packages were missing the `@sanity`-prefix.
=> [chore] Fix missing @sanity prefix

packages/@sanity/cli/src/util/noSuchCommandText.js
When you type `sanity deploy` or other Sanity core commands in a non-project context, tis' nice to get a little help telling you they are only available in project context. A few commands were missing from the list, so added the missing ones.
=> [cli] Add more commands to list of core cmds

packages/@sanity/webpack-integration/src/v3/index.js
When calling `getPostcssPlugins`, there is currently no way to pass options to the cssnext and lost plugins. This PR adds this functionality.
=> [webpack-integration] Allow passing options to CSSNext/Lost

packages/@sanity/resolver/package.json, packages/@sanity/resolver/src/resolvePlugins.js, packages/@sanity/resolver/src/resolver.js, packages/@sanity/resolver/test/fixtures.js, packages/@sanity/resolver/test/resolvePlugins.test.js
Some functions had been moved from promises to async functions, which was causing the synchronous mode to fail. This PR fixes that and upgrades some dependencies for the test suite to work on later versions of node.
=> [resolver] Fix sync functions being forced to async

packages/@sanity/plugin-loader/loader.js, packages/@sanity/plugin-loader/package.json
The plugin-loader was not using postcss plugins, which _might_ result in different hashes.
Additionally, there was no way to resolve from the current module parent directory. This is now fixed with an option (defaults to false).
=> [plugin-loader] Use postcss plugins, improved resolving

packages/@sanity/form-builder/test/.init.js, packages/@sanity/form-builder/test/sanity.json
The tests were not passing due to some issues in the resolver. This has been fixed in #381.
Once that was fixed, there were a few more issues; project ID not being defined, as well as a few modules that needs to be resolved in a different way due to being development dependencies.
There are still issues with the tests, but they seem to be form-builder related now, at least.
=> [form-builder] Set project ID for tests, allow local module resolution

packages/@sanity/form-builder/src/patch/array.js
This took me a while to track down, and I'm not 100% sure it covers all cases, but it should provide a good starting point:
When you pass the form builder a (simplified) JSONPath selector (`{foo: bar}` == `'[foo == "bar"]'`), it is passed to lodash's `findIndex` function. If you pass it something where there is no match, it returns `-1`.
This value was being used "raw", so for an `unset` patch with a non-matching selector, it ended up calling `splice(-1, 1)`, which removes the last item in the array, instead of doing nothing, as is the intended result.
In the same way, saying "insert this item after the item where key is X" in a case where that item did not exist in the array would insert the item at the end of the list, whereas the API would not insert it at all.
I'm a little unsure if …
=> [form-builder] Fix array index resolving bug

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/styles/Syncer.css
The "out of sync" dialog only fills a certain portion of the screen, which looks... less than great.
We should be able to remove this dialog altogether soon, but until then..
=> [form-builder] Make out-of-sync warning full-width

packages/@sanity/form-builder/src/inputs/Reference/ReferenceInput.js, packages/test-studio/schemas/references.js
This fixes a minor UI issue with weak refs in arrays that would show a weak mismatch warning for the reference before the `_ref` key was set.
=> [form-builder] Fix false weak mismatch false positive

packages/@sanity/block-tools/src/converters/blocksToSlateState.js, packages/@sanity/block-tools/src/converters/slateStateToBlocks.js, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/decorators/output.json, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/markDefs/input.json, packages/@sanity/block-tools/test/tests/converters/blocksToSlateState/markDefs/output.json, packages/@sanity/block-tools/test/tests/converters/slateStateToBlocks/decorators/output.json, packages/@sanity/block-tools/test/tests/converters/slateStateToBlocks/markDefs/index.js, packages/@sanity/block-tools/test/tests/converters/slateStateToBlocks/markDefs/input.json, packages/@sanity/block-tools/test/tests/converters/slateStateToBlocks/markDefs/output.json, packages/example-studio/schemas/richText.js, packages/example-studio/schemas/schema.js
This will set keys on blocks and spans, and make them persistent going back and forth from the frontend and backend. If you load old data into the editor, keys will be generated and populated when syncing.
=> [block-tools] Set keys on blocks and spans

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/BlockEditor.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/styles/BlockEditor.css
This adds a "Jump to editor"-button when tabbing into the block editor:
=> [form-builder] Support skipping directly to block editor

packages/@sanity/default-layout/src/components/DefaultLayout.js, packages/@sanity/default-layout/src/components/DefaultLayoutContainer.js, packages/@sanity/default-layout/src/components/ToolSwitcher.js, packages/@sanity/default-layout/src/datastores/urlState.js, packages/test-studio/sanity.json, packages/test-studio/src/test-intent-tool.js
This refactors the url state management out of the components layer and into its own store and gives current active tool precedence when resolving intent links.
=> [default-layout] Give active tool precedence when resolving intent links

packages/@sanity/default-layout/src/components/Search.js
This avoids a setState call on _click outside_ and prevents an unneccessary rerenders of the search component on every click anywhere in the studio.
=> [default-layout] Prevent unnecessary rerenders of Search

packages/@sanity/form-builder/src/FormBuilderContext.js
The resolution of which input to use for which schema type is currently treated as a static mapping between _schema type_ *=>* _input component_. The resolution is done quite excessively, so this PR memoizes the _schema type_ *=>* _input component_ map.
We may consider supporting dynamic input resolution later on, but I have not seen any compelling reasons to do so yet.
=> [form-builder] Memoize hot methods

packages/@sanity/block-tools/src/HtmlDeserializer/index.js, packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/lists/input.html, packages/@sanity/block-tools/test/tests/HtmlDeserializer/lists/output.json
The deserializer did not put the annotation mark in the blocks's ``markDefs`` array when originating from a list item. This will fix it.
=> [block-tools] Fix bug in deserializing annotations within list item block

packages/@sanity/components/src/tags/TextField.js, packages/@sanity/components/src/tags/story.js, packages/@sanity/components/src/tags/styles/TextField.css
This cleans up the tags textfield so it aligns better with the rest of the inputs in that it emits an onChange and takes a value.
This also makes it focusable through a `.focus()` method.
I'm not sure if the focusHelper element is needed/in use here, so I kept it for now (it seemed to refer to a unused style):
https://github.com/sanity-io/sanity/blob/f30921333bd6f29ab6c834337e444a610d0c6da0/packages/%40sanity/components/src/tags/TextField.js#L132
=> [components] Clean up tags textfield and make focusable

packages/@sanity/components/src/fieldsets/DefaultFieldset.js, packages/@sanity/components/src/fieldsets/story.js, packages/@sanity/form-builder/examples/schema-testbed/schemas/fieldsets.js, packages/@sanity/form-builder/src/inputs/Object/Object.js, packages/@sanity/schema/test/legacy/fixtures/schemas/fieldsets.js
In order to be able to deep link to form builder fields, the default fieldset must support being expanded initially. This PR fixes that.
Summary:
- Adds a `isCollapsible`-prop that must be true to make the fieldset collapsible.
- Adds a `isCollapsed`-prop that, renders the fieldset as collapsed initially.
- Fixes a typo: _collapsable_ should be _collapsible_ (preserved backwards compatibility with schema options)
- General cleanup
=> [components] Cleanup fieldset - support isExpanded by default

packages/@sanity/cli/scripts/pack.js
Seems like fsevents is installed by default on Mac, so we need to whitelist this module when packing the CLI. It seems to work fine without it, seeing as people have been running the packed CLI for about two weeks.
=> [cli] Whitelist fsevents module when packing

packages/@sanity/import/package.json, packages/@sanity/import/src/assignDocumentId.js, packages/@sanity/import/src/documentHasErrors.js, packages/@sanity/import/src/import.js, packages/@sanity/import/test/fixtures/invalid-id-format.ndjson, packages/@sanity/import/test/fixtures/valid-but-missing-ids.ndjson, packages/@sanity/import/test/import.test.js
Certain operations, such as strengthening of references and asset document generation, currently require you to have document IDs, but do not warn you of this.
This PR adds document IDs for any documents that do not already have one, which should solve this in the easiest way I could think of.
Fixes #402
=> [import] Generate document IDs on client side

packages/@sanity/block-tools/src/HtmlDeserializer/index.js, packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/default.js, packages/@sanity/block-tools/src/HtmlDeserializer/rules/default.js, packages/@sanity/block-tools/test/tests/HtmlDeserializer/customRules/index.js, packages/@sanity/block-tools/test/tests/HtmlDeserializer/customRules/input.html, packages/@sanity/block-tools/test/tests/HtmlDeserializer/customRules/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/nestedContainers/input.html, packages/@sanity/block-tools/test/tests/HtmlDeserializer/nestedContainers/output.json
This will handle block elements within blockquotes.
Also fix bug where non-text-elements only (like img) within block elements, made it be preprocessed away.
=> [block-tools] Fix deserialization of blockquotes containing block elements

packages/@sanity/form-builder/src/FormBuilderContext.js
Sometimes you get into weird cases where there is no preview component or input component available. The memoization introduced recently breaks when this happens, because it tries to use `undefined` as the key on a WeakMap.
This PR simply checks if the key is truthy, and skips memoization if it isn't.
=> [form-builder] Fix crash when input/preview cannot be resolved

packages/@sanity/core/src/commands/dataset/deleteDatasetCommand.js, packages/@sanity/core/src/commands/dataset/exportDatasetCommand.js, packages/@sanity/core/src/commands/dataset/importDatasetCommand.js
If you have a numeric dataset name, say `2018`, certain dataset commands will fail because the CLI casts it to a number. When fetching available datasets and comparing it with a strict equals operator, it misses. This PR manually casts all dataset names to strings.
=> [core] Fix numeric datasets being treated as missing

packages/@sanity/schema/src/legacy/types/array.js
Not quite sure what this code was doing in a source file, but I _assume_ it's just code that have been used while developing which has unintentionally made it's way into the release.
Assuming it's safe to remove.
=> [schema] Remove stray test code from array schema type

packages/@sanity/schema/src/sanity/validation/utils/validateTypeName.js
If you have an error in your schema where a `type`-field is a non-string, the schema validation will fail when trying to figure out the closest match to it it with a levenshtein distance comparator.
This adds an additional step ensuring that the type is a string.
=> [schema] Validate that type name is a string

packages/@sanity/base/src/datastores/user/createUserStore.js
... this fixes a case where the message is published, the observable triggers a `next`, state gets updated in the LoginWrapper and React updates it's tree but encounters an error during rendering. Currently this is caught by the `catch` clause in the user store, which makes it really hard to debug.
This is a *temporary hack*. We need a proper way of handling these situations soon.
=> [base] Asynchronously publish resolved user

packages/@sanity/base/src/datastores/user/createUserStore.js
Instead of doing a `setTimeout()` to prevent swallowing errors in the `then`-handler on the user store, use the `.then(onSuccess, onError)` form, which prevents errors happening in the `onSuccess` handler from being caught in the `onError` handler.
=> [base] Solve swallowed error without defering to next tick

packages/@sanity/base/src/datastores/user/createUserStore.js, packages/@sanity/block-tools/src/HtmlDeserializer/index.js, packages/@sanity/core/src/commands/dataset/deleteDatasetCommand.js, packages/@sanity/core/src/commands/dataset/exportDatasetCommand.js, packages/@sanity/core/src/commands/dataset/importDatasetCommand.js, packages/@sanity/form-builder/src/FormBuilderContext.js, packages/@sanity/image-url/README.md, packages/@sanity/image-url/src/builder.js, packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/builder.test.js, packages/@sanity/import/package.json, packages/@sanity/import/src/util/getBufferForUri.js, packages/@sanity/schema/src/legacy/types/array.js, packages/@sanity/schema/src/sanity/validation/utils/validateTypeName.js, packages/@sanity/vision/src/SanityVision.js
Upgrade with:
sanity upgrade
And install the latest Command Line Interface (CLI) with:
npm install --global @sanity/cli
- Fix bug where certain studio errors (uncaught schema errors, for instance) would not give any indication or error message
- Vision no longer switches dataset for entire studio, but rather just for that tool
- When importing assets from a URL and the response is a redirect from http->https or https->http, the requests no longer fail
- Couple of issues with how the CLI tool treated numeric datasets is now fixed
Author | Message | Commit
------------ | ------------- | -------------
Per-Kristian Nordnes | [block-tools] Fix bug which expected node.children which is not always the case | 84f24392
Espen Hovlandsdal | [import] Use forked get-uri with redirect fix | bd146383 …
=> Release 0.123.1

packages/@sanity/imagetool/src/makeDragAware.js, packages/test-studio/package.json
`TouchEvent` is not defined in Firefox. When attempting to drag the hotspot, Firefox throws an error.
I did some basic tests and it seems that `touches` is not present on regular mouse events.
=> [imagetool] Fix hotspot drag not working in Firefox

packages/@sanity/block-tools/src/converters/slateStateToBlocks.js
Seems like there were a little snag in the code, where it would initiate the markDefs with existing values. It should always start from an empty array as it builds it up anyway from every span node.
=> Start block markDefs from empty array

packages/@sanity/desk-tool/src/SchemaPaneResolver.js
Fixes a bug where documentspane did not display correct view/ordering without reload.
=> [desk-tool] Force update of documents pane with key

packages/@sanity/form-builder/src/FormBuilderInput.js
This fixes an annoyance causing page scroll when dragging elements in an array
(cc @kristofferj)
=> [form-builder] Remove scroll into view offset on FormBuilderInput

packages/@sanity/default-layout/src/components/styles/DefaultLayout.css
Fixes a bug where the loading screen stays on screen after loading.
Maybe that animationend happends before the listener is added
=> [default-layout] Not showing loadingscreen if not loading

packages/@sanity/components/src/selects/StatelessSearchableSelect.js
Fixed by making the loading message and no results message be escapable & closeable
=> [components] Fix: unable to close reference search popover

packages/@sanity/components/src/textareas/DefaultTextArea.js, packages/test-studio/schemas/schema.js, packages/test-studio/schemas/texts.js
This exposes both `.focus()` and `.select()` methods on DefaultTextArea instances.
=> [components] Make DefaultTextArea focusable

packages/@sanity/schema/src/legacy/types/reference.js, packages/@sanity/schema/src/legacy/types/string.js
This is rather embarrassing. These were only useful at the early stage of writing the (now legacy) schema code, so it should have been removed a long time ago.
=> [schema] Remove stray assertions

packages/@sanity/default-login/README.md, packages/@sanity/default-login/config.dist.json, packages/@sanity/default-login/package.json, packages/@sanity/default-login/src/LoginDialog.js, packages/@sanity/default-login/src/UnauthorizedUser.js, packages/@sanity/default-login/src/authenticationFetcher.js, packages/@sanity/default-login/src/styles/LoginDialog.css, packages/@sanity/default-login/src/util/getProviders.js
Allow overriding and configuring the provider list in the default-login part.
This is to support the third party login enterprise features.
=> [default-login] Allow overriding provider list

packages/@sanity/base/src/preview/observeWithPaths.js
When resolving previews, we often end up with queries such as:
```js
[
*[_id==$id_0]{_id,_type,url},
*[_id==$id_1]{_id,_type,url},
*[_id==$id_2]{_id,_type,url},
*[_id==$id_3]{_id,_type,url},
*[_id==$id_4]{_id,_type,url},
*[_id==$id_5]{_id,_type,url}
]
```
Which currently is not optimized on the server side. This PR optimizes the cases where the projects are equal, such as in the case above, and instead creates a query like the following:
```js
*[_id in ["someId_0", "someId_1", "someId_2", "someId_3", "someId_4"]]{_id, _type, url}
```
When the response arrives, we reassemble the array so that the results are in the same order as the selection passed to the `observeWithPaths`.
I'm sure this could be solved slightly cleaner, but this reduces a 15-document query from ~250ms to ~15ms.
=> [base] Optimize preview snapshot fetching

packages/@sanity/core/src/actions/build/buildStaticAssets.js, packages/@sanity/core/src/actions/config/reinitializePluginConfigs.js, packages/@sanity/core/src/actions/start/startAction.js, packages/test-studio/.gitignore
This PR ensures that the plugin re-initialization is ran before building static assets. Currently, if you've bootstrapped a studio and run `sanity build` or `sanity deploy` before running `sanity start`, the build might fail due to missing configs.
=> [core] Re-initialize plugin configs before building to static assets

packages/@sanity/form-builder/src/inputs/Array/Array.js, packages/test-studio/schemas/arrays.js
Sorting in arrays with grid view was accidentally broken in v0.124.0. This fixes it.
Let's merge it into master and release a fix immediately.
(Also added a test case to the example studio with grid array of mixed types)
=> [form-builder] Use drag handle *unless* layout is grid

packages/@sanity/form-builder/package.json, packages/@sanity/form-builder/src/FormBuilderInput.js
Scrolling into view when an input receives focus is not needed as browsers seem to do this by default anyway. In addition, it messed with sorting in arrays too, so let's remove it.
(also including a few minor flowtype fixes)
=> [form-builder] Don't force scroll input into view on focus

packages/@sanity/base/package.json, packages/@sanity/base/sanity.json, packages/@sanity/base/src/components/VersionChecker.js, packages/@sanity/default-layout/src/components/DefaultLayout.js, packages/@sanity/default-layout/src/components/UpdateNotifier.js, packages/@sanity/default-layout/src/components/UpdateNotifierDialog.js, packages/@sanity/default-layout/src/components/styles/UpdateNotifier.css, packages/@sanity/default-layout/src/components/styles/UpdateNotifierDialog.css
Warning: This needs styling before merge.
Basically, checks for outdated modules and gives a little indication in the lower left corner of the screen. In the future, we'll want to move this functionality to a separate plugin, but I don't think it's worth doing right now.
You can fake the functionality by setting `fakeOutdatedModule` to `true` in `packages/@sanity/base/src/components/VersionChecker.js`.
Sorry about the large number of changes in the default layout component - Prettier had a field day on it.
=> [default-layout] Add update notifier for outdated modules

packages/@sanity/form-builder/src/inputs/ArrayOfPrimitives/ArrayOfPrimitives.js, packages/@sanity/form-builder/src/inputs/ArrayOfPrimitives/Item.js
- Fixes a bug that broke sorting of items in PrimitiveArray
- Adds support for "add item on enter key" (#457)
- Sets focus on newly added items.
- shift + backspace in an empty item will delete it (not sure if this is sane, thoughts welcome)
Pinging @kristofferj and @evenwestvang for review/opinions.
=> [form-builder] Improve UX of PrimitiveArray

packages/@sanity/form-builder/src/inputs/ImageTool/ImageToolInput.js, packages/@sanity/imagetool/src/ImageTool.js
This restores the old ImageTool behavior that emitted`onChange`-events continuously while adjusting hotspot/crop, but also adds an `onChangeEnd` event to signal that the adjustments have ended.
Also caches the ImageTool value in the (recently added) ImageTool input, and forwards the change from there on `ImageTool.onChangeEnd`.
(And a few formatting/lint fixes)
=> [imagetool] Support onChangeEnd event and cache imagetool value in ImageToolInput

packages/@sanity/form-builder/src/FormBuilderInput.js, packages/@sanity/form-builder/src/inputs/Array/ConfirmButton.js
So turns out the `setTimeout`-hack that I used to fix an issue with focus in popovers caused more problems than it solved (who could have guessed?!).
It caused focus to sometimes get stuck jumping really fast between inputs, which is less desirable than losing focus state on an element inside a popover (which should be fixed separately).
=> [form-builder] Remove setTimeout workaround for popover focus issue

packages/@sanity/form-builder/src/inputs/ArrayOfPrimitives/ArrayOfPrimitives.js
This fixes a bug that would make ArrayOfPrimitives throw an error if `value` was missing.
=> [form-builder] Make ArrayOfPrimitives tolerant of missing value

packages/@sanity/form-builder/src/inputs/Image/ImageInput.js, packages/test-studio/schemas/author.js
The edit button only appeared on image fields when there were one or more fields defined on the image type, even if `hotspot`: `true` was set. This will always show the edit button if `hotspot: true`
=> [form-builder] Always show edit button when hotspot tool is enabled

packages/@sanity/schema/src/legacy/preview/createPreviewGetter.js, packages/@sanity/schema/src/legacy/preview/guessPreviewConfig.js, packages/@sanity/schema/src/legacy/types/blocks/block.js, packages/@sanity/schema/src/legacy/types/blocks/span.js, packages/@sanity/schema/src/legacy/types/file.js, packages/@sanity/schema/src/legacy/types/image.js, packages/@sanity/schema/src/legacy/types/object.js, packages/test-studio/schemas/images.js
This should correctly resolve image fields if no preview config is defined on a type.
=> [schema] Fix default image preview resolution

packages/@sanity/base/src/preview/index.js, packages/@sanity/preview/index.js, packages/@sanity/preview/src/createPathMaterializer.js, packages/@sanity/preview/src/materializePaths.js, packages/@sanity/preview/src/observeForPreview.js
This exposes a function for materializing a set of paths on a given value. Useful e.g. when you have a partially fetched document but need to retrieve more of its properties, e.g.:
```js
import {materializePaths} from '@sanity/preview'
const partialDoc = {
_id: 'abc'
}
materializePaths(partialDoc, ['title', 'publishDate'])
.subscribe(doc => {
console.log('Title: %s, publish at: %s', doc.title, doc.publishDate)
})
```
=> [preview] Expose the materializePaths function used in the preview package

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/Syncer.js, packages/@sanity/form-builder/src/utils/withPatchSubscriber.js
This fixes a bug in a higher order component that we use for subscribing to incoming patch events. It was just forwarding `.focus()`-calls to the composed component, but that failed if the composed input did not implement a `.focus()` method. This fix will guard against it by only forwarding `focus()` calls if the composed component exposes a `focus`-method.
=> [form-builder] Don't fail if wrapped input is missing a .focus-method

packages/@sanity/schema/src/legacy/preview/guessPreviewConfig.js, packages/test-studio/schemas/recursiveArray.js
This supersedes #505.
This will pick any image field as `media` (unfortunately this solution still got all the shortcomings mentioned in #505, but is less intrusive).
=> [schema] Give image fields higher priority for media preview

packages/test-studio/package.json
The test studio is not using the latest version of vision currently, which makes it hard to develop on it.
=> [test-studio] Update vision

packages/@sanity/client/README.md, packages/@sanity/client/src/config.js
Make it clearer that a Promise polyfill is needed in older browsers
=> [client] Make Promise polyfill details clearer, add url to thrown error

packages/@sanity/form-builder/src/inputs/Object/Object.js
Something got messed up with the defaults here, so fieldsets ended up being non-collapsible and collapsed by default, which was unfortunate. This fixed it so that the defaults are:
``` 
collapsible: true
collapsed: true
```
=> [form-builder] Fix bug with fieldsets

packages/@sanity/desk-tool/src/components/TimeAgo.js
"4 hours ago" is not necessarily as specific as one might want. This PR adds the specific timestamp as title attribute on relative times, so the user might hover the relative timestamp to see a more specific version.
=> [desk-tool] Add timestamp as title attribute on relative dates

packages/@sanity/desk-tool/src/pane/EditorWrapper.js
This is a partial fix for preserving `_createdAt` throughout the lifetime of a document. We still have a bug in the mutator that omits it from on setIfMissing patches, but that should be fixed separately.
=> [desk-tool] Preserve _createdAt between draft <=> published version of a document

packages/@sanity/image-url/README.md, packages/@sanity/image-url/src/builder.js, packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/builder.test.js
We were missing the `crop`-transformation in the builder API.  This PR adds it.
=> [image-url] Add missing `crop`-transformation

packages/@sanity/desk-tool/src/pane/Editor.js, packages/test-studio/src/resolveProductionUrl.js
- Move the menu item to the top
- Don't invoke `resolveProductionPreviewUrl` if document is `null`
=> [desk-tool] Minor tweaks: production preview

packages/@sanity/mutator/src/document/Mutation.js, packages/@sanity/mutator/test/BufferedDocument.test.js
#525 introduced a bug where `createOrReplace` and `createIfNotExists`-mutations would fail when attempting to set `_createdAt`.  This PR fixes this and introduces tests to prevent similar issues in the future.
=> [mutator] Fix createOrReplace and createIfNotExists mutations

packages/@sanity/base/src/assets/asset-url-builder.js, packages/@sanity/preview/src/components/SanityDefaultPreview.js
This will ignore params targeted at our image CDN API like `w=200` from any `imageUrl`-s returned from previews.
=> [preview] Ignore image cdn parameters from preview.imageUrl

packages/@sanity/form-builder/src/inputs/Object/Object.js, packages/test-studio/schemas/fieldsets.js
This fixes a bug with defaults on collapsible fields that got introduced in #514
=> [form-builder] Fix collapsible/collapsed defaults on fieldsets

packages/@sanity/core/package.json, packages/@sanity/core/src/actions/build/compressJavascript.js
After #533 and #534 we are only compiling source code to the targets defined in the toplevel `.babelrc`, that is:
https://github.com/sanity-io/sanity/blob/575ffa1c7b0af96a6247239fdea61035f19690dd/.babelrc#L6-L10
This means the minification step on sanity deploy will have to be able to parse non-ES5 code from  @sanity-modules (from node_modules), so lets replace uglify-js with uglify-es, which can handle  ES6+.
I pinned it to a version that I've tested, just to be on the safe side.
=> [core] Use uglify-es instead of uglify-js for minifying

packages/@sanity/form-builder/src/FormBuilderInput.js, packages/@sanity/form-builder/src/inputs/Array/ConfirmButton.js, packages/@sanity/form-builder/src/inputs/Reference/ReferenceInput.js
This fixes a few minor issues/annoyances:
- Calling .focus() on confirmButton threw an error because of render/timing issues with popover, so disabled for now
- The `focusPath`-prop was sometimes passed to input components and caused an _invalid prop type_-warning
- The reference select would display a link even if there were no `_ref`-property on the value.
=> [form-builder] Minor fixes

packages/@sanity/block-tools/src/converters/blocksToSlateState.js, packages/@sanity/block-tools/src/converters/slateStateToBlocks.js
As we cannot guarantee the integrity of the data block tools is trying to convert, do some extra checks that keys are truthy before putting them on a converted state,  so it is possible to recover from it in the editor.
=> [block-tools] Robustify annotation conversion

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderSpan.js
When an annotation contained a reference, it was not properly cleaned up when blanking it via the reference picker clear button.
=> [form-builder] Fix annotations cleanup bug

packages/@sanity/webpack-loader/src/partLoader.js
This PR ensures that the environment passed to `reduceConfig()` is based on the webpack context instead of environment variables. Altering the config passed to the part loader is a bit risky at this point, so I went for the easier approach of checking which devtool setting we are using, since it is always set to `false` when building for production.
=> [webpack-loader] Reduce configs based on webpack environment

packages/@sanity/default-layout/src/components/CurrentVersionsDialog.js, packages/@sanity/default-layout/src/components/UpdateNotifier.js, packages/@sanity/default-layout/src/components/UpdateNotifierDialog.js, packages/@sanity/default-layout/src/components/styles/UpdateNotifier.css
This PR makes the update notifier show "Up to date" instead of a version number in the bottom left corner. This is done because we can't really figure out a single specific version number, since the studio is composed of many packages. Clicking the text will open a dialog showing the current version numbers.
=> [default-layout] Show 'Up to date' instead of specific version number

packages/@sanity/server/src/configs/webpack.config.js
Currently we are (in monorepo development) double-compiling modules. This is obviously unnecessary and also very confusing. While it would be optimal if webpack reported the symlink location instead of the resolved location, we'll use this hack for now.
=> [server] Exclude `packages/@sanity`-paths from babel-loader

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderBlock.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderInline.js
This should give a pretty good perf boost on documents with a lot of block nodes.
=> [form-builder] Optimize selectionchange event handlers in FormbuilderBlock/FormBuilderInline

packages/@sanity/client/README.md, packages/@sanity/client/src/data/patch.js, packages/@sanity/client/test/client.test.js
This PR adds the missing `ifRevisionId()` patch method to the client.
=> [client] Add ifRevisionId() method to patches

packages/@sanity/core/src/actions/build/buildStaticAssets.js, packages/@sanity/core/src/actions/dataset/chooseDatasetPrompt.js, packages/@sanity/core/src/actions/deploy/deployAction.js, packages/@sanity/core/src/commands/build/buildCommand.js, packages/@sanity/core/src/commands/dataset/importDatasetCommand.js, packages/@sanity/core/src/commands/deploy/deployCommand.js
This PR adds help text that describes the available flags for deploy, build and import commands.
=> [core] Improve help text for deploy, build and import commands

packages/@sanity/core/package.json, packages/@sanity/core/src/actions/exec/babel.js
The latest infra changes broke the `sanity exec` command. This PR should fix that again, and also switches to using `preset-env`.
=> [core] Fix missing dependencies for 'sanity exec' command

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderBlock.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderInline.js
This fixes an error thrown when switching between documents that have a block array.
=> [form-builder] Guard against this._editorNode being null

packages/@sanity/cli/templates/blog/schemas/post.js, packages/@sanity/cli/templates/moviedb/schemas/movie.js, packages/@sanity/cli/templates/moviedb/schemas/screening.js
These has never been supported and AFAIK the new validation format is different.
=> [cli] Remove required: true from template schemas

packages/@sanity/cli/templates/moviedb/schemas/blockContent.js
This converts the different types of references into named types so the UI becomes clearer.
Before:
After:
=> [cli] Make block text references to separate named types

packages/@sanity/base/src/datastores/document/index.js
The document store listeners don't need the mutation results, so we can safely discard them.
=> [base] Don't include results on document store listeners

packages/@sanity/preview/src/createPathMaterializer.js
When the preview was called with a value that was materialized, it was extending it afterwards with the original passed value. This caused the `_ref` (and sometimes `_key`) attributes to be added to the resulting value, and could potentially cause subsequent calls with the same value to identify it as a reference and (needlessly) materialize it again.
This patch omits writing the original attributes if the passed value was a reference.
=> [preview] Don't write ref attributes on materialized values

packages/@sanity/components/src/buttons/styles/DefaultButton.css, packages/@sanity/components/src/dialogs/styles/DefaultDialog.css, packages/@sanity/components/src/dialogs/styles/FullscreenDialog.css, packages/@sanity/components/src/fieldsets/styles/DefaultFieldset.css, packages/@sanity/components/src/loading/styles/Spinner.css, packages/@sanity/components/src/panes/DefaultPane.js, packages/@sanity/components/src/panes/styles/DefaultPane.css, packages/@sanity/components/src/panes/styles/SplitController.css, packages/@sanity/default-layout/src/components/DefaultLayout.js, packages/@sanity/default-layout/src/components/Search.js, packages/@sanity/default-layout/src/components/styles/DefaultLayout.css, packages/@sanity/default-layout/src/components/styles/Navigation.css, packages/@sanity/default-layout/src/components/styles/Search.css, packages/@sanity/desk-tool/src/pane/DocumentsPane.js, packages/@sanity/desk-tool/src/pane/Editor.js, packages/@sanity/desk-tool/src/pane/TypePane.js, packages/@sanity/desk-tool/src/pane/enhanceWithAvailHeight.js, packages/@sanity/desk-tool/src/pane/styles/DocumentsPane.css, packages/@sanity/desk-tool/src/pane/styles/Editor.css, packages/@sanity/desk-tool/src/pane/styles/ListView.css, packages/@sanity/desk-tool/src/pane/styles/enhanceWithAvailableHeight.css, packages/@sanity/desk-tool/src/styles/DeskTool.css
* Better scroll performance on mobile
* Better search UX on mobile
* Design tweaks on navigation for mobile
* Panes content follows body on mobile. (better performence on mobile)
Tested by me. Should be safe to merge but should be tested by one more person.
=> Optimize responsive

packages/@sanity/form-builder/src/inputs/ImageTool/ImageToolInput.js, packages/@sanity/form-builder/src/inputs/ImageTool/styles/ImageToolInput.css, packages/@sanity/imagetool/src/HotspotImage.js, packages/@sanity/imagetool/src/ImageTool.js, packages/@sanity/imagetool/src/makeDragAware.js, packages/@sanity/imagetool/src/styles/HotspotImage.css, packages/@sanity/imagetool/src/styles/ImageTool.css
* Imagetool inside Fieldset
* Nicer previews
* Fixes bug where mousedown is locked when dragging outside window
* Rearrange the listeners to support touch. Also using syntetic events
* Keep cropbox inside boundries when dragging
Some bugs are still present:
* moving hotspot still makes show incorrectly previews while moving
* the code preventing drag crop outside seems to be choppy (should work on the axis that do not goes outside the boundries)
=> [imagetool] Make imagetool responsive

packages/@sanity/check/package.json, packages/@sanity/document-store/package.json, packages/@sanity/import/package.json, packages/@sanity/plugin-loader/package.json, packages/@sanity/preview/package.json, packages/@sanity/production-preview/package.json, packages/@sanity/resolver/package.json, packages/@sanity/schema/package.json, packages/@sanity/server/package.json, packages/@sanity/util/package.json, packages/@sanity/uuid/package.json, packages/@sanity/webpack-integration/package.json, packages/@sanity/webpack-loader/package.json, packages/blog-studio/package.json, packages/movies-studio/package.json, scripts/normalizePackageFields.js
This PR ensures that any package that has a declared `engines.node` property in its `package.json` will be on the same level (node >= 6, currently) as well as setting the author field to `Sanity.io <hello@sanity.io>`.
I also added the engines field to all node-only packages.
=> [chore] Normalize engines and author fields

packages/@sanity/preview/src/observeWithPaths.js
This is an optimization of preview fetching that uses a lower debounce time for initial fetch, and a higher delay for subsequent fetches (e.g. when the previewed document has changed).
It should give a small perceived speedup on the first load of everything that is previewed, and fewer refresher requests when something changed.
=> [preview] Optimize preview fetching

packages/@sanity/client/src/data/listen.js, packages/@sanity/client/test/helpers/sseServer.js, packages/@sanity/client/test/listen.test.js
While the EventSource implementation in browsers will generally reconnect automatically, there are certain cases where it does not. An example of this is when a laptop lid is closed - this will set the `readyState` to `CLOSED` (indicating that it won't reconnect) and trigger an `error` event on the EventSource.
Currently we are simply saying that the observable is `complete`, but we don't have the necessary pieces in place to reconnect, which causes for instance the studio to stop receiving mutation events in these cases.
After some discussion, we find that it makes more sense to never treat the observable as "completed" unless we receive an explicit unsubscribe from the user or a `disconnect` event from the server.
This PR ensures that we _always_ reconnect, manually setting a timer and …
=> [client] Always reconnect listeners, even when auto-reconnect fails

packages/@sanity/server/src/configs/postcss.config.js
The maintainers of `postcss-custom-properties`-module changed a default in a minor release, which broke the studio styling.
Big ups to @rexxars for debugging.
=> [server] Configure custom properties with preserve: false

packages/@sanity/preview/src/utils/optimizeQuery.js
When performing accumulated preview queries we need to ensure we get the whole result set back. This prevents implicit default slices from being applied to accumulated queries.
=> [preview] Fix issue with accumulated queries + default pagination limit

packages/@sanity/base/src/schema/types/fileAsset.js, packages/@sanity/base/src/schema/types/imageAsset.js
Provides ordering by file size on image and file assets, as well as adding the size in megabytes to the subtitles.
While this is a bit of a "hidden feature", it's some fairly cheap sugar :)
=> [base] Provide size ordering + size subtitles for assets

packages/@sanity/components/package.json, packages/@sanity/components/src/previews/DetailPreview.js
This had a severe impact on performance in detailed list views, so removing it.
=> [components] Remove react-text-ellipsis due to perf issues

packages/@sanity/components/src/utilities/ActivateOnFocus.js, packages/@sanity/components/src/utilities/styles/ActivateOnFocus.css, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/BlockEditor.js
We had som problems with this earlier.
But I think this is more stable. Anyway: We need to test this properly before merging.
=> [components] Click to scroll for block editor #76

packages/@sanity/schema/src/sanity/validateSchema.js, packages/@sanity/schema/src/sanity/validation/createValidationResult.js, packages/@sanity/schema/src/sanity/validation/types/slug.js, packages/test-studio/schemas/slugs.js
This provides backwards compatibility for the `slugifyFn` function while deprecating it with a warning, as we discussed in #585
=> [schema] Deprecate `slugifyFn` (now called `slugify`)

packages/@sanity/base/src/styles/forms/text-input.css
=> [base] Not using height on text input

packages/@sanity/desk-tool/src/pane/EditorWrapper.js, packages/@sanity/form-builder/src/sanity/utils/gradientPatchAdapter.js
This is a less controversial version of #605 
By using a "noop patch" (unsetting an arbitrary field), we can use the `ifRevisionID` feature to lock the publishing process and prevent overwriting with a possibly outdated version.
=> [desk-tool] Lock to last-known local revision when publishing

packages/@sanity/schema/src/legacy/types/slug.js, packages/test-studio/schemas/slugs.js
This changes the name of the uniqueness check from `checkUnique` to `isUnique`. This makes it easier to reason about what the function should return.
I also snuck in a small change where the default uniqueness check is passed down to custom `isUnique` functions so that you can compose it more easily.
=> [schema] Change slug uniqueness function name to `isUnique`

packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.js, packages/@sanity/form-builder/src/inputs/ObjectInput/UnknownFields.js
If you have a `readOnly` object that unknown fields, you will get a warning that includes an _Unset_-button. This will not work, as read-only inputs do not forward onChange-events from their children.
This removes the Unset-button if the enclosing input is `readOnly`, and gives the user an explanation of why the value can't be unset.
=> [form-builder] Handle readOnly on unknown fields

packages/@sanity/cli/.eslintrc, packages/@sanity/cli/src/actions/init-project/initProject.js, packages/@sanity/cli/src/commands/init/initCommand.js
This restructures the CLI init process a bit in order to allow creation of new projects in unattended mode (through the `--create-project <name>` flag), as well as skipping prompts when CLI-flags has been given to specify a project ID or dataset.
=> [cli] Allow creating new projects in unattended mode

packages/@sanity/cli/package.json
In order to run the movie-studio during development, the `@sanity/cli` package must have all modules required from schema files as declared dependencies in its package.json.
Added `react-icons` as devDependency.
=> [cli] Add react-icons as dev dependency

packages/@sanity/client/src/data/dataMethods.js, packages/@sanity/client/src/data/transaction.js, packages/@sanity/client/test/client.test.js
This PR allows specifying a transaction ID on transactions. Not necessarily an important feature for most users, but for some use cases (like listeners and webhooks) it's helpful to match a mutation back to it's source.
=> [client] Allow specifying ID of transactions

packages/@sanity/base/src/datastores/document/index.js, packages/@sanity/components/src/snackbar/DefaultSnackbar.js, packages/@sanity/desk-tool/src/pane/Editor.js, packages/@sanity/desk-tool/src/pane/EditorWrapper.js, packages/@sanity/document-store/src/createDocumentStore.js, packages/@sanity/form-builder/src/sanity/SanityFormBuilder.js, packages/@sanity/preview/src/observeFields.js
This supersedes #626 as it relies on the old listener reconnect behavior.
This is a few adjustments regarding how we deal with connection errors (e.g. when the network is down, laptop lid is closed, etc.)
=> [infrastructure] Improve how we handle connection failures/reconnects

packages/@sanity/preview/src/createPathObserver.js, packages/@sanity/preview/src/observeFields.js, packages/@sanity/preview/src/observeForPreview.js, packages/@sanity/preview/src/utils/hasEqualFields.js, packages/@sanity/preview/src/utils/isUniqueBy.js
This improves how deleted/missing documents are passed through the preview pipeline, and fixes an error that would sometimes be triggered when a previewed document got deleted.
Previously, any preview observer that declared that they would display some fields on some document (e.g. `fieldX`, `fieldY` for document with _id `abc`) would always receive an object with the given fields no matter if the document existed or not. This made it impossible to tell the difference between a document that was deleted and a document that existed but had missing values for these fields.
(One consequence of this was that the reference select input for weak references was displaying "Untitled" after the reference got deleted.)
This fixes this problem by passing on `null` as the snapshot for deleted/missing …
=> [preview] Emit null as snapshot for missing documents

packages/@sanity/validation/src/inferFromSchema.js, packages/@sanity/validation/src/inferFromSchemaType.js, packages/@sanity/validation/src/validateDocument.js
This PR ensures that you can disable validation for a given field or document type by specifying `validation: false` in the schema declaration.
=> [validation] Allow disabling validation for field and document types

packages/@sanity/form-builder/src/inputs/ArrayInput/ItemValue.js
This hides the delete button from the _edit array item dialog_ where for arrays that are read only.
=> [form-builder] Hide delete button from dialog when array is read only

packages/@sanity/import/package.json, packages/@sanity/import/src/assetRefs.js, packages/@sanity/import/src/importFromFolder.js
There was an issue where the import would add all found assets as queued uploads, but would fail to include the `file://`-prefix, which resulted in the import failing due to a missing protocol.
=> [import] Fix importing of unreferenced assets

packages/@sanity/cli/templates/moviedb/schemas/castMember.js, packages/@sanity/cli/templates/moviedb/schemas/crewMember.js, packages/@sanity/cli/templates/moviedb/schemas/movie.js, packages/@sanity/cli/templates/moviedb/schemas/person.js, packages/@sanity/cli/templates/moviedb/schemas/screening.js
Now that #587 is in place, we can use the `media` preview config in the movies database template schema.
=> [cli] Use media for preview in movies template

packages/@sanity/form-builder/src/inputs/ImageToolInput/styles/ImageToolInput.css, packages/@sanity/imagetool/src/ImageTool.js, packages/@sanity/imagetool/src/styles/ImageTool.css
The fix in #636 made matters worse by making the crop/hotspot handles not respond to user input at all. This reverts it, and fixes it by setting min-width on the container instead.
(Also snuck in a little optimization that avoids a superfluous setState too)
=> [imagetool] Hotfix hotspot

packages/@sanity/form-builder/src/inputs/Slug/SlugInput.js, packages/@sanity/schema/src/legacy/types/slug.js, packages/test-studio/schemas/slugs.js, packages/test-studio/schemas/validation.js
Fix a bug where the uniqueness check of slugs fails because it is placed inside the path of an array, as well as the validation failing when placed directly inside of an array and not having a current value.
=> [schema] Fix validation of slugs in arrays

packages/@sanity/export/package.json, packages/@sanity/export/src/AssetHandler.js, packages/@sanity/export/src/export.js, packages/@sanity/export/test/AssetHandler.test.js, packages/@sanity/export/test/__snapshots__/AssetHandler.test.js.snap, packages/@sanity/export/test/helpers/index.js
There is a sporadic issue where downloaded assets are not correctly added to the exported archive, resulting in half-completed images and such. Obviously this has to be fixed ASAP. This PR ensures that assets are stored to the filesystem temporarily and added to the archive using a simpler method in the underlying library, which should prove more reliable.
I also managed to sneak in a fix for old asset IDs that don't follow the same document ID pattern that we use nowadays.
=> [export] Temporarily store files to filesystem before archiving

packages/@sanity/schema/src/legacy/types/slug.js, packages/@sanity/schema/src/legacy/types/utils.js, packages/test-studio/schemas/slugs.js
Note: This reveals some flaws in how we can provide default validation for core types and should be addressed separately. This is a hot-fix.
Fixes an issue where specifying your own validation rules for a slug field would override the built-in rules.
=> [schema] Fix combining slug validation rules with custom ones

packages/@sanity/base/src/styles/forms/text-input.css
For some reason an select is :read-only in some cases, and select inherits styling from text-input root.
=> [base] 50% opacity only affects text-input with readonly

packages/@sanity/client/README.md
As the title says. `filename` and  `contentType` options had no examples.
=> [client] Improve asset upload documentation examples

packages/@sanity/core/src/util/checkReactCompatibility.js
Since #639 has landed, we can now support React 16 🎉
This allows React 16 when running `sanity start`
=> [cli] Support react 16

packages/@sanity/cli/src/actions/init-project/initProject.js, packages/@sanity/cli/src/commands/init/initCommand.js, packages/@sanity/client/src/datasets/datasetsClient.js, packages/@sanity/core/src/commands/dataset/createDatasetCommand.js, packages/@sanity/core/src/commands/dataset/datasetVisibilityCommand.js, packages/@sanity/core/src/commands/index.js
This PR adds support for private datasets in four different parts:
- `@sanity/client` gets a new method to edit properties on existing datasets as well as specifying properties for new ones
- `@sanity/core` gets a new `sanity dataset visibility` command that can get and set the visibility mode
- `@sanity/core` now prompts for visibility mode when running `sanity dataset create`
- `@sanity/cli` prompts for dataset visibility mode when running `sanity init`
=> [cli] Add support for private datasets

packages/@sanity/cli/src/versionRanges.js
This will use v16 as default React version for new studios (prop-types is still on 15.6).
=> [cli] Use React 16 by default in new studios

package.json
After releasing 0.127.0, we had some issues with transitive depencies of `@sanity`-packages not being updated. I think it would be safer to always release with exact version deps.
=> [chore] Always publish with --exact

packages/@sanity/validation/src/Rule.js, packages/@sanity/validation/src/validate.js
Currently, custom validation functions are not run on undefined values, but there are cases where you might want to conditionally allow undefined values. This PR changes the default behavior (hey, it's an experimental feature) to always run custom validators on undefined values, unless `optional()` or `required()` is set. 
I've already updated the documentation to note that you should check for undefined values.
=> [validation] Run custom validators on undefined values unless rule is optional

packages/@sanity/image-url/src/builder.js, packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/urlForHotspotImage.test.js
When developing Sanity, we sometimes use a different host than `cdn.sanity.io`. This PR allows us to override the base url for generated URLs, and if the builder is instantiated with a client, infers it from the API URL.
=> [image-url] Allow specifying a baseUrl

packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.js, packages/test-studio/schemas/objects.js, packages/test-studio/schemas/recursiveObject.js, packages/test-studio/schemas/schema.js
This adds support for `options: {collapsible: boolean, collapsed: boolean}` for object types.
Additionally, it changes the default behavior, making objects on level (depth) 3 and above collapsible and collapsed by default.
If the default is overridden to be `{collapsible: false, collapsed: false}`, we still force-collapse when reaching level 10 and beyond (this is mainly to avoid infinite recursion on object types that have fields of its own type).
This requires doc updates on objects and fieldsets docs when released
=> [form-builder] Support collapsible objects with default limit

packages/@sanity/schema/src/legacy/types/slug.js, packages/@sanity/validation/src/inferFromSchemaType.js, packages/@sanity/validation/src/validators/slugValidator.js
This moves slug validation from the @sanity/schema package to the @sanity/validation package and makes it possible to import the @sanity/schema package without having a registered parts loader.
Also includes a few minor code cleanups (bf95bfd)
=> [validation] Move slug validation to @sanity/validation

packages/@sanity/form-builder/src/inputs/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.js, packages/@sanity/form-builder/src/sanity/inputResolver/resolveArrayInput.js, packages/test-studio/schemas/arrays.js
This is a workaround for a bug where array of primitive subtypes (e.g. `url`, `email`) did not resolve to the input for array of primitives.
=> [form-builder] Resolve array of primitives input for to array of primitive subtypes

packages/@sanity/cli/src/cli.js, packages/@sanity/cli/src/util/getUpgradeCommand.js, packages/@sanity/cli/src/util/mergeCommands.js, packages/@sanity/cli/src/util/updateNotifier.js, packages/@sanity/core/src/index.js, packages/@sanity/core/src/requiredCliVersionRange.js
Certain functionality and dependencies are shared between `@sanity/cli` and `@sanity/core`. For instance, we bundle a version of @sanity/client with the CLI which is then exposed to the CLI commands in `@sanity/core` to prevent having to bundle the dependency in both projects.
Sometimes when we add new functionality to @sanity/core, it thus implicitly depends on a given version range of `@sanity/cli`, which is not currently enforced and thus can lead to unexpected crashes because of incorrect assumptions.
This PR adds a feature to `@sanity/cli` that allows `@sanity/core` to declare a minimum CLI version requirement, and if it does not satisfy it, exit with an error telling the user to upgrade.
We'll still have to explicitly add checks in `@sanity/core` commands until we are sure most …
=> [cli] Allow @sanity/core to declare CLI version requirement

packages/@sanity/form-builder/src/PatchEvent.js, packages/@sanity/form-builder/src/sanity/utils/gradientPatchAdapter.js, packages/@sanity/form-builder/src/utils/patches.js
This adds support for creating `inc` and `dec` patches from the form-builder
- `inc(amount?: number, path?: Array)`
- `dec(amount?: number, path?: Array)`
For example:
```js
import PatchEvent, {inc, dec} from 'part:@sanity/form-builder/patch-event'
// ...
this.props.onChange(
PatchEvent.from([
inc(1, ['someField']),
dec(2, ['someOtherField'])
]))
)
```
=> [form-builder] Support inc + dec patches

packages/@sanity/desk-tool/src/pane/DocumentsPane.js, packages/@sanity/desk-tool/src/pane/Editor.js
Clicking on the "hamburger icon" in the desk tool currently does not allow *toggling*. That is, when it is open, it won't close when clicking the icon. This is because both the "click outside" and the "click" action happens. This PR stops propagation when handling the event, which seems to do the trick without breaking anything else as far as I can tell.
=> [desk-tool] Allow hamburger menus to be toggled

packages/@sanity/webpack-integration/package.json
v1 and v2 need it and it's not listed as a dependency
=> add postcss-url dependency to webpack-integration

packages/@sanity/import/src/importFromStream.js, packages/@sanity/import/src/util/getJsonStreamer.js
Because of the new "peek at the stream to see if it's an ndjson or a tarball" behavior, JSON parse errors were not being surfaced. With this PR we apply a separate error handler on the ndjson stream and reject if encountering any errors. Because the concatenation stream finishes prior to the pipeline callback, I had to slightly change the flow to assign the gathered JSON-documents to a variable and resolving only on pipeline completion.
=> [import] Fix JSON parse errors not being emitted

packages/@sanity/cli/src/commands/debug/debugCommand.js, packages/@sanity/cli/src/commands/debug/printDebugInfo.js, packages/@sanity/cli/src/util/clientWrapper.js
This PR makes the CLI read `SANITY_AUTH_TOKEN` environment variable for authentication purposes, making it easier for scripts and CI-environments to use the CLI tool.
=> [cli] Allow providing auth token through environment variable

packages/@sanity/storybook/package.json
Seems like `@storybook/react` has released a breaking change, or we're relying on some internal module exported by the package. Either way, the latest version gives the following error:
```
Storybook: module.js:540
throw err;
^
Error: Cannot find module '@storybook/react/dist/server/middleware'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (~/sanity/packages/@sanity/storybook/lib/server/server.js:7:20)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
```
Don't have time to investigate …
=> [storybook] Pin version of @storybook/react

packages/@sanity/components/package.json
Due to a regression in a recent patch release of popper.js (which we depend on through react-popper), the reference input suddenly stopped displaying hits (see #709).   
Related issue in react-popper here: souporserious/react-popper/issues/122
This fixes it by pinning the popper.js version.
=> [components] Pin version of popper.js (fixes #709)

packages/@sanity/core/package.json, packages/@sanity/core/src/commands/dataset/importDatasetCommand.js, packages/@sanity/import/src/import.js, packages/@sanity/import/src/importFromStream.js, packages/@sanity/import/src/uploadAssets.js, packages/@sanity/import/src/util/getHashedBufferForUri.js, packages/@sanity/import/src/util/getJsonStreamer.js, packages/@sanity/import/src/validateOptions.js, packages/@sanity/import/test/__snapshots__/import.test.js.snap, packages/@sanity/import/test/__snapshots__/uploadAssets.test.js.snap, packages/@sanity/import/test/helpers/helpers.js, packages/@sanity/import/test/import.test.js, packages/@sanity/import/test/uploadAssets.test.js, packages/@sanity/storybook/package.json
As the title says. I also snuck in a few fixes for an issue where the streams would not be destroyed when encountering an error, leading to unnecessary work and API requests.
=> [core] Allow importing datasets from directory 

packages/@sanity/base/src/components/Document.js, packages/@sanity/core/src/actions/build/buildStaticAssets.js, packages/@sanity/default-layout/src/components/DefaultLayoutContainer.js, packages/@sanity/default-layout/src/datastores/urlState.js, packages/@sanity/default-layout/src/defaultLayoutRouter.js, packages/@sanity/server/src/baseServer.js, packages/@sanity/server/src/configs/webpack.config.dev.js, packages/@sanity/server/src/configs/webpack.config.js, packages/@sanity/server/src/devServer.js, packages/@sanity/server/src/util/getStaticBasePath.js
When building a studio for use outside of development and `sanity.studio`-context, you might want not want to host it at the root of a domain name. In order to allow for this, we need to:
- Make the CLI tool build an index file containing paths to static files that is not always fixed to `/static`
- Make the studio aware of the base path, prefixing the routes with it
- Make it possible to customize the base path through configuration
This PR implements the above, and also (for consistency) makes the development server use the same base path. I felt this would make it easier to debug routing issues, among other things.
Using it is as simple as adding a `basePath` property under the `project` object in `sanity.json`:
```js
{
// ...
"project": {
"name": "Movies studio",
"basePath": "/studio" …
```
=> [server] Allow specifying a basePath for a studio

packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/parseSource.test.js
According to documentation `image(source)` "Accepts either a Sanity image record, an asset record, or just the asset id as a string."
`@sanity/image-url` from master works only when whole Sanity image record is passed. For an asset record it is returning `null` and for asset id as string (`_ref`) is trowing an exception.
=> [image-url] Fix parsing image source

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderBlock.js
Fixes a bug where an insert dialog in block editor is too wide on mobile, and makes it clip
=> [form-builder] Min width causes image dialog to fail

packages/@sanity/validation/src/validators/objectValidator.js
This will ensure that the reference search dialog is opened
=> [validation] Include $ in path on reference validation errors

packages/@sanity/core/package.json, packages/@sanity/core/src/actions/exec/configClient.js, packages/@sanity/core/src/actions/exec/execScript.js, packages/@sanity/core/src/commands/exec/execCommand.js
With this PR, you can use the `--with-user-token` option when running `sanity exec` to easily be able to import a preconfigured, authenticated client from `part:@sanity/base/client`.
=> [core] Add `--with-user-token` flag for exec command

packages/@sanity/cli/src/util/updateNotifier.js
In certain edge cases, we displayed a prompt telling the user that an upgrade was available when it actually wasn't. This PR checks whether we have a diff in the versions before prompting.
=> [cli] Don't show upgrade prompt on same version

packages/@sanity/form-builder/src/sanity/utils/gradientPatchAdapter.js
This fixes a bug causing an error when form builder code expected the recieved patch to include a path property.
Fixed it by filtering out the `ifRevisionID`-field from received patches and not treating `ifRevisionID` as a kind of patch.
=> [form-builder] Fix bug causing form-builder to fail on patches w/ifRevisionID

packages/@sanity/schema/src/sanity/validation/types/object.js
This fixes #434 by disallowing dash and whitespace from field names.
=> [schema] Make sure field name regex fail on dash and whitespace

packages/@sanity/validation/src/validators/stringValidator.js
Invoking `new URL(<insert valid url here>, undefined)` in Safari always throws an error.
=> [validation] Fix wrong URL constructor invocation. Fixes #751

packages/@sanity/core/src/actions/start/startAction.js
We used to have an option for running the "production build" of a built Sanity studio. This is seldom if ever used, and is not documented anywhere. This PR removes the functionality since it has been out of order for a good number of versions.
=> [core] Remove production server option from start command

packages/@sanity/preview/src/components/PreviewSubscriber.js, packages/@sanity/preview/src/constants.js, packages/@sanity/preview/src/prepareForPreview.js, packages/test-studio/schemas/invalidPreviews.js, packages/test-studio/schemas/schema.js
This will prevent the studio from crashing if preview config targets values that cannot be handled by the preview component (e.g. `{title: {foo: 'bar'}}`). It will show a warning in stead of the placeholder preview, and provide a detailed explanation in the developer console.
=> [preview] Tolerate invalid values returned from preview config and provide helpful errors

packages/@sanity/cli/src/actions/yarn/yarnWithProgress.js
Currently `sanity init` fails on Node 10 due to a thirdparty dependency that has `node < 10` set in its engines field.
This fixes it by running yarn with the `--ignore-engines` flag the engines field when resolving dependencies in new projects.
=> [cli] Run yarn with --ignore-engines when resolving dependencies

packages/@sanity/cli/src/actions/yarn/yarnWithProgress.js, packages/@sanity/cli/src/scripts/package-yarn.js
npm is working towards being [GDPR compliant](https://twitter.com/seldo/status/989637189259612160) by May 25th. I have yet to hear if yarn has any changes planned for their registry.
While our long term plan will probably be to replace yarn with npm, for now this will tell yarn to use the npm registry, minimizing the number of external providers we touch during a `sanity init`/`sanity upgrade`.
=> [cli] Use npm registry for modules. Upgrade yarn to 1.6.0

packages/@sanity/form-builder/src/inputs/FileInput/FileInput.js
Currently they are served using `Content-Disposition: inline`, so even with a `download` attribute it may be up to the browser whether or not they are actually downloaded or displayed inline.
=> [form-builder] Use `dl`-param on download to trigger attachment disposition

packages/@sanity/desk-tool/src/pane/Editor.js
This fixes a bug that could cause the published document to get overwritten by an empty draft when publishing using the hotkey.
=> [desk-tool] Prevent empty draft from overwriting published document

packages/@sanity/plugin-loader/loader.js, packages/@sanity/plugin-loader/test/loader.test.js
Sometimes you are running scripts which utilize the parts system, but you don't need the class names of the CSS modules referenced by any imports. This PR adds a `stubCss` option to skip the overhead of PostCSS compilation.
=> [plugin-loader] Add option to stub CSS loading

packages/@sanity/cli/src/actions/versions/findSanityModuleVersions.js, packages/@sanity/cli/src/commands/upgrade/upgradeDependencies.js
Two fixes:
- When running `sanity upgrade`, it previously included `@sanity/cli` in the output, which was very misleading.
- When running `sanity upgrade`, we've encountered an inexplicable bug where yarn will upgrade the lockfile with the resolved tarball URL and version, but will somehow not extract and replace the installed module. With `dce1716`, we will _delete_ the modules that need to be upgraded before actually running `yarn` to work around this bug.
This once again puts some further pressure on prioritizing #716
=> [cli] Delete Sanity-modules that needs upgrading to work around yarn bug

packages/@sanity/components/package.json, packages/@sanity/components/src/buttons/DropDownButton.js, packages/@sanity/components/src/dialogs/PopOver.js, packages/@sanity/components/src/selects/StatelessSearchableSelect.js, packages/@sanity/components/src/selects/StyleSelect.js, packages/@sanity/components/src/selects/styles/StyleSelect.css
- Fixing style select (the one in block editor)
- Using official react-popper
=> Styleselect and official react popper

packages/@sanity/base/src/styles/layout/tippy.css, packages/@sanity/code-input/src/CodeInput.js, packages/@sanity/code-input/src/Fieldset.css, packages/@sanity/components/src/dialogs/styles/DefaultDialog.css, packages/@sanity/components/src/textareas/styles/DefaultTextArea.css, packages/@sanity/default-layout/src/components/styles/RenderTool.css, packages/@sanity/desk-tool/src/components/InspectView.js, packages/@sanity/desk-tool/src/components/styles/InspectView.css, packages/@sanity/desk-tool/src/pane/styles/Editor.css, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ItemValue.css, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/styles/BlockEditor.css
- Dialog now has a min-width
- Array input sets its min-width of the content in dialog
- Composable CSS to use when components wants to make the dialog bigger
- Max-width on editor in desk-tool to prevent too wide inputs
=> Responsive dialogs width

packages/@sanity/form-builder/src/inputs/ArrayInput/ItemValue.js
This is a twofold change:
1. When the user closes an edit dialog and the edited item value is "empty", the item will now be removed from the array. This is a partial fix for #727 and #725, and should make it a lot less annoying. I suggest we still keeps those issues open, as the problems still exists to a lesser extent (e.g if the browser window closes, network disconnects, etc.).
2. Passing `undefined` as `value`-prop to the input for "empty" placeholder array items. When making a form builder input, a check for undefined should be enough in order to determine if the input has a value or not. In the case of object types contained in an array, the input will currently be passed the placeholder value (e.g. `{_key: 'adebee222'}`, and any _has value_ check inside the input component easily …
=> [form-builder] Remove empty values when array dialog closes and pass undefined as item values if empty

packages/@sanity/google-maps-input/src/GeopointInput.js, packages/test-studio/schemas/geopoint.js
The Google Maps Input emitted a `set`-patch overwriting the whole value on change, causing any `_key`-property to be cleared for each edit. As a consequence, editing geopoints in an array did not work very well.
This makes the Google Maps input emit a `setIfMissing` + `set` patches targeting the `lat`+`lng`-fields.
=> [google-maps-input] Don't overwrite value, just set lat/lng

packages/test-studio/package.json, packages/test-studio/schemas/customInputs.js, packages/test-studio/src/components/AuthorReferenceInput.css, packages/test-studio/src/components/AuthorReferenceInput.js
This PR adds an example of how to create a custom input for the reference type. Kind of simple and naive, but should explain the basics clear enough.
=> [test-studio] Add custom reference input example

packages/@sanity/image-url/package.json, packages/@sanity/image-url/src/builder.js, packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/.eslintrc, packages/@sanity/image-url/test/builder.test.js, packages/@sanity/image-url/test/fixtures.js, packages/@sanity/image-url/test/parseSource.test.js, packages/@sanity/image-url/test/urlForHotspotImage.test.js
In certain situations, it might be easier to specify transformation parameters using the actual query string parameters which you see in image URLs instead of using the more user-friendly versions exposed by the image url module.
An example would be when you parse an existing image URL and want to apply additional parameters. This PR allows using either form.
I also took the liberty of converting the tests from mocha to jest and raised the test coverage in certain areas.
=> [image-url] Allow using actual query parameters instead of aliases 

packages/@sanity/schema/src/legacy/types/reference.js, packages/@sanity/schema/src/legacy/types/slug.js
The reference and slug types were missing their fields. If the default input component was not in play, the form builder would not render any input/field. The validation infrastructure also traverses the schema definition, and missing fields will prevent it from functioning as intended.
An interesting thought would be whether or not we should add fields to the document type as well, for `_id`, `_type`, `_createdAt` etc. They could be marked as hidden and read only, but it would make schema traversal more complete/correct. Thoughts?
=> [schema] Add missing fields for reference and slug types

packages/@sanity/default-layout/src/components/UpdateNotifierDialog.js
The previous copy assumed contextual knowledge of the CLI, this text makes it a bit clearer.
=> [cli] Make upgrade message less confusing

packages/@sanity/components/src/lists/grid/styles/GridList.css, packages/@sanity/components/src/previews/MediaPreview.js, packages/@sanity/components/src/previews/styles/MediaPreview.css, packages/@sanity/components/src/progress/ProgressCircle.js, packages/@sanity/components/src/progress/story.js, packages/@sanity/form-builder/src/inputs/ArrayInput/ItemValue.js, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ConfirmButton.css, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ItemValue.css, packages/@sanity/preview/src/components/SanityDefaultPreview.js
- adding progress to grid view (thumbnails)
- Cleaning up circle preview
- Styling fallback icon
Think it is safe include `options: {layout: 'grid'}` in the documentation now.
=> Fix array grid view

packages/@sanity/base/package.json, packages/@sanity/components/package.json, packages/@sanity/core/src/util/checkReactCompatibility.js, packages/@sanity/default-layout/package.json, packages/@sanity/desk-tool/package.json, packages/@sanity/form-builder/package.json, packages/@sanity/google-maps-input/package.json, packages/@sanity/imagetool/package.json, packages/@sanity/preview/package.json, packages/@sanity/server/package.json, packages/@sanity/state-router/package.json, packages/@sanity/vision/package.json
It's hard to track usage of React 16 specific features in our own code base, especially since we develop against React 16.2, so lets officially drop support for React < v16.2.
It should be safe to do this as using React 15 with sanity studios has yielded an upgrade warning since v0.127.0.
Side note: since we still officially support React 16.2 we should be careful not to use features introduced in React after 16.2.
=> [chore] Drop support for React 15

packages/@sanity/image-url/src/parseAssetId.js, packages/@sanity/image-url/src/parseSource.js, packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/__snapshots__/parseAssetId.test.js.snap, packages/@sanity/image-url/test/builder.test.js, packages/@sanity/image-url/test/fixtures.js, packages/@sanity/image-url/test/parseAssetId.test.js, packages/@sanity/image-url/test/parseSource.test.js
As requested in #800.
Also took the liberty of splitting some logic into separate files and increasing test coverage for a bunch of cases.
=> [image-url] Allow passing asset documents as source

packages/@sanity/cli/src/util/mergeCommands.js
E.g. `0.131.0-alpha.7b4bcb14` --> `0.131.0`
=> [cli] Coerce @sanity/core version string before performing satisfaction check

packages/@sanity/preview/src/prepareForPreview.js, packages/test-studio/schemas/numbers.js, packages/test-studio/schemas/slugs.js
This fixes a bug introduced in 0.130.0 triggering preview errors when having numbers (and null/undefined) on preview fields. This should be allowed as all of these can be rendered by React just fine (as React will coerce values of these types strings/nothing).
This also removes an example schema that had a React element set on one of its preview fields. Not sure about the value of keeping this "feature", and for the sake of simplicity I suggest we remove it for now (actually, the support for it was removed in the previous release, it was possible "by accident" and has never been documented)
=> [preview] Don't fail on numbers, booleans and empty values

packages/@sanity/form-builder/src/inputs/ArrayInput/ItemValue.js
After #780 we remove empty values when the user closes the "edit item"-dialog. Since it doesn't make sense to remove the value when it's empty any more, I'm hiding the "Delete"-button it when value is empty, and instead showing a "Cancel"-button
I noticed the rightmost button is "jumping" when the leftmost button appears/disappears. Maybe you could have a look at it, @kristofferj ?
=> [form-builder] Show cancel and hide delete buttons if edited item is empty

packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayInput.js
Currently drag + drop to upload multiple files to an array did trigger opening the edit dialog for the _last_ newly added item, which was a bit strange and confusing. This fixes it by only appending items.
=> [form-builder] Don't open edit dialog for uploaded items

packages/@sanity/desk-tool/package.json, packages/@sanity/vision/package.json
Since the official react-json-inspector now supports react 15 and above, there is no need to depend on an unofficial branch anymore.
=> [chore] Upgrade react-json-inspector

packages/@sanity/default-layout/src/defaultLayoutRouter.js, packages/@sanity/server/src/baseServer.js, packages/@sanity/server/src/util/getStaticBasePath.js, packages/@sanity/util/src/reduceConfig.js
Solves #817 
Better than specifying it in the cli as I did in #818 , as basePath is used in files that aren't referring to cli flags (throw that PR away)
=> [core] Add ability to override project basePath option with an environment variable

packages/@sanity/components/src/panes/SplitController.js
Switching to responsive when resizing browser. This is nice when developing.
Before it was necessary to refresh the browser.
=> [components] Switch to mobile on resize. No need to refresh browser

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/ItemForm.js, packages/test-studio/schemas/blocks.js
This fixes a bug causing editing of inline objects to crash
=> [form-builder] Use FocusManager with inline items

packages/@sanity/components/src/buttons/createButtonLike.js, packages/@sanity/form-builder/src/inputs/ArrayInput/ConfirmButton.js
All our buttons have an inner span with `tabIndex={-1}`. This makes the span receive focus on clicks before the button, and messes with the order the button itself receives focus/blur/click events. Currently when clicking a button, `onblur` is triggered on the button before `onclick` because the inner span receives focus first.
This made the "confirm delete button" on array items break as it had an `onBlur` trigger that closed it. Since onBlur was triggered when the inner span received focus, the confirm popup with the button inside got closed before the click event got triggered on the button at all.
The `tabIndex` on the inner span was there in the first place to be able to differentiate button styling based on whether focus came from tabbing into it, or from clicking on it.
I'll have …
=> [components] Prevent inner element in button from stealing focus

packages/@sanity/core/src/commands/dataset/createDatasetCommand.js, packages/@sanity/core/src/commands/dataset/deleteDatasetCommand.js
The `--visibility` flag was broken on `sanity dataset create`. In addition, I added a basic filter to trim whitespace when confirming dataset deletes since its hard to see whitespace in the terminal.
=> [core] Fix visibility mode flag on dataset creation

packages/@sanity/preview/src/utils/fromEvent.js
I'm attempting to run some tests in a JSDom environment, and the warning is causing some noise.
=> [preview] Log EventListenerOptions warning only in development mode

packages/@sanity/preview/components.js, packages/@sanity/preview/src/components/ObserveForPreview.js, packages/@sanity/preview/src/components/PreviewSubscriber.js, packages/@sanity/preview/src/components/WithVisibility.js
This is a refactor of the existing PreviewSubscriber component, which is now split it into two different components.
Exposes a new `WithVisibility` component that will call its child function component with a boolean value indicating whether the component is on screen or not, e.g:
```jsx
<WithVisibility>
{isVisible => isVisible ? 'Component is visible' : 'Component is hidden'}
</WithVisibility>
```
This could probably be promoted to an official API building block at some point, but let's just keep it in here for now.
=> [preview] Refactor and expose WithVisibility helper component

packages/@sanity/import/src/serializePath.js
While this generally shouldn't be used, there are cases where someone creates an object with numeric keys:
```json
{
"0": {
"_type": "foo",
"text": "moo"
},
"1": {
"_type": "foo",
"text": "moo"
}
}
```
The import module currently serializes this to something along the lines of `body.0.text`, but this is not an allowed path. Instead, we need to use `body["0"].text`.
=> [import] Fix serialization of numeric object keys

packages/@sanity/image-url/src/parseSource.js, packages/@sanity/image-url/test/fixtures.js, packages/@sanity/image-url/test/parseSource.test.js
This PR allows the image url module to parse the following formats:
```
"https://cdn.sanity.io/images/projectId/datasetName/someImageFilename-200x200.jpg"
```
```json
{
"asset": {
"url": "https://cdn.sanity.io/images/projectId/datasetName/someImageFilename-200x200.jpg"
}
}
```
=> [image-url] Support parsing asset objects with only URL

packages/@sanity/server/src/configs/webpack.config.js, packages/test-studio/src/components/PertEstimate.css, packages/test-studio/src/components/PertEstimateInput.js
Needs discussion.
We've talked about having an "escape hatch" for using third party components with styling. Currently, importing CSS will always assume you want CSS modules, which doesn't work when people hardcode class names.
Probably we should find or create a postcss plugin which allows you to write a CSS module file (`thatPlugin.css`) with something like the following:
```css
@import-with-class-prefix('react-that-plugin/styles.css', 'container')
```
Which will find all selectors in the file and prefix them with a (CSS-module) class name:
```css
.thatPlugin_container_lkk7x .thatPlugin .datePicker { /* ... */ }
```
Which you can then use in your plugin:
```js
import ThatPlugin from 'react-that-plugin'
import styles from './thatPlugin.css'
export default () => (
<div …
```
=> [server] Allow importing CSS with ?raw to bypass CSS modules

.drone.yml
This adds a drone build that will deploy the test-studio when new changes are pushed to `next`. We could in theory keep this in Travis, but I feel slightly safer keeping credentials in Drone.
I'm not sure what the deal should be regarding publishing of a `next` release. Should it be done on every single commit? Should it be need to be tagged somehow? I don't know how npm behaves when you have a gazillion published releases. Thoughts?
=> [chore] Add Drone CI

packages/@sanity/components/src/dialogs/PopOver.js, packages/@sanity/components/src/dialogs/styles/PopOver.css, packages/@sanity/form-builder/src/inputs/ArrayInput/ConfirmButton.js, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ConfirmButton.css
Fixes a bug where safari trigged blur (that closed the confirmButton dialog) before the onClick action fire.
=> Fix confirm button

packages/@sanity/core/src/commands/dataset/exportDatasetCommand.js, packages/@sanity/core/src/commands/dataset/importDatasetCommand.js
The `sanity dataset import` and `sanity dataset export` commands had left out the `dataset` part from the help text/examples.
=> [core] Fix missing 'dataset' prefix in import/export help

packages/@sanity/base/src/schema/types/imageAsset.js, packages/@sanity/form-builder/src/inputs/FileInput/FileInput.js, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.js, packages/@sanity/form-builder/src/sanity/inputs/client-adapters/assets.js, packages/@sanity/form-builder/src/sanity/uploads/typedefs.js, packages/@sanity/form-builder/src/sanity/uploads/uploadFile.js, packages/@sanity/form-builder/src/sanity/uploads/uploadImage.js, packages/@sanity/form-builder/src/sanity/uploads/uploaders.js, packages/@sanity/schema/src/sanity/validateSchema.js, packages/@sanity/schema/src/sanity/validation/createValidationResult.js, packages/@sanity/schema/src/sanity/validation/types/file.js, packages/@sanity/schema/src/sanity/validation/types/image.js, packages/test-studio/schemas/images.js
This PR allows users to specify which metadata the server should attempt to extract on a per-field basis. Some information on this here: https://www.sanity.io/help/asset-metadata-field-invalid
Asset documentation should be updated to include more examples and information on which metadata is available for extraction, but I think this is a good start.
=> [form-builder] Allow specifying metadata to extract for images/files

packages/@sanity/components/src/dialogs/styles/DefaultDialog.css, packages/@sanity/google-maps-input/styles/GeopointInput.css
Just a small fix in addition to #864 where the max-height is different based on if the dialog has functions or not
=> [components] Dialog with functions height fix

packages/@sanity/cli/package.json, packages/@sanity/cli/src/util/updateNotifier.js
The update notifier has a max time it'll wait for a latest version reply, but it is totally useless at this point since it waits for the reply without actually using it. This PR implements the _intended_ behavior.
=> [cli] Make update check actually respect timeout

packages/@sanity/form-builder/src/inputs/InvalidValueInput/InvalidValueInput.js, packages/@sanity/form-builder/src/inputs/ObjectInput/Field.js
This fixes a bug in the invalid value warning input that could sometimes cause an error saying `Uncaught TypeError: Cannot read property 'focus' of undefined`
=> [form-builder] Let InvalidValueInput be focusable like any other input

packages/@sanity/validation/package.json, packages/@sanity/validation/src/util/promiseLimiter.js, packages/@sanity/validation/src/validate.js
The concurrency limitation in the validation is causing stalled validation jobs and is probably a premature optimization without a thought-through implementation, so removing it for now seems like the best choice.
=> [validation] Remove promise concurrency limitation for now

packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.js, packages/test-studio/schemas/validation.js
The reference input was not showing markers or validation errors as other inputs did. This passes the appropriate markers and errors on to the right components.
=> [form-builder] Show validation status in reference inputs

packages/@sanity/client/src/data/dataMethods.js, packages/@sanity/client/test/client.test.js
This fixes #889 - transactions were not called `serialize()` on and this resulted in incorrect JSON.
It also fixes a regression introduced by #768 where transaction IDs would not be passed correctly.
=> [client] Fix passing clientless transaction to mutate(). Fixes #889

packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.js, packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.js
This optimises the query generated when the user opens the reference search dropdown with an empty search term. Previously we generated a filter that matched `**` on all text fields on possible referenced types. This PR fixes it by only constraining on referenced types.
=> [form-builder] Optimize reference search query

packages/@sanity/components/src/lists/default/List.js, packages/@sanity/components/src/lists/default/ListItem.js, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ArrayInput.css
This has not been picked up until now, since the css build added the grid-class later. Since this got the same specificity, we can not control it. The fix is to not set the defaultClass in array-input, but use the defaultList css in the defaultList component.
=> [form-builder] Not send inn the defaultList class in arrayInput

appveyor.yml
This PR adds Appveyor as a CI platform, which allows us to run tests on Windows.
=> [chore] Run tests on Appveyor

packages/@sanity/cli/templates/clean/schemas/schema.js
Switch from CommonJS to ESM in the clean template schema in order to align with the documentation and other templates.
=> [cli] Use ESM for clean template schema

packages/@sanity/image-url/src/parseSource.js, packages/@sanity/image-url/test/fixtures.js, packages/@sanity/image-url/test/parseSource.test.js, packages/@sanity/image-url/test/urlForHotspotImage.test.js
Allows using things like:
```js
{
_type: 'image',
asset: {
_id: 'image-Tb9Ew8CXIwaY6R1kjMvI0uRR-2000x3000-jpg',
_type: 'sanity.imageAsset',
url: 'https://cdn.sanity.io/images/ppsg7ml5/test/Tb9Ew8CXIwaY6R1kjMvI0uRR-2000x3000.jpg'
},
crop: {
bottom: 0.1,
left: 0.1,
right: 0.1,
top: 0.1
},
hotspot: {
height: 0.3,
width: 0.3,
x: 0.3,
y: 0.3
}
}
```
=> [image-url] Allow using materialized assets

packages/@sanity/core/src/actions/start/startAction.js, packages/@sanity/core/src/commands/start/startCommand.js
Suggestion for some alternative wording at startup. We want to be clearer about what you're running locally, i.e. the Content Studio. Ideally, we could add wording about `the studio being connected to the project ${projectId} and the ${dataset} dataset through the Sanity API`, but I was not sure how to get to the configuration in startAction.js
=> [core] More helpful CLI messages

packages/@sanity/desk-tool/src/pane/DocumentsPane.js, packages/test-studio/schemas/author.js, packages/test-studio/schemas/book.js
This fixes #908 by making sure we join in any referenced fields targeted by the ordering config.
E.g.
```*[_type == 'book'] | order(author.name asc) {_id, _type}```
gets rewritten as
```*[_type == 'book'] {_id, _type, author -> {name}} | order(author.name asc) {_id, _type}```
=> [desk-tool] Support ordering by fields on referenced documents.

packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayInput.js, packages/@sanity/form-builder/src/inputs/ArrayInput/ItemValue.js, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ArrayInput.css, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ItemValue.css, packages/@sanity/form-builder/src/inputs/common/Details.js
This makes the array input tolerate items that is missing `_key`, and provides a way for the user to fix it from within the content studio UI.
=> [form-builder] Tolerate missing keys and provide a way of fixing

packages/@sanity/image-url/package.json, packages/@sanity/image-url/src/parseSource.js, packages/@sanity/image-url/test/__snapshots__/builder.test.js.snap, packages/@sanity/image-url/test/builder.test.js, packages/@sanity/image-url/test/urlForHotspotImage.test.js
This fixes an error that happened if image url builder was passed an image with either `hotspot` or `crop` but not both.
While I was at it, I took the liberty to upgrade jest (which fixes the notorious `SecurityError: localStorage is not available for opaque origins`- error) and switched to using jest snapshots instead of hard coded expected return values.
=> Fix image url error when missing crop or hotspot

packages/@sanity/eventsource/package.json
The current `eventsource` dependency has an issue when unicode sequences are split across multiple chunks. I've fixed the issue and published a new version.
=> [eventsource] Upgrade EventSource dependency with unicode fix

packages/@sanity/cli/src/actions/init-project/initProject.js
For some obscure reason, when using `fse.readdir()` where it returns `ENOENT`, the whole process would just silently crash/exit on windows with no meaningful error. I'll try to debug the problem in more depth, but for now I've switched to using plain old `fs.readdirSync()` which seems to work fine.
Edit: I also snuck in a few readability tweaks, and most importantly fixed a bug where when specifying `--dataset` it would still prompt for dataset visibility when the dataset already exists, which makes no sense.
Also the `--output-path` flag would only work in unattended mode, but will now work regardless.
=> [cli] Fix validation check that would silently crash on windows

packages/@sanity/form-builder/src/sanity/inputResolver/resolveArrayInput.js, packages/test-studio/schemas/arrays.js, packages/test-studio/schemas/schema.js
This fixes a bug that resolved the array-of-primitives-input to be resolved for "root level" array types (even if they contained non-primitive types).
=> [form-builder] Fallback to default array input when resolving

packages/@sanity/vision/src/css/visionGui.css
When in Vision (`/vision`), the background label is selectable which interfere with selection of QUERY and text from RESULT.
This PR fixes this. Although I have tested in our Content Studio running locally. I can not test it in this repo since I don't have a login. I'm not sure if I'm suppose to add our own `sanity.json` to this repo when contributing. Would be nice if the [Contributing guide](https://github.com/sanity-io/sanity/blob/master/CONTRIBUTING.md) would specify what the requirements are for running this repo locally.
=> [vision] Fixing background label being selectable (.inputLabelQuery)

packages/@sanity/client/README.md, packages/@sanity/client/src/data/patch.js
We want to remove the `merge` patch operation at some point in the future. For now, I figured it would be smart to log a warning when the patch is used.
I've also added documentation for the patch operations that were not present in the README.
=> [client] Deprecate merge patch

packages/@sanity/check/package.json, packages/@sanity/date-input/package.json, packages/@sanity/document-window/package.json, packages/@sanity/generate-help-url/package.json, packages/@sanity/storybook/package.json, packages/@sanity/validation/package.json, packages/@sanity/webpack-integration/package.json, packages/ecommerce-studio/package.json, packages/movies-studio/package.json
I noticed a few projects did not have a clean task, so their `lib` folder didn't get removed on `npm run clean`. This fixes that.
=> [chore] Add missing clean tasks

packages/@sanity/form-builder/src/FormBuilderContext.js, packages/@sanity/form-builder/src/inputs/BooleanInput.js, packages/@sanity/form-builder/src/inputs/EmailInput.js, packages/@sanity/form-builder/src/inputs/NumberInput.js, packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.js, packages/@sanity/form-builder/src/inputs/SelectInput.js, packages/@sanity/form-builder/src/inputs/Slug/SlugInput.js, packages/@sanity/form-builder/src/inputs/StringInput.js, packages/@sanity/form-builder/src/inputs/TagsArrayInput.js, packages/@sanity/form-builder/src/inputs/TelephoneInput.js, packages/@sanity/form-builder/src/inputs/TextInput.js, packages/@sanity/form-builder/src/inputs/UrlInput.js
This removes forwarding of props to the underlying input component. I'd rather prefer us to be explicit about the props we'd like to forward (both in order to state intent, and to avoid causing unnecessary warnings about non-supported props passed to underlying native dom elements).
It _should_ be safe, but can potentially break stuff, so we should keep this in mind if we get error reports on something related to inputs not receiving expected props (I've also tested pretty thoroughly, and everything looks fine).
=> [form-builder] Don't blindly forward props to wrapped input components

packages/@sanity/form-builder/src/FormBuilderContext.js
Fixes an annoying warning if, for some reason, the schema prop is not an instanceof the schema constructor (this may be a symptom of the schema package being included as two separate packages in the studio and worth investigating separately, but since things still would work, there's no reason to include this warning).
=> [form-builder] Don't check propType using instanceOf

packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.js
This makes it possible to _narrow_ the reference search by adding more words/search terms.
=> [form-builder] Use && for each term when searching for references

packages/@sanity/schema/src/legacy/ordering/guessOrderingConfig.js, packages/test-studio/schemas/typeWithNoToplevelStrings.js
When creating a default sort order in the studio, we looked for fields on the document type that was named either `title`, `name`, `label`, `heading`, `header`, `caption` or `description`, and assumed they were primitive fields that could be included in an order clause.
This assumption turns out to be wrong in many cases, so this PR includes a check to ensure the candidate fields are also primitives.
=> [schema] Make sure we don't create fallback order config for non-primitive field types

packages/@sanity/default-layout/src/components/Search.js
This makes sure we send the search terms as parameters instead of inlining in query string, which fixes an escaping issue that caused the search to produce an invalid query (when typing `'`). As a bonus, the size of the search payload will also be reduced.
=> [default-layout] Pass search terms as params

packages/@sanity/image-url/src/builder.js, packages/@sanity/image-url/src/parseSource.js, packages/@sanity/image-url/src/urlForImage.js
Replaces all the uses of `Object.assign` with object rest spread (which babel compiles down to something else), adding support for older versions of IE.
=> [image-url] Use object rest spread instead of Object.assign

packages/@sanity/form-builder/src/inputs/BooleanInput.js, packages/@sanity/form-builder/src/inputs/EmailInput.js, packages/@sanity/form-builder/src/inputs/NumberInput.js, packages/@sanity/form-builder/src/inputs/SelectInput.js, packages/@sanity/form-builder/src/inputs/Slug/SlugInput.js, packages/@sanity/form-builder/src/inputs/StringInput.js, packages/@sanity/form-builder/src/inputs/TagsArrayInput.js, packages/@sanity/form-builder/src/inputs/TelephoneInput.js, packages/@sanity/form-builder/src/inputs/TextInput.js, packages/@sanity/form-builder/src/inputs/UrlInput.js
I noticed that #942 accidentally broke focus handling in certain cases by not passing `onFocus` to the actual input component.
It's not super critical from what I can tell, so lets merge it into next for now (and instead cherry-pick it  into a hotfix if it turns out otherwise).
=> [form-builder] Make sure we pass down onFocus to wrapped input components

packages/@sanity/desk-tool/src/pane/DocumentsPane.js, packages/test-studio/schemas/book.js
The fix in #908 did not consider fields on deeper levels, e.g. `image.asset.size`. This fix ensures we support this too.
=> [desk-tool] Support order by reference fields on level > 1

packages/@sanity/reflector-client/.babelrc
...since it is/might be used outside of studio context
=> [reflector-client] Use IE9 as babel target

packages/@sanity/image-url/src/parseAssetId.js
`Number.isFinite` is not defined in IE11 and below, so use the global form instead
=> [image-url] Use global form of isFinite

package.json, packages/@sanity/image-url/package.json, packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/__snapshots__/builder.test.js.snap, packages/@sanity/image-url/test/builder.test.js
Certain crops produced source rectangle parameters where the top/left coords were negative, which obviously won't work. This PR fixes this by ensuring we won't go below 0.
Also had to upgrade/install some dependencies to get the image url tests to work with Babel 7, apologize for not moving that commit to a separate PR.
=> [image-url] Fix negative top/left crop in certain crops

packages/@sanity/server/src/configs/babel-env-config.js
We currently have an issue where if you combine `import` statements and `module.exports`, things seem to break. This PR might prevent tree shaking from working properly, but at least does not crash peoples studios.
=> [server] Make babel use CommonJS modules

packages/@sanity/desk-tool/src/components/DocumentPaneItemPreview.js
Currently, if you have a document list item and have not assigned a title explicitly, you will end up with `Untitled` as the title, since the spread operator overrides `title` in the fetched value with an `undefined` value for the same property.
This PR changes this so that only _defined_ values are overriden. This fixes the above issue while allowing an explicitly defined title to have precedence over the value in the document.
=> [desk-tool] Prefer assigned titles over document titles when both exist

packages/@sanity/components/src/panes/DefaultPane.js
Currently, we are not passing the actual action to the menu action handler, so it's hard to do anything helpful with it. This PR fixes action handlers in custom desk tool panes.
=> [components] Pass action item to menu action handler

packages/@sanity/client/src/data/listen.js, packages/@sanity/client/src/util/once.js
The EventSource implementation in browsers does not allow specifying headers, so to help people debug unexpected issues, this will warn in the browser when calling client.listen(..) and the Sanity client is configured with a token.
=> [client] Warn about using a token with listeners in the browser

packages/@sanity/desk-tool/src/components/DocumentPaneItemPreview.js
The fix in 84e972bea709c0ce358dcabd5349f1fda7ad3ad8 incorrectly assumed that DocumentPaneItemPreview would be passed a value with a "normalized id" (e.g. the id of the published document, without the `draft.`-prefix), which caused the list item to signal "missing document" after publish. This fixes it by using id utils to ensure the correct ids when listening for events on draft/published version of the document.
=> [desk-tool] Make sure DocumentPaneItemPreview listens on correct draft/published ids

packages/@sanity/base/src/datastores/settings/backends/localStorage.js, packages/@sanity/base/src/datastores/settings/backends/memory.js, packages/@sanity/base/src/datastores/settings/backends/resolve.js, packages/@sanity/base/src/datastores/settings/settingsStore.js, packages/@sanity/desk-tool/src/pane/DocumentsListPane.js
This includes a small refactor of the settings store so that changes in keys can be subscribed to. It fixes a regression from the structure feature that broke persisting of sort order/layout for document lists.
I also refactored out the localStorage/noop storage parts into a more generic concept of "storage backends", (of which `localStorage` is just one of several possible), and replaced the noop store with an in-memory storage that we fall back to if localStorage is not supported. Hope it's not too overengineered 😅 
Note: I also took the liberty of removing the `clear()`-method for now, as it's not currently needed. It should be pretty trivial to add later.
=> [base] Make settings store observable + integrate with DocumentsListPane

packages/@sanity/structure/src/documentTypeListItems.ts
For instance, when editing a `book` from a navigation structure using a document type list, if you navigate to an intent for an author, the document list will say that it can handle the intent, but the editor will give a 'cannot handle editing of document of type "author" as "book", do you want to edit as "author"?' type of message.
This tells the intent resolving that the document in question needs to be of the same type as we are displaying in the document list pane.
=> [structure] Disallow document lists to show editor for different type

packages/@sanity/desk-tool/src/DeskTool.js, packages/@sanity/desk-tool/src/index.js
This PR fixes an issue where an edit intent for a document without a defined type would fail to render an editor as intended. It also renames one use of `editDocumentId` to `legacyEditDocumentId` in the route parameters in order to more easily distinguish the use case of redirecting old desk tool URLs from the use case of editing a specific document ID without a correlated structure item.
=> [desk-tool] Handle generic edit intents without type name

packages/@sanity/desk-tool/src/DeskTool.js
When using the "fallback editor" (edit document by ID) and navigating to a different edit intent, the editor was not updated with the correct pane. This PR fixes that, and also makes sure we pass a proper key for the pane to trigger a proper reload.
=> [desk-tool] Fix fallback edit intent pane not updating properly

appveyor.yml
This should fix the build failure we're currently seeing on AppVeyor
=> [chore] Make appveyor use npm ci if available

packages/@sanity/base/sanity.json, packages/@sanity/base/src/util/documentActionUtils.js, packages/@sanity/default-layout/src/components/DefaultLayout.js, packages/@sanity/desk-tool/src/pane/DocumentsListPane.js, packages/@sanity/desk-tool/src/pane/Editor.js, packages/@sanity/structure/src/documentTypeListItems.ts, packages/@sanity/structure/src/parts/documentActionUtils.ts, packages/test-studio/schemas/actions.js, packages/test-studio/schemas/schema.js
This introduces an experimental feature to enable/disable different affordances for document types.
It makes it possible to configure a document type with a set of named actions (currently: `create`, `update`, `delete` and `publish`), and based on this, we enable/disable affordances in the UI.
For now, you'll have to configure this on `<type>.__experimental_actions`. Example:
https://github.com/sanity-io/sanity/blob/8045de1a9a9c573409fa0161835a9ff800a903c1/packages/test-studio/schemas/actions.js#L6
If `__experimental_actions` is not set on the document type, the default will be to enable all actions in order to preserve the current behavior.
This makes it possible to e.g.:
- Prevent a document type from appearing in the "Create new" dialog 
- Prevent the "delete"-menu action from …
=> [desk-tool] Experimental feature: actions

packages/@sanity/server/src/configs/webpack.config.js, packages/@sanity/storybook/package.json, packages/@sanity/storybook/src/config/webpack.config.js, packages/@sanity/webpack-integration/src/v3/index.js
The webpack-integration module was simply requiring webpack and expecting it to be the right version. This usually works, but there is no guarantees. With this change, we allow webpack to be injected, and use this from `@sanity/server` and `@sanity/storybook`. We fall back to regular require as before in order to maintain backwards compatibility.
=> [webpack-integration] Allow passing webpack instance to use

packages/@sanity/form-builder/src/sanity/utils/withMaxConcurrency.js
This fixes a bug causing error when uploading of more than four entries concurrently.
=> [form-builder] Fix broken batch upload when uploading > 4 entries

packages/@sanity/desk-tool/src/pane/Editor.js, packages/@sanity/desk-tool/src/pane/EditorPane.js
Currently we have no way to override the editor title through the structure builder, even though we do expose a `title` setter. This PR fixes this by passing the set title through to the actual editor. Falls back to document title as before if no title is set.
This addresses a problem where certain documents do not have a title field (as is often the case for "singletons" such as "site config" etc)
=> [desk-tool] Allow setting editor title

packages/@sanity/import/src/references.js, packages/@sanity/import/src/uploadAssets.js
When importing an ndjson stream without any references or assets, the progress indicator for those steps would never complete because the `progress()` function would never be called.
This PR ensures that in the case of empty batches, we don't even show the indicator.
=> [import] Fix spinner issue on no references/assets

packages/@sanity/base/src/styles/forms/textarea.css, packages/@sanity/components/src/textareas/DefaultTextArea.js, packages/@sanity/components/src/textareas/story.js, packages/@sanity/components/src/textareas/styles/DefaultTextArea.css, packages/@sanity/components/src/textinputs/story.js
Regular text inputs (`type: string`) has a subtle but pretty hover effect, whereas text areas do not. I suppose this is an oversight rather than a feature? Copy+pasted some styles from the text input styles, please double-check that this looks sane.
=> [base] Use same active/hover/focus styles for textarea as inputs

packages/@sanity/base/src/datastores/document/getPairListener.js, packages/@sanity/document-store/src/createDocumentStore.js, packages/@sanity/document-store/src/createObservableBufferedDocument.js
This is a refactor of the part of the document store that deals with document editing (checking out drafts/published, listening for events, adding mutations, etc.).
It fixes an issue with listener connections not getting closed when switching between documents. As a bonus it also fixes a regression that caused the "reconnect" message not being displayed (and disabling the form) if the internet connection went down while editing.
=> [document-store] Refactor document store

packages/@sanity/components/src/previews/CardPreview.js, packages/@sanity/components/src/previews/DefaultPreview.js, packages/@sanity/components/src/previews/DetailPreview.js, packages/@sanity/desk-tool/src/components/DocumentPaneItemPreview.js, packages/@sanity/desk-tool/src/pane/PaneItem.js, packages/@sanity/desk-tool/src/utils/getIconWithTypeFallback.js, packages/@sanity/preview/src/components/SanityDefaultPreview.js
This PR enables you to pass `false` as `media` to previews to explicitly disable the rendering of it. This differs from the default `undefined` or `null`, which still renders the gray square placeholder.
Certain previews already had handling for this which was weaker - any falsey value would skip the rendering of the media element. In the cases where this was true, I chose to leave it as-is.
=> [components] Allow disabling media in previews

packages/@sanity/desk-tool/src/DeskTool.js
We were using `shouldComponentUpdate` for side effects, which is obviously not pretty.
This changes to using `componentWillReceiveProps` which isn't really all that much better, but at least it reads better.
In addition, we now prevent re-rendering the desk tool when the pane deriving is about to be performed - this prevents a "phantom" re-render where the `keys` prop would be updated with the new keys from the URL, but the `panes` would be left with the old panes. This is very confusing when debugging, so it feels like a step forward.
The real solution here is probably to have the state router be observable in some way, so we may subscribe to changes on it and update the state without relying on being passed new props.
=> [desk-tool] Clean up pane deriving flow slightly

packages/@sanity/desk-tool/src/components/DocumentPaneItemPreview.js
When a schema type has only a single field to select for preview and that field is called `title`, when splatting in the structure config for a list item of that type, the `observeForPreview` config would optimize this as "we already have the info we need" and not run a query.
This would lead to the list item being displayed as `Untitled` if no `title` was set, and showing a draft indicator when this was not actually true, caused by the draft snapshot returning the ID and title from the passed value as an optimization.
This fix applies the title on the receiving end instead, which seems to do the trick, though I am not 100% confident that this is the right place to fix this, or if it hints at an underlying issue - feedback welcome.
=> [desk-tool] Fix document list items with only title being displayed as Untitled

packages/@sanity/components/src/panes/SplitController.js, packages/@sanity/desk-tool/src/DeskToolPanes.js
Fixes a bug that I think was introduced in "structure" where the pane does not collapse when resized  smaller than minWidth
=> [components] Collapse pane when too narrow

packages/@sanity/default-layout/src/datastores/urlState.js
Bug details explained on Slack, but tl;dr: resolving an intent twice in a row would yield an empty tool state for the second `getIntentState()` call.
=> [default-layout] Defer intent redirect to fix empty tool state

packages/@sanity/structure/src/DocumentList.ts, packages/@sanity/structure/src/DocumentTypeList.ts, packages/@sanity/structure/src/Intent.ts, packages/@sanity/structure/src/StructureNodes.ts, packages/@sanity/structure/src/documentTypeListItems.ts, packages/@sanity/structure/test/__snapshots__/documentTypeListItems.test.ts.snap, packages/@sanity/structure/test/documentTypeListItems.test.ts
This fixes an issue where someone would start out with a document type list (`S.documentTypeList('author')`) but would then alter the specification - most importantly, override the  `child`.
When this happened, the pane was still configured as being able to handle an edit/create intent for the schema type, but in reality it just resolved the child that was configured, instead of the editor.
With this fix, we reset `canHandleIntent` when parts of the specification is changed which would make the intent resolving incorrect - but only if the `canHandleIntent` function is the default, generated one (we trust the user to know what they are doing if they provide their own).
=> [structure] Reset `canHandleIntent` on doc type list spec changes

packages/@sanity/vision/src/components/ParamsEditor.js, packages/@sanity/vision/src/components/QueryEditor.js
This adds the auto close brackets option to the Vision plugin. It may be opinionated, but I think it adds some improved DX to the tool. Requested by @finiteattention in the [community slack](https://sanity.slack.com).
=> [vision] Add auto close brackets to editors in Vision

packages/@sanity/vision/package.json, packages/@sanity/vision/src/components/JsonDump.js
This replaces the JS(ON)-viewer in Vision with the [react-json-view](https://www.npmjs.com/package/react-json-view) component. The previous had formatting errors (strings in arrays). This also features a copy-function so that you can actually get sensible data out of vision.
=> [vision] Replace JSON viewer

packages/@sanity/components/src/selects/styles/DefaultSelect.css
Fixes a bug where DefaultSelect on firefox is thinner than DefaultTextInput
=> [components] Set height on select for firefox

packages/@sanity/client/src/config.js
`useCdn: true` + `token` is usually a bad combination, since it will "silently" use the live API for queries and listeners. This PR adds a warning when combining the two, encouraging people to use a different combination (a few examples outlined in the linked help article)
=> [client] Warn when token is used with useCdn set to true

packages/@sanity/desk-tool/src/pane/EditorPane.js
This fixes a bug introduced in #1003 that could cause the disconnected-state in the editor UI to persist even when connection is restored.
Will release in a hotfix after merge.
=> [desk-tool] Clear reconnect state when receiving new snapshots

packages/@sanity/client/src/config.js, packages/@sanity/client/test/warnings.test.disabled.js, packages/@sanity/client/warnings.js
This issues a console warning if you configure the sanity client to use a token in the browser. The warning will only be visible on local hosts.
Changed the order of appearances of warnings so that you get them in the following order (and only one at a time):
1) Token in browser (fixing this may invalidate the warning below)
2) Token together with `useCdn: true` (fixing this may invalidate the warning below)
3) Missing `useCdn`
=> [client] Warn if client is configured with a token in the browser

packages/@sanity/base/package.json, packages/@sanity/base/src/components/QueryContainer.js
When using arrays for parameters (think *[_id in $ids]), if the array of ids have the same members for the array itself does not have referential identity, the query container currently resubscribes.
This PR fixes this by using a deep compare for the parameters. I also took the liberty of changing a potential rerender when going from `error: null` to `error: false` - I couldn't see any reason why it was built this way initially, correct me if this has some specific purpose.
=> [base] Use deep compare when diffing query parameters

packages/@sanity/desk-tool/src/DeskTool.js, packages/@sanity/desk-tool/src/utils/resolvePanes.js
When navigating from:
> Content → Movies by genre → Sci-Fi → 2010 → Some Movie
to:
> Content → Movies by genre → Sci-Fi → 2010 → Some *Other* Movie
We are currently resolving the structure from the ground up. The way I see it, this isn't necessary, and causes potential rerendering/reflow issues, especially when using async operations in child resolvers. 
With this PR, we find the index of the first pane ID that changed (based on URL) from the previous, and derives panes from that index and upwards. By passing the previously resolved structure, we can then keep the existing, resolved panes.
=> [desk-tool] Resolve only changed panes

packages/@sanity/components/src/utilities/ActivateOnFocus.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/BlockEditor.js
Also automatic focuses input on activate/click
=> [form-builder] Keep focus alive when clicking inside blockEditor 

packages/@sanity/schema/src/legacy/types/object.js, packages/@sanity/validation/src/Rule.js, packages/@sanity/validation/src/inferFromSchema.js, packages/@sanity/validation/src/inferFromSchemaType.js, packages/test-studio/schemas/localeString.js, packages/test-studio/schemas/schema.js, packages/test-studio/schemas/strings.js
You have defined a `localeString` type at the root level, and you have certain validation rules you generally apply ("english is required, because it is the default").
In certain locations, you want to override the validation with more rules. For instance, for a `title` field, you may want to set all the languages as required, or set the max length of all fields as 80 characters.
This is currently not possible, since validation is applied at definition time. 
This PR implements a `.fields()` validation rule on objects, which takes an object where the keys represent the name of the fields to provide rules for, which will override the previously declared rule. Should be used sparingly, but in certain situations (like the above), I think it makes sense.
```js
{
name: 'localeTitle',
title: …
```
=> [validation] Allow field validation overrides for top-level objects

packages/@sanity/preview/src/components/SanityDefaultPreview.js
Fixes issues with 404s when switching dataset through space switcher.
=> [preview] Instantiate image url builder on render to catch config changes

packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderBlock.js, packages/@sanity/form-builder/src/inputs/BlockEditor-slate/Syncer.js, packages/@sanity/form-builder/src/utils/pathUtils.js
Currently, when the block editor embeds an input that just emits set-patches of objects, the associated `_key` gets lost and eventually crashes the UI. This fixes it by always setting the key back on the node data.
=> [form-builder] Preserve _key on items when applying patches

packages/@sanity/client/package.json, packages/@sanity/core/package.json, packages/@sanity/core/src/actions/build/compressJavascript.js, packages/@sanity/image-url/package.json
`UglifyJS`/`uglify-es` is no longer maintained and has been superceded by `terser`. Also, uglify-es has some pretty seriuous issues with React: https://twitter.com/sebmarkbage/status/1060053812075872256
This replaces uglify-js/es with terser (still sticking with `uglifyify` since it's using terser under the hood)
=> [chore] Replace uglify with terser

packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.js
This fixes an issue that could under some circumstances cause an error due to `assetDocument.metadata` not being set.
Even though this particular document type (`sanity.imageAsset`) never will have an undefined value for `metadata` in the data store, it can still be missing in the frontend as a consequence of how we optimize data fetching for previews. This will most likely not be an issue after #613 is in place.
=> [form-builder] Guard against missing metadata on image asset

packages/@sanity/base/package.json, packages/@sanity/base/src/components/QueryContainer.js, packages/@sanity/base/src/components/listenQuery.js, packages/@sanity/desk-tool/src/pane/DocumentsListPane.js
This is a complete rewrite of the rather messy QueryContainer Component. The data flow should be a bit more explicit now.
Also did a few tweaks to make the data fetching a bit more robust.
- Will waits 400ms before displaying spinner in documents pane
- Will display an error message if eventsource connection fails
- Removed deprecated child component
=> [desk-tool] Refactor QueryContainer

packages/@sanity/client/src/config.js
Fixes an issue where using the client in React Native environment would fail because `window` is present, but not `window.location`.
=> [client] Check for presence of window.location to determine if browser env

packages/@sanity/vision/src/components/JsonDump.js
Removes the confusing "root" name (as seen above) from the result view in vision
=> [vision] Remove "root"-prefix in results

packages/@sanity/form-builder/src/inputs/FileInput/FileInput.js, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.js, packages/@sanity/form-builder/src/sanity/inputs/client-adapters/assets.js, packages/@sanity/form-builder/src/sanity/uploads/typedefs.js, packages/test-studio/schemas/files.js
While the client has had the option to disable the original filename for assets for a while, it seems we have not exposed this functionality in the form-builder. This PR adds this functionality.
I went for the option `storeOriginalFilename` which seems to me more correct than the `preserveFilename` option used in the client (we should probably deprecate this and move to  `storeOriginalFilename` there as well in the near future, as the current name is misleading).
=> [form-builder] Add ability to disable original filename for assets

packages/@sanity/default-layout/src/components/SearchContainer.js
When doing a search, the query generated currently does not use any projection, and instead returns complete documents. This will load (and parse) a lot more JSON data than actually needed.
This patch selects only `_type` and `_id` which is the only fields we need in order to delegate to preview components (which will lazily load fields mandated by the preview config when preview components appear on screen).
=> [default-layout] Only select _id and _type when searching

packages/@sanity/structure/package.json
In order to call `require()`, we should now have the typings for node as a dependency, apparently.
=> [structure] Add @types/node for proper node.js typings

packages/@sanity/core/src/actions/exec/execScript.js
Currently if you run a script with sanity exec, there's no way to read from stdin in it (this is useful to e.g. display user prompts or other kinds of interactive CLIs).
This fixes the issue by forwarding the parent process stdio streams to the child process.
=> [cli] Pass through stdio streams to child process when running sanity exec

packages/@sanity/color-input/package.json, packages/@sanity/color-input/src/ColorInput.js
Did a small refactoring/cleanup of the color input so that it emits setIfMissing patches instead of overwriting the value. This fixes an issue causing missing keys when adding color objects to arrays.
=> [color-input] Make color input emit setIfMissing w/default value in order to preserve _key

lerna.json, packages/create-sanity/README.md, packages/create-sanity/index.js, packages/create-sanity/package.json
This adds the `create-sanity` package which enables `npm init sanity` scaffolding introduced in npm [5.10.0](https://github.com/npm/npm/releases/tag/v5.10.0).
More info here: https://docs.npmjs.com/cli/init#description
We could also consider adding `@sanity/create`
=> [create-sanity] Add create-sanity package

packages/@sanity/color-input/src/ColorPicker.css, packages/test-studio/schemas/color.js
Stop using negative margin since we can not know how big the parent (fieldset) margin is. 
The color picker field will no longer have bleed layout.
=> [color-input] Object with object with colors

packages/@sanity/components/sanity.json, packages/@sanity/components/src/buttons/ButtonCollection.js
Some plugins seems to use button-collection. Lets give a warning that it is deprecated
=> Deprecate button collection

packages/@sanity/preview/package.json, packages/@sanity/preview/src/components/ObserveForPreview.js, packages/@sanity/preview/src/components/PreviewSubscriber.js
Currently we re-display the preview placeholder when unsubscribing from changes in previewed values (e.g. when the preview component is off screen). This causes unnecessary scroll jumps in cases where the preview component's height varies with its content (e.g when displaying block images in the block editor). It also causes unnecessary re-renders for offscreen elements.
This patch will instead make the preview component keep the "last known" value of the previewed value after unsubscribing. When a preview component re-enters the visible area, it will re-subscribe and catch up with any changes that may have happened in the meantime.
=> [preview] Keep latest snapshot when unsubscribing from offscreen previewed values

packages/@sanity/cli/src/actions/init-plugin/bootstrapFromTemplate.js, packages/@sanity/cli/src/actions/init-plugin/initPlugin.js
The bootstrapping was using `path.join()` which is usually a good idea, but inside of the zip files, paths were unix-style, so filtering for files within the template path yielded no files to be extracted. This PR fixes that, and also adds a bunch of logging to make future debugging easier.
=> [cli] Fix plugin bootstrapping on Windows

packages/@sanity/core/package.json, packages/@sanity/core/src/actions/cors/addCorsOrigin.js, packages/@sanity/core/src/commands/cors/addCorsOriginCommand.js, packages/@sanity/core/src/commands/cors/deleteCorsOriginCommand.js
This PR adds support for adding CORS-origins which can contain wildcards, as well as being able to disallow credentials from certain CORS-origins.  The messages might need some work, they are difficult to get the right tone of voice on. Feedback welcome.
=> [core] Add support for wildcard + credential-less CORS-origins

packages/@sanity/core/src/actions/deploy/undeployAction.js, packages/@sanity/core/src/commands/deploy/undeployCommand.js, packages/@sanity/core/src/commands/index.js
This command will both remove the deployed files as well as unassigning a hostname so it can be reassigned to a different value.
Important to note that this will free up the hostname for others to use.
Not 100% sure if "undeploy" is the right word, but opening it for the functionality - feel free to suggest a better alternative name.
=> [core] Introduce `sanity undeploy`

packages/@sanity/preview/src/components/ObserveForPreview.js
Did a small goof up in #1094 and assumed the preview component would always get passed a value with `_id`, but that's not the case for e.g. array items. This fixes it by instead doing a shallow compare on `props.value` in order to detect changes.
=> [preview] Use shallow equals on value when comparing props

packages/@sanity/import/package.json, packages/@sanity/import/src/importFromArray.js, packages/@sanity/import/src/util/ensureUniqueIds.js, packages/@sanity/import/test/__snapshots__/uploadAssets.test.js.snap, packages/@sanity/import/test/fixtures/duplicate-ids.ndjson, packages/@sanity/import/test/import.test.js, packages/@sanity/import/test/uploadAssets.test.js
When importing documents with specified IDs, the order of them are not guaranteed since we're doing multiple transactions in parallel. When running without `--replace`, they will yield error messages about the document already existing, which can be confusing if you are not aware that the duplicate was from the dataset you were _importing_ rather than in the dataset from before.
This PR ensures that we throw an error when encountering explicitly defined, duplicate IDs.
=> [import] Throw error when encountering duplicate IDs

gulpfile.js, lerna.json, packages/groq/.gitignore, packages/groq/README.md, packages/groq/package.json, packages/groq/src/groq.js, packages/groq/test/groq.test.js
This module exports a single function that can be called with an ES2015 [template string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals) to signal that it represents a GROQ-query.
The result will be the exact same string as the input, - this is currently helpful for getting syntax highlighting in editors, but in the future it might also parse and validate queries, strip unncessary whitespace and similar.
Pairs well with [vscode-sanity](https://github.com/sanity-io/vscode-sanity)!
```js
import groq from 'groq'
const query = groq`*[_type == 'products'][0...10]`
```
=> [groq] Add groq module for use with tagged template literals

packages/@sanity/desk-tool/src/pane/Editor.js
Currently, when duplicating a document of a type that has liveEdit enabled, we inadvertently created a draft document. This patch makes sure we only duplicate the published version.
=> [desk-tool] Only duplicate published version if liveEdit is enabled

packages/@sanity/form-builder/src/inputs/BlockEditor/styles/BlockEditor.css, packages/@sanity/form-builder/src/inputs/BlockEditor/styles/BlockExtras.css
Mystery bug, scrollbar eats of scroll-container width differently on same Chrome version and MacOS. Also different in various Chrome on Linux versions.
I added ``overflow-y: 'overlay';`` to make it calculate the same width everywhere.
=> [form-builder] Block editor: fix scrollcontainer width issues

packages/@sanity/default-layout/package.json, packages/@sanity/default-layout/src/components/SanityStatusContainer.js
This PR ensures that the Sanity version check is only run for administrators. Since read/read+write users can't really do anything about being on an outdated version, it just creates clutter. 
Requested by a user on the [community slack](https://sanity-io-land.slack.com/archives/CB2F69QBU/p1545215180051300)
=> [default-layout] Only show version status to administrators

packages/@sanity/schema/src/sanity/groupProblems.js, packages/@sanity/schema/src/sanity/validateSchema.js, packages/@sanity/schema/src/sanity/validation/types/block.js
Currently there are little to no validation for the block type, which has arguably one of the more complex type definitions. This PR implements basic checks - arrays should be arrays, required properties needs to be present etc. It also checks that annotations are object types, as using scalar types would result in very weird errors.
=> [schema] Improve schema validation for block type

packages/@sanity/form-builder/src/inputs/BlockEditor/BlockExtrasOverlay.js
This removes a warning due to setting state after a component is unmounted
=> [form-builder] Clear timeout on cwu

packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/ScrollAbsoluteTopBottomPlugin.js
There were some issues with this where it would scroll in unexpected situations.
Only scroll to top when focus is first block and selection offset is the first char.
=> [form-builder] Block editor: tweak ScrollAbsoluteTopBottomPlugin

packages/@sanity/form-builder/src/inputs/BlockEditor/SyncWrapper.js
In an attempt to try to optimise the speed of the writing experience in the block editor, local patches was attempted to be sent debounced. This led to some side-effects, so we can't do that. We need instead to focus on optimising the Mutator (especially the aggressive rebasing) and probably also inside the form builder on a higher level.
=> [form-builder] Fix block editor patching issues

packages/@sanity/form-builder/src/inputs/BlockEditor/BlockExtrasOverlay.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createBlockActionPatchFn.js
Improved the patch function given as props to renderBlockActions. The `insert` function now accepts both a block and an array of blocks to insert below the block whose block action is being called.
Also, normalization of the set function block input.
=> [form-builder] Block editor: improve block action patch functions

packages/@sanity/webpack-loader/package.json
Webpack's loader-utils was [upgraded today](https://github.com/webpack/loader-utils/releases) with the result that some of our CSS stopped loading / building. The end result is that text fields and all popups loose some crucial styling. :tada: 
Comparing all updated packages to a local last known good narrowed the list of candidate packages down and the problem went away when pinning `loader-utils` to 1.1.0.  
I have an hunch it might be this fix causing the issues:
> isUrlRequest: ignore all url with extension (like moz-extension:, ms-browser-extension: and etc)
Didn't dig after root causes or an explanation for why it doesn't clobber all CSS parts.
=> [webpack-loader] Peg loader-utils at 1.1.0

packages/@sanity/schema/src/sanity/validateSchema.js
This PR enables external schema builders/schema creators to use the schema error machinery, by manually applying `_problems: [{severity: 'error', message: 'foo'}]` to the returned types/fields.
=> [schema] Allow problems from external schema creators to flow through

packages/@sanity/cli/package.json, packages/@sanity/cli/scripts/pack.js, packages/@sanity/cli/src/commands/projects/listProjectsCommand.js
Replaces the `tty-table` dependency with a simple no-divider "table".
Reason: easier consumption through sed/awk/xargs/whatever, as well as cutting down on dependencies (`tty-table` specifically has a downstream dependency causing issues in our windows builds, currently).
=> [cli] Replace tty-table dependency with simple list

packages/@sanity/components/src/dialogs/DefaultDialog.js, packages/@sanity/default-layout/src/components/CurrentVersionsDialog.js, packages/@sanity/default-layout/src/components/UpdateNotifierDialog.js
This adds a distinction between onClickOutside and onClose on the `DefaultDialog` component. These events is currently conflated in a single `onClose` event.
Being able to distinguish between these events makes it possible to disable close on _click outside_ for array item edit dialog, which again fixes an issue with the default input for `datetime` types. The current onClickOutside handling could potentially also have caused issues for other custom inputs that renders parts of its UI in portals.
=> [components] Make a distinction between onClickOutside and onClose dialog events

packages/@sanity/schema/src/sanity/groupProblems.js
When a schema declaration has a `fields` declaration (for instance) that is _assumed_ to be an array, we blindly try to iterate over it. This PR introduces an array check and falls back to filling the problems with a member declaration error.
=> [schema] Ensure that members declaration is an array

packages/@sanity/export/src/export.js, packages/@sanity/export/src/filterDrafts.js, packages/@sanity/export/src/filterSystemDocuments.js, packages/@sanity/export/src/logFirstChunk.js, packages/@sanity/export/src/rejectOnApiError.js, packages/@sanity/export/src/stringifyStream.js
Has been working so far because people usually only export once per node.js process.
This should fix it by calling functions that return new streams on each invocation
=> [export] Fix bug where streams would be reused across invocations

packages/@sanity/schema/src/legacy/types/blocks/span.js
This PR adds the two missing fields `marks` and `text` to the `span` type, as well as removing the ability to pass custom fields. Since we're never exposing the span configuration other than through the block type, I don't think this should cause any problems.
Necessary for the GraphQL API to have visibility of these fields.
=> [schema] Add missing fields to span type

packages/@sanity/components/src/panes/DefaultPane.js, packages/@sanity/components/src/panes/styles/DefaultPane.css, packages/@sanity/components/src/panes/styles/SplitController.css
We have to render the DOM to avoid that pane grows when larger content get rendered.
=> Autocollapse animation smoothness

packages/@sanity/cli/src/actions/init-project/initProject.js
Minor changes to copy. Split the introductory text when installing completely new projects and did a slight rewrite for reconfigurations as we can assume more knowledge. Also changed wording under reconfigure as it is slightly unclear what `project` (local JS, sanity.io, etc) refers to here.
=> [cli] Make minor changes to copy

.travis.yml, appveyor.yml, packages/@sanity/cli/src/actions/init-project/initProject.js, packages/@sanity/cli/src/commands/init/initCommand.js, packages/@sanity/core/src/actions/start/startAction.js
This PR introduces the ability to configure the project ID and dataset of a studio project in the following cases:
- When running `sanity init` in a studio folder with the `--reconfigure` flag
- When running `sanity init` in a studio folder that has no `projectId` in `sanity.json` (prompts for confirmation first)
- When running `sanity start` in a studio folder that has no `projectId` in `sanity.json`
This allows a user to more easily "restart" a project, or ship a template for a studio that can easily by bootstrapped.
=> [cli] Allow reconfiguring studio projects

packages/@sanity/desk-tool/src/pane/EditorPane.js
This fixes a rather curious issue we had with image uploads on iOS Safari.
When the listener connection for the document your'e editing disconnects we were setting the form in read only mode while displaying a "connection lost, reconnecting…" message. Since Safari is pretty eager on the energy saving, the _browse image/take a photo dialog_ would cause Safari to shut down open connections (but _only_ after a few seconds). As a consequence - when coming back after taking/selecting a photo, the reconnect event from the listener would trigger, causing the whole form to be set in read only state. This would happen _just_ before the `onchange` event on the file input would normally trigger, but since `onchange` doesn't trigger on read only inputs, nothing would then happen.
This provides a fix …
=> [desk-tool] Delay reconnect events to fix broken image upload on iOS

packages/@sanity/base/src/search/weighted/createWeightedSearch.js, packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.js
In #1168 we united the reference search with the global search, so that they both follow the same ranking/weighting rules. This accidentally made draft documents appear in reference search, making it possible to reference drafts. This caused problems when publishing documents later on. This PR provides a fix by adding an `includeDrafts` option (which is true by default).
=> [base] Support excluding drafts from search

packages/@sanity/form-builder/src/inputs/NumberInput.js, packages/@sanity/form-builder/src/inputs/UrlInput.js, packages/@sanity/form-builder/src/utils/getValidationRule.js, packages/test-studio/schemas/validation.js
This fixes the annoying case where browsers would show a relative URI as invalid even though the validation allows it.
Refactored the fetching of rules into a separate utility since it's kinda verbose and used in the number input as well.
We should probably revisit the validation implementation given that we now have a clearer picture of the weaker points of its implementation, but will create a separate issue for that.
=> [form-builder] Use text input for relative URL fields

packages/@sanity/schema/src/legacy/types/blocks/defaults.js
We previously did not do any validation on annotations. After the new block editor, we do.
This PR will allow the mailto and tel schemes in the default link annotation.
=> [schema] Allow tel: and mailto: as URI schemes for block link annotation

packages/@sanity/core/src/util/checkReactCompatibility.js
Currently our React version check disallows prereleases of React, which I don't think there are any good reasons to do. This coerces the semver before calling the satisifes check.
For reference
```js
semver.satisfies(semver.coerce('16.8.0-alpha.0'), '^16.2') // true
semver.satisfies(semver.coerce('16.6'), '^16.2') // true
semver.satisfies(semver.coerce('16.1'), '^16.2') // false
semver.satisfies(semver.coerce('17.0.0'), '^16.2') // false
```
=> [core] Coerce semver to allow prereleases of React

packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayInput.js, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ArrayInput.css, packages/@sanity/validation/src/validateDocument.js
If you somehow end up with `null`-values (or other non-object values) inside an array that is supposed to contain objects, the desk tool currently crashes.
This PR introduces a check for whether or not this is the case, and allows you to unset the non-object values.
=> [form-builder] Show warning on non-object array values

packages/@sanity/default-layout/src/components/SchemaErrorReporter.js, packages/@sanity/default-layout/src/components/SchemaErrors.js, packages/@sanity/schema/src/sanity/validation/types/array.js
When using a type ``block`` in an array, we must validate that it also doesn't use object types without a name, because the block editor is dependent on all the members having names.
In the future we probably should make it an overall requirement that every array member type should have a name.
There is also a commit here that fixes unique keys (we now have warnings) and completes propTypes for the SchemaErrorReporter component.
=> Validate array type of types for object without a name when used in combination with a block type

packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayInput.js
This adds a note about the expected format of `_key` in arrays when displaying the _missing keys_ warning
=> [form-builder] Include note about the format of _key in the missing keys warning

packages/test-studio/schemas/uploads.js
Fixes a bug that causes this error in test-studio.
=> [test-studio] Add missing name

packages/@sanity/image-url/src/parseSource.js, packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/__snapshots__/builder.test.js.snap, packages/@sanity/image-url/test/builder.test.js
Tolerant to crop/hotspot being null + fetching asset id from _id instead of _ref if asset is materialized.
=> [image-url] Now compatible with data from GraphQL apis

packages/@sanity/form-builder/src/inputs/StringInput.js
This makes the StringInput pass the onBlur to the underlying <input element.
=> [form-builder] Pass onBlur to underlying string input

packages/@sanity/schema/src/sanity/validation/types/block.js, packages/@sanity/schema/src/sanity/validation/utils/isJSONTypeOf.js, packages/example-studio/schemas/customBlockEditor.js
In certain cases, it seems `jsonType` is not returned when validating the schema types. For instance, when using the color schema type as a block annotation, `type` is returned as `object`, but `jsonType` is not present. Maybe @bjoerge has some insight on whether this approach is wrong in the  first place.
Example:
```js
export default {
name: 'pageBody',
title: 'Page body',
type: 'array',
of: [
{
type: 'block',
marks: {
annotations: [
{
name: 'link',
title: 'URL',
fields: [
{
title: 'URL',
name: 'href',
type: 'url'
}
]
},
{name: 'color', title: 'Color', type: 'color'}
]
}
},
{type: 'image'},
{type: 'callToAction'},
{type: 'placeholder'}
]
}
```
=> [schema] Fix block annotation validation not handling certain objects

packages/@sanity/default-layout/src/components/ToolSwitcher.js
When clicking on the current active tool it is expected that the tool resets to its initial state.
Let me know if this is an ok way of doing it.
=> [default-layout] Reset tool when selecting active tool

packages/@sanity/form-builder/src/inputs/BlockEditor/Editor.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Input.js, packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/EnsureEmptyTextBlockPlugin.js, packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/QueryPlugin.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/buildEditorSchema.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createEmptyBlock.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createOperationToPatches.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createPatchToOperations.js
Previously when deleting all the editor content, there would be left an empty block in the data (to ensure that it was possible to put the cursor there afterwards). This is now handled better so that the data is completely wiped, but an empty text bock placeholder will be inserted in the editor as soon as it gets focused. The block will be saved as soon as the user begins typing again.
Also this removes the need for the Slate schema normalization of min nodes (always keeping an empty block) which caused a lot of trouble when several clients were using the same document.
=> [form-builder] Block editor: reset field on delete all

packages/@sanity/form-builder/src/inputs/BlockEditor/Editor.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Input.js, packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/EnsurePlaceHolderBlockPlugin.js, packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/OnFocusPlugin.js, packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/TogglePlaceHolderPlugin.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createEmptyBlock.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createOperationToPatches.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createPatchToOperations.js
The last PR on this issue broke the tests because there were no longer a 1-1 relationship between the editor state and the actual data.
This is now handled in a way that the editors content gets in a placeholder state (a single block  with no text in the document gets a data attribute `placeholder` toggled by an own plugin on `keyUp`).
The function that converts editor operations to patches looks for this state and will send an unset patch if that is the case. Any other operations on a placeholder block is just ignored until there is actual content.
Also included are some minor fixes (setifMissing patches in additional required contexts) plus some minor other fixes.
=> [form-builder] Better handling of unsetting field when block editor is empty

packages/@sanity/block-tools/src/HtmlDeserializer/rules/html.js
There were a bug in the HTML Deserializer where when you had not defined a link type (but had other annotation types thus overwriting the default ones), the intended fallback deserialization of anchor tags (write out the hrefs in plain text) errored. This fixes this.
=> [block-tools] Fix bug in link deserialization fallback

packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/InsertInlineObjectPlugin.js
No need trying to predict the key name here, it will automatically get normalized afterwards. This lead to errors in some cases where the block structure was complex.
=> [form-builder] Block editor: fix sometimes failing insert inline object

packages/@sanity/code-input/package.json
We are currently implicitly depending on the react-icons package, which seems like an oversight.
This adds it as an explicit dependency.
=> [code-input] Add react-icons as dependency (fixes #1149)

packages/@sanity/components/src/dialogs/PopOver.js, packages/@sanity/components/src/dialogs/story.js, packages/@sanity/components/src/dialogs/styles/PopOver.css, packages/@sanity/form-builder/src/inputs/BlockEditor/EditNode.js
- Use DialogContent to set the size of the content
- Set title on dialogs on block editor to the type title
Before:
After:
=> Block editor dialog title

packages/@sanity/base/src/search/common/tokenize.js, packages/@sanity/base/src/search/weighted/createWeightedSearch.js, packages/@sanity/base/test/search-tokenize.test.js
In #1168 we used `lodash.words` for tokenization of the search string. Can't really remember the rationale behind it (think it had something to do with unicode, but in retrospect it feels misguided). Using `lodash.words` had some unintended side effects, like splitting words like `2pac` into `['2', 'pac']`.
This PR replaces `lodash.words` with a simple regex that splits the search string on space+comma.
=> [base] Split string on space and comma instead of using lodash.words for tokenization

packages/@sanity/base/src/schema/types/imageMetadata.js
Our image pipeline now populates two new fields on upload: `hasAlpha` and `isOpaque`. In order for these to be exposed in GraphQL APIs and be easier to discover, we should add them to the schema definition, so here goes.
=> [base] Add `hasAlpha`, `isOpaque` fields to image metadata fields

packages/@sanity/code-input/src/CodeInput.js, packages/@sanity/code-input/src/schema.js
This adds a filename input field for the code-input blocks:
The filename will be used for the previewing instead of the language as the language is both represented as the file ending as well as with a logo
=> [code-input] Add a filename field to code input blocks

packages/@sanity/client/package.json, packages/@sanity/client/src/http/nodeMiddleware.js, packages/@sanity/import/package.json
This enables keep-alive for the client when using node.js. Improves performance on subsquent requests.
=> [client] Introduce keepAlive in client

packages/@sanity/form-builder/src/sanity/inputResolver/customInputs.js
This removes a legacy feature that provided a part for overriding a default code-input.
=> [form-builder] Remove import for overriding code-input part

packages/@sanity/client/README.md
Clarified how to unsubscribe from a listen query, and fixed/added a few links to official RxJS-docs
=> [client] Improve docs wrt. client.listen and returned observable and how to unsubscribe

packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createPatchToOperations.js
When there came incoming patches trying to patch an editor's inline object, and that inline object contained another editor -  the  "root" block editor didn't apply these patches as it should (just like any other inline object). This commit fixes that. Also added some better names for various helper functions inside `createPatchToOperations`.
=> Fix bug where editor didn't patch inline objects correctly if containing another editor

packages/@sanity/form-builder/src/inputs/BlockEditor/Input.js
There was a bug when toggling to fullscreen on an editor which not yet has received focus that the `requestAnimationFrame` was placed in the wrong location. `requestAnimationFrame` must be run before trying to reference the editor React node.
=> [form-builer] Block editor - fix focus bug when toggling fullscreen mode

packages/@sanity/cli/templates/ecommerce/schemas/product.js
This fixes `Error: Encountered anonymous inline object "variant" for field/type "variants"` when trying to deploy a GraphQL API for the e-commerce template.
=> [cli] Remove  from variants

packages/@sanity/image-url/README.md, packages/@sanity/image-url/src/builder.js, packages/@sanity/image-url/src/urlForImage.js, packages/@sanity/image-url/test/__snapshots__/builder.test.js.snap, packages/@sanity/image-url/test/builder.test.js
Adds support for the `auto=format` feature.
=> [image-url] Add `auto('format')` support for automatic WebP switching

packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/Toolbar.js
Don't show link to more in the editor toolbar if there isn't more to actually show (very restricted editor feature-set).
=> [form-builder] Block editor: hide 'More' button if empty

packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/PastePlugin.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createOperationToPatches.js
This is related to the placeholder blocks that ensures that there always is a cursor in the editor even though the data itself is empty.
When pasting HTML and trying to `insertFragment`, it must check if there only is a placeholder in the editor, and do things a little differently if it is.
=> [form-builder] Fix bug where pasting into an editor inside an editor would sometimes error

packages/@sanity/default-login/src/LoginDialog.js, packages/@sanity/default-login/src/LoginWrapper.js
With the latest Mac OS release today, Safari was updated, and the workaround/exception we did for Safari is now broken (just returns to the login screen - even though it's not being hit by ITP). Resetting it to use the standard login flow while we work on a more permanent ITP solution.
Also removed code introduced by #1018
=> [default-login] Remove Safari login exception

packages/@sanity/default-login/src/LoginWrapper.js
Issue introduced in #1263 - I should have spotted this in code review, sorry.
On first mount, the auth store does not have any state, so resolves asynchronously and works as expected.
On subsequent mounts (in hot reload mode), we already have the user so it resolves synchronously. This makes it call `setState` inside of the constructor, which is a noop. It's therefore stuck in a loading state until you manually reload.
This PR fixes that by introducing the ugly but functional sync check - I'm sure we could make a better fix at some point, this is 🔥 🚒
=> [default-login] Fix synchronous setState in constructor

packages/@sanity/core/src/actions/cors/addCorsOrigin.js
Needs backend change to be merged first, but this will allow the CLI to add any protocol as CORS-origin.
=> [core] Allow specifying non-HTTP protocols for CORS-origins

packages/@sanity/cli/src/actions/init-project/promptForDatasetName.js
This should give more meaningful errors when using invalid dataset names (usually this was because of uppercase characters).
=> [cli] Improve dataset name validation

packages/@sanity/dashboard/src/widget.css, packages/@sanity/dashboard/src/widgets/sanityTutorials/SanityTutorials.css, packages/@sanity/dashboard/src/widgets/sanityTutorials/SanityTutorials.js, packages/@sanity/dashboard/src/widgets/sanityTutorials/Tutorial.css, packages/@sanity/dashboard/src/widgets/sanityTutorials/Tutorial.js, packages/test-studio/src/dashboardConfig.js
Updates the tutorials stream to use flex box (to allow for cut-off of the last item, for discoverability).
Changes the max-height logic to fix weird overflow scrolling.
Adds play icon to tutorial items.
=> [dashboard] Update design

packages/@sanity/core/src/actions/dataset/validateDatasetName.js
Fixes a bug where `sanity dataset create 2019` would fail because the CLI auto-converts the argument to a number
=> [core] Ensure dataset name is a string before validating

packages/@sanity/form-builder/src/inputs/FileInput/FileInput.js, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.js
Image and file fields were not getting their markers displayed because they were not passed down to the fieldset. This fixes that, making validation status more prominent.
=> [form-builder] Pass on markers from asset inputs to fieldset

packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.js
If you have an image field where all the fields are "hoisted"/"highlighted" to always be shown and the hotspot tool is enabled, the edit button is shown. If however the field does not have any asset, the dialog shows nothing but a header.
With this PR, we only show the edit button if the image has non-hoisted fields, _OR_ the image field both has an asset _and_ has hotspot enabled.
=> [form-builder] Hide image edit button if no fields and no asset

packages/@sanity/import/src/uploadAssets.js, packages/@sanity/import/test/__snapshots__/uploadAssets.test.js.snap
If you have the following in an exported dataset dump:
```js
{
_id: 'foo',
_type: 'someDocument',
coverImage: {
_type: 'myCustomImage',
_sanityAsset: 'image@some-path.jpg'
}
}
```
The `_type` property will be overwritten:
```js
{
_id: 'foo',
_type: 'someDocument',
coverImage: {
_type: 'image',
asset: {_ref: 'some-ref'}
}
}
```
This PR fixes this by using a `setIfMissing` patch instead.
=> [import] Don't override _type for imported assets

packages/@sanity/client/src/data/dataMethods.js, packages/@sanity/client/src/http/requestOptions.js, packages/@sanity/client/src/sanityClient.js, packages/@sanity/client/test/client.test.js
This PR ensures that the default timeout is above the technical limits (5 minutes, vs 3 minute mutation and 1 minute query timeout). This will lead to more understandable error messages on timeouts, and being able to more easily differentiate between _client_ and _server_ timeouts.
Also added the ability to override timeout and token on a per-request basis, which can be quite useful in a lot of situations.
=> [client] Raise default timeout, allow overriding per-request

packages/@sanity/validation/src/Rule.js, packages/@sanity/validation/src/inferFromSchemaType.js, packages/@sanity/validation/src/validators/objectValidator.js
When you have an image or a file field with custom metadata fields attached, `required()` will still yield true if you have set one of those fields. This PR introduces `assetRequired()`, which requires that the actual `asset` field is set and has a `_ref`.
=> [validation] Add new `assetRequired`-flag

packages/@sanity/validation/src/validators/objectValidator.js
Currently, if you have an object type with an object only consisting of meta fields, for instance:
```
{_type: 'foo'}
```
...it is treated as having a value, and the `required()` validation does not kick in.
This PR changes the semantics to exclude the following meta keys: `_key`, `_type`, `_weak`.
=> [validation] Exclude meta fields from object emptiness check

packages/@sanity/schema/src/legacy/types/file.js, packages/@sanity/schema/src/legacy/types/image.js
If you extend an image or file type by adding custom fields, validation no longer kicked in. This PR fixes that by allowing the specification of the `validation` property on subtypes.
=> [schema] Allow file + image to extend validation

packages/@sanity/export/src/AssetHandler.js, packages/@sanity/export/test/AssetHandler.test.js, packages/@sanity/export/test/__snapshots__/AssetHandler.test.js.snap
This fixes an issue with `sanity export` that affected asset fields that had additional fields that also included assets.
=> [export] Recusively rewrite additional fields on image/file fields

packages/@sanity/import/package.json, packages/@sanity/import/src/importFromStream.js
Previously `sanity import` reused the same tempdir when unpacking archives to be imported. This could leave the import folder in an unwanted state (e.g. including assets from previous imports). This patch ensures every run of `sanity import` gets assigned it's own unique tempdir.
=> [import] Use unique tempdirs when unpacking archive for import

packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/InsertInlineObjectPlugin.js, packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/TogglePlaceHolderPlugin.js
Fixes two bugs where there would be deviations in the data in the editor and in the actual datastore, leading to crashes. Both are related to InlineObjects.
=> Fix block editor inline bug

packages/@sanity/export/.eslintrc, packages/@sanity/export/src/AssetHandler.js
Because _mistakes were made_ ™️ , we don't always have an md5 sum available for uploaded assets, but we _do_ have a SHA1 sum. With this change;
- If no etag (md5) or sha1 header is present, assume the download is valid
- If no etag (md5) is present but a sha1 header _is_, use sha1 for validation
- If both etag (md5) _and_ sha1 header is available, use md5 for validation
A bit messy, but we can phase out one approach in the future.
=> [export] Use SHA1 for validation if MD5 is not available

packages/@sanity/export/src/AssetHandler.js
This fixes a bug where failed asset downloads that occurred before the documents stream was finished would cause a "Asset handler errored before finish was called" error.
Now, we store the rejection and reject once the finish handler is added.
In additional, we try to parse the error from the backend so we can include any potentially helpful error messages.
=> [export] Include more descriptive messages on download error

packages/@sanity/form-builder/src/inputs/BlockEditor/Editor.js, packages/example-studio/components/FunkyEditor/FunkyEditor.js, packages/example-studio/package.json
The custom paste handler must take into account that the field can now be empty (it was always populated by a block before)
=> Fix editor on paste patch bug

packages/@sanity/form-builder/src/inputs/ImageInput/SelectAsset.js
If no images are found, we just show an empty dialog with the title "Select image". This adds a (minimal) message to let you know what's going on.
=> [form-builder] Display "no images found" text if no images are found

packages/@sanity/form-builder/src/inputs/ImageInput/SelectAsset.js
If we request 200 items and receive less than this amount, we can assume we're at the end. This doesn't solve the case where there is exactly `PER_PAGE` items to load, but should at least provide a better UX 99% of the time.
=> [form-builder] Don't show 'Load more'-button if reached known end

packages/@sanity/components/src/selects/SearchableSelect.js, packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.js
When you are on a slow connection, the reference input will simply show an empty input with the placeholder "Type to search" while it is loading the preview snapshot. This fixes this issue by checking for this state and changing the placeholder to "Loading..." as well as putting the input into read-only mode. The loading state is also passed down to the underlying searchable select.
In order to make this work, I had to remove a special-cased check for the placeholder in SearchableSelect, where if the input was in read-only mode, it would show "No value". I'm not sure why this was chosen as a behavior, so please correct me/this PR if this has to be done differently.
=> [form-builder] Use loading state for reference input while loading initial value

packages/@sanity/form-builder/src/inputs/ImageInput/Asset.js
We are currently scaling small images up to 100px in height, and on high-density displays, we're scaling 100px tall images to 200/300px etc. This PR ensures that we're not upscaling small images, as well as taking device pixel ratio into account when requesting an appropriate size.
=> [form-builder] Use max-fit and and DPR-aware height

packages/@sanity/mutator/src/jsonpath/Expression.js, packages/@sanity/mutator/test/Expression.test.js, packages/@sanity/mutator/test/patchExamples/unset.js
Given the object:
`{attr: "123"}`
The following expression matches in the mutators JSONPath implementation:
`[attr==123]`
While in the Sanity DB, it does not (should be `[attr=="123"]`).
The error was simply not using a strict equality check when evaluating the expression.
This PR fixes this and adds tests for this case.
Over-the-shoulder, IRL-approved by @simen
=> [mutator] Use strict equals when comparing equality

packages/@sanity/components/src/utilities/Poppable.js
The `Poppable` utility is referencing the `window.Element` global implicitly, which does not work in Node.js.
This PR makes it return `PropTypes.any` for that property in non-browser environments.
=> [components] Fix propType depending on window global

packages/@sanity/form-builder/package.json, packages/@sanity/form-builder/src/inputs/common/UploadTarget/canvasToBlob.js, packages/@sanity/form-builder/src/inputs/common/UploadTarget/imageUrlToBlob.js, packages/@sanity/form-builder/src/sanity/uploads/image/orient.js
The canvas-to-blob dependency has not been touched for 5 years and implicitly depends on `window`. Sometimes you end up requiring stuff in a node environment which includes dependant files in the dependency tree, which blows up. This PR moves the polyfill logic into our own repo, patches the `window` check and removes the dependency.
=> [form-builder] Make canvas to blob polyfill node.js-safe

packages/@sanity/components/package.json
This dependency doesn't seem to be used anywhere within components
=> [components] Remove unused canvas-to-blob dependency

packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.js, packages/@sanity/imagetool/src/index.js
The image input renders the full-size image, which can be quite expensive in terms of both bandwidth and CPU/memory usage.
While the optimal thing to do may be to constrain it to the size of the container, that can quickly yield a myriad of different variations based on the client. Instead, we constrain it to the max size that the image tool (the crop/hotspot editor) will use, currently 1000px in width. We also factor in the DPR, scaling it up if the device supports it.
It's a bit convoluted, but I think this is the best I can come up with within a reasonable timeframe. Better than 20 MB jpegs, I guess? ;)
=> [form-builder] Constrain rendered images to a reasonable size

packages/@sanity/components/src/lists/styles/DefaultList.css, packages/@sanity/desk-tool/src/pane/ListPane.js, packages/@sanity/structure/src/List.ts, packages/@sanity/structure/src/StructureNodes.ts, packages/@sanity/structure/src/index.ts, packages/test-studio/src/deskStructure.js
Usage:
```js
import S from '@sanity/desk-tool/structure-builder'
export default
S.list()
.id('content')
.title('Content')
.items([
S.listItem().title('Foo'),
S.divider(),
S.listItem().title('Bar'),
])
```
Currently just renders a `<hr />`:
Needs some design work, I assume. Open for discussion.
=> [structure] Add divider builder method

packages/@sanity/base/src/datastores/location/createLocationStore.js
Fixes this warning in the console:
> Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.
=> [base] Fix history import to match new API

packages/@sanity/schema/src/core/traverseSchema.js, packages/@sanity/schema/src/sanity/validateSchema.js, packages/@sanity/schema/src/sanity/validation/createValidationResult.js, packages/@sanity/schema/src/sanity/validation/types/rootType.js
This PR makes sure that if you include a `null`, `undefined` or `false` in your `types` array, instead of crashing the studio you will get a descriptive error back. It also catches the case where you import an ES module through `require` and end up with an object with a `default` property.
Help articles have also been written to cover these cases.
=> [schema] Catch and display errors for falsey/incorrectly imported type defs

packages/@sanity/default-layout/src/components/DefaultLayout.js, packages/@sanity/default-layout/src/components/SideMenu.js, packages/@sanity/default-layout/src/datastores/urlState.js
The default layout currently crashes if desk tool is not installed as a tool, because it uses the data-aspects resolver to infer which items to display in the "New" dialog. I also discovered a few issues where the layout would crash if no tools were installed, which I also fixed. 
I think we intend to deprecate/remove data aspects at some point, but leaving that for a different PR.
=> [default-layout] Decouple default layout from desk tool

packages/@sanity/schema/src/sanity/validation/types/array.js
The following code will crash the validation machinery:
```js
export default {
title: 'Block Content',
name: 'blockContent',
type: 'array',
of: [
{type: 'richBlock'},
undefined,
{type: 'image'},
]
}
``` 
This fixes that by explicitly checking for falsey values and gives back a meaningful error
=> [schema] Fix crash on invalid array `of`-member declaration

packages/@sanity/desk-tool/src/utils/resolvePanes.js
The following structure fails to resolve the list:
```js
import S from '@sanity/desk-tool/structure-builder'
export default S.list()
.title('Content')
.items([
S.listItem()
.title('Posts')
.schemaType('post')
.child(
S.documentTypeList('category')
.title('Posts by category')
.child(S.list().title('test'))
),
...S.documentTypeListItems()
])
```
The following works:
```js
import S from '@sanity/desk-tool/structure-builder'
export default S.list()
.title('Content')
.items([
S.listItem()
.title('Posts')
.schemaType('post')
.child(
S.documentTypeList('category')
.title('Posts by category')
.child(() => S.list().title('test'))
),
...S.documentTypeListItems()
])
```
This was caused by us explicitly checking whether the `child` was a function, which it shouldn't have to be. Changed to only care …
=> [desk-tool] Fix issue where non-function `child` would fail to resolve

packages/@sanity/desk-tool/src/pane/LoadingPane.js
When the "loading" indicator is shown, it is cut at the top, so spinner is not actually visible. Text also cut in certain cases. This fixes the issue by cutting an intermediary div, which aligns the loading indicator to the vertical center.
=> [desk-tool] Fix loading indicator being cut at top

packages/@sanity/cli/src/actions/init-project/initProject.js
Fixes a bug where `sanity init --visibility private` would yield "visibility mode not allowed" (a check had mistakenly been inverted).
Also took the liberty of adding a check for whether a different output path is given and skipping the reconfiguration prompts if such is the case.
=> [cli] Fix inverted visibility allowed check

packages/@sanity/structure/src/List.ts
```js
S.list().title('Things').items([Promise.resolve(thing)])
```
Gives something along the lines of "Expected _listItem_, got _object_"
With this change, it gives "Expected _listItem_, got _Promise_"
The documentation link that follows it gives some helpful information on how to deal with cases where you actually want to use a promise for building list items.
=> [structure] Improve error when promise is passed in list items

packages/@sanity/core/src/commands/documents/createDocumentsCommand.js, packages/@sanity/core/src/commands/documents/deleteDocumentsCommand.js, packages/@sanity/core/src/commands/documents/getDocumentsCommand.js
This fixes an issue where `sanity documents delete 123` and `sanity documents get 123` would not work because the CLI would automatically cast the argument to a number, where the client expects a string.
=> [core] Cast document IDs to string for document commands

packages/@sanity/core/src/actions/exec/babel.js, packages/@sanity/core/src/actions/exec/execScript.js, packages/@sanity/core/src/actions/exec/pluginLoader.js
Currently, if you have JSX or class properties in any files required when doing `sanity exec` on a script, it'll fail because the only loaded plugin is the env plugin. This brings the default babel config in line with the studio.
Also makes the plugin loader stub the CSS to speed up the sanity exec process a bit.
=> [core] Make `sanity exec` use same babel config as studio

packages/@sanity/cli/bin/sanity, packages/@sanity/cli/package.json
Using the `v8-compile-cache` module speeds up the CLI bootup by ~100ms on my machine.
=> [cli] Use v8 compile cache

packages/@sanity/block-tools/README.md
A user was having issues with running a script using `@sanity/block-tools`.
> Hei, jeg prøver å bruke @sanity/block-tools i et eksternt node-script i vårt sanity-prosjekt til å konvertere html. Men jeg får aldri kjørt scriptet. Hvis jeg kjører med modules-støtte så fungerer ikke referansen til @sanity/schema. Hvis jeg bruker require så kommer jeg et skritt lenger, men det stopper i schema.js på import av part:@sanity/base/schema-creator.
> Hva er det jeg gjør galt?
Which is understandable, because `sanity exec` is not mentioned anywhere in the README.
=> [block-tools] Add info about running sanity scripts

packages/@sanity/client/src/data/listen.js, packages/@sanity/preview/src/observeFields.js
This adds support for specifying the `visibility`-parameter to `@sanity/client`. (Described here: https://www.sanity.io/docs/listening#parameters)
It also modifies the preview observer so that it re-fetches a previewed document immediately when receiving a mutation event with `visibility: query` (https://www.sanity.io/docs/realtime-updates#object-object-events)
=> [preview] Use visibility query when setting up listener

packages/@sanity/export/src/AssetHandler.js
Primarily:
- Was md5 or sha1 used to check for a valid file?
- What was the expected and the calculated hash?
- What was the expected size of the file, and how many bytes did we receive?
=> [export] Provide better error messages on download failure

packages/@sanity/components/src/toggles/ToggleButton.js, packages/@sanity/form-builder/package.json, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/AnnotationButtons.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/BlockStyleSelect.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/CollapsibleButtonGroup.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/DecoratorButtons.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/InsertMenu.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/ListItemButtons.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/PrimaryGroup.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/Toolbar.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/ToolbarClickAction.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/AnnotationButtons.css, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/CollapsibleButtonGroup.css, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/DecoratorButtons.css, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/ListItemButtons.css, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/PrimaryGroup.css, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/Toolbar.css, packages/@sanity/form-builder/src/inputs/BlockEditor/styles/BlockEditor.css, packages/test-studio/schemas/blocks.js
- Auto-collapsing groups in toolbar when needed
- Insert menu supports not being collapsed
- Display a "show menu" button when there is no room for all
- Touch scrolling in mobile with paper-cut-shadow™ to show scrollability
=> Collapsible button group in block editor

packages/@sanity/base/src/search/weighted/createWeightedSearch.js, packages/@sanity/default-layout/src/components/SearchContainer.js
If you have no document types in your schema (for instance in the case of the clean template) and try to do a search, two bugs are surfaced:
1. An invalid query is generated. In essence, it looks like this: `*[_type in $types && ()] {...select()}` - an empty parentheses is not allowed, so it fails. Also, the `select()` function needs a body.
2. When pressing Enter in the search input, the studio crashes because it tries to use `querySelector` on a non-existing element. 
This PR fixes both of these issues. To reproduce/test this issue, remove all document types from your `types` array and try to search.
=> [base] Fix broken search on no document types

package.json
GitHub recently introduced the "Used by"-feature, which displays usage numbers based on the package `name` in the repo's root level `package.json`. This has initially been just `sanity`, but I think it makes more sense (and better reflects real-world usage) if we change this to `@sanity/client` instead.
This change may introduce some confusion for people coming looking for the actual `@santiy/client`-package, so I added a comment about where to find it (who says you can't have comments in JSON).
=> [chore] Set root package name to '@sanity/client'

packages/@sanity/cli/templates/blog/schemas/schema.js, packages/@sanity/cli/templates/clean/schemas/schema.js, packages/@sanity/cli/templates/ecommerce/schemas/schema.js, packages/@sanity/cli/templates/moviedb/schemas/schema.js
A simple fix to the comment: // Then proceed to concatenate our our document type
=> [cli] Fix duplicated word in the comments of cli/schema.JS

package.json, packages/@sanity/code-input/src/CodeInput.js, packages/@sanity/code-input/src/config.js
If you specify a language that there is no corresponding ace mode registered for, it'll currently crash the studio. With this PR, it'll warn and fall back to text mode instead. Unknown modes will also be removed from the dropdown and a warning will be logged.
I also took the time to add basic aliasing support with warning for `js` instead of `javascript`
=> [code-input] Only render editor on supported languages

packages/@sanity/core/src/actions/build/buildStaticAssets.js, packages/@sanity/core/src/actions/deploy/deployAction.js
When you set a `basePath` for a studio, this information is not carried over to the `sanity.studio` hosting. The result is that the `index.html` file references paths that do not exist, which obviously fails.
For now, let's ignore any base path when using `sanity deploy`, but obviously keep support for it when using `sanity build`.
=> [core] Deploy to sanity.studio without basePath

packages/@sanity/preview/src/prepareForPreview.js
We are currently only catching prepare errors in development. We briefly discussed this IRL and decided that maybe we should just do the same for production.
This PR implements this, as well as fixing an error where the prepare error would be garbled into a string because of an incorrect order of arguments.
=> [preview] Always run preview prepare in try/catch

packages/@sanity/server/src/configs/webpack.config.js
Fixes react-hot-loader not resolving in symlinked modules
=> [server] Prevent build error on symlinked modules

packages/@sanity/base/src/components/ErrorHandler.js, packages/@sanity/base/src/components/SanityRoot.js, packages/@sanity/base/src/util/uncaughtErrorHandler.js
The full-screen global error handler is quite intrusive. Sometimes this is necessary, because the error that occurs actually crashes the app in a way it cannot recover. However, a lot of the time the errors are fairly innocent, where most of the app continues to work as expected despite the error.
To allow for these errors not to fully block the studio from functioning, this change introduces a _second_ error handler, which takes over as quickly as React has been mounted. This makes sure that any low-level errors that prevents React from rendering will still use the full-screen error handler. Any errors after this point will render a "Snackbar" error that prompts the user to take a peek at their browsers devtools to figure out the error.
In development, it shows the first line of the …
=> [base] Add less intrusive error handler

packages/@sanity/base/src/components/ErrorHandler.js, packages/@sanity/base/src/components/styles/ErrorHandler.css
Fixes the case where a really long error message would fill the whole screen (at least partly).
Might be worth changing the snackbar to have some sort of max-height as well, but this at least partly addresses the issue.
=> [base] Use ellipsis for long error messages

packages/@sanity/form-builder/src/inputs/ImageInput/Asset.js, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.js
Prevents a case where some browsers report a DPR of things like 1.005 or something along those lines.
=> [form-builder] Round device pixel ratio, avoiding float dimensions for images

packages/@sanity/client/src/http/requestOptions.js
If you have a client globally configured to use credentials (such as in the studio), then do a request using the client where you explicitly tell it not to use credentials (`client.request({uri: '/ping', withCredentials: false})`), the client does not currently respect this.
This breaks the CORS-check we do when a network failure happens during the login phase, which can be confusing for users.
This PR fixes this by always honoring the `withCredentials` override first, then falling back to token/globally configured `withCredentials` option.
=> [client] Fix `withCredentials` override not being applied

packages/@sanity/preview/src/components/WithVisibility.js
This is a workaround for a bug recently introduced in Chromium, released in Chrome 75 which is causing the `IntersectionObserverEntry.isIntersecting` to report `false` on empty elements. This again affected list previews in the Sanity Studio (see full description here:  #1375)
See also https://bugs.chromium.org/p/chromium/issues/detail?id=972196
Fixes #1375
=> [preview] Insert a nonbreaking space initially to workaround chromium bug

packages/@sanity/desk-tool/src/pane/Editor.js, packages/@sanity/desk-tool/src/utils/copyDocument.js
When you duplicate a document using the desk tool, the timestamps (`_createdAt`, `_updatedAt`) are kept as-is. Whether or not this is a bug or a feature is up for discussion, I guess, but it feels odd to me. I was expecting to see my new duplicate document at the top of the list when ordering by updated date.
This PR omits these timestamps from the cloned document.
=> [desk-tool] Omit _createdAt, _updatedAt when creating duplicate document

packages/@sanity/desk-tool/src/pane/Editor.js
When the desk tool is showing the "fallback" edit pane instead of a specific structure, the "duplicate" action tried to use the `panes` router state, which didn't exist. With this change, it will only reuse the last pane if present, and in the case of the fallback; replace the edited document ID with the new one.
=> [desk-tool] Fix error when duplicating document in fallback edit pane

packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.js
This fixes an issue with the reference input in `readOnly` mode, where it still displayed "Type to search…" as placeholder.
=> [form-builder] Reference input: Don't show placeholder when input is readOnly

packages/@sanity/export/.eslintrc, packages/@sanity/export/src/AssetHandler.js
Two changes worth mentioning:
- Fix incorrect wording in error messages - always says "image", when it could be a file. Changed to "asset" to be more generic.
- Fix case where remote md5/sha1 was not present, but we still compared against it. This would basically compare `undefined` to a hash, which obviously would always be incorrect.
=> [export] Check for remote hash before attempting to compare against it

packages/@sanity/form-builder/src/inputs/BlockEditor/BlockExtrasOverlay.js
The `BlockExtrasOverlay` component is using `requestAnimationFrame`, but is not cancelling on unmount. This sometimes causes the classic "setState after unmount" bug.
This PR fixes that.
=> [form-builder] Cancel requestAnimationFrame on unmount

packages/@sanity/transaction-collator/src/transactionsToEvents.ts, packages/@sanity/transaction-collator/test/__snapshots__/transactionsToEvents.test.ts.snap
There was an invalid edit threshold constant, which gave a longer threshold value than the intended five minutes.
Also a typescript issue fix, and updated test snapshot.
=> [transaction-collator] Bugfixes

packages/@sanity/base/src/styles/layout/selectable.css, packages/@sanity/components/src/history/ListItem.js, packages/@sanity/components/src/history/styles/ListItem.modules.css, packages/@sanity/components/src/presence/PresenceCircle.js, packages/@sanity/components/src/presence/story.js, packages/@sanity/components/src/presence/styles/PresenceCircle.css, packages/@sanity/desk-tool/src/components/InspectHistory.js, packages/@sanity/desk-tool/src/pane/Editor/Editor.js, packages/@sanity/desk-tool/src/pane/Editor/HistoryForm.js, packages/@sanity/desk-tool/src/pane/History.js, packages/@sanity/desk-tool/src/pane/styles/History.css, packages/movies-studio/resolveProductionUrl.js, packages/test-studio/src/resolveProductionUrl.js
- Disabled hover on touch-devices
- Smooth overflow scroll on touch devices
- Removed colored border around avatars and make the border transparent with calculated clip-path to show the background color
- Enables as many context menu items as possible in history mode
- Send `_rev` to document preview
- 2px gap between user avatars
=> [all] History UI fixes

packages/@sanity/base/src/client/index.js, packages/@sanity/base/src/components/MissingProjectConfig.js, packages/@sanity/base/src/components/SanityRoot.js, packages/@sanity/default-login/src/ErrorDialog.js
When running `sanity build` without having specified a project ID or dataset in  `sanity.json`, the studio currently crashes when trying to initialize the studio client with a missing configuration.
There is some value in being able to build a Sanity project without specifying these credentials, for instance when shipping examples/templates that is deployable to a provider.
This PR adds a new dialog that lets you know what the error is:
=> [base] Check for missing projectId/dataset on startup

gulpfile.js
Fixes the recently introduced issue where CSS files would not be rebuilt/copied on change when watching the monorepo
=> [chore] Fix gulp assets watch task

packages/@sanity/cli/scripts/pack.js
`write-file-atomic` is used by a dependency of ours, and tries to bundle `worked_threads`. It doesn't break anything, but the warning is kind of annoying every time I rebuild the CLI, so adding it to the ignore list.
=> [cli] Ignore missing worker_threads module when building

packages/@sanity/preview/src/components/PreviewSubscriber.js
There is currently a regression in the way visibility toggling for previews are keeping their height when hidden. This is a quick fix to disable visibility toggling for previews that are either `inline` or `block`. They should only apply to previews inside the PT editor, where the bug is currently really annoying.
=> [preview] Don't toggle visiblity for 'inline' and 'block' previews

packages/@sanity/form-builder/src/inputs/BlockEditor/Input.js
There is some invalid logic here introduced in https://github.com/sanity-io/sanity/pull/1335/commits/aa93a906cbb302478cd680c347785d2b9a2a6f7d that prevents focus to be maintained between toggling fullscreen. This reverts that, and as far as I can tell there is no longer any issues by setting focus when the document is first openend which the invalid logic tried to deal with.
=> [form-builder] Block editor: fix focus bug

packages/@sanity/block-tools/src/util/blockContentTypeFeatures.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/AnnotationButtons.js, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/DecoratorButtons.js, packages/@sanity/schema/src/legacy/types/blocks/block.js, packages/@sanity/schema/src/legacy/types/blocks/span.js, packages/@sanity/schema/src/legacy/types/object.js, packages/@sanity/schema/src/sanity/validation/types/block.js, packages/test-studio/schemas/blocks.js
- Support adding `icon` directly on `blockTypes`, `annotations` and  `decorators` in the same way we add icons on other types
- Resolve annotation icons from types/references in schema
=> Icons in blockeditor

packages/@sanity/base/src/util/draftUtils.js, packages/@sanity/base/test/draftUtils.test.js, packages/@sanity/desk-tool/src/pane/DocumentsListPane.js
This optimizes how we collate drafts and published into a single entry for display in document lists. Also moved the collate function into the common draftUtils package so that we can re-use it anywhere else it's needed.
The numbers I got when collating a list of 10474 items locally (average of around 10 samples):
*Before*: 142.15 ms
*After*: 18.47 ms
=> [base] Optimize and move drafts collate function to draft-utils

packages/@sanity/base/src/datastores/history/createHistoryStore.js, packages/@sanity/desk-tool/src/pane/Editor/Editor.js, packages/@sanity/desk-tool/src/pane/EditorPane.js, packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.js
When restoring a document to an earlier revision, it may have references to documents that no longer exists. This adds a check that removes any references to documents that no longer exists right before the restore is performed.
Moved most of the restore logic over into a `restore` method in the revision history store and cleaned up some frontend code as well.
=> [base] Remove nonexistent references when restoring to an earlier revision

packages/@sanity/default-layout/src/components/LoginStatus.js, packages/@sanity/default-layout/src/components/SideMenu.js, packages/@sanity/default-layout/src/components/styles/LoginStatus.css, packages/@sanity/default-layout/src/components/styles/SideMenu.css
In some cases the avatar image is broken, and the `alt` text is no very pretty. Uses a CSS-trick to show the initials of the user in the avatar circle instead.
=> [default-layout] Prettier styling of broken avatar image

packages/@sanity/base/sanity.json, packages/@sanity/base/src/components/ErrorHandler.js, packages/@sanity/base/src/components/SanityRoot.js, packages/@sanity/base/src/components/icons/CheckCircle.js, packages/@sanity/base/src/components/icons/CircleCheck.js, packages/@sanity/base/src/components/icons/Danger.js, packages/@sanity/base/src/components/icons/Info.js, packages/@sanity/components/sanity.json, packages/@sanity/components/src/buttons/styles/DefaultButton.css, packages/@sanity/components/src/selects/StyleSelect.js, packages/@sanity/components/src/snackbar/DefaultSnackbar.js, packages/@sanity/components/src/snackbar/SnackbarItem.js, packages/@sanity/components/src/snackbar/SnackbarProvider.js, packages/@sanity/components/src/snackbar/story.js, packages/@sanity/components/src/snackbar/styles/SnackbarItem.css, packages/@sanity/desk-tool/src/pane/DocumentsListPane.js, packages/@sanity/desk-tool/src/pane/Editor/Editor.js, packages/@sanity/desk-tool/src/pane/History.js, packages/@sanity/form-builder/src/inputs/FileInput/FileInput.js, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.js, packages/@sanity/form-builder/src/inputs/common/UploadTarget/createUploadTarget.js
- Add new snackbar design and functionality for better feedback on user actions
- Makes queuing of snackbars in the studio possible (current max stack of 3)
=> [components] Add new snackbars

packages/@sanity/validation/src/validators/slugValidator.js
When you have fields within an array that contain slugs, the uniqueness check doesn't currently work. In addition to not actually working, it raises a few interesting questions about what should be considered as unique. Unique within the array? Unique within all documents of the same type, within the array?
For now, I've disabled the uniqueness check and warned when this happens. In the future, we may be able to provide a better check that works either on array level or globally, but we need a better validation machine that batches requests and makes sure it doesn't fire too many checks at once.
=> [validation] Disable uniqueness check for fields in arrays

packages/@sanity/server/src/configs/webpack.config.dev.js, packages/@sanity/server/src/configs/webpack.config.js
I should have caught this in the code review: https://travis-ci.org/sanity-io/sanity/jobs/570811472
We should only alias react-dom in development. In production, we want to use the regular react-dom.
=> [server] Only alias react-dom in development

packages/@sanity/components/src/snackbar/SnackbarItem.js, packages/@sanity/components/src/snackbar/styles/SnackbarItem.css, packages/@sanity/desk-tool/src/pane/DocumentsListPane.js, packages/@sanity/desk-tool/src/pane/Editor/Editor.js, packages/@sanity/desk-tool/src/pane/History.js
- Fixed some snacks using the wrong snack kind (danger)
- Fixed the icon prop type in the snackbar item's action prop
- Fixed scrollbar appearing when a snackbar is entering
=> Fix issues with the snacker

packages/@sanity/base/src/styles/body.css, packages/@sanity/base/src/styles/variables/typography.css
- Sets the base font-size to 16px
- Makes it possible to override the base font-size for the studio
=> Make base font-size overridable

packages/@sanity/form-builder/src/FormBuilderErrorBoundary.js, packages/@sanity/form-builder/src/inputs/BlockEditor/SyncWrapper.js, packages/@sanity/form-builder/src/inputs/BlockEditor/index.js, packages/@sanity/form-builder/src/styles/FormBuilderErrorBoundary.css
Currently, if something goes wrong during the rendering of the portable text editor, the whole desk tool crashes. Because this happens in the case outlined in #1449, we need something to prevent it from fully crashing so the user can still restore other versions of the document, for instance.
What I ended up with was a very minimal but possibly reusable error boundary that is _currently_ only wrapped around the PT editor, but could potentially be included by default on the FormBuilderInput level (unless it has drawbacks in terms of performance and the like).
=> [form-builder] Add error boundary around portable text editor

packages/@sanity/base/jest.config.js, packages/@sanity/base/src/datastores/history/createHistoryStore.js, packages/@sanity/base/test/__snapshots__/history.test.js.snap, packages/@sanity/base/test/history.test.js, packages/@sanity/base/test/mocks/client.js
#1423 seems to have broken restoring of documents which included arrays. The culprit was in a tiny typo: `map(item)` vs `jsonMap(item)`.
While pursuing the issue, I refactored slightly to be able to test the method/functionality in question.  I also added a minor change which to me makes the code/result slightly more readable: instead of including `undefined` array elements and object values and relying on the JSON implementation to remove these, I explicitly filter them out.
=> [base] Fix references in arrays being nulled when restoring

packages/@sanity/base/src/components/ErrorHandler.js, packages/@sanity/components/src/snackbar/SnackbarItem.js
Currently some snackbars disappear too fast, particularly errors.
- Increased the default dismiss timeout (4s -> 5s)
- Increased the timeout for error snackbars (4s -> 8s)
=> [components] fix errors disappearing too fast

packages/@sanity/components/package.json, packages/@sanity/components/src/presence/colorHasher.js
This provides a fix for #1447 by resolving the actual value of `var(--brand-primary)` at runtime if it isn't already transpiled to a valid color in css import.
For now I think we should also make sure you can't override browserslists in new studios, so that we make sure our css gets properly transpiled. Currently if you have a browserslists config saying e.g. latest chrome, the studio gets visually borked due to lack of support for `color(var(...))` syntax
=> [components] Handle color hashing on non-transpiled css var() syntax

packages/@sanity/server/src/configs/postcss.config.js
This will ignore any browserslist config and always transpile customProperties/css variables syntax until we're on a webpack version that enables us to support a more up to date syntax.
See a description of the original issue in #1447 and the related PR #1462.
=> [server] Force transpiling of customProperties/css-variables syntax

packages/@sanity/form-builder/src/inputs/BlockEditor/index.js, packages/test-studio/schemas/blocks.js
The change in #1450 wrapped the Block/Portable Text editor in a function component. Since function components can't be given refs, this caused the form builder to fail when trying to set focus on the portable text input component (see #1456).
I'm afraid we're going to see a lot more of these errors going forward, since the whole React community is shifting towards function components. So we should probably reconsider how we do the focus management in the form-builder (and align with the recent work/proposal to add declarative focus management to React).
I'll see if I can whip up a separate PR improving the error message to hint about this particular case, but this should at least fix the issue at hand.
=> [form-builder] Wrap BlockEditor in forwardRef

packages/@sanity/components/src/history/styles/ListItem.modules.css
- Fix #1429: unreadable link in selected truncated history pane item
=> [components] fix link color in selected item (#1429)

packages/@sanity/base/src/styles/body.css, packages/@sanity/form-builder/src/inputs/DateInputs/styles/BaseDateTimeInput.css
- Make body use the font-family-base variable instead of the sans-serif variable for clearer and easier Studio customization
=> [base] use base font-family variable for body

packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createOperationToPatches.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createPatchToOperations.js, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/editLink1/input.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/editLink1/operations.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/editLink2/input.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/editLink2/operations.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/editLink3/input.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/editLink3/operations.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/editLink4/input.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/editLink4/operations.json
This will fix an issue where editing the text for an annotation (i.e. the link text) would not send the correct patch paths.
=> [form-builder] Block editor: Fix bug with editing annotated text

packages/@sanity/components/src/history/ListItem.js
The user list returned from `userStore` could potentially include `null` user objects. So guard against that in the history view.
=> [components] Guard against null users in HistoryListItem

packages/@sanity/default-layout/src/components/ToolSwitcher.js
No need to show the tool-switcher when there is only one tool.
=> [default-layoyt] Hide toolswitcher when no choices

packages/@sanity/default-layout/src/components/SanityStatus.js, packages/@sanity/default-layout/src/components/styles/SanityStatus.css
Improvements to the way we indicate that the Studio has available updates:
- Font size is now relative instead of fixed to 14px
- Package icon uses a colored circle to indicate severity level, and is labeled for accessibility
- A more accessible approach regardless of severity level and navigation bar background color (like when using custom Studio themes)
Further possible improvements to these changes:
- Position and size of indicator on package icon
- Colors indicating severity level
Examples, current vs. proposed changes:
=> [default-layout] improve studio module update indicator

packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/PastePlugin.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createOperationToPatches.js, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createPatchToOperations.js
If the first action in the document is pasting, a unset patch for the placeholder block was made, and it should not unset it, but remove the placeholder status (set block patch) instead.
This removed the need for https://github.com/sanity-io/sanity/pull/1473/commits/b93fa935a481623e0d20f6e74a03c0cead0b7a70, which is reverted.
=> [form-builder] Block editor: fix bug with dealing with placeholder onPaste

packages/@sanity/form-builder/src/inputs/BlockEditor/nodes/styles/Decorator.css
Code decorator has horizontal padding that in some situations seems like whitespace which is not really there.
=> [form-builder] Block editor: fix decorator horiz. padding

packages/@sanity/form-builder/src/inputs/ImageInput/styles/Asset.css
To make images/assets easier to see (and to see if an image is actually transparent) in the browse assets dialog, this adds the same white/grey checkered background to assets as the image input (fixes #1487).
Before:
After:
=> [form-builder] add checkered background for assets

packages/@sanity/google-maps-input/src/GeopointSelect.js, packages/test-studio/schemas/blocks.js
Fixes a case where the input wouldn't work inside of arrays because the lat/lng values would not be set, but the `_type` would be.
=> [google-maps-input] Merge value with defaults before setting lat/lng

packages/@sanity/cli/src/actions/init-project/initProject.js
(sorry about this, the other one closed and I can't reopen it)
Inform about /create when running `sanity init` and creating a new project.
```
print('Prefer web interfaces to terminals?')
print('You can also set up best practice Sanity projects with')
print('your favorite frontends on https://sanity.io/create\n')
```
=> [cli] inform about /create when init new project

packages/@sanity/client/README.md, packages/@sanity/client/src/data/dataMethods.js, packages/@sanity/client/test/client.test.js
This adds a client method for fetching multiple _entire_ documents in one go, using the `/doc` endpoint.
Usage: `client.getDocuments(['foo', 'bar']) => [{_id: 'foo', ...}, {_id: 'bar', ...}]`
Note: This adds a workaround for an issue with the `/doc` HTTP endpoint not yielding `null` values for nonexsting documents in the resulting array. This can lead to nasty bugs, e.g.:
`const [draft, published] = await client.getDocuments([draftId, publishedId])`
Without the workaround, this will assign the published document to the `draft` variable if the draft does not exists.
=> [client] Add client.getDocuments

packages/@sanity/form-builder/src/sanity/inputs/client-adapters/assets.ts
If you drag and drop a bunch of images to an array input, it currently breaks because the `withMaxConcurrency` function doesn't pass any options to the asset uploader, which causes it to crash when attempting to access `metadata` on the options.
This defaults the options to an empty object.
=> [form-builder] Make asset upload options optional

packages/@sanity/imagetool/src/ImageTool.js
On an image without any hotspot/crop, if you attempt to move the crop area, it'll crash with `cannot read "top" of undefined`.
This PR makes it fall back to using the default crop area if none is specified, which fixes the issue.
=> [imagetool] When limiting, use default crop if none specified

packages/@sanity/desk-tool/src/pane/styles/History.css
This makes the history pane background be calculated from the component background color, with a shade darker (2%) to match the previous gray light. This also makes it easier to customise and create themes for the Studio that look better.
=> [desk-tool] fix history pane background

packages/@sanity/form-builder/src/inputs/FileInput/FileInput.tsx, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.tsx
For file and image inputs, we seem to somewhere in the stack reject files that do not match the configured `accept` value, but we don't actually pass the accept value to the underlying file input.
This is confusing, as you'll be able to select files of any type, but they are silently ignored if they do not match. It also creates a less than ideal selection of files, especially on mobile devices.
This PR passes the configured accept value down to the file input, and also defaults to `image/*` for the image input - this will make mobile devices (at least Android) use a different mode.
=> [form-builder] Pass accepted mime types to input

packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createOperationToPatches.ts, packages/@sanity/form-builder/src/patch/primitive.ts
Is the block trying to be unset is a placeholder block in the editor, it should not produce unset patches (because it's not really there).
=> [form-builder] Fix invalid unset patch

packages/@sanity/schema/src/legacy/preview/createPreviewGetter.ts
This does not yield `Static title`:
```js
export default {
name: 'noTitleField',
title: 'No title field',
preview: {
prepare: () => ({title: 'Static title'})
},
fields: [
{
name: 'isChecked',
type: 'boolean',
title: 'Is checked?'
}
]
}
```
This works:
```js
export default {
name: 'noTitleField',
title: 'No title field',
preview: {
select: {},
prepare: () => ({title: 'Static title'})
},
fields: [
{
name: 'isChecked',
type: 'boolean',
title: 'Is checked?'
}
]
}
```
With this PR, the first example also works :)
=> [schema] Provide fallback for preview select if none is given

packages/@sanity/components/sanity.json, packages/@sanity/components/src/dialogs/PanePopover.js, packages/@sanity/components/src/dialogs/styles/PanePopover.css, packages/@sanity/components/src/snackbar/styles/SnackbarItem.css, packages/@sanity/desk-tool/src/components/BrokenReferences.js, packages/@sanity/desk-tool/src/components/ReferringDocumentsList.js, packages/@sanity/desk-tool/src/components/styles/BrokenReferences.css, packages/@sanity/desk-tool/src/components/styles/ReferringDocumentsList.css, packages/@sanity/desk-tool/src/utils/withInitialValue.js
Styled error dialogs that appear when document template references unpublished or missing documents.
**Comments**
Some color changes may still be coming, depending on what @mariuslundgard says.
- Styled error dialogs that appear when document template references unpublished or missing documents
**Checklist**
=> [desk-tool] Style broken references errors and warnings

packages/@sanity/cli/src/actions/init-project/initProject.js
After choosing options for creating a dataset, it can feel like the CLI stopped working because there is no indicator of what is happening (dataset is being created).
This adds a spinner and a message to let you know that your dataset is being created.
Also improved some of the prompts with clearer messaging and a default project name to avoid ugly `displayName` error message.
N/A
**Checklist**
=> [cli] Add spinner for dataset creation

packages/@sanity/cli/src/actions/init-project/createManifest.js, packages/@sanity/cli/src/versionRanges.js
Maybe?
When creating a new project from a template in the CLI, the vision plugin is not installed by default.
Makes the vision plugin be installed in templates by default
- When creating a project from the CLI using a template, the vision plugin is now installed by default.
**Checklist**
=> [cli] install vision in CLI templates by default

packages/@sanity/validation/src/validateDocument.js
When adding an empty string or a numeric 0 to an array, the current validation check naively returns an "unable to resolve type for item" error. 
This PR fixes the above issue by not using a loose falsey check but instead checking for undefined/null values. 
Fix bug where empty strings in arrays would yield "unable to resolve type for item".
**Checklist**
=> [validation] Fix "unable to resolve type" for array items

packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/PastePlugin.ts
Fixes a bug where an error occurred pasting fragment into a placeholder block.
=> [form-builder] Block editor: fix paste controller bug

packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/html.ts, packages/@sanity/block-tools/src/HtmlDeserializer/rules/html.ts, packages/@sanity/block-tools/src/util/normalizeBlock.ts, packages/@sanity/block-tools/test/tests/HtmlDeserializer/annotations/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/decorators/input.html, packages/@sanity/block-tools/test/tests/HtmlDeserializer/decorators/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/githubIssue/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/whitespace2/input.html, packages/@sanity/block-tools/test/tests/HtmlDeserializer/whitespace2/output.json, packages/@sanity/block-tools/test/tests/converters/editorValueToBlocks/leafNode/index.ts, packages/@sanity/block-tools/test/tests/converters/editorValueToBlocks/leafNode/input.json, packages/@sanity/block-tools/test/tests/converters/editorValueToBlocks/leafNode/output.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/removeLink/input.json, packages/@sanity/form-builder/test/patching/blocks/tests/operationsToPatches/removeLink/operations.json
This will a couple of HTML deserialization and PT normalization issues.
* Keep space between links https://github.com/sanity-io/sanity/issues/1493
* Remove leftover markDefs (https://github.com/sanity-io/sanity-priv/issues/1632)
* Fix bug where trailing text after an annotation got lost in the remove link operation.
=> Fix serialization issues

packages/@sanity/block-tools/src/HtmlDeserializer/helpers.ts
This prevents program from crashing when an image is not contained within a block, but parent is __block
=> add check for prior __block

packages/@sanity/code-input/src/CodeInput.js, packages/@sanity/code-input/src/PreviewCode.css, packages/@sanity/code-input/src/PreviewCode.js
- Fixes an issue where the code input preview tried to load an JS file that does not exist.
- Minor linting fixes
- pointer-events: none on the ace editor in preview, to prevent ace from triggering edits. Also makes it easier to drag the block around
=> [code-input] bugfix: Support groq and fallback in preview

packages/@sanity/base/src/styles/variables/globals.css, packages/@sanity/default-layout/src/components/Branding.js, packages/@sanity/default-layout/src/components/styles/Branding.css, packages/@sanity/default-layout/src/components/styles/NavBar.css
When using a custom brand logo component that returns an image or SVG, the sizing is botched.
This makes images and SVGs display correctly in terms of size and how they take up space. Works when returning an img and svgs  in a custom brand logo component, as well as anything else.
- Improved styling and sizing when using a custom logo
**Checklist** 
**Other comments**
There seem to be a chrome glitch when it comes to SVGs and the height property. The SVG won't fill the space as it should if the logo is long (compared to round or squared), but when you toggle on and off the height in dev tools, it works as expected. Not sure how …
=> [default-layout] fix brand logo sizing

packages/@sanity/block-tools/README.md, packages/@sanity/block-tools/changelog.md, packages/@sanity/block-tools/src/converters/blocksToEditorValue.ts, packages/@sanity/block-tools/src/converters/editorValueToBlocks.ts, packages/@sanity/block-tools/src/util/normalizeBlock.ts, packages/@sanity/block-tools/test/tests/util/normalizeBlock.test.ts, packages/@sanity/form-builder/src/inputs/BlockEditor/BlockExtrasOverlay.tsx, packages/@sanity/form-builder/src/inputs/BlockEditor/Editor.tsx, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createBlockActionPatchFn.ts, packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createEmptyBlock.ts
The block normalization function should normalize span marks and remove those who aren't allowed by the schema. This includes both decorator marks and annotation marks.
In order to differentiate between decorator marks and annotation marks, we need to know which decorator names are allowed in the schema.
Fixes https://github.com/sanity-io/sanity-priv/issues/1632
=> Normalize decorators

packages/@sanity/base/src/components/DevServerStatus.js, packages/@sanity/base/src/components/SanityRoot.js
When the dev server disconnects, there is no way of knowing this happened by looking at the Studio in the browser. Can be confusing, if changes are being made and you don't understand why the Studio isn't updating.
This adds a snackbar to show that the dev server was disconnected and needs to be restarted to see any changes made to the Studio.
- If your development server is disconnected/stops working, the Studio will now show you a notification to let you know that you should restart with `sanity start` to see your latest changes.
**Checklist**
=> [components] add dev server status snackbar

packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/OnFocusPlugin.ts
There is a very annoying bug in the version of `slate-react` we are using that tries to scroll to focus in invalid situations. Typically where focus is set programatically. By aborting the `onFocus` plugin chain the built in onFocus functions in `slate-react` doesn't kick in.
This was recently fixed in `slate-react`: https://github.com/ianstormtaylor/slate/pull/3019 and we should upgrade the Slate version when time.
I'm still not 100% certain where we are in the plugin chain by setting onFocus as prop on the component, as opposed to the `onFocus` plugins we are running ourselves  *This needs to be checked up upon before merging.*
**Note for …
=> [form-builder] prevent slate-react built in scrolling

packages/@sanity/google-maps-input/README.md
This improves the README.md of the Google Maps input plugin with installation instructions, and to get the API key.
This PR adds more helpful instructions for how to use this plugin.
**Checklist**
=> Add installation instructions for Google Maps plugin

packages/@sanity/structure/src/DocumentList.ts, packages/@sanity/structure/src/GenericList.ts, packages/@sanity/structure/src/Intent.ts, packages/@sanity/structure/src/List.ts, packages/@sanity/structure/test/__snapshots__/documentTypeListItems.test.ts.snap
When you use filters for document lists such as `_type in [$foo]`, the inferring of schema type fails, which makes intent handlers fail to recognize they can handle the intent, as well as initial value templates from appearing automatically. 
This PR picks up on  type filters using the `in` operator, and also expands to match all specified types. This enables document lists with filters such as  `_type == "foo" || _type == "bar"` to pick up initial value templates from both `foo` and  `bar`, as well as allowing both schema types to be recognized by the intent handler. 
Fixes #1567 
Improve type inference for document list …
=> [structure] Improve type inference from filters

packages/@sanity/core/src/actions/deploy/deployAction.js, packages/@sanity/preview/src/createPathObserver.ts
This fixes two issues:
1. `sanity deploy graphql` vs `sanity graphql deploy`. I can't see someone actually wanting to deploy a `graphql` directory, so I decided to just error out when specifying that.
2. `sanity deploy somedir` wouldn't actually use `somedir` unless `--no-build` was passed. Very confusing.
=> [core] Deploy: use passed SOURCE_DIR even when building

packages/@sanity/cli/bin/sanity
Apparently some of our upstream dependencies have started using object rest spread, which is only supported in node 8.6 and higher. While we would ideally use a different dependency, it's getting progressively harder to find alternatives with a better engine support.
Given that node 8 will be out of maintenance in a month and a half, I feel like it's OK to raise the minimum version requirement to 8.6 or higher (we'll bump to v10 in January, I suspect). Thoughts?
=> [cli] Require node version 8.6 or higher

packages/@sanity/core/src/commands/graphql/deleteGraphQLAPICommand.js, packages/@sanity/core/src/commands/graphql/deployGraphQLAPICommand.js, packages/@sanity/core/src/commands/graphql/graphqlGroup.js
Since the GraphQL API is in open beta, it doesn't make sense to hide the commands from the help output anymore.
=> [core] Include GraphQL commands in CLI help output

packages/@sanity/components/src/snackbar/DefaultSnackbar.js, packages/@sanity/components/src/snackbar/SnackbarProvider.js
I have a case where I'm rendering a snackbar item and later want to update the message while it's being displayed. Currently, nothing happens if you send new properties to the snackbar component.
With this change, the new properties are reflected in the providers state/queue.
I also took the liberty of:
- Rendering `null` and/or fragments instead of `<div />`, to cut down on the number of DOM-elements actually being generated
- Lifting `isCloseable` property through to the snackbar item
=> [components] Make snackbar items updateable

packages/groq/src/groq.js
We should probably add a specific  babel config here soon, but for now this should do the trick.
=> [groq] Don't use arrow functions - fixes IE11 compatibility

packages/@sanity/desk-tool/src/utils/parsePanesSegment.js
This fixes a regression introduced in v0.144.0 that broke editing of a document that had an `_id` that included a dot character (`.`)
This fixes a regression introduced in v0.144.0 that broke editing of a document that had an `_id` that included a dot character (`.`)
**Checklist**
=> [desk-tool] Fix issue with path segments getting stripped out of from ids containing `.`

packages/@sanity/desk-tool/src/pane/Pane.js
When switching between documents from the search bar (and with no document list panes open), the portable text editor retains the value from the previous document.
I wasn't able to figure out the root cause, but this PR at least provides a quickfix by changing the key for EditorPane, triggering an unmount + remount with new id.
This provides a fix for a bug that affected portable text fields: When switching between documents from the search bar (and with no document list panes open), the portable text editor would retain the value from the previous document.
**Checklist**
=> [desk-tool] Wrap EditorPane and use document id as key to force reload

packages/@sanity/components/src/loading/Spinner.js, packages/@sanity/components/src/loading/story.js
The `Spinner` component currently blindly renders `message`, but it does not accept anything but a string. I have a case where I want to render a message with `<strong>Some message</strong>`. Let me know if this is "bad behavior".
=> [components] Spinner: Allow passing children instead of message

packages/@sanity/base/package.json, packages/@sanity/base/src/components/DevServerStatus.js, packages/@sanity/server/package.json, packages/@sanity/server/src/browser/hot-client.js, packages/@sanity/server/src/browser/process-update.js, packages/@sanity/server/src/configs/webpack.config.dev.js
I liked the "you are disconnected" dev server status message so much that I wanted to also allow it to show  messages based on the current build status. When you save a file,  there is currently no indication that the server is building a new bundle until it's completed. Also, sometimes it cannot hot-reload the changes and you need to open up the dev console to actually see what's going on.
Unfortunately, the events I needed to subscribe to were not exposed by the webpack hot middleware client, so I've reimplemented the client and exposed a thin "eventbus" on the window when in development mode, which you can use to subscribe to events.
With this change, the dev server status will show a "Building..."-spinner in a snackbar item while it's working, which is removed when the build …
=> [server] Implement custom HMR client for in-studio build status

packages/@sanity/core/src/actions/graphql/extractFromSanitySchema.js
This PR fixes the generation of array and reference types at the top-level. Currently they fail with mysterious messages, such as
> Bad Request - Field "stuff" of type "Author" claims to be of type "Array" which is not a declared type
Tested on the Gatsby blog and portfolio starters and seems to work as expected.
=> [core] Fix top-level references/array types

CONTRIBUTING.md, packages/@sanity/block-tools/package.json, packages/@sanity/check/package.json, packages/@sanity/check/src/bin.js, packages/@sanity/cli/src/versionRanges.js, packages/@sanity/components/package.json, packages/@sanity/data-aspects/package.json, packages/@sanity/default-layout/package.json, packages/@sanity/default-login/package.json, packages/@sanity/form-builder/package.json, packages/@sanity/google-maps-input/package.json, packages/@sanity/rich-date-input/package.json, packages/@sanity/server/package.json, packages/@sanity/state-router/package.json
The `npm run test-all` is a little flaky due to a dependency in `in-publish`. It doesn't say anywhere that you also need to build the repository before running tests.
This PR completely removes the usage of the `in-publish` package in favor for `prepublishOnly`, as that's what was missing a while back.
- Replace `in-publish` package with `prepublishOnly` NPM step
- Reflect that `npm run build` must be run before running the tests as some tests are running against compiled assets
**Checklist**
=> [chore] Replace in-publish with prepublishOnly

packages/@sanity/client/package.json, packages/@sanity/core/package.json, packages/@sanity/core/src/actions/build/compressJavascript.js
Terser has had a bunch of fixes and performance improvements since we last upgraded, so it makes sense to try and follow along.
In addition to this, when minifying javascript for `sanity build`/`sanity deploy`, we currently do the minification in-process, which blocks the "minifying" spinner in the CLI. This PR changes this to simply spawn the terser binary out-of-process.
=> [core] Upgrade to Terser 4.4, execute out-of-process

packages/@sanity/desk-tool/src/pane/DocumentsListPane.js
Codebase has a constant defined that is never referenced.
Motivation is to make repo more maintainable by removing something that isn't used.
Remove declaration of `noop` that is never used.
**Checklist**
=> [desk-tool] Remove extraneous `noop` declaration

packages/@sanity/structure/src/Document.ts, packages/test-studio/src/deskStructure.js
Regression in v0.145.0: the `title` attribute was removed from the editor/document node.
=> [structure] Reintroduce title attribute to document node

packages/@sanity/structure/src/Component.ts, packages/@sanity/structure/src/views/ComponentView.ts, packages/@sanity/structure/test/Component.test.ts
The `S.component()` and  `S.view.component()` methods tried to be smart and infer the title/id from the component display name. What I had not factored into the equation is that when minifying the javascript bundle, these display names becomes absolutely useless (`SomeAwesomePreview` becomes `n`, for instance).
This PR removes this inferring logic and instead relies on users explicitly specifying a stable ID, which seems like a better choice anyway.
=> [structure] Remove auto-inferring of ID based on function name

packages/@sanity/desk-tool/src/DeskTool.js, packages/@sanity/desk-tool/src/tool.js
The "fallback editor" URL and pane handling changes significantly in 0.145.0, but it seems I forgot to account for the old fallback URLs potentially being bookmarked/integrated somewhere.
With this PR, we handle the `/edit/type/documentId` route and redirect to the new format.
=> [desk-tool] Redirect old edit URLs to new fallback edit route

packages/@sanity/validation/src/validateDocument.js
If you have an array with multiple object types where _one of them_ does not have a `name` property, the validator incorrectly picks the first declared object member of the array and uses it's validation rules.
This PR fixes this by using a more specific check and matching the first candidate without a name. This is safe because we don't allow more than a single unnamed object member within an array, since they can't be told apart.
Fixes #813
=> [validation] Fix unnamed object type matching incorrect array member

packages/@sanity/desk-tool/src/pane/DocumentPane.js
When you use the keyboard shortcut for toggling the inspector on an empty (non-existent) document, it crashes when attempting to access the `_type` property of a snapshot that is  `null`.
This PR adds a check that prevents the inspect flag from being toggled when there is no snapshot.
Fixes #1559
=> [desk-tool] Prevent showing document inspector on no snapshot

packages/@sanity/schema/src/sanity/validation/createValidationResult.ts, packages/@sanity/schema/src/sanity/validation/types/array.ts
We currently don't give a good, meaningful error message when you model multidimensional arrays in your schemas.
This PR introduces a basic check for this case. Help article has been written to explain how you might go about remodelling your schema (wrap it in an object).
Fixes #452
=> [schema] Guard against multidimensional arrays

packages/@sanity/mutator/package.json
The mutator uses quite a long time to "boot up" the tests, especially in a CI-environment, which leads to flakey tests when it sometimes goes over the 30s default timeout for tap.
~This PR adds the `-T` flag ("no timeout") to the mutator tests and should hopefully remove the flakey CI results.~
This PR increases the timeout to 2 minutes (120 seconds) through the `-t` flag ("timeout") for the mutator tests and should hopefully remove the flakey CI results.
=> [mutator] Increase test timeout to 120 seconds

packages/@sanity/structure/src/Document.ts, packages/@sanity/structure/src/views/ComponentView.ts, packages/@sanity/structure/src/views/FormView.ts, packages/@sanity/structure/src/views/View.ts, packages/@sanity/structure/test/ComponentView.test.ts, packages/@sanity/structure/test/Document.test.ts, packages/@sanity/structure/test/FormView.test.ts, packages/@sanity/structure/test/__snapshots__/ComponentView.test.ts.snap, packages/@sanity/structure/test/__snapshots__/Document.test.ts.snap, packages/@sanity/structure/test/__snapshots__/FormView.test.ts.snap
I discovered by chance that we did not validate the the ids for views were unique within it's parent document node. This has the unfortunate side-effect of not being able to select more than the first view which share the ID. 
This PR adds validation for this, along with tests to ensure that the serialization of structure view nodes work as intended.
=> [structure] Enforce unique IDs for views, add serializer tests

packages/@sanity/structure/src/DocumentTypeList.ts, packages/@sanity/structure/src/documentTypeListItems.ts, packages/@sanity/structure/test/DocumentTypeList.test.ts, packages/@sanity/structure/test/__snapshots__/DocumentTypeList.test.ts.snap
While most structure nodes accept an object form specification, the  `documentTypeList()` method does not - instead it accepts a string. This is fine for most cases, but sometimes you may want to override certain aspects of the default setup without using the "builder" approach (`.child(differentChildResolver)`). 
With this PR, the method now accepts _either_ a string _or_ an object specification.
=> [structure] Allow passing object spec to documentTypeList()

packages/@sanity/form-builder/src/utils/isEmpty.ts
Same, but with a bunch of redundant stuff.
`null` values were going down the isEmptyObject code path. There was a check that type !== null (but it never will be, I think the intent was to check the value not the type).
Just exit early for null cases and stop worrying about them later on in the function.
isEmptyArray was checking if the value was undefined, which we already know its not.
Same with isEmptyPrimative; we already know its not undefined, why check again.
Tidy up isEmpty function.
**Checklist**
=> [form-builder] Cleanup isEmpty function

packages/@sanity/desk-tool/package.json, packages/@sanity/desk-tool/src/DeskTool.js, packages/@sanity/desk-tool/src/components/IntentResolver.js, packages/@sanity/desk-tool/src/pane/DocumentPane.js, packages/@sanity/desk-tool/src/tool.js, packages/@sanity/desk-tool/src/utils/calculatePanesEquality.js, packages/@sanity/desk-tool/src/utils/resolvePanes.js, packages/@sanity/desk-tool/test/mocks/styles.js, packages/@sanity/state-router/src/RouterContext.ts, packages/@sanity/state-router/src/components/RouteScope.tsx, packages/@sanity/state-router/src/components/RouterProvider.tsx, packages/@sanity/state-router/src/components/types.ts, packages/@sanity/state-router/src/index.ts
The desk tool uses a very basic approach in trying to figure out where an intent (edit/create) can be handled. Currently it looks at the open panes and recursively (depth first) calls  `canHandleIntent` on the structure nodes until it finds one that returns true. When it does, it navigates to it.
If no pane says it can handle the intent, we use a "fallback route" (`__edit__${documentId}`) which makes sure we can _always_ handle editing/creating a document, regardless of structure setup. 
What it fails to do is to look _upwards_, in other words: check structure nodes that _are not_ open. The reason for this is that the intent checker is on the _resolved_ child, which we can't statically analyze/get to without passing the child handler an ID and seeing what it returns, which could possibly …
=> [desk-tool] Implement naive, shallow, async intent resolver

packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.tsx
The asset source plugin would not know about the document. 
This will send in the document as prop to the asset source plugins, which can enable some additional functionality.
Asset source plugins now will receive the document as prop.
**Checklist**
=> [form-builder] Send document to asset source plugin

packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.tsx, packages/@sanity/form-builder/src/sanity/inputs/SanityImageInput.tsx
This is restoring #1628  which was reverted due to a circular import issue.
In this PR `withDocument` is wrapped around `SanityImageInput` (the root) and not the `ImageInput` itself, which does not lead to the previous issues.
It's already written.
Was reverted due to bug.
**Checklist**
=> [form-builder] Send document to asset source plugin (restore #1628)

packages/@sanity/cli/src/actions/init-plugin/pluginTemplates.js
Adds a [template](https://github.com/sanity-io/plugin-template-asset-source) that makes it easier to get started with creating a custom asset source plugin!
- Create asset source plugins from the CLI with `sanity init plugin` and select the custom asset source option
**Checklist**
=> [cli] add template for custom asset source plugin

packages/@sanity/cli/src/actions/init-plugin/bootstrapFromTemplate.js
When bootstrapping a plugin from a template URL,  we were only checking for network errors, not HTTP errors. This makes it hard to debug problems such as a 404 response from the server, since it would end up with the hopeless error message of:
> Error: Could not find `package.json` in template
This adds rejection logic based on the HTTP status code.
=> [cli] Reject template download if statusCode is not 2xx

packages/@sanity/structure/src/DocumentList.ts, packages/@sanity/structure/test/__snapshots__/DocumentList.test.ts.snap
As outlined in #1633, the following structure does not get a schema type set:
```js
S.documentList()
.title('Unspecified books list')
.menuItems(S.documentTypeList('book').getMenuItems())
.filter('_type == $type')
.params({type: 'book'})
```
While this shouldn't normally cause any problems, in this case we can actually infer it based on the filter/parameter, which saves us from having to resolve it further down the stack.
=> [structure] Try to infer schema type from filter in document lists

packages/@sanity/schema/src/sanity/groupProblems.ts, packages/@sanity/schema/src/sanity/validation/createValidationResult.ts, packages/@sanity/schema/src/sanity/validation/types/file.ts, packages/@sanity/schema/src/sanity/validation/types/image.ts, packages/@sanity/schema/src/sanity/validation/types/object.ts
There is currently no validation for an incorrectly defined `fields` property on file and image types. This PR reuses the fields validation from `object`, and also adds a type check for each field entry (ensuring it's an object before attempting to validate its properties).
I also fixed an issue where a `visitContext` was passed to the `visit()` method instead of an index, which resulted in field paths with `objectObject` in them 🤔
=> [schema] Validate file, image schema fields

packages/@sanity/server/src/browser/process-update.js
Sometimes the hot module reloading cannot find a module in it's module map - when this happens the `process-update` script fails because it tries to split a string which is actually `undefined`. We only use this to display which modules have been updated,  so it's non-critical that the path is correct.
This PR checks for this case and returns `<unknown>` should we not be passed a path name.
=> [server] Fix potential crash when attempting to normalize module path

packages/@sanity/desk-tool/src/utils/withInitialValue.js, packages/test-studio/src/deskStructure.js
Given the following structure:
```js
S.documentList()
.title('Unspecified books list')
.menuItems(S.documentTypeList('book').getMenuItems())
.filter('_type == $type')
.params({type: 'book'})
```
You may end up in a situation where the automatically generated editor has the schema type value `*`, which should be resolved by the desk tool to the correct type (structure doesn't figure out that this pane holds a specific schema type, since it's not set using `schemaType(someTypeName)`/`documentTypeList(someTypeName)`.
With this PR, we use the template parameter to resolve the schema type to use if none is explicitly defined.
=> [desk-tool] Resolve document type from template if available

packages/@sanity/desk-tool/src/pane/DocumentPane.js, packages/@sanity/desk-tool/src/pane/Editor/FormView.js, packages/@sanity/desk-tool/src/pane/documentPaneFooterActions.js, packages/@sanity/structure/src/DocumentList.ts
After the editor => document + pane refactoring work in v0.145.0, certain of the experimental action affordances were not accounted for.
This PR addresses these points:
- Initial value templates were listed in panes even when the `create` action was disabled
- Publish button was shown even when `publish` action was disabled
- Publish action could be triggered through hotkey even when `publish` action was disabled
- Form was not set to read-only for new documents even with `create` action disabled
- Creating new documents could (theoretically) be done by triggering `onChange` in an input component even when `create` action was disabled
There may be more edge-cases that are unaccounted for, but given that this is an _experimental_ feature, I think this should at least address the …
=> [desk-tool] Fix unhandled experimental actions

packages/@sanity/desk-tool/src/contexts/PaneRouterContext.js, packages/test-studio/src/previews/developer/DeveloperPreview.js
There is currently no way to set the payload of a pane. This PR adds the missing  `setPayload` method. Note that payloads are undefined by default, and can be any JSON value; thus you should always make sure the payload _exists_ before attempting to use it.
Also added an example of how to use the method in the test-studio.
=> [desk-tool] Add missing `setPayload` method to pane router context

packages/@sanity/cli/src/CommandRunner.js, packages/@sanity/cli/src/actions/init-project/initProject.js, packages/@sanity/cli/src/cli.js, packages/@sanity/cli/src/util/clientWrapper.js, packages/@sanity/cli/src/util/getUserConfig.js, packages/@sanity/core/package.json, packages/@sanity/core/src/actions/build/buildStaticAssets.js, packages/@sanity/core/src/actions/config/reinitializePluginConfigs.js, packages/@sanity/core/src/actions/exec/configClient.js, packages/@sanity/core/src/actions/exec/execScript.js, packages/@sanity/core/src/actions/start/startAction.js, packages/@sanity/plugin-loader/loader.js, packages/@sanity/resolver/src/readManifest.js, packages/@sanity/resolver/src/resolvePlugins.js, packages/@sanity/util/package.json, packages/@sanity/util/src/getConfig.ts, packages/@sanity/util/src/reduceConfig.ts, packages/@sanity/webpack-integration/package.json, packages/@sanity/webpack-integration/src/v3/index.js, packages/@sanity/webpack-loader/src/partLoader.js
There are many cases where you might want to override the Sanity project ID and dataset which is defined in `sanity.json`. Common use cases is having a different dataset for development/staging/production, building the same studio for many different project IDs in a CI-workflow etc. The common way people want this to work is to defined environment variables.
With this PR, this is now possible by defining `SANITY_STUDIO_API_DATASET` and `SANITY_STUDIO_API_PROJECT_ID`. 
We currently have no way of passing environment variables to the javascript bundle. For instance, an agency might want to provide the same base schema and studio for many different clients, but alter both the project ID / dataset as well as things inside the bundle. 
With this PR, all environment variables starting with …
=> [all] Allow setting studio environment variables

packages/@sanity/desk-tool/src/pane/DocumentPane.js, packages/@sanity/desk-tool/src/pane/UserComponentPane.js, packages/@sanity/structure/src/Component.ts, packages/@sanity/structure/src/views/ComponentView.ts, packages/@sanity/structure/test/Component.test.ts, packages/@sanity/structure/test/ComponentView.test.ts, packages/@sanity/structure/test/Document.test.ts, packages/@sanity/structure/test/DocumentList.test.ts, packages/@sanity/structure/test/DocumentListItem.test.ts, packages/@sanity/structure/test/DocumentTypeList.test.ts, packages/@sanity/structure/test/FormView.test.ts, packages/@sanity/structure/test/List.test.ts, packages/@sanity/structure/test/ListItem.test.ts, packages/@sanity/structure/test/MenuItem.test.ts, packages/@sanity/structure/test/__snapshots__/Component.test.ts.snap, packages/@sanity/structure/test/__snapshots__/ComponentView.test.ts.snap
This PR introduces the `options()` method on `S.component()` and `S.view.component()` - allowing you to pass arbitrary options through to the view layer from the structure definition.
Example:
```js
function MyReactComponent(props) {
return <div>{props.options.arb}</div>
}
S.component(MyReactComponent)
.id('that-custom-thing')
.title('My custom thing')
.options({arb: 'itrary'})
```
Also discovered that the tests were not doing a good job at testing immutability of setter methods, so I fixed those within this PR as well.
=> [structure] Allow setting options on component, component view

packages/@sanity/form-builder/src/inputs/Slug/SlugInput.tsx, packages/@sanity/util/paths.d.ts, packages/test-studio/schemas/experiment.js
Quite often you'll want to reference a property on the parent of the slug, especially when it is nested. Right now, we only pass the parent path and the document, which requires a user to look up the parent using something like lodash's `_.get()`. The issue is that we also pass keyed path segments (`{_key: 'abc123'}`) which makes it needlessly complicated to do inside of arrays.
With this PR, we pass both `parent` and `parentPath` to the `source` function.
=> [form-builder] Pass parent object to slug source function

packages/@sanity/desk-tool/src/pane/DocumentPane.js, packages/test-studio/src/deskStructure.js
The component view was being passed the options of the _pane_ instead of the _view_. This fixes that.
=> [desk-tool] Fix bug where pane options would be passed to view

packages/@sanity/core/src/actions/graphql/deployApiAction.js
If a plugin config is missing and you try to run `sanity graphql deploy`, you might end up with a crash if something in the runtime path tries to load the configuration. This PR ensures we initialize the plugins before the deploy command is run.
=> [core] Initialize plugin configs before resolving GraphQL schema

packages/@sanity/export/src/AssetHandler.js, packages/@sanity/export/src/requestStream.js
Currently we are only retrying asset _download_ errors, not _connection_ errors.
In addition to this, the connection errors did not have any rejection handler, so the export would continue even if an asset failed to download, leading to potentially missing assets.
This PR fixes both of these issues.
=> [export] Retry assets on connection errors

packages/@sanity/form-builder/src/inputs/BlockEditor/Editor.tsx
Blocks returned from a custom paste handler is not normalized. This can lead to errors (missing keys etc). We should totally normalize them, before inserting them into the block array.
Blocks are now normalized so that they are always "right", and the end user doesn't have to worry about it.
Fix a bug where blocks returned from a custom paste handler in the portable text editor was not normalized.
**Checklist**
=> [form-builder] Normalize blocks received from custom paste handler

CONTRIBUTING.md, packages/@sanity/client/src/assets/assetsClient.js
Documentation change does not impact behavior.
Updated documentation to fix spelling errors.
**Checklist**
=> [@sanity/client] Fix spelling errors

packages/@sanity/desk-tool/src/pane/Editor/FormView.js, packages/test-studio/sanity.json, packages/test-studio/src/components/AfterEditorComponent.js
Fixes a bug where using the `part:@sanity/desk-tool/after-editor-component` part will crash the desk tool if the currently viewed document is not yet published.
=> [desk-tool] Fix deprecated part crashing on unpublished documents

packages/@sanity/core/src/actions/graphql/deleteApiAction.js, packages/@sanity/core/src/actions/graphql/deployApiAction.js, packages/@sanity/core/src/commands/graphql/deleteGraphQLAPICommand.js, packages/@sanity/core/src/commands/graphql/deployGraphQLAPICommand.js
The CLI defaults to use the `default` tag when deploying GraphQL endpoints.
When migrating schemas, it's very useful to specify a custom tag and not break the existing endpoint.
This PR only merges to the `gql-tag-option` as there's more to do in regards to handle error messages from the GraphQL service.
This change makes it possible for developers to provide a custom tag when deploying their GraphQL endpoints. This to either migrating to a new endpoint if the new schema contains breaking changes.
**Checklist**
=> [core] Add a tag option when interacting with GraphQL endpoints

packages/@sanity/base/src/util/draftUtils.js
#1422 introduced a change of behavior in `collate()`, where the order of the passed documents would not be maintained anymore.
I'm not sure if this was intentional, but there is code that depends on the order currently - the desk tool, when showing a list of documents ordered by a specific field, for instance.
This PR switches from using an object (which does not guarantee order) + Object.values, to using a Map - which is guaranteed to maintain order.
=> [base] Maintain order of documents when collating drafts/published

packages/@sanity/form-builder/src/inputs/FileInput/FileInput.tsx, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.tsx
Currently, if you have a file or an image field with a selected asset, then click the "remove" button, the only thing that is unset is the `asset` property. This leads to a dangling `_type` property, which results in weird results in frontends that assume it'll also have an `asset`.
In addition to this, the image input does not currently clear the `crop` and `hotspot` properties (though they are cleared when selecting a new asset, luckily).
This PR checks whether or not the "container" object is "empty" after unsetting the asset: in other words, does it have any properties that are not `_type`, `_key`, `_upload`? For the image type we also consider  `crop` and `hotspot` to be unset, as they don't make sense for the next asset to be selected. If there are no other properties present on the …
=> [form-builder] Unset empty object when removing asset

packages/@sanity/base/src/search/weighted/createWeightedSearch.js, packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx, packages/@sanity/form-builder/src/sanity/inputs/client-adapters/reference.ts, packages/@sanity/form-builder/src/utils/withValuePath.tsx, packages/@sanity/schema/src/sanity/validation/createValidationResult.ts, packages/@sanity/schema/src/sanity/validation/types/reference.ts, packages/test-studio/schemas/references.js
Sometimes, you may want to be more specific about which documents to reference than just the document type. This is a basic implementation where you can pass a `filter` and an optional `filterParams` in the `options` object of reference fields.
Let the discussion commence!
=> [form-builder] Support additional filter to reference input

packages/@sanity/base/src/components/QueryContainer.js, packages/@sanity/desk-tool/src/pane/DocumentsListPane.js, packages/@sanity/desk-tool/src/pane/InfiniteList.js, packages/@sanity/desk-tool/src/pane/styles/InfiniteList.css
Document lists with a large number of documents are currently pretty slow to load. At some point we want to provide a scrolling window implementation that we've talked about for a while.
This is a temporary workaround until we can get around to that implementation, however. In essence, it:
- Loads only the 100 first documents matching the query
- Waits for the user to scroll half way down in that list
- Starts loading the "full" list (without clearing the list while loading)
- Re-renders the list with the "full" document set, which should usually be an add-only operation
I'm putting "full" in quotes because we were previously loading up to 50 000 document IDs, while we're now stopping at 2000. Even this seems excessive, as I/we can't see a legitimate reason for using such an enormous list …
=> [desk-tool] Optimize loading of large lists

packages/@sanity/default-layout/src/components/NavBar.js, packages/@sanity/default-layout/src/components/NotFound.js, packages/@sanity/default-layout/src/components/SpaceSwitcher.js
Because we can't guarantee that all code in the studio will respect the "new" space when switching, a "quick-fix" which this PR implements simply reloads the studio after the URL has changed.
In addition, I've fixed the "root" links within the default layout to include a space if present. This makes sure it doesn't reset when clicking on the studio logo, for instance.
=> [default-layout] Reload window when switching spaces

packages/@sanity/desk-tool/src/pane/DocumentsListPane.js
I seem to have broken ordering in the latest release due to the new list optimizations. This fixes that by setting up a new query/listener pair when changing the order.
=> [desk-tool] Fix query not updating on changed sort order

packages/@sanity/core/src/commands/dataset/exportDatasetCommand.js, packages/@sanity/core/src/commands/dataset/importDatasetCommand.js, packages/@sanity/export/README.md, packages/@sanity/export/package.json, packages/@sanity/export/src/AssetHandler.js, packages/@sanity/export/src/export.js, packages/@sanity/export/src/requestStream.js, packages/@sanity/export/src/validateOptions.js, packages/@sanity/import-cli/README.md, packages/@sanity/import-cli/src/sanity-import.js, packages/@sanity/import/src/uploadAssets.js, packages/@sanity/import/src/validateOptions.js
Exporting and importing assets is currently quite slow. The assumption was that we would be able to saturate a clients connection and should thus keep the number of parallel downloads/uploads to a minimum.
This isn't the case, however, so by increasing the number of concurrent downloads and uploads, we greatly increase the speed of the process.
Exporting a large number of assets is improved by a factor of ~300%
Imports greatly vary based on the size of the assets, but should see benefits too.
=> [export/import] Improve asset performance

packages/@sanity/cli/src/actions/init-plugin/bootstrapFromTemplate.js
When you try to create a plugin with the CLI, the name is validated against npm package naming rules, and when the name you give is invalid, the CLI crashes instead of showing a helpful error message.
This adds a message that says the name needs to be a valid npm package name and includes a link to the npm package naming rules.
- Fixed a bug where the CLI would crash if trying to create a plugin with an invalid name
**Checklist**
=> [cli] add error message when plugin name is invalid

packages/@sanity/form-builder/src/FormBuilderInput.tsx
While doing some shallow profiling work, I discovered that the `path` property passed to the `FormBuilderInput` component was causing it to be re-rendered more often than necessary.
By comparing the path array using the path utils and the rest of the properties with a shallow equals function, we can significantly reduce the amount of re-renders.
=> [form-builder] Use shallow equality check on path property

packages/@sanity/core/src/actions/graphql/deleteApiAction.js, packages/@sanity/core/src/actions/graphql/deployApiAction.js, packages/@sanity/core/src/commands/graphql/deployGraphQLAPICommand.js
This adds validation logic to the GraphQL API deployment, ensuring that the user is made aware of any dangerous or breaking changes. 
If any dangerous changes are found, a confirmation dialog is shown. A new flag,  `--force` can be used to blindly overwrite the API (useful for CI flows etc).
=> [core] Check for breaking changes when deploying GraphQL API

packages/@sanity/core/src/actions/graphql/deployApiAction.js, packages/@sanity/core/src/actions/graphql/generateTypeQueries.js, packages/@sanity/core/src/actions/graphql/generateTypeSortings.js
Currently, there's no way to sort in the GraphQL API. This generates all the types required in order to do that.
Dynamically generate sorting types for possibility to sort on documents, objects and fields.
**Checklist**
=> [core] Dynamically generate type sortings

packages/@sanity/preview/src/prepareForPreview.ts, packages/@sanity/preview/src/utils/portableText.ts, packages/@sanity/schema/src/legacy/preview/guessPreviewConfig.ts, packages/@sanity/schema/src/legacy/preview/portableText.ts
If a schema type does not contain any string fields, it falls back to using an object representation for the previews. I find that a quite common scenario is to have a portable text field with a title or description, and while you _could_ create a snippet and set up a prepare function yourself, this is a bit tedious.
This PR adds support for:
- Guessing the title and description fields based on whether or not the schema type is a portable text array (strings still preferred if available)
- Extracting the text from all spans within the first portable text block of matched arrays
Jury is still out on whether or not this is a good idea - potentially we may want to just select `someBlockField.0` to cut down on the amount of data returned and hope that the first entry in the array is a text …
=> [preview] Add support for extracting text from portable text

packages/@sanity/base/types/parts.d.ts, packages/@sanity/cli/templates/blog/tsconfig.json, packages/@sanity/cli/templates/clean/tsconfig.json, packages/@sanity/cli/templates/ecommerce/tsconfig.json, packages/@sanity/cli/templates/moviedb/tsconfig.json, packages/@sanity/core/package.json, packages/@sanity/core/src/actions/exec/babel.js, packages/@sanity/core/src/actions/graphql/registerBabelLoader.js, packages/@sanity/server/package.json, packages/@sanity/server/src/configs/webpack.config.dev.js, packages/@sanity/server/src/configs/webpack.config.js
This PR adds support for using typescript in the studio. It uses the babel preset.
To work around parts not being resolvable, I've added an ambient module which defines the `part:*`, `all:*`, `config:*` patters as basically just `any` (`all` returns array of `any`, `config` returns an object). Since we're using CSS modules, I also added `*.css` as an object of class name mappings.
Unfortunately I could not find any way for the definitions to be automatically picked up without adding a `tsconfig` in each studio - I tried a bunch of different approaches to no avail. Thus, I've added the `tsconfig.json` file to all the CLI templates, and we should probably also add it to any of our other templates when we've verified that it works.
=> [core] Add support for typescript in studio

packages/@sanity/client/package.json, packages/@sanity/client/sanityClient.d.ts, packages/@sanity/observable/minimal.d.ts, packages/@sanity/observable/package.json
This PR adds hand-written typescript definitions to the client.
It doesn't try to be clever in reusing methods/types for the promise/observable versions - I tried a few approaches but couldn't come up with something that easily worked, so I decided to just do it the simple way for now.
I initially started converting the client to typescript, but quickly realized it was quite a lot of work trying to figure out the right way to model everything in a backwards-compatible way. We've been talking about slimming down the client to a more "importable"/"tree-shakable" implementation anyway, so I feel like the typescript rewrite is better done as part of that process.
Tried to have some community members give the definitions a try, but have not heard of any 👍 / 👎 , so I assume the easiest way to …
=> [client] Add typescript definitions

packages/@sanity/form-builder/src/inputs/BlockEditor/SyncWrapper.tsx, packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/UndoRedoPlugin.ts
When the editor is emptied, we delete the value from the document, but the editor still needs to have a placeholder block in order to have something to write into. The creation and removal of this placeholderblock should not be included in the undo/redo history, because it makes an extra step there that is unexecpted (you have to undo twice when deleting everything in the editor to get it back).
This makes the placeholder operations not to be included in the undo/redo stack.
Related issue: https://github.com/sanity-io/sanity/issues/1730
Avoid redundant undo step related to deleting all content in the PTE.
**Checklist**
=> [form-builder] Don't put placeholder operation into undo step

packages/@sanity/default-layout/src/components/styles/Sidecar.css
Sidecar overlaps editor and other things when open, because it's z-index is too hight.
**Checklist**
=> [default-layout] Fix z-index issue of sidecar in default layout

packages/@sanity/cli/src/util/clientWrapper.js
#1741 introduced a regression where the `response` property was not present on errors but would blindly be checked. This adds a more fool-proof check for it.
=> [cli] Use more fool-proof status code check for auth errors

packages/@sanity/desk-tool/src/actions/PublishAction.tsx, packages/@sanity/desk-tool/src/pane/Editor/Validation.tsx, packages/test-studio/schemas/validation.js
This PR fixes a few issues with validation _warnings_:
- Fixes an issue where publishing would not be allowed on warnings (only errors should block)
- Fixes an issue where the validation error indicator would show a red button with the count of `0` when warnings were present. With this change, the count now correctly includes warnings, as well as changing the color of the button to a yellow warning color when no errors are present.
=> [desk-tool] Allow publishing on validation warnings

packages/@sanity/form-builder/src/inputs/Slug/SlugInput.tsx, packages/test-studio/schemas/slugs.js
According to the documentation, the slug `source` property should be allowed to return a promise. The code does not actually reflect this, so it simply doesn't set a new value.
This PR ensures that the slug `source` property _can_ return a promise. I also made sure that the `source` property was not called on every render if it is a function, to prevent sending needless API requests/asynchronous calls.
- Fix slug `source` property not allowing asynchronous resolving of value
**Checklist**
=> [form-builder] Fix slug source not supporting asynchronous resolving

packages/@sanity/validation/src/validators/slugValidator.js
The `slug` field default validator appears to expect to find `disableArrayWarning` in the second argument (confusingly named `options`), but actually at `options.type.options.disableArrayWarning` if it's been specified in the field options by the user.
This commit fixes the reference to utilize the value by the field options in the schema.
**Checklist**
=> [@sanity] Fix invalid `disableArrayWarning` reference on slug

packages/@sanity/core/src/actions/graphql/listApisAction.js, packages/@sanity/core/src/commands/graphql/listGraphQLAPIsCommand.js, packages/@sanity/core/src/commands/index.js
After we introduced multiple GraphQL endpoints, there are currently no way of knowing what you already deployed (unless you take notes).
This PR adds functionality for listing out currently deployed GraphQL endpoints.
Add a CLI GraphQL sub-command for listing out deployed GraphQL endpoints.
**Checklist**
=> [core] Add a CLI command for listing out deployed GraphQL endpoints

packages/@sanity/base/package.json
Potentially crashes due to missing dependency (usually works because of hoisted dependencies)
This PR adds a missing dependency on `@sanity/generate-help-url`.
It's used in https://github.com/sanity-io/sanity/blob/next/packages/@sanity/base/src/actions/utils/legacy_documentActionUtils.js#L2 but not declared as a dependency.
**Checklist**
=> [base] Add missing @sanity/generate-help-url dependency

.npmrc, lerna.json
Lockfiles tends to get in our way when publishing packages and they are already ignored by `.gitignore`. There's not much value in having them generated locally anyways.
This adds an .npmrc that prevent lockfiles from being generated on `npm install` and adds the `--no-package-lock` flag when lerna installs dependencies using npm.
N/A
=> [chore] Prevent lockfiles from being generated locally

packages/@sanity/storybook/package.json, packages/storybook/config/.checksums, packages/storybook/config/@sanity/form-builder.json, packages/test-studio/package.json, packages/test-studio/sanity.json
This removes storybook from running in test studio by default. It can still be started using `npm run storybook`
N/A
=> [chore] Remove storybook from test-studio

packages/@sanity/client/sanityClient.d.ts
I seem to have forgotten to include the `SanityImagePalette` interface in the client definitions, which this PR fixes. Closes #1758.
=> [client] Typings: Including missing SanityImagePalette definition

packages/@sanity/client/sanityClient.d.ts
The default return type of `client.fetch` was returning unfiltered response which conflicts with the actual client.
This PR fixes the problem for both typings - the Promise API & Observable API. I also made the typings more explicit.
Also fixed a typo in `UnfilteredResponseQueryOptions`.
**Checklist**
=> [@sanity/client] Fixed the default return type of client.fetch

packages/@sanity/base/src/datastores/document/document-pair/operations/restore.ts, packages/@sanity/base/src/datastores/history/createHistoryStore.js
This patch ensures we restore to the published document instead of creating a new draft when restoring a document from history that has `liveEdit` enabled.
=> [base] Make sure restoring from history takes liveEdit into account

packages/@sanity/desk-tool/src/pane/Editor/Validation.tsx
A prop type warning is displayed, and validation list does not list the field names properly
This PR fixes an error where the `Validation` component expects a schema type object, but receives a string.
**Checklist**
=> [desk-tool] Fix incorrect schema type property for validation list

packages/@sanity/dashboard/package.json, packages/@sanity/dashboard/src/widgets/projectInfo/ProjectInfo.js, packages/@sanity/dashboard/src/widgets/projectUsers/ProjectUsers.js, packages/@sanity/dashboard/src/widgets/sanityTutorials/SanityTutorials.js, packages/@sanity/dashboard/src/widgets/sanityTutorials/dataAdapter.js, packages/@sanity/studio-hints/src/components/HintsPackage.js, packages/@sanity/studio-hints/src/datastore.js
Dashboard and hints sidebar causes React warnings about using `setState` after unmount 
This PR switches from promises to observables when fetching data in dashboard widgets and the studio hints package, and unsubscribes on unmount.  Needs a bit more testing before merging.
- Fix bug where dashboard widgets sometimes would try to update state after unmount
**Checklist**
=> [dashboard] Use observables for fetching, unsubscribe on unmount

packages/@sanity/components/src/dialogs/DefaultDialog.js, packages/@sanity/form-builder/src/inputs/ArrayInput/ItemValue.tsx, packages/@sanity/schema/src/legacy/types/object.ts, packages/test-studio/schemas/book.js, packages/test-studio/schemas/review.js, packages/test-studio/schemas/schema.js
If you had a field of type array and a member that array was defined in a separate file _and_ had no title key, the rendered title in the DefaultDialog would be `Edit undefined`. This PR solves this issue by:
- Falling back to use a human-friendly version of `name`, if `title` is missing
- Guarding against producing such titles in `ItemValue.tsx`
Fixes: https://github.com/sanity-io/sanity-priv/issues/2173
=> Fix "Edit undefined" in title

packages/@sanity/preview/src/observeForPreview.ts
This fixes an issue caused by an optimization in the preview package that excluded other preview fields than the one that should be displayed. This caused problems in cases where the `preview.prepare` method would put together a title by combining values from other fields.
Fixed an issue that would under some circumstances caused problems in cases with preview configs that put together a title by combining values from other fields.
=> [preview] Fetch all fields specified in preview.select even when requesting only a specific preview field

packages/@sanity/cli/src/actions/init-project/initProject.js, packages/@sanity/cli/src/actions/init-project/promptForDatasetName.js
The CLI prompts for default dataset config in the wrong place when choosing an existing project, and crashes when using the default config because the dataset name already exists.
This improves the DX by only prompting for default dataset config when creating a dataset for the first time, or when there are no datasets named "production". This PR also adds additional validation to check if a new dataset name already exists or not.
- Fixed a bug where the CLI prompts for default dataset config in the wrong place and causes the CLI to crash when choosing the default config
**Checklist**
=> [cli] fix default dataset settings crashing CLI on existing projects

packages/@sanity/block-tools/test/fixtures/customFeatures.json
[This commit](https://github.com/sanity-io/sanity/pull/1778/commits/a02066646c2fa4a86f1c85c0612d46944fe01336) changed some behavior that make the block-tools tests fail.
Preferably the test should be more specific on what it expects, but this will at least fix the tests for now.
=> [block-tools] Fix test to be in line with new schema changes

packages/@sanity/base/src/actions/utils/GetHookCollectionState.tsx, packages/@sanity/base/src/actions/utils/HookStateContainer.ts, packages/@sanity/base/src/actions/utils/RenderActionCollectionState.tsx, packages/@sanity/base/src/actions/utils/RenderBadgeCollectionState.tsx, packages/@sanity/base/src/actions/utils/index.ts, packages/@sanity/base/src/actions/utils/requestIdleCallback.ts, packages/@sanity/base/src/actions/utils/types.ts, packages/@sanity/desk-tool/src/actions/DiscardChangesAction.tsx, packages/@sanity/desk-tool/src/actions/PublishAction.tsx, packages/@sanity/desk-tool/src/components/DocumentActionShortcuts.tsx, packages/@sanity/desk-tool/src/components/DocumentStatusBar/DocumentStatusBarActions.tsx, packages/@sanity/desk-tool/src/components/DocumentStatusBar/DocumentStatusBarBadges.tsx, packages/test-studio/src/resolveDocumentActions.js
This is an internal rewrite of how we get the state out of the document action components. Previously we would call a function from within the render function of a state containing component. This caused a lot of warnings being spewed out into the console in React 16.13 (and possibly breakage in future React versions).
This patch switches to another approach which schedules updates to the action component renderer at most every 60ms, and in a requestIdleCallback to avoid updates from blocking more critical tasks.
Fixed an issue that triggered a flood of console warnings in Studios using in React 16.13.
=> [base] Improve scheduling of document action state updates

packages/@sanity/components/src/dialogs/DefaultDialog.js
If you currently pass both a `title` and `showCloseButton={false}` to DefaultDialog, the close button will still appear:
This PR actually disables close button even when a title is passed.
Fix an issue with `DefaultDialog` causing the close button to appear if `showCloseButton` is passed along with a `title`.
=> [components] DefaultDialog: Actually hide close button when 'showCloseButton' is falsy

packages/@sanity/core/src/actions/graphql/registerBabelLoader.js
When running `sanity graphql deploy` and you have a require/import of a `.ts` or `.tsx` file as part of the schema, it will currently crash because it does not know how to resolve it, and if it does resolve, it won't be compiled with babel.
This PR adds `.ts` and `.tsx` to the extensions that are ran through `@babel/register`, which fixes this issue.
- Fix bug where using typescript in schema would crash `sanity graphql deploy`
**Checklist**
=> [core] Use babel loader for ts/tsx files when generating GraphQL schema

.travis.yml
Node.js 8 is out of LTS. Let's not spend CPU cycles on Travis CI: https://nodejs.org/en/about/releases/
Since Node.js 8 is out of LTS we no longer run CI tests for it.
=> [chore] Remove Node 8 from .travis.yml

packages/@sanity/export/src/export.js, packages/@sanity/export/src/rejectOnApiError.js, packages/@sanity/export/src/tryParseJson.js
If the export stream (ndjson) terminates with a JSON error without a `statusCode` property, the export doesn't throw. In the same way, if the stream is terminated mid-stream with a JSON error, there is nothing that gives any clear indication of what the actual error message was.
Consider the following cases:
```ndjson
{"_id":"valid","_type":"document"}
{"error":{"description":"Operation timed out"}}
```
```ndjson
{"_id":"valid","_type":"document"}
{"_id":"start-of{"error":{"description":"Operation timed out"}}
```
With this change, we pick up both "whole line"-errors (such as the first example) and "mid-line" errors such as the second, and throw an …
=> [export] Catch errors in JSON stream without a statusCode property

packages/@sanity/cli/src/actions/init-project/createManifest.js
Currently if you rename the schema from `.js` to `.ts` after initialising a new project using `sanity init` will fail because the path of the implementation for `part:@sanity/base/schema` ships with an explicit `.js` extension. (See https://github.com/sanity-io/sanity/issues/1799)
This fixes the issue by removing the explicit `.js` extension when we generate sanity.json manifests in during `sanity init`.
Removed explicit `.js` extension from schema file in new projects initialised using `sanity init`.
=> [cli] Remove explicit .js extension from path of schema part in new projects

packages/@sanity/check/package.json, packages/@sanity/cli/package.json, packages/@sanity/core/package.json, packages/@sanity/export/package.json, packages/@sanity/import-cli/package.json, packages/@sanity/import/package.json, packages/@sanity/initial-value-templates/package.json, packages/@sanity/plugin-loader/package.json, packages/@sanity/react-hooks/package.json, packages/@sanity/resolver/package.json, packages/@sanity/server/package.json, packages/@sanity/structure/package.json, packages/@sanity/studio-hints/package.json, packages/@sanity/transaction-collator/package.json, packages/@sanity/util/package.json, packages/@sanity/webpack-integration/package.json, packages/@sanity/webpack-loader/package.json, packages/create-sanity/package.json, packages/sanity/package.json, scripts/normalizePackageFields.js
We currently say that we support node 8 and up, while our tests are (since a few days ago) only run on node 10 and up. 
This PR sets the engines field to require node 10 for all packages.
- Require node v10 and up to run Sanity
**Checklist**
=> [chore] Require node 10 across packages

packages/@sanity/client/sanityClient.d.ts
For some reason, typescript was having issues resolving the constructor options for this call:
```ts
const client = new SanityClient({
projectId: 'foo',
dataset: 'bar',
token: 'baz',
useCdn: false
})
```
It seemed to infer that it should be a `ProjectlessClientConfig`, which requires `useProjectHostname` to be set to  `false`. It seems like introducing `useProjectHostname` as an optional, `true` value in the `ProjectClientConfig`, it resolves correctly.
- Fixed bug where typescript resolved incorrect option signature for client constructor
**Checklist**
=> [client] Fix typings for constructor options (useProjectHostname)

packages/@sanity/client/sanityClient.d.ts
When calling `transaction.serialize()` or `transaction.toJSON()`, an array of mutations is returned, but typescript definitions says it will return a patch. This is a copy+paste bug from `Patch`.
This PR fixes the definitions.
- Fixed typescript definition for client having incorrect return value type for `transaction.serialize()` and  `transaction.toJSON()`
**Checklist**
=> [client] Fix incorrect return value type for transaction.serialize()

packages/@sanity/base/initial-value-template-builder.d.ts, packages/@sanity/base/initial-value-templates.d.ts, packages/@sanity/base/structure-builder.d.ts
Adds "proxy" typescript definitions for things in `@sanity/base` that just re-export the upstream definitions. 
- Added typescript definitions for structure builder and initial value templates
**Checklist**
=> [base] Add typescript definitions for structure, initial value templates

packages/@sanity/core/src/actions/graphql/extractFromSanitySchema.js
When deploying a GraphQL endpoint with a schema that contains an array definition with the same type both in the `references` array and the `to` array, the `sanity graphql deploy` command fails.
This change fixes a problem where deploying a GraphQL endpoint with a schema that contains an array definition with the same type both in the `references` array and the `to` array, the `sanity graphql deploy` command fails.
Fix an issue where deploying a GraphQL endpoint with a schema that contains an array definition with the same type both in the `references` array and the `to` array, the `sanity graphql deploy` command fails. …
=> [core] GraphQL: Allow types to be present both as a reference and as an inline object in an array

packages/@sanity/base/src/datastores/history/createHistoryStore.js
Currently, when restoring a document from the revision history we look through the restored version for references to check if they still exist. Due to an erroneous typeof check, which should have been a falsey check, any null values in the restored version would throw an error saying `Cannot read property _ref of null`.
Fixed a bug that would cause an error when trying to restore a document that has `null` values.
=> [base] Fix wrong typeof check

packages/@sanity/default-login/src/LoginDialog.js, packages/@sanity/default-login/src/util/getProviders.js
Sometimes you may want to limit the available login providers for a studio. A common example is when users log in with their Google account and later try to log in with their GitHub and get confused when they don't have access. To prevent this confusion, a developer may choose to only allow logins through one provider, and update their default login configuration to reflect this:
```json
{
"providers": {
"mode": "replace",
"redirectOnSingle": true,
"entries": [
{
"name": "sanity",
"title": "Sanity ",
"url": "https://api.sanity.io/v1/auth/login/sanity"
}
]
}
}
```
The problem is that all entries in the configuration are treated as "custom", which require the …
=> [default-login] Treat official provider URLs as non-custom

packages/@sanity/core/src/actions/graphql/extractFromSanitySchema.js
If a field has a description set to a React element (`description: <span>Foo</span>`), it gets serialized and sent to the server as the object description of the element, and is rejected by the validation.
This PR silently ignores any non-string description fields. I don't see any reason for adding a flag or a warning as I think this is an edge-case (in an upcoming "editor declaration" implementation, we'll have better ways of achieving rich "descriptions" for fields while keeping the schema definition "pure".
- Fixed bug where non-string field descriptions would prevent GraphQL APIs from being deployed
**Checklist**
=> [core] GraphQL: Only use field description if type is string

packages/@sanity/core/package.json, packages/@sanity/core/src/actions/exec/execScript.js, packages/@sanity/core/src/actions/exec/requireContext.js, packages/@sanity/core/src/actions/graphql/getSanitySchema.js, packages/@sanity/core/src/util/requireContext.js
If you're using `require.context` in the studio (for instance, to load all schema type files without having to specify them all), this works fine until you try to deploy a GraphQL API or running a script with `sanity exec`, at which point it'll crash because `require.context` does not exist in the node APIs. 
This PR injects a "polyfill" for `require.context` into the node environment when running `sanity graphql deploy` and `sanity exec`. It's a bit of a hairy beast, so it comes with a set of pessimistic try/catch clauses, warning should it fail to register itself. 
To try it out, here's a sample `schema.js` file which requires all `.js` files in …
=> [core] Add `require.context` hook for schema generation, script exec

packages/@sanity/eventsource/browser.js, packages/@sanity/eventsource/package.json
When trying to use listeners in React Native, the current polyfill implementation crashes because it tries to access `window.location.origin`, which is not defined.
This PR uses a forked version of the polyfill, which addresses this (and a few other) issues. Can't guarantee that this makes listener work in react native, but it will at least prevent _that_ error from happening.
**Checklist**
=> [eventsource] Use forked eventsource polyfill

packages/@sanity/validation/src/validators/numberValidator.js
When a field using `validation: Rule => Rule.precision(limit)` has an empty value, the `precision` validator will fail with the error message “Cannot read property 'toString' of undefined”. This error message subsequently overrides the validation failure messages for the field. 
This PR short-circuits the function by returning `true` early when the field value is undefined.
Improved handling of empty values when using precision validation on number fields
**Checklist**
=> [validation] Short-circuit to avoid failed coercion of `undefined` to string

packages/@sanity/validation/src/Rule.js, packages/@sanity/validation/src/inferFromSchemaType.js, packages/@sanity/validation/src/util/handleValidationResult.js, packages/@sanity/validation/src/validators/blockValidator.js, packages/@sanity/validation/src/validators/genericValidator.js, packages/@sanity/validation/src/validators/objectValidator.js, packages/@sanity/validation/test/strings.test.js
When validating the type `block`, it uses the `custom` validation function which spins up one or two `setTimeout`s which apparantly kills the browser.
This PR changes the validation of a block to use it's own validation function. Earlier it used the 'custom' function which spins up one or two setTimeouts for each block. When working on huge documents that was too much for the browser (it seems, in Node it runs pretty good). This commit changes it to not use setTimeouts at all (if not the validation is overridden with an async validation function).
Fix a performance issue when validating blocks
**Checklist**
=> [validation] Fix a performance issue when validating blocks

packages/@sanity/form-builder/src/inputs/BlockEditor/EditNode.tsx
If the document is in readOnly mode, the editor will still try to set focus on the editable. This should not happen.
Fix bug related to portable text editor and closing edit modals when in readonly mode.
**Checklist**
=> [form-buidler] PTE: fix focus bug when in readOnly mode

packages/eslint-config-sanity/react.js
```jsx
<div>It's a "thing"</div>
```
has to be written as either
```jsx
<div>It&apos;s a &quot;thing&quot;</div>
```
or
```jsx
<div>It{"'"}s a {'"'}thing{'"'}</div>
```
...making the code hard to read. I've rarely (if ever) encountered this warning in cases where it legitimately was an error on my part. 
This changes the eslint rule to allow quotes, but still disallow unescaped `}` and `>`, as those are rarely used in normal text flow.
**Checklist**
=> [eslint-config-sanity] Allow unescaped quotes in JSX

packages/@sanity/cli/src/util/clientWrapper.js, packages/@sanity/core/src/actions/start/startAction.js
`ensureProjectConfig()` in startAction.js fails when there are no values in `sanity.json`'s `api.project_id` and `api.dataset`, while with the recent addtion of dotenv (`.env`) functionality, `.env.[development|productions|etc.]` can be used to set these values. There should be no values in `sanity.json` in this case for these since it would confuse someone who reads through the configuration. Also, it is easy to configure these values through `.env` in cases where `gatsby-source-sanity` is used and the same values need to be set there as well.
This code change checks `context.apiClient().clientConfig.projectId` and …
=> [@sanity/core] Allow startup with env without api settings

packages/@sanity/client/package.json, packages/@sanity/import/package.json
Upgrades the `get-it` dependency in the client + import to the latest version, which fixes a bug where error middlewares would be called with `null`/`undefined` if errors were handled by a previous middleware. When the `retry` middleware successfully retried a request, it would flag the error as being handled, but any following error handers would still be called with `null` as the first argument, often crashing because they were expecting an `Error`.
**Checklist**
=> [chore] Upgrade get-it dependency

packages/@sanity/components/src/fieldsets/styles/DefaultFieldset.css, packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx, packages/@sanity/form-builder/src/inputs/ObjectInput/styles/Field.css, packages/@sanity/form-builder/src/inputs/ObjectInput/styles/ObjectInput.css, packages/test-studio/schemas/fieldsets.js
- Fixes https://github.com/sanity-io/sanity/issues/1877
- Fixes https://github.com/sanity-io/sanity-priv/issues/2094
- https://github.com/sanity-io/sanity-priv/issues/2095
- https://sanity-io.slack.com/archives/CA9HS8MQQ/p1588948049459600?thread_ts=1588947505.455400&cid=CA9HS8MQQ
- Add an example of fieldset columns layout to the `fieldsetsTest` type in Test Studio
- Move responsibility of spacing fields away from `Field` to `ObjectField` and `DefaultFieldset`
- Add `ObjectField.css` with a `.fieldWrapper` to apply CSS grid
**Test script**
1. Start the Studio locally
1. Go to http://localhost:3333/test/desk/fieldsetsTest;b79acf77-6d67-482e-9a25-7c73a …
=> [form-builder] Fix fieldset columns layout

packages/@sanity/base/src/styles/variables/globals.css, packages/@sanity/components/src/previews/DefaultPreview.js, packages/@sanity/components/src/previews/styles/DefaultPreview.css
The recent release that placed form fields in a vertical grid, caused the rendering of DefaultPreview to behave differently. Specifically, there was an issue with text-overflow not working, and forcing the width of all other field elements to exceed their bounds.
See report here: https://sanity-io.slack.com/archives/CAJ4KP63G/p1589363595001100
This change adds a container (`.inner`) in DefaultPreview that has `position: absolute`. This caused `text-overflow` to behave in a much more resilient manner.
**Checklist**
=> [components] Make DefaultPreview more resilient to being placed within CSS grids

packages/@sanity/components/src/presence/AvatarCircle.css, packages/@sanity/components/src/presence/AvatarCircle.tsx, packages/@sanity/components/src/presence/GlobalStatus.tsx, packages/@sanity/components/src/presence/StackCounter.css, packages/@sanity/components/src/presence/StackCounter.tsx, packages/@sanity/components/src/presence/UserAvatar.tsx
- Adds property `tone` to the AvatarCircle component. This is used to tell the component whether it is rendered in the navbar or not (and some colors are based on that)
- Removes `showFill` property. Uses instead `imageUrl` to tell whether or not to render the thin "transparent" border between the image and the border of the avatar.
- Bases size values in the SVG on constants `W` and `H` (which are set to 21px for now). This is to avoid the SVG scaling leading to unwanted stroke widths and such.
=> [components] Tweak avatar component

packages/@sanity/base/src/components/DevServerStatus.js, packages/@sanity/components/src/snackbar/DefaultSnackbar.js, packages/@sanity/components/src/snackbar/SnackbarProvider.js, packages/@sanity/desk-tool/src/panes/documentPane/DocumentOperationResults.tsx, packages/@sanity/desk-tool/src/panes/documentPane/DocumentPane.tsx
When publishing a document when using split panes, you get _n_ amount of Snackbar messages based on how many panes are open.
This PR uses the `preventDuplicate` functionality already available in the `SnackbarProvider` to prevent multiple instances of the same Snackbar type to appear.
Not sure if this was the intended solution for this, as it still generates multiple Snackbars when multiples panes are open. It kind of just swallows if it's of the same type in this PR. I saw other Snackbars which would also appear multiple times from what I can see, as they are rendered in each pane. A more robust way to fix this would be to move the connectionstate …
=> [desk-tool] Prevent duplicate publish Snackbars when using split panes

packages/@sanity/components/src/fieldsets/styles/DefaultFieldset.css, packages/@sanity/components/src/formfields/styles/DefaultFormField.css, packages/@sanity/components/src/previews/DefaultPreview.js, packages/@sanity/components/src/previews/styles/DefaultPreview.css, packages/@sanity/desk-tool/src/panes/documentPane/DocumentStatusBar/DocumentStatusBar.css, packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayInput.tsx, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ArrayInput.css, packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ItemValue.css, packages/@sanity/form-builder/src/inputs/ArrayOfPrimitivesInput/styles/ArrayOfPrimitivesInput.css, packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/Toolbar.css, packages/@sanity/form-builder/src/inputs/FileInput/styles/FileInput.css, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.tsx, packages/@sanity/form-builder/src/inputs/ImageInput/styles/ImageInput.css, packages/@sanity/form-builder/src/inputs/ObjectInput/UnknownFields.tsx, packages/@sanity/form-builder/src/inputs/ObjectInput/styles/ObjectInput.css, packages/@sanity/form-builder/src/inputs/ObjectInput/styles/UnknownFields.css, packages/@sanity/form-builder/src/inputs/OptionsArrayInput/OptionsArrayInput.tsx, packages/@sanity/google-maps-input/src/GeopointInput.js, packages/@sanity/google-maps-input/styles/GeopointInput.css, packages/test-studio/schemas/blocks.js, packages/test-studio/schemas/schema.js, packages/test-studio/schemas/spotifyEmbed.js
- Jørn reported that grid blowout still happens within PTE content.
- Discovered that it's caused by a case in CSS grids called "grid blowout" (see [post](https://css-tricks.com/preventing-a-grid-blowout/) by Chris Coyier).
- Added `grid-template-columns: minmax(0, 1fr);` on the various places that form fields are spaced.
- While working on this (and testing throughly), I discovered several related layout issues.
- Fixed an issue in DefaultPreview where it would render an unstyled `0` when providing it with the property `subtitle={0}`.
- Added `spotifyEmbed` type for testing.
- Prevent fieldset grid blowout and fix related …
=> [components] Prevent fieldset grid blowout and fix related layout issues

packages/@sanity/components/src/previews/styles/BlockPreview.css
When the block preview has a lot of text, it doesn't wrap and goes outside its container, effectively extending the container and makes the PTE very hard to use. 
This PR fixes this by properly wrapping the text, so it doesn't extend outside its container.
Fix an issue where the BlockPreview extended outside its container
**Checklist**
=> [components] Fix an issue where the BlockPreview extended outside its container

packages/@sanity/client/sanityClient.d.ts
You're currently not allowed by the typescript definitions to pass a `Patch` instance to a `Transaction`, eg `trx.patch(somePatchInstance)`
This PR declares a separate method overload for the case where you pass it a patch instance instead of a document ID + patch builder/patch operations bundle.
**Checklist**
=> [client] Typings: Fix patch() signature not accepting patch instance

packages/@sanity/client/sanityClient.d.ts
If you don't specify a type for a document, you may end up with typescript errors like:
```
Type '{ _id: string; _type: string; title: string; }' is not assignable to type 'SanityDocument<{}>'.
Object literal may only specify known properties, and 'title' does not exist in type 'SanityDocument<{}>' 
```
The definition of `SanityDocument` declares that the provided document type should extend `Record<string, any>`, but then provides a default of `{}`, which _doesn't_ extend it (it has no key signature).
I believe that this PR should fix it by saying that the default type is a plain record of `<string, any>`, but correct me if I'm wrong here. …
=> [client] Typings: Use record as default document extension

packages/@sanity/validation/package.json, packages/@sanity/validation/src/inferFromSchemaType.js, packages/@sanity/validation/src/validateDocument.js, packages/@sanity/validation/src/validators/dateValidator.js
When you have validation on date fields, the date isn't formatted when showing in the validation message, which makes it hard to read.
Also, validation hasn't been possible on the `date` type.
This gets the options from the field to be validated, and uses it in the validator to format the dates using either the default format, or the format specified in options.
This adds the same validation methods to the `date` type. 
- Fixed an issue where `date` wouldn't get the same built-in validation methods as `datetime`
- Fixed date formatting in validation messages
**Checklist**
=> [validation] format dates in validation messages and support validations on date type

packages/@sanity/desk-tool/src/panes/documentPane/DocumentStatusBar/ActionStateDialog.tsx
There's no way of hiding the close button when using modal dialogs for document actions.
This adds the necessary prop to make hiding the close button in customisable when creating a document action using modal dialogs.
- N/A
**Checklist**
=> [desk-tool] add showCloseButton prop to document action modal dialogs

packages/@sanity/core/src/actions/graphql/listApisAction.js
```
$ sanity graphql list
Here are the GraphQL endpoints deployed for this project:
1.  Dataset:     blog
Tag:         current
Generation:  gen2
Playground:  true
2.  Dataset:     blog
Tag:         default
Generation:  gen2
Playground:  false
```
Added a row url URL for endpoint
```
$ sanity graphql list
Here are the GraphQL endpoints deployed for this project:
1.  Dataset:     blog
Tag:         current
Generation:  gen2
Playground:  true
URL:  https://ppsa7ml5.api.sanity.io/v1/graphql/blog/current
2.  Dataset:     blog
Tag:         default
Generation:  gen2
Playground:  false
URL:  https://ppsa7ml5.api.sanity.io/v1/graphql/blog/default
```
**Note …
=> [core] Add GraphQL endpoint URL to `sanity graphql list` action

packages/@sanity/default-layout/src/components/NotFound.js, packages/@sanity/default-layout/src/components/styles/NotFound.css
In some circumstances the `router.state` is null, and `router.state.space` will throw an error.
Added a test for `router.state` before using it. Also added some padding to the NotFound component, because that page looked weird without.
**Checklist**
=> [default-layout] Fix router state bug (NotFound component)

packages/@sanity/base/src/datastores/document/buffered-doc/createObservableBufferedDocument.ts, packages/@sanity/base/src/datastores/document/buffered-doc/types.ts, packages/@sanity/form-builder/src/sanity/SanityFormBuilderContext.tsx, packages/@sanity/mutator/src/document/BufferedDocument.ts, packages/@sanity/mutator/src/document/Document.ts
When we get a rebase event from the mutator, we have no data for what actually happened in regard to remote and local mutations. They get swallowed, and the only thing the mutator emits is the new rebased document.
This PR will make it possible to get that data. Instead of the rebase callback just sending the rebased document as the first and only param, it will now send the document as first arg like before, and remote mutations and local mutations as the second and third param.
In this way we can forward the actual patches through the patch channel in the Form Builder with their respective origin and data.
**Checklist**
=> Detailed rebase event

packages/@sanity/desk-tool/src/panes/documentPane/DocumentStatusBar/DocumentStatusBarActions.tsx
This fixes a regression introduced in 6da6802, causing the issue described in #1830
Also made sure to display the dropdown button *only* if there's more than one available action
Closes #1830
Fixed an issue that could sometimes make a document action button disappear.
=> [desk-tool] Fix an issue with disappearing document action button

packages/@sanity/export/src/AssetHandler.js, packages/@sanity/export/src/requestStream.js, packages/@sanity/export/test/AssetHandler.test.js, packages/@sanity/export/test/__snapshots__/AssetHandler.test.js.snap
If encountering documents with an `asset` property which happens to be a reference, but is not a reference to a sanity image or file asset, the export potentially crashes  because it assumes it's a Sanity asset and tries to download the asset.
This PR introduces more strict checking of the referenced ID, to make sure it matches the image or file ID pattern. In the future we should probably check that the dataset actually exports the referenced asset, as _theoretically_ someone could make a document with the same asset shape.
I also took the liberty of removing handling of (very) legacy assets, which has the side benefit of removing an async hot …
=> [export] Fix incorrectly handled rewriting of non-sanity assets

packages/@sanity/export/src/AssetHandler.js
If exporting a dataset containing assets with a number in the extension (such as mp3, mp4), the export does not understand that it is a Sanity asset and skips it. This can lead to breaking imports when combined with the  `--no-assets` flag, as it will still be referencing excluded assets.
This PR fixes the regular expression used to match the Sanity asset to also allow for numbers.
- Fixed issue where exporting assets with numeric extensions (eg `mp3`) would not be recognized as valid Sanity assets
**Checklist**
=> [export] Fix extensions with numbers not recognized as valid asset ID

packages/@sanity/desk-tool/src/components/IntentResolver.js, packages/@sanity/desk-tool/src/tool/index.js
The issue with generating document links using draft ids from the document list dashboard-widget was fixed in https://github.com/sanity-io/dashboard-widget-document-list/commit/04f87b1e77cd9a7b313e117b14286b67b3cee15c. However, there are still studios out there with the older versions or that for some reason are still having intent links with draft id in them. This PR fixes this issue by rewriting intent links with draft prefix in the component that resolves intent links.
Closes #1865
> Fixed an issue causing studio crash with different variations of "editOpsOf does not expect a draft id" and "useDocumentOperation(...) is null" (more details in #1865)
=> [desk-tool] Remove the drafts prefix + warn when resolving intent links

packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.css, packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.tsx
Advanced image edit dialogs used a fullscreen dialog which made the field stretch and look weird. This replaced the fullscreen dialog with a default one with medium sized content. Presence also didn't know where to place avatars when someone enters an advanced image edit dialog, so a `PresenceOverlay` was also added to fix this.
**Before**
**After**
=> Fix presence in advanced image edit dialogs and replace fullscreen dialog

packages/@sanity/core/src/actions/build/buildStaticAssets.js
If you delete the `static` folder, the `sanity build` command fails to run because it attempts to copy it.
This PR checks for `ENOENT` errors and allows these. Other errors are still thrown.
- Fixed `sanity build` crashing if `static` folder does not exist
**Checklist**
=> [core] Prevent throwing on missing static folder when building

packages/@sanity/client/sanityClient.d.ts, packages/@sanity/client/src/data/listen.js
This PR adds support to the sanity client for the `effectFormat` parameter on listeners, which will be used in upcoming features. It expresses the difference between the previous and the next revision as a minimal patch, and is an alternative to sending the entire previous/next versions.
- Added support for `effectFormat` parameter on listeners
**Checklist**
=> [client] Add effectFormat as allowed parameter to listener

packages/@sanity/base/package.json, packages/@sanity/dashboard/package.json, packages/@sanity/preview/package.json, packages/@sanity/studio-hints/package.json, packages/test-studio/package.json
Upgrades the `@sanity/image-url` dependency, which fixes a few bugs. Also added it as dependency to some packages that were using it without declaring it as a dependency.
**Checklist**
=> [chore] Upgrade image-url dependency

packages/@sanity/schema/src/legacy/types/array.ts, packages/test-studio/schemas/schema.js, packages/test-studio/schemas/validation.js
This makes subtypes of array types override validation rules from its parent type, fixing the issue described in #1774.
- Fixed an issue with subtypes of arrays not overriding validation rules from its parent type
=> Support overriding validation on array subtypes. Fixes #1774

gulpfile.js, scripts/utils/getPackagesOrderedByTopology.js
Currently the gulpfile uses a hand written list of TypeScript modules that depends on each other so that they can be compiled in order. This was brittle and easily got out of hand. This PR instead retrieves the list of packages ordered by toplology (e.g. their interdependencies - leaves first) from lerna. This makes sure all packages gets compiled in order.
This probably increases the build time for release a bit since it now builds all TypeScript modules serially, but I guess reliability trumps performance in this regard. On the bright side I didn't notice any significant differences in startup time for the test studios compared to before.
Sneaking in 44eb047 into …
=> Make a couple of stability improvements to gulpfile

packages/@sanity/schema/src/legacy/types/any.ts, packages/@sanity/schema/src/legacy/types/array.ts, packages/@sanity/schema/src/legacy/types/boolean.ts, packages/@sanity/schema/src/legacy/types/constants.ts, packages/@sanity/schema/src/legacy/types/date.ts, packages/@sanity/schema/src/legacy/types/datetime.ts, packages/@sanity/schema/src/legacy/types/email.ts, packages/@sanity/schema/src/legacy/types/file.ts, packages/@sanity/schema/src/legacy/types/image.ts, packages/@sanity/schema/src/legacy/types/number.ts, packages/@sanity/schema/src/legacy/types/object.ts, packages/@sanity/schema/src/legacy/types/reference.ts, packages/@sanity/schema/src/legacy/types/string.ts, packages/@sanity/schema/src/legacy/types/text.ts, packages/@sanity/schema/src/legacy/types/url.ts
When using a custom array type, it's not possible to set the array to hidden or readonly because they're not overridable. Same on image and file.  #1864 
_Edit:_
Other types also don't allow this to be overridden. Is this on purpose or bug?
_Edit2:_
Talked to @p10e and @saasen, and we agreed that this seems like a bug. It's also been reported in the community, on multiple types. So I've updated all the types to make it possible to override `hidden`, `readOnly`, and `validation`. As well as `rows` for the `text` type.
- Fixed an issue where certain fields were not overridable when creating and using subtypes
**Checklist**
=> [schema] support overriding readonly, hidden, validation, on all subtypes (#1864)

packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayFunctions.tsx
Menu does not include type icons and it can't be customized
This adds icons to the insert array item dropdown menu. Supports custom icons, fallback is type icon, icon for reference (if ref is to one type only), or plus icon
Edit: primitives also get an icon now, which is always the plus icon. Might look a little weird.. :/ 
- Dropdown menu for adding array items now include type icons, and they can also be overridden
**Checklist**
=> [components] support type icons in insert array element menu list

packages/@sanity/form-builder/src/inputs/DateInputs/BaseDateTimeInput.tsx
> Right now, the date picker closes when selecting a date. If the user also wants to change the time, they have to reopen the date picker.
This prevents the date picker closing before it's supposed to. The datepicker library handles closing it.
- Fixed an issue where the date and time picker closed when choosing a date and had to reopened to choose a time
**Checklist**
=> [form-builder] prevent date picker from closing before selecting a time

packages/@sanity/form-builder/src/inputs/PortableText/Toolbar/helpers.tsx
**Not sure if intended,** but if a field in a block array has hidden: true, it's still possible to insert it from the insert menu in the PT editor.
```
{
name: 'defaults',
title: 'Content',
description: 'Profound description of what belongs here',
type: 'array',
of: [
{type: 'image', name: 'image1', title: 'Image, hidden true', hidden: true}, // should be hidden in the menu list
{type: 'image', name: 'image2', title: 'Image, hidden false'},
{
type: 'block',
of: [
{
type: 'color',
title: 'Color'
}
]
}
]
},
```
Return `null` when `hidden: true` to prevent that item from showing up in the menu.
**Checklist**
=> [form-builder] Hide insert menu item when hidden true

packages/@sanity/desk-tool/src/components/IntentResolver.js
This fixes an issue with the path parameter not being passed through when resolving intent links on the format `__edit__<id>`
(N/A: bug in unreleased code, so nobody has been affected by this)
=> [desk-tool] Pass extra parameters through the intent resolver

packages/@sanity/form-builder/package.json, packages/@sanity/form-builder/src/inputs/PortableText/Editor.tsx, packages/@sanity/form-builder/src/inputs/PortableText/Input.tsx, packages/@sanity/form-builder/src/inputs/PortableText/PortableTextInput.css, packages/@sanity/form-builder/src/inputs/PortableText/PortableTextInput.tsx, packages/@sanity/form-builder/src/inputs/PortableText/Toolbar/OverflowMenu.css
* Re-implemented the focus-skipper button for easy access to the editor without tabbing through all the toolbar-buttons.
* Export a React class as the outmost component with `focus` and `blur` class methods. The FormBuilder expects this.
* Optimize when props.value is deserialized in regard to not updating the value while the user is actively selecting text. The editor value will not be updated unless the actual props.value is changed while selecting.
* Fix focus ring cutoff for overflow menu buttons in the PTE toolbar.
* Don't wait for the onChange result from the FormBuilder - we will update the value when a new prop comes in anyway.
* Set the editor active when the editor has focus. …
=> Various PTE  enhancements

packages/@sanity/form-builder/src/inputs/PortableText/Objects/renderers/PopoverObjectEditing.tsx
the url popover is not very wide. I’ve wrapped the popover content in the pt object rendderer in a `DialogContent` component and set the size to medium, then it will always have the same width as most other dialogs in the studio. Not sure if this is the desired look tho, so here's a PR
Screenshots: https://sanity-io.slack.com/archives/C011W8DMVH8/p1594290401004400
=> [form-builder] Give popover in pt object renderer a medium content size

gulpfile.js, package.json
Currently, if there are compile errors when you start the dev server the gulp script will just crash and the process will exit, leaving the dev server running and occupying the port.
This PR adds graceful handling of TS compile errors during both startup and later on if introducing compile errors during development. It also pops a notification when a compile error appears during development.
N/A
=> [chore] Improve handling of TypeScript compile errors during dev

packages/@sanity/react-hooks/src/useConnectionState.ts, packages/@sanity/react-hooks/src/useDocumentOperation.ts, packages/@sanity/react-hooks/src/useDocumentOperationEvent.ts, packages/@sanity/react-hooks/src/useEditState.ts, packages/@sanity/react-hooks/src/useSyncState.ts, packages/@sanity/react-hooks/src/useValidationStatus.ts, packages/@sanity/react-hooks/src/utils/use-observable.ts
The change in 2f34d6a makes sure the `useObservable` utility function in @sanity/react-hooks resubscribe whenever it receives a new observable.
Additionally, in 5148c37 we avoid creating new observables on every render by memoizing them by the given parameters.
N/A
=> Fix: Make useObservable resubscribe when receiving new observables

packages/@sanity/components/src/validation/ValidationList.tsx, packages/@sanity/form-builder/package.json, packages/@sanity/form-builder/src/inputs/PortableText/Input.tsx, packages/@sanity/form-builder/src/inputs/PortableText/Objects/BlockObject.tsx, packages/@sanity/form-builder/src/inputs/PortableText/Toolbar/helpers.tsx, packages/test-studio/schemas/simpleBlock.js
Changes:
* Updated the core Portable Text Editor to latest version
- Fixes reversed selection issues
- Fixes clunky scrollIntoView behaviour on block objects (will now only scroll if focused and totally out of the scroll area)
- Adds functionality to strip formatting inside the selection (select anything and click bold to remove everything bold in that selection)
- Fixes unnecessary renders of block object previews (keep object equality)
* Fixes an issue where clicking items in the root validation list would not scroll and set focus correctly
* Memoize the block preview on the value inside the Studio code
=> Various fixes to the PTE

packages/@sanity/vision/src/containers/VisionContainer.js
When attempting to use the Vision tool when you are logged in via SSO, a call to the backend for a list of datasets will fail, since the user doesnt have that access level. This causes the Vision tool to end up in an Error message state and does not present its main functionality.
This PR simply falls back to the dataset name configured in `sanity.json` in the event that any error occurs while loading the list of datasets. This should be fine, as any other errors would be handled by its child component when attempting to run queries etc.
Vision tool now works with SSO
**Checklist**
=> [@sanity/vision] Use default dataset if loading dataset names from API fails

packages/@sanity/base/src/actions/utils/GetHookCollectionState.tsx
When developing on the studio, the "Hook collection state" utility sometimes re-renders, and some logic is calling a `setTick` method, which attempts to set state on a now unmounted component. This results in the following error in the console:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
in GetHookCollectionState (created by RenderActionCollectionState)
in RenderActionCollectionState
in Unknown (created by DocumentPane)
in Popover (created by DocumentPane)
in DocumentPane
in …
```
=> [base] Fix setState after unmount in hook collection state

packages/@sanity/form-builder/package.json
This is an update of `@sanity/portable-text-editor` in `form-builder` which fixes a couple of issues with hoisted block types.
- Fixed an issue where an hoisted block type, would wrongly be included in the insert menu.
- Fixed an issue with hoisted block type and pasting of HTML (unknown type 'block').
=> [form-builder] Update @sanity/portable-text-editor

packages/@sanity/components/src/tabs/stories/withIcons.js
Breaks if `react-icons` is installed in project at a non-2x version range.
A file inside of `@sanity/components` is requiring something from `react-icons` without `@sanity/components/package.json` having declared react-icons as a dependency.
This usually works because of hoisting - `@react/base` has a dependency on `react-icons`, and usually lifts this dependency up to the root, which means `@sanity/components` can find it and use it.
However, when the user installs `react-icons` in their project and the version range does not match ours (2.x), `react-icons` will be installed two places: inside of `@sanity/base/node_modules` (2x) and inside of the …
=> [components] Fix use of undeclared react-icons dependency in story

.eslintrc.js, packages/eslint-config-sanity/index.js, packages/eslint-config-sanity/package.json, packages/eslint-config-sanity/typescript.js
Rationale for rule changes:
- `complexity` - Seems very low, very common to have large React components where breaking them into separate modules only leads to prop-drilling and unnecessarily deep trees. Also quite common to have readable but long validation/switch statements where adjusting to standard only makes code less readable rather than more. Depend on code reviews to catch hard-to-read code. If 30 is not enough for actual cases, ignore in-place.
- `id-length` - `itemA`/`itemB` and similar is not necessarily more readable than `a`, `b`. Lots of exceptions already in place. Commonly disabled. Catch in code reviews if variables are difficultly named.
- `max-depth` - Seems arbitrarily low. Quite common to have valid, deeper blocks than this. Again, catch exceptions in code-reviews …
=> [eslint] Tweak ESLint rules for commonly ignored cases

packages/@sanity/form-builder/src/inputs/ObjectInput/Field.tsx
When the "InvalidValueInput" component is rendered, the form builder crashes because it's trying to call `focus()` on it, which does not exist.
Crashing example: https://test-studio-git-next.sanity-io.now.sh/test/desk/book;f7101679-9b44-4dbf-824d-1b8b03a4068f
This PR makes sure we check for a `focus` method before attempting to call it. 
Fixed example: https://test-studio-git-fix-schema-type-change.sanity-io.vercel.app/test/desk/book;f7101679-9b44-4dbf-824d-1b8b03a4068f
- Fixed crash when displaying "invalid value" dialog
**Checklist**
=> [form-builder] Check for focus method before calling it

packages/@sanity/form-builder/src/inputs/ArrayInput/InvalidItem.tsx, packages/@sanity/form-builder/src/inputs/ArrayInput/ItemValue.tsx, packages/@sanity/form-builder/src/inputs/InvalidValueInput/InvalidValueInput.tsx, packages/@sanity/form-builder/src/inputs/InvalidValueInput/UntypedValueInput.tsx, packages/@sanity/form-builder/src/utils/resolveTypeName.ts
If an array member type has a `name`, but array items exist that do not have a `_type`, they are silently hidden.
Example: https://test-studio-git-next.sanity-io.now.sh/test/desk/arraysTest;untyped-objects
- "Array of multiple types" actually has one array item, but is not displayed
This PR checks for the case when a member type cannot be found.
- If there is only a single member type that is valid, it renders an option to set the type name
- If there are multiple member types that are valid, it renders the possible types and an option to remove the item
Example: https://test-studio-git-fix-array-missing-type.sanity-io.now.sh/test/desk/arraysTest;unt …
=> [form-builder] Show warning for array items without `_type`

packages/@sanity/core/package.json, packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js, packages/@sanity/core/src/commands/index.js
N/A
This PR adds a CLI command to start the process of copying a dataset. It also exposes a `--wait` flag to wait for the process to finish.
Add CLI command to copy a dataset
**Checklist**
=> [cli] Add a CLI command to copy a dataset

packages/@sanity/cli/.babelrc, packages/@sanity/cli/codemods/reactIconsV3.js, packages/@sanity/cli/src/actions/codemod/mods/index.js, packages/@sanity/cli/src/actions/codemod/mods/reactIconsV3.js, packages/@sanity/cli/src/commands/codemod/codemodCommand.js, packages/@sanity/cli/src/commands/index.js
Every once in a while we find ourselves in a situation where doing changes to a studio is either required or is encouraged. For instance, we've for a while been encountering issues with people inadvertently depending on `react-icons` as a side-effect of `@sanity/base` using it, as well as our documentation having examples encouraging the usage of it without perhaps clearly stating that you should be adding it as a dependency of the studio.
This PR introduces a new CLI command, "codemod", which allows us to run certain code modifications using  [jscodeshift](https://github.com/facebook/jscodeshift). For now, the only included codemod is one that fixes the import/require …
=> [cli] Add codemod command with react-icons migration

packages/@sanity/core/src/actions/start/startAction.js
When you run `sanity start` without being authenticated in the CLI, it'll tell you: 
> Error: You must login first - run "sanity login"
...which is weird, as there are no API interactions to start up a development server
This PR passes a flag to the client wrapper telling it that the command does not require an authenticated user.
- Fixed `sanity start` giving error if CLI had no locally authenticated user
**Checklist**
=> [core] Do not require authed user for `sanity start`

packages/@sanity/core/src/actions/graphql/gen2/generateTypeQueries.js
Currently you have to know which type a document is before querying for it with a `DocumentTypeName` query.
This PR introduces a `Document` field (matches the interface name, is a reserved type for Sanity Studio, and matches the other `DocumentTypeName` queries). It has the same, single argument of a document ID, and has the return type of `Document`, which means you'll have to use conditional fragments to query on non-document properties.
In time we should also see if we can make some kind of psuedo-filter for all types, which would allow `allDocument(...)`, but that's a much larger task.
- Introduce new `Document` field on …
=> [core] Add "Document" query field, returning any document with given ID

packages/@sanity/components/src/tooltip/tooltip.tsx, packages/@sanity/field/src/diff/components/DiffTooltip.tsx
When a diff is hovered and it's close to the top or bottom of the change panel, the tooltip will cover the content instead of positioning itself correctly.
This will make the tooltip place itself where there's enough space, with placement auto and fallback to top and bottom if needed.
- Fixed an issue where tooltips in diff components had the wrong placement when close to top or bottom of the changes panel 
**Checklist**
=> [components, field] fix diff tooltip placement when close to top or bottom of panel

packages/@sanity/components/src/presence/index.ts
When you follow the old presence documentation, it tells (told) you to import paths from `@sanity/components/lib/presence`. This is currently breaking, because we moved the presence pieces into `@sanity/base`. 
This PR adds back the path to the source tree with a deprecation warning. We can probably deprecate this in 3.0.
- Add back (deprecated) presence components in `@sanity/components`
**Checklist**
=> [components] Add back deprecated presence export path

packages/@sanity/cli/templates/blog/tsconfig.json, packages/@sanity/cli/templates/clean/tsconfig.json, packages/@sanity/cli/templates/ecommerce/tsconfig.json, packages/@sanity/cli/templates/moviedb/tsconfig.json
As mentioned in #2035, the tsconfig.json file in bootstrapped studios is not used for transpilation, but only serves to help editors understand parts and such. There is nothing that's indicating that fact, however, which can lead you to believe that modifying the config will yield different results.
This PR adds a few comments to the tsconfig explaining the fact that it's only there for editors sake, and that babel is the brains behind the transpilation.
- Clarify role of tsconfig in new studios
**Checklist**
=> [cli] Clarify tsconfig role in studios

packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/views/editForm.tsx
When the first segment of the focus path is larger than the viewport, the form scrolls to the center of that element instead of to its top.
This PR specifies an option that makes sure we scroll to the top, not the center of the target element.
- Fix issue where the form would scroll to the center of the focused element instead of the top of it
**Checklist**
=> [desk-tool] Scroll to top of input instead of center

packages/@sanity/components/src/tooltip/tooltip.tsx
Fixes a bug where the onHover didn't cover the whole element therefore
making it difficult to get the tooltip shown.
Probably because we attach the onMouseLeave and onMouseEnter onto the
individual child nodes instead of making it enclose all of them.
Difficult to keep the tooltip open because the hover area is inconsistent.
This change adds a div in order to nest the tooltip inside something so the hover area covers all children.
n/a
**Checklist**
=> [components] Wrap Tooltip children in div

packages/@sanity/default-layout/src/navbar/search/SearchResults.css
Vertically centers the loading spinner while it's loading:
**Checklist**
=> [default-layout] Vertically center searching spinner

packages/@sanity/base/src/time/useTimeAgo.ts, packages/@sanity/desk-tool/src/panes/documentPane/changesPanel/changesPanel.tsx, packages/@sanity/desk-tool/src/panes/documentPane/documentPanel/header/header.tsx, packages/@sanity/desk-tool/src/panes/documentPane/statusBar/documentSparkline.tsx
Noticed that the sparkline doesn't currently use the minimal timestamp format, which sometimes makes it hard to read + causing layout issues when document was only published or updated a while ago. Also didn't match the Figma sketch.
This uses the minimal format for the timestamp in the sparkline, but also adds an option called `useAgo` to the `useTimeAgo` hook to make it possible to use both the default and minimal format with and without a trailing `ago`. 
The components using the `useTimeAgo` hook with the minimal format have been updated to use the appropriate `ago` as well.
**Checklist**
=> [base, desk-tool] Update useTimeAgo hook to make trailing `ago` optional, and update sparkline to use minimal timestamp

packages/@sanity/components/src/fieldsets/DefaultFieldset.css, packages/@sanity/components/src/fieldsets/DefaultFieldset.tsx
**Descriptioin**
The field wrappers would also get columns when nested, causing incorrect layouts:
This only applies columns to the field wrapper if there are one or more columns:
- Fixed column layout not working properly in fieldsets with certain content types
**Checklist**
=> [components] fix fieldsets columns with nested fieldwrappers

packages/@sanity/base/src/presence/index.ts
The export of the PresenceScope component which is a part of the public presence API seems to have been accidentally removed in 2.0. This patch adds it back.
Added back export of the PresenceScope component that got accidentally removed in the 2.0 release.
=> [base] Export PresenceScope as part of the public API

packages/@sanity/preview/src/components/RenderPreviewSnapshot.tsx
If you have a reference to a type, it doesn't seem to be passed down to the DefaultPreview component.
Reported by the community:
> If I have a reference type field in a block array, how can I customize the icon to match the selected reference? For example, in this case I’d like the icon to use the configured pie chart icon if a pie chart is selected as the reference.
This checks if it's a reference and tries to find the referenced type icon. Test it in `Array of named references` here: 
**This branch:** https://test-studio-git-type-icons-for-references-in-preview.sanity-io.now.sh/test/desk/arraysTest;4d7e9f30-20eb-4894-a4f1-c6a4eae2646a
**Current:** https://test-studio-git-current.sanity-io.now.sh/test/desk/arrays …
=> [preview] fix type icons not passed down to DefaultPreview for references

packages/@sanity/base/src/change-indicators/ChangeBar.css, packages/@sanity/base/src/change-indicators/ChangeBar.tsx
It's currently not possible to open the changes panel from a field when using a keyboard only.
This makes the hit area in `ChangeBar` a button so that it is possible to get to it with keyboard only, and giving it a negative tab index when the changes panel is open to keep correct focus order of the fields 
- Fixed accessibility in field change bar to make it possible to open changes panel with keyboard only from a field
**Checklist**
=> [base] Fix keyboard accessibility in change bars

packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js
The copy dataset command only checks against the first item in the dataset list response, instead of the whole list of datasets.
This PR fixes ☝️ by actually checking against the whole list instead of the first item in the response.
Fix a problem with the copy dataset command where it didn't correctly check that the source dataset actually exists.
**Checklist**
=> [core] When copying a dataset, the check for existing source datasets was wrong

packages/@sanity/base/src/components/react-track-elements/createScope.tsx, packages/@sanity/base/src/components/react-track-elements/createStore.ts
Do not delete the instructional comments. -->
When using the `useReporter()` or `useReportedValues()` hook outside of a Tracker element context we currently throw an error which makes the studio crash. Since this is currently used for non-critical features like the change connectors and presence we should hard fail when it happens.
This PR issues a console warning instead of crashing the studio. A future improvement would be to make the failure mode configurable on a per-tracker basis, since there might be situations where it's used for more critical features.
Added a more graceful handling of cases where no tracker context …
=> [base] Switch to a warning instead of hard failure on missing tracker context

packages/@sanity/base/package.json, packages/@sanity/base/src/change-indicators/overlay/ConnectorsOverlay.tsx, packages/@sanity/base/src/util/resizeObserver.ts, packages/@sanity/desk-tool/package.json, packages/@sanity/desk-tool/src/tool/DeskToolPanes.js, packages/@sanity/desk-tool/src/tool/resize-observer.ts
Currently the connector lines are not redrawn/recalculated on resize.
This makes sure the connector lines are being redrawn properly on window resize.
There are three separate commits that can be reviewed individually:
- a9718b8 Exports a single resizeObserver instance that can be shared across different studio components (there are performance gains to be had from using a single instance instead of creating multiple). It's also exported with a bit nicer API that fits React hooks a bit better than the native ResizeObserver API.
- 4825c6c Makes desk-tool import the shared resizeObserver instance from base instead of creating its own.
- 55e0e5f Makes …
=> Connectors redraw on resize

packages/@sanity/form-builder/package.json, packages/@sanity/form-builder/src/inputs/PortableText/Input.tsx, packages/@sanity/form-builder/src/inputs/PortableText/Objects/EditObject.tsx
- Fixed an issue where changes to portable text inside a modal would not be saved, if you closed the modal quickly after making changes. 
- Updated to the latest Portable Text Editor - fixes a normalization bug, and adds validation to markDefs and marks.
=> [form-builder] Update PTE module and fix modal saving bug

packages/@sanity/field/src/types/portableText/diff/helpers.ts
Just tolerate that the block might be missing the `.markDefs` property.
=> [field] PT: tolerate missing .markDefs on block

packages/@sanity/components/src/selects/StyleSelect.tsx
The StyleSelect menu is unreachable in certain conditions (small screens, or when PTE is nested in a dialog).
This fix adds a custom Popper modifier that checks the size of the scroll parent (PTE container) and constrains the height based on that.
- Fix overflow issue with StyleSelect menu.
**Checklist**
=> [components] Add maxSize modifier to StyleSelect

packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayInput.tsx, packages/@sanity/form-builder/src/inputs/ArrayInput/item/ArrayInputGridItem.tsx, packages/@sanity/form-builder/src/inputs/ArrayInput/item/ArrayInputItem.tsx, packages/@sanity/form-builder/src/inputs/ArrayInput/item/ArrayInputListItem.tsx
Object arrays with items missing a `_key` will crash the desk tool
Some refactoring in the array input has lead to it crashing the desk tool because it always assumes that items will have a `_key`. This PR checks whether or not it does and uses the array index if the key is not present. I spotted some focus path checking that I think also assumes a `_key`, so this might not be the only fix required for change bars/indicators/connectors to work on keyless items, but it at least prevents the tool from crashing.
- Fixed a bug where array items without a `_key` would crash the desk tool
**Checklist**
=> [form-builder] Fix crash on array items missing `_key`

packages/@sanity/base/sanity.json, packages/@sanity/cli/templates/ecommerce/plugins/barcode-input/sanity.json, packages/@sanity/code-input/sanity.json, packages/@sanity/color-input/sanity.json, packages/@sanity/dashboard/sanity.json, packages/@sanity/data-aspects/sanity.json, packages/@sanity/date-input/sanity.json, packages/@sanity/default-layout/sanity.json, packages/@sanity/default-login/sanity.json, packages/@sanity/desk-tool/sanity.json, packages/@sanity/form-builder/sanity.json, packages/@sanity/language-filter/sanity.json, packages/@sanity/plugin-loader/test/fixture/plugins/better-date/sanity.json, packages/@sanity/plugin-loader/test/fixture/plugins/date/sanity.json, packages/@sanity/plugin-loader/test/fixture/sanity.json, packages/@sanity/plugin-loader/test/loader.test.js, packages/@sanity/production-preview/sanity.json, packages/@sanity/rich-date-input/sanity.json, packages/@sanity/storybook/sanity.json, packages/@sanity/studio-hints/sanity.json, packages/@sanity/vision/sanity.json, packages/blog-studio/sanity.json, packages/clean-studio/sanity.json, packages/ecommerce-studio/plugins/barcode-input/sanity.json, packages/ecommerce-studio/sanity.json, packages/example-studio/sanity.json, packages/movies-studio/sanity.json, packages/storybook/sanity.json, packages/test-studio/sanity.json
Many paths specify an extension, eg ".js", where it's not strictly necessary for the resolving to work. By dropping the extension, we allow for the source paths to resolve to the typescript equivalent (eg `.ts`), while the compiled paths resolve to `.js`.
**Checklist**
=> [chore] Remove extensions from sanity.json paths

packages/@sanity/field/src/diff/components/DiffFromTo.css, packages/@sanity/form-builder/src/inputs/ObjectInput/styles/Field.css
Content in a field overflows the fieldset width:
Content in a field overflows the diff component:
This fixes the overflow issue in both cases. Path to test it in  `/test/desk/blocksTest;6f5befe8-d84a-4b2a-95f3-eae63bbce31f%2Csince%3D%40lastPublished` under recursive blocks and in the changes panel.
**Checklist**
=> [field, form-builder] fix text overflow issue in diff component and field overflow modals

packages/@sanity/form-builder/package.json, packages/@sanity/form-builder/src/inputs/PortableText/Editor.tsx
Upgraded to latest `@sanity/portable-text-editor`. Fixes the following issues:
- Fixed a bug where marks where continued to the next block when pressing enter (splitting) on the end of a block text.
- Fixed a bug with undo/redo when using marks in portable text.
**Checklist**
=> Fix mark bugs in the PTE

packages/@sanity/components/src/fieldsets/DefaultFieldset.tsx, packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx, packages/test-studio/schemas/objects.js
For some reason presence didn't show on collapsed objects and fieldsets. It didn't show when someone was inside a collapsed fields.
Issue was that presence wasn't passed down properly and filtered too early. This fixes that problem.
Also added objects to the schema for testing purposes.
I have tested it a lot, but if I missed something let me know!
- Fixed an issue where presence didn't display people inside collapsed objects or fieldsets
**Checklist**
=> [components, form-builder] fix child presence on collapsed objects and fieldsets

packages/@sanity/dashboard/package.json, packages/@sanity/react-hooks/package.json, packages/@sanity/studio-hints/package.json
These three modules are explicitly listing `@sanity/base` as a dependency, when they're actually only using the parts system to import. That means the additional dependency is a potential for version mismatches, which has been happening now and then.
This PR removes the direct dependency on `@sanity/base`, hopefully solving the problem where the modules would not get a bumped version of `@sanity/base` when publishing new versions, and reducing cross-dependency chatter.
**Checklist**
=> [chore] Remove unnecessary internal dependency

packages/@sanity/core/package.json, packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js
Currently the dataset copy command crashes unless the `eventsource` dependency happens to be hoisted by a sibling.
This adds `@sanity/eventsource` as a direct dependency and uses that internally. Fixes #2102
- Fixed missing dependency in `@sanity/core` sometimes causing `sanity dataset copy` to crash
**Checklist**
=> [core] Fix missing eventsource dependency

packages/@sanity/form-builder/src/inputs/common/UploadTarget/createUploadTarget.tsx
With the change in 636bb79d1a7cfd694909fa941c43b6bd1e9f7ee4 we are now passing a path to the `onFocus` method of the input, which apparently was expecting an event in the upload target for images/files. Thus, calling  `stopPropagation` on it would crash. 
This PR changes it to expect a Path. I haven't seen any side-effects of this change, but I wasn't 100% sure if there were still cases where an event would be passed and expecting the focus terminator to be passed down, so I added a ternary just in case, to maintain the old behavior (apart from the `stopPropagation` call)
**Checklist**
=> [form-builder] Handle focus when passed a path instead of an event

packages/@sanity/cli/src/actions/init-project/createManifest.js
CLI templates include only the npm scripts `start` and `test`.
If you're making a template starter for /create with a CLI bootstrapped studio, you have to remember to add a `build` script to the package.json. This seems like something we could've just include from the get-go. 
I tried to figure out how we could add the `@sanity/cli` to dev-dependencies too with no avail. This is also needed (or the npx equivalent) to run the build script in a CI environment.
Add build script to template studios to make them more easily deployable on other hosting platforms.
**Checklist**
=> [cli] Add build script to template package.json
