- packages/@sanity/components/src/edititem/PopOver.js
- packages/@sanity/components/src/edititem/styles/PopOver.css
- packages/@sanity/components/src/edititem/utils.js
Rebuilt from the ground up.
* Fix modal stacking and positioning (modals within modals)
* Track focus (when modals in modals)
* Fix resize event handling bugs
* Fix bug closing all dialogs on escape (not just the topmost)
* Make code more streamlined / less complex
> [components] Refactor PopOver heavily

- packages/@sanity/components/sanity.json
- packages/@sanity/components/src/buttons/AnchorButton.js
- packages/@sanity/components/src/buttons/story.js
- packages/@sanity/form-builder/src/inputs/File/FileInput.js
- packages/@sanity/form-builder/src/inputs/File/createFileInput.js
- packages/@sanity/form-builder/src/inputs/File/styles/FileInput.css
Currently dumps the referenced object as JSON, needs some more styling.
> [form-builder] Materialize file reference in File component

- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/conversion/slateHTMLDeserializer/helpers.js
Transforms nested block tags into a flat structure when pasting html.
> [form-builder] Block editor: paste from html - unwrap nested block tags

- packages/@sanity/components/src/panes/SplitController.js
- packages/@sanity/components/src/panes/styles/DefaultPane.css
- packages/@sanity/components/src/panes/styles/SplitController.css
Make consistent DOM so that react does not reload content in the panes. Also fixes some glitches with the UI
> [components] Fixing panes

- CONTRIBUTING.md
- README.md
This is ment as a starting point and should be continuously be improved upon as we go. The part about _release/workflow guidelines_ is based on our internal discussions, the rest is mainly just copy paste from https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md (the parts I felt was relevant, with minor adjustments)
Other resources:
- https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines
- http://mozillascience.github.io/working-open-workshop/contributing/
> [community] First pass at establisning contributor guidelines

- packages/@sanity/cli/src/scripts/package-yarn.js
> [cli] Upgrade yarn to 0.27.5

- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderBlock.js
... until we have a rock solid popover
> [form-builder] Using fullscreen to edit blocks in block editor 

- packages/@sanity/base/src/components/QueryContainer.js
This fixes some weird update behavior in a few cases
> [base] Include props.children in sCU equality check

- packages/@sanity/form-builder/src/inputs/Array/ItemValue.js
This should be trivial and critical enough to go directly into master
> [form-builder] Use default drag handle

- packages/@sanity/base/src/preview/streams/intersectionObservableFor.js
Just a minor code style issue that wouldn't allow the tests to pass
> [base] Fix code style issue

- packages/@sanity/components/src/toggles/Switch.js
> [components] Fix onBlur error

- packages/@sanity/default-layout/src/components/Search.js
Split and filter correctly, then join back the query string correctly into a (suboptimal) constraint.
> [default-layout] Make query work as expected

- packages/@sanity/cli/src/actions/user/createProvisionalUser.js
- packages/@sanity/cli/src/commands/init/bootstrapPlugin.js
- packages/@sanity/cli/src/commands/init/initPlugin.js
- packages/@sanity/cli/src/commands/init/initSanity.js
This PR removes some unused code paths in the CLI that will need reimplementation if we want to utilize them in the future.
> [cli] Clean up unused code paths

- packages/@sanity/import/src/assetRefs.js
- packages/@sanity/import/src/uploadAssets.js
This fixes a rather emberrasing bug where assets would not have their references set correctly during import.
> [import] Fix issue where asset references would not be set correctly

- packages/@sanity/base/src/styles/variables/brand-colors.css
- packages/@sanity/base/src/styles/variables/gray-colors.css
- packages/@sanity/base/src/styles/variables/selectable-item.css
- packages/@sanity/base/src/styles/variables/typography.css
- packages/@sanity/components/src/buttons/styles/DefaultButton.css
- packages/@sanity/components/src/edititem/styles/FoldOut.css
- packages/@sanity/components/src/edititem/styles/PopOver.css
- packages/@sanity/default-layout/src/components/styles/ToolSwitcher.css
Adding space between + and -. 
Example: color(var(--my-var) lightness(+ 10%))
> [css] Fixing color syntax

- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/BlockEditor.js
- packages/@sanity/form-builder/src/inputs/Image/ImageInput.js
- packages/@sanity/form-builder/src/inputs/Object/Field.js
- packages/@sanity/form-builder/src/inputs/Object/Object.js
- packages/@sanity/form-builder/src/inputs/Reference/searchableSelect/ReferenceSearchableSelect.js
- packages/@sanity/form-builder/src/inputs/Slug/SlugInput.js
This removes the validation cruft which has no function yet. We will need to re-introduce this some point in the future, but for now it is just noise, so I suggest we just remove it.
> [form-builder] Remove unused validation cruft

- packages/@sanity/components/package.json
- packages/@sanity/components/src/previews/CardPreview.js
- packages/@sanity/desk-tool/package.json
- packages/@sanity/desk-tool/src/components/ConfirmDiscard.js
- packages/@sanity/desk-tool/src/components/ConfirmPublish.js
- packages/@sanity/desk-tool/src/components/TimeAgo.js
- packages/test-studio/schemas/book.js
In my journey down the 🐰 🕳  yesterday, I desperately tried to see if replacing moment with date-fns would relieve me from my woes. It didn't, but at least I managed to replace moment with date-fns in a few places.
> [chore] Replace moment with date-fns

- packages/@sanity/server/src/configs/webpack.config.js
> [server] Fix issue with webpack/moment

- packages/@sanity/form-builder/src/inputs/Image/SelectAsset.js
This sorts the assets in the "Select from library"-dialog by newest first.
> [form-builder] Sort assets by last updated

- packages/@sanity/default-layout/src/components/Search.js
This opens the suggestion panel if hitting arrow keys or clicking the input (e.g. after escape)
> [default-layout] Make global search open on arrows + input click

- scripts/symlinkDependencies.js
> [chore] Use indexOf instead of includes for node 4 compat

- packages/@sanity/google-maps-input/src/GeopointInput.js
> [google-maps-input] Make remove button actually remove

- packages/@sanity/default-login/README.md
- packages/@sanity/default-login/src/LoginWrapper.js
Children can be a function that passes the user to the wrapped content.
> [default-login] Pass user to child content

- packages/@sanity/components/src/selects/DefaultSelect.js
This should go into master and be released immediately.
> [components] Remove onChange from props before passing down {...rest}

- packages/@sanity/client/src/data/dataMethods.js
- packages/@sanity/client/test/client.test.js
Pending infrastructure changes, but this PR increases the max query size limit to 11kB.
> [client] Increase query size limit to 11kB

- packages/@sanity/schema/src/sanity/validation/types/reference.js
This gives a sane warning if the `to` property on references has an invalid value or is missing.
> [schema] Improve reference type validation

- packages/example-studio/components/ProteinInput/PDBS.js
- packages/example-studio/components/ProteinInput/ProteinInput.js
- packages/example-studio/components/ProteinInput/schema.js
- packages/example-studio/schemas/proteinTest.js
- packages/example-studio/schemas/schema.js
This cleans up the protein input, removes a few unused methods and makes the flow of events a bit more predictable. Should make it more robust wrt. realtime editing too.
> [example-studio] Simplify and fix a a few issues w/protein input example

- packages/@sanity/default-layout/src/components/styles/Branding.css
> [default-layout] Center project name

- packages/@sanity/document-window/.eslintignore
- packages/@sanity/document-window/.eslintrc
- packages/@sanity/document-window/.gitignore
- packages/@sanity/document-window/.npmignore
- packages/@sanity/document-window/KNOWN-ISSUES.md
- packages/@sanity/document-window/README.md
- packages/@sanity/document-window/package.json
- packages/@sanity/document-window/src/Constants.js
- packages/@sanity/document-window/src/DocumentWindow.js
- packages/@sanity/document-window/src/Query.js
- packages/@sanity/document-window/src/concatWindows.js
- packages/@sanity/document-window/src/sortBy.js
- packages/@sanity/document-window/src/sortOrderToOperator.js
- packages/@sanity/document-window/test/.eslintrc
- packages/@sanity/document-window/test/__snapshots__/insertion-in-buffers.test.js.snap
- packages/@sanity/document-window/test/__snapshots__/insertion-inside-window.test.js.snap
- packages/@sanity/document-window/test/__snapshots__/insertion-outside-buffers.test.js.snap
- packages/@sanity/document-window/test/__snapshots__/update-in-buffers.test.js.snap
- packages/@sanity/document-window/test/__snapshots__/update-inside-window.test.js.snap
- packages/@sanity/document-window/test/basics.test.js
- packages/@sanity/document-window/test/fixtures.js
- packages/@sanity/document-window/test/helpers.js
- packages/@sanity/document-window/test/insertion-in-buffers.test.js
- packages/@sanity/document-window/test/insertion-inside-window.test.js
- packages/@sanity/document-window/test/insertion-outside-buffers.test.js
- packages/@sanity/document-window/test/setup.js
- packages/@sanity/document-window/test/update-in-buffers.test.js
- packages/@sanity/document-window/test/update-inside-window.test.js
This is the first draft of the document window module that we've been talking about.
There are a couple of known issues regarding total list size and backfilling as well as sorting for equal values not being correct. This is documented in KNOWN-ISSUES.md.
I also want to move away from the class structure and rather have all the internal state as actual, private state variables instead of prefixing them with `_`.
> Document window module

- packages/@sanity/client/package.json
This adds React Native support to `@sanity/client` though https://github.com/sanity-io/get-it/pull/10
> [client] Upgrade get-it

- packages/@sanity/default-login/src/CookieTest.js
- packages/@sanity/default-login/src/CorsCheck.js
- packages/@sanity/default-login/src/ErrorDialog.js
- packages/@sanity/default-login/src/LoginDialog.js
- packages/@sanity/default-login/src/LoginWrapper.js
- packages/@sanity/default-login/src/authenticationFetcher.js
- packages/@sanity/default-login/src/styles/LoginDialog.css
* Fix broken design putting elements on top of each other in some screens and resolutions (never use absolute positions)
* Catch 401 from /users/me which was making it impossible to get out of the error dialog.
* Show design correctly on the CookieTest-component.
* Minor tweaks
> [default-login] Design and error handling fixes

- packages/@sanity/cli/bin/sanity.js
Related: https://github.com/nodejs/node/issues/13557
> [cli] Ban node version 8.1.0 and 8.1.1

- packages/@sanity/cli/src/scripts/package-yarn.js
Been a while since we last upgraded yarn. Since then there's been a lot of bugfixes, so we should try to keep up.
> [cli] Upgrade yarn to latest version

- packages/test-studio/schemas/arrays.js
- packages/test-studio/schemas/datetime.js
- packages/test-studio/schemas/fieldsets.js
- packages/test-studio/schemas/recursiveArray.js
This just adds a few more test cases to the test-studio schema
> [test-studio] Tweak test cases and add a few more

- packages/@sanity/base/src/styles/variables/selectable-item.css
- packages/@sanity/components/src/buttons/styles/InInput.css
- packages/@sanity/components/src/loading/Spinner.js
- packages/@sanity/components/src/previews/common/SvgPlaceholder.js
- packages/@sanity/components/src/previews/styles/DefaultPreview.css
- packages/@sanity/components/src/progress/styles/ProgressBar.css
- packages/@sanity/default-layout/src/components/styles/Search.css
This should be good to be merged IMHO. Only minor changes.
> [all] Some changes to make the dark theme plugin work

- packages/@sanity/cli/src/actions/init-plugin/pluginTemplates.js
One more plugin template to help people get started.
Is the name good enough?
> [cli] Add chess board input as plugin template

- packages/@sanity/default-layout/src/components/DefaultLayoutContainer.js
- packages/@sanity/default-login/src/CookieTest.js
- packages/@sanity/default-login/src/LoginDialog.js
- packages/@sanity/default-login/src/LoginWrapper.js
Strange thing. React seems to not render functions when lowercase first letter.
> [default-login] Using capital first letter to render SanityLogo

- packages/@sanity/image-url/README.md
- packages/@sanity/image-url/src/builder.js
- packages/@sanity/image-url/src/urlForImage.js
- packages/@sanity/image-url/test/builder.test.js
Adds support for `fit('crop')` to the image-url builder
> [image-url] Added support for the fit-parameter

- packages/@sanity/form-builder/package.json
- packages/@sanity/form-builder/src/inputs/Image/ImageInput.css
- packages/@sanity/form-builder/src/inputs/Image/ImageInput.js
- packages/@sanity/imagetool/src/ImageTool.js
* Better performance on bigger image (sending chenges only on dragEnd)
* Responsive CSS
* Using imageUrlBuilder creating suitable sizes
> UX on image tool

- packages/@sanity/vision/src/SanityVision.js
This solves #433 by cloning the client on vision startup
> [vision] Clone client on startup (prevents reconfiguration)

- packages/@sanity/base/src/styles/forms/clear-button.css
- packages/@sanity/base/src/styles/forms/text-input.css
- packages/@sanity/base/src/styles/variables/brand-colors.css
- packages/@sanity/base/src/styles/variables/forms.css
- packages/@sanity/base/src/styles/variables/globals.css
- packages/@sanity/components/src/buttons/createButtonLike.js
- packages/@sanity/components/src/buttons/story.js
- packages/@sanity/components/src/buttons/styles/DefaultButton.css
- packages/@sanity/components/src/buttons/styles/DropDownButton.css
- packages/@sanity/components/src/fieldsets/styles/DefaultFieldset.css
- packages/@sanity/components/src/selects/DefaultSelect.js
- packages/@sanity/components/src/selects/StatelessSearchableSelect.js
- packages/@sanity/components/src/selects/StyleSelect.js
- packages/@sanity/components/src/selects/styles/DefaultSelect.css
- packages/@sanity/components/src/selects/styles/SearchableSelect.css
- packages/@sanity/components/src/selects/styles/StyleSelect.css
- packages/@sanity/components/src/textfields/DefaultTextField.js
- packages/@sanity/components/src/textfields/story.js
- packages/@sanity/components/src/textinputs/styles/DefaultTextInput.css
- packages/@sanity/components/src/toggles/styles/ToggleButton.css
Needs to be merged after design/initial view
> Design/input components (wait for #486)

- package.json
- packages/@sanity/code-input/package.json
- packages/@sanity/default-layout/package.json
- packages/@sanity/desk-tool/package.json
- packages/@sanity/rich-date-input/package.json
- yarn.lock
Seems like I missed a few things in #474. This should get rid of all cyclic dependencies from `package.json`'s and also upgrade Lerna for reals.
> [chore] More deps cleanup + upgrade lerna

- .travis.yml
- packages/@sanity/cli/src/actions/init-project/initProject.js
This should hopefully fix a few issues with the Travis build. Fingers crossed.
> [chore] Fix travis build

- packages/@sanity/base/sanity.json
- packages/@sanity/base/src/components/icons/Calendar.js
- packages/@sanity/base/src/styles/forms/text-input.css
- packages/@sanity/default-layout/src/components/styles/UpdateNotifier.css
- packages/@sanity/form-builder/package.json
- packages/@sanity/form-builder/src/inputs/DateTime/DateTimeInput.js
- packages/@sanity/form-builder/src/inputs/DateTime/styles/DateTimeInput.css
- packages/@sanity/form-builder/src/inputs/DateTime/styles/variables.css
- packages/@sanity/rich-date-input/package.json
- packages/@sanity/rich-date-input/src/RichDate.css
- packages/@sanity/rich-date-input/src/variables.css
- packages/test-studio/schemas/richDate.js
> [form-builder] Moving over styling from rich-date and fixing datetime

- packages/@sanity/components/src/progress/ProgressCircle.js
- packages/@sanity/components/src/progress/styles/ProgressBar.css
- packages/@sanity/components/src/progress/styles/ProgressCircle.css
- packages/@sanity/form-builder/src/inputs/File/FileInput.js
- packages/@sanity/form-builder/src/inputs/File/styles/FileInput.css
- packages/@sanity/form-builder/src/inputs/Image/ImageInput.js
- packages/@sanity/form-builder/src/inputs/Image/styles/ImageInput.css
Using circle progress on image
> Styling upload input progress

- packages/@sanity/desk-tool/src/pane/EditorWrapper.js
Publishing a document is a two-step process:
1. Create a document from the draft (without the `draft.`-prefix in document id)
2. Delete the draft
This makes sure the publishing happens in a single transaction so that if (for some reason) one of the steps above fails, the whole process is aborted.
This change needs to be thoroughly tested.
> [desk-tool] Publish documents in a transaction

- packages/@sanity/cli/templates/moviedb/schemas/blockContent.js
- packages/@sanity/cli/templates/moviedb/schemas/castMember.js
- packages/@sanity/cli/templates/moviedb/schemas/crewMember.js
- packages/@sanity/cli/templates/moviedb/schemas/movie.js
- packages/@sanity/cli/templates/moviedb/schemas/person.js
- packages/@sanity/cli/templates/moviedb/schemas/screening.js
- packages/movies-studio/package.json
- packages/movies-studio/resolveProductionUrl.js
- packages/movies-studio/sanity.json
This contains a few adjustments to the moviedb template, for example it now uses `media` for preview where applicable. Also adds a production url resolver to the movies studio.
> [cli] Tweak moviedb template schema

- packages/@sanity/preview/src/components/PreviewSubscriber.js
This will tear down preview listeners 20 seconds _after_ a `visibilitychange` event has changed the document visibility state to hidden unless a new event changes it to visible in the meantime.
> [preview] Wait 20s after page visibility changes to off before disposing preview listeners

- .prettierrc
> [chore] Bump prettier print width to 100

- packages/@sanity/google-maps-input/styles/GeopointInput.css
This fixes a bug where the close button would fall behind the actual map.
> [google-maps-input] Fix close button layering

- packages/@sanity/imagetool/src/ImageTool.js
This displays drag handles on crop rect in image tool for improved touch screen usability.
> [imagetool] Always show drag handles on crop rect

- packages/@sanity/form-builder/src/sanity/focusManagers/HashFocusManager.js
- packages/@sanity/form-builder/src/sanity/formBuilderValueStore.js
- packages/@sanity/form-builder/src/sanity/utils/convertPath.js
- packages/@sanity/form-builder/src/sanity/utils/gradientPatchAdapter.js
- packages/@sanity/form-builder/src/typedefs/patch.js
- packages/@sanity/form-builder/src/typedefs/path.js
- packages/@sanity/form-builder/src/utils/patches.js
This is a refactoring of the adapter that converts between the internal patch format used by the form builder and the patch format used on the backend.
> [form-builder] Refactor gradientPatchAdapter

- packages/@sanity/default-layout/src/components/styles/DefaultLayout.css
> [default-layout] Removing padding from secondary navigation

- packages/@sanity/components/src/panes/styles/DefaultPane.css
Fixes a bug causing the form to not appear
> [components] Override scrollcontainer default style.

- packages/@sanity/imagetool/src/styles/ImageTool.css
Quickfix for canvas rendering to small
> [imagetool] Min-width on canvas

- packages/@sanity/validation/src/inferFromSchemaType.js
This fixes a bug allowed options using title + value would not be inferred correctly
> [validation] Infer value from title/value list options

- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/BlockEditor.js
- packages/test-studio/schemas/blocks.js
This adds readOnly support for the block editor.
> [form-builder] Support readOnly on block editor

- packages/@sanity/cli/src/actions/init-project/templates/moviedb.js
Bundled assets (with reduced sizes)
> [cli] Update URL for moviedb dataset

- packages/@sanity/default-layout/package.json
- packages/@sanity/default-layout/src/components/SchemaErrors.js
For some reason this import was relative when it should've been targeting the package.
> [default-layout] Fix wrong relative import

- packages/@sanity/components/src/buttons/styles/DefaultButton.css
- packages/@sanity/components/src/dialogs/ConfirmDialog.js
- packages/@sanity/desk-tool/src/components/ConfirmDelete.js
kind="secondary" is deprecated on button. Use inverted.
>  [components] Remove deprecated kind secondary button

- packages/@sanity/core/package.json
- packages/@sanity/core/src/util/checkReactCompatibility.js
This will warn when studio is started with one or more deprecated react packages.
> [core] Warn on deprecated react version

- packages/blog-studio/package.json
- packages/example-studio/package.json
- packages/movies-studio/package.json
- packages/storybook/package.json
- packages/test-studio/package.json
Lets upgrade to React 16 in the development/example studios
> [dev-studios] Upgrade to React 16

- packages/@sanity/form-builder/src/sanity/inputs/client-adapters/assets.js
This will prevent uploading the same file multiple times and instead create a reference to the previous uploaded file
> [form-builder] Checksum files before uploading and link with existing asset document if any

- packages/@sanity/cli/templates/moviedb/schemas/blockContent.js
- packages/@sanity/cli/templates/moviedb/schemas/plotSummaries.js
- packages/@sanity/cli/templates/moviedb/schemas/schema.js
> [movies-studio] Removing references from block content. 

- packages/@sanity/cli/templates/moviedb/schemas/plotSummaries.js
Using text to avoid recursive block conent
> [movies-studio] No recursive blockContent

- packages/@sanity/core/src/actions/config/reinitializePluginConfigs.js
The attempt to fix this in #298 didn't quite succeed, cause there was another similar check. Quick-fixing this for now by commenting out the check. Should probably clean this up properly later on :)
> [core] Remove checksum warning until we can provide a way of fixing

- .travis.yml
- packages/@sanity/core/src/actions/config/reinitializePluginConfigs.js
> [chore] Test on node 10 instead of node 9

- packages/@sanity/presence-store/package.json
- packages/@sanity/presence-store/src/PresenceStore.js
Couple of code style fixes as well
> [presence-store] Fix path to entry file

- packages/@sanity/components/src/toggles/styles/Switch.css
- packages/test-studio/schemas/booleans.js
Fixes a bug where description in fieldsets overflows.
> Overflowing switch description

- packages/@sanity/desk-tool/src/pane/Editor.js
- packages/@sanity/desk-tool/src/pane/styles/Editor.css
Minor tweaks to the desk-tool editor header
> [desk-tool] Fix syncing icon and publish button spacing

- packages/@sanity/core/src/actions/cors/addCorsOrigin.js
- packages/@sanity/core/src/commands/cors/addCorsOriginCommand.js
- packages/@sanity/core/src/commands/cors/corsGroup.js
- packages/@sanity/core/src/commands/cors/deleteCorsOriginCommand.js
- packages/@sanity/core/src/commands/cors/listCorsOriginsCommand.js
- packages/@sanity/core/src/commands/index.js
Allows listing, creating and deleting CORS-origins.
Closes #729
> [core] Add CLI-commands for managing CORS-origins

- packages/@sanity/cli/templates/ecommerce/schemas/product.js
Trivial change form text to strings for blurbs.
> [ecommerce-studio] Change blurb to from localText to localeString

- packages/@sanity/form-builder/src/inputs/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.js
Fixes a bug causing the add-button on array of primitives to faceplant
> [form-builder] Fix invalid prop

- packages/@sanity/components/sanity.json
- packages/@sanity/components/src/dialogs/DefaultDialog.js
- packages/@sanity/components/src/dialogs/DialogContent.js
- packages/@sanity/components/src/dialogs/styles/DefaultDialog.css
- packages/@sanity/components/src/dialogs/styles/DialogContent.css
- packages/@sanity/components/src/dialogs/styles/PopOver.css
- packages/@sanity/form-builder/src/inputs/ArrayInput/ItemValue.js
- packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ItemValue.css
- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderBlock.js
- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderInline.js
- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/FormBuilderSpan.js
- packages/@sanity/form-builder/src/inputs/DateInputs/styles/BaseDateTimeInput.css
- DateTime input dialog as now working
- DialogContent component is now a part and can be used to size content
- minor cleanup
> DialogContent component for sizing dialogs

- packages/@sanity/components/src/selects/StyleSelect.js
- packages/@sanity/components/src/selects/styles/StyleSelect.css
Portal does not longer take the `className` prop.
Wrapping it in a `<div>`.
> [components] Fixing styleselect portal

- packages/@sanity/import/package.json
- packages/@sanity/import/src/importBatches.js
- packages/@sanity/import/src/references.js
- packages/@sanity/import/src/uploadAssets.js
- packages/@sanity/import/src/util/getHashedBufferForUri.js
- packages/@sanity/import/src/util/retryOnFailure.js
- packages/@sanity/import/test/retryOnFailure.test.js
This PR introduces some basic retrying while importing data with a simple backoff algorithm.
> [import] Add retry handling on write operations

- packages/@sanity/block-tools/src/converters/blocksToSlateState.js
- packages/@sanity/components/src/selects/StyleSelect.js
- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/BlockEditor.js
- packages/@sanity/form-builder/src/inputs/BlockEditor-slate/Syncer.js
- packages/test-studio/schemas/blocks.js
instead of enhanceWithClickOutside
This fixes a bug where styleselect in an dialog closes when a style is selected.
This still have an issue where the dialog seems to re-render when onChange is called.
Maybe @skogsmaskin have a solution to this?
> [components] Using stacked and captureclickoutside

- packages/@sanity/cli/src/actions/init-project/initProject.js
Yep. Here it is. Since I'm keeping forgetting to set the clean template flag, and since we want to communicate that Sanity can be used for anything.
> [cli] Add option for initiating sanity with a clean template

- packages/@sanity/color-input/README.md
- packages/@sanity/color-input/sanity.json
- packages/@sanity/color-input/src/schema.js
> [color-input] Add documentation for color input

- packages/@sanity/form-builder/src/inputs/DateInputs/BaseDateTimeInput.js
- Make datepicker stay open on change date
- Reset inputValue when edit raw is parsed and valid
> [form-builder] Datepicker fixes

- packages/@sanity/cli/package.json
- packages/@sanity/cli/scripts/pack.js
- packages/@sanity/cli/src/commands/index.js
- packages/@sanity/cli/src/commands/projects/listProjectsCommand.js
- packages/@sanity/cli/src/commands/projects/projectsGroup.js
This PR adds functionality for listing out all projects with some basic info tied to the logged-in Sanity user account.
> [cli] Add project list command

- README.md
- packages/@sanity/cli/templates/blog/README.md
- packages/@sanity/cli/templates/blog/schemas/blockContent.js
- packages/@sanity/cli/templates/blog/schemas/schema.js
- packages/@sanity/cli/templates/clean/README.md
- packages/@sanity/cli/templates/clean/schemas/schema.js
- packages/@sanity/cli/templates/ecommerce/README.md
- packages/@sanity/cli/templates/ecommerce/schemas/blockContent.js
- packages/@sanity/cli/templates/ecommerce/schemas/schema.js
- packages/@sanity/cli/templates/moviedb/README.md
- packages/@sanity/cli/templates/moviedb/schemas/blockContent.js
- packages/@sanity/cli/templates/moviedb/schemas/schema.js
README.md on all template examples. Some work on the main Readme.md with updated links and such.
> Improve onboarding

- packages/@sanity/cli/src/actions/init-project/bootstrapTemplate.js
- packages/@sanity/cli/src/actions/init-project/initProject.js
- packages/@sanity/cli/src/actions/init-project/templates/ecommerce.js
- packages/@sanity/cli/src/actions/init-project/templates/moviedb.js
Based on user tests, here's some changes to make things clearer in the on-boarding context. Feedback appreciated!
> Improve cli onboarding

- packages/@sanity/components/src/toggles/Switch.js
- packages/@sanity/components/src/toggles/story.js
- packages/@sanity/components/src/toggles/styles/Switch.css
Also fixes weird line break on description
> [components] Cleanup switch component

- packages/test-studio/schemas/texts.js
Show rows settings on text input in test-studio.
> [test-studio] Example of setting rows

- packages/@sanity/schema/src/legacy/resolveSearchFields.js
This improves search for text contents within arrays by actually stepping into the content types of arrays when looking for string fields.
> [schema] Improve text search within arrays

- packages/@sanity/core/src/actions/build/buildStaticAssets.js
- packages/@sanity/core/src/commands/build/buildCommand.js
- packages/@sanity/core/src/commands/deploy/deployCommand.js
This is very important and urgent.
> [chore] Fix a very important and urgent issue

- packages/@sanity/server/package.json
This upgrades react-hot-loader to latest, which should fix some babel 7 issues.
> [server] Upgrade React hot loader

- packages/@sanity/base/src/styles/variables/selectable-item.css
- packages/@sanity/components/package.json
- packages/@sanity/components/sanity.json
- packages/@sanity/components/src/buttons/DropDownButton.js
- packages/@sanity/components/src/buttons/styles/DropDownButton.css
- packages/@sanity/components/src/lists/default/ListItem.js
- packages/@sanity/components/src/utilities/ArrowKeyNavigation.js
- packages/test-studio/schemas/arrays.js
- Keyboard navigation
- Using list and listitem (no menu)
- fixes position bug
> Dropdown button cleanup

- packages/@sanity/image-url/package.json
- packages/@sanity/image-url/src/builder.js
- packages/@sanity/image-url/src/urlForImage.js
- packages/@sanity/image-url/test/__snapshots__/builder.test.js.snap
- packages/@sanity/image-url/test/builder.test.js
Adds the `bg` (background color) parameter to the builder API.
> [image-url] Add builder method for background color (bg)

- packages/@sanity/mutator/.babel-init.js
- packages/@sanity/mutator/.babelrc
- packages/@sanity/mutator/package.json
- packages/@sanity/mutator/perf/fixtures/patches.js
- packages/@sanity/mutator/perf/fixtures/snapshot.js
- packages/@sanity/mutator/perf/run.js
- packages/@sanity/mutator/src/document/SquashingBuffer.js
- packages/@sanity/mutator/test/SquashingBuffer.test.js
Optimize SquashingBuffer by consecutively applying patches on the PRESTAGE document
> [mutator] Optimize SquashingBuffer

- packages/@sanity/default-login/src/LoginDialog.js
- packages/@sanity/default-login/src/LoginWrapper.js
Also fix deprecated React lifecycle methods.
> [default-login] Fix invalid notice of no providers configured

- packages/@sanity/preview/src/observeFields.js
When we fetch values for previews and get `undefined` back, it can be because the index is not yet updated, so we wait a second before checking to verify. This mechanism sometimes caused the previews to stall for up to a second.
This fixes it so that we "optimistically" assume that the value is undefined by passing it through immediately while performing the check in the background instead.
> [preview] Pass through undefined and re-fetch in background when encountering undefined values

- packages/@sanity/components/src/dialogs/FullscreenDialog.js
- packages/@sanity/desk-tool/src/components/InspectView.js
- packages/@sanity/desk-tool/src/components/styles/InspectView.css
- packages/@sanity/desk-tool/src/pane/DocumentsListPane.js
This fixes an issue with view mode toggle buttons, uses fullscreen when inspecting document + misc. minor improvements
> [desk-tool] Inspect-view improvements

- packages/@sanity/components/src/panes/styles/DefaultPane.css
> [components] Fix editor menu z-index

- packages/@sanity/desk-tool/src/pane/EditorPane.js
- packages/@sanity/desk-tool/src/pane/styles/EditorWrapper.css
- packages/@sanity/document-store/src/createObservableBufferedDocument.js
- packages/@sanity/mutator/src/document/Document.js
... and display error message in desk tool
> [mutator/desk-tool] Propagate mutator errors through document store

- lerna.json
- packages/sanity/README.md
- packages/sanity/package.json
- packages/sanity/placeholder.js
This adds the `sanity` package placeholder to the monorepo until we figure out how to use it (note: it's already published).
> [sanity] Add sanity package placeholder

- packages/@sanity/default-layout/src/components/styles/DefaultLayout.css
- packages/@sanity/default-layout/src/components/styles/SideMenu.css
> [default-layout] Use safe area to place outside notch

- packages/@sanity/color-input/src/ColorInput.js
- packages/@sanity/color-input/src/ColorPicker.css
- packages/@sanity/color-input/src/ColorPicker.js
- packages/test-studio/schemas/color.js
> Readonly color input

- packages/@sanity/components/src/panes/SplitController.js
- packages/@sanity/components/src/panes/SplitPaneWrapper.js
- packages/@sanity/components/src/panes/styles/SplitController.css
- packages/@sanity/desk-tool/src/DeskToolPanes.js
- Fixes a bug where panes get unmounted
- Fixes a bug where panes did not load when switching when it was collapsed
- Forces Expand on new panes
> Auto collapse fixes

- packages/@sanity/code-input/sanity.json
I got the parts mixed up on the last PR 🤦‍♂️
> [code-input] Fix incorrect parts implemented

- packages/@sanity/desk-tool/src/pane/EditorPane.js
- packages/@sanity/desk-tool/src/pane/styles/EditorWrapper.css
- packages/@sanity/desk-tool/src/utils/UseState.js
This improves the error message displayed if, for some reason, an error occurs during patching.
> [desk-tool] Improve error message display

- packages/@sanity/form-builder/src/inputs/BlockEditor/BlockExtrasOverlay.js
There were some wrong props passed to the render block action component.
> [form-builder] Fix block actions props

- packages/@sanity/core/.eslintrc
- packages/@sanity/core/src/actions/dataset/datasetNamePrompt.js
- packages/@sanity/core/src/actions/dataset/validateDatasetName.js
- packages/@sanity/core/src/commands/dataset/createDatasetCommand.js
- packages/@sanity/core/src/commands/dataset/datasetVisibilityCommand.js
- packages/@sanity/core/src/commands/dataset/deleteDatasetCommand.js
- packages/@sanity/core/src/commands/dataset/exportDatasetCommand.js
- packages/@sanity/core/src/commands/dataset/importDatasetCommand.js
> [core] Improve dataset name validation

- packages/@sanity/default-layout/src/components/LoginStatus.js
- packages/@sanity/default-layout/src/components/SideMenu.js
- packages/@sanity/default-layout/src/components/styles/LoginStatus.css
- packages/@sanity/default-layout/src/components/styles/SideMenu.css
> [default-layout] Show first letter in name as fallback

- .github/ISSUE_TEMPLATE/bug_report.md
Wasn't aware that we had a separate template for feature requests.
> Remove feature request description

- packages/@sanity/core/src/actions/build/compressJavascript.js
Terser decided to switch to bundle their releases with rollup in a minor change. This broke our minifying;
```
TypeError: Cannot read property 'minify' of undefined
at Object.<anonymous> (/Users/espenh/webdev/tersertest/node_modules/@sanity/core/lib/actions/build/compressJavascript.js:12:29)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Module._compile (/Users/espenh/webdev/tersertest/node_modules/pirates/lib/index.js:83:24)
at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Object.newLoader [as .js] (/Users/espenh/webdev/tersertest/node_modules/pirates/lib/index.js:88:7)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at …
```
> [core] Fix breaking change in upstream terser dependency

- packages/@sanity/client/package.json
- packages/@sanity/import/package.json
Upgrading get-it to ensure proxy support
> [chore] Upgrade get-it to 4.1.0

- packages/@sanity/server/package.json
Upgraded to latest version in `@sanity/server`
> [server] Upgrade @sanity/css-loader

- packages/@sanity/components/src/buttons/story.js
- packages/@sanity/components/src/buttons/styles/DefaultButton.css
- packages/@sanity/components/src/dialogs/DefaultDialog.js
- packages/@sanity/components/src/dialogs/styles/DefaultDialog.css
- packages/@sanity/form-builder/src/inputs/ImageInput/Asset.js
- packages/@sanity/form-builder/src/inputs/ImageInput/SelectAsset.js
- packages/@sanity/form-builder/src/inputs/ImageInput/styles/Asset.css
- packages/@sanity/form-builder/src/inputs/ImageInput/styles/SelectAsset.css
> [form-builder] Asset delete button

- packages/@sanity/cli/src/actions/init-project/initProject.js
When a user creates their first project, this PR will ask if they want to be invited to join the community.  I'm not attached to the prompt text, feel free to suggest changes (and decide whether or not this is a good idea ;) )
> [cli] Prompt to send community invitation on first project creation

- packages/@sanity/desk-tool/src/pane/DocumentsListPane.js
Add comment regarding slice and order, plus some minor formatting
> [desk-tool] Add comment regarding slice and order

- packages/@sanity/export/src/AssetHandler.js
This PR utilizes a new query parameter (`dlRaw`) on our image pipeline for downloading the raw, unprocessed versions of original assets. It requires authentication, since the assets could potentially include GPS or sensitive exif data. This is handled transparently by the export package, since it includes a token.
The `dlRaw` parameter will also give back the file's md5 sum in the etag header (the file pipeline already does this), which we use to compare it to the downloaded version and retry if they differ (up to a max of 3 times).
This should also be slightly faster since it doesn't require any processing on the server side.
Needs to be tested a bit before we roll it out.
> [export] Verify downloaded assets with checksum

- packages/@sanity/validation/src/validateDocument.js
Happened to corrupt my data while testing/experimenting, and seems like we need some more guards here for missing types.
> [validation] Check for type validating arrays and objects in document

- packages/@sanity/desk-tool/src/pane/Editor.js
- packages/@sanity/desk-tool/src/pane/styles/Editor.css
Moved the overlay out of the scroll container to maintain relative height.
> [desk-tool] Moving overlay out of scroll container

- packages/@sanity/form-builder/src/inputs/BlockEditor/EditNode.js
- packages/@sanity/form-builder/src/inputs/BlockEditor/Input.js
- packages/@sanity/form-builder/src/inputs/BlockEditor/SyncWrapper.js
- packages/@sanity/form-builder/src/inputs/BlockEditor/nodes/BlockObject.js
- packages/@sanity/form-builder/src/inputs/BlockEditor/nodes/InlineObject.js
- packages/@sanity/form-builder/src/inputs/BlockEditor/nodes/Span.js
- packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createPatchToOperations.js
Collection of different bug-fixes and enhancements for the portable text editor.
> [form-builder] Various PT-editor fixes

- packages/@sanity/cli/src/actions/login/login.js
Works around the (node:33102) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated. error in node >= 11 by using an iv.
> [cli] Generate and use initialization vector for token exchange

- packages/@sanity/base/src/util/uncaughtErrorHandler.js
(This is actually @kristofferj's work, I just put it into a commit)
> [base] Use pre-wrap to constrain width when displaying uncaught errors

- packages/@sanity/export/src/export.js
Currently, if the export fails because of archiving or asset download errors, the temporary files are not cleaned up. With this change, we make sure to always clean up after ourselves (well, in a best-effort matter).
> [export] Clean up temporary files on failure

- packages/@sanity/cli/src/actions/init-plugin/pluginTemplates.js
Made a new unopinionated template that I've tested (it works!).
> [cli] Add example plugin for dashboard widgets

- packages/@sanity/base/src/components/listenQuery.js
This fixes a bug that could occasionally – when mutations were received just as the document list query listener were set up – cause an error saying "Unexpected mutation as first listener event".
Also switches the listener we use in the document list so it uses `visibility: query`, which will make it receive events after they are ready to be queried.
> [base] Fix unexpected first event "mutation" error

- packages/@sanity/transaction-collator/src/transactionsToEvents.ts
This will fix two bugs with the transaction collator.
> [transaction-collator] Bug fixes

- gulpfile.js
Fixes the recent issue where typescript wouldn't rebuild on change
> [chore] Fix typescript watch task

- packages/@sanity/default-login/package.json
- packages/@sanity/default-login/src/CookieTest.js
- packages/@sanity/default-login/src/styles/CookieTest.css
- packages/@sanity/default-login/src/util/openWindow.js
This is the new test cookie view that works with Safari and the new Schengen API endpoints.
> Update cookie test view

- packages/@sanity/core/src/commands/documents/deleteDocumentsCommand.js
This PR adds the ability to delete multiple documents in the same transaction:
`sanity documents delete id1 id2 id3` etc.
> [core] Allow specifying multiple document IDs to delete

- packages/@sanity/form-builder/src/FormBuilderInput.js
If a custom input can't be given a ref, the studio currently fails. Since it's now a lot more common to create function components in React and function components can't be given refs, this situation is bound to happen a lot more often. This patch makes sure we don't throw an error when this happens, but instead display a warning pointing at the problem and the actual input:
Background/related #1464
> [form-builder] Gracefully handle missing input refs

- packages/@sanity/form-builder/src/inputs/BlockEditor/BlockEditor.js
- packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/Toolbar.js
> [form-builder] Block editor: avoid toolbar making drag and scroll up not function

- packages/@sanity/form-builder/src/inputs/BlockEditor/nodes/BlockObject.js
Fixes issues with drag/drop of blocks.
> [form-builder] Block editor: fix issues with drag/drop of blocks

- packages/@sanity/dashboard/src/widgets/sanityTutorials/Tutorial.js
Open dashboard video links in a new tab
> [dashboard] open dashboard video links in new tab

- packages/@sanity/core/src/actions/graphql/extractFromSanitySchema.js
I think this should fix this bug. If the type derived from a scalar was being used as a field, it was already correctly handled. However, if the type derived from a scalar was being used as a reference or in an array, then it would not be correctly dereferenced.
I've tested as well as I can, but you probably want to check this closely.
> Bug 1478: [graphql] fix deploy where type derived from string used as reference

- packages/test-studio/schemas/blocks.js
Just a test editor in the test-studio which shows custom markers.
> [test-studio] Make test with custom markers

- packages/@sanity/form-builder/src/inputs/Slug/SlugInput.tsx
- packages/@sanity/validation/src/validators/slugValidator.js
I've made a fix for #1484, but I'm unsure about the solution. 
Would love some input!
> [validation] fix slug always required after being set once

- packages/@sanity/base/src/datastores/document/getPairListener.js
Note: this requires #1507 to be merged first.
We previously used the query endpoint when checking out documents for edit. This patch changes that so we instead use the more suitable `/doc` endpoint (via `client.getDocuments()`)
> [base] Use doc endpoint when checking out document for edit

- packages/@sanity/form-builder/src/inputs/BlockEditor/BlockEditor.tsx
- packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/Toolbar.tsx
- packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/Toolbar.css
Fix block editor design regressions made by #1492
> [form-builder] Block editor: fix design regressions from #1492

- packages/@sanity/components/src/menus/styles/DefaultMenu.css
Items have large spacing and icons are misaligned in the pane dropdown menu (see screenshot comparison below).
This PR makes the menu more condensed and aligns icon with the text.
N/A
**Checklist**
> [components] fix icon alignment issues in menu items

- packages/@sanity/code-input/README.md
Add withFilename option to readme, from PR1234 https://github.com/sanity-io/sanity/pull/1234
**Checklist**
> fix typo, add withFilename option

- packages/@sanity/code-input/src/CodeInput.js
- packages/@sanity/code-input/src/config.js
- packages/@sanity/code-input/src/groq.js
- packages/test-studio/schemas/code.js
If a user adds a custom language, it is filtered out.
Changes this to fallback with text
- GROQ support in code-input. Also let you define custom language (without syntax highlighting)
> [code-input] Add support for GROQ

- packages/@sanity/components/src/panes/DefaultPane.js
- packages/@sanity/components/src/panes/styles/DefaultPane.css
- packages/@sanity/desk-tool/src/pane/DocumentsListPane.js
- packages/@sanity/structure/src/InitialValueTemplateItem.ts
Adds a dropdown menu to the "+" (new) button in a pane if initial value templates exist and styled according to the sketches.
- Added dropdown menu in panes that lets you create new documents from existing templates
**Checklist**
> [components] Add dropdown menu for initial value templates

- packages/@sanity/structure/src/InitialValueTemplateItem.ts
This fixes a typescript compilation error. Feel free to squash it together with a more relevant commit
> [structure] Guard against possible undefined value

- gulpfile.js
I feel like everything in this gulpfile is a bit of a hack, so I'm 100% sure there are better ways of fixing this. Regardless: This should fix the case where all JS/TS files are recompiled instead of only the ones that are changed.
> [chore] Gulp: Only recompile changed files

- packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/PastePlugin.ts
This is an additional patch to the recent https://github.com/sanity-io/sanity/commit/b6e99b8d837705d635b9cf734561e88e20cf059a
It should also remove placeholder status when pasting an editor fragment (like with pasting html)
> [form-builder] Block editor: ensure placeholder status is removed when pasting fragment

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Some of the markdown files in the project's root have a few tiny typos, and some of them aren't linted.
Fixed typos and linted using the rules of [markdownlint](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md). A few errors are still there, namely Emphasis used instead of a heading (MD036) in issue and PR templates, but I didn't want to touch these as it might look quite a bit different afterwards.
**Checklist**
> Fix typos in md files

- packages/@sanity/form-builder/src/inputs/BlockEditor/nodes/styles/ListItem.css
* Made the bullet points smaller
* Adjusted the tab offset scale
* Applied `prettier`+`stylelint` formatting (automated by my editor)
Closes sanity-io/sanity-priv#1601
> [form-builder] Adjust styling of lists in block editor

- packages/@sanity/default-layout/src/components/CurrentVersionsDialog.js
- packages/@sanity/default-layout/src/components/UpdateNotifierDialog.js
- packages/@sanity/default-layout/src/components/styles/UpdateNotifierDialog.css
The current update dialog styling is kind of botched. 
This adds styling and copy to make the update dialog more polished, and make the dialog showing when everything is up to date similar to the one when upgrades are available.
- N/A
**Checklist**
> [default-layout] Fix studio status updates dialog

- gulpfile.js
Our gulp script is currently logging a lot of build info. This sometimes cause compile errors and other useful information about server address/port etc, to be lost in all the noise. This hides it by default but it can be enabled by setting the VERBOSE env variable, e.g. `VERBOSE=1 npm start`
N/A
**Checklist**
> [chore] Hide verbose gulp output behind env flag

- packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/html.ts
- packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild/output.json
- packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild4/index.ts
- packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild4/input.html
- packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild4/output.json
When using `htmlToBlocks` in script context (i.e. with JSDOM), text nodes which are a child of the body, was ignored.
This fix will make sure text is wrapped in container tags (spans), before they are processed further. 
In a browser context, the browser makes sure this is done before putting the HTML on the clipboard.
Fixed a bug in the HTML deserializer where text nodes directly on the body was not handled correctly.
**Checklist**
> [block-tools] Deserialize HTML text nodes directly on the body better

- gulpfile.js
- packages/@sanity/base/src/components/DevServerStatus.js
- packages/@sanity/base/src/components/SanityRoot.js
- packages/@sanity/block-tools/README.md
- packages/@sanity/block-tools/changelog.md
- packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/html.ts
- packages/@sanity/block-tools/src/converters/blocksToEditorValue.ts
- packages/@sanity/block-tools/src/converters/editorValueToBlocks.ts
- packages/@sanity/block-tools/src/util/normalizeBlock.ts
- packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild/output.json
- packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild4/index.ts
- packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild4/input.html
- packages/@sanity/block-tools/test/tests/HtmlDeserializer/fromTheWild4/output.json
- packages/@sanity/block-tools/test/tests/util/normalizeBlock.test.ts
- packages/@sanity/cli/src/actions/init-project/initProject.js
- packages/@sanity/cli/src/commands/init/initCommand.js
- packages/@sanity/cli/src/util/generateCommandsDocumentation.js
- packages/@sanity/form-builder/src/inputs/BlockEditor/BlockExtrasOverlay.tsx
- packages/@sanity/form-builder/src/inputs/BlockEditor/Editor.tsx
- packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createBlockActionPatchFn.ts
- packages/@sanity/form-builder/src/inputs/BlockEditor/utils/createEmptyBlock.ts
Currently the CLI always prompts for setting a dataset name and choosing a dataset visibility mode
This adds a simple setup mode that skips dataset name and visibility mode prompt and instead use the default values of `production` and `public`. This mode can also be used with a `--simple` flag.
With `--simple` flag:
- Added a simple configuration mode to `sanity init` that doesn't prompt for dataset name and visibility mode, but instead uses default name and mode (production/public).
**Checklist** 
**Notes/Comments**
I wonder if I did this right 😅
> [cli] Add a default dataset config

- packages/@sanity/desk-tool/src/components/StructureError.js
The error body content is so extremely spot on, so the "Hmm" kind of ruins its clarity. This PR will make it read just "Encountered an error while reading structure"
**Checklist**
> [desk-tool] Edit error header text

- packages/@sanity/components/src/buttons/DropDownButton.js
When you click on the dropdown button, then click again to close it, the menu is kept open.
This PR mirrors the logic from `DefaultMenu`, preventing the "click outside" logic from keeping the menu open. Also removed the `handleClickOutside` function since it wasn't being called.
Fixed DropDownButton not being closable when using button
**Checklist**
> [components] Fix DropDownButton not being closable with button

- README.md
N/A
As seen in the image below, one of the bullets in the "Stay up to date" section of the README file wasn't displaying correctly.
It looks like the list was using the wrong type of dash. A quick swap solved the problem. 
N/A
**Checklist**
> Update README to fix bullet in "Stay up to date" section

- packages/@sanity/components/sanity.json
Remove a part for the snackbar that doesn't exist or isn't used.
**Checklist**
> [components] remove unused snackbar part

- README.md
Do not delete the instructional comments. -->
The readme was a bit stale and outdated.
I have lifted the getting started instructions to the top. Summarized key features with helpful links. Updated illustrations. Removed a lot of the links that can be found on our site anyways.
Updated the readme for the main repository.
**Checklist**
> [readme] Update with new messaging and illustrations

- packages/@sanity/client/README.md
The example of listening to a query with @sanity/client is wrong, it omits that the returned object is a mutation object with a result property.
Fixed the example
Fix wrong code example in @sanity/client README.md
**Checklist**
> [client] Fix code example in README.md

- packages/storybook/schema.js
Same, but with a pointless extra line.
Remove redundant key/val declaration. It may be useful to introduce linting that highlights things of this nature.
Remove redundant key/val declaration
**Checklist**
> [storybook] remove duplicate key/val

- packages/@sanity/client/README.md
> [client] Update readme with an example of how to delete an element from an array

- packages/groq/groq.d.ts
- packages/groq/package.json
> [groq] Add typescript definition for tagged template literal

- packages/@sanity/studio-hints/src/components/HintCard.js
- packages/@sanity/studio-hints/src/components/HintsPackage.js
- packages/@sanity/studio-hints/src/components/LinksList.js
- packages/@sanity/studio-hints/src/components/utils.js
This adds UTM query params to links in the hints tray.
> Add utm to links

- packages/@sanity/cli/src/commands/debug/debugCommand.js
The current help text for the `debug` command is a tad confusing.
Improves the `debug` command help text.
N/A
**Checklist**
> [cli] improve debug command help text

- packages/@sanity/core/src/actions/graphql/filters/booleanFilters.js
- packages/@sanity/core/src/actions/graphql/filters/dateFilters.js
- packages/@sanity/core/src/actions/graphql/filters/dateTimeFilters.js
- packages/@sanity/core/src/actions/graphql/filters/floatFilters.js
- packages/@sanity/core/src/actions/graphql/filters/idFilters.js
- packages/@sanity/core/src/actions/graphql/filters/integerFilters.js
- packages/@sanity/core/src/actions/graphql/filters/stringFilters.js
- packages/@sanity/core/src/actions/graphql/filters/urlFilters.js
- packages/@sanity/core/src/actions/graphql/generateTypeFilters.js
This PR adds support for the new filtering system in GraphQL. I have opened this as a draft PR to get some feedback on the work.
N/A, will be done in a separate PR from the `gql` branch to the `next` branch.
**Checklist**
> Gql implement existing filters v2

- packages/@sanity/form-builder/src/inputs/BlockEditor/nodes/CustomMarkers.tsx
A prop type is invalid. For some reason this gave a build error in another branch. This will fix that.
**Checklist**
> [form-builder] Fix type error

- packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/gdocs.ts
In some circumstances (like when pasting incomplete selections from Notion) the `doc.body.firstElementChild` is null. We must test for this before trying to use it.
Doesn't need to be mentioned I think.
**Checklist**
> [block-tools] Test for doc.body.firstElementChild before using it

- now.json
- package.json
This adds CI deployment of our test-studio using ZEIT Now
> [chore] Add ZEIT Now deployment for test-studio

- packages/@sanity/cli/src/util/clientWrapper.js
If you run a command and get a 401 error, the CLI deletes your tokens and you are logged out of your sanity user.
Instead of logging you out, this will show a more helpful error message and include a link to a help article.
- n/a
**Checklist**
> [cli] prevent cli logout on auth errors

- packages/@sanity/form-builder/src/inputs/BlockEditor/plugins/UndoRedoPlugin.ts
The placeholder prop can sometimes be left behind when doing undo operations.  This ensures that it is removed.
**Checklist**
> [form-builder] Undo plugin must ensure that placeholder prop is removed

- packages/@sanity/client/sanityClient.d.ts
#1750 - There are type errors produced with the current version of `@sanity/client`.
This PR solves some of them, but not the issue of the missing type for `SanityImagePalette`.
**Checklist**
> [client] fix type errors

- packages/@sanity/form-builder/src/inputs/BlockEditor/BlockEditor.tsx
- packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/BlockStyleSelect.tsx
Something has changed (suspect React upgrade), that made the refs not resolve correctly sometimes. This resulted in weird behaviour drawing the toolbar for the PTE.  I suspect it has to do with nested render functions. A `forceUpdate`  on `componentDidMount` fixes this, though it should probably be refactored so that the refs work like they are supposed to and awlays available on `componentDidMount`. But this is a larger task. Why it is working sometimes, I suspect has to do with new props coming in (like focus), and thus it triggers a re-render so that the refs are resolved.
This PR also includes a minor displaybug for the style selector where it was drawn when it …
> Fix toolbar display bugs

- gulpfile.js
Looks like the TypeScript compilation is sensitive for the order packages are compiled in. A previous commit apparently made compiling `@sanity/mutator` finish after `@sanity/base`, causing compile errors in `@sanity/base`. This patch quickfixes the issue by allowing us to explicitly specify packages that should be compiled serially.
(n/a)
> [chore] Quickfix TS compile order issue

- packages/@sanity/cli/templates/blog/schemas/blockContent.js
- packages/@sanity/cli/templates/ecommerce/schemas/blockContent.js
- packages/@sanity/cli/templates/moviedb/schemas/blockContent.js
In the blockContent.js files of eCommerce, blog and moviedb schema templates (CLI package), there was a spelling mistake in the comments.
Fixed the spelling mistake in 3 files.
**Checklist**
> [cli] Fixed typos in blockContent comments

- packages/@sanity/desk-tool/src/panes/documentPane/Editor/EditForm.tsx
- packages/@sanity/desk-tool/src/panes/documentPane/Editor/HistoryForm.js
https://github.com/sanity-io/sanity/issues/16
Remove `id` attribute from the editor form, as this will cause issues when there are more than 1 form in the desk tool.
_n/a_
**Checklist**
> [desk-tool] Remove 'id' attribute from the editor form

- packages/@sanity/default-layout/src/components/CurrentVersionsDialog.js
Improvement to the copy in the package status dialog
**Checklist**
> [components] improve package status dialog copy

- packages/@sanity/desk-tool/src/tool/DeskTool.js
> [desk-tool] Prevent 'Cmd+S' from triggering HTML document save dialog

- packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/Toolbar.tsx
- packages/@sanity/form-builder/src/inputs/BlockEditor/Toolbar/styles/Toolbar.css
Thread: https://sanity-io.slack.com/archives/CAJ4KP63G/p1589374190005900
- Add wrapper with `position: relative` around the Toolbar
- Add an inner wrapper (the preview root wrapper), with `position: absolute`
Since the resize logic is wrapped in an absolute element, it will not affect the surrounding layout (CSS grid) anymore.
- Fixes an issue with PTE toolbar sizing on narrow screens.
**Checklist**
> [form-builder] Make PTE toolbar more resilient to being placed within a CSS grid

- packages/@sanity/cli/scripts/pack.js
- packages/@sanity/default-login/src/CookieTest.js
- packages/eslint-config-sanity/react.js
Fixes a few references to words we no longer want to use
> [chore] Fix inconsiderately named references

- packages/@sanity/client/README.md
`nanoid` have moved to use named exports. So our example code doesn't work with the new version.
**Checklist**
> [chore] Replace with named import

- README.md
"thruth" -> "truth"
"thruth" -> "truth"
**Checklist**
> Update README.md because of a typo

- packages/@sanity/base/src/components/AppLoadingScreen.js
- packages/@sanity/base/src/styles/variables/forms.css
- packages/@sanity/base/src/styles/variables/globals.css
- packages/@sanity/base/src/styles/variables/typography.css
- packages/@sanity/components/src/buttons/styles/DefaultButton.css
- packages/test-studio/src/themes/dark.css
https://sanity-io.slack.com/archives/C9QMY5AP5/p1598958857014300
- Fixed by changing the `--text-muted` to a color that is WCAG 2.0 level AA compatible.
- Fixed by increasing the contrast of "inverted" and "simple" buttons (using CSS `color()` function)
- Thanks to Andreas in the community for reporting this!
**Checklist**
> [base] Fix text contrast

- packages/@sanity/base/src/styles/forms/clear-button.css
- packages/@sanity/base/src/styles/forms/text-input.css
- packages/@sanity/base/src/styles/variables/forms.css
- packages/@sanity/components/src/buttons/styles/DefaultButton.css
- packages/@sanity/components/src/fieldsets/styles/DefaultFieldset.css
- packages/@sanity/components/src/fileinput/DefaultFileInput.css
- packages/@sanity/components/src/formfields/styles/DefaultFormField.css
- packages/@sanity/components/src/selects/styles/DefaultSelect.css
- packages/@sanity/components/src/selects/styles/RadioSelect.css
- packages/@sanity/components/src/selects/styles/SearchableSelect.css
- packages/@sanity/components/src/selects/styles/StyleSelect.css
- packages/@sanity/components/src/tags/styles/TextField.css
- packages/@sanity/components/src/toggles/Checkbox.css
- packages/@sanity/components/src/toggles/Checkbox.tsx
- packages/@sanity/components/src/toggles/Switch.css
- packages/@sanity/components/src/toggles/Switch.tsx
- packages/@sanity/components/src/toggles/shared.css
- packages/@sanity/form-builder/src/inputs/ArrayInput/styles/ItemValue.css
- packages/@sanity/form-builder/src/inputs/DateInputs/styles/BaseDateTimeInput.css
- packages/@sanity/form-builder/src/inputs/ImageInput/ImageInput.css
- packages/@sanity/form-builder/src/inputs/OptionsArrayInput/OptionsArrayInput.tsx
- packages/@sanity/form-builder/src/inputs/OptionsArrayInput/styles/OptionsArrayInput.css
- packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx
- packages/@sanity/form-builder/src/inputs/ReferenceInput/styles/ReferenceInput.css
Various minor inconsistencies in the UI of the studio forms
• improved design of boolean inputs
• improved spacing between form elements
• fixed label of switch components
• unified focus states for form elements: inputs, buttons etc.
**Checklist**
> [form-builder][components] Fix various UI forms issues

- packages/@sanity/base/package.json
- packages/@sanity/base/sanity.json
- packages/@sanity/base/src/components/icons/Robot.js
- packages/@sanity/base/src/components/icons/ThLarge.js
- packages/@sanity/base/src/components/icons/ThList.js
- packages/@sanity/cli/package.json
- packages/@sanity/cli/templates/moviedb/schemas/person.js
- packages/@sanity/code-input/package.json
- packages/@sanity/components/src/icons/stories/icons.js
- packages/@sanity/components/src/tabs/stories/withIcons.js
- packages/@sanity/dashboard/package.json
- packages/@sanity/dashboard/src/widgets/projectUsers/ProjectUsers.js
- packages/@sanity/studio-hints/package.json
> [chore] Remove usage of react-icons

- packages/@sanity/desk-tool/src/panes/documentPane/DocumentOperationResults.tsx
Message says "A draft have been created" which doesn't make sense.
Message fixed.
- Fix typo in snackbar message when unpublishing a document.
**Checklist**
> [desk-tool] Fix message when unpublishing a document.

- packages/@sanity/base/src/change-indicators/helpers/findMostSpecificTarget.ts
For portable text fields that aren't full size you want the keyed
objects to resolve to the text field itself. Otherwise we won't display
connectors for non-fullsize portable text editors.
Can do this by making sure that the target and path only differ by
being:
* 1 path segment shorter
* The last path segment is a keyed object
Then only perform the length-check where this doesn't apply.
After the fix the connectors will render correctly.
n/a
**Checklist** 
- [n/a]  The PR title includes a link to the relevant issue
- [n/a]  Corresponding changes to the documentation have been made
> [base] Allow connector match to shorter paths

- packages/@sanity/components/src/dialogs/PopoverDialog.css
- packages/@sanity/components/src/dialogs/PopoverDialog.tsx
- packages/@sanity/components/src/popover/popover.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/Editor.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/Input.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/Objects/renderers/PopoverObjectEditing.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/boundaryElement/BoundaryElementContext.ts
- packages/@sanity/form-builder/src/inputs/PortableText/boundaryElement/BoundaryElementProvider.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/boundaryElement/hooks.ts
- packages/@sanity/form-builder/src/inputs/PortableText/boundaryElement/index.ts
> [form-builder] Fix popover dialog overflow

- packages/@sanity/form-builder/package.json
- packages/@sanity/form-builder/src/inputs/PortableText/Editor.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/InvalidValue.tsx
Fixed an issue where default hotkeys for the PTE decorators would be active even though the schema doesn't support them. Check if actually supported for enabling them.
Changed the copy of the PTE validation and mitigation tool.
Fixed an issue where default hotkeys for adding formatting in the editor of portable text was enabled even though the schema would not support that formatting.
**Checklist**
> [form-builder] PTE: fix hotkeys issue, improve validation error message

- packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayFunctions.css
- packages/@sanity/form-builder/src/inputs/ArrayInput/ArrayFunctions.tsx
- packages/test-studio/schemas/arrays.js
The array dropdown menu is missing code that renders type icons. It was supposed to be added in https://github.com/sanity-io/sanity/pull/1958
This fixes icons not rendered in array insert dropdown menu 
- Fixed an issue with icons not rendering in array insert dropdown menu
**Checklist**
> [form-builder] fix icons not rendred in array insert dropdown menu

- packages/@sanity/components/src/fieldsets/DefaultFieldset.tsx
Clicking a collapsed fields inside a modal will close it.
Fixed a bug where expanding a collapsed field inside a modal would close it.
**Checklist**
> [components] Fix bug where clicking a collapsed field inside a modal will close it

- packages/@sanity/form-builder/package.json
The editor will split text blocks in unfavourable ways in regard to PT marks/annotations if you split in the start or the end of a text block. Then the PT validator will not accept it, displaying an error (which is good). This is now fixed upstream in the PTE.
Upgrade to latest portable-text-editor which is normalizing marks better.
Fix issues in the portable text editor related to marks when splitting lines at start/end offsets.
**Checklist**
> [form-builder] PTE: upgrade module

- packages/@sanity/form-builder/package.json
An error will occur in two special circumstances using the portable text editor.
Upgrade to latest portable-text-editor which is normalizing marks better.
Fix an issue in the portable text editor related to marks and splitting of blocks.
**Checklist**
>  [form-builder] PTE: upgrade module

- packages/@sanity/color-input/src/ColorPickerFields.js
There is currently an error where you cannot change the hex value with @sanity/color-input.
The following error occurs
```An error occured: Cannot read property 'isValidHex' of undefined```
Please see:
#2124 
[also noted in slack](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1605239060066200)
color should be imported as ```import * as color from 'react-color/lib/helpers/color'```
[fix] Import correct color module to fix isValidHex error in color-picker plugin
**Checklist**
> [color-input] Fix `isValidHex` error (#2124)

- packages/@sanity/core/src/commands/dataset/copyDatasetCommand.js
The `sanity dataset copy` command will not wait for copy completion by default. In addition the CLI doesn't give you an obvious way of checking in with the copy progress after initating the copy unless you add the `--wait` flag.
This changes the `sanity dataset copy` command to `--wait` by default.
It also adds a new flag `--background` which runs the copy in the background. If you do that the CLI will give you a job ID and a command you can run to check in with the progress.
This changes the behaviour of the `sanity dataset copy` command.
**Checklist**
> [core] Dataset copy wait by default

- packages/@sanity/base/package.json
- packages/@sanity/base/src/components/GlobalStyle.tsx
- packages/@sanity/base/src/components/SanityRoot.tsx
- packages/@sanity/base/src/index.ts
- packages/@sanity/base/src/theme/index.ts
> [base] Update @sanity/ui

- packages/@sanity/cli/src/actions/init-project/initProject.js
[Issue with CLI creating private datasets](https://github.com/sanity-io/sanity/issues/1952)
**Checklist**
> [cli] Fix init command not respecting dataset visibility flag

- packages/@sanity/form-builder/src/inputs/Slug/SlugInput.tsx
> [form-builder] Trigger `onFocus` in SlugInput

- packages/@sanity/cli/src/util/clientWrapper.js
- packages/@sanity/client/src/validators.js
- packages/@sanity/client/test/client.test.js
- packages/@sanity/core/src/actions/start/startAction.js
Restores some commits that were lost in a PR snafu 😓
> [client] Add support for dataset aliases

- packages/@sanity/base/package.json
- packages/@sanity/base/src/__legacy/@sanity/components/avatar/stories/stack.tsx
- packages/@sanity/base/src/components/formField/FormFieldValidationStatus.tsx
- packages/@sanity/base/src/user-color/manager.ts
This change updates the dependency on `@sanity/color`.
> [base] Update @sanity/color

- examples/test-studio/schemas/fieldsets.js
- packages/@sanity/base/src/__legacy/@sanity/components/tooltip/tooltip.tsx
- Fixed an issue with `Tooltip` not opening.
> [base] Fix regression in Tooltip

- packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx
#2299
Add support for this requested feature
**Checklist**
> [@sanity/form-builder] Add support for async filtering (#2299)

- packages/@sanity/types/src/reference/types.ts
Looks like I forgot to add this in #2301
> Add type def for async filtering

- packages/@sanity/form-builder/src/inputs/DateInputs/base/calendar/Calendar.tsx
This fixes an issue with the date picker that would sometimes make it lose focus when navigating from the last day of a month to the first day of the next. This would only happen when moving from the last day of a month where the calendar grid displayed 6 weeks to the first day of a month that would display as 5 weeks (e.g. going from may 2021 to june 2021).
Fix an issue that would in some cases make the date picker lose focus when using arrow keys to move between months.
> fix: preserve focus on calendar buttons between renders

- packages/@sanity/mutator/src/document/SquashingBuffer.ts
- packages/@sanity/mutator/test/SquashingBuffer.test.ts
Detect when there are multiple createIfNotExists in the same transaction and then only keep the first one. This works nicely
with the way @sanity/base uses createIfNotExists to ensure that a draft version of a document exists.
- Reduce the size of mutations when editing text fields.
> perf(mutator): remove duplicated createIfNotExists

- cypress/support/commands.js
- packages/@sanity/base/src/datastores/grants/createGrantsStore.ts
- packages/@sanity/base/src/datastores/grants/debug/exampleGrants.ts
- packages/@sanity/base/src/datastores/grants/debug/index.ts
- packages/@sanity/base/src/datastores/grants/debug/roleGrants.ts
- packages/@sanity/base/src/datastores/grants/types.ts
This PR updates the roles aware branch to the new `acl` endpoint specified [here](https://www.notion.so/sanityio/Document-Grants-fa79007060ab4f3da307530f472e6ee5).
Ensure all the types and names are correct. ~Note: I did not test this yet (thus the draft).~ Still works 😎 
N/A
> refactor(base): update to new acl endpoint

- packages/@sanity/base/src/components/InsufficientPermissionsMessage.tsx
This adds a safeguard against missing roles property on the user object.
N/A
> fix(base): guard against missing user roles in InsufficientPermissionsMessage

- packages/@sanity/base/src/__legacy/@sanity/components/panes/DefaultPane.tsx
This reverts commit 8680eea9b03867b55386f75dd9be23b08c786f38, which added a (too) simplistic permission checking to the DefaultPane's create menu. In some cases we ended up disabling it when the current user actually had access to create the document. Reverting this will always make the create button enabled an clickable, but if you try to create a document that you don't have access to, you'll see the "lack of permission"-message above the form instead.
- Fixes a bug which caused the create menu to be disabled in cases where the current user actually had access to create the type of document
> Revert "feat(base): add basic permission check to default pane menu"

- packages/@sanity/form-builder/README.md
Change to language in a package readme.
Not related to a feature/bug.
None
> adjust tone of voice

- packages/@sanity/data-aspects/src/DataAspectsResolver.js
Removes unwanted todo comment from in code
Removal of comment
None
> remove unwanted TODO comment

- packages/@sanity/cli/src/actions/login/login.js
Add support for logging in to Sanity with an SSO/SAML provider.
- `sanity login --experimental`
- Exposes an `SSO` option in the list of providers and prompt the user to specify the organization slug. If multiple providers are found, a choice list is displayed.
- `sanity login --sso=slug`
- Logs in to the sso provider configured on the organization defined by the slug. If multiple providers are specified, a choice is displayed to the user.
- API
- Code style
This ought to be a silent release as the SSO functionality is still being actively developed.
> feat(cli): add experimental support for sso/saml login

- packages/@sanity/code-input/README.md
As it stands, the documentation offers no example of how `languageAlternatives` is structured, which leads many to wrongfully input an array of plain strings. This includes me from the present and the past - I've faced this 3 times already 😆 
This is a simple addition to the README.md file for the `@sanity/code-input` package to help newcomers understand how they should format their `languageAlternatives` option.
I've also linked to the underlying library's site for a reference on themes, as the 4 listed in the current documentation aren't doesn't comprehend all possibilities. Let me know if this makes sense :)
**Checklist**
> [code-input] Make @sanity/code-input's documentation clearer

- packages/@sanity/core/src/actions/graphql/deployApiAction.js
When adding fields to your schema, a side effect is that the input types for field filters and sortings will also get new fields (for instance, adding a `name` field on a `BlogPost` type will yield the follow "dangerous changes":
```
An optional field `name` on input type BlogPostFilter was added.
An optional field `name` on input type BlogPostSorting was added.
```
It's hard to reason about why this should be considered a dangerous change, and it adds quite a bit of noise when trying to automate deployments of schemas. 
This PR explicitly ignores this specific warning. 
- That the code makes sense
- That the _change_ makes sense
- Added schema fields will no longer be treated as a dangerous change when deploying GraphQL schemas
> feat(core): GraphQL: treat added optional input fields as non-dangerous

- packages/@sanity/default-login/src/ErrorDialog.js
- packages/@sanity/default-login/src/LoginDialog.js
- packages/@sanity/default-login/src/UnauthorizedUser.js
This PR removes the temporary solution to hide the close button in dialogs.
> fix(default-login): remove temporary solution to hide close button in dialogs

- examples/test-studio/schemas/validation.js
- gulpfile.js
- packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx
- packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx
- packages/@sanity/form-builder/src/utils/getValidationRule.ts
- packages/@sanity/types/src/schema/types.ts
- packages/@sanity/types/src/validation/types.ts
- packages/@sanity/validation/src/Rule.ts
- packages/@sanity/validation/src/validateDocument.test.ts
- packages/@sanity/validation/src/validateDocument.ts
- packages/@sanity/validation/src/validators/blockValidator.ts
I did a squash merge instead of a rebase merge so i'm just re-writing history nbd
> fix: run nested validation

- packages/@sanity/base/src/__legacy/@sanity/components/validation/ValidationList.tsx
I made a bit of a mistake in the traversal for the breadcrumbs and end it one short 😅. This PR fixes that:
Before:
After:
Check to see the output of the validation breadcrumbs look good!
N/A (breadcrumbs has been released yet)
> fix(base): validation breadcrumbs

- .eslintrc.js
- gulpfile.js
- jest.config.base.js
- packages/@sanity/form-builder/src/utils/getValidationRule.ts
- packages/@sanity/types/src/schema/types.ts
- packages/@sanity/types/src/validation/types.ts
- packages/@sanity/validation/src/inferFromSchema.ts
- packages/@sanity/validation/src/inferFromSchemaType.ts
- packages/@sanity/validation/src/util/normalizeValidationRules.test.ts
- packages/@sanity/validation/src/util/normalizeValidationRules.ts
- packages/@sanity/validation/src/validateDocument.test.ts
- packages/@sanity/validation/src/validateDocument.ts
- packages/@sanity/validation/src/validators/blockValidator.ts
I accidentally squashed instead of rebased 🤦‍♀️
> fix: validate item context paths

- packages/@sanity/default-layout/src/useDefaultLayoutRouter.ts
- packages/@sanity/state-router/src/useRouterState.ts
Prevents re-renders on default layout due to route changes
> perf(default-layout): prevent re-renders on route change

- packages/@sanity/base/src/__legacy/@sanity/components/buttons/ButtonGrid.tsx
Refactoring `ButtonGrid` from a class based component to functional one. It should be a one for one refactor. It was actioned as a first commit and ticks off a todo list item in the sanity code base.
Ensure feature parity is kept.
> refactor: ButtonGrid to functional component

- packages/@sanity/form-builder/src/inputs/PortableText/object/BlockObject.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/text/TextBlock.tsx
> fix(form-builder): update PTE tooltips

- packages/@sanity/field/src/diff/components/FieldChange.tsx
- packages/@sanity/field/src/diff/components/GroupChange.tsx
> fix(field): add missing dependency in `FieldChange` and `GroupChange`

- .eslintrc.js
- dev/test-studio/schema/standard/references.js
- packages/@sanity/base/src/components/InsufficientPermissionsMessage.tsx
- packages/@sanity/base/src/datastores/grants/debug/exampleGrants.ts
- packages/@sanity/desk-tool/src/contexts/paneRouter/PaneRouterProvider.tsx
- packages/@sanity/desk-tool/src/contexts/paneRouter/ReferenceChildLink.tsx
- packages/@sanity/desk-tool/src/contexts/paneRouter/types.ts
- packages/@sanity/desk-tool/src/panes/document/DocumentPane.tsx
- packages/@sanity/form-builder/src/inputs/ReferenceInput/ArrayItemReferenceInput.tsx
- packages/@sanity/form-builder/src/inputs/ReferenceInput/CreateButton.tsx
- packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferenceInput.tsx
- packages/@sanity/form-builder/src/inputs/ReferenceInput/__tests__/ReferenceInput.test.tsx
- packages/@sanity/form-builder/src/inputs/ReferenceInput/types.ts
- packages/@sanity/form-builder/src/sanity/contexts/ReferenceInputOptions.tsx
- packages/@sanity/form-builder/src/sanity/inputs/reference/SanityArrayItemReferenceInput.tsx
- packages/@sanity/form-builder/src/sanity/inputs/reference/SanityReferenceInput.tsx
- packages/@sanity/types/src/reference/types.ts
Adds permission considerations to the recent reference input updates. Also adds a new flag to disable in-place creation
> reference updates with permissions

- packages/@sanity/base/src/components/formField/FormFieldValidationStatus.tsx
- packages/@sanity/base/src/components/previews/mediaPreview.styled.tsx
- packages/@sanity/base/src/components/previews/mediaPreview.tsx
- packages/@sanity/base/src/components/previews/types.ts
- packages/@sanity/form-builder/src/Preview.tsx
- packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ArrayInput.tsx
- packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/ConfirmDeleteButton.tsx
- packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/ArrayItem.tsx
- packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/CellItem.tsx
- packages/@sanity/form-builder/src/inputs/arrays/ArrayOfObjectsInput/item/ItemWithMissingType.tsx
- packages/@sanity/form-builder/src/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx
- packages/@sanity/form-builder/src/inputs/arrays/ArrayOfPrimitivesInput/ItemRow.tsx
- packages/@sanity/form-builder/src/inputs/arrays/common/DragHandle.tsx
- packages/@sanity/form-builder/src/inputs/arrays/common/list.tsx
> feat(form-builder): array design updates

- packages/@sanity/base/src/_exports/_internal.ts
- packages/@sanity/base/src/components/previews/types.ts
- packages/@sanity/base/src/preview/availability.ts
- packages/@sanity/base/src/preview/components/ObserveForPreview.tsx
- packages/@sanity/base/src/preview/components/PreviewSubscriber.tsx
- packages/@sanity/base/src/preview/components/SanityPreview.tsx
- packages/@sanity/base/src/preview/createPreviewObserver.ts
- packages/@sanity/base/src/preview/types.ts
- packages/@sanity/base/src/preview/utils/prepareForPreview.ts
Fix type import/exports to work with vite.js
> Fix types import/exports

- packages/@sanity/form-builder/src/inputs/ReferenceInput/AutocompleteContainer.tsx
Make the reference input responsive based on available/container size rather than screen size
- Test studio with references in different context/dialog widths etc.
> refactor(form-builder): make reference input responsive based on available width

- packages/@sanity/cli/src/commands/logout/logoutCommand.js
When attempting to log out of the CLI, one might encounter situations where the session is either timed out, has been cleared or does not exist. In these cases it is perfectly acceptable to just clear the token from the CLIs point of view, instead of throwing an error which is not actionable.
Also removes a bunch of ancient provisional session handling that is no longer used.
- Fixes a bug preventing `sanity logout` from working in the case of expired sessions
> fix(cli): clear auth token on 401 on logout

- packages/@sanity/desk-tool/src/components/pane/PaneHeader.tsx
- packages/@sanity/desk-tool/src/panes/document/documentPanel/header/ValidationMenu.tsx
- Update the validation list button so that its icon reflects the highest level of validation in the list (error > warning > info).
- Fix minor UI issue in `PaneHeader` related to tabs overflow indicators (see screenshot of issue). 
Make sure that the correct icon is displayed depending on the validation of a document
> feat: validation updates

- dev/test-studio/schema/debug/fieldGroupsDefault.js
- packages/@sanity/form-builder/src/EditPortal.tsx
- packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.styled.tsx
- packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.tsx
This fixes a few reported bugs in the upcoming Field Groups feature:
- Columns in objects was broken
- When field groups is used inside arrays, the All fields tab is always focused when opening the edit modal
n/a
> field group fixes

- packages/@sanity/cli/src/actions/init-project/initProject.js
(See individual commit messages)
> fix(cli): do not require a user to fetch coupon info

- package.json
- packages/@sanity/portable-text-editor/package.json
This dev. package was both outdated and had different versions between packages.
> Upgrade @types/node

- scripts/normalizeDependencyVersions.js
This change adds rendering of path to `package.json` when running `npm run versions`:
- That this change makes sense in different scenarios.
> chore: render path to `package.json` when running `npm run versions`

- packages/@sanity/base/package.json
- packages/@sanity/base/src/components/__workshop__/CollapseMenuStory.tsx
- packages/@sanity/base/src/components/__workshop__/RovingFocusStory.tsx
- packages/@sanity/base/src/components/__workshop__/index.ts
- packages/@sanity/base/src/components/collapseMenu/CollapseMenu.tsx
- packages/@sanity/base/src/components/collapseMenu/CollapseMenuButton.tsx
- packages/@sanity/base/src/components/collapseMenu/CollapseMenuDivider.tsx
- packages/@sanity/base/src/components/collapseMenu/CollapseOverflowMenu.tsx
- packages/@sanity/base/src/components/collapseMenu/ObserveElement.tsx
- packages/@sanity/base/src/components/collapseMenu/index.ts
- packages/@sanity/base/src/components/index.ts
- packages/@sanity/base/src/components/rovingFocus/__tests__/useRovingFocus.test.tsx
- packages/@sanity/base/src/components/rovingFocus/index.ts
- packages/@sanity/base/src/components/rovingFocus/types.ts
- packages/@sanity/base/src/components/rovingFocus/useRovingFocus.ts
- packages/@sanity/default-layout/src/navbar/toolMenuCollapse/ToolMenuCollapse.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/toolbar/ActionMenu.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/toolbar/InsertMenu.tsx
- packages/@sanity/form-builder/src/inputs/PortableText/toolbar/Toolbar.tsx
This pull request adds:
- Improvements to the `CollapseMenu` component.
- General code improvement
- Implement custom intersection observer logic and hence get rid of the `react-intersection-observer` dependency
- Preserve focus on the current focused button when the layout changes from expanded to collapsed state
- Slightly modified and improved API
- A hook (`useRovingFocus`) that enables adding arrow keyboard navigation. An example of when this hook is useful is in 
the PTE toolbar, where there are several elements combined together, which should have a unified arrow keyboard navigation logic. Usage example:
```ts
const [rootElement, setRootElement] = useState<HTMLDivElement | null>(null)
useRovingFocus({
rootElement: rootElement,
direction: 'horizontal'
})
<ToolbarRoot …
```
> feat: improve `CollapseMenu` and add keyboard arrow navigation in PTE toolbar and Navbar tools menu

- packages/@sanity/base/package.json
Contains a security upgrade of prismjs@1.27.0
Refs: https://github.com/PrismJS/prism/pull/3341
Refs: https://github.com/advisories/GHSA-3949-f494-cm99
Closes #3158
Build/tests pass
* Upgraded the base to use `refractor` version 3.6.0
> chore(deps): update to `refractor@^3.6.0`

- packages/@sanity/base/package.json
Updates `react-refractor` to `2.1.6` which includes the security update of `refractor@3.6.0`
Build/tests pass
* Upgraded the base to use `react-refractor` version 2.1.6
> chore(deps): update react-refractor@^2.1.6

- packages/@sanity/portable-text-editor/src/editor/PortableTextEditor.tsx
- packages/@sanity/portable-text-editor/src/editor/plugins/createWithPatches.ts
This will make the change events 'patch', 'throttle' and 'mutation' work more correctly together.
There could be rare situations where mutations would not be sent in how this was set up before.
That the changes makes sense and don't have any gotchas.
* Improves how changes are being batched sent to the server in the Portable Text editor, hopefully fixing a rare (and close to impossible to reproduce) bug where the latest change in the editor would not be sent to the sever.
> refactor(portable-text-editor): refactor mutation and patch handling

- packages/@sanity/default-layout/src/navbar/Navbar.tsx
Add data attributes to elements in `Navbar` to enable being targeted with CSS. 
Does the attribute names make sense?
Add data attributes to elements in Navbar
> refactor(default-layout): add data attributes to elements in `Navbar`

- README.md
* Fixes broken Slack badge
* Header refresh
* Updates Studio screenshot
* Removes old graphics
> Chore: Refresh README

- packages/@sanity/cli/templates/get-started/plugins/sanity-plugin-tutorial/CustomDefaultLayout.js
Only render the tutorial component if the user has permission to the project (i.e. has any role in the project)
n/a 
n/a
> fix(cli): update condition to render tutorial component

- packages/@sanity/default-layout/src/navbar/Navbar.tsx
This PR adds copy in the 'create new document' button tooltip when there's no schema defined. Currently, when there's no schema defined, the permission message is displayed in the tooltip.
- Start a studio without a defined schema and check that the correct tooltip copy is displayed. A good way to test is to start the `clean-studio` with `npm run clean-studio`.
- Review the code – does the use of `getNewDocumentOptions` make sense in this situation, or are there other more optimals ways to check if the schema is empty?
Add empty schema copy in the create document button tooltip
> feat(default-layout): add empty schema copy in the create document button tooltip

- package.json
- packages/@sanity/cli/templates/getting-started-pets/README.md
- packages/@sanity/cli/templates/getting-started-pets/schemas/article.js
- packages/@sanity/cli/templates/getting-started-pets/schemas/pet.js
- packages/@sanity/cli/templates/getting-started-pets/schemas/product.js
- packages/@sanity/cli/templates/getting-started-pets/schemas/siteSettings.js
Update schema descriptions for new template
Update schema descriptions for new template
> refactor(cli): update field descriptions

- packages/@sanity/form-builder/src/inputs/files/common/UploadProgress.tsx
Make sure that it doesn't try to read the name from a file when it is not available.
Fix potential error when trying to access a file that is not existent
> refactor(form-builder): add condition for name in upload progress

- packages/sanity/src/components/globalErrorHandler/GlobalErrorHandler.tsx
- packages/sanity/src/components/globalErrorHandler/_script.js
This PR adds code comments – no code changes.
> chore: add comments to global error listener source code

- packages/sanity/src/cli/commands/documents/createDocumentsCommand.ts
The `sanity documents create` command has a bug in v3 where it does not respect the `--missing` and `--replace` - instead it always defaults to using `create` as the mutation. This PR fixes this issue.
- Fixed a bug where the `sanity documents create` command would not respect the `--missing` and `--replace` flags
> fix(cli): use correct mutation based on `--missing`/`--replace` flags

- packages/sanity/src/form/members/MemberItem.tsx
The logic seems to be reversed here.
> fix(forms): Fix bug with openField/closeField

- packages/sanity/src/studio/router/routerEvent.ts
This PR fixes an issue where `navigateIntent` only worked once. 
Example of the issue:
1. Clicking on the first button navigated to author with `id-1` successfully
2. Clicking on the second button in order to navigate to author with `id-2` did not work
```jsx
const { navigateIntent } = usePaneRouter()
return (
<div>
<button onClick={() => navigateIntent('edit', {id: 'id-1', type: 'author'})}>
Go to id-1
</button>
<button onClick={() => navigateIntent('edit', {id: 'id-2', type: 'author'})}>
Go to id-2
</button>
</div>
)
```
Make sure that `navigateIntent` works as expected.
fix(desk): `navigateIntent` only worked once
> fix(desk): `navigateIntent` only worked once

- packages/sanity/src/form/inputs/PortableText/text/TextBlock.tsx
This PR fixes the placement of custom markers in the portable text edtior
Make sure that the placement of custom markers looks good
fix(form): placement of custom markers in portable text editor
> fix(form): placement of custom markers in portable text editor

- packages/@sanity/types/src/schema/types.ts
- packages/sanity/src/field/diff/resolve/resolveDiffComponent.ts
This PR updates the configuration of a diff component.
Before: 
```js
{
name: 'title',
title: 'Title',
diffComponent: DiffComponent
}
```
After:
```js
{
name: 'title',
title: 'Title',
components: {
diff: DiffComponent
}
}
```
Test to configure a diff component with the new API
feat: update diff component API
> feat: update diff component API

- packages/sanity/src/form/inputs/ReferenceInput/useReferenceInfo.ts
Fixes https://github.com/sanity-io/sanity/issues/3495
> Fix issue where reference input autocomplete was disabled

- packages/@sanity/default-layout/src/navbar/presence/PresenceMenu.tsx
> fix linting errors

- packages/@sanity/base/src/_exports/hooks.ts
- packages/@sanity/base/src/components/__workshop__/PreviewCardStory.tsx
- packages/@sanity/base/src/datastores/presence/hooks.ts
- packages/@sanity/base/src/datastores/presence/presence-store.ts
- packages/@sanity/base/src/datastores/presence/types.ts
- packages/@sanity/base/src/datastores/presence/useDocumentPresence.tsx
- packages/@sanity/base/src/datastores/presence/useGlobalPresence.tsx
- packages/@sanity/base/src/presence/DocumentPreviewPresence.tsx
- packages/@sanity/base/src/presence/index.ts
- packages/@sanity/default-layout/src/navbar/presence/PresenceMenu.tsx
- packages/@sanity/default-layout/src/navbar/presence/PresenceMenuItem.tsx
- packages/@sanity/default-layout/src/navbar/search/components/searchResultItem/SearchResultItem.tsx
- packages/@sanity/default-layout/src/navbar/search/components/searchResultItem/SearchResultItemPreview.tsx
- packages/@sanity/desk-tool/src/components/ReferencePreviewLink.tsx
- packages/@sanity/desk-tool/src/components/paneItem/PaneItem.tsx
- packages/@sanity/desk-tool/src/components/paneItem/PaneItemPreview.tsx
- packages/@sanity/desk-tool/src/panes/document/documentPanel/documentViews/FormView.tsx
- packages/@sanity/form-builder/src/inputs/ReferenceInput/ReferencePreview.tsx
cc @rexxars 
Two PRs in one - they are closely related, so probably makes sense to review together. More details in each commit message.
- Verify that presence works as before and does not trigger as many re-renders as we used to
- Optimized Studio presence to trigger less re-renders
> refactor: optimize presence

- packages/@sanity/core/src/commands/dataset/alias/deleteAliasHandler.js
This is getting sorta repetitive, ain't it? 😅 Apologies, should probably have bundled all of these together.
- That the alias delete command works, with or without the flag
- Added `--force` flag to `sanity dataset alias delete` command, in order to skip the confirmation prompt
> feat(core): add `--force` flag to dataset alias delete command

- packages/@sanity/base/src/client/bifur.ts
This tags Bifur requests with studio origin.
- That the websocket is able to connect and handle messages as before
n/a
> fix(base): tag bifur requests

- packages/@sanity/form-builder/src/inputs/StringInput.tsx
- packages/@sanity/form-builder/src/inputs/TextInput.tsx
This will introduce a local editing state on String and Text inputs and then submits the produced patches throttled (1000 ms throttle time, non-leading).
This makes the performance and writing experience in these fields a lot better.
* Better typing performance in String and Text inputs.
> Throttle onChange in text inputs

- packages/@sanity/server/package.json
Fixes some deps that didn't get updated in #3612
> chore: fix deps versions for react 18

- packages/sanity/package.json
- packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts
- packages/sanity/src/core/store/_legacy/history/createHistoryStore.ts
- yarn.lock
> fix(sanity): upgrade json-reduce to 3.0

- dev/example-studio/package.json
- packages/@sanity/form-builder/package.json
This will upgrade the @sanity/portable-text-editor and fix a bug in the custom paste handler code.
* Fixes an issue causing content to be inserted twice when using custom paste handler
> Upgrade @sanity/portable-text-editor

- packages/@sanity/react-hooks/src/useEditState.ts
This PR fixes an issue that documents are not loaded when using the `useEditState` hook with "low priority" with `rxjs@7`. 
- Test that documents load when using `rxjs@7`
Fix issue with documents not loading when using `rxjs@7`
> fix(react-hooks): issue with `useEditState` low priority

- packages/sanity/src/core/user-color/__tests__/userColorManager.test.ts
- packages/sanity/src/core/user-color/manager.ts
- packages/sanity/src/core/user-color/provider.tsx
This pull request adds scheme support in the color manger. This means that colors used the review changes panel will adjust to dark mode.
Make sure that the colors in review changes panel looks nice in dark and light mode
feat(core): add scheme support in color manager
> feat(core): add scheme support in color manager

- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItem.tsx
> fix(core): use anchor tag and href on `SearchResultItem`

- packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx
- packages/sanity/src/core/form/inputs/PortableText/Editor.tsx
- packages/sanity/src/core/form/inputs/PortableText/text/Annotation.tsx
- packages/sanity/src/core/form/inputs/PortableText/text/ListItem.tsx
- packages/sanity/src/core/form/inputs/PortableText/text/Style.tsx
- packages/sanity/src/core/form/inputs/PortableText/toolbar/helpers.tsx
This is a update to the PT-input with the lastest schema changes from https://github.com/sanity-io/sanity/pull/3971
> Refactor PT-input with updated schema types

- packages/sanity/src/core/form/inputs/files/__workshop__/UploadPlaceholderStory.tsx
- packages/sanity/src/core/form/inputs/files/__workshop__/index.ts
- packages/sanity/src/core/form/inputs/files/common/UploadPlaceholder.tsx
This PR improves the responsiveness of the file and image input.
Make sure that the image and file input adjusts its layout when used in narrow containers
Improve responsiveness of file and image inputs
> fix(core): file and image input responsiveness

- packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx
- packages/sanity/src/core/form/inputs/arrays/common/list.tsx
This pull request adds a transition effect when sorting an array of primitives. This fix should be considered a workaround, but right now there is no obvious way to implement this in a more stable way.
Make sure that the array of primitives use transition and works as expected
n/a
> fix(core): add transition effect when sorting array of primitives

- LICENSE
- dev/design-studio/LICENSE
- examples/blog-studio/LICENSE
- examples/clean-studio/LICENSE
- examples/ecommerce-studio/LICENSE
- examples/movies-studio/LICENSE
- packages/@sanity/block-tools/LICENSE
- packages/@sanity/cli/LICENSE
- packages/@sanity/cli/templates/shopify/LICENSE
- packages/@sanity/diff/LICENSE
- packages/@sanity/export/LICENSE
- packages/@sanity/import-cli/LICENSE
- packages/@sanity/import/LICENSE
- packages/@sanity/mutator/LICENSE
- packages/@sanity/portable-text-editor/LICENSE
- packages/@sanity/schema/LICENSE
- packages/@sanity/types/LICENSE
- packages/@sanity/util/LICENSE
- packages/@sanity/validation/LICENSE
- packages/@sanity/vision/LICENSE
- packages/create-sanity/LICENSE
- packages/groq/LICENSE
- packages/sanity/LICENSE
- packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/LICENSE
It's that time of year again :)
> chore: update license files

- packages/@sanity/schema/src/legacy/types/file.ts
- packages/@sanity/schema/src/legacy/types/image.ts
Currently when defining a field without a provided `title` on an image or file type, the fallback title becomes the field type.
Given
```
defineField({
type: "image",
name: "image",
fields: [
{ type: "string", name: "title" },
{ type: "string", name: "notTitle" },
],
})
```
The `title` and `notTitle` fields are rendered like this:
This PR fixes the issue by "parsing" image and file fields the same way as we do for object fields
- Make sure image and file fields are rendered with the field name capitalized as fallback title
- Fixed incorrect fallback title on image fields
> fix(schema): set correct fallback title for image and file fields

- packages/sanity/src/core/form/store/formState.ts
The bug described in #4124 happened because we ignored use the `readOnly`-state for fields inside fieldsets. This PR makes sure we properly forward it as the field's formState.
- Make sure readOnly fields inside fieldsets actually becomes readOnly
- Fixes an issue that ignored the `readOnly` state for fields inside fieldsets
> fix(form): make sure fields inside fieldsets inherits the object's readOnly state

- packages/sanity/src/desk/panes/document/documentPanel/header/ValidationMenu.tsx
Field validation: adds scroll to relevant field when clicking on the error/warning. 
Add a warning/error for a field and click on the icon to scroll to the relevant field. 
Adds scroll to correct field in field validation.
> fix(desk): field validation - scroll to field

- package.json
- perf/suite.ts
- yarn.lock
> fix: perf testing save results

- dev/design-studio/package.json
- dev/test-studio/package.json
- examples/ecommerce-studio/package.json
- packages/@sanity/portable-text-editor/package.json
- packages/@sanity/vision/package.json
- packages/sanity/package.json
- packages/sanity/src/core/form/components/EditPortal.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/renderers/DefaultEditDialog.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FileActionsMenu.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FileInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageActionsMenu.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
- packages/sanity/src/core/form/studio/assetSource/AssetThumb.tsx
- packages/sanity/src/core/form/studio/assetSource/AssetUsageDialog.tsx
- packages/sanity/src/core/form/studio/assetSource/DefaultSource.tsx
- packages/sanity/src/desk/panes/document/inspectDialog/InspectDialog.tsx
- yarn.lock
This pull request implements:
- Consistent dialog behavior. In order to be able to do this, `@sanity/ui` has been updated to `1.2.0` where improvements to the `Dialog` component were introduced. 
- Some focus issues in the image and file input.
- When several dialogs are open at the same time with split panes, you should only be able to close one of the dialogs (with "Escape" or click outside)
- Image and file input is usable with keyboard
n/a
> fix(core): focus handling and dialog behavior

- packages/@sanity/cli/src/studioDependencies.ts
Fixes #4198
- Added `@types/styled-components` dependency to new projects
> fix(cli): add `@types/styled-components` dependency to new projects

- packages/sanity/src/core/field/diff/resolve/defaultComponents.ts
- packages/sanity/src/core/field/diff/resolve/resolveDiffComponent.ts
- packages/sanity/src/core/field/types/datetime/diff/DatetimeFieldDiff.tsx
This pull request improves the `date` and `datetime` review changes ui.
n/a
n/a
> fix(core): date and date time review changes ui

- packages/sanity/src/desk/structureBuilder/Component.ts
- packages/sanity/src/desk/structureBuilder/Document.ts
- packages/sanity/src/desk/structureBuilder/GenericList.ts
- packages/sanity/src/desk/structureBuilder/ListItem.ts
- packages/sanity/src/desk/structureBuilder/util/__tests__/getStructureNodeId.test.ts
- packages/sanity/src/desk/structureBuilder/util/getStructureNodeId.ts
- packages/sanity/src/desk/structureBuilder/util/validateId.ts
Fix issue where adding Cyrillic characters in title for deskStructure crashes Sanity
Fixes #4185 
1. Created a new file to generate id from either title or provided id since it was being used in multiple place
- _Note: Not sure if the name of the file makes sense, I would love some suggestions_
2. Does the location of test make sense?
- Allow Cyrillic characters in Desk Structure titles
> fix(desk): cyrillic characters in deskStructure crashes studio

- packages/sanity/src/core/preview/components/PreviewLoader.tsx
Fixes icons not showing in array fields in v3
Fixes #4077  
Fixes icons not showing in array fields
> fix(core): icons not showing in array fields

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/actions/login/login.js
Backports auth changes changes from #4222 to v2
Making sure everything is backported and I didn't miss anything
> feat(cli): use local callback server for auth instead of listener

- packages/@sanity/vision/src/components/VisionGui.tsx
- Fix result cut off in vision result
- Fix scroll bar being hidden in vision result
[sc-26725]
[sc-26731]
Before:
After:
- Fix result cut off in vision result
- Fix scroll bar being hidden in vision result
> fix(vision): fix results getting cut off in vision

- perf/cli.ts
- perf/runner/utils/testIds.ts
- perf/studio/sanity.config.ts
- perf/studio/schema/deepArrayReferences.ts
- perf/studio/schema/deepArrayString.ts
- perf/tests/arrayOf1kReferenceItems.test.ts
- perf/tests/arrayOf1kStringItems.test.ts
This PR adds more tests for performance testing, specifically
- Array of string
- Array of references
N/A (It's internal)
> chore(perf): add perf tests for different array items

- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/useMemoCompare.ts
- packages/sanity/src/core/form/store/utils/__tests__/immutableReconcile.test.ts
- packages/sanity/src/core/form/store/utils/immutableReconcile.ts
- packages/sanity/src/core/form/studio/contexts/FormCallbacks.tsx
This adds a handful of perf opmitizations that's especially noticeable on large arrays.
Editing in the studio should work exactly as before, just feel smoother and faster
- Optimized typing performance of array items. This should make editing feel a lot faster, especially for large arrays.
> fix(perf): various perf improvements

- packages/@sanity/initial-value-templates/package.json
- packages/@sanity/initial-value-templates/src/builder.ts
- packages/@sanity/initial-value-templates/src/resolve.ts
- packages/@sanity/mutator/package.json
- packages/@sanity/structure/package.json
- packages/@sanity/transaction-collator/package.json
Fixes permissions issue when initialValue is set to an empty object
[sc-32010]
1. Is there another way to write the conditional more cleanly?
2. Are there any other things that can go wrong with this change? 
- Fixes permission issue when initialValue is set to empty object
> fix(form-builder): fix permission when initialValue is empty object

- packages/sanity/src/core/form/studio/assetSource/AssetRow.tsx
Design improvement to type name in file picker. 
That the type field in the file picker list looks good on all screen sizes
Small design improvement in file picker list
> fix(core): add ellipsis textOverflow to type in file picker list

- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
- packages/sanity/src/core/form/inputs/arrays/common/list.tsx
- packages/sanity/src/core/form/members/array/items/ArrayOfObjectsItem.tsx
- packages/sanity/src/core/form/members/object/ObjectInputMember.tsx
- packages/sanity/src/core/form/members/object/ObjectInputMembers.tsx
- packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
Adds virtualization to Array of Objects which helps fix performance issues when dealing with large arrays
- If the virtualization logic make sense
- ~Is boundary component implemented correctly?~ Confirmed with Marius, usage is fine
- I tested different scenarios including drag and drop, custom height components and there was no issue
- Fixes performance issues when dealing with large arrays
> fix(core): add virtualization to array of objects and references

- packages/sanity/src/core/components/popoverDialog/PopoverDialog.tsx
- packages/sanity/src/core/form/components/EditPortal.tsx
Fixes issue with Popover not being displayed that was broken in #4410 
N/A (fixing change from previous PR)
> fix(core): popper editing of arrays

- packages/@sanity/cli/src/packageManager/packageManagerChoice.ts
When running the CLI `init` command (and similar) through a package manager (eg `npm create sanity`, `yarn create sanity`, `pnpm create sanity`, `npx create-sanity`, `npx @sanity/cli init` etc), it seems logical to me that the user would want to install dependencies for the project using the same package manager. In other words, when running `yarn create sanity`, automatically suggest using yarn to install dependencies, instead of defaulting to npm.
I decided not to be _too_ presumptuous - we don't _skip_ the prompt, we just default to the same one that is being run. The exception to this rule is when running in unattended mode, in which case we _do_ presume that this is the right choice.
Slightly hard to test this, _but_:
1. Create an empty `package.json` somewhere
2. Add a script that …
> fix(cli): prefer package manager that is currently executing

- perf/cli.ts
Lil' change to add a perf cli flag for listing current testids
n/a - internal tooling
> fix(perf): add flag to list known test ids

- scripts/printReleaseNotesTemplate.js
Correct the installation command and bring some more helpful context to the upgrade command
Corrected the installation command in the release note template.
Does the MD render as it should?
No notes are needed for this.
> chore: fix installation command in release note template

- packages/sanity/package.json
- yarn.lock
Fixes #4593
Studio still builds
None
> fix(core): align @types/react-is module version

- packages/sanity/src/router/IntentLink.tsx
- packages/sanity/src/router/Link.tsx
- packages/sanity/src/router/withRouter.tsx
Add tsdoc for IntentLink, Link and withRouter APIs
If the descriptions and examples makes sense, I am not very familiar with this APIs
N/A (Not sure if we want to include this in the release)
> chore(router): add docs for IntentLink, Link and withRouter APIs

- packages/sanity/tsdoc.json
Fix issue with the ESLinting (on next)
https://github.com/sanity-io/sanity/actions/runs/5320741764/jobs/9634918275#logs
@rexxars 
Main question I have about the workflow (Should the linter fix? 🤔) is if there is a reason why we shouldn't have this running on each Push? When merging the tsdoc changes into next we got an error from the linting because of missing tags, but these would have be useful to have as we push. Thoughts? :thinking_face:
Make sure the question asked ☝️ is answered and that we're ok with it
n/a
> fix: add missing tags

- packages/@sanity/cli/src/commands/debug/printDebugInfo.ts
Currently, the `sanity debug` command prints the value of `user.role`, which can only ever contain the built-in roles we used to support, or the string "custom". This is not great for debugging, since a user can now have a number of different roles.
This PR changes to use a newer API version for the project info request, which includes the full `roles` array. Additionally, it moves the `User role` from the project info to the user info, since this makes more sense to me.
Note that we only print the name (id) of the roles, not the descriptions. I think this usually good enough to debug with.
- `sanity debug` in global context works (skips outputting the `Roles` key)
- `sanity debug` in project context works (outputs the array of user roles)
- `sanity debug` now outputs all the roles of the …
> feat(cli): print all current user roles in debug output

- package.json
- packages/@sanity/cli/package.json
- packages/@sanity/import-cli/package.json
- packages/@sanity/import/package.json
- packages/@sanity/types/package.json
- packages/@sanity/validation/package.json
- packages/@sanity/vision/package.json
- packages/@sanity/vision/src/components/PerspectivePopover.styled.tsx
- packages/@sanity/vision/src/components/PerspectivePopover.tsx
- packages/@sanity/vision/src/components/VisionGui.tsx
- packages/@sanity/vision/src/perspectives.ts
- packages/@sanity/vision/src/util/encodeQueryString.ts
- packages/@sanity/vision/src/util/parseApiQueryString.ts
- packages/sanity/package.json
- perf/package.json
- yarn.lock
Adds perspective support to the vision plugin
> feat(vision): add support for perspectives

- packages/sanity/src/router/IntentLink.tsx
- packages/sanity/src/router/Link.tsx
- packages/sanity/src/router/RouteScope.tsx
- packages/sanity/src/router/RouterProvider.tsx
- packages/sanity/src/router/StateLink.tsx
- packages/sanity/src/router/route.ts
- packages/sanity/src/router/types.ts
- packages/sanity/src/router/useIntentLink.ts
- packages/sanity/src/router/useLink.ts
- packages/sanity/src/router/useRouter.ts
- packages/sanity/src/router/useRouterState.ts
- packages/sanity/src/router/useStateLink.ts
Adds documentation for `sanity/router` package
- Accuracy for the documentation
- If more details are needed in anything
- If examples need more details
- Also converts some `type` to `interface` 
N/A
> chore(router): add docs for sanity/router package

- packages/@sanity/schema/src/legacy/types/blocks/defaults.ts
This updates microcopy for:
- PTE toolbar items
- URL field in PTE Link annotation
- "Show more options.." toolbar buttons for formatting/blocks
[sc-22402] [sc-22400] [sc-22403] [sc-22404]
- Improved microcopy in Portable Text Editor
> PTE microcopy updates

- packages/@sanity/portable-text-editor/package.json
- yarn.lock
Removes unused dependency of `typedoc` 
Making sure the dependency is not used anywhere
N/A
> chore(deps): remove unused typedoc dependency

- packages/@sanity/portable-text-editor/package.json
- packages/@sanity/portable-text-editor/src/editor/plugins/createWithUndoRedo.ts
- packages/@sanity/portable-text-editor/test/__tests__/undoRedo.collborative.test.ts
Just bringing this back into the correct branch
> test(portable-text-editor): add more undo/redo tests

- packages/sanity/src/core/components/hookCollection/requestIdleCallback.ts
> fix(core): timeouts randomly being cancelled

- packages/sanity/src/desk/components/deskTool/DeskTitle.tsx
Some minor refactoring suggestions to the existing PR in-flight – genuinely curious to get your thoughts @pedrobonamin! 
This also adds a minor change to ensure that the last (or right-most) document title is always displayed. 
Visiting a page with multiple document panes should always render the document title of the right-most pane. [Example](https://test-studio-git-feature-edx-92-all-pages-have-the-same-t-22d212.sanity.build/test/content/untitledRepro;grrm;03d08532-319f-44b6-a655-15f2e7bea8f6%2Ctype%3Dauthor%2CparentRefPath%3DbestFriend)
N/A
> fix(desk): try simplify title creation, always display the last document pane title where applicable

- .github/workflows/docReportTeardown.yml
Fixes failure with wrong env var on the actions https://github.com/sanity-io/sanity/actions/runs/6100899574/job/16556141478 
N/A
> chore(docs): fix doc report cleanup script

- .github/workflows/docReport.yml
- .github/workflows/docReportTeardown.yml
- scripts/doc-report/docReport.ts
- scripts/doc-report/docReportCleanup.ts
- fixes token mismatch when deleting dataset
- better message when no changes to documentation coverage
The actions conditionals are valid
N/A
> chore(docs): compare PRs against next branch instead of current

- scripts/doc-report/docReport.ts
Lifted from PR #4919 fixes formatting issues and calculation for PR docs comment
> chore(docs): fix docs report comment

- packages/sanity/src/core/store/user/hooks.ts
Adds docs for useCurrentUser hook
This hook changes from `internal` to `public` are there any concerns about that? 
N/A
> chore(docs): adds docs for useCurrentUser hook

- packages/sanity/src/core/store/_legacy/document/listenQuery.ts
As the title says.
- Added support for perspectives in the `listenQuery()` method
> feat: support perspectives in `listenQuery`

- packages/sanity/src/desk/panes/document/inspectors/validation/getPathTypes.ts
Changed 1 error message as there was a small typo
> chore: typo in error message

- packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.styled.tsx
- packages/sanity/src/core/studio/Studio.test.tsx
- packages/sanity/src/core/theme/_legacy/theme.ts
Add changes in studio so it doesn't break with the new sanity/ui alpha changes.
> fix(alpha-ui): support for breaking changes inside studio with new sanity/ui

- dev/test-studio/schema/debug/virtualizationDebug.tsx
This PR adds debug schema for issue https://github.com/sanity-io/sanity/issues/4687#issuecomment-1767853613
Fix will be added in future PR
- N/A
> chore(core): add debug schema for virtualization bug

- packages/sanity/src/desk/comments/src/context/comments/CommentsProvider.tsx
- packages/sanity/src/desk/comments/src/hooks/useCommentOperations.ts
- packages/sanity/src/desk/comments/src/types.ts
> feat: add `currentThreadLength` to notification context

- dev/design-studio/package.json
- dev/test-studio/package.json
- examples/ecommerce-studio/package.json
- packages/@sanity/cli/src/actions/init-project/templates/getStarted.ts
- packages/@sanity/cli/src/actions/init-project/templates/shopify.ts
- packages/@sanity/cli/src/actions/init-project/templates/shopifyOnline.ts
- packages/@sanity/portable-text-editor/package.json
- packages/@sanity/vision/package.json
- packages/sanity/package.json
- yarn.lock
Bumps version of `@sanity/ui` to latest
- Any downside to doing this?
- Bumps `@sanity/ui` to latest version
> fix(deps): bump @sanity/ui to latest

- dev/test-studio/plugins/locale-no-nb/bundles/studio.ts
- packages/sanity/src/core/form/components/FormInput.tsx
- packages/sanity/src/core/form/components/formField/FormFieldHeaderText.tsx
- packages/sanity/src/core/form/components/formField/FormFieldSetLegend.tsx
- packages/sanity/src/core/form/components/formField/FormFieldValidationStatus.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
Translates the form field components
> feat(i18n): translate form field components

- dev/test-studio/plugins/locale-no-nb/bundles/studio.ts
- packages/sanity/src/core/form/inputs/files/FileInput/FileActionsMenu.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FileInput.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/InvalidFileWarning.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageActionsMenu.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/InvalidImageWarning.tsx
- packages/sanity/src/core/form/inputs/files/ImageToolInput/ImageToolInput.tsx
- packages/sanity/src/core/form/inputs/files/common/DropMessage.tsx
- packages/sanity/src/core/form/inputs/files/common/UploadPlaceholder.tsx
- packages/sanity/src/core/form/studio/inputs/StudioFileInput.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/test/form/renderFileInput.tsx
Updates translation for files in `packages/sanity/src/core/form/inputs/files`
> feat(i18n): updates translation for form/inputs/files after rebase of feat/i18n

- packages/sanity/src/core/form/inputs/DateInputs/__tests__/CommonDateTimeInput.test.tsx
- packages/sanity/src/core/form/inputs/DateInputs/base/calendar/Calendar.tsx
- packages/sanity/src/core/form/inputs/DateInputs/base/calendar/types.ts
- packages/sanity/src/core/form/inputs/DateInputs/utils.ts
- packages/sanity/src/core/form/inputs/InvalidValueInput/InvalidValueInput.tsx
- packages/sanity/src/core/form/inputs/InvalidValueInput/UntypedValueInput.tsx
- packages/sanity/src/core/form/inputs/ObjectInput/UnknownFields.tsx
- packages/sanity/src/core/form/inputs/ObjectInput/fieldGroups/FieldGroupTabs.tsx
- packages/sanity/src/core/form/members/object/MemberFieldError.tsx
- packages/sanity/src/core/form/members/object/errors/DuplicateKeysAlert.tsx
- packages/sanity/src/core/form/members/object/errors/MissingKeysAlert.tsx
- packages/sanity/src/core/form/members/object/errors/MixedArrayAlert.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
Updates translation for object form inputs
> feat(i18n): updates translation for object form inputs

- packages/sanity/src/desk/comments/plugin/inspector/CommentsInspector.tsx
- packages/sanity/src/desk/comments/plugin/inspector/CommentsInspectorFeedbackFooter.tsx
This pull request adds a footer in the comments inspector with a link to a feedback form.
- Make sure that it looks good!
n/a
> feat(comments): add feedback footer in the inspector

- .eslintrc.cjs
Adds another directory to the exclude list for comments related files
> chore(i18n): updates eslint config to exclude more comments files

- packages/sanity/src/desk/comments/src/context/setup/CommentsSetupProvider.tsx
This pull request changes the API version in the addon dataset client used in comments.
- Make sure that everything works with the new API version
n/a
> fix(comments): addon dataset client api version

- packages/sanity/src/_internal/cli/commands/dataset/exportDatasetCommand.ts
- packages/sanity/src/_internal/cli/commands/dataset/importDatasetCommand.ts
- yarn.lock
If any copy changes or style changes need to happen
- Adds information about `projectId` and `dataset` on import and export dataset commands
> feat(cli): adds information about projectId and datasets on import and export dataset commands

- packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialog.tsx
Remove hardcoded Delete text and use capitalized action instead for the delete/unpublish dialog
The dialog when deleting/unpublishing a document
> fix(desk): add capitalizedAction as button text in delete dialog

- packages/sanity/src/desk/comments/plugin/inspector/CommentsInspectorFeedbackFooter.tsx
This pull request changes the font size in the comments feedback footer and updates the copy.
> fix(comments): feedback footer font size and copy

- packages/sanity/src/core/components/NoJavascript.tsx
- packages/sanity/src/core/studio/components/navbar/configIssues/ConfigIssuesButton.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/DebugOverlay.tsx
- packages/sanity/src/core/studio/screens/CorsOriginErrorScreen.tsx
- packages/sanity/src/core/studio/screens/NoSourcesScreen.tsx
- packages/sanity/src/core/studio/screens/NoToolsScreen.tsx
- packages/sanity/src/core/studio/screens/NotAuthenticatedScreen.tsx
- packages/sanity/src/core/studio/screens/NotFoundScreen.tsx
- packages/sanity/src/core/studio/screens/ToolNotFoundScreen.tsx
- packages/sanity/src/core/studio/screens/schemaErrors/InitialValueTemplateError.tsx
- packages/sanity/src/core/studio/screens/schemaErrors/SchemaErrorsScreen.tsx
- packages/sanity/src/core/studio/screens/schemaErrors/SchemaProblemGroups.tsx
- packages/sanity/src/core/studio/workspaceLoader/ErrorMessage.tsx
Marking files deemed out of scope for translation to ignore i18n lint rules
> chore(i18n): ignore i18n eslint rules for files out of scope for translation

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/studio/components/navbar/NavDrawer.tsx
- packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx
Adds missing translation for a few random files that had already had most of the strings translated already
> feat(i18n): adds missing translation for a few random files

- packages/sanity/src/desk/components/pane/PaneHeader.styles.tsx
- packages/sanity/src/desk/components/pane/PaneHeader.tsx
- packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/desk/panes/document/documentPanel/header/DocumentPanelHeader.tsx
Adds a permanent border to the document panes and conditional borders to the document lists
> fix(desk): add border always on document header, remove padding

- packages/sanity/src/desk/comments/src/components/pte/comment-input/Editable.tsx
This pull request fixes an issue where the reply comment input is getting focused when clicking outside of it. The reason for this behavior is not immediately apparent, but replacing `styled(Stack)` with a plain div resolves the problem. In addition, this pull request refactors some logic in the editable component in the comment input to make it more readable.
https://github.com/sanity-io/sanity/assets/15094168/903d5e45-bd85-4141-8b8f-78d755c2be88
- Make sure that the comment input don't get focused when clicking outside of it
n/a
> fix(comments): reply input focus issue

- package.json
- yarn.lock
Upgrading to lerna v5 has incompatibility with prettier v3 which can only be fixed via upgrading to v7 which needs more extensive testing
changes looks good from https://github.com/sanity-io/sanity/pull/5099
- N/A
> fix(deps): downgrade lerna to v4

- dev/test-studio/plugins/locale-no-nb/bundles/studio.ts
- packages/sanity/src/core/form/inputs/DateInputs/CommonDateTimeInput.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
Localizes datetime input placeholder value
Not sure if I did this correctly. I didn't format the date in the placeholder since it can be overridden via the schema
(probably part of larger release notes for 18n)
> feat(i18n): localize datetime input placeholder

- packages/sanity/src/_internal/cli/commands/dataset/importDatasetCommand.ts
Minor change to bring the help output in line with the behaviour.
> doc: add tarball to help output of dataset import

- packages/sanity/src/core/i18n/debug.ts
Vite does not have `process.env` exposed. This makes it so that usage of the env var is wrapped safely
Change makes sense
- Fixes issue where studio would crash when embedded inside a vite app
> fix(core): fixes issue where studio crashes when embedded w/ vite

- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/form/studio/inputs/crossDatasetReference/datastores/getReferenceInfo.ts
I apologise - I forgot to commit the suggestions from @bjoerge on this [PR](https://github.com/sanity-io/sanity/pull/5352) 🤦‍♀️
> fix(core): simplify code for getting preview paths

- packages/sanity/src/core/form/inputs/PortableText/toolbar/ActionMenu.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
After merging this PR: https://github.com/sanity-io/sanity/pull/5257 eslint throws error in next
This fixes that error.
> fix(pte): add transalation to disabled tooltip text

- packages/sanity/src/core/components/DefaultDocument.tsx
> fix(facelift): self serve Inter font

- packages/@sanity/vision/src/components/VisionGui.tsx
Fixes an issue where selection Other option in vision causes crash which would only recover after clearing the localstorage.
changes makes sense
- Fixes issue with vision where selecting Other would crash the studio
> fix(vision): fixes an issue where selection other would crash

- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ObjectBlock.spec.tsx
- packages/sanity/src/core/studio/Studio.test.tsx
- packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentButton.tsx
- packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentListOption.tsx
- packages/sanity/src/core/studio/components/navbar/resources/ResourcesButton.tsx
- test/e2e/tests/navbar/createNewDocumentNav.spec.ts
> fix(core/tests): fix failed tests

- packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrialContext.tsx
Add api Version stamp to free trial request
> fix(free-trial): add apiVersion stamp to free trial request

- packages/sanity/README.md
Added section on contributing translation improvements
New README section
> chore: update readme contribution info

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/__telemetry__/cli.telemetry.ts
- packages/@sanity/cli/src/__telemetry__/init.telemetry.ts
- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/src/actions/login/login.telemetry.ts
- packages/@sanity/cli/src/actions/login/login.ts
- packages/@sanity/cli/src/cli.ts
- packages/@sanity/cli/src/commands/init/initCommand.ts
- packages/@sanity/cli/src/types.ts
- packages/@sanity/cli/src/util/createTelemetryStore.ts
- packages/@sanity/cli/src/util/detectRuntime.ts
- packages/sanity/package.json
- packages/sanity/src/_internal/cli/actions/build/build.telemetry.ts
- packages/sanity/src/_internal/cli/actions/build/buildAction.ts
- yarn.lock
Instruments the CLI with telemetry events
- Does the setup make sense? Are the events on the format that we want them to be?
- n/a will be included in general release notes for telemetry
> feat(cli): instrument cli with telemetry events

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/__telemetry__/cli.telemetry.ts
- packages/@sanity/cli/src/cli.ts
- packages/sanity/package.json
- yarn.lock
Includes contextual info with all telemetry trace events
n/a
> fix(cli): include command context in trace.completed/trace.failed

- packages/@sanity/cli/src/actions/init-project/templates/getStarted.ts
- packages/@sanity/cli/src/actions/init-project/templates/shopify.ts
- packages/@sanity/cli/src/actions/init-project/templates/shopifyOnline.ts
Upgrades the templates that uses @sanity/ui directly to use the new beta of Sanity UI
n/a
> fix(cli): upgrade templates to use @sanity/ui@beta

- dev/design-studio/package.json
- dev/embedded-studio/package.json
- dev/studio-e2e-testing/package.json
- dev/test-studio/package.json
- examples/ecommerce-studio/package.json
- packages/@sanity/portable-text-editor/package.json
- packages/@sanity/vision/package.json
- packages/sanity/package.json
- yarn.lock
update @sanity/ui to 2.0.0-beta.16
update @sanity/ui to 2.0.0-beta.16
> chore(dependencies): update @sanity/ui to 2.0.0-beta.16

- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridItem.tsx
- packages/sanity/src/core/form/inputs/arrays/common/DragHandle.tsx
- packages/sanity/src/core/form/inputs/arrays/layouts/CellLayout.tsx
- packages/sanity/src/core/studio/Studio.test.tsx
Same drill as #5284
Fixed console warnings about passing through non-DOM properties to styled-components
> fix: prevent props that are unknown html attributes from passing through

- dev/test-studio/schema/debug/deprecatedFields.ts
- packages/sanity/src/core/form/components/formField/FormFieldHeaderText.tsx
- packages/sanity/src/core/form/components/formField/FormFieldSet.tsx
- test/e2e/tests/desk/deprecatedFields.spec.ts
Adds test for deprecated fields for core types 
Slug and geopoint failing are known, they are still being worked on
- N/A
> chore(test): add tests for deprecated fields

- packages/sanity/src/structure/components/structureTool/StructureTitle.test.tsx
Updates StructureTitle tests to be use actual provider for i18n
all unit tests pass
- N/A
> test(structure): update StructureTitle tests

- packages/@sanity/schema/src/legacy/types/constants.ts
This passes the deprecated info so it works for named objects, slugs and geopoint
All E2E tests pass
- N/A
> feat: pass deprecated info to object types

- .github/PULL_REQUEST_TEMPLATE.md
Updating the pull request template to put more of an emphasis on the importance of automated testing. Now that we have an E2E test bench, most PRs should include adding tests. If not, we should document why we are not testing so we can look to extend our test bench or improve documentation on testing.
> chore(core): updated pull request template to emphasize testing

- packages/sanity/src/structure/comments/src/__tests__/mergeCommentReactions.test.ts
- packages/sanity/src/structure/comments/src/__workshop__/CommentReactionsMenuButtonStory.tsx
- packages/sanity/src/structure/comments/src/__workshop__/CommentReactionsMenuStory.tsx
- packages/sanity/src/structure/comments/src/components/list/CommentsListItemContextMenu.tsx
- packages/sanity/src/structure/comments/src/components/list/CommentsListItemLayout.tsx
- packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsBar.tsx
- packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsMenu.tsx
- packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsMenuButton.tsx
- packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsUsersTooltip.tsx
- packages/sanity/src/structure/comments/src/components/reactions/EmojiText.styled.ts
- packages/sanity/src/structure/comments/src/components/reactions/TransparentCard.styled.ts
- packages/sanity/src/structure/comments/src/constants.ts
- packages/sanity/src/structure/comments/src/types.ts
(See inline comments for more context)
> fix: force emoji-specific fonts, prefer buttons over cards, minor styling updates

- packages/@sanity/cli/src/actions/init-project/templates/getStarted.ts
- packages/@sanity/cli/src/actions/init-project/templates/shopify.ts
- packages/@sanity/cli/src/actions/init-project/templates/shopifyOnline.ts
Upgrades the templates that uses @sanity/ui directly to use `^2.0.0`
N/A
N/A
> fix(cli): upgrade templates to use @sanity/ui@2

- packages/sanity/src/structure/comments/src/components/list/CreateNewThreadInput.tsx
Fixes a small issue where a source file imported from `@sanity/ui-workshop` instead of `sanity`, leading to unwanted files being bundled.
None.
> fix(structure): fix unintended import from `@sanity/ui-workshop`

- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/documentInspector/DocumentInspectorHeader.tsx
Fixes SDX-908
This change fixes a missing translation for the close button for a few panels.
> fix(i18n): missing translation on close button

- packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Adds a prompt before running a real migration with the projectId and dataset so the user is aware and intentionally selects running a real migration
`sanity migration run <name-of-migration> --dry=false` should show a prompt like "This migration will run on the “test” dataset in “yajkdsl” project. Are you sure?"
- N/A
> feat(migration): add a prompt before runing a real migration

- packages/sanity/src/structure/documentActions/DuplicateAction.tsx
Fixes a bug where duplicating large documents would result in opening a blank document.
Take a look at the code and ensure it navigates correctly.
**Before**:
https://github.com/sanity-io/sanity/assets/10551026/db8d2839-ad25-490a-8ac0-11794645f480
**After**: 
https://github.com/sanity-io/sanity/assets/10551026/2aa6f843-3b9e-48dd-bb53-4757b18fe4ee
- Fixes a bug where large documents would not duplicate correctly
> fix(core): wait for duplicate success before navigating

- packages/@sanity/migrate/src/runner/dryRun.ts
- packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
- Fixes the dry run command to show an done message. The progress indicator probably needs some love but there is #5573 to take care of it
- Also shows proper error message if the migration file has code issues instead of file not found error.
The dry-run from export file hangs for me not sure if it's just me or widespread. Please confirm that. 
- N/A
> fix(migration): fixes issue with dry-run output

- packages/@sanity/migrate/src/fetch-utils/sanityRequestOptions.ts
- packages/@sanity/migrate/src/runner/run.ts
- packages/@sanity/migrate/src/sources/fromExportEndpoint.ts
Adds appropriate tags params and user agent headers to migration runner.
> fix(migrate): add request tags and user agent

- packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Removes `from-export` flag from migration CLI
> chore(migration): remove from-export flag from migration cli

- packages/@sanity/migrate/src/runner/utils/createFilteredDocumentsClient.ts
- packages/@sanity/migrate/src/types.ts
Removes `query` method from filter object in the migration context
> chore(migration): remove query from migration context

- packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Changes from `--dry` flag to `--dry-run` flag
> chore(migration): change dry command to dry-run

- packages/sanity/src/_internal/cli/commands/migration/createMigrationCommand.ts
- packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
- changes `--project-id` to `--project` flag for consistency
- updates copy in create migration command
> fix(migration): parse cli arguments so the types are proper

- packages/@sanity/migrate/src/runner/utils/__tests__/toSanityMutations.test.ts
- packages/@sanity/migrate/src/runner/utils/toSanityMutations.ts
> fix(migration): fixes issues where patch would happen twice

- packages/sanity/src/_internal/cli/commands/migration/listMigrationsCommand.ts
Provides helpful error messages when migrations folder is not found or there are no migrations in the folder 
- Did some cleanup on wrong types and signature. Let me know if that makes sense
- Copy makes sense
- Everything still works as expected
TBD
- Provides more helpful error message when running list migrations without existing migrations present
> fix(migration): shows better error message when running migration list

- packages/sanity/src/_internal/cli/commands/migration/createMigrationCommand.ts
Updates copy on migration create command
Copy makes sense
N/A
N/A (Probably does not need to be mentioned)
> chore(migration): fixes help copy on migration create command

- packages/sanity/src/structure/comments/src/context/upsell/CommentsUpsellProvider.tsx
Transitions from using a direct GROQ query towards a given project ID to using the dedicated `/journey/comments` endpoint. This allow us to change the shape on the backend more easily while maintaining backwards compatibility, as well as allowing for more granular cache control and similar.
- Check and response still works (currently only enabled in staging)
None.
> refactor(comments): use journey endpoint for comments upsell

- package.json
Fixing an oversight with the CI setup after #5533 
n/a
> fix(chore): fix lint script

- packages/sanity/src/tasks/src/tasks/components/list/TasksList.tsx
- packages/sanity/src/tasks/src/tasks/components/list/TasksListItem.tsx
- packages/sanity/src/tasks/src/tasks/components/list/TasksStatus.tsx
- packages/sanity/src/tasks/src/tasks/context/tasks/useTaskOperations.ts
- packages/sanity/src/tasks/src/tasks/types.ts
> fix(tasks): add status to task

- perf/studio/package.json
- perf/tests/runner/runner.ts
Found a couple of remaining yarn references that didn't make it into #5533 
- The diff :)
n/a
n/a - internal
> chore(perf): replace references to yarn with pnpm

- packages/@sanity/import/README.md
ndjson.org looks to be expired and hijacked.
Click the link :smile:
> fix: update ndjson specification url

- .github/CODEOWNERS
Assign some more code to the EX Team.
> chore: update codeowners details

- packages/@sanity/codegen/package.json
- packages/@sanity/codegen/src/typescript/__tests__/findQueriesInPath.test.ts
- packages/@sanity/codegen/src/typescript/__tests__/fixtures/source1.ts
- packages/@sanity/codegen/src/typescript/__tests__/fixtures/source2.ts
- packages/@sanity/codegen/src/typescript/findQueriesInPath.ts
- pnpm-lock.yaml
> feat(codegen): ensure unique query names

- packages/sanity/src/structure/comments/src/hooks/use-comment-operations/createOperation.ts
- packages/sanity/src/structure/comments/src/types.ts
> fix(comments): use `_weak` instead of `weak`

- packages/sanity/src/structure/comments/src/components/list/CommentsListItem.tsx
- packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityLog.tsx
- packages/sanity/src/tasks/src/tasks/components/activity/TasksSubscribers.tsx
This pull request makes two minor UI tweaks to the Tasks feature:
- Spacing in comment items
- Fixes subscribers avatar size
N/A
N/A
> fix(tasks): ui tweaks

- packages/sanity/src/tasks/plugin/TasksStudioActiveToolLayout.tsx
- packages/sanity/src/tasks/src/tasks/components/sidebar/TasksSidebar.tsx
This pull request makes the sidebar work in narrow screens.
- Make sure that the sidebar looks good in various breakpoints
N/A
> feat(tasks): responsive sidebar

- packages/sanity/src/tasks/plugin/TasksStudioActiveToolLayout.tsx
- packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityLog.tsx
- packages/sanity/src/tasks/src/tasks/components/form/tasksFormBuilder/FormCreate.tsx
- packages/sanity/src/tasks/src/tasks/components/form/tasksFormBuilder/FormEdit.tsx
- packages/sanity/src/tasks/src/tasks/components/form/tasksFormBuilder/TasksFormBuilder.tsx
- packages/sanity/src/tasks/src/tasks/components/list/TasksList.tsx
- packages/sanity/src/tasks/src/tasks/components/list/TasksListItem.tsx
- packages/sanity/src/tasks/src/tasks/components/sidebar/TasksHeaderDraftsMenu.tsx
- packages/sanity/src/tasks/src/tasks/components/sidebar/TasksSidebar.tsx
- packages/sanity/src/tasks/src/tasks/components/sidebar/TasksSidebarHeader.tsx
This pull request addresses three minor UI issues: handling long task descriptions in task list items, removing unwanted space from the bottom of the list, and increasing the spacing between activity log items to make the interface a bit less busy and dense. Additionally, it attempts to unify the way spacing and padding are handled by making the outermost padding of the list the responsibility of the root component, rather than allowing individual components to manage their own outer spacing. The pull request also includes a few code cleanups and refactoring efforts to enhance readability in some components.
- Make sure that feature works as before
- Make sure that the UI changes looks good
N/A
> feat(tasks): ui improvements 

- packages/@sanity/migrate/package.json
- pnpm-lock.yaml
Updates `@sanity/migrate` groq version to match rest of the packages
Everything still works
> chore(deps): pin @sanity/migrate groq to 1.5.0

- packages/@sanity/codegen/src/typescript/__tests__/__snapshots__/typeGenerator.test.ts.snap
- packages/@sanity/codegen/src/typescript/__tests__/typeGenerator.test.ts
- packages/@sanity/codegen/src/typescript/typeGenerator.ts
Uppercase all generated types
✔️ 
N/A - no notes needed
> fix(codegen): uppercase query type names

- packages/sanity/src/tasks/i18n/resources.ts
- packages/sanity/src/tasks/src/tasks/components/form/addonWorkspace/taskSchema.tsx
- packages/sanity/src/tasks/src/tasks/components/sidebar/TasksListTabs.tsx
Updates some copy for the Tasks feature and also some remaining strings for i18n
> fix(tasks): copy changes for Tasks feature

- packages/sanity/src/tasks/plugin/TasksStudioNavbar.tsx
- packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityCommentInput.tsx
- packages/sanity/src/tasks/src/tasks/components/activity/TasksSubscribers.tsx
- packages/sanity/src/tasks/src/tasks/components/form/fields/assignee/AssigneeEditFormField.tsx
- packages/sanity/src/tasks/src/tasks/components/list/TasksListItem.tsx
This pull request makes a few UI adjustments to the Tasks feature; these adjustments include:
- Unifying padding in the comment input
- Hiding "undefined" subscribers from the UI
- Updating the hover styling of a Task list item
Additionally, this pull request implements a change that only allows Tasks to be opened from the Studio navbar, but not closed.
- Make sure that the UI adjustments look good
N/A
> fix(tasks): ui adjustments

- packages/sanity/src/tasks/src/tasks/components/form/fields/assignee/AssigneeSelectionMenu.tsx
Disable autocomplete on 'assign to' input
> fix(tasks): disable autocomplete on 'assign to' input

- dev/test-studio/sanity.config.ts
Disables server actions in our test studio since it caused unusual behavior in PTE.
> fix: disable server actions in test studio

- package.json
- packages/@repo/package.config/src/package.config.ts
- packages/@repo/tsconfig/base.json
- packages/@repo/tsconfig/build.json
- packages/@sanity/block-tools/package.json
- packages/@sanity/cli/package.json
- packages/@sanity/cli/templates/shared/tsconfig.json
- packages/@sanity/codegen/package.json
- packages/@sanity/diff/package.json
- packages/@sanity/migrate/package.json
- packages/@sanity/mutator/package.json
- packages/@sanity/portable-text-editor/package.json
- packages/@sanity/schema/package.json
- packages/@sanity/types/package.json
- packages/@sanity/types/tsconfig.lib.json
- packages/@sanity/util/package.json
- packages/@sanity/vision/package.json
- packages/groq/package.json
- packages/sanity/package.json
- packages/sanity/src/_internal/cli/actions/build/buildAction.ts
- packages/sanity/tsconfig.json
- packages/sanity/tsconfig.lib.json
- packages/sanity/tsconfig.settings.json
- packages/sanity/tsconfig.tsdoc.json
- pnpm-lock.yaml
- scripts/etl.ts
- turbo.json
Fixes the type check errors during `sanity build`.
Here's the before:
```bash
sanity:build: > sanity@3.37.2 build /home/runner/work/sanity/sanity/packages/sanity
sanity:build: > pkg-utils build --check --clean
sanity:build: 
sanity:build: Deleting the `dist` folder: './lib' before building...
sanity:build: Build type definitions...
sanity:build:   entries:
sanity:build:     - sanity: ./src/_exports/index.ts → ./lib/index.d.mts
sanity:build:     - sanity: ./src/_exports/index.ts → ./lib/index.d.ts
sanity:build:     - sanity/_internal: ./src/_exports/_internal.ts → ./lib/_internal.d.ts
sanity:build:     - sanity/_internalBrowser: ./src/_exports/_internalBrowser.ts → ./lib/_internalBrowser.d.mts
sanity:build:     - sanity/_internalBrowser: ./src/_exports/_internalBrowser.ts → …
```
> fix: tsc build

- packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.test.ts
Updates unit tests to deal with recent changes to server action create functions. 
If the tests now pass.
See above 😅
> fix: update unit tests to account for new create behavior

- .github/CODEOWNERS
Update the Code owners file to match with the new folder structure for tasks and comments
> fix(codeowners): update codeowners for tasks and comments

- packages/sanity/package.json
- pnpm-lock.yaml
Bumps sanity export to include a small fix to relay better error messages.
Nothing really.
Tested it in export
Fixes an issue where some error messages where swallowed when exporting a dataset.
> chore(deps): bump @sanity/export

- packages/@sanity/portable-text-editor/src/editor/Editable.tsx
This is a follow up to https://github.com/sanity-io/sanity/pull/6531 which we found some additional issues with (not rendering decorators properly for annotations).
> fix(portable-text-editor): fix issue where decoration would not target correctly

- test/e2e/tests/desk/documentTypeListContextMenu.spec.ts
- test/e2e/tests/desk/inspectDialog.spec.ts
- test/e2e/tests/navbar/search.spec.ts
Add more extensive testing for following cases
1. Changing the sort order in document list
2. Change display layout type in document list
3. Changing Inspect view mode
4. Save searches
Tests make sense
Added
N/A
> test(core, desk): add tests for keyvalue storage

- packages/sanity/src/core/components/documentStatus/DocumentStatus.tsx
- test/e2e/tests/inputs/text.spec.ts
Attempting to fix flaky tests with publishing like [this](https://github.com/sanity-io/sanity/actions/runs/8988057967/job/24688178038?pr=6594)
✅
N/A
> test(core): fixes flaky test with document publish

- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/consistencyStatus.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/documentEvents.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/editOperations.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/editState.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/memoizeKeyGen.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/operationArgs.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/remoteSnapshots.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/snapshotPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/utils/fetchFeatureToggle.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts
- packages/sanity/src/core/store/_legacy/document/document-store.ts
- packages/sanity/src/core/store/_legacy/grants/documentPairPermissions.ts
- packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts
> refactor(document-store): pass in server actions config as observable

- packages/sanity/src/core/form/inputs/PortableText/hooks/usePortableTextMembers.tsx
This will prevent any input calling element.onFocus() on any opened block or inline-object inside the PT-input, as that will close the editing modal for them (through DocumentPaneProvider)
> fix(core/form): prevent onFocus for root object path

- packages/sanity/src/core/form/studio/tree-editing/__workshop__/TreeEditingBreadCrumbsStory.tsx
- packages/sanity/src/core/form/studio/tree-editing/__workshop__/TreeEditingBreadcrumbsMenuButtonStory.tsx
- packages/sanity/src/core/form/studio/tree-editing/__workshop__/TreeEditingBreadcrumbsMenuStory.tsx
- packages/sanity/src/core/form/studio/tree-editing/__workshop__/TreeEditingLayoutStory.tsx
- packages/sanity/src/core/form/studio/tree-editing/__workshop__/index.ts
- packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingDialog.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingLayout.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbs.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenuButton.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/constants.ts
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/index.ts
- packages/sanity/src/core/form/studio/tree-editing/components/index.ts
- packages/sanity/src/core/form/studio/tree-editing/types.ts
- packages/sanity/src/core/form/studio/tree-editing/utils/buildTreeEditingState.ts
> feat(core): initial tree editing breadcrumbs

- dev/studio-e2e-testing/README.md
- examples/clean-studio/README.md
- packages/@sanity/cli/templates/blog/README.md
- packages/@sanity/cli/templates/clean/README.md
- packages/@sanity/cli/templates/ecommerce/README.md
- packages/@sanity/cli/templates/get-started/README.md
- packages/@sanity/cli/templates/moviedb/README.md
- packages/@sanity/cli/templates/quickstart/README.md
Changes "open source" to "open-source" in new Studio readme's
> chore: correct grammar for open-source

- packages/sanity/src/core/form/studio/tree-editing/__tests__/buildTreeEditingState.test.ts
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbs.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenuButton.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsTitle.tsx
- packages/sanity/src/core/form/studio/tree-editing/types.ts
- packages/sanity/src/core/form/studio/tree-editing/utils/build-tree-editing-state/buildArrayState.ts
- packages/sanity/src/core/form/studio/tree-editing/utils/build-tree-editing-state/buildBreadcrumbsState.ts
Add array title to the array dropdown in breadcrumbs.
Kayla mentioned to drop the "keyboard" shortcuts for now.
> feat(core): add title to breadcrumb dropdown

- scripts/uploadBundles.ts
Stores the versions in the manifest file. 
Change makes sense, already tested by running the circleci job on the branch working as expected.
N/A
N/A
> feat: store all versions in the manifest

- packages/sanity/src/core/form/studio/tree-editing/__tests__/buildTreeEditingState.test.ts
- packages/sanity/src/core/form/studio/tree-editing/__tests__/treeEditingSearch.test.ts
- packages/sanity/src/core/form/studio/tree-editing/__workshop__/TreeEditingSearchStory.tsx
- packages/sanity/src/core/form/studio/tree-editing/__workshop__/index.ts
- packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingLayout.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenuButton.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsTitle.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/index.ts
- packages/sanity/src/core/form/studio/tree-editing/components/search/TreeEditingSearch.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/search/TreeEditingSearchMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/search/constants.ts
- packages/sanity/src/core/form/studio/tree-editing/components/search/index.ts
- packages/sanity/src/core/form/studio/tree-editing/components/search/utils.ts
- packages/sanity/src/core/form/studio/tree-editing/types.ts
- packages/sanity/src/core/form/studio/tree-editing/utils/build-tree-editing-state/buildArrayState.ts
This pull request implements search in the tree editing sidebar.
> feat(core): tree editing sidebar search [WIP]

- dev/test-studio/package.json
- package.json
- packages/@sanity/cli/package.json
- packages/@sanity/migrate/package.json
- packages/@sanity/types/package.json
- packages/@sanity/util/package.json
- packages/@sanity/vision/package.json
- packages/sanity/package.json
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/delete.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/discardChanges.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/publish.ts
- packages/sanity/src/core/store/_legacy/history/createHistoryStore.ts
- perf/tests/package.json
- pnpm-lock.yaml
This branch aligns usage of the Actions API with the correct types, which will be released in the next version of `@sanity/client`. Once `@sanity/client` has been released, tests for this branch should pass, and it can then be merged.
**Update:** `@sanity/client` has now been released. This branch can be merged.
Actions work as expected, and there are no type errors once `@sanity/client` has been released.
Tests already exist for this functionality.
> fix(sanity): align Actions API usage with correct types

- packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingLayout.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/search/TreeEditingSearch.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/search/TreeEditingSearchMenu.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
Update sections of the tree editing dialog that require translation keys
> Edx 1428: translation

- packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbs.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenu.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenuButton.tsx
- packages/sanity/src/core/form/studio/tree-editing/components/search/TreeEditingSearchMenu.tsx
> feat: add default preview

- packages/sanity/src/core/studio/copyPaste/types.ts
- packages/sanity/src/core/studio/copyPaste/useCopyPasteAction.ts
- packages/sanity/src/core/studio/copyPaste/utils.ts
This will refactor the CopyPaste action to support multiple sources and targets to prepare for implementing multiple select copy / paste.
> refactor(core): support multiple sources and targets for copy/paste

- packages/@sanity/vision/src/containers/VisionContainer.tsx
Center the vision tool loading bar and fixes this [issue](https://github.com/sanity-io/sanity/issues/6775)
> fix(vision): center loading spinner

- .github/renovate.json
Always bump @sanity/export instead of relying on lock file.
n/a 
> chore(deps): always bump @sanity/export package

- scripts/printReleaseNotesTemplate.ts
We've been different headers for our release notes and they are getting inconsistent. This one correct the release notes template to use the new header.
N/A - this is an internal thing
> chore: update release note template

- packages/sanity/src/core/studio/copyPaste/__test__/mockClient.ts
- packages/sanity/src/core/studio/copyPaste/__test__/schema.tsx
- packages/sanity/src/core/studio/copyPaste/__test__/valueTransfer.test.ts
- packages/sanity/src/core/studio/copyPaste/useCopyPasteAction.ts
- packages/sanity/src/core/studio/copyPaste/valueTransfer.ts
> fix(form): validate option.accept on paste

- packages/sanity/package.json
- pnpm-lock.yaml
Looks like #7001 missed one reference to the editor.
Still builds and runs.
None
> fix(deps): drop @sanity/portable-text-editor dependency

- packages/sanity/src/core/form/field/actions/copyAction.ts
- packages/sanity/src/core/form/field/actions/pasteAction.ts
- packages/sanity/src/core/i18n/bundles/copy-paste.ts
- packages/sanity/src/core/i18n/localeNamespaces.ts
- packages/sanity/src/core/i18n/locales.ts
- packages/sanity/src/core/studio/copyPaste/__test__/valueTransfer.test.ts
- packages/sanity/src/core/studio/copyPaste/useCopyPasteAction.ts
- packages/sanity/src/core/studio/copyPaste/valueTransfer.ts
This pull request translates all strings in the copy-paste feature.
- Ensure that no strings are missed.
- Verify that the translated strings make sense.
N/A
> feat(core): translate copy-paste

- packages/sanity/src/core/studio/packageVersionStatus/checkForLatestVersions.ts
Fixes issue where the timestamp in URL was not using a `Math.floor` causing it to add decimals to url which is not valid
Change makes sense
Don't believe there are tests for this but existing tests should cover this
N/A
> fix(core): fixes url for checking studio version

- packages/sanity/src/core/config/studio/types.ts
> chore(config): comment to clarify logo deprecation

- packages/sanity/src/core/bundles/util/dummyGetters.ts
When the name -> slug change was added, this was not updated.
> fix(corel): update getAllVersionsOfDocument dummy getter function

- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
- packages/sanity/src/core/releases/tool/useBundlesMetadata.ts
- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/bundles/createBundlesMetadataAggregator.ts
- packages/sanity/src/core/store/bundles/createBundlesStore.ts
> fix(releases): fixing issue loading metadata and controlling aggregator loading state

- packages/sanity/src/core/form/inputs/DateInputs/base/DateTimeInput.tsx
- packages/sanity/src/core/form/inputs/DateInputs/base/calendar/types.ts
- packages/sanity/src/core/form/inputs/DateInputs/utils.ts
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/scheduledPublishing/components/dateInputs/base/DateTimeInput.tsx
Adds missing aria label to the date picker button for accessibility.
> fix(chore): add aria label to datepicker button

- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
> fix: releases default sort order in wrong direction

- packages/sanity/src/core/releases/components/BundleMenuButton/BundleMenuButton.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentActions.tsx
- Add translations when discarding version and deleting releases
- Add toast (and translations) when deletions are successful
- Any mistranslations?
Existing tests should suffice
> refactor(sanity): Add toast when discarding version and for deleting releases

- packages/sanity/src/core/bundles/components/dialog/BundleForm.tsx
Add prop to the bundle form to fix behavior of the date time input
> Remove constraint size publish

- packages/sanity/test/testUtils/TestProvider.tsx
`TestProvider` now also supplies mocked contexts for `Router` and `AddonDataset` to better harness all types of tests
Not currently used in any tests, however benefits can be found when writing tests currently
N/A
> test: improved context mocking on TestProvider

- packages/sanity/src/_internal/cli/commands/build/buildCommand.ts
- packages/sanity/src/_internal/cli/commands/deploy/deployCommand.ts
This adds some additional lines of text to update users about auto-updates in the CLI surface.
@runeb would love a language / style check here!
Don't believe it's necessary?
> chore: add help text for auto-updates in the studio

- dev/test-studio/schema/standard/portableText/simpleBlock.tsx
Made a change as part of #7526 that was intended to be dropped before merging but forgot 
N/A
> chore(form): revert unintended schema change

- pnpm-lock.yaml
> chore(test): move `@sanity/block-tools` to vitest

- packages/sanity/src/core/releases/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/releases/tool/components/Table/TableHeader.tsx
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/store/release/createReleaseMetadataAggregator.ts
> feat(releases): docs in a release display their action (added or changed)

- packages/sanity/src/core/releases/hooks/usePerspective.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/release/reducer.ts
- packages/sanity/src/core/store/release/useReleases.ts
> fix: reducer action to update perspective for stack

- packages/sanity/src/core/releases/__telemetry__/releases.telemetry.ts
- packages/sanity/src/core/releases/components/dialog/ReleaseDetailsDialog.tsx
- packages/sanity/src/core/releases/components/dialog/__tests__/ReleaseDetailsDialog.test.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/releases/tool/components/ReleasePublishAllButton/ReleasePublishAllButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleasePublishAllButton/ReleaseScheduleButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleasePublishAllButton/ReleaseUnscheduleButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardFooter.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseReview.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseSummary.test.tsx
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx
- packages/sanity/src/core/releases/tool/detail/review/DocumentDiffContainer.tsx
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/release/constants.ts
- packages/sanity/src/core/store/release/createReleaseOperationStore.ts
- packages/sanity/src/core/store/release/createReleaseStore.ts
- packages/sanity/src/core/store/release/types.ts
- packages/sanity/src/core/store/release/useReleases.ts
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveList.test.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/contextMenu/__tests__/VersionContextMenu.test.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/contextMenu/__tests__/VersionContextMenuItem.test.tsx
> feat(releases): schedule and unschedule releases

- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleasePublishAllButton/ReleaseScheduleButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentHeaderTitle.test.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveList.test.tsx
> feat(releases): supporting selecting a publish time on scheduled releases

- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/ui-components/inputs/DateFilters/calendar/CalendarDay.tsx
- packages/sanity/src/ui-components/inputs/DateFilters/calendar/CalendarFilter.tsx
- packages/sanity/src/ui-components/inputs/DateFilters/calendar/CalendarMonth.tsx
> feat: calendar filter can be disabled when no releases

- scripts/printReleaseNotesTemplate.ts
Updates the release notes template
N/A
> chore(scripts): reordering blocks in release notes template script

- perf/tests/jest.config.mjs
- perf/tests/package.json
- perf/tests/runner/__tests__/parseDecoratedRefs.test.ts
- perf/tests/vitest.config.mts
- pnpm-lock.yaml
- vitest.workspace.ts
> test(perf): migrate perf runner tests to vitest

- packages/sanity/src/core/config/types.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
> test(core): fix reference e2e test

- packages/@sanity/mutator/package.json
Pin version of `@types/diff-match-patch` to fix build error
> fix(mutator): pin version of @types/diff-match-patch

- packages/sanity/src/core/studio/upsell/upsellDescriptionSerializer/UpsellDescriptionSerializer.tsx
Updates how list items are rendered in the `<UpsellDescriptionSerializer />` 
Reducing the text size and making the text color muted.
| Light | Dark |
| <img width="400" alt="Screenshot 2024-11-11 at 14 16 38" src="https://github.com/user-attachments/assets/1909c082-98cf-4fe0-b103-c8984d1ade06"> | <img width="400" alt="Screenshot 2024-11-11 at 14 16 38" src="https://github.com/user-attachments/assets/2b4f29c1-e079-4ba0-94b5-66804e0db6a7"> | 
No tests added 
n/a
> fix(core): update upsell description list items

- packages/sanity/src/core/releases/__fixtures__/release.fixture.ts
- packages/sanity/src/core/releases/hooks/__tests__/__mocks__/usePerspective.mock.ts
- packages/sanity/src/core/releases/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/releases/store/__tests__/__mocks/useReleaseOperations.mock.ts
- packages/sanity/src/core/releases/store/__tests__/__mocks/useReleases.mock.ts
- packages/sanity/src/core/releases/store/__tests__/__mocks/useReleasesMetadata.mock.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/__tests__/ReleaseMenuButton.test.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/__mocks__/useBundleDocuments.mock.ts
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
> test(releases): calendar tests for releases overview

- package.json
- pnpm-lock.yaml
- scripts/normalizeDependencyVersions.ts
- scripts/utils/getPackagePaths.ts
Just bumping this as it is causing some audit noise.
Supersedes #7567
None
> chore(deps): update dependency glob to ^11.0.0

- packages/sanity/src/core/components/commandList/CommandList.tsx
The `<CommandList>` component underpins heavy duty views like `<DocumentPaneList>`. By splitting out logic required to handle each list item, into a separate, memoized, `<CommandListItem>`, it significantly improves render performance on common interactions like scrolling, and filtering the list.
Is there enough context or are code comments missing?
Existing tests should be sufficient for this PR, although it would be nice with better coverage on the E2E suite, and possibly eFPS suite, for this.
Improved the scrolling performance of document list pane views.
> fix: improve command list performance

- packages/sanity/README.md
Updated socials in README:
- Added Bluesky and YouTube
- Renamed Twitter to X
- Updated URL of newsletter
Ensure the README renders fine.
n/a
n/a
> chore: update social links in readme

- packages/sanity/package.json
- pnpm-lock.yaml
Bumps `@sanity/presentation` to include a host of bugfixes we've made since last time ❤
> chore: bump presentation

- packages/sanity/src/core/releases/__telemetry__/releases.telemetry.ts
Telemetry should be:
> Should be in the form of , e.g. Document Published, Studio Entered, or Trial Started, and be capitalized.
> chore: updating release telemetry to conform to style guides

- packages/sanity/src/core/store/_legacy/history/history/diffValue.ts
As part of `releases` we are using the `diffValue` function and we need it to accept a generic property instead of the previously `Meta` one.
This is only a TS definition change, existing tests should cover this.
n/a
> chore(core): update `diffValue` to accept a generic `Meta` property

- packages/sanity/package.json
- pnpm-lock.yaml
Includes fixes that has happened between v1.19.x and v1.22.x
> fix(deps): upgrade `@sanity/presentation` to v1.22.1-release.0

- test/e2e/tests/inputs/reference.spec.ts
update tests based on the changes done in corel 
some things we were relying on next no longer look or work the same, so the tests have been updated
> test(e2e): update reference tests for corel

- test/e2e/tests/desk/documentList.spec.ts
- test/e2e/tests/inputs/reference.spec.ts
Improve some flaky e2e tests
- DocumentList
- Reference
The reference test probably will need to be touched later (unsure if it will continue being flaky), but I ran out of time 🙏  
N/A
> test(e2e): make e2e sturdier

- dev/embedded-studio/package.json
- dev/test-studio/package.json
- package.json
- packages/@sanity/cli/package.json
- packages/sanity/package.json
- perf/efps/package.json
- pnpm-lock.yaml
- test/e2e/tests/desk/documentList.spec.ts
- test/e2e/tests/inputs/reference.spec.ts
> chore(core): merge `next` into. `corel`

- packages/sanity/src/core/releases/store/createReleaseStore.ts
During development, release documents were initially stored at a different path. To aid the transition to the final path, Bjørge created a neat migration process that invisibly moved the documents.
At this stage, the migration is no longer needed.
Does everything look okay?
Run Studio, make sure releases are still fetched correctly.
> refactor(sanity): remove defunct release migration

- packages/sanity/src/core/releases/hooks/useDocumentVersions.tsx
> feat(sanity): use new name for `sanity::versionsOf`

- packages/@sanity/types/src/reference/types.ts
- packages/sanity/src/core/form/FormBuilderProvider.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/useReferenceInput.tsx
- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/hooks/useConnectionState.ts
- packages/sanity/src/core/hooks/useSyncState.ts
- packages/sanity/src/core/preview/types.ts
- packages/sanity/src/core/preview/utils/getPreviewStateObservable.ts
- packages/sanity/src/core/search/common/types.ts
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItemPreview.tsx
- packages/sanity/src/presentation/overlays/PostMessageDocuments.tsx
- packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusLine.tsx
- packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts
- packages/sanity/src/structure/panes/documentList/useDocumentList.ts
Some miscellaneous changes to apply to the content releases branch before merging it to next.
No behavior changes, just types, functions params updates, renaming etc
Each commit explains the intent
[chore(core): rename bundleIds and bundleStack](https://github.com/sanity-io/sanity/commit/fa9fcf2385ee074f4627d05816e36feebb89cd37)
[fix(core): update sanity ReferenceFilterSearchOptions type](https://github.com/sanity-io/sanity/commit/03312d996f973ec3f3c5c7e90cdc5c038dfcb247)
[fix(core): remove version from formBuilder, it's not used, neither pr…](https://github.com/sanity-io/sanity/commit/1738f1c0ad7bfd48ecc788a66466d352d2044d56) 
[fix(core): update useConnectionState and useSyncState hooks version p…](https://github.com/sanity-io/sanity/commit/566673eb510a94782acea005986707cc0dbedeb9) …
> chore(core): misc fixes to content-releases branch

- packages/sanity/src/core/preview/observeFields.ts
Version documents are hidden in old versions of the api, this forces to use the releases API version when querying for version documents in a preview lists and search 
Check the previews for version documents it should show the version dots if a version document exists. e.g.
fixes an issue in which preview using version documents was not showing the correct versions.
> fix(core): use `vX` for `observeFields` when querying for version docs

- packages/sanity/src/core/components/inputs/DateInputs/DateTimeInput.tsx
- packages/sanity/src/core/releases/components/ScheduleDatePicker.tsx
- packages/sanity/src/core/releases/components/dialog/CreateReleaseDialog.tsx
- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/components/dialog/TitleDescriptionForm.tsx
- packages/sanity/src/core/releases/components/documentHeader/dialog/CopyToNewReleaseDialog.tsx
- packages/sanity/src/core/releases/hooks/useCreateReleaseMetadata.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseScheduleButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseTypePicker.test.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseTime.tsx
| ![timezone1OLD](https://github.com/user-attachments/assets/3b817c50-192f-4151-9cf7-c182d31ac9f1) | ![timezone1NEW](https://github.com/user-attachments/assets/9927c48e-be02-4aab-a99b-80870f05bf8b) |
| ![timezone2OLD](https://github.com/user-attachments/assets/1cf25584-d69d-4c87-9383-09428894eabe) | ![timezone2NEW](https://github.com/user-attachments/assets/5c2ebbdc-545c-41d0-a851-32be174dfd66) |
| ![timzone3OLD](https://github.com/user-attachments/assets/ef9ab1e8-9838-4093-8fde-c926aea8b70b) | ![timezone3NEW](https://github.com/user-attachments/assets/0b803e8d-fc4a-4660-a1a8-48f72b07684d) |
| ![timezone4OLD](https://github.com/user-attachments/assets/184dbb61-bbc7-4c47-b564-0ba0ed6152c8) | ![timezone4NEW](https://github.com/user-attachments/assets/bd …
> fix(releases): timezone fixes in content releases

- packages/sanity/src/core/i18n/bundles/studio.ts
Updates the Create release modal title to **New release**
> chore(core): updates release create modal title

- packages/sanity/src/core/releases/tool/detail/ReleaseDetail.tsx
The `ReleaseView` is a vestige from when we were working with a review and summary screen for the release detail. These are no longer relevant
Regression tests with the existing tests
N/A
> refactor(releases): removing redundant release details view screen conditions

- packages/sanity/src/structure/panes/document/documentPanel/banners/__telemetry__/DraftLiveEditBanner.telemetry.ts
Update name of telemetry event to match with the naming guidelines
Used the name that was brought up by Jon. Should just be right :)
N/A 
Internal
> fix(core): fix resolveLiveEdit name

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleasePreviewCard.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/releaseActions.ts
Updates the archive and delete release dialogs to match the new designs.
| | Before 🚧   | After 💅🏻  |
|--------|--------|--------|
| Archive with docs | <img width="450" alt="Screenshot 2025-02-18 at 16 14 56" src="https://github.com/user-attachments/assets/95cafa00-ca9e-4fd6-8f8e-f6fb734fb31d" /> | <img width="450" alt="Screenshot 2025-02-18 at 16 07 39" src="https://github.com/user-attachments/assets/074ca910-612e-4f20-9a7a-6433e3fa681c" /> |
| Archive, no docs | <img width="450" alt="Screenshot 2025-02-18 at 16 14 50" src="https://github.com/user-attachments/assets/8c76d0a0-094c-487d-aa78-a1a0b210e91b" /> | <img width="450" alt="Screenshot 2025-02-18 at 16 07 47" src="https://github.com/user-attachments/assets/b109f857-2dfd-4ae3-a52c-dfbbdee21f79" /> |
| Delete | <img width="450" …
> fix(core): archive and delete release dialogs revised

- packages/sanity/src/core/releases/store/useReleasePermissions.ts
Update after https://github.com/sanity-io/sanity/pull/8702 landed
Double check that everything works as intended
Existsting tests should suffice 
N/A
> refactor(core): update dependencies array after fix pushed

- dev/test-studio/sanity.config.ts
Removing explicit opt-in for test studio workspaces
N/A
> chore: releases is opt-out; remove explicit opt in for test-studio

- .github/workflows/are-we-compiled-yet.yml
- .github/workflows/efps.yml
- .github/workflows/formatCheck.yml
- .github/workflows/lintPr.yml
Should help reduce pressure on the queue
> chore(ci): auto cancel more jobs on push to next

- .github/workflows/e2e-ct.yml
- .github/workflows/e2e-ui.yml
- .github/workflows/e2e.yml
Reverts sanity-io/sanity#8833.
> chore: end blacksmith trial

- packages/sanity/src/core/releases/store/useDocumentVersionInfo.ts
This fixes a regression in v3.78.0 that made draft+published status indicators not appear unless the dataset had existing releases.
Knowing what releases a document exists in involves subscribing to a stub of each version. Prior to this PR this was done by using something along the lines of
```tsx
versions = combineLatest(
knownReleases.map(releaseId => subscribeToPreviewStub({_id: getVersionId(release, documentId)))
)
```
However, this wouldn't work when no known releases exists, as it would be equivalent with `combineLatest([])`, which never completes. This fixes the issue by checking whether knownReleases is empty, and if so, returning `of({})` instead.
- Test in a dataset without any releases and notice before/after, for example:
- before: …
> fix(releases): fix issue with missing draft/publish status tooltips

- packages/sanity/src/core/i18n/bundles/studio.ts
Fixes an error caused by whitespace inside at tag in a i18n string
- Fixes an error caused by whitespace inside at tag in a i18n string
> fix(i18n): remove whitespace from tag

- packages/sanity/src/core/i18n/bundles/studio.ts
Tiny copy refinement.
The copy change.
> feat(sanity): refine phrasing of `scheduled-for-publishing-on` string

- packages/sanity/src/structure/components/paneHeaderActions/PaneHeaderCreateButton.tsx
| <img width="350" alt="Screenshot 2025-03-13 at 13 53 39" src="https://github.com/user-attachments/assets/f415961a-9655-4141-83ab-55912e3ee3a9" /> | <img width="389" alt="Screenshot 2025-03-13 at 13 53 15" src="https://github.com/user-attachments/assets/2359732e-0ee8-44b2-a79a-97275112e1b3" /> | 
N/A
N/A
> fix: published perspective shows correct tooltip for create buttons

- packages/sanity/src/core/releases/store/__tests__/__mocks/useActiveReleases.mock.ts
- packages/sanity/src/core/releases/store/__tests__/useActiveReleases.test.ts
- packages/sanity/src/core/releases/tool/components/ReleaseDocumentPreview.tsx
- packages/sanity/src/core/releases/tool/components/__tests__/ReleaseDocumentPreview.test.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx
Further testing for releases
Just tests
N/A
> test(core): enhance tests for useActiveReleases and add ReleaseDocumentPreview tests

- packages/sanity/src/core/perspective/navbar/PerspectiveLayerIndicator.tsx
Following the feedback from Marius
| Before    | After |
| <img width="314" alt="image" src="https://github.com/user-attachments/assets/326aa8bd-ee04-484e-a2e8-367ad3dede42" />  | <img width="314" alt="image" src="https://github.com/user-attachments/assets/77ba6451-e78e-47d1-89a7-b846ec39af05" />    |
The chance should speak for itself :) 
N/A
N/A
> refactor(core): updated background for the indicator

- packages/sanity/src/core/releases/tool/components/Table/Table.tsx
- packages/sanity/src/core/releases/tool/components/Table/types.ts
- packages/sanity/src/core/releases/tool/detail/ReleaseDetail.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseName.tsx
https://github.com/user-attachments/assets/8d919234-4e22-413f-9b03-2bb0f2b609c1
Existing tests are fine
N/A
> feat: releases tool tables show skeletons when loading rather than spinner

- packages/sanity/src/presentation/preview/PreviewHeader.tsx
- test/e2e/tests/presentation/presentation.spec.ts
This test helps prevent regressions like #8620 from sneaking back in in the future 🙌 
If tests pass we're good 👍 
N/A
> chore: add presentation e2e test for viewport toggle

- packages/sanity/src/_internal/cli/server/renderDocument.tsx
Fixes an issue where apps would require styled-components dependency even though it didn't need it. From what I can tell this was because the require import cause the esbuild to start importing sanity-ui dependency (screenshot in the ticket). Using an `import` uses a tree-shaken version so it does not load dependencies that are not need. This is what my understanding is but and I tested it locally with that. Let me know if you see other issues
Let me know if this makes sense or if there are any downsides.
`3.80.2-sdk-265.17` - canary release
- `npx sanity@3.80.2-sdk-265.17 init --template app-quickstart` 
- Choose `npm` as package manager
- cd in folder and run `npm run build`, you should get an error
- replace the sanity version in package.json with the canary
- run `npm install` again
- …
> fix(cli): fixes issue where apps required styled-components dependency

- packages/sanity/src/core/form/components/formField/FormFieldValidationStatus.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx
> [!NOTE]
> Approved by Marius
- Update to the tooltip placement to reduce noise in a smaller area and confusion due to the proximity to other things
| before    | after |
| ![image](https://github.com/user-attachments/assets/cc1cb67a-456d-45a0-a8a2-b4c4c37b8812) | ![image](https://github.com/user-attachments/assets/fd2657ef-1ae2-433a-aea9-8461cf4df294)   |
- Update spacing for array items 
| before    | after |
| <img width="693" alt="image" src="https://github.com/user-attachments/assets/1b28ebb9-cca5-4ee3-9903-969984ad3077" /> | <img width="693" alt="image" src="https://github.com/user-attachments/assets/f5ebb8b5-a6b3-44da-8cdd-aab566637427" /> |
Just double check everything looks good
N/A
N/A
> refactor(core): update smaller UI aspects in the Reference Item 

- test/e2e/tests/comments/inline.spec.ts
- test/e2e/tests/desk/inspectDialog.spec.ts
> test: inspect dialog flake

- packages/sanity/src/core/error/sentry/sentryErrorReporter.ts
Fixes a race condition that prevented errors thrown during config init from being reported to Sentry for auto-updating Studios
This is kinda tricky to test. Here's what I did to test locally:
- set `localStorage.DEBUG_ERROR_REPORTING = true` in devtools.
- add `errorReporter.enable()` after this line: https://github.com/sanity-io/sanity/blob/15b5376c527cf86ab79ce2a1775ebbeb8e8aa709/packages/sanity/src/core/studio/StudioProvider.tsx#L65
- add an early `return true` at the beginning of this function: [hasSanityPackageInImportMap](https://github.com/sanity-io/sanity/blob/8ea7d8fe9a60594476621bca1f52368b69a7ee15/packages/sanity/src/core/environment/hasSanityPackageInImportMap.ts#L6)
- Trigger a configuration error, e.g. by uncommenting the string type here: …
> fix(sentry): report errors happening before init

- packages/sanity/src/presentation/useDocumentLocations.ts
When using the `select` option in presentation for the [Document Location Resolvers](https://www.sanity.io/docs/presentation-resolver-api#8d8bca7bfcd7) we were not passing the perspective neither using the release id of the document to listen for it's changes. 
This PR updates this hook to get the changes when using versions, so now the resolver is updated accordingly.
**Future refactor**
Not sure why this is not using the `documentPreviewStore` and it's setting a new listener instead, it would be nice to reuse the observeDocumentPaths function which takes a perspective. The `listenQuery` function doesn't support a perspective for the listener.
Fixes an issue in presentation when using `select` in the resolvers and working on a release document.
> fix(presentation): use perspectiveStack for useDocumentLocations listen

- dev/test-studio/schema/standard/portableText/allTheBellsAndWhistles.ts
> test: add Image slideshow to the first all bells-PTE field

- packages/@sanity/cli/templates/app-quickstart/src/App.tsx
- packages/@sanity/cli/templates/app-quickstart/src/ExampleComponent.tsx
- packages/@sanity/cli/templates/app-sanity-ui/src/App.tsx
Updates the SDK app templates for new SDK signatures (primarily, the `sanityConfigs` prop -> `config`, plus example code).
Sneaks in a tiny fix for the Sanity UI template as well.
It's a doozy, watch out!
N/A
None, internal
> feat(cli): Update SDK app templates for new signatures

- packages/sanity/src/core/studio/workspaceLoader/WorkspaceRouterProvider.test.tsx
> fix(core): restores onUncaughtError test

- .release-please-manifest.json
Adds the required release-please manifest as a follow up to #9228 .
n/a
> chore(ci): add release-please manifest

- packages/@sanity/cli/templates/app-sanity-ui/src/App.tsx
Swapped the order of `ThemeProvider` and `SanityApp` components in the App component to ensure the theme is applied correctly throughout the application. The `ThemeProvider` now wraps the `SanityApp` component instead of the other way around.
- Check that the theme is properly applied to all components within the application
- Verify that the application still renders correctly with this new component hierarchy
- Ensure that no styling issues are introduced by this change
Tested by running the application locally and verifying that all UI components render with the correct theme styles. The theme context is now properly available to all components within the application, including those rendered by SanityApp.
N/A
> fix(cli): fixes app template for sanity ui

- packages/@sanity/cli/src/actions/init-project/initProject.ts
This PR improves the organization selection flow when initializing a project with an app template. It:
1. Adds query parameters to the organizations API request to include members and implicit memberships
2. Creates a dedicated `getOrganizationIdForAppTemplate` function separate from the general `getOrganizationId` function
3. Implements smarter default organization selection logic that prioritizes:
- The only organization if the user has just one
- The organization matching the user's name if available
- The new query parameters added to the organizations API request
- The implementation of the `getOrganizationIdForAppTemplate` function
- The default organization selection logic
Tested the changes manually but adding this to current unit tests will be complicated especially with mocking …
> fix(cli): allow selecting orgs with implicit membership for new apps

- packages/@sanity/cli/src/actions/init-project/initProject.ts
If a user was part of an organization they only had implicit permissions to (for example, they were a member of project in the org but not a member of the org itself), running `sanity init` would fail if you tried to create a new project.
Since all project now need to be attached to an organization, the `initProject` process would loop through all organizations you had membership to, even if it was "implicit" membership (e.g., you have access to a project in that org but may not be a member of the org itself).
However, the grants check from a user in such a position to these organizations would result in a 401, halting the init process.
Are there any other places in this code where we might face the same issue?
The CLI will be tested... soon!
Fixes an error where creating a new project …
> fix(cli): recover from 401s in org grant checks during init

- packages/@sanity/cli/src/actions/init-project/templates/appQuickstart.ts
- packages/@sanity/cli/src/actions/init-project/templates/appSanityUi.ts
Updates SDK packages in templates to the (unreleased) 1.0.0 version. When it's released we can update Studio as well.
Is this it?
Not possible to test right now.
None, internal.
> chore(cli): update templates to sdk 1.0.0

- .circleci/config.yml
> chore(ci): use large resource class for job

- packages/@sanity/cli/templates/app-sanity-ui/src/ExampleComponent.tsx
Updates the URL for the App SDK docs in the Sanity UI app template
Is the URL correct? (It is!)
N/A
None, internal
> fix(cli): update App SDK reference docs URL

- packages/@sanity/cli/src/commands/blueprints/destroyBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/stacksBlueprintsCommand.ts
correct commands listed in `sanity blueprints --help`
> fix(cli): blueprints commands help entries

- packages/@sanity/cli/src/actions/init-project/initProject.ts
Updated the output of "Would you like to join our community?" question to display discord link
Formatting
Not sure best practice for testing this
> chore: Update community invite to discord

- packages/sanity/README.md
Readme has new Monogram logo; updated community links to Discord
N/A
> docs: updating readme logo and discord links for community

- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/shared/MediaLibraryAssetSource.tsx
Adds tags to API queries done by the Media Library Asset Source plugin.
N/A
> fix(core): add tags to Media Library requests

- packages/sanity/src/core/form/inputs/files/common/UploadPlaceholder.tsx
Update client api version to remove the console warnings from the Upload component
N/A
> refactor(core): updated client api version

- perf/efps/README.md
- perf/efps/index.ts
Smol internal tooling quality of life docs addition.
> chore(efps): add debug info

- packages/@sanity/cli/package.json
- pnpm-lock.yaml
update `@sanity/runtime-cli`
Just a package bump. I put all commands through their paces locally.
Existing tests passing
`blueprints` and `functions` stability improvements. no breaking changes
> chore(cli): update runtime-cli

- dev/studio-e2e-testing/README.md
- examples/clean-studio/README.md
- packages/@sanity/cli/templates/blog/README.md
- packages/@sanity/cli/templates/clean/README.md
- packages/@sanity/cli/templates/ecommerce/README.md
- packages/@sanity/cli/templates/get-started/README.md
- packages/@sanity/cli/templates/moviedb/README.md
- packages/@sanity/cli/templates/quickstart/README.md
- packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceAuth/Layout.tsx
Updates outdated url for joining community
> fix: update link to join community

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/commands/blueprints/addBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/initBlueprintsCommand.ts
- pnpm-lock.yaml
related PR in `runtime-cli` is no. 145
https://github.com/user-attachments/assets/232b51e3-bfd2-475a-960e-03ee0a057c91
> feat(cli): update runtime-cli and enable example flag

- package.json
- pnpm-lock.yaml
No longer needed now that https://github.com/conventional-changelog/conventional-changelog/issues/1381 has been fixed
n/a
> fix(ci): remove @conventional-changelog/git-client version override

- packages/sanity/src/structure/panes/document/documentPanel/header/hook/useChipScrollPosition.tsx
Due to a race condition sometimes made it that the "lastChip" that it found was actually the draft because the version documents hadn't ifnished being fetched. What that meant was that, especially if you were already in a version chip that is scrolled, it was showing the gradient when it shouldn't (because it is tracking the intersection with Draft)
Now we're using an observable also to make sure that if the container (the parent) is mutated, that we change the lastChip as needed
See video:
https://github.com/user-attachments/assets/146455b4-6e7a-4028-96c3-107cd8a68a23
And after fix:
https://github.com/user-attachments/assets/61d97054-8c24-48cb-b84d-1be26e5051cc
What's on the tin :)
Existing should be enough
**(I don't think it needs to be mentioned)**
Fix issue with release chips in the …
> fix(structure): fix issue where the versions were being slowly loaded and so the last chip was the wrong one giving us the wrong element

- dev/page-building-studio/.depcheckrc.json
- dev/page-building-studio/sanity.cli.ts
Just to enable perf profiling 🙌
> chore: enable profiling of page building studio

- packages/@sanity/cli/package.json
- pnpm-lock.yaml
Updating the `@sanity/runtime-cli` package to 9.0.0
see package.json
Added numerous tests in `@sanity/runtime-cli` 
In conversation with docs team on this change.
> fix: Update runtime-cli dependency

- .github/workflows/create-release-pr.yml
- .github/workflows/e2e-ct.yml
- .github/workflows/e2e-ui.yml
- .github/workflows/e2e.yml
- .github/workflows/efps.yml
- .github/workflows/perf.yml
- .github/workflows/pkg-pr-new.yml
- .github/workflows/release-latest.yml
- .github/workflows/release-next.yml
- dev/test-create-integration-studio/package.json
- package.json
- perf/efps/index.ts
- test/e2e/scripts/cleanup.ts
The dev engine requirement change is breaking the [release actions ](https://github.com/sanity-io/sanity/actions/runs/15997308565) .
Reverting this so we can get the release out and we will come back to this and fix the underlying issue. 
Are the changes ok?
> fix(core): reverts dev engine requirement

- .github/workflows/release-latest.yml
Increase lerna logs for debug; run one lerna process at once for logging
N/A
> chore: increase lerna release log level

- .github/workflows/release-next.yml
> chore: debugging next release with provenance off

- .github/workflows/release-next.yml
Generated semver version with provenance, tagged to next
N/A
> fix: lerna provenance publishing for next

- .github/workflows/release-latest.yml
* Malformed yaml for git tag and push - meant that git tagging did not complete on latest release
* Typo
N/A
> fix: correcting yaml syntax to git tag on publish

- examples/README.md
- examples/functions/algolia-document-sync/README.md
- examples/functions/auto-summary/README.md
- examples/functions/auto-tag/README.md
- examples/functions/brand-voice-validator/README.md
- examples/functions/capture-tone-of-voice/README.md
- examples/functions/first-published/README.md
- examples/functions/slack-notify/README.md
Updates the instructions for how to create/init blueprints and functions
> chore(examples): update instructions

- packages/@sanity/migrate/src/fetch-utils/__test__/sanityRequestOptions.test.ts
> chore: fix migrate test hardcoding v3

- examples/functions/algolia-document-sync/README.md
- examples/functions/algolia-document-sync/index.ts
- examples/functions/algolia-document-sync/package.json
I ran through this example and found a few things that may make help things run smoother.
Everything I've changed can be considered a suggestion and feel free to follow up with me if it's not clear.
Created a new functions project and added algolia function to it.
n/a
> fix: feedback on algolia example

- examples/functions/algolia-document-sync/README.md
- examples/functions/auto-summary/README.md
- examples/functions/auto-summary/package.json
- examples/functions/auto-tag/README.md
- examples/functions/auto-tag/package.json
- examples/functions/brand-voice-validator/README.md
- examples/functions/brand-voice-validator/package.json
- examples/functions/capture-tone-of-voice/README.md
- examples/functions/capture-tone-of-voice/package.json
- examples/functions/first-published/README.md
- examples/functions/first-published/package.json
- examples/functions/slack-notify/README.md
- examples/functions/slack-notify/package.json
- examples/package.json
This PR is pretty repetitive and does three things:
1. Updates the functions dependency to 1.0.3 or later for all examples.
2. Fixes some typos
3. Removes the step where you cd into the functions directory to install dependencies. This is now redundant, dev/test/deploy will do that for you.
see description
I'd be lying if I said I did.
n/a
> chore(examples): update function examples

- .github/workflows/create-release-pr.yml
> chore: remove auto-merge in release PR

- .github/workflows/release-stable.yml
> chore: update release workflow to include version in run name

- packages/@sanity/cli/src/commands/functions/testFunctionsCommand.ts
Updating help docs for functions cli command "test"
Trust me, it makes more sense now.
n/a
n/a
> fix(functions): update help docs

- .github/workflows/create-release-pr.yml
> chore: tidy release template description

- .github/workflows/release-latest.yml
Enables latest tagging as part of release flow in production manifest.
n/a
> fix(ci): tag latest in production manifest

- .github/workflows/generate-dts-tests-if-needed.yml
- .github/workflows/lint-fix-if-needed.yml
- .github/workflows/pnpm-if-needed.yml
- .github/workflows/react-compiler.yml
I'd rather not talk about it 🤦
> chore(ci): fix automerge

- packages/sanity/src/_internal/cli/actions/app/devAction.ts
> fix(cli): updates dev action to trigger async work while showing spinner

- packages/sanity/src/structure/documentActions/PublishAction.tsx
Currently, when the user hits the publish action, we track pending state by setting local state to "publishing" and we only clear this after we detect that the draft has been deleted. However, in case of eg. an intermittent connection loss and a new draft being recreated immediately after publish, this could lead to infinite "publishing"-state being reported by the action. This fixed the issue by tracking the revision of the draft at the time of publish, and then clear the pending state when we that the draft is either deleted or has a different revision than it had when the user hit publish.
We should have existing tests covering regressions. Without a reliable repro its hard to say for certain that the issue will no longer happen after this.
- Fixes an issue that in …
> fix(sanity): clear 'publishing' state when published revision change

- packages/sanity/src/core/store/_legacy/document/utils/__test__/sequentializeEvents.test.ts
- packages/sanity/src/core/store/_legacy/document/utils/sequentializeListenerEvents.ts
Found a bug with our gap detection causing the deadline to be reset in cases where mutation events kept coming in. This could lead to cases where gap detection would take longer to trigger than intended, e.g. if a steady stream of mutation events come in at an intervall less than the current gap detection deadline of 30s, eg. worst case, if a broken chain is detected and a new mutation event comes in right before the 30s mark, the current deadline timer would be stopped and a new one scheduled. Worst case, if you've got a broken chain, and events keeps coming in right before the deadline timer expires, you could go on for closer to 10 minutes, eg:
- gap is detected, deadline timer scheduled to expire in 30s
- 29.9s passes, mutation event comes in, current deadline timer is stopped, a new …
> fix(core): preserve desync deadline when new mutation events arrive

- packages/sanity/src/core/store/_legacy/document/utils/sequentializeListenerEvents.ts
Two small dev improvements:
- Adds debug logging
- Renames a variable for improved clarity
> refactor(core): rename applicableChains to resolvedChains and add debug logging

- packages/sanity/src/core/releases/tool/detail/documentTable/useReleaseHistory.ts
A few final refactors and upgrades to the useReleaseHistory
Made at the suggestion of Pedro to do one last improvement to the history logic
Does this make sense? I tested it and everything looks as it should when navigating the studio and releases.
N/A
Tests already exist for the getTransactionsLogs, existing tests should suffice
> refactor: change useReleaseHistory to use getTransactionsLogs and limit to 1 and reverse to true

- .npmrc
- package.json
- packages/sanity/package.json
- pnpm-lock.yaml
Hopefully this fixes the vercel build issues we've been seeing
> chore(deps): fix vercel builds by bumping `@sanity/pkg-utils`

- package.json
- packages/@repo/eslint-config/package.json
- pnpm-lock.yaml
Pin oxlint version to avoid surprises when needing to run pnpm install 
Did I miss something?
N/A
> chore: pint oxlint version

- dev/efps/index.ts
- dev/efps/package.json
- package.json
Add build command to efps folder
> chore: add build to dev/efps

- packages/sanity/src/core/store/_legacy/project/projectStore.ts
Looks like the refcount added in #10770 had the unindended side effect of spawning a bunch of requests initially. Likely because of rapidly changing useEffect deps on first load, causing the observable to be unsubscribed and then immediately resubscribed a handful of times. This fixes the issue by postponing the actual teardown of the observable until a second has passed after the last subscriber unsubscribed.
Makes sense?
Go to the [preview build](https://test-studio-git-sapp-3129-delay-teardown.sanity.dev/ ) and observe that only one request to get org id is performed
n/a – already covered by #10770
> fix: delay teardown of get-org-id request

- .github/workflows/efps.yml
> fix: fix issue related to the efps stuff
