sanity-io/sanity

packages/@sanity/block-tools/src/HtmlDeserializer/helpers.ts, packages/@sanity/block-tools/src/HtmlDeserializer/rules/html.ts, packages/@sanity/block-tools/src/types.ts
This will make sure that HTML is not deserialized to list blocks where there is no such support in the given schema.
That pasting HTML lists into Portable Text will not produce any list blocks with the current schema:
```
{
type: 'block',
lists: [],
}
```
* Fixed a bug where pasting HTML lists into the Portable Text Input would disregard schema configuration for list blocks.
=> fix(block-tools): enforce list support in schema

packages/sanity/src/desk/comments/src/components/list/CommentThreadLayout.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInputInner.tsx
This PR adds a max-height (20% of current viewport height) to comment inputs to better handle long text / overflow scenarios. 
It also optically aligns thread titles with the document inspector title.
Try create comments with massive amounts of text – comment footer actions should still be accessible in these scenarios and/or when on smaller viewports (at both the field and inspector level).
=> fix(comments): handle text overflow in editable surfaces, optically align field titles

package.json, packages/sanity/src/core/i18n/debug.ts, packages/sanity/src/core/i18n/hooks/useTranslation.ts, packages/sanity/src/core/i18n/i18nConfig.ts
Adds a flag based on the `SANITY_STUDIO_DEBUG_I18N` environment variable, which enables the debug mode in `i18next`, as well as adding "markers" (◤ this is translated ◢) around anything translated by the `t` function. I think this is what you meant, @jtpetty ?
We can (probably) remove this before this goes live, but helpful for spotting parts that are not yet localized.
Example:
The user menu options are translated, but the locale names are not (they shouldn't be, I guess).
You can also see the tooltip on the configuration issues button is not localized (this one we said we would wait with, but proves the concept of spotting unlocalized areas)
=> feat(i18n): add environment variable flag for debugging i18n

.eslintrc.cjs, package.json, yarn.lock
This PR adds an [eslint rule](https://github.com/edvardchen/eslint-plugin-i18next) for preventing string literals in javascript file
=> chore(i18n): add the i18next/no-literal-string eslint rule

packages/sanity/src/core/form/inputs/index.ts, packages/sanity/src/core/store/_legacy/authStore/createLoginComponent.tsx, packages/sanity/src/core/store/_legacy/authStore/providerLogos.tsx
Fixes an issue where custom logo would not show up on custom auth providers unless the name of the provider was `custom` and even in that case it would throw an error since the provider prop was not passed to the component.
Change makes sense
- Fixes an issue where logo is not shown on custom auth providers
=> fix(login): fix issue where logo is not shown on custom auth providers

packages/sanity/src/core/studio/components/navbar/resources/helper-functions/helpResources.ts
Passes the `locale` parameter to the `/help` endpoint, in order to (at some point) be able to localize the responses.
=> refactor(i18n): pass locale to help/versions check

dev/test-studio/plugins/locale-no-nb/bundles/studio.ts, packages/sanity/src/core/form/inputs/DateInputs/__tests__/CommonDateTimeInput.test.tsx, packages/sanity/src/core/form/inputs/DateInputs/base/calendar/Calendar.tsx, packages/sanity/src/core/form/inputs/DateInputs/base/calendar/types.ts, packages/sanity/src/core/form/inputs/DateInputs/utils.ts, packages/sanity/src/core/i18n/bundles/studio.ts
Found a few inconsistencies and missing translations for the calendar:
- "Go to next month" was not localized (_previous_ was)
- "Select minute" was not localized (_hour_ was)
- As these labels are used for aria-labels, I think they should read "Go to next month" instead of just "Next month", but I may be wrong. Please advice (or commit a change directly to this branch). Similarily, I am wondering if these perhaps should be suffixed with a `-aria-label` for consistency - but as they are under an `action` prefix I wasn't sure. Opinions welcome.
=> fix(i18n): add missing calendar labels

.github/workflows/e2e.yml, .gitignore, playwright.config.ts
This PR enables e2e tests to run in shards as well as takes the report from each shard and merges into one final html report. See it [here](https://github.com/sanity-io/sanity/actions/runs/6563629567?pr=5006)
- chromium (1, 2)
- chromium (2,2)
- firefox (1, 2)
- firefox(2, 2)
This should reduce the CPU constraint per shard 
Fixes SDX-787
- N/A
=> chore(e2e): Run e2e tests in shards

packages/@sanity/cli/test/shared/globalSetup.ts, scripts/symlinkDependencies.js
#4917 adds styled-components@6.1 as default to newly created Sanity Studios. The CLI tests are currently installing dependencies first, before symlinking in the local dependencies, but this now fails because the current `@sanity/cli` from npm doesn't have `styled-components@6` in it's accepted peer-dependency range. This addresses the issue (and future similar issues) by symlinking the local dependencies before running npm install.
Note: We might want to consider looking into replacing this with installing from local tarballs of the local packages instead (potentially via something like [yalc](https://github.com/wclr/yalc)), to make sure dependencies are installed in a way that is more like a "real-life" npm install, but this seems to work fine for now.
N/A – internal
=> test(cli): symlinkDependencies before running `npm install`

packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/gdocs.ts, packages/@sanity/block-tools/src/HtmlDeserializer/rules/gdocs.ts, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocs/index.ts, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocs/input.html, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocs/output.json
This will fix an issue on Windows when serializing a Google Docs HTML fragment into blocks.
The clipboard HTML was slightly different on Windows and our code didn't take that into account.
I have made some xpath matchers more specific and resilient now so they work both places. 
I have also added tests for this.
That pasting from Google Docs into the PTE on Windows and MacOS will work correctly, without adding everything as bold.
* Fix an issue where pasting from Google Docs into the Portable Text editor would make everything 'bold' on Windows computers.
=> fix(block-tools): fix Google Docs preprocessing issue on Windows

packages/sanity/playwright-ct/tests/formBuilder/ArrayInputStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/AnnotationsStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/DecoratorsStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/FocusTracking.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/FocusTrackingStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/InputStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ObjectBlockStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/StylesStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ToolbarStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/utils/TestForm.tsx, packages/sanity/playwright-ct/tests/formBuilder/utils/TestWrapper.tsx, packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx, packages/sanity/src/core/form/inputs/PortableText/Editor.tsx, packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/inputs/PortableText/hooks/useTrackFocusPath.tsx
* Track editor focus for a focusPath that points to a span's text property.
* Harden test for span text by testing that the _type property is actually a 'span' too.
I found and issue where inline blocks having a .text property also triggered editor focus here, which they shouldn't.
* Only focus the editor if focusPath is actually pointing to a editor focusable node.
* Improve test for `hasFocus` variable used in the PT-input (also test that the opened member is a editor node).
* Added component test for this
* That the Portable Text Input will correctly track focus paths that terminate with a span's `text` property.
* That the Portable Text Input will not take focus if you have an inline object containing a root `.text` property.
* Fixed a bug where the Portable Text Input would capture …
=> fix(form/inputs): Track focusPath for a span's .text prop + harden test condition

packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Annotations.spec.tsx, packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx, packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx
This will fix an issue with the annotation toolbar popover's visibility in the PT-input.
* It should never show when the annotation object is open (this was not the case when an annotation was created)
* It should show again when closing the annotation object editing popover
Added tests for this.
Also fixed an issue where the toolbar would not scroll with the content when visible.
The annotation toolbar is showing and hiding correctly when creating and editing annotations in the PT-input.
* Fixed minor issues with annotation toolbar popover not displaying correctly in some situations.
=> fix(core/inputs): fix issue with toolbar popover visibility toggling

packages/sanity/src/core/form/types/definitionExtensions.ts
This will add some TS-doc with examples to the block component extension.
That it's correctly written and makes sense.
N/A
=> doc(form): add doc and example for components extention of block type

packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/@sanity/portable-text-editor/src/types/editor.ts
This will allow the consumer to specify their own `onKeyDown`, `onFocus`, and `onBlur` event handlers on the `Editable` component of the PTE in addition to the internal ones.
Also fixed a prop typing (`onBeforeInput`) that was problematic to use.
That the code looks alright.
N/A
=> fix(portable-text-editor): allow user event handlers on Editable component

.github/workflows/e2e.yml
This PR fixes the playwright report to include all versions of the shards based on browsers.
- N/A
=> chore(e2e): fix report merging

packages/@sanity/mutator/src/patch/parse.ts, packages/@sanity/mutator/test/patch.test.ts, packages/@sanity/mutator/test/patchExamples/mixed.ts
Fixes an issue where the order of operations of set/setIfMissing is reversed from what Content Lake does. By applying `setIfMissing` first, it ensures we can "prepare" structures that a deep `set` operation might use, for instance.
- Mutations still work and apply as before
- Fixes an issue where certain patches would apply differently in the studio and in Content Lake, leading to the studio UI not reflecting new values for certain fields
=> fix(mutator): apply `setIfMissing` prior to `set`

packages/sanity/src/core/changeIndicators/__workshop__/.eslintrc, packages/sanity/src/core/components/collapseMenu/__workshop__/.eslintrc, packages/sanity/src/core/components/commandList/__tests__/.eslintrc, packages/sanity/src/core/components/commandList/__workshop__/.eslintrc, packages/sanity/src/core/components/image/__workshop__/.eslintrc, packages/sanity/src/core/components/previewCard/__workshop__/.eslintrc, packages/sanity/src/core/components/previews/__workshop__/.eslintrc, packages/sanity/src/core/components/rovingFocus/__workshop__/.eslintrc, packages/sanity/src/core/components/textWithTone/__workshop__/.eslintrc, packages/sanity/src/core/components/userAvatar/__workshop__/.eslintrc, packages/sanity/src/core/field/__workshop__/.eslintrc, packages/sanity/src/core/form/__workshop__/.eslintrc, packages/sanity/src/core/form/components/formField/__workshop__/.eslintrc, packages/sanity/src/core/form/inputs/PortableText/__workshop__/.eslintrc, packages/sanity/src/core/form/inputs/PortableText/_legacyDefaultParts/__tests__/.eslintrc, packages/sanity/src/core/form/inputs/__workshop__/.eslintrc, packages/sanity/src/core/form/inputs/files/__workshop__/.eslintrc, packages/sanity/src/core/preview/__workshop__/.eslintrc, packages/sanity/src/core/schema/__workshop__/.eslintrc, packages/sanity/src/core/store/_legacy/__workshop__/.eslintrc, packages/sanity/src/core/studio/components/navbar/__workshop__/.eslintrc, packages/sanity/src/core/studio/components/navbar/search/__workshop__/.eslintrc, packages/sanity/src/desk/__workshop__/.eslintrc, packages/sanity/src/desk/components/pane/__workshop__/.eslintrc, packages/sanity/src/desk/panes/document/statusBar/__workshop__/.eslintrc, packages/sanity/src/desk/panes/document/timeline/__workshop__/.eslintrc
Since we are not translating files in `__workshop__` directories, this PR disables the `no-literal-string` rule for these directories.
=> chore(i18n): add no-literal-string lint exceptions for __workshop__ dirs

packages/sanity/playwright-ct/tests/comments/CommentInput.spec.tsx, packages/sanity/playwright-ct/tests/comments/CommentInputStory.tsx, packages/sanity/src/desk/comments/plugin/field/CommentFieldButton.tsx, packages/sanity/src/desk/comments/src/components/list/CommentsListItem.tsx, packages/sanity/src/desk/comments/src/components/list/CommentsListItemLayout.tsx, packages/sanity/src/desk/comments/src/components/list/CreateNewThreadInput.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInput.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInputInner.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInputProvider.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/Editable.tsx
* Enter will submit the comment
* Input field is reset after submission or discard
* Setting focus is handled through the same function everywhere.
* Input key events are propagated to the parent components
Also made a performance optimization making sure the thread isn't re-rendered whenever there is a new value in the `CommenListItem` input.
Also added a test for comment submission.
=> refactor(comments): refactor how input and focus is handled

packages/@sanity/portable-text-editor/package.json, packages/@sanity/portable-text-editor/src/editor/components/Synchronizer.tsx, yarn.lock
Speed up the PTE collaboration tests considerably. They seem to run much better on the CI now.
This is a follow up to https://github.com/sanity-io/sanity/pull/5069
=> Chore/jest 28 migration rebase (speedup tests)

packages/@sanity/mutator/src/patch/Patcher.ts, packages/@sanity/mutator/src/patch/SetIfMissingPatch.ts, packages/@sanity/mutator/src/patch/SetPatch.ts, packages/@sanity/mutator/test/patchExamples/set.ts, packages/@sanity/mutator/test/patchExamples/setIfMissing.ts
There seems to be a few mismatches between `@sanity/mutator` and Content Lake:
- In Content Lake, a `set`/`setIfMissing`-patch targeting a deep key with missing parents will recursively create an object structure for it
- In `@sanity/mutator`, it will stop once it encounters a key that is not present in the document.
This PR attempts to align the behavior with what Content Lake does. Please review carefully - my knowledge of the mutator is limited and there may be (edge) cases I have not considered.
Fixes SDX-772.
Edit: I see that arrays also gets overwritten in a similar vein as primitives, but I am not quite sure yet how to resolve it.
- Mutations work as expected
- Fixed an issue where certain remote patches would not cleanly apply in the studio, requiring a reload of the document in …
=> fix(mutator): match deep set/setIfMissing behavior

packages/@sanity/mutator/src/jsonpath/tokenize.ts, packages/@sanity/mutator/test/parse.test.ts, packages/@sanity/mutator/test/patchExamples/set.ts
Using the `>=` or `<=` attributes in JSONMatch filters would crash the mutator. The tokenizer found a `>` or `<` and consumed it as a token, yielding a lone `=`, which is not a valid token. Fixed by altering the order that the JSONMatch symbols are consumed in, so that longer ones are consumed first.
Fixes #2474
- JSONMatch patches gets correctly applied
- Fixed an issue where using `>=` or `<=` in JSONMatch filters for patch operations would cause the studio to give error messages and not apply patch correctly
=> fix(mutator): restore greater than/less than in jsonmatch constraints

packages/sanity/src/core/changeIndicators/ChangeIndicator.tsx, packages/sanity/src/core/changeIndicators/ElementWithChangeBar.styled.tsx, packages/sanity/src/core/changeIndicators/ElementWithChangeBar.tsx, packages/sanity/src/core/changeIndicators/__workshop__/ChangeBarStory.tsx, packages/sanity/src/core/field/diff/components/DiffTooltip.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceLinkCard.tsx, packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.styled.tsx, packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.tsx, packages/sanity/src/desk/panes/document/documentPanel/header/DocumentHeaderTabs.tsx
This PR migrates a number of styled components to now use [transient props](https://styled-components.com/docs/api#transient-props), and remove a number of warnings that were shown in localhost as a result of upgrading to styled-components to `6.x`.
A fully exhaustive audit wasn't conducted, but this should address most of the more common / egregious examples.
Touched components should be unaffected in function or style. We should no longer see a glut of transient prop related warnings in localhost.
N/A
=> refactor: use transient props in various styled components

.github/workflows/test.yml
Noticed that when running the action second time incase of a flaky test failure the cache key is missed since it only runs failed builds, like [here](https://github.com/sanity-io/sanity/actions/runs/6709153887/job/18232817737) this removes the `run_attempt` from the key so that the key is same for workflow run and since we are deleting the cache after the workflow successfully runs it should be okay to use just the workflow_id across multiple runs and commits
- Changes makes sense.
- N/A
=> chore(test): fixes cache key so it can be re-ran successfully without error

packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withEditableAPIDelete.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts
This will fix bugs related to deleting content in the PTE through the `PortableTextEditor.delete` function.
* Test that the range produced from the `PortableTextEditor.delete` method is valid before deleting anything. There was an issue where if you gave it an invalid path, the resulting path for the produced range would be `[]` which would then delete content not targeted for deletion.
* If you deleted block by block with this method until there were no blocks left, it would not properly produce a new placeholder block causing issues with inserting new content.
* While writing tests for this I discovered some additional bugs with the `block` mode when providing a selection containing multiple blocks.
Code looks good
* N/A
=> fix(portable-text-editor): fix issues for .delete fn and add tests

.github/workflows/e2e.yml, .github/workflows/pr-cleanup.yml
Learning from sharding issues in test CI discovered some parallelization dataset creation causing failure in the e2e tests. This PR updates the e2e CI setup to mimic the test CI setup where the install and build step is moved out of the shards into their own step. It now creates datasets per project and PR like so
```
- pr-chromium-5098
- pr-firefox-5098
```
It also updates the cleanup action to delete the proper datasets and finally adds the same caching treatment as test action setup with proper keys and deleting the cache after the workflow run completes.
All the changes make sense
N/A
=> chore(e2e): refactor e2e ci to not fail due to parallelization of runs

packages/@sanity/vision/src/apiVersions.ts
Adds `v2022-03-07` to the list of known API versions. It is the lowest version required to use cross-dataset references, and is explicitly called out in documentation.
- API version appears, is choosable, and can be used to query cross-dataset references
- Adds `v2022-03-07` to predefined list of API versions in the Vision tool
=> feat(vision): add v2022-03-07 to list of API versions

packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.tsx
This will fix an issue with the wrong path being sent to the PTE inside the block component's `onRemove` function. It should be the relative path, not the form builder path.
Also,  `.focus` can now be called without a `setTimeout` here.
I have already tested this with a custom component, but if you want to test it yourself, you can use this schema:
```
{
name: 'foo',
title: 'Foo',
type: 'array',
of: [
defineArrayMember({
type: 'block',
components: {
block: (blockProps) => {
return (
<Flex>
<Box flex={1}>{blockProps.renderDefault(blockProps)}</Box>
<Box contentEditable={false} style={{userSelect: 'none'}}>
<Button
icon={TrashIcon}
onClick={(event) => {
event.preventDefault()
blockProps.onRemove()
}}
/>
</Box>
</Flex>
)
},
},
}),
],
},
```
N/A
=> fix(form/inputs): fix invalid path used with onRemove for TextBlock

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceLinkCard.tsx
Fixes #5105
#5093 introduced a regression where references can no longer be opened in-place.
This is caused by removing the `documentId` from [being passed to the state link](https://github.com/sanity-io/sanity/pull/5093/files#diff-f08509f8474b2f3f1c0301d9ca9693b77fa019a86d6ece6c45013ba55f5f7a77).
This revert _this_ change, but reintroduces warnings about passing it to DOM elements, so it is not a perfect solution. I struggled to figure out what is actually being passed to what here - a lot of `as`/`data-as`/Card/StyledCard magic and layers of abstraction, so I would appreciate if either of you had time to fix this properly and push to this branch.
This warrants a hotfix release once addressed.
- That it fixes the problem
- What the proper solution is
- Fixed an issue where references …
=> fix(core): reference links not opening correct pane

dev/test-studio/schema/debug/comments.ts, packages/sanity/src/desk/comments/src/__tests__/buildCommentBreadcrumbs.test.ts, packages/sanity/src/desk/comments/src/components/list/CommentThreadLayout.tsx, packages/sanity/src/desk/comments/src/utils/buildCommentBreadcrumbs.ts
This pull request fixes:
- Issue with adding comments to anonymous objects
- Issue with the breadcrumbs in comments where text overflow ellipsis wasn't handled correctly.
- Make sure that you can add comments to anonymous objects
- Make sure that the breadcrumbs handles text overflow ellipsis correctly
=> fix(desk): comments on anonymous objects 

packages/@sanity/portable-text-editor/src/editor/hooks/useSyncValue.ts, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withEditableAPIInsert.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithPortableTextMarkModel.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithSchemaTypes.ts, packages/@sanity/portable-text-editor/src/editor/plugins/index.ts, packages/@sanity/portable-text-editor/src/utils/__tests__/patchToOperations.test.ts, packages/@sanity/portable-text-editor/src/utils/__tests__/values.test.ts, packages/@sanity/portable-text-editor/src/utils/values.ts
This will improve and fix a couple of things with the PTE:
* Simplify the key name used for the "virtual" text node of inline objects and object blocks in the state for easier tests and value comparisons. This key doesn't need to be unique and can be put in a constant. This will fix an issue where the external value would need to be synced after inserting inline objects when it really isn't needed.
* When normalizing a Slate node that haven't been assigned the span type, generate a key and spread the existing node data (possibly .marks) in the normalization step. This will save us other normalization steps (`._key` normalization, and `.marks` normalization) down the line.
* Fix an issue with the `PortableTextEditor.insertChild`  function, where if you inserted a new span child when having …
=> fix(portable-text-editor): fix various

dev/test-studio/components/TranslateExample.tsx, dev/test-studio/locales/index.ts, packages/sanity/src/core/i18n/Translate.tsx, packages/sanity/src/core/i18n/__tests__/Translate.test.tsx, packages/sanity/src/core/i18n/__tests__/simpleParser.test.ts, packages/sanity/src/core/i18n/simpleParser.ts
It's a bit tedious to pass in components like `<Code>` that just maps to `<code>`. This PR allows using this predefined list of tags without specifying it directly: `<abbr>`, `<address>`, `<cite>`, `<code>`, `<del>`, `<em>`, `<ins>`, `<kbd>`, `<q>`, `<samp>`, `<strong>`, `<sub>`, `<sup>`.
The reason for these specifically is that they are inline elements that do not require any attributes for use, and is not deprecated by the HTML5 spec.
I'm not sure if my solution in the parser was the best, but I didn't want to spend more time finding a more elegant way to approach it - open to suggestions.
- Using simple tags with the `<Translate/>` component works as it should
None.
=> feat(i18n): allow simple HTML tags when using Translate component

packages/sanity/playwright-ct/tests/comments/CommentInput.spec.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInputInner.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInputProvider.tsx
This pull request fixes an issue when opening the mentions menu when inserting an '@' character in the comments input with the button. 
Insert a '@' character with the mention button and make sure that you can navigate the menu.
=> fix(desk): comment mention list issue when using the '@' button

packages/sanity/src/desk/comments/src/components/CommentDeleteDialog.tsx, packages/sanity/src/desk/comments/src/components/list/CommentsListItemLayout.tsx, packages/sanity/src/desk/comments/src/components/onboarding/CommentsOnboardingPopover.tsx, packages/sanity/src/desk/comments/src/components/pte/blocks/MentionInlineBlock.tsx
(These changes only affect comments within desk)
- Forces gray on all comment dates (edx-701)
- Fixes mention tooltip layout (edx-709)
- Updates thread delete copy (edx-711)
- Updates coachmark copy (edx-716)
That all of the above looks as it should!
N/A
=> fix(desk): various comments UX papercuts

packages/sanity/src/core/form/components/formField/FormFieldBaseHeader.tsx, packages/sanity/src/core/form/field/actions/FieldActionMenu.tsx
This pull request fixes a small alignment issue with in the field actions menu.
- Make sure that field action buttons are aligned nicely
=> fix(core): field actions vertical alignment

packages/sanity/playwright-ct/tests/comments/CommentInput.spec.tsx, packages/sanity/playwright-ct/tests/comments/CommentInputStory.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInputProvider.tsx
This will conveniently insert a space after a mention is inserted into the comment input.
=> fix(desk/comments): insert space after mention insert

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceLinkCard.tsx
Follow-up fix removing a console warning, and a small readability improvement after #5116 was merged
- The console warning complaining about forwarding `documentId` should be gone
- Is it a little more clear?
n/a
=> fix: avoid forwarding as-props/link props to reference link card before document type is known

.eslintrc.cjs, packages/sanity/src/core/form/inputs/ObjectInput/fieldGroups/FieldGroupTabs.tsx, packages/sanity/src/core/form/inputs/ObjectInput/fieldGroups/GroupTab.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferencePreview.tsx, packages/sanity/src/core/studio/Studio.test.tsx, packages/sanity/src/desk/components/pane/__workshop__/ExampleStory.tsx, packages/sanity/src/desk/components/paneItem/PaneItemPreview.tsx, packages/sanity/src/desk/panes/document/documentPanel/header/DocumentHeaderTabs.tsx, packages/sanity/src/desk/panes/document/inspectDialog/InspectDialog.tsx, packages/sanity/src/ui/index.ts, packages/sanity/src/ui/tab/Tab.tsx, packages/sanity/src/ui/tab/index.ts
Introduces `StudioUI Tab`, adding defaults to create the tabs. Introduces a `small` and `default` size. 
Removes the possibility of adding `icons`, custom `padding` and `fontSize`. 
Updates all the uses of tabs to use the ones.
Tab uses (can be tested in field groups)
Introduces `StudioUI Tab` components, adding defaults to create them.
=> feat(tab): add StudioUI Tab component

packages/sanity/src/desk/comments/src/components/onboarding/CommentsOnboardingPopover.tsx
This pull request adds a delay to the comments onboarding popover.
The onboarding popover should fade in after 500ms when opening the comments inspector.
n/a
=> feat(desk): delay comments onboarding popover visibility

.eslintrc.cjs
For now, we want to ignore i18n requirements in files related to the newly added Comments feature. The feature squad working on Comments will do the string extraction before the feature goes GA.
=> chore(i18n): temporarily ignore i18n in Comments files

packages/@sanity/portable-text-editor/src/utils/getPortableTextMemberSchemaTypes.ts, packages/@sanity/schema/src/legacy/types/blocks/block.ts, packages/@sanity/types/src/schema/asserters.ts
This will fix some issues with the block type schema, where it is missing definition for level, and the list definition is using the wrong key as illustrated by editing a PT-field with the regular array input:
The correct key here is `listItem`. 
After:
This change is trivial to do (renaming the schema field). I think it is, as all tests are passing and I can't find any other references to this field other than those I have already changed.
N/A - not a user-facing problem.
=> fix(schema/types): fix wrong key being used for block schema def.

packages/sanity/src/core/studio/workspaceLoader/WorkspaceRouterProvider.tsx, packages/sanity/src/router/README.md, packages/sanity/src/router/__test__/api.test.ts, packages/sanity/src/router/__test__/basepath.test.ts, packages/sanity/src/router/__test__/errors.test.ts, packages/sanity/src/router/__test__/examples.ts, packages/sanity/src/router/__test__/factory.test.ts, packages/sanity/src/router/__test__/findMatchingNodes.test.ts, packages/sanity/src/router/__test__/resolvePathFromState.test.ts, packages/sanity/src/router/__test__/resolveStateFromPath.test.ts, packages/sanity/src/router/__test__/scope.test.ts, packages/sanity/src/router/__test__/transform.test.ts, packages/sanity/src/router/__test__/urlSearchParams.test.ts, packages/sanity/src/router/__test__/usage.test.ts, packages/sanity/src/router/_findMatchingRoutes.ts, packages/sanity/src/router/_resolvePathFromState.ts, packages/sanity/src/router/_resolveStateFromPath.ts, packages/sanity/src/router/route.ts, packages/sanity/src/router/types.ts, packages/sanity/src/router/utils/parseScopedParams.ts
This PR adds support for a special key on the url state: `_searchParams` , which is an array of `[key: string, value: string]` tuples (similar to what you'd get from `URLSearchParams.entries()`).
It uses the scope (aka namespace) feature of the router, so when you're within a scope you don't need to worry about how your own search params fits in with the global environment. In the url, they will be namespaced with `/some/route?scope[param]=value`. Params in nested scopes will be `scopeA[scopeB][param]=value` (see added unit tests for details).
Given the route `/path/to/:someParam`
Given the url: `/path/to/something?foo=bar&bar=baz`
```ts
const router = useRouter()
console.log(router.state)
```
Will log
```ts
{
someParam: 'something',
_searchParams: [['foo', 'bar'], ['bar', 'baz']]
//^ see …
```
=> feat(router): add support for search params

packages/sanity/src/desk/comments/src/components/mentions/MentionsMenu.tsx
This pull request improves the filtering logic in the comments mention list by sorting the results with what the user has searched for first
- Make sure that you get most relevant results first in the list when you search for a user
=> feat(desk): improve comments mention list filtering

packages/sanity/src/desk/components/paneRouter/index.ts, packages/sanity/src/desk/index.ts, packages/sanity/src/desk/panes/DeskToolPane.tsx, packages/sanity/src/desk/panes/document/DocumentPane.tsx, packages/sanity/src/desk/panes/document/index.ts, packages/sanity/src/desk/panes/document/pane.ts, packages/sanity/src/desk/panes/documentList/DocumentListPane.tsx, packages/sanity/src/desk/panes/documentList/index.ts, packages/sanity/src/desk/panes/documentList/pane.ts
This is to support the work on visual editing, so that some Desk components can be reused in the Presentation tool. The changes result in some extra components and supporting types being exported from `sanity/desk`.
The Presentation tool needs to import the following from `sanity/desk`:
`BackLinkProps`
`deskTool`
`DeskToolProvider`
`DocumentListPane`
`DocumentPane`
`DocumentPaneNode`
`PaneLayout`
`PaneNode`
`PaneRouterContext`
`PaneRouterContextValue`
`ReferenceChildLinkProps`
`useDeskTool`
To resolve SDX-721, as part of ECO-66.
These changes should result in no functional difference. The changes only alter some exports and imports, and add tags.
N/A
=> feat(desk): export `DocumentPane` and `DocumentListPane`

packages/@sanity/block-tools/test/tests/util/__snapshots__/blockContentTypeFeatures.test.ts.snap, packages/@sanity/portable-text-editor/src/utils/getPortableTextMemberSchemaTypes.ts, packages/@sanity/schema/src/legacy/types/blocks/block.ts, packages/@sanity/types/src/schema/asserters.ts, packages/sanity/test/cli/graphql/__snapshots__/extract.test.ts.snap, packages/sanity/test/cli/graphql/__snapshots__/gen2.test.ts.snap, packages/sanity/test/cli/graphql/__snapshots__/gen3.test.ts.snap
This follows up https://github.com/sanity-io/sanity/pull/5079. 
This will update some test snapshots that I don't quite understand why didn't fail in the original PR but failed when rebasing on current `next`.
This also fixes an issue with an invalid list of fields array for the block type. Not sure what happened to this during merge either, as tests were passing in the original PR.
I have also strengthened the code in `block-tools` to not rely on array order to find schema fields for the block type but rather to find them exclusively.
I have removed https://github.com/sanity-io/sanity/pull/5079 from `next` and included the merge commit in this new PR.
* Are the changes to the Graphql schema OK? It is now correct, but maybe there's some logic attached to this inconsistency in the current …
=> fix(schema/types): fix block schema internal structure

packages/@sanity/cli/src/commands/init/initCommand.ts
Removes `--reconfigure` from sanity init help
Change makes sense
(Maybe not needed) - Removes deprecated `--reconfigure` from `sanity init --help`
=> chore(cli): remove '--reconfigure' command from help for sanity init command

packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditor.test.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/Editable.tsx
Fixes instances where long field names will cause the comment input placeholder to be wrapped over multiple lines, causing a overflow.
- That long names is truncated and looks good in different scenarios
- That placeholders in normal PTE inputs outside of comments is properly position as before
- Fixes instances where long field names in placeholders would cause overflow in comments input
=> fix(comments): truncate long field names in placeholder

packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx, packages/sanity/src/desk/panes/document/types.ts
This introduces a `onFocusPath` callback property on `DocumentPane`. This is needed by the new Presentation tool in order to subscribe to currently focused path within a document pane.
It also introduces an optimization to prevent unecessary `blur` events from triggering when the `path` is changed from the outside of `DocumentPane`.
- Read the code changes.
- Consider what sorts of unit tests we might add for this.
n/a
=> feat(desk): add `onFocusPath` callback property

packages/sanity/src/router/RouteScope.tsx
This change memoizes the `navigate` callback from the state router when using scoped routes.
Without this fix, depending on `navigate` in hooks could lead to infinite loops (e.g. in Presentation):
```ts
const {navigate} = useRouter()
const [viewParam, setViewParam] = useState(null)
useEffect(() => {
// navigate because some param was changed
navigate({
// ...
})
}, [navigate, viewParam])
```
The changes to the code.
- fix(router): memoize `navigate` callback
=> fix(router): memoize `navigate` callback

packages/sanity/src/core/form/inputs/files/ImageInput/ImageActionsMenu.tsx, packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
Prior to this change, the hotspot editor has been opened using `onFieldOpen`. This caused an issue with the hotspot editor not being able to maintain its open state when used in the Presentation tool.
This change involves using `onPathFocus` instead, which seems to be more idiomatic. This also means the hotspot editor is deep-linkable.
- The code changes.
- n/a
=> fix(form): open hotspot editor using `focusPath`

packages/sanity/src/desk/comments/plugin/inspector/CommentsInspector.tsx, packages/sanity/src/desk/comments/src/context/comments/CommentsProvider.tsx, packages/sanity/src/desk/comments/src/context/comments/types.ts
This pull request cleans up the `CommentsProvider` by removing the unused `getCommentPath` function.
- Everything should work as normal
n/a
=> refactor(comments): remove unused function in comments provider

packages/sanity/src/desk/comments/plugin/inspector/CommentsInspector.tsx
This pull request fixes so that the correct view (open or resolved) is selected in the inspector when scrolling to a comment from the URL.
- When copying the URL to a resolved comment, the resolved view should be selected when navigating to the URL
=> fix(comments): consider comment status when scrolling from URL

packages/sanity/src/desk/comments/plugin/field/CommentFieldButton.tsx
This pull request changes the default placement of the comment input popover. Ideally, when there's available space, the popover will now be positioned to the right. In cases where space is limited, the fallback position will be at the bottom.
- Make sure that the position of the tooltip works correctly
n/a
=> fix(comments): default placement of comment popover

packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx, packages/sanity/src/desk/i18n/resources.ts
A follow up from #5114 so that these components use the `context` prop instead of passing it through `values`
=> feat(i18n): fix confirm delete dialog

dev/test-studio/plugins/router-debug/RouterDebug.tsx, dev/test-studio/plugins/router-debug/index.ts, dev/test-studio/plugins/router-debug/plugin.tsx, dev/test-studio/plugins/router-debug/types.ts, dev/test-studio/sanity.config.ts
This adds a quick and simple debug tool to the dev/test studio that lets us debug studio router/link generation. Can be tested here: https://test-studio-git-dev-add-router-debug-tool.sanity.build/
n/a internal
=> dev(test-studio): add router debugging tool

packages/sanity/src/core/studio/components/navbar/tools/ToolLink.tsx
With the introduction of search params in #5148, we discovered that search params could sometimes carry over from one tool to another. This makes sure any existing state is cleared when generating links to tools in the nav bar.
N/A unlikely to be a known issue
=> fix(navbar): reset url state when navigating to other tools

packages/sanity/src/desk/comments/src/components/pte/config.ts
This PR updates the block schema to explicitly provide an empty annotations array. Pasting HTML with links will no longer render unsightly `DefaultAnnotations` at author time (before submission). Please refer to the issue for more context!
Pasting HTML with links should always render as 'plain' text.
N/A
=> fix(comments): prevent pasted links from being rendered as DefaultAnnotations at author time

packages/sanity/src/router/__test__/urlSearchParams.test.ts, packages/sanity/src/router/_resolvePathFromState.ts
Note: this stacks on top of changes in #5173 
This omits undefined from being encoded as search params
N/A
=> fix(router): omit undefined from search params

packages/sanity/src/core/form/components/formField/FormFieldBaseHeader.tsx, packages/sanity/src/desk/comments/plugin/field/CommentFieldButton.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInput.tsx
This pull request makes field actions keyboard accessible + fixes a few issues in comments.
`core` changes:
- Make field actions keyboard accessible
`desk` changes:
- Replaces `react-focus-lock` with custom focus lock behavior to resolve issues related to return focus.
- Adjusts click outside functionality to trigger only when the comment input popover is open.
- Enables discarding a comment using the "Escape" key, not just when the comment input is focused.
- Make sure that you can use the keyboard to access field actions
- Make sure that everything still works as before
Make field actions keyboard accessible
=> feat(core): make field actions keyboard accessible

packages/sanity/src/router/__test__/scope.test.ts, packages/sanity/src/router/__test__/urlSearchParams.test.ts, packages/sanity/src/router/_resolvePathFromState.ts, packages/sanity/src/router/encodeURIComponentExcept.ts
This adds support for skipping certain characters when encoding urls using sanity/router. This results in more readable urls. For now, only brackets and forward slashes are preserved, so instead of encoding the url like this
```
/section/foobar?tool%5Bpage%5D=%2Fproducts
```
it will be encoded like this
```
/section/foobar?tool[page]=/products
```
Does it make sense? Any unintended consequences of this that I'm forgetting?
N/A
=> fix(router): improve search params encoding

packages/sanity/src/core/studio/StudioLayout.tsx, packages/sanity/src/core/studio/router/helpers.ts, packages/sanity/src/router/RouteScope.tsx, packages/sanity/src/router/__test__/urlSearchParams.test.ts, packages/sanity/src/router/_resolvePathFromState.ts, packages/sanity/src/router/route.ts, packages/sanity/src/router/types.ts
This task enables a tool to declare that it fully "owns" and controls the search params, as a way to conditionally opt-out of the search parameter scoping, resulting in cleaner urls (see #5148 for backround info about search params support).
Declaring this on the tool level makes it possible to detect if there are multiple tools that declare they own the search params, and enables us to add safeguards/dev warnings if we want to do this later.
Whether the change makes sense. I'm not too satisfied with having to add special handling in so many different places, so ideally we should look into refactoring this behavior into core router utilities.
N/A
=> feat(router): add support for tools to bypass search param scoping

dev/design-studio/package.json, dev/studio-e2e-testing/package.json, dev/test-studio/package.json, examples/ecommerce-studio/package.json, packages/@sanity/portable-text-editor/package.json, packages/@sanity/vision/package.json, packages/sanity/package.json, yarn.lock
This PR updates `@sanity/ui` to latest (`1.9.3`)
Tooltips should render correctly and not appear 'squashed', especially at the periphery of boundary elements.
For comparison, try hover over field actions in the first field (`name`) in this document: [before](https://test-studio.sanity.build/ai-assist/content/untitledRepro;grrm) and [after](https://test-studio-git-chore-bump-sanity-ui.sanity.build/ai-assist/content/untitledRepro;grrm)
N/A
=> chore(deps): bump @sanity/ui to latest

packages/sanity/src/core/form/components/formField/FormFieldBaseHeader.tsx
This pull request makes sure that the field actions don't allow pointer events until they are visible. Currently, it is possible to hover the field actions when they are not visible, causing them to flicker. See video of the current issue:
https://github.com/sanity-io/sanity/assets/15094168/b13dd842-f678-4a67-ab18-4f0e70981100
Make sure that field action appears on hovering without flickering### Notes for release
n/a
=> fix(core): disable pointer events when field actions are hidden

packages/sanity/src/core/config/types.ts, packages/sanity/src/core/studio/router/helpers.ts, packages/sanity/src/desk/deskTool.ts, packages/sanity/src/desk/structureBuilder/InitialValueTemplateItem.ts, packages/sanity/src/desk/structureBuilder/Intent.ts, packages/sanity/src/router/types.ts
Attempts to solve the problem where you have multiple tools that can handle the same intent, and you want to weight them differently based on a parameter.
- One should be able to link from inside and outside of a studio to an edit intent, and give it a `mode` that is _better_ handled by one tool than another, but still be able to fall back if that "better" tool is not installed
- The currently active tool should be given priority if multiple tools are _equally_ good at handling the intent
- If the current active tool _can_ handle the intent, but a _better_ one is found, we should navigate to it
You have a "visual editing" tool and a "structured content" tool. They can both modify (edit) documents, but one is better at the schematic modification ("structured") and the other is better at …
=> feat(core): support weighted `template`, `mode` intent parameters

packages/sanity/src/desk/panes/document/statusBar/DocumentStatusBarActions.tsx
Adds wrapper to Publish Action button, it's needed to render the Tooltip correctly.
The button was the direct child of the tooltip, so the modified onMouseEnter action was passed to that button, given the button is disabled, the onMouseEnter action won't be triggered.
=> fix(facelift): add wrapper to publish action button

packages/@sanity/portable-text-editor/package.json, packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts, packages/sanity/src/core/form/inputs/PortableText/toolbar/BlockStyleSelect.tsx, yarn.lock
This will upgrade `slate` and `slate-react` to the latest. Latest version of `slate-react` includes [a bug fix](https://github.com/ianstormtaylor/slate/pull/5527) related to `ReactEditor`'s `.focus` function.
This means we now can remove a couple of workarounds we had in our code to work around this.
That the inputs are getting focused properly.
* The comment input
* The PT-input when changing block styles
N/A - no user-facing issues (due to current workarounds)
=> chore(portable-text-editor): upgrade slate + remove workarounds

packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditor.test.tsx, packages/@sanity/portable-text-editor/src/editor/components/Synchronizer.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithHotKeys.ts, packages/sanity/src/core/form/inputs/PortableText/Editor.tsx, packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
This will improve the selection management of the Portable Text Editor's Editable component when used in unknown contexts where the underlying context might uncontrollably cause re-renders to be made.
For instance when having a PortableText Input inside an object that is inside another Portable Text Input.
In this case, we would have two nested form contexts that each will update themselves as soon as the value from the nested editor is propagated to the root PT-input, and the `component.input`'s for both of them will then be re-rendered.
Though none of the actual editor nodes are re-rendered, this may cause the window selection to change and the editor will try to make an editor selection out of it.
If the user then is in the middle of making changes (like splitting a block into a new …
=> fix(portable-text-editor): selection validation and perf. improvement

packages/sanity/src/core/components/collapseMenu/CollapseMenu.tsx, packages/sanity/src/core/components/collapseMenu/CollapseOverflowMenu.tsx, packages/sanity/src/core/components/collapseMenu/ObserveElement.tsx
This changes the approach we use to check whether there's enough space to show menu options as expanded or collapsed or whether we need to move menu options to the menu:
1. We keep two "shadow" (hidden) navbars: One is rendering all items as expanded and the other is rendering all items as collapsed.
2. For each of these "shadow" navbars, we keep track of intersections for each rendered item in a dictionary on the format `Record<element.key, {intersecting: boolean, element: ReactElement}>`
3. This enables us to easily check whether we have received the intersections for all the current menu options, which again enables us to defer the first render until we have got all the intersection data we need.
This should also pave the way for future work that let's us track the individual widths …
=> refactor(core): improve navbar collapse menu

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceFinalizeAlertStrip.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceMetadataLoadFailure.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceStrengthMismatchAlertStrip.tsx, packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/NoItemsPlaceholder.tsx
Found some non-i18n related lint violations and fixed them. 
The lint error was:
```
'React' must be in scope when using JSX
```
=> chore(i18n): fixes missing react import for some files

packages/sanity/src/core/components/collapseTabList/CollapseTabList.tsx, packages/sanity/src/core/components/collapseTabList/__workshop__/CollapseTabListStory.tsx, packages/sanity/src/core/components/collapseTabList/__workshop__/index.ts, packages/sanity/src/core/components/collapseTabList/index.ts, packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx, packages/sanity/src/core/studio/components/navbar/tools/ToolCollapseMenu.tsx
Adds `<CollapseTabList />` component, which works similar to ColapseMenu but instead of removing the text it hides the elements that don't fit and renders them into a `<Menu />`
https://test-studio-git-edx-742.sanity.build/test/workshop/core;components;collapseTabList;collapse-tab-list?scheme=light
=> feat(facelift): create CollapseTabList for redesigned navbar

packages/sanity/.eslintignore, packages/sanity/.gitignore, packages/sanity/exports/presentation.ts, packages/sanity/package.json, packages/sanity/turbo.json, yarn.lock
- Add a pinned dependency from `sanity` on `@sanity/presentation` (currently handled in an external package and repository)
- Re-export `@sanity/presentation` as `sanity/presentation` so projects don't have to depend on `@sanity/presentation` directly.
- That the configuration looks sound and works.
- Link to the launch blog post.
=> feat: re-export `@sanity/presentation` as `sanity/presentation`

.eslintrc.cjs, dev/test-studio/plugins/locale-no-nb/bundles/studio.ts, packages/sanity/src/core/components/InsufficientPermissionsMessage.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/CreateButton.tsx, packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentButton.tsx, packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentListOption.tsx, packages/sanity/src/desk/components/paneHeaderActions/InsufficientPermissionsMessageTooltip.tsx, packages/sanity/src/desk/components/paneHeaderActions/PaneHeaderCreateButton.tsx, packages/sanity/src/desk/documentActions/DeleteAction.tsx, packages/sanity/src/desk/documentActions/DiscardChangesAction.tsx, packages/sanity/src/desk/documentActions/DuplicateAction.tsx, packages/sanity/src/desk/documentActions/PublishAction.tsx, packages/sanity/src/desk/documentActions/UnpublishAction.tsx, packages/sanity/src/desk/i18n/resources.ts
~~EDIT: Alright second try here. I opted to keep the interpolation value in the roles string but simplify the english phrase so that there is a clearer and stronger "action" clause. Additionally. I removed the roles from the phrase and move it into another that always displays it as a unit list. I think the result should translate better and has some nice consistencies. See new screenshot:~~
Edit edit: talked to @jtpetty who clarified and went with another approach that uses known context keys instead of the interpolation.
=> feat(i18n) localize insufficient permissions message

packages/sanity/src/core/form/studio/assetSource/shared/AssetMenu.tsx, packages/sanity/src/core/studio/screens/ConfigErrorsScreen.tsx
Adds missing react import for AssetMenu.tsx
Waives string literal in unused file
=> chore(i18n): adds missing react import

.github/workflows/e2e.yml, .github/workflows/pr-cleanup.yml
This is a temporary change to prevent explosive dataset growth in our CI tests.
Do the CI the tests still pass? We wanted each run to have nearly its own dataset but our current suite should work fine with just one.
N/A
=> test(e2e): disable dataset creation per PR

packages/sanity/src/core/form/components/formField/FormFieldBaseHeader.tsx
This pull request addresses an issue where hidden field actions caused the horizontal scroll bar to be visible within dialogs.
- Confirm that the horizontal scroll bar in dialogs is no longer visible.
- Verify that field actions still work as expected.
N/A
=> fix(core): field actions hidden issue

packages/sanity/src/desk/components/pane/Pane.tsx, packages/sanity/src/desk/components/pane/PaneHeader.styles.tsx, packages/sanity/src/desk/components/pane/PaneHeader.tsx, packages/sanity/src/desk/components/pane/types.ts, packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx, packages/sanity/src/desk/panes/documentList/DocumentListPaneContent.tsx, packages/sanity/src/desk/panes/list/ListPaneContent.tsx
Adds conditional borders to the pane header
https://github.com/sanity-io/sanity/assets/44635000/c088a0e7-bf30-4d45-9462-cf6fd1f137f5
The border for lists/documents lists/the document panel
FYI: I haven't added border logic to the components where the content is just one sentence and the scroll wasn't able to trigger (`ErrorPane.tsx `and `UnknownPaneType.tsx`)
=> feat(desk): add conditional borders to PaneHeader

packages/sanity/src/desk/deskRename/deskRenamedIcon.tsx
Changes the URL of the article explaining the rationale behind renaming Desk to Structure. Instead of a hard coded full url, it uses the `@sanity/generate-help-url` package.
N/A
=> fix(desk): change link to help article about the Desk - Structure rename

.github/workflows/test.yml
This disables the CLI CI tests that create datasets causing an internal issue. (just looking for a quick fix, a better one will come soon)
Does this stop the CLI tests while still leaving the normal jest tests in tact?
N/A
=> test(cli): disable exploding CI tests

packages/sanity/src/desk/components/paneHeaderActions/PaneHeaderCreateButton.tsx
Update the PaneHeaderCreateButton to include the tooltip in cases where it has only 1 template item type.
Incorrectly assumed in latest changes that the `<InsufficientPermissionsMessageTooltip >` was rendering in both cases. 
Now, if it doesn't have permissions it will render that template, in case it has permissions it will show the `Create new document` tooltip
=> fix(facelift): update pane header create button tooltip

packages/sanity/src/desk/comments/plugin/inspector/CommentsInspector.tsx, packages/sanity/src/desk/comments/src/components/list/CommentsListItem.tsx, packages/sanity/src/desk/comments/src/components/list/CommentsListItemContextMenu.tsx, packages/sanity/src/desk/comments/src/components/list/CommentsListItemLayout.tsx
This pull request fixes a layer issue, as can be seen in the screenshot. The solution here is to render the popover in the `MenuButton` in a portal, and we rely on the `isTopLayer` boolean from `useLayer` to determine whether we should deselect the selected comment in `CommentsInspector`.
This pull request also makes sure that the menu of the root comment is always visible when hovering over the thread item card.
- Make sure that the hover styles are correctly applied to the thread item card
- Make sure that the menu of root comment is always visible when hovering over the thread item card
n/a
=> fix(comments): context menu layer issue

packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInputDiscardDialog.tsx
This pull request fixes a z-index issue with the comment discard dialog where it was positioned below the document pane footer and document pane headers.
- Make sure that the comment discard dialog is positioned at the top
n/a
=> fix(comments): discard dialog z-offset

packages/sanity/src/core/form/inputs/PortableText/toolbar/Toolbar.tsx
This pull request addresses an issue where two menus in the PTE toolbar could be open simultaneously.
1. Open one menu in the PTE toolbar.
2. Open the second menu.
3. Confirm that the first menu closes when the second one is opened.
=> fix(form): only allow one PTE toolbar menu to be open

packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentButton.tsx, packages/sanity/src/desk/components/paneHeaderActions/PaneHeaderCreateButton.tsx, packages/sanity/src/desk/structureBuilder/DocumentList.ts, packages/sanity/src/desk/structureBuilder/InitialValueTemplateItem.ts
This PR changes the icon for create new document buttons (from the 'compose' to the 'add' icon). This button is found in the studio navbar and document lists.
This was a proposed change in upcoming facelift work, but has been brought forward to reduce ambiguity with the just released _Presentation_ tool, as that also uses the compose icon.
That the correct 'add' icon is being rendered in the above instances.
N/A
=> fix: globally replace compose with add icon

packages/@sanity/portable-text-editor/src/editor/plugins/createWithHotKeys.ts
This improves backspace handling when backspacing at the start of text blocks following a void block.
If the text block is empty, it will be deleted as before, and the selection will be set on the void block.
Improved: When the text block is non-empty, we will select the void block but skip deleting the text block.
https://github.com/sanity-io/sanity/assets/10508/d2094ca9-bdb9-420e-9488-6d8e2df064f0
- That deleting a empty text block following a void block works as before
- That the new behaviour where backspacing at the start of on a non-empty text block selects the previous void block (and that it feels like a good change)
- That backspacing inside the text block works as before
- That backspacing on a focused void block will delete it as before
- Improved backspace handling on text …
=> fix(portable-text-editor): improve backspace handling on text blocks

packages/@sanity/portable-text-editor/src/utils/__tests__/values.test.ts, packages/@sanity/portable-text-editor/src/utils/values.ts
This fixes an issue where the PTE would crash if you inserted a block with undefined `children`.
We will now show the correct "Invalid Portable Text Editor value" message.
How to reproduce:
```typescript
// someScript.ts
import {getCliClient} from 'sanity/cli'
getCliClient().create({
_type: 'blocksTest',
first: [{_key: 'a', _type: 'block'}],
})
```
```bash
// In the test studio folder
sanity exec someScript.ts --with-user-token
```
- Create a document with the repro above
- Navigate to the document in Standard inputs -> Portable Text -> Blocks and find your document
- See the "Invalid Portable Text Editor value" message
- Fixed a issue where the PTE would crash  if you inserted a block with undefined `children`
=> fix(portable-text-editor): handle undefined block children

packages/sanity/src/core/form/inputs/PortableText/Editor.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx, packages/sanity/src/core/studio/components/navbar/search/components/filters/addFilter/items/MenuItemFilter.tsx, packages/sanity/src/desk/comments/src/components/pte/comment-input/CommentInputInner.tsx, packages/sanity/src/desk/components/paneHeaderActions/PaneHeaderActions.tsx, packages/sanity/src/desk/components/paneItem/PaneItemPreview.tsx, packages/sanity/src/desk/panes/document/DocumentPane.tsx, packages/sanity/src/desk/panes/document/statusBar/DocumentStatusBarActions.tsx, packages/sanity/src/desk/panes/documentList/DocumentListPaneHeader.tsx, packages/sanity/src/ui/tooltip/Tooltip.tsx
Wraps button collections within a `<TooltipDelayGroupProvider>`
Wrapped tooltips will only have a open delay for the first tooltip that opens from the group, for an improved experience, related buttons are wrapped together, so once the first tooltip shows, hovering on the next ones will show the tooltip without delays. 
Groups the following:
- Navbar – LHS (workspace, create new)
- Navbar – RHS (search, help, presence)
- Document pane header actions
- Document list pane header actions
- Document footer - publish button / review changes buttons
- Document actions - menu items
- PortableText toolbar.
- Comments input actions. (mention user and send message)
- Reference preview
- Pane preview item
https://github.com/sanity-io/sanity/assets/46196328/5f858887-3176-44b6-a4da-e4d85e7a2470
Is …
=> fix(tooltips): wrap button collections within a TooltipDelayGroupProvider

packages/sanity/src/core/form/components/ActivateOnFocus/ActivateOnFocus.styles.tsx
This pull request fixes an issue where the "activate overlay" for the PTE input was not visible.
- Make sure that the overlay is shown on hover/focus
N/A
=> fix(form): pte activate overlay

perf/cli.ts, perf/queries.ts
Adds a flag to perf test runner that lets you exclude patch releases when running perf tests against earlier versions (tags)
- Does it look sensible?
n/a - internal tooling
=> feat(perf): add cli flag for excluding patch releases

packages/sanity/src/core/form/store/formState.ts, packages/sanity/src/core/form/store/types/nodes.ts, packages/sanity/src/core/form/store/utils/getExpandOperations.ts, packages/sanity/src/core/form/store/utils/immutableReconcile.ts
This fixes a couple of perf related issues.
1. 3ada4852f06cf4c8f6e156c39dd133e909aeff48 – When traversing over the previous + next formState to see what values are unchanged, we previously had a circular reference detection that added parents to a set as it went over it. When arriving at a node that's in the set of parents, it will short-circuit and return the next value. After done traversing over a subtree, the parent was still kept around in the set, which made it appear in parents of sibling subtrees, sometimes short-cirquiting (and returning the next) value in cases where it could have re-used the previous value (by referential identity). This PR fixes the issue by removing a node from parents after done iterating over a subtree.
2. d9f22ba762d91e6525f6ed6300e3539ec36a6d50 – Fixing …
=> perf(form): improve form state reconciliation

packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/inputs/PortableText/hooks/usePortableTextMembers.tsx
There were some issues here with member form inputs not being re-rendered properly when rendered inline in the editor
This makes sure we re-render those every time we need to (members change).
This can now be achieved by object equality checks after https://github.com/sanity-io/sanity/commit/a0f93cba7430a4584d01256a55e078d52a05c459
N/A
=> fix(form/inputs): optimize rendering of member inputs

dev/embedded-studio/.depcheckignore.json, dev/embedded-studio/.eslintrc, dev/embedded-studio/.gitignore, dev/embedded-studio/index.html, dev/embedded-studio/package.json, dev/embedded-studio/src/App.tsx, dev/embedded-studio/src/index.css, dev/embedded-studio/src/main.tsx, dev/embedded-studio/src/vite-env.d.ts, dev/embedded-studio/tsconfig.json, dev/embedded-studio/tsconfig.node.json, dev/embedded-studio/vite.config.ts, package.json, packages/sanity/src/core/studio/Studio.tsx, packages/sanity/src/core/studio/StudioLayout.tsx, packages/sanity/src/core/studio/studio-components-hooks/componentHooks.ts, yarn.lock
This pull request ensures that `StudioLayout` utilizes the Components API (`studio.components.layout`) when used in isolation. Recent features, such as Comments and AI assist, utilize this property in the Components API to wrap the layout in context providers. However, in an embeddable context, one might import the `StudioLayout` directly, like this:
```ts
import {StudioProvider, StudioLayout, defineConfig} from 'sanity'
const config = defineConfig({
// ...
})
export function MyStudio() {
return (
<StudioProvider config={config}>
<StudioLayout />
</StudioProvider>
)
}
```
With this approach, you import the _default_ `StudioLayout` component, which does not include any modifications added to `studio.components.layout`. This leads to errors when components in `StudioLayout` try to access …
=> fix(core): ensure that `StudioLayout` utilizes the components API

packages/sanity/src/desk/comments/plugin/field/CommentField.tsx, packages/sanity/src/desk/comments/src/context/comments/CommentsProvider.tsx, packages/sanity/src/desk/comments/src/context/comments/types.ts, packages/sanity/src/desk/panes/document/DocumentPaneProvider.tsx
This pull request removes the use of `useDocumentPane` in the `CommentField` component to improve performance. The hook was used to open the comments inspector, which is now replaced with props passed to the `CommentsProvider`.
=> fix(comments): performance issue in `CommentField`

packages/sanity/src/core/store/_legacy/datastores.ts, packages/sanity/src/core/store/_legacy/presence/useGlobalPresence.tsx
When running the build command on the test studio I noticed this warning:
It appears to be caused by the circular dependency fixed in this PR.
Warning should be gone, and nothing else should break/change as a result. The generated bundle should stay the same as none of the publicly exported paths changed.
None
=> fix: remove circular dependency between `useGlobalPresence` and `usePresenceStore`

packages/sanity/src/core/form/inputs/ReferenceInput/CreateButton.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceAutocomplete.tsx, packages/sanity/src/core/studio/components/navbar/search/components/common/CustomTextInput.tsx, packages/sanity/src/core/studio/components/navbar/search/components/common/CustomTextInputBox.tsx, packages/sanity/src/desk/components/IntentButton.tsx
Sometimes huge chonkers console warnings will fill up your devtools:
No more chonkers when running `yarn dev` on the monorepo or `sanity dev`.
Fixed console warnings about passing through non-DOM properties to styled-components
=> fix: prevent props that are unknown html attributes from passing through

packages/sanity/src/core/form/inputs/ObjectInput/fieldGroups/GroupTab.tsx
Very small change to fix the `data-testid` attribute given to group tab buttons. At the moment, they use the `name` variable, which is undefined.
=> fix(form): include group name in group tab test id

packages/sanity/package.json
Currently we are publishing the entire `src` folder, which contains some stuff we don't really need to publish:
```
npm notice 132B    src/desk/panes/document/statusBar/__workshop__/.eslintrc
npm notice 960B    src/desk/panes/document/statusBar/__workshop__/DocumentActionsStory.tsx
npm notice 960B    src/desk/panes/document/statusBar/__workshop__/DocumentBadgesStory.tsx
npm notice 613B    src/desk/panes/document/statusBar/__workshop__/index.ts
npm notice 751B    src/desk/panes/document/statusBar/__workshop__/ReviewChangesButtonStory.tsx
npm notice 3.2kB   src/router/__test__/api.test.ts
npm notice 1.2kB   src/router/__test__/base64url.test.ts
npm notice 320B    src/router/__test__/basepath.test.ts
npm notice 803B    src/router/__test__/errors.test.ts
npm notice 1.4kB …
```
=> chore: prevent tests, workshop files from being published

packages/sanity/src/core/form/components/EditPortal.tsx
Contain onDragEnter event to the dialog only, as it's propagating to the elements behind it causing unexpected behaviours in the elements.
https://github.com/sanity-io/ui/assets/46196328/c2661532-44de-4fd5-bef9-a693e34eb224
https://github.com/sanity-io/ui/assets/46196328/c6b317b1-cd5e-42a8-997b-93263ede1c06
EditPortal modal behaviour. 
Fix error in which working in a PTE which is opened in a modal over an array, drag'n'dropping blocks will affect the underlying array (error:"Can't upload this file here")
=> fix(dialog): drag events in editPortal are applied to underlying elements

packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/ToolCanvas.styles.tsx, packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/ToolCanvas.tsx, packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/makeDragAware.tsx, packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/types.ts
This PR fixes an issue where drag handles in the image crop tool would not correctly work on devices with both _coarse_ and _fine_ pointer support (e.g. a touchscreen laptop connected to a mouse).
This opts to use pointer events (as opposed to conditionally picking either touch or mouse events) which simplifies things a little, especially since there aren't any multi-touch requirements.
Drag handles in the image crop tool should work as normal on devices with either coarse, fine or both coarse pointer support.
Fixes an issue where the image crop tool would not work on touchscreen devices with connected pointer devices.
Fixes #4807, Fixes #4947
=> fix: ensure image tool drag handles work when both coarse + fine pointers are present

packages/@sanity/cli/src/actions/init-project/templates/nextjs/index.ts
Fixes an issue in the bootstrapped Next.js template where the `urlForImage` function wouldn't return a url. It would instead return a class and cause the following error:
`Error: Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported.`
The addition of the `url()` method resolves the error and allows the builder to work properly without further configuration on the user's part. To test that this fix is needed, try to use the builder without this addition by bootstrapping a template inside of a Next project. 
Fixes an issue in the Next.js template where the urlForImage function would return a class instead of a url.
=> fix next template image url builder not returning a url

dev/test-studio/plugins/locale-no-nb/bundles/structure.ts, dev/test-studio/plugins/locale-no-nb/bundles/studio.ts, packages/@sanity/vision/src/i18n/resources.ts, packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/core/i18n/bundles/validation.ts, packages/sanity/src/desk/i18n/resources.ts, packages/sanity/src/desk/panes/document/inspectDialog/Search.tsx, packages/sanity/src/desk/panes/document/timeline/timelineI18n.ts, packages/sanity/src/desk/panes/document/timeline/timelineItem.tsx, packages/sanity/src/desk/panes/document/timeline/timelineMenu.tsx
To ease automation and findability, it makes sense for the keys to be alphabetically sorted. Once I made this change, I discovered a few inconsistently named items, which I have fixed.
There were also a few camelCased and dynamic strings being used, which does not align with the rest of the identifiers - I took the liberty of changing these and putting them under a subgroup (`timeline.operation`)
There may be some inconsistencies in the Norwegian translations, but these will be cleared up as they are moved out of the monorepo soon.
None
=> fix(i18n): sort keys and adjust inconsistently named properties

.github/workflows/cli-test.yml, .github/workflows/test.yml
This PR moves the CLI tests to it's own workflow without jest sharding so that it does not create a lot of datasets. The total number of datasets it should create per PR should be  (datasets(5) + copy) * studio version (2) * node versions (2) = **24** which is not ideal and hence long term solution would be moving some of the API calls but this should make the tests functional
If the changes makes sense
N/A
=> test(ci): move cli test to separate workflow without sharding

.github/CODEOWNERS
Updating CODEOWNERS file to use teams over individuals and added a default rule to add Studio DX to reviews.
=> chore(core): update CODEOWNERS file to use teams over individuals

packages/sanity/src/desk/i18n/resources.ts, packages/sanity/src/desk/panes/document/documentPanel/PermissionCheckBanner.tsx
Fixes the "permission check" banner at the top of a document when you do not have the sufficient permissions to create or edit a document. Previously it showed something like this:
This is because interpolating JSX elements won't work.
This PR:
1. Uses the list formatter to split into parts and makes it available as `<Roles/>`
2. Uses context to define the different permissions available (`create`, `update`) so they can be translated to other languages
3. Uses the `count` parameter to differentiate between one and multiple roles, to align with other pluralization keys
Permission checks now render correctly
None
=> fix(i18n): correct permission check banner interpolation

packages/sanity/src/desk/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx
Just an incorrect key being used.
CDR table has the correct tooltip title
None
=> fix(i18n): invalid key for cdr "copy id to clipboard" button tooltip

dev/test-studio/plugins/locale-no-nb/bundles/studio.ts, packages/sanity/src/core/form/components/ActivateOnFocus/ActivateOnFocus.tsx, packages/sanity/src/core/i18n/bundles/studio.ts
Localizes activation message for PTE on hover or on tap hover.
There seems to be uncommitted `yarn.lock` from next that got included as well
If keys makes sense and logic makes sense
(probably part of larger i18n release notes)
=> feat(i18n): localize PTE activation message

packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/desk/panes/document/timeline/timelineMenu.tsx
An oversight on my part - when selecting a revision, we were not actually passing the i18n key to the `t` function, but rather showing it as-is. This fixes that.
Review changes shows the correct label when selecting an operation.
None
=> fix(i18n): key being used instead of translated value

packages/sanity/src/core/form/studio/assetSource/file/AssetRow.tsx, packages/sanity/src/core/form/studio/assetSource/file/FileListView.tsx, packages/sanity/src/core/form/studio/assetSource/shared/DefaultSource.tsx, packages/sanity/src/core/i18n/bundles/studio.ts
This PR ensures correct i18n keys are used within the default file asset source. It also fixes an issue with accepted types not displaying correctly.
- When browsing assets in the default file asset source (on mobile breakpoints) – file headers and the show usage button should render correct localized text
- Accepted types should also render correctly
**Before**
**After**
N/A
=> fix(i18n): use correct keys for file asset source headings and accepted types

packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx
This pull request addresses small UI issues in the global presence menu:
- Ensures that the menu is always positioned at the bottom
- Fixes a background issue with the footer in the popover (see image below)
- Make sure that it looks good
N/A
=> fix(core): presence menu ui

packages/sanity/src/core/form/components/formField/FormFieldBaseHeader.tsx
This pull request ensures that field actions do not impact the layout within the field when they are not visible. Currently, the field actions are hidden using opacity, resulting in presence avatars being pushed to the left even when the field actions are not visible.
- Make sure that it looks good
N/A
=> fix(core): field actions hidden state

dev/test-studio/structure/constants.ts, dev/test-studio/structure/resolveStructure.ts, packages/sanity/src/desk/comments/src/context/setup/CommentsSetupProvider.tsx
Fixes a few console warnings:
- Use the new API version for the dataset profile requests - fixes EDX-729.
- Two trivial test-studio issues
Not sure if the API version thing was an oversight or if I have overlooked something not having been released under a non-experimental version yet? Please advise.
- Fixes a console warning being printed about using an experimental API version
=> fix(comments): experimental API warning for dataset profile request

packages/sanity/src/core/hooks/__tests__/useRelativeTime.test.tsx, packages/sanity/src/core/hooks/useRelativeTime.ts
This PR updates `useRelativeTime` to prefer `narrow` styling for both Intl.RelativeTimeFormat's styling and Intl.NumberFormat's unitDisplay when `minimal=true`.
In other words, it'll display `3 wk. ago` as `3w ago`, which was how relative dates were displayed prior to recent i18n work.
That relative dates in the studio display their more condensed versions. 
Whilst these minimal dates aren't used much in the current studio (primarily in the document status bar / sparkline), they're a little more prevalent in upcoming facelift work.
- Fixed an issue where relative dates were not displaying fully condensed versions
=> fix(i18n): prefer narrow relative time formatting in `useRelativeTime`

packages/sanity/src/core/form/inputs/ObjectInput/ObjectInput.tsx, packages/sanity/src/desk/panes/document/documentPanel/DocumentPanel.tsx
This branch uses the same approach Binoy employed to fix list virtualisation at the document level, but applies it to all object inputs. It wraps object inputs in a React fragment that uses the selected group name as its key. This causes a unique element to be rendered for each selected group, and therefore all virtualised descendants are recalculated when the selected tab changes.
Adding the key at this level solves the problem both at the document level, and inside modals.
This branch also removes Binoy's fix, which is now redundant.
Fixes #4687.
**Top-level groups before fix**
https://github.com/sanity-io/sanity/assets/1454914/6529d228-63c7-4770-9a09-2e3e0c997a5d
**Top-level groups after fix**
https://github.com/sanity-io/sanity/assets/1454914/573e66ca-17e1-486f-b816-f334058e2772 …
=> fix(form): recalculate virtualized descendants when selected group changes

packages/sanity/src/core/form/inputs/DateInputs/base/calendar/CalendarMonth.tsx, packages/sanity/src/core/form/inputs/DateInputs/base/calendar/types.ts, packages/sanity/src/core/form/inputs/DateInputs/utils.ts
As part of the i18n work, we localized the week day names, but we put the names in monday-sunday order, while the calendar expects sunday-saturday. By switching the localized input so sunday is the first entry, it should fix this.
- In date/datetime inputs, the week days should be showing the right week day in the header
- Fixed an issue where the wrong week day was shown for a date in date inputs
=> fix(core): incorrect week day names for calendar

packages/sanity/src/core/hooks/useFormattedDuration.ts, packages/sanity/src/core/hooks/useRelativeTime.ts, packages/sanity/src/core/hooks/useUnitFormatter.ts, packages/sanity/src/core/i18n/LocaleContext.ts, packages/sanity/src/core/i18n/components/LocaleProvider.tsx, packages/sanity/src/core/i18n/fallback.ts, packages/sanity/src/core/i18n/hooks/useIntlDateTimeFormat.ts, packages/sanity/src/core/i18n/hooks/useIntlListFormat.ts, packages/sanity/src/core/i18n/hooks/useIntlNumberFormat.ts, packages/sanity/src/core/i18n/hooks/useLocale.ts, packages/sanity/src/core/i18n/i18nConfig.ts, packages/sanity/src/core/i18n/types.ts, packages/sanity/src/core/studio/components/navbar/resources/helper-functions/hooks.ts, packages/sanity/src/core/studio/components/navbar/userMenu/LocaleMenu.tsx, packages/sanity/src/core/validation/util/localizeMessage.ts
The `useCurrentLocale` hook currently only exposes the locales' ID. As we mature the API, this won't be all the information we want to get from it, and thus we should change this now so we can expand in the future.
Introduces a new `Locale` type that is basically `LocaleDefinition` but without `bundles`. Again, as we mature we may want to split what the user passes as input for the locale from what the framework exposes, such as computed values (calendar info, date formatting rules, pluralization info etc)
None (not yet public)
=> feat: expose all locale info from `useCurrentLocale` hook

packages/sanity/src/core/form/inputs/DateInputs/__tests__/CommonDateTimeInput.test.tsx, packages/sanity/src/core/form/inputs/DateInputs/base/calendar/Calendar.tsx, packages/sanity/src/core/form/inputs/DateInputs/base/calendar/CalendarMonth.tsx, packages/sanity/src/core/form/inputs/DateInputs/base/calendar/types.ts, packages/sanity/src/core/form/inputs/DateInputs/base/calendar/utils.ts, packages/sanity/src/core/form/inputs/DateInputs/utils.ts, packages/sanity/src/core/hooks/__tests__/useUnitFormatter.test.tsx, packages/sanity/src/core/i18n/__tests__/Translate.test.tsx, packages/sanity/src/core/i18n/i18nConfig.ts, packages/sanity/src/core/i18n/locales.ts, packages/sanity/src/core/i18n/types.ts, packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/datePicker/calendar/Calendar.tsx, packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/datePicker/calendar/CalendarMonth.tsx, packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/datePicker/calendar/constants.ts, packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/datePicker/calendar/contexts/CalendarContext.ts, packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/datePicker/calendar/utils.ts
*Note*: builds on #5343
Currently, the date/datetime/date filter calendars always start the shown weeks on Sundays. This is fine for some locales, but  for others it is more natural to show the week starting on Mondays.
This PR introduces a `weekInfo` object to locale definitions. Theoretically it should be inferable using `new Intl.Locale('en-US').weekInfo` / `new Intl.Locale('en-US').getWeekInfo()`, but it seems browser support is less than ideal, to say the least, so better to define this up front.
Calendars still start on Sunday (test studio currently does not have additional locales installed, so hard to test).
None
=> feat(core): make calendars aware of locale week start day

packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts, packages/sanity/src/core/form/studio/inputs/crossDatasetReference/datastores/getReferenceInfo.ts, packages/sanity/src/core/preview/utils/getPreviewPaths.ts
Unless explicitly added, the `updatedAt` prop was not included in the previews, hence not showing a timestamp for when it was last edited/published.
That the list previews (and all previews really) show a correct timestamp of last edited/published
Fixes issue where timestamp was not included in last edited/published in list previews
=> fix(core): add timestamps to all preview components

packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx
The annotation toolbar popover would wrongly appear at the top left corner of the parent container when you selected text over the annotation. 
https://github.com/sanity-io/sanity/assets/44635000/f5454db0-3216-4419-bb82-68992c5f7280
Annotation popover and dialog logic. 
Fixes issue where annotation popover open when selecting annotation text.
=> fix(core): prevent annotation popover from jumping when opening

packages/sanity/src/core/form/inputs/PortableText/toolbar/ActionMenu.tsx
When selecting multiple blocks in the PTE editor and then adding an annotation to it, the PTE editor breaks, because annotations are not meant to be multi-block.
Annotations require a `markDef` and that `markDef` needs to exist in the block in which the annotation is referred. 
To avoid issues, disable the `annotations` when selecting multiple blocks
- If block is empty, annotations will be disabled (this is already happening) and will show a tooltip message : Cannot apply {{annotationTitle}} to empty block
- If is selecting multiple blocks, annotation will be disabled and will show tooltip message Cannot apply {{annotationTitle}} to multiple blocks
- Selecting 1 block with content, annotation enabled and message: {{annotationTitle}}
Annotations behaviour
Disabled multiple blocks …
=> fix(pte): disable multiple blocks annotations

packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withEditableAPIInsert.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts
When inserting a new block the PTE editor was creating empty text blocks.
This PR adds a check to remove the text block in the user selection if it's empty before inserting a new block.
So, if you have a empty editor and try to insert any new block, no empty text blocks will be created.
If the editor has values, and you are in an empty text block, no new blocks will be added.
https://github.com/sanity-io/sanity/assets/46196328/03afca8c-5f02-439b-87ef-58fd07e8a568
Adding text blocks should continue working as expected.
Fixes issue in which new empty text blocks where added when adding a block in the portable text editor.
=> fix(pte): removes empty text block when inserting a new block in that position

packages/sanity/src/core/preview/utils/getPreviewPaths.test.ts, packages/sanity/src/core/preview/utils/getPreviewPaths.ts
Fixes issue introduced in which the custom previews are not showing the values, introduced by this changes https://github.com/sanity-io/sanity/pull/5352/files#diff-82e6260f1ef4bafb24e139098b0b68d038a73f2043aa977530bd59749b025228R14
Should be using `Object.values` instead of `Object.keys`
=> fix(core): update getPreviewPaths function

dev/test-studio/schema/standard/portableText/allTheBellsAndWhistles.ts, packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditorTester.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withPortableTextMarkModel.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts
Fixes issue in which splitting the paths when removing annotations and creating new spans was not always selecting the correct span to remove the annotations from.
See video:
https://github.com/sanity-io/sanity/assets/46196328/ee99bd69-be52-4a29-99e0-30d70ac3d996
Annotations, adding and removing.
Fixes issue in which splitting the paths when removing annotations and creating new spans was not always selecting the correct span to remove the annotations from
=> fix(pte): removing annotations cleans incorrect path

packages/sanity/src/desk/panes/document/statusBar/ActionMenuButton.tsx
A tooltip should only be visible if the menu item is disabled
=> fix(desk): add tooltip on menuitem when disabled only

packages/sanity/src/core/form/components/formField/FormFieldBaseHeader.tsx, packages/sanity/src/core/studio/Studio.test.tsx
Update how the`<FieldPresence>` element is positioned and remove the` width:0 `from the `<FieldActionFloatingCard>` as it is causing layout to shift in an unexpected way.
Now the Root will add the position to the field presence element, this was moved to the Root because we need to handle the case of focus-within. This is the nearest parent we can choose. 
https://github.com/sanity-io/sanity/assets/46196328/cff41096-dc96-4ca6-92c8-57af45ce98ae
https://github.com/sanity-io/sanity/assets/46196328/e6fce327-1f37-4283-ade3-35b04751bd78
=> fix(core): fields actions position shift

packages/@sanity/block-tools/package.json, packages/sanity/package.json, yarn.lock
Fixes #5316 (deprecated packages warning)
Block tools and CLI exec command and family still works
None
=> chore(deps): upgrade jsdom dependency

packages/@sanity/schema/src/legacy/ordering/guessOrderingConfig.ts, packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/desk/i18n/resources.ts, packages/sanity/src/desk/structureBuilder/MenuItem.ts, packages/sanity/src/desk/structureBuilder/documentTypeListItems.ts
This PR:
- fixes an incorrect configuration causing the default orderings to not be localized
- adds a fallback localization for menu items that takes in the legacy sorting item title
- localizes the default group titles (actions, layout, sort)
- Does the orderings appear localized for you?
- Does the new menu item groups appear localized?
N/A
=> fix(i18n): fix incorrect menu items; localize default group titles

packages/@sanity/cli/src/types.ts, packages/sanity/src/_internal/cli/actions/graphql/deployApiAction.ts, packages/sanity/src/_internal/cli/actions/graphql/gen3/__tests__/utils.test.ts, packages/sanity/src/_internal/cli/actions/graphql/gen3/generateTypeFilters.ts, packages/sanity/src/_internal/cli/actions/graphql/gen3/generateTypeQueries.ts, packages/sanity/src/_internal/cli/actions/graphql/gen3/index.ts, packages/sanity/src/_internal/cli/actions/graphql/gen3/utils.ts, packages/sanity/src/_internal/cli/actions/graphql/types.ts, packages/sanity/test/cli/graphql/__snapshots__/gen3.test.ts.snap, packages/sanity/test/cli/graphql/gen3.test.ts
This PR adds support for customizing the name of the autogenerated `Filter` types by providing a `filterSuffix` key in the `sanity.cli.ts` under the graphql key.
Adds custom suffix to graphql key in `sanity.cli.ts`
```ts
graphql: [ { filterSuffix: 'Custom' }]
```
- Adds ability to customize the filter suffix for graphql schema
=> feat(graphql): add support for customizing the filter suffix for graphql types

packages/@sanity/cli/src/actions/init-project/initProject.ts, packages/@sanity/cli/src/packageManager/installPackages.ts, packages/@sanity/cli/src/packageManager/packageManagerChoice.ts
Adds bun as (experimental) package manager to use for sanity projects
Is marking it as experimental necessary? My reasoning was that we don't expclitly test with `bun` and (afaik) haven't aquired much data/confidence about adoption/error rates.
- Add bun as possible package manager to use for new sanity projects
=> fix(cli): add (experimental) support for bun as package manager

packages/sanity/src/core/i18n/bundles/studio.ts
Self-explanatory, I hope. We were referencing a missing resource.
=> fix(i18n): add missing string for cancelling uploads

dev/test-studio/sanity.config.ts, packages/sanity/src/core/i18n/i18nConfig.ts, packages/sanity/src/core/studio/components/navbar/userMenu/LocaleMenu.tsx
Until we land schema localization, choosing a different language has limited value. For now, select the last registered locale and use that, disabling the choice. Will fall back to English (US) on missing strings.
- Enabling a locale plugin will use that as the default (last one defined wins)
None.
=> feat(i18n): use last registered locale as default

dev/design-studio/structure.ts, dev/test-studio/locales/index.ts, dev/test-studio/schema/allTypes.ts, packages/sanity/src/core/form/components/tagInput/tagInput.tsx, packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/desk/i18n/resources.ts, packages/sanity/src/desk/panes/loading/LoadingPane.tsx, packages/sanity/src/desk/panes/loading/getWaitMessages.ts, packages/sanity/src/desk/structureBuilder/createStructureBuilder.ts
Fixes a few missing translation surfaces:
- Root structure node ("Content")
- Placeholder text for tag input ("Type tag and press enter")
- Structure tool loading pane (not the skeleton, but shown while async panes are resolving)
=> fix(i18n): missing translations for structure, tag input, loading pane

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
This will test the window selection `rangeCount` before calling `getRangeAt(0)`. Calling this without any ranges will result in a JS-error.
* Fixed an potential JS-error related to window selections
=> fix(portable-text-editor): return unless range count

packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx, packages/sanity/src/core/studio/components/navbar/free-trial/DescriptionSerializer.tsx, packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrialContext.tsx, packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrialProvider.tsx
Few refactorings;
- We should always check for the presence and ability to use localStorage before calling it. Strict browsers will throw an error when you try to access it with localStorage disabled.
- The request for the trial endpoint should be cancelled on unmount
- If the trial endpoint returns Portable Text blocks/marks/annotations that are not known, the default behavior is to warn. This warning is not something we want to expose to third-party users of the studio however, so lets disable it.
- We generally try to keep the context and providers as separate files, and have their exports match the filename where applicable. Also, the preferred naming convention is `SomethingContext` (actual React context returned from `createContext`) and `SomethingContextValue` (the interface/type …
=> refactor(free-trial): fault tolerance, code conventions

packages/@sanity/cli/src/actions/login/login.ts, packages/@sanity/cli/src/actions/telemetry/setTelemetryConsent.ts, packages/@sanity/cli/src/cli.ts, packages/@sanity/cli/src/commands/index.ts, packages/@sanity/cli/src/commands/logout/logoutCommand.ts, packages/@sanity/cli/src/commands/telemetry/disableTelemetryCommand.ts, packages/@sanity/cli/src/commands/telemetry/enableTelemetryCommand.ts, packages/@sanity/cli/src/commands/telemetry/telemetryGroup.ts, packages/@sanity/cli/src/commands/telemetry/telemetryStatusCommand.ts, packages/@sanity/cli/src/util/createExpiringConfig.ts, packages/@sanity/cli/src/util/createTelemetryStore.ts, packages/@sanity/cli/src/util/telemetryDisclosure.ts, packages/@sanity/cli/test/telemetry.test.ts
Adds three new CLI commands for managing telemetry consent, and also adds caching of telemetry consent status.
- `sanity telemetry status` – view consent status
- `sanity telemetry disable` – disable telemetry by withdrawing consent
- `sanity telemetry enable` – enable telemetry by granting consent
In addition:
- Adds a short lived cache of consent status (to avoid excessive api calls in case of serial cli usages)
- Adds information about telemetry that will appear the first time the cli is run after upgrading (or on new machines)
- Does the changes look ok?
TBD
=> feat(cli): add telemetry cli commands

packages/@sanity/cli/src/util/createTelemetryStore.ts
Adds the ability to inspect telemetry events by writing them to a file in cwd
~Note: tests are failing due to not-yet-deployed production APIs. They should pass once they gets deployed.~
N/A
=> feat(cli): add env var for logging telemetry events to file

packages/@sanity/portable-text-editor/src/editor/plugins/createWithPatches.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithUndoRedo.ts, packages/@sanity/portable-text-editor/src/utils/ranges.ts
After #5136 this code is no longer needed as the MutationObserver does what it is supposed to and verifies the selection properly. 
There is also a bug in this removed code that doesn't take into account that the particular editor is focused and selected before removing all the DOM selection ranges, which has side effects in documents with several editors.
* Improved selection handling for the Portable Text Editor when using several editors in the same document.
=> refactor(portable-text-editor): remove obsolete code

packages/@sanity/cli/src/cli.ts, packages/@sanity/cli/src/util/createTelemetryStore.ts
This adds a 2 second timeout to sending telemetry events at process exit. If, for some reason the intake api takes long to respond, we don't want to keep the process going.
In addition, this PR adds a SIGINT (Ctrl+C) listener that flushes the telemetry store before exiting.
- Does it make sense?
N/A
=> fix(cli): improve telemetry exit flushing

packages/sanity/src/core/field/diff/components/ChangeList.tsx, packages/sanity/src/core/field/diff/components/FieldChange.tsx, packages/sanity/src/core/field/diff/components/GroupChange.tsx
Updates the revert changes popover to match with the new facelift designs.
=> fix(core): update changes revert confirmation popovers

packages/sanity/src/core/studio/components/navbar/navDrawer/LocaleMenu.tsx, packages/sanity/src/core/studio/components/navbar/userMenu/LocaleMenu.tsx
This PR removes the locale selection menu in the nav drawer ('burger' menu on smaller breakpoints). The locale menu was introduced here in facelift, as there was no way to switch between locales on smaller viewports.
Given that it's been [temporarily disabled in the user menu](https://github.com/sanity-io/sanity/blob/bb0377aa732786dac500dbfe529ef7c6c5177471/packages/sanity/src/core/studio/components/navbar/userMenu/LocaleMenu.tsx#L7-L14) in #5381, it only makes sense that we disable it here too.
Note: there is a bit a duplication between both nav 'drawer' and nav 'bar' menus, since they both technically use different child components and props. This could / should certainly be optimised in future.
The locale switcher menu should _not_ be visible in the nav drawer menu on smaller …
=> fix: temporarily disable locale selection in nav drawer

dev/test-studio/schema/standard/arrays.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx, packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/PreviewItem.tsx
Fixes missing subtitle in object and reference previews inside arrays.
References:
Objects:
- Fix missing subtitle in object and reference previews inside arrays
=> fix(form): fix missing subtitles in array previews

packages/sanity/src/desk/panes/document/statusBar/DocumentStatusBar.tsx
=> fix(core): adds consistent padding to document footer

packages/sanity/src/core/components/previews/general/CompactPreview.tsx, packages/sanity/src/core/components/previews/general/DefaultPreview.tsx, packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrial.tsx
Sanity UI has a default `box-sizing: content-box` but this in some scenarios can be overridden in embebed studios, for example in a NextJS app which includes Tailwind, as it's usual to reset that and use `box-sizing: border-box`.
With these changes, the box sizing will be consisten in a normal studio and an embebed one.
It also adds a delay to mount the popover given that in embebed studios it was positioning in an incorrect place.
Adding this delay, gives time for the element to mount and the popover to position as expected.
=> fix(core): box sizing content box in preview elements, free trial popover position

packages/sanity/src/core/config/types.ts
The workspace logo was missing deprecated tag, as this is no longer supported
=> fix(core): add missing deprecated tag to workspace logo

packages/@sanity/cli/src/actions/telemetry/setTelemetryConsent.ts
Currently, if `sanity telemetry enable` fails, you'll get a quite unhelpful stack trace printed to the terminal. This PR improves the error formatting and forwards the error message given by the API.
- This one is a bit tricky to test live – feel free to reach out to me for any details. I've verified that it works as intended.
- Note: I also removed some of the env var based mocking code that were left in here as I don't think it's that relevant anymore. Preferable this should be moved into unit tests and be run against mocked API responses.
- Improved message in case of an error with enabling telemetry consent
=> fix(cli): improve error message in case `sanity telemetry enable` fails

.github/workflows/e2e.yml, .github/workflows/pr-cleanup.yml
Reverts sanity-io/sanity#5210
When I was originally investigating the exploding dataset issue, I thought the e2e tests were causing the dataset issue so we merged #5210 to stop the e2e tests from creating a dataset per PR.
In actuality, the e2e tests were well set up and the issue was with the CLI tests so this PR simply reverts #5210
=> fix(e2e): Revert "test(e2e): disable dataset creation per PR"

packages/@sanity/cli/package.json, packages/sanity/package.json, packages/sanity/src/_internal/cli/actions/build/buildAction.ts, yarn.lock
We recently added a `telemetry` instance to the context passed from the global cli to "local" project cli commands. However, if the global CLI is on an older version than the one installed locally in the project folder, the local command implementation will be handed a context from the old version of the global cli which doesn't include telemetry. This again again will cause the CLI to crash. This patch fixes the issue, by falling back to a noop telemetry instance the global CLI doesn't provide it.
- A bit tricky to review, but I've verified that it works locally
- Fix an issue that could occur when using an older version of the CLI globally in combination with a more recent version installed locally
=> fix(sanity): guard against telemetry not provided from older global CLI versions

packages/sanity/src/desk/components/pane/PaneHeaderActionButton.tsx
The field action button had inverted colour scheme. 
Add this to `config` to test: 
```js
document: {
unstable_fieldActions: (prev, {documentType, schema}) => {
return [
...prev,
{
name: 'test',
useAction: () => ({
type: 'group',
title: 'Test',
icon: RobotIcon,
children: [{type: 'action', title: 'test'}],
renderAsButton: true,
}),
},
]
},
}
```
Fixes issue with inverted colour for field action buttons
=> fix(desk): add bleed mode to field action button

packages/@sanity/cli/src/actions/init-project/initProject.ts
Pins `next-sanity` to latest version.
- That installing a vanilla Next.js app + studio works
- That v7 is intended to be the latest version
=> chore(cli): pin next-sanity to v7

packages/sanity/src/core/components/previews/_common/Media.styled.ts
This pull request makes sure that custom icons have the correct sizing in previews.
- Make sure that icons have the correct size
Fix icon size issue in previews
=> fix(core): icon size in previews with custom icon

packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrial.tsx
This defers trial popover visibility until the anchor element is present in the DOM instead of using a 300ms delay, which turns out to not always be enough.
- A bit tricky to test, but I've verified that it works locally
- Fixes occasional wrong placement of free trial popover
=> fix(core): wait until the ref is available before showing trial popover

packages/sanity/src/core/theme/_legacy/theme.ts
Sanity UI v2 introduced the `v2` object into the theme. 
This `v2` is included as part of the studioTheme, which we are spreading by using the defaults in the `buildLegacyTheme` function, but those are the default values, that's the reason why the legacy theme colors were lost.
With this updates, the theme v2 will be generated by the `v0_v2` function that converts v0 to v2 and it won't use the default studio theme v2 values.
Theme works as expected.
update buildLegacyTheme to support custom colors
=> fix(legacy-theme): update buildLegacyTheme to support custom colors

packages/sanity/src/core/config/document/actions.ts, packages/sanity/src/desk/__workshop__/DocumentStateStory.tsx, packages/sanity/src/desk/panes/document/statusBar/dialogs/ConfirmDialog.tsx, packages/sanity/src/desk/panes/document/statusBar/dialogs/ModalDialog.tsx, packages/sanity/src/desk/panes/document/statusBar/dialogs/PopoverDialog.tsx
This PR fixes a regression introduced by Facelift where custom document actions of the `modal` _dialog_ type ([reference](https://www.sanity.io/docs/document-actions-api#037f877ad3f1)) were erroneously using internal ui-components rather than 'vanilla' Sanity UI.
This fix means that custom document actions with `modal` dialogs will now correctly render any supplied footer component, whereas previously they weren't rendering anything at all.
Custom document actions with `modal` dialogs should correctly render footer content.
This can be validated by comparing the custom **Test document modal** document action on the test studio ([before](https://test-studio.sanity.build/test/structure/input-debug;documentActionsTest;05bcc930-5e43-41a0-b48b-432b51878567) and …
=> fix: opt-out of internal studio ui-components for user facing custom document action dialogs

packages/sanity/src/desk/i18n/resources.ts
This PR updates the locale string key for the document restore confirmation message.
Currently, if you try and restore a previous document revision, you'll be greeted with the following:
Updating this key will now display the correct message:
It appears the previous key (`action.restore.confirm-dialog.confirm-discard-changes`) isn't used anywhere throughout the codebase, and its name doesn't align with its value. Possible that it may have been accidentally mangled in a previous rebase?
Restoring a previous document revision should display correct localized text.
N/A
=> fix(i18n): use correct locale string for document restore confirmation

packages/@sanity/vision/src/components/VisionGui.tsx
Fixes https://github.com/sanity-io/sanity/issues/5432
=> fix(vision): use untranslated value for other api version

packages/@sanity/block-tools/src/HtmlDeserializer/rules/gdocs.ts, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocsLists/output.json
This PR preserves strike-through formatting when pasting from Google Docs.
Fixes #5290 
- That text formatted with strike-through is preserved when copy pasting from a Google doc
- Fixed issue with strike-through formatting being lost when copy-pasting from Google Docs into a PTE field
=> fix(block-tools): keep strike-through formatting when pasting from gdocs

packages/sanity/src/core/components/DefaultDocument.tsx
There was an issue with font rendering in iOS16, resulting in a very thin font weight. This seemingly had to do with font variables. This PR adds a separate font-face for each font weight used. 
Before: 
After: 
The font weights on iOS16 in Xcode. 
Fixes font weights in iOS16
=> fix(core): remove variable fonts in global styles

packages/sanity/src/structure/i18n/resources.ts, packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormHeader.tsx
Adds new resource for missing form view title 
The document form view title - if it is missing, it should say `Untitled` in the respective language 
Adds translation to untitled document titles
=> fix(desk): translate when form title is missing

packages/sanity/src/core/studio/GlobalStyle.tsx
This PR fixes the following issues:
- custom scrollbars (in browsers that support them) within text fields wouldn't correctly render RHS borders
- resize handles in text fields (with scroll overflow) would render with an unsightly white box on dark mode
**Before** ([link](https://test-studio.sanity.build/test/structure/input-standard;textsTest;61ead1a7-6a4a-489e-8d02-8564528c2d10)):
**After** ([link](https://test-studio-git-fix-add-custom-resize-icon.sanity.build/test/structure/input-standard;textsTest;61ead1a7-6a4a-489e-8d02-8564528c2d10)):
**More context:**
This is accomplished by rendering a custom SVG (as a Data URI) as a background image. Similar to custom scrollbars, this custom resize handle image is only displayed in webkit browsers.
I don't believe it's possible to accomplish …
=> fix: add custom resize handle icon

packages/sanity/src/core/form/components/formField/FormFieldSet.tsx
This pull request addresses an issue with the left border of fieldsets.
- Is there any situation when we want border radius on the field set?
N/A
=> fix(core): form fieldset border

dev/test-studio/schema/playlist.ts, packages/@sanity/types/src/schema/definition/type/document.ts, packages/@sanity/types/src/schema/types.ts, packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormHeader.tsx
With facelift a new title was introduced to all the documents, this title takes some space and doesn't work well with some custom implementations users have done to the document pane.
With this new flag `__experimental_form_preview_title ` users will be able to opt out from the new title.
Allows users to hide the the large preview title is displayed in the document pane form
=> feat(desk): add __experimental_formPreviewTitle to documents

packages/sanity/src/core/config/prepareConfig.ts
This pull request changes the comments feature from being an opt-in feature to be an opt-out feature by making it enabled by default. 
- Make sure that the `document.unstable_comments.enabled` config works as expected
Make comments enabled by default
=> feat(comments): enable by default

packages/sanity/src/_internal/cli/actions/graphql/deployApiAction.ts, packages/sanity/src/_internal/cli/actions/graphql/extractFromSanitySchema.ts, packages/sanity/src/_internal/cli/commands/graphql/deployGraphQLAPICommand.ts, packages/sanity/test/cli/graphql/__snapshots__/gen3.test.ts.snap, packages/sanity/test/cli/graphql/fixtures/many-self-refs.ts, packages/sanity/test/cli/graphql/gen3.test.ts
We're seeing an exponential slowdown when we are generating graphql schemas for sanity schemas that has many types referering to each other. This PR adds an, opt-in, cache that speeds up generating these schemas. Don't be alarmed by the diff, it's 95% snapshots 😅 
In the test schema case there's a 95% performance gain when generating with the cache:
```
withUnionCache: true:  88 ms
withUnionCache: false: 1732 ms
```
---
There were also some cases of looping over the same objects multiple times, I refactored the code into single loops.
This change should, even with the flag on, generate the same schema. Is there a case where it might not? Any other test cases that might be beneficial?
GraphQL: Add mode to optimize GraphQL deployment when schemas has many self referencing documents
=> Optimize graphql deployment

packages/sanity/src/_internal/cli/util/mockBrowserEnvironment.ts
I ran into issues with the `mockBrowserEnvironment` function when re-using in a different branch.
Setting the format to `'cjs'` enforces that esbuild outputs code compatible with the commonjs module loader used to mock the browser environment on the fly and updating the extensions ensures that those files get ran through esbuild and converted into cjs compatible code.
- Does the graphql command still work? Does this increase compatibility?
Fixes an issue where certain files would not get loaded correctly in the mock browser environment used for GraphQL deploys.
=> fix(cli): update esbuild options for better compat

packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrialButton.tsx, packages/sanity/src/core/studio/components/navbar/navDrawer/ManageMenu.tsx
This PR makes a few minor changes to the free trial buttons:
- These are more inline with facelift styles (using the same sized buttons / hit areas and tooltips)
- Free trial buttons now use tooltips (like all other text-less Studio buttons). These are also now localized.
- Fixes a small issue with buttons that weren't correctly spaced in the mobile nav drawer
Free trial buttons should look like the above, and all tooltips should be localized as expected.
N/A
=> fix: update reverse trial button styles, add tooltips and localize nav button

packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
This PR moves the navbar search button to the LHS (next to the create new button) in order to make it a little more discoverable. Mobile lockup is unchanged. That's it!
That the search button appears on the LHS in the navbar.
Updated search button navbar position to aid discoverability
=> fix: update search button navbar position

packages/sanity/src/core/form/inputs/PortableText/toolbar/Toolbar.tsx
Adds missing aria-label to `Expand editor` button in PTE
=> fix(core): add aria-label to expand PTE button

.github/CODEOWNERS
This PR adds code owners for the following surfaces:
- Search
- 'Visual' components (it's possible that this will include `src/core/components` in future)
- Legacy theming
=> chore: add codeowners for search, theming and visual components

dev/test-studio/schema/debug/deprecatedFields.ts, packages/sanity/src/core/form/components/formField/FormField.tsx, packages/sanity/src/core/form/components/formField/FormFieldHeaderText.tsx, packages/sanity/src/core/form/components/formField/FormFieldSet.tsx, packages/sanity/src/core/form/inputs/BooleanInput.tsx, packages/sanity/src/core/i18n/bundles/studio.ts
Adds a badge for deprecated fields
To test check preview [here](https://test-studio-git-feat-field-deprecation-badge.sanity.build/test/structure/input-debug;deprecatedFields;9e3da168-ae3a-46b6-8359-9befeb3829e7)
- N/A
=> feat(core): add badge for deprecated fields

packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/index.ts, packages/@sanity/block-tools/src/HtmlDeserializer/preprocessors/notion.ts, packages/@sanity/block-tools/src/HtmlDeserializer/rules/index.ts, packages/@sanity/block-tools/src/HtmlDeserializer/rules/notion.ts
This creates a new ruleset for Notion, and handles block decorators for bold/emphasis/italic.
Normally Notion will export semantic HTML, but this behaviour changes when you have only copied a single block.
Then the exported HTML will contain spans with inline styles.
Fixes EDX-818.
- That copy pasting a single block from Notion containing italic, emphasis or bold will be correctly formatted 
- Fixed bold/emphasis/italic formatting in PTE when copying a single block from Notion
=> feat(block-tools): add notion handling for single block decorators

packages/@sanity/block-tools/src/HtmlDeserializer/rules/gdocs.ts, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocs/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocsFirefox/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocsWhitespaceNormalize/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocsWhitespaceRemove/output.json, packages/@sanity/block-tools/test/tests/HtmlDeserializer/gdocsWhitespaceRemoveFirefox/output.json
This updates the regexes we use to detect basic formatting when copy pasting text from Google Docs. In Safari these would be rendered with an extra space between the rule and value.
As part of the work we also discovered that Google Docs by default adds a underline to all links. The logic has been updated to skip underline decorators where the text node is inside a link.
Fixes #5483, fixes #5463 
Fixes EDX-1011
- That pasting from Google Docs to the PTE retains formatting
- That underline decorators is not applied when pasting links
- Fixed an issue in Safari where formatting would not carry over when copy pasting from Google Docs in Safari
- Fixed an issue where copy pasting links from Google Docs would have a underline decorator applied
=> fix(block-tools): more robust formatting detection on copy paste in Safari

packages/sanity/package.json, yarn.lock
* remove problematic peer dependency declarations ([91c1f7d](https://github.com/sanity-io/visual-editing/commit/91c1f7d98748f8d82c873420cab60304bfade518))
* **deps:** update dependency @sanity/client to ^6.11.1 ([#666](https://github.com/sanity-io/visual-editing/issues/666)) ([487d552](https://github.com/sanity-io/visual-editing/commit/487d552ffdef039ab9807a440df3b1a66b9fa064))
* **deps:** Update dependency framer-motion to ^10.18.0 ([#669](https://github.com/sanity-io/visual-editing/issues/669)) ([63496aa](https://github.com/sanity-io/visual-editing/commit/63496aaa671233929bec191b39fc49b86e80b65b))
* handle race condition when `rev` and `id` search params both change ([2b1288c](https://github.com/sanity-io/visual-editing/commit/2b1288c5a74a218133e260f824d06785c5819df4))
* **deps:** …
=> fix(deps): update dependency @sanity/presentation to v1.5.3

.babelrc
This PR allows us to use JSX without importing react. Seems like the last thing not to support this was just our jest tests which uses babel to compile on the fly.
Later we should open a PR that removes all unused react imports as well but that can come at a later time.
- Everything still work? Does this have any effect on the build system?
N/A
=> fix(test): use `"runtime": "automatic"` for `"@babel/preset-react"`

packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
The `AuthStore.logout` method doesn't currently pass the token to the `logout` API if cookieless auth is used. Therefore, the token is only invalidated if cookie-based auth is used.
This change adds any cookieless token present for the project to the `Authorization` header of the `logout` request, so the token is invalidated both for cookie-based and cookieless auth.
Signing out of the Studio should invalidate the token, regardless of whether cookie-based or cookieless auth is used.
=> fix(core): include cookieless auth token in logout request if it exists

packages/@sanity/cli/src/cli.ts
Caps the args list we log at max 10 entries
I'm wondering if we could also remove the (duplicated) log statement, see my comment below.
n/a
=> fix(cli): telemetry: only log first 10 elements in args array

packages/sanity/src/structure/i18n/resources.ts, packages/sanity/src/structure/panes/document/statusBar/DocumentStatusPulse/DocumentStatusPulse.tsx
Fixed two missing translations.
=> chore(i18n): fixed missing translations with document status pulse

packages/@sanity/cli/test/dev.test.ts, packages/@sanity/cli/test/shared/devServer.ts, packages/@sanity/cli/test/shared/environment.ts
We've experienced some flakiness in the CLI dev server tests when they run in CI. This appears to be caused by port collisions that can occur when running the tests using multiple versions of node simultaneously.
The dev server now uses a different port depending on whether it's running in node LTS or node current.
That the CLI tests pass in CI.
=> test(cli): fix flaky dev server test

packages/sanity/src/core/form/inputs/PortableText/hooks/usePortableTextMembers.tsx
Regular text blocks must be included in the PT-member array when they are focused too, or they can't be focused by pointing the focusPath to them if none of the other requirements are met.
This will fix an issue where text blocks cannot be focused by setting the `focusPath` from the outside.
Visual editing can take you to a specific block when working on a published document.
Fix a bug where clicking to edit in the presentation mode didn't focus the relevant block in the Portable Text Editor.
=> fix(form/inputs): include focused text blocks in PT-members array

packages/sanity/src/core/studio/components/navbar/resources/ResourcesButton.tsx
This PR updates the help + resources button to use the correct icon (`HelpCircleIcon`)
The icon for help + resources should look correct (and as it was prior to facelift)
Fixes an issue where the help and resource button was using the incorrect icon
=> fix: use help icon for help + resources button

packages/sanity/src/core/form/components/withFocusRing/withFocusRing.ts, packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
This PR fixes a tiny visual issue where the focus ring in array items were appearing slightly cropped and weren't using the correct radius.
That the focus ring for array items appear in full.
N/A
=> fix: ensure list array card focusRing isn't cropped

packages/sanity/package.json, yarn.lock
* enable new URL sharing menu ([83fe01f](https://github.com/sanity-io/visual-editing/commit/83fe01fbe4ee3128a49401e2882e04463b5b1540))
* always use the same `@sanity/ui` version as `sanity` ([e61312d](https://github.com/sanity-io/visual-editing/commit/e61312d9a2d8ebcce8f0b06a62b0bcd5ca42522f))
* **presentation:** allow forward navigation ([#686](https://github.com/sanity-io/visual-editing/issues/686)) ([f9099e8](https://github.com/sanity-io/visual-editing/commit/f9099e88f5d3f4158fbe26737e0b1c6987df29f9))
* **presentation:** derive params from routerState to fix focus ([175efe0](https://github.com/sanity-io/visual-editing/commit/175efe0a3881c288c8ea30086e427a1de21c60cd))
* remove MetaBanner as it's now part of `sanity` ([c920188](https://github.com/sanity-io/visual-editing/commit/c920188859 …
=> fix(deps): update dependency `@sanity/presentation` to `v1.6.0`

packages/sanity/src/structure/components/structureTool/StructureTitle.tsx, packages/sanity/src/structure/i18n/resources.ts
In the structure tool, the document title was not localized when showing new documents (`New author`) or documents where the preview title cannot be resolved (`Untitled`). This PR introduces new i18n resource keys for the two cases.
- Creating a new document still shows "New <schemaTypeTitle>" in document title (eg browser tab)
- Second case is not trivial to reproduce, so carefully read the code - should be safe to assume it has the same behavior as before, only localizable
- Made the browser document title localizable by locale plugins
=> feat(i18n): add i18n resources for browser document title

packages/sanity/src/core/config/auth/types.ts, packages/sanity/src/core/config/types.ts, packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts, packages/sanity/src/core/store/_legacy/authStore/index.ts, packages/sanity/src/core/store/_legacy/authStore/utils/asserters.ts
When initialising `AuthStore`, Studio only attempts to read the cookieless auth token from localStorage if the login method is `dual`. If the login method is `token` (e.g. cookie-based auth is explicitly disabled), Studio **does not** attempt to read the cookieless auth token from localStorage. This means that the active session is not restored when Studio initialises (e.g. when reloading the host webpage after signing in).
[The fix is quite small](https://github.com/sanity-io/sanity/pull/5497/commits/5b3afd39d1acd10f026477c97757d8a0bcaaceb6). As part of this work, I've also taken care of a few small chores.
Configure a Studio workspace to authenticate using the `token` method:
```ts
{
auth: {
loginMethod: 'token',
},
}
```
Sign into the Studio, and then reload the webpage. The active …
=> fix(core): `token` login method session restoration

.eslintrc.cjs, packages/sanity/src/core/form/components/formField/FormFieldBaseHeader.tsx, packages/sanity/src/core/form/inputs/PortableText/Editor.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx, packages/sanity/src/core/form/inputs/files/ImageInput/ImageActionsMenu.tsx, packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItemContextMenu.tsx, packages/sanity/src/structure/comments/src/components/pte/comment-input/CommentInputInner.tsx, packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx, packages/sanity/src/structure/panes/document/document-layout/DocumentLayout.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx, packages/sanity/src/structure/panes/documentList/DocumentListPaneHeader.tsx, packages/sanity/src/ui-components/index.ts, packages/sanity/src/ui-components/tooltipDelayGroupProvider/TooltipDelayGroupProvider.tsx, packages/sanity/src/ui-components/tooltipDelayGroupProvider/index.ts
Adds internal `<TooltipDelayGroupProvider>` to ui-components, forcing delay consistency for all uses of tooltips and delay groups.
Refactors uses of `<TooltipDelayGroupProvider>` to consume from internal ui-components.
Tooltip delay groups still work as expected. 
Refactors uses of `<TooltipDelayGroupProvider>` to consume from internal ui-components.
=> fix(ui-components): add TooltipDelayGroupProvider to ui-components

packages/sanity/src/core/hooks/useFeatureEnabled.ts
Some features, such as Comments, are only available on specific plans. To determine whether some features should be rendered in Studio, we make an API call to get a list of the project's available features. If this API call fails, currently, an error is thrown and displayed in a toast. This pull request ensures that if an error is thrown, we catch it and instead return an empty list of features.
- Make sure that the toast is not appearing when an error is thrown
N/A
=> fix(core): error handling in `useFeatureEnabled`

package.json, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/types.ts, packages/sanity/src/core/form/inputs/PortableText/toolbar/ActionMenu.tsx, packages/sanity/src/core/i18n/.eslintrc, packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrialButton.tsx, packages/sanity/src/core/studio/components/navbar/search/SearchButton.tsx, packages/sanity/src/structure/panes/document/document-layout/DocumentLayout.tsx, packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormHeader.tsx, packages/sanity/src/ui-components/dialog/Dialog.tsx, yarn.lock
The only place we should be importing from `i18next`/`react-i18next` is from the `i18n` folder, as the usage of it is an implementation detail and may change with time. This PR upgrades our `@sanity/eslint-config-i18n` module to enforce this, and also fixes the locations in the codebase where we were not currently following this pattern.
Things still works/builds.
ESLint passes, and the tests for the ESLint config/plugin has been updated in the respective repos.
None
=> fix(i18n): import i18n utils from relative path/sanity module

.github/CODEOWNERS
Adds growth as codeowners for `*.telemetry.ts` files.
n/a
=> chore(codeowners): add growth team as owners of telemetry definitions

packages/sanity/src/ui-components/__workshop__/ButtonStory.tsx, packages/sanity/src/ui-components/__workshop__/DialogStory.tsx, packages/sanity/src/ui-components/__workshop__/MenuButtonStory.tsx, packages/sanity/src/ui-components/__workshop__/MenuGroupStory.tsx, packages/sanity/src/ui-components/__workshop__/MenuItemStory.tsx, packages/sanity/src/ui-components/__workshop__/PopoverStory.tsx, packages/sanity/src/ui-components/__workshop__/TabStory.tsx, packages/sanity/src/ui-components/__workshop__/TooltipDelayGroupProviderStory.tsx, packages/sanity/src/ui-components/__workshop__/TooltipStory.tsx, packages/sanity/src/ui-components/__workshop__/index.ts, packages/sanity/src/ui-components/tab/Tab.tsx
This PR adds some basic workshop stories outlining usage guidelines for internal components, and is intended to be expanded on in future.
This also simplifies the internal `<Tab>` component and removes the `size` prop, since these are only ever rendered in a single size throughout.
Workshop stories are accessible and make sense.
These stories act as a simple reference and facilitate spot testing.
N/A
=> chore: add ui component workshop stories, simplify internal tab component

packages/@sanity/export/package.json, packages/@sanity/export/src/tryParseJson.js, packages/@sanity/migrate/package.json, packages/@sanity/migrate/src/_exports/index.ts, packages/@sanity/migrate/src/it-utils/__test__/json.test.ts, packages/@sanity/migrate/src/it-utils/json.ts, packages/@sanity/migrate/src/it-utils/ndjson.ts, packages/@sanity/migrate/src/runner/dryRun.ts, packages/@sanity/migrate/src/runner/run.ts, packages/@sanity/migrate/src/sources/fromExportEndpoint.ts, packages/@sanity/util/.gitignore, packages/@sanity/util/exports/createSafeJsonParser.ts, packages/@sanity/util/package.json, packages/@sanity/util/src/createSafeJsonParser.ts, packages/@sanity/util/test/createSafeJsonParser.test.ts, packages/@sanity/util/turbo.json, packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
When streaming from the Export HTTP API, NDJSON lines may be interrupted by an error object. Handling for this scenario was already implemented in #1787, exclusively for the exporter CLI. I've moved the safe JSON parser to `@sanity/util` so that it can be used by both `@sanity/export` and `@sanity/migrate`.
- Exporting datasets using the CLI works correctly.
- Running migrations using the CLI works correctly.
Build the project, run the `dataset export` and `migration run` CLI commands.
I've added tests for the JSON parser:
```
yarn test packages/@sanity/util/test/createSafeJsonParser.test.ts
```
=> feat(migrate): use safe JSON parser when streaming from Export HTTP API

packages/@sanity/types/src/validation/types.ts, packages/sanity/src/core/validation/Rule.ts
Related to #5551.
This fixes the types for `rule.min` and `rule.max` to include strings because the date validator allows them. This was just an oversight on types when this part of the codebase was converted to TS (by me lol)
Can you use `rule.min()` and `rule.max()` with a string now?
Re-ran `npm run type-check` and tried out using a string in rule.min and it worked as expected
- Fixes an type bug where `Rule.min` and `Rule.max` did not allow strings
=> fix(validation): update min and max to include string for dates

packages/@sanity/util/src/legacyDateFormat.ts, packages/sanity/src/core/validation/validators/dateValidator.ts, packages/sanity/test/validation/__snapshots__/dates.test.ts.snap, packages/sanity/test/validation/dates.test.ts
=> fix(core): fix type issues and add tests for datetime input

packages/sanity/src/structure/comments/src/hooks/use-comment-operations/createOperation.ts, packages/sanity/src/structure/comments/src/hooks/use-comment-operations/useCommentOperations.ts
This pull request fixes an issue introduced in `v3.26.0` when the comments reactions feature was added. The issue is that when the first comment is made in a project without an addon dataset, the dataset isn't created, and the comment isn't posted.
- Ensure the addon dataset is created and the comment is posted when the first comment is made in a project without an addon dataset.
Fixes issue introduced in `v3.26.0` where, upon the first comment in a project lacking an addon dataset, the dataset fails to be created, and the comment remains unposted.
=> fix(comments): addon dataset creation

packages/@sanity/export/src/AssetHandler.js
We are experiencing that our export assets endpoints hangs up the connections, and for some reason the CLI is trying to reuse the dead connection. This PR adds more retry mechanisms to download assets.
```
$ npm run build
$ cd dev/test-studio
$ DEBUG=sanity* ../../packages/@sanity/cli/bin/sanity dataset export test --overwrite
```
=> Improve asset export retrying 

dev/test-studio/migrations/cleanup-empty/cleanup-empty-values.ts, dev/test-studio/migrations/convert-string-to-pt/convert-string-to-pte.ts, dev/test-studio/migrations/rename-location-to-address/index.ts, dev/test-studio/migrations/sync-from-spreadsheet/sync.ts, packages/@sanity/migrate/src/fetch-utils/endpoints.ts, packages/@sanity/migrate/src/runner/dryRun.ts, packages/@sanity/migrate/src/runner/normalizeMigrateDefinition.ts, packages/@sanity/migrate/src/runner/run.ts, packages/@sanity/migrate/src/sources/fromExportEndpoint.ts, packages/@sanity/migrate/src/types.ts, packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Adds support for passing an array of strings to `documentType`
It looks like the documentType was never sent to the export endpoint so this makes it so it always sends it and supports for both `string` and `string[]` 
Need a test framework which is larger task in itself
- N/A
=> feat(migration): support passing an array of documentTypes to migration

packages/@sanity/migrate/src/runner/normalizeMigrateDefinition.ts, packages/@sanity/migrate/src/types.ts
Adds support for async hooks in migration nodes for instance you can do the following thing
```ts
export default defineMigration({
name: 'Cleanup empty values',
documentType: 'playlist',
migrate: {
async object(node) {
if (Object.keys(node).filter((k) => !k.startsWith('_')).length) {
await setTimeout(() => console.log('waiting object'), 1000)
return unset()
}
},
async array(node) {
if (node.length === 0) {
await setTimeout(() => console.log('waiting array'), 1000)
return unset()
}
},
async string(node) {
if (node.length === 0) {
await setTimeout(() => console.log('waiting string'), 1000)
return unset()
}
},
},
})
```
If everything still works
N/A
=> feat(migration): support async hooks in migration nodes

.eslintrc.cjs, packages/sanity/playwright-ct/tests/comments/CommentInputStory.tsx, packages/sanity/src/structure/comments/i18n/index.ts, packages/sanity/src/structure/comments/i18n/resources.ts, packages/sanity/src/structure/comments/plugin/field/CommentsFieldButton.tsx, packages/sanity/src/structure/comments/plugin/index.ts, packages/sanity/src/structure/comments/plugin/inspector/CommentsInspector.tsx, packages/sanity/src/structure/comments/plugin/inspector/CommentsInspectorFeedbackFooter.tsx, packages/sanity/src/structure/comments/plugin/inspector/CommentsInspectorHeader.tsx, packages/sanity/src/structure/comments/plugin/inspector/index.ts, packages/sanity/src/structure/comments/src/components/CommentDeleteDialog.tsx, packages/sanity/src/structure/comments/src/components/list/CommentThreadLayout.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItem.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItemContextMenu.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItemLayout.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListStatus.tsx, packages/sanity/src/structure/comments/src/components/list/CreateNewThreadInput.tsx, packages/sanity/src/structure/comments/src/components/mentions/MentionsMenu.tsx, packages/sanity/src/structure/comments/src/components/mentions/MentionsMenuItem.tsx, packages/sanity/src/structure/comments/src/components/onboarding/CommentsOnboardingPopover.tsx, packages/sanity/src/structure/comments/src/components/pte/blocks/MentionInlineBlock.tsx, packages/sanity/src/structure/comments/src/components/pte/comment-input/CommentInputDiscardDialog.tsx, packages/sanity/src/structure/comments/src/components/pte/comment-input/CommentInputInner.tsx, packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsBar.tsx, packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsMenu.tsx, packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsMenuButton.tsx, packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsUsersTooltip.tsx
This PR adds a resource file to the comments plugin with all the strings and localizes every string in the comments plugin. 
All strings for the comments plugin feature 
Adds localization to the comments plugin
=> fix(comments): localize all strings

packages/@sanity/types/src/validation/types.ts, packages/sanity/src/core/studio/StudioTelemetryProvider.tsx, packages/sanity/src/core/validation/Rule.ts, packages/sanity/src/structure/documentActions/DuplicateAction.tsx
This change adds `userAgent` and `screen` properties to the user identify call for telemetry.
- In a telemetry enabled studio, check that calls to the telemetry intake (`/intake/batch`) includes user agent and screen properties
n/a
=> chore(core): include user agent and screen density in telemetry calls

packages/sanity/src/_internal/cli/actions/validation/validateAction.ts, packages/sanity/src/_internal/cli/commands/documents/validateDocumentsCommand.ts
Removes Beta Copy for `sanity documents validate` command
When you checkout the branch and run `yarn build && cd dev/test-studio && npx sanity documents validate --help` it does not show beta copy
N/A
N/A (Need to double check)
=> chore(cli): remove beta copy from documents validate command

packages/sanity/playwright-ct/tests/comments/CommentInput.spec.tsx, packages/sanity/src/structure/comments/src/components/pte/blocks/MentionInlineBlock.tsx
Added skeleton to loading state when mentioning users in comment. 
The test for the hardcoded `@Loading` text when it is loading is no longer applicable, as this also created some issues with the current localisation work that is in progress for comments 
The loading state when mentioning a user in a comment
=> fix(src): add textskeleton to loading state of mentions

packages/sanity/src/_internal/cli/threads/validateDocuments.ts
Fixes issue with logic of filtering out system documents when running `sanity documents validate` 
To test it on the branch run `yarn build && cd dev/test-studio && npx sanity documents validate` and check if there are any system documents in there
N/A
=> fix(validation): filter system documents when running validation

packages/@sanity/migrate/src/runner/normalizeMigrateDefinition.ts
`documentTypes` should act like a filter, just like ?types=foo,bar does on the export endpoint (no types=all documents)
=> fix(migrate): run migration against all documents if documentTypes is omitted

packages/sanity/src/_internal/cli/commands/migration/createMigrationCommand.ts, packages/sanity/src/_internal/cli/commands/migration/listMigrationsCommand.ts, packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Various consistency fixes,
- consistent use of migration _title_ instead of Migration _name_
- consistent use of migration _id_ instead of migration _name_
=> fix(migrate): various naming consistency fixes

packages/sanity/src/_internal/cli/commands/migration/createMigrationCommand.ts, packages/sanity/src/_internal/cli/commands/migration/listMigrationsCommand.ts, packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Smaller error handling improvements, listing available migrations if you run `sanity migration run` without specifying migration id
=> fix(sanity): improve error handling on 'sanity migration run' without id

packages/sanity/src/core/studio/StudioTelemetryProvider.tsx
Telemetry currently logs `undefined` as the name for plugins without a name. This fallbacks to `<unnamed>` instead.
n/a
n/a
=> fix(studio): fallback to <unnamed> when logging installed plugins

packages/@sanity/migrate/src/runner/dryRun.ts, packages/sanity/src/_internal/cli/actions/validation/reporters/prettyReporter/formatDocumentValidation.ts, packages/sanity/src/_internal/cli/commands/migration/prettyMutationFormatter.ts, packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts, packages/sanity/src/_internal/cli/commands/migration/utils/mutationFormatter.ts, packages/sanity/src/_internal/cli/util/tree.ts
This branch adds pretty formatting when running migrations (both in dry-run and commit mode). This uses the same tree style report that is used when reporting document validation results.
- Pretty formatting looks good when running migrations.
- Validation output is still correct (the tree generator code has been abstracted in this branch).
- Run some migrations in dry-run and commit mode.
- Run some document validation checks.
=> feat(cli): add pretty mutation formatting to migration runner

packages/sanity/src/_internal/cli/actions/validation/reporters/jsonReporter.ts, packages/sanity/src/_internal/cli/actions/validation/reporters/ndjsonReporter.ts, packages/sanity/src/_internal/cli/actions/validation/reporters/prettyReporter/__tests__/formatDocumentValidation.test.ts, packages/sanity/src/_internal/cli/actions/validation/reporters/prettyReporter/formatDocumentValidation.ts, packages/sanity/src/_internal/cli/actions/validation/reporters/prettyReporter/prettyReporter.ts, packages/sanity/src/_internal/cli/actions/validation/reporters/prettyReporter/util.ts, packages/sanity/src/_internal/cli/threads/__tests__/validateDocuments.test.ts, packages/sanity/src/_internal/cli/threads/validateDocuments.ts
- Adds `intentUrl` to the results of `sanity documents validate --format json` and `--format ndjson`
- Fixes an edge case where there is an unnecessary leading slash in the intentUrl
- Fixes the logic in `validateDocument.test.ts` that failed to catch the documents with `system.` types to show up bug.
- Fixes a bug where valid documents would be reported in `sanity documents validate --format json`
Take a look at the logic and ensure nothing else changes.
- I ran the build and tried out the command for myself.
- Includes `intentUrl` in `json` and `ndjson` formats for `sanity documents validate`
- Fixes a bug where valid documents would be reported in `sanity documents validate --format json`
=> feat(cli): add `intentUrl` to `json` and `ndjson` reporters

packages/@sanity/migrate/package.json, packages/@sanity/migrate/src/runner/dryRun.ts, packages/@sanity/migrate/src/runner/run.ts, packages/@sanity/migrate/src/runner/runFromArchive.ts, packages/@sanity/migrate/src/runner/utils/client-concurrency-limiter/ConcurrencyLimiter.ts, packages/@sanity/migrate/src/runner/utils/client-concurrency-limiter/README.md, packages/@sanity/migrate/src/runner/utils/client-concurrency-limiter/createClientConcurrencyLimiter.ts, packages/@sanity/migrate/src/runner/utils/createFilteredDocumentsClient.ts, packages/@sanity/migrate/src/runner/utils/limitClientConcurrency.ts, packages/@sanity/migrate/src/types.ts, packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
- Moves `filtered` document methods (getDocument(), getDocuments(), query() to a separate `filtered`-key to better communicate their limitations
- Provides a client instance with limited concurrency on the migration context.
=> refactor(migration): move filtered methods to own key, provide a client on migration context

packages/@sanity/migrate/src/runner/dryRun.ts, packages/@sanity/migrate/src/runner/run.ts, packages/@sanity/migrate/src/runner/runFromArchive.ts, packages/@sanity/migrate/src/runner/utils/createContextClient.ts, packages/@sanity/migrate/src/types.ts
The migration context is currently called with a full client instance, including methods to mutate documents. Calling these during a migration is a bad idea, so this PR removes them from the interface, and also throws an error if they are accessed.
=> Limit access to client methods during a migration

packages/sanity/src/_internal/cli/util/mockBrowserEnvironment.ts
The following adds minimal support for `import.meta.env` inside of the mock browser environment used in the CLI.
Does it work?
I added an import.meta.env usage in the test-studio and ran the command.
- Fixes a bug that caused uses of `import.meta.env` to break the mock browser environment used in the CLI.
=> fix(cli): add support for `import.meta.env`

packages/@sanity/migrate/src/mutations/asserters.ts, packages/@sanity/migrate/src/runner/normalizeMigrateDefinition.ts
Last one from me today 🤞🏼 
This makes sure any node patch returned from a visitor-style migration is relative to the node path itself.
=> fix(migrate): scope node path to the current node

packages/sanity/src/core/studio/components/navbar/home/HomeButton.tsx
Fixes #5582, turns out the `__unstable_focusRing` prop wasn't needed as the styled component was already setting up `&:focus-visible` styling and using the same `focusRingStyle` helper as `<Card>` is when `__unstable_focusRing` is used.
Also refactored out of needing to use `import {css} from 'styled-components'`.
<kbd>tab</kbd>-ing to the Home Button should continue to show a focus outline.
No styling regressions should happen from this PR.
fix: remove `__unstable_focusRing` unknown forwarded prop warning
=> fix: remove `__unstable_focusRing` unknown forwarded prop warning

packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Toolbar.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ToolbarStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/utils/TestForm.tsx, packages/sanity/src/core/form/inputs/PortableText/Editor.tsx, packages/sanity/src/core/form/inputs/PortableText/toolbar/ActionMenu.tsx, packages/sanity/src/core/form/inputs/PortableText/toolbar/InsertMenu.tsx, packages/sanity/src/core/form/inputs/PortableText/toolbar/Toolbar.tsx
This PR updates PTE Toolbars to conditionally collapse at smaller element widths _only_ when displayed in a `<FormBuilder>` instance with `id="root"` (the default ID assigned within the document pane).
**Current behaviour:**
https://github.com/sanity-io/sanity/assets/209129/681ae41e-56a3-45a9-a956-a54c558098b2
**The problem:**
https://github.com/sanity-io/sanity/assets/209129/3929ef4b-5ff8-43dc-8e77-a9fc29e85271
**Approach:**
- We only apply this behaviour when the form builder context within the current PTE component has `id === "root"` (the default)
- This felt like the simplest option that avoids adding extra layout-specific props to `<FormBuilder>`. 
- It felt reasonable to add an extra `FormBuilderContext` dependency in `Editor.tsx`, given that PTE objects are also dependent on this. …
=> fix: only fully collapse PTE toolbars in 'root' FormBuilder instances

packages/@sanity/cli/src/commands/docs/docsCommand.ts, packages/sanity/src/core/studio/components/navbar/workspace/constants.ts
* Updated which URL is opened by `sanity docs`
* Removed a reference to v3 preview beta in `create-sanity` module README
* updated a workspace docs URL
Please review that the URLs are as expected
=> chore: remove outdated beta docs URLs

packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Updated options help text to align with usage example
=> fix(cli): update migration run usage text

packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormHeader.tsx
Pretty-fies document titles
CSS
I have tested this by editing inline styles of an existing Studio to double-check the desired outcome of prettier titles.
Balanced text in document titles
=> feat: apply text balance to document titles

package.json, packages/groq/.depcheckignore.json, scripts/depcheck.ts, yarn.lock
Updates depcheck to `1.4.7`. 
**Why change the script changed?**
- There seems to be function signature change
- `1.4.4` fixes an issue where `.cjs` and `.mjs` files are checked now by depcheck. The problem is the groq tests use node assert and depcheck doesn't have a parser for that so it's easier to just ignore that since it's just referencing itself.  
If the changes makes sense
N/A
N/A
=> chore(deps): update dependency depcheck to ^1.4.7

packages/@sanity/migrate/src/runner/dryRun.ts, packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
This branch unifies the way migration dry runs are executed, regardless of whether the export endpoint or an archive is used as a source. The `dryRun` runner now accepts an optional export path, and the CLI formats output for all dry runs the same.
- The output when dry running migrations is consistent, regardless of whether the `--from-export` flag is used.
- Is the output okay?
=> feat(cli): improve reporting when dry running from export

packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts
In #5440, released in `v3.24.1`, the debug URL secrets feature broke.
When using `sanity/presentation` it's possible to [view generated URL secrets](https://github.com/sanity-io/visual-editing/tree/main/packages/preview-url-secret#debugging-generated-secrets).
On versions `3.23.4` and older it works fine:
Updating to `v3.24.1`, or all the way up to `v3.27.1`, then the list is empty:
The regression fix shouldn't cause further regressions. For example it's not desirable that url preview secrets shows up in the global search. We just want a way for it to show up when the debug plugin is added to the config:
```ts
import { defineConfig } from 'sanity'
import { debugSecrets } from '@sanity/preview-url-secret/sanity-plugin-debug-secrets'
// ... other options …
```
=> fix: regression caused by #5440

packages/sanity/src/_internal/cli/commands/migration/createMigrationCommand.ts, packages/sanity/src/_internal/cli/commands/migration/listMigrationsCommand.ts, packages/sanity/src/_internal/cli/commands/migration/prettyMutationFormatter.ts, packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts, packages/sanity/src/_internal/cli/commands/migration/utils.ts, packages/sanity/src/_internal/cli/commands/migration/utils/mutationFormatter.ts, packages/sanity/src/_internal/cli/commands/migration/utils/resolveMigrationScript.ts
When running `sanity migration list`, it would not include migrations defined as `migrations/some-migration.ts` and similar, only those in directories. This PR fixes that.
Also snuck in some code cleanup:
- Clean up after esbuild-register once done using it
- Sorting imports and using type-only imports where possible
- Use `chalk` from context where possible (I see there are other ocurences in other commands, but lets address later)
- Aligned and reused the logic for finding defined migrations, use them across list and run commands
- Moved the `utils.ts` file into the `utils` folder and gave it a descriptive name
- `sanity migration list` works both with `migrations/someFile.ts` and `migrations/someMigration/index.ts`
- `sanity migration run <id>` works both with `migrations/someFile.ts` …
=> fix(migration): list file-based migrations in list command

packages/sanity/src/core/form/components/formField/FormFieldHeaderText.tsx, packages/sanity/src/core/form/inputs/BooleanInput.tsx, packages/sanity/src/core/studio/Studio.test.tsx
This branch improves vertical alignment in boolean fields. It uses CSS size containment to prevent the block size of elements appended to field labels (such as the deprecated field badge) affecting the intrinsic block size of the label.
Closes #5579.
- Does the vertical alignment in boolean fields look better?
- Does general field rendering still look correct?
- Take a look at the Test Studio. In particular, booleans (`/test/structure/input-standard;booleansTest`).
Improve vertical alignment of boolean fields.
=> fix(form): preserve intrinsic block size of field labels

packages/sanity/src/structure/i18n/resources.ts, packages/sanity/src/structure/panes/document/DocumentOperationResults.tsx
This PR adds the document title name to the toast messages that appear when you publish or unpublish a document. 
It truncates the title if it is above 25 characters. 
The toast messages that appear for document actions
=> fix(src): add document title to publosh/unpublish success message in toast

dev/test-studio/schema/debug/fieldsets.js, dev/test-studio/schema/standard/objects.tsx, packages/sanity/src/core/form/components/formField/FormFieldSet.tsx, packages/sanity/src/core/form/components/formField/styles.ts, packages/sanity/src/core/form/inputs/ObjectInput/ObjectInput.styled.tsx, packages/sanity/src/core/form/inputs/ObjectInput/ObjectInput.tsx, packages/sanity/src/core/studio/Studio.test.tsx
Fixes alignments of columnar fieldsets/objects. When some objects/fields have a description, the alignments seemed off. 
Have added `align-items: flex-end` to the `Grid`. 
Make sure it looks as expected in debug inputs -> fieldsets test 
Fixes alignment of fieldsets/objects
=> fix(core): fix aligning of columnar objects/fieldsets

packages/@sanity/migrate/src/fetch-utils/endpoints.ts, packages/@sanity/migrate/src/runner/run.ts
Sets visibility to `async` when submitting mutations from `sanity migraiton run`.
- Any considerations I'm missing? I based it on the visibility used by `sanity import`
n/a
=> fix(migrate): submit mutations with visibility=async

package.json, packages/sanity/package.json, packages/sanity/src/_internal/cli/commands/migration/createMigrationCommand.ts, yarn.lock
Removes `mkdirp` package and uses fs to create the directory.
Also removes `mkdirp` and related types from package.json. Search does not yield any other usage.
migration create command still works as expected
- Fixes an issue where migration command would error in some instances
=> fix(migration): fixes an issue where migration command would error sometimes

packages/sanity/src/structure/structureBuilder/documentTypeListItems.ts
This PR removes the check to show icons from `S.documentTypeList()`. Like all other list types, `S.documentTypeList()` will now fall back to showing icons by default, regardless of preview parameters set. 
In the past, customers were sometimes surprised when they simply defined a `select` selection in a `preview` parameter of a schema type without a `media` parameter, like:
```js
export default defineType({
name: 'myType',
fields: [...],
preview: {
select: {
title: 'title',
subtitle: 'description'
}
}
})
```
which would change the list view to an icon-less one. However, _not_ setting a `media` parameter in a `prepare` return object still resulted in an icon being shown, which seems inconsistent.
Because an icon or media preview still shows up in all other kinds of desk …
=> fix(core): add icon display as default to documentTypeList

packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx, packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx, packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx, packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx, packages/sanity/src/core/form/inputs/PortableText/object/InlineObjectToolbarPopover.tsx, packages/sanity/src/core/i18n/bundles/studio.ts
Adding some accessibility labels to pte objects
Adds some accessibility labels to PTE objects
=> fix(core): adding accessibility labels to pte objects

packages/@sanity/cli/src/actions/init-project/initProject.ts
A recent change to the CLI added user prompts when attempting to use a nonexistent coupon (`--coupon`) or a plan (`--project-plan`), however, this change did no respect unattended mode (`-y, --yes`) and would prompt the user regardless. 
- Initialising a project using a nonexistent coupon or plan in unattended mode:
- `init -y --project-plan beep`
- `init -y --coupon boop`
- Does the command proceed without prompting the user?
=> fix(cli): respect unattended mode

packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
Centered the navigation menu in Studio
Edit: After a discussion with @robinpyon, the navigation menu is now only centering on large screens (1200px and up).
Check that the navigation menu is centered independently from surrounding items
- Verified that layout does not break when adding a bunch of menu items
- Verified that nav stays the same on breakpoints below 1200px
- Centered navigation in Studio
=> fix(studio): center studio nav

packages/@sanity/migrate/src/fetch-utils/endpoints.ts, packages/@sanity/migrate/src/runner/run.ts
Sets `autoGenerateArrayKeys` to `true` when submitting mutations from the `sanity migraiton run` CLI command.
Did a quick round of manual testing with a Studio having a document open while a mutation ran that added non-keyed array items to an array field in it, and didn't see any issues.
- Adding objects without unique `_key`s to an array during a content migration will now automatically generate unique `_key`s
=> feat(migrate): use autoGenerateKeys=true when submitting mutations

packages/@sanity/cli/src/util/noSuchCommandText.ts, packages/sanity/src/_internal/cli/commands/index.ts, packages/sanity/src/_internal/cli/commands/schema/schemaGroup.ts
Adds `schema` command to help list
running `sanity help` shows the `schema` command in the list with the correct copy
N/A
N/A
=> chore(cli): add schema command to help list

packages/@sanity/vision/src/SanityVision.tsx, packages/@sanity/vision/src/components/VisionGui.tsx, packages/@sanity/vision/src/containers/VisionErrorBoundary.tsx, packages/@sanity/vision/src/util/localStorage.ts, packages/@sanity/vision/src/util/validateApiVersion.ts
When pasting certain URLs (see testing section for one), vision crashes, and worse - stores a value to localStorage that makes it impossible to get vision working again unless you clear localStorage.
This PR:
- Fixes the paste handling (by persisting the "raw" (_string_) parameters instead of a parsed representation
- Fixes handling pasting of a URL with `v1` not being treated as a valid API version
- Adds stricter checking of the localStorage value
- Wraps in an error boundary that (upon one failed retried render) offers to clear cache (localStorage) and retry
While I hope we do not have any more mismatches in expected vs actual values (and thus the error boundary should not be needed), there's always the odd chance that someone already has an invalid localStorage value, or that it is …
=> fix(vision): prevent crashes when pasting certain URLs

packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
Internal TS reference for PortableTextInput customisation returns a 404.
https://www.sanity.io/docs/portable-text-features
This PR updates to the correct place in the documentation.
https://www.sanity.io/docs/customizing-the-portable-text-editor
update PortableTextInput doc reference
=> fix(core): update PortableTextInput doc reference

packages/sanity/src/structure/comments/src/context/upsell/CommentsUpsellProvider.tsx
Fixes #5697
- Fixed an issue where a comments-related request could trigger an uncaught error dialog being displayed
=> fix(comments): catch and suppress errors from comments upsell

package.json
This changes lint-staged config to automatically fix problems through eslint.
- That commiting a staged file with issues like formatting mistakes etc - anything that can be fixed with eslint --fix - is automatically applied.
=> chore: apply auto eslint fixes with lint-staged

packages/@sanity/cli/test/basics.test.ts
The CLI test suite have been running with a session token for a test user with a registered email. This token has a short expiry and causes the test suite to suddenly start failing when the token expires. Using a robot token works, but one of the assertions for `sanity debug` output fails because the email of the roboto token is `null`. This fixes the issue by allowing `null` as a valid email, which should not make it matter whether the tests are run using a session token or a robot token.
Self evident
n/a internal
=> fix(cli) allow cli tests to run with a robot token

packages/@sanity/import/README.md, packages/@sanity/import/src/importFromArray.js, packages/@sanity/import/src/validateOptions.js, packages/@sanity/import/test/__snapshots__/import.test.js.snap, packages/@sanity/import/test/fixtures/system-documents.ndjson, packages/@sanity/import/test/import.test.js, packages/sanity/src/_internal/cli/commands/dataset/importDatasetCommand.ts
As part of the import process through CLI and `@sanity/import` package, we prefer that users do not send in system documents. These documents are considering to be an internal detail and if imported, their interaction with existing system documents is undefined.
This PR attempts at adding a new flag `--allow-system-documents` to `sanity dataset import` CLI and an option `allowSystemDocument` to `@sanity/import` package, to explicitly permit system document import if the user knows what they are doing.
This can be considered to be a breaking change since it by default skips system documents from import, but I highly doubt anyone is importing system documents from CLI. And, if they are, they should stop doing that. Ideally, I should add data to my gut-feeling and figure out how many users …
=> feat(import): add --allow-system-documents to dataset import

packages/sanity/src/structure/panes/document/DocumentOperationResults.tsx
The toast message for when documents are published or deleted did not use the `useDocumentTitle()` hook. This PR fixes it so that the the toast message uses the same logic that the large title of the document uses. 
The toast message that appears when a document is published/deleted. 
Fixes issue where the toast message always shows the correct title
=> fix(structure): use useDocumentTitle hook for toast message

packages/sanity/src/structure/comments/i18n/resources.ts, packages/sanity/src/structure/comments/src/__workshop__/CommentsListStory.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItem.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItemLayout.tsx, packages/sanity/src/structure/comments/src/context/index.ts, packages/sanity/src/structure/comments/src/context/intent/CommentsIntentContext.ts, packages/sanity/src/structure/comments/src/context/intent/CommentsIntentProvider.tsx, packages/sanity/src/structure/comments/src/context/intent/index.ts, packages/sanity/src/structure/comments/src/context/intent/types.ts, packages/sanity/src/structure/comments/src/helpers.ts, packages/sanity/src/structure/comments/src/hooks/index.ts, packages/sanity/src/structure/comments/src/hooks/use-comment-operations/createOperation.ts, packages/sanity/src/structure/comments/src/hooks/use-comment-operations/useCommentOperations.ts, packages/sanity/src/structure/comments/src/hooks/useCommentsIntent.ts, packages/sanity/src/structure/comments/src/store/useCommentsStore.ts, packages/sanity/src/structure/comments/src/types.ts, packages/sanity/src/structure/index.ts
This PR adds a mechanism for associating and displaying an intent link alongside a comment. This is so other tools (namely Presentation) can augment comments with added context about where a comment was made.
An optional provider is exported for use in other tools, if this provider is used and intent context is available it will be attached to the comment context payload.
The workshop `CommentsListStory` has been updated to include an example of an intent link.
No tests added.
n/a
=> feat(comments): add optional intent link to comments

.github/workflows/release.yml, lerna.json, package.json, yarn.lock
Introduces the new release automation that publishes from an action.
- Review the release.yml workflow and try to come up with scenarios that break it.
- Are all the pre-flight check good?
We tried this out in another repo and copied and pasted the results.
N/A
=> build: release automation

packages/@sanity/cli/src/util/resolveRootDir.ts, packages/@sanity/cli/test/basics.test.ts, packages/@sanity/cli/test/shared/environment.ts
The CLI is intended to automatically resolve the project root if it's used inside the subdirectory of a Studio project. This behaviour has been broken for v3, because the resolution code mistakenly searches for `studio.config.{ts,js}` files, rather than `sanity.config.{ts,js}`. Therefore, it never finds the project root.
This was discovered and discussed in #5684.
- That it's possible to use the CLI inside the subdirectory of a Studio project.
- That when doing so, a warning is printed: "Not in project directory, assuming context of project at ${path}".
- I've added a basic CLI unit test to ensure the `help` command can be executed inside Studio project subdirectories, and that the warning is printed.
Fixed a bug that prevented the CLI being used inside Studio project subdirectories.
=> fix(cli): project root resolution

packages/sanity/src/tasks/__workshop__/TasksCreateStory.tsx, packages/sanity/src/tasks/plugin/TasksDocumentInputLayout.tsx, packages/sanity/src/tasks/src/tasks/components/create/TasksCreate.tsx, packages/sanity/src/tasks/src/tasks/components/list/TasksListItem.tsx, packages/sanity/src/tasks/src/tasks/components/sidebar/TasksSidebarContent.tsx, packages/sanity/src/tasks/src/tasks/types.ts
Clicking on the task document reference will navigate to that document. 
Updates some imports and refactors some types.
=> feat(tasks): add document navigation from tasks

packages/@sanity/cli/src/commands/codemod/codemodCommand.ts, packages/@sanity/cli/src/commands/debug/debugCommand.ts, packages/@sanity/cli/src/commands/docs/docsCommand.ts, packages/@sanity/cli/src/commands/help/helpCommand.ts, packages/@sanity/cli/src/commands/init/initCommand.ts, packages/@sanity/cli/src/commands/install/installCommand.ts, packages/@sanity/cli/src/commands/login/loginCommand.ts, packages/@sanity/cli/src/commands/logout/logoutCommand.ts, packages/@sanity/cli/src/commands/manage/manageCommand.ts, packages/@sanity/cli/src/commands/projects/projectsGroup.ts, packages/@sanity/cli/src/commands/telemetry/telemetryGroup.ts, packages/@sanity/cli/src/commands/versions/versionsCommand.ts, packages/sanity/src/_internal/cli/commands/build/buildCommand.ts, packages/sanity/src/_internal/cli/commands/cors/corsGroup.ts, packages/sanity/src/_internal/cli/commands/dataset/datasetGroup.ts, packages/sanity/src/_internal/cli/commands/deploy/deployCommand.ts, packages/sanity/src/_internal/cli/commands/deploy/undeployCommand.ts, packages/sanity/src/_internal/cli/commands/dev/devCommand.ts, packages/sanity/src/_internal/cli/commands/documents/documentsGroup.ts, packages/sanity/src/_internal/cli/commands/exec/execCommand.ts, packages/sanity/src/_internal/cli/commands/graphql/graphqlGroup.ts, packages/sanity/src/_internal/cli/commands/hook/hookGroup.ts, packages/sanity/src/_internal/cli/commands/migration/migrationGroup.ts, packages/sanity/src/_internal/cli/commands/preview/previewCommand.ts, packages/sanity/src/_internal/cli/commands/schema/schemaGroup.ts, packages/sanity/src/_internal/cli/commands/start/startCommand.ts, packages/sanity/src/_internal/cli/commands/users/usersGroup.ts
Updates the help copy for cli commands
Copy makes sense
`yarn build && npx sanity help` 
N/A
=> chore(cli): update help copy for CLI commands

packages/sanity/src/structure/comments/i18n/resources.ts
Updated comment for an i18n resource to provide more context for translators. Specifically the text used for rendering intent links to navigate back to where a comment was made, e.g. in Presentation tool.
The text provides enough context for community and AI translators to provide an accurate translation.
N/A
N/A
=> chore(comments): improve i18n resource for comment contexts

.github/workflows/release.yml
This removes the final rebase step in the release workflow. This step will always fail because of our branch protection rules so for now we'll run this step locally.
N/A
=> build: remove last rebase step

packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Tiny whitespace tuning.
```
Tried the following files:
-foo.js
- foo.mjs
```
```
Tried the following files:
- foo.js
- foo.mjs
```
=> fix(cli): minor whitespace tuning for migration error output

.github/workflows/prettier-if-needed.yml
Merging to next revealed a couple of issues with lint/prettier scripts. This should hopefully fix it.
Not sure if it's possible to properly test these before merging, unfortunately
N/A
=> chore(ci) fix prettier & eslint workflows

packages/sanity/src/core/config/studio/types.ts, packages/sanity/src/core/studio/StudioLayout.tsx, packages/sanity/src/core/studio/components/navbar/StudioActiveToolLayout.tsx, packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx, packages/sanity/src/core/studio/studio-components-hooks/componentHooks.ts, packages/sanity/src/core/studio/studio-components-hooks/picks.ts
This PR adds two necessary core changes for the `tasks` feature. 
It's intention is to wrap the `ActiveTool` and allow plugins to modify the layout around it. 
The red border shows how it wraps the active tool.
```
// Plugin implementation
export const tasks = definePlugin({
name: 'sanity/tasks',
studio: {
components: {
...
activeToolLayout: TasksStudioActiveToolLayout,
},
},
})
// Usage
export function TasksStudioActiveToolLayout(props: ActiveToolLayoutProps) {
const {isOpen} = useTasks()
const {enabled} = useTasksEnabled()
if (!enabled) return props.renderDefault(props)
return (
<Flex height="fill">
<div style={{minHeight: '100%', width: '100%'}}>{props.renderDefault(props)}</div>
{isOpen && <TasksStudioSidebar />}
</Flex>
)
}
```
Adds a prop to the studio navbar prop which will be used …
=> feat(core): add studioActiveToolLayout and navbar rightSectionNode prop

packages/@sanity/block-tools/package.json, packages/@sanity/cli/package.json, packages/@sanity/vision/package.json, packages/sanity/package.json, pnpm-lock.yaml
Add missing types for lodash and react-dom in various packages.
=> chore: add missing types packages

packages/sanity/src/tasks/src/tasks/components/create/TasksCreate.tsx, packages/sanity/src/tasks/src/tasks/components/mentionUser/index.ts, packages/sanity/src/tasks/src/tasks/components/mentionUser/mentionUser.tsx, packages/sanity/src/tasks/src/tasks/types.ts
Adds assignedTo property to tasks.
When a user is assigned, he will see that task in his list of tasks. 
AssignedTo property works as expected
Create a new task, assign yourself or any other user, it should work.
=> feat(tasks): add assignee property to tasks

package.json, pnpm-lock.yaml
Adds missing `@types/lodash` to workspace root.
Does `pnpm check:types` report any errors?
=> fix(core): add `@types/lodash`

dev/test-studio/.depcheckignore.json, dev/test-studio/package.json, dev/test-studio/plugins/router-debug/RouterDebug.tsx, dev/test-studio/sanity.config.ts, packages/sanity/src/core/search/common/utils.ts, packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts, pnpm-lock.yaml
The #5657 PR didn't manage to fix the regression in #5440. With the help of @sjelfull this time it's actually resolved and the fix reproducible on the Test Studio.
Adding `sanity.previewUrlSecret` should only have an effect on this particular type, other `sanity.` prefixed types shouldn't show up anywhere, like in global search.
In a Studio that has this plugin installed:
```ts
import {debugSecrets} from '@sanity/preview-url-secret/sanity-plugin-debug-secrets'
import {defineConfig} from 'sanity'
// ...
plugins: [
debugSecrets()
]
})
```
Then Structure tool should show this menu:
And global search should let you filter by the type as well:
When the plugin isn't used then these document types should remain hidden:
- fixed regression that affected `import …
=> fix(structure): allow sanity.previewUrlSecret in document lists

.github/workflows/e2e.yml, .github/workflows/pr-cleanup.yml, dev/studio-e2e-testing/turbo.json, package.json
With migrating to pnpm we by mistake enabled turbo build for e2e testing studio which caused an issue where the build was cached until a new remote cache was enabled. This posed a problem as the cache dataset would not match the dataset in the test causing failure. This changes the process to not use turbo for building the testing studio. 
Also fixes the cleanup script to install pnpm so it does not fail
Changes makes sense, test is passing 
N/A
=> test(e2e): fix e2e test caching issue

packages/@sanity/migrate/src/runner/collectMigrationMutations.ts
A tiny DX improvement that catches an attempt to iterate over the provided `documents` function without calling it. (Note that TypeScript will usually catch these too)
Is the error message clear?
Create an async iterable migration and iterate over documents without calling it:
```tsx
import {defineMigration} from 'sanity/migrate'
export default defineMigration({
title: 'Demo migration',
async *migrate(documents, context) {
for await (const doc of documents) {
// yield mutations…
}
},
})
```
- Improves error handling for a migration script that attempts to iterate over the passed `document` function without calling it
=> fix(migrate): throw if attempting to iterate over documents producer

.github/workflows/release.yml
Forgot to update release workflow as part o #5533
Does the changes make sense? I have not been able to test, but from reading the docs it seems accurate.
Hard to test this one without polluting npm
n/a - internal
=> fix(ci): use pnpm for package releases

packages/sanity/src/structure/comments/plugin/field/CommentsField.tsx, packages/sanity/src/structure/comments/plugin/input/components/CommentsPortableTextInput.tsx, packages/sanity/src/structure/comments/plugin/inspector/CommentsInspector.tsx, packages/sanity/src/structure/comments/src/__tests__/buildRangeDecorationSelectionsFromComments.test.ts, packages/sanity/src/structure/comments/src/__workshop__/CommentInlineHighlightDebugStory.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItemLayout.tsx, packages/sanity/src/structure/comments/src/helpers.ts, packages/sanity/src/structure/comments/src/types.ts, packages/sanity/src/structure/comments/src/utils/buildCommentThreadItems.ts, packages/sanity/src/structure/comments/src/utils/inline-comments/buildRangeDecorationSelectionsFromComments.ts, packages/sanity/src/structure/comments/src/utils/inline-comments/buildRangeDecorations.tsx
This pull request implements logic that omits inline comments if we are unable to find a match in the current value of the Portable Text.
=> feat(comments): omit inline comments without referenced value

packages/@sanity/migrate/src/runner/__tests__/normalizeMigrationDefinition.test.ts
Adds test for `normalizeMigrationDefinition` function
Not 100% sure if it makes sense and is testing the full capability of the functions, @bjoerge thoughts? 
Added :)
N/A
=> test(migration) add tests for normalizeMigrationDefinition

packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
When there are validation errors the tooltip is enabled, when validation errors disappear the tooltip is disabled.
Making that update when the modal is rendered it will trigger a "unmount" and "re-mount" of the BlockObject causing the  modal to unmount and remount, triggering the animation again and losing the input focus.
By checking if the modal is open to **enable / disable** the tooltip, we can be sure that this component won't unmount and mount causing this unwanted issues. 
https://github.com/sanity-io/sanity/assets/46196328/41f3e428-fb9c-4390-a374-0e77f469388e
PTE dialogs and tooltips work as always
Create a new object within pte with validation eror
=> fix(pte): PTE modal re-render on validation state change due to tooltip disabled change

packages/@sanity/migrate/src/runner/__tests__/normalizeMigrationDefinition.test.ts
Merged #5565 without rebasing and didn't realize we moved to jest globals, this fixes the failures on next
No errors
=> chore(test): fix linting and type errors

dev/test-studio/package.json, package.json, packages/sanity/package.json, pnpm-lock.yaml
Fixes SDX-1090
```
1.0.0-alpha.42 (2024-02-15)
Bug Fixes
regex to rewrite JSX_2 to JSX 
1.0.0-alpha.41 
Bug Fixes
fix issue with reference to properties not being saved 
1.0.0-alpha.40 
Bug Fixes
url path for reference document links 
1.0.0-alpha.39 
Bug Fixes
UI issues and trigger path update when clicking internal links (#28) (0d88f39)
```
N/A
=> chore(deps): bump @sanity/tsdoc to 1.0.0-alpha.42

packages/sanity/src/tasks/src/tasks/components/list/DocumentPreview.tsx, packages/sanity/src/tasks/src/tasks/components/list/TasksListItem.tsx, packages/sanity/src/tasks/src/tasks/components/sidebar/TasksListTabs.tsx, packages/sanity/src/tasks/src/tasks/components/sidebar/TasksSidebar.tsx, packages/sanity/src/tasks/src/tasks/hooks/useDocumentPreviewValues.ts
This fixes document previews in tasks by utilising the same drafts-aware preview store as the document lists.
=> fix(tasks): utilise document preview store for document titles

package.json, packages/@sanity/portable-text-editor/package.json, packages/sanity/package.json, perf/tests/package.json, pnpm-lock.yaml
The Playwright version we are using currently has a bug as [described here.](https://github.com/microsoft/playwright/issues/29028)
I got hit by it trying to pass a ref made by `createRef` to the mounted test component in playwright-ct. Upgrading Playwright to latest fixes the issue.
The Playwright tests work as expected.
If all the Playwright-related CI tests pass, we are good.
N/A
=> chore: upgrade @playwright/test to latest

packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/inputs/PortableText/hooks/usePortableTextMembers.tsx, packages/sanity/src/core/form/inputs/PortableText/hooks/useTrackFocusPath.tsx
This will make the PT-input report the `focusPath` when the focus is on text spans ending with `text` so that the Presentation Tool can work out of the box without making any exceptions for the PT-input.
With this change, we have a bi-directional mapping of focus with the forms and the presentation tool.
Note that this will not change the PTE `EditorSelection` which will continue reporting as before,  it's only the studio-specific `focusPath` reporting that will be affected by this change.
* That regular form focus works as expected
* That the Presentation Tool focus handling works as expected
* That features like AI-Assist still works as expected.
* Improved focus handling with the Presentation tool and Portable Text Inputs.
=> refactor(core/inputs): report focusPath on text spans ending with .text

packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/FocusTracking.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/FocusTrackingStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/utils/TestForm.tsx, packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
I discovered some issues in #5786.
* Forgot to call `onPathFocus` on anything else than spans.
* There was an issue where it was testing for inlineBlocks against the wrong member key, not correctly identifying inline blocks.
* Added missing tests that should have discovered these issues.
* Added some more code comments as the code isn't too easy to understand.
I have added some Playwright-CT tests for this functionality now that test the values emitted by `onPathFocus` for focus on spans, inline blocks, and block objects.
The bi-directionality and production of paths for various types of content should now be fully covered by the tests.
N/A - should use notes from #5786
=> fix(core/inputs): fix issues with calling onPathFocus for PT-input

packages/sanity/src/core/studio/Studio.test.tsx, packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx, packages/sanity/src/core/studio/components/navbar/workspace/WorkspacePreview.tsx, packages/sanity/src/ui-components/__workshop__/MenuItemStory.tsx, packages/sanity/src/ui-components/menuItem/MenuItem.tsx
This PR reintroduces the `subtitle` in the list view for the workspace list. 
The workspaces list view and that it looks good with and without subtitles. 
Reintroduces subtitle field for workspace list views
=> fix(core): bring back subtitle in workspace list view

dev/test-studio/structure/resolveStructure.ts, packages/sanity/src/core/components/StatusButton.tsx, packages/sanity/src/structure/components/pane/PaneHeaderActionButton.tsx, packages/sanity/src/structure/menuNodes.ts
Fixes #4891
Menu items in structure nodes that defined an intent instead of an action handler did not work after the facelift launch. There appears to be multiple different issues that caused this - I have addressed them in separate commits:
1. The `intent` definition was not actually passed onto the structure nodes, leading to them being treated as a menu button without an action handler instead of an intent button
2. The intent buttons did not actually render, because the `as="a"` rendered the entire button as a single link without any styling. I've modified it to use `forwardedAs`, but I am not confident that this approach is correct, or needs adjustment.
While investigating, I also found that the menu buttons got an aria label of `This is disabled`, even when not disabled. For now, I …
=> fix(structure): intent menu item nodes not rendering

.github/workflows/release.yml
Setup pnpm and installed dependencies.
=> fix(ci): setup pnpm

.github/workflows/release.yml
Remove pnpm reference from setup-node step.
=> fix(ci): remove pnpm reference from setup-node step

packages/sanity/src/structure/components/pane/PaneContextMenuButton.tsx, test/e2e/tests/desk/documentTypeListContextMenu.spec.ts
As we start to re-organize how we think about storing our settings, it's important to write tests first to ensure we're not losing any old functionality, especially during a transition period.
The new test file and the small change to add a data-testid to a component that would have been brittle to reach without it.
Feel free to run the tests locally as needed.
It would have been nice to _also_ test, in true end-to-end fashion, whether or not these parameters have the desired effect on the in-studio experience. However, that would require us to create multiple documents to sort and check, which our current testing strategy makes a bit difficult, because it runs parallel workers. I think it would be an excellent idea in the future!
=> test(core): add tests for sort order local storage values

packages/@sanity/portable-text-editor/src/editor/PortableTextEditor.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Input.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/InputStory.tsx, packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/types/inputProps.ts
This will allow for controlling the PortableTextEditor instance from outside of the PortableTextInput, by providing
a React ref object through the input's `props.editorRef`
Also added a Playwright Component test for this.
Is there a better way to test the ref in the Playwright Component tests? 
After a lot of back and forth, this pattern was what I landed on.
Should be tested automatically.
* PortableTextInput can now control the underlaying PortableTextEditor instance with ref passed through props.
=> feat(form/inputs): control PortableTextEditor instance via ref

packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Input.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/InputStory.tsx, packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/types/inputProps.ts
This will support providing your own PortableTextEditor change callback to the PortableTextInput through props.
Handy for making custom functionality through the component extensions API.
Also provided a Playwright CT test for this.
That the change is ok.
See Playwright CT test
* PortableTextInput now supports providing a custom editor change callback.
=> feat(core/inputs): support custom editor change callback

packages/@sanity/portable-text-editor/e2e-tests/__tests__/selectionAdjustment.collaborative.test.ts, packages/@sanity/portable-text-editor/e2e-tests/__tests__/undoRedo.collborative.test.ts, packages/@sanity/portable-text-editor/e2e-tests/__tests__/writingTogether.collaborative.test.ts, packages/@sanity/portable-text-editor/e2e-tests/setup/collaborative.jest.env.ts, packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditor.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withEditableAPIInsert.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withPortableTextSelections.test.tsx, packages/@sanity/portable-text-editor/src/types/editor.ts, packages/@sanity/portable-text-editor/src/utils/ranges.ts, packages/@sanity/portable-text-editor/src/utils/selection.ts
Add .backward? on EditorSelection to be able to tell if the selection was made backward in the content when returned by `PortableTextEditor.getSelection`
This is needed in situations where the selection is made backward in the content, but we can only perform a task in the natural order (some for loop on text extractions or similar). By knowing that the selection is made backward, it's then just a matter of switching the anchor and focus points to have it in the natural order.
That the change looks good.
Should be covered by a lot of existing tests (see patch that updates them).
* Added a `backward` property to the EditorSelection of the Portable Text Editor to tell if a selection was made backward in the content.
=> feat(portable-text-editor): determine if selection is made backward

packages/@sanity/portable-text-editor/src/editor/PortableTextEditor.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withEditableAPIGetFragment.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts, packages/@sanity/portable-text-editor/src/types/editor.ts
This function will get the current selection in the editor as a Portable Text fragment.
See the included test for how it works.
That the changes look good.
See test
* Portable Text Editor can now return a Portable Text fragment for the selected content.
=> feat(portable-text-editor): new API method getFragment

packages/sanity/src/core/components/StatusButton.tsx, packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx
Adding some missing `aria-labels` to navbar buttons that are icons without labels
=> fix(core): add missing aria-labels to navbar icons

packages/sanity/src/core/form/inputs/PortableText/toolbar/ActionMenu.tsx, packages/sanity/src/core/i18n/bundles/studio.ts
Adds `aria-label` to the PTE toolbar action menus
=> fix(core): add aria label to action button pte toolbar

packages/sanity/src/core/studio/components/navbar/search/hooks/useSearchMaxFieldDepth.ts
This endpoint is changing to allow for multiple settings resources to be grouped under `/settings/...`.
=> feat: update indexing endpoint for new name

packages/sanity/src/structure/i18n/resources.ts
There is no language string for the `restore` event, which causes the generic toast message to be rendered with a missing `{{context}}` value:
This change adds a dedicated string for successful document restoration:
- Is the string okay?
I don't believe we test document operation toasts at the moment, so it wouldn't make sense to implement just for document restoration.
=> fix(i18n): add successful document restoration string

packages/sanity/src/core/studio/components/navbar/search/components/searchResults/SearchResults.tsx, test/e2e/tests/desk/documentTypeListContextMenu.spec.ts, test/e2e/tests/navbar/appearanceMenu.spec.ts, test/e2e/tests/navbar/search.spec.ts
As we start to re-organize how we think about storing our settings, it's important to write tests first to ensure we're not losing any old functionality, especially during a transition period.
The new test files and the small change to add a data-testid to a component that would have been brittle to reach without it.
Feel free to run the tests locally as needed.
=> test(core): add test for storing color scheme preference and search

packages/sanity/src/_internal/cli/commands/backup/disableBackupCommand.ts, packages/sanity/src/_internal/cli/commands/backup/enableBackupCommand.ts
This PR adds two minor changes:
1. At the moment, error parsing is being done inline in a few place where the logic is incorrect. We are getting undefined in error message. So, first change replaces this inline code with common error parser.
2. Second change is update CLI text when backups are enabled to meet expectations.
I have tested API error parsing locally. So, a general overview of changes may suffice.
These commits should not included in release notes because dataset backup is an unreleased feature.
=> Dataset Backups: Handle API Error and update text output when backups are enabled

.github/workflows/etl.yml
This is a follow up to #5855. For now, instead of using the PAT, we'll allow this workflow to be ran manually at this time.
N/A
=> build: allow `etl.yml` to be ran manually

dev/test-studio/package.json, package.json, packages/sanity/package.json, packages/sanity/tsdoc.config.ts, pnpm-lock.yaml, scripts/etl.ts
=> chore(deps): bump tsdoc to 1.0.0-alpha.44

packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx, packages/sanity/src/core/form/inputs/PortableText/object/modals/ObjectEditModal.tsx
This PR changes the inline objects in portable text to be wider by default. 
There has been a lot of signal of the reference picker being too narrow. After talking with design, the decision landed on making the default width of _all_ inline objects larger (but might revisit later) 
The reference picker/objects popovers in for example in the portable text in Standard inputs - Portable text - All the editors!
Increases default size of inline objects in portable text
=> fix(core): change modalWidth of inlineObjects to 1 by default

packages/@sanity/portable-text-editor/src/editor/PortableTextEditor.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withUndoRedo.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithObjectKeys.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithUndoRedo.ts
Previously when doing undo/redo in the PortableTextEditor it would generate new keys for the created content.
With this change, the keys will be preserved along with the original content. This makes it possible to support situations where something externally depends on the previous content's keys, it will be possible to restore that dependency when calling undo after an operation breaks it.
I have also introduced some unit tests for undo/redo that will test this functionality.  Previously we only had e2e tests for undo/redo.
Manual testing, unit test, and e2e tests seem to verify that there are no issues with this change.
But could it be something we are not thinking of here?
It should be covered by various tests.
* Preserve content keys when doing undo/redo in the Portable Text Editor.
=> feat(portable-text-editor): preserve keys on undo/redo

packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withEditableAPISelectionsOverlapping.test.tsx, packages/@sanity/portable-text-editor/src/utils/ranges.ts
This will validate that a range path is lengthy before we return a non-null `EditorSelection`. 
Empty Range paths don't make sense in the PTE and will lead to bugs.
Also fixed a test that was using the wrong block type, and was incorrectly passing before this fix.
That the tests pass.
See the automatic tests.
N/A
=> fix(portable-text-editor): check that path is lengthy 

packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/types/inputProps.ts
This pull request adds an `onFullScreenChange` callback to the Portable Text Input.
- Make sure that the callback returns the correct value.
N/A
=> feat(core): add `onFullScreenChange ` to Portable Text Input 

packages/sanity/src/core/form/studio/uploads/accepts.ts
when using extension based accepts settings
Fixes EDX-795
When configuring a file input that restricts file types, we accept either extensions `'.pdf'` or mime type `'application/pdf'`.  When using drag and drop, while hovering, if the file type is not accepted, we display an error message. In order for the extension based restriction to work, we need the file name, which is not passed by the browser when hovering, but is when the file is dropped. Because of this, when an extension rule was used, we were incorrectly showing the error message but then accepting the file when it was dropped. The correct fix is to update the rule to be based on mime type. For the case where extension rules are used, we should not show an error on hover.
Before: …
=> fix(core): updates to not show "cannot upload" on hover 

packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts, packages/@sanity/codegen/src/typescript/findQueriesInSource.ts
Codegen generates query types named after the query variable name. This change only adds the word 'Result' at the end of the type name to differentiate between the variable name and the imported type.
E.g.
```js
import {postsResult} from './types.d.ts'
const posts = groq`*[_type="post"]`
export async function getPosts(client: SanityClient): postsResult {
return await client.fetch(posts)
}
```
=> feat(codegen): add 'Result' to query type names

packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTitle.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx, packages/sanity/src/structure/panes/document/useDocumentTitle.ts
Currently, if the connection drops while you're editing a document, the whole pane reloads and the react tree inside it will unmount/remount, loosing all its state. Since we're introducing more transient state in these components (comments, etc), we're running a bigger risk of losing people's stuff when this happens. Short disconnects happens quite often, so it can be pretty disruptive to the end-user. This PR makes sure that instead of taking over the pane when the listener disconnects (technically, is in a "reconnecting" state), we retain the form  component instance, but set it as readonly to prevent the editor for making edits without being connected.
- I've changed a few places to use `connectionState !== 'reconnecting'` instead of `connectionState === 'connected'`. 
- Is there …
=> fix(sanity): preserve form (as readOnly) when reconnecting

packages/@sanity/portable-text-editor/src/editor/Editable.tsx
This optimization was a bit too optimistic.
It's causing issues with some types of selections.
Check every path here.
N/A
=> fix(portable-text-editor): all paths must be checked

packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/sanity/src/structure/comments/src/utils/inline-comments/buildRangeDecorationSelectionsFromComments.ts
This is needed to support including empty blocks within the commented range.
Two first commits here are part of #5891
N/A
=> fix(comments): allow ranges to be collapsed

.github/workflows/release.yml
This branch adds caching for pnpm dependencies in the release workflow. It's based on [Binoy's implementation in the e2e workflow](https://github.com/sanity-io/sanity/blob/next/.github/workflows/e2e.yml).
- Do you see any issues in the approach?
This approach already works for the e2e workflow. If there are any issues when we next release Studio, we can revert this commit. I'm happy to be on hand for the next release.
=> feat(ci): cache release dependencies

packages/sanity/src/core/studio/components/navbar/search/components/SearchPopover.tsx, packages/sanity/src/core/studio/components/navbar/search/components/index.ts, packages/sanity/src/core/studio/components/navbar/search/components/searchResults/SearchResults.tsx, packages/sanity/src/core/studio/components/navbar/search/components/searchResults/index.ts, packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItem.tsx, packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItemPreview.tsx, packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/index.ts, packages/sanity/src/core/studio/components/navbar/search/contexts/index.ts, packages/sanity/src/core/studio/components/navbar/search/contexts/search/SearchContext.ts, packages/sanity/src/core/studio/components/navbar/search/contexts/search/index.ts, packages/sanity/src/core/studio/components/navbar/search/contexts/search/useSearchState.ts, packages/sanity/src/core/studio/components/navbar/search/index.ts
This PR exports some search components and providers that are necessary for the `tasks` feature.
We will reuse the logic from this search to allow users to search and assign tasks to content.
To reuse the search, we will do it as follows, importing the `SearchProvider` and the `SearchPopover`  [see dependant PR here](https://github.com/sanity-io/sanity/pull/5897/files#diff-f4ee5e22fae5b72d23163ee05278e3eda58dd1b2791f84f199a97e79900b4f37R220)
```
<SearchProvider>
<SearchPopover
open={open}
onClose={handleCloseSearch}
onOpen={handleOpenSearch}
onItemSelect={handleItemSelect}
disableIntentLink
/>
</SearchProvider>
```
The `SearchPopover` props have been extended to support and `onItemSelect` and `disableIntentLink` props.
=> chore(search): refactor search to export necessary components and providers.

packages/@sanity/export/package.json, packages/@sanity/import/package.json, packages/sanity/package.json, pnpm-lock.yaml
Upgrades `archiver` to patch [SNYK-JS-INFLIGHT-6095116](https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116) as well as `split2` for improved typescript support.
- `sanity export` still produces valid tarballs (`archiver`'s only breaking changes are dropping support for node 12, so should be safe)
- `sanity import` still works as intended, reading an exported tarball correctly (`split2`'s breaking change is also dropping support for node 12)
Existing tests should suffice
None.
=> chore(deps): upgrade archiver, split2 dependencies

packages/sanity/src/core/templates/__tests__/resolve.test.ts, packages/sanity/src/core/templates/__tests__/schema.ts, packages/sanity/src/core/templates/validate.ts
It is currently not possible to create a cross-dataset reference from an initial value template, as the template validation runs and disallows unknown properties on references, where `_dataset` was not an allowed prop.
Perhaps we should recurse down the type chain to look for a field that extends from `crossDatasetReference`, but this is beyond what we do for other types - eg we do not check for a `reference` type when encountering `_ref`. Leaving this for a future iteration to improve on if we feel it is worth it.
- Can create a cross-dataset reference from an initial value template
- Implementation looks acceptable
I added some surrounding tests not only for the `_dataset` case but also for other reference properties, as I could not find any tests for that code path.
- Fixes an issue …
=> fix(core): allow `_dataset` for cross-dataset references in templates

packages/sanity/src/structure/comments/plugin/inspector/CommentsInspector.tsx
This pull request changes the behavior to display the comments loading state when:
- Comments are loading
- The `connectionState` of the form is "connecting"
Previously, we utilized the `ready` value from `useDocumentPane`, which caused the comments to show a loading state whenever the form was _reconnecting_. This behavior is undesirable because a comment that a user is in the process of writing will disappear if the form is "reconnecting".
- Ensure that the comments list does not load when the `connectionState` is "reconnecting"
N/A
=> fix(comments): loading state

packages/sanity/src/core/hooks/useEditState.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts
The following PR adds a `complete()` method to the document pair interface so that `memoizedPair` can close open connections.
Before:
https://github.com/sanity-io/sanity/assets/10551026/c035a6cf-3bac-4b93-be47-390d49ae3374
After:
https://github.com/sanity-io/sanity/assets/10551026/008fc3c3-ea64-4155-b393-a51eb70b428f
Try reproducing the related bug. You should not be able to see it any more.
Did lots of manual testing and debugging. We should get
Fixes a bug that caused listener to stay open causing slow document lists and other related crashes.
=> fix(core): clean up edit state listeners

packages/sanity/src/structure/comments/plugin/index.ts, test/e2e/tests/comments/inline.spec.ts
This pull request enables the inline comments feature and the e2e test for it.
- Make sure that inline comments is enabled
N/A
=> chore(comments): enable inline comments

packages/sanity/src/core/i18n/bundles/studio.ts
Fixes EDX-1123
Updates copy for placeholder text
Before:
After:
Typos?
Copy only change, no functional change
=> fix(core): update placeholder text to be more clear and accessible

packages/@sanity/codegen/tsconfig.json, packages/@sanity/codegen/tsconfig.lib.json, packages/sanity/tsconfig.json, packages/sanity/tsconfig.lib.json
This repo is using [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) which lets us to run `tsc --build` from source files, and have TypeScript build the packages in topological order (e.g. start by building the packages that's depended on by other packages). Unfortunately TS isn't workspace aware, so the workspace dependencies needs to be explicitly declared as references in `tsconfig.json`. This PR adds them where they are needed.
The type check should now pass on CI.
n/a
=> fix: add missing project reference

.github/PULL_REQUEST_TEMPLATE.md
Updates the pull request template to remind developers to be explicit for PRs that are partial implementations of an in-progress feature
Is the language clear?
=> chore(core): update pull request template

packages/sanity/src/core/hooks/useFeatureEnabled.ts, packages/sanity/src/structure/comments/src/hooks/useResolveCommentsEnabled.ts
This pull request ensures that we only display the upsell UI or the comments UI if we can successfully fetch the feature flags for the current project. If fetching the feature flags is not possible, for example, due to the current user's permissions restricting access to "project details," we cannot accurately determine which UI to display. Therefore, in such scenarios, we must disable the feature entirely to prevent inadvertently showing the upsell UI for a project where it is actually enabled.
- Make sure that the upsell UI is only displayed if the project is not having access to `studioComments`
N/A
=> fix(comments): enable check

packages/sanity/src/core/store/_legacy/datastores.ts, packages/sanity/src/core/store/key-value/KeyValueStore.ts, packages/sanity/src/core/store/key-value/backends/localStorage.ts, packages/sanity/src/core/store/key-value/backends/memory.ts, packages/sanity/src/core/store/key-value/backends/resolve.ts, packages/sanity/src/core/store/key-value/backends/server.ts, packages/sanity/src/core/store/key-value/backends/types.ts, packages/sanity/src/core/store/key-value/types.ts, packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx, packages/sanity/src/structure/useStructureToolSetting.ts, test/e2e/tests/desk/documentTypeListContextMenu.spec.ts
Scaffolds a Dataloader that hits an API endpoint for user settings -- in this case, specifically those settings relevant to structure tools.
This is meant to be just a scaffold. In the following day, please expect:
- unit tests for hooks to handle malformed or null data
- any additional error handling that can be called out here
- possible fallbacks for situations if the API is not available.
The Dataloader backend specifically -- does it work as we expect? Any gotchas? Are errors being handled correctly?
End-to-end tests are already in place. They've been refactored since they referred to localStorage changes.
=> feat(core): fetch structure tool settings from backend

packages/sanity/src/structure/comments/plugin/document-layout/CommentsDocumentLayout.tsx, packages/sanity/src/structure/comments/plugin/field/CommentsField.tsx, packages/sanity/src/structure/comments/plugin/field/CommentsFieldButton.tsx, packages/sanity/src/structure/comments/src/context/authoring-path/CommentsAuthoringPathContext.ts, packages/sanity/src/structure/comments/src/context/authoring-path/CommentsAuthoringPathProvider.tsx, packages/sanity/src/structure/comments/src/context/authoring-path/index.ts, packages/sanity/src/structure/comments/src/context/authoring-path/types.ts, packages/sanity/src/structure/comments/src/context/index.ts, packages/sanity/src/structure/comments/src/hooks/index.ts, packages/sanity/src/structure/comments/src/hooks/useCommentsAuthoringPath.ts
This pull request addresses an issue where the comment input unmounts during document reconnection, leading to the loss of the comment being authored. To resolve this, the following solutions have been implemented:
- Introduction of a new `CommentsAuthoringPathContext`. This context is needed because if the "open state" of the comment input is managed locally within the component, the state resets when unmounting. By tracking the user's current authoring path in a context, it ensures the comment input remains open even when the component is re-rendered.
- Caching the message to make sure that it is not lost when re-rendering. Unlike the "authoring path", the comment message is not stored in a context to avoid potential performance degradation, as this would require all consumers to …
=> fix(comments): lost comment message while document is reconnecting

dev/aliases.cjs, packages/sanity/src/_internal/cli/threads/__tests__/validateDocuments.test.ts
This registers dev resolve aliases in the validation worker thread when running the tests.
This allows us to run the test suite directly from source, without first having to build, which means we can skip the build step entirely before running unit tests on CI. See [this comment](https://github.com/sanity-io/sanity/pull/5920#discussion_r1515201182) for more context.
n/a
n/a internal
=> test(sanity): use dev aliases in the validation test's worker threads

.eslintrc.cjs, packages/sanity/src/structure/comments/plugin/document-layout/CommentsDocumentLayout.tsx, packages/sanity/src/structure/comments/plugin/field/CommentsField.tsx, packages/sanity/src/structure/comments/plugin/input/components/CommentsPortableTextInput.tsx, packages/sanity/src/structure/comments/plugin/inspector/CommentsInspector.tsx, packages/sanity/src/structure/comments/src/__workshop__/CommentInlineHighlightDebugStory.tsx, packages/sanity/src/structure/comments/src/__workshop__/CommentsListStory.tsx, packages/sanity/src/structure/comments/src/__workshop__/CommentsProviderStory.tsx, packages/sanity/src/structure/comments/src/components/list/CommentThreadLayout.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsList.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItem.tsx, packages/sanity/src/structure/comments/src/context/comments/CommentsProvider.tsx, packages/sanity/src/structure/comments/src/hooks/use-comment-operations/createOperation.ts, packages/sanity/src/structure/comments/src/store/useCommentsStore.ts, packages/sanity/src/structure/comments/src/types.ts, packages/sanity/src/structure/comments/src/utils/buildCommentThreadItems.ts, packages/sanity/src/structure/comments/src/utils/inline-comments/buildRangeDecorationSelectionsFromComments.ts
This pull request introduces a `type` configuration to the comments feature (`"field" | "task"`) to enable the creation of comments in the upcoming Tasks feature. Additionally, the UI components have been made somewhat less tied to the field comments scenario by moving the previously required `fieldPath` value to an optional `payload` property. Although the UI components are still somewhat tied to the field comments scenario, this change is a step in the right direction towards making them more generic and adaptable to other contexts, such as when creating comments on tasks.
- Make sure that field comments works as before
N/A
=> feat(comments): support task comments

packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
This PR adds an `onDoubleClick` to the `ImagePreview` component and opens the `Crop image` dialog when the image preview is double clicked. 
Go to an asset with an image preview and with the ability to crop this image, and double click on the image - it will open the `Crop image` dialog. 
Adds ability to open 'Crop image' dialog by double clicking image preview
=> fix(core): add onDoubleClick to open image crop

dev/test-studio/sanity.config.ts, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/types.ts
This aligns how to enable the tasks feature with how we enable other features, by adding back the `unstable_tasks` flag.
The challenge with the current method is that we have to include untranspiled config in the config by importing it from `packages/sanity/...`. There is no guarantee this will work, however.
- That tasks still works in the staging workspace
=> refactor(tasks): include tasks plugin via config flag

.github/workflows/cli-test.yml, .github/workflows/depCheck.yml, .github/workflows/docReport.yml, .github/workflows/e2e-ct.yml, .github/workflows/e2e-pte.yml, .github/workflows/etl.yml, .github/workflows/formatCheck.yml, .github/workflows/lint-fix-if-needed.yml, .github/workflows/lintPr.yml, .github/workflows/perf.yml, .github/workflows/pnpm-if-needed.yml, .github/workflows/pr-cleanup.yml, .github/workflows/prettier-if-needed.yml, .github/workflows/test.yml, .github/workflows/typeCheck.yml
This aligns how we install dependencies across all our workflow definitions. It's using the same approach as @binoy14 previously added for the e2e test workflow.
- Should we always pass `--config.ignore-scripts=true` when running pnpm install? (side note: why the `config.`-prefix and not just `--ignore-scripts`?)
- CI is taking care of it!
n/a internal
=> fix(ci): align pnpm install across all workflows

packages/sanity/src/core/store/_legacy/authStore/createLoginComponent.tsx, packages/sanity/src/core/store/_legacy/authStore/types.ts, packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceAuth/WorkspaceAuth.tsx
The following PR updates the `origin` parameter of our login to include the current path so that after the user logs in, they should be redirected to the path they were trying to get to instead of having to click the link again.
https://github.com/sanity-io/sanity/assets/10551026/8605fcb6-9767-44b0-802f-0a1340178822
Ensure that the code works and does what is expected. Ensure there are no breaking changes to the API as well (I deprecated a key).
See the video.
- Resolves an issue where users were not redirected to their original destination after re-authenticating, ensuring seamless access to linked content within the Studio.
=> feat(core): redirect to previous path after login

packages/sanity/src/structure/comments/src/components/avatars/SpacerAvatar.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItem.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItemContextMenu.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItemLayout.tsx, packages/sanity/src/structure/comments/src/components/pte/comment-input/CommentInput.tsx, packages/sanity/src/structure/comments/src/components/pte/comment-input/CommentInputInner.tsx
Adds support for avatar config in comments layout.
```
{
parentCommentAvatar: boolean
threadCommentsAvatar: boolean
replyAvatar: boolean
avatarSize: AvatarSize
}
```
Supports building the UI needed for tasks. 
Notice how the avatar size is reduced and also removed from the parent comment.
=> chore(comments): add support for comments layout avatar config

packages/sanity/src/core/form/inputs/DateInputs/base/calendar/Calendar.tsx
Fixes EDX-1124
Removes the previous and next buttons on the month for the calendar input
Before:
After:
Anything I missed?
Code deletion, no test changes
=> fix(core): remove prev and next month buttons in calendar input

.eslintrc.cjs, packages/sanity/src/core/components/hookCollection/GetHookCollectionState.tsx, packages/sanity/src/core/config/document/actions.ts, packages/sanity/src/structure/components/RenderActionCollectionState.tsx, packages/sanity/src/structure/components/pane/PaneContextMenuButton.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx, packages/sanity/src/structure/panes/document/statusBar/ActionMenuButton.tsx, packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
Introduces `groups` into [DocumentActions](https://www.sanity.io/docs/document-actions-api) allowing plugin developers to add actions and decide where they want this actions to show:
- `default` will add the actions to the same position as before, in the footer right next to the publish button.
- `paneActions` will add the action in the context menu right next to the inspectors and other pane actions.
This is initially intended to support creating `tasks` from within a document. 
```
export function ConfirmDialogAction({onComplete}): DocumentActionDescription {
const [dialogOpen, setDialogOpen] = useState(false)
return {
label: 'Show confirm',
onHandle: () => {
setDialogOpen(true)
},
group: ['paneActions'],
dialog: dialogOpen && {
type: 'confirm',
onCancel: onComplete,
onConfirm: () => { …
```
=> feat(core): add groups to document actions, introduce paneActions group

dev/embedded-studio/package.json, package.json, packages/@sanity/types/src/schema/define.ts, packages/@sanity/types/src/schema/test/alias.test.ts, perf/tests/package.json, pnpm-lock.yaml
The following PR upgrade typescript to version 5.4 and updates our type definitions for better compatibility.
- There was a type error on some of the "widden" types. I'm not too sure why that's there but just to unblock I 'fixed' the type error with a cast and a TODO comment to revisit for later.
- I used the newer typescript 5.0 ["const type"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters) parameters to ensure that we're capturing the correct `type`.
Anything I'm missing on these types? Is the cast I added okay for now?
I upgraded one of our starter templates [that broke](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/actions/runs/8186007972/job/22383499811) to typescript 5.4 and pasted the newer type definitions and ran `npm …
=> fix(core): upgrade and fix types for typescript 5.4

dev/test-studio/schema/standard/crossDatasetReference.ts, dev/test-studio/schema/standard/references.ts, packages/sanity/src/core/templates/__tests__/resolve.test.ts, packages/sanity/src/core/templates/validate.ts
A simple follow up to #5889 and adds `_projectId` and `_strengthOnPublish`.
This is the PR description from #5889:
> It is currently not possible to create a cross-dataset reference from an initial value template, as the template validation runs and disallows unknown properties on references, where `_dataset` was not an allowed prop.
> 
> Perhaps we should recurse down the type chain to look for a field that extends from `crossDatasetReference`, but this is beyond what we do for other types - eg we do not check for a `reference` type when encountering `_ref`. Leaving this for a future iteration to improve on if we feel it is worth it.
- Can actually create a cross-dataset reference from an initial value template
I actually tested this one manually and added fields for initial templates in …
=> fix(core): allow `_projectId` and `_strengthOnPublish` in templates

packages/sanity/src/tasks/plugin/TaskCreateAction.tsx, packages/sanity/src/tasks/plugin/TasksBadge.tsx, packages/sanity/src/tasks/plugin/index.tsx
This pull request makes sure that the document action and badge related to Tasks is only included if the feature is enabled.
- Make sure that the document action and badge is only included when the feature is enabled
N/A
=> fix(tasks): enable check for document action and badge

playwright.config.ts
Disabling the github reporter from playwright config for now, as it adds too much noise to be useful (see https://github.com/sanity-io/sanity/pull/5950/files for an example). Figured it was better to disable it for our repo, since removing it from the default reporters defined by `@sanity/test` could lead to unsurprising behavior for other consumers of that package.
Will this actually remove the reporter?
n/a – internal
=> chore(test): exclude the github reporter from playwright tests for now

dev/test-studio/package.json, dev/test-studio/preview/SimpleBlockPortableText.tsx, dev/test-studio/preview/loader.tsx, dev/test-studio/preview/main.tsx, dev/test-studio/sanity.config.ts, dev/test-studio/schema/standard/portableText/simpleBlock.tsx, pnpm-lock.yaml, renovate.json
=> chore: add PTE in Presentation race condition reproduction

packages/@sanity/schema/package.json, packages/@sanity/schema/src/_exports/_internal.ts, packages/@sanity/schema/src/sanity/extractSchema.ts, packages/@sanity/schema/test/extractSchema/__snapshots__/extractSchema.test.ts.snap, packages/@sanity/schema/test/extractSchema/extractSchema.test.ts, packages/@sanity/schema/test/extractSchema/fixtures/assetSourceData.ts, packages/@sanity/schema/test/extractSchema/fixtures/block.ts, packages/@sanity/schema/test/extractSchema/fixtures/fileAsset.ts, packages/@sanity/schema/test/extractSchema/fixtures/geopoint.ts, packages/@sanity/schema/test/extractSchema/fixtures/imageAsset.ts, packages/@sanity/schema/test/extractSchema/fixtures/imageCrop.ts, packages/@sanity/schema/test/extractSchema/fixtures/imageDimensions.ts, packages/@sanity/schema/test/extractSchema/fixtures/imageHotspot.ts, packages/@sanity/schema/test/extractSchema/fixtures/imageMetadata.ts, packages/@sanity/schema/test/extractSchema/fixtures/imagePalette.ts, packages/@sanity/schema/test/extractSchema/fixtures/imagePaletteSwatch.ts, packages/@sanity/schema/test/extractSchema/fixtures/slug.ts, packages/sanity/package.config.ts, packages/sanity/src/_internal/cli/actions/schema/extractAction.ts, packages/sanity/src/_internal/cli/commands/index.ts, packages/sanity/src/_internal/cli/commands/schema/extractSchemaCommand.ts, packages/sanity/src/_internal/cli/threads/extractSchema.ts, pnpm-lock.yaml
Adds a new command that can be executed within a sanity context to extract a JSON representation of the studios schema. This makes it easier for other tools(TM) to consume it without depending on browser environments etc. I tried to base most of the logic on `sanity schema validate` to keep consistency in the repo/package.
Correctness: Do we parse the schema correctly? 
Naming things: It's hard! Can we name the command line argument or flags differently?
Note that we consider this feature **beta**, anything more than in the help text it should be indicated?
```
$ pnpm build
$ sanity schema extract # somewhere there's a sanity.config.ts
```
Beta: Extract sanity schema as JSON, to be consumed by other tools
=> feat: add cmd to generate a JSON representation of schema

packages/sanity/src/core/studio/components/navbar/search/datastores/useStoredSearch.ts, test/e2e/tests/navbar/search.spec.ts
Changes the key of recent searches to fetch from the backend store.
Please feel free to review if the files changed here make sense. Testing suites (like recentSearches.test.tsx) pass -- they are now noisier because of some state updates, but other tests in our suit also unfortunately suffer from the same issue.
Two existing test files are in play here -- recentSearches.test.tsx and navbar.spec.ts. The e2e test won't pass until the backend is up and running in production.
=> feat(core): store recent search history in backend

packages/sanity/src/structure/panes/document/inspectDialog/InspectDialog.tsx, packages/sanity/src/structure/useStructureToolSetting.ts, test/e2e/tests/desk/inspectDialog.spec.ts
Changes the key of inspect mode to be a bit simpler and universal for all documents.
The new key for this setting, the default setting. The test is not confirmed -- please see the below note.
E2E test staged, but can't properly check it until the backend service is out in production.
=> feat(core): fetch inspect mode settings from backend.

packages/sanity/src/tasks/src/tasks/components/activity/TaskActivityEditedAt.tsx, packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityCreatedAt.tsx, packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityLog.tsx, packages/sanity/src/tasks/src/tasks/components/activity/helpers/groupChanges.test.ts, packages/sanity/src/tasks/src/tasks/components/activity/helpers/groupChanges.ts, packages/sanity/src/tasks/src/tasks/components/activity/helpers/index.tsx, packages/sanity/src/tasks/src/tasks/components/activity/helpers/parseTransactions.ts, packages/sanity/src/tasks/src/tasks/components/form/addonWorkspace/TasksAddOnWorkspaceProvider.tsx, packages/sanity/src/tasks/src/tasks/components/form/addonWorkspace/taskSchema.tsx, packages/sanity/src/tasks/src/tasks/components/form/fields/StatusSelector.tsx, packages/sanity/src/tasks/src/tasks/constants/API_VERSION.ts, packages/sanity/src/tasks/src/tasks/constants/TaskStatus.tsx
Adds tasks activity log. 
Shows history changes made by users.
=> feat(tasks): track activity changes with document history.

package.json, packages/@sanity/types/src/schema/test/alias.test.ts, pnpm-lock.yaml
This is a temporary workaround for some weird build issues we've been seeing locally today.
TL;DR: Running: 
```
pnpm i --frozen-lockfile && pnpm -r --filter='./packages/*' --filter='./packages/@sanity/*' build
```
from a fresh clone of this repo fails with the error:
```
sanity:build: [error] Internal Error: Cannot assign isExternal=false for the symbol KeyedSegment \
because it was previously registered with isExternal=true
```
- A new clone of this repo and running the above command should not fail.
n/a
=> chore(deps): pin typescript to 5.3

packages/sanity/src/_internal/cli/commands/migration/createMigrationCommand.ts
When used inside a Studio project subdirectory, the CLI searches parent directories in order to infer the project root. The `migration create` command doesn't currently respect the inferred root, and will attempt to create/use a `migrations` directory in the current working directory. This behaviour is incorrect; it's impossible to run migrations located anywhere other than the `migrations` directory in the project root.
This branch makes `migration create` command respect the inferred project root.
Does this fix make sense?
Attempt to create a migration from a Studio project subdirectory. The migration should always be added to the `migrations` directory in the project root.
=> fix(cli): use inferred project root when creating migrations from subdirectory

packages/sanity/src/core/store/key-value/backends/server.ts, packages/sanity/src/core/studioClient.ts
Updates the default studio client version to the key-value store's date of release. Since we haven't had a significant change in client behavior, and we generally ask that users use a current date for their own API versioning, this should be a non-breaking change, but is required to query our key-value store per internal guidelines.
Is there anything that depended on the old client version? Any unexpected behaviors?
All current tests should behave as normal.
=> chore: update API version for production-ready cellar

packages/sanity/src/core/store/_legacy/user/userStore.ts
This pull request ensures that we do not proceed with fetching the user with `getUser` in `createUserStore` if there's no user id available. This is added because if there's no user id provided, we know that the fetch will fail. So, we can prevent the request from erroring by returning early instead.
- Make sure that `getUser` works as before.
- Does the change make sense?
N/A
=> fix(core): handle no user id in `getUser`

packages/@sanity/portable-text-editor/e2e-tests/__tests__/writingTogether.collaborative.test.ts, packages/@sanity/portable-text-editor/package.json, packages/@sanity/portable-text-editor/src/utils/applyPatch.ts
There is an issue where a certain merge block operation goes rogue when there are multiple editors in a document.
I have pinned this issue down to invalid paths being used when trying to remove the children of a block as part of the transformation happening on the receiving client when a whole block is set through a set patch.
After fixing this, the added test passes (it failed without this fix).
That the changes are ok.
Should be covered by automatic tests now, but see #EDX-946 for more details on how to manually reproduce it.
* Fixed a bug with the Portable Text Editor where merging two text blocks could result in data loss in the topmost block when several editors were inside the document.
=> fix(portable-text-editor): fix and test issue with merge block operation

test/e2e/tests/desk/documentTypeListContextMenu.spec.ts, test/e2e/tests/desk/inspectDialog.spec.ts, test/e2e/tests/navbar/search.spec.ts
Updates previous e2e tests to run successfully.
The changed test files.
Unfortunately with multiple runners and state persisting outside the test environment, search results are not tracked as well as they used to be. However, their cases are covered in recentSearches.test.tsx
=> fix: update tests to match api

packages/sanity/src/core/store/_legacy/datastores.ts, packages/sanity/src/core/store/key-value/KeyValueStore.ts, packages/sanity/src/core/store/key-value/backends/localStorage.ts, packages/sanity/src/core/store/key-value/backends/memory.ts, packages/sanity/src/core/store/key-value/backends/resolve.ts, packages/sanity/src/core/store/key-value/backends/server.ts, packages/sanity/src/core/store/key-value/backends/types.ts, packages/sanity/src/core/store/key-value/types.ts, packages/sanity/src/core/studio/components/navbar/search/datastores/useStoredSearch.ts, packages/sanity/src/core/studioClient.ts, packages/sanity/src/structure/panes/document/inspectDialog/InspectDialog.tsx, packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx, packages/sanity/src/structure/useStructureToolSetting.ts, test/e2e/tests/desk/documentTypeListContextMenu.spec.ts, test/e2e/tests/desk/inspectDialog.spec.ts, test/e2e/tests/navbar/search.spec.ts
We do not currently persist user settings and actions taken in the Studio in a way that follows the user. We store _some_ user choices and actions to browser localStorage which means they do not follow users between desktop and mobile or different browsers. Browsers may also evict localStorage manually or automatically. These settings and actions are then lost and the user may need to reconfigure their experience or accept that things like search history is lost.
Not persisting this data in a universal manner gives a bad user experience since users need to make the same preference choices and settings again and again. Not having this capability also makes it harder for Sanity to develop new features that should follow the user, and we risk either continuing the localStorage limitation in …
=> feat(core): store and fetch user settings from backend

packages/sanity/src/core/search/text-search/createTextSearch.ts
The search request tag was not being included in Text Search API requests.
The dedicated search tag is included when sending Text Search API requests.
When a search request has a dedicated tag, it should be included in the Text Search API request.
| Surface | Tag |
| --- | --- |
| Global search | `sanity.studio.search.global` |
| Reference search | `sanity.studio.search.reference` |
| Cross Dataset Reference search | `sanity.studio.search.cross-dataset-reference` |
Note: Document list search doesn't use a dedicated tag at present.
=> fix(core): include request tag in Text Search API requests

LICENSE, dev/design-studio/LICENSE, examples/blog-studio/LICENSE, examples/clean-studio/LICENSE, examples/ecommerce-studio/LICENSE, examples/movies-studio/LICENSE, packages/@sanity/block-tools/LICENSE, packages/@sanity/cli/LICENSE, packages/@sanity/cli/templates/shopify/LICENSE, packages/@sanity/diff/LICENSE, packages/@sanity/export/LICENSE, packages/@sanity/import-cli/LICENSE, packages/@sanity/import/LICENSE, packages/@sanity/mutator/LICENSE, packages/@sanity/portable-text-editor/LICENSE, packages/@sanity/schema/LICENSE, packages/@sanity/types/LICENSE, packages/@sanity/util/LICENSE, packages/@sanity/vision/LICENSE, packages/create-sanity/LICENSE, packages/groq/LICENSE, packages/sanity/LICENSE, packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/LICENSE
Updates year of our MIT licenses across packages.
Did I miss anything?
Probably not possible.
=> chore: update licenses across packages for current year

packages/sanity/src/structure/useStructureToolSetting.ts
We should ensure we're avoiding unnecessary calls to the backend whenever possible, as well as any unnecessary re-renders. This PR adds a check to ensure actions only happen in the case of new state.
The check and any gotchas for loops or side effects.
This util is tested in an E2E test that is currently being refactored.
=> fix: ensure that useStructureToolSetting updates only when necessary

packages/@sanity/schema/src/sanity/extractSchema.ts, packages/@sanity/schema/test/extractSchema/__snapshots__/extractSchema.test.ts.snap
For some objects(I belive it's nested objects, but yet to verify) we sometimes generate object schema types with name set to `object`. This PR removes the _type if it's object, as it's better to miss data than to be wrong.
One example from the tests are `Homestead`, the compiled schema type look like:
```ts
{
jsonType: 'object',
type: { name: 'object', title: 'Object', type: null, jsonType: 'object' },
name: 'object',
title: 'Homestead',
fields: [
{
name: 'lat',
group: undefined,
fieldset: undefined,
type: [Object]
},
{
name: 'lon',
group: undefined,
fieldset: undefined,
type: [Object]
}
],
options: {},
orderings: [
{ name: 'lat', i18n: [Object], title: 'Lat', by: [Array] },
{ name: 'lon', i18n: [Object], title: 'Lon', by: [Array] }
],
fieldsets: [Getter],
groups: [Getter],
preview: …
```
=> fix: schema extraction object type name

packages/@sanity/util/src/paths.ts, packages/@sanity/util/test/PathUtils.test.ts
Fields named as GROQ data types (`true`, `false`, and `null`) cannot be accessed using dot notation. These fields must instead be serialized using square bracket notation.
Segments names `true`, `false`, or `null` will now be serialized using square bracket notation. All other segments will continue to use dot notation.
```groq
parent.true
```
```groq
parent["true"]
```
You can observe this by executing a GROQ query such as:
```groq
[{
"true": "positive"
}, {
"false": "negative"
}, {
"null": "nothing"
}].null
// attribute expected
```
Versus:
```groq
[{
"true": "positive"
}, {
"false": "negative"
}, {
"null": "nothing"
}]["null"]
// [
//   null,
//   null,
//   "nothing"
// ]
```
The paths created by the `toString` function are correct.
This branch adds tests to the …
=> fix(util): safely stringify path segments named as GROQ data types (e.g. `null`)

packages/sanity/src/core/search/common/deriveSearchWeightsFromType.ts
When deriving search weights, we previously relied on a new `pathToString` function that replicated much of the functionality already implemented in the `toString` function from `@sanity/util/paths`. The one additional piece of functionality (handling segments that are `true`, `false`, or `null`) has now been implemented in #5986. Once merged, we can remove the redundant `pathToString` function and switch to the `toString` function from `@sanity/util/paths`.
- Search requests are constructed correctly.
There are tests for this functionality in `packages/sanity/src/core/search/common/__tests__/deriveSearchWeightsFromType.test.ts`.
=> refactor(core): use path `toString` function from `@sanity/util/paths`

packages/sanity/src/core/search/common/types.ts, packages/sanity/src/core/search/text-search/createTextSearch.test.ts, packages/sanity/src/core/search/text-search/createTextSearch.ts, packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.test.ts, packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts
This branch finalises the Text Search API ordering integration. Ordering is now formatted correctly and is included in Text Search API requests.
**Note: The Text Search API functionality to support this has not yet been deployed to production.**
It also includes a fix for global search results not resetting after ordering has changed. We didn't catch this before because ordering wasn't working at all.
Does ordering results from global search and document lists work as expected?
The `packages/sanity/src/core/search/text-search/createTextSearch.test.ts` test suite ensures ordering requests are formatted correctly.
=> feat(core): integrate with Text Search API ordering

packages/sanity/src/tasks/src/tasks/components/sidebar/TasksHeaderDraftsMenu.tsx
This pull request makes sure that we only display tasks with edits in the drafts menu. 
- Make sure that only tasks with edits is displayed in the drafts menu
N/A
=> fix(tasks): only display tasks with edits in the drafts menu

packages/sanity/src/core/studio/components/navbar/search/datastores/recentSearches.ts
Since we moved the recent search results to a server-side service, we started seeing duplicate results in the global search results. The previous implementation, which stored search results in local storage, stringified recent searches before storing them and compared stringified new searches against them.
Since we switched to using a backend service, we could no longer rely on keys being in the same order. This PR uses the `isEqual` lodash method (used in many other places in the studio) to more reliably compare the values of the objects, rather than a string result.
The changed file. Any performance or other repercussions from using this comparison.
Tests already exist for this utility, but did not catch this because of mocking. A ticket has been created to better address this in the …
=> fix: use more reliable comparison in deduping search results

packages/@sanity/codegen/.depcheckrc.json, packages/@sanity/codegen/.eslintrc.cjs, packages/@sanity/codegen/.gitignore, packages/@sanity/codegen/README.md, packages/@sanity/codegen/jest.config.cjs, packages/@sanity/codegen/package.config.ts, packages/@sanity/codegen/package.json, packages/@sanity/codegen/src/_exports/index.ts, packages/@sanity/codegen/tsconfig.json, packages/@sanity/codegen/tsconfig.lib.json, packages/@sanity/codegen/tsdoc.json, pnpm-lock.yaml, tsconfig.json
This PR introduces a skeleton for the new codegen package, it should just introduce the infrastructure and tooling for the package.
Features are introduced in the subsequent stacked PRs.
I will wait to merge the PRs until all prs are approved and ready ✅ 
* Package setup and general configuration
N/A
N/A - not to include in release notes
=> feat(codegen): add codegen skeleton package

packages/@sanity/codegen/babel.config.json, packages/@sanity/codegen/package.json, packages/@sanity/codegen/src/_exports/index.ts, packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts, packages/@sanity/codegen/src/typescript/__tests__/fixtures/exportStar.ts, packages/@sanity/codegen/src/typescript/__tests__/fixtures/exportVar.ts, packages/@sanity/codegen/src/typescript/__tests__/fixtures/source1.ts, packages/@sanity/codegen/src/typescript/__tests__/fixtures/source2.ts, packages/@sanity/codegen/src/typescript/expressionResolvers.ts, packages/@sanity/codegen/src/typescript/findQueriesInSource.ts, packages/@sanity/codegen/src/typescript/moduleResolver.ts, packages/@sanity/codegen/src/typescript/parseSource.ts, packages/@sanity/codegen/src/typescript/registerBabel.ts, pnpm-lock.yaml
This PR adds babel runtime capabilities to scan a given source file for groq queries.
It checks for GROQ tagged template literal that's assigned to a variable, and tries to extract the value. It tries to follow variable references through resolving file local variables, but also imports/exports. 
* Correctness: Are we missing any critical functionality when parsing the source?
* Code quality: This has been a long running branch. Any suggestion on improving quality of life for the code is very welcome!
We've added the tests for the most expected code paths, but more suggestions are also welcome.
We don't test the custom resolver now, as it's deemed best effort... 
N/A - No notes needed.
=> feat(codegen): add groq finder methods.

packages/@sanity/codegen/package.json, packages/@sanity/codegen/src/_exports/index.ts, packages/@sanity/codegen/src/readSchema.ts, packages/@sanity/codegen/src/typescript/__tests__/__snapshots__/typeGenerator.test.ts.snap, packages/@sanity/codegen/src/typescript/__tests__/findQueriesInPath.test.ts, packages/@sanity/codegen/src/typescript/__tests__/fixtures/schema.json, packages/@sanity/codegen/src/typescript/__tests__/typeGenerator.test.ts, packages/@sanity/codegen/src/typescript/expressionResolvers.ts, packages/@sanity/codegen/src/typescript/findQueriesInPath.ts, packages/@sanity/codegen/src/typescript/typeGenerator.ts, pnpm-lock.yaml
This PR adds type generation method given a set of TypeNodes. It can generate type nodes from either a schema, or a TypeNode and return typescript types as a string.
* `readSchema.ts`: We don't provide any validation that the schema read is correct atm. That should be fine for now, as all schemas should be generated by the schema extract cmd.
We should have good coverage on the type generation methods
N/A - No notes needed
=> feat(codegen): add typegen methods to codegen package

.eslintrc.cjs, packages/sanity/src/tasks/i18n/index.ts, packages/sanity/src/tasks/i18n/resources.ts, packages/sanity/src/tasks/index.ts, packages/sanity/src/tasks/plugin/TaskCreateAction.tsx, packages/sanity/src/tasks/plugin/TasksFooterOpenTasks.tsx, packages/sanity/src/tasks/plugin/TasksStudioNavbar.tsx, packages/sanity/src/tasks/plugin/index.tsx, packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityCommentInput.tsx, packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityCreatedAt.tsx, packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityLog.tsx, packages/sanity/src/tasks/src/tasks/components/form/CurrentWorkspaceProvider.tsx, packages/sanity/src/tasks/src/tasks/components/form/RemoveTaskDialog.tsx, packages/sanity/src/tasks/src/tasks/components/form/fields/DateEditFormField.tsx, packages/sanity/src/tasks/src/tasks/components/form/fields/DescriptionInput.tsx, packages/sanity/src/tasks/src/tasks/components/form/fields/TargetField.tsx, packages/sanity/src/tasks/src/tasks/components/form/fields/assignee/AssigneeCreateFormField.tsx, packages/sanity/src/tasks/src/tasks/components/form/fields/assignee/AssigneeEditFormField.tsx, packages/sanity/src/tasks/src/tasks/components/form/fields/assignee/AssigneeSelectionMenu.tsx, packages/sanity/src/tasks/src/tasks/components/form/tasksFormBuilder/FormCreate.tsx, packages/sanity/src/tasks/src/tasks/components/form/tasksFormBuilder/FormEdit.tsx, packages/sanity/src/tasks/src/tasks/components/list/TasksList.tsx, packages/sanity/src/tasks/src/tasks/components/sidebar/TasksActiveTabNavigation.tsx, packages/sanity/src/tasks/src/tasks/components/sidebar/TasksHeaderDraftsMenu.tsx, packages/sanity/src/tasks/src/tasks/components/sidebar/TasksSidebarHeader.tsx
Fixes EDX-1072
Extracting static strings for Task feature into localizable resource file
Are the key names accurate?
Did I miss any strings?
Manual testing and eslint
Nothing needed for release notes
=> feat(tasks): Localize Task feature

packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx, packages/sanity/src/core/form/inputs/PortableText/object/modals/ObjectEditModal.tsx, packages/sanity/src/core/form/inputs/PortableText/object/modals/PopoverModal.tsx
It was decided that the width of the reference selectors in the PT should be increased - this has already been merged.
For consistency, the default width of the **all** inline popovers in PT is increased to match the other inline popovers in portable text. I've therefore now set the default width in the `RootPopover` instead and removed it from the `InlineObjects` popover. 
This default width can be overwritten in the schema. 
That the width of all inline objects in the PT has a default width that is wider. 
Increased width of all inline PT popovers.
=> fix(core): increase default width of PT inline popovers

packages/sanity/src/structure/comments/plugin/field/CommentsField.tsx, packages/sanity/src/structure/comments/plugin/input/components/CommentsPortableTextInput.tsx, packages/sanity/src/structure/comments/src/context/comments/CommentsProvider.tsx, packages/sanity/src/structure/comments/src/context/comments/types.ts
This pull request ensures that the user has `read` permissions on the current document to determine whether the comments UI should be displayed in fields. The add-on dataset permission allows users with `read` access to both read and write comments, making it the only necessary permission to check.
- Ensure the permission check functions correctly by testing with various roles.
N/A
=> fix(comments): permission check

packages/@sanity/codegen/package.json
When generating types we depend on babel.config.json being bundled with the package.
```
» ls /Users/sgulseth/workspace/src/github.com/sanity-io/turtle-blue/node_modules/.pnpm/@sanity+codegen@3.35.0/node_modules/@sanity/codegen/
LICENSE  README.md  lib/  node_modules/  package.json  src/
```
Confirmed that the file gets added when running `npm pack .` in this branch.
n/a
=> fix(codegen): include babel.config.json in the published package

packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts, packages/@sanity/codegen/src/typescript/findQueriesInSource.ts, packages/sanity/src/_internal/cli/threads/typegenGenerate.ts
Moves `Result` appending to the type identifier into the type generation. This way we can keep the actual query name across usages.
👍 
N/A - no notes needed
=> refactor(codegen): move Result appending into type generation

packages/sanity/src/structure/comments/src/components/list/CommentsListItemContextMenu.tsx
This pull request ensures that the resolve action is hidden from a comment item's context menu when no handler is provided.
- Verify that the resolve action is hidden when no handler is provided.
N/A
=> fix(comments): hide resolve action if no handler is provided

packages/sanity/src/core/studio/addonDataset/AddonDatasetProvider.tsx
Fixes an issue in which when trying to create the addon dataset through the tasks plugin, this was not being created.
This is caused because the `ready: true` value was only set if the dataset name exists.
By updating this, the addon provider will return `ready:true` after fetching the dataset, either it exists or not. 
This flag is used by [`<TasksAddonWorkspaceProvider />`](https://github.com/sanity-io/sanity/blob/fix-task-addon-creation/packages/sanity/src/tasks/src/tasks/components/form/addonWorkspace/TasksAddOnWorkspaceProvider.tsx#L68) to decide if it should or not create the addon dataset.
=> fix(tasks): update how addonDatasetProvider ready state is set

packages/sanity/src/tasks/src/tasks/components/activity/TasksActivityLog.tsx, packages/sanity/src/tasks/src/tasks/components/form/tasksFormBuilder/FormEdit.tsx, packages/sanity/src/tasks/src/tasks/hooks/useActivityLog.ts
When creating a comment inside a task we need to pass a notification context for it.
The data obtained for the context was incorrect because it was pulling from the addon workspace instead the users current workspace. 
This Pr updates this to pull the data from the correct workspace.
It also moves `useActivityLog` to the hooks folder, and uses it from the FormEdit, given that hook needs to have access to the addon workspace.
=> fix(tasks): update info passed to the tasks comments notification context

packages/@sanity/codegen/src/typescript/__tests__/findQueriesInPath.test.ts, packages/@sanity/codegen/src/typescript/findQueriesInPath.ts
We were using absolute paths, so we ended up printing user information in the type comments.
Now we generate:
```
// Source: src/pages/resources/[slug]/index.tsx
// Variable: categoryQuery
// Query: ...
```
👍 
=> fix(codegen): use relative path when globbing for files

packages/sanity/src/tasks/src/tasks/context/enabled/TasksEnabledProvider.tsx
Add new `sanityTasks` flag.
We are introducing a new flag to require this version of the studio in order to get the tasks feature enabled.
We are keeping the staging flag until the new flag is added to production and staging.
=> fix(tasks): add new sanityTasks flag

packages/sanity/src/structure/__workshop__/LoadingPaneStory.tsx, packages/sanity/src/structure/__workshop__/index.ts, packages/sanity/src/structure/panes/loading/LoadingPane.tsx
While the structure panes are resolving (when using async resolvers), we show one or more loading messages. It starts with a "Loading..." message, shown after X ms. Later, after X seconds, it is supposed to show a "Still loading..." followed by a "Check if there's something wrong with your structure definition" kind of thing.
This code path has been broken for a while now, it seems:
1. The i18n changes had an error, so we're actually showing the resource key instead of the translated message for the first loading message
2. After v3, we checked for a subscribe method on what hopefully is an observable of loading messages, but we _returned_ if that was the case, when we actually wanted the opposite. If what was passed did _not_ have a subscribe method, we would actually have crashed here. …
=> fix(structure): use correct loading messages while resolving panes

packages/sanity/src/structure/comments/plugin/field/CommentsField.tsx, packages/sanity/src/structure/comments/plugin/input/components/CommentsPortableTextInput.tsx, packages/sanity/src/structure/comments/src/context/comments/CommentsProvider.tsx, packages/sanity/src/structure/comments/src/context/comments/types.ts
This pull request addresses an issue where the PTE changes from fullscreen to collapsed when content is changed in the editor. This problem was caused by the permission check logic for comments introduced in #6057.
The issue can be resolved by storing the permission result in a `useRef` instead of returning the value directly from `useDocumentValuePermissions` in the `CommentsProvider`. However, since users can both **create** and **read** comments if they only have **read** permissions, this permission check is not entirely necessary. This is because if a user does not have **read** permissions, they would not be able to see the document and, therefore, could not create a comment.
With this consideration, this pull request reverts the permission check logic introduced in #6057, thereby …
=> fix(comments): drop permission check

packages/sanity/src/structure/comments/plugin/inspector/CommentsInspectorHeader.tsx
Fixes EDX-728
Before:
After:
Is this icon correct?
Simple icon change
=> fix(comments): update close icon to be consistent

packages/@sanity/cli/src/commands/typegen/generateTypesCommand.ts, packages/sanity/src/_internal/cli/commands/schema/extractSchemaCommand.ts
We now want to display both schema extract and typegen in `--help`
n/a
=> chore(typegen): show schema extraction and typegen in help texts

dev/test-studio/schema/standard/portableText/allTheBellsAndWhistles.ts, packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx
Same issue as in https://github.com/sanity-io/sanity/pull/5766 but in this case affecting inline objects.
When we have validation errors the tooltip is enabled, when validation errors disappear the tooltip is disabled.
Making that update when the modal is open it will trigger a "unmount" and "re-mount" of the InlineObject causing the  modal to unmount and remount, triggering the animation again and losing the input focus.
By checking if the modal is open to **enable / disable** the tooltip, we can be sure that this component won't unmount and mount causing  issues. 
https://github.com/sanity-io/sanity/assets/46196328/f2ca9093-7d42-4059-b09f-cec3bc221fd7
=> fix(pte): PTE inline block object modal closing on validation state changes

packages/@sanity/schema/src/sanity/extractSchema.ts, packages/@sanity/schema/test/extractSchema/extractSchema.test.ts
We were asserting the optional value wrong for required fields 🤦
Agree that it's correct now?
✅  
fixes a bug, where all fields got marked as non-optional, when extracting schema with `--enforce-required-fields`
=> fix(schema): correctly assert optional fields with enforce required fields

packages/@sanity/cli/src/actions/init-plugin/bootstrapFromTemplate.ts, packages/@sanity/cli/test/shared/request.ts, packages/@sanity/export/src/requestStream.js, packages/@sanity/import-cli/src/sanity-import.js, packages/@sanity/import/src/util/getHashedBufferForUri.js, packages/@sanity/import/test/helpers/helpers.js, packages/sanity/src/_internal/cli/actions/backup/downloadAsset.ts, packages/sanity/src/_internal/cli/actions/backup/downloadDocument.ts, packages/sanity/src/_internal/cli/commands/dataset/importDatasetCommand.ts, packages/sanity/src/_internal/cli/util/getUrlHeaders.ts
This is done to unblock us - more investigation needed into whether the rule is wrong or the module is wrong, but seems to work fine so lets make our builds work for now.
None.
=> chore(import): disable `import/extensions` rule for middleware import

packages/@sanity/schema/src/sanity/extractSchema.ts, packages/@sanity/schema/test/extractSchema/extractSchema.test.ts, packages/@sanity/schema/test/legacy/fixtures/schemas/index.ts, packages/@sanity/schema/test/legacy/fixtures/schemas/listObjectOption.ts
We have gotten reports that `createStringTypeNodeDefintion` throws an error `stringSchemaType.options?.list.map is not a function` this indiciates that we, even though the types & docs says it will be an array, are not receiving an array.
I've noticed that in other parts of the code base we are guarding for `list` being an array https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/block-tools/src/util/blockContentTypeFeatures.ts#L115
My suspicion is that we handle plugin types incorrectly, the report indicated usage of a [visual-options](https://github.com/fddigital-uk/sanity-plugin-visual-options/blob/trunk/src/index.js#L7-L14), which might indicate that we are parsing plugin types incorrectly.
I think this work around should be fine for now? Will have a look at the root case …
=> fix(schemaExtract): guard for list options not being an array

packages/@sanity/vision/src/codemirror/extensions.ts
Fixes an annoying bug where code mirror would insert another new line on cmd-return, which also executes the query
Should be safe, tested fine on mac
n/a
Fix  bug where Vision would insert another new line on cmd-return.
=> fix(vision): fixes bug where codemirror would insert a new line on cmd-return

packages/sanity/src/tasks/i18n/resources.ts, packages/sanity/src/tasks/src/tasks/components/list/DocumentPreview.tsx, packages/sanity/src/tasks/src/tasks/components/list/EmptyStates.tsx, packages/sanity/src/tasks/src/tasks/components/list/TasksList.tsx, packages/sanity/src/tasks/src/tasks/hooks/useActivityLog.ts
- Adds empty states to tasks. To improve discoverability of tasks, empty states are modified, including more details and how's to.
- Fixes an issue when removing tasks.
- Fixes overflow issue in tasks document preview.
=> feat(tasks): add tasks empty states

.github/CODEOWNERS
Adds CL team as codeowner for codegen related packages and files.
Is the format correct? Did I miss any packages?
N/A
N/A - no notes needed
=> chore(codegen): add cl as codeowners for {code,type}gen

packages/@sanity/cli/src/workers/typegenGenerate.ts, packages/@sanity/codegen/src/__tests__/safeParseQuery.test.ts, packages/@sanity/codegen/src/_exports/index.ts, packages/@sanity/codegen/src/safeParseQuery.ts
Attempt to find occurrences of parameters used in groq queries, and extract the parameter.
Can this have any unintended side effects?
Any more variants we should test for?
=> feat(codegen): attempt to parse groq queries with parameter in slices

packages/@sanity/cli/src/actions/init-project/initProject.ts, packages/@sanity/cli/src/actions/init-project/templates/index.ts, packages/@sanity/cli/src/actions/init-project/templates/quickstart.ts, packages/@sanity/cli/templates/quickstart/README.md, packages/@sanity/cli/templates/quickstart/schemaTypes/index.js, packages/@sanity/cli/templates/quickstart/static/.gitkeep
Project metadata.template should reflect if the --quickstart flag was used
Project metadata should show `cli-quickstart` rather than `cli-clean` if the --quickstart flag was used for pulling down a project and its schema
=> feat: indicate in metadata that the quickstart option was used in project creation

packages/sanity/src/core/i18n/Translate.tsx, packages/sanity/src/core/i18n/__tests__/Translate.test.tsx, packages/sanity/src/core/i18n/__tests__/simpleParser.test.ts, packages/sanity/src/core/i18n/simpleParser.ts
It seems we [used a formatter](https://github.com/sanity-io/sanity/issues/6003) in a resource passed to `<Translate>`, which won't work as the "simple parser" does not reimplement all the logic from i18next. I initially did an approach where I changed the key to not use a formatter, but it quickly got a bit messy to think about whether the key should be a _new_ key, and how to reason about old versions of it.
Instead, I chose to implement _partial_ support for formatters inside of the `Translate` component - currently only for the `list` formatter, and only without arguments. In time we can see if we can expand on this, but this fixes #6003 and moves us a bit forward at least.
- Code makes sense
- There aren't any regressions in how this works
- Added tests for both parser and for the …
=> fix(i18n): allow list formatter without arguments in `Translate` component

packages/sanity/src/core/config/flattenConfig.ts
🟡 Suggestions will be highly appreciated  🟡 
- `Tasks` plugin is inserted into the studios through the `structure` plugin [here](https://github.com/sanity-io/sanity/blob/remove-duplicated-plugin/packages/sanity/src/structure/structureTool.ts#L105).
- Users could be importing more than once the `structure` plugin in their studios, this produces an unwanted result in which `tasks` plugin is inserted as many times as the structure plugin.   <img width="400" alt="Screenshot 2024-03-26 at 19 58 18" src="https://github.com/sanity-io/sanity/assets/46196328/fdf499dc-d68a-4afb-883c-a156011b0f11">
It checks in the flattenConfig function for the tasks plugin, and removes it from the `allPlugins` list, and adds it back only once.
Eventually, we will need to have a way to add `default plugins` into …
=> fix(core): remove duplicateds tasks plugins

packages/@sanity/cli/src/commands/index.ts, packages/@sanity/cli/src/commands/typegen/typegenGroup.ts
Adds missing typegen group cmd
```
» pnpm sanity help
usage: sanity [--default] [-v|--version] [-d|--debug] [-h|--help] <command> [<args>]
Commands:
backup     Manage backups.
build      Builds the Sanity Studio configuration into a static bundle
codemod    Updates Sanity Studio codebase with a code modification script
cors       Configures CORS settings for Sanity projects
dataset    Manages datasets, like create or delete, within projects
debug      Provides diagnostic info for Sanity Studio troubleshooting
deploy     Builds and deploys Sanity Studio to Sanity hosting
dev        Starts a local dev server for Sanity Studio with live reloading
docs       Opens Sanity Studio documentation in your web browser
documents  Manages documents in your Sanity Content Lake datasets
exec …
```
=> fix(typegen): add placeholder group to allow typegen to show in help

packages/sanity/src/tasks/src/tasks/components/form/fields/assignee/AssigneeSelectionMenu.tsx
When searching for users in the tasks plugin, we are using lodash deburr to convert all the letters to latin letters. Also, we lowercase the display name. 
This, was going all the way to the UI, which should not happen.
This PR addresses that, by introducing a new property `searchName` when searching for users to avoid modifying the names that will be displayed in the UI.
Fixes an issue in which user names displayed in the user selection dropdown inside tasks were changing when filtering
=> fix(tasks): don't lowercase users when searching in the assignee menu

packages/sanity/src/core/form/members/object/fields/ArrayOfObjectsField.tsx, packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
This PR makes some improvements to how the `DocumentPaneProvider` handles paths, specifically `openPath`. It also makes a small change so that missing PTE input blur events are now emitted.
There are a few UI issues that users are unlikely to encounter within the context of the Structure tool—but become much more prevalent within the context of Presentation—as they only occur when `openPath` state is set from a path provided via the URL:
- PTE cursor (sometimes) jumps to beginning of a block on focus.
- PTE scrolls to previously opened block on blur.
- PTE scrolls to block on click.
In addition:
- The PTE currently emits no handleable blur event (needed to fix these issues).
- Presentation's persistence of the path in the URL causes duplicate element focus.
- This duplication causes …
=> fix: improve document pane path handling

packages/@sanity/schema/src/sanity/extractSchema.ts, packages/@sanity/schema/test/extractSchema/extractSchema.test.ts
Follow up from #6151 
If the schema is setting `assetRequired()` on an asset-field, we mark the underlying asset attribute as non-optional
Correct implementation? Tested it with a compiled schema as well, and works as expected.
=> feat(schema): handle assetRequired when extracting schema with enforceRequiredFields

packages/@sanity/cli/package.json, packages/@sanity/codegen/package.json, packages/@sanity/migrate/package.json, packages/@sanity/schema/package.json, packages/sanity/package.json, pnpm-lock.yaml
Upgrades groq-js to latest version, improves typegen support
=> chore(deps): upgrade groq-js to latest

packages/sanity/src/core/studio/components/navbar/search/components/SearchPopover.tsx, packages/sanity/src/core/studio/components/navbar/search/components/common/SearchWrapper.tsx, packages/sanity/src/tasks/src/tasks/components/form/fields/TargetField.tsx
Fixes an issue in which when tasks panel is open, cmd + K search changes target document rather than searches the studio.
This happens because the SearchPopover takes a `onOpen` prop which is triggered by the[ `useSearchHotkey` ](https://github.com/sanity-io/sanity/blob/edx-1223/packages/sanity/src/core/studio/components/navbar/search/hooks/useSearchHotkeys.ts#L38-L39) hook. Producing an undesired effect of opening by duplicated the search popover when tasks is open. Actually triggering the changes of the task form instead of the search change. 
Making this prop optional, and not passing it through from the `TargetField` fixes the issue.
Fixes an issue in which when the tasks panel is open, cmd + K search changes target document rather than searches the studio.
=> fix(tasks): don't open tasks search on hotkey + enter

packages/sanity/src/_internal/cli/actions/schema/extractAction.ts
Helps debugging that the flag is turned on, it's also consistent with the spinner text shown when the extraction is running
spelling :p 
n/a
=> chore(codegen): add enforceRequriedFields to spinner output

.github/renovate.json
Updates renovatebot to use the preset that specifies the latest stable `framer-motion` that we've thoroughly tested in `@sanity/presentation` and `@sanity/ui`: https://github.com/sanity-io/renovate-config/commit/23fe9b1ec84932ef8487f91908b2c452c2c4c8e9
=> chore(renovate): pin framer-motion to known stable

.eslintrc.cjs
Adds a lint rule to enforce named `styled` import from `styled-components`
=> chore(eslint): add eslint rule to enforce named styled import from styled-components

packages/sanity/src/structure/comments/src/context/upsell/CommentsUpsellProvider.tsx
fixes: SGH-6 
fixes: https://github.com/sanity-io/visual-editing/issues/1079
Some users continue reporting CORS issues with the request done to `'/journey/comments` this removes the custom options given they are not needed and where added for the initial iteration in which we requested the data directly from one of our studios. 
This change, aligns this request to the one in [free trial provider](https://github.com/sanity-io/sanity/blob/edx-1082/packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrialProvider.tsx#L68).  
Fixes CORS issue report accessing to `/journey/comments`
=> fix(core): remove custom options in comments upsell request

packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Annotations.spec.tsx, packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx, packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
With the changes pushed in https://github.com/sanity-io/sanity/pull/6129 a bug was introduced into the PTE editor.
Annotations wont open.
The issue is generated by the onBlur action, when it's triggered, it's setting as `openPath` the blurred path. 
This specific change was introduced in that PR, possibly an oversight?
Fixes an issue in PTE in which annotations were not opening by a bug introduced in v3.36.3
=> fix(structure): annotations not opening in portable text editor

packages/@sanity/cli/test/telemetry.test.ts
Tired of re-running failed jobs due to one of these timing out
=> chore: reduce test flakiness by increasing timeout to 60s

packages/sanity/src/core/schema/types/slug.ts
With the new schema extraction and typegen functionality, we're seeing a lot of signal around required fields in types. Slug fields can be set as `Rule.required()`, but the resulting type will have a `current` property that is _not_ required. This may require some explanation:
Our studio schema validation currently works on a "parent is present" basis. Consider the following schema stub:
```ts
[
{
name: 'business',
fields: [
{
name: 'address',
type: 'address',
},
],
},
{
name: 'address',
fields: [
{
name: 'street',
validation: Rule => Rule.required(),
},
{
name: 'zip',
type: 'number',
}
],
},
]
```
A `business` document without an address is considered valid, since the `address` _field_  is not marked as required. A document with an …
=> fix(schema): make `current` field for slugs required

packages/@sanity/cli/src/util/noSuchCommandText.ts
If you use a command that does not exist, such as `sanity update`, but there is a similarly named command (`sanity upgrade`), we suggest it. However, this currently includes commands that were part of Sanity v2 and that we no longer support. This PR prevents the CLI from suggesting these.
`sanity update` does not suggest `sanity upgrade`.
Did not add tests for this since it is not the most critical functionality to maintain, and we'll be phasing out support for v2 commands in the next major.
- Fixes an issue where the CLI might suggest commands that only work on Sanity v2 if you mistype a command name
=> fix(cli): do not suggest v2 cli commands on "no such command" error

packages/@sanity/cli/src/actions/typegen/generateAction.ts, packages/@sanity/cli/src/commands/typegen/generateTypesCommand.ts, packages/@sanity/cli/test/__fixtures__/v3/folder-typegen.json, packages/@sanity/cli/test/__fixtures__/v3/missing-typegen.json, packages/@sanity/cli/test/__fixtures__/v3/working-schema.json, packages/@sanity/cli/test/__fixtures__/v3/working-typegen.json, packages/@sanity/cli/test/typegen.test.ts
When you run `sanity typegen generate`, a fairly common case is that one may have forgotten to run `sanity schema extract` first. This currently gives a rather unhelpful error (if you're unfamiliar with the setup):
```
Error: ENOENT: no such file or directory, open './schema.json'
```
With this PR, I propose that we give a more helpful error if you have not provided even a custom path for the schema:
```
Error: Schema file not found: ./schema.json - did you run "sanity schema extract"?
```
I also noticed that using a `--config-path` flag did not work, only `--configPath`. To be consistent with other CLI commands, I changed this to allow both forms.
Added some basic tests to ensure that the different forms work and gives the expected output.
- Improved error message when extracted schema …
=> fix(cli): improve error handling on missing extracted schema

packages/sanity/src/_internal/cli/util/mockBrowserEnvironment.ts
The mocked browser environment that we use for commands that need access to the schema did not have a stub loader for the SCSS and SASS file extensions. While not super common, if they are used in a dependency, they will currently crash.
This PR uses the stub loader for these file extensions, which just returns an empty object as the imported module. 
There currently aren't any tests for the browser environment, and we're wanting to pursue something like [vite-node](https://www.npmjs.com/package/vite-node) to see if we can more closely resemble the environment that we have in the browser long term. In the meantime, I will not spend time adding tests for this since we already know this approach works for other extensions, such as `.css`.
- Fixes an issue where importing `.scss` or `.sass` …
=> fix(cli): use stub file loader for scss, sass extensions

.github/renovate.json
=> refactor(renovate): ignore `slate` and `slate-react` as they're bumped manually

packages/@sanity/cli/src/studioDependencies.ts, packages/sanity/src/_internal/cli/util/checkStudioDependencyVersions.ts
This formalizes the requirement of using `styled-components@6.x` and `@sanity/ui@2.x` by showing an error on sanity start if the studio project depends on incompatible versions of these. The error will include a link to a help article explaining more in-depth details about how to upgrade.
Any downside to making this move? We have been "soft requiring" these versions for a while, and you could make the argument that we should have added these sooner :)
n/a
- Formalize requirement of styled-components@6 and @sanity/ui@2.
=> fix(cli): formalize requirement of styled-components@6 and @sanity/ui@2

packages/sanity/src/tasks/plugin/TasksStudioNavbar.tsx
Change tasks button in nav to be toggle.
Clicking the task button should open the tasks sidebar if it's closed and should close it if it's open.
=> fix(tasks): change tasks button in nav to be toggle

packages/sanity/src/core/store/_legacy/document/document-pair/operations/publish.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operations/publish.ts, packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormHeader.tsx, test/e2e/tests/document-actions/publish.spec.ts
Note: I've skipped, rather than removed, the redundant unit tests for now. This is in case we keep the existing functionality behind a feature flag, and saves us regenerating test snapshots for now. I've made the implementation changes directly so it's easier to follow the changes (if we decided to feature flag this, we can easily grab the existing implementation from git).
=> feat(sanity): use actions API when publishing documents

dev/test-studio/sanity.config.ts, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/types.ts, packages/sanity/src/core/store/_legacy/datastores.ts, packages/sanity/src/core/store/_legacy/document/document-pair/actionTypes.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/consistencyStatus.ts, packages/sanity/src/core/store/_legacy/document/document-pair/documentEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/editOperations.ts, packages/sanity/src/core/store/_legacy/document/document-pair/editState.ts, packages/sanity/src/core/store/_legacy/document/document-pair/memoizeKeyGen.ts, packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operationArgs.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operations/helpers.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operations/types.ts, packages/sanity/src/core/store/_legacy/document/document-pair/remoteSnapshots.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/patch.ts, packages/sanity/src/core/store/_legacy/document/document-pair/snapshotPair.ts, packages/sanity/src/core/store/_legacy/document/document-store.ts, packages/sanity/src/core/store/_legacy/document/getPairListener.ts, packages/sanity/src/core/store/_legacy/grants/documentPairPermissions.ts, packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts
After some discussion, we decided that it would be beneficial to be able to internally use document actions in the studio sooner rather than later, to be able to dogfood and detect errors.
This PR adds a parameter to studio config to enable server actions.
It changes the datastores invocation of documentStore to read from the workspace, and pass that parameter down.
Within the document store, it will pass that parameter to various functions that change behavior.
The most dramatic changes were needed in checkoutPair, which is used in many places, and is sometimes memoized or consumed as `snapshotPair`.
All of these changes are temporary and should be removed once these APIs become permanent.
It also includes @bjoerge 's changes from #6116, since that refactored checkoutPair and …
=> feat(core): add serverActions flag to config

packages/sanity/src/core/store/_legacy/document/document-pair/operations/unpublish.ts
=> feat(sanity): use Actions API when unpublishing documents

packages/sanity/src/core/store/_legacy/document/document-pair/operations/delete.ts
=> feat(sanity): use actions API when deleting documents

packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts
Both the `createSearch` factory and the returned `search` function accept a `filter` option. These filters are additive (joined together using the `&&` operator). We were accidentally providing the same filter to both functions, causing it to be needlessly duplicated in the produced search request.
Document list filtering and search works the same way as before, but the produced search request no longer contains duplicated filters.
We do not have tests for the `listenSearchQuery` function at the moment. Given this is a very limited change, I've not invested in adding a test suite at this point in time.
=> fix(structure): prevent duplication of search filters when `listenSearchQuery` is used (e.g. in document lists)

packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operations/helpers.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/delete.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/publish.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/unpublish.ts, packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormHeader.tsx, test/e2e/tests/document-actions/publish.spec.ts
This branch adds Actions API integrations for the following document operations:
- Publish
- Unpublish
- Delete
They can be enabled using the `unstable_serverActions.enabled` configuration option.
=> feat(core): adopt Actions API

packages/sanity/src/tasks/i18n/resources.ts, packages/sanity/src/tasks/src/tasks/components/sidebar/TaskListFeedbackFooter.tsx, packages/sanity/src/tasks/src/tasks/components/sidebar/TasksSidebar.tsx
Adds feedback link to tasks. Inviting users to add feedback on how we can improve.
=> feat(tasks): add feedback link to tasks

.github/workflows/testExports.yml, package.json, packages/@repo/test-exports/.depcheckrc.json, packages/@repo/test-exports/package.json, packages/@repo/test-exports/test/exports.cjs, packages/@repo/test-exports/test/exports.test.cjs, packages/@repo/test-exports/test/exports.test.mjs, packages/@repo/test-exports/tsconfig.json, packages/@repo/test-exports/turbo.json, pnpm-lock.yaml
There are some issues in native ESM mode in Node when using `sanity` and other packages. 
In this PR I'm adding a testing suite that repros them, and guards against re-introducing them in the future once we've fixed the remaining issues.
=> chore: add `@repo/test-exports` suite

.github/workflows/testExports.yml, packages/@repo/test-exports/test/exports.cjs, packages/@repo/test-exports/test/exports.test.cjs, packages/@repo/test-exports/test/exports.test.mjs, packages/groq/.depcheckrc.json, packages/groq/package.json, packages/groq/test/groq.test.cjs, packages/groq/test/groq.test.mjs
It's not ideal to have a failing CI test until `@sanity/cli` and `@sanity/codegen` are refactored to support ESM native node envs, so this PR marks them as `todo` instead.
It also improves the CI test input by enabling both the default `spec` reporter, and not just `node-test-github-reporter`.
=> refactor(test-exports): mark tests that are expected to fail as `todo`

packages/@sanity/cli/test/__fixtures__/v3/package.json, packages/@sanity/cli/test/__fixtures__/v3/src/queries.ts, packages/@sanity/cli/test/typegen.test.ts, packages/@sanity/codegen/src/getBabelConfig.ts, packages/@sanity/codegen/src/readConfig.ts, packages/@sanity/codegen/src/typescript/findQueriesInPath.ts, packages/@sanity/codegen/src/typescript/findQueriesInSource.ts, packages/@sanity/codegen/src/typescript/registerBabel.ts
In v3.37.0, the output directory structure of the `@sanity/codegen` module changed as a result of a `pkg-utils` upgrade:
- From: `lib/_exports/`
- To: `lib/`
This broke some assumptions inside of the module which defined a relative path from the source file to the location of the babel configuration, which resulted in errors such as `Error: Cannot find module '<dir>/node_modules/@sanity/babel.config.json'`  
This PR recursively looks for the configuration file from the directory of the output and upwards until it finds it, which should make regressions due to other bundling changes more resilient.
While researching this bug, I had queries inside of a `.mjs` file that was not being picked up, so I have also snuck in a change that finds queries in both `.mjs` and `.cjs` files as well.
- …
=> fix(codegen): prevent crash due to incorrect babel config path

packages/@sanity/cli/src/actions/typegen/generateAction.ts, packages/@sanity/cli/test/__fixtures__/v3/working-typegen.json
If the `generates` path in the typegen configuration points to a path that does not exist, it will crash with a `ENOENT: no such file or directory, open '<some-path>/<generates-path>'` error.
This PR fixes this by running a recursive directory creation process before writing the output file.
- Changes makes sense, paths are correct
Added a CLI test to reproduce - the `out` directory does not exist in the fixture, and thus should fail before this change and pass after this change.
- Fixes an issue where `sanity typegen generate` would crash if the configured output path did not exist prior to running the command
=> fix(cli): ensure output path for types exist before writing

packages/sanity/src/structure/documentActions/PublishAction.tsx, packages/sanity/src/structure/i18n/resources.ts
Adds a new translation string for when the published time was "yesterday" to avoid "ago" suffix
The tooltip text for the publish button when the document is already published
Fixes tooltip text for publish button when document is already published
=> fix(structure): remove 'ago' suffix when published time was yesterday

dev/test-studio/package.json, pnpm-lock.yaml
`@sanity/assist` is now using `lodash-es` in the ESM bundle, allowing `pnpm dev` to work again
=> chore: fix `pnpm dev` by bumping `@sanity/assist`

dev/test-studio/sanity.config.ts, packages/sanity/src/core/store/_legacy/datastores.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/consistencyStatus.ts, packages/sanity/src/core/store/_legacy/document/document-pair/documentEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/editOperations.ts, packages/sanity/src/core/store/_legacy/document/document-pair/editState.ts, packages/sanity/src/core/store/_legacy/document/document-pair/memoizeKeyGen.ts, packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operationArgs.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operations/types.ts, packages/sanity/src/core/store/_legacy/document/document-pair/snapshotPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/validation.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts, packages/sanity/src/core/store/_legacy/document/document-store.ts
When the `serverActions` config flag was set, we noticed inconsistent behavior coming from the Portable Text Editor: strings were being duplicated, new lines were being inserted, and patches generally seemed to be repeated or inconsistent.
This behavior can be tracked down to `document-store` -- `documentEvents` were not being initialized with the `serverActionsEnabled` parameter. 
Interestingly, before this was tracked down, forcing both `serverActions: enabled` and `serverActions: disabled` to use the Actions API still resulted in this inconsistent behavior, and I suspect that the `patchChannel` used in FormView (and published to by `documentEvents`) was in some way misaligned about remote and local patches (possibly because of inconsistent memoization) so there are some fixes to ensure …
=> fix: resolve PTE inconsistency by passing serverActionsEnabled to documentEvents

packages/@repo/tsconfig/base.json
Unless your IDE, like VS Code, is set to use the monorepo version of TypeScript it might load the one it's bundled with. Which might not be 5.4 which is required to understand `module: "Preserve"`. This PR sets the other options `moduleResolution`, `esModuleInterop` and `resolveJsonModule` to what `module: "Preserve"` is using, to make sure everything still works
=> chore: support IDE's using older TypeScript versions on the monorepo

packages/sanity/src/core/form/inputs/PortableText/text/Decorator.tsx
This pull request addresses an issue where the caret was not visible on code-formatted text within the PTE when using the dark scheme.
- Verify that the caret is now visible on code-formatted text when using the dark scheme.
N/A
=> fix(core): hidden caret on code formatted text

packages/@sanity/cli/src/cli.ts, packages/@sanity/cli/src/types.ts
Merely renaming userProperty key from `platform` to `machine_platform` to be more descriptive
=> fix: update TelemetryUserProperties to use key machinePlatform instead of platform

packages/@repo/test-exports/test/exports.test.cjs, packages/@repo/test-exports/test/exports.test.mjs
Improves the test output of `pnpm test:exports` from:
```bash
@repo/test-exports:test: ▶ @sanity/schema
@repo/test-exports:test:   ✔ @sanity/schema (0.244875ms)
@repo/test-exports:test:   ✔ @sanity/schema/_internal (4.150458ms)
@repo/test-exports:test: ▶ @sanity/schema (4.640667ms)
@repo/test-exports:test: ▶ @sanity/types
@repo/test-exports:test:   ✔ @sanity/types (0.327041ms)
@repo/test-exports:test: ▶ @sanity/types (0.418833ms)
```
To easier distinguish the CJS tests from the ESM ones:
```bash
@repo/test-exports:test: ▶ @sanity/schema
@repo/test-exports:test:   ✔ require('@sanity/schema') (0.244875ms)
@repo/test-exports:test:   ✔ require('@sanity/schema/_internal') (4.150458ms)
@repo/test-exports:test: ▶ @sanity/schema (4.640667ms)
@repo/test-exports:test: ▶ @sanity/types …
```
=> chore: improve test output of `test:exports`

dev/starter-studio/package.json, pnpm-lock.yaml
Starter studio was missing `react-dom` package as a dependency causing the build to fail
Start studio build `cd dev/starter-studio && pnpm build`
=> chore: fix start-studio build

packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx
Setting a custom sort order function on a `documentList` will send over an incomplete key to /users/me/keyvalue, which will return a 400 error, because it is sending keys like `studio.structure-tool.sort-order`, which is not a valid format.
This PR uses the paneKey (which has its own regex restrictions) if a type is not available.
Are there any edge cases here that might be an issue?
e2e tests do exist for this functionality, but are currently a bit flaky and thus not available.
Resolves an issue where custom sort orders, or sort orders in lists that are not `documentTypeList`s, would send invalid requests to the persistent user settings backend.
=> fix: use pane key in list settings that do not have a type available

packages/sanity/src/core/components/collapseMenu/ObserveElement.tsx
After [updating](https://github.com/sanity-io/template-nextjs-personal-website/commit/bcc3a2c656a6d05e6a1ba526eb5635ad77d3c754) to the just-released Next.js 14.2 I noticed the tools in the navbar were gone:
[It appears to be related to the underlying pre-release of React v18.3.](https://github.com/radix-ui/primitives/issues/2769), which Next [is using](https://github.com/vercel/next.js/blob/6d96c3f468801fc2d8f648ccf468d689f930ce06/package.json#L201).
After working around it the menu appears again:
The fix is verified here: 
- [live deploy](https://template-nextjs-personal-website-git-test-canary-fix.sanity.build/studio/presentation/home/home)
- [git branch](https://github.com/sanity-io/template-nextjs-personal-website/tree/test-canary-fix)
The menu should work just as before, since the …
=> fix: regression hiding tool buttons when embedded on Next.js

packages/sanity/src/structure/comments/plugin/input/helpers.ts
While investigating EDX-906, I noticed an uncaught exception thrown if a PTE input was expanded and then the validation panel was shown or hidden. This error seems to benign and should not be surfaced.
Before:
https://github.com/sanity-io/sanity/assets/6889008/d99fde5f-e4a7-48f0-a430-cf40e2616af6
After:
https://github.com/sanity-io/sanity/assets/6889008/fa600c22-6c45-4ed0-8108-21edb716deca
I am not 100% this is the right fix. It definitely makes the problem not visible but I wonder if something is not being cleaned up properly when the validation panel is shown or hidden.
Manual UI testing
=> fix(pte): fix an issue where when PTE throws exception after resize

packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Fixes SDX-1156
Adds a message to warn users that migrations will trigger web hooks.
Is this the right message?
No behavioral change
=> fix(cli): add note about webhooks in migration run command

packages/@sanity/cli/src/actions/versions/findSanityModuleVersions.ts, packages/@sanity/cli/src/util/getLocalVersion.ts
Background: gradually removing `require()` calls across the codebase in order to be more ready for an "ESM-first" world
Replaces a few `require()` calls for `.json` files with `fs.readFile` + `JSON.parse`.
- CLI commands still work as expected
- Code refactorings look okay
None
=> refactor(cli): use fs methods for reading package.json files

packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
Fixes EDX-48
If you add an annotation but do not fill out any fields for it, we still mark the text as having the annotation. This change updates the logic so that if none of the fields are filled out, the annotation is removed.
Before:
https://github.com/sanity-io/sanity/assets/6889008/321f9367-88c5-4d23-a920-1e03831ce444
After:
https://github.com/sanity-io/sanity/assets/6889008/eabc930c-15f0-44ac-ae22-c43bbf597332
Is this the right approach?
Manual testing
=> fix(bug): update to not add annotation in PTE if all fields are null

packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx, packages/sanity/src/core/form/inputs/PortableText/Editor.tsx, packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/inputs/PortableText/hooks/usePortableTextMembers.tsx, packages/sanity/src/core/form/inputs/PortableText/hooks/useTrackFocusPath.tsx, packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx, packages/sanity/src/core/form/members/object/fields/ArrayOfObjectsField.tsx, packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
This will fix some issues with focus handling in form inputs and the document pane that are problematic with the presentation tool (and potential causing problems in other situations as well).
* Fixes an issue where the PT-input wasn't properly calling formBuilder onBlur, or called a synthetic onBlur through imperative handling. This caused some issues because the event targets would not be the same elements as the inputElement ref had (imperative handle).  The PT-Input is now using the editable element as the inputElement ref, so that the blur and focus functions are now the native ones with the correct targets. The imperative handle that previously was used for this is now removed.
*  DocumentPaneProvider will now automatically open the path up to the focusPath. So when something is …
=> fix(core/inputs): fix issues with focus handling

packages/sanity/src/core/form/inputs/PortableText/toolbar/BlockStyleSelect.tsx
This pull request ensures that the component defined for custom PTE styles is displayed in the style selector.
```tsx
import {type BlockStyleProps, defineField} from 'sanity'
function MyStyleComponent(props: BlockStyleProps) {
const {children} = props
return <div style={{color: 'magenta'}}>{children}</div>
}
const body = defineField({
type: 'array',
name: 'body',
of: [
{
type: 'block',
styles: [{title: 'My style', value: 'my-style', component: MyStyleComponent}],
},
],
})
```
Ensure that the component for the custom style is rendered correctly.
Fixes an issue where the component for custom PTE styles was not being rendered in the style selector.
=> feat(core): display custom styles in PTE style selector

.eslintrc.cjs, packages/@sanity/cli/templates/.eslintrc, packages/sanity/src/structure/__workshop__/ResolvePanesStory.tsx, packages/sanity/src/structure/comments/plugin/input/components/CommentsPortableTextInput.tsx, packages/sanity/src/structure/comments/src/components/list/CommentsListItem.tsx, packages/sanity/src/structure/comments/src/components/pte/comment-input/CommentInputProvider.tsx, packages/sanity/src/structure/comments/src/components/reactions/CommentReactionsBar.tsx, packages/sanity/src/structure/comments/src/context/selected-path/CommentsSelectedPathProvider.tsx, packages/sanity/src/structure/components/pane/__workshop__/SplitPanesStory/DocumentPane/DocumentPane.tsx, packages/sanity/src/structure/components/pane/__workshop__/SplitPanesStory/ListPane/ListPane.tsx, packages/sanity/src/structure/components/paneRouter/types.ts, packages/sanity/test/form/renderArrayOfObjectsInput.tsx, packages/sanity/test/form/renderBooleanInput.tsx, packages/sanity/test/form/renderCrossDatasetReferenceInput.tsx, packages/sanity/test/form/renderFileInput.tsx, packages/sanity/test/form/renderImageInput.tsx, packages/sanity/test/form/renderInput.tsx, packages/sanity/test/form/renderObjectInput.tsx, packages/sanity/test/form/renderStringInput.tsx
Disallows and removes usage of the React default export from the code base:
These will now give a lint error:
- `import React from 'react'`
- `import * as React from 'react'`
- `import type * as React from 'react'`
- Do you agree with this change? The main benefit of doing it is consistency, and that not using default imports may give some ESM/tree-shaking benefits down the line.
- I'm deliberately ignoring this rule in CLI templates as I find it hard to reason about what impact removing default imports may have there.
n/a - internal
=> chore: disallow and remove react default imports

package.json, packages/@sanity/migrate/.eslintignore
Currently, if you run `pnpm lint` locally it bails on the first error and does not catch all the errors. The change makes it so it continues on error and reports all the linting issues at once
Also fixes lint issue with `@sanity/migrate` 
linting still works
N/A
=> chore(lint): continue linting on error

.eslintrc.cjs, packages/sanity/.depcheckrc.json, packages/sanity/.eslintrc.cjs
Fixes an issue where the boundaries eslint plugin was not actually enforcing boundaries
Why?
> When we run lint in the monorepo, we use turbo, turbo runs lint script in each package.json and the eslintrc gets merged with the root to create a final config and the linting runs scoped to that working directory. The issue happens is at the root config we define the glob paths relative to the root and now the working directory of the package which causes the glob pattern to not match any of the paths and get ignored
What's Changed?
I have moved the boundary configuration to the `.eslintrc.cjs` in `packages/sanity` as the glob can be relative to that package and it reads much better than using relative glob at the root level 
If it's linting and change makes sense
N/A
=> chore(lint): fixes issue where boundaries lint rule was not working

packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.test.ts, packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts
After a global search request completes, the reducer will either merge or replace the existing results held in state:
1. If the search parameters have changed (e.g. query, filter, or order), that means a different search has been performed. The results are replaced.
2. If the search parameters haven't changed, that means a subsequent page of results has been fetched for the current search parameters. The results are merged.
This is handled by setting `result.hasLocal` to `true` (if the results should be merged) or `false` (if the results should be replaced).
There are currently some instances of scenario 1 that we don't account for. This branch ensures `result.hasLocal` is set to `false` when any action is dispatched that changes the search parameters. Without this change, there are some …
=> fix(core): reset global search results when `SEARCH_REQUEST_COMPLETE` occurs after any action causing search parameters to change

packages/sanity/src/core/search/common/types.ts, packages/sanity/src/core/search/text-search/createTextSearch.test.ts, packages/sanity/src/core/search/text-search/createTextSearch.ts
This branch enables Text Search API prefix searching for all Studio search surfaces. This is achieved by appending a wildcard token (`*`) to all search queries.
Search and document lists (which are powered by search) work correctly when Text Search API is enabled.
Added tests to `packages/sanity/src/core/search/text-search/createTextSearch.test.ts`.
Added prefix search behaviour to the new search implementation. This allows partial matches to be surfaced when a search occurs before the user finished entering their query.
=> feat(core): add prefix search support

packages/@sanity/vision/src/components/DownloadCsvButton.tsx, packages/@sanity/vision/src/components/VisionGui.tsx, packages/@sanity/vision/src/i18n/resources.ts, packages/@sanity/vision/src/util/getBlobUrl.ts
Builds on #6158
I suggest we use blob urls for the downloads instead of data urls, as it is somewhat safer in terms of encoding. Additionally, lets use `text/csv` which is the recognized mime type instead of `application/csv`.
There are a number of cases where the query result cannot be encoded to CSV. In these cases, I think we should explicitly call that out, instead of allowing the user to download a CSV file with only spaces/newlines.
=> fix(vision): use blob urls for downloads

packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
Previously it was necessary to restore the editor selection here, but it's no longer needed as our focus and blur handling has improved since then.
Should be removed to avoid confusion and noise.
That when selecting text (or just placing the cursor) inside an annotated text, for example a link, it should keep that exact selection after clicking the edit Annotation button, and closing the edit modal again. 
N/A
=> fix(form/inputs): Remove obsolete code for restoring selection

packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/patch.ts, test/e2e/tests/inputs/reference.spec.ts, test/e2e/tests/inputs/text.spec.ts
When using server actions, `createIfNotExists` should never be submitted to the actions API, as these are applied server side as part of the edit action (we still want them to be applied optimistically though).
When patching locally, and we don’t have either a published or a draft we need to submit a create mutation in order to ensure that the draft exist. This will fail if someone concurrently creates it, but that’s ok, and what we want.
- Does the logic make sense?
n/a - internal for now
=> fix(core): ignore locally applied createIfNotExists mutations when using server actions

packages/sanity/src/core/form/inputs/PortableText/Editor.styles.tsx, packages/sanity/src/core/form/inputs/PortableText/Editor.tsx
This pull request makes the PTE resizable in non-fullscreen mode.
- Make sure resizing the editor works
Make the Portable Text Editor resizable
=> feat(core): make PTE resizable

dev/test-studio/sanity.config.ts, packages/@sanity/types/src/reference/types.ts, packages/sanity/src/core/config/configPropertyReducers.ts, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/types.ts, packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts, packages/sanity/src/core/form/studio/inputs/crossDatasetReference/StudioCrossDatasetReferenceInput.tsx, packages/sanity/src/core/form/studio/inputs/reference/StudioReferenceInput.tsx, packages/sanity/src/core/search/common/types.ts, packages/sanity/src/core/search/search.ts, packages/sanity/src/core/studio/components/navbar/search/hooks/useSearch.ts, packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts, packages/sanity/src/structure/panes/documentList/useDocumentList.ts
This branch enables the Text Search API for all search surfaces by default. It can still be switched off by setting the `search.enableLegacySearch` configuration option to `true`.
- The Text Search API is used by default.
- The Text Search API can be switched off by setting the `search.enableLegacySearch` configuration option to `true`
Testing is already in place for the flagged search functionality.
Enabled new search for all Studios by default. Global search, document list search, and reference search are now faster; especially for workspaces with large schemas. Additionally, wildcard (`*`) and negation (`-`) tokens can now be used in search queries.
=> feat(core): enable Text Search API search strategy by default

packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/delete.ts, test/e2e/tests/document-actions/liveEdit.spec.ts
We received confirmation from the backend team that the upcoming Actions API is not going to be able documents that have the liveEdit parameter. Using the Actions API with a liveEdited document led to undesirable behaviors.
This PR adds a check to checkoutPair to see if mutations are targeting the "published" (whatever that may mean in the future) document. As far as I can see, the only situation in which that would happen is if we are in a liveEdit situation. If that's the case, then checkoutPair falls back to using the mutations endpoint.
Is my assumption correct? Or is it too naive to consider?
I've added a case for this in our unit tests, and an additional e2e test that goes through the full end-to-end experience of a liveEdited document. I'm not sure how to guarantee the `playlist` …
=> fix: refactor checkoutPair to allow mutations for liveEdit documents

packages/sanity/src/core/search/text-search/createTextSearch.test.ts, packages/sanity/src/core/search/text-search/createTextSearch.ts
Search requests fail if the query ends with a negation token (e.g. `monstera -deliciosa`). This is because the query is automatically transformed into `monstera -deliciosa*` to support prefix searching, but Text Search API doesn't currently support wildcards inside negations (and, even if it did, it's unlikely to be what the user intended).
This branch prevents this occurring by instead converting the final *non-negation* token to a wildcard prefix. e.g.  `monstera -deliciosa` is now transformed into `monstera* -deliciosa`.
It also ensures a wildcard token is never appended if the user has explicitly added one already (e.g. `monstera del*`).
Search works as expected. Especially that it is now possible to successfully search when the query ends in a negation token (e.g.  `monstera …
=> fix(core): prevent transformation of negation tokens into wildcard prefix tokens

packages/@sanity/migrate/src/fetch-utils/__test__/assert2xx.test.ts, packages/@sanity/migrate/src/fetch-utils/fetchStream.ts
Currently, when running a migration and the server responds with a non-2xx status, the error details from response body (e.g. in case of 4xx) is not properly forwarded to the error thrown by the migration command. This causes otherwise helpful details to be omitted from the error output.
Before:
```
npx sanity migration run some-migration
Running migration "some-migration" in dry mode
Project id:  some-project-id
Dataset:     doesnt-exist
Error
at assert2xx (<snip>/fetchStream.ts:21:17)
//…
```
After:
```
npx sanity migration run some-migration
Running migration "some-migration" in dry mode
Project id:  some-project-id
Dataset:     doesnt-exist
HTTPError: Dataset not found: Dataset "doesnt-exist" not found for project ID "some-project-id"
at assert2xx (<snip>/fetchStream.ts:21:17)
//…
``` …
=> fix(migrate): forward possible API error response to error thrown for non 2xx

dev/test-studio/package.json, dev/test-studio/sanity.config.ts, dev/test-studio/schema/index.ts, dev/test-studio/schema/plugins/hotspotArray.tsx, dev/test-studio/structure/constants.ts, pnpm-lock.yaml
The following PR adds the `sanity-plugin-hotspot-array` to our test studio just so we don't completely forget about it. I believe we own this plugin now and have to maintain it 😳
Does it work?
I added the plugin to the test studio structure.
N/A
=> test: add sanity-plugin-hotspot-array

dev/tsconfig.dev.json, examples/tsconfig.json, packages/@sanity/vision/tsconfig.json, packages/sanity/tsconfig.json, packages/sanity/tsconfig.settings.json
Problem: tsconfig using `/*` from exports was causing the `index.ts` getting imported twice causing IDEs to suggest incorrect `sanity/index` auto imports which is not correct as it would translate to `sanity/index.ts/index`. Although the wildcard imports are nice I think it's better to have more control here and avoid other issues in future. 
`build` and `dev` works correctly. 
N/A
N/A
=> fix: TS import paths importing index.ts twice incorrectly

packages/sanity/src/core/tasks/context/upsell/TasksUpsellProvider.tsx
Updates tasks upsell API version in which an object is returned from the data instead of an array.
=> fix(tasks): update tasks upsell provider client version

dev/test-studio/sanity.config.ts
This enables server actions for the dev/test studio
- The diff for this particular PR is miniscule as it only enables the server actions in the dev/test-studio in order for us to dogfood and catch potential errors.
- Unit tests has been included in prior work.
- I've done a bit of manual testing and haven't found any issues.
n/a - internal
=> chore: turn server actions on by default in test-studio

packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/RangeDecoration.spec.tsx
This will fix a bug where a range decoration for a single point (collapsed) range would be rendered three times.
This is because we can't do a Range include check on those collapsed ranges, we must equality check the points.
Added test for this.
That  collapsed range decorations aren't rendered multiple times.
Covered by automatic tests.
N/A
=> fix(portable-text-editor): support collapsed range decorations

packages/sanity/src/core/comments/context/enabled/CommentsEnabledProvider.tsx, packages/sanity/src/core/comments/hooks/useCommentsEnabled.ts, packages/sanity/src/core/comments/plugin/document-layout/CommentsDocumentLayout.tsx, packages/sanity/src/core/index.ts, packages/sanity/src/structure/panes/document/DocumentPane.tsx, packages/sanity/src/structure/panes/document/comments/CommentsWrapper.tsx, packages/sanity/src/structure/panes/document/comments/index.ts
This pull request ensures that the `CommentsProvider` only wraps the `DocumentPane` in `structureTool` if the comments feature is enabled.
- Ensure that the `CommentsProvider` is not rendered when the feature is not enabled.
N/A
=> fix(comments): conditional rendering of `CommentsProvider`

packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditorTester.tsx, packages/@sanity/portable-text-editor/src/editor/__tests__/RangeDecorations.test.tsx
This will skip unnecessary re-renders of range decorations when the previous values are the same (but the object might be different). 
Also added a test for this.
Will there be a situation where we did want to re-render even though the values are the same, but the object is different? I can't think of anything, but perhaps give this an extra thought.
Covered by automatic tests
N/A
=> perf(portable-text-editor): improve range deocration render perf

dev/test-studio/structure/resolveStructure.ts, packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx, packages/sanity/src/structure/panes/documentList/__tests__/helpers.test.ts, packages/sanity/src/structure/panes/documentList/helpers.ts, packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts, packages/sanity/src/structure/panes/documentList/useDocumentList.ts
There was a bug where the regex used to match static types that would eagerly match type filters that included more than one type. This would cause the document listener to not grab the search config for all the types in certain filter expressions.
For example, the search filter expression:
```
_type == 'testDocument'  || (_type == 'webhookDocument' && isActive != true
``` 
would only grab the search config for the `'testDocument` instead of both the `testDocument` and `webhookDocument`.
Does the structure tool still work? Can you provide any filter and it finds all the appropriate types?
I added a few unit tests and double checked the "Authors & Books"` custom pane.
Fixes a bug that caused types to be incorrectly parsed from filter statements.
=> fix(structure): resolve static types in document list filters

packages/@sanity/types/src/schema/define.ts, packages/@sanity/types/src/schema/types.ts
Supersedes #6426 by @GregorGabric. Include the original commit by @GregorGabric.
This pull request introduces a small but crucial change to the typing of the `defineType` function to improve the autocomplete experience in VSCode.
The original implementation used a type parameter that extended `string | IntrinsicTypeName`, which caused VSCode's autocomplete to not effectively prioritize or sometimes display the specific string literals defined under `IntrinsicTypeName`. This was due to the broad nature of the `string` type overwhelming the specific suggestions that `IntrinsicTypeName` could provide.
By introducing an intersection type `AllowOtherStrings = string & {}`, we differentiate the generic string type from our specific string type (`IntrinsicTypeName`). This subtle change …
=>  fix(core): fix autocomplete for `defineType` in VSCode

test/e2e/tests/desk/deprecatedFields.spec.ts
Fixes an e2e test that was improperly awaiting its assertions, sometimes causing the test to timeout.
That the `test/e2e/tests/desk/deprecatedFields.spec.ts` test runs correctly.
=> test(e2e): fix unawaited assertion

packages/@sanity/cli/src/actions/typegen/generateAction.ts
If `typeNodesGenerated` is `0` the ratio is `NaN`, it then gets serialized to null - which is not what we want
Would be nice to have some proper testing for telemetry labels and variants; but think that's out of scope for this issue  
No notes needed
=> fix(typegen): fixes a case where we track ratio as NaN

packages/sanity/src/core/config/flattenConfig.ts, packages/sanity/src/core/deprecatedPlugins/DeprecatedScheduledPublishing.tsx
🟡 Before merging, remove the import for scheduled-publishing plugin in the test studio 🟡 
Shows a warning to users if they are adding a deprecated plugin in their studio config.
=> feat(scheduled-publishing): add warning for deprecated plugin

packages/sanity/src/_internal/cli/util/mockBrowserEnvironment.ts
The mux video plugin uses `matchMedia`, which throws an error since matchMedia is missing:
```
» pnpm sanity schema extract                                                                                                                                                                                          1 ↵ 
✖ Failed to extract schema                                                                                                                                                                                                                                   
TypeError: Failed to load configuration file "/Users/sgulseth/workspace/src/sindre.dev/scratch/mux-mvp/sanity.config.ts": …
```
=> fix(cli): mock matchMedia window function

pnpm-lock.yaml, pnpm-workspace.yaml
Tiny one adding `perf/tests` to pnpm workspace, making it possible to run the perf tests again
- The diff
- It should now be possible to run the perf tests
n/a – internal
=> chore: add perf runner to workspace

packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts, packages/@sanity/codegen/src/typescript/expressionResolvers.ts
We we're checking the wrong variable for relative imports. importName is the variable being imported, but we want to check the actual path. The tests were also wrong...
Tests fixed
typegen: fixes a bug where relative imports would fail.
Fixes #6297
=> fix(typegen): fixes a bug where we imported the wrong relative path

.github/renovate.json, packages/@sanity/cli/package.json, packages/@sanity/codegen/package.json, packages/@sanity/migrate/package.json, packages/@sanity/schema/package.json, packages/sanity/package.json, pnpm-lock.yaml
Upgrades groq-js to latest, improves typegen support
Typegen: fixes various bugs when generating types
Typegen: implement support for `count`
=> chore: upgrade groq-js

packages/sanity/src/core/studio/Studio.test.tsx
Removes a test asserting SSR hydrateRoot finishes without warnings. This test started failing after upgrading to React 18.3 due to a deprecation warning when importing `act` react/test-utils.
Now that #6487 is merged we have a next build of the entire test studio which should cover a lot more SSR/hydration issues, so removing this test for now.
- Do we still need the other tests here?
n/a
n/a
=> fix(test): remove hydrateroot warning test

packages/@sanity/cli/src/util/journeyConfig.ts
Settings a max print width when formatting schema types that are fetched from the Journey API.
This makes it so each key is on its own line
Is there a better way of doing this in with Prettier?
No functionality change done, so everything should work as before
None
=> feat(cli): Set printWidth to 40 for Journey schema types

packages/@sanity/cli/src/actions/init-project/templates/moviedb.ts, packages/@sanity/cli/templates/moviedb/schemaTypes/screening.js
There's an issue I am struggling to find the cause of, where `npm create sanity@latest` will crash when trying to create the configuration file for the movie db template.
Reading the stack trace, it appears as part of the comments handling in recast, but I am struggling to easily reproduce it in testing. I modified the template to not include any comments, by simply removing the google maps input references. It was a bit of an oversight that it had stayed commented out since v3 was launched, and it looks a bit unprofessional in my opinion.
I also chose to hide the location field in the schema, since showing plain lat/lng fields seems... not very user friendly, but the data exists in the tarball that we provide, so I'd rather not show warnings on data for missing fields.
We can reintroduce …
=> fix(cli): remove comments from moviedb template, hide location field

packages/sanity/src/core/config/prepareConfig.ts
We've got some reports about a subpar search experience with the new API, as well as certain GROQ functions and features that may be used in custom document lists and reference search filters that do not work with the new API.
We need to have a proper look at addressing this, but for now we've decided to roll back to using the old search API for now. This PR ensures that we can still explicitly _enable_ the new search if we want, but by default it is disabled.
Studio uses old search API by default
- Disabled the new search API introduced in [v3.38.0](https://github.com/sanity-io/sanity/releases/tag/v3.38.0) by default
=> fix(search): revert to old search API for now

packages/sanity/src/core/form/inputs/PortableText/hooks/useTrackFocusPath.tsx
Kind of the same as this [pr](https://github.com/sanity-io/sanity/pull/6310) - when adding a link to the bottom of the PTE, it would scroll to the top and it wasn't possible to scroll down to the open popover. 
This PR sets the `block` to scroll to `nearest` instead of `start` to have the least amount of scroll movement. 
Fixes issues [5909](https://github.com/sanity-io/sanity/issues/5909) and [5586](https://github.com/sanity-io/sanity/issues/5586). 
Opening a link in a PTE where the paragraph is longer than the PTE block itself. 
Fixes issue where creating a link at the bottom of a PTE would scroll to the top.
=> fix(core): change scrollIntoView block to be nearest

packages/sanity/src/core/form/inputs/PortableText/hooks/useScrollSelectionIntoView.tsx
There was an issue with deleting characters in a pte where the length of the paragraph exceeded the size of the box - it would jump to the top of the pte. 
By setting the `block` in the `scrollIntoView()` to `nearest` instead of `start`, which means the browser will align `leafEl` with the least amount of vertical movement. 
https://github.com/sanity-io/sanity/assets/44635000/f2d786d1-9d31-4d9a-bafa-404e83706161
Fixes [5648](https://github.com/sanity-io/sanity/issues/5648)
Deleting characters will not cause the view to jump to the top. 
Fixes issue where the cursor would move out of viewpoint when deleting a character in PTE. 
Does changing this have any other implications in the studio?
=> fix(core): set scroll boundary to nearest

packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
In Presentation, users were having a somewhat misleading experience when clicking on a popover (which used an intent link) to load a document in the side pane. The document pane would show the latest revision, even if the users were looking at the "published" perspective.
This PR adds a parameter that can be read from an intent link (e.g., `https://example.sanity.studio/production/intent/edit/id=the-page-id;type=page;prefersLatestPublished=true`) which sets the revision of the latest published document on first load.
The document will then load in a readOnly state to that last published revision. Users can then switch revisions if needed.
You can test this out by running the studio locally and using an intent link like: [http://localhost:3333/test/intent/edit/id=grrm;type=author;prefersLat …
=> feat: add and use prefersLatestPublished parameter in DocumentPaneProvider

packages/sanity/src/core/studio/components/navbar/search/datastores/useStoredSearch.ts
A bit of logic was transplanted from the old localStorage recent searches store that did not translate well to an async request format. Certain users, who are not able to reach the `/users/me/keyvalue` endpoint for various reasons, would get stuck in a loop while they were trying to fetch recent searches:
1. They would open the search bar and request recent searches, which returned a null because they were not able to access it
2. The default logic would see that there was an empty search with an invalid version and set an empty object
3. Because they were not able to set the value, they would end up at step 1 of the process again.
This PR short-circuits that process by checking if there is data at all and returns a default value, rather than trying to set it immediately, as the old …
=> fix: prevent looping requests to keyvalue in recent searches

.eslintrc.cjs, packages/sanity/src/core/components/react-track-elements/createTrackerScope.tsx
Adds an eslint rule that complains about using `createContext` from react in `structure`, `core` or `router`
requires https://github.com/sanity-io/sanity/pull/6350
Linting passes
N/A
=> chore: add eslint rule for disabling createContext outside _singletons

packages/sanity/src/core/comments/plugin/input/components/CommentsPortableTextInput.tsx, packages/sanity/src/core/comments/plugin/input/helpers.ts
This pull request fixes an issue where the comment input fails to appear when clicking the "Add Comment" button to create an inline comment in Safari.
- Ensure that the comment input appears in Safari
N/A
=> fix(comments): inline comment creation issue in Safari

packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
This pull request resolves an issue where the popover for editing objects in the PTE closes immediately after opening. This issue was introduced with the implementation of presence cursors, where the `onPathFocus` function is called to reset the `selection` presence state when the PTE input is blurred. The fix here is to avoid resetting the presence selection on blur, and instead, allow the selection to be reset when another input is focused, thereby updating the presence.
- Ensure that editing objects in the PTE (such as links) is possible.
N/A
=> fix(core): skip reset presence selection on PTE blur

packages/sanity/src/core/deprecatedPlugins/DeprecatedScheduledPublishing.tsx
The deprecated `scheduledPublishing` toast in some cases shows multiple times, adding an id to it fixes it and ensures it will only show once.
=> fix(scheduled-publishing): deprecated error toast shows multiple times

packages/sanity/src/structure/i18n/resources.ts
Adds localisation string for toast message for a successful duplicate action. 
The toast message when duplicating a document 
Fixes toast message for document duplicate action
=> fix(structure): add string for successful duplicate action

packages/@sanity/block-tools/package.json, packages/@sanity/block-tools/src/HtmlDeserializer/helpers.ts, pnpm-lock.yaml
Follows up on the same change as in `@sanity/client`: https://github.com/sanity-io/client/pull/773
The new utility is faster, and should improve the perf when pasting large amounts of text.
If tests pass then it works.
It's sufficient to use existing tests.
N/A
=> fix: use `vercelStegaClean` util from `@vercel/stega`

packages/sanity/src/core/search/text-search/createTextSearch.ts, packages/sanity/src/core/studio/components/navbar/search/components/SortMenu.tsx, packages/sanity/src/core/studio/components/navbar/search/contexts/search/SearchProvider.tsx, packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.test.ts, packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts, packages/sanity/src/core/studio/components/navbar/search/definitions/getOrderings.ts, packages/sanity/src/core/studio/components/navbar/search/types.ts
**This branch relates only to global search.**
Ordering by relevance ("best match") when using the GROQ Query API search strategy causes the order `{direction: 'desc', field: '_updatedAt'}` to be applied. This is correct, because the results are subsequently ordered client-side.
**However, this is incorrect when using the Text Search API search strategy.** The Text Search API yields results ordered by relevance by default, and we do not apply any client-side ordering.
This branch eliminates the incorrectly applied `{direction: 'desc', field: '_updatedAt'}` ordering when the Text Search API search strategy is used.
- `order(_updatedAt desc)` is still present in the GROQ Query API request when ordering by relevance using the GROQ Query API search strategy.
- `{order: [{"attribute": …
=> fix(sanity): do not order by `_updatedAt` when relevance ordering is used with Text Search API search strategy

dev/test-studio/package.json, pnpm-lock.yaml
Test studio is crashing due to having  different @vercel/stega version , required due to this change https://github.com/sanity-io/sanity/pull/6544
=> chore(test-studio): bump vercel stega version

packages/sanity/src/_internal/cli/server/getViteConfig.ts, packages/sanity/src/core/components/DefaultDocument.tsx
This one is just a quick follow up for #6394.
I merged @binoy14's PR to unblock another item i'm working on and I later found out that there was an unconditional thing that should've been deactivated. #6514 is a better fix but this should go in now. Apologies for any noise.
N/A
=> fix: remove unconditional external from vite build

packages/@sanity/block-tools/src/HtmlDeserializer/helpers.ts
Version 1.0.2 of `@vercel/stega` removes the need to have a try/catch block around `vercelStegaClean`, so the `cleanStegaUnicode` utility is no longer needed.
The `@sanity/client` made the same change: https://github.com/sanity-io/client/pull/788
Pasting stega into PTE should be stripped without any exceptions thrown just like before.
Existing tests should be sufficient.
N/A, it's a refactor without any user facing changes
=> fix: remove `cleanStegaUnicode` helper

packages/@sanity/cli/src/actions/init-project/initProject.ts
Updates project metadata to indicate the project has been initialized locally
Backend errors should not interrupt project init flow under any circumstances
=> feat: add cliInitializedAt field to project metadata

packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.test.tsx, packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.tsx, packages/sanity/src/core/tasks/context/enabled/TasksEnabledProvider.test.tsx
The flag used to check the availability of scheduled publishing is incorrect, it should check `scheduledPublishing`, not `sanityTasks`
Fixes an issue in which users were incorrectly seeing the schedule publishing upsell ui.
=> fix(schedule-publishing): update flag used to check scheduledPublishing

packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/PresenceCursors.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/PresenceCursorsStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/utils/TestForm.tsx, packages/sanity/playwright-ct/tests/formBuilder/utils/TestWrapper.tsx, packages/sanity/src/core/form/inputs/PortableText/presence-cursors/UserPresenceCursor.tsx
=> fix(core): collapsed range decorations

.github/CODEOWNERS, packages/sanity/src/core/scheduledPublishing/tool/schedules/Schedules.tsx, packages/sanity/src/core/studio/upsell/UpsellPanel.tsx
Update schedule tool upsell layout to horizontal in desktop.
=> chore(scheduled-publishing): update schedule tool upsell layout

packages/sanity/src/core/tasks/plugin/TasksStudioActiveToolLayout.tsx
Updates tasks sidebar z index to sit on top of the rest of elements.
=> fix(tasks): update tasks panel z index

packages/@sanity/portable-text-editor/src/editor/Editable.tsx, packages/@sanity/portable-text-editor/src/editor/__tests__/handleClick.test.tsx, packages/@sanity/portable-text-editor/src/editor/__tests__/utils.ts, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withHotkeys.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithHotKeys.ts, packages/sanity/src/core/form/inputs/PortableText/Editor.styles.tsx
This changes improve the editor experience by adding empty text blocks into PTE when needed.
https://github.com/sanity-io/sanity/assets/46196328/623e28aa-f5e6-47b2-89e2-64142c1995bd
https://github.com/sanity-io/sanity/assets/46196328/0425bee3-4de8-4f7b-ab7f-e6e62c2fdb4a
https://github.com/sanity-io/sanity/assets/46196328/a241fdf4-50ee-49c1-81c9-354321dc848c
=> feat(pte): create new text blocks if needed

packages/sanity/src/structure/components/paneItem/PaneItem.tsx, test/e2e/tests/desk/documentList.spec.ts
Adds a test that only one listener is open when navigating document lists
I did write a test to assert that only one connection is kept open but it is not very ideal way but this is a limitation of playwright that it does not support connection close event for long polling request. Fortunately they get marked as failed requests when they get closed which helps us write some assertions around it.
- N/A
=> test(core): add test to ensures that only one listener is open when navigating list

packages/sanity/src/core/tasks/components/form/tasksFormBuilder/FormCreate.tsx
Fixes an issue in which tasks are kept in draft mode after clicking on the "create" button. 
The on change action triggered by the form doesn't provides a way to validate that the transaction ended, so in this case we will persist the form in `creating` state until the task store is updated with the correct values.
The task store fetches the latest task values when a task is updated, so if the value has been updated in the store it means the transaction has ended.
Is there a better way to do this? 
Is there any way to access the transaction from the form onChange or from any form action?
fixes an issue in tasks in which the UI showed that they were created but the transaction was didn't ended.
=> fix(tasks): close the form only after the task is created

packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/delete.ts, test/e2e/tests/document-actions/delete.spec.ts
The `delete` action in server side document actions requires a published document. In those cases when there is not a published document, we can't use this endpoint.
This PR adds logic for those cases by using the discard endpoint instead, and adds a few tests.
That the logic makes sense and this is how we want to proceed. We can always work with other teams to ensure we're doing something semantic that won't hinder us later.
This PR adds two tests for the delete action.
=> fix: use discard in delete action when document is not published

packages/@sanity/portable-text-editor/src/editor/components/SlateContainer.tsx, packages/@sanity/portable-text-editor/src/editor/hooks/useSyncValue.ts, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withPlaceholderBlock.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withPortableTextMarkModel.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithPlaceholderBlock.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithPortableTextMarkModel.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithUtils.ts, packages/@sanity/portable-text-editor/src/editor/plugins/index.ts, packages/@sanity/portable-text-editor/src/utils/applyPatch.ts
After clearing a PTE field with blocks, there is a very short period where attempting to input text after manually re-focusing will yield errors `(Cannot get the start point in the node at path [] because it has no start text node)` as well as rendering text incorrectly.
This is caused because the editor gets an "empty" state, which is later restored to the placeholder state with an empty text block.
Instead of waiting on the editor to restore itself after getting the empty state, avoid going to that state by inmediately adding an empty text block when removing the non text block if it's necessary.
It is necessary when this block is the only available. 
If we have another void or text block the editor won't be empty.
Is this change correct?
Manual testing of the changes.
Unit tests …
=> fix(pte): insert empty text block after removing void block 

packages/sanity/package.json, pnpm-lock.yaml
In `v3.41.0` we have a regression in `@sanity/presentation` causing it to crash when used in an embedded Studio: 
We fixed it in `@sanity/presentation` `v1.15.1` and it's sufficient to just bump the depedency to fix the issue.
It's already reviewed here: https://github.com/sanity-io/visual-editing/pull/1482
We've tested the fix on affected repos already by using `@sanity/presentation` and confirmed it works.
Fixes a regression in Presentation Tool introduced in `v3.41.0` that causes it to crash in embedded studios.
=> fix(presentation): regression causing a crash when in an embedded studio

packages/sanity/src/structure/structureBuilder/Component.ts, packages/sanity/src/structure/structureResolvers/__tests__/resolveIntent.test.ts
Some users would like to implement their own custom component within Structure, rather than just a desk list. However, this becomes difficult when trying to route to this component from other parts of the Studio, because there was no way for us to signal that this component could indeed handle that intent.
This PR takes the `canHandleIntent` argument available on lists and makes it available on components.
Is this a valid approach? Does it break inheritance of Structure Builder items in any way? Are there any gotchas?
This can be tried out in the test studio by adding a `canHandleIntent` to an `S.component`, like so:
```javascript
S.listItem()
.id('translate')
.title('Translate Test')
.child(S.component(TranslateExample).id('example')
.canHandleIntent((intent, params, context) =>  { …
```
=> feat: add canHandleIntent to Structure Builder component

packages/sanity/src/structure/panes/document/inspectDialog/InspectDialog.tsx
The inspect dialog is currently case sensitive, which seems somewhat unnecessary. 
Search is now case insensitive.
I'd argue this is non-critical functionality, and is tested in the upstream component (`react-json-inspector`). 
- Makes the search/filter in the document "Inspect" dialog case-insensitive
=> fix(structure): use case insensitive search for inspect dialog

test/e2e/tests/document-actions/delete.spec.ts
We [recently](https://github.com/sanity-io/sanity/pull/6595) introduced some improvement to prevent flaky tests on our publish action. Since our delete test also uses the publish button, let's use the same strategy to prevent flakiness.
I suppose the test is the test passing!
=> test(core): await publish action to prevent test flakiness

dev/test-studio/schema/index.ts, dev/test-studio/schema/standard/portableText/customBlockEditors.tsx, dev/test-studio/structure/constants.ts, packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx, packages/sanity/src/core/form/inputs/PortableText/Editor.tsx, packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/types/inputProps.ts
This PR introduces additional props to `<PortableTextInput>`:
- `hideToolbar` – whether the input's toolbar is hidden
- `fullscreen` – whether the input is initially full screen on mount
... that's it! Both of these are used by the various PTE inputs used in _Create_.
Existing PTE inputs in the studio should be unaffected. Fullscreen toggling should work as normal.
AFAIK there aren't any dedicated component tests for `<PortableTextInput>` – we only have some for `<FormBuilder>`. Please correct me if otherwise! Let me know if you need specific integration tests here.
I've also created an example document type in the test studio (`Standard Inputs > Portable Text > BlockEditor examples`) which demonstrates `hideToolbar` in action (I'd have included an example for `fullscreen`, but opening a …
=> feat(pte): add `hideToolbar` and `fullscreen` props to `PortableTextInput`

packages/sanity/src/core/form/inputs/PortableText/_common/ReviewChangesHighlightBlock.tsx, packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.styles.ts, packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.tsx
This PR makes some minor changes to text blocks and highlights.
**1. Disables `pointer-events` from the review changes highlight block**
Currently, it's possible to cause some render thrashing when hovering over the change indicator bar in fullscreen mode.
The highlight block doesn't contain any children, so it's safe for us to disable pointer events without having to fight z-index wars.
Before:
https://github.com/sanity-io/sanity/assets/209129/75ef6092-9736-464f-a68b-6fa336dd0183
After
https://github.com/sanity-io/sanity/assets/209129/39494504-a240-4c69-9233-fd5622fb8750
**2. Disables `pointer-events` from the validation highlight pseudo element**
_Really subtle_, but the presence of this would yield unwanted cursor changes when hovering over the periphery of text blocks.
Similar to the …
=> fix(pte): don't render the PTE block extras container when not in use, disable pointer events on highlights

packages/sanity/src/core/preview/utils/prepareForPreview.ts
While validating some preview behaviour, I noticed the `invokePrepare` func being called a second time in the same scope.
This is just a quick amend to use the assignment from the first call.
Ensure the system wasn't relying on it being called twice in succession
Tests and typesafety should remain the same
Prevent extra work on preview prepare
=> chore(core): prevent extra work on preview prepare

playwright.config.ts, test/e2e/helpers/envVars.ts
adds ability to run e2e tests headful by specifying `HEADLESS=false pnpm run test:e2e`. This is useful for debugging and provides insight into what the e2e tests actually do and can tell you what parts of the studio are actually covered, etc.
- Is this supported by other means/existing env vars already? :)
- Is it sensible to use an env var for this?
This is for the test runner
n/a internal
=> fix(e2e): support headless/headful env var toggle

packages/@sanity/schema/src/sanity/validation/types/block.ts, packages/@sanity/schema/test/validation/validation.test.ts, packages/@sanity/types/src/schema/definition/type/block.ts
This PR adds support for specifying a custom `icon` to block styles (similar to `lists` and `annotations`). 
Whilst not immediately useful to the Studio right now, this is helpful for _Create_ as it employs a block-level slash command palette which displays a list of available _text_ and _list_ styles (and other custom blocks / actions) available in the current schema.
Whilst we could hard-code icons for text styles, it felt more idiomatic to make these customisable at the schema level (which is already possible for lists and annotations). 
These could come into play for Studio users if a similar slash command palette is added here – or if we look to change the look of the block style dropdown to be a little more streamlined.
Adding an `icon` to a custom block style shouldn't throw …
=> feat(schema): add icon to BlockStyleDefinition

packages/@sanity/portable-text-editor/e2e-tests/__tests__/selectionAdjustment.collaborative.test.ts, packages/@sanity/portable-text-editor/src/editor/plugins/__tests__/withInsertBreak.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithInsertBreak.ts, packages/@sanity/portable-text-editor/src/editor/plugins/index.ts, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/PresenceCursors.spec.tsx, packages/sanity/src/core/form/inputs/PortableText/presence-cursors/UserPresenceCursor.tsx, packages/sanity/src/core/form/inputs/PortableText/presence-cursors/usePresenceCursorDecorations.tsx
Structure consistently crashes with` Cannot resolve a DOM point from Slate `point when editing a document with multiple users
I've been debugging this and it seems to be generated because the `PresenceCursor` element is not rendering the `Leaf` that is generated in the [editable component](https://github.com/sanity-io/sanity/blob/5bc6f0390e914ed5e38729cff11a9919db13796d/packages/%40sanity/portable-text-editor/src/editor/Editable.tsx#L199-L200), which causes that the editable leaf "dissapears" and crashes the editor.
This were the original steps to reproduce the issue:
Steps to reproduce
- **User 1**: Create a new document with a PTE field
- **User 2**: visit the same URL
- **User 1**: focus the PTE field
- **User 2**: focus the PTE field
- **User 1**: enter a line break
- User 2's screen …
=> fix(pte): cursor presence causes pte error

packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx, packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.tsx
This tiny PR adds data attributes to PTE text + object blocks, as well as their children which have styles applied in JS (via `innerPaddingProps`)
These have been added in order for _Create_ to be able to safely target and override styles applied on these elements without resorting to sketchy CSS selectors.
There's definitely a greater question of how we could look to render `<PortableTextInput>` in a style-agnostic fashion in future. For now, this is very much a short term solve.
Nothing – this doesn't impact the studio...
.. but does lead to some interesting questions!
- **When it comes to exposing arbitrary (non-test) data-attributes, is there a convention we should use to denote certain attributes as protected and in use externally?** 
- E.g. I could easily see a future where someone …
=> feat(pte): expose data-attributes on PTE Text + Object blocks

.github/renovate.json
This PR tweaks our Renovatebot preset to better align with changes to this repository settings since its introduction:
- Pull requests require code reviews from codeowners before merging.
- Pull requests require at least 1 code review from someone with write access before merging.
- GitHub Merge queues are enabled.
- If a rebase or a merge commit is pushed to a PR then existing PR review approvals are automatically dismissed and require re-approval to merge.
With those rules in mind these are the changes to our Renovate config:
- The `"rebaseWhen": "behind-base-branch"` rule is removed since it causes Renovatebot to always rebase a PR everytime someone pushes a commit to `next`. Removing this rule allows you to queue up Renovate PRs and batch them. It also greatly reduces the amount of …
=> chore(ci): tweak renovate preset to better align with branch rulesets

.github/renovate.json
Follow up on #6648, the grouping didn't actually work as the `ignorePresets` directive takes presedence: https://github.com/sanity-io/sanity/blob/11dcb1ad9be866db21840b9868d6c23e934ac862/.github/renovate.json#L8
=> refactor(renovate): group non major dev deps

packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts
Fixes issue with history just hanging indefinitely 
Changes makes sense, using suggested code from Rob
This one is very hard to test, since you need to be able to have a way to create a massive history on a document. This is something for us to look at making it easier
Fixes an issue where history menu would sometimes keep loading indefinitely
=> fix(core): fixes issue with history loading indefinitely

packages/@sanity/cli/src/actions/typegen/generateAction.ts, packages/@sanity/cli/src/workers/typegenGenerate.ts, packages/@sanity/cli/test/__snapshots__/typegen.test.ts.snap, packages/@sanity/codegen/src/typescript/typeGenerator.ts
Prettier were adding a newline, and then we were adding an additional new line to each type. This moves new line into the maybeFormatCode to either rely on prettier adding it, or adding it manually if prettier is not found.
We have test that checks a snapshot, these are updated
fixes a bug where typegen would add an additional new line between types.
=> fix(typegen): move type new line separator into formatter

packages/sanity/src/_internal/cli/actions/schema/extractAction.ts
Adds a new line to generated schema json file, this is expected by most formatters
We don't have any test for this specific part of the code as all it does is json.stringify the extracted schema. The extracted schema part is well tested already.
schema extraction: add a trailing new line to the generated schema.json file
=> chore: add a newline to the extracted schema.json

packages/sanity/src/core/config/__tests__/resolveConfig.test.ts, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/resolveDefaultPlugins.ts
Before the implementation of scheduled publishing as a default feature, when visiting the studio with no plugins added users were seeing the following screen:
Once scheduled publishing was implemented, users no longer see that screen and instead are seeing the schedule publishing tool.
This PR fixes that, and only includes into the plugins array the scheduled publishing tool if other plugins have been added to the source.
=> fix(scheduled-publishing): don't include it if it's the only plugin available

packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operations/helpers.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/discardChanges.ts, packages/sanity/src/structure/panes/document/statusBar/dialogs/ConfirmDialog.tsx, test/e2e/tests/document-actions/discardChanges.spec.ts
This branch adopts the Actions API for discarding changes.
Does everything work as expected when discarding changes?
E2E tests for the discard changes document action added in `test/e2e/tests/document-actions/discardChanges.spec.ts`.
=> feat(sanity): use actions API when discarding drafts

dev/test-studio/sanity.config.ts, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/types.ts, packages/sanity/src/core/store/_legacy/datastores.ts, packages/sanity/src/core/store/_legacy/grants/documentPairPermissions.ts, packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts
While reviewing #6418 I realized that we probably want a way to enable server actions (e.g. to test intenrally) even in the case it's turned off for most users.
I think it also makes sense to make it very clear that it's internal, and not meant for studio developers.
- Might need to update some tests - opening as draft PR for now to gauge.
n/a – not public facing
=> fix(sanity): make config flag override server document actions

dev/studio-e2e-testing/sanity.config.ts, dev/test-studio/sanity.config.ts, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/types.ts, packages/sanity/src/core/store/_legacy/datastores.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/consistencyStatus.ts, packages/sanity/src/core/store/_legacy/document/document-pair/documentEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/editOperations.ts, packages/sanity/src/core/store/_legacy/document/document-pair/editState.ts, packages/sanity/src/core/store/_legacy/document/document-pair/memoizeKeyGen.ts, packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operationArgs.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/remoteSnapshots.ts, packages/sanity/src/core/store/_legacy/document/document-pair/snapshotPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/utils/featureToggleRequest.ts, packages/sanity/src/core/store/_legacy/document/document-pair/utils/fetchFeatureToggle.ts, packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts, packages/sanity/src/core/store/_legacy/document/document-store.ts, packages/sanity/src/core/store/_legacy/grants/documentPairPermissions.ts, packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts, test/e2e/tests/document-actions/fetchFeatureToggle.spec.ts
As we move toward transitioning to server-side document actions, we'd like to have some ability to have a remote way to configure whether or not our end users' document actions should be utilizing the Actions API endpoint, in case there's some risk or problem in content creation.
This PR introduces a remote check used in those places that code paths might diverge based on whether or not to use server actions. This way, we can shut off server actions and revert to old and tested functionality if needed.
This is done through the following:
1. Continuing to use the `sanity.config.ts` flag. If it is set to false, then the old mutations endpoint should be used, no matter what.
2. Introducing a HTTP request that is fed into `document-store`. This HTTP request lasts, at most, two minutes (thanks …
=> feat: fetch feature toggle to enable serverside document actions

dev/test-studio/schema/standard/portableText/customBlockEditors.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Input.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/InputStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Toolbar.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ToolbarStory.tsx, packages/sanity/playwright-ct/tests/utils/testHelpers.tsx, packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx, packages/sanity/src/core/form/types/inputProps.ts
This PR adds `initialActive` to `<PortableTextInput>`. 
This simply allows PTE inputs to be mounted without the need to manually 'activate' them by focusing beforehand.
This is used by _Create_ as all PTE inputs there are always active by default.
Like other recent PTE changes brought in from _Create_, existing PTE inputs in the studio are unaffected. PTE inputs in the studio should still require activation by manually focusing / clicking them.
- An additional example has been added to `BlcokEditor examples` in test-studio
- A playwright component test has been added (some others covering `hideToolbar` and `initialFullscreen` have also been added)
N/A
=> feat(pte): add `initialActive` prop to `PortableTextInput`

packages/sanity/src/core/scheduledPublishing/hooks/usePollSchedules.ts
This PR updates how the `usePollSchedules` hook works.
If the client is in `upsell` mode we have no need to poll the `schedules` data, given it won't change for them. We do have the need to query it when the document loads as we need to show the upsell UI at document level if that document has a schedule.
This is done by changing the options passed to the `useSwr` hook.
https://swr.vercel.app/docs/revalidation#disable-automatic-revalidations
```ts
{
refreshInterval: undefined,
revalidateOnFocus: false,
revalidateIfStale: false,
revalidateOnReconnect: false
}
```
=> fix(schedule-publishing): avoid polling in upsell mode

packages/sanity/src/core/store/_legacy/grants/templatePermissions.ts, packages/sanity/src/core/templates/__tests__/resolve.test.ts, packages/sanity/src/core/templates/resolve.ts
Wherever Studio allows users to create new documents, it runs `getTemplatePermissions`, which subsequently resolves the initial value of every schema type. It's troublesome for schema types that use an `initialValue` function (especially async function that may call an HTTP API), because it causes that function to be called at multiple unexpected times.
- When rendering a document list containing a type with an `initialValue` function, a `PaneHeaderCreateButton` is rendered.
- When the Studio navbar renders.
- When rendering the document pane for any type of document, `ReferenceInputOptionsProvider` is rendered.
We cannot simply remove initial value resolution. Studio must resolve initial values before allowing the user to create a new document in case those values would preclude the user …
=> feat(sanity): memoize initial value resolver

packages/sanity/src/structure/panes/document/comments/CommentsWrapper.tsx
When running `sanity build` this annoying warning happens:
```bash
✔ Clean output folder (3ms)
Export "P" of module "node_modules/sanity/lib/_chunks-es/StructureToolProvider.mjs" was reexported through module "node_modules/sanity/lib/structure.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/@sanity/presentation/dist/_chunks-es/PresentationTool.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "S" of module …
```
=> fix: remove circular reference to `usePaneRouter`

packages/sanity/src/structure/panes/documentList/ColumnsControl.tsx, packages/sanity/src/structure/panes/documentList/DocumentSheetListPane.tsx, packages/sanity/src/structure/panes/documentList/__tests__/ColumnsControl.test.tsx, packages/sanity/src/structure/panes/documentList/useDocumentSheetColumns.tsx
Suggestion to use columns initial state rather than setting them later in a useEffect.
=> fix(structure): remove useEffect and set table columns as initial state

packages/sanity/package.json, pnpm-lock.yaml
`@sanity/ui` `Popover` animations don't run properly when the Studio is embedded in a Next.js canary app. This change downgrades `framer-motion` to the latest version we shipped `@sanity/ui` with and that we know works. We can upgrade again later once the underlying problem has been fixed.
- `@sanity/ui` has already been pinned here: https://github.com/sanity-io/ui/pull/1302 and
- `renovate-config` has been pinned here: https://github.com/sanity-io/renovate-config/pull/197
This is already enough to fix https://github.com/sanity-io/sanity/issues/6688, but @stipsan and I thought it would be good to pin the dependency everywhere.
=> fix: pin framer-motion to an earlier version

packages/sanity/src/core/tasks/plugin/TasksStudioActiveToolLayout.tsx
**Modals** have a z-index of 600.
**Popover** have a z-index of 400.
**Tooltips** have a z-index of 200
Reducing tasks sidebar to **100**, the same as the navbar to stay below modals, popovers and tooltips, it will still sit on top of the elements that were discovered as breaking on the previous fix when this was moved to 1000.
=> fix(tasks): reduce tasks sidebar zoffset

packages/sanity/src/core/tasks/plugin/TasksFooterOpenTasks.test.tsx, packages/sanity/src/core/tasks/plugin/TasksFooterOpenTasks.tsx
The footer button was shown due to this condition being true in some documents which this value is undefined, until the active document value was correctly set.
`item.target?.document._ref === activeDocument?.documentId`  -> `undefined === undefined` 
By checking if the activeDocument is present before validating the values this issue is fixed.
The removal of the `enabled` check is intentional given the whole plugin won't be added if the plugin is not enabled, so this check is unnecessary. See [resolveDefaultPlugins](https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/core/config/resolveDefaultPlugins.ts)
Added some tests.
=> fix(tasks): hide footer button until the active document is set

packages/sanity/src/structure/panes/documentList/__tests__/useDocumentSheetColumns.test.ts, packages/sanity/src/structure/panes/documentList/useDocumentSheetColumns.tsx
Fixes an issue introduced in EDX-1308 (https://github.com/sanity-io/sanity/pull/6661) where tanstack col visibility expects field separator as `_` but incorrectly `.` was being used for our definitions
Defining an id for all cols which is used in flatColumns.
Selected column now a display column
Updated test case
Not relevant - this feature is not yet user facing
=> fix(structure): fixing incorrect way of setting col visibility

packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts, packages/@sanity/codegen/src/typescript/findQueriesInSource.ts
Added functionality in `findQueriesInSource.ts` to ignore queries which are prefixed with the comment `@sanity-typegen-ignore`.
In some cases you want to extract a single use query to its own value:
```ts
const query = `
*[_type == "post"]
`
const posts = await client.fetch(query)
```
Now if you validate the posts with zod you will have to explicitly write the result anyway
If there are any other cases than the ones specified in the function `getDeclarationLeadingComment`, please let me know and I will add them
Added tests for const declarations, export const and making sure it chooses the correct comment if there are multiple leading comments
=> Add support for @sanity-typegen-ignore to ignore queries

packages/@sanity/cli/test/shared/globalSetup.ts
We were only symlinking in local packages in the studio tests, however if the changes is only in the cli package we also need the changes locally in the installed CLI
Can this break in any, unforeseen, way? :p 
Fixes the tests in https://github.com/sanity-io/sanity/pull/6702
=> chore(cli): symlink in local packages for the installed sanity cli

packages/sanity/src/core/i18n/bundles/studio.ts
Tiny one, removes an extraneous curly brace when confirming image deletion: 
- the diff :)
- should be fine to not have a separate test for this one
- removes an extraneous curly brace from delete asset confirmation dialog
=> fix(i18n): remove extraneous curly brace

packages/@sanity/cli/src/actions/typegen/generateAction.ts, packages/@sanity/codegen/src/readConfig.ts
We've gotten reports that formatting breaks between macos and windows, this adds a way to opt-out of the formatting
Configuration flag looks sensible?
we test generating both formatted and unformatted code already.
=> feat(typegen): add optout for prettier formatting

packages/sanity/src/core/form/inputs/files/ImageInput/ImageActionsMenu.tsx, packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx, packages/sanity/src/core/form/studio/inputs/client-adapters/assets.ts
We have a racing condition in the `BaseImageInput` component, in some cases, specially with big images the fetch request to resolve the reference is happening before the reference exists. Making the image input to persist in a "loading" state which nothing indicates it. 
Also, there was no retry option when the reference was not properly resolved.
With this changes, a retry option is added to the  `observeAssetDoc` function, fixing this problem.
Also, a loading state was included in the image input.
How to reproduce this issue:
- Go to https://test-studio-git-next.sanity.build/test/structure/
- Open any document with an image input.
- Add a large image which is not in the client assets, see if it stales, if not, remove the image and try with another one.
- Retry previous step until you …
=> fix(core): add retry to image observer and loading state

packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/__snapshots__/publish.test.ts.snap, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/publish.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/publish.ts
This branch adds optimistic locking when publishing documents via the Actions API by adopting its `ifDraftRevisionId` and `ifPublishedRevisionId` guards. These guards are a recent addition to the Actions API.
Optimistic locking ensures the editor can see the latest state of both the draft document they are publishing, and the published document they are choosing to replace.
Additionally, this branch adds a check prior to publishing that ensures Studio has a draft snapshot. This check is already in place when publishing via the Mutations API. It stands to reason that the editor must be able to see the draft they are choosing to publish.
Is the usage of the `ifDraftRevisionId` and `ifPublishedRevisionId` guards correct?
- I've copied the existing unit tests from the Mutations API based …
=> feat(sanity): use optimistic locking when publishing documents

packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/DisableFocusAndUnset.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/DisableFocusAndUnsetStory.tsx, packages/sanity/src/core/form/inputs/PortableText/hooks/usePortableTextMembers.tsx
<strike>NOTE: this PR builds on top of https://github.com/sanity-io/sanity/pull/6705 and this should be merged first.</strike>
This will prohibit that a input for a object modal inside the PT-input can call `onPathFocus` or `unset()` on itself.
Calling `onPathFocus([])` will focus the editor element and close the editing modal.
Also if the input calls `unset()` on itself (like the Reference Input) it will cause the modal to abruptly dissapear, and we might miss out on any cleanup and other expected functions in the editor when this happens.
This change will make sure that any input for the PT-content inside the editor will not be allowed to do this.
`onPathFocus([])` will be a no-op, and `unset([])` will instead reset the object (keeping `_key` and `_type`) allowing the editor to deal …
=> fix(core/form): prohibit focus and unset on root input

.eslintrc.cjs, .github/workflows/are-we-compiled-yet.yml, dev/test-next-studio/next.config.mjs, dev/test-next-studio/package.json, dev/test-studio/package.json, package.json, packages/@repo/shared-modules.bundle/package.json, packages/@sanity/cli/package.json, packages/@sanity/portable-text-editor/src/editor/hooks/useSyncValue.ts, packages/sanity/package.json, pnpm-lock.yaml
Adds support for the [React Compiler](https://es.react.dev/learn/react-compiler) in the `test-next-studio`. Also adds the `eslint-plugin-react-compiler` plugin, which warns us about areas in the codebase that the compiler will skip due to either breaking the rule of hooks, or the code being structured in a way where deps can't be inferred.
Components that are memoized by the Compiler gets their own little sparkly badge in the React Devtools extension:
Why add the Compiler? Even though we can't fully reap the benefits of it until we're ready to drop react v18 and make v19 the new baseline, it's useful to be able to track how much perf is improved by the Compiler.
It's also usually a good thing for react v18 perf to refactor the codebase to fix hooks bugs, and to make the code structured so …
=> chore: setup react compiler test and linting

packages/sanity/src/core/form/inputs/PortableText/Editor.styles.tsx, packages/sanity/src/core/form/inputs/PortableText/Editor.tsx, packages/sanity/src/core/form/inputs/PortableText/_common/ReviewChangesHighlightBlock.tsx, packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.styles.ts, packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx, packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.styles.ts, packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.tsx, packages/sanity/src/core/studio/Studio.test.tsx
This PR sets `max-width` on PTE blocks, rather than the editable container.
This enables block margins to be clickable and improve ergonomics of focusing and selecting text, especially in fullscreen mode.
This is useful for _Create_ as there effectively all PTE inputs are in fullscreen by default and this was especially noticeable, as often these margins occupy much of the screen!
This change especially improves text selection in this context, as you can now start selections directly in the margins – fairly standard behaviour across various editors.
Before:
https://github.com/sanity-io/sanity/assets/209129/5ccac024-add5-446d-9ce6-032126113ea8
After:
https://github.com/sanity-io/sanity/assets/209129/e14d0e73-3235-482d-8ab9-5478e7e42ab3
**Other minor changes:**
1. Remove padding in …
=> fix(pte): improve text selection in fullscreen inputs

package.json, packages/sanity/src/core/comments/components/reactions/CommentReactionsMenuButton.tsx, packages/sanity/src/core/comments/plugin/inspector/CommentsInspector.tsx, packages/sanity/src/core/form/inputs/PortableText/Compositor.tsx, packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx
Fixes some issues that were flagged by the compiler that are simple to clear up.
Everything works the same
Existing tests should be enough to cover possible regressions. And the perf impact can be tested by trying the `test-next-studio` Vercel deploy on the PR
N/A
=> fix: handle React Compiler errors

packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operations/helpers.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/restore.ts, packages/sanity/src/core/store/_legacy/history/createHistoryStore.ts, packages/sanity/src/structure/panes/document/timeline/timelineItem.tsx, packages/sanity/src/structure/panes/document/timeline/timelineMenu.tsx, test/e2e/tests/document-actions/restore.spec.ts
This branch adopts the Actions API for restoring revisions. This was made possible by the introduction of the `sanity.action.document.replaceDraft` action.
Does everything look correct when restoring a previous revision of a document?
Added an E2E test for revision restoration in `test/e2e/tests/document-actions/restore.spec.ts`.
=> feat(sanity): use Actions API when restoring drafts

dev/test-studio/sanity.config.ts, packages/sanity/src/core/store/_legacy/document/document-pair/actionTypes.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
When using server actions, we forwarded the patch mutations as-is, but that means they would also include the document id. The doucment ID is alredy provided as part of the actions payload, and should not be part of the action's patch here.
The diff :)
This was already covered by a test that I've updated.
N/A
=> fix(core): remove id from patch when using server actions

dev/test-studio/documentActions/actions/TestCustomRestoreAction.tsx, dev/test-studio/documentActions/index.ts, dev/test-studio/schema/debug/removeRestoreAction.ts, dev/test-studio/schema/index.ts, dev/test-studio/structure/constants.ts, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx, packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx, test/e2e/tests/document-actions/restore.spec.ts
The Studio document actions configuration is not currently respected when rendering the "Restore" document action.
``` ts
actions.filter((action) => action.action !== 'restore')
```
In order to replace the restore action, developers **must** set the `action` property to `"restore"` on their `DocumentActionComponent`.
```diff
import {RocketIcon} from '@sanity/icons'
import {type DocumentActionComponent} from 'sanity'
export const TestCustomRestoreAction: (
action: DocumentActionComponent,
) => DocumentActionComponent = (restoreAction) => {
const action: DocumentActionComponent = (props) => ({
...restoreAction(props),
label: 'Custom restore',
tone: 'positive',
icon: RocketIcon,
})
+ action.action = 'restore'
return action
}
```
This is because the restore action is specially handled by …
=> fix(sanity): respect Studio configuration when rendering "restore" document action

scripts/uploadBundles.ts
Update the cache header on the manifest to be 10s and JS files to 1 year immutable
FIXES SDX-1343
N/A
N/A (internal)
=> chore(ci): set a shorter cache on manifest

packages/@sanity/portable-text-editor/src/editor/__tests__/pteWarningsSelfSolving.test.tsx
Added a test for the condition where the prop value is an empty array, which should be tolerated.
N/A
=> test(portable-text-editor): add test for empty array value

dev/page-building-studio/turbo.json
When deploying on Vercel, this studio fails with `Error: No Output Directory named "dist" found after the Build completed.` whenever there is a cache hit. Hopefully, specifying the `outputs` of the `build` pipeline makes sure that `dist` can in fact be found in these instances.
=> chore(page-building): configure build outputs

dev/test-studio/schema/standard/crossDatasetReference.ts, packages/sanity/src/core/search/common/__tests__/deriveSearchWeightsFromType.test.ts, packages/sanity/src/core/search/common/deriveSearchWeightsFromType.ts
This fixes a regression introduced by #5948 which caused nested preview fields defined on cross dataset references to be included by their preview key instead of their actual path.
E.g. the following cross dataset reference eould produce a query that looked for keyword matches in `title`, which would yield no results, and should instead be `translations.no`.
```
{
title: 'Example',
name: 'exampleCrossDatasetReference',
type: 'crossDatasetReference',
dataset: 'other-dataset',
to: [
{
type: 'book',
preview: {
select: {
title: 'translations.no',
},
},
},
],
},
```
This PR includes:
- 👀 an added repro case to our dev/test studio (d7dd3bc64c319d8bfb00b747ba96cdb730ce3921)
- 🔴 a (failing) unit test covering the particular case (997a020a811efdfe86fa8a761212d1b33da1a4a9)
- 🟢 the fix …
=> fix(core): fix issue with nested preview fields not being included in legacy text search

packages/sanity/package.json, packages/sanity/src/core/store/_legacy/presence/message-transports/bifurTransport.ts, pnpm-lock.yaml
The new bifur client introduced a breaking change, where subscription based methods have to be called on the `listen()` method instead of on the `request()` method. This makes it more obvious that they're going to provide values over time and not a one-off response. Additionally, it allows reusing the same base method name for both subscriptions and one-off requests, eg `authorize` vs `authorize_subscribe`.
Presence still work as before.
Only a dependency upgrade, so should not be necessary.
None
=> chore(deps): update dependency @sanity/bifur-client to ^0.4.0

packages/sanity/src/core/form/types/definitionExtensions.test.ts, packages/sanity/src/core/form/types/definitionExtensions.ts, packages/sanity/src/core/form/types/index.ts
This PR addresses a type error caused by the missing 'preview' property in 'DocumentComponents'. The error, "Object literal may only specify known properties, and 'preview' does not exist in type 'DocumentComponents'", was resolved by inlining the type definitions within the module augmentation. This ensures TypeScript recognizes the 'preview' property as part of 'DocumentComponents' and avoids naming collisions that were causing the build process to prefer the incorrect type.
Note that this should not change the public API of the package at all due to the re-export but I may be missing something. An alternative would be to rename the `DocumentComponents` interface to something that doesn't collide.
Closes #6542
The fix involves:
- Moving the component type definitions from …
=> fix: resolve type error by inlining DocumentComponents definition

packages/sanity/src/core/comments/components/reactions/CommentReactionsMenuButton.tsx
This pull request fixes an issue where the comment reactions popover menus would open when clicking outside of them.
- Ensure that the comment reactions menus are correctly opened and closed.
N/A
=> fix(core): reactions menu open issue

packages/sanity/src/core/form/store/utils/__tests__/immutableReconcile.test.ts, packages/sanity/src/core/form/store/utils/immutableReconcile.ts
This PR adds the fix and unit test proposed in #6646 with a few minor modifications, mostly in order to align it with established coding conventions. See #6646 for an in-depth explanation of the issue.
A unit test asserting the correct behavior is included.
Fixes an issue that could under certain conditions cause a circular structure to enter an infinite loop. Shoutout to  @sarahsvedenborg and @stian-svedenborg for identifying the issue and proposing a fix.
=> fix(form): fix issue making circular structures sometimes causing infinite loop

packages/@sanity/portable-text-editor/src/editor/__tests__/PortableTextEditor.test.tsx, packages/@sanity/portable-text-editor/src/editor/__tests__/pteWarningsSelfSolving.test.tsx, packages/@sanity/portable-text-editor/src/editor/plugins/createWithEditableAPI.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithInsertData.ts, packages/@sanity/portable-text-editor/src/editor/plugins/createWithPortableTextMarkModel.ts, packages/@sanity/portable-text-editor/src/utils/validateValue.ts
This will add two auto-resolving validations:
* Test a block for orphaned markDefs and remove obsolete ones (previously only done through editor normalization).
* Test a block for orphaned marks and remove obsolete ones (previously a hard validation error).
By introducing these new validations, I found two issues. The first was there before, and the other one occured introducing  the new normalization rules of markDefs. 
* Fix issue where deleting block 3, 2 and partially 1 where block 1 contains an remaining annotation (too many validation iterations error).
* Fix issue where copying an text fragment containing an annotation would not be valid with the new validation code.
Should be covered by unit tests.
Improve the validation of content in the Portable Text Editor.
=> fix(portable-text-editor): add autoresolving validations and fix normalization issues

packages/sanity/src/_internal/cli/actions/build/buildAction.ts, packages/sanity/src/_internal/cli/util/checkRequiredDependencies.ts
This PR adds the minimum version to the import map grabbed from the installed sanity version.
Try the build action out, try the deploy action out with auto updates.
Tested it in by building the test-studio with --enable-auto-updates (flag needs to be renamed but will come in another PR)
N/A
=> feat: create import map w/ installed sanity version

packages/sanity/src/core/store/_legacy/document/document-pair/utils/fetchFeatureToggle.ts
This adds caching to the actions feature toggle, so we avoid refetching when switching between documents, etc.
In order to test this with the test-studio, this config flag has to be commented out here:
(note - it must be `undefined`, setting it to `false` will disable server actions entirely and skip fetching the flag from the backend):
https://github.com/sanity-io/sanity/blob/373af6a12047e16870fa03270a2452e822a37b55/dev/test-studio/sanity.config.ts#L153
n/a
=> refactor(core): cache fetchFeatureToggle by client

dev/test-studio/structure/resolveStructure.ts, packages/sanity/src/core/search/common/__tests__/getSearchableTypes.test.ts, packages/sanity/src/core/search/common/getSearchableTypes.ts, packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts
We previously allowed users to list assets in the structure tool by using a `S.documentTypeList('sanity.imageAsset')`, but during search refactoring this seems to no longer be possible.
This reintroduces the ability, by ensuring that the `getSearchableTypes()` does not remove explicitly declared types.
- In the test studio, observe that in `next`, the document list under `Custom panes > Images` does not list images, and that the preview deploy of this _does_
- Check that the ["all document types"](https://test-studio-git-fix-structure-explicit-allow-types.sanity.build/test/structure/custom;allDocumentTypes) custom pane in test studio does not list image and file asset types, as well as the global search not including these types.
I attempted to test the actual `listenSearchQuery()` …
=> fix(structure): allow search/list ignored types when explicitly requested

test/e2e/tests/pte/Toolbar.spec.ts
This test was a bit flaky now it should be a bit more sturdy where it checks that the portal has some children (with each opened full screen in PTE more children are added and so are checked).
That it makes sense, maybe there is a better approach to this?
Improves the sturdiness of e2e tests for Portable Text Editor
=> test(core): update e2e test for toolbar in PTE to be more reliable

package.json, packages/sanity/src/core/components/previewCard/PreviewCard.tsx, packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx
By moving the import to colocate with the `StyledCard` definition we're able to avoid the circular deps issue in CJS, and regain the benefit of declaring the `styled(PreviewCard)` on the top-level instead of at runtime in that the CSS is known ahead of time for `styled-components`.
It makes sense what it's named and its internal warning.
I tested it manually, but I'm not familiar with the original cjs bundle issue being referred to, can @bjoerge advice?
N/A as it's an internal refactor that allows React Compiler but is otherwise the same as before
=> fix: handle circular import issue in a compiler friendly way

packages/sanity/src/core/studio/Studio.test.tsx
#6812 had some failing snapshot that I missed. This PR fixes that 
Snapshots makes sense
updated snapshot
N/A
=> test(core): update snapshot for failing test

packages/@sanity/migrate/src/runner/dryRun.ts, packages/@sanity/migrate/src/runner/run.ts, packages/@sanity/migrate/src/types.ts
When running a migration, there may be side-effects like calling a third-party API, or using client to make Sanity requests. A developer may wish to log those effects rather than actually executing them in a dry run.
```ts
import { defineMigration } from "sanity/migrate";
/**
* Run this migration with
* `npx sanity migration run my-migration`
*/
export default defineMigration({
title: "my-migration",
// pass whether the migration is a dry-run as context
async *migrate(documents, { dryRun }) {
for await (const document of documents()) {
if(dryRun) {
// Only log the effect
console.log(`Something happened`)
} else {
// Execute the side-effect
await thirdPartyRequest();
}
// ... do something with the document, maybe yield patches
}
},
});
```
I manually tested that the flag comes through the …
=> feat(migrate): add `dryRun` to context

package.json, packages/sanity/src/structure/components/pane/Pane.tsx
React Compiler isn't able to optimize `<Pane>` when it mutates the `forwardedRef` value returned by `useForwardedRef`.
That's fine, because we can use `useImperativeHandle` to forward refs to the parent in a way that is sound, and that React Compiler is able to handle.
We should probably deprecate the `useForwardedRef` hook in `@sanity/ui` as `useImperativeHandle` is a much better alternative (`useForwardedRef` for example needs a `useEffect` cycle to handle forwarding):
```diff
-import {useForwardedRef} from '@sanity/ui'
-import {forwardRef} from 'react'
+import {forwardRef, useImperativeHandle} from 'react'
export default forwardRef(function Component(props, ref) {
-  const nodeRef = useForwardedRef(ref)
+  const nodeRef = useRef()
+  useImperativeHandle(ref, () => nodeRef.current) …
```
=> fix: use `useImperativeHandle` instead of mutating a parent ref

package.json, packages/sanity/src/structure/components/pane/Pane.tsx
The change in #6813 caused some regressions.
For example previously this would log `HTMLDivElement` on the first render:
```tsx
function MyComponent() {
const ref = React.useRef(null)
React.useEffect(() => {
console.log(ref?.current)
}, [])
return <Pane ref={ref} />
}
```
But in #6813  it's `null`, forcing you to use this pattern for it to be safe:
```tsx
function MyComponent() {
const [el, setEl] = React.useState(null)
React.useEffect(() => {
console.log(el) // eventually logs `HTMLDivElement`
}, [el])
return <Pane ref={setEl} />
}
```
In this PR we regain the behaviour that it's `HTMLDivElement` on the first render, while preserving the ability for React Compiler to compile `<Pane />` since it still uses `useImperativeHandle` instead of `useForwardedRef` 🙌 
It also preserves the …
=> fix: regression in #6813

test/e2e/tests/pte/Toolbar.spec.ts
Update test, had thought the last change I did had made it a bit more sturdy but it needed one more guardrail.  
The update to the test
N/A
=> test(test): update e2e pte toolbar test

packages/@sanity/cli/src/actions/init-project/initProject.ts, packages/@sanity/cli/src/commands/init/initCommand.ts, packages/@sanity/cli/src/packageManager/packageManagerChoice.ts
Adds `--package-manager` flag to the init command. If passed and valid, it will use this flag as the package manager when installing dependencies. 
Note: I have not touched the nextjs init package manager choosing piece not sure if it should or not. 
Changes and copy makes sense. You can still create new projects with and without this flag.
I manually tested different scenarios, this PR will unblock future PRs for testing the init command
- Adds `--package-manager` flag to init command to choose a package manager
=> feat(cli): allow the ability to specify package manager in init command

package.json, packages/sanity/src/core/form/field/actions/FieldActionsResolver.tsx, packages/sanity/src/structure/panes/document/DocumentInspectorMenuItemsResolver.tsx
Refactors `FieldAction` and `InspectorMenuItem` components so they're no longer calling hooks that come from props. Instead, the components themselves are dynamically defined, allowing React to call said underlying hooks in a dynamic way.
It upholds the guarantee that no matter how many times, say, `FieldAction` re-renders, it'll never suddenly see `props.action.useAction()` change identity, because if it changes a new component is created instead.
It should make sense. There's another linter warning in `DocumentInspectorMenuItemsResolver.tsx` that will be handled in a follow up.
Existing tests should be enough.
N/A
=> fix: call dynamic hooks in a way that can be compiled

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx, packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridItem.tsx, packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/InsertMenuGroups.tsx, packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/PreviewItem.tsx, packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ItemRow.tsx
I want to introduce a new `InsertMenu` abstraction and this component's name is conflicting with that. At the same time, I think this component is wrongly named. It does not return an "insert menu", it returns two menu groups that can be used as sub menus in an existing menul.
Is this new name good?
No testing needed.
=> refactor(core): rename InsertMenu->InsertMenuGroups

packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/ArrayOfObjectsFunctions.tsx, packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/getSchemaTypeIcon.ts
I need the same logic in a new component in a subsequent PR so I'm abstracting it beforehand. `||` and `&&` have been changed to `??` and `?:` to avoid returning `| false` from the function. Now, it just returns `ComponentType | undefined`.
Do you like the function name and placement in the repo?
I verified in the test studio that array insert menu icons still show up:
=> refactor(core): abstract `getSchemaTypeIcon`

packages/@sanity/cli/src/actions/init-project/initProject.ts, packages/@sanity/cli/src/actions/project/createProject.ts
Adding "cli" as integration to `metadata.integration` field to better track where a project is created. This follows the pattern we already use for Manage and our onboarding flow.
Tbd
Tbd
None
=> Feat(CLI): Add "cli" as an integration when creating a new project through the CLI

packages/sanity/src/structure/panes/documentList/sheetList/DocumentSheetListSelect.tsx, packages/sanity/src/structure/panes/documentList/sheetList/__tests__/DocumentSheetListSelect.test.tsx
A regression came in around shift-selecting documents and selecting all in between. This was because the IDs of rows changed from being the row index to the document ID.
Updates to the Select tests also
Nothing to note - this feature is not customer facing
=> fix(structure): fixing issue with shift mutli select of documents

packages/sanity/src/core/store/_legacy/user/__tests__/userStore.test.ts, packages/sanity/src/core/store/_legacy/user/userStore.ts
Fixes a case where passing a large number of users to retrieve from the user store would cause too large of a request to be sent. This chunks the number of users to fetch into batches of 400.
- User fetching works as intended
Added tests for the user store in general, there was previously only tests for the 403 case - now it should have the majority of the functionality covered (some missing tests for the `getUser` function, but it calls `getUsers` internally - can add those later)
- Fixes an issue where projects with a large amount of users would sometimes get a request error when loading user info
=> fix(core): chunk user loading into batches of max 400 items

packages/sanity/src/core/environment/hasSanityPackageInImportMap.test.ts, packages/sanity/src/core/environment/hasSanityPackageInImportMap.ts, packages/sanity/src/core/environment/index.ts
Auto-updating studios include importmap scripts in their HTML. For a number of reasons, it's useful to determine whether or not the current studio is an auto-updating one (for metadata in error reporting, or to execute certain pieces of logic that are specific to these studios.
This PR adds a function that can be used to determine whether or not the current studio is an auto-updating one.
The function -- anything that might slow things down or cause errors?
I've added some unit tests but unsure how useful they are, since we have to mock a lot of the rendered HTML. I'm happy to remove them if they're not worth our while.
=> feat: add hasSanityPackageInImportMap

dev/test-next-studio/next.config.mjs, dev/test-next-studio/turbo.json, packages/sanity/src/core/form/studio/FormBuilder.tsx, packages/sanity/src/core/form/studio/FormBuilderInputErrorBoundary.tsx, packages/sanity/src/core/i18n/bundles/studio.ts
While debugging issues in React 19, as well as React Compiler, I've frequently encountered crashes [that takes down the Structure Tool completely](https://test-compiled-studio-b8mfdmi85.sanity.build/test/structure/input-standard;portable-text;pt_allTheBellsAndWhistles;7455ba88-75d5-4a77-94a4-91738fa670c5):
It's difficult to track down exactly what's causing it, the same is true when handling user reports of crashes, in Next v14 and v15 embedded studios in particular.
This PR adds an error boundary for input components, [which narrows down the crash to the input level](https://test-compiled-studio-git-add-input-error-boundary.sanity.build/test/structure/input-standard;portable-text;pt_allTheBellsAndWhistles;7455ba88-75d5-4a77-94a4-91738fa670c5):
In the image above only some of the Portable …
=> feat: add error boundary for form input components

.eslintignore.react-compiler, .eslintrc.cjs, dev/test-studio/components/workspaceLogos.tsx, dev/test-studio/workshop/WorkshopTool.tsx, package.json, packages/@sanity/portable-text-editor/src/editor/hooks/useSyncValue.ts, packages/sanity/src/core/form/inputs/PortableText/hooks/usePortableTextMembers.tsx, packages/sanity/src/core/form/studio/FormBuilderInputErrorBoundary.tsx, packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/core/studio/colorScheme.tsx, packages/sanity/src/core/studio/components/navbar/configIssues/ConfigIssuesButton.tsx, packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentButton.tsx, packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx, packages/sanity/src/core/studio/components/navbar/search/SearchDialog.tsx, packages/sanity/src/core/studio/components/navbar/tools/ToolCollapseMenu.tsx, packages/sanity/src/core/tasks/context/tasks/TasksProvider.tsx, packages/sanity/src/core/user-color/provider.tsx, packages/sanity/src/structure/panes/document/DocumentPane.tsx
On React 19 the Portable Text Editor sometimes ends up in an infinite render loop when there's no value yet, as demonstrated here: https://test-compiled-studio-b8mfdmi85.sanity.build/test/structure/input-standard;portable-text;pt_allTheBellsAndWhistles;7455ba88-75d5-4a77-94a4-91738fa670c5
This PR fixes it: https://test-compiled-studio-git-fix-portable-text-editor-crash.sanity.build/test/structure/input-standard;portable-text;pt_allTheBellsAndWhistles;7455ba88-75d5-4a77-94a4-91738fa670c5
The PR also contains a lot of other minor fixes related to React Compiler, improvements to how the color scheme state is passed around, adding the React Component stack to the form input error boundary etc.
There shouldn't be any infinite render recursion loops happening in React 19 anymore for Portable …
=> fix: portable text editor crash

packages/sanity/src/core/studio/copyPaste/CopyPasteProvider.tsx, packages/sanity/src/core/studio/copyPaste/__test__/schema.tsx, packages/sanity/src/core/studio/copyPaste/__test__/valueTransfer.test.ts, packages/sanity/src/core/studio/copyPaste/types.ts, packages/sanity/src/core/studio/copyPaste/useCopyPasteAction.ts, packages/sanity/src/core/studio/copyPaste/utils.ts, packages/sanity/src/core/studio/copyPaste/valueTransfer.ts
This is a new and improved version of the transferValue function.
It's made more generic so that it's not too tightly coupled to the CopyPasteAction.
It will also work recursively in objects and array values, besides collecting warnings / errors for the result.
I have hooked it up with the copy/paste functionality for the studio.
Also made some new tests for the function.
=> refactor(core): use new value transfer function for copy/paste + tests

test/e2e/tests/document-actions/discardChanges.spec.ts, test/e2e/tests/inputs/reference.spec.ts, test/e2e/tests/pte/Toolbar.spec.ts
- Update two e2e tests that tend to be flaky on next because the timeout runs out
<image src="https://github.com/sanity-io/sanity/assets/6951139/2383f308-d771-4a73-93f6-961a82948a48" width=500>
=> test(e2e): update timeouts for opening popovers

packages/sanity/src/core/scheduledPublishing/components/editScheduleForm/EditScheduleForm.tsx, packages/sanity/src/core/scheduledPublishing/index.ts
Some users are depending on the `EditScheduleForm` for custom scheduled publishing  integrations, this was previously exported from the [plugin](https://github.com/sanity-io/sanity-plugin-scheduled-publishing/blob/main/src/index.ts#L13) but when the plugin was moved into core this export was not included.  
Is this correct?
Export EditScheduleForm from core
=> fix(scheduled-publishing): export EditScheduleForm from core

packages/sanity/src/_internal/cli/actions/build/buildAction.ts, packages/sanity/src/_internal/cli/server/buildVendorDependencies.ts, packages/sanity/src/_internal/cli/util/__tests__/compareStudioDependencyVersions.test.ts, packages/sanity/src/_internal/cli/util/checkStudioDependencyVersions.ts, packages/sanity/src/_internal/cli/util/compareStudioDependencyVersions.ts, packages/sanity/src/_internal/cli/util/getAutoUpdatesImportMap.ts, packages/sanity/src/_internal/cli/util/readPackageJson.ts
Shows a prompt if the installed version of importmap deps are different then what it would resolve to.
FIXES SDX-1342
Updates makes sense.
To test no error case in test-studio
1. cd `dev/test-studio/` 
2. run `pnpm sanity:build --auto-updates` 
Expected: No warning
To test error case in test-studio
1. Update the `sanity` and/or `@sanity/vision` version to something older in `dev/test-studio/package.json` and run `pnpm install`
2. cd `dev/test-studio` 
3. run `pnpm sanity:build --auto-updates` 
Expect: will show copy with different versions
It's probably very hard to do a more integration level test for this, I wrote a unit test for the compare function at least
N/A
=> feat(cli): show prompt if local version doesn't match remote

packages/sanity/src/_internal/cli/actions/build/buildAction.ts, packages/sanity/src/_internal/cli/commands/build/buildCommand.ts
Respects unattended mode when using `auto-updates` flag
`npx sanity build --auto-updates` 
If not using unattended mode it will default to no
`npx sanity build --auto-updates -y` 
If using unattended mode it will default to yes and not show the prompt
Don't have specific tests for this, I will make a follow up PR to add tests for build command with auto-updates in general
N/A
=> fix(cli): allow using auto-updates in unattended mode

packages/sanity/src/structure/panes/document/usePreviewUrl.ts
This removes usage of (now inlined) useAsObservable which will be removed in react-rx@3.x, and also currently causes the React compiler to deopt.
Note: If the user-provided resolveProductionUrl fails, it will currently throw an error in a separate stack frame that can only be captured by window.onerror. After https://github.com/sanity-io/react-rx/pull/87 lands, this error will be part of the react render stack frame and will be captured by the closest error boundary.
This is mostly removing and simplifying existing code. I didn't prioritize adding tests at this point since this is not a very critical part of the Studio, and the main goal here was to avoid React compiler deopt.
n/a - internal
=> refactor(structure): refactor usePreviewUrl for react-rx v3

packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridArrayInput.tsx
Before this change, React would throw a runtime error stating that `A props object containing a "key" prop is being spread into JSX`. Now, the `key` is passed to the JSX without using spread.
=> fix(form): avoid spreading key prop

packages/sanity/src/core/form/inputs/arrays/common/UploadTargetCard.tsx
Fixes regression caused by #6867
Existing tests are enough.
In the future please don't ignore the [testExports](https://github.com/sanity-io/sanity/actions/workflows/testExports.yml) check 🙌 
N/A as AFAIK the regression caused by #6867 isn't published yet
=> fix: regression causing ESM build errors

packages/sanity/src/structure/panes/documentList/sheetList/SheetListCell.tsx, packages/sanity/src/structure/panes/documentList/sheetList/fields/BooleanCellInput.tsx, packages/sanity/src/structure/panes/documentList/sheetList/fields/CellInput.tsx, packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetColumns.tsx, packages/sanity/typings/tanstack-table.d.ts
Boolean input for the sheet list, with `switch` and `checbox`
Supports:
- Copy
- Paste
- Delete (transforms into undetermined value)
=> feat(structure): add support for boolean inputs

packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
If we have html and text on the clipboard, don't include any files into the pasted content.
Word is putting a preview image of the text on the clipboard for instance, when you copy text from the application.
If the intention is to paste a an image or file, there will be no text and html version on the clipboard as far as  I can tell, testing different scenarios on my machine (Mac).
That this assumption holds water. 
Fix issue where a text preview image would be included into the Portable Text input, when pasting text from Word.
=> fix(core): fix issue with pasting mixed content (files and text) for PT-input

packages/sanity/src/core/presence/overlay/StickyOverlay.tsx
There have been some reports that the `StickyOverlay` component is being given regions that have no DOM node (instead, the `element` property is `null`). This causes an error when we attempt to read the `scrollTop` property of the element inside `getOffsetsTo`.
For affected users, this crashes the entire structure tool when it occurs.
I haven't yet been able to replicate this issue, nor determine the cause. We have a hook named `useReporter` that we use to track the position of field presence indicators. It passes up the value of a ref attached to a DOM node. That ref is read inside a layout effect, so it should never be `null` as far as I understand.
As an exploratory fix, I've added a condition to `StickyOverlay` to ignore any region that has a falsey DOM node. My hope is this will fix …
=> fix(sanity): ignore sticky overlay regions with a falsey DOM node

packages/sanity/src/router/RouteScope.tsx
Scoped routers implement their own `navigate` function which wraps that of the parent router and calls it with some new resolved state.
Currently this wrapper function does not pass an options param to the parent function call. As far as I can tell this means scoped routers can only push, not replace history state. I suspect this is an oversight as for example the `PaneRouter` [attempts to replace using an options param](https://github.com/sanity-io/sanity/blob/a8270d224d55e052608fa21e0ce0d1f440279db7/packages/sanity/src/structure/components/paneRouter/PaneRouterProvider.tsx#L183-L188).
Similarly, in the Presentation tool, we can't currently replace history state as we implement our own scoped router (`PresentationPaneRouterProvider`), I believe this PR would fix that issue for us.
1. …
=> fix(router): pass options on scoped router navigation

packages/sanity/package.json
When running playwright component tests locally we often have a problem with stale playwright cache, that is separate from the cache in the monorepo.
This change makes sure the cache is deleted every time you run `test:ct`.
=> chore: clean playwright-ct cache on each run

packages/sanity/src/core/form/components/ActivateOnFocus/ActivateOnFocus.tsx
After the change in #6867 you have to activate the PTE before you are able to drag files into the PTE.
This change fixes that situation by activating the PTE whenever the drag starts.
- That the PTE activates when you start dragging files into it.
- Fixes a issue where the PTE won't activate when you start dragging files into it
=> fix(form): activate PTE input when dragging files

package.json, packages/sanity/src/core/form/inputs/files/ImageToolInput/imagetool/Resize.tsx
Currently everytime `<Resize>` renders it calls `resize()` before handing it off to the `children` prop callback.
Even though the init of `canvas` is memoized with `useState`, and it's only added to the dom once, in a `useEffect`, what happens during `resize` voids any benefits from these optimizations:
- it sets `canvas.height` and `canvas.width`, [causing layout trashing](https://web.dev/articles/avoid-large-complex-layouts-and-layout-thrashing) and repaint.
- it calls ` ctx.drawImage(image, ...)`, which is expensive especially on larger images.
This PR changes it to run it in a single layout effect (the reasoning for why a layout effect is used instead of a regular effect is explained in code comments).
The effect only runs if the `image`, or `maxHeight` and `maxWidth` changes. …
=> fix: improve perf of <Resize> by creating the canvas in a side effect

package.json, packages/sanity/src/core/hooks/useListFormat.ts
Calling a hook inside a try/catch boundary is violating the [rules of hooks](https://19.react.dev/warnings/invalid-hook-call-warning).
React relies on call order for core hooks (`useState`, `useMemo`, all the hooks that come from `react`) and that they are consistent on every re-render.
The fact that this currently works for `useListFormat` is a hack, and has downsides:
- [v8 and other browser engines have to deopt a lot of JIT perf boosts when catch boundaries are used, and errors thrown](https://blog.dubbelboer.com/2012/04/16/node-try-catch.html).
- if other errors than a missing context is thrown then the hook swallow said errors, for example what if calling `intlCache.listFormat` throws a unhandled runtime error?
- React Compiler is unable to optimize components that have hooks that …
=> fix: change `useListFormat` to no longer violate the rule of hooks

packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/restore.ts, packages/sanity/src/core/store/_legacy/history/createHistoryStore.ts
This fixes an issue with using [API actions](https://www.sanity.io/docs/http-actions) causing a 409 error when restoring a document from history that already has a published version.
The e2e tests should cover this already
- Fixes an issue that could cause a 409 error when restoring a document from history.
=> fix(sanity): only include create action when restoring a deleted document

package.json, packages/sanity/src/core/presence/overlay/RegionsWithIntersections.tsx
By destructuring the array, which is guaranteed to always be a `[number, number, number, number]` tuple, the memoization is no longer violating the rules of hooks by overriding how deps are specified in `useMemo`. And it no longer calls `JSON.stringify` on every single render.
Thus it can also be compiled by React Compiler.
Presence circles should work like before in general, and slightly faster in https://test-compiled-studio.sanity.build
Existing tests should cover it.
N/A
=> refactor: change memoization of margins to support the rule of hooks

packages/@sanity/schema/src/legacy/types/file.ts, packages/@sanity/schema/src/legacy/types/image.ts, packages/@sanity/schema/src/legacy/types/object.ts, packages/@sanity/schema/test/legacy/fixtures/schemas/arrays.ts, packages/@sanity/schema/test/legacy/schemas.test.ts
In certain UI locations, especially for array members, image and files would be listed without a title, or using the type name (`image`) when the member declaration is simply: `{type: 'image'}`.
This PR ensures that we fall back to the base types' title.
I also modified the _object_ to use the same approach, but I think this one is more theoretical, since we require a name for  objects.
- Code looks good
- "Add item" menus lists images and files correctly (there's a "Array of multiple types" field that has this in the test studio)
Added new tests to ensure no regressions.
Also did some manual testing.
- Fixes a case where image and file types might be listed in their lowercase variant in array insert menus
=> fix(schema): use base type title if no subtype title or name is given

packages/sanity/src/_internal/cli/actions/build/buildAction.ts, packages/sanity/src/_internal/cli/server/__tests__/buildVendorDependencies.test.ts, packages/sanity/src/_internal/cli/server/buildVendorDependencies.ts
Accounts for basePath in the import map for vendor packages.
How to test 
1. Add the following code in `dev/test-studio/sanity.cli.ts` 
```
project: { basePath: '/something' }
```
2. Run `pnpm sanity:build --auto-updates` 
3. Run `pnpm start` and notice the vendor packages are served from `/something/react/...` 
I tried writing a test for build command with auto updates but it runs into an issue. Since the CLI is packaged and run as a whole there is no ability to mock anything. We would need to mock the getRemoteVersions function so it works and does not fail. I tried using `msw` and `nock` with no luck and I am curious if there is a better way to do this?
Did update the tests for buildVendorDependencies to account for basePath variations
N/A
=> fix(cli): account for base path in the importmap

packages/sanity/src/core/form/inputs/SelectInput.tsx, packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/string/StringList.tsx, packages/sanity/src/structure/panes/documentList/sheetList/DocumentSheetListProvider.tsx, packages/sanity/src/structure/panes/documentList/sheetList/SheetListCell.tsx, packages/sanity/src/structure/panes/documentList/sheetList/__tests__/DocumentSheetListSelect.test.tsx, packages/sanity/src/structure/panes/documentList/sheetList/fields/BooleanCellInput.tsx, packages/sanity/src/structure/panes/documentList/sheetList/fields/CellInput.tsx, packages/sanity/src/structure/panes/documentList/sheetList/fields/DropdownCellInput.tsx, packages/sanity/src/structure/panes/documentList/sheetList/types.ts, packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetColumns.tsx, packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetListStore.ts, packages/sanity/src/structure/panes/documentList/sheetList/useOnMouseDownCell.ts, packages/sanity/typings/tanstack-table.d.ts
* Supporting Dropdown selection for string and number selects and radio button groups
* Fixing issue where unsetting a value in document form would not propagate to sheet list
* New `DropdownCellInput` renders for dropdown selects
* `useOnMouseDownCell` hook to group the logic around whether a cell should require dbl click to focus or not
I'll add more wider tests for all the sheet list inputs in a separate branch
Nothing relevant to note- no user facing changes
=> feat(structure): Sheet List dropdown selects

packages/@sanity/cli/test/__snapshots__/typegen.test.ts.snap, packages/@sanity/codegen/src/typescript/__tests__/__snapshots__/typeGenerator.test.ts.snap, packages/@sanity/codegen/src/typescript/__tests__/typeGenerator.test.ts, packages/@sanity/codegen/src/typescript/typeGenerator.ts
Adds a union that exports all the potential schemas to the generated file. This can be useful in mocks/testing environments and used by third party tools to get a list of potential types.
Name of the exported variable `allSchemaTypes`, should it be prefixed with anything? `_`? Anything else to indicate that this is a "special" type?
Already test schema generation, so updated the snapshots
TypeGen: Added a type export of all the the discovered Sanity Schema variants.
=> feat(typegen): add all schema types exported union

dev/test-studio/documentActions/actions/createCustomPublishAction.ts, dev/test-studio/documentActions/index.ts, dev/test-studio/schema/debug/documentActions.js, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/__snapshots__/publish.test.ts.snap, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/publish.ts, test/e2e/tests/document-actions/publish.spec.ts
This branch removes usage of the `ifDraftRevisionId` optimistic lock when publishing documents using the Actions API. For custom publish document actions, `snapshots.draft._rev` may be stale, which means the `ifDraftRevisionId` optimistic lock cannot currently be used.
This is less safe, because it means it's technically possible for a user publishing a document via Studio to cause the publication of a draft that has not yet been synced to them. However, it's important to note this same issue exists with the Mutations API integration today. When the underlying staleness bug is fixed in the future, we should switch `ifDraftRevisionId` back on.
We still make use of `ifPublishedRevisionId` to ensure concurrent publish action invocations do not override each other.
That removing the …
=> fix(test-studio): add repro case for using server actions with custom publish document action

packages/@sanity/types/package.json, packages/sanity/package.json, pnpm-lock.yaml
Needs to be merged after https://github.com/sanity-io/sanity/pull/6969. The build will fail until that PR has been merged.
=> deps(core): update @sanity/insert-menu

packages/sanity/src/structure/components/paneRouter/PaneRouterProvider.tsx
Before the fix in #6923 got merged, when deleting a document, you could always hit the back button to get back to the newly deleted document, and there you’d be given a way to undo/restore it. 
Now after this fix, if you delete a document you can no longer hit the back button to recover a deleted document if you realise you made a mistake (unless you remember the id, which you probably don’t). This is not great, and we want to leave a history entry in this case so you navigate back.
Deleting a document should allow you to navigate back to restore it.
n/a since the changes in #6923 has not been released yet
=> fix(structure): don't replace url when navigating back to list after document deletion

packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/core/store/_legacy/history/history/Aligner.ts, packages/sanity/src/structure/documentActions/HistoryRestoreAction.tsx, packages/sanity/src/structure/panes/document/timeline/timelineMenu.tsx
This makes our labeling of revision to be more consistent. We are calling it revision in someplaces but not everywhere. Also updated the code to be more consistent too.
- Is the way I've deprecate the old i18n key ok?
- Would it be better to leave the key as-is and instead just change the label?
Don't think it makes all that much sense to add automated testing for this one
n/a - should just make the studio terminology more consistent.
=> refactor(core): change revision history label from 'Version' to the more accurate 'Revision'

dev/test-studio/plugins/error-reporting-test/ErrorReportingTest.tsx, dev/test-studio/plugins/error-reporting-test/index.ts, dev/test-studio/plugins/error-reporting-test/plugin.tsx, dev/test-studio/sanity.config.ts, packages/sanity/package.json, packages/sanity/src/core/error/errorReporter.ts, packages/sanity/src/core/error/sentry/README.md, packages/sanity/src/core/error/sentry/sentryErrorReporter.ts, packages/sanity/src/core/studio/StudioErrorBoundary.tsx, packages/sanity/src/core/studio/StudioProvider.tsx, packages/sanity/src/core/version.ts, pnpm-lock.yaml
This introduces an error reporter using Sentry, for auto-updating, non-embedded studios. In the future, we may extend this to other studio types/configurations.
- Can be reviewed as a whole - I'll squash on merge
- The only (seemingly) unrelated commit here is the first one, which changes the `SANITY_VERSION` constant from being a static `0.0.0-development` to say `3.15.3-development`. This is really only relevant for the monorepo, but is helpful in the context of error reporting to see what the "base" version is.
- The Sentry relay is currently not working due to some CORS issues I am working to figure out, but the _code_ aspect of this is ready for review.
- I am aware of a few locations in the code that needs a few comments to clarify the purpose/rationale for them - I'll see if I can …
=> feat(core): implement basic error reporting

packages/sanity/src/_internal/cli/server/buildVendorDependencies.ts
Fixes import map path on windows since we are using join to create specifier it is using windows style in output
change makes sense.
~My attempt to simply add windows to actions testing list was not successful. I am not what really is the best way to test this, would love to some suggestions~ - Will be fixed in future PRs
Manually tested in windows and it works
N/A
=> fix(cli): fixes importmap path on windows

packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/core/studio/StudioProvider.tsx, packages/sanity/src/core/studio/packageVersionStatus/PackageVersionStatusProvider.tsx, packages/sanity/src/core/studio/packageVersionStatus/checkForLatestVersions.ts, packages/sanity/src/core/version.ts, test/e2e/tests/default-layout/versionStatus.spec.ts
As we move to certain packages being able to auto-update, we want end-users of the studio to know when to refresh their browsers and work with the most up-to-date packages.
This PR adds a Provider that will:
1. Poll an endpoint in module-server every 30 minutes to check for the most up-to-date packages.
2. Check if the current studio is an auto-updating studio.
3. If so, send a toast alerting the user to reload their browsers, along with a button.
1. The language and design of the toast.
2. The logic of the check -- anything strange?
Unfortunately I think the reviewer ought to pull this down and review manually -- see below for why (because of limited ability to test).
I've added a few e2e tests. I'm not testing if the reload button actually reloads the page; I couldn't find an easy way …
=> feat: notify AUS studio users of new studio versions

packages/@sanity/migrate/src/fetch-utils/__test__/assert2xx.test.ts, packages/@sanity/migrate/src/fetch-utils/fetchStream.ts
Seems like the error response from backend is in the shape below
```ts
{ error: { type: string, description: string }
```
When we receive error in this shape we don't properly log that message making it hard for folks to debug. See screenshots below 
Copy and change makes sense, I checked the repo and there seems to be other places checking `error.description` so I am not sure if error will not be an object but I added a conditional to keep backwards compatibility
Updated the test
- Migration error messages provide more details
=> fix(migrate): fixes error message to be more helpful

packages/sanity/src/_internal/cli/server/renderDocument.ts
Saw this randomly on [this test-next-studio build](https://vercel.com/sanity-io/test-next-studio/GmsQegGwVvZBMssTnGz94fYEwtDY?filter=errors) - in some cases the unregistration of the esbuild-register instance failed. After some investigation, it seems like we're returning a function where we should be returning an object.
Not quite sure why this popped up _now_, but worth fixing.
- test-next-studio should build without errors (CI)
None
=> fix(cli): correct noop return value on esbuild-register in dev

packages/sanity/src/core/studio/packageVersionStatus/checkForLatestVersions.ts
We recently introduced a version check for auto-updating studios that depend on `process.env` for telling if we're in staging or not - this doesn't work nicely across all environments, as some of them use `import.meta.env`, and others use `process.env`. To make things worse, we can't easily check for `process.env` and use `process.env[envVar]` as bundlers define these as "hard replacements" instead of actually defining an object.
This replaces the check with the same approach as we do in [createAuthStore](https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts#L147-L151), relying on the somewhat magic `__SANITY_STAGING__`  global defined in our [vite config](https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/_internal …
=> fix(core): make version check not depend on `process.env`

.github/workflows/are-we-compiled-yet.yml, .github/workflows/cli-test.yml, .github/workflows/depCheck.yml, .github/workflows/docReport.yml, .github/workflows/e2e-ct.yml, .github/workflows/e2e-pte.yml, .github/workflows/e2e.yml, .github/workflows/etl.yml, .github/workflows/formatCheck.yml, .github/workflows/lint-fix-if-needed.yml, .github/workflows/lintPr.yml, .github/workflows/perf.yml, .github/workflows/pnpm-if-needed.yml, .github/workflows/pr-cleanup.yml, .github/workflows/prettier-if-needed.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/testExports.yml, .github/workflows/typeCheck.yml
This upgrades `pnpm/action-setup@v2` that uses Node 16 to v4 that uses Node 20. This gets rid of the deprecation warnings in GH actions. This version is also more strict and requires you to install the exact version if you have defined `packageManager` in package.json.
Any downsides to upgrading? I know we do tests against Node 18 as well, but don't think this affects that in any way?
=> chore(ci): upgrade pnpm setup to use node20

packages/@sanity/cli/src/util/journeyConfig.ts
Remove trailing commas on Journey schema sanitizer as this in will output invalid code that makes Prettier throw in certain cases.
This is a schema that would previously throw:
```json
[{"name":"post","title":"Post","type":"document","fields":[{"name":"title","title":"Title","type":"string"},{"name":"slug","title":"Slug","type":"slug","options":{"source":"title","maxLength":96}},{"name":"author","title":"Author","type":"reference","to":{"type":"author"}},{"name":"mainImage","title":"Main image","type":"image","options":{"hotspot":true}},{"name":"categories","title":"Categories","type":"array","of":[{"type":"reference","to":{"type":"category"}}]},{"name":"publishedAt","title":"Published at","type":"datetime"},{"name":"body","title":"Body","type":"blockContent"}]},{"name":"author","title":"A …
```
=> fix: remove trailing commas when sanitizing

packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingDialog.tsx, packages/sanity/src/core/form/studio/tree-editing/utils/getRootPath.ts
This pull request fixes an issue with `getRootPath`, which caused the tree editing dialog to not open correctly using `shouldArrayDialogOpen`. The function incorrectly returned an empty array when no `_key` was present in the path.
**Before**: `['array']` => `[]`  
**After**: `['array']` => `['array']`
The fix changes the condition to `if (keyedSegmentIndex === -1)`, ensuring the entire path is returned if no `_key` is found.
- Make sure that the tree editing dialog opens correctly
N/A
=> fix(core): tree editing dialog open issue

packages/sanity/src/structure/panes/documentList/__tests__/PaneContainer.test.tsx, packages/sanity/src/structure/panes/documentList/sheetList/DocumentSheetListPane.tsx, packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetList.ts, packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetListStore.ts
When a document for the type is added it is received in the sheet list store, but the search is not updated because we are not triggering a new search.
Producing the effect of not adding the document into the sheet view.
With this changes when either a document is added or removed, the sheet list view will react accordingly, because the items map is updated.
=> fix(structure): when documents are added, add them to sheet list

packages/sanity/src/_internal/cli/server/__tests__/buildVendorDependencies.test.ts, packages/sanity/src/_internal/cli/server/buildVendorDependencies.ts
This PR updates the `buildVendorDependencies` function to correctly handle and return hashed filenames in the import map. The changes involve modifying the Vite build configuration to include hashes in the output filenames and then updating the function to map the original import specifiers to their hashed filenames. This ensures that the import map reflects the hashed filenames produced by the Vite build process, improving cache management and consistency.
- Review the changes in `buildVendorDependencies.ts` to ensure the correct handling of hashed filenames in the import map.
- Check the test file `buildVendorDependencies.test.ts` to confirm that the tests accurately reflect the new behavior and correctly mock the Vite build process.
- Ensure that the implementation correctly maps …
=> feat: include hashes in vendor builds

packages/sanity/src/core/studio/packageVersionStatus/checkForLatestVersions.ts
Updates the URL for notify endpoint to add the timestamp
Changes makes sense, I haven't really tested it thoroughly
Probably not needed
N/A
=> fix(core): update url for notify endpoint

packages/sanity/src/structure/panes/documentList/sheetList/DocumentSheetListHeader.tsx, packages/sanity/src/structure/panes/documentList/sheetList/SheetListCell.tsx
Adds validation at cell level, showing a call out line in the feels with validation errors, warning or info.
=> feat(structure): add validation to sheet list cell

packages/@sanity/cli/src/actions/init-project/initProject.ts, packages/@sanity/cli/src/actions/project/createProject.ts, packages/@sanity/cli/src/util/journeyConfig.ts
Moving the position of where integration for a new project is defined, since createProject is called in multiple places throughout the CLI.
- Create a new project though the cli
- Curl the `v1/projects/{projectId}` endpoint
- Verify that integration value is set to `cli`
No notes
=> Fix(CLI): Set integration value for createProject directly in the createProject function

packages/sanity/src/structure/documentActions/DiscardChangesAction.tsx
Old: `action.discard-changes.disabled.no-changes`
New: `action.discard-changes.disabled.no-change`
This is to match what is in https://github.com/sanity-io/locales/
Localization key for the alt text on the "Discard Changes" action when it is disabled. 
https://github.com/sanity-io/locales/blob/main/locales/fr-FR/src/structure.ts#L17 for an example of the key translated / used
None
=> fix(structure): fix incorrect i18n key for discard changes button "no changes" status

packages/sanity/package.json, packages/sanity/src/core/error/errorReporter.ts, packages/sanity/src/core/error/sentry/makeBufferedTransport.ts, packages/sanity/src/core/error/sentry/sentryErrorReporter.ts, packages/sanity/src/core/studio/EnableErrorReporting.ts, packages/sanity/src/core/studio/EnableErrorReporting.tsx, packages/sanity/src/core/studio/StudioProvider.tsx, pnpm-lock.yaml
In order to respect our users' telemetry consent, it's become necessary to ensure we don't send events to Sentry when consent has not been granted.
We are somewhat changing the paradigm of error reporting, where error reporters are assumed to be in a "disabled" state until otherwise enabled. We're doing so by:
1. Adding an `enable` and `disable` function on the errorReporter.
2. Adding a component to StudioProvider at an appropriate depth where the client can check the user's consent status.
3. In our specific Sentry implementation, initializing Sentry with a custom transport that buffers events until consent is received.
Are we satisfied with this? Any caveats about in-memory issues or fragility?
I'd like to incorporate tests for this in my other PR (#7002) -- possibly by intercepting …
=> fix: check for telemetry consent before error reporting

packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputBrowser.tsx
Seems like there was a regression in #6930 where the Select/Browse button would not render if there was only a single asset source.
Does the button show up now for a single asset source?
I removed the custom asset source so that there would only be one in the test studio, observed the bug, then fixed it.
Fixes a regression that caused the Select button to not appear.
=> fix(core): put back select button for single-asset source

packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
Supersedes #7016 but has the same outcome.
Does this allow `--no-dry-run` and `--no-confirm` together?
https://github.com/sanity-io/sanity/assets/10551026/73708788-b698-4063-b34e-8debc6ad5978
Fixes a bug where `--no-dry-run` and `--no-confirm` could not be used together.
Big thanks to @pawelngei
=> fix(cli): allow no-confirm no-dry-run migrations

.github/workflows/release.yml
The `Version` step in the release.yml workflow was added so that the build could be ran with updated `package.json` version but this was causing an issue with mismatched types and packages causing the build when installing after the version bump. it's not strictly necessary so we'll be removing this as a result.
~~Do we rely on the `Version` step at all? I believe we have measures in place that get the monorepo version in other ways so this version step should not be necessary.~~
Had a sync with @rexxars and we found that if the environment variable `PKG_VERSION` is set, it circumvents the needs to run `lerna version` prior to running the build.
In order to test the above theory, I ran the build locally with the environment variable PKG_VERSION set to a different version than in the …
=> build: remove `Version` step from release workflow

packages/sanity/src/core/tasks/components/list/TasksList.tsx
Small UI fix when tabbing in tasks
Before: 
After: 
Tab box in tasks
=> fix(core): change padding to fix tab box

packages/sanity/src/core/store/bundles/__workshop__/BundlesStoreStory.tsx, packages/sanity/src/core/store/bundles/__workshop__/ReleaseForm.tsx, packages/sanity/src/core/store/bundles/__workshop__/index.ts, packages/sanity/src/core/store/bundles/index.ts, packages/sanity/src/core/store/bundles/reducer.ts, packages/sanity/src/core/store/bundles/types.ts, packages/sanity/src/core/store/bundles/useBundleOperations.ts, packages/sanity/src/core/store/bundles/useBundlesStore.ts
Introduces `bundlesStore` allowing to fetch bundles metadata from the `addon-dataset`.
Also, introduces a minimal implementation for `bundlesOperations` for testing purposes.
It can be tested in the following story:
https://test-studio-git-corel-6.sanity.build/test/workshop/core;bundles;bundles-store
=> feat(corel): integrate bundles store

dev/test-studio/schema/debug/objectsDebug.ts, packages/sanity/playwright-ct/tests/formBuilder/tree-editing/TreeEditing.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/tree-editing/TreeEditingStory.tsx, packages/sanity/src/core/form/components/FormInput.tsx
This pull request fixes an issue where the `FormInput` would not render a field inside a fieldset. The current logic only finds fields that have the `kind` of `"field"` but does not handle the `kind` of `"fieldSet"`. The issue can be reproduced by:
1. Adding the following schema with an array field that has a fieldset defined:
```ts
import {defineType} from 'sanity'
export const myDocument = defineType({
name: 'myDocument',
fieldsets: [
{
name: 'fieldset',
title: 'Fieldset',
},
],
fields: [
{
type: 'array',
name: 'fieldsetArray',
title: 'Fieldset array',
fieldset: 'fieldset',
of: [
{
name: 'myObject',
fields: [
{
name: 'string',
title: 'String',
},
],
},
],
},
],
})
```
2. Enabling the array tree editing beta feature:
```ts
import …
```
=> fix(core): handle fieldset members in `FormInput`

packages/sanity/playwright-ct/tests/formBuilder/tree-editing/TreeEditing.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/tree-editing/TreeEditingStory.tsx, packages/sanity/src/core/form/studio/tree-editing/utils/build-tree-editing-state/buildArrayState.ts
This pull request fixes an issue where the tree editing dialog does not open correctly when the `openPath` points to an array item inside a portable text block. This can occur, for example, when navigating to a field with presence, from a comment, or using the validation menu.
Steps to reproduce the issue:
1. Open the tree editing dialog.
2. Open an array item inside a portable text editor.
3. Add a comment to a field in the array item.
4. Close all dialogs.
5. Click the comment in the inspector.
6. Notice that the dialog(s) do not open.
- General code review
- Ensure that the PTE dialogs are opening correctly inside the tree editing dialog when setting the `openPath`
- Component tests added to cover this particular situation
N/A
=> fix(core):  open PTE dialogs in tree editing dialog with `openPath`

packages/@sanity/codegen/src/typescript/__tests__/__snapshots__/typeGenerator.test.ts.snap, packages/@sanity/codegen/src/typescript/__tests__/typeGenerator.test.ts, packages/@sanity/codegen/src/typescript/typeGenerator.ts
When we generate the types we hold the generated type name in case it's referenced later. This was needed primarily because we, earlier, wanted to support multiple queries having the same name etc. Since we now doesn't allow this, it's not a big case. However, in https://github.com/sanity-io/sanity/pull/6997 we need to later reference all the names by the type nodes.
Correctness: The outputted types should be 100% identical to the previous.
Tests should still pass, I added a test for the case where it's referencing a type node we haven't seen.
=> refactor(typegen): use typenode to lookup referencing type names

packages/sanity/playwright-ct/tests/formBuilder/tree-editing/TreeEditing.spec.tsx, packages/sanity/src/core/form/studio/FormBuilder.tsx, packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingDialog.tsx
This pull request ensures that the root array item is focused when the tree editing dialog is closed. It also adds animation to the tree editing dialog to be consistent with other dialogs in the studio.
Note: there is currently an issue with setting the correct `focusPath` when closing the tree editing dialog without having focused on any input in the form. This will be addressed as a separate issue.
- Ensure that the changes are working as expected.
- Component test for focusing the root array item when closing the tree editing dialog.
N/A
=> feat(core): focus root array item when closing tree editing dialog

packages/@sanity/cli/test/exportImport.test.ts, packages/sanity/src/_internal/cli/commands/dataset/exportDatasetCommand.ts
A new mode in the export endpoint allows streaming incrementally with a cursor
Added a CLI test to make sure it picks it up 👍 
Export: Add new export mode that can uses a cursor when exporting, this might be more performant for larger datasets, but might not be as accurate if the dataset is being modified during export. Defaults to stream
=> feat(cli): Add support for exporting dataset with cursor

packages/@sanity/migrate/src/mutations/operations/creators.ts
The TSDoc for the `insert` method incorrectly gives examples of 2 provided args
=> docs(migrate): updating insert examples to showing always 3 args

packages/sanity/src/_internal/cli/util/mockBrowserEnvironment.ts
A user reported importing the `quill` dependency in some plugin/schema, which (on startup) calls `document.execCommand`, which does not exist in our mocked environment and thus crashes.
This PR mocks the function as a no-op.
`sanity schema extract` works as before. Adding a `document.execCommand()` call in a schema file does not crash.
The browser env mocking does not have tests currently, and it throws when trying to run it in jest because of the odd worker  setup they are using. I couldn't find an immediate and clean way to test this - perhaps we could take a stab at some separated tests that runs in regular node environment at some point?
- Fixes an issue when trying to extract schemas/deploy GraphQL APIs when a subdependency tries to call `document.execCommand` at import time
=> fix(cli): mock `document.execCommand` when emulating browser env

dev/studio-e2e-testing/sanity.config.ts, packages/sanity/src/core/store/_legacy/document/document-pair/utils/fetchFeatureToggle.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/utils/fetchFeatureToggle.ts, pnpm-lock.yaml, test/e2e/helpers/mockActionsFeatureToggle.ts, test/e2e/tests/document-actions/fetchFeatureToggle.spec.ts
This change allows us to dynamically enable the Actions API based on the Studio version (post this release) from the Actions API. The API response now includes a `compatibleStudioVersions` property specifying a semver range that indicates the compatible Studio versions. If the feature toggle is enabled, Studio will first confirm it satisfies the semver constraint before enabling the gated functionality.
The feature toggle will never be acknowledged by existing Studio releases.
1. Existing Studio versions will treat the absence of the deprecated `actions` property as falsey, meaning they will never enable Actions API usage based on this feature toggle.
2. Future Studio versions will enable Actions API usage based on this feature toggle as long as `enabled` is `true` and the Studio version …
=> feat(sanity): allow Actions API enablement based on Studio version semver constraint

.github/renovate.json
When https://github.com/sanity-io/sanity/pull/6920 were closed it didn't turn off `styled-components` renovation for just [that particular `package.json`](packages/sanity/fixtures/examples/prj-with-styled-components-5/package.json), it also disabled `styled-components` updates for the rest of this repo.
The rules in this PR will instead opt-out the fixture `package.json` files from being part of the manifests that renovate maintains, allowing us to see future updates to `styled-components`
=> chore(renovate): add fixtures to `ignorePaths`

dev/studio-e2e-testing/sanity.config.ts, dev/test-studio/sanity.config.ts, packages/sanity/playwright-ct/tests/formBuilder/tree-editing/TreeEditingStory.tsx, packages/sanity/playwright-ct/tests/formBuilder/utils/TestWrapper.tsx, packages/sanity/src/core/config/configPropertyReducers.ts, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/types.ts, packages/sanity/src/core/form/studio/tree-editing/__tests__/useTreeEditingEnabled.test.tsx, packages/sanity/src/core/form/studio/tree-editing/context/enabled/TreeEditingEnabledProvider.tsx, packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
As spoken with Rune, remove the `features` object and rely instead on the `beta` object.
- Make sure that the code makes sense
- Try out the feature and make sure that everything is still working as expected
There are already automated tests for this (and of the feature itself)
N/A shadow release related
=> refactor(sanity): remove "features"

packages/@sanity/cli/test/exportImport.test.ts
We're seeing some [new failures](https://github.com/sanity-io/sanity/actions/runs/9865117760/job/27241410606?pr=7117) in the CLI tests intermittently. After some brief investigation, I think perhaps it is caused by the same tarball location being used for both the regular and cursor based export tests, which can run concurrently.
This PR changes the filename used by the cursor based export test, to ensure they do not interfere with eachother.
Tests should still pass, but be more stable
None
=> test(cli): use separate tarball location for cursor export test

packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetList.ts
Just a tiny fix for a typo I saw when translating, + a few consistency fixes adding spaces after comments
Changes do not contain typos
Shouldn't need any changes, just comment fixes
None
=> fix(core): minor typo fix in i18n comment

packages/sanity/src/core/studio/router/helpers.test.ts, packages/sanity/src/core/studio/router/helpers.ts, packages/sanity/src/core/studio/router/types.ts, packages/sanity/src/router/IntentLink.test.tsx, packages/sanity/src/router/IntentLink.tsx, packages/sanity/src/router/RouterProvider.tsx, packages/sanity/src/router/types.ts, packages/sanity/src/router/useIntentLink.ts
As part of releases we are introducing a query param that needs to be persisted in the url, `perspective`
It will determine which `perspective` the user has selected and we need to use the `IntentLink` component to change the perspective the user has selected when navigating to a version document.
How it will be used:
```ts
<IntentLink
{...linkProps}
intent="edit"
params={{
id: getPublishedId(documentId, true),
type: documentTypeName,
}}
searchParams={[['perspective', `bundle.${release.name}`]]}
ref={ref}
/>
```
Path example: `/test/intent/edit/id=c0c99e43-40de-4d8b-abec-a710d5752ea2;type=book/?perspective=bundle.pedro-summer` 
see https://github.com/sanity-io/sanity/pull/7092/files#diff-729068b8f99a9501225501d3379505aa1a85162b6e41aa9654b7c5aa8a83d067R122-R139 for further details.
Is this …
=> feat(router): update router to support query params in intent links

.github/renovate.json
Following up on #7126 this changes renovate so it doesn't keep creating PRs that bump `esbuild` minor (minor are breaking btw) or major versions: https://github.com/sanity-io/sanity/pull/7127
=> chore(renovate): only bump esbuild within `0.21.x`

packages/sanity/src/_internal/cli/util/checkRequiredDependencies.ts
Bit of an edge case, but; in some settings (like plugin development) you might have a studio installed to test the plugin. In those settings, styled-components shouldn't be a dependency - instead it should be a _dev_ dependency, in order to not cause multiple versions to be installed (dev + peer, to be exact). Currently the CLI will complain that it can't find the package declared in `dependencies` and attempt to install it, which leads to an infinite install loop, as npm already sees it listed and installed - and then re-runs the same command again.
This change should ensure that it can exist in `devDependencies` _or_ `dependencies`. Don't believe this to be an issue for regular users either, since strictly speaking in an app setting it is only a _build time_ dependency.
- Running …
=> fix(cli): allow styled-component as dev dependency

packages/sanity/src/core/releases/components/BundleMenuButton/BundleMenuButton.tsx, packages/sanity/src/core/releases/components/BundleMenuButton/__tests__/BundleMenuButton.test.tsx, packages/sanity/src/core/store/bundles/useBundleOperations.ts
When a bundle document is removed the related version documents in the main dataset should also be removed.
This PR adds that functionality and implements a confirmation modal before deleting everything, given this is a destructive operation.
🟡 Missing changes due to the listener updates for the related documents count 🟡
=> feat(corel): remove version documents when deleting bundle

packages/sanity/src/core/releases/tool/detail/documentTable/DocumentActions.tsx, packages/sanity/src/core/releases/tool/detail/documentTable/DocumentRow.tsx, packages/sanity/src/core/releases/tool/detail/documentTable/useDocumentPreviewValues.ts
Updates discard version dialog to match with the UI, discard functionality was included in base branch.
=> feat(corel): update discard version dialog

dev/studio-e2e-testing/i18n/bundles.ts, dev/studio-e2e-testing/sanity.config.ts, dev/test-studio/locales/index.ts, dev/test-studio/schema/debug/fieldGroupsWithI18n.ts, dev/test-studio/schema/index.ts, dev/test-studio/structure/constants.ts, packages/@sanity/types/src/schema/definition/type/common.ts, packages/@sanity/types/src/schema/types.ts, packages/sanity/src/core/form/inputs/ObjectInput/fieldGroups/FieldGroupTabs.tsx, packages/sanity/src/core/form/store/constants.ts, packages/sanity/src/core/form/store/formState.ts, packages/sanity/src/core/form/store/types/fieldGroup.ts, packages/sanity/src/core/i18n/bundles/studio.ts, test/e2e/tests/inputs/object.spec.ts
The "All fields" field group is currently not translatable - this is an oversight on our part.
This PR allows field groups the ability to specify i18n titles, in the same way that certain other schema level properties can (sort orders, for instance).
Additionally, it introduces a new i18n key: `inputs.object.field-group-tabs.all-fields-title` - which is used by the default "All fields" group.
- The studio builds as before
- Navigating to the new "[field groups with i18n](https://test-studio-git-fix-i18n-all-fields-title.sanity.build/test/structure/input-debug;field-groups;fieldGroupsWithI18n;5bdf0fb2-84ae-4fbe-b0e7-717681ef8e11)" debug type should show three field groups; `🇺🇸 Group 1` (translated through `i18n.title`), `intentionally-missing-key` (defined through `i18n.title`, but does …
=> fix(i18n): allow locale plugins to translate "All fields" field group

dev/design-studio/package.json, dev/embedded-studio/package.json, dev/studio-e2e-testing/package.json, dev/test-studio/package.json, examples/ecommerce-studio/package.json, packages/@sanity/vision/package.json, packages/sanity/package.json, pnpm-lock.yaml
Bumps sanity ui to 2.6.7 to prevent a regression that was introduce in previous sanity ui version. See https://github.com/sanity-io/ui/pull/1372
Do the e2e tests pass now?
This bump was a simple revert so if the e2e tests, we should be good!
N/A
=> fix(deps): bump @sanity/ui ^2.6.7

packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx, packages/sanity/src/ui-components/menuItem/MenuItem.tsx, packages/sanity/src/ui-components/tooltip/Tooltip.tsx, test/e2e/tests/document-actions/publish.spec.ts
Seems the facelift PR caused a regression that basically reverted [this PR](https://github.com/sanity-io/sanity/pull/5065) in terms of end result.
This PR reverts to using the `<Hotkeys>` component from the sanity core, which is platform aware.
- Shows `Ctrl + Option + P` on publish and similar, when on Mac
- Shows `Ctrl + Alt + P` on publish and similar, when _not_ on Mac
(This should be uncovered by the test suite, fwiw)
I added one test for this in the publish action. Ideally I would test all the different locations that use any kind of hotkeys that _may_ involve the `Alt` key, but that would be a lot of tests in a lot of different places. I may introduce an ESLint rule to disallow the use of `<Hotkeys>` from `@sanity/ui` later.
- Fixes a regression causing platform-aware hotkeys not …
=> fix(core): restore platform-aware keyboard shortcuts

packages/sanity/src/core/bundles/components/BundleMenu.tsx, packages/sanity/src/core/bundles/components/__tests__/BundleMenu.test.tsx, packages/sanity/src/core/bundles/components/dialog/BundleForm.tsx, packages/sanity/src/core/bundles/components/dialog/BundleIconEditorPicker.tsx, packages/sanity/src/core/bundles/components/dialog/CreateBundleDialog.tsx, packages/sanity/src/core/bundles/components/dialog/__tests__/BundleForm.test.tsx, packages/sanity/src/core/bundles/components/dialog/__tests__/BundleIconEditorPicker.test.tsx, packages/sanity/src/core/bundles/components/dialog/__tests__/CreateBundleDialog.test.tsx, packages/sanity/src/core/bundles/index.ts, packages/sanity/src/core/bundles/util/__tests__/createWrapper.tsx, packages/sanity/src/core/bundles/util/tests/createWrapper.tsx, packages/sanity/src/core/releases/tool/__tests__/ReleasesOverview.test.tsx, packages/sanity/test/testUtils/TestProvider.tsx
- Add createWrapper in core (with resource options)
- Add bundleForm test
- Add BundleIconEditorPicker test
- Add createBundleDialog test
- Add BundleMenu test
- Replace createWrapper in the releases tool with the new one.
Left some components out since they were either:
- Too simple / UI focused
- Will eventually change
- Make sure that the changes to the releases plugin makes sense
A lot of these were taken with inspiration from the tests that Jordan has been writing, so thank you 🙏 🥺
=> test(COREL): add core tests

packages/sanity/src/core/store/_legacy/document/document-pair/utils/isLiveEditEnabled.ts, packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
This is a temporary change that allows document versions to be viewed and edited. It works by modifying `DocumentPaneProvider` to treat the version document (e.g. `someVersion.x`) as a published document in live edit mode if a bundle is checked out *and* the document being viewed exists in that bundle.
This is not the proper solution—hence `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED_LIVE_EDIT_OVERRIDE`—and should be reverted (and ideally the commit removed altogether) once we have a better one in place.
Note: the appearance of the "live" badge in the document pane footer lags. To be precise, it seems to reflect the last viewed document rather than the one currently being viewed. I think we can ignore this for now. The live edit functionality itself works as intended.
=> feat(sanity): #TEMPORARY #DELETE handle versions in `DocumentPaneProvider`

packages/sanity/src/core/bundles/components/panes/BundleActions.tsx
I know this code is temporary, but I noticed it seems to be fetching repeatedly the entire time it's mounted. Here's a tiny 🤏 bandaid to stop that.
=> fix(sanity): avoid fetching in a loop

.github/workflows/e2e-ui.yml, .gitignore, package.json, pnpm-lock.yaml
This PR adds a new workflow action that allows the `@sanity/ui` repo to run the Playwright tests defined in this repo, with changes to `@sanity/ui` that isn't published yet.
Example PR on the other side: https://github.com/sanity-io/ui/pull/1377
=> chore: setup workflow for E2E tests that `@sanity/ui` can run on its PRs

dev/test-studio/preview/FieldGroups.tsx, dev/test-studio/preview/main.tsx, dev/test-studio/schema/debug/fieldGroupsWithFieldsetsHidden.js, dev/test-studio/schema/index.ts, dev/test-studio/structure/constants.ts, packages/sanity/src/core/form/store/utils/__tests__/immutableReconcile.test.ts, packages/sanity/src/core/form/store/utils/getExpandOperations.ts, packages/sanity/src/core/form/store/utils/immutableReconcile.ts
For context, this PR is to resolve issues largely reported by Presentation users. I believe the same issue affects the Structure tool, but is far less visible as this is a less common scenario and largely non-critical in that context.
In summary: `setOpenPath` in the `DocumentPaneProvider` fails to focus the specified field if it exists in non-default groups or collapsed fieldsets.
This is because `getExpandOperations` is not returning the expected operations, which in turn seems to be because `immutableReconcile` drops the `_allMembers` property of the form state as it currently only handles enumerable properties (and `_allMembers` is explicitly set to non-enumerable).
There is also a small change to `getExpandOperations` as I believe the `setSelectedGroup` operation was returning the …
=> fix(sanity): open correct groups and fieldsets on `setOpenPath`

examples/ecommerce-studio/package.json, package.json, packages/@sanity/vision/package.json, packages/sanity/package.json, pnpm-lock.yaml, test/setup.ts
It seems like the reason the #7165 test suite is failing is because a lot of tests call `jest.resetAllMocks()`, and since the `matchMedia` mock uses `jest.fn().mockImplementation` it leads to the implementation later becoming `() => undefined` when it should always be `(query: string) => ({matches: false, media: query, onchange: null, ...rest})`
Closes #7165
=> fix(deps): update dependency @sanity/ui to ^2.7.0

packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/delete.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/discardChanges.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/publish.ts, packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/unpublish.ts, packages/sanity/src/core/store/_legacy/document/document-pair/utils/actionsApiClient.ts, packages/sanity/src/core/store/_legacy/history/createHistoryStore.ts
We observed that some Studios use an inadequate API version when calling the Actions API. It may be the case that developers are inadvertently mutating the client configuration object, however, we aren't certain. This change attempts to resolve the issue by explicitly setting all Actions API requests to use the minimally adequate API version.
When performing actions on a document while the Actions API integration is enabled, the API requests produced should be exactly the same as before, but always use the minimally adequate API version (`2024-05-23`).
I have not added tests, because we have not been able to replicate a scenario in which the API version used is anything other than the one required. For this change, I believe the existing tests are sufficient.
=> fix(sanity): ensure Actions API client uses adequate API version

packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveMenu.test.tsx
sanity import was being mocked in `DocumentPerspectiveMenu`, but `createWrapper` therefore wasn't available.
This PR uses the actual sanity package and mocks additions
N/A
=> fix: document perspective menu test fix

packages/@repo/package.bundle/.depcheckrc.json, packages/@repo/package.bundle/src/package.bundle.ts, packages/@sanity/vision/package.bundle.ts
This pull request addresses an issue where the sanity build with auto-update was breaking the sanity presentation. The issue was due to the package bundle configuration not including externals. The changes introduced include adding externals to the build configuration for the sanity module, ensuring that external dependencies are properly handled in the import map. This resolves the issue of the presentation tool crashing.
The reviewer should:
1. Review the changes made to the build configuration, specifically the inclusion of externals.
2. Verify that the local setup with the module server and localhost URLs is correctly implemented.
3. Test the presentation tool to ensure it no longer crashes with the new configuration.
4. Consider the architectural suggestion regarding the handling of …
=> fix: unify externals in auto-updating builds

packages/sanity/package.json, packages/sanity/src/_internal/cli/server/__tests__/aliases.test.ts, packages/sanity/src/_internal/cli/server/aliases.ts, packages/sanity/src/_internal/cli/server/getViteConfig.ts, pnpm-lock.yaml
This pull request enhances the `sanity` React library's build tooling by adding comprehensive comments and JSDoc annotations to improve maintainability and understanding of the code. Specifically, it elaborates on package exports, conditions, and the `getAliases` function. Additionally, it completes the associated test file to ensure the `getAliases` function operates correctly in both monorepo and normal build scenarios.
**Key changes:**
- Added detailed comments and JSDoc annotations to `aliases.ts` to explain the purpose and functionality of the code.
- Completed the test file `aliases.test.ts` with test cases for normal builds and monorepo builds.
- Mocked monorepo development aliases in the test to ensure accurate alias resolution.
**Why these changes were introduced:**
- To prevent …
=> feat(core): add aliases to mitigate context issues

packages/sanity/src/core/components/previewCard/PreviewCard.tsx, packages/sanity/src/core/field/diff/components/FieldChange.tsx, packages/sanity/src/core/field/types/portableText/diff/components/Annotation.tsx, packages/sanity/src/core/field/types/portableText/diff/components/InlineObject.tsx, packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/VirtualizerScrollInstanceProvider.tsx, packages/sanity/src/core/scheduledPublishing/tool/contexts/schedules.tsx, packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrialProvider.tsx, packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/datePicker/calendar/Calendar.tsx, packages/sanity/src/core/tasks/__workshop__/TasksCreateStory.tsx, packages/sanity/src/core/tasks/context/navigation/TasksNavigationProvider.tsx
All the React Context Providers in this PR suffers from the same problem:
- Each time react renders the `value` prop is given a new object.
- Since the object has a new referential identity, all related `useContext` hooks will also rerender.
- This happens regardless of any object properties in `value` has actually changed and dramatically increases unnecessary rerenders.
There are two ways to combat this:
1. Have multiple context providers, for the same reasons you'd rather have multiple `useState` hooks instead of cramming everything into a single `useState` hook, React performs far better with a large amount of contexts that are small and individually change infrequently [(the react docs touches about this briefly, and its example splits up the state and dispatcher in separate …
=> fix: ensure context provider values are memoized

packages/sanity/src/core/releases/tool/detail/ReleaseReview.tsx, packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseReview.test.tsx, packages/sanity/src/core/releases/tool/detail/review/DocumentDiffContainer.tsx
Adds search input to review changes screen.
This search is using the preview values to search in the document, using only the document title. 
Is a low effort implementation, further implementation to be discussed if we want to use the seach api once text search lands.
---
=> feat(corel): add search input to release review screen

dev/test-next-studio/next.config.mjs, dev/test-next-studio/turbo.json, dev/test-studio/sanity.cli.ts, dev/test-studio/turbo.json
This PR enables using the React Profiler on the production build of the studio.
In other words, instead of seeing this message on preview deployments [(like for this branch)](https://test-studio-git-react-production-profiling.sanity.build/test/structure):
You'll be able to run the profiler:
The main benefit of running the profiler in production, is that the perf overhead in React from running Strict Mode, as well as all the checks and instrumentation that is only used in local development (Hot Module Reload, checking if `key` is spread to attributes, checking if you're trying to set dom attributes that don't exist etc), all of that no longer interferes with the profiling results.
Additionally, since the regular components debugger is often used in conjunction with the profiler, I've made …
=> chore: enable production react profiling in test studios

packages/sanity/src/core/studio/StudioProvider.tsx, packages/sanity/src/core/studio/workspaces/WorkspacesProvider.tsx
Since `WorkspacesLoader` runs `prepareConfig` during render, without using React Suspense features, it winds up blocking render for quite some time on the first render of the Studio:
You can repro this yourself here: https://test-studio-git-add-profiling-script.sanity.build/test/structure
By pressing "Reload and start profiling":
After scheduling it to run in a passive effect React is able to render the initial loading far more efficiently:
You can load up these profiles yourself in the React Profiler to compare the before and after:
[before.workspaces.provider.fix.json.zip](https://github.com/user-attachments/files/16335990/before.workspaces.provider.fix.json.zip)
[after.workspaces.provider.fix.json.zip](https://github.com/user-attachments/files/16335994/after.workspaces.provider.fix.json …
=> fix(WorkspacesProvider): run `prepareConfig` in a passive effect

dev/test-studio/turbo.json, package.json
Run `pnpm dev:test-studio-production-profiling` to have a production build of the test studio on http://localhost:3333 that supports the React Profiler devtools :)
It's important to note that this mode does not have Hot Module Reloading, you'll need to restart the process when you make changes for them to apply 🙌
=> chore: add `dev:test-studio-production-profiling` script

packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx
In embedded studios, we noticed that not all document operations being sent were going to the chosen workspace's dataset. While there's a very specific set of conditions that might cause this issue, it is potentially destructive. 
Although we don't believe any customers have been affected by this, out of an abundance of caution, we felt it better to ensure context was entirely refreshed between workspaces by using an anchor link to switch between them instead.
This does add to increased friction in changing between workspaces in the studio, but we hope to resolve this soon by addressing the underlying issue -- this is a temporary fix.
The changed file is pretty minimal -- please ensure that functionality remains the same.
As mentioned above, the conditions that caused the leaky mutations …
=> fix(core): use anchor link to switch between datasets

packages/sanity/src/core/bundles/hooks/useDocumentVersions.tsx
Fixes an issue that is crashing the Form when removing a document and making tests fail. 
The return value of the `useVersionDocument` hook was. `{data: [undefined]}` and this is making the ui crash because it doesn't handle undefined values inside the array of bundles
=> fix(core): update useDocumentVersions to restore breaking tests

packages/sanity/src/core/bundles/util/util.test.ts, packages/sanity/src/core/bundles/util/util.ts, packages/sanity/src/core/components/documentStatus/DocumentStatus.tsx, packages/sanity/src/core/components/documentStatusIndicator/DocumentStatusIndicator.tsx, packages/sanity/src/core/index.ts, packages/sanity/src/core/releases/tool/detail/documentTable/useReleaseHistory.ts, packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx
It adds to `core` a new function `getDocumentIsInPerspective` which can be used to know when a document belongs to the current perspective.
```
- document: `summer.my-document-id`, perspective: `bundle.summer` : **true**
- document: `my-document-id`, perspective: `bundle.summer` : **false**
- document: `summer.my-document-id`perspective: `bundle.winter` : **false**
- document: `summer.my-document-id`, perspective: `undefined` : **false**
- document: `my-document-id`, perspective: `undefined` : **true**
- document: `drafts.my-document-id`, perspective: `undefined` : **true**
```
It uses that function in `PaneItemPreview` to create a distinction between documents that are part of the release or not.
Tests included for the new function added.
=> fix(structure): update PaneItemPreview to reflect when a document is in the current perspective

jest.config.cjs, packages/sanity/jest.config.cjs, packages/sanity/src/_internal/cli/actions/schema/__tests__/formatSchemaValidation.test.ts, packages/sanity/src/_internal/cli/jest.config.cjs, packages/sanity/tsconfig.json, packages/sanity/tsconfig.lib.json, packages/sanity/tsconfig.tsdoc.json, test/config.cjs
This PR introduces updates to the Jest configuration to align the environment settings with the CLI environment, which is a Node.js environment, instead of the previous browser-like environment. The key changes include:
- Updating the Jest configuration files to use `node:path` instead of `path`.
- Refactoring the way Jest config files are globbed to find all `jest.config.cjs` files instead of just the ones in workspaces.
- Adding new Jest configuration for the CLI within the `sanity` package.
- Adjusting TypeScript configuration files to exclude `jest.config.cjs` files from certain processes for the build
These changes are necessary to ensure that tests are running in the correct environment, reflecting the actual usage scenario of the new CLI. This is a prerequisite for another PR that …
=> test: adds jest config for CLI tests within the `sanity` module

packages/sanity/src/core/store/bundles/__workshop__/BundlesStoreStory.tsx
HOC WithAddonDatasetProvider is read as a component instead of a HOC because it starts with a capital letter, so react compiler exposes an error because of the name mutation.
Changing the `WithAddonDatasetProvider` to lowercase `withAddonDatasetProvider` fixes the issue
[
](url)
=> fix(core): fix lint warning in WithAddonDatasetProvider

package.json, packages/sanity/src/core/bundles/components/BundleBadge.tsx, packages/sanity/src/core/releases/components/BundleMenuButton/BundleMenuButton.tsx, packages/sanity/src/core/releases/components/ReleaseDocumentPreview.tsx, packages/sanity/src/core/releases/components/ReleasePublishAllButton/ReleasePublishAllButton.tsx, packages/sanity/src/core/releases/components/ReleasePublishAllButton/useObserveDocumentRevisions.ts, packages/sanity/src/core/releases/components/Table/Table.tsx, packages/sanity/src/core/releases/tool/detail/ReleaseDetail.tsx, packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx, packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx, packages/sanity/src/core/releases/tool/detail/documentTable/DocumentActions.tsx, packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx, packages/sanity/src/core/store/bundles/useBundleOperations.ts
Clicking 'Publish all' on a release with all valid documents will not publish the version documents, and update the bundle metadata with the publish date
https://www.loom.com/share/94911ea76b484457aca3ffa31ceca78f?sid=1851e5b8-fb86-4052-ae3f-0ff9958b97e8
* Presence added to `ReleaseDocumentPreview`
* `handlePublishBundle` added to `useBundleOperations`
* validation of documents used to control disabled state of publish all in `ReleaseDetail`
* Tests in `ReleaseDetail.test` updated for new publish all calls
N/A
=> feat(releases): publish all documents in a bundle

packages/sanity/src/core/bundles/components/panes/BundleActions.tsx, packages/sanity/src/structure/panes/document/DocumentPaneContext.ts, packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveMenu.tsx, packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
This moves the invocation of `useDocumentVersions` to the PaneProvider, deduplicating it invocation and making it available for any consumer inside the Pane.
=> chore(structure): move useDocumentVersions to PaneProvider

packages/sanity/src/core/preview/createGlobalListener.ts, packages/sanity/src/core/preview/documentPreviewStore.ts
Note: I've left fixup! in the commit/PR title so it can be squashed with the earlier commit at next rebase of this branch
Note2: also snuck in a [tiny fix](https://github.com/sanity-io/sanity/pull/7246/commits/333ee5861dbf8ffcddd273e484f0d003cd3e3c1a) that caused previews always to show "Undefined" when there was only a published version
#7176 introduced a regression in that the `welcome`-event would not be emitted to new subscribers of the preview listener, causing previews to show the loading skeleton infinitely. This PR refactors the preview listener event stream so that:
- The `welcome` is emitted immediately to new subscribers. This is typically when downstream subscribers will do the initial fetch
- In case of a connection loss (e.g. the last connection event was `reconnecting`, the …
=> fixup! feat(preview): add `unstable_observeDocument(s)` to preview store (#7176)

packages/sanity/src/core/bundles/components/BundleBadge.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveMenu.test.tsx
With the introduction of https://github.com/sanity-io/sanity/pull/7237 the DocumentPerspectiveMenu tests failed and it was not detected on time.
This PR updates those tests to pass
It also updates the `BundleBadge` to use a styled component to define it's styles instead of inline styles, not specifically related to this PR but caught that while reviewing the changes needed for the tests.
Are the changes correct? 
Tests have been updated to pass
=> fix(structure): update DocumentPerspective menu test

packages/sanity/package.json, packages/sanity/src/core/preview/createObserveDocument.ts, packages/sanity/src/core/preview/documentPreviewStore.ts, packages/sanity/src/core/preview/liveDocumentIdSet.ts, packages/sanity/src/core/preview/useLiveDocumentIdSet.ts, packages/sanity/src/core/preview/useLiveDocumentSet.ts, pnpm-lock.yaml
Adds a new (unstable) method to the preview store that supports subscribing to a set of document ids that matches a given groq-filter. The set of document ids are returned in ascending order and will update in real-time as documents appear or disappear from the set.
A query based on the given filter is performed once, initially, and thereafter the set of ids are patched based on the listener events `appear` and `disappear` transition.
This provides a lightweight way of subscribing to a list of ids for simple cases where you just want to subscribe to a set of documents ids that matches a particular filter.
- Implementation and accompanying hooks
TBD
n/a - internal (for now)
=> feat(preview): add support for live document id sets

package.json, packages/sanity/src/_singletons/core/releases/ReleasesTableContext.ts, packages/sanity/src/core/bundles/components/panes/BundleActions.tsx, packages/sanity/src/core/releases/components/Table/Table.tsx, packages/sanity/src/core/releases/components/Table/TableHeader.tsx, packages/sanity/src/core/releases/components/Table/TableProvider.tsx, packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx, packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx, packages/sanity/src/core/store/bundles/reducer.ts
This PR sorts the list of documents in a bundle by default to show most recent first. This way, when new releases are created they immediately appear at the top of the list, rather than being added at the bottom
* possible to now set a default sort col and direction on the `Table`
* Updated a mis-named setter
* Updated the `ReleaseSummary` tests
=> feat(releases): default sorting version documents in release

packages/sanity/src/core/bundles/hooks/__tests__/useDocumentVersions.test.tsx, packages/sanity/src/core/bundles/hooks/useDocumentVersions.tsx
refactor useDocumentVersion to use `ListenQuery` observable. 
Existing tests updated and new tests added.
=> chore(core): refactor useDocumentVersion to use ListenQuery

packages/sanity/src/core/bundles/components/BundleMenu.tsx, packages/sanity/src/core/bundles/components/__tests__/BundleMenu.test.tsx
The bundles menu component was showing an unnecessary divider when the bundles are archived.
Archived bundles are not rendered, but they were not considered for the `hasBundles` check.
By moving the list that is generated to the body of the component and reusing that to check the bundles length this issue is fixed.
Tests are updated.
=> fix(core): unify items to render in BundlesMenu

packages/sanity/src/_internal/cli/server/__tests__/aliases.test.ts, packages/sanity/src/_internal/cli/server/aliases.ts, packages/sanity/src/_internal/cli/server/getViteConfig.ts
The following PR removes the [`conditions`](https://vitejs.dev/config/shared-options#resolve-conditions) configuration in the `getViteConfig` function in order to preserve previous behavior.
The `conditions` configuration appears to have caused an issue with a third-party dependency, resulting in Vite failing to start properly due to incorrect interoperability with a CJS module.
Make sure I didn't miss anything.
I removed this configuration in a reproduction that involved the third-party plugin `sanity-plugin-icon-picker` and it seemed to work as normal.
- Resolves a build configuration issue that led to interoperability problems with CJS modules, causing the error `Uncaught error: _interopRequireDefault2 is not a function`.
=> fix(cli): remove `conditions` to prevent CJS interop errors

packages/sanity/src/core/presence/FieldPresence.tsx
Fixes #7261. Some third party plugins rely on this export. The `FieldPresence` and `FieldPresenceWithOverlay` have always been identical, but the theory is that the naming have created the assumption that `FieldPresence` doesn't implement presence overlays, leading third party plugin authors to import `FieldPresenceWithOverlay`.
This PR adds it back, with a TSDOC `@deprecated` tag noting that `FieldPresence` should be used instead. It also has `@hidden` so that it's excluded from the generated API docs.
I've only added back `FieldPresenceWithOverlay`. The original PR (#6946) also removed `EnabledChangeConnectorRoot`, but I'm not adding it back here as its name isn't as ambiguous as `FieldPresenceWithOverlay` and it's usage is far less likely from third parties than `FieldPresence` is.
The …
=> fix: add back `FieldPresenceWithOverlay` export

packages/sanity/src/core/bundles/components/dialog/BundleDetailsDialog.tsx, packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx, packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx, packages/sanity/src/core/releases/tool/useBundlesMetadata.ts, packages/sanity/src/core/store/_legacy/datastores.ts, packages/sanity/src/core/store/bundles/createBundlesMetadataAggregator.ts, packages/sanity/src/core/store/bundles/createBundlesStore.ts, packages/sanity/src/core/store/bundles/useBundleOperations.ts
This PR introduces two changes:
- Fixes an issue in which it was not possible to open releases in workspaces with no bundles previously created
- Adds the ability to create the addon dataset, when creating a bundle, if it doesn't exist. 
https://www.loom.com/share/f8b6bf115a8e40ad89e82feee3e1635d?sid=8714f116-7be3-4b91-a26d-3a9ae51ba082
=> feat(core): fix infinite loading in releases and create addon dataset if it doesn't exist

packages/sanity/src/core/form/inputs/common/fileTarget/fileTarget.tsx, packages/sanity/src/core/hooks/useGlobalCopyPasteElementHandler.ts
This PR fixes a bug where the new copy/paste paste-handler would prevent the paste handler in image and file inputs from firing.
This PR introduces a data attribute that is used by the copy/paste handler in order to early return and not call `event.preventDefault`.
Review the approach and let me know if you can think of a better mechanism.
Tested manually in the test studio. This needs a better automated test in the future.
- Fixes a bug that prevents keyboard shortcuts from pasting images and files.
=> fix(core): early return if paste target is a file/image

dev/embedded-studio/package.json, dev/test-next-studio/package.json, package.json, packages/@sanity/block-tools/package.json, packages/@sanity/cli/package.config.ts, packages/@sanity/mutator/package.json, packages/@sanity/types/package.json, packages/@sanity/types/src/schema/definition/type/array.ts, packages/@sanity/types/test/date.test.ts, packages/@sanity/types/test/datetime.test.ts, packages/@sanity/types/test/image.test.ts, packages/sanity/package.json, packages/sanity/src/core/i18n/hooks/useTranslation.ts, packages/sanity/src/core/studio/StudioThemeProvider.tsx, packages/sanity/src/core/tasks/components/activity/TasksActivityCreatedAt.tsx, packages/sanity/src/core/validation/Rule.ts, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTabs.tsx, perf/tests/package.json, pnpm-lock.yaml
Bumps `@sanity/pkg-utils` from `v6.9` to `v6.10`.
Doing so allows us to bump `typescript` from `v5.4` to `v5.5` as well, allowing us to get rid of a `@ts-expect-error` line.
In `v6.10` the `extract.bundledPackages` API in `@sanity/pkg-utils` are automatically populated by dependencies that are in `devDependencies`, and not in `peerDependencies`.
In most cases that's what you want, as it ensures the generated typings play the same rules as the default bundling. It removes the ability to have accidental implicit dependencies that only apply to typings, while the compiled JS is bundled/inlined.
Since the new `@sanity/pkg-utils` has a different default setting for `extract.bundledPackages` there is a small risk for unintended changes to the generated typings we publish to npm.
Therefore I …
=> fix(deps): bump `@sanity/pkg-utils` to `v6.10.7`

packages/@sanity/cli/src/actions/init-project/initProject.ts, packages/@sanity/cli/src/actions/init-project/prompts/nextjs.ts, packages/@sanity/cli/src/actions/init-project/templates/nextjs/index.ts, packages/@sanity/cli/src/actions/init-project/templates/nextjs/schemaTypes/blog.ts
* Adds icons to the `blog` template schema types
* Installs `@sanity/icons` as a dependency when using the `blog` template
* Uses `defineType/Field` functions in both JS and TS schema type files of the `blog` template
* Adds default structure builder configuration to `blog` and `clean` templates
* Sets `blog` template as the default when `init` is run inside a Next.js app
=> feat: embellish nextjs blog starter

.npmrc
Looks like some of the options we set doesn't play too nice with `pnpm dedupe`, as seen in https://github.com/sanity-io/sanity/pull/7281.
I've removed them and set us to trust the defaults, except for `prefer-workspace-packages` and `link-workspace-packages = deep` as they make a lot of sense for our monorepo setup.
It makes sense?
Existing tests should be enough. I ran `pnpm dedupe && pnpm install --fix-lockfile` locally before pushing.
N/A
=> chore: remove agressive npmrc options

packages/sanity/src/core/studio/components/navbar/search/components/common/SearchWrapper.tsx, packages/sanity/src/core/studio/components/navbar/search/contexts/search/SearchProvider.tsx
Relates to #7199, read its description for all the deets. The SearchProvider warrants its own PR since it required more work than simply wrapping the context value in a `useMemo`.
If you can click outside the global search and it closes successfully then it works 🎉 
N/A
=> fix: ensure search context provider value is memoized

dev/test-studio/sanity.config.ts
Adds a US-based dataset so it is easier to test things like latency etc
See that there are requests going to the `test-us` dataset when selecting the US workspace
👆
None.
=> chore(test-studio): add workspace for us based dataset

packages/@sanity/cli/src/actions/init-project/initProject.ts
You can init a new Sanity project to just create an .env file like so
```
npx sanity init --env
```
But you can also stipulate the name of the file, like
```
npx sanity init --env=.env.local
```
Currently we always prepend a message in the file about using an `.env.local` file instead for secrets, which is confusing if that's exactly what you **are** creating.
Fixed default messaging in `.env` file created by `sanity init --env` if creating a `.env.local` file
=> don't prepend message about .env.local if creating .env.local

packages/sanity/src/core/form/inputs/PortableText/Editor.styles.tsx
I was reading the docs on [`counter-reset`](https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset#description) when this paragraph suddenly stood out:
> After creating a counter using `counter-reset`, you can adjust its value by
> using the `counter-set` property. This is counterintuitive because, despite
> its name, the `counter-reset` property is used for creating and initializing
> counters, while the `counter-set` property is used for resetting the value
> of an existing counter.
This made me realise that we probably used `content-reset` somewhere, incorrectly, where we actually meant to use `counter-set`.
Before this change, counters on each list level would not reset at all across a PTE document. Now, the counters reset properly.
Before:
```
1. This
a. is
i. nested
1. list …
```
=> fix(core): correctly reset PTE list counts

packages/sanity/src/core/preview/createGlobalListener.ts, packages/sanity/src/core/preview/documentPreviewStore.ts
This was an interesting thing to explore, but it doesn't scale well, so turning this off for now (it's only been enabled in this branch, fwiw).
=> fix(preview): remove full document preview support

packages/@sanity/cli/src/actions/typegen/generateAction.ts, packages/@sanity/cli/src/workers/typegenGenerate.ts, packages/@sanity/codegen/src/readConfig.ts, packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts, packages/@sanity/codegen/src/typescript/__tests__/typeGenerator.test.ts, packages/@sanity/codegen/src/typescript/expressionResolvers.ts, packages/@sanity/codegen/src/typescript/findQueriesInSource.ts, packages/@sanity/codegen/src/typescript/typeGenerator.ts, packages/groq/README.md, packages/groq/package.config.ts, packages/groq/package.json, packages/groq/src/_exports.cts.ts, packages/groq/src/_exports.mts.ts, packages/groq/src/define.ts, packages/groq/src/groq.ts, packages/groq/test/define.test.cjs, packages/groq/test/define.test.mjs
This PR is just forwarding #6997 by @romeovs (with help from @sgulseth ), so that we can run all the CI testing flows that otherwise are skipped/fail on PRs from forked branches.
Check #6997 for all the deets, the gist of it is that it allows typegen that are much more ✨ **_magical_** ✨ and **easier** to use.
Today typegen requires you to instrument your `client.fetch` calls with the generated query response:
```tsx
import {createClient} from '@sanity/client'
import groq from 'groq'
// You have to manually import from the generated `sanity.types.ts` file
import type { SettingsQueryResult } from "~/sanity.types";
const client = createClient({ /* ... */ })
const settingsQuery = groq`*[_type == "settings"][0]`
// And also manually add the type for the response to the generic slot in …
```
=> feat(codegen): generate SanityQueries interface in @sanity/codegen

packages/sanity/src/_internal/cli/server/getViteConfig.ts
This PR supersedes #7298 in favor of just adding `styled-components` into the vite's `resolve.dedupe` option.
- Tested this out in the test studio and vision no longer crashes due to two versions of styled-components.
- Also tested this out in our admin studio and it built with no issues.
- Dedupes `styled-components` in our build config to prevent errors related to different context instances.
=> fix(cli): dedupe `styled-components` in vite config

packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
With #7302 `@sanity/presentation` now takes full ownership of how it opens the "latest published" document when needed, and no longer use or need the `prefersLatestPublished` parameter and its related handling in the Studio core 😌 
This param was always something that were implement only for usage in `@sanity/presentation`, with the intention of it to be a temporary escape hatch. Removing it doesn't affect the public API in any way and isn't considering a breaking change.
`sanity/presentation` has always been using a pinned version of `@sanity/presentation` to allow us to do these kinds of cleanups and internal changes.
This can be tested [manually in the Presentation Studio](https://test-studio-git-preferslatestpublished.sanity.dev/presentation/presentation/simpleBlock/eed1de44-4731-48f5- …
=> refactor: remove `prefersLatestPublished` handling

packages/sanity/src/core/presence/overlay/WithIntersection.tsx
[In React 19 it's possible to set a `ref` as a prop](https://react.dev/blog/2024/04/25/react-19#ref-as-a-prop), while in React 18 you must implement `React.forwardRef` for this.
Components that implement `React.forwardRef` isn't impacted by this change, and won't see that `ref` exists as a prop. But for components like `WithIntersection`, it's now important to have the right order when setting refs and spreading props:
```tsx
export default function Component(props) {
// On React 19 this ref is never set
const ref = useRef()
return <div ref={ref} {...props} />
}
```
On React 18 this is fine, because `<Component ref={123} />` won't result in `props` containing `ref={123}`.
On React 19 it's not, because not only is `<Component ref={123} />` now possible and will result in `props.ref=123`, …
=> fix: support field presence avatars on react 19

packages/@sanity/migrate/src/it-utils/__test__/decodeText.test.ts, packages/@sanity/migrate/src/it-utils/decodeText.ts
=> fix(migrate): properly decode chunks of multibyte unicode strings

packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts, packages/@sanity/codegen/src/typescript/expressionResolvers.ts, packages/@sanity/codegen/src/typescript/findQueriesInSource.ts
Adds a location object to the discovered queries, this is practical when using codegen to parse a source file and find location of queries. Ie in vscode-sanity
Does the start/end interface make sense?
Added
N/A - no notes needed
=> feat(typegen): add location of discovered query

packages/sanity/src/_internal/cli/actions/deploy/__tests__/deployAction.test.ts, packages/sanity/src/_internal/cli/actions/deploy/__tests__/helpers.test.ts, packages/sanity/src/_internal/cli/actions/deploy/deployAction.ts, packages/sanity/src/_internal/cli/actions/deploy/helpers.ts
Doesn't create default apps on new CLI version. DM for more context if needed
Changes make sense, there shouldn't be any instance of `isDefaultForDeployment` 
Updated
N/A
=> fix(cli): don't create default apps on deploy

packages/sanity/src/_internal/cli/actions/deploy/__tests__/deployAction.test.ts, packages/sanity/src/_internal/cli/actions/deploy/__tests__/helpers.test.ts, packages/sanity/src/_internal/cli/actions/deploy/deployAction.ts, packages/sanity/src/_internal/cli/actions/deploy/helpers.ts
Handles known error codes and responds with proper error message
Added test for 402 status code
N/A
=> feat(cli): handle error statusCode from API

packages/sanity/src/core/preview/constants.tsx, packages/sanity/src/core/preview/createGlobalListener.ts, packages/sanity/src/core/preview/documentPreviewStore.ts, packages/sanity/src/core/preview/utils/replayLatest.test.ts, packages/sanity/src/core/preview/utils/shareReplayLatest.ts
fixes a regression introduced earlier in this branch (49591de54dc3788ddd3f97cfa7b9a4168f37362c to be specific) - where previews would sometimes stall. This PR fixes the issue by implementing a [share](https://rxjs.dev/api/operators/share)-based operator function that re-emits the latest event matching the provided predicate.
Does the naming make sense?
- Added unit tests with the `shareReplayLatest` operator
n/a – internal
=> fix(preview): fix bug with replaying of welcome event to new subscribers

dev/test-studio/schema/standard/portableText/customMarkers/schemaTypes.tsx
Before this change, annotations would not be properly rendered in the editor. Instead of rendering the text element, the form for editing the annotation was rendered in the editor. This is clearly not intended and causes Slate to blow up when you try to focus the rendered form.
---
Can be tested here: 
Annotated text before:
Annotated text now:
=> chore(test-studio): fix custom markers PTE example

dev/test-studio/documentActions/actions/createCustomPublishAction.ts, dev/test-studio/documentActions/index.ts, dev/test-studio/schema/debug/documentActions.js, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.test.ts, packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
This branch fixes an issue arising when Studio executes an empty array of actions using the Actions API. This usage is permitted by Content Lake, but is effectively a noop, with no transaction being executed and propagated through the system.
Although this scenario doesn't occur in Studio code, it can occur in user code. For example: if a custom document action patches a document, but the value it sets is unchanged from the current value. This can cause Studio to become stuck in a "saving" state, because it expected a transaction to be executed.
This branch fixes the issue by adding a fake `unset: ['_empty_action_guard_pseudo_field_']` patch when executing an array of actions that would otherwise be empty. This is similar to the approach employed elsewhere to emulate optimistic locking. …
=> fix(sanity): prevent empty actions being executed

packages/sanity/src/core/field/__workshop__/ChangeListStory.tsx, packages/sanity/src/core/field/__workshop__/ChangeResolverStory.tsx, packages/sanity/src/core/field/diff/contexts/DocumentChangeContext.tsx, packages/sanity/src/core/field/types/boolean/diff/BooleanFieldDiff.tsx, packages/sanity/src/core/field/types/image/diff/ImageFieldDiff.tsx, packages/sanity/src/core/releases/i18n/resources.ts, packages/sanity/src/core/releases/tool/detail/ReleaseReview.tsx, packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx, packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx, packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseReview.test.tsx, packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseSummary.test.tsx, packages/sanity/src/core/releases/tool/detail/documentTable/DocumentActions.tsx, packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx, packages/sanity/src/core/releases/tool/detail/review/DocumentDiff.tsx, packages/sanity/src/core/releases/tool/detail/review/DocumentDiffContainer.tsx, packages/sanity/src/core/releases/tool/detail/review/DocumentReviewHeader.tsx, packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts, packages/sanity/src/core/store/_legacy/__workshop__/HistoryTimelineStory.tsx, packages/sanity/src/structure/panes/document/inspectors/changes/ChangesInspector.tsx, packages/sanity/test/testUtils/TestProvider.tsx
This PR introduces some changes to address the use case of reviewing a new document in a release.
Replaces the `new document` view for a difference showing all the fields as added with the corresponding value.
To generate this difference it:
- Calculates the diff of the element with an empty object as initial value, all new fields will be calculated as "added".
- Adds new `showFromValue` property to the `DocumentDiff` context which will be used to define if the original value needs to be shown or not, some components, like the image, show an empty image placeholder when no initial `from` value is provided.
- Updates the necessary Diff components to check for the `showFromValue` and avoid rendering empty or placeholder values.
- Adds a `memoKey` property to the `BundleInDocumentResult` …
=> feat(core): document diff review for new documents

packages/sanity/package.json, packages/sanity/src/core/i18n/i18nConfig.ts, pnpm-lock.yaml
Our dependency for translations, `react-i18next` has an open performance regression caused by multiple re-renders from `useTranslation`
https://github.com/i18next/react-i18next/issues/1756
As one maintainer mentiones, this issue was fixed in version `14.0.2` of that library, a fix they later rolled back because it broke changing of languages at runtime:
https://github.com/i18next/react-i18next/issues/1756#issuecomment-2282227940
Since we currently do not support changing languages, I suggest we pin to `14.0.2` until the library is fixed properly in more current versions.
That the version we upgraded to is still compatible with the way we use their API. They seem to bump major versions for fixes and type changes.
https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md
I manually …
=> fix(deps): update and pin `react-i18next` to 14.0.2

packages/@sanity/schema/src/sanity/extractSchema.ts, packages/@sanity/schema/test/extractSchema/__snapshots__/extractSchema.test.ts.snap, packages/@sanity/schema/test/extractSchema/extractSchema.test.ts
It's possible to reference a document the same way as an object is referenced. However, they will not get the builtin attributes that are available on a document stored in Content Lake. The Studio treats it as a "normal" object. Since we are making some assumption around document we are inlining the whole object whenever this happens, it's an edge case and not a recommended pattern as it is mixing concerns.
Correctness. This change also changed a snapshot in the existing test. This is because the referenced block type from the fixture is using "author" as a inline type reference, but also using author as a reference.
Updated the current snapshots and added a specific test for inlined documents
TypeGen: Fixes an edge case where referencing documents with a normal "type"-reference, and not …
=> fix(typegen): dont treat all document type refs as references

.eslintrc.cjs, packages/sanity/src/core/form/studio/tree-editing/components/TreeEditingDialog.tsx, packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbs.tsx, packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenu.tsx, packages/sanity/src/core/form/studio/tree-editing/components/breadcrumbs/TreeEditingBreadcrumbsMenuButton.tsx, packages/sanity/src/core/form/studio/tree-editing/components/search/TreeEditingSearch.tsx, packages/sanity/src/core/form/studio/tree-editing/components/search/TreeEditingSearchMenu.tsx, packages/sanity/src/core/form/studio/tree-editing/components/tree-menu/TreeEditingMenuItem.tsx, packages/sanity/src/core/studio/packageVersionStatus/PackageVersionStatusProvider.tsx, packages/sanity/src/structure/panes/documentList/sheetList/ColumnsControl.tsx, packages/sanity/src/structure/panes/documentList/sheetList/DocumentSheetListHeader.tsx, packages/sanity/src/ui-components/tooltip/Tooltip.tsx
The existing eslint config is overriding the original `no-restricted-imports` rule.
When this rule was added:
```
'no-restricted-imports': [
'error',
{
paths: [
{
name: 'react',
importNames: ['createContext'],
message: 'Please place context in _singletons',
},
],
},
```
The previous rules stopped working.
- This PR introduces changes to make all the `no-restricted-imports` rules work at the same time.
- This PR also fixes the failing checks, by either importing the corresponding files or opting out where needed.
With the changes introduced, now we are seeing all the expected errors.
- Are this changes ok? 
- Is there any way to configure the eslint file to expose different error messages for React default import error and context error ?
- **Small caveat:** The error for "Please place …
=> fix(core): update eslintrc config to show no-restricted-imports rules

packages/sanity/src/core/store/_legacy/datastores.ts
The bundles store was added to the resource cache with a key that was not possible to recreate, given it was using an object created in place which gets a new identity every time a component invoque `useBundlesStore`.
```
dependencies: [workspace, addonClient, {addonClientReady: ready}]
// {addonClientReady: ready} is incorrect, the object is created in place so it has a new identity each time it is created
```
Generating in some cases hundreds of requests with the query `*[_type == "bundle"]`
By updating the dependencies to use **stable objects** this issue is fixed, and the store is created only once and the request is only triggered once.
=> fix(core): update cache dependencies for useBundlesStore

dev/test-studio/components/formBuilder/FormInputExample.tsx, dev/test-studio/schema/docs/v3/form-components-api/formInputTest.tsx, dev/test-studio/schema/docs/v3/form-components-api/index.ts, dev/test-studio/schema/docs/v3/index.ts, packages/sanity/src/core/form/components/FormInput.tsx
Currently using `FormInput` with `includeField` does not work for nested fields. This PR fixes the issue, and also adds proper support for `includeItem` so fields and array items works the same way.
Repro steps, current (broken) behavior:
- Go to the playground in the preview build _without_ the fix [here](https://test-studio-4orv430uh.sanity.dev/test/structure/v3;formInputTest;9108e390-aa8f-4ac4-ba1c-d655ddba7347)
- Scroll down to the `Nested` -> `Nested` field and click the "eye"-icon to put it in "attention mode"
- Then hit the "Include Field" checkbox
- Observe that the field is _not_ rendered (bad)
Repro steps with fix applied:
- Go to the playground in the preview build with the fix _included_ [here](https://test-studio-git-sdx-1527.sanity.dev/test/structure/v3;formInputTest;9108e390 …
=> fix(form): fix issue where FormInput was not rendering field when passed 'includeField'

packages/sanity/src/core/bundles/components/dialog/BundleDetailsDialog.tsx, packages/sanity/src/core/bundles/components/dialog/BundleForm.tsx, packages/sanity/src/core/bundles/components/dialog/__tests__/BundleDetailsDialog.test.tsx, packages/sanity/src/core/bundles/components/dialog/__tests__/BundleForm.test.tsx, packages/sanity/src/core/bundles/components/dialog/__tests__/useGetBundleSlug.test.ts, packages/sanity/src/core/bundles/components/dialog/getBundleSlug.ts, packages/sanity/src/core/bundles/components/dialog/useGetBundleSlug.ts
There are now no error states in the bundle form. If a protected title is entered, then a unique slug will still be generated (eg title of Published, will create slug of `published-1`). If a slug already exists, the the closest unique one will be used. This allows for bundles with identical titles to be generated
* new `useGetBundleSlug` hook that does the generation of slug from title
* Testing for `useGetBundleSlug`
* Updated tests for `BundleForm` and `BundleDetailsDialog`
* Trimming bundle title
Relevant tests added and updated. Tests related to asserting on showing form errors have been removed
N/A
=> feat(releases): suffix to bundle slug

packages/sanity/src/core/bundles/components/panes/BundleActions.tsx, packages/sanity/src/core/bundles/hooks/__tests__/useDocumentVersions.test.tsx, packages/sanity/src/core/bundles/hooks/useDocumentVersions.tsx, packages/sanity/src/core/bundles/util/util.test.ts, packages/sanity/src/core/bundles/util/util.ts, packages/sanity/src/core/preview/availability.ts, packages/sanity/src/core/preview/utils/getPreviewStateObservable.ts, packages/sanity/src/core/releases/components/ReleaseDocumentPreview.tsx, packages/sanity/src/core/releases/components/ReleasePublishAllButton/useObserveDocumentRevisions.ts, packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseReview.test.tsx, packages/sanity/src/core/releases/tool/detail/review/DocumentDiffContainer.tsx, packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts, packages/sanity/src/core/store/_legacy/document/document-pair/operations/newVersion.ts, packages/sanity/src/core/store/_legacy/document/useInitialValue.ts, packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts, packages/sanity/src/core/store/bundles/createBundlesMetadataAggregator.ts, packages/sanity/src/core/store/bundles/useBundleOperations.ts, packages/sanity/src/core/util/draftUtils.test.ts, packages/sanity/src/core/util/draftUtils.ts, packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx, packages/sanity/src/structure/panes/documentList/DocumentListPaneContent.tsx, packages/sanity/src/structure/panes/documentList/helpers.ts
- Change `newVersion` to use `versions.[bundle].[id]` vs `[bundle].[id]`
- Change `newVersion` to remove `_version`
- Update `getPublishedId`
- Update places where `_version` was being used
- Add `getVersionId` and `isVersionId`
- Remove `isVersion` parameter from `getPublishedId` (and update each location where it was used)
- Update areas where `getVersionId` / `isVersionId` makes sense to be used
- Update tests
❗ 
- Using an alternative groq to `versionsOf` since that changes hasn't landed in CL yet
- waiting for `versionsOf` to work with version.(bundle).(id)
- has _version removal landed?
- Did I miss anything? 
- Does the structure tool work as you'd expect?
- Does the linking documents in the release tool work as expected?
- Can you edit / see the right documents on the structure …
=> refactor(sanity): update version id to match `versions.[bundle].[id]`

packages/sanity/src/core/preview/availability.ts, packages/sanity/src/core/preview/constants.tsx, packages/sanity/src/core/preview/createGlobalListener.ts, packages/sanity/src/core/preview/createPathObserver.ts, packages/sanity/src/core/preview/createPreviewObserver.ts, packages/sanity/src/core/preview/documentPair.ts, packages/sanity/src/core/preview/documentPreviewStore.ts, packages/sanity/src/core/preview/observeFields.ts, packages/sanity/src/core/preview/types.ts, packages/sanity/src/core/preview/useValuePreview.ts, packages/sanity/src/core/preview/utils/getPreviewPaths.ts, packages/sanity/src/core/preview/utils/getPreviewStateObservable.ts, packages/sanity/src/core/preview/utils/prepareForPreview.ts, packages/sanity/src/core/preview/utils/shareReplayLatest.test.ts, packages/sanity/src/core/preview/utils/shareReplayLatest.ts
Note: This originally happened as part of work in a feature branch, but the changes here are generic and standalone improvements that makes sense to merge to main already.
This extracts the global listener used by the preview system, improves consistency and readability and typings of of the core/preview code. These changes should not affect the behavior of previews in any significant way or cause any visible differences in how previews work currently.
This also includes a small improvement to the global preview listener: Currently this listener is subscribed once, and the subscription is kept active forever. This means that if the user navigates to a part of the Studio that does need to preview anything, the listener connection is still kept active. With the changes proposed here, the …
=> refactor(preview): extract global listener, refactor preview APIs and improve typings

packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTitle.tsx
Before  
After (hovering over the title text)
- Double check the css makes sense
Manual testing
- When no global bundle: the drop arrow should be next to the title, the title should behave as normal (if it's short or long)
- With a global bundle but no version document: the drop down arrow should be next to the title 
- With a global bundle and document version selected: the drop down arrow and badge next to it, the title should behave as normal (ellipsing if it's too long). The whole content should be in the title
=> fix(sanity): update the title to be ellipsed when the text is too long 

packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts, packages/@sanity/codegen/src/typescript/findQueriesInSource.ts
Find queries imported with defineQuery from next-sanity
Any other packages we should detect?
Added 👍 
TypeGen: generate types defined by defineQuery from the next-sanity package
=> fix(typegen): find queries imported with defineQuery from next-sanity

packages/sanity/src/core/studio/components/navbar/resources/ResourcesMenuItems.tsx
We do not want to show the latest version label to those on auto-updating studios. There are a couple of scenarios in which the current text could be confusing:
1. If we are doing a gradual rollout -- the users may be in a bucket that does not allow them to upgrade to the "latest" version. 
2. If developers have pinned the studio version to a past version and again, the user does not have the power to update.
Any edge cases in which this may not be helpful.
I would like to test this! I am trying to reduce flakiness in our test suite so we can [run the entire suite against auto-updating studios](https://github.com/sanity-io/sanity/pull/7002). Once that is done, I will write a test for this as well!
=> fix: do not show latest version if auto-updating

scripts/generate-documents/run.ts
Small follow up from #7387 - the way a document was added to a bundle was based on the old way, this fixes it by prepending `versions.` to the id instead of writing to the `_version` property
n/a
n/a – internal
=> chore: fix wrong version format in generate documents script

packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx, packages/sanity/src/core/studio/copyPaste/utils.ts
This fixes a few issues related to copy paste:
Referenced could not open when you had a reference field inside a field group and was not on the All fields tab. The fix here was to remove the `onBlur` handler. I'm not entirely sure why this breaks inside a group, since I could only reproduce in a newly installed studio and not inside the monorepo.  Having a blur handler here is a footgun, and doesn't make sense given that we don't want to change the focused path until you click another field.
Fixes #7265
It was also not possible to copy selected text in a textarea, since the Copy action was triggered and copied the full field content to the clipboard. Text areas should now be ignored.
- That copying selected text in a textarea works
- That a reference can open inside a group
- Fixes an …
=> fix(core): fix copy related issues

packages/sanity/src/_internal/cli/actions/build/buildAction.ts, packages/sanity/src/_internal/cli/actions/deploy/deployAction.ts, packages/sanity/src/_internal/cli/util/__tests__/shouldAutoUpdate.test.ts, packages/sanity/src/_internal/cli/util/shouldAutoUpdate.ts
As auto-updates become the new "default" way to build and deploy studios, we should ensure we're offering ways to easily override default behavior. This PR adds a helper function used in the build and deploy functions that prioritizes CLI flags first, then `sanity.cli.{ts|js}` parameters, and then finally a default (which we can easily change).
The new file -- does it belong in utils (it was a bit hard to place since it was shared by two different actions)?
Ways to test I may have missed? (see below)
This function is quite simple and goes through several layers of abstraction -- I'm not sure if it's particularly useful to test on its own. It would be ideal to test the `--no-auto-updates` command line input, but I'm not sure it's possible. An integration test with the flags and a cliConfig …
=> feat(cli): respect `--no-auto-updates flag` in CLI config

packages/sanity/src/structure/structureBuilder/DocumentList.ts
The JSdoc details for the `DocumentListBuilder.filter` don't provide enough information of how the filter works and what it supports.
This adds extra information and the reference to the realtime-updates docs
Once this is merged, will also update the docs in https://www.sanity.io/docs/structure-builder-reference#filter-c0dc69f8c387 to: 
Solves: https://github.com/sanity-io/sanity/issues/7399 
n/a
n/a
=> chore(structure): add DocumentListBuilder.filter JSdoc details

packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx, packages/sanity/src/structure/panes/document/documentPanel/documentViews/useConditionalToast.ts
An issue is present in structure in which sync toasts are forever present. 
For what was discussed with the internal team, is that the toast is persisted even though the condition for it is gone or and even if the document is not in view anymore. 
This seems to be caused because when the `FormView` component is unmounted, the toast doesn't trigger a close action, to solve this a cleanup function was added to the useEffect to close the toast if it is still shown.
This seems to be happening even if the `FormView` is not visually unmounted (document is still open), this seems to be caused because the `FormView` component takes a key [` key={documentId + (ready ? '_ready' : '_pending')}`](https://github.com/sanity-io/sanity/blob/dismissable-document-sync-toast/packages/sanity/src/structure/pan …
=> fix(structure): make sync document toast dismisable

packages/@sanity/types/src/schema/definition/type/array.ts, packages/sanity/playwright-ct/tests/formBuilder/tree-editing/TreeEditing.spec.tsx, packages/sanity/playwright-ct/tests/formBuilder/tree-editing/TreeEditingNestedObjects.spec.tsx, packages/sanity/src/core/config/configPropertyReducers.ts, packages/sanity/src/core/config/prepareConfig.ts, packages/sanity/src/core/config/types.ts, packages/sanity/src/core/form/studio/tree-editing/__tests__/useTreeEditingEnabled.test.tsx, packages/sanity/src/core/form/studio/tree-editing/context/enabled/TreeEditingEnabledProvider.tsx, test/e2e/tests/inputs/array.spec.ts, test/e2e/tests/tree-editing/TreeEditingBasicInteraction.spec.ts, test/e2e/tests/tree-editing/TreeEditingNavigation.spec.ts
This changes disable the "Array Tree Editing" beta feature for everyone, even those that opted in to the beta.
Deprecates the beta flag `treeArrayEditing`
In version 3.50.0 a month ago we launched a beta of an experimental modal for editing nested objects in arrays. Thank you to everyone who opted in to the beta and gave us valuable feedback on the user experience. We are now ending the experiment and we continue working on alternative ways to navigate nested structured content.
=> chore(core): end "Array Tree Editing" beta

packages/sanity/src/core/bundles/hooks/useDocumentVersions.tsx
Work in CL has finalised, so I'm re-adding the right query
❗ the query is not optimised for all datasets (including the one we are using by default in the studio), but this should not bea concern for this PR
=> refactor(sanity): re-add sanity::versionOf

packages/sanity/src/_internal/cli/actions/schema/extractAction.ts
When running `schema extract` there's no feedback about what has happened, only that it succeeded or failed. I'd like it to be more descriptive and obvious, especially useful when modifying the output path.
I've only modified the `.succeed` call, but I see also these lines:
```ts
spinner.text = `Writing schema to ${path}`
```
```ts
.start(
enforceRequiredFields
? 'Extracting schema, with enforced required fields'
: 'Extracting schema',
)
```
But I've not seen them when I run `schema extract`, I only get the succeed call.
Does this need testing?
* Output path to file when extracting schema
=> output path when extracting schema

packages/sanity/src/core/bundles/components/dialog/BundleForm.tsx
Made the input use the generic date inputs.
This is temporary since the design for the dialog will likely change this is useful for being able to create releases with published dates
Code changes
Can you create a release with a publishAt date (in the future)?
Does it appear properly?
=> refactor(sanity): remove commented publishat input

packages/sanity/src/ui-components/inputs/DateInputs/DateTimeInput.tsx
Add a prop to the dateTImeInput in ui-components because you might not want it always (example: from within a modal)
- Addition makes sense, is there anything missing?
Add ability to constraint the size of the date picker popover in the DateTimeInput in ui-components
=> fix(sanity): add prop for constraintSize

packages/sanity/src/core/bundles/components/panes/BundleActions.tsx, packages/sanity/src/core/bundles/hooks/useDocumentVersions.tsx, packages/sanity/src/core/bundles/util/util.test.ts, packages/sanity/src/core/bundles/util/util.ts, packages/sanity/src/core/index.ts, packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItemPreview.tsx, packages/sanity/src/core/tasks/components/form/fields/TargetField.tsx, packages/sanity/src/core/tasks/components/form/utils.ts, packages/sanity/src/core/tasks/plugin/structure/SetActiveDocument.tsx, packages/sanity/src/core/util/draftUtils.test.ts, packages/sanity/src/core/util/draftUtils.ts, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTitle.test.tsx
When tasks are created for a version document , link the task with the version document instead of the live document, so tasks for a version are only visible in a version. And the version won't show tasks from the published document.
https://www.loom.com/share/487a5c732b7d4367a7d737720f24351a?sid=99a7112b-00a0-4730-a0e2-da5bd78a1091
- This PR renames and move `getBundleSlug` to `getVersionFromId`, given the id is not specifically related to the bundles, it's related to the `version` 
- Once the search allows looking for version documents the tasks document search should be updated to allow users to link tasks to version documents from there.
=> feat(tasks): link tasks to the version document

packages/sanity/src/core/comments/components/list/CommentsListItem.tsx, packages/sanity/src/core/comments/components/list/CommentsListItemLayout.tsx, packages/sanity/src/core/comments/context/comments/CommentsProvider.tsx, packages/sanity/src/core/comments/store/useCommentsStore.ts, packages/sanity/src/structure/panes/document/DocumentPane.tsx, packages/sanity/src/structure/panes/document/comments/CommentsWrapper.tsx
Added changes to the comments to allow for version comments to show up when the version is switched to.
https://github.com/user-attachments/assets/42de80ed-38b5-467c-b343-4d4022b53f7d
Added a todo for when the release is "complete", tested out the readOnly and it looks to do what we want. The rest will depend on design
=> refactor(sanity): add changes to allow for comments in version documents

dev/design-studio/package.json, dev/studio-e2e-testing/package.json, dev/test-studio/package.json, packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/core/studio/components/navbar/navDrawer/ManageMenu.tsx, packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx, packages/sanity/src/core/studio/components/navbar/userMenu/ManageMenu.tsx, pnpm-lock.yaml
This PR makes some updates to the presence dropdown menu action button to encourage seat expansion.
- Button text has been changed to "Invite collaborators"
- `@sanity/icons` has been updated to version 3.4.0
- Icon has been changed to new AddUserIcon
- Link has been updated to take the user directly to the project members tab
[Linear issues](https://linear.app/sanity/issue/GRO-2406/studio-update-manage-members-dropdown-menu-item)
Review the text and link changes.
Change does not affect or require new automated tests. To test the change, navigate to a studio document with someone else present and open the presence menu by clicking on the user avatars.
No notes for release
=> feat(sanity): Update presence menu button for inviting new collaborators

packages/sanity/src/core/store/_legacy/document/document-pair/editState.ts
When the new versions id was introduced `versions.release-slug.foo` the update to the way we calculate the `bundleSlug` was not added. 
This adds that change, using the new `getVersionFromId` function which gives us safety in how the bundleSlug is obtained from the id. 
Previously, version ids were `release-slug.foo` that's why we were accessing it using the `.at(0)`
=> fix(core): update how bundleSlug is obtained from the version ids

packages/sanity/src/structure/i18n/resources.ts, packages/sanity/src/structure/panes/document/DocumentOperationResults.tsx
When an operation is completed, and there is not a specific label that exists for the operation, then a general toast should appear and interpolate the name of the operation. However, this was trying to read from `{{context}}` which didn't exist in the scope. As such the toast description was incorrect.
This PR just passes through the operation name to the i18n scope, so that it can be interpolated correctly
N/A
=> fix(structure): passing from operation context to label for success toast

dev/starter-next-studio/next.config.js, dev/test-next-studio/next.config.mjs, packages/sanity/src/_internal/cli/server/getViteConfig.ts
This PR enables `styled-components` "speedy mode" in `sanity dev` by explicitly setting the `‎SC_DISABLE_SPEEDY` flag to `false`. By default, `styled-components` have different modes for inserting CSS rules, choosing which mode to use based on whether `process.env.NODE_ENV` is set to `production` or not. When `NODE_ENV` is `production`, it uses the "speedy mode," which significantly boosts performance. Otherwise, it falls back to a slower mode.
I discovered this performance difference while working on an unrelated benchmark in the [`concurrent-styled-components`](https://github.com/sanity-io/concurrent-styled-components#readme) repository. I noticed that `styled-components` had drastically different performance results depending on whether I ran `next dev` or `next build && next start`. …
=> fix: significantly speed up styled-components in dev mode

packages/sanity/src/core/studio/addonDataset/AddonDatasetProvider.tsx
The addon dataset context will only be wrapped if it does not already exist. This is inkeeping with how many newer contexts are being defined, to avoid multiple separate contexts being nested
N/A
N/A
=> chore(core): single addon dataset context

packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Toolbar.spec.tsx
Skip toolbar test (spoken on slack) to prepare for eventual rewrite (linear story has been created)
N/A
=> test(sanity): skip toolbar test

packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/structure/documentActions/HistoryRestoreAction.tsx, packages/sanity/src/structure/i18n/resources.ts, packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBar.tsx, packages/sanity/src/structure/panes/document/statusBar/RevisionStatusLine.tsx
Update the footer when reviewing different revisions of a document
https://github.com/user-attachments/assets/8490901e-2125-4de0-bb83-0b7b36e78b3c
Does everything work as expected?
I don't think new tests are necessary. e2e can be added later but I'm unsure if the noise is necessary beyond testing the "reverting to revision" and that test likely already exists.
Behaviour remains the same, it is mostly a visual change 
n/a this will go to a feature branch
=> feat(sanity): update restore button

packages/sanity/src/core/i18n/bundles/studio.ts, packages/sanity/src/structure/i18n/resources.ts, packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx, packages/sanity/src/structure/panes/document/document-layout/DocumentLayout.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx, packages/sanity/src/structure/panes/document/inspectors/changes/ChangesInspector.tsx, packages/sanity/src/structure/panes/document/inspectors/changes/ChangesTabs.tsx, packages/sanity/src/structure/panes/document/inspectors/changes/HistorySelector.tsx, packages/sanity/src/structure/panes/document/inspectors/changes/index.ts, packages/sanity/src/structure/panes/document/timeline/timeline.styled.tsx, packages/sanity/src/structure/panes/document/timeline/timeline.tsx, packages/sanity/src/structure/panes/document/timeline/timelineMenu.tsx
This pull request joins the history revision and the review changes into 1 inspector, divided by tabs.
Reuses the existing [`Timeline`](https://github.com/sanity-io/sanity/blob/corel-143/packages/sanity/src/structure/panes/document/timeline/timeline.tsx) component to render the view of the `Timeline` and allows the user to select which revision to see in the form.
By moving this into the history tab, the `TimelineMenu` was removed from the [`DocumentPanelHeader`](packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx)
Reuses the existing Review changes, it now includes the **From** and **To** selector, making it easier for the user to understand where the changes he is seeing are coming from.
**Other**
When clicking the fields `ChangeBarButton` the …
=> feat(structure): add history and review tabs to changes inspector panel

packages/sanity/src/core/store/_legacy/history/createHistoryStore.ts, packages/sanity/src/core/store/_legacy/history/history/Aligner.ts, packages/sanity/src/core/store/_legacy/history/history/Timeline.ts, packages/sanity/src/core/store/_legacy/history/history/TimelineController.ts, packages/sanity/src/core/store/_legacy/history/history/chunker.ts, packages/sanity/src/core/store/_legacy/history/history/replay.ts, packages/sanity/src/core/store/_legacy/history/history/types.ts, packages/sanity/src/core/store/_legacy/history/useTimelineStore.ts
https://www.loom.com/share/b1e04c690f7b45dcb40d153cf055c97b?sid=6a600c40-cf41-4bc3-ad0c-d0b90bba4414
1. The first commit includes the fix for this issue - https://github.com/sanity-io/sanity/commit/5cff65b34ac04d4c1c038b5e624c53b3e8f2862a
2. The second is a refactor. The intention behind this renaming of `publishedId` to `documentId`, is to give affordance that in cases where the document is a version, then publishedId is a misnomer. It was really this line:  `this.draftId = isVersionId(documentId) ? documentId : `drafts.${documentId}`` where it felt incorrect to refer to `publishedId`
3. A further refactor in `Timeline` to use `versionId` to reference a version Id and a canonical draft
N/A
N/A
=> fix(core): version document's history was returning error

packages/sanity/src/_internal/cli/actions/validation/validateAction.ts, packages/sanity/src/_internal/cli/actions/validation/validateDocuments.ts, packages/sanity/src/_internal/cli/commands/documents/validateDocumentsCommand.ts, packages/sanity/src/_internal/cli/threads/validateDocuments.ts, packages/sanity/src/core/validation/validateDocument.ts
This PR addresses an issue where the `sanity documents validate` CLI command times out for complex validation rules. The problem occurs when a set of documents with custom validators requires more concurrent `client.fetch` requests than the current hard-coded limit allows, potentially causing the validation process to block indefinitely.
Changes introduced:
1. Increased the default maximum fetch concurrency from 10 to 25.
2. Made the maximum fetch concurrency configurable via a new CLI flag `--max-fetch-concurrency`.
3. Made the default maximum custom validation concurrency explicit and configurable.
These changes aim to prevent situations where the validation process exhausts the available concurrent requests, leading to timeouts.
Related issue: SDX-1617
1. Review the changes in …
=> feat(cli): add `--max-fetch-concurrency` to prevent stalled validators

packages/sanity/src/core/releases/tool/detail/ReleaseDetail.tsx, packages/sanity/src/core/releases/tool/detail/documentTable/useReleaseHistory.ts
The `useReleaseHistory` hook was incorrectly constructing the ID of the documents it needs to fetch and construct the history.
=> fix(core): update useReleaseHistory to fetch with the version documents

packages/sanity/src/core/releases/components/BundleMenuButton/BundleMenuButton.tsx, packages/sanity/src/core/releases/i18n/resources.ts, packages/sanity/src/core/releases/plugin/index.ts, packages/sanity/src/core/releases/tool/ReleasesTool.tsx, packages/sanity/src/core/releases/tool/detail/ReleaseDetail.tsx, packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx, packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseReview.test.tsx, packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx, packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx, packages/sanity/src/core/releases/types/router.ts, packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTitle.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveMenu.tsx, packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveMenu.test.tsx
Fixes an issue with intent link in which the intent was not resolved correctly.
It also replaces the <Button> for a <Link> component, which will allow users to cmd + click to open in new tab. 
Updates the `bundleId` param in the releases tool router for `releaseId`
Existing tests have been updated to reflect the change.
n/a
=> fix(core): update intent link for releases tool
