sanity-io/sanity

- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/form/studio/inputs/crossDatasetReference/datastores/search.ts
- packages/sanity/src/core/tasks/plugin/index.tsx
* Passing function reference to `collate` was not matching expected types, so now anon function is defined
* Using the tasks plugin name variable when declaring the plugin
N/A
N/A
> refactor(core): minor type usage improvement and using task plugin name

- packages/sanity/src/structure/panes/document/DocumentOperationResults.tsx
This PR fixes a bug where a success message shows "Untitled was published" when publishing (and unpublishing) a document with a title. This is especially prevalent on documents with an `image` field. 
It adds an additional check for a title in the current document title when the title is not available on the document preview title.
Ensure that the using the document pane value directly as a last resort for a title is a safe approach.
* Create a new document with an image field
* Add a `title` and then publish the document
* Ensure that the success toast includes the title that you typed and not "Untitled was published" 
* Unpublish the document
* Ensure that the success toast includes the title that you typed and not "Untitled was unpublished" 
* Fixes the "Untitled was published" success …
> fix(core): Fix Title in "Untitled was published" toast

- packages/sanity/src/core/bundles/components/panes/BundleActions.tsx
- packages/sanity/src/core/components/documentStatus/DocumentStatus.tsx
- packages/sanity/src/core/components/perspective/PerspectiveBadge.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentActions.tsx
- packages/sanity/src/structure/documentActions/HistoryRestoreAction.tsx
- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBar.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusLine.tsx
- packages/sanity/src/structure/panes/document/statusBar/RevisionStatusLine.tsx
Part of the code uses changes that exist in [this PR](https://github.com/sanity-io/sanity/pull/7448) from [history-updates](https://github.com/sanity-io/sanity/tree/history-updates) which are required and useful for this PR
____
❗ 
I didn't add the "version" text after because If found it strange. I want to bring it up with Marius that it feels _strange_, the badge should be enough. We don't add specifics about drafts or published text wise. In any case, if anyone or if Marius has a strong opinion I can of course add it
Do the changes make sense? Is there a better way of doing it?
> feat(sanity): update document footer for versions

- packages/@sanity/cli/src/actions/init-project/initProject.ts
When running `sanity init` inside a Next.js project, this will:
* Default the name of the `.env` file (if created) to `.env.local` as this is what Next.js `.gitignore` targets
* Create a new CORS origin for Next.js default `http://localhost:3000` so that the user isn't prompted to do so the first time they open the Studio
I would've thought there'd be somewhere else in the codebase where this check-first-then-add-CORS logic would already exist, but couldn't find it, so recreated it.
Create a new Next.js project
```
npx create-next-app@latest --tailwind --ts --app --src-dir --eslint --import-alias "@/*"
```
Within it, run the below (but obviously targeting your local build)
```
npx sanity init
```
* When `sanity init` is run inside a Next.js project, an appropriate CORS origin is added to …
> Next.js specific defaults for new projects

- packages/sanity/src/router/IntentLink.test.tsx
- packages/sanity/src/router/RouterProvider.tsx
- packages/sanity/src/router/stickyParams.ts
- packages/sanity/src/router/types.ts
- packages/sanity/src/structure/components/IntentButton.tsx
- packages/sanity/src/structure/structureBuilder/Intent.ts
> chore(router): reverting sticky params whilst issue with presentation exists

- packages/@sanity/migrate/src/mutations/creators.ts
- packages/@sanity/migrate/src/mutations/operations/creators.ts
Remove `@beta` tags from migrate package
Did I miss any parts?
Not required, docs only
> docs(@sanity): remove @beta tags from migrate

- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/patch.ts
This branch prevents the `patch` Actions API operation resulting in an empty array of mutations being executed, regardless of whether the operation is a noop.
This caused Studio to get stuck in a syncing state when all of the following conditions were true:
1. Attempting to publish a draft that has no corresponding published document.
2. A custom publish action sets a document value prior to publication.
3. The value the custom publish action tries to set is already the value set in the draft.
Does this solution make sense?
This can be tested in Test Studio by:
1. Navigating to [a document with custom document actions](http://localhost:3333/test/structure/input-debug;documentActionsTest).
2. Creating a new document.
3. Setting the "Some Boolean" field to `true` in the UI.
4. Executing the …
> fix(sanity): prevent empty patches being created

- packages/sanity/src/core/form/inputs/PortableText/Editor.styles.tsx
I find that the numbered list is incorrectly indexed in two places.
The indices of list items starting at `level 2` to `level 9` do not start over even though they are separate lists. Instead, they continue on the counter from the previous list. This is already mentioned at #6879.
```
1. L1
a. L2
i. L3
2. L1
b. L2 // This is supposed to be 'a.'
ii.L3 // This is supposed to be 'i.'
```
```
1. L1
a. L2
i. L3
2. L1
a. L2
i.L3
```
If a numbered list is created right after a bullet list, the indices continue from the previous list counter. It is caused by using the `counter-reset` instead of `counter-set`, making the reset step ineffective.
```
1. L1
2. L1
Some random text
● Bullet list item 1
● Bullet list item 2
3. L1 // This is supposed to reset to '1'
4. L1 // This is supposed to '2'
``` …
> fix(core): correctly reset PTE list counts after non-numbered lists and in sublists

- packages/sanity/src/core/studio/packageVersionStatus/PackageVersionStatusProvider.tsx
Fixes this padding issue by moving it above the button instead of below. This screenshot shows the current state:
Adjusts vertical padding around "Push to reload" button
> fix: add padding above the "Push to reload" button instead of below

- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridArrayInput.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
- packages/sanity/src/core/form/members/object/fields/ArrayOfObjectsField.tsx
All array inputs are passed `onItemPrepend` and `onItemAppend` that they  can call to append and prepend items. Still, the default array input(s) defines their own internal handlers for these two events and passes them on to the ArrayFunctions component. This is both unneccesary, and also makes it harder to customize the behavior by passing in a different onItemAppend function to the array input. This PR removes the redundant handleItemPrepend/handleItemAppend handlers in the standard array inputs.
I also additionally refactored the internal append/prepend handlers so they build upon the default insertion handler and aligned some naming with current convention (e.g. changed from `handleAppendItem` to `handleItemAppend`)
There should not be any significant …
> fix: forward onItemPrepend/onItemAppend to ArrayFunctions

- packages/sanity/playwright-ct/tests/formBuilder/utils/TestForm.tsx
- packages/sanity/src/core/form/store/__tests__/collapsible.test.ts
- packages/sanity/src/core/form/store/__tests__/equality.test.ts
- packages/sanity/src/core/form/store/__tests__/formState.test.ts
- packages/sanity/src/core/form/store/__tests__/members.hidden.test.ts
- packages/sanity/src/core/form/store/__tests__/shared.ts
- packages/sanity/src/core/form/store/conditional-property/createCallbackResolver.ts
- packages/sanity/src/core/form/store/formState.ts
- packages/sanity/src/core/form/store/index.ts
- packages/sanity/src/core/form/store/types/state.ts
- packages/sanity/src/core/form/store/useFormState.ts
- packages/sanity/src/core/form/store/utils/__tests__/immutableReconcile.test.ts
- packages/sanity/src/core/form/store/utils/createMemoizer.ts
- packages/sanity/src/core/form/store/utils/getId.ts
- packages/sanity/src/core/form/store/utils/immutableReconcile.ts
- packages/sanity/src/core/form/studio/FormBuilder.test.tsx
- packages/sanity/src/core/tasks/components/form/tasksFormBuilder/useTasksFormBuilder.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/test/form/renderInput.tsx
This PR introduces memoization to the `prepareFormState` function to significantly improve performance, especially for complex documents with multiple large objects in arrays.
Key changes:
- Implemented memoization for `prepareFormState` and its sub-functions for improved performance for complex documents, with up to 10x improvements in some cases
- Removed computation of `hidden` and `readOnly`. Their `StateTree`s are calculated outside of `prepareFormState` to remove the dependency of the `document` to the inputs of `prepareFormState`.
This addresses performance issues with form state computation, particularly for large and complex documents.
Note: Dependes on #7407 
- Review the memoization implementation in `prepareFormState`
- Check the implementation of conditionally hidden and …
> perf(core): memoize `prepareFormState`

- packages/sanity/src/core/tasks/components/form/fields/assignee/AssigneeSelectionMenu.tsx
Add virtualised list in task assigned
https://github.com/user-attachments/assets/63cf8e76-62b5-4732-930d-83472e6c77f2
Double check all looks well
Already existing tests should be enough
Small performance improvement in assignee task list
> refactor(structure): add virtualization when rendering assigneeds list

- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
As seen in the chart below, the commit that merged [#6370](https://github.com/sanity-io/sanity/pull/6370) had severe impact on editor FPS.
The reason for this is that [#6370](https://github.com/sanity-io/sanity/pull/6370) reverted an earlier [PR](https://github.com/sanity-io/sanity/pull/6129) that, among other things, [skipped](https://github.com/sanity-io/sanity/pull/6370/commits/21846c07de1e3a23cb9608d8290efe68ac698db7#diff-7d4931380ae88cfbe9b089e1b3ff44dd33c5a1ce0d737817076e3ef6be17a494L534) updating focusPath state in DocumentPaneProvider if the emitted focusPath was (deeply) equal to the current focus path. This, in combination with the portable text input emitting onFocus on selection change, which is emitted from the portable text editor on every keystroke, triggered excessive …
> fix(core): skip updating focusPath state if unchanged

- packages/sanity/src/core/store/_legacy/datastores.ts
The document store cache was never found so each time we try to access it is creating a new store. 
This is because the dependencies used in the cache were not the same in the set and get.
This PR fixes that.
Is there any possible side effect of utilizing the  memoized store?
Existing tests should cover this .
> fix(core): document store cache memo not working

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
As part of looking into #7524, I looked into whether we could skip emitting onFocus from the portable text input in cases where the focus-path is unchanged. I realized that we can't do that because we also pass along selection state for cursor presence, but before realizing I had already done a small cleanup, so figured I could make a separate PR for it.
This removes what appears to be a redundant update and read to the `nextSelectionRef`. I could not think of any reason to write to the ref and then immediately after reading from it, and it was only used in this place, so I figured it's better to just pass it as an argument. Let me know if I'm overlooking something.
Should be covered by existing tests
n/a – just an internal cleanup
> fix(core): clean up portable text input's selection change handling

- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
Add a timeout to the toast message so that it doesn't trigger immediately.
In any doc you can use `window.stop()` in the dev console which will set the studio state to trigger the reconnecting state
Add timeout to reconnecting message
> refactor(structure): add timeout to reconnecting message

- packages/@repo/package.bundle/src/package.bundle.ts
- scripts/uploadBundles.ts
Enables source maps for the package bundles, and uploads them to the bucket as well. This also adds a check for the files found in the traversed directories - if they're not `.mjs` or `.map`, we will throw. I think this is actually a feature in disguise, as we don't necessarily want to start uploading other stuff that might be emitted/part of the folder structure.
I originally used the mime-types npm module, but felt the extra dependency was unnecessary for two different file types - so sticking with just a simple map for now.
- Bundling outputs sourcemap and references it in the javascript file
- Upload script logic appears correct
Ran this locally, but without uploading to a bucket.
None
> chore: enable source maps for package bundles

- packages/sanity/src/core/preview/__test__/observeFields.test.ts
- packages/sanity/src/core/preview/observeFields.ts
When previewing a document field, we keep a memo of the latest value so that when resubscribing to the same document later starts by emitting the latest known value (before we fetch from the server).
However, there was a flaw in the current implementation causing unneccessary loading states to appear in the studio:
In short: We assumed the memo being `null` meant that it hadn't been set, but in many cases it’s being explicitly set to `null` because we get `null` back from fetching the fields from the server.
This PR fixes the issue by instead treating `undefined` as "memo not being set".
See code changes + added tests
Added a unit test covering this particular case.
- Fixes a few cases of unnecessary loading states appearing in the Studio
> fix(preview): allow `null` as valid cache/memo value for preview fields

- .github/workflows/efps.yml
- package.json
- perf/efps/index.ts
Adds a github action that runs EFPS test suite to compare PR performance to latest version of sanity. 
It builds on the child branch and this branch is only responsible for the comment 
N/A
N/A - internal
> chore: add efps github actions

- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAsset.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputPreview.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.styled.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/usePreviewImageSource.ts
- packages/sanity/src/core/form/inputs/files/common/UploadProgress.styled.tsx
- packages/sanity/src/core/form/inputs/files/common/UploadProgress.tsx
This branch introduces refinements to the image input preview, primarily to address the layout shift reported in #7337.
There are two scenarios in which layout shift can occur:
1. When the image is loading.
2. When the selected image state transitions to the uploading state, and the uploading state subsequently transitions to the new image. There has been a previous attempt to fix this (#6930), but I believe this may be causing the layout shift when the image loads.
This branch removes the ref added in #6930. Instead of attempting to preserve the last known height of the image preview DOM node using a ref, the known image dimensions are set as CSS custom properties on the outer container of the image input. Both the image preview and upload state UI use CSS to match the aspect ratio of …
> fix(sanity): prevent layout shifts in image input

- packages/sanity/src/core/studio/copyPaste/CopyPasteProvider.tsx
- packages/sanity/src/core/studio/copyPaste/__test__/transferValue.test.ts
- packages/sanity/src/core/studio/copyPaste/transferValue.ts
Fixes an issue where pasting in a conditional readOnly field would not actually resolve the value of the property and always return true for a function. This PR fixes it so that the actual resolved value is used
Error Case
1. Navigate to [test-studio](https://test-studio.sanity.build/test/structure/input-debug;conditionalFieldsTest;0f871579-d0de-46cb-8f63-c3bc8fdb1e12) conditional field document
2. Add a value to title that does not contain the word "read only" 
3. Find field titled "Read Only If Title Is Read Only" and click on paste item
Actual: Cannot paste even if the field is not read only
Fixed Case
1. Navigate to preview [test-studio](https://test-studio-git-sdx-1645.sanity.dev/test/structure/input-debug;conditionalFieldsTest;0f871579-d0de-46cb-8f63-c3bc8fdb1e12) conditional field …
> fix(core): fixes an issue with pasting in conditional readonly field

- packages/@sanity/util/package.json
- pnpm-lock.yaml
We are implicitly already depending on the new version (through the version range), so this is mostly to get rid of a deprecation notice on the types module.
Stuff still works. The only place we still use this is in a deprecated old date format that we can hopefully get rid of in Sanity v4.
No new tests needed.
None.
> chore(deps): upgrade moment, drop `@types` module

- packages/@sanity/cli/src/commands/projects/listProjectsCommand.ts
- packages/@sanity/cli/test/basics.test.ts
Previously `sanity projects list` command listed a URL to the deployed studio but since a project can have multiple studios it does not make sense to show the URL anymore. A decision was made to instead link to manage and in future we can have a command to list deployments for a project.
1. Run `pnpm build` at the root
2. cd `dev/test-studio` 
3. run `npx sanity projects list` 
Confirm the link to manage works
Updates project list command to link to manage instead of single deployed studio 
(Might not be needed, please confirm before adding)
> refactor(cli): updates projects list command to link to manage

- .github/workflows/efps.yml
- package.json
- perf/efps/helpers/aggregateLatencies.ts
- perf/efps/helpers/measureBlockingTime.ts
- perf/efps/helpers/measureFpsForInput.ts
- perf/efps/helpers/measureFpsForPte.ts
- perf/efps/index.ts
- perf/efps/runTest.ts
- perf/efps/tests/article/article.ts
- perf/efps/tests/recipe/recipe.ts
- perf/efps/tests/synthetic/synthetic.ts
- perf/efps/types.ts
The following PR:
1. Revamps the eFPS performance suite to compare the results of the benchmark to a released tag on npm. This is set to `latest` by default.
2. Adds a `efps.yml` workflow file that runs the eFPS suite and includes the results as a comment in PRs.
In addition to 1, the eFPS suite has also be updated to rerun the tests 3 times in CI and then the best performing value is taken. This is to mitigate against noisy neighbors. I've found that comparing the median performance between two different runs and re-running the tests 3 times yield relatively stable results for the relatively unstable environment. Hopefully this provides a good signal on performance without requiring the complex infrastructure.
- Take a look at the output here and see if everything makes sense or if you …
> test: add efps to CI 

- packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx
- packages/sanity/src/structure/panes/documentList/DocumentListPaneContent.tsx
- packages/sanity/src/structure/panes/documentList/constants.ts
- packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts
- packages/sanity/src/structure/panes/documentList/types.ts
- packages/sanity/src/structure/panes/documentList/useDocumentList.ts
This adds Stale-While-Revalidate behavior to document lists in the Studio. This means that when coming back to a previous list, we'll immediately show the last known contents, and then fetch the new version in the background. In many cases this means that going back and forth between document lists feels instant.
The actual SWR logic is implemented with an LRU cache in [packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts](https://github.com/sanity-io/sanity/compare/simplify-key-value-store...fix-memoize-list-results?expand=1#diff-351b61b4553a9471d3d02094781702e9da5aeb21780233022f8543efc2590813) and it uses a memo key based on various input parameters for the search query request.
I took the liberty of refactoring some of the logic and renaming a few variables etc based …
> fix(structure): memoize search query results

- packages/sanity/src/core/studio/components/navbar/search/definitions/operators/stringOperators.test.ts
- packages/sanity/src/core/studio/components/navbar/search/definitions/operators/stringOperators.ts
This branch adjusts the global search "contains" filter to allow matches inside words. Although this filter is named `stringMatches` internally, it is publicly named "contains", which suggests it should match *inside* words.
The match expression is wrapped in wildcard `*` operators to achieve this. 
| --- | --- |
| <img width="837" alt="Screenshot 2024-10-02 at 10 24 17" src="https://github.com/user-attachments/assets/908107a4-df00-4702-8a74-6a4322f43f4c"> | <img width="837" alt="Screenshot 2024-10-02 at 10 25 11" src="https://github.com/user-attachments/assets/df83340f-7249-4576-af36-f0293d0f264a"> |
- Does this change make sense?
- Do global searches using the "contains" filter still produce relevant results?
- Updated unit tests in …
> fix(sanity): allow global search "contains" filter to match inside words

- packages/sanity/src/_internal/cli/actions/validation/validateAction.ts
- packages/sanity/src/_internal/cli/actions/validation/validateDocuments.ts
- packages/sanity/src/_internal/cli/threads/__tests__/validateDocuments.test.ts
- packages/sanity/src/_internal/cli/threads/validateDocuments.ts
Updates the validate command to use studioHost configured in the CLI config instead of relying on the projects endpoint studioHost for this information.
Tests Updates
N/A (does not seem it is important to mention in release notes)
> fix(cli): use studioHost from CLI config for intent link

- packages/sanity/src/core/store/_legacy/document/types.ts
The `listenerName` property is handy to debug certain listener related issues, but was not part of the typings.
That there's no… typo, I guess?
Shouldn't need any changes.
None.
> fix(core): add missing `listenerName` property on welcome event

- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/form/studio/inputs/crossDatasetReference/datastores/search.ts
- packages/sanity/src/core/util/draftUtils.test.ts
- packages/sanity/src/core/util/draftUtils.ts
- packages/sanity/src/structure/panes/documentList/helpers.ts
- packages/sanity/src/structure/panes/documentList/types.ts
- Re-adds `QueryResult` interface
- Changing the type in the collate to not explode when versions are present.
When rebasing against `next` something went wrong specifically around this [PR](https://github.com/sanity-io/sanity/pull/7555/files). I wasn't able to fix it by using rebasing however this unblocks us and allows us to continue work.
I imagine that the fix will likely be more around making sure that the collate prop type stayed the same (making the changes in the ENABLE_LRU_MEMO changes however I don't know the larger impact of making that change, so, for now I've set this up.
Folks that are more knowledgeable around this should weight in before I merge since this is more like a temporary bandaid than a fix 🥲 
Ash set up a branch `corel-pre-rebase-20241003` in case if you want to …
> refactor(sanity): fix type issues with collate, update tests and readQueryResult

- packages/sanity/src/core/form/store/formState.ts
This fixes a bug that caused the document editor to crash in certain cases where there is no selected group. This occurs when the default field group is not found. Allow this value to be `undefined` and checking for it fixes the issue.
Does this correct protect against all cases where the selectedGroup is undefined? Are all the types updated correctly?
This was tested manually in the admin studio. I built sanity package, packed it, and install it in the admin studio and the issue was resolved.
Fixes a bug that caused the document editor to crash when the default field group is not found.
> fix: protect against falsy `selectedGroup`

- packages/sanity/package.json
- pnpm-lock.yaml
Just a dependency update. v2 of this module uses ESM by default, aside from that there shouldn't be any meaningful changes.
Stuff still works. In particular, image and file fields + copy/paste of these fields.
Existing tests should hopefully be enough.
Have done some manual testing as well.
None
> chore(deps): upgrade `@sanity/asset-utils` to v2

- .github/workflows/efps.yml
Minor; it took me 15 seconds to figure out that reference tag meant npm tag, not git tag.
Also, "install" seems a bit wide for the job name since it does the whole run.
…and we might as well use Node 20, I'd say?
Changes make sense
Don't think this should affect anything
None
> chore(ci): use `efps` for job name, use node 20, clarify tag description

- .github/workflows/e2e-ui.yml
- .github/workflows/efps.yml
- .github/workflows/etl.yml
I don't think there's any reason to hide variables such as dataset and project IDs. It makes it harder to debug issues and read logs, as any value in these secrets will be scrubbed from logs as `****`. In particular, we use `test` as a dataset name 😅
- CI configs still looks right
- [Environment variables](https://github.com/sanity-io/sanity/settings/variables/actions) are in place to take the place of the secrets
Letting the CI workflows run should be enough
None
> chore(ci): use environment variables, not secrets, for non-sensitive vars

- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
Currently, we defer marking the document as "ready" until we have loaded the timeline. This was originally done to avoid the confusion from first loading the current revision of the document and then replacing it when the selected revision is loaded from the timeline.
In a certain cases, loading the timeline can be quite slow, so the changes in this PR only waits if there's actually a selected revision (represented by `params.rev` being set)
Does it make sense? Any case I'm not thinking about?
Unfortunately non-trivial to add automated tests for, but I've verfied that the current behavior is preserved if params.rev is set.
- fixed an issue that could in certain rare cases make loading of a document to take a long time.
> fix(structure): improve and clean up form ready state

- .eslintrc.cjs
- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/config/configPropertyReducers.ts
- packages/sanity/src/core/config/prepareConfig.ts
- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/form/studio/FormBuilderInputErrorBoundary.test.tsx
- packages/sanity/src/core/form/studio/FormBuilderInputErrorBoundary.tsx
- packages/sanity/src/core/studio/StudioErrorBoundary.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/FilterForm.tsx
- packages/sanity/src/core/studio/workspaceLoader/WorkspaceLoader.tsx
- packages/sanity/src/core/studio/workspaceLoader/WorkspaceRouterProvider.test.tsx
- packages/sanity/src/core/studio/workspaceLoader/WorkspaceRouterProvider.tsx
- packages/sanity/src/structure/components/confirmDeleteDialog/index.tsx
- packages/sanity/src/structure/components/structureTool/StructureTitle.tsx
- packages/sanity/src/structure/components/structureTool/StructureToolBoundary.tsx
- packages/sanity/src/structure/panes/document/inspectors/validation/ValidationInspector.tsx
- packages/sanity/src/ui-components/errorBoundary/ErrorBoundary.tsx
- packages/sanity/src/ui-components/errorBoundary/__test__/ErrorBoundary.test.tsx
- packages/sanity/src/ui-components/errorBoundary/index.ts
- packages/sanity/src/ui-components/index.ts
Adds ability to callback when an error happens and allows developers to add custom error telemetry (for example)
I will drop the throw errors before merging, those are for testing purposes
- Does the code make sense? 
- Does the naming of the callback make sense?
- I tried in other places, however, while discussing it with others in the team after not finding a place that would have context for the `useSource`, the current place where it exists seems to be the better option. If you all have any other suggestions I'd love to hear it!
Automated tests are in place.
You can also manually trigger it by adding `throw new error("oh no new error)` within the `imageInput` or the `studioComponents` and then going to the `custom-components/structure` workspace and seeing the console logs work
Adds …
> feat(sanity): add config for onUncaughtError

- .github/workflows/e2e.yml
This changes some remaining references to secrets in the e2e workflow after #7598 moved them to env vars.
Did I miss any?
CI passes, I guess?
n/a
> chore(ci): change env vars from secrets to env

- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/store/_legacy/document/debug.ts
- packages/sanity/src/core/store/_legacy/document/getPairListener.ts
- packages/sanity/src/core/store/_legacy/document/types.ts
- packages/sanity/src/core/store/_legacy/document/utils/__test__/eventChainUtils.test.ts
- packages/sanity/src/core/store/_legacy/document/utils/__test__/sequentializeEvents.test.ts
- packages/sanity/src/core/store/_legacy/document/utils/__test__/test-utils.ts
- packages/sanity/src/core/store/_legacy/document/utils/eventChainUtils.ts
- packages/sanity/src/core/store/_legacy/document/utils/sequentializeListenerEvents.ts
In very rare cases, the /listen endpoint may drop mutation events. This PR implements detection of "holes" in the received mutation events, and implements error recovery by restarting the connection.
Are the threshold values sensible? Error detection and recovery is now triggered by the following thresholds.
- `DEFAULT_MAX_BUFFER_SIZE=20`: If we se more than 20 mutation events that can't be applied in order we treat it as an error
- `DEFAULT_DEADLINE_MS=30_000`: If 30 seconds pass since we last received a message that can't be applied in order we treat it as an error
This PR includes unit tests and has also undergone extensive manual testing.
- Fixes an issue that could in rare cases lead to an outdated version of the document being displayed locally
> fix(core): add detection and recovery for missing mutation events

- dev/test-studio/schema/debug/simpleReferences.js
- packages/sanity/src/core/components/previews/general/DefaultPreview.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/AutocompleteContainer.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/types.ts
- packages/sanity/src/core/form/inputs/ReferenceInput/useReferenceInfo.ts
- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/preview/availability.ts
- packages/sanity/src/core/preview/components/PreviewLoader.tsx
- packages/sanity/src/core/preview/useValuePreview.ts
- packages/sanity/src/core/preview/useVisibility.ts
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
This PR fixes various loading and rendering issues with reference previews. It should significantly reduce the number of re-renderings and layout shifts happening as we load what's needed to preview references in the Studio. These issues are particularily visible behind slower networks.
Here's before/after with network throttling set to 3g
**Before**
https://github.com/user-attachments/assets/1b87897e-0abf-49db-8a2e-edb3669e2353
**After**
https://github.com/user-attachments/assets/a37704a0-4b52-4f94-8f76-3a2101cc0f2e
Included some additional improvments here as well:
- useVisibility now use [`Element.checkVisibility()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/checkVisibility) if available
- Waiting 300ms before showing "loading skeletons". This aligns with how it's done …
> fix(core): fix reference preview flickering and improve loading

- .github/workflows/efps.yml
- perf/efps/index.ts
- perf/efps/runTest.ts
Sometimes it can be really helpful to see what is going on in the eFPS test suite. This PR adds an option to record videos for runs. It is off by default, cause I don't think we necessarily need the videos for every run - but we may consider changing it if we see it being really useful.
None
> ci(efps): allow recording video in efps suite

- packages/sanity/src/core/config/types.ts
Mistakenly a property in Source was tagged as internal when it should have been beta.
This impacts the docs
> docs(sanity): update label onUncaughtError from internal to beta

- packages/sanity/src/core/store/_legacy/grants/documentPairPermissions.ts
- packages/sanity/src/core/store/_legacy/grants/documentValuePermissions.ts
- packages/sanity/src/core/store/_legacy/grants/types.ts
- packages/sanity/src/core/studio/screens/RequestAccessScreen.tsx
- packages/sanity/src/structure/components/requestPermissionDialog/useRoleRequestsStatus.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/InsufficientPermissionBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/index.ts
This one needs a proper read-through, I am not super confident with these changes - especially the last commit. There might be a lot easier ways to solve the problem outlined in the title here, but let me explain:
When researching why there were constant requests being fired to the `/access` API, I saw that it was due to a hook being run inside of the `<PermissionCheckBanner />`. Upon further inspection, I saw that this component remounts (unmounts and mounts) constantly while edits are going on, due to the continuous evaluation of permissions as the document changes. When this happens, the `isPermissionsLoading` state gets set to `true`, which triggers the banner to unmount. Once it's calculated if it should be allowed/disallowed, it re-mounts. My hunch is that this is not only causing …
> fix: prevent excessive requests to access endpoint 

- package.json
- pnpm-lock.yaml
- scripts/uploadBundles.ts
The source maps we upload to our module CDN now contains source maps, which helps in debugging. Sources are inlined, but the original source _locations_ are also left intact. This isn't a _problem_ per se, but it does lead to tooling trying to link to them and failing. For instance, a source map could be referencing `../../../node_modules/.pnpm/@sanity+client@6.22.0_debug@4.3.7/node_modules/@sanity/client/dist/index.browser.js`, which would be resolved to `https://modules.sanity-cdn.com/modules/v1/node_modules/.pnpm/@sanity+client@6.22.0_debug@4.3.7/node_modules/@sanity/client/dist/index.browser.js`, which we obviously do not host.
It is helpful to have _some_ source location, as from the example above I can see that the source pointed to `@sanity/client`. To make this even more helpful, …
> fix: use absolute urls for published sourcemap urls

- package.json
- packages/sanity/src/core/studio/components/navbar/search/components/common/FilterLabel.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/common/__tests__/FilterLabel.test.tsx
- packages/sanity/test/testUtils/TestProvider.tsx
Fixes issue where boolean values were not showing the proper value in search. See issue #7608 
I have added unit tests for the boolean case and basic tests covering the FilterLabel component's responsibilities
- Fixes an issue where boolean filters in search did not show the actual value
> fix(core): boolean value in search shows actual value

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/index.ts
- packages/sanity/src/core/releases/components/dialog/ReleaseDetailsDialog.tsx
- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/components/dialog/__tests__/ReleaseDetailsDialog.test.tsx
- packages/sanity/src/core/releases/util/const.ts
- packages/sanity/src/core/store/bundles/types.ts
Add release types to bundles metadata (asap, scheduled or undecided)
Names are still in flux, these seemed to be the ones that we would least regret in the long run as well as make it clearer from a code standpoint, I'm open to other suggestions though!
Also, we were planning on having these properties exist in a separate place other than the bundle metadata, but due to limitations outside of our control this is the temporary solution
Does the code provided make sense?
Keep in mind, this is simply for unblocking us in continuing corel development, **the actual development and changes to the modal will be done in a separate task and so are out of scope**
Updated tests to pass
> feat(sanity): add release types

- dev/test-studio/structure/resolveStructure.ts
- packages/sanity/src/core/store/key-value/localStorageSWR.ts
- packages/sanity/src/structure/useStructureToolSetting.ts
fixes #7586
#7554 broke default sorting because `useStructureToolSetting` always returned `null` from localStorage synchronously, therefore overriding the passed defaultValue. This fixes the issue by always falling back to the defaultValue whenever the settings store emits `null`.
Ideally `useStructureToolSetting` should have unit tests, but I'm not able to prioritize spending time on that right now.
I've manually tested and verified that the behavior is as intended.
- Fixes a bug causing default sorting for document lists to not be applied
> fix: restore support for defaultOrdering.

- .github/workflows/pr-validate.yml
- .github/workflows/validate-pr-title.yml
Adds github action that validates the PR title follows semantic syntax
Change the title to non semantic and re-run the Validate PR workflow to see the failing error. Change it back to semantic and see it pass
N/A
N/A
> feat: validate PR title against conventional commits

- dev/test-studio/structure/resolveStructure.ts
It is useful to  see the image and file assets at times - this PR adds some structure entries for them to the test studio structure. Also removes an annoying warning about not specifying API version for one of the document lists.
Structure items shows up, works.
None
None
> chore(test-studio): add asset types to structure navigation

- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/src/actions/init-project/readPackageJson.ts
Using React 19 in an embebed studio inside NextJs is not supported. 
We want to show documentation to users on how to fix the issue in the cli when starting the project.
This adds warning and documentation for users https://www.sanity.io/help/react-19
https://github.com/user-attachments/assets/39e61c72-91f6-4d2a-aa33-abecb2eeb2db
Are we missing something?
Add warning and documentation for users using React 19 and NextJs 15, visit https://www.sanity.io/help/react-19
> feat(cli): add warning and docs for react-19 and Next.Js combined

- packages/sanity/src/core/store/_legacy/datastores.ts
> fix: creating perspective reference to avoid recreating releases store on perspective change

- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenuItem.tsx
- packages/sanity/src/core/releases/navbar/PerspectiveLayerIndicator.tsx
- packages/sanity/src/core/releases/navbar/ReleaseTypeMenuSection.tsx
- packages/sanity/src/core/releases/navbar/ReleasesNav.tsx
- packages/sanity/src/core/releases/tool/components/Table/Table.tsx
- packages/sanity/src/core/releases/tool/components/Table/TableHeader.tsx
- packages/sanity/src/core/releases/tool/components/Table/types.ts
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/util/util.ts
> feat(releases): global perspective release type grouped menu

- packages/sanity/src/core/releases/components/ReleasesMenu.tsx
- packages/sanity/src/core/releases/hooks/__tests__/utils.test.ts
- packages/sanity/src/core/releases/hooks/usePerspective.tsx
- packages/sanity/src/core/releases/hooks/utils.ts
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/releases/tool/detail/AddDocumentSearch.tsx
- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/release/createReleaseStore.ts
- packages/sanity/src/core/store/release/reducer.ts
- packages/sanity/src/core/store/release/types.ts
- packages/sanity/src/core/store/release/useReleases.ts
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItemPreview.tsx
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/SearchProvider.tsx
- packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx
- packages/sanity/src/structure/components/paneRouter/PaneRouterProvider.tsx
- packages/sanity/src/structure/components/paneRouter/types.ts
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusLine.tsx
- packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx
This Pr moves the `releases.stack` to the `usePerspective` hook into the `bundlesPerspective` property, this relates to the client query parameter.
This also includes changes to sort the releases and exports the releases from the store now sorted.
The sorting is as it follows:
- undecided sorted by created at
- scheduled sorted by publishAt || intended publish date
- asap sorted by created at
Tests for sorting and bundles perspective have been added.
> feat(core): move bundlesPerspective to usePerspective hook, sort releases

- packages/@sanity/types/src/schema/preview.ts
- packages/sanity/src/core/components/documentStatus/DocumentStatus.tsx
- packages/sanity/src/core/components/documentStatusIndicator/DocumentStatusIndicator.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/ReferencePreview.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/types.ts
- packages/sanity/src/core/form/inputs/ReferenceInput/useReferenceInput.tsx
- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/preview/components/SanityDefaultPreview.tsx
- packages/sanity/src/core/preview/types.ts
- packages/sanity/src/core/preview/utils/getPreviewStateObservable.ts
- packages/sanity/src/core/scheduledPublishing/components/scheduleItem/PreviewWrapper.tsx
- packages/sanity/src/core/scheduledPublishing/utils/paneItemHelpers.tsx
- packages/sanity/src/core/store/release/useReleases.ts
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItemPreview.tsx
- packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBar.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusLine.tsx
- packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetColumns.tsx
This PR adds changes to the preview and document status components.
It nows shows the versions of the document.
The preview value correctly reflects the stack of releases when previewing a release.
So if a document is part of the releases `asap1, asap2, scheduled1, undecided1` and user is seeing the release `scheduled2` the preview value will reflect the value of the document in release `scheduled1` which is scheduled to be released before scheduled 2
> feat(core): add versions to references and status icons

- packages/sanity/src/core/store/_legacy/grants/__tests__/templatePermissions.test.ts
- packages/sanity/src/core/store/_legacy/grants/templatePermissions.ts
- packages/sanity/src/core/templates/__tests__/resolve.test.ts
- packages/sanity/src/core/templates/resolve.ts
This PR refactors the template permissions resolution to handle templates sequentially instead of in parallel. The key changes are:
- Replaces `combineLatest` with `from().pipe(concatMap())` to process templates one at a time
- Improves caching of initial value resolution to reduce duplicate computations
- Fixes test timeouts by properly mocking async operations and providing complete contexts
These changes were introduced to improve performance and reliability when resolving template permissions, particularly for large numbers of templates. The sequential processing helps prevent potential race conditions and resource contention.
Key areas to review:
1. The shift from parallel to sequential processing in `templatePermissions.ts`
2. The new caching implementation in `resolve.ts` …
> perf(core): memoize resolveInitialValueForType

- packages/sanity/src/core/index.ts
- packages/sanity/src/core/releases/hooks/usePerspective.tsx
- packages/sanity/src/core/releases/hooks/useVersionOperations.tsx
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenuItem.tsx
- packages/sanity/src/core/releases/navbar/ReleaseTypeMenuSection.tsx
- packages/sanity/src/core/releases/navbar/ReleasesNav.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardDetails.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/util/getReleaseTone.ts
- packages/sanity/src/core/releases/util/util.ts
- packages/sanity/src/structure/components/paneHeaderActions/PaneHeaderCreateButton.tsx
- packages/sanity/src/structure/panes/document/document-layout/useBundleDeletedToast.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/DeletedDocumentBanners.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusLine.tsx
> refactor: making published perspective not a ReleaseDocument

- packages/sanity/src/core/releases/components/dialog/__tests__/ReleaseDetailsDialog.test.tsx
- packages/sanity/src/structure/components/paneRouter/PaneRouterProvider.tsx
- packages/sanity/src/structure/components/paneRouter/types.ts
- packages/sanity/src/structure/components/structureTool/StructureTitle.tsx
- packages/sanity/src/structure/panes/StructureToolPane.tsx
- packages/sanity/src/structure/panes/document/DocumentPane.tsx
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/comments/CommentsWrapper.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/ReferenceChangedBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/inspectors/validation/index.ts
Perspective is only a global concept, initially we allowed changing the perspective in each pane, but that is not supported anymore.
Removing this simplifies things for consumers and allows presentation to render the releases form in the correct way.
> chore(structure): remove perspective from paneRouter

- .github/CODEOWNERS
No notes for release, merely updating CODEOWNERS to @sanity-io/data-eng from @sanity-io/growth  for who gets pinged for these files
> chore: telemetry definition files are owned by @data-eng

- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/scheduledPublishing/index.ts
Export types `BetaFeatures` and `ScheduledPublishing` from `sanity` 
External libraries, like [sanity-typed ](https://github.com/saiichihashimoto/sanity-typed) need the types used in `defineConfig` to be exported.
fixes: https://github.com/sanity-io/sanity/issues/7637
Any side effect to consider? 
No new functionality added, no tests added.
n/a
> fix(core): export BetaFeatures and ScheduledPublishing types

- packages/sanity/src/core/create/i18n/resources.ts
The namespace was incorrectly specified for the new `create` strings, which causes issues for the locales repository, as it clobbers the `comments` namespace.
Should be pretty obvious ;)
Shouldn't be needed.
None.
> fix: invalid locale namespace specified for create

- packages/@sanity/codegen/jest.config.mjs
- packages/@sanity/codegen/package.json
- packages/@sanity/codegen/src/__tests__/safeParseQuery.test.ts
- packages/@sanity/codegen/src/typescript/__tests__/__snapshots__/typeGenerator.test.ts.snap
- packages/@sanity/codegen/src/typescript/__tests__/findQueriesInPath.test.ts
- packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts
- packages/@sanity/codegen/src/typescript/__tests__/typeGenerator.test.ts
- packages/@sanity/codegen/vitest.config.mts
- pnpm-lock.yaml
- vitest.workspace.ts
Migrates codegen tests to vitest
Changes makes sense 
Existing tests should pass
N/A
> test(codegen): migrate codegen tests to vitest

- packages/sanity/src/core/index.ts
- packages/sanity/src/core/releases/components/dialog/__tests__/ReleaseDetailsDialog.test.tsx
- packages/sanity/src/core/releases/components/dialog/__tests__/ReleaseForm.test.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDetailsEditor.test.tsx
- packages/sanity/src/router/RouterProvider.tsx
- packages/sanity/src/router/types.ts
- packages/sanity/src/structure/components/paneItem/PaneItem.tsx
- packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx
- packages/sanity/src/structure/components/structureTool/StructureTitle.test.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/__tests__/DeletedDocumentBanners.test.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentHeaderTitle.test.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveList.test.tsx
- packages/sanity/src/structure/panes/documentList/__tests__/PaneContainer.test.tsx
We are storing the same state in the `usePerspective` hook and in the router, this PR removes the one from the router.
> chore(router): remove perspective state from router

- packages/sanity/src/core/releases/i18n/index.ts
- packages/sanity/src/core/releases/store/constants.ts
Should fix the `pnpm etl sanity` task that's currently failing in the base branch
> fix(ci): avoid literal as const package exports due to etl error

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
In an effort to make `@portabletext/editor` become more stand-alone, I'm looking into removing the few `@sanity/*` dependencies that it has. Here, `@sanity/util` is a low-hanging fruit.
If the `keyGenerator` prop isn't passed, the `PortableTextEditor` will use `randomKey(12)` from `@sanity/util`. However, passing this key generator explictly from the `PortableTextInput` removes this implicit dependency. Now, the Studio keeps getting the same type of random keys and `@portabletext/editor` is free to remove the `@sanity/util` dependency and just copy/paste the source code of `randomKey` or use another default key generator.
> fix(core): explicitly pass `randomKey(12)` as the PTE `keyGenerator`

- packages/@sanity/codegen/src/typescript/__tests__/findQueriesInSource.test.ts
- packages/@sanity/codegen/src/typescript/expressionResolvers.ts
Adds support to Typegen for:
* Export all (`export * from "source.ts"`)
* Nested functions with parameters (#7748)
* Function parameters with default values
Only worker code for the Typescript parser was changed. Examples of code that wasn't but is now successfully parsed is in the new tests.
Tests were added for the newly supported features.
Typegen now supports slightly more advanced types of interpolation, e.g. 
```ts
const query = groq`*[_type="asdf"] { 
"linkA": ${linkQuery('linkA')},
}`;
```
Client code can also import through an export all without confusing Typegen.
> feat(codegen): function resolving

- packages/sanity/src/core/releases/components/dialog/CreateReleaseDialog.tsx
- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/components/dialog/TitleDescriptionForm.tsx
- packages/sanity/src/core/releases/components/dialog/__tests__/CreateReleaseDialog.test.tsx
- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
- packages/sanity/src/core/releases/components/documentHeader/dialog/CopyToNewReleaseDialog.tsx
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDetailsEditor.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
> refactor(core): rename dialogs

- packages/@sanity/base/src/datastores/history/createHistoryStore.ts
Fixes an issue that cleared cross dataset references when restoring a document from history
n/a - fixes an issue in v2 which is EOL
> fix(base): support restoring cross dataset references

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/index.ts
- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
- packages/sanity/src/core/releases/components/documentHeader/contextMenu/VersionContextMenu.tsx
- packages/sanity/src/core/releases/components/documentHeader/contextMenu/VersionContextMenuItem.tsx
- packages/sanity/src/core/releases/components/documentHeader/contextMenu/__tests__/VersionContextMenuItem.test.tsx
- packages/sanity/src/core/releases/tool/components/ReleasePublishAllButton/ReleaseScheduleButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardFooter.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/util/util.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
updated tooltip contents
update formatting for document header
add locked icon to chips on the document header 
add banner when the release is scheduled / locked
make document readOnly when release is locked
> refactor(sanity): fix date formating, add locked chips and locked document on scheduled releases

- .github/CODEOWNERS
This commit changes all Studio teams in CODEOWNERS to `@sanity-io/studio`, which is necessary because the `@sanity-io/studio-dx` and `@sanity-io/studio-ex` teams have been removed.
> chore: update Studio teams in CODEOWNERS

- packages/sanity/src/core/create/components/CreateLinkedDocumentBannerContent.tsx
- packages/sanity/src/core/create/components/CreateUnlinkConfirmDialog.tsx
- packages/sanity/src/core/create/i18n/resources.ts
- packages/sanity/src/core/create/start-in-create/StartInCreateAction.tsx
- packages/sanity/src/core/create/start-in-create/StartInCreateActionContent.tsx
- packages/sanity/src/core/create/start-in-create/StartInCreateActionFooter.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
- packages/sanity/src/core/form/inputs/PortableText/text/TextBlock.tsx
This PR introduces some very minor copy and layout updates to the existing Studio → Create integration. All changes are purely cosmetic.
- All copy changes should read naturally (these have been pre-vetted)
- All dialog buttons (the "Start in Sanity Create" document action and "Unlink" button) should now look more 'native', as they're now correctly passed to the dialog-specific `footer` prop (as opposed to rendering these within the dialog body)
N/A – copy and minor layout tweaks only
Not required
> fix: create integration copy + layout updates

- packages/sanity/src/core/releases/components/documentHeader/contextMenu/VersionContextMenuItem.tsx
- packages/sanity/src/core/releases/components/documentHeader/contextMenu/__tests__/VersionContextMenuItem.test.tsx
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenuItem.tsx
- packages/sanity/src/core/util/__tests__/formatRelativeLocale.test.ts
- packages/sanity/src/core/util/formatRelativeLocale.ts
- packages/sanity/src/core/util/index.ts
- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
Currently:
For dates more than a week in the past/future, these would be formatted as 'MM/dd/yyyy':
Now:
These dates are formatted correctly according to the locale formatting of the client, eg in my case 'dd/MM/yyyy':
Ideally we would pass through the client locale to `date-fns` however given the way that `date-fns` requires the locale to be imported, and that the mappings of `navigator.language` to the `date-fns` are rather specific, taking the approach in this PR felt most extensible to all locales.
Added tests for the wrapper util `formatRelativeLocale`
N/A
N/A
> fix: issue with the US formatting used by formatRelative when no locale defined

- packages/@sanity/cli/src/actions/init-project/initProject.ts
When running `npx sanity@latest init` inside a Next.js 15 project the install errors because of React 19 incompatability.
That the `yarn` and `pnpm` install commands don't also need editing.
* Added `--legacy-peer-deps` flag to the automatic install of `next-sanity` inside Next.js projects
> fix: add --legacy-peer-deps to next-sanity pacakge install

- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/ui-components/inputs/DateInputs/DatePicker.tsx
- packages/sanity/src/ui-components/inputs/DateInputs/DateTimeInput.tsx
- packages/sanity/src/ui-components/inputs/DateInputs/calendar/Calendar.tsx
- Add timezone to create release and to the release details
- Update formating for the inputs
- Make inputs readOnly
> feat(sanity): Add timezones to create release and to the release details

- dev/studio-e2e-testing/sanity.config.ts
- packages/sanity/src/core/config/configPropertyReducers.ts
- packages/sanity/src/core/config/prepareConfig.ts
- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/studio/studioAnnouncements/StudioAnnouncementsProvider.tsx
- packages/sanity/src/core/studio/studioAnnouncements/__tests__/StudioAnnouncementsProvider.test.tsx
- packages/sanity/src/core/studio/studioAnnouncements/useStudioAnnouncements.tsx
Adds a new config flag that can be used to opt out from announcements.
It also opts out in e2e tests, given tests are failing when the announcement renders
Is the config name accurate?
Announcements should work as always in the test studio, you can test it by appending the `?reset-announcements` to the test studio url.
https://test-studio-git-announcements-opt-out.sanity.dev/test/structure?reset-announcements=true
New tests for the opt out flag has been added
> fix(core): add opt out option to studioAnnouncements 

- packages/sanity/src/core/studio/studioAnnouncements/StudioAnnouncementsCard.tsx
Updates icon used in the close button for the studio announcements card.
From  `-` to `x`
> chore(core): update announcements card close icon

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
PTE does not emit the `undo` and `redo` events, and I don't think it ever has, at least not for a long time. Whenever an undo or redo happens, the end result is still patches and the `mutation` event is enough to listen for that.
---
You can test this by verifying that undo/redo still works.
> refactor(core): remove unneeded PTE event handling

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
Currently, PTE emits a connection event whenever it goes offline and online.
However, I don't believe this logic belongs inside PTE:
https://github.com/portabletext/editor/blob/main/packages/editor/src/editor/editor-machine.ts#L41-L60
At the same time, Studio already does an even better job at making sure to mark
fields as `readOnly` when it detects that it's offline.
> refactor(core): remove PTE connection event handling

- packages/sanity/src/core/releases/__fixtures__/release.fixture.ts
- packages/sanity/src/core/releases/hooks/__tests__/__mocks__/usePerspective.mock.ts
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenuItem.tsx
- packages/sanity/src/core/releases/navbar/ReleaseTypeMenuSection.tsx
- packages/sanity/src/core/releases/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/releases/store/__tests__/__mocks/useReleases.mock.ts
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetailsEditor.test.tsx
- packages/sanity/src/core/releases/util/getBundleIdFromReleaseDocumentId.ts
> test(releases): comprehensive testing on release nav

- packages/sanity/src/core/create/i18n/resources.ts
- packages/sanity/src/core/create/start-in-create/CreateLinkingDialog.tsx
This tiny PR includes some copy + icon only changes to the Studio Create integration. Purely cosmetic!
All copy has been pre-vetted, but please shout if anything looks out of place to you.
N/A – copy and icon changes only
Not required
> fix: update create integration copy, use correct chevron icons

- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAssetMenu.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAssetSource.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputUploadPlaceholder.tsx
- packages/sanity/src/core/form/inputs/files/__workshop__/UploadPlaceholderStory.tsx
- packages/sanity/src/core/form/inputs/files/constants.ts
- packages/sanity/src/core/form/studio/inputs/client-adapters/assets.ts
- packages/sanity/src/core/form/studio/uploads/uploadImage.ts
- packages/sanity/src/core/form/studio/uploads/uploaders.ts
- packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/asset/Asset.tsx
This reverts commit 0b0a6fa53a1e1fb321d023fee3333e1941412ca0. We were experiencing [consistent Playwright CT test failures in CI](https://github.com/sanity-io/sanity/actions/runs/11860280163/job/33055316755) after the change introduced. Reverting for now to unblock Studio release.
> chore: revert failing commit

- packages/@sanity/cli/test/telemetry.test.ts
The CLI telemetry tests are very flakey and doesn't hold up well when there are multiple runs going on at the same time, since they reuse the same user for setting/enabling status and then checking the result.
This temporarily disables them, until we can find a better way to mock the network calls or similar.
- Tests are disabled
We're dropping some tests here - we could consider refactoring them to at least check that we get _some_ output from the commands, but seems less than useful right now.
None
> chore(cli): temporarily disable telemetry tests

- packages/sanity/test/validation/infer.test.ts
Applies [this update](https://github.com/sanity-io/sanity/commit/2cc67f8b9e2f9e413e80b7d8bf6e19bfd2857478) to the associated testing suite
N/A
> test: resolving mismatch on snapshot for updated slugValidator

- packages/sanity/src/core/studio/studioAnnouncements/StudioAnnouncementsDialog.tsx
Adds **onClickOutside** handler to the announcements dialog.
When clicking outside of the dialog we want it to close.
fix: close the announcements dialog when clicking outside
> fix(core): discard announcements dialog onClickOutside

- packages/sanity/src/core/releases/store/createReleaseStore.ts
Removes the timeout and retry function from the observable, given they are not needed and was causing issues by creating new listeners every 10 seconds.
Retry is not needed here given is already included in the listener.
> fix(core): remove timeout and retry from releases store

- packages/sanity/src/core/releases/hooks/__tests__/useVersionOperations.test.tsx
- packages/sanity/src/core/releases/hooks/useVersionOperations.tsx
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
Fixes an issue that made it impossible to create a new document in a release. Ideally you should be able to just start typing, but this fix at least makes it _possible_.
Also adds low-level API support for providing an initial/fallback value to use when adding a version to a document.
> fix: support creating version with initial value

- dev/test-create-integration-studio/sanity.config.ts
- packages/sanity/src/core/config/prepareConfig.ts
This PR makes "Start in Create" button enabled by default for pristine, new documents. 
For more context, see the original feature PR: https://github.com/sanity-io/sanity/pull/7635
Feel free to run `test-create-integration-studio` locally and check that it has a `Start in Create` button for new documents.
For new documents you will now find a "Start in Create" button in place of "Publish"
This allows you to start authoring the document in [Sanity Create](https://www.sanity.io/create), by linking a new Create document to the Studio document.
By default any Studio deployed with `sanity deploy` (on this version or later) will have the button show up in the deployed studio. 
For studios hosted with other means, please confer [Configuring Content …
> feat: Start in Create button is now enabled by default

- packages/sanity/src/core/components/commandList/CommandList.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
- packages/sanity/src/core/scheduledPublishing/tool/schedules/VirtualList.tsx
- packages/sanity/src/core/scheduledPublishing/tool/schedules/VirtualListItem.tsx
Adding React Compiler caused a regression in paths that uses `import {useVirtualizer} from '@tanstack/react-virtual'`. [It's a known issue](https://github.com/TanStack/virtual/issues/736), and I've subscribed to the issue so I get notified when we can come back and remove the `'use no memo'` directives 👍 
This should fix SAPP-1945, repro: https://test-studio.sanity.dev/test/structure/input-standard;arraysTest;18db9a51-b3fe-4843-94a6-c5a2ba6ac039
Didn't have time to add an E2E test that covers this case, but it might be worth doing in a follow-up 🙌  Manually tested by checking http://localhost:3333/test/structure/input-standard;arraysTest;18db9a51-b3fe-4843-94a6-c5a2ba6ac039 and scrolling, verifying that array reference items render without focusing/clicking first.
Fixes a regression …
> fix: opt-out `@tanstack/react-virtual` from React Compiler

- dev/test-create-integration-studio/schema.ts
- packages/sanity/src/core/create/__tests__/createUtils.test.ts
- packages/sanity/src/core/create/createUtils.ts
Turns out that "Start in Create" button did not correctly check for `options.sanityCreate.exclude: true`, and it was essentially not possible to opt-out per document type.
This new implementation checks options recursively (and more importantly maybe; it checks the base type 🤦 ). Recursion stops at the first boolean `sanityCreate.exclude`. This allows alias types to override parent options.
Read the unit-tests and 👍 👎 
I deployed a new version of the test studio for this:
https://create-integration-test.sanity.studio/
Check that:
* New "Documentation Article" documents has a "Start in Sanity Create" button.
* New "Sanity Create Excluded" documents does does NOT have a "Start in Sanity Create" button.
Fixes an issue where the `options.sanityCreate.exclude: true` was not respected when …
> fix: Start in Create type exclusion now recursively checks for sanityCreate.exclude options

- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/DraftLiveEditBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- test/e2e/tests/document-actions/liveEdit.spec.ts
This PR changes how the `readOnly` state in the document pane provider works to support editing `live edit` document from the published view, and it disables editing them in the draft view.
| draft mode | Publish mode |
|<img width="840" alt="Screenshot 2024-11-28 at 14 22 49" src="https://github.com/user-attachments/assets/983bcff2-0d4a-46c2-a701-649c94098e9d">|<img width="839" alt="Screenshot 2024-11-28 at 14 22 57" src="https://github.com/user-attachments/assets/a4da4530-38c5-4cd5-bcfc-f51c4f62e102">|
> fix(structure): add support to edit live documents in published perspective

- packages/sanity/src/structure/components/pane/PaneHeader.tsx
Previously the difference in height on the document pane header weren't very noticeable as it was perceived as a toolbar with two rows, while presentation tool and tasks were single row.
Annotated with guides
This changed with #7462, which moved the revision dropdown into the top row, making the toolbar single row as well unless custom tabs are defined in structure builder:
With guides:
For neurodivergents like me this tiny misalignment becomes a constant distraction and frustrating. It's like an airhorn, and there is no noise cancelling headphones. So I had no choice but to make this PR 😅
Now it's perfectly balanced, like everything should be:
Without regressing the custom tabs layout
Test the document tabs, I hope I haven't missed a spot 🙌 
Existing tests should be sufficient.
Fixed a …
> fix: vertically center pane header when no tabs

- packages/sanity/src/core/components/StatusButton.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.styled.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.tsx
In order to support new tones introduced in Sanity UI, we need to do some minor refactoring to internal studio components.
The reason why this is necessary, is that in 2 places we rely on Sanity UI v1’s theming object in a way which is not future compatible.
The most elegant solution to this is to remove dependency on the theme object, and use CSS variables and primitive components instead.
- The internal `StatusButton` component has a little dot which can be colored. This PR changes how this dot is colored to using a CSS variable instead of accessing the theme object. Please review that the color application works as intended.
- The internal `Overlay` component within the `ImagePreview` component – which shows when dragging a file from the OS on top of an image field – can be toned …
> fix(sanity): support future UI tones

- packages/sanity/src/core/releases/__telemetry__/releases.telemetry.ts
- packages/sanity/src/core/releases/hooks/useVersionOperations.tsx
- packages/sanity/src/core/releases/tool/detail/AddDocumentSearch.tsx
- packages/sanity/src/core/releases/util/util.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/operations/types.ts
- packages/sanity/src/core/util/draftUtils.ts
- packages/sanity/src/core/util/getDocumentVariantType.ts
- test/e2e/tests/navbar/appearanceMenu.spec.ts
Renames `VersionOriginType` to `DocumentVariantType`, given this type is useful in more contexts not only the creation of a document.
This type will indicate the type of document we are working with according to the id.
If it's a document that starts with `version` it's a version document.
If it's a document that starts with `drafts` it's a draft document.
Otherwise, it's a published document.
It's quite obvious when you see the id, but exposing a function that we can use to get this information in a type safe way is necessary when we need the ui, or other internal functions, to react different according to the type of document we are using.
> fix(core):  `VersionOriginType` to `DocumentVariantType`

- packages/sanity/src/core/releases/tool/components/ReleasePublishAllButton/ReleasePublishAllButton.tsx
This restores the changes introduced in https://github.com/sanity-io/sanity/pull/7862 which seems to be lost from the `corel` branch.
Once a released is published (archived), it should be unpinned if it was pinned, to avoid bugs in the rest of the system.
> fix(core): when publishing a release unpin it

- packages/@repo/package.bundle/src/package.bundle.ts
[When using both `autoUpdates: true` and `reactCompiler: {target: '18' | '19'}`](https://github.com/sanity-io/community-studio/blob/52042ca23eecd0d853439a2f79e2d248abf612fe/sanity.cli.ts#L8-L10) then only userland custom studio code is compiled, while the `sanity` and `@sanity/vision` modules are not.
I thought we were pulling these packages off of npm, I wasn't aware they had their own vite pipeline 😅 
It turns out that if `autoUpdates: true` is in use, then the `sanity` and `@sanity/vision` code isn't pre-compiled by React Compiler.
I'm not super familiar with how this pipeline is setup, so I hope it's the right place 😮‍💨 
I don't know how we can test this e2e without publishing. I've verified that other libraries that are pushed out, like `@sanity/ui`, as well as custom studio code, …
> fix: support react compiler for auto updating studios

- test/e2e/tests/document-actions/unpublish.spec.ts
- As part of making sure we have more e2e tests for actions. The unpublish one was specifically pointed out.
Overall health of test
This PR is just a e2e test
N/A
> test(e2e): add unpublish e2e test

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/actions/init-project/bootstrapLocalTemplate.ts
- packages/@sanity/cli/src/actions/init-project/bootstrapRemoteTemplate.ts
- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/src/actions/init-project/updateInitialTemplateMetadata.ts
- packages/@sanity/cli/src/commands/init/initCommand.ts
- packages/@sanity/cli/src/types.ts
- packages/@sanity/cli/src/util/getProviderName.ts
- packages/@sanity/cli/src/util/journeyConfig.ts
- packages/@sanity/cli/src/util/remoteTemplate.ts
- packages/@sanity/cli/test/init.test.ts
- pnpm-lock.yaml
A remote template is really any GitHub repo that passes a given set of requirements.
The requirements are:
1. **package.json**  
- Each package must have a valid `package.json`.  
- At least one package must include `sanity` in its `dependencies` or `devDependencies`.
2. **Sanity Configuration Files**  
- At least one package must include both `sanity.config.js/ts` and `sanity.cli.js/ts`.
3. **Environment Template Files**  
- Each package must have at least one of the following:
- `.env.template`
- `.env.example`
- `.env.local.example`
1. **package.json**  
- The repository must have a valid `package.json` with `sanity` listed in `dependencies` or `devDependencies`.
2. **Sanity Configuration Files**  
- The repository must include both `sanity.config.js/ts` and `sanity.cli.js/ts`.
3. …
> feat(cli): add support for remote templates with `--template` 

- packages/@sanity/vision/src/SUPPORTED_PERSPECTIVES.ts
- packages/@sanity/vision/src/components/VisionGui.tsx
- packages/@sanity/vision/src/perspectives.ts
https://github.com/sanity-io/sanity/pull/7935 broke (internal) vision types because of the changes introduced in https://github.com/sanity-io/client/pull/934
This is a quickfix that shows a warning if you try to paste an url with a perspective param not included in the allowlist defined here. This should fix the issue at hand, and be good enough for now until we land support for releases/perspective layering in vision
Does the change look ok?
The tests should be sufficient here.
n/a - this warning would likey not appear to anyone for a while
> fix(vision): add a warning about unsupported perspective when pasting

- packages/sanity/src/core/form/components/Details.tsx
- packages/sanity/src/core/form/inputs/files/ImageToolInput/ImageToolInput.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
The fact that hotspot and crop won't be applied to SVG images is [unexpected](https://github.com/sanity-io/sanity/issues/2966) and can easily become a time sink to debug because it fails silently, and we don't offer much docs around it either (at least to my knowledge). This PR adds a gotcha to the hotspot/crop UI in case you're setting it on an SVG.
Note: I believe we still want to alow setting hotspot/crop for SVGs because it works fine when appending `fmt=jpg` to the image url.
- Is the phrasing clear/sensible? Note: this message might appear a bit confusing to non-devs. I don't think we have an easy way to tell whether the current user is a developer or not, and I think it's an OK tradeoff showing it to everyone. I did consider only showing it during DEV, but I think that would make …
> fix: add svg hotspot+crop gotcha to image tool dialog

- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Decorators.spec.tsx
- packages/sanity/src/structure/components/pane/PaneMenuButtonItem.tsx
- packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
- packages/sanity/src/structure/util/toLowerCaseNoSpaces.tsx
- test/e2e/tests/document-actions/delete.spec.ts
- test/e2e/tests/document-actions/discardChanges.spec.ts
- test/e2e/tests/document-actions/publish.spec.ts
- test/e2e/tests/document-actions/restore.spec.ts
- test/e2e/tests/document-actions/unpublish.spec.ts
- test/e2e/tests/inputs/date.spec.ts
- test/e2e/tests/inputs/datetime.spec.ts
- test/e2e/tests/inputs/reference.spec.ts
- test/e2e/tests/inputs/text.spec.ts
- test/e2e/tests/tree-editing/TreeEditingBasicInteraction.spec.ts
- We had some e2e tests that were disabled due to being unreliable while work with the Actions was on going. As things seem more stable, this PR brings back those tests.
- Some updates had to be done to data-test ids since a lot of them were breaking (not correctly formatted, hence why the large number of files)
Review tests and make sure they make sense, I have tried reducing the flakiness but they are e2e tests so 🫠 any pointers would be appreciated.
This PR is just tests 
N/A
> test(e2e): restore last e2e tests

- packages/sanity/src/core/scheduledPublishing/tool/Tool.tsx
- packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.test.tsx
- packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.tsx
- packages/sanity/src/core/tasks/context/enabled/TasksEnabledProvider.test.tsx
- packages/sanity/src/core/tasks/context/enabled/TasksEnabledProvider.tsx
Some users have reported that they see the upsell ui even though the feature is enabled for the project.
That is due to the `features` api returning an error if the user doesn't have the right permissions to query it.
This PR adds the same check for `scheduledPublishing` and `tasks` plugins.
In `comments` we are currently doing that check here https://github.com/sanity-io/sanity/blob/edx-1599/packages/sanity/src/core/comments/hooks/useResolveCommentsEnabled.ts#L42-L43
Are this changes ok?
New tests have been introduced to guard this behavior.
Disable schedule publishing and tasks plugin if user doesn't have the right access.
> fix(core): disable scheduledPublishing and tasks if `/features` returns error

- packages/@sanity/vision/src/components/ResultView.tsx
- packages/@sanity/vision/src/components/VisionGui.tsx
Suggestion: Add a link icon next to each _id and _ref attributes
Is this "safe"? Ref #6074 the user might be querying another dataset 🤔  Though it provides an easy way to inspect a document.
N/A
> feat(vision): link to edit documents

- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveList.test.tsx
What it says on the tin :) 
- fix issue where you could click the published chip even when the published doc didn't exist
See video for a before:
https://github.com/user-attachments/assets/3acf5453-e9b2-4be8-89b3-e4703e127285
Does it make sense? Did I miss something?
Tests should be enough
> fix(sanity): fix issue where you could click the published chip even when the published doc didn't exist

- test/e2e/tests/document-actions/unpublish.spec.ts
- Updated the test, the message has changed since the document pane and writing in documents has changed. It not longer shows a message once the unpublish goes through (in the footer)
wow, can you believe a e2e test was failing NOT because it was flaky but because it captured a regression??
> test(e2e): update unpublish test to match update

- packages/sanity/package.json
- pnpm-lock.yaml
Fixes a minor issue where the preview iframe initially loads with `perspective=previewDrafts` regardless of `usePerspective().selectedPerspectiveName`, causing a "flash of draft content" before the `usePerspective().perspectiveStack` state is applied to the preview.
> fix(deps): bump `@sanity/presentation` to `1.19.5-release.3`

- packages/sanity/src/core/form/inputs/files/ImageToolInput/ImageToolInput.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
I know this went through a review already, but I still have some issues with the current wording:
- "Bitmap" is less precise than "raster" in my opinion. Whether or not the raster format uses a bitmap internally is irrelevant.
- "SVG" is too specific - we might support other vector formats in the future, which will have the same restrictions.
- The i18n strings should preferably describe the _purpose_ of the string, not the contents per se. This helps the AI translator understand it better. There was also a typo in the comment (`fp` instead of `fm`).
New messages/keys looks accurate/correct
Same as before, only strings changed.
None
> fix: reword warning about vector images not support crop/hotspot

- packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.test.ts
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts
This branch fixes global search pagination bugs caused by the cursor state not correctly being reset when some input parameters change. For example, when removing a filter, the cursor was not being reset. This could cause the next result set to be fetched using a cursor for the previously active set of filters.
This isn't currently a problem, because global search results aren't paginated. However, we will begin using pagination when we soon introduce the new GROQ search strategy.
- Global search input parameters and predicated builder (e.g. filters).
- Added unit tests to the reducer to ensure cursor state is reset when input parameters change.
> fix(sanity): reset search cursor state when any parameter changes

- packages/sanity/src/core/studio/StudioTelemetryProvider.tsx
#7958 seems to have caused an issue (see #7964) in environments that doesn't define `process` globally.
Fixes #7964
- Fixes an issue causing the Studio to crash in an environment that doesn't provide a global `process` variable
> fix(core): guard against missing process variable

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/__tests__/ReleaseMenuButton.test.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardFooter.tsx
For scheduled or scheduling releases, the release menu button now gives an option to unschedule from the releases overview list
Added a new test block for `ReleaseMenuButton`
N/A
> feat(releases): unschedule release from release menu button menu

- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveList.test.tsx
Fix issue where the publish disable wasn't working as expected.
I have added tests to match all the use cases that I could think of for when it is disabled :)
Does it make sense? could I have done it in a different better way?
The tests should be good enough but just to be sure go to the preview and try with documents **that don't** have published documents (from an existing version seeing if the chip is enabled when you know there is no published doc) and when there is.
> fix(sanity): issue with the publish chip disable + update tests

- packages/sanity/package.json
- pnpm-lock.yaml
Brings the same minor bugfixes to the content releases version of `@sanity/presentation` that shipped on the stable channel (#7966)
> fix(deps): bump `@sanity/presentation` to `1.19.8-release.0`

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/index.ts
- packages/sanity/src/core/releases/hooks/index.ts
- packages/sanity/src/core/releases/hooks/useIsReleaseActive.ts
- packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentButton.tsx
- packages/sanity/src/structure/components/paneHeaderActions/PaneHeaderCreateButton.tsx
Currently if you are in published perspective or a scheduled release perspective, trying to add a new release in studio will show a new draft has been created but will be read only. The global perspective will remain as published or scheduled release even though the document form is showing a draft.
This change disables the UI elements that allow for creating documents in these scenarios.
NOTE: currently the tooltip clarification is the same for published as it is for a scheduled release. This should probably be made clearer to avoid confusion by separating these 2 scenarios, but I'd rather get this initial change in, and can then follow up once the copy has been confirmed later.
There aren't currently any tests for these components or for their parents, so adding testing coverage here is …
> fix(releases): blocking UI elements that allow for adding documents to inactive releases

- packages/sanity/src/core/i18n/types.ts
- packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/datePicker/calendar/CalendarMonth.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/datePicker/calendar/contexts/CalendarContext.ts
- packages/sanity/src/ui-components/inputs/DateInputs/calendar/CalendarMonth.tsx
Certain locales start their week on Saturdays - Nepal, Iran and certain other middle eastern cultures. This PR allows the studio to reflect this.
Week day extractions seem correct
No added tests, and we currently don't have any language packs to exercise this with.
None
> fix(i18n): allow weeks to start on Saturday

- packages/@sanity/types/src/schema/definition/type/slug.ts
- packages/sanity/src/core/validation/validators/slugValidator.ts
Adds `disableArrayWarning` to the `SlugOptions` interface. Purpose is to allow users to disable the automatic array warning for slug fields within arrays.
Below is warning seen in the console.
Following the steps suggested by the warning works and stops the warning from showing up. However, if the developer creating the schema is using TypeScript they are hit with the following error
So adding `disableArrayWarning` removes that TS error.
Also a change to the `schemaOptions` `const` within the `slugValidator.ts` file as its type assertion is not needed due to `disableArrayWarning` is now included within the `SlugOptions` interface.
Review the changes to the `SlugOptions` interface found in the `slug.ts` file and to the `defaultIsUnique` function, specifically the `schemaOptions` variable`. …
> feat: add disableArrayWarning option to SlugOptions

- dev/test-studio/package.json
- dev/test-studio/sanity.config.ts
- dev/test-studio/schema/plugins/color.tsx
- pnpm-lock.yaml
It was removed some time back, it's useful to have it for perf testing reasons, and to make easier detect if changes in the studio breaks the plugin
Try it here https://test-studio-git-ad-back-color-input-plugin.sanity.dev/test/structure/input-plugin;colorTest;0575367a-08b6-4b88-b953-2cbf5e63fc55 it works 🥳 
N/A
> chore: add back the `@sanity/color-input` plugin to test studio

- dev/studio-e2e-testing/package.json
- dev/studio-e2e-testing/sanity.config.ts
- pnpm-lock.yaml
[#7502](https://github.com/sanity-io/sanity/issues/7502) & [#7475](https://github.com/sanity-io/sanity/issues/7475) broke the e2e test suite because the e2e Studio is importing the schema types from the `test-studio` but those PRs didn't add the required plugins to the e2e Studio config.
If CI is happy we should be good
n/a
> test(e2e): add missing plugins to e2e studio

- packages/sanity/src/core/releases/store/createReleaseStore.ts
- packages/sanity/src/core/releases/store/reducer.ts
Removes unused  `releaseStack` from releasesStore.
We are using the `perspective` from `usePerspective` for this, nothing is populating the `releaseStack` value.
> chore(core): remove `releaseStack` from releasesStore

- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveList.test.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
**Enables the **published chip** for `liveEdit` documents.**
Live edit documents are only editable through the published perspective, we need to enable it even if the published document doesn't exists.
For the rest of documents, validate if the `published` document exists.
**Update actions data-testid**
action tests were failing because the test id was not found, this updates them to match what we have in `next` .https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx#L62
> fix(structure): enable published chip for live edit documents

- dev/test-studio/sanity.config.ts
- packages/@sanity/types/src/search/types.ts
- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/search/common/__tests__/tokens.test.ts
- packages/sanity/src/core/search/common/deriveSearchWeightsFromType2024.ts
- packages/sanity/src/core/search/common/index.ts
- packages/sanity/src/core/search/common/token.ts
- packages/sanity/src/core/search/common/types.ts
- packages/sanity/src/core/search/groq2024/createGroq2024Search.ts
- packages/sanity/src/core/search/groq2024/createSearchQuery.test.ts
- packages/sanity/src/core/search/groq2024/createSearchQuery.ts
- packages/sanity/src/core/search/groq2024/getNextCursor.test.ts
- packages/sanity/src/core/search/groq2024/getNextCursor.ts
- packages/sanity/src/core/search/groq2024/index.ts
- packages/sanity/src/core/search/search.ts
- packages/sanity/src/core/search/text-search/createTextSearch.test.ts
- packages/sanity/src/core/search/text-search/createTextSearch.ts
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/SearchResults.tsx
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/SearchProvider.tsx
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.test.ts
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts
This branch introduces a new search strategy: `groq2024`. This strategy adopts GROQ's new `text::query` function and ability to match all text content inside an object using `@ match text::query($query)`. This enables dataset search without necessitating every searchable path in the schema is serialised and included in the search request (as is the case with `groqLegacy` search).
This experimental strategy is being added to Studio behind a flag so that interested users can help us test it, before it hopefully graduates to being the default search strategy.
To enable this strategy, set `search.strategy` to `"groq2024"` inside the Studio config.
```diff
import {defineConfig} from 'sanity`
+ search: {
+   strategy: 'groq2024',
+ },
})
```
- Test Studio has been …
> feat: add `groq2024` search strategy

- packages/sanity/src/core/search/common/__tests__/deriveSearchWeightsFromType.test.ts
- packages/sanity/src/core/search/common/deriveSearchWeightsFromType.ts
When working on schemas that branch out a lot (i.e. have arrays that can hold many different types), the current `getLeafWeights` implementation throws with a `RangeError: Maximum call stack size exceeded` after a while.
This PR optimises the method to use an accumulator instead, which keeps the stack usage flat and no longer overflows for the same amount of data. I have also added a test to verify this (it used to explode with the previous version, see screenshots).
In addition, this PR optimises the method to be much more efficient by:
- Merging the loops for `objectTypes` and `arrayTypes` into one
- Adding a few extra tiny optimisations
As a result, this should be much faster and no longer explode the stack.
* We originally ran into this when rendering a document list once the schema …
> fix(sanity): optimise getLeafWeights to not stack overflow

- packages/@sanity/cli/src/actions/init-project/bootstrapLocalTemplate.ts
- packages/@sanity/cli/src/studioDependencies.ts
Depends on https://github.com/sanity-io/eslint-config-studio/pull/41
Bootstrap new studios with ESLint 9 and the new version of the studio ESLint configuration.
Part of SAPP-1961
Part of SAPP-1690
- Bootstrapped files look correct
Should be able to test this out by building and bootstrapping a new studio, but changes are also small enough that upgrading and replacing the config file as per the PR will let you test this out
- Use ESLint 9 for new studios
> feat: use eslint 9 for new studios

- dev/test-create-integration-studio/sanity.config.ts
- packages/sanity/src/core/config/prepareConfig.ts
- packages/sanity/src/core/create/components/StartInCreateDevInfoButton.tsx
- packages/sanity/src/core/create/components/constants.ts
This PR enables the "Start in Create" banner by default for all documents (essentially running back #7884). Please note that Create is still in early access.
This also updates a few Create links to now use URLs provided by our link management service (should they need to be updated in future).
- In the test studio, all documents will now include this banner by default.
- In the test create integration studio (`dev/test-create-integration-studio`), you can find an example where this has been disabled for a specific workspace.
This is in-flight and will be added separately by @mmgj
> feat: switch create integration to opt-out flow

- packages/sanity/src/core/store/translog/getTransactionLogs.ts
Extracts the logic to consume from the transactions logs.
This is WIP, and part of another branch, but Jordan needs to use it in his branch, so pushing this as a standalone change.
Tests will come in the other PR
> chore(core): add new function getTransactionsLogs

- packages/sanity/src/core/store/events/createEventsObservable.ts
- packages/sanity/src/core/store/events/utils.ts
- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/DocumentEventsPane.tsx
- packages/sanity/src/structure/panes/document/DocumentPane.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/ArchivedReleaseDocumentBanner.tsx
- packages/sanity/src/structure/panes/document/useResetHistoryParams.ts
Fixes some issues with releases history:
- Refreshing the browser or linking to a revision parameter was not persisted. [fix(structure): reset historyParams only if selectedPerspective changes](https://github.com/sanity-io/sanity/commit/837089adb1fd086d95e7c0ebc6f91d0645f355fb)
- Version documents showing `draft` when inspecting them as part of an archived/published release  [fix(core): update version events documentId](https://github.com/sanity-io/sanity/commit/eb8e1054b0e6a2a57891d86a93b5a9bb2d2bc5f1)
- Adds the release title to the archived document banner
| <img width="926" alt="Screenshot 2024-12-10 at 16 26 31" src="https://github.com/user-attachments/assets/17248bcf-334c-4878-84b2-87f64b27c1e2"> | <img width="960" alt="Screenshot 2024-12-10 at …
> fix(core): documents history fixes

- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleasePublishAllButton.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx
Adds a second publish action using the new action `sanity.action.release.publish2`. which is being developed.
To enable it, you need to add `publish2: true` in local storage
> feat(core): corel  publish 2 action - test

- packages/@sanity/cli/package.config.ts
- packages/@sanity/cli/package.json
- pnpm-lock.yaml
This removes the `is-builtin-module` package since all node versions within our `engine` constraint already have such a function built in.
This also allows us to remove the temporary workaround we had around `string_decoder/` since the built in function will not have such a bug.
The CLI should be the only affected package.
Existing tests should cover this.
N/A
> feat(cli): remove is-builtin-module

- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseDocumentPreview.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx
- packages/sanity/src/core/releases/tool/detail/review/DocumentReviewHeader.tsx
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/documentPanel/banners/ArchivedReleaseDocumentBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
For an archived release can view version documents; clicking through will show the historical version document and a temporary archived release chip
---
For a published release can view version documents; clicking through will show the historical version document within the published perspective
N/A
> feat: showing documents in archived and published releases

- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/src/actions/login/login.ts
- packages/@sanity/cli/src/commands/logout/logoutCommand.ts
- packages/@sanity/cli/src/outputters/cliOutputter.ts
- packages/@sanity/cli/src/types.ts
- packages/@sanity/cli/src/util/generateCommandsDocumentation.ts
- Added new method `success` in `cliOutputter`. This logs a message with a `chalk.green('✓')` in front
- Adjusted warn method to have `chalk.yellow('⚠')` in front
- Adjusted error method to have `chalk.red('✗')` in front
- Slight modification on intro message
- Modified login copy
- Modified logout print method to use success method instead
- Sanity command suggestions are now prefixed with `npx`
- Are there any typos?
- Does the new copy make sense?
Run 
```shell
sanity init
```
```shell
sanity logout
```
```shell
sanity login
```
N/A
> feat(cli): misc copy changes

- package.json
- packages/sanity/package.json
- packages/sanity/playwright-ct.config.ts
- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Decorators.spec.tsx
- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Toolbar.spec.tsx
- packages/sanity/playwright-ct/tests/utils/testHelpers.tsx
- perf/tests/package.json
- pnpm-lock.yaml
I have identified several issues that caused the `playwright-ct` tests to be flaky.
Some were real issues, some were with the library itself, and some were issues with the tests (see individual commits for details).
I have upgraded the Playwright packages used in the mono-repo.
There might still be flake, but this should help at least.
This PR is also tied into https://github.com/sanity-io/sanity/pull/8021 and https://github.com/sanity-io/sanity/pull/8022 which was moved into own separate PRs
* That the tests pass and have become less flaky.
Should be tested automatically.
N/A
> test(playwright-ct): fix issues and flake

- packages/sanity/src/core/create/components/StartInCreateBanner.tsx
- packages/sanity/src/core/create/types.ts
- packages/sanity/src/structure/panes/document/document-layout/DocumentLayout.tsx
Currently, the Start in Create banner will appear when a document pane is loading:
With this fix, the banner should no longer appear when the document pane is in a loading state.
Got a report that the Start in Create banner was breifly flashing (appearing and disappearing for < 500ms) on localhost.
I was unable to reproduce _that_ issue, but noticed that when running on 3G Network, the Create banner will render whilst the document is loading.
This PR delays rendering the banner until the document is ready. Opted for prop-drilling to get the ready state, as not to add any new useDocumentPane calls.
The ready check is done in the wrapper component where appId checks runs; this allows the initial requests to run in parallel with document load, so the data is ready as soon as possible.
The …
> fix: delays rendering the Start in Create banner until document is ready

- .github/workflows/e2e.yml
The key here should be made from `env`, and not `vars`.
As proved by cache names under https://github.com/sanity-io/sanity/actions/caches
Invalid entry for e2e:
Valid entry for component tests:
> test(e2e): refer to correct env variable for Playwright version

- packages/sanity/src/core/field/diff/components/Event.tsx
- packages/sanity/src/core/field/diff/components/constants.ts
- packages/sanity/src/core/store/events/getDocumentChanges.ts
- packages/sanity/src/core/store/events/getEditEvents.test.ts
- packages/sanity/src/core/store/events/getEditEvents.ts
- packages/sanity/src/core/store/events/types.ts
- packages/sanity/src/structure/panes/document/DocumentEventsPane.tsx
- packages/sanity/src/structure/panes/document/inspectors/changes/EventsSelector.tsx
- packages/sanity/src/structure/panes/document/timeline/events/EventTimelineItem.tsx
- packages/sanity/src/structure/panes/document/timeline/events/EventsTimeline.tsx
- packages/sanity/src/structure/panes/document/timeline/events/EventsTimelineMenu.tsx
Content lake has renamed the events types that are returned from the events api to camel case.
This reflects that update in the studio.
> fix(core): release events types are lowercase

- packages/sanity/src/core/form/field/actions/FieldActionMenu.tsx
Chromium and Firefox will tab to the FieldActions menu without tabIndex=0, but Webkit needs to have it explicitly set to include it in the tab flow. Add it so all browsers follow the same tab order, and WebKit users can access the field actions with the keyboard.
This will also prevent issues with Playwright tests that rely on tabbing through forms.
That WebKit can tab into the field actions menus.
Test any form with multiple fields.
* Fixed an issue where WebKit was unable to tab into a form field's action menu.
> fix(core): fix issue with different Webkit tab order in forms

- packages/sanity/src/core/hooks/useRelativeTime.ts
It appears React Compiler is failing to see the base comparison date (`now`) as a dependancy when using `useRelativeTime` to calculate a relative date. This causes the base comparison date (`now`) to become stale, resulting in the relative date incorrectly appearing to be in the future.
This affects the History inspector. Changes made externally (e.g. by another editor or the API) after the page loads may appear to be from the future:
Spooky! 👻
Switching off auto-memoization for `useRelativeTime` appears to solve the problem for now.
- Does this seem reasonable?
1. When viewing a document, open the History inspector.
2. In another tab, or via the API, mutate the document you are viewing.
3. In the original tab, the change should never appear to be in the future.
Fixed a bug that could …
> fix(sanity): relative dates incorrectly appearing to be in the future

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/actions/init-project/bootstrapRemoteTemplate.ts
- packages/@sanity/cli/src/util/remoteTemplate.ts
- pnpm-lock.yaml
- Stripping away all template validation logic away from the CLI
- Using the `@sanity/template-validator` package for validating
- remove `yaml` dependency
Fixes GRO-3004
The lock file diff seems very large for some reason. Am I doing something wrong? 
N/A
N/A
> feat(cli): use `@sanity/template-validator` package

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
PTE emits a single `'ready'` event when it's done syncing the initially provided `value`. Therefore, it's best to treat it as (and make it look) read-only until that event has been emitted.
As of v1.6.0 PTE also treats itself as read-only until it's done setting up: https://github.com/portabletext/editor/releases/tag/editor-v1.16.0
It is especially important to respect the `'ready'` event since in the near-future PTE will **stream** the initial value in order to not block the main thread if the value is thousands of blocks long.
Note: I noticed that the Studio's PTE wrapper (and perhaps PTE itself too) does not fully respect it's own `readOnly` prop. For example, it seems like you can edit annotations while in read-only. However, it's outside of the scope of this commit to fix that.
Is …
> fix(core): make PTE read-only until it's `'ready'`

- packages/@sanity/cli/src/outputters/cliOutputter.ts
Slight regression from #8003 where I started joining console arguments. 
This ended up breaking string format specifiers making prints like this: 
```ts
success('You are logged in as %s using %s', user.email, getProviderName(user.provider))
```
render like this:
```shell
✓ You are logged in as %s using %s rosti@sanity.io Google
```
Run
```shell
sanity init
```
See if the intro command look like this again
```shell
✓ You are logged in as rosti@sanity.io using Google
```
N/A, as #8003 hadn't reached a release yet.
> fix(cli): outputters should respect %s

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/hooks/usePerspective.tsx
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/releases/navbar/GlobalPerspectiveMenuItem.tsx
- packages/sanity/src/core/releases/navbar/PerspectiveLayerIndicator.tsx
- packages/sanity/src/core/releases/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/releases/navbar/useScrollIndicatorVisibility.ts
Adds `drafts` to the perspective menu list and adds the ability to hide it.
This is specially useful when previewing content in `presentation` or other tools, to avoid adding the `drafts` to the list of perspective stack.
Are this changes correct?
New tests added for this new behavior
> feat(core): option to exclude draft perspective 

- packages/@sanity/cli/src/util/remoteTemplate.ts
Filter away .github directories when initializing with a remote template. This is to prevent potential security risks from running unknown actions if the user decides to push their project to GitHub
Fixes GRO-3053
Are there any more directories we should omit?
Run
```shell
sanity init --template sanity-io/sanity-template-nextjs-clean
```
See if the directory includes a .github folder
N/A
> feat(cli): remove .github dirs when initializing with a remote template

- packages/@sanity/cli/src/actions/init-project/bootstrapRemoteTemplate.ts
- packages/@sanity/cli/src/util/frameworkPort.ts
- packages/@sanity/cli/src/util/remoteTemplate.ts
- Made a map of all the default ports for all frameworks listen in `@vercel/frameworks`
- Using said map to automatically apply a CORS entry per package in template
Fixes GRO-3036
Run
```shell
sanity init --template sanity-io/sanity-template-nextjs-clean
```
See if http://localhost:3000 was added in Manage for your project
N/A
> feat(cli): add cors entry automatically for template package

- packages/sanity/src/core/form/inputs/PortableText/object/modals/PopoverModal.tsx
* Remove the workaround for the @sanity/ui issue (which has been fixed) with the initial rendering in the wrong position. This is no longer needed and can cause problems with assertions in tests.
* Implement focus locking inside the modal. The PopoverModal should have the same kind of focus locking as other dialogs
That popover modals for links inside the Portable Text Input traps focus and work as expected.
The popover modal position is correct when first opened.
Open a Portable Text Editor with a link schema type and do the review steps above.
* Keep tab focus inside Popover Dialogs for the Portable Text Input when editing links and similar.
> fix(core): fix issues with PT-Input PopoverModal

- package.json
- packages/@repo/test-config/package.json
- packages/@sanity/block-tools/package.json
- packages/@sanity/cli/package.json
- packages/@sanity/codegen/package.json
- packages/@sanity/migrate/package.json
- packages/@sanity/mutator/package.json
- packages/@sanity/schema/package.json
- packages/@sanity/types/package.json
- packages/@sanity/util/package.json
- perf/tests/package.json
- pnpm-lock.yaml
Gets rid of some peer dependency warnings.
Tests still run as before.
No changes needed.
None.
> chore(deps): upgrade vitest to v2.1.8

- packages/@sanity/vision/package.json
- packages/@sanity/vision/src/components/ResultView.tsx
- packages/sanity/package.json
- packages/sanity/src/structure/panes/document/inspectDialog/InspectDialog.tsx
- pnpm-lock.yaml
Upgrades `@rexxars/react-json-inspector` to the latest version, which is compatible with React 19 and drops lifecycle events that are deprecated. The conversion was a bit quick and dirty, but from what I can tell things seems to work fine.
"Inspect document" and vision results works as expected
Check out the preview deployment, see that it matches current look/behavior
None
> fix(deps): upgrade react-json-inspector

- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
| ![summaryFlickerBeforePR](https://github.com/user-attachments/assets/6dbbb877-5fb5-4c50-bc48-96b37819285c) | ![summaryFlickerAfterPR](https://github.com/user-attachments/assets/985c3ecf-2766-490e-9c84-4d9a828be54e) | 
* Moved to using a getter style pattern for creating the observables eg:
```
const getObservable = () => ...
...
const memoObservable = useMemo(() => getObservable(), [])
```
* Using `releasesState` from `releasesStore` to drive the emission for the returned observable (this removed the dependency on the mutable `releases` which was causing the flicker by returning a new observable each time `releases` changed
* Moved the existing `ActiveReleaseDocumentsObservable` into a getter
Existing tests act as regression
N/A
> fix(releases): stabilising observable for archived and published version documents

- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/RangeDecoration.spec.tsx
- packages/sanity/playwright-ct/tests/utils/testHelpers.tsx
Small improvement to make PTE tests less flaky.
> test(pte): properly wait for PTE to be editable

- packages/sanity/src/_singletons/context/HoveredFieldContext.ts
- packages/sanity/src/core/form/field/HoveredFieldProvider.tsx
- packages/sanity/src/core/form/field/actions/FieldActionsProvider.tsx
Every time a field is hovered, every field rerenders, even though each field is only interested if its hover state is `true` or `false`:
https://github.com/user-attachments/assets/8897e931-0ccd-4d75-a67f-b07e2ced7aa4
This is due to the context provider broadcasting the current field that has focus, to all its `useContext` subscribers. Even though each field only wants to know a boolean, they rerender even if the boolean haven't changed.
By refactoring to a simple `useSyncExternalStore`, we're able to use `getSnapshot` to control when renders happen. Since `getSnapshot` returns a boolean, it'll only re-render when the returned boolean actually changes. In other words, even if `getSnapshot` is called every time a field is hovered, the components subscribed to the store won't rerender unless …
> fix: speed up hovered field provider

- dev/test-studio/package.json
- dev/test-studio/sanity.cli.ts
- pnpm-lock.yaml
Follows up on code review comments by @bjoerge in #8032 :)
> chore: add follow up comments on million lint

- packages/@sanity/vision/package.json
- packages/@sanity/vision/src/components/VisionGui.tsx
- pnpm-lock.yaml
I've reworked `react-split-pane` to be compatible with React 19, and also upgraded the tooling to be ESM-forward as well as use named exports, drop prop-types and other ancient reactisms. Still could use a proper refactoring/perhaps use a different module, but should at least progress the React 19 story.
Vision still works, can resize panes. 
No new tests
None.
> fix(vision): upgrade react-split-pane to v1.0.0

- package.json
- packages/sanity/src/core/studio/colorScheme.tsx
- packages/sanity/src/core/studio/colorSchemeStore.ts
This refactor is mostly about making the React Compiler support optimizing the `ColorSchemeProvider` component, so it can be excluded from Million Lint reports and not show up as false positives (as it re-renders only when the color scheme is changed manually, which is rare).
Tested manually, unsure if our E2E suite checks color scheme switching 🤔 
N/A perf improvement too small to be worth calling out
> fix: improve color scheme store perf

- packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx
- packages/sanity/src/core/studio/components/navbar/presence/PresenceMenuItem.tsx
Fixes a performance issue in `<PresenceMenuItem />` causing edit intent links to constantly unmount and mount new dom nodes on every single render.
Tested manually, verified with `pnpm dev:million-lint` that the issue is resolved.
Links in the global presence dropdown menu had a bug that caused nodes to constantly unmount and remount, slowing down exponentially with how many people are in the studio at the same time. It now renders efficiently.
> fix: improve presence menu performance

- packages/sanity/package.json
- packages/sanity/src/core/components/commandList/CommandList.tsx
- packages/sanity/src/core/components/commandList/__tests__/CommandList.test.tsx
- packages/sanity/src/core/components/commandList/types.ts
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/ListArrayInput.tsx
- pnpm-lock.yaml
Moves the dependency out of the beta range, and **brings React 19 support** which is why this is happening _now_.
@binoy14 There were some minor crashes in the array input after upgrading - the `observeElementOffset` seems to need a second argument, `isScrolling`. I assumed that since we were calling this from a scroll handler it would be safe to set this to always be `true`, but we're also calling it once on "mount", at which point I am giving it `false`. Additionally, the virtual items seems to start at an empty array now, which crashed when attempting to use the first element in the styles. Can you see that things works as expected? I did some testing and to my eyes it appears to work fine.
@robinpyon I am requesting a review from you since you have been involved in multiple components …
> fix(deps): upgrade `@tanstack/react-virtual` to v3.11.2

- packages/sanity/src/core/comments/components/onboarding/CommentsOnboardingPopover.tsx
Driveby fix for a dev-error in Comments Upsell dialog I noticed:
Everything ;)
N/A
> fix: fixes unknown event handler error in CommentsOnboardingPopover

- packages/sanity/src/core/form/studio/inputs/client-adapters/assets.ts
- packages/sanity/src/core/preview/observeFields.ts
Occationally after uploading an image, the hotspot and crop icons remains greyed out forever.
Traced this down to being caused by us returning `null` from the batch fetcher we use to fetch previewed documents, in combination with a subsequent check for `undefined` to check if we need to refetch after document creations as a safeguard against initial indexing taking some time.
Commits can be reviewed one-by-one.
- The fix is in the first commit
- The second removes moot error handling: We're connected to a shared ("hot") observable emitting the "current preview value" so the retrying logic won't trigger any refetches here
- The third cleans up the code slightly and removes some unneccesary `as any` casts
A bit involved to add unit test for this particular case as it is highly dependent on …
> fix(preview): fix issue sometimes causing hotspot menu to stay a gray box after uploading

- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/SearchResults.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItem.tsx
Added a check for the `metaKey` property flag on the `MouseEvent` event. The goal here is that when you open the global search, you should be able to open multiple tabs with relevant documents from your search without needing to reopen the model every time.
As this is my first PR to the studio, I'm wondering if there are any things/flows I'm missing here. Seems like it should be ok, and I can't see any search related tests but please do let me know otherwise 😄
Probably not big enough to have anything here, but maybe something like `add more ergonomic search result handling for multiple documents`.
> fix: search modal stays open with metaKey

- packages/sanity/src/core/templates/__tests__/resolve.test.ts
Promise-based tests should be awaited - vitest complained about some tests not doing this. This PR fixes that
Tests pass
Tests are already in place, just needed to be async/awaited
None
> test: fix missing await on assertions for `resolveInitialValue()`

- packages/sanity/src/core/hooks/useRelativeTime.ts
Follows up on #8034, as the `'use no memo'` directive is meant as a short term fix.
The original issue is due to React Compiler working under the assumption that reactive values are in `useState`, `useReducer` or `useSyncExternalStore`.
Calling `Date.now()` during render is considered a side-effect, and also breaks in other scenarios, such as SSR Hydration (as `Date.now()` will return different values during server render and when the browser hydrates).
Since we already have a `useReducer` trick in place that is used to schedule re-renders on set intervals, the theory is that we can just move the `Date.now()` value as state in that same reducer.
The benefit of doing this is that it allows memoizing and reduce work during render, as the `useRelativeTime` hook might be called by its …
> fix: allow `useRelativeTime` to be auto-memoized

- dev/test-studio/components/panes/debug/DebugPane.tsx
- packages/sanity/playwright-ct/tests/formBuilder/utils/TestForm.tsx
- packages/sanity/src/core/components/scroll/scrollContainer.tsx
- packages/sanity/src/core/create/context/SanityCreateConfigProvider.tsx
- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/useReferenceInfo.ts
- packages/sanity/src/core/form/store/useFormState.ts
- packages/sanity/src/core/form/studio/FormBuilder.test.tsx
- packages/sanity/src/core/scheduledPublishing/hooks/useTimeZone.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/filters/filter/inputs/date/CommonDateRange.tsx
- packages/sanity/src/core/tasks/components/form/tasksFormBuilder/useTasksFormBuilder.ts
- packages/sanity/src/router/RouterProvider.tsx
- packages/sanity/src/structure/components/pane/PaneLayout.tsx
- packages/sanity/src/structure/components/pane/__workshop__/ResizeStory.tsx
- packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx
- packages/sanity/src/structure/panes/documentList/useDocumentList.ts
- packages/sanity/src/structure/structureResolvers/useResolvedPanes.ts
[From the React docs on `useMemo`](https://react.dev/reference/react/useMemo#caveats):
> **React will not throw away the cached value unless there is a specific reason to do that.** For example, in development, React throws away the cache when you edit the file of your component. Both in development and in production, React will throw away the cache if your component suspends during the initial mount. In the future, React may add more features that take advantage of throwing away the cache—for example, if React adds built-in support for virtualized lists in the future, it would make sense to throw away the cache for items that scroll out of the virtualized table viewport. This should be fine if you rely on `useMemo` solely as a performance optimization. Otherwise, a [state …
> fix: replace unsafe `useMemo` with `useState`

- packages/sanity/src/core/form/store/useFormState.ts
I missed these in #8047, the same description, release notes etc is applicable for this PR
> fix: replace useMemo with useState

- packages/sanity/src/core/studio/studioAnnouncements/StudioAnnouncementsDialog.tsx
Here is a video of what was happening before this change, you can see that the _Close_ tooltip is rendering at the end of the announcements dialog. I noticed also that now that we have more announcements and scroll that this is causing some layout shift.
https://github.com/user-attachments/assets/9ae5fac0-889d-4248-9efc-2a7e8099d455
It seems as though the container for the button component should have an extra `position: relative` in the container to stop the tooltip from flying around, what I have done to remedy this is to just add a container around the button in the dialog.
Whether this is something that should be tackled in `@sanity/ui` or whether we are ok to proceed with this approach.
n/a
n/a
> fix: tooltip position in announcements popup

- packages/sanity/src/core/preview/components/SanityDefaultPreview.tsx
Improves render performance on lists and reference previews by wrapping `SanityDefaultPreview` in `React.memo`, as well as by refactoring it to make full use of React Compiler.
Makes sense?
Existing tests should be enough.
Refactored `SanityDefaultPreview` to be auto memoized by React Compiler, improving performance on document list previews, and reference selectors.
> fix: improve `SanityDefaultPreview` memoization

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
`EditorProvider` is the new way of setting up the Portable Text Editor. It's
going to be the way we document how to use standalone PTE and it's the way
Create already uses PTE.
It exposes all the new APIs that have been under development, and for now it's
also 100% backwards compatible by the fact that:
1. No types or interfaces have been removed.
2. The old `usePortableTextEditor()` and `usePortableTextEditorSelection()`
hooks are still exposed.
3. Static methods like `PortableTextEditor.addAnnotation(...)` still work (even
though the `PortableTextEditor` React class isn't used to instantiate the
editor anymore.)
3. You can hand-roll custom "plugins" to achieve backwards compatible
behaviours like listening for a `value` prop change or forwarding a ref to
the `PortableTextEditor` …
> refactor(core): replace `PortableTextEditor` with `EditorProvider`

- packages/sanity/package.json
- pnpm-lock.yaml
Uses the same semver range as in [`@sanity/presentation`](https://github.com/sanity-io/visual-editing/blob/f46626032fc42c8eda2075b0badb489307f5cccd/packages/presentation/package.json#L59) and [`@sanity/ui`](https://github.com/sanity-io/ui/blob/a8935003d110c15404cb43098a0164d25fa7f438/package.json#L112).
It ensures that once `framer-motion` v11.16 and later comes out we won't have duplicate versions of `framer-motion` being loaded up.
Should make sense?
Existing tests enough.
Probably unnecessary since we just bumped `framer-motion` for react 19 support, unless we publish a studio release of that before merging this PR 🤔
> fix: use consistent `framer-motion` semver range

- packages/sanity/src/core/store/_legacy/ResourceCacheProvider.tsx
- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/_legacy/presence/presence-store.ts
- packages/sanity/src/core/store/_legacy/presence/useDocumentPresence.tsx
- packages/sanity/src/core/store/_legacy/presence/useGlobalPresence.tsx
Ever since I gave up on #7227 it's been in the back of my mind, and taunting me every time I've been in a studio and seen this warning:
```
WebSocket connection to 'wss://:projectId.api.sanity.io/v2022-06-30/socket/:dataset?tag=sanity.studio' failed: WebSocket is closed before the connection is established.
```
That ends today, I've finally found a stable workaround!
At some point we should dive into `@sanity/bifur-client` and find out exactly why [the observable teardown](https://github.com/sanity-io/bifur-client/blob/b6062c27c87b130fa179704885d42d96361027d7/src/createConnect.ts#L70) calling `ws.close` causes the warning, maybe we have to check `ws.readyState`? Maybe we can't avoid this warning if the observable is unsubscribed to before the connection is established, and while the …
> fix: `WebSocket is closed before the connection is established` warning

- packages/@sanity/codegen/src/typescript/__tests__/findQueriesInPath.test.ts
- packages/@sanity/codegen/src/typescript/__tests__/fixtures/import.astro
- packages/@sanity/codegen/src/typescript/__tests__/parseSource.test.ts
- packages/@sanity/codegen/src/typescript/parseSource.ts
if a file ends with astro we find all code fences and only attempt to discover queries inside those. We also append .ts to the filename to enable ts with the babel ts preset
* Correctness 
* Any test cases missing?
Added 👍 
feat: Add support for discovering queries in .astro files.
Fixes #6965
> feat(typegen): add support for astro

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/actions/init-project/bootstrapRemoteTemplate.ts
- packages/@sanity/cli/src/util/remoteTemplate.ts
- pnpm-lock.yaml
Bumping @sanity/template-validator to latest version (v1.2.1)
This version includes some api changes, so I've adjusted bootstrapRemoteTemplate to account for that
- Build the CLI and running `npm link`
- Run `sanity init --template sanity-io/sanity-template-nextjs-clean` in your terminal.
- Make sure template installs as expected
N/A
> chore(cli): bump template validator

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/actions/init-project/initProject.ts
- pnpm-lock.yaml
The primary motivation for this change is to get rid of silver-fleece as a dependency. See https://github.com/evertheylen/silver-fleece/issues/4 for more information about that problem.
This simply removes the functionality we used it for: Patching tsconfig.json to set `compilerOptions.target` to ES2017.
- The latest Next.js template already sets the target to ES2017.
- Even so, I've tested this against a newly configured Next.js app where I set `compilerOptions.target` to ES5 and `npm run dev` still worked. I'm not sure why this target is required anyway.
Think about scenarios where `sanity init` will be executed and if this change could lead to more confusing onboarding experience.
@RostiMelk tested this locally in his machine against a newly initialized Next.js project (Next.js 15).
> feat(cli): remove patching of tsconfig.json and thus silver-fleece dependency

- packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts
- packages/sanity/src/core/store/_legacy/document/getPairListener.ts
While testing #8110 I noticed that even when preloading, clicking a document would cause a new listener request to be made. 
Tracked this down to being caused by the memoization of the shared document pair listener. This PR fixes the issue by:
- Replacing the `connector.complete()` trick with instead exposing a `_keepalive` stream that we merge in with the (memoized &  shared) stream of the pair listener. This ensures that the listener connection will be kept open for as long as there are subscribers to the pair object.
- Moving the delayed reset to the memoized function (returning a pair listener for keyed by document id). This ensures that the delayed reset happens on the memoized observable itself, rather than the connection stream.
- Navigate to a document (A) in the Studio
- Make …
> fix(core): re-subscribes to shared pair listener opens a new connection

- package.json
- packages/sanity/src/structure/components/pane/Pane.tsx
- packages/sanity/src/structure/components/paneItem/PaneItem.tsx
By preloading the `editState` for a document it makes for a much snappier experience when navigating documents, here's a video demonstrating both side-by-side (with the new behavior on the left, and no preloading on the right):
https://github.com/user-attachments/assets/118162cb-0c06-4508-8c6d-774df83f5920
Is there enough inline context or should I add code comments?
Existing tests should capture regressions, otherwise the manual testing steps are demonstrated in the video 🙌 
Added preloading of documents when hovering them in document list panes. This speeds up the experience of navigating between documents pretty significantly.
> fix: preload documents on hover

- packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
Small follow up from #8120 – I mistakenly thought subscribing to commit stream was sufficient because I thought it built upon the listener, but turns out it wasn't so. This fix merges in listener stream with _keepalive.
The review procedure from #8120 should still hold water:
- Navigate to a document (A) in the Studio
- Make sure there is a single event source set up with the tag `sanity.studio.document.pair-listener`
- Navigate to another document (B)
- Make sure there is a single new event source set up with the tag `sanity.studio.document.pair-listener`
- Go back to document A before 10s has passed
- Verify that no request was made with the tag  `sanity.studio.document.pair-listener`
- Stay on document A for more than 10s
- Verify that the listener connection made for document B is now …
> fix(core): merge in listenerEvents in _keepalive stream

- packages/@sanity/types/package.json
- pnpm-lock.yaml
On React 19 I'm seeing build errors like this:
```
Type error: Argument of type 'ComponentType | ReactNode' is not assignable to parameter of type 'ReactNode | ComponentType<{}>'.
Type 'ComponentClass<{}, any>' is not assignable to type 'ReactNode | ComponentType<{}>'.
Type 'import("/vercel/path1/node_modules/@sanity/types/node_modules/@types/react/index").ComponentClass<{}, any>' is not assignable to type 'React.ComponentClass<{}, any>'.
Types of property 'contextType' are incompatible.
Type 'import("/vercel/path1/node_modules/@sanity/types/node_modules/@types/react/index").Context<any> | undefined' is not assignable to type 'React.Context<any> | undefined'.
Property '$$typeof' is missing in type 'import("/vercel/path1/node_modules/@sanity/types/node_modules/@types/react/index").Context<a …
```
> fix: support react 19 type definitions

- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseSummary.test.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
- packages/sanity/test/testUtils/setupVirtualListEnv.ts
- packages/sanity/test/testUtils/setupVirtualisedEnvironment.ts
With Tanstack Virtual being upgraded in Next, this introduces issues in testing environments where the size of virtual list items is 0px, resulting in none of them being rendered (failing tests). 
The workaround is already present in next, but has been abstracted into a function as it's quite likely this will need to be used in other places as there's no clear sign this will be rectified. 
This also necessitated some changes to the testing harnesses for `RealeasesOverview` and `ReleaseSummary` to ensure the virtual list isn't rendered until the exact sized parent is first. 
Tests updated and all now pass on COREL
N/A
> test(releases): fixing issues with virtual list and releases overview and summary tests

- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseRevertButton/__tests__/useDocumentRevertStates.test.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseRevertButton/useDocumentRevertStates.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseRevertButton/usePostPublishTransactions.ts
- packages/sanity/src/core/util/__tests__/draftUtils.test.ts
Wrongly, the translog for the version of the document in the published release was being used to derive the revert state for each document. This worked in most cases because the first translog record for the version document is copying the existing publish document - but this fails when the published document is updated before publish but after release creation; or in other cases such as when a document is unpublished in a release.
This PR updates this so that the translog of the published document is always used to lookup the transaction of the release publish. As previously this will also:
1. `usePostPublishTransactions` checks if there are any transactions after the publish tranaction
2. `useDocumentRevertStates` which derives the revert state by looking at the transaction 1 prior to …
> fix(releases): when reverting, published versions are used to derive translog

- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseTypePicker.test.tsx
> fix(releases): hiding calendar on release picker dialog when not scheduled release type

- packages/sanity/src/core/releases/tool/detail/ReleaseDetailsEditor.tsx
| https://github.com/user-attachments/assets/ff7e2ee0-081c-4817-aaa7-1a0d3ae3c034 | [9ea9222c-8d55-479b-ae48-d2a2d2ef59f3.webm](https://github.com/user-attachments/assets/d58c14ed-0c41-4f6a-9e55-901643071c8f) |
> fix(releases): remounting the title/description form for release when release being shown changes

- packages/sanity/src/core/releases/__fixtures__/release.fixture.ts
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleasePublishAllButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseTypePicker.test.tsx
> feat(releases): published label; unarchive server action; and fixture fix

- packages/sanity/src/core/releases/tool/overview/ReleaseCalendarFilter.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/queryParamUtils.ts
- packages/sanity/src/core/releases/tool/overview/useTimezoneAdjustedDateTimeRange.ts
> refactor: releasesOverview into utils and smaller components for calendar filter

- packages/sanity/src/core/releases/tool/components/Table/TableHeader.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseActivityListItem.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardActivityPanel.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/structure/panes/document/timeline/events/EventsTimeline.tsx
> chore: removing deprecated motion for motion.create

- packages/sanity/src/core/tasks/i18n/resources.ts
Trivial grammatical mistake fixed in i18n bundle
N/A
> chore(tasks): fixing typo in empty state title

- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
Fixes an issue in `useBundleDocuments` when a document schema is not found.
The studio is throwing an error and not allowing users to continue working:
```
{
"error": {
"stack": "Error: Schema type not found for document type "<type>"
"message": "Schema type not found for document type "<type>""
},
"eventId": null
}
```
> fix(core): do not throw if schemaType is not found

- packages/@sanity/cli/package.json
- pnpm-lock.yaml
Bump `@sanity/template-validator` to v2.0.0
- Build the CLI and running `npm link`
- Run `sanity init --template sanity-io/sanity-template-nextjs-clean` in your terminal.
- Make sure template installs as expected
N/A
> chore(cli): bump `@sanity/template-validator` to v2.0.0

- packages/sanity/playwright-ct/tests/formBuilder/utils/TestForm.tsx
- packages/sanity/src/core/tasks/components/form/tasksFormBuilder/useTasksFormBuilder.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
If an input component calls onChange() during the initial render cycle a quite unhelpful error will be thrown currently.
This PR improves the error message, providing developers with a more precise description of the issue.
Does the wording make sense?
n/a - no code paths are changed
n/a
> fix(sanity): throw a better error if onChange called during initial render 

- .github/eslint-compact.json
- .github/workflows/lintPr.yml
- dev/design-studio/package.json
- dev/page-building-studio/package.json
- dev/starter-studio/package.json
- dev/strict-studio/package.json
- dev/studio-e2e-testing/package.json
- dev/test-create-integration-studio/package.json
- dev/test-next-studio/package.json
- dev/test-studio/package.json
- examples/blog-studio/package.json
- examples/clean-studio/package.json
- examples/ecommerce-studio/package.json
- examples/movies-studio/package.json
- package.json
- packages/@sanity/block-tools/package.json
- packages/@sanity/cli/package.json
- packages/@sanity/codegen/package.json
- packages/@sanity/diff/package.json
- packages/@sanity/migrate/package.json
- packages/@sanity/mutator/package.json
- packages/@sanity/schema/package.json
- packages/groq/package.json
- packages/sanity/package.json
- packages/sanity/src/core/form/studio/assetSource/file/AssetRow.tsx
- perf/studio/package.json
- perf/tests/package.json
Makes ESLint errors on PRs a lot easier to deal with, as they show up on PR "Files changed":
I thought about adding `--quiet` to silence warnings, like the regular `pnpm lint` command is doing. But decided against it as the linter warnings are really noisy right now and I don't want the CI to mask over it, I want it to be honest so it motivates brave souls to clean up our linter config so it's no longer so noisy.
I tested this by introducing linter errors on `AssetRow.tsx`, like seen in the above screenshot. After seeing it working I fixed the linter issues and rebased.
N/A - only applies to monorepo.
> chore: add github problem matcher for PR linting

- package.json
- packages/sanity/src/core/tasks/components/form/tasksFormBuilder/FormCreate.tsx
- packages/sanity/src/core/tasks/hooks/useActivityLog.ts
- packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx
- packages/sanity/src/structure/panes/documentList/DocumentListPaneContent.tsx
Suppressing the linter on `react-hooks/exhaustive-deps` causes React Compiler to bail, as it can no longer determine if the optimization it plans to do will preserve the original behavior of how often and when `useEffect` hooks will fire.
It's also a bit dangerous to leave in the codebase as what may have started off as omitting a single value from the dependencies array, can over time lead to other values being omitted that would otherwise been caught be the linter.
For example `DocumentListPaneContent` have had its linter suppression for a long long time, and since then we have added `const {t} = useTranslation(structureLocaleNamespace)` and `t` should be a dependency, but it's not.
This PR removes all of them, and in the case of `useEffect` the `useEffectEvent` ponyfill is used to …
> fix: remove react-hooks linter suppression

- packages/sanity/src/structure/panes/document/DocumentPaneContext.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/comments/CommentsWrapper.tsx
- packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx
- packages/sanity/src/structure/panes/types.ts
Adds an option for the `DocumentPaneProvider` to opt out from checking the global release or version when determining the document id.
This is useful in cases where plugins need to use the `DocumentPaneProvider` but not have it checking for the global version, like in the case of `sanity-assist` which has a PaneProvider inside a inspector which allows you to edit a document that will give the actions to the assist ai
Updates the return type of the `DocumentPaneValue` and verifies that the value is correctly returned by the provider with the `satisfies` validation.
Is the new prop naming correct?
> fix(structure): add opt out option from releases in DocumentPaneProvider

- packages/sanity/src/structure/panes/document/DocumentEventsPane.tsx
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/types.ts
`Sanity assist ` uses a document defined as liveEdit so not using the global version is not enough, we need to force the published one.
So, this removes the `matchGlobalVersion` prop and changes it for a `forcedVersion` allowing the user to define which version to link the paneProvider to.
See the use for when we have a history item selected. 
Assist should do the folllowing:
```
<DocumentPaneProvider
{...props}
forcedVersion={{
selectedPerspectiveName:"published",
selectedReleaseId: undefined,
isReleaseLocked: false,
}}
/>
```
Is there a better naming we could use for the `forcedVersion` ?
> fix(structure): add support to force a version for the pane provider

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
This change extends the core behaviors of PTE with default markdown behaviors for a more pleasant writing experience. This allows you to:
1. Use `#` characters to create headings
2. Use `>` to create a blockquote
3. Use `Backspace` at the beginning of block to clear its style
4. Use `-`, `*`, `_` or `1.` to initiate a list
This is achieved by providing the `behaviors` configuration for PTE where the `coreBehaviors` are first spread into the array (to preserve core behaviors) and the additional markdown behaviors are added afterwards. The markdown behaviors require us to define what styles to use, and here we just default to the most common names for these. Later, we can figure out how to allow you to configure markdown behaviors through the Schema, but for now these sensible defaults are …
> feat(core): add default markdown behaviors to PTE

- dev/page-building-studio/package.json
- dev/starter-studio/package.json
- dev/studio-e2e-testing/package.json
- dev/test-studio/package.json
- packages/@sanity/vision/package.json
- packages/sanity/package.json
- perf/efps/package.json
- perf/studio/package.json
- pnpm-lock.yaml
The latest version of `react-compiler-runtime` is ESM, which breaks some systems.
The runtime doesn't really change between versions anyway so it's fine to pin it for now.
https://github.com/facebook/react/pull/31993
> chore: temporarily downgrade compiler runtime

- packages/@sanity/cli/src/actions/init-project/bootstrapRemoteTemplate.ts
- packages/@sanity/cli/src/actions/init-project/initProject.ts
- Added a success message for when a CORS entry is added
- Added a success message for when an API token is added
Fixes: GRO-3076
Run
```shell
sanity init --template sanity-io/sanity-template-nextjs-clean
```
You should see a message for both CORS and API token
N/A or:
Adjusted copy in CLI
> feat(cli): copy additions for remote project bootstrapper

- packages/@sanity/cli/src/util/remoteTemplate.ts
Allowing credentials when adding CORS entry on remote template init. This is because some of the remote templates embeds a Studio, which requires your CORS entry to allow for credentials. 
My initial idea was to somehow dynamically figure out if you need to allow for credentials, but given that we're only dealing with localhost entries here, I think it's fine to just hardcode it. 
Run
```shell
sanity init --template sanity-io/sanity-template-nextjs-clean
```
Your project should have a CORS entry for localhost:3000 with credentials allowed
N/A
> feat(cli): allow credentials when adding CORS entry

- packages/sanity/src/_internal/cli/actions/graphql/extractFromSanitySchema.ts
- packages/sanity/test/cli/graphql/__snapshots__/extract.test.ts.snap
- packages/sanity/test/cli/graphql/__snapshots__/gen3.test.ts.snap
- packages/sanity/test/cli/graphql/extract.test.ts
- packages/sanity/test/cli/graphql/fixtures/union-refs.ts
- packages/sanity/test/cli/graphql/gen3.test.ts
This was seen in a schema produced by automated tooling. The recursion
guard was too strict in this case as the two occurrences of a
reference ending up having the same guard path name and extraction
would therefore abort before looking inside the second one, instead
returning `{}` which would fail when attempting to inspect the name
field a little lower down.
> fix: fixes schema extraction with nested union refs

- packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts
#8120 introduced a regression that would occationally cause the document to be stuck at loading. Huge thanks @pedrobonamin for catching this! I believe this issue appeared because the `_keepalive` stream would start start pulling events from the pair listener immediately, but callers of memoizedPair will typically start subscribing to the draft.events and published.events streams a little later, and when they did, they sometimes wouldn’t get the listener events, because they have already been consumed by `_keepalive`.
This fixes the issue by partially reverting the PR to the way it was before #8120. Both the issue fixed by #8120 and the initial loading issues should be fixed by this.
- The initial loading issue should be fixed
- The issue in #8120 should still be fixed (the steps to …
> fix(sanity): fix race condition introduced by #8120

- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenu.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/releaseActions.ts
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardFooter.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDashboardFooter.test.tsx
> refactor: useBundleDocuments only invoked when release menu is opened

- packages/sanity/src/core/config/__tests__/resolveConfig.test.ts
- packages/sanity/src/core/config/prepareConfig.tsx
I honestly cant tell you how this slipped through when building Start in Create, but here we go:
Turns out that if you `definedConfig({})` without providing a name, then `useWorkspace().name` will be undefined.
In other contexts, the name will be `default` (for instance when building the create manifest).
This is not a problem in multi-workspace settings, where `name` is required for each config. I suspect I've overindexed on testing multi-workspace.
In short, this ensures that resolved workspace summary and unstable_sources gets a name, by setting single workspace name to `'default'` as soon as possible, when it is missing.
The bug occurs in WorkspaceLoader, where the values in `unstable_sources` are spread over the current workspace config (the former had undefined name property, the …
> fix: ensures singleworkspace falls back to the name 'default' as expected in all contexts

- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenu.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/__tests__/ReleaseMenuButton.test.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardFooter.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
Also passing document count through
> refactor: removing unnecessary use of useBundleDocuments in ReleaseMenu

- packages/sanity/src/core/form/components/EditPortal.tsx
- packages/sanity/src/core/form/components/index.ts
Exporting `EditPortal` from `sanity` to allow users build custom Dialogs or Popover without having to care about Presence and Scroll Virtualizers.
Before this if a user needs to have a custom dialog, they need to include all of the Virtualizer Scroll element and Presence logic by themselves, for example:
```diff
+import React, {useRef, useState} from 'react'
+import {
+  ArrayOfObjectsInputProps,
+  FormInput,
+  Path,
+  PresenceOverlay,
+  VirtualizerScrollInstanceProvider,
+} from 'sanity'
+export function ScrollVirtualizerWrapper(props: {children: React.ReactNode}) {
+  const {children} = props
+  const [contentElement, setContentElement] = useState<HTMLDivElement | null>(null)
+  const containerElement = useRef<HTMLDivElement | null>(null)
+
+  return (
+    <Box …
```
> chore(core): export EditPortal from sanity 

- .github/workflows/e2e-ct.yml
Looks like latest ubuntu has issues with missing libraries required by webkit. See recent comments at
https://github.com/microsoft/playwright/issues/30368
Component tests should pass again
n/a
n/a
> fix(ci): pin ubuntu version for e2e component tests to 22.04

- dev/studio-e2e-testing/sanity.config.ts
- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/config/configPropertyReducers.ts
- packages/sanity/src/core/config/prepareConfig.tsx
- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/releases/plugin/index.ts
- test/e2e/tests/document-actions/fetchFeatureToggle.spec.ts
- test/e2e/tests/inputs/text.spec.ts
Server actions don't yet support version documents. 
This PR includes some changes necessary to make it possible to opt out from the server document actions through a plugin config.
It also disables that flag in the releases plugin, so users using releases will get this value and they will not use server actions.
Is there any missing change?
> fix(core): support serverDocumentActions flag in plugins

- packages/sanity/src/_internal/cli/threads/extractManifest.ts
- packages/sanity/src/_internal/cli/threads/extractSchema.ts
- packages/sanity/src/_internal/cli/threads/getGraphQLAPIs.ts
- packages/sanity/src/_internal/cli/threads/validateDocuments.ts
- packages/sanity/src/_internal/cli/threads/validateSchema.ts
A Node script only exists once all pending handles/requests are completed. It's quite common for dependencies to open various handles and thus prevent the script for naturally exiting. This changes all the scripts which we run inside worker threads to explicitly exit when they're done.
This impacts the following commands: `schema extract`, `manifest extract`, `graphql deploy`, `documents validate`, `schema validate`.
This also now unifies the commands so that they all have a `main` function.
`schema extract`, `manifest extract`, `graphql deploy`, `documents validate`, `schema validate`.
I've tested `schema extract` and `manifest extract` on a custom Studio linked to this version locally. I've not tested the other ones.
Fixes a case where the commands `schema extract`, `manifest extract`, …
> fix(cli): explicitly exit workers when they're done

- packages/@sanity/block-tools/README.md
`@sanity/block-tools` has been moved to the `portabletext` org and has thus
been republished as `@portabletext/block-tools`. The source code of the new
package lives in https://github.com/portabletext/editor/tree/main/packages/block-tools.
In a subsequent commit and PR, `@sanity/block-tools` will be deleted from the
`sanity` repo and the few usages will be replaced with
`@portabletext/block-tools`.
But first, we need to mark the old `@sanity/block-tools` package as deprecated
and wait until the next release of the `sanity` repo is triggered.
Does the outlined process make sense?
n/a
n/a
> fix(block-tools): "soft" deprecate in favour of @portabletext/block-tools

- packages/sanity/src/core/components/loadingBlock/LoadingBlock.tsx
- packages/sanity/src/core/components/userAvatar/UserAvatar.tsx
- packages/sanity/src/core/tasks/components/TasksUserAvatar.tsx
This PR adds a reusable `AvatarSkeleton` component, which is useful to display in loading states when using the `UserAvatar` component.
Usage example:
https://github.com/user-attachments/assets/0123d68c-edd7-4994-8725-b90008b40361
chore(core): adds reusable AvatarSkeleton component
> chore(core): add `<AvatarSkeleton />` component

- packages/@sanity/vision/src/components/ParamsEditor.tsx
- packages/@sanity/vision/src/components/VisionGui.tsx
When typing in `vision` , in some cases, you could get into an scenario in which the cursor jumped to the beginning of the editor.
So user was typing:
```
a
ab
abc
``` 
and when typed `d`, the cursor jumps to the start
```
dabc
```
I identified this as an issue generated by multiple setStates called when typing, adding a debounce helps with this, so the setState will only be executed 300ms after the user finishes typing.
The onPaste handle needs to be modified, so that when the CodeMirror component captures an onPaste event this one is not propagated to the global, neither to the CodeMirror component, applying the event only once and not triggering a subsequent queryChange.
fixes **Vision** cursor jump
> fix(vision): debounce type setState to fix cursor jump

- packages/sanity/src/core/search/groq2024/createSearchQuery.test.ts
- packages/sanity/src/core/search/groq2024/createSearchQuery.ts
In GROQ, when the `@` operator is used to match a text query, the content of the `_id` field is not included. Explicitly adding a match on `_id`  allows users to find documents by id.
It should be possible to find a document in Test Studio (where `groq2024` search is enabled) by searching for its id.
Updated relevant unit tests.
> feat(sanity): include `_id` field in `groq2024` searches

- packages/@sanity/cli/package.json
- pnpm-lock.yaml
bump `@sanity/template-validator` to latest (2.3.2)
This version includes some bug fixes related to the use of wildcards when defining packages in monorepos. 
1. Checkout to this branch
2. `cd packages/@sanity/cli`
3. `pnpm install`
4. `pnpm run build && npm link`
5. In a projects folder, run `sanity init --template https://github.com/hrithikroboto/next-sanity-turbo`
N/A
> chore(cli): bump `@sanity/template-validator` to latest (2.3.2)

- packages/sanity/src/core/form/components/EditPortal.tsx
export `<EditPortal/>` as `@beta`
n/a
> fix(core): export EditPortal as beta

- packages/sanity/src/structure/panes/document/useDocumentTitle.ts
`useDocumentTitle` is checking for the existence of `editState.draft` | `editState.published` 
With the introduction of `releases` this is error prone, because now we can display different values, not only draft or published inside the document pane.
This changes the hook to depend on the `displayed` value, which will be the value shown in the form. 
chore(core): use displayed value for document title
> chore(core): use displayed value for document title

- packages/sanity/src/core/store/_legacy/document/document-pair/operations/publish.test.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/publish.test.ts
- test/e2e/tests/document-actions/unpublish.spec.ts
Restores tests that `corel` skipped.
Tests are restored they should pass on CI.
n/a
> fix(test): restore skipped tests

- packages/sanity/src/core/form/store/utils/__tests__/immutableReconcile.test.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/validation.test.ts
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTitle.test.tsx
Fixes a type import issue in where using `vi.<Type>` would give the following error:
```
Cannot find namespace 'vi'
```
Is the change correct?
It's only a type definition change, existing tests cover this.
n/a, internal only
> fix(core): cannot find namespace 'vi'

- packages/sanity/src/core/field/diff/contexts/DocumentChangeContext.tsx
- packages/sanity/src/structure/panes/document/useResetHistoryParams.ts
History params need to be reseted when the perspective changes, that's the reason for the `useResetHistoryParams` hook, however, this hook was triggering unnecessary `setParams` and that was creating a glitch in which the router starts jumping between perspectives when the user changes them fast.
See video:
https://github.com/user-attachments/assets/5e5e5d1e-6553-4209-b46f-9756eb3c07b9
This updates the useResetHistoryParams hook to only trigger the `setParams` function when a param needs to be updated, preventing this bug.
> fix(structure): only reset history params if needed

- packages/sanity/playwright-ct/tests/formBuilder/utils/TestWrapper.tsx
Adds the router context to the test wrapper used in the e2e playwright tests
Does it make sense for us to also default to having our e2e test wrapper create a router state
N/A
> chore: playwright test wrapper creates router context

- packages/sanity/src/core/releases/hooks/__tests__/useDocumentVersions.test.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/store/createReleaseMetadataAggregator.ts
- packages/sanity/src/core/releases/store/useReleasesMetadata.ts
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/columnCells/ReleaseDocumentsCounter.test.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/columnCells/ReleaseName.test.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/columnCells/ReleaseTime.test.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseDocumentsCounter.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseName.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseTime.tsx
| Scenario | Before | After |
|--------|--------|--------|
| Active releases | <img width="1208" alt="Screenshot 2025-01-10 at 16 03 46" src="https://github.com/user-attachments/assets/76fdafd7-40ca-446d-b7fc-2694530de5a1" /> | <img width="1204" alt="Screenshot 2025-01-10 at 16 02 31" src="https://github.com/user-attachments/assets/99ad9f95-8cc6-4d75-ad60-ea33a9bcc6be" /> |
| Archived/Published releases | <img width="1206" alt="Screenshot 2025-01-10 at 16 04 20" src="https://github.com/user-attachments/assets/4145b3a0-3761-4b28-a215-54468c70be97" /> | <img width="1206" alt="Screenshot 2025-01-10 at 16 03 08" src="https://github.com/user-attachments/assets/9c89aa6e-8773-4da4-b7c3-f94257ce7b97" /> | 
* Split out the cell components for `ReleasesOverview` into separate components rather than …
> feat: releases overview shows total docs in release

- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Annotations.spec.tsx
- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/FocusTracking.spec.tsx
- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ObjectBlock.spec.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/Annotation.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/AnnotationToolbarPopover.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/BlockObject.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/InlineObject.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/InlineObjectToolbarPopover.tsx
There is currently an issue with reaching the annotation and inline object edit toolbar buttons with the keyboard leaving annotation editing impossible with the keyboard.
This will make sure that when these toolbars shows, it will be possible to press `Tab` in order to get to the buttons with the keyboard.
https://github.com/user-attachments/assets/6a928a83-980b-47ba-83b3-ad1e49cb7d74
Also added component tests for this.
That you are able to tab into the buttons when the toolbar is showing.
* Fixed an issue with keyboard navigation to edit buttons for annotation and inline objects in the Portable Text Input.
> fix(core/form/inputs): fix issue with tabbing to popover toolbar buttons in PT-input

- packages/sanity/src/core/config/studio/types.ts
- packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
- packages/sanity/src/core/studio/components/navbar/navDrawer/NavDrawer.tsx
- packages/sanity/src/core/tasks/i18n/resources.ts
- packages/sanity/src/core/tasks/plugin/TasksStudioNavbar.tsx
| Scenario | Before | After |
|--------|--------|--------|
| Desktop navbar | <img width="240" alt="Screenshot 2025-01-14 at 10 03 04" src="https://github.com/user-attachments/assets/19b57da9-f7be-49f9-8f53-228a04883da7" /> | <img width="152" alt="Screenshot 2025-01-14 at 10 02 31" src="https://github.com/user-attachments/assets/4c8c4fc0-1f57-4718-a598-61bd7ce2d130" /> |
| Mobile tray | <img width="329" alt="Screenshot 2025-01-14 at 10 03 14" src="https://github.com/user-attachments/assets/ad4045f6-3519-4e85-a242-c32d6b79e1e7" /> | <img width="327" alt="Screenshot 2025-01-14 at 10 02 47" src="https://github.com/user-attachments/assets/521cdd99-32be-4dd5-b777-6ed1a9596e87" /> | 
* There is now support for a custom rendered for plugin navbar links, in addition to just defining a string and …
> feat: Updated Navbar link for Tasks tool

- dev/embedded-studio/package.json
- dev/test-studio/package.json
- package.json
- packages/@sanity/cli/package.json
- packages/sanity/package.json
- perf/efps/package.json
- pnpm-lock.yaml
Upgrades vite to the latest version (v6), as well as vitest to v3
Give it a test, see how it feels! Does anything break?
There's a prerelease you can use to test it on a local studio, under the `upgrade-vite-v6` branch on npm.
Commands involved:
- `sanity dev`
- `sanity build`
- `sanity preview`
- Upgrades vite to version 6
> fix(deps): upgrade `vite` to v6

- packages/@sanity/types/src/schema/types.ts
This avoids the need to specify `__experimental_search: []` when constructing an `ObjectSchemaType` by hand.
> fix(types): make `ObjectSchemaType['__experimental_search']` optional

- packages/sanity/src/core/preview/__test__/createObserveDocument.test.ts
- packages/sanity/src/core/preview/createGlobalListener.ts
- packages/sanity/src/core/preview/createObserveDocument.ts
- packages/sanity/src/core/preview/documentPreviewStore.ts
- packages/sanity/src/core/preview/utils/applyMendozaPatch.ts
In certain cases its useful to be able to subscribe to the complete version of a document (by id) and receive updates to it as it changes in the backend. The only way to achieve this in the Studio today involves either setting up a full optimistic mutation pipeline, or setting up a "live query", both of which adds a separate listener connection per document. This doesn't scale well, so this PR proposes an alternative approach that re-uses the global listener currently use for Studio previews.
The intended use is cases where you always need  the latest version of a complete document, but don't need to be able to do optimistic updates to it (i.e. you can live with a server roundtrip).
It introduces two new method to the preview store API, both unstable and marked as internal for now:
- …
> feat(preview): add experimental support for observing full documents

- dev/test-studio/package.json
- package.json
- packages/@sanity/cli/package.json
- packages/@sanity/migrate/package.json
- packages/@sanity/types/package.json
- packages/@sanity/util/package.json
- packages/@sanity/vision/package.json
- packages/sanity/package.json
- packages/sanity/src/core/preview/__test__/createObserveDocument.test.ts
- packages/sanity/src/core/preview/createObserveDocument.ts
- packages/sanity/src/core/preview/documentPreviewStore.ts
- packages/sanity/src/core/preview/utils/applyMendozaPatch.ts
- packages/sanity/src/core/releases/tool/detail/events/buildReleaseEditEvents.ts
- perf/efps/package.json
- perf/tests/package.json
- pnpm-lock.yaml
> chore(core): merge `next` into `corel`

- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
| ![patchReadOnlyBEFORE](https://github.com/user-attachments/assets/2d01ffcf-ef95-4897-b234-eee42ceb4408) | ![patchReadOnlyAFTER](https://github.com/user-attachments/assets/662a8162-aa68-4650-866f-a5e8daad412f) | 
Above shows a demo where a document is placed in readOnly mode, but the custom input still called the `onChange` callback. After refresh in 'Before' the change has persisted. In 'After' the change has not persisted
Fixing issue where custom form inputs could wrongly patch a `readOnly` document by call `onChange`
> fix: patching a readOnly document is blocked

- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
Resolved a bug in https://github.com/sanity-io/sanity/pull/8292
Verified this works locally with the markdown plugin using content releases
N/A - Noted in https://github.com/sanity-io/sanity/pull/8292
> fix: readOnly pane overrides patch

- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/operations/patch.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/patch.test.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/patch.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/utils/actionsApiClient.ts
This branch fixes version editing when using the Actions API, and  enables the Actions API in the default workspace in Test Studio.
When using the Actions API to edit a version document, the `draftId` option must refer to the version id. Previously, the draft document would be patched instead, which is incorrect.
This branch also temporarily changes the API version to `vX` when executing Actions API actions. At this point in time, the Actions API can only execute certain actions for version documents (e.g. `sanity.action.document.edit`) in `vX`.
Editing a version document successfully calls the edit action for the version document. The draft and published documents must not be affected.
Added unit test in `packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/patch …
> fix(sanity): editing version document using Actions API

- packages/sanity/src/presentation/editor/DocumentListPane.tsx
Fixes a regression (I don't know exactly when this regressed) causing only published documents to show up in the list of documents in use in presentation.
When using the default `Drafts` perspective, notice the before and after (the right hand side is correct, the left hand side only shows documents that are published and have no drafts):
For the `Published` perspective it should only filter out documents that only have a draft variant:
The Presentation Tool's "Documents in use" pane is now including draft documents, and unpublished documents. So that it actually shows all documents in use, and not just some of them.
> fix(presentation): always show all documents in use

- packages/sanity/src/presentation/loader/LoaderQueries.tsx
Fixes #8309
Fixes #8310
When React is in strict mode there's a warning coming from Presentation.
When using `sanity dev` strict mode is opt-in:
```ts
// sanity.cli.ts
import {defineCliConfig} from 'sanity/cli'
export default defineCliConfig({
reactStrictMode: true,
})
```
While on Next.js App Router it's opt-out.
The fix is to wrap the `useEffect` that batches documents to fetch in a `requestAnimationFrame`, which is cancelled if we're in React Strict Mode which double-fires `useEffect`.
This isn't a good long term fix in general, but in this case it's ok. The code where this happens is presentation's `<LoaderQueries />` driver, which uses the legacy way of live updating user provided GROQ queries.
As soon as https://www.sanity.io/live becomes stable for draft content we have another …
> fix(presentation): avoid duplicate key warning

- packages/@sanity/cli/src/actions/init-project/bootstrapRemoteTemplate.ts
- packages/@sanity/cli/src/util/remoteTemplate.ts
Allow the remote template bootstrapper to generate a write token by specifying it in your .env.example. 
I'm using the earlier implementation of `generateSanityApiReadToken`, but renamed it to `generateSanityApiToken`, and added an arg for specifying the role of the token.
- The copy, is the token naming and cli output ok? 
- Are the roles ok to use? 
1. Checkout to this branch
2. `cd packages/@sanity/cli`
3. `pnpm install`
4. `pnpm run build && npm link`
5. In a projects folder, run `sanity init --template https://github.com/sanity-io/nextjs-blog-cms-sanity-v3` (this template expects a write token)
6. the .env.local should have a write token env set
Tbd if we need one
> feat(cli): remote template bootstrapper to support write token

- packages/@sanity/vision/package.json
- packages/@sanity/vision/src/SanityVision.tsx
- packages/@sanity/vision/src/components/VisionGui.tsx
- packages/@sanity/vision/src/i18n/resources.ts
- packages/@sanity/vision/src/perspectives.ts
- packages/@sanity/vision/src/types.ts
- packages/@sanity/vision/src/util/encodeQueryString.ts
- packages/sanity/src/core/index.ts
- pnpm-lock.yaml
This branch adds perspective support to `@sanity/vision` by adding a new "pinned release" perspective option to the Vision UI. When this perspective is selected, Vision will inherit the release stack that is pinned in Studio.
- When there is a pinned release, the "pinned release" perspective is selected by default.
- When there is no pinned release, the "pinned release" perspective is inactive.
- Users can choose to use system perspectives in Vision even when there is a pinned release.
- The selected Vision perspective is set in `localStorage` and restored when Vision mounts.
- If Vision mounts while there **is** a pinned release, but the last perspective stored to `localStorage` **was not** `pinnedRelease`, `pinnedRelease` will override the last perspective stored.
- If Vision mounts …
> feat(vision): add release layering support

- packages/@sanity/vision/package.json
- packages/@sanity/vision/src/SanityVision.tsx
- packages/@sanity/vision/src/components/VisionGui.tsx
- packages/@sanity/vision/src/i18n/resources.ts
- packages/@sanity/vision/src/perspectives.ts
- packages/@sanity/vision/src/types.ts
- packages/@sanity/vision/src/util/encodeQueryString.ts
- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/index.ts
- packages/sanity/src/core/preview/utils/getPreviewStateObservable.ts
- packages/sanity/src/core/releases/hooks/useIsReleaseActive.ts
- packages/sanity/src/core/releases/hooks/usePerspective.tsx
- packages/sanity/src/core/releases/hooks/utils.ts
- packages/sanity/src/core/releases/navbar/ReleasesNav.tsx
- packages/sanity/src/core/releases/util/getReleaseTone.ts
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItemPreview.tsx
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/SearchProvider.tsx
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts
- packages/sanity/src/core/studio/components/navbar/search/types.ts
- pnpm-lock.yaml
There are some places across the codebase we could improve the typing of perspective stacks so that they're more precise and consistent. In a lot of places, these stacks are currently typed as `string[]`, which is not compatible with `ClientPerspective`. This code now uses the new type `PerspectiveStack`, which reflects only the array values accepted by `ClientPerspective`.
Note: It would be a good idea to export `PerspectiveStack` from `@sanity/client` in the future, rather than us extracting it from the `ClientPerspective` type.
This branch also adopts the `isReleaseDocument` type guard where applicable to determine whether the selected perspective is a system perspective (e.g. `published`) or a release document. In the past, this tended to be done by explicitly checking whether the …
> refactor(sanity): refine perspective stack types

- packages/sanity/src/core/store/_legacy/document/document-pair/editState.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/operations/duplicate.ts
Duplicate action should work with versions.
This PR updates how the id is created for the new document created by the duplicate action, if it's a version id it will preserve the version and it won't create a draft document.
Is this correct?
Open a version document.
Click on duplicate, it should create a new document in the same release.
Non version documents should continue being created as draft or live documents.
> fix(core): duplicate should work with version documents

- dev/test-studio/schema/debug/arrayCapabilities.ts
- dev/test-studio/schema/debug/simpleArrayOfObjects.js
- dev/test-studio/schema/index.ts
- dev/test-studio/structure/constants.ts
- packages/@sanity/types/src/schema/definition/type/array.ts
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/ArrayOfObjectsFunctions.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/Grid/GridItem.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/InsertMenuGroups.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/InsertMenuMenuItems.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfObjectsInput/List/PreviewItem.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesFunctions.tsx
- packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ItemRow.tsx
- packages/sanity/src/core/form/studio/inputResolver/fieldResolver.tsx
- test/e2e/tests/inputs/array-capabilities.spec.ts
This adds support for the `disableActions` option on array fields for disabling various array input capabilities like:
- `add` – Removes the ability to add new items to the array
- `addBefore` – Removes the "Add item before"-menu item from the array item menu
- `addAfter` – Removes the "Add item after"-menu item from the array item menu
- `remove` – Removes the ability to remove items from the array
- `duplicate` – Removes the ability to duplicate array items
- `copy` – Removes the ability to copy items from the array
Usage example:
```ts
{
name: 'someArrayField',
options: {
disableActions: ['add', 'duplicate'],
},
title: "Array you can't add elements to",
type: 'array',
of: [
{
name: 'something',
title: 'Something',
fields: [{name: 'first', type: 'string', title: 'First …
```
> feat(form): add support for disabling array input capabilities

- packages/sanity/src/core/preview/availability.ts
- packages/sanity/src/core/validation/validateDocumentWithReferences.ts
Validates that references to documents in the same release are valid.
Previously we only considered as valid references the references to documents that are published, with the introduction of releases now references to documents that will be part of the same release, but not published yet, are valid, because they will be released at the same time.
This PR fixes that, allowing us to reference documents from the same release.
**What this doesn't fix?**
It doesn't fix references to documents that are part of other releases which will be released before this one, following the stack criteria.
Example:
This document is referencing a document that only exists in the same release:
[Validation passing in preview ](https://test-studio-git-corel-validate-references.sanity.dev/test/structure/author; …
> fix(core): references to documents on same release are valid

- packages/sanity/src/core/util/__tests__/draftUtils.test.ts
- packages/sanity/src/core/util/draftUtils.ts
While working on the [reference changes](https://github.com/sanity-io/sanity/pull/8324) I noticed the that getIdPair function returns the same id for a version document even if you are passing a different version.
Example:
```
getIdPair("versions.r1.foo", {version: "r2"})
resolves to: 
{
publishedId: "foo",
draftId: "drafts.foo"
versionId: "versions.r1.foo"
}
``` 
I think this could be miss leading, given if you provide a version you would want that version to be applied to the id.
So with this update:
```
getIdPair("versions.r1.foo", {version: "r2"})
resolves to: 
{
publishedId: "foo",
draftId: "drafts.foo"
versionId: "versions.r2.foo"
}
```
> fix(core): update getIdPair to calculate the new id given the version

- packages/sanity/src/structure/panes/document/documentPanel/banners/ReferenceChangedBanner.tsx
When opening a reference from a document in `published` perspective the studio crashes.
This happens because the `observeDocumentPair` function was receiving the `selectedPerspectiveName` which could be "published". instead of the `releaseId` which is what we want here.
This updates and fixes the issue. 
See how it crashes here: https://test-studio-git-corel.sanity.dev/test/structure/author;f219b738-f1b9-410c-8c26-d9eb8925dc34;b8512898-d875-4331-a27a-ab915a559a99%2Ctype%3Dauthor%2CparentRefPath%3DbestFriend?perspective=published
But it passes here:  https://test-studio-git-corel-354.sanity.dev/test/structure/author;f219b738-f1b9-410c-8c26-d9eb8925dc34;b8512898-d875-4331-a27a-ab915a559a99%2Ctype%3Dauthor%2CparentRefPath%3DbestFriend?perspective=published
> fix(core): issue opening references with published perspective

- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTitle.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx
- test/e2e/tests/inputs/reference.spec.ts
collapsed document should show document title, not the releases the document belongs to.
> fix(structure): collapsed document show document title

- packages/sanity/src/core/store/_legacy/history/useTimelineSelector.ts
- packages/sanity/src/structure/panes/document/DocumentPane.tsx
- packages/sanity/src/structure/panes/document/DocumentPaneContext.ts
- packages/sanity/src/structure/panes/document/DocumentPaneLegacyTimeline.tsx
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/DocumentPaneProviderWrapper.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/index.ts
- packages/sanity/src/structure/panes/document/inspectors/changes/HistorySelector.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBar.tsx
- packages/sanity/src/structure/panes/document/timeline/__workshop__/DefaultStory.tsx
- packages/sanity/src/structure/panes/document/timeline/timelineMenu.tsx
- packages/sanity/src/structure/panes/document/types.ts
We have always had only one way to represent the Timeline, it has been defined by the TimelineStore, with the addition of releases we are adding a new store that builds on the events api.
This PR updates the `DocumentPaneProvider` to receive the timeline through the props, allowing us to inject either this Legacy Timeline or the new Events API. 
It also changes the `structure` export to expose the `DocumentPaneProviderWrapper` instead of the `DocumentPaneProvider` 
The wrapper now only inserts the legacy Timeline, but in `corel` it will check the feature flag and use the events store instead.
This PR also removes the `timelineMode` property from the document pane, given it's not used anywhere. This is a legacy property that was used before the [History UI …
> chore(structure): remove `TimelineStore` from `<DocumentPaneProvider/>`

- dev/test-studio/schema/standard/crossDatasetReference.ts
- packages/@sanity/schema/src/sanity/validation/types/block.ts
This branch makes Cross Dataset References permissible inside Portable Text blocks. Adding `crossDatasetReference` types to a block's `of` option would previously cause Studio to crash, despite aliased Cross Dataset Reference types working correctly.
| --- | --- |
| <img width="1536" alt="before" src="https://github.com/user-attachments/assets/3f8f052e-c68b-4a96-8ac3-d2fe7ca2176d" /> | <img width="1536" alt="after" src="https://github.com/user-attachments/assets/af85fcb4-d418-4a91-aae1-8f792fcd8550" /> |
- Adding Cross Dataset Reference type to a Portable Text block's `of` option.
- Adding a Cross Dataset Reference to the document data using Studio.
- Added replication to Test Studio. Therefore, prior to this fix, E2E tests fail.
- Inserting an **inline** Cross Dataset …
> fix(@sanity/schema): allow Cross Dataset References in Portable Text blocks

- dev/embedded-studio/package.json
- dev/test-studio/package.json
- package.json
- packages/@sanity/cli/package.json
- packages/sanity/package.json
- perf/efps/package.json
- pnpm-lock.yaml
This reverts upgrading vite to v6 due to discovering issues with auto upgrading Studios
Does the changes look ok?
Downgrading Vite from v6 to v5 due to incompatibilities with Auto Updating Studios
> fix: revert back to vite v5

- packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/types.ts
- packages/sanity/src/core/form/studio/contexts/ReferenceInputOptions.tsx
- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/form/studio/inputs/reference/StudioReferenceInput.tsx
- packages/sanity/src/core/index.ts
- packages/sanity/src/core/preview/documentPair.ts
- packages/sanity/src/core/releases/hooks/__tests__/useDocumentVersions.test.tsx
- packages/sanity/src/core/releases/hooks/useDocumentVersions.tsx
- packages/sanity/src/core/releases/plugin/documentActions/DiscardVersionAction.tsx
- packages/sanity/src/core/releases/plugin/documentActions/UnpublishVersionAction.tsx
- packages/sanity/src/core/releases/util/util.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/patch.test.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/patch.ts
- packages/sanity/src/structure/components/paneRouter/PaneRouterProvider.tsx
- packages/sanity/src/structure/components/paneRouter/types.ts
- packages/sanity/src/structure/panes/document/DocumentPaneContext.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/ScheduledReleaseBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveList.test.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBar.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
- packages/sanity/test/testUtils/TestProvider.tsx
When working with releases it should be possible to create a document that only lives inside a release.
This could happen in two different places:
1) Clicking the **New Document Button**
https://github.com/user-attachments/assets/9f1b19ca-6be0-407c-a1b8-04281f02b941
2) Clicking on the **Create reference** button. 
https://github.com/user-attachments/assets/069c57b2-841b-44b8-9fb2-2d9e52a5d703
In both cases the document that will be created needs to belong to the release and it should not create a draft.
This PR fixes that, allowing us to create version inside releases.
To do this, it adds a `version` parameter to the pane router, when that parameter exists, the initial value id will be the correct version id.
When working on this update I noticed that we don't need anymore the …
> feat(core): create references from version documents and new version documents.

- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
Inside the release overview table, for an open release the count of documents is read from `release.documentsMetadata.documentCount`. This was currently being used correctly for open releases, however for archived (archived or published) releases, this should be read from `release.finalDocumentStates`.
This PR adds in the conditional key
Tested by verifying that for an archived release that has documents, when trying to delete the release from the overview list, a dialog appears confirming that all the document versions will be deleted (previously this was never showing for archived and published releases since incorrectly the releases appeared as though it was empty)
N/A
> fix: fixing issue with counting documents in archived or published releases

- dev/test-studio/preview/SimpleBlockPortableText.tsx
- packages/sanity/package.json
- packages/sanity/src/presentation/loader/LiveQueries.tsx
- packages/sanity/src/presentation/loader/LoaderQueries.tsx
- packages/sanity/src/presentation/loader/utils.ts
- pnpm-lock.yaml
Fixes #8379.
Run `pnpm dev` and go to http://localhost:3333/presentation/presentation, and you should see content rendered with `pt::text` above the full PT render, which continues to work as you edit the PT fields.
Presentation, and loaders like `@sanity/react-loader`, `@sanity/core-loader`, `@sanity/svelte-loader` and more now allows using `pt::text` in your GROQ protections when used with `useQuery` and `useLiveMode`, instead of causing a crash as your app probably didn't expect an array of blocks to appear in what was originally a string.
> fix(presentation): support `pt::text` in live queries

- dev/test-studio/package.json
- package.json
- packages/@sanity/cli/package.json
- packages/@sanity/migrate/package.json
- packages/@sanity/types/package.json
- packages/@sanity/util/package.json
- packages/@sanity/vision/package.json
- packages/sanity/package.json
- packages/sanity/src/presentation/loader/LiveQueries.tsx
- packages/sanity/src/presentation/loader/LoaderQueries.tsx
- perf/efps/package.json
- perf/tests/package.json
- pnpm-lock.yaml
Fixes the issue flagged by @RitaDias in the [PR](https://github.com/sanity-io/sanity/pull/8317#pullrequestreview-2561537549) that moved the `@sanity/presentation` codebase into the `corel` branch.
It makes sense?
Until we got E2E tests setup, it has to be manually tested on `http://localhost:3333/presentation`.
N/A
> fix(presentation): support releases in optimistic updates

- packages/sanity/src/presentation/preview/Preview.tsx
When [adding the Vercel Bypass Tool](https://github.com/sanity-io/visual-editing/pull/2479/files), I started forwarding the current perspective [while at it](https://github.com/sanity-io/visual-editing/pull/2479/files#diff-80fbc13cc919843352bf73130ac5964233caaebf4fe49d11bbc4e652103e9dc0R94-R97):
https://github.com/sanity-io/visual-editing/blob/d26635224057fcdf237bb187a3416c92a762ecd1/packages/presentation/src/preview/Preview.tsx#L94-L97
This caused a regression that lead to the iframe reloading and losing connection with Presentation Tool when switching perspectives and ultimately failing to swap the perspective in loaders' live mode:
https://github.com/user-attachments/assets/8eab26f8-4919-4995-9270-422a059100f7
Here's with the fix applied, restoring the previous behavior: …
> fix(presentation): perspective switching regression

- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardFooter.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDashboardFooter.test.tsx
| <img width="1512" alt="Screenshot 2025-01-24 at 12 09 24" src="https://github.com/user-attachments/assets/525bbd11-f5e8-49f4-801b-73b1bf6dc1a2" /> | <img width="1512" alt="Screenshot 2025-01-24 at 12 10 33" src="https://github.com/user-attachments/assets/bf560e20-b961-43ac-9a61-eec42f51fc81" /> | 
Before: Wrongly, a scheduled published release was showing `schedule for publish` when it should have been showing revert release`
Added a new test case for this particular scenario
> fix: scheduled published releases allow for reverting

- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
References to documents that are only drafts are not showing in the `corel` branch.
This is because the `getReferenceInfo` function is returning an incorrect value, instead of the actual DocumentPreview is returning an object containing `{snapshot: DocumentPreview, type: string}`
This PR changes that and fixes the preview.
See for example in this page:
- [Corel](https://test-studio-git-corel.sanity.dev/test/structure/author;0aaedd66-6d0b-4eb3-b030-1090a36561fb)
- [Branch](https://test-studio-git-corel-fix-get-reference-info.sanity.dev/test/structure/author;0aaedd66-6d0b-4eb3-b030-1090a36561fb)
| Corel | Fixed |
| <img width="742" alt="Screenshot 2025-01-23 at 18 31 07" src="https://github.com/user-attachments/assets/a6dc116a-6275-4368-b095-67400a10e9c1" />| <img …
> fix(core): reference to drafts not showing values

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/__tests__/ReleaseMenuButton.test.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/releaseActions.ts
- Added the ability to open the confirmation dialog even when there are no documents in a release
- Updated the translation approach for plural approach + added new translations for when it's zero
Does this make sense? 
Nothing needed outside of what currently exist
> refactor(core): adds confirmation when there are no documents in a release (for archiving and delete)

- packages/sanity/src/core/preview/documentPair.ts
- packages/sanity/src/core/preview/documentPreviewStore.ts
- packages/sanity/src/core/preview/utils/getPreviewPaths.test.ts
- packages/sanity/src/core/preview/utils/getPreviewPaths.ts
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseReview.test.tsx
- packages/sanity/src/core/releases/tool/detail/review/DocumentDiff.tsx
- packages/sanity/src/core/search/text-search/createTextSearch.ts
- packages/sanity/src/core/search/weighted/createSearchQuery.test.ts
- packages/sanity/src/core/search/weighted/createSearchQuery.ts
- packages/sanity/src/core/store/events/getDocumentChanges.ts
The `_version` field is no longer used to signal that a document is a version (this is instead handled via the `versions.` id prefix). This branch removes defunct references to the `_version` field.
> refactor(sanity): remove references to defunct `_version` field

- packages/sanity/src/core/store/_legacy/grants/documentPairPermissions.ts
- packages/sanity/src/core/store/_legacy/grants/documentValuePermissions.ts
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/InsufficientPermissionBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/index.ts
In `corel` we lost some changes applied in #7597, this PR restores them.
> fix(core): revert lost changes from #7597

- packages/@sanity/types/src/reference/types.ts
- packages/sanity/src/core/form/studio/inputs/client-adapters/reference.ts
- packages/sanity/src/core/form/studio/inputs/reference/StudioReferenceInput.tsx
- packages/sanity/src/core/perspective/PerspectiveProvider.tsx
- packages/sanity/src/core/search/groq2024/createSearchQuery.test.ts
- packages/sanity/src/core/search/groq2024/createSearchQuery.ts
- packages/sanity/src/core/search/weighted/createSearchQuery.test.ts
- packages/sanity/src/core/search/weighted/createSearchQuery.ts
When searching to add a reference in a document, documents that are available in the same release should show.
https://github.com/user-attachments/assets/8958ee12-04a8-417b-9bfc-8fb76286f822
Manual testing for now:
- Create a document in a release.
- Go to a document that could reference the previously created document.
- The document should show in the list.
> fix(core): support searching references in same release

- packages/sanity/src/structure/documentActions/PublishAction.tsx
- packages/sanity/src/structure/documentActions/UnpublishAction.tsx
Publish and unpublish actions are not available in version documents, this PR updates them to return `null` if it's being used in a version document.
This actions should happen through the release publish action, not individually in each document,.
> fix(structure): disable publish and unpublish actions for releases

- packages/sanity/src/structure/panes/document/inspectors/changes/HistorySelector.tsx
The `getScrollerRef` function is called when the element is empty, this changes the height to 0 and it doesn't reset after selecting the tab.
This adds a check to validate that the height is only set if it exists.
fixes an issue in which the history will not load if user open the History → Review Changes → History.
> fix(structure): do not set history inspector height to 0

- packages/sanity/src/presentation/constants.ts
- turbo.json
Fixes #8381
The `SANITY_STUDIO_PRESENTATION_ENABLE_LIVE_DRAFT_EVENTS` isn't really used anywhere so it should be fine to remove. Once Live Content for Drafts goes GA we'll remove this feature flag as well.
Checked the build output in `packages/sanity/lib`, after this change there's no longer a `process.env`.
Fixes an issue where Shopify Hydrogen apps that embed studios and use Presentation would see an error about `calling env on undefined`. The undefined stowaway var was `process` and walked the plank. Let us know if you see any other stowaways though! 🫡
> fix: remove `process.env.SANITY_STUDIO_PRESENTATION_ENABLE_LIVE_DRAFT_EVENTS`

- packages/sanity/src/core/form/FormBuilderContext.ts
- packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceField.tsx
- packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx
- packages/sanity/src/core/form/studio/FormBuilder.tsx
- packages/sanity/src/core/form/studio/FormProvider.tsx
- packages/sanity/src/core/form/studio/inputs/reference/StudioReferenceInput.tsx
- packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx
When we started with the `corel` branch `version` was added as a value that the `formBuilder` exposed, this was used by the internal fields when they needed to fetch data, like the `reference` inputs.
Later, we added the `<PerspectiveProvider>` with the `usePerspective` hook, this PR removes the `version` from the `formBuilder` to simplify the usage by devs and knowing which one to use. 
Allowing us to pick the same value from two different context could lead to hard to track bugs and code inconsistency.
> fix(core): remove `version` from `formBuilder`, replace for `usePerspective`

- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/config/configPropertyReducers.ts
- packages/sanity/src/core/config/prepareConfig.tsx
- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/releases/tool/detail/events/getReleaseActivityEvents.ts
- packages/sanity/src/core/releases/tool/detail/events/useReleaseEvents.ts
- packages/sanity/src/core/store/events/README.md
- packages/sanity/src/core/store/events/createEventsObservable.ts
- packages/sanity/src/core/store/events/getInitialFetchEvents.ts
- packages/sanity/src/core/store/events/useEventsStore.ts
- packages/sanity/src/core/store/events/utils.test.ts
- packages/sanity/src/core/store/events/utils.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProviderWrapper.tsx
- packages/sanity/src/structure/panes/document/inspectors/changes/ChangesTabs.tsx
This PR updates the events api routes that we were using.
The routes now will be:
- Documents events: `data/history/{datasetName}/events/documents/{ids}` 
- Release events `data/history/{datasetName}/events/releases/{id}`
It also modifies the config flag we have added for the events api and **enables** it by default for documents events for all the studios.
It's kept as a flag in case we need to turn it off.
Releases events are not ready to be used by everyone yet, so a new flag has been added to handle this. It will be enabled by default in the `playground` studio.
It also updates the sort algorithm for the events, given the timestamp validation is not the only check necessary, because edit and publish events now have the same timestamp and the order was incorrect.
> feat(core): update events api routes and config flags, fix events sorting

- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
Makes form readOnly if the selected perspective is `published` and the document type is not live editable
> fix(structure): make form readOnly in published view

- packages/sanity/src/core/components/documentStatus/DocumentStatus.tsx
- packages/sanity/src/core/create/components/StartInCreateBanner.tsx
- packages/sanity/src/core/store/events/utils.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBar.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusLine.tsx
- packages/sanity/src/structure/panes/document/timeline/index.ts
- test/e2e/tests/document-actions/unpublish.spec.ts
- test/e2e/tests/inputs/text.spec.ts
This PR updates how the document status will be shown depending if the document exists or not for the current perspective, it also updates the document status line to use the history events if available, to display information about the last user who did an update to the document.
**Published perspective**
- If the document doesn't have a `published` variant yet, it will show as empty, the `draft` chip will not show as selected
- If the document has a `published` variant it will show the published value
---
**Draft perspective**
- If the document is **in creation** it won't display the status chip and it will show the chip in a light gray color
- If the document doesn't have a `draft`  but it has a `published`, it will show the value of the `published`, the chip will change it's tone to a …
> feat(structure): document status updates

- packages/sanity/src/_internal/cli/threads/__tests__/validateDocuments.test.ts
- packages/sanity/src/_internal/cli/threads/validateDocuments.ts
Add condition to hide internal types in the 
Should we add more tests? 
Anything glaring in the code where we should also add this condition?
Pulling from the branch you should be able to run `~[path to your monorepo]/packages/@sanity/cli/bin/sanity schema validate` or `~[path to your monorepo]/packages/@sanity/cli/bin/sanity document validate` and see that no sanity.[name] appears when you run those commands.
The way I was able to debug with minimal work was by going into the `examples/blog-studio` and run the documents command
Internal document types will no longer appear in validation results in the CLI
> fix(cli): fix issue where core sanity types were appearing in the validation for schemas and documents

- packages/sanity/src/core/releases/tool/detail/AddDocumentSearch.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItem.tsx
Added document title to the toast when adding document to a release from the search in the release details. 
This is from feedback from knut
https://github.com/user-attachments/assets/c6d1dcf4-bd13-4fc6-942a-9aa90638046f
I found this solution a bit more forceful than it probably needs to be, however, when I tried adding it directly on the addDocumentSearch, I found that it would need to pull a lot more information than it easily has access to. Open to hearing any thoughts
Existing ones should exist.
N/A
> refactor(core): add document title to the toast when adding document to release

- packages/sanity/src/_internal/cli/server/buildVendorDependencies.ts
When building auto-updating Studios with Vite 6 we ran into an issue caused by the default of `commonjsOptions.strictRequires` that changed from `auto` to `true` between v5 and v6 (mentioned in the advanced section here: https://vite.dev/guide/migration#advanced)
This caused the vendorized react bundle to place all named exports on the `default` export instead of exporting them all individually which then broke named imports.
This PR explicitly sets `commonjsOptions.strictRequires` to `auto` which will produce the same output in both Vite v5 and v6.
We mitigated the earlier issue by reverting back to to Vite 5 (#8362). Now that we know the exact cause, and the fix, it would be good to have this merged so we can safely upgrade to Vite 6 again without affecting auto-updating Studios.
n/a …
> fix: set strictRequires to auto when building auto updating studios

- packages/sanity/src/core/components/inputs/DateInputs/DatePicker.tsx
- packages/sanity/src/core/components/inputs/DateInputs/DateTimeInput.tsx
- packages/sanity/src/core/components/inputs/DateInputs/calendar/Calendar.tsx
- packages/sanity/src/core/components/inputs/DateInputs/calendar/CalendarDay.tsx
- packages/sanity/src/core/components/inputs/DateInputs/calendar/CalendarMonth.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/components/ScheduleDatePicker.tsx
- packages/sanity/src/core/releases/components/dialog/CreateReleaseDialog.tsx
- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/components/dialog/__tests__/CreateReleaseDialog.test.tsx
- packages/sanity/src/core/releases/components/documentHeader/dialog/CopyToNewReleaseDialog.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseScheduleButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseTypePicker.test.tsx
- packages/sanity/src/core/releases/util/getIsScheduledDateInPast.ts
Cherrypick of https://github.com/sanity-io/sanity/pull/8403
> fix: resolving dateTime picker bugs with content releases

- packages/sanity/src/core/releases/plugin/index.ts
In the past, Content Releases did not work correctly with Actions API. Therefore, the Releases plugin ensured the Actions API was switched off when it was in use.
This has been fixed, and it is no longer necessary for Actions API to be switched off when Content Releases is in use.
> fix(sanity): remove Actions API override

- packages/sanity/src/core/releases/plugin/documentActions/DiscardVersionAction.tsx
Fixes one known instance of string literal being used instead of language string.
> feat(sanity): use language strings in `DiscardVersionAction`

- packages/sanity/src/core/perspective/useSetPerspective.tsx
- packages/sanity/src/core/releases/util/getReleaseIdFromReleaseDocumentId.ts
- packages/sanity/src/presentation/PresentationTool.tsx
Initially we decided that releases ids will be required to start with `r` , this is no longer true, so this removes that explicit check from `presentation` and uses the `selectedReleaseId` to determine if we are viewing a release
It also removes the client side validations applied in `core`
> fix(presentation): remove explicit check for `r` in perspectives

- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/config/resolveDefaultPlugins.ts
- packages/sanity/src/core/releases/plugin/ReleasesStudioLayout.tsx
This branch makes Content Releases opt-in, and enables it in Test Studio.
> feat(sanity): make Content Releases opt-in

- packages/@sanity/migrate/src/fetch-utils/__test__/sanityRequestOptions.test.ts
- packages/@sanity/migrate/src/fetch-utils/endpoints.ts
`perspective=raw` is currently default for all current API versions, but that might not be true in for all _future_ API versions. 
For migrations in particular, `perspective=raw` is the most sensible default (and currently what's being used), so this PR explicitly sets `perspective=raw` when fetching documents for migration.
Note: If there's a compelling use case for having user-provided perspectives, we can always consider adding support for that that later, but this change ensures that `perspective=raw` is always used, no matter what the default is backend side.
- Does it makes sense?
unit test included
n/a - not visible to end users
> fix(migrate): always use raw perspective for migrations

- packages/sanity/src/core/index.ts
- packages/sanity/src/core/releases/__telemetry__/releases.telemetry.ts
Removes unnecessary exports and removes the `@internal` tag from the releases telemetry events to avoid exporting them in the future by mistake.
> chore(core): remove unnecessary exports

- packages/sanity/src/core/config/__tests__/resolveConfig.test.ts
- packages/sanity/test/testUtils/getMockWorkspaceFromConfig.ts
We recently made Content Releases opt-in, but we didn't opt in for the test environment, causing tests to fail.
This branch opts in the test environment.
> test(sanity): switch on content releases for test workspace

- packages/sanity/src/core/releases/store/createReleaseStore.ts
This branch makes the releases projection more precise, including only fields that are used by the app.
> feat(sanity): include only necessary fields in release projection

- packages/sanity/src/core/releases/store/createReleaseStore.ts
The `userMetadata` field is no longer used, nor is it loaded by the app. This commit removes the defunct mapping of this field.
> chore(sanity): remove defunct `userMetadata` mapping

- packages/sanity/src/core/releases/store/reducer.ts
This commit removes the unused `BUNDLE_RECEIVED` and `BUNDLE_UPDATED` actions from the releases reducer.
> refactor(sanity): remove defunct release reducer actions

- dev/test-studio/schema/debug/components/CreateDraft.tsx
- dev/test-studio/schema/playlist.ts
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/preview/utils/getPreviewStateObservable.ts
- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/DraftLiveEditBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/__tests__/DocumentPerspectiveList.test.tsx
This PR updates how the `liveEdit` documents behave and allows users to edit them while being on the `draft` perspective.
Instead of forcing them to switch to the `published` perspective it shows them with the **published badge** that they are gonna be editing the published document and not the draft. It also adds information in the draft badge on why that one is disabled.
We have two different scenarios to consider for the `liveEdit` documents, draft exists or not.
In most cases the draft won't exist, given it's a live edit.
| Publish perspective | Drafts perspective |
| <img width="1013" alt="Screenshot 2025-02-03 at 09 30 51" src="https://github.com/user-attachments/assets/f69c45b2-aa62-4e77-863d-68421d330323" />| <img width="1011" alt="Screenshot 2025-02-03 at 09 …
> feat(structure): edit `liveEdit` documents through the global draft perspective

- packages/sanity/src/core/releases/store/createReleaseStore.ts
Releases metadata is not a system property, so in some cases this info could not exist.
This modifies the query we use to fetch them and adds default values if the object doesn't exist.
Create a release with no metadata outside of the studio, the studio should load with the default values.
> fix(core): add default values to releases metadata

- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
- packages/sanity/src/structure/components/pane/PaneHeader.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTitle.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx
- Fix design implementation of `VersionChip`
- Fix a regression in how document title was rendered in document panes
> refactor(releases): UI polish

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/overview/CalendarPopover.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
- packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
This has been cleared with Marius!
- When the screen is smaller (and the text starts getting crunched), we hide the calendar and leave it in a popover next to the page title. see video
https://github.com/user-attachments/assets/78edded8-2f02-46ba-97a3-7d7c74252b20
Looks good?
> feat(core): add responsiveness to overview releases page

- packages/@sanity/migrate/src/fetch-utils/__test__/sanityRequestOptions.test.ts
> fix(migrate): update sanityRequestOptions test

- packages/sanity/src/structure/panes/document/DocumentEventsPane.tsx
Live edit documents are shown in the Form even if the release selected is not the `published` one, you can see a live edit document through the `drafts` perspective.
This PR updates how the id for the Events store is calculated, so the published Id is passed to the history store and not the draft when previewing a live edit document which is missing a draft
> fix(core): show accurate history for live-edit documents

- .github/workflows/test.yml
- package.json
- packages/@repo/test-config/package.json
- packages/@sanity/cli/package.json
- packages/@sanity/codegen/package.json
- packages/@sanity/migrate/package.json
- packages/@sanity/mutator/package.json
- packages/@sanity/schema/package.json
- packages/@sanity/types/package.json
- packages/@sanity/util/package.json
- packages/sanity/package.json
- perf/tests/package.json
- pnpm-lock.yaml
New attempt at upgrading vitest to v3, rebased against next since previous review :)
Note: Tests seems to run significantly slower between vitest v2 and v3. Didn't seem worth spending time looking into why since simply increasing test timeouts seems to have fixed it (see c066b138813915fd337a471d3269c7f63c259f0e), and since tests are sharded they usually don't take more than a few mins anyway.
Does the test pass?
Tests should pass
n/a – internal
> chore: upgrade vitest to v3

- playwright.config.ts
Adds a small config change that retries failing e2e tests 4 times in the hopes of alleviating some recurring pains caused by flake.
Does it make sense? Will it take effect?
changes test config, so n/a
n/a – internal
> chore(e2e): retry e2e tests when running in CI

- packages/sanity/src/core/releases/util/util.ts
With upcoming changes to the state machine, an ASAP release will briefly pass through the `scheduling` and `scheduled` states before moving to `publishing` and `published`.
The condition we reuse for determining whether to show the scheduled release UI elements (eg CTAs to schedule/unschedule) currently only checks on the state. This won't be enough when the above state machine change is made - ASAP releases will wrongly at times be shows as scheduled releases.
This change just restricts the condition, requiring that `metadata.releaseType` is `scheduled` first.
Does restricting the conditions for a scheduled release with a `releaseType` assertion make sense?
No regressions expected. Manually tested a few hot spots
> chore: restricting scheduled release UI

- .github/workflows/cli-test.yml
- .github/workflows/test.yml
Node 22 has been out for a closer to a year now, so time to add it to our test matrix I guess :)
n/a internal
> chore(test): add node 22 to test matrix

- dev/test-studio/sanity.config.ts
- packages/@sanity/vision/src/apiVersions.ts
- packages/@sanity/vision/src/components/PerspectivePopover.tsx
- packages/@sanity/vision/src/components/VisionGui.tsx
- packages/@sanity/vision/src/i18n/resources.ts
- packages/@sanity/vision/src/perspectives.ts
This adds some smaller changes to Vision as part of the upcoming default perspective change (from `raw` => `published`):
- Currently, raw is selected as the default. With these changes, the default becomes "unspecified" (i.e. no perspective param is sent with the request, effecively using the default for the given API version). I can imagine this can be useful for debugging. This also means published will soon become the default.
- In accordance with the above, it should then also be possible to select “No perspective” from the dropdown.
- With these changes, you'll get today’s date as the default API version. Currently, we’re using the last element in a [hard coded array of dates](https://github.com/sanity-io/sanity/blob/next/packages/@sanity/vision/src/apiVersions.ts#L2). This means …
> refactor(vision): simplify perspective handling, no default perspective

- packages/sanity/src/core/hooks/useUserListWithPermissions.ts
Currently, every time document form value updates, comments-enabled projects will re-fetch `/projects/<projectId>` via `projectStore.get()`.
Furthermore, `useUserListWithPermissions` uses a global grants cache which could/will cause problem in a multi-workspace studio setting.
This PR reworks `useUserListWithPermissions` so it only fetches projects _once_, as well as removes the global cache in favor of rxjs `shareReply` as a cache layer instead.
Scrutinize the rxjs changes.I am a rxjs noob.
* Is it ok to use `shareReply` to cache like this?
* Are we ok with caching project & grants like this in the first place? 
* As written, memberships and grants will _not_ be kept up to date until the component that runs `useUserListWithPermissions`(`CommentsProvider`) is remounted. Personally, I …
> fix: ensures comments permission check only requests project memberships once

- packages/sanity/src/core/releases/hooks/useDocumentVersions.tsx
The correct usage here should be singular `versionOf`
existing tests should be enough
n/a internal
> fix(releases): change usage of versionsOf to versionOf

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
PTE has a new concept of `@portabletext/editor/plugins` which, going forward, will be the preferred way to add additional Behaviors to the editor. The benefit is that you don't have to manually import and remember to spread the `coreBehaviors` when configuring the `initialConfig.behaviors` array.
Markdown Behaviors should still work, but feel free to take them for a spin to be sure.
n/a
n/a
> fix(core): use `MarkdownPlugin` instead of `behaviors={[...]}`

- packages/sanity/package.json
- packages/sanity/test/matchers/toMatchEmissions.ts
- packages/sanity/test/setup/environment.ts
- pnpm-lock.yaml
This branch adds a `toMatchEmissions` matcher to Vitest. This can be used to assert a specific value is emitted for each value that is piped to a given observable.
```ts
function uppercase(): OperatorFunction<string, string> {
return map((string) => string.toUpperCase())
}
await expect(uppercase).toMatchEmissions([
['a', 'A'],
['foo', 'FOO'],
])
```
```ts
function countSheep(): OperatorFunction<string, number> {
return pipe(
filter((maybeSheep) => maybeSheep === 'sheep'),
scan((sum) => sum + 1, 0),
startWith(0),
)
}
await expect(countSheep).toMatchEmissions([
['aardvark', 0],
['capybara', NO_EMISSION],
['sheep', 1],
['sheep', 2],
['gila monster', NO_EMISSION],
['sheep', 3],
])
```
You can see how this is used in practice by taking a look at the next commit in this Graphite stack.
- Does …
> test(sanity): add `toMatchEmissions` matcher

- packages/sanity/src/core/releases/tool/ReleasesTool.tsx
Changing the `<ReleaseDetail >` component `key` when switching release ensures all local states are updated, preventing bugs like the time picker not updating correctly.
This bug is reproducible when switching the release from the detail screen by clicking in the global picker.
https://github.com/user-attachments/assets/22c8fa44-9fbf-4bf7-88f6-bf0698684a3b
Open the release dashboard, navigate to another release using the global release picker, states should not be mixed between releases.
fixes an issue that when switching releases in the dashboard some local states are not updating accordingly.
> fix(core): reset all releaseDetail states when switching the release

- package.json
#8513 fixed a react compiler [bailout](https://playground.react.dev/#N4Igzg9grgTgxgUxALhAegFQAIFgDYCWAdgC4C0AJgWAIYBGeCWAtjQB5lG4kIVlw08eOjTgBrMFgxoAOkQLMADhBgkswEgE9FTAMo15WgCIQ4UZglIBfLADMYEZlgDkAAVqHNaOIUslncgrKqupaOlgAqmAIMDb2ji7uBgRaaGG4AfJKKmrAkKoAQppxDk7OeBAUNGAAFplBOepQ0QCitrYIcCQANFjNCACyCMwQvf26JDQ8JQnOMAii-oHZIcBwEEQCPXYqYgBSEMS9rIrHMQDmgzSnWOlYAPJ00TAAbvSMvRC2vWAA7ilwGoDa4zMowNgAKzAmWWwVyciwt20TBMZgspAAaoIoAgAAoxZjUMAEDbdBFYc4wAwkMD4mCEsDEjb3IhkoiIu64hwQzokIxTGhsxH9LkQHldCYqBBCvrRKIxSXzNmglwAOlVaDAJCl9RWuSMLQAYgBBCIAGQAKgB9XQWiJGACS9ytAGEzQ6WgA5a33XEWp2e3Qq5zqzUkKBUCAu3ykXVwprRaMEPzBjX9JN+GGkZFYM0QGhVBgIAA8FoAfFgALzqclVSbILAWrAAHywRCgQnJMQcMAbLRgPZbbY7eHJFQLxHODboEAgjAMciscjkmAwCOwrjoCEm66wrhqBAoFEs69kXDY8bu8pgZuoJAA6ikanSGUyiGAABKzsRYvA4qu5vmhaMMW16PiQz4EkSJJEAA2gAuhWABkNbslgq …
> chore: update compiler warnings counter

- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusLine.tsx
Fixes this warning:
In `framer-motion` v12 the `motion()` utility is deprecated, and `motion.create()` should be used instead. Maybe we should add a linter rule to prevent it from sneaking back in?
`pnpm dev`, as the warning isn't shown in production only on `sanity dev` or `next dev`.
Annoying, and unactionable, `motion() is deprecated. Use motion.create() instead.` warnings are handled and should no longer spam your developer console ❤
> fix: handle `motion()` deprecation warning

- packages/sanity/src/core/perspective/navbar/ReleasesList.tsx
Removes the  `<Box>` that is wrapping the list and the button, this box was blocking the gap property the menu has, so the items were rendering without space between them.
**See New release button**
|<img width="339" alt="Screenshot 2025-02-07 at 15 07 27" src="https://github.com/user-attachments/assets/2475182d-7581-4e22-9fb0-29a6eb596091" />|<img width="347" alt="Screenshot 2025-02-07 at 15 06 43" src="https://github.com/user-attachments/assets/ab020840-c96f-4700-ab36-82cd7a2b0b6a" />|
This do not affect users with releases disabled.
> fix(core): add breathing space for release create button in picker

- .github/CODEOWNERS
assign releases codeowners to studio-app
n/a internal
> chore(core): assign releases codeowners to studio-app

- .github/workflows/e2e-ct.yml
- .github/workflows/e2e.yml
- .github/workflows/efps.yml
- .github/workflows/test.yml
We often get congestion and bottlenecks if there's a lot of PRs being worked on, as the default `ubuntu-latest` runner has a 60 concurrent builds limit. Current queue status is visible here: https://github.com/organizations/sanity-io/settings/actions/hosted-runners
Based on the stats [here](https://github.com/sanity-io/sanity/actions/metrics/performance?sort=jobs), I picked the jobs that use the most resources on two new images, `ubuntu-latest-m` and `ubuntu-22.04-m`, which have their own separate 60 concurrent builds limits, and have more memory and more CPU cores (as well as faster ones).
Everything should work like before, only faster and less bottlenecks on the PR checks.
If the status checks behave exactly like before (but faster) then we're good to go 👍 
N/A
> chore: test larger gh runners

- packages/sanity/src/core/releases/components/dialog/DiscardVersionDialog.tsx
- packages/sanity/src/core/releases/components/dialog/UnpublishVersionDialog.tsx
- packages/sanity/src/core/releases/hooks/useVersionOperations.tsx
Fixes an issue when discarding or un-publishing documents, instead of the release document title we were sending to the toast the window.document.title , so it was showing an incorrect value.
This fixes it by passing the preview value to the toast.
Discard or un-publish a document inside a release, the document title should render in the toast.
https://github.com/user-attachments/assets/a9e13780-6217-4405-80b8-ce7d219fb030
fixes an issue with incorrect titles shown in when discarding or un-publishing a document inside a release
> fix(core): use preview value title when unpublishing or discarding a document

- .github/workflows/e2e-ct.yml
- .github/workflows/e2e-ui.yml
- .github/workflows/e2e.yml
- .github/workflows/efps.yml
- .github/workflows/perf.yml
I got a strange error on the CI on another PR:
Turns out the `Cache Playwright Browsers for Playwright's Version` step is failing to restore the cache:
```bash
Cache restored successfully
Cache restored from key: playwright-browsers-
```
It should be restoring the cache from `playwright-browsers-1.50.1`, but it's falling back to some previous cache step that had an empty `PLAYWRIGHT_VERSION` env var.
This issue started appearing after #8552 merged. This PR changes it so that the playwright version is stored with the GitHub output API instead of an intermediary env var.
It also shifts the cache key to `${version}-playwright-browsers`. That way, if `1.50.1-playwright-browsers` has no match, github will look at these as fallbacks:
```bash
1.50.1-playwright-browsers
1.50.1-playwright
1.50.1 …
```
> fix(CI): update playwright cache on CI consistently

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardDetails.tsx
Change the messages so that it'll show schedule if it's a release can can be scheduled or publish if it's a release that can be published
This is a more naive way of handling these errors without taking into account spceifically the error messages that come from the backend, however, it should be enough for now. If it needs a finer touch we can come back and adjust accordingly. A story has been created as a follow up.
Do you agree with my assessment? The code?
Existing tests should be fine
Update translations for error messages in releases.
> chore(core): update message to be schedule or publish error

- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
Before: Creating a new scheduled release will set the default scheduled time **to be the next minute**
After: Creating a new scheduled release will set the default scheduled time **to be the start of the next hour**
| <img width="496" alt="Screenshot 2025-02-10 at 17 54 27" src="https://github.com/user-attachments/assets/d4390404-5b9e-4710-89b3-15e3ba3a5236" /> | <img width="507" alt="Screenshot 2025-02-10 at 17 54 02" src="https://github.com/user-attachments/assets/3c8e123e-8810-4252-a240-7c8d5da0a5a7" /> | 
There aren't currently any tests covering this story
N/A
> feat: creating new scheduled release defaults time to start of next hour

- .github/workflows/cli-test.yml
CLI tests are sometimes flaky. This adds retrying to cli tests similar to what we did for e2e tests in #8501, and unit tests in #8371
Makes sense?
n/a – internal
> test(cli): add retry for cli tests

- packages/sanity/playwright-ct.config.ts
Bumping number of retries component tests on CI from 2 to 6 to mitigate flake.
Yep :)
n/a
> test(playwright-ct): bump number of retries for playwright ct tests

- packages/sanity/src/structure/documentBadges/LiveEditBadge.ts
Currently, when editing a version document, we'll show a "Live" badge. This fixes the issue by using the `liveEditSchemaType` instead, which reflects the schema config instead of the "mode" of the selected document
- The "Live"-badge should not show in the footer when editing a version (even if the schema has liveEdit enabled)
- The "Live"-badge should show in the footer when editing a document where the schema has live edit enabled
n/a
> fix(sanity): don't show Live edit badge for versions

- packages/sanity/src/core/hooks/useClient.ts
- packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
- packages/sanity/src/presentation/useDocumentLocations.ts
- packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx
- packages/sanity/src/structure/panes/documentList/__tests__/PaneContainer.test.tsx
(meta: wrong ticket id, should've been sapp-2049)
This explicitly uses `raw` as perspective unless overridden (e.g. by perspective stack)
This change should be safe, given that raw is currently the default on existing API versions.
Does the change make sense? As of this PR, Studio should longer do `/query` requests without a perspective param.
Everything should work as before
n/a - not user facing
> fix(sanity): use raw as default perspective

- packages/sanity/src/core/error/ErrorLogger.tsx
- packages/sanity/src/core/error/__tests__/ErrorLogger.test.tsx
- packages/sanity/src/core/studio/StudioErrorBoundary.tsx
- packages/sanity/src/core/studio/ViteDevServerStopped.tsx
Improves error handling for Vite dev server errors by adding type checking to ensure the error object is properly validated before accessing its properties. This prevents potential runtime errors when checking for `ViteDevServerStoppedError`.
- Error handling logic in `ErrorLogger.tsx` and `StudioErrorBoundary.tsx`
- Type checking implementation for the error object before accessing `ViteDevServerStoppedError` property
- Consistency of error handling between both files
The changes have been tested by verifying error handling behavior when:
- Vite dev server stops unexpectedly
- Different types of errors are thrown
- Invalid error objects are passed
Fixed an edge case where Vite dev server error handling could fail due to improper checking.
> fix(core): adds proper check for vite dev server stop

- packages/sanity/src/core/comments/store/useCommentsStore.ts
- packages/sanity/src/core/tasks/store/useTasksStore.ts
- packages/sanity/src/presentation/useDocumentLocations.ts
- packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts
- packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetListStore.ts
Added `tag` property to listen options across various store implementations
- Verify tag names are descriptive and accurately represent their respective listeners
- Check that all relevant listen option configurations include the new tag property
Existing functionality remains unchanged as this is a monitoring enhancement. The addition of tags does not affect the behavior of listeners.
N/A
> fix: add missing tags for listen queries

- packages/sanity/src/structure/panes/types.ts
- packages/sanity/src/structure/panes/userComponent/UserComponentPane.tsx
Edge case, but some plugins/setups apparently define a `key` property for structure `component` panes, which gives a warning about `A props object containing a "key" prop is being spread into JSX` when we render. This PR explicitly calls out `key` as being deprecated/should be avoided, but also picks it out of the props being spread and explicitly forwards it. This ensures backwards compatibility as well as avoiding the error, and potentially helps developers know not to pass it in the first place.
User component panes still work as expected
Very edge-case, so not adding a test here.
None
> fix(structure): avoid spreading `key` into props, pass explicitly

- packages/sanity/src/presentation/PresentationTool.tsx
- packages/sanity/src/presentation/__tests__/usePreviewUrl.test.tsx
- packages/sanity/src/presentation/editor/PostMessagePreviewSnapshots.tsx
- packages/sanity/src/presentation/loader/__tests__/turboChargeResultIfSourceMap.test.ts
- packages/sanity/src/presentation/loader/__tests__/useLiveQueries.test.ts
- packages/sanity/src/presentation/useMainDocument.ts
Since https://github.com/sanity-io/client/pull/1007 the client warns when using `perspective: 'previewDrafts'`. This PR refactors to the new `perspective: 'drafts'` approach.
> fix(docs): replace `previewDrafts` with `drafts`

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
The `MarkdownPlugin` now ships with automatic bold/italic shortcuts that you can opt in to by defining an `italicDecorator` and/or a `boldDecorator`. The italic decorator is then mapped to `*`/`_` pairs and the bold decorator is mapped to `**`/`__` pairs.
Following the standard behaviour that is observed in most other text editors, the mapping only occurs when the end char is inserted. For example, typing `*foo` and then `*` makes `foo` italic, but typing `foo*` and then adding a `*` before `foo*` does nothing.
After a mapping occurs, if you didn't like it, you can undo it as expected. And if you don't move your cursor, you can even undo it by hitting Backspace.
Try it out and see if it works as expected :)
Note: There is one known flaw in the RegEx that is used. `*hello*world*` matches …
> feat(core): add default bold/italic markdown shortcuts to PTE

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/columnCells/ReleaseDocumentsCounter.test.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseDocumentsCounter.tsx
In releases Overview the documents row has:
* 'Documents' header
* Just show the count in the cells
| <img width="369" alt="Screenshot 2025-02-10 at 17 48 43" src="https://github.com/user-attachments/assets/06e845a1-e524-45cd-ad30-c8ca513796c9" /> | <img width="348" alt="Screenshot 2025-02-10 at 17 49 47" src="https://github.com/user-attachments/assets/b83d7bfd-4dd2-48a4-ada0-52b4d404fd98" /> | 
Updated the existing tests
Added a few tests for the document counts
N/A
> feat: updating document count for release overview cells

- packages/sanity/src/structure/constants.ts
- packages/sanity/src/structure/getIntentState.ts
This fixes a bug where the EMPTY_PARAMS object is modified
Fixes a bug that could cause initial value template parameters to carry over from an earlier document
> fix(structure): don't modify EMPTY_PARAMS object

- packages/sanity/src/core/perspective/types.ts
- packages/sanity/src/core/perspective/usePerspective.ts
- packages/sanity/src/core/releases/store/types.ts
Making the `usePerspective` hook `@beta` for `tsdocs`. Also updating the associated types used in `PerspectiveContextValue`
* Is it right to move to `@beta` for these types
* The comment added to `usePerspective` - does this look ok?
N/A
> docs(core): exposing `usePerspective` and updating tsDoc

- packages/sanity/README.md
Before
After
Did a few additional minor tweaks:
- Replaced `<p>` with `<div>`, since headers are not a valid descendant of paragraphs
- Removed whitespace after the image, which got rendered as underline
Do we want to keep the old one? Can think of lots of good reasons not to, but happy to review a follow-up PR that adds it back.
n/a
n/a
> chore: update social badge in readme

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentButton.tsx
| <img width="331" alt="Screenshot 2025-02-12 at 16 55 44" src="https://github.com/user-attachments/assets/1f3d3a1f-a48c-4b26-8308-51a8817bff56" /> | <img width="350" alt="Screenshot 2025-02-12 at 16 55 24" src="https://github.com/user-attachments/assets/5d533920-d75c-4de1-b8d9-cd577bdf1203" /> | 
When the perspective is published, the tooltip on create new document is more appropriate named
N/A
N/A
> fix(core): create new doc button tooltip updated for when perspective is published and not a release

- packages/sanity/src/core/search/common/__tests__/deriveSearchWeightsFromType2024.test.ts
- packages/sanity/src/core/search/common/deriveSearchWeightsFromType2024.ts
This branch ports the recursion fixes contributed by Nikas in #7999 to `deriveSearchWeightsFromType2024`.
- All Studio search surfaces should respect weights configured in schema.
- Adds unit test contributed by Nikas.
> fix(sanity): apply recursion fix to `deriveSearchWeightsFromType2024`

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseScheduleButton.tsx
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseUnscheduleButton.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseName.tsx
Various improvements including:
* Cannot schedule release with validation errors
* Cannot cancel scheduling/unscheduling of release whilst the action is in progress
* Cannot cancel archive/unarchive/delete of release whilst the action is in progress
* Action confirm dialog does not show description if there are no documents in release
* Release Overview header styles to align Release title header with preview card
* Release Overview can be sorted by release title
N/A
> fix: release action dialog fixes; release overview style 

- package.json
- packages/sanity/playwright-ct/tests/fixtures/copyPasteFixture.ts
- packages/sanity/playwright-ct/tests/fixtures/debugFixture.ts
- packages/sanity/playwright-ct/tests/fixtures/scrollToTopFixture.ts
- packages/sanity/src/core/hooks/useGlobalCopyPasteElementHandler.ts
- packages/sanity/src/core/tasks/components/form/tasksFormBuilder/FormCreate.tsx
- packages/sanity/src/core/tasks/hooks/useActivityLog.ts
- packages/sanity/src/presentation/PresentationTool.tsx
- packages/sanity/src/presentation/document/PresentationDocumentProvider.tsx
- packages/sanity/src/presentation/loader/LiveQueries.tsx
- packages/sanity/src/presentation/useMainDocument.ts
- packages/sanity/src/structure/panes/document/documentPanel/documentViews/FormView.tsx
- packages/sanity/src/structure/panes/document/useResetHistoryParams.ts
- pnpm-lock.yaml
The `eslint-plugin-react-hooks` linter now supports `useEffectEvent`, when using the experimental release. More info: https://react.dev/reference/react/experimental_useEffectEvent
The renaming of `use` to `_use` in the tests are due to some red herrings where the linter thought it was related to `React.use`:
```bash
error  React Hook "use" is called in function "page" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"   
```
CI linter is enough.
N/A
> chore: use `useEffectEvent` aware linting

- packages/sanity/src/core/hooks/__mocks__/useProjectSubscriptions.mock.ts
- packages/sanity/src/core/hooks/useProjectSubscriptions.ts
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/components/dialog/TitleDescriptionForm.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardDetails.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardHeader.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseTypePicker.test.tsx
PR makes changes for archived and published release details:
* 'Release' breadcrumb links back to the archived grouping on release overview
* 'Pin release' hidden on archived and published release details
* Release Type picker hidden on archived release detail
* Published release type uses icon and updated style
* Release title and description are `readOnly` on archived and published release detail
* Retention card added on archived and published release detail
* Adding `useProjectSubscription` to get the retention period - this is a close copy of `useFeatureEnabled`
* Style updates look ok?
* Updated tests on `ReleaseDetail` to cover the new scenarios for archived and published releases
N/A
> fix(releases): improvements to archive release detail

- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx
Only show errors for the error count in the release documents row.
Open a release in which a document has both error and warnings or info, the document should only account for the number of errors.
n/a
> fix(core): in release documents rows only show errors count

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
This branch updates tooltip copy and reduces its stack spacing a little to make it a bit more visually comfortable.
_The tooltip_ [waves arms in air]
Try the new tooltip. I think you're going to love it.
> chore(sanity): update release time tooltip

- packages/sanity/src/core/hooks/useProjectSubscriptions.ts
@bjoerge This resolved the comments you'd made in https://github.com/sanity-io/sanity/pull/8597
* Move to `interface` over `type`
* Correct some incorrect types on the subscription
* `@internal` for these types and the hook
N/A
N/A
> chore: improving type definition for useProjectSubscriptions

- packages/sanity/src/core/preview/createGlobalListener.ts
- packages/sanity/src/core/releases/tool/detail/events/getReleaseEditEvents.test.ts
- packages/sanity/src/core/releases/tool/detail/events/getReleaseEditEvents.ts
- packages/sanity/src/core/releases/tool/detail/events/getReleaseEvents.ts
The Releases Activity Panel was previously relying on release documents from the **releases store**. Initially, these documents were complete. However, we recently introduced a [projection to the documents](https://github.com/sanity-io/sanity/blob/sapp-2101/packages/sanity/src/core/releases/store/createReleaseStore.ts#L39-L60), which means they are now **partial**.
The activity panel retrieves changes using the **transactions endpoint** and applies **Mendoza patches** to the documents. However, Mendoza patches require **complete documents** to function correctly—they **do not** work with partial documents.
---
This PR refactors the `getReleaseEditEvents` observable to use the new `observeDocument` observable, which ensures that **complete** documents are returned. This resolves the issue …
> fix(core): releases edit events error when calculating differences

- packages/sanity/src/core/releases/i18n/resources.ts
Updates the text for the Publish now action in releases from "Publish all documents" to "Run release"
> fix(core): change publish now release action wording

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/perspective/navbar/ReleasesList.tsx
- packages/sanity/src/core/perspective/navbar/__tests__/ReleasesList.test.tsx
- packages/sanity/src/core/perspective/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/releases/components/dialog/CreateReleaseDialog.tsx
- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
- packages/sanity/src/core/releases/components/documentHeader/contextMenu/VersionContextMenu.tsx
- packages/sanity/src/core/releases/components/documentHeader/contextMenu/__tests__/VersionContextMenu.test.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
- packages/sanity/src/core/releases/util/const.ts
- packages/sanity/src/ui-components/menuGroup/MenuGroup.tsx
- packages/sanity/test/mocks/useDocumentPairPermissions.mock.ts
Prevent create release
Discard version discard
Anything could be improved?
The existing test should be enough.
Can manually test by following the screenshots
Discard version and create releases action menus and buttons for releases now respect permissions.
> fix(core): add permission limitation for create release

- packages/sanity/src/structure/structureBuilder/Intent.ts
Updated the TSDoc links for Intents. They are currently pointing to `router.BaseIntentParams` and `router.IntentJsonParams`.  Those links don't resolve. 
This PR updates the the links to `structure.BaseIntentParams` and `structure.IntentJsonParams`. 
https://www.sanity.io/docs/reference/api/sanity/structure/BaseIntentParams
https://www.sanity.io/docs/reference/api/sanity/structure/IntentJsonParams
related to DOCS-841
> chore(sanity): fix intent params links

- packages/@sanity/cli/src/actions/init-project/bootstrapLocalTemplate.ts
- packages/@sanity/cli/src/actions/init-project/createCoreAppCliConfig.ts
- packages/@sanity/cli/src/actions/init-project/createStudioConfig.ts
- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/src/types.ts
FIXES SDK-180
Since core applications will not be attached to specific projects, they need to be attached to organizations instead. This PR updates the `sanity init --template core-app` process to use the "select organization" part of the CLI flow and pass the resulting organization ID to the `sanity.cli.ts` template.
This should hopefully be straightforward. I had to update some variable names in legacy code because of an ESLint `no-shadow` rule. If you disagree with this choice, please let me know!
1. Run `pnpx sanity@3.74.2-canary.67+a9a66e73d5 init --template core-app`
2. Verify that you are prompted for an organization.
3. Verify that the organization ID is in your `sanity.cli.ts`
None, should be internal.
> feat(cli): select org and add to sanity.cli.ts on initialization

- dev/design-studio/package.json
- dev/embedded-studio/package.json
- dev/studio-e2e-testing/package.json
- dev/test-studio/package.json
- examples/ecommerce-studio/package.json
- package.json
- packages/@sanity/vision/package.json
- packages/sanity/package.json
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardHeader.tsx
- pnpm-lock.yaml
Needing to make a hotfix as we have reports of framer motion warnings taking over the studio experience which is caused in Sanity UI. See more in this [PR](https://github.com/sanity-io/ui/pull/1604).
Check the PR above and the framer motion [changelog](https://github.com/motiondivision/motion/blob/main/CHANGELOG.md)
n/a
A fix needed in order to ensure that locally running studios don't receive a warning from framer motion due to the downstream dependency update.
> fix: bump sanity ui

- packages/@sanity/util/package.json
Looks like a formatting issue with the `sanity` package's package.json managed to sneak into `next`. This patch should fix it.
Fixed by sorting dependencies
n/a
n/a
> chore: fix package.json formatting

- packages/sanity/src/core/perspective/navbar/GlobalPerspectiveMenuItem.tsx
- packages/sanity/src/core/perspective/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/releases/__fixtures__/release.fixture.ts
This branch adds release error indicators to the global perspective menu.
- The global perspective menu for releases in an error state.
- Added unit test.
- Manually tested with a release that has an error.
- Manually tested with a locked release that has an error, to ensure the states combine harmoniously.
> feat(sanity): add granular release error icons to global switcher

- packages/sanity/src/core/error/types/isErrorWithDetails.ts
- packages/sanity/src/core/releases/contexts/upsell/ReleasesUpsellProvider.tsx
- packages/sanity/src/core/releases/contexts/upsell/types.ts
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
- packages/sanity/src/core/releases/store/isReleaseLimitError.ts
- packages/sanity/src/core/releases/store/useReleasePermissions.ts
With the new permission checks for releases (by running a `dryRun` release action to check for permissions, there were some issues when the project was already at the release limit for the plan.
> [!NOTE]
> The Upsell components here will be further updated for organisation level limit - this is a stopgap until then so will be very short lived
**No Permissions but at release limit**
Before:
The upsell would keep flashing repeatedly (because of the dryRun request triggering the dialog)
After [FIXED]:
The create buttons are enabled (this is because content lake returns the limit error rather than the permission error - which will be changed shortly), but the upsell only shows when an action is attempted by the user
**No Permissions but under the limit**
Before:
The create buttons are …
> fix(releases): handling cases where no create release permissions whilst at limit of release in project

- packages/sanity/src/core/releases/components/dialog/TitleDescriptionForm.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDetailsEditor.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetailsEditor.test.tsx
If a user doesn't have user permissions, they will not be allowed to edit the title (or perceive that they could otherwise).
| With Permission    | Without Permission |
<video src="https://github.com/user-attachments/assets/a46d88e8-3547-4a02-a11c-764ef49c7a96">  |  <video src="https://github.com/user-attachments/assets/ec7ba185-70ed-4b1d-8055-71380c2a4c75">
|
Double check the code makes sense,
I thought that I could have done the check all the way in the ReleasesList (which also calls for the same method in the useEffect, however, I felt like it made more sense to cause a re-render further down _if_ it's needed than potentially re-rendering multiple things at a component at a higher level since that's not the only child that it has)
Unit tests added
You should be …
> refactor(core): prevent updating release title and description if the user doesn't have permissions

- packages/sanity/src/core/releases/tool/detail/AddDocumentSearch.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItem.tsx
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/SearchProvider.tsx
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts
If a user doesn't have create permissions they will have the action disabled in the search for the release details. **Searching should still work**
https://github.com/user-attachments/assets/f0192bf9-b543-47ab-9c46-d25f9cd6e351
Thoughts? Concerns?
Existing tests should be enough
Search items in a Release Detail now respect role permissions
> fix(core): add permission limitation for adding new version in the release details search

- .github/workflows/efps.yml
The `ubuntu-latest-m` machines have been changed from 4 cores to 2 cores, and it seems like their RAM is no longer sufficient to run the EFPS suite.
> chore: swap to ubuntu-latest

- dev/studio-e2e-testing/sanity.config.ts
- packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceInput.tsx
- packages/sanity/src/core/releases/store/__tests__/createReleaseOperationsStore.test.ts
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
- packages/sanity/src/core/releases/util/prepareVersionReferences.ts
- test/e2e/tests/inputs/reference.spec.ts
The strengthen-on-publish process is not necessary for documents inside a release, and in fact must be skipped in order for release preflight checks to function.
Strengthen-on-publish is still necessary for drafts, and for documents in a bundle *that isn't a release* (this isn't a scenario Studio supports today, but it may need to in the future).
This branch prevents the `_weak` property being added to references in version documents **unless the reference is defined as weak in the schema**, thereby skipping the strengthen-on-publish process for documents inside a release.
The `_strengthenOnPublish` field is always set, regardless of whether the strengthen-on-publish process should be used. This is because the field is used to store details such as the non-existing document's type, which …
> feat(sanity): skip strengthen-on-publish process for documents inside a release

- packages/sanity/src/core/releases/components/dialog/DiscardVersionDialog.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
Updates the wording for the discard version dialog
| <img width="1170" alt="Screenshot 2025-02-17 at 18 38 30" src="https://github.com/user-attachments/assets/924514e0-6a38-441b-a8fe-20059e8d1a1c" /> | <img width="1168" alt="Screenshot 2025-02-17 at 18 36 48" src="https://github.com/user-attachments/assets/fdcded53-49e7-4a9c-99f9-4b007c117421" /> |
> fix(core): clarify 'discard version' message for better understanding

- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardActivityPanel.tsx
Removes the activity panel borders to match with the prototype designs.
> fix(core): remove activity panel borders

- dev/test-studio/components/panes/JsonDocumentDump.tsx
- packages/@sanity/vision/src/components/VisionGui.tsx
- packages/sanity/src/core/comments/store/useCommentsStore.ts
- packages/sanity/src/core/preview/createGlobalListener.ts
- packages/sanity/src/core/preview/liveDocumentIdSet.ts
- packages/sanity/src/core/releases/store/createReleaseMetadataAggregator.ts
- packages/sanity/src/core/store/_legacy/document/getPairListener.ts
- packages/sanity/src/core/store/_legacy/document/listenQuery.ts
- packages/sanity/src/core/tasks/store/useTasksStore.ts
- packages/sanity/src/presentation/overlays/PostMessageDocuments.tsx
- packages/sanity/src/structure/panes/documentList/listenSearchQuery.ts
- packages/sanity/src/structure/panes/documentList/sheetList/useDocumentSheetListStore.ts
In order to prepare for an upcoming API change, we want to explicitly add `includeAllVersions` to all the /listen calls made by the Studio.
- Ideally, after this PR, there shouldn't be any listen calls made from the studio that doesn't pass `includeAllVersions`. It's only a critical requirement for new code paths that will expect version documents, but for consistency it makes sense to use it everywhere.
- A bit of manual testing required unfortunately; open the studio with these changes applied, make sure all listen requests going from the studio are passing `includeAllVersions=true`
n/a – internal
> refactor: pass includeAllVersions to listeners

- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
Patches submitted to the `handleChange` provided by `DocumentPaneProvider` are currently disallowed when the document is in a read-only state. This renders it impossible to unlink a Create-linked document, which relies on a patch being created programmatically.
This branch sidesteps the issue by excluding Create-linked documents from the read-only check.
- `handleChange` may now patch any part of a Create-link document that would otherwise be read-only. Is this acceptable?
Unlink a Create-linked document.
Fixes a bug preventing Sanity Create documents from being unlinked.
> fix(sanity): allow patching via `handleChange` in Create-linked documents

- packages/sanity/src/core/studio/StudioTelemetryProvider.tsx
This removes the coercing of workspace names to well known names before logging to telemetry.
n/a
> refactor(telemetry): log workspace and dataset names

- packages/sanity/src/core/releases/store/__tests__/createReleaseOperationsStore.test.ts
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleasePublishAllButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardDetails.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx
Remove unstable (and no longer needed) publish 2 and confirm-2 mentions across the release feature.
Did I miss something? Any odd behaviours that were missed?
Publishing a release should work as it did before.
N/A
> refactor(core): remove publish2 and confirm-2

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDashboardFooter.test.tsx
Updates the text in release schedule actions .
> fix(core): revise wording for releases schedule actions

- packages/sanity/src/core/preview/createObserveDocument.ts
- packages/sanity/src/core/preview/documentPreviewStore.ts
- packages/sanity/src/core/preview/useLiveDocumentSet.ts
- packages/sanity/src/core/preview/useObserveDocument.ts
- packages/sanity/src/core/releases/tool/detail/events/getReleaseEvents.ts
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
Updates the `unstable_observeDocuments` function to accept a apiPerspective param, given we need to query version documents using `vX` for now
When we worked on https://github.com/sanity-io/sanity/pull/8466 version documents were returned even when using a version prior to `2025-02-19` which is the stable version for releases.
Now a flag has been turned on in content lake and the version documents are not returned anymore unless you are using `2025-02-19` or above.
By updating this function and passing the apiVersion as a parameter, we can configure it so it uses `vX` when fetching for version documents.
would be amazing if you could help me review if there is other place that should be updated to include this change.
Navigate in the studio, queries should work as always, version …
> fix(core): add api version config to `observeDocuments`

- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/config/resolveDefaultPlugins.ts
- packages/sanity/src/core/scheduledPublishing/components/infoCallout/InfoCallout.tsx
- packages/sanity/src/core/scheduledPublishing/components/warningBanner/WarningBanner.tsx
- packages/sanity/src/core/scheduledPublishing/constants.tsx
- packages/sanity/src/core/scheduledPublishing/hooks/usePollSchedules.ts
- packages/sanity/src/core/scheduledPublishing/plugin/index.ts
- packages/sanity/src/core/scheduledPublishing/tool/Tool.tsx
- packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.test.tsx
- packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.tsx
- packages/sanity/src/core/scheduledPublishing/types.ts
- packages/sanity/src/core/studio/components/navbar/tools/StudioToolMenu.tsx
With the introduction of releases we want to start moving users into it and out of `scheduled publishing` , to do this we will make scheduled publishing opt in.
Scenarios considered:
- Workspaces that have previously used scheduled publishing.
- Workspaces that have not used scheduled publishing.
- Workspaces that have enabled scheduled publishing in the config (this is not required[ since this was moved into core](https://github.com/sanity-io/sanity/issues/6416))
We rely on the information provided by the schedules endpoint `/schedules/<projectId>/<dataset>`. If this endpoint returns at least 1 schedule it means that the workspace has previously used it.
**Workspaces that have previously used scheduled publishing.**
If they have previously used it we will continue showing the document …
> fix(core): hide schedule publishing if not used and not enabled by users

- packages/sanity/src/core/releases/components/dialog/TitleDescriptionForm.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
- packages/sanity/src/core/releases/tool/overview/queryParamUtils.ts
This PR updates the archived releases table overview.
Adding two columns that are exclusive for this view:
- **Published**
- **Archived**
This will be the anchor for users to make it possible to determine if a release was published or archived.
It also renames the **Open** tab to **Active**
And fixes a small oversight in were users could edit archived releases descriptions.
> feat(core): updates archived releases overview

- packages/sanity/src/core/perspective/navbar/ReleasesList.tsx
- packages/sanity/src/core/perspective/navbar/__tests__/ReleasesList.test.tsx
- packages/sanity/src/core/perspective/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/releases/components/documentHeader/contextMenu/VersionContextMenu.tsx
- packages/sanity/src/core/releases/components/documentHeader/contextMenu/__tests__/VersionContextMenu.test.tsx
- packages/sanity/src/core/releases/store/__tests__/__mocks/useReleasePermissions.mock.ts
- packages/sanity/src/core/releases/store/__tests__/createReleasePermissionsStore.test.ts
- packages/sanity/src/core/releases/store/createReleasePermissionsStore.ts
- packages/sanity/src/core/releases/store/useReleasePermissions.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenu.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/__tests__/ReleaseMenuButton.test.tsx
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleasePublishAllButton.tsx
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseScheduleButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardDetails.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDetailsEditor.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetail.test.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseDetailsEditor.test.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
- Updates permissions hook logic to use a store that takes advantage of the resourceCache in the studio
- A lot of file changes are related to updating mocks and making things in tests a bit smoother. Don't be scared by the number of files changed
This will then mean that there is no need to make needless dryRun requests multiple times exponentially reducing the number of calls in the release package.
Everything make sense?
Updated the tests and mocks, everything should work as expected.
N/A
> refactor(core): update managing permissions 2

- packages/sanity/src/core/store/_legacy/ResourceCacheProvider.tsx
In cases where resourceCache is `set` and `get` with no dependencies, eg:
```ts
resourceCache.get({
dependencies: [],
namespace: 'myNamespace',
})
```
Then the weak map key would be a different reference each time, meaning setting and getting wouldn't return the correct namespace value.
This change essentially maps the case of `dependencies: []` to become a weak map key of `[{}]`, where `{}` is always the same reference (`nullReplacer`).
Testing manually by... seeing that it fixed the issue, whilst also regression testing that passing non empty dependencies doesn't break
N/A - `ResourceCache` is internal only
> fix(core): handling cases where no dependencies are passed to a resourceCache value set

- packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
The navbar will now react at an earlier point so that the menu items don't overlap
This took me too embarrassingly long to figure out where I need to make the change 🫠 
Before
After
<video src="https://github.com/user-attachments/assets/30bf880e-fede-440c-95a7-a142b98ebe8d">
You can test it out on the preview deployment
N/A
Responsible improvements on the nav ba
> fix(core): update responsive design on navbar

- packages/sanity/src/core/releases/__fixtures__/release.fixture.ts
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseTypePicker.test.tsx
In some scenarios, the release type picker produces a changed release object, despite the user making no intentional changes.
For example: when transitioning from an "at time" to an "ASAP" release, and then back again (without first closing the picker), the initial `metadata.intendedPublishAt` value is lost. This causes a mutation to occur when the user closes the release type picker when no mutation was expected. This is problematic because it produces an unexpected spinner in the UI, and could cause subtle unintended mutations.
This branch fixes several scenarios that provoked this bug.
The release type picker.
Added component tests for the known scenarios that provoke this bug.
Fixes a bug that caused the release type picker to unexpectedly enter a loading state.
> fix(sanity): prevent unexpected release type picker mutation

- packages/sanity/src/core/releases/components/documentHeader/contextMenu/VersionContextMenu.tsx
When conducting a discard permission check for a draft document, the `version` is erroneously set to a draft document id.
This manifests as a crash when opening the context menu of the "draft" version chip in the document editor (typically by right-clicking it).
This branch fixes the bug by ensuring no `version` value is provided for drafts. `version` is now only provided for version documents, and always reflects the release id.
The version chips in the document editor. In particular, the "draft" version chip.
- Can open context menu for all version chips
- Published
- Draft
- Versions
> fix(sanity): discard draft permission check

- packages/sanity/src/_singletons/context/ScheduledPublishingEnabledContext.ts
- packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.tsx
Fixes #8712
The scheduled publishing plugin currently inserts a context provider, but if the plugin is not enabled specifically, this context provider won't be inserted in the layout, causing the useScheduledPublishingEnabled() to throw due to missing context value.
Does this make sense as a fix? Are there better ways of solving this?
A Studio that does not enable scheduled publishing should not fail because of missing context.
- Fixes an issue that could cause an error for Studios without Scheduled publishing enabled.
> fix: add fallback context value for scheduled publish enablement

- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
This `useInsertionEffect` hook was recently updated, but the new dependency was not added.
This mistake wasn't caught by our linter. We should investigate why.
The new hook dependency.
The document editor renders correctly.
> fix(sanity): add missing `useInsertionEffect` hook dependency `isCreateLinked`

- packages/@sanity/vision/src/components/VisionGui.tsx
- packages/sanity/src/core/comments/i18n/resources.ts
- packages/sanity/src/core/comments/plugin/inspector/CommentsInspector.tsx
- packages/sanity/src/core/components/errorActions/strings.ts
- packages/sanity/src/core/components/errorActions/useCopyErrorDetails.ts
- packages/sanity/src/core/i18n/bundles/copy-paste.ts
- packages/sanity/src/core/scheduledPublishing/hooks/useTimeZone.tsx
- packages/sanity/src/core/studio/copyPaste/CopyPasteProvider.tsx
- packages/sanity/src/core/studio/copyPaste/__test__/useCopyPaste.test.tsx
- packages/sanity/src/core/tasks/context/navigation/TasksNavigationProvider.tsx
- packages/sanity/src/structure/components/confirmDeleteDialog/ConfirmDeleteDialogBody.tsx
- packages/sanity/src/structure/i18n/resources.ts
This branch removes a handful of success toast messages across the Studio codebase that are arguably redundant because they can largely be expected to succeed immediately and reliably.
There is a commit for each affected toast. Do they all seem reasonable? Note: Marius has reviewed and approved the removals.
Existing tests pass.
Some success toast messages have been removed in order to streamline Studio UI. These removals have been made where there is a reasonable expectation the operation will succeed immediately and reliably (for example, when copying a value to the clipboard). Error toast messages remain as they were before.
> feat: reduce redundant success toast messages

- packages/@sanity/vision/src/apiVersions.ts
Adds `v2025-02-19` to the API version dropdown list in Vision.
* `v2025-02-19` brings breaking changes and should be one of the API versions in Vision's dropdown for testing.
* This should be released as part of the changes that make `published` the default perspective.
> feat(vision): add API version 2025-02-19

- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx
Before
After
https://github.com/user-attachments/assets/e2015b06-6783-44e4-ab1d-03b543fb5948
Does it make sense, anything look odd?
Not needed
Improvements to document header when there are many versions of a document
> refactor(core): update so that there is an horizontal scroll on the title

- packages/sanity/src/core/config/resolveDefaultPlugins.ts
Make content releases opt-out by flipping the default `releases.enabled` to be `true` in the studio config default resolver.
This is part of the larger public release of the content releases feature and will show the releases button by default on the top of the studio.
n/a
n/a but lots of manual testing has been done and automated testing as part of the code that has already been merged behind this flag.
Lots of notes here that are already in draft.
> feat: make content releases opt out

- packages/sanity/src/core/form/inputs/common/fileTarget/utils/extractFiles.ts
This makes it possible to drag inline objects in the editor without getting a
"Can't upload any of these files here" error.
---
Drag and drop in PTE is still very lackluster:
1. Block objects like images can be dragged around, but this is purely
implemented by maintaining an internal drag state, and dragging these
objects doesn't use the `application/x-portable-text` MIME type yet.
2. Inline objects can be dragged more freely. They are stored using
`application/x-portable-text` and even support being dragged from one editor
to another.
`application/x-portable-text` is what PTE uses when serializing and
deserializing to and from the clipboard. And it's also the MIME type used for
drag and drop going forward. And soon block objects will be stored on this MIME
type as well.
Verify that you …
> fix(core): flag `application/x-portable-text` as portable text 

- packages/sanity/src/core/scheduledPublishing/constants.tsx
In the event that both content releases and scheduled publishing is enabled in the studio, we provide a warning banner. This PR updates the link to the documentation for getting help in resolving this.
Link isn't live yet, but confirmed with editorial that this is correct.
n/a
n/a
> fix: add correct link to content releases banner

- packages/sanity/src/core/studio/Studio.test.tsx
Fixes a flaky test, that fails on almost every [single PR](https://github.com/sanity-io/sanity/actions/runs/13504557073/job/37731007799).
The core issue were that the `hydrateRoot` instance creates a React render tree that continues to live on after the test is tore down.
And in some cases it would try to re-render the `<Studio />` test after teardown, at which point globals like `window` were no longer there and thus created this confusing error on builds:
```bash
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯
ReferenceError: window is not defined
This error originated in "src/core/studio/Studio.test.tsx" test file. …
```
> chore: fix flaky test on CI

- packages/sanity/src/core/search/groq2024/createSearchQuery.ts
- packages/sanity/src/core/search/weighted/createSearchQuery.ts
This fixes an issue that caused drafts (and versions) not to appear in reference search by explicitly 
- Does the fix make sense?
- Create a draft document (without publishing it)
- Go to a reference field that can reference its type and search for it.
Prior to this PR, the draft document would not appear in search results
After this PR the draft should appear and you should be able to create a reference to it
- Fixes an issue causing draft-only documents to not appear in reference search
> fix: use raw perspective by default for search

- .github/workflows/are-we-compiled-yet.yml
- .github/workflows/cli-test.yml
- .github/workflows/docReport.yml
- .github/workflows/e2e-ct.yml
- .github/workflows/e2e.yml
- .github/workflows/efps.yml
- .github/workflows/etl.yml
- .github/workflows/formatCheck.yml
- .github/workflows/lintPr.yml
- .github/workflows/test.yml
We have a lot of congestion and rebasing happening on PRs. Especially with renovatebot which auto rebases when a merge conflict is detected.
When this happens it's not necessary to wait for previous builds to complete, as we use GitHub required checks to control what PRs can merge anyway, and they only care about the checks on the latest commit on the branch.
Does it make sense? The way `group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}` works is that a matching name will be cancelled if a new build starts. Thus `group` should be unique to each workflow file (that's what `github.workflow` ensures).
It should have a stable name for the lifecycle of a PR, `github.head_ref` does that by using the branch name. `head_ref` is only available on PRs, so `${{ github.head_ref || …
> chore(ci): auto cancel workflows on PRs

- dev/test-studio/sanity.config.ts
Switching back to using the common search strategy for our day-to-day development Studio and instead enabling `groq2024` for the playground workspace.
n/a – internal
> chore(test-studio): move experimental search api to playground workspace

- packages/@sanity/cli/src/util/frameworkPort.ts
Update the default port assigned to Astro when setting CORS origin during the --template CLI initiation.
You could review that `4321` is the correct port.  [Astro Docs](https://docs.astro.build/en/reference/cli-reference/#--port-number)
To replicate this, you can try installing the Astro template with `npm create sanity@latest -- --template sanity-io/sanity-template-astro-clean` and them viewing the manage console to see that `http://localhost:3000` was added as a CORS origin.
Im not totally sure.
> fix(cli): correct the default port for Astro app

- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/templates/core-app/src/App.tsx
- packages/@sanity/cli/templates/core-app/src/ExampleComponent.tsx
This updates the core app template to use the proper components for wrapping a core app. This is iterative, and likely not the final state of what this template looks like.
Does this seem all right as an initial intro to core apps for internal parties?
1. Run `pnpx sanity@3.75.1-canary.151+ccab07e8db init --template core-app`
2. Run `pnpm dev`
3. Note no crashes and the usage of `SanityProvider` in the repository
None, internal.
> fix(cli): update core app template

- .github/workflows/e2e-ct.yml
- .github/workflows/e2e.yml
- .github/workflows/test.yml
We'll need to find alternative methods to solve congestion. Like better use of `concurrency` with `cancel-in-progress: true`, better caching like turborepo and such.
> chore(ci): end custom runners experiment

- packages/sanity/src/core/studio/components/navbar/free-trial/FreeTrialProvider.tsx
- packages/sanity/src/core/tasks/context/navigation/TasksNavigationProvider.tsx
The way the `router.state._searchParams` is parsed and handed to `useEffect` are leading to `useEffect` over-firing.
In the case of `FreeTrialProvider`, it's causing it to perform a network call that's only supposed to happen on mount, on every search param change. In Presentation Tool this means that every time you toggle the viewport size it performs a fetch:
https://github.com/user-attachments/assets/a19e5077-48b2-415d-9343-a9713202230a
The reason this happens is the underlying `useEffect` is reacting to _any_ change to `router.state._searchParams`. The fix is to extract the search params the `useEffect` is interested in, so it only reacts to those params changing ✨ 
Are there enough context in the comments to explain the pattern used, that isn't resulting in over-fetching?
The repro …
> fix: prevent over-fetching in free trial provider

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
The `MarkdownPlugin` now also handles the conversion of "\`" pairs as well as
the conversion of "~~" pairs. All you need to do is tell it what decorator to
use for the conversion. In our case, we go with the default decorator names so
anyone who has these configured get the shortcuts.
Do the shortcuts work as expected?
The Portable Text Editor has internal tests for these behaviors.
The Portable Text Input now includes Markdown shortcuts for decorators named `code` and `strike-through`
> feat(core): add default `code` and `strike-through` markdown shortcuts to PTE

- packages/sanity/src/_internal/cli/commands/migration/constants.ts
- packages/sanity/src/_internal/cli/commands/migration/runMigrationCommand.ts
- packages/sanity/src/_internal/cli/commands/migration/utils/ensureApiVersionFormat.ts
- packages/sanity/src/_internal/cli/commands/migration/utils/esureVersionPrefix.ts
Allow Sanity Migrate to run on any api version by reading flag `--api-version`. This is very beneficial when testing migrations against content releases, which has many of its api's still under vX
Does helper text make sense?
I think you can set some sort of debug env to see the requests being sent
@sanity/migrate now takes an optional `--api-version` flag
> feat(migrate): add support for `--api-version` flag

- packages/sanity/src/presentation/preview/Preview.tsx
- packages/sanity/src/presentation/preview/PreviewHeader.tsx
The Preview header in Presentation is constantly unmounting and remounting. Besides being inefficient and contributing to React having to perform more work (as mounting involves creating DOM elements and other DOM operations), it also affects the user experience.
Note how in this video that if you focus a field in a document, and then attempt to click a button in the toolbar, it's "ignored", and you have to "double click":
https://github.com/user-attachments/assets/1c196151-1cde-467d-9558-b72f1073eae6
The TL;DR of how the preview header renders is:
1. `<Preview>` in `Preview.tsx` renders the header and the iframe. The header is output as `<PreviewHeader />`
2. `PreviewHeader` is a component returned by `usePresentationPreviewHeader(props)`.
3. `usePresentationPreviewHeader` lives in …
> fix(presentation): don't remount header when props change

- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
| Before    | After |
| <img width="439" alt="image" src="https://github.com/user-attachments/assets/6ad072ca-0b3e-433d-8581-172e406030b5" />  | <img width="196" alt="image" src="https://github.com/user-attachments/assets/902b7ddf-8a0b-4f24-8db5-c04b5a22a450" />  |
The change
N/A
Update visual bug when a release was locked in the document header chip
> fix(structure): fix issue with locked icon

- packages/sanity/src/core/validation/util/deepEqualsIgnoreKey.ts
- packages/sanity/src/core/validation/validators/arrayValidator.ts
- packages/sanity/src/core/validation/validators/genericValidator.ts
In the codebase we have uses of `deepEquals from "react-fast-compare"` and `deepEquals from "util/deepEquals"` , this could lead to hard to reason about errors or bugs given they both seem to do the same.
Our internal `deepEquals` ignore the value of `_key` (see [here](https://github.com/sanity-io/sanity/pull/8790/files#diff-1f840ffb1fed669b0a7bebf617ab1da2115a75605c05a8b0d7cfea13bdd9ca73R53) and [here](https://github.com/sanity-io/sanity/pull/8790/files#diff-1f840ffb1fed669b0a7bebf617ab1da2115a75605c05a8b0d7cfea13bdd9ca73R64)) 
This PR renames it to clearly express that this deepEquals function ignores the value of `_key`
> fix(core): rename internal `deepEquals` to `deepEqualsIgnoreKey`

- packages/sanity/src/core/preview/utils/getPreviewValueWithFallback.tsx
Fixes an oversight with #8655 that picked the "original" preview value over the "snapshot" (which has the current perspective applied)
This should be the other way around: we always want to preview in current perspective, but in case we cant (e.g. the document we're trying to preview exists only outside of the current perspective, we want to fallback to the original)
Notice "this is the published" before vs "this is the draft" after – these are draft and published of the same document.
Looks ok?
n/a
> fix(preview): prefer snapshot over original when previewing

- packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx
Prior to this PR, document lists included all documents across all versions. This was never the original intention, so this reverts that behavior by applying the current perspective when fetching for document lists.
Ensure that
- Using the default (drafts) perspective doesn't include documents that only exists in a release
- Selecting the "published" perspective doesn't include documents that exists only as drafts (or documents that only exists in a release)
- Selecting a release perspective doesn't include documents that exists only outside of the selected release stack
- Excluding a release from the global release dropdown correctly excludes documents that only exists in this release
Not currently covered by tests afaik, but the review steps above should be a great starting point for …
> fix(structure): exclude documents outside of selected perspective from document lists

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/detail/ReleaseDetail.tsx
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
We were doing one request to the history endpoint per document in the archived releases view, this doesn't scale well and in releases with 40 documents the archived view doesn't load because of rate limiting.
This PR removes the 1 request per doc solution and implements a batching strategy, fetching 10 documents per time and waiting for the previous response to end before getting the next one.
So instead of doing N requests (1 per document)
```
https://ppsg7ml5.api.sanity.io/v2025-02-19/data/history/test/documents/doc1
https://ppsg7ml5.api.sanity.io/v2025-02-19/data/history/test/documents/doc2
https://ppsg7ml5.api.sanity.io/v2025-02-19/data/history/test/documents/doc3
```
it does the following request:
```
https://ppsg7ml5.api.sanity.io/v2025-02-19/data/history/test/documents/doc1,doc2,doc …
```
> fix(core): batch requests for archived releases view

- packages/sanity/package.json
`mocks` and `fixtures` were being included in the generated tarball for `sanity`, [see here](https://www.npmjs.com/package/sanity?activeTab=code) where you can find these dirs.
This change excludes them.
Tested by `pnpm build` and `pnpm pack` within `packages/sanity` and verifying that these dirs are no longer included
N/A
> chore: exclude mocks and fixtures from bundle

- packages/sanity/src/_internal/cli/actions/app/__tests__/undeployAction.test.ts
- packages/sanity/src/_internal/cli/actions/app/undeployAction.ts
- packages/sanity/src/_internal/cli/actions/deploy/__tests__/helpers.test.ts
- packages/sanity/src/_internal/cli/actions/deploy/helpers.ts
- packages/sanity/src/_internal/cli/commands/app/undeployCommand.ts
- packages/sanity/src/_internal/cli/commands/index.ts
Adds a new CLI command `sanity app undeploy` that allows users to remove deployed Core applications from Sanity hosting. This complements the existing studio undeploy functionality by providing a way to manage Core application deployments.
- Implementation of the new `undeployCoreAppAction` function
- Error handling and user confirmation flow
- Integration with the existing deployment helpers
- Addition of the new command to the CLI command registry
- Test coverage for the new functionality
Added tests
N/A
> feat(cli): add app undeploy command

- packages/sanity/src/core/releases/tool/detail/ReleaseDetail.tsx
Fixes `motion() is deprecated. Use motion.create() instead.` warnings on `sanity dev` as well as in the test suite log output (CMD + F "motion()" [here](https://github.com/sanity-io/sanity/actions/runs/13590063088/job/37993996651))
Assigning you @pedrobonamin since you showed up on the `git blame` ❤ 
N/A
N/A
> fix: handle motion.create warning

- packages/sanity/src/_internal/cli/actions/app/devAction.ts
- packages/sanity/src/_internal/cli/actions/dev/devAction.ts
- packages/sanity/src/_internal/cli/commands/app/devCommand.ts
FIXES SDK-178
Introduces a dedicated development server for Sanity applications that runs on port 3334 by default, separate from the main Sanity development server which runs on port 3333. This separation allows developers to run both servers simultaneously without port conflicts.
- Verify the new `devAction.ts` implementation in the app directory
- Check that the default port configuration is set to 3334
- Ensure the command documentation reflects the correct default port
- Confirm the dev server initialization and error handling are properly implemented
The changes can be tested by:
1. Running the new app dev server using `sanity app dev`
2. Verifying it starts on port 3334 by default
3. Confirming that both the main Sanity dev server and app dev server can run concurrently
N/A
> chore(cli): run app dev command on different port

- packages/sanity/src/structure/components/paneItem/PaneItem.tsx
Fixes: SAPP-2455
If the `<PreloadPane>` gets a draft id instead of a published, it will throw an error.
`useEditState` should always use the `publishedId` this Pr updates the Preload to pass the published id.
and fix the following error
Fixes an issue in which in some cases the document list could crash when hovering over a document.
> fix(structure): preload should use published id

- packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.test.tsx
- packages/sanity/src/core/scheduledPublishing/tool/contexts/ScheduledPublishingEnabledProvider.tsx
- packages/sanity/src/core/scheduledPublishing/tool/contexts/useHasUsedScheduledPublishing.ts
This PR updates the `hasUsedScheduledPublishing` check to trigger only once by memoizing the observable that will do the request.
It also adds a check in the case that users have opted out from the feature, if they have opted out ` scheduledPublishing.enabled = false` we won't do a request to check if they have used it before or not, because it will be off by default anyways.
If they have explicitly opted in, we won't check this, because it will be true anyways.
Is the approach correct?
Open the studio, you should see only one request.
> fix(core): memoize scheduledPublishing calls, trigger only once

- packages/sanity/src/core/form/useDocumentForm.ts
- packages/sanity/src/core/perspective/PerspectiveProvider.tsx
- packages/sanity/src/core/perspective/getSelectedPerspective.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
In some cases the documents should have a read only state either because the release is locked or the document will be unpublished.
We are doing this check in the `<DocumentPaneProvider>` but this should be part of `useDocumentForm` so consumers don't need to care about this.
If a release is locked, editing the document will end in an error.
documents that will be unpublished are in theory possible to edit them, but it doesn't make sense from an user perspective and we are disabling this in the document pane.
does the changes makes sense?
> fix(core): add `isReleaseLocked` or `willBeUnpublished` to `useDocumentForm`

- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
Currently, when adding a document to a release there is no progress feedback in the UI. Usually it goes fast enough for you to notice, but in cases where it takes a little while, the button is kept active, and if you hit it again you'll eventually get an error. This fixes the issue by disabling the button as long as the action is in-flight, and also adds a sprinkle of error handling.
Does it work as expected?
- Try adding a document to a release – the add button should be disabled while adding. Can use network throttling in devtools to simulate latency/lossyness
n/a
> fix(structure): provide feedback as document is added to release

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/src/commands/init/initCommand.ts
- pnpm-lock.yaml
From now on we want all projects to be part of an organization. This means the CLI flow should be a little different - no "None" option for selecting an organization. Instead, we want people to choose one or create one.
This PR modifies the flow so that:
* If a user is not part of any organizations, prompt them to create one
* It shows organizations you are a member of but do not have the sufficient grants to (helps people understand why they can't choose it)
* Removes the "none" option, replaces it with a "Create new organization" option
There are a few code paths (through flags/unattended mode) that may still send a project creation request without an organization - that's fine - the API will assign those projects to the users' organization (if they have one), otherwise creates a new …
> fix(cli): require projects to be part of an organization

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/commands/functions/devFunctionsCommand.ts
- packages/@sanity/cli/src/commands/functions/functionsGroup.ts
- packages/@sanity/cli/src/commands/functions/logsFunctionsCommand.ts
- packages/@sanity/cli/src/commands/functions/testFunctionsCommand.ts
- packages/@sanity/cli/src/commands/index.ts
- pnpm-lock.yaml
This PR introduces a new CLI command group `functions`. The group includes three commands `dev`, `logs` and `test`.
Testing for these code changes lives in `@sanity/runtime-cli` where the non-trivial code lives.
Part of feature Sanity Functions
Start the Sanity Function emulator
```
Options
--port <port> Port to start emulator on
Examples
sanity functions dev
sanity functions dev --port 3333
```
Retrieve logs for a Sanity Function
```
Options
--id <id> The ID of the function to retrieve logs for
Examples
sanity functions logs --id abcd1234
```
Invoke a local Sanity Function
```
Options
--data <data> Data to send to the function
--file <file> Read data from file and send to the function
--path <path> Path to your Sanity Function code
--timeout <timeout> Execution timeout value in seconds …
```
> feat: add runtime functions cli group

- packages/sanity/src/_createContext/createGlobalScopedContext.ts
While working on some CLI improvements, I am seeing the context warnings being emitted when loading the studio configuration through a JSDOM-enriched environment, such as from `sanity schema extract` etc. This PR silences these as they are not actionable.
Do the new checks seem safe and logical? JSDOM user agent note here: https://github.com/jsdom/jsdom?tab=readme-ov-file#advanced-configuration
> It defaults to `Mozilla/5.0 (${process.platform || "unknown OS"}) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/${jsdomVersion}`.
None
> fix: silence context warnings in jsdom environments

- packages/sanity/src/_internal/cli/actions/deploy/__tests__/undeployAction.test.ts
- packages/sanity/src/_internal/cli/actions/deploy/undeployAction.ts
- packages/sanity/src/_internal/cli/commands/deploy/undeployCommand.ts
Adds a `--yes` (or `-y`) flag to the `undeploy` command, enabling unattended mode:
```sh
sanity undeploy --yes
```
This flag is particularly useful for CI/CD workflows, such as deploying a feature branch of a Sanity Studio and automatically undeploying it when the corresponding pull request is closed.
Updating documentation to include new flag. The help docs for the command have been updated with an example.
> feat(cli): add unattended mode flag to `sanity undeploy`

- packages/sanity/test/matchers/toMatchEmissions.ts
- packages/sanity/typings/vitest.d.ts
This branch moves the ambient type definitions for custom Vitest matchers to `packages/sanity/typings`, ensuring the types are available inside `packages/sanity`. Prior to this change, the `toMatchEmissions` matcher was available at runtime, but the type itself was not.
Does it seem reasonable to load the ambient type definitions in this way?
The `toMatchEmissions` matcher should be available in the assertion type when the subject is a function that returns an RxJS `OperatorFunction`.
> fix(sanity): ambient types for custom Vitest matchers

- .github/workflows/e2e-ui.yml
- .github/workflows/e2e.yml
- packages/sanity/playwright-ct.config.ts
- playwright.config.ts
1. Doubles shards for e2e tests, they currently run 40-ish tests each so now it's down to 20. Making it easier to find and isolate slow and flaky tests.
2. E2E suite is setup to use the `line` playwright reporter, like the e2e-ct suite. This makes it much easier to see what's wrong if something fails (unless you're able to decrypt `Running 44 tests using 2 workers, shard 2 of 2 °·············×··±°···°·····°·×··±·······°°°°·`). It also reports test results progressively, so you don't have to wait 15 mins to see which test failed.
3. e2e-ct suite is no longer opting out of parallelism, like the e2e suite. This should make them about twice as fast since our runners has 2 vCPU's.
> chore: speed up e2e tests

- packages/sanity/src/core/perspective/__mocks__/usePerspective.mock.ts
- packages/sanity/src/core/perspective/types.ts
- packages/sanity/src/core/perspective/usePerspective.ts
- packages/sanity/src/core/preview/useValuePreview.ts
- packages/sanity/src/core/releases/hooks/__tests__/utils.test.ts
- packages/sanity/src/core/releases/hooks/utils.ts
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/SearchProvider.tsx
- packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx
- packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx
- packages/sanity/src/structure/panes/documentList/__tests__/PaneContainer.test.tsx
The `usePerspective` hook exposes the `perspectiveStack` but that is only valid as the `perspective` to use with the client when you have a release selected.
If no releases are selected then the `perspectiveStack` returns an empty array, blocking us from using it as intended and making us do all over the place things like this:
```ts
const {perspectiveStack, selectedPerspective} = usePerspective()
const perspective = useMemo(
() =>
selectedPerspective === 'published'
? ['published'] // or "published" it returns the same result 
: selectedPerspective === 'drafts'
? ['drafts']  // or "dradts" it returns the same result 
: perspectiveStack,
[selectedPerspective, perspectiveStack],
)
client.fetch(query, {}, {perspective})
```
This PR updates the `perspectiveStack` to also return either …
> fix(core): update perspectiveStack, use it as the client perspective

- packages/sanity/src/core/releases/store/useOrgActiveReleaseCount.ts
- packages/sanity/src/core/releases/store/useReleaseLimits.ts
We had a couple of useClient() calls that didn't specify `apiVersion` causing a bit of warning-spam in the console.
After checking out this branch there should be no more warnings about useClient() calls not specifying version
- Removes a few console warnings
> fix(releases): specify apiVersion in useClient calls

- packages/sanity/src/core/form/useDocumentForm.ts
Fixes the title for the reconnection toast.
> fix(core): reconnection title was missing

- packages/sanity/src/core/releases/store/createReleaseMetadataAggregator.ts
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
Currently, if you add a document with a dot-path, it won't show up in the listing of documents in a release.
This happens because the query that listens for documents was using `_id in path("versions.${releaseId}.*")` which only matches documents with one immediate path element. This PR fixes the issue by rewriting the filter to add a trailing `**`, which matches ids recursively
- I think I caught all the relevant places, and did a round of manual testing.
This release has a version of the document with `_id=dot.path.author` in it:
- Before: https://test-studio.sanity.dev/test/releases/rvwDnxsPf?perspective=rvwDnxsPf
- After: https://test-studio-git-fix-releases-query.sanity.dev/test/releases/rvwDnxsPf?perspective=rvwDnxsPf
- Fixes an issue causing documents with nested dot-paths in them
> fix(sanity): use recursive wildcards for release document listings

- packages/sanity/src/structure/diffView/components/DiffViewPane.tsx
- packages/sanity/src/structure/panes/document/document-layout/pickDocumentLayoutComponent.ts
- packages/sanity/src/structure/panes/document/document-layout/useDocumentLayoutComponent.ts
`DiffViewPane` does not currently use the document layout middleware chain when it's rendered. This is problematic for plugins that rely on the `document.components.unstable_layout` option to inject context providers, such as `@sanity/assist`, which crashes inside `DiffViewPane` due to the absent context provider.
This branch wraps the `DiffViewPane`'s `FormBuilder` in the entire document layout middleware chain to solve the issue.
Note: I did consider adding the middleware chain to `FormBuilder` itself, but decided against this, because `FormBuilder` may be used in places where the document layout middleware chain is not desired. For example: when rendering the task form we likely do not wish to wrap it with components that were intended to influence the document editor layout.
We may …
> feat(sanity): use document layout middleware chain when rendering `DiffViewPane`

- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/renderingContext/coreUiRenderingContext.test.ts
- packages/sanity/src/core/store/renderingContext/coreUiRenderingContext.ts
- packages/sanity/src/core/store/renderingContext/createRenderingContextStore.test.ts
- packages/sanity/src/core/store/renderingContext/createRenderingContextStore.ts
- packages/sanity/src/core/store/renderingContext/defaultRenderingContext.test.ts
- packages/sanity/src/core/store/renderingContext/defaultRenderingContext.ts
- packages/sanity/src/core/store/renderingContext/listCapabilities.ts
- packages/sanity/src/core/store/renderingContext/types.ts
This branch adds a data store to the global resource cache for keeping track of the _Studio Rendering Context_. This store reflects _where Studio is being rendered_, and which capabilities are provided by that context and therefore can be omitted from Studio UI.
There are currently two rendering contexts:
1. `coreUi` - when Studio is rendered inside the Core UI app.
2. `default` - when Studio is rendered anywhere else.
Each context can additionally provide metadata. For example, `coreUi` provides environment metadata (such as `"development"` or `"production"`).
This branch introduces two "capabilities". When these capabilities are provided by the parent context, they should be omitted from Studio UI:
1. `globalUserMenu` - the global user menu, typically represented by the user's avatar at …
> feat(sanity): add Rendering Context Store

- packages/sanity/src/core/components/CapabilityGate.test.tsx
- packages/sanity/src/core/components/CapabilityGate.tsx
This branch adds a `CapabilityGate` component that can be used to conditionally render other components based on the current rendering context. For example, to prevent the global user menu from rendering when the rendering context provides this capability. You can see this exact scenario in #8591.
Any issues with the component implementation?
There are added unit tests, and you can see the changes in action in #8591.
> feat(sanity): add `CapabilityGate` component

- packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
- packages/sanity/src/core/studio/components/navbar/navDrawer/NavDrawer.tsx
This branch removes the global user menu when Studio is rendered inside Core UI. Core UI provides the global user menu capability, so Studio doesn't need to.
The removal of the global user menu.
This can be tested by running Studio locally and then accessing the local dev server using a Core UI preview deployment.
> feat(sanity): hide global user menu inside Core UI Rendering Context

- packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceMenuButton.tsx
This branch removes the workspace switcher when Studio is rendered inside Core UI. Core UI instead controls workspace selection.
Does the removal look okay?
Note: I'm aware the "Select workspace" tooltip is still present. I'd like to do a fast-follow that slightly changes the way we handle this. But I think this is _good enough for now_.
This can be tested by running Studio locally and then accessing the local dev server using a Core UI preview deployment.
> feat(sanity): hide workspace switcher inside Core UI rendering context

- packages/sanity/src/core/search/groq2024/createGroq2024Search.ts
- packages/sanity/src/core/search/groq2024/createSearchQuery.test.ts
- packages/sanity/src/core/search/groq2024/createSearchQuery.ts
- packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts
- packages/sanity/src/core/util/__tests__/draftUtils.test.ts
- packages/sanity/src/core/util/draftUtils.ts
- packages/sanity/src/structure/panes/documentList/helpers.ts
- packages/sanity/src/structure/panes/documentList/types.ts
The `groq2024` search strategy currently relies on Content Lake perspectives to collate documents. This means global search is unable to discover document versions outside of the selected perspective.
This branch changes back to the `raw` perspective and returns to client-side collation in order to make all document versions discoverable via global search, regardless of the selected perspective.
Global search: discoverability of versions outside the selected perspective.
Document lists: should be unchanged.
Updated unit tests and tested manually.
> fix(sanity): allow discovery of all document versions using groq2024 search

- packages/sanity/src/core/perspective/ReleasesToolLink.tsx
- packages/sanity/src/core/perspective/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/perspective/navbar/ReleasesNav.tsx
- packages/sanity/src/core/perspective/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/perspective/navbar/currentGlobalPerspectiveLabel.tsx
- packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
Updates the releases nav button,
main changes:
- Move perspective menu and tasks to the left
Order:  perspective | tasks | presence | help
- Remove x button inside perspective menu
- Remove dot inside perspective menu button
- Use padding 0.5 around buttons inside perspective menu
- Increase hitarea of buttons with the perspective menu
- Add user-select: none on the Published / Drafts text in the collapsed menu, so that it's not possible to click or select this text.
Extra: updates width animation to scale from the previous width and not from 0, making it smoother.
https://github.com/user-attachments/assets/ac00c8de-da70-49a7-97cd-b524537a6bd9
Manually tested everything keeps working.
Existing tests are updated.
Updates the releases navigation button UI, …
> chore(core): update perspective menu

- packages/sanity/src/core/create/components/CreateLinkedActions.tsx
- packages/sanity/src/core/create/components/StartInCreateBanner.tsx
- packages/sanity/src/structure/components/pane/PaneFooter.styles.tsx
- packages/sanity/src/structure/components/pane/PaneHeader.styles.tsx
- packages/sanity/src/structure/components/pane/PaneHeader.tsx
- packages/sanity/src/structure/panes/document/document-layout/DocumentLayout.tsx
- packages/sanity/src/structure/panes/document/document-layout/DocumentLayoutFooter.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/Banner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/CreateLinkedBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/DraftLiveEditBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTabs.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelSubHeader.tsx
- packages/sanity/src/structure/panes/document/inspectors/changes/ChangesTabs.tsx
- packages/sanity/src/structure/panes/document/statusBar/ActionMenuButton.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBar.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusLine.tsx
This PR updates the document panel UI
TLDR; 
- Title and tabs are now in the same line, taking less vertical space.
- Banners are rounded and have padding surrounding them, creating a more compelling effect.
- Footer is also rounded to match the banners design and the footer border is removed
- The inspector panel takes full height, the width occupied by the title and the footer when the inspector is open is reduced.
- Footer Call To Action button size reduced.
| **Before** | **After** |
|<img width="871" alt="Screenshot 2025-02-13 at 09 15 57" src="https://github.com/user-attachments/assets/da4e2654-cfb8-4406-9b8a-f1c9e0802a69" />|<img width="875" alt="Screenshot 2025-02-13 at 09 17 07" src="https://github.com/user-attachments/assets/b2aa98b7-e51b-4e36-8bf7-71f3ab33b54 …
> feat(structure): document panel UI updates

- packages/sanity/src/_internal/cli/actions/app/__tests__/undeployAction.test.ts
- packages/sanity/src/_internal/cli/actions/app/undeployAction.ts
- packages/sanity/src/_internal/cli/actions/deploy/__tests__/undeployAction.test.ts
- packages/sanity/src/_internal/cli/actions/deploy/undeployAction.ts
- packages/sanity/src/_internal/cli/commands/deploy/undeployCommand.ts
Improves error messaging and handling for the `sanity undeploy` command, particularly for Core applications. The changes provide clearer feedback when an application ID is missing or invalid, and standardizes error presentation across both Core and regular Studio deployments.
- Error message updates in both Core and Studio undeploy flows
- The new application ID validation logic in the Core undeploy action
- The integration of Core app detection in the undeploy command
- The updated prompt messaging format and consistency
Added new test cases covering:
- Scenarios where no app ID is provided
- Invalid application ID handling
- Updated error message verification
N/A internal
> fix(cli): add undeploy command back for apps

- packages/sanity/src/core/preview/liveDocumentIdSet.ts
Small cleanup removes projection with listener call, as they are ignored anyway.
n/a
> fix(preview): pass filter only to liveDocumentIdSet listener

- packages/sanity/src/core/perspective/navbar/ReleasesList.tsx
This branch updates the release overlay visualisation to include the drafts perspective, because the drafts perspective overlays published documents.
| --- | --- |
| <img width="298" alt="Screenshot 2025-03-07 at 12 07 29" src="https://github.com/user-attachments/assets/9f6e93b7-4853-456f-9212-58b8806a1104" />  | <img width="298" alt="Screenshot 2025-03-07 at 12 07 13" src="https://github.com/user-attachments/assets/479594a2-e363-47eb-8c68-8b3f76b4610d" /> |
Any mistakes in the assumptions I've made in the code?
Open the menu 🙂.
> feat(sanity): include drafts perspective in overlay visualisation

- packages/sanity/src/core/releases/tool/detail/ReleaseDashboardDetails.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseName.tsx
This branch adds an accessible name to release "pin" and "unpin" buttons. It also makes the button an ARIA live region so that the updated accessible name is announced when the button is toggled.
https://github.com/user-attachments/assets/42764464-61c3-4b44-bb76-7828695ecc4e
I've made the ARIA live region _assertive_, meaning that it will interrupt other announcements. I made this decision because the previous value being read is irrelevant as soon as the button is toggled. Making the live region assertive means that the new value is announced as soon as it changes.
Does this seem resonable?
Keyboard navigation when using macOS VoiceOver with Safari and Chrome.
> feat(sanity): improve "pin release" button accessibility

- test/e2e/tests/inputs/reference.spec.ts
The reference tests are flaky.
Disable them for now.
We will come back to it in SAPP-2485
> chore(tests): disable flaky references e2e tests

- packages/@sanity/vision/src/codemirror/VisionCodeMirror.tsx
- packages/@sanity/vision/src/components/ParamsEditor.tsx
- packages/@sanity/vision/src/components/VisionGui.tsx
fixes: https://github.com/sanity-io/sanity/issues/8827
Linear issue: SAPP-2009
This PR does two different things:
By one side it reverts the change introduced in https://github.com/sanity-io/sanity/pull/8238 because it didn't fix the underlying issue and it introduced a new one (hitting enter after just finishing writing was not triggering the correct query).
Instead, it takes a new approach of transforming the component to an uncontrolled editor, it does that by setting only an initial value, any subsequent change that is needed, like for example when pasting a url to process the query and get the correct values it's done by the `resetEditorContent` function which is exposed by the imperative handle.
https://github.com/user-attachments/assets/9522acf9-eeae-48c5-aec9-9e1ae5e855d7
I have a …
> fix(vision): scroll jump - transform vision code mirror to uncontrolled

- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
This branch makes some small changes to improve the releases overview toolbar layout and make the buttons more consistent.
This is best illustrated with the flex layout highlighted.
The updated layout.
Tested the layout manually in web browser.
> feat(studio): refine releases overview toolbar layout

- dev/test-studio/schema/debug/arrayCapabilities.ts
- packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceItem.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBar.tsx
- playwright.config.ts
- test/e2e/tests/inputs/array-capabilities.spec.ts
| <img width="701" alt="Screenshot 2025-03-11 at 04 20 26" src="https://github.com/user-attachments/assets/c041a6d0-1007-43dc-9ec5-2523b0e4672b" /> | <img width="688" alt="Screenshot 2025-03-11 at 04 19 03" src="https://github.com/user-attachments/assets/d0a13bba-89b8-4dbe-8147-5d882c3d2cb9" /> | 
The same logic that is used across other arrays of items eg `/packages/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ItemRow.tsx`, has been added to the `menu` rendered in `ReferenceItem`, so that support for `options.disableActions` is brought to arrays of references.
There is a separate minor refactor that will be raised shortly which will consolidate all array item menus from a single hook that can be reused both here, in `ItemRow` and …
> fix(core): arrays of references support disableActions

- packages/sanity/package.json
- pnpm-lock.yaml
Adds (explicit) React 19 support  
Focus locking still works
No new tests. Dependency update.
None
> chore(sanity): upgrade react-focus-lock to ^2.13.6

- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentActions.tsx
The tooltips were wrongly showing all the time, even when the actions were enabled and the user had permissions
N/A
> fix: release document actions disabled tooltips only shown when relevant

- packages/sanity/src/presentation/document/PresentationDocumentHeader.tsx
- packages/sanity/src/presentation/plugin.tsx
- packages/sanity/src/presentation/types.ts
- packages/sanity/src/presentation/useDocumentLocations.ts
This PR adds to presentation resolvers two new options that are necessary for the resolvers to correctly resolve the queries when using releases.
`version`
`perspectiveStack``
The version is necessary to know if the document you are trying to resolve is a version document and which version it belongs to.
The stack is necessary to expose to users a way to query for the document, they can provide this value to the `client.perspective` 
Example of returned value:
```ts
{
id: "5ca15b90-6317-4ab0-a757-54a961671661",
perspectiveStack: ['rKM9a34iK', 'drafts'],
type: "author",
version: "rKM9a34iK"
}
```
Is this change correct? Is there any other place we need to update to expose this value?
include `perspectiveStack` and `version` in presentation resolvers
> feat(presentation): include perspectiveStack and version in resolvers

- packages/sanity/src/core/releases/components/ScheduleDatePicker.tsx
- packages/sanity/src/core/releases/components/dialog/CreateReleaseDialog.tsx
- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/components/dialog/TitleDescriptionForm.tsx
- packages/sanity/src/core/releases/store/types.ts
This branch implements release creation dialogue and release form refinements.
Note that this branch does not move the timezone control into the date picker, as that change would be quite a lot wider in scope.
https://github.com/user-attachments/assets/5cd33647-f0d5-464e-b73a-12ddf8ddd160
The release creation UI (dialogue and form).
Existing tests pass.
Refines release creation UI, making it easier to use across a wider range of viewport sizes.
> feat(sanity): refine release creation dialogue

- packages/sanity/src/core/studio/copyPaste/__test__/transferValue.test.ts
- packages/sanity/src/core/studio/copyPaste/transferValue.ts
Copy-pasting a document with a reference ended up crashing the studio with an error like:
```
Mutation failed: Document "drafts.05a476fe-4995-4e3e-aa8c-771dca935f43" references non-existent document "d7ad5b07-5e6b-4de3-91c0-ce4fff3ea1bd"
```
In examining further, we were sending an action like:
```
{
"actionType": "sanity.action.document.edit",
"draftId": "drafts.05a476fe-4995-4e3e-aa8c-771dca935f43",
"publishedId": "05a476fe-4995-4e3e-aa8c-771dca935f43",
"patch": {
"set": {
"author": {
"_type": "reference",
"_ref": "d7ad5b07-5e6b-4de3-91c0-ce4fff3ea1bd",
"_strengthenOnPublish": {
"type": "author"
}
}
}
}
}
```
to the Content Lake. Although the pasted object included a `_strengthenOnPublish` parameter, it did not include a `_weak` parameter. I tracked this down to the `transferValue` …
> fix(studio): handle document-level copy/paste reference mismatches

- packages/sanity/src/core/preview/utils/getPreviewValueWithFallback.tsx
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
- packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItem.tsx
- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItemPreview.tsx
- packages/sanity/src/core/tasks/components/form/fields/TargetField.tsx
- packages/sanity/src/presentation/editor/ContentEditor.tsx
- packages/sanity/src/structure/components/paneItem/PaneItemPreview.tsx
Fixes a couple of issues:
Took the opportunity to clean up and document the logic related to getting preview values and fallback
Also fixed a bug that leaked document.title in previews for cases where the document was missing.
Switching between release/draft/published should use the correct preview for search results (global search, reference search), document lists etc.
- Fixed an issue where list previews sometimes did not reflect the current release.
> refactor(preview): clean up preview with fallback logic

- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
After #8904 we ended up passing the fallback value to `prepareForPreview` which caused an error because react isn't valid as preview attributes. 
The document previews for archived releases should display the right values
n/a - fixes an earlier unreleased bug
> fix(preview): don't apply preview fallback for documents in archived release

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/components/dialog/DiscardVersionDialog.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/releaseActions.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleasePublishAllButton.tsx
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseScheduleButton.tsx
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseUnscheduleButton.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
This branch continues the work of refining toasts, focusing on Content Releases. Primarily, this means removing success toasts when it's apparent in the UI that the operation was successful.
Do all the removals make sense? The commits are atomic, so it's probably easiest to look over them to see the individual changes.
Tested in browser. Existing tests succeed.
> feat(sanity): refine release toasts

- packages/sanity/src/core/releases/store/__tests__/createReleaseMetadataAggregator.test.ts
- packages/sanity/src/core/releases/store/__tests__/useActiveReleases.test.ts
Some more tests to fill in gaps around the releases store and hooks
This is just tests
N/A
> test(releases): add unit tests for createReleaseMetadataAggregator and useActiveReleases hooks

- packages/sanity/src/core/releases/components/dialog/DiscardVersionDialog.tsx
- packages/sanity/src/core/releases/components/dialog/UnpublishVersionDialog.tsx
- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
- packages/sanity/src/core/releases/hooks/useVersionOperations.tsx
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
| <img width="446" alt="Screenshot 2025-03-13 at 11 43 27" src="https://github.com/user-attachments/assets/57e9ce64-3176-4880-ad6e-163f4f56b3bf" /> | <img width="467" alt="Screenshot 2025-03-13 at 11 42 21" src="https://github.com/user-attachments/assets/a8dc7a36-e706-4903-b521-63560de0653a" /> | 
Before: the error was caught in `useVersionOperations` and so callers would handle operation like it had resolved.
After: `useVersionOperations` delegates to the caller to show all success and error toast
* Does it make sense to move the toast showing to the caller and away from the operations store hook (this is how `useReleaseOperations`/`createReleaseOperationsStore` also works)?
Manually tested and verified to be working against failure and success …
> fix: version operations error toast

- packages/sanity/src/core/releases/store/__tests__/createReleaseOperationsStore.test.ts
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
Some of the actions used in `createReleaseOperationsStore` (which is used by `useReleaseOperations` and `useVersionOperations`) have drifted from the actual APIs. 
This PR adjusts the types and updates the uses of these actions according to [the version actions](https://www.sanity.io/docs/http-actions#8c43ee58aa51) and [the release actions](https://www.sanity.io/docs/http-actions#a102448a3a7a) from content lake.
Additionally, since `version.create` is now supported by content lake, `handleCreateVersion` uses the version action rather than creating a document directly with the version `_id`.
Tests updated for `createReleaseOperationsStore.test`
Manual testing trying to use most of the actions that have been impacted
Creating a new version of a document uses the [Sanity …
> fix(core): updating document version actions to match deviated API

- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
When viewing a document from an archived release users expect to click the published chip and get back to the published document, not only by clicking the button in the banner.
This PR updates the change perspective action to remove the history params when clicking the published if you are in a history version.
See video for details:
https://github.com/user-attachments/assets/982893dd-a1d0-4fd0-a14d-5f5d493891ff
fix: clicking published badge on version
> fix(structure): click on published chip should take you back to document

- packages/sanity/src/core/perspective/ReleasesToolLink.tsx
- packages/sanity/src/core/perspective/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/perspective/navbar/ReleasesNav.tsx
- packages/sanity/src/core/perspective/navbar/currentGlobalPerspectiveLabel.tsx
- packages/sanity/src/core/perspective/styles.ts
This PR updates the spacing for the releases navbar menu.
It refactors the initial implementation by applying a pseudo element to expand the clickable area of the elements, thank you @juice49 for the suggestion.
| <img width="187" alt="Screenshot 2025-03-14 at 09 47 29" src="https://github.com/user-attachments/assets/f7014c01-d583-4cc6-bf4d-dcb408505ca7" />| <img width="183" alt="Screenshot 2025-03-14 at 09 47 57" src="https://github.com/user-attachments/assets/4fdc76fb-1469-4a21-bcb1-7b42f6e69e7b" />| 
| <img width="131" alt="Screenshot 2025-03-14 at 09 47 20" src="https://github.com/user-attachments/assets/b9821f16-e863-4b2b-9862-9180e42597ba" />| <img width="141" alt="Screenshot 2025-03-14 at 09 47 48" …
> fix(core): update releases navbar menu spacing and click area

- packages/sanity/src/core/releases/components/documentHeader/contextMenu/VersionContextMenu.tsx
Hides "locked" scheduled releases in copy version to menu
|<img width="499" alt="Screenshot 2025-03-14 at 10 04 57" src="https://github.com/user-attachments/assets/07f7a32a-42f2-4987-98b0-fb9893caeae3" />|<img width="472" alt="Screenshot 2025-03-14 at 10 05 19" src="https://github.com/user-attachments/assets/975fe134-8a5c-4cce-9248-d03b424fc264" />| 
Not much
Hides "locked" scheduled releases in copy version to menu
> chore(core): hide scheduled releases in copy version to menu

- packages/sanity/src/core/releases/components/ReleaseAvatar.tsx
- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
Changes the borders for the version chips.
Removes the background for disabled chips and instead uses muted colors.
Last updates:
> fix(structure): some touches to version chips

- packages/sanity/src/core/releases/tool/components/ReleaseMenuButton/ReleaseMenuButton.tsx
Clears the release perspective when archiving or deleting a release if that release is the pinned one.
This is to avoid showing the **release archived** or **release deleted**  toast when archiving or deleting a release.
https://github.com/user-attachments/assets/c943f70b-2a59-49c4-bf9e-a05933af92a9
> fix(core): clear perspective when archiving or deleting a release

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentActions.tsx
Prevents crashing the releases view if a document type doesn't exist.
The `<DocumentActions>` is doing a check for document permissions, which throws an error if the schema type doesn't exist.
Visit this [page](https://test-studio-git-sapp-2443.sanity.dev/test/releases/rjRelfUYt)
The studio should not crash
> fix(core): releases screen should not crash if schema type is unknown

- .github/renovate.json
- dev/design-studio/package.json
- dev/embedded-studio/package.json
- dev/page-building-studio/package.json
- dev/starter-studio/package.json
- dev/strict-studio/package.json
- dev/studio-e2e-testing/package.json
- dev/test-create-integration-studio/package.json
- dev/test-studio/package.json
- examples/blog-studio/package.json
- examples/clean-studio/package.json
- examples/ecommerce-studio/package.json
- examples/movies-studio/package.json
- packages/@sanity/cli/test/__fixtures__/v3/package.json
- packages/@sanity/vision/package.json
- packages/sanity/fixtures/examples/prj-with-react-18/package.json
- packages/sanity/fixtures/examples/prj-with-react-19/package.json
- packages/sanity/package.json
- perf/studio/package.json
- pnpm-lock.yaml
Hopefully fixes #8927, although I couldn't verify that it does given that it didn't contain a reproduction.
Before the crash this warning is seen:
```bash
•Warning: Function components cannot be given refs. Attempts to access this ref will chunk-PWQMGZHF.js?v=84711372:521 fail. Did you mean to use React. forwardRef()?
Check the render method of 'PopChild'.
at Toast (http://localhost:3333/node modules/.sanity/vite/deps/chunk-5ZLLAU7C.js?v=84711372:23998:51)
```
We don't send refs as a prop in our codebase. But `styled-components` had an issue in React 19 where it accidentally sent `ref={null}` if no ref were provided, it was fixed in [v6.1.14](https://styled-components.com/releases#styled-components@6.1.14). This PR bumps the requirement from v6.1 to v6.1.15 to hopefully make package …
> fix: bump peer deps for `styled-components`

- packages/sanity/src/_internal/cli/commands/dataset/importDatasetCommand.ts
This change is the smallest possible band-aid for fixing dataset import containing version documents. It explicitly sets the importer to use API version `2025-02-19`.
Prior to API version `2025-02-19`, `"versions."` is a reserved document id path. The API therefore prevents the importer creating such documents, erroring with:
```
Invalid document version ID "versions.<id>": "versions" is a reserved prefix
```
I think we should take a closer look at how CLI API versions are managed. For example, if you arrive at [this code](https://github.com/sanity-io/sanity/blob/f70fe46de682ad952b836ef81c279126e6e32875/packages/@sanity/cli/src/cliClient.ts#L25), you may end up thinking _`2022-06-06` is probably used_. But if you make it to [this …
> fix(sanity): use minimum supported API version for dataset import

- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
Updates the padding and spacing for new releases and timezone button.
| <img width="381" alt="Screenshot 2025-03-14 at 10 21 57" src="https://github.com/user-attachments/assets/36886e68-d3b6-4439-beae-afe038847fce" /> | <img width="344" alt="Screenshot 2025-03-14 at 10 22 09" src="https://github.com/user-attachments/assets/5047272b-524a-432f-b584-7ef386461ed1" />| 
Does it looks good?
> chore(core): reduce new releases and timezone buttons size

- packages/sanity/src/core/components/inputs/DateInputs/DateTimeInput.tsx
- packages/sanity/src/core/components/inputs/DateInputs/LazyTextInput.tsx
- packages/sanity/src/core/components/inputs/DateInputs/TimeInput.tsx
- packages/sanity/src/core/components/inputs/DateInputs/calendar/Calendar.tsx
- packages/sanity/src/core/components/inputs/DateInputs/calendar/YearInput.tsx
- packages/sanity/src/core/components/inputs/DateInputs/calendar/constants.ts
- packages/sanity/src/core/components/inputs/DateInputs/calendar/types.ts
- packages/sanity/src/core/form/inputs/DateInputs/__tests__/CommonDateTimeInput.test.tsx
- packages/sanity/src/core/form/inputs/DateInputs/utils.ts
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/tool/detail/ReleaseTypePicker.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseTypePicker.test.tsx
- packages/sanity/src/core/scheduledPublishing/components/dateInputs/base/DateTimeInput.tsx
- packages/sanity/src/core/scheduledPublishing/components/dateInputs/base/calendar/YearInput.tsx
This branch switches from an hour and a minute `select` input to a single browser-native `time` input. This provides a better user interface for selecting times.
This branch includes a little work to make the input consistent with Sanity UI, but we may want to do some more work on this in the future. Perhaps Sanity UI's `TextInput` itself should be modified to better handle `type="time"`.
| --- | --- |
| <img width="425" alt="Screenshot 2025-03-14 at 09 44 43" src="https://github.com/user-attachments/assets/4bb87470-263c-4e61-b2de-e873db11aa98" /> | <img width="425" alt="Screenshot 2025-03-14 at 09 44 11" src="https://github.com/user-attachments/assets/034075e2-48d1-4fdb-af9a-98d8ea8fa1e8" /> |
The time selector.
Tested in various browsers (Safari Desktop, Firefox …
> feat(sanity): use time input in calendar

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/tool/components/ReleaseDocumentPreview.tsx
- packages/sanity/src/core/releases/tool/components/__tests__/ReleaseDocumentPreview.test.tsx
- packages/sanity/src/core/store/events/useEventsStore.ts
- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/documentPanel/banners/ArchivedReleaseDocumentBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/timeline/events/PublishedEventMenu.tsx
This PR updates how the links on published and archived releases work:
**Published releases**
Now when clicking on a document as part of a published release, instead of opening the document in the detailed view for that release it will open the published view with the history having selected that release:
https://github.com/user-attachments/assets/0132e4ff-46e6-4240-8316-c2fc1909b607
**Archived releases**
Clicking a document as part of releases that are archived we cannot show the document from the published view, we instead open the document "faking" that the release exists, and it will show the badge in the document for that release, but the badge will be disabled.
https://github.com/user-attachments/assets/3d640659-dc7a-41fe-a6fe-f923ab6ce011
This PR also fixes an issue with the open …
> fix(structure): update archived and published docs in release links

- packages/sanity/src/core/validation/validators/slugValidator.ts
- packages/sanity/test/validation/infer.test.ts
Fixes: https://github.com/sanity-io/sanity/issues/8724
With releases feature a bug was introduced in how the slugs are validated, allowing for repeated slugs across documents.
This PR fixes this by updating the query used to validate this making use of the [versionOf](https://www.sanity.io/docs/content-releases-cheat-sheet#d774f2dfc40f) function
Existing tests are updated.
Manual tests:
Created some documents with slug validations to verify:
- **San francisco** is published, has a repeated slug in a draft document, it should error.
- [Next](https://test-studio.sanity.dev/test/structure/input-standard;slugsTest;63be9484-35c6-40fa-8ee5-874c5c80ff8b)  No error shown, this is incorrect ❌ 
- [Branch](https://test-studio-git-fix-slug-validation.sanity.dev/test/structure/ …
> fix(core): slugs validation

- packages/sanity/src/core/studio/components/navbar/workspace/WorkspaceAuth/Layout.tsx
- Fixing a long standing issue of our Logo being used wrong on the auth screen when theme is "dark"
- Removed unused hook import
https://github.com/user-attachments/assets/902ccdac-71b2-487a-aa54-65235ffd944f
Visit a studio and try flipping your system scheme. The logo should be red on light mode, white on dark mode.
N/A
> fix(studio): use correct logo in dark mode

- packages/sanity/src/core/store/_legacy/document/hooks/__tests__/useDocumentType.test.tsx
- packages/sanity/src/core/store/_legacy/document/resolveTypeForDocument.ts
- packages/sanity/src/structure/structureBuilder/util/resolveTypeForDocument.ts
Fixes https://github.com/sanity-io/sanity/issues/8761
This PR fixes an issue with `resolveTypeForDocument` if the document only exists as a version document the return value of this getters will be undefined, it won't find the document so the studio will crash.
As seen here https://test-studio.sanity.dev/test/structure/custom;anythingWithATitle;5e5cb18e-0559-4319-95bd-3fb225fcb1a6?perspective=rlaZGnKM3
This PR, as suggested by @mariusGundersen updates the two `resolveTypeForDocument` functions we have to use the `versionOf` groq function.
Now, if you visit  https://test-studio-git-sgh-272.sanity.dev/test/structure/custom;anythingWithATitle;5e5cb18e-0559-4319-95bd-3fb225fcb1a6?perspective=rlaZGnKM3 it will pass
Are this changes correct?
How could we identify all the other places this type …
> fix(core): update `resolveTypeForDocument` to work with version docs

- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/_legacy/document/__telemetry__/listenerLatency.telemetry.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/checkoutPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/consistencyStatus.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/documentEvents.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/editOperations.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/editState.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/memoizedPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/operationArgs.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/operationEvents.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/remoteSnapshots.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/snapshotPair.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/validation.ts
- packages/sanity/src/core/store/_legacy/document/document-store.ts
- packages/sanity/src/core/store/_legacy/document/getPairListener.ts
- packages/sanity/src/core/store/_legacy/grants/documentPairPermissions.ts
We want to track e2e listener latency, this reports a telemetry event every time we detect >1s latency from after an edit action request has completed until we receive an event with a corresponding transaction id back from the listener.
I've tried to implement this as cleanly as possible to make it easy to delete the code path for tracking latency at some point in the future. The implementation follows the same pattern as the "document desynced" event in the document store takes a callback that will be called with latency, shard identifier and transaction id.
To see that the the Studio sends the event, start with `SANITY_STUDIO_DEBUG_TELEMETRY=true pnpm dev` which will log the telemetry events to the console.
This, combined with network throttling should likely cause some "High Listener …
> feat(studio): detect and report high listener roundtrip latency

- packages/@sanity/vision/src/components/VisionGui.tsx
- test/e2e/tests/vision/utils.ts
- test/e2e/tests/vision/vision.spec.ts
Adds e2e tests for vision.
This branch https://github.com/sanity-io/sanity/pull/8879 is changing vision to a functional component.
So having some e2e tests for the basics functionality before merging the refactor is a nice thing to do and get some extra security.
> chore(tests): add vision e2e tests

- test/e2e/tests/pte/ImageArrayDrag.spec.ts
The PTE image array test [tries to use a file ](https://github.com/sanity-io/sanity/blob/next/test/e2e/tests/pte/ImageArrayDrag.spec.ts#L30)that is added by another [test](https://github.com/sanity-io/sanity/blob/next/test/e2e/tests/inputs/array.spec.ts#L9), and it always fails on the first pass. 
With this changes, the test is responsible for adding the file, so it can run in isolation, without reusing files added by other tests, which could exist or not at the time this test runs.
> fix(test): updates flaky imageArrayDraft pte test

- packages/sanity/src/_internal/cli/actions/app/devAction.ts
- packages/sanity/src/_internal/cli/actions/dev/devAction.ts
Fixes a regression in 3.80.0 where the host/port CLI flags would get default values if not provided, but would be treated as explicitly set. The result is that they took precedent over both env vars and CLI config values, which they should do _if explicitly passed_, but not if they are the fallback values.
- Using `http.port`/`http.host` in `sanity.cli.ts` still works.
Would be ideal to get a test in here, but hotfixing for now
- Fixes a regression in 3.80.0 causing http host/port configured in environment variables/CLI configuration not to be respected by the `dev` command
> fix(cli): respect cli config for http host/port

- dev/studio-e2e-testing/sanity.config.ts
- packages/sanity/src/presentation/PresentationTool.tsx
- test/e2e/tests/presentation/presentation.spec.ts
- test/e2e/tests/presentation/utils.ts
After merging #8299 the Presentation [test workspace](https://test-studio-jw4ozwi1o.sanity.dev/presentation/presentation) started crashing. [The build just prior works fine.](https://test-studio-5h0wzd5p4.sanity.dev/presentation/presentation)
Turns out the root cause is `@sanity/assist`, fixed here: https://github.com/sanity-io/assist/pull/64
To avoid breaking the test workspace in the future I'm adding a very simple E2E test. I'll be expanding the test suite over time, this is just to catch simple crash cases like this.
This PR should have a failing test until #8983 is merged, which upgrades `@sanity/assist` with the required fix.
Does it make sense? I followed the same pattern as the new Vision Tool tests ✨ 
If it passes it works (after #8983, before that it should fail consistently). …
> chore: add simple e2e presentation test

- packages/sanity/src/core/studio/components/navbar/new-document/NewDocumentListOption.tsx
This Pr adds the `version` to the intent link generated when the user clicks to create a new document from the Studio Navbar **New document** button.
Now, if you have a release pinned, that release will follow you in the creation of the document.
We do this by assigning the `version` parameter to the link, in the same way as in **[PaneHeaderCreateButton](https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/structure/components/paneHeaderActions/PaneHeaderCreateButton.tsx#L43)**
https://github.com/user-attachments/assets/25f7c10d-48f0-4d53-8330-8a965151cc53
Pin a release, click on **new document**, the document should be added as part of the release.
If the user has a release pinned, when creating a new document from the studio navbar, the document will be created as part of …
> feat(core): add version to documents when creating with a release pinned

- packages/sanity/src/presentation/types.ts
The `previewUrl` option is actually required, but the `presentationTool` typings mark it as optional.
The `previewUrl` option is now marked as required in the `presentationTool` typings, matching the fact that it's required at runtime.
> fix(presentation): previewUrl is required

- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
| ![noReleaseBEFORE](https://github.com/user-attachments/assets/fddddeef-db89-44c2-b6ff-c517fc22e9d9) | ![noReleasesNEW](https://github.com/user-attachments/assets/76e9c556-a394-4c42-9df7-90e271999709) | 
Fixes issue in Releases Tool so that creating first release shows the create release dialog
> fix: no releases screen shows the create release dialog

- package.json
- pnpm-lock.yaml
While adding tests for #8900 I ran into a lot of issues with snapshots not being generated.
It can be reproduced on `next` with:
```bash
cd packages/sanity
pnpm vitest run
Error: The snapshot state for '/packages/sanity/test/validation/strings.test.ts' is not found. Did you call 'SnapshotClient.setup()'?
```
This lead me down quite the rabbit hole 😅 
It turns out the problem is due to duplicate instances of `vitest` in our monorepo:
https://github.com/sanity-io/sanity/blob/d8217b119024512573d990feeeb42ffdfb6308a9/pnpm-lock.yaml#L23755-L23873
There should only be 1 instance, not 3. The reason for these are differences in `jsdom` and `@types/node` versions. 2 instances of `vite` is also a factor: https://github.com/sanity-io/sanity/blob/d8217b119024512573d990feeeb42ffdfb6308a9/pnpm-lock.yaml …
> chore: fix vitest snapshot client error

- packages/sanity/src/core/studio/components/navbar/search/components/searchResults/item/SearchResultItem.tsx
Use `publishedId` for search intent links, in some cases, using a draft id could lead to not finding the document.
fixes an issue in where sometimes navigating to a draft document from the search dialog was not working
> fix(core): use publishedId for search intent links

- dev/test-studio/preview/FieldGroups.tsx
- dev/test-studio/preview/SimpleBlockPortableText.tsx
- dev/test-studio/preview/loader.tsx
- dev/test-studio/sanity.config.ts
Just adds the Presentation Tool to the regular workspace so it's a bit easier to work with and expand the complexity of the integration tests.
Makes sense?
Click around on http://localhost:3333/test/presentation and it should work like it did on http://localhost:3333/presentation/presentation
N/A
> chore: add presentation to regular workspace

- packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/utils/fetchFeatureToggle.ts
- packages/sanity/src/core/store/_legacy/grants/__tests__/createGrantsStore.test.ts
- packages/sanity/src/core/store/_legacy/grants/grantsStore.ts
- packages/sanity/src/core/store/_legacy/user/__tests__/userStore.test.ts
- packages/sanity/src/core/store/_legacy/user/userStore.ts
- packages/sanity/src/core/store/key-value/storage/serverStorage.ts
- packages/sanity/src/core/studio/addonDataset/AddonDatasetProvider.tsx
- packages/sanity/test/mocks/mockSanityClient.ts
- test/e2e/tests/desk/documentTypeListContextMenu.spec.ts
- test/e2e/tests/navbar/search.spec.ts
Two changes:
1. Only provide `withCredentials: true` to client constructor if we are not using a token. If we have a token, we don't _also_ want to send a cookie, as this is both unnecessary (it's likely not there, given we are using a token), and might include irrelevant cookies that were mistakenly attached to the `.sanity.io` domain. 
2. Providing `withCredentials: true` to the client's `.request()` _shouldn't_ be necessary unless the base client for the source does _not_ do so. While it traditionally hasn't been a problem, we want to discourage this pattern as it is confusing: what happens if both an auth cookie and an `authorization` header is provided? While the answer in our case is that the `authorization` header wins, this is not necessarily obvious, and can make things harder to …
> fix(core): drop explicit `withCredentials` on requests

- packages/@sanity/cli/src/actions/init-project/bootstrapLocalTemplate.ts
This PR fixes an issue with the app template initialization process. Currently, when using the app template, the CLI doesn't ask for a package name, resulting in potentially invalid package names in the generated `package.json` file.
The change adds logic to derive a valid package name from the output path when using an app template. It:
- Uses the last part of the output path as the base for the package name
- Removes diacritical marks using lodash's `deburr`
- Converts to lowercase
- Replaces spaces with hyphens
- Removes any characters that aren't lowercase letters, numbers, or hyphens
- The new logic for generating package names for app templates
- Verify that the generated package names follow npm naming conventions
- Check that the original behavior for non-app templates remains …
> fix(cli): use outpath as package name for apps

- packages/sanity/src/core/perspective/navbar/ReleasesNav.tsx
- packages/sanity/src/core/releases/hooks/useReleasesToolAvailable.ts
- packages/sanity/src/core/releases/plugin/ReleasesStudioLayout.tsx
- packages/sanity/src/core/releases/util/releasesToolAvailable.ts
- packages/sanity/src/core/scheduledPublishing/tool/Tool.tsx
There are various parts of the codebase that rely on `releases.enabled` from the workspace configuration to determine whether releases—and the releases tool—are available. This check fails when `releases.enabled` is `true`, but the releases tool is later removed (e.g. in the workspace tool filter).
In this scenario, Studio crashes because `ReleasesNav` attempts to generate a link to the nonexistent releases tool.
This branch fixes the problem by instead basing the availability of releases on the presence of the releases tool in the workspace.
The parts of the UI that rely on this check correctly respond to the presence of the releases tool.
Tested manually by adding the following `tool` filter to `defaultWorkspace` in Test Studio:
```ts
{
tools: (prev) => prev.filter((tool) => tool.name …
```
> fix(sanity): treat releases as inactive if releases tool not present

- packages/sanity/src/core/scheduledPublishing/plugin/documentActions/schedule/index.ts
- packages/sanity/src/core/scheduledPublishing/plugin/index.ts
- packages/sanity/src/structure/documentActions/DiscardChangesAction.tsx
Currently we don't have tests for this
Hide "Discard Changes" and "Schedule" actions from the document actions when the displayed document is the published
> fix(core): hide discard changes action when published

- dev/test-studio/sanity.config.ts
- dev/test-studio/schema/standard/portableText/simpleBlock.tsx
- packages/sanity/src/presentation/editor/usePreviewState.ts
- packages/sanity/src/presentation/useMainDocument.ts
Fixes https://github.com/sanity-io/sanity/issues/8986
This PR adds the `perspectiveStack` to the `useMainDocument` get function, allowing presentation to get the correct document when using a perspective.
If not, if the document doesn't exist as a draft it won't be shown as the main document.
It also fixes an issue with the preview for the main document shown in the presentation list to also respect the perspective.
See video for example:
https://github.com/user-attachments/assets/8e858b9c-2ecf-4e84-9904-2ab6934f7bd4
Open our presentation studio, a main document should load.
If you add a main document to another release, then it should be respected when visiting the page.
Fixes an issue in where main documents won't be accurately displayed if they only exist as …
> fix(presentation): use `perspectiveStack` when resolving main document

- packages/@sanity/vision/package.json
- pnpm-lock.yaml
Fixes https://github.com/sanity-io/sanity/issues/8917
We are declaring in the vision package to use `^4.19.9` and that is resolving to the version `4.23.8` which exports the EditorSelection, but version `4.19.9` doesn't export it , this is breaking some studios on build.
fixes build issue for `EditorSelection` not found
> fix(vision): update code-mirror dependency, fix EditorSelection error

- packages/sanity/src/core/perspective/useExcludedPerspective.tsx
- packages/sanity/src/core/perspective/useSetPerspective.tsx
- packages/sanity/src/core/releases/components/dialog/CreateReleaseDialog.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/router/RouteScope.tsx
- packages/sanity/src/router/RouterProvider.tsx
- packages/sanity/src/router/__test__/RouterProvider.test.tsx
- packages/sanity/src/router/__test__/RouterScope.test.tsx
- packages/sanity/src/router/types.ts
A PR of 2 halves: 1 simple, 1 more involved:
Simple:
For pinning the new release when created from the perspective menu, or from the 'copy to new release' flow, it's possible to just `setPerspective` to assign the `perspective` sticky param. This is because we don't navigate elsewhere when a release is created in these flows.
More:
In the other flow where a release can be created - from 'create release' CTA in releases overview, we already navigate to the release detail page after creation.
This causes some issues - calling `router.navigateStickyParams` (which is used by `setPerspective`), followed immediately by `router.navigate` to navigate to the release detail, causes a race, where `navigate` knows nothing about the perspective `stickyParam`, so the end result is that the release is …
> fix: creating new release immediately pins as perspective

- packages/sanity/src/router/index.ts
- packages/sanity/src/router/types.ts
After merging https://github.com/sanity-io/sanity/pull/9006 a new exports snapshot test was added.
this PR https://github.com/sanity-io/sanity/pull/8620 is exporting a new function, given it didn't have the tests on that branch, it was not notified about the new test and the snapshot was not updated.
This PR updates the snapshot to include this new function
> fix(test): don't export `isNavigateOptions` 

- packages/sanity/src/core/tasks/plugin/TasksStudioActiveToolLayout.tsx
Withe the releases update, responsive wise it looks like the "triggering" for the hovering taskbar sidebar to becoming floating comes too late. With this update, instead of making it floating by the 900px breakpoint, it will make it by 1200px. 
This will impact all areas of the studio, instead of just the releases page, however, I think this is an acceptable thing given that the task sidebar should likely not take as important a real-estate as the "main" opened things in the studio
| Month    | Savings |
| <img width="998" alt="image" src="https://github.com/user-attachments/assets/64a04b6f-e99d-4626-a6d0-a490064d1c63" />  |  <img width="998" alt="image" src="https://github.com/user-attachments/assets/5809256c-b066-4dd4-a782-34623062019c" />   |
Is there a better …
> fix(core): increase the window interfac for when the sidebar for the task is hovering

- packages/sanity/src/core/components/documentStatusIndicator/DocumentStatusIndicator.tsx
Adds a new green dot that will show when a document is published 
Updates the published + draft view from only 1 orange dot to a green and orange dot.
Drafts will show always the orange dot.
Versions colors are updated to match the new colors introduced last week for releases.
Updates the status dots for the documents previews, showing a green color for the published, a orange for drafts and overlaying the green + orange when the document is both a published and a draft.
> fix(core): update document status indicator colors

- packages/sanity/src/router/RouterProvider.tsx
- packages/sanity/src/router/__test__/RouterProvider.test.tsx
Fixes a bug that was introduced in https://github.com/sanity-io/sanity/pull/8620 where non-sticky search params would be preserved across navigation events.
This was surfaced in the viewport toggle in Presentation:
| ![nonStickyBEFORE](https://github.com/user-attachments/assets/189fbcad-9896-4903-990d-4b0edf61669d) | ![nonStickyAFTER](https://github.com/user-attachments/assets/37e00cf0-a682-46da-8be7-aab676dcc589) | 
Added a new test case on `RouterProvider` to capture this exact scenario
N/A - covered in 8620
> fix: non sticky params are not preserved during navigation

- packages/sanity/src/core/releases/tool/components/Table/Table.tsx
- packages/sanity/src/core/releases/tool/components/Table/TableHeader.tsx
- packages/sanity/src/core/releases/tool/components/Table/TableProvider.tsx
- packages/sanity/src/core/releases/tool/components/Table/types.ts
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseName.tsx
* Default sorting on a hidden column - which sorts by either `_updatedAt` or `publishedAt` depending on which is available 
* When sorting by published, all archived releases are at the end of the list, when sorting by archived, all published releases are at the end of the list
| Scenario | Before | After |
|--------|--------|--------|
| Default sort | ![defaultSortOLD](https://github.com/user-attachments/assets/8f0fe13c-e816-4e08-bc05-c8b269e8c677) | ![defaultSortNEW](https://github.com/user-attachments/assets/154414e6-22ce-4ae5-8e5e-79e0aa26ee8b) |
| Published at sort | ![publishedSortOLD](https://github.com/user-attachments/assets/90696bd6-4340-4ad3-bd56-42c215d32715) | ![publishedSortNEW](https://github.com/user-attachments/assets/c41cf07f-c32d-4328-9d6a-039eda45d93e) |
| Archived at …
> fix: archived releases table has default sort and defined sort working

- packages/sanity/src/core/releases/plugin/documentActions/index.ts
In minified bundles `name` may be minified, since I believe this is the `name` of the component. It is safer to use `action`.
Testing with additional studios and verified it works
Fixing an issue where content releases would incorrectly hide the duplicate document action
> fix: releases used wrong key on duplicate action

- dev/test-studio/package.json
- packages/sanity/src/core/config/prepareConfig.tsx
- pnpm-lock.yaml
> fix: filters out @sanity/assist plugin if it is older than 3.2.2

- packages/sanity/playwright-ct.config.ts
- perf/efps/runTest.ts
- playwright.config.ts
Disabling the GPU and software rasterizer helps make test runs more consistent by reducing visual or timing issues that can sometimes cause flaky E2E tests. 
This should lead to fewer random failures, especially in CI.
The E2E tests still run
N/A
> test: Disabling hardware acceleration during e2es

- packages/sanity/src/core/components/documentStatusIndicator/DocumentStatusIndicator.tsx
- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/util/const.ts
- packages/sanity/src/core/releases/util/getReleaseTone.ts
For the releases we had multiple spread across sections that had to be updated when the colours were updated. Moved code to have a single source of truth based on consts 
Did I miss somewhere?
Tests should have been updated
N/A
> refactor: update colour consts

- packages/sanity/package.json
- packages/sanity/src/core/form/useDocumentForm.ts
- packages/sanity/src/core/store/_legacy/document/initialValue/initialValue.ts
- packages/sanity/src/core/store/_legacy/document/useInitialValue.ts
- packages/sanity/src/core/tasks/components/form/tasksFormBuilder/TasksFormBuilder.tsx
- packages/sanity/src/core/templates/resolve.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/tsconfig.settings.json
- pnpm-lock.yaml
- test/e2e/tests/comments/inline.spec.ts
When schemas have many initial value templates, or long initial value templates, the main thread may become blocked while these are resolved. When examining performance in a Studio affected by this issue, you will likely see the browser cumulatively spends a lot of time executing the `resolveInitialObjectValue` function.
This branch improves the situation by using [the Prioritized Task Scheduling API](https://developer.mozilla.org/en-US/docs/Web/API/Prioritized_Task_Scheduling_API) to break initial value template resolution into smaller tasks that the browser can coordinate without blocking the main thread.
Not only does this keep the UI responsive while initial value templates are being resolved, but it appears the browser is able to coordinate the work more efficiently. **Users who …
> feat(sanity): make initial value template resolution interruptible

- packages/sanity/src/core/studio/StudioProvider.tsx
- packages/sanity/src/core/studio/__telemetry__/performance.telemetry.ts
- packages/sanity/src/core/studio/telemetry/PerformanceTelemetry.ts
- packages/sanity/src/core/studio/telemetry/StudioTelemetryProvider.tsx
- packages/sanity/src/core/studio/telemetry/useMeasurePerformanceTelemetry.ts
Collects [INP](https://web.dev/articles/inp) (Interaction to Next Paint) telemetry from the field.
This adds a performance observer that samples INP at most every minute. In addition to the INP duration, we also log the interaction event target. Example payload:
```json
{
"target": "input#myNumberField.Input-sc-h62wco-4.evDwFo",
"attrs": {"testId":"number-input"},
"interaction": "keydown",
"duration": 160
}
```
- Does the event definition look sane?
- Is the sample rate of 1 minute acceptable?
n/a
> feat(telemetry): track INP performance from the field

- packages/sanity/playwright-ct/tests/formBuilder/utils/TestWrapper.tsx
- packages/sanity/src/presentation/editor/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/ArchivedReleaseDocumentBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/CreateLinkedBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/OpenReleaseToEditBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/__tests__/DeletedDocumentBanners.test.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
- packages/sanity/src/structure/panes/document/inspectors/changes/EventsSelector.tsx
- packages/sanity/src/structure/panes/document/timeline/events/PublishedEventMenu.tsx
- packages/sanity/src/structure/panes/documentList/__tests__/PaneContainer.test.tsx
- packages/sanity/src/structure/panes/documentList/sheetList/__tests__/DocumentSheetListPane.test.tsx
When running a build with my astro/vite application it logs a few warning messages
```sh
13:47:22 [WARN] [vite] Export "structureLocaleNamespace" of module "node_modules/.pnpm/sanity@3.81.0_@emotion+is-prop-valid@1.2.2_@types+node@22.13.13_@types+react@19.0.12_ji_b540238d86544ced2c46ad0688fd4a8f/node_modules/sanity/lib/_chunks-es/pane.mjs" was reexported through module "node_modules/.pnpm/sanity@3.81.0_@emotion+is-prop-valid@1.2.2_@types+node@22.13.13_@types+react@19.0.12_ji_b540238d86544ced2c46ad0688fd4a8f/node_modules/sanity/lib/structure.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to …
```
> fix: remove circular references

- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx
- test/e2e/tests/document-actions/unpublish.spec.ts
Sometimes there can be 2 'Published' elements available after unpublishing is run in `unpublish.spec` - this is because briefly the Publish document action button shows 'Published' as the document state is reconciled.
This PR places a `data-testid` around the document perspective list, and uses this to target the correct 'Published'
Repeat running of this particular test (locally and in CI) shows improved robustness
N/A
> test: improving robustness of unpublish.spec e2e

- packages/sanity/src/structure/panes/document/documentPanel/banners/AddToReleaseBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/ArchivedReleaseDocumentBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/ScheduledReleaseBanner.tsx
Updates the padding for the **Document in Scheduled release banner** and refactors the `AddToReleaseBanner` and `ArchivedReleaseDocumentBanner` to use the Banners default values instead of defining it's own spacing and padding.
[ScheduledReleaseBanner](https://test-studio-git-sapp-2496.sanity.dev/test/structure/book;555c9aec-9563-43a1-8368-fe622d828208?perspective=rlgC25MaP)
[AddDocumentToReleaseBanner](https://test-studio-git-sapp-2496.sanity.dev/test/structure/author;19648fe9-1b20-47a1-a235-2f746c1ea11f?perspective=rowtBLG0B)
[ArchivedReleaseBanner](https://test-studio-git-sapp-2496.sanity.dev/test/structure/book;5c80b890-badc-482b-a656-3adcc2ed75f7%2Crev%3D%2540lastEdited%2Cinspect%3Dsanity%252Fstructure%252Fhistory%2ChistoryEvent%3DuiACJ6LTu4zD9hQbAcQSpB%2ChistoryVersion%3DrKEX64Tz4%2C …
> fix(structure): update release banners

- packages/sanity/src/router/__test__/RouterScope.test.tsx
- packages/sanity/src/router/types.ts
in cases where `router.navigate({state: 'stateRouteValue'})` is called, this was wrongly matching on the type guard `isNavigateOptions` for thinking this was the newer `navigate` signature (where `state` and other options are provided together as a single parameter).
Updating the guard to verify that `state` must be an object (to match `type RouterState = Record<string, unknown> & {_searchParams?: SearchParam[]}`) resolves the issue by correctly identifying `{state: 'stateRouteValue'}` as being the older `navigate(state, options)` signature
Improvements to the type guard `isNavigateOptions`
Added multiple tests specifically for these scenarios
* Fixes issue where Scheduled Publishing would not be accessible from the Studio tools bar
* [DEV] Fixes a regression in `router.navigate` where a …
> fix: resolving issue where string state is passed as a route parameter to router.navigate

- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/shared/MediaLibrarySource.tsx
We have a new endpoint available under the project API host to fetch the projects media libraries. 
This will use the same auth and CORS settings as with everything else in the studio.
Also we get rid of one hop to fetch the organization id.
That it works.
Can be tested in the test-studio by selecting "Media Library". The test studio is configured without specifying `libraryId`.
N/A - part of yet unannounced code.
> feat(core): use project scoped media-libraries endpoint

- test/e2e/tests/comments/inline.spec.ts
Lots of changes to the test:
* Turning on for webkit and firefox (since fingers crossed it seems robust enough to handle these)
* Using a triple click to highlight the text in the PTE
* Using a fallback of keyboard highlighting if the triple click didn't work
* Using network idle checks to ensure that test is ready to begin
* Marking as slow because firefox can be very slow at this test (and in general this is one of the most flakey tests)
N/A
> test: trying to make inline.spec more robust

- packages/sanity/src/core/form/inputs/NumberInput.tsx
Fixes the issue where number inputs gets modified if scroll wheel is used while hovering over while having focus.
Modifying the input value based on scroll wheel movement is the native browser behavior _when and only when_ a [`wheel`](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event) event listener is added to any element on the page, and because React eagerly adds listeners for all events to the root container, this opts-in to the mutate-on-wheel behavior.
The issue is currently present in latest Chrome and Safari. Firefox has disabled the mutate-on-wheel behavior entirely as of v130, and Safari has disabled it in the latest Technology Preview.
Unfortunately, the workaround in this PR only applies to Chromium based browsers and the issue remains in Safari until they …
> fix(form): workaround for mutate-on-wheel-issue for number inputs

- packages/sanity/src/core/releases/components/dialog/DiscardVersionDialog.tsx
- packages/sanity/src/core/releases/components/documentHeader/VersionChip.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/plugin/documentActions/DiscardVersionAction.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentActions.tsx
> [!Note]
> Waiting for a final ✅ from knut for the draft version but everything else should be good to go.
- Update copy for the discard module as feedback from Knut
| Discard a draft | Discard a version |
| ![image](https://github.com/user-attachments/assets/2b9fd0fb-5c3b-4f39-8a73-87abe192a30b) | ![image](https://github.com/user-attachments/assets/9d09e30f-e9b1-430d-a591-9f2382456af7) |
N/A
N/A
> refactor(core): add release description to discard dialog

- packages/sanity/src/core/validation/validators/objectValidator.ts
Currently, if you have an unpublished document with a reference field that references itself, you're not allowed to publish. This isn't a backend datastore restriction, but purely due to client side validation not considering whether a reference points at the current document when validating.
Any unforeseen consequences of this? I can't think of any.
- Create a new draft, e.g here: https://test-studio.sanity.dev//test/structure/input-debug;simpleReferences
- Make a self reference
- Observe that you are allowed to publish
- Fixes an issue preventing unpublished documents from referencing themselves.
> fix(validation): allow self-referencing drafts

- packages/sanity/src/_internal/cli/actions/graphql/deployApiAction.ts
When deploying a specific GraphQL API with the dry run flag if there are no breaking changes the API deploys even though dry run is set to true. This is happening because the `process.exit(0)` is not guaranteed to immediately stop execution. To address that I removed the process.exit(0) from that dryRun block and replaced it with a `continue`. Given the `api` flag can support multiple APIs it makes sense to test all of the requested APIs rather than stopping after the first one that matches. Given that `process.exit` can not be relied on I set the `process.exitCode` to **1** in any of the places where `process.exit(1)` was being called before.
1. Create a sanity.cli.ts file with multiple GraphQL APIs (this shouldn't matter but could help illustrate the race condition)
2. Run the deploy …
> fix: GraphQL deploy runs regardless of dry run argument

- packages/sanity/src/core/releases/util/prepareVersionReferences.ts
Upon version creation, Studio must not strengthen weak references unless the referenced document was created in place **and** is not mandated as weak in the schema.
Prior to this commit, the `prepareVersionReferences` function erroneously strengthened all weak references that were not created in place.
The correct behaviour is described in a code comment:
> Therefore, when creating a version of a document, the `_weak` property must be removed from any existing reference **that is set to strengthen on publish**.
However, the code was not checking whether the reference was set to strengthen on publish.
Manually tested each of the scenarios.
Fixes a bug causing weak references to erroneously  be strengthened when creating a version of a document.
> fix(sanity): reference strengthening upon version creation

- packages/@sanity/cli/src/actions/init-project/bootstrapLocalTemplate.ts
- packages/@sanity/cli/src/actions/init-project/createAppCliConfig.ts
- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/src/actions/init-project/templates/appQuickstart.ts
- packages/@sanity/cli/src/types.ts
- packages/sanity/src/_internal/cli/actions/app/__tests__/deployAction.test.ts
- packages/sanity/src/_internal/cli/actions/app/__tests__/undeployAction.test.ts
- packages/sanity/src/_internal/cli/actions/app/deployAction.ts
- packages/sanity/src/_internal/cli/actions/app/devAction.ts
- packages/sanity/src/_internal/cli/actions/app/undeployAction.ts
- packages/sanity/src/_internal/cli/actions/build/buildAction.ts
- packages/sanity/src/_internal/cli/actions/deploy/__tests__/helpers.test.ts
- packages/sanity/src/_internal/cli/actions/deploy/helpers.ts
- packages/sanity/src/_internal/cli/server/buildStaticFiles.ts
- packages/sanity/src/_internal/cli/server/devServer.ts
- packages/sanity/src/_internal/cli/server/getEntryModule.ts
- packages/sanity/src/_internal/cli/server/runtime.ts
- packages/sanity/src/_internal/cli/util/determineIsApp.ts
- packages/sanity/src/_internal/cli/util/servers.ts
Renamed `__experimental_appConfiguration` to `app` in the CLI config, and renamed its properties for better clarity:
- `appLocation` → `entry`
- `appId` → `id`
This change improves the developer experience by moving from an experimental API to a stable one with more intuitive property names.
Before:
```js
export default defineCliConfig({
__experimental_appConfiguration: {
organizationId: 'your-org-id',
appLocation: './src/App.tsx',
appId: 'your-app-id',
},
})
```
After:
```js
export default defineCliConfig({
app: {
organizationId: 'your-org-id',
entry: './src/App.tsx',
id: 'your-app-id',
},
})
```
- The renaming of configuration properties in the CLI config
- Updates to all references of these properties throughout the codebase
- Error messages and hints that reference these configuration …
> refactor(cli): rename app config keys and properties

- packages/sanity/src/_internal/cli/server/components/BasicDocument.tsx
- packages/sanity/src/_internal/cli/server/components/DefaultDocument.tsx
- packages/sanity/src/_internal/cli/server/components/Favicons.tsx
- packages/sanity/src/_internal/cli/server/components/NoJavascript.tsx
- packages/sanity/src/_internal/cli/server/components/globalErrorHandler/GlobalErrorHandler.tsx
- packages/sanity/src/_internal/cli/server/components/globalErrorHandler/_script.js
- packages/sanity/src/_internal/cli/server/components/globalErrorHandler/types.ts
- packages/sanity/src/_internal/cli/server/renderDocument.tsx
- packages/sanity/src/core/components/index.ts
- packages/sanity/test/__snapshots__/exports.test.ts.snap
This is another attempt at fixing not requiring styled-components deps for non studio templates. #9008 did not work as import also import styled-components dependency from down the tree. In this iteration, it moves the documents from the core package to the internal package to avoid the boundaries and the marks the DefaultDocument as deprecated. It is kept to avoid breaking change and there is duplication right now which is unfortunate.
`3.81.1-sdk-295.36` - canary release
- `npx sanity@3.81.1-sdk-295.36 init --template app-quickstart` 
- Choose `npm` as package manager
- cd in folder and run `npm build`
- run `npm run build`, you should get an error
- replace the sanity version in package.json with `3.81.1-sdk-295.36`
- run `npm install --legacy-peer-deps` again
- run …
> fix(cli): fixes issue where apps required styled-components

- packages/sanity/src/core/form/inputs/files/FileInput/FileInput.tsx
There's a discrepancy between the File og Image Input:
File Input's "Select"-button doesn't have a chevron, while ImageInput does.
Added the chevron to File Input to have consistency in the design.
After:
Too small to be mentioned?
> fix(core): add chevron to file browse sources button

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/studio/components/navbar/resources/ResourcesButton.tsx
- packages/sanity/src/core/studio/components/navbar/resources/ResourcesMenuItems.tsx
If installing the Studio from a tagged release or using pkg.pr.new, version numbers often gets too long to fit in the version menu. For example:
This information is too useful to cut off like this, so when looking into a fix, I figured why not make the version menu item pop a dialog with a bit of additional info with an easy way to copy it to the clipboard. So now, when you click the version info you'll now see this:
- Does it make sense?
- Is it a good start?
- What other information can we consider adding here?
Check out the preview build here: https://test-studio-git-more-version-details.sanity.dev/
- Now opens a version info dialog when clicking the "Current version"-menu item in the help resources from the Studio navigation bar
> feat(studio): add version info/about dialog

- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/config/configPropertyReducers.ts
- packages/sanity/src/core/config/prepareConfig.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FileInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAssetMenu.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputBrowser.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
The `config.form.image.directUploads` and similar for `config.form.file.directUploads` was introduced when we created assetSources in v2. 
These config parameters were intended to prohibit local uploads and force editors to use existing assets from (external) asset sources.
Somewhere along the v3 journey, this option was misinterpreted and prohibited selecting from the external asset sources when set to true. It was only possible to select from the "Uploaded images":
This breaks the intention of the config parameter. I have restored it to how it should work:
I have also added a reducer function for the config parameters to set them appropriately through plugins (was only supported on workspace config level)
Also, this is how it looks when there's only one (the build in) asset source. It …
> fix(core): restore intended func. for 'directUploads' config param

- .circleci/config.yml
- .github/workflows/are-we-compiled-yet.yml
- .github/workflows/cli-test.yml
- .github/workflows/docReport.yml
- .github/workflows/e2e-ct.yml
- .github/workflows/e2e-ui.yml
- .github/workflows/e2e.yml
- .github/workflows/formatCheck.yml
- .github/workflows/lint-fix-if-needed.yml
- .github/workflows/lintPr.yml
- .github/workflows/perf.yml
- .github/workflows/pnpm-if-needed.yml
- .github/workflows/prettier-if-needed.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- scripts/doc-report/docReport.ts
- scripts/printReleaseNotesTemplate.ts
This prepares for renaming `next` to `main`, mostly updates to workflow definitions and docs.
Once this is merged, I'll rename the main branch of this repo to uhm… `main`. This will hopefully not cause too much trouble, as GH should make sure open PRs get `main` as their new base automatically, and if I'm not mistaken GitHub will also set up redirects from urls pointing at `next` to `main`
Don't think this can (or should) be subject to automated testing. I'll do the required manual testing once the rename is done.
n/a
> refactor(ci): prepare for renaming next-branch to main

- packages/@sanity/cli/test/init.test.ts
Small fix for this test failure that we got after renaming `next` to `main`:
https://github.com/sanity-io/sanity/actions/runs/14246268611/job/39928363613?pr=9137#step:7:144
> fix(test): make test for sanity init w/template fetch from main branch instead of next

- packages/@sanity/cli/src/studioDependencies.ts
The peer-dependecy requirement for `styled-components` was bumped in #8940, but sanity init will still add `^6.1.8` to package.json for new projects, so this PR also updates that to be `^6.1.15`.
Probably best tested via the pkg.pr.new version that will be published after PR approval
n/a
> fix(cli): bump version of styled-components used by sanity init

- packages/sanity/src/core/form/inputs/ReferenceInput/ReferenceAutocomplete.tsx
- test/e2e/tests/inputs/reference.spec.ts
For some reason when running the test the dropdown doesn't want to open when clicking the arrow down button. However, when testing manually there is no issue. It is also not a consistent bug / behaviour.
However, using the input to trigger the input to open the list seems to work consistently and since the button behaviour is not what we are checking I've just changed that.
It's all test
N/A
> test(e2e): update e2e reference test

- dev/test-studio/schema/standard/portableText/customBlockEditors.tsx
- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Input.spec.tsx
- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ToolbarStory.tsx
- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
- packages/sanity/src/core/form/types/inputProps.ts
- test/e2e/tests/comments/inline.spec.ts
There's been some feedback internally and externally that it would be nice if
the Portable Text Input was active by default. So I think we should try it.
Therefore, the default value of the `PortableTextInput.initialActive` prop has
been flipped from `false` to `true`.
The only downside is that the editor might scrolljack you on a small
device/viewport, but this does not appear to be a good reason to make the
editor inactive by default for everyone, especially not when most users are on
desktop devices.
Does it work as expected? Is an input with `initialActive={false}` correctly made inactive on mount?
Some existing component tests have been adjusted to match the new behaviour.
The Portable Text Input is now active by default
> fix(core): make PTE active by default

- test/e2e/tests/releases/revert/revertASAP.spec.ts
- test/e2e/tests/releases/revert/revertSchedule.spec.ts
- test/e2e/tests/releases/revert/revertUndecided.spec.ts
- test/e2e/tests/releases/unarchive/unarchiveASAP.spec.ts
- test/e2e/tests/releases/unarchive/unarchiveScheduled.spec.ts
- test/e2e/tests/releases/unarchive/unarchiveUndecided.spec.ts
Tests are failing again, we need to find a better way or lift the 10 releases limit
This will make main healthy again (hopefully)
Did I miss anything? I think the displayDocument is safe to keep
N/A
N/A
> test(e2e): skip release tests for now

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/studio/components/navbar/resources/AboutDialog.tsx
Fixes the whitespace issue and removes redundant parens from the version info dialog that currently looks like this:
> fix(i18n): remove extra parens

- packages/sanity/src/_internal/cli/server/components/DefaultDocument.tsx
This pull request fixes a minor issue where the initial background of the Studio does not respect the user's color scheme preferences. The main issue it solves is that, if a user prefers a dark color scheme, the app flashes white while loading before switching to the appropriate dark background color.
The `#13141b` color matches the default dark background in Sanity UI. While it may not exactly match custom Studio themes, it's probably generally a better fallback than white and will likely align more closely with most potential custom dark mode styles.
**Before:**  
https://github.com/user-attachments/assets/93d77270-57f9-46a4-82fd-e57b6037e896
**After:**  
https://github.com/user-attachments/assets/8e71ce60-a230-4305-89a0-fd093e423788
- Does this makes sense?
Fixes an issue where the …
> feat: set background based on `prefers-color-scheme`

- dev/test-studio/sanity.config.ts
- packages/sanity/src/presentation/useDocumentLocations.ts
Fixes an issue in where if users had configured a presentation resolver the studio the document will crash when trying to resolve the published id, this fixes this by not using "published" when trying to get the version id.
Fixes an issue in where the presentation resolver would crash when using published perspective
> fix(presentation): resolve to publishedId when using publishedPerspective

- packages/sanity/src/_internal/cli/commands/dataset/exportDatasetCommand.ts
This PR updates sanity dataset export CLI text to include how failing assets are handled.
Failing assets in certain conditions are ignored after [this](https://github.com/sanity-io/export/pull/19) release of export package, which was included in `v3.69.0` sanity CLI version. Sanity documentation update reflecting this change is already in draft, pending review.
> docs: update sanity dataset export CLI help text

- dev/media-library-aspects-studio/aspects/colourDetails.ts
- dev/media-library-aspects-studio/aspects/productDetails.ts
- dev/media-library-aspects-studio/package.json
- dev/media-library-aspects-studio/sanity.cli.ts
- dev/media-library-aspects-studio/sanity.config.ts
- packages/@sanity/cli/src/types.ts
- packages/@sanity/schema/src/_exports/_internal.ts
- packages/@sanity/schema/src/sanity/validateMediaLibraryAssetAspect.ts
- packages/@sanity/schema/src/sanity/validateSchema.ts
- packages/@sanity/types/src/mediaLibrary/asserters.ts
- packages/sanity/package.json
- packages/sanity/src/_internal/cli/actions/media/constants.ts
- packages/sanity/src/_internal/cli/actions/media/createAspectAction.ts
- packages/sanity/src/_internal/cli/actions/media/deleteAspectAction.ts
- packages/sanity/src/_internal/cli/actions/media/deployAspectAction.ts
- packages/sanity/src/_internal/cli/actions/media/lib/determineTargetMediaLibrary.ts
- packages/sanity/src/_internal/cli/actions/media/lib/withMediaLibraryConfig.ts
- packages/sanity/src/_internal/cli/commands/index.ts
- packages/sanity/src/_internal/cli/commands/media/createAspectCommand.ts
- packages/sanity/src/_internal/cli/commands/media/deleteAspectCommand.ts
- packages/sanity/src/_internal/cli/commands/media/deployAspectCommand.ts
- packages/sanity/src/_internal/cli/commands/media/mediaGroup.ts
- pnpm-lock.yaml
This branch adds Media Library CLI config and three commands for managing asset aspects.
All commands that require a media library id to be specified accept a `--media-library-id` option. If no `--media-library-id` is specified, the CLI will load available media libraries and present a list to the user.
The `mediaLibrary.aspectsPath` option specifies the path in the project in which aspect definitions are stored. This must be specified for the CLI to be able to manage aspects.
> [!NOTE]
> These commands are currently hidden from the CLI's help text.
Scaffold a new aspect definition in the path specified by the project's `mediaLibrary.aspectsPath` option.
Undeploy the aspect matching the provided name. This command does not clean up dangling aspect data, nor does it delete aspect …
> feat(cli): add Media Library CLI

- packages/sanity/package.json
- packages/sanity/src/core/form/useComlinkViewHistory.ts
- packages/sanity/src/core/form/useDocumentForm.ts
- packages/sanity/src/core/hooks/useDocumentOperation.ts
- packages/sanity/src/core/hooks/useDocumentOperationWithComlinkHistory.ts
- packages/sanity/src/core/hooks/useRecordDocumentHistoryEvent.ts
- packages/sanity/src/core/store/_legacy/datastores.ts
- packages/sanity/src/core/store/comlink/createComlinkStore.ts
- packages/sanity/src/core/store/comlink/types.ts
- packages/sanity/src/core/store/renderingContext/listCapabilities.ts
- packages/sanity/src/core/store/renderingContext/types.ts
- packages/sanity/src/core/studio/workspaceLoader/WorkspaceRouterProvider.test.tsx
- packages/sanity/test/__snapshots__/exports.test.ts.snap
- packages/sanity/test/testUtils/TestProvider.tsx
- pnpm-lock.yaml
This branch adds support for capturing Studio activity and sharing it with Dashboard via Comlink.
> [!IMPORTANT]
> These changes only affect Studio when rendered inside Dashboard. When rendered standalone, Comlink isn't instantiated and no events are captured.
- The addition of the Comlink store.
- Capture of `viewed` event when viewing a document. For existing documents, this occurs once upon opening the document. For new documents, this occurs as soon as the user edits the document, causing it to be created.
- Capture of `edited` event when editing a document. This occurs once per document open to prevent inundating Dashboard with events.
Running a Studio inside Dashboard and watching the network for mutations tagged `sanity.dashboard`.
> feat: Dashboard history (without SDK)

- dev/test-studio/schema/standard/images.ts
- packages/@sanity/types/src/schema/definition/type/image.ts
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageToolInput/ImageToolInput.tsx
This PR introduces an image schema option: the `hotspot` object to enable and configure the hotspot tool, this pattern is being mindful of future options for both the hotspot tool and previews.
Mentioned in #957 
- Currently, setting this object in schema options will enable the hotspot tool.
- **Should we instead have a required `enabled` boolean inside this new options object?**
I have verified image fields in the Test Studio:
The `image` schema options now supports a `hotspot` object for configuring the image hotspot tool. This now enables custom aspect ratios for the crop previews to be configured:
```js
{
name: 'hotspotImage',
title: 'Hotspot image',
type: 'image',
options: {
hotspot: {
previews: [
{title: '2:1', aspectRatio: 2 / 1},
{title: '4:5', aspectRatio: 4 / 5},
{title: …
```
> feat(core): add image schema options for hotspot tool configuration

- packages/sanity/src/core/releases/hooks/useDocumentVersions.tsx
fixes an issue in where in some cases opening a document throws a set state error
> fix(core): useDocumentVersions should use stable initial value

- packages/sanity/src/core/studio/workspaceLoader/WorkspaceRouterProvider.tsx
When using query params, a trailing slash was always required after the URL route, before the `?`, otherwise the default tool and workspace would not load.
Now the trailing slash is not required, and query params are persisted during the routing
Manually tested, but there are some existing unit tests around this to verify no regressions
Fixes an issue that stops the studio loading when the URL does not include a trailing slash immediately preceding  a query string.
> fix: excluding query params from pathname check when routing to tool

- packages/sanity/src/core/perspective/navbar/ReleasesNav.tsx
- Fixes a CSS issue that caused the studio navbar to take up 6px more vertical height than intended.
- Make sure the navbar takes up 50px vertical height in all scenarios (any device width).
> fix(studio): add missing negative margin to global perspective menu

- .github/workflows/release-please.yml
- CHANGELOG.md
- release-please-config.json
Adds release-please workflow to this repository. The manifest is more or less a verbatim copy of [release-please.yml](https://github.com/sanity-io/visual-editing/blob/main/.github/workflows/release-please.yml) from the visual-editing repo, with the notable difference of versioning all packages together (using the linked-versions plugin, see release-please-config.json) and using lerna for actual publishing to npm.
Probably not the easiest to review without context
Note that merging this will not _release_ anything on its own. This workflow will be triggered after a package version bump has  been merged to main. I might need to do some follow up tweaks, so safe to merge this. 
Hard to test in isolation. Hopefully, a PR should appear after this gets merged.
n/a
> chore(ci): set up release-please workflow

- packages/sanity/src/_internal/cli/actions/app/deployAction.ts
- packages/sanity/src/_internal/cli/actions/app/undeployAction.ts
This PR updates the messaging in the app deployment and undeployment processes:
1. Changes the deployment spinner message from "Deploying to Core..." to simply "Deploying..."
2. Updates the undeployment confirmation message to show the application ID instead of the application host
- Check the deployment spinner message in `deployAction.ts`
- Verify the undeployment confirmation message in `undeployAction.ts` now shows the application ID
Tested by running the deploy and undeploy commands and verifying the updated messages appear correctly.
N/A
> fix(cli): update copy for app undeploy

- dev/depcheck-test/package.json
- dev/design-studio/package.json
- dev/embedded-studio/package.json
- dev/media-library-aspects-studio/package.json
- dev/page-building-studio/package.json
- dev/starter-studio/package.json
- dev/strict-studio/package.json
- dev/studio-e2e-testing/package.json
- dev/test-create-integration-studio/package.json
- dev/test-studio/package.json
- examples/blog-studio/package.json
- examples/clean-studio/package.json
- examples/ecommerce-studio/package.json
- examples/movies-studio/package.json
- lerna.json
- packages/@repo/dev-aliases/package.json
- packages/@repo/package.bundle/package.json
- packages/@repo/package.config/package.json
- packages/@repo/test-config/package.json
- packages/@repo/test-exports/package.json
- packages/@repo/tsconfig/package.json
- perf/studio/package.json
- perf/tests/package.json
We need to configure release-please to bump every package (ideally also the version in lerna.json), but for now, this manually bumps internal packages up to v3.86.0
n/a – internal
> chore: manually bump internal packages

- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
`.value` on the PTE `EditorSchema` types has been renamed to `.name`.
Do Markdown behaviours still work? (yes)
n/a
n/a
> refactor(core): remove usage of deprecated `EditorSchema` props

- .release-please-manifest.json
- dev/depcheck-test/package.json
- dev/design-studio/package.json
- dev/embedded-studio/package.json
- dev/media-library-aspects-studio/package.json
- dev/page-building-studio/package.json
- dev/starter-studio/package.json
- dev/studio-e2e-testing/package.json
- dev/test-create-integration-studio/package.json
- dev/test-studio/package.json
- examples/blog-studio/package.json
- examples/clean-studio/package.json
- examples/ecommerce-studio/package.json
- examples/movies-studio/package.json
- packages/@repo/dev-aliases/package.json
- packages/@repo/package.config/package.json
- packages/@repo/test-config/package.json
- packages/@repo/test-exports/package.json
- packages/@repo/tsconfig/package.json
- perf/efps/package.json
- perf/studio/package.json
- perf/tests/package.json
- release-please-config.json
Includes some tweaks and improvements to the release setup.
- bumps all packages as part of the release. This is a continuation of our already established convention.
- sets the version of internal packages to 0.0.0, these are never release anyway, so no reason to bump them as part of published packages.
- adds `packages/@repo/package.bundle` to the list of packages that will be bumped. This is the source of truth for "current version" used by Auto-Updating Studios.
Example PR made by this config: https://github.com/sanity-io/sanity/pull/9256
Note: The description of that PR isn't great, ideally it should list the package name in the section summary, but think it's just merged as is from changelogs and found no way to easily configuring this.
n/a
> chore(ci): simplify release-please setup

- .github/workflows/cli-test.yml
Currently, the CLI tests tries to install the current version from npm as part of running the tests (these versions are later replaced with the local version). However, with our new release automation, a PR will be opened with version bumps _before_ they get published to npm, which means the CLI tests will fail on that PR and the subsequent merge of that PR (after merge the packages will be published, so after a while the tests will succeed, but I'd prefer not to have to hit retry after they fail initially)
Once merged, we should see that the CLI tests are skipped on [this release PR](https://github.com/sanity-io/sanity/pull/9246), and the following merge of it.
n/a
> chore(ci): skip cli tests on release PR and push

- .github/workflows/cli-test.yml
The change in #9262 produced invalid shell script (thanks ChatGPT! 🙄):
```sh
if [[ "pull_request" == "pull_request" ]] && \
[[ "[
"autorelease: pending"
]" == *"autorelease: pending"* ]]; then
echo "✅ Skipping test on release PR"
exit 0
fi
```
This PR updates the check to use a similar check for PR title as we use for the commit. Third time is the charm, eh?
> chore(ci): improve check for release pr or commit

- release-please-config.json
looks like "skip-github-release": true, is not what we want as it looks like it will skip creating the tags and doing the release alltogether
> chore(ci): don't skip github release

- .github/workflows/etl.yml
* triggers ETL on release events as well as other pushes
* Uses production secrets for pushing TSDocs when triggered by a release publish event
N/A
> chore(ci): update ETL workflow to trigger on release events

- release-please-config.json
Adds the linked-packages plugin so that all packages are versioned together, based on the highest version number in the group, as per docs:
> When any component in the specified group is
updated, we pick the highest version amongst the components and update all
group components to the same version (keeping them in sync).
I initially thought that `updateAllPackages` would do this, but seems like that just guarantees that all packages are _bumped_, so that could leave us with e.g. `@sanity/types` being patch-bumped to `3.87.1` and, `sanity` minor-bumped to `3.88.0`
> chore(ci): link all versions

- packages/sanity/src/core/config/prepareConfig.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FileAsset.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FilePreview.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAsset.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAssetMenu.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputPreview.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImagePreview.tsx
- packages/sanity/src/core/form/inputs/files/common/PlaceholderText.tsx
- packages/sanity/src/core/form/inputs/files/common/UploadPlaceholder.tsx
If the Media Library is enabled in the workspace, set it as the first (and default) asset source.
Also, fix a couple of bugs related to the asset sources config.
N/A
> refactor(core): set MediaLibrary as the first (default) asset source

- packages/sanity/src/core/config/document/actions.ts
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelHeader.tsx
- packages/sanity/src/structure/panes/document/keyboardShortcuts/DocumentActionShortcuts.tsx
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
Adds a boolean for the documentActionProps to indicate if a initial value is resolved or not.
This is necessary because in some cases we want to disable a custom action while the initial values are resolving, initial values can be async and there is nothing to indicate if this process has ended or not.
See [LinkToCanvasAction](https://github.com/sanity-io/sanity/pull/9289/commits/1becedb09a9425372ec434107811a72b8ef33525#diff-b6dc28109fa776de745fc0e66f56ea28dd32bb62ceda784e622d8a4705363055R57-R59) in  https://github.com/sanity-io/sanity/pull/9289 
Adds a new property to `DocumentActionProps` indicating if the document initial value is resolved.
> feat(structure): adds `initialValueResolved` to DocumentActionProps

- release-please-config.json
Looking at the generated [diff for the release PR](https://github.com/sanity-io/sanity/pull/9270/files) after merging #9275, not all packages were bumped, so looks like we _also_ want to keep `updateAllPackages` in combo with linked-versions.
> chore(ci): enable updateAllPackages

- dev/test-create-integration-studio/CustomAction.tsx
- dev/test-create-integration-studio/sanity.config.ts
- packages/sanity/src/core/components/hookCollection/defineHookStateComponent.tsx
- packages/sanity/src/core/components/hookCollection/types.ts
- packages/sanity/src/structure/components/RenderActionCollectionState.tsx
- packages/sanity/src/structure/i18n/resources.ts
This PR consist of two changes:
1) Adds `action.action` value to the action states hooks return value. This are the value of the hooks returned by the document actions. We need this in order to help categorize an action as custom or not, and also to expose more action data down the tree.
2) Adds a placeholder to disable the actions that are not supported when a document is linked to canvas, see https://github.com/sanity-io/sanity/pull/9289/
This `TEMP_DISABLED_BY_CANVAS` will be removed in the PR mentioned above and will be replaced by the canvas companion doc validation.
Are this changes correct?
Actions should remain the same, nothing should change.
If you want to test the disabled actions locally go to `sanity/dev/test-create-integration-studio` and then `pnpm dev`, this will run the …
> feat(structure): add actions.action value to actions states

- .github/workflows/cli-test.yml
Sets the PR title as an env var instead of passing to bash.
- Does it make sense?
No way to easily test this, but the CLI tests still be skipped for release PRs after merging
n/a
> chore(ci): prevent passing PR title to workflow script

- packages/sanity/src/core/store/_legacy/project/projectStore.ts
- packages/sanity/src/core/store/_legacy/project/types.ts
- packages/sanity/src/core/store/_legacy/project/useProjectOrganizationId.ts
Adds a new `getOrganizationId` function  in the `projectStore` to get the project organization id, this is useful in our move to dashboard as we will need to fetch the org id to navigate to the correct dashboard. 
It also includes a hook to simplify the usage of the new function.
Are this changes correct?
You can see how it is being used in the [`studio-canvas`](https://github.com/sanity-io/sanity/compare/studio-canvas/actions) integration.
n/a
> feat(core): add `useProjectOrganizationId` hook

- packages/sanity/src/core/presence/DocumentPreviewPresence.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
> feat: i18n for release tool presence tooltips

- packages/@sanity/cli/src/cli.ts
- packages/sanity/src/_internal/cli/actions/app/buildAction.ts
- packages/sanity/src/_internal/cli/server/getStudioEnvironmentVariables.ts
- packages/sanity/src/_internal/cli/server/getViteConfig.ts
This PR changes the environment variable prefix for Sanity apps from `SANITY_STUDIO_` to `SANITY_APP_`. This creates a clearer distinction between studio and app environments, making it easier to configure different settings for each context.
- The changes to environment variable loading in the CLI
- The implementation of `getAppEnvironmentVariables` function
- The updated environment variable prefix in the Vite configuration for apps
- The order of operations in the CLI to ensure environment variables are loaded after the CLI config is determined
Tested by verifying that:
- Apps correctly load environment variables with the `SANITY_APP_` prefix
- Studios continue to use the `SANITY_STUDIO_` prefix
- The basePath configuration works correctly with the new prefix
N/A
> feat(cli): add env prefix for apps

- packages/sanity/src/_internal/cli/util/checkStudioDependencyVersions.ts
- packages/sanity/src/_internal/cli/util/readPackageManifest.ts
Exported the `readPackageJson` function from `readPackageManifest.ts` and added error handling to provide more context when reading a package.json file fails. Updated `checkStudioDependencyVersions.ts` to use the newly exported function.
- The error handling in `readPackageJson` now includes the file path in the error message
- The function is now properly exported for reuse
- The usage of this function in `checkStudioDependencyVersions.ts`
The changes have been tested by verifying that:
- The function correctly reads package.json files
- Error messages now include the file path for better debugging
- The exported function works correctly when imported in other files
Fixes issue where build command would fail if there is no version in package.json
> fix(cli): fixes issue where cli would error if version is missing

- packages/sanity/src/_internal/cli/actions/deploy/deployAction.ts
When deploying `Sanity.Studio` looks weird as it uses Title Case in a domain name.
> chore: lowercase sanity.studio url

- packages/@sanity/cli/src/actions/init-project/initProject.ts
I discovered that the init command incorrectly prompts for user input even when running in unattended mode within Next.js. This PR addresses that issue by adding correct handling for unattended mode specifically within Next.js contexts.
Additionally, I noticed that the command currently exits with an error if the --output-path flag is omitted in unattended mode. However, the --output-path value isn't actually utilized when initializing within Next.js. Therefore, this PR also removes the requirement for the --output-path flag when running in unattended mode inside Next.js.
This change affects unattended `sanity init` when ran in a nextjs project. See Testing for more details.
That you can initialize unattended within a nextjs project. Before this change you would be prompted
> Would you …
> fix(cli): Support unattended init within nextjs

- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/DocumentNotInReleaseBanner.tsx
This PR fixes a bug where, when viewing the Studio with a pinned release that was scheduled, a "Scheduled to be released" banner would show on all documents.
We've refined the logic to check if the specific document you're viewing is part of the release.
Just the additional logic condition. Any gotchas or places this will break?
Also, I believe it's intended that a user should _not_ be able to edit any document when viewing the Studio with a scheduled perspective, so I haven't made any additional changes to allow documents to be edited in this state, but please let me know if that's incorrect and I'll fix this too.
I didn't see existing tests for this but feel free to point me in the right direction.
Resolves an issue where a "Scheduled to be released" banner would show on all documents …
> fix(structure): check that document is in scheduled release before showing banner

- packages/sanity/src/core/canvas/__telemetry__/canvas.telemetry.ts
- packages/sanity/src/core/canvas/actions/EditInCanvas/EditInCanvasAction.tsx
- packages/sanity/src/core/canvas/actions/LinkToCanvas/LinkToCanvasAction.tsx
- packages/sanity/src/core/canvas/actions/LinkToCanvas/LinkToCanvasDialog.tsx
- packages/sanity/src/core/canvas/actions/LinkToCanvas/useLinkToCanvas.ts
- packages/sanity/src/core/canvas/actions/UnlinkFromCanvas/UnlinkFromCanvasAction.tsx
- packages/sanity/src/core/canvas/types.ts
- packages/sanity/src/core/canvas/useCanvasTelemetry.ts
- packages/sanity/src/core/canvas/useNavigateToCanvasDoc.ts
- packages/sanity/src/structure/panes/document/documentPanel/banners/CanvasLinkedBanner.tsx
Adds studio canvas telemetry.
It will track the following actions:
1) link to canvas (event)
- no diffs - auto-accept (event)
- has diffs
-   show diffs dialog (event)
-   Accepts diffs (event)
-   Rejects diffs (event)
2) Unlink from canvas (event)
- accept - unlink (event)
- reject - do nothing
3) Open canvas (event)
- origin: action
- origin: banner
Is there any other event to track?
n/a
> feat(core): add studio - canvas telemetry

- packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
Before:
Currently studio has only one way of storing an auth token -> it takes an SID from an auth provider and uses a backend auth endpoint to convert this to an unstamped token. This token is then stored in local storage and possibly as a cookie.
After:
Now the studio will bypass the exchange from SID to token when a token is provided via the URL hash. This has 2 benefits. 1, it reduces a server round trip, which should speedup initial load times of studios running in these environments. Secondly, this resolves issues with running local studios within these environments.
Demo:
This is best demonstrated in terms of running a local studio within a wrapping environment.
| ![dashboardAuthTokenBEFORE](https://github.com/user-attachments/assets/ff0e5d91-3 …
> fix: supporting passing an auth token via URL hash

- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseRevertButton/__tests__/useDocumentRevertStates.test.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseRevertButton/useDocumentRevertStates.ts
reverting document with only unpublish documents is handled correctly; fixes issue with reverting one transaction too far back
Fixes an issue in Releases+ where reverting a release would fail is only unpublish documents had been included in the release.
Fixes an issue in Releases+ where reverting a release would revert documents back 1 revision too far
> fix: reverting release translog handling

- playwright.config.ts
Update BASE_URL, to instead of using `readEnv` which throws if the env var doesn't exist, use the `findEnv` so it supports having a fallback value, and update it to localhost:3339, which is the default port we use for testing.
> fix(test): use base url fallback value

- .github/workflows/e2e-ui.yml
- .github/workflows/e2e.yml
- .github/workflows/pr-cleanup.yml
- scripts/e2e/cleanup.ts
- scripts/e2e/e2eClient.ts
- Changed the ids to rely not only on the PR id (example: 9295) but also on the workflow ID. I used the workflow instead of the SHA (commit) because sometimes we need to re-run works - and in those instances, what we want to rely on is the workflow ID - example (`pr-9295-chromium-14727017893`)
- The clean up will now find any dataset that starts with the right PR id and remove any and all datasets.
- Removed split between chrome and firefox in the cleanup, the cleanup for the datasets happens based on the PR id than necessarily focused on specific environments / projects
Did we miss anything? My biggest concern is that this will be solely focused on the branches and PRs and that I feel that the main branch will remain untouched - which might be what we want - but it …
> chore(github): dataset create per push + dataset deletion on close/merge

- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleasePublishAllButton.tsx
We weren't passing the error message through so the toast was malformed
N/A
> fix: include publishing error message in ReleasePublishAllButton 

- packages/sanity/src/core/canvas/actions/UnlinkFromCanvas/UnlinkFromCanvasAction.tsx
- packages/sanity/src/core/canvas/actions/UnlinkFromCanvas/UnlinkFromCanvasDialog.tsx
When using hooks the hook should start with  `use` or react will fail when unmounting the component in production mode.
This PR updates the use of `unstable_useValuePreview` to be `useValuePreview`
> fix(core): unlink dialog crash

- dev/test-create-integration-studio/schema.ts
- packages/@sanity/types/src/schema/definition/type/common.ts
- packages/@sanity/types/test/options.test-d.ts
- packages/@sanity/types/test/url.test.ts
- packages/@sanity/types/vitest.config.mts
[WIP]
Adds canvas app options to the schema types allowing users to configure how the fields or the schema type will behave inside canvas.
> chore(core): adds `canvasApp` options to schema types 

- packages/sanity/package.json
- packages/sanity/src/_internal/cli/actions/build/buildAction.ts
- packages/sanity/src/_internal/cli/actions/dev/devAction.ts
- packages/sanity/src/_internal/cli/util/packageManager/getUpgradeCommand.ts
- packages/sanity/src/_internal/cli/util/packageManager/packageManagerChoice.ts
- packages/sanity/src/_internal/cli/util/packageManager/upgradePackages.ts
- packages/sanity/src/_internal/cli/util/shouldAutoUpdate.ts
- pnpm-lock.yaml
Currently it's easy to miss it if you have auto-updates enabled and are running `sanity dev` with outdated local dependencies compared to what's currently served at runtime for your deployed studio. This can lead to situations where you get different behavior locally than after deployment (i.e. you get hit by a bug during dev that's fixed for your deployed studio). It might also be surprising that your local versions aren't updated, since you've opted into auto-updates after all.
As of this PR, when `sanity dev` is invoked, we'll check if auto-updates are enabled, and if it is, and you have outdated local dependencies, we'll ask you if you'd like to upgrade.
Example:
```
npx sanity dev
? The following local package versions are different from the versions currently served at runtime.
When …
```
> feat(cli): ask to auto update on sanity dev, build and deploy

- packages/@sanity/types/src/assets/types.ts
- packages/@sanity/types/src/schema/types.ts
- packages/sanity/src/core/form/inputs/files/FileInput/FileInput.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FileInputAssetSource.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAssetSource.tsx
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/shared/MediaLibraryAssetSource.tsx
This will add the allowed metadata as configured on an Image schema type to be put on the local asset document from the Media Library.
> feat(core): allow pulling metadata as configured on image type for ML assets

- packages/sanity/package.json
- packages/sanity/src/core/studio/StudioProvider.tsx
- packages/sanity/src/core/studio/components/ComlinkRouteHandler.tsx
- packages/sanity/src/core/studio/hooks/useComlinkRouteHandler.ts
- pnpm-lock.yaml
This branch adds a subscription to the Comlink `dashboard/v1/history/change-path` message. This message allows the Studio rendering context to perform a navigation inside Studio.
This is important for allowing users to navigate to documents from the Dashboard favourites list.
If no Comlink node is available (e.g. because Studio is rendered standalone), no subscription will be created.
Note that the [the `PathChangeMessage` type defined in `@sanity/message-protocol`](https://github.com/sanity-io/ada/blob/cb6498e4e4b5c971d9866c44230cd434154a1dbb/packages/message-protocol/src/window-messages/index.ts#L6-L12) includes a required `type` property. In my testing, this property is not included in the event emitted by Dashboard. For now, the received path is always applied using `push`. This is a …
> feat: sync Dashboard path 

- packages/sanity/src/core/canvas/actions/LinkToCanvas/LinkToCanvasAction.tsx
- packages/sanity/src/core/canvas/actions/LinkToCanvas/useLinkToCanvas.ts
- packages/sanity/src/core/canvas/i18n/resources.ts
- packages/sanity/src/core/canvas/useNavigateToCanvasDoc.ts
- packages/sanity/src/core/store/_legacy/project/projectStore.ts
- packages/sanity/src/core/store/_legacy/project/types.ts
In some cases users could not have permissions to fetch the organization id endpoint. In this cases we will catch the error and handle the `null` response in the consumers.
For canvas, the link action will be disabled.
Fixes an issue in where some users couldn't open documents in the studio due to missing permissions to get the org id
> fix(core): catch error on getOrganizationId

- dev/test-studio/schema/debug/manyViews.tsx
- dev/test-studio/schema/index.ts
- dev/test-studio/structure/constants.ts
- dev/test-studio/structure/resolveStructureDocumentNode.ts
- packages/sanity/src/structure/components/pane/PaneHeader.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentHeaderTabs.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/DocumentPanelSubHeader.tsx
This PR reverts the UX changes to document view tabs that was done as part of the Releases launch.
- Open document types without view tabs and make sure they behave as before.
- Open document types with view tabs and make sure they behave as prior to the Releases launch.
- [Type with many views](https://test-studio-git-refactor-sapp-2658.sanity.dev/test/structure/input-debug;manyViews;45afd740-f949-4920-bc1d-58459a8a5638)
- [Type with 1 view](https://test-studio-git-refactor-sapp-2658.sanity.dev/test/structure/author;e0e1b95d-6182-4198-a92d-4c0c63215681)
> fix(structure): revert document view tabs placement and behavior

- packages/sanity/src/core/perspective/navbar/currentGlobalPerspectiveLabel.tsx
This small visual regression was probably introduced when we adjusted the perspective menu's layout. It only manifests when the releases tool is unavailable.
It's fixed by switching the inner component from a `Card` with an inherited background colour, to a `Box` with no background colour at all.
| --- | --- |
| <img width="124" alt="before" src="https://github.com/user-attachments/assets/f7d172c6-f5d8-4042-9293-f422d417f7bf" /> | <img width="124" alt="after" src="https://github.com/user-attachments/assets/5ecb9c04-1df6-4768-b490-506e4693def6" /> |
- The perspective menu when the releases tool is unavailable.
- Tested in browser.
> fix(sanity): remove redundant background colour from perspective label child

- packages/sanity/src/_internal/cli/util/getAutoUpdatesImportMap.ts
This PR makes `@sanity/vision` imports optional in the auto-updates import map. It modifies the `getStudioAutoUpdateImportMap` function to accept a new `includeVision` parameter (defaulting to `true`), which controls whether Vision-related imports are included in the returned map. The `getAppAutoUpdateImportMap` function now explicitly passes `false` for this parameter when calling `getStudioAutoUpdateImportMap`.
- The type changes to make `@sanity/vision` and `@sanity/vision/` optional in the `StudioAutoUpdatesImportMap` interface
- The refactoring of `getStudioAutoUpdateImportMap` to conditionally include Vision imports
- The updated call to `getStudioAutoUpdateImportMap` in `getAppAutoUpdateImportMap` with `includeVision` set to `false`
Verify that:
- Studio auto-updates continue to …
> fix(cli): fixes vision deps check for apps

- dev/test-studio/schema/standard/globalDocumentReference.ts
- packages/@sanity/schema/src/sanity/validation/types/globalDocumentReference.ts
- packages/@sanity/types/src/globalDocumentReference/types.ts
- packages/@sanity/types/src/schema/definition/type/globalDocumentReference.ts
- packages/sanity/src/core/form/inputs/GlobalDocumentReferenceInput/GlobalDocumentReferenceInput.tsx
* Instead of providing a function we can provide a studio base url. This allows us to serialize them in aspects, and it's also easier to construct.
* If no studio url is given, we hide the icon.
Missed anything?
* Added to the test studio and tested manually
N/A - No release notes needed for this.
> feat(gdr): allow sending base url to studioUrl for GDRs

- packages/sanity/src/core/studio/hooks/useComlinkRouteHandler.ts
Comlink-driven navigation currently relies on the history instance provided by `useRouterHistory`. This does not work correctly for intent resolution when multiple workspaces are present.
This branch fixes the problem by switching to the router instance provided by `useRouter`.
- The router usage.
- Tested by installing this tagged release in a Studio with multiple workspaces, deploying it to production, and using it in Dashboard. [You can access that Studio in Dashboard here](https://core.sanity.io/@oSyH1iET5/studio/zdd721swr6za1cgp5ot34hxf).
- Tested the same Studio with only a single workspace and verified routing continues to work correctly.
> fix(sanity): switch to `RouterContextValue` instance for performing Comlink-driven navigation

- dev/test-studio/locales/index.ts
- dev/test-studio/structure/resolveStructure.ts
- packages/sanity/src/structure/panes/list/ListPaneContent.tsx
- packages/sanity/src/structure/structureBuilder/Divider.ts
- packages/sanity/src/structure/structureBuilder/List.ts
- packages/sanity/src/structure/structureBuilder/StructureNodes.ts
- packages/sanity/src/structure/structureBuilder/createStructureBuilder.ts
- packages/sanity/src/structure/structureBuilder/types.ts
- packages/sanity/src/structure/types.ts
> [!NOTE]  
> This PR has consciously left out .icons() and .component() methods as to keep it in shorter scope
> There are implications to both in the UI and UX that we don't have time to tackle right now but have been added in a separate story
Add a `.title()` and `.i18n()` methods to the `.divider()` 
Does this make sense? Did I miss anything?
You can manually test the translation by following the next steps:
https://github.com/user-attachments/assets/047a3bcd-7fb7-494c-a502-31c11c695ba9
￼- In resolveStructure do
``` 
S.divider()
.title('Divider title what what')
.i18n({title: {key: 'text-divider-title', ns: structureLocaleNamespace}}),
```
- You can activate the translate of the studio by going to `userMenu/LocaleMenu` and removing the return nulls
- In the sanity.config.ts for the …
> feat(struture): add title and translate aspects

- packages/sanity/src/core/releases/store/createReleaseMetadataAggregator.ts
- packages/sanity/src/core/releases/tool/detail/events/getReleaseEvents.ts
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
Minor refactor to use `partOfRelease` query rather than our own `_id in ...`
Verified that the 3 places this touches still load as expected.
Release overview list still loads - tests `createReleaseMetadataAggregator`
Release detail list still loads - tests `useBundleDocuments`
`getReleaseEvents` is more tricky to visually show, but have verified that the correct subscription is being setup.
N/A
> refactor: using sanity::partOfRelease where appropriate

- .github/renovate.json
[ESBuild <= 0.21 is allowed by our Renovate config](https://github.com/sanity-io/sanity/blob/de31066a46a4405380c3749031d65451f73f2734/.github/renovate.json#L108-L112), so we have no automation to keep the four ESBuild dependencies across the monorepo in sync. We added this exception because subsequent ESBuild releases removed support for Windows 7 & 8.
The result is that we have no automation for updating ESBuild security patches. Members of the community have kindly opened PRs to update ESBuild, however, we now have a combination of ESBuild versions in the monorepo. We should keep these versions consistent.
Important security fixes (e.g. [GHSA-67mh-4wv8-2f99](https://github.com/advisories/GHSA-67mh-4wv8-2f99)) have not been backported to older ESBuild versions. We have decided to remove …
> chore(renovate): remove ESBuild <=0.21 allowance

- packages/sanity/src/core/releases/tool/detail/AddDocumentSearch.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
When reviewing releases with more than 1000 documents I found that we are doing a duplicated invocation of `useBundleDocuments`, this hook is the one that gets all the documents in the release, validates them and gets the preview for them.
By calling this hook in two components inside the `ReleasesDetail` view we are duplicating all of this logic, in small releases it's not a big problem, but in very large ones this could lead to thousands of queries being duplicated and eventually crashing.
As next steps we could think on moving this to a cached store so we can reuse the hook anywhere with no risks, but doing this now feels like an unnecessary risk.
We should also consider how we fetch and validate data in the releases overview screen given we are also calling this hook there in …
> fix(core): remove duplicated call to useBundleDocuments

- packages/sanity/src/core/form/studio/inputs/globalDocumentReference/StudioGlobalDocumentReferenceInput.tsx
- packages/sanity/src/core/form/studio/inputs/globalDocumentReference/datastores/getReferenceClient.ts
- packages/sanity/src/core/form/studio/inputs/globalDocumentReference/datastores/getReferenceInfo.ts
- packages/sanity/src/core/form/studio/inputs/globalDocumentReference/datastores/search.ts
We were using a "fake" resource client to resolve GDR referenced documents. Now that we have resource support in the sanity client we can use the client to resolve these.
Correctness
Since this is more of a refactor, the functionality should stay the same, so no tests should be added or removed.
N/A : No notes needed, more an internal improvements for future maintainability
> feat: use sanity client to resolve GDR references

- dev/test-studio/plugins/error-reporting-test/ErrorReportingTest.tsx
Silences the following warning that was introduced by #9349
```
./test-studio/plugins/error-reporting-test/ErrorReportingTest.tsx
225|  const ReactLazyError = lazy(_c3 = () => {
226|    const name = "/does-not-exist.js";
227|    return import(name);
|                  ^^^^
228|  });
229|  _c4 = ReactLazyError;
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.
Plugin: vite:import-analysis
File: ./test-studio/plugins/error-reporting-test/ErrorReportingTest.tsx
```
n/a
> chore(test-studio): add vite-ignore to dynamic imports to silence warning

- packages/@sanity/cli/templates/app-quickstart/src/App.tsx
- packages/@sanity/cli/templates/app-sanity-ui/src/App.tsx
The "example" strings with projectId and dataset were added before certain changes to the template and the SDK. In its current state, it tries to get permissions from a project and dataset that do not exist, meaning the first experience a user has with a template is an error.
The only hook in the template can work without a projectId or dataset, so the initial load does not present the user with an error.
Does this make sense to a new user? Is there a better way to approach this?
Probably the best way to test this is to use our existing init command (`pnpx sanity@latest init --template app-quickstart`), remove the projectId and dataset, and see the result. It should be an error-free app.
Removes the default projectId and dataset from the App SDK templates.
> fix(cli): remove projectId and dataset strings from app templates

- packages/sanity/src/core/form/useDocumentForm.ts
Not ready yet
Fixes issue where a user without permissions to edit or create drafts but _did_ have permissions to create and edit versions wasn't being able to edit versions and was instead being given the banner that they didn't have permissions
before
Assign your user to the role, rita custom groq query role, you'll be able to edit and perform operations with versions as long as the pinned version matches (if you use the deployed version, if you use the main version you'll see the issue)
Fixes issue where a user that should have permissions to edit version of documents, wasn't being able to.
> fix(core): add fix for useDocumentForm

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/commands/blueprints/addBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/configBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/deployBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/destroyBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/infoBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/logsBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/planBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/stacksBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/functions/functionsGroup.ts
- packages/@sanity/cli/test/blueprints.test.ts
- pnpm-lock.yaml
`runtime-cli` is now at v7+, adding some function name validation for `blueprints add`, bug fixes, new config initialization helpers, and options for installing `@sanity/functions` helpers 
The `blueprints add` command has new flags. They are not required and if omitted, users will be prompted about adding and installing the functions helpers.
I updated the blueprints command tests to mock the new initBlueprintConfig and initDeployedBlueprintConfig functions
the main update is the addition and installation of `@sanity/functions` helpers when using `blueprints add function`
> chore(cli): update runtime cli

- packages/sanity/src/core/hooks/useClient.ts
Currently calling `useClient()` will trigger a console warning. We have let this slip through a few times and retrospectively caught it in the monorepo, but this can also occur in client plugins.
Requiring `clientOptions` would be a breaking change, so instead if we overload `useClient` and mark `undefined` `clientOptions` signature as `deprecated` then we can give clear DX signal not to use this approach, whilst still supporting it.
* Does this imply that `useClient` might be deprecated entirely?
* Is there an alternative approach?
N/A
Using `useClient` without a defined `apiVersion` is now marked as deprecated.
> chore: marking use of useClient() with no options as deprecated

- .eslintrc.cjs
This rule frequently adds friction and provides very little value IMO. Yes, nested ternaries be definitely be overused and make code less readable, but I don't expect us to go wild with nested ternaries and we do have a low bar for requesting readability improvements in code reviews.
It's also not clear how to work around the rule in a way that makes things more readable. Extracting the logic into a separate function adds extra work and a level of indirection (often justified though!), IIFEs are weird, and combinations of `&&` and `||` ends up being harder to unpack in my experience.
> chore(eslint): switch off no-nested-ternary rule

- packages/sanity/src/core/components/hookCollection/useHookCollectionStates.tsx
- packages/sanity/src/core/templates/resolve.ts
- packages/sanity/src/core/util/postTask.ts
- test/e2e/tests/document-actions/liveEdit.spec.ts
There was a bug where the request for the collections states (which eventually resolves the document actions) was being hang by other on going threads (such as, in the case that identified this issue, resolving templates). The solution now relies on the same resolver as the templates does so that it internally knows and can better adjust what should be resolved first without blocking.
Before
https://github.com/user-attachments/assets/0f6ad74c-cf59-4b1e-8764-041dac1dfddb
After
https://github.com/user-attachments/assets/669c58e0-d80f-4e38-9bc3-78def4cb71de
Does it work? Does it make sense? Should I have done it in a different way?
To more easily test this it's better to place a test studio in the monorepo and test it from there.
I can provide the test studio and instructions if needed
Fixes …
> fix(core): add fix for hanging requests for the collection states

- packages/sanity/src/core/releases/hooks/useVersionOperations.tsx
- packages/sanity/src/core/releases/store/__tests__/createReleaseOperationsStore.test.ts
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
- packages/sanity/src/core/releases/store/createReleasePermissionsStore.ts
- packages/sanity/src/core/releases/store/useReleasePermissions.ts
- packages/sanity/src/core/releases/util/const.ts
Moving `createReleaseOperationsStore` to use the new methods exported from `client`.
This involves a slight refactor of how the release limit error catching happens, but means a lot of the types for actions can be removed and replaced with uses from client.
Updated and adding in more test coverage to `createReleaseOperationsStore.test` to cover limit testing and test that the client is being called with the correct method and args.
The E2Es that test around creating releases still pass too.
Also manually tested the various release and version flows to ensure there are no regressions.
Would appreciate if when reviewing you could also give a whirl through a few flows to make sure there aren't any fails
N/A
> refactor: use release version actions client

- packages/sanity/src/core/releases/store/__tests__/createReleaseOperationsStore.test.ts
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
Moves the revert handler from creating individual requests to create a new version for each document, to a single API call with an array of `sanity.action.document.version.create` actions
Updated the existing tests
N/A
> refactor: createReleaseOperationsStore uses action client for version creation when reverting release

- packages/@sanity/cli/templates/app-quickstart/src/App.tsx
- packages/@sanity/cli/templates/app-sanity-ui/src/App.tsx
Removes the named export from SDK app templates. The `getEntryModule` file [expects a default export](https://github.com/sanity-io/sanity/blob/1adedb59f02c0f6bf47dc45f424e023a6755341c/packages/sanity/src/_internal/cli/server/getEntryModule.ts#L33). This is also aligned with a vanilla Vite app. 
Probably the easiest way to test this is to make the same change in a local app template app (created via `npx sanity@latest init --template app-quickstart`) and match the generated files to this change.
N/A
> fix(cli): remove named export from SDK application templates

- packages/sanity/.eslintrc.cjs
- packages/sanity/src/_internal/manifest/extractWorkspaceManifest.tsx
- packages/sanity/src/_internal/manifest/manifestTypes.ts
- packages/sanity/test/manifest/extractManifest.test.ts
This exposes the `mediaLibrary` config from the workspace when extracting the studio manifest.
We just pull the full `mediaLibrary` property from the workspace config into the manifest. I assume this is fine, it only include a `enabled` boolean for now but might include more information later.
- Run the `sanity manifest extract` command
- Verify that `dist/static/create-manifest.json` includes the `mediaLibrary` property in the workspace config
n/a
> chore(manifest): add media library config to extracted manifest

- dev/tsconfig.dev.json
Using `import "groq"` _inside_ the monorepo caused strange errors (`groq__default.default is not a function`) because we had an incorrect path in `tsconfig.json`. This changes that.
That the dev studios still work.
Not required.
> chore: use correct path for "groq" package

- dev/test-studio/plugins/input/auto-close-brackets-plugin.tsx
- dev/test-studio/plugins/input/wave-plugin.tsx
- dev/test-studio/schema/standard/portableText/customPlugins.tsx
- packages/@sanity/types/src/schema/types.ts
- packages/sanity/src/core/config/form/types.ts
- packages/sanity/src/core/form/form-components-hooks/picks.ts
- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/Plugins.tsx
- packages/sanity/src/core/form/types/blockProps.ts
- packages/sanity/src/core/form/types/definitionExtensions.ts
- packages/sanity/src/core/form/types/inputProps.ts
Introduces `components.pte.plugins` property to the system, allowing users to define custom pte plugins.
They can be defined in a plugin or in schemas
When multiple plugins are defined, they will be all inserted as long as each new plugin keeps expanding on the rest by using the `props.renderDefault(props)` function.
```ts
components: {
pte: {
plugins: (props) => {
return (
<>
{props.renderDefault(props)}
<AutoCloseBracketsBehaviorPlugin />
</>
)
},
```
> feat(core): pte plugins middleware components

- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/ObjectBlock.spec.tsx
From testing, it seems that the chromium browser can intermittently trigger a unfocus event briefly after the focus has been changed from a keyboard event. This meant the test in this PR that uses Tab and Esc to navigate was becoming increasingly flakey.
By moving to testing just by using mouse clicks, the test is made more robust
N/A
> test: refactor ObjectBlock tests to use clicks instead of Tab navigation to fix issue with focus in chromium

- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
Fix issue where an unpublished document preview was showing up as "Untitled" in the release detail page
Before:
After (previous version in the perspective stack has the value "Kayla's version") :
- As left in the comments: when there is only the published + drafts combo (no previous version), it will show the preview for the draft. This follows through with the behaviour in other parts of the studio (like the document list items preview)
Existing tests should suffice
manually:
Go to any version document that has a published version and select unpublish on release in the document actions.
When viewing the release in the detail page, the preview shouldn't be untitled and show instead show the previous document preview based on the perspective stack
The preview of documents slated for …
> fix(core): fix issue where document for unpublished should show the preview for the published document and not untitled

- packages/sanity/src/structure/panes/documentList/DocumentListPane.tsx
Fixes #9480
Fixes a regression introduced by #5893 reported in #9480
This behavior actually has two separate causes:
1. Popover trashes the children DOM when switching between enabled/disabled
2. `connected` state is flipped when setting up a new eventsource listener (which happens as you type).
The second can be fixed in a better way (e.g. by tracking whether we're "re-issuing" the listener connection), but 1. will still be an issue, so figured we just remove the popover for now and allow typing even when the listener is not connected.
- The issue reported in #9480 should no longer be possible to repro
- fixes a regression in v3.89.0 that caused the search input in document list to lose focus while typing
> fix(structure): make document list search interactive when not connected

- packages/@sanity/cli/templates/app-quickstart/src/ExampleComponent.css
Added a media query to disable the wave animation when the user has enabled the "prefers-reduced-motion" setting in their operating system. This improves accessibility by respecting user preferences for reduced motion, which can help prevent discomfort for users with vestibular disorders or motion sensitivity.
- Check that the animation is properly disabled [when the "prefers-reduced-motion" setting is enabled](https://developer.chrome.com/docs/devtools/rendering/emulate-css#emulate_css_media_feature_prefers-reduced-motion)
- Verify that the animation still works normally for users without this setting
- Ensure the CSS selector properly targets the avatar container's after pseudo-element
Tested by toggling the "prefers-reduced-motion" setting in the operating system and browser developer …
> fix(cli): respect prefers reduced motion for SDK template

- packages/@sanity/cli/src/actions/init-project/templates/appQuickstart.ts
- packages/@sanity/cli/src/actions/init-project/templates/appSanityUi.ts
Updated the SDK dependencies in the app templates to use version 2 instead of version 1. This change updates both `@sanity/sdk` and `@sanity/sdk-react` from `^1` to `^2` in the appQuickstart and appSanityUi templates.
- Verify that the version bump from `^1` to `^2` is appropriate for both SDK packages
- Check that the templates will work correctly with the updated SDK versions
- Ensure there are no compatibility issues with other dependencies in the templates
Tested by creating new projects with these templates and verifying that they initialize correctly with the updated SDK versions.
Updated the SDK dependencies in app templates to use version 2. New projects created with the CLI will now use `@sanity/sdk` and `@sanity/sdk-react` version 2.
> chore(cli): update SDK templates to version ^2

- .github/workflows/e2e.yml
In some cases the preview url is not generated, in those cases the e2e tests will fail. 
This introduces a error when the preview url is not found and also warns about the use case that we have found for this to fail.
Seems that using  double quotes `""` on the pr title will make the vercel deploy action to fail.
See this [fail](https://github.com/sanity-io/sanity/actions/runs/15228095248/job/42832590430?pr=9493) and [this one](https://github.com/sanity-io/sanity/actions/runs/15188414156/job/42714856054?pr=9472)
Updating the titles fixed it, so now developers will be warned about it.
> chore(actions): fail e2e tests if no preview url is found

- packages/@sanity/schema/src/legacy/Schema.ts
- packages/@sanity/types/src/schema/types.ts
- packages/sanity/src/_internal/cli/actions/graphql/extractFromSanitySchema.ts
- packages/sanity/src/core/schema/createSchema.ts
- packages/sanity/src/core/validation/inferFromSchema.ts
This changes the internal representation of `Schema` to also support a "parent schema". We're using this to build a schema containing the built-in types once, and then each workspace's schema has this schema as a parent. This has a bunch of nice properties:
- We end up only validating/parsing the built-in types once. We also end up reusing the type objects.
- It's now easy to determine the local types defined in a schema (`getLocalTypeNames()`) as opposed to ones that are built-in.
The main purpose of this is in the context of serialized schema. In this world we'd like to serialize the built-in schema separately from the custom schema. Without this work there's no clean way of 
This changes the internal representation of `Schema`. Some questions I'm wondering:
- Are there other parts of …
> feat(schema): place builtin types in a separate registry

- packages/sanity/src/core/field/diff/components/DiffTooltip.tsx
- packages/sanity/src/core/field/diff/components/constants.ts
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/store/events/getDocumentAtRevision.ts
- packages/sanity/src/core/store/events/getDocumentChanges.ts
- packages/sanity/src/core/store/events/getInitialFetchEvents.ts
- packages/sanity/src/core/store/events/types.ts
- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/inspectors/changes/EventsInspector.tsx
In some scenarios, according to users retention policy the events are removed.
Parts of the internal implementation on how to show the diffs and pull the transactions depend on this initial created event, but given transactions are removed after certain period of time the creation event is also removed.
This PR adds some changes to include a new event of the type `history-cleared` this will be added when there are no other events but we have access to some transactions and we want to show a diff to users.
When using the initial event in the from we will use the last published document as the document to compare against, that is what most users are expecting and what is more useful to show.
This same comparison with published view will show when there is any error fetching the events.
| …
> feat(core): add history cleared event and compare to published

- packages/@sanity/schema/src/legacy/types/any.ts
- packages/@sanity/schema/src/legacy/types/array.ts
- packages/@sanity/schema/src/legacy/types/blocks/block.ts
- packages/@sanity/schema/src/legacy/types/blocks/span.ts
- packages/@sanity/schema/src/legacy/types/boolean.ts
- packages/@sanity/schema/src/legacy/types/constants.ts
- packages/@sanity/schema/src/legacy/types/crossDatasetReference.ts
- packages/@sanity/schema/src/legacy/types/date.ts
- packages/@sanity/schema/src/legacy/types/datetime.ts
- packages/@sanity/schema/src/legacy/types/email.ts
- packages/@sanity/schema/src/legacy/types/file.ts
- packages/@sanity/schema/src/legacy/types/globalDocumentReference.ts
- packages/@sanity/schema/src/legacy/types/image.ts
- packages/@sanity/schema/src/legacy/types/number.ts
- packages/@sanity/schema/src/legacy/types/object.ts
- packages/@sanity/schema/src/legacy/types/reference.ts
- packages/@sanity/schema/src/legacy/types/string.ts
- packages/@sanity/schema/src/legacy/types/text.ts
- packages/@sanity/schema/src/legacy/types/url.ts
- packages/@sanity/schema/src/legacy/types/utils.ts
This adds a new property (`_internal_ownProps`) on each `SchemaType`. This contains only the properties which was defined on _this_ specific type and _not_ the parent properties inherited from the super type. Without this it's impossible to know if a property on a type is defined there or inherited from the parent. This is intended to be used when serializing the schema as there we'd like to only serialize the properties where they are _defined_. 
Make sure that this doesn't accidentally break anything. This is supposed to be 100% backwards compatible and not change the existing schema type in any way.
No manual testing. Currently trusting the CI.
Not required.
> feat(schema): introduce internal own props on each type

- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/components/CreateReleaseMenuItem.tsx
The new `releases.limit` configuration option can be used to prevent Studio users creating releases if the number of active releases in the dataset has reached the configured limit.
Other workspaces may have a different limit configured, and users are still able to create releases using the HTTP API directly. This is a purely client-side guard intended to help control release usage across an organisation.
- The "create new release" action.
- Whether there are any other surfaces that allow release creation in Studio that we've missed.
- Tested with various limits configured across workspaces.
The new `releases.limit` configuration option can be used to prevent Studio users creating releases if the number of active releases in the dataset has reached the configured limit. This is a purely …
> feat(sanity): add workspace release count limit

- packages/@sanity/types/src/validation/types.ts
- packages/sanity/src/core/validation/Rule.ts
This is purely a type fix: The definition of `RuleSpec` was actually wrong. The `constraint` field _can_ be set to a FieldReference in some cases. However, when invoking a validator, then we turn every field reference into a concrete value. 
N/A.
Not required.
> chore(schema): fix internal typing of RuleSpec and FieldReference

- packages/sanity/src/presentation/document/LocationsBanner.tsx
- packages/sanity/src/presentation/document/PresentationDocumentHeader.tsx
- packages/sanity/src/presentation/useDocumentLocations.ts
This PR fixes an issue ([reported in the community Slack](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1747127158130599)) where document locations state was being incorrectly resolved when multiple instances of a Presentation tool were resolving locations for the same document type. In those situations, location state would be duplicated from that returned from the first resolver across any subsequent location state representations in the UI.
In the screenshot below, `First Instance: Page Title` is incorrectly shown in the resolved locations for the second instance of the Presentation tool.
After this change, the location would show correctly as below:
The `useDocumentLocations` hook has also been refactored and simplified to use the document preview store. It now uses the store's …
> fix(presentation): fix multiple resolver document location state

- packages/sanity/src/core/preview/useValuePreview.ts
- test/e2e/tests/releases/displayDocument/DisplayedDocument.spec.ts
Fixes issue where the preview of a document that is slated for unpublished shows the wrong preview
Before
After
Check the code
Automated test should suffice.
Otherwise, put a version to unpublish and double check that the document title appears as expected
Or you can go to [this document](https://test-studio-git-sapp-2635-follow-up.sanity.dev/test/structure/species;cb97aa56-63db-43f5-ae84-809d8ec93d5f?perspective=rooVsdzKz) 
The document displayed of a version that will be unpublished within a release will show the right title
> fix(core): add condition in useDocumentTitle to allow for unpublished preview title

- packages/sanity/src/_internal/cli/actions/dev/devAction.ts
The [question for upgrade ](https://github.com/sanity-io/sanity/pull/9153/files#diff-bb8ffbe21f9725c6a83f4eed919e1215bff20eb65b73b9ffc4630b85850a2e9c) when using an autoupdate studio blocks the dev command when used in non interactive environments, like when running inside a pnpm workspace with `pnpm dev --filter=studio`
This PR uses the `isInteractive` check and skips the question if it is non interactive.
fixes an issue in where the studio dev command will get blocked if using auto update in a non interactive environment.
> fix(cli): check if is interactive before prompting to upgrade

- .github/workflows/pr-cleanup.yml
- package.json
- test/e2e/envVars.ts
- test/e2e/scripts/cleanup.ts
- test/e2e/scripts/cleanupPr.ts
- test/e2e/scripts/e2eClient.ts
- test/e2e/scripts/setup.ts
Partially reverts #9479 to bring back the cleanup script that runs on PR close and deletes the dataset associated with the PR.
I'm leaving the "delete old datasets" script with a note that it can later be adjusted to use the GH api to periodically (e.g. twice a day) check against open/closed PRs and delete datasets for PRs that has been closed, which would be a better solution.
The cleanup workflow should remove the dataset created by e2e tests for this PR
n/a
> chore(ci): run dataset cleanup for individual pull requests

- .github/workflows/cli-test.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/release-latest.yml
- .github/workflows/release.yml
- lerna.json
- package.json
- pnpm-lock.yaml
Sets up release automation for packages in this repo.
Consists of two workflows:
- [create-release-pr.yml](https://github.com/sanity-io/sanity/blob/release-automation/.github/workflows/create-release-pr.yml): triggers on commits to main and maintains a PR with version bumps and changelog edits based on the unreleased commits in `main`, using conventional commits to guide version increments
- [release-latest.yml](https://github.com/sanity-io/sanity/blob/release-automation/.github/workflows/release-latest.yml): triggers when the release PR is merged to main, performs the publish to npm, and tags the version.
You can see an example of a release PR here: https://github.com/sanity-io/sanity/pull/9541 and a dry run of the workflow that triggers on release PR merge here: …
> chore(ci): set up release automation

- .github/workflows/create-release-pr.yml
Fixes a silly mistake that caused the "Create Release PR" workflow to run on the version commit that did the release. Triggering a new release PR with the changes that just got released.
> fix(ci): skip creating release pr for release commit

- packages/sanity/src/_internal/cli/util/packageManager/upgradePackages.ts
fixes #9544
`npm upgrade` doesn't accept exact versions of packages, see report in #9544 
This changes the command we run so it uses `npm install package@version` instead.
- A bit tricky to test, but can be tested by installing the pkg.pr.new version of the `sanity`-package built from this PR and pinning `@sanity/vision` to an older version in an auto-updating studio. Then, `npm run dev --yes` should run the npm command successfully.
- fixes wrong npm command being invoked when prompted to update local versions in Auto-updating Studios
> fix(cli): use correct npm command for upgrading

- lerna.json
Seeing an error when running `lerna version` that only happens in the github container (reported here: https://github.com/lerna-lite/lerna-lite/issues/1061). Enabling debug logging for lerna lite to get more details.
> chore(ci): set lerna loglevel=debug

- .github/workflows/pkg-pr-new.yml
- packages/sanity/src/_internal/cli/util/packageManager/upgradePackages.ts
Passes the [--pnpm arg](https://github.com/stackblitz-labs/pkg.pr.new#:~:text=also%20use%20the-,%2D%2Dpnpm,-or%20%2D%2Dyarn%20flag) to pkg.pr.new which makes it use `pnpm pack` instead of `npm pack`. Since it's currently using `npm pack`, `workspace:` protocol won't be replaced with the local version during publish, which means any attempt at installing a pr-version with npm will fail with the error: `npm error code EUNSUPPORTEDPROTOCOL`.
the package published from this PR should be possible to install using npm (I've verified already)
installing the pr release using npm should work
n/a
> fix(ci): use pnpm for pkg.pr.new

- packages/sanity/src/core/form/inputs/PortableText/object/modals/PopoverModal.tsx
Looks like #8849 introduced a regression/issue. In an upcoming version of React (available on `next@canary`, or on `next@stable` with for example `experimental.viewTransition: true`) `Fragment` components can have a [`ref`](https://github.com/facebook/react/blob/37054867c15a7381abe0f73d98f3fecd06da52da/fixtures/dom/src/components/fixtures/fragment-refs/FocusCase.js#L45).
So it's no longer safe to give `<FocusLock>` an `as={Fragment}` prop.
@jordanl17 do you recall the original reason why `as={Fragment}` where added, and if this PR might cause a regression?
Clone https://github.com/sanity-io/template-nextjs-personal-website and add this below `reactCompiler: true` in `next.config.ts`:
```
viewTransition: true,
```
Next, run `npm install && npm run dev` and open …
> fix: resolve `getAttribute` is not a function errors in PTE on next.js

- packages/sanity/src/core/components/timeZone/DialogTimeZone.tsx
When searching for timezones in the time zone modal, we were seeing that timezones that have spaces were not correctly being filtered in the list. This PR adds a custom `filterOption` on the `AutoComplete` function to make sure that it does the filtering correctly.
This allows you to search on all text that is shown in the rendering of the options in the timezone modal.
Give it a test if you want!
Bug fix for wrong filtering results for timezone modal.
> fix: fixing search for timezones

- dev/test-studio/plugins/input/auto-close-brackets-plugin.tsx
- dev/test-studio/plugins/input/wave-plugin.tsx
- dev/test-studio/sanity.config.ts
- dev/test-studio/schema/index.ts
- dev/test-studio/schema/standard/portableText/customPlugins.tsx
- dev/test-studio/structure/constants.ts
- packages/@sanity/types/src/schema/types.ts
- packages/sanity/src/core/config/form/types.ts
- packages/sanity/src/core/form/form-components-hooks/picks.ts
- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
- packages/sanity/src/core/form/inputs/PortableText/object/Plugins.tsx
- packages/sanity/src/core/form/types/blockProps.ts
- packages/sanity/src/core/form/types/definitionExtensions.ts
- packages/sanity/src/core/form/types/inputProps.ts
**UPDATE**: @pedrobonamin has made subsequent commits to the branch which lets PTE (Portable Text Editor) plugins be configured under `form.components.portableText.plugins`:
```ts
export const autoCloseBrackets = definePlugin({
name: 'auto-close brackets',
form: {
components: {
portableText: {
plugins: (props) => {
return (
<>
{props.renderDefault(props)}
<AutoCloseBracketsBehaviorPlugin />
</>
)
},
},
},
},
})
```
The improved API makes sure that plugins are added recursively so a Studio plugin like the one above can add a PTE plugin and then a document-level array field config further down can add its own and in the end, both will be registered in PTE:
```ts
/**
* One-Line Editor
*
* Uses the `OneLinePlugin` to restrict the editor to one line of text.
*/
{
type: 'array',
name: …
```
> feat(core): allow configuring PTE plugins

- packages/sanity/src/core/index.ts
- packages/sanity/src/core/perspective/navbar/GlobalPerspectiveMenu.tsx
- packages/sanity/src/core/perspective/navbar/GlobalPerspectiveMenuItem.tsx
- packages/sanity/src/core/perspective/navbar/ReleaseTypeMenuSection.tsx
- packages/sanity/src/core/perspective/navbar/ReleasesList.tsx
- packages/sanity/src/core/perspective/navbar/ReleasesNav.tsx
- packages/sanity/src/core/perspective/navbar/__tests__/ReleasesNav.test.tsx
- packages/sanity/src/core/perspective/navbar/currentGlobalPerspectiveLabel.tsx
- packages/sanity/src/core/perspective/types.ts
- packages/sanity/src/core/studio/components/navbar/StudioNavbar.tsx
- packages/sanity/test/__snapshots__/exports.test.ts.snap
This PR takes some steps to make the `ReleasesNav` component shareable, as it's a very useful component to use outside of the nav bar.
For example, here's an upcoming piece of work that uses it in a banner:
In the future, we should consider moving the files to a different directory.
- The new export.
- The new `menuItemProps` prop, which allows consumers to customise the props of each menu item. The screenshot above demonstrates this being used to make release menu items inactive if a new document cannot be created within.
Existing tests passing.
> feat(sanity): make `ReleasesNav` shareable

- .github/workflows/e2e.yml
Fixes Vercel deployment failure when PR titles contain double quotes.
Vercel deployments were failing when PR titles contained double quotes. The issue was caused by improper shell quoting in the GitHub Actions workflow.
**Root Cause**
The commit message parameter was being passed directly to the shell command without proper escaping:
```bash
-m githubCommitMessage="${{ github.event.head_commit.message || github.event.pull_request.title }}"
```
When a PR title like `refactor(sanity): move "create release" menu item` was used, it would break the shell parsing, causing the deployment to fail.
[This was reported here to vercel and this was their response
](https://github.com/vercel/vercel/issues/13378)
>I think this is a shell quoting issue with your GitHub Actions workflow where the " is …
> fix(actions): Vercel deployment failure when PR titles "contain" double quotes

- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Annotations.spec.tsx
This reverts commit 978176faa983e8f95d056a7e4f780ae13850811b.
Tests are now (somewhat) stable again due to an upstream PTE bugfix.
> test: revert #9632

- .github/workflows/docReport.yml
- .github/workflows/e2e.yml
- .github/workflows/efps.yml
A small little quality of life improvement:  our GitHub workflows that comments on PRs now creates a placeholder comment immediately and then update the comment when it’s done doing its work. This should reduce the oncoming stream of interruptions for those of us that have notifications enabled for github comments.
The workflow changes. This PR shows the order of which the comments appear. Here's a screenshot taken right after opening this PR:
> chore(ci): add placeholder comments to workflows

- packages/@sanity/cli/src/cli.ts
- packages/sanity/src/_internal/cli/util/getStudioWorkspaces.ts
During schema extraction, we were previously attempting to set the `message` property of an unknown caught value. We have received a couple of reports indicating an object is caught with only a getter defined for the `message` property, causing an error to be thrown when we attempt to set it, and thus concealing the underlying error.
This branch makes two changes to improve the situation:
1. Throws a new error with a cause, rather than attempting to manipulate the caught value.
2. Adds error cause reporting in the CLI runner's catch clause.
Note that I have not added recursive unfolding of error cause; only the outermost cause will be reported. This seems pragmatic given the CLI is currently being redeveloped.
We can see an example of this by throwing a contrived error object:
```
class …
```
> fix(sanity): avoid writing to message property of unknown caught value

- .oxlintrc.json
Some rules set to `warn` still triggers when running `--fix`, this wasn't the intention when landing #9629. This PR dials it back a bit so we can handle it properly.
Enough inline context?
We have to merge before the bot reruns and we know for sure it's fixed.
N/A
> chore: reduce lint:fix noise

- .prettierignore
- packages/sanity/src/core/field/types/portableText/diff/helpers.ts
- packages/sanity/src/router/RouteScope.tsx
- packages/sanity/src/router/_resolveStateFromPath.ts
There are still some adverse effects [to running `pnpm lint:fix`](https://github.com/sanity-io/sanity/pull/9667), this PR handles them, without running `pnpm lint:fix` on unrelated files (so we can test the bot).
[The failures where specifically](https://github.com/sanity-io/sanity/actions/runs/15685812311/job/44188587212?pr=9667):
```bash
Error: sanity:build: [error] src/core/field/types/portableText/diff/helpers.ts:360:28 - TS7006: Parameter 'cld' implicitly has an 'any' type.
Error: sanity:build: [error] src/router/RouteScope.tsx:136:25 - TS2698: Spread types may only be created from object types.
Error: sanity:build: [error] src/router/_resolveStateFromPath.ts:71:5 - TS2698: Spread types may only be created from object types.
Error: sanity:build: [error] …
```
> chore: fix issues by `pnpm lint:fix`

- package.json
- packages/sanity/package.json
- perf/efps/package.json
- perf/tests/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Seeing a really weird issue when trying to [bump playwright](https://github.com/sanity-io/sanity/pull/9673), the kanji test seems to [always fail](https://github.com/sanity-io/sanity/actions/runs/15700381266/job/44239828478):
```bash
Call Log:
- Timeout 30000ms exceeded while waiting on the predicate
37 |     // Enter initial text and wait for the mutate call to be sent
38 |     await field.fill(kanji)
> 39 |     await expect.poll(getRemoteValue, {timeout: 30_000}).toBe(kanji)
```
Maybe we can avoid this issue by bumping to `1.52` instead of `1.53` 🤞 
Makes sense?
If tests pass 🤞 🤞 🤞 
N/A
> chore(deps): bump playwright to 1.52 and use pnpm catalog

- packages/sanity/package.json
- pnpm-lock.yaml
When renovate [tries to bump `@tanstack/react-virtual` we have tests consistently failing](https://github.com/sanity-io/sanity/pull/9661). This PR pins `@tanstack/react-virtual` to the current working version according to our `pnpm-lockfile.yaml`, which is the version we've been testing on the monorepo for the last few months.
It buys us time to get to the bottom of the issue, and ensures userland don't pull in a potentially buggy version.
Makes sense?
Tests should pass just as on `main`.
N/A
> fix(deps): pin react-virtual to v3.13.2

- packages/sanity/package.json
- pnpm-lock.yaml
Draft PR to triage which exact version is causing tests to fail. [Diff of changes](https://npmdiff.dev/%40tanstack%2Fvirtual-core/3.13.5/3.13.6/)
> fix(deps): bump react virtual to v3.13.6

- .gitignore
- .vscode/extensions.json
Now that we use oxlint it can be confusing that if you search for `oxlint` on VS Code extensions you won't find anything, as the extension you need is called `oxc`.
To make it easier to see what extensions help you when working on the monorepo I'm adding a recommended list (it works with the VS Code derivatives, like Cursor, not just strictly VS Code).
While at it I've added some other extensions that are really helpful and might not be obvious that they exist.
Are there more extensions we want to add while at it?
Open the monorepo on this branch in your IDE, you should see a prompt in the bottom left corner like this:
You should also be able to filter extensions by `@recommended` to see the full list:
N/A
> chore(monorepo): add recommended extensions list to improve DX

- packages/sanity/src/core/i18n/bundles/copy-paste.ts
- packages/sanity/src/core/studio/copyPaste/CopyPasteProvider.tsx
Update error messages on both copy and paste when the browser doesn't allow for the action.
On paste, we are narrowing down to that specific error (while still throwing if any other error comes) but for this in particular it will no longer the an uncaught exception
You can go to your browser and change the settings for the clipboard to blocked (in arc you need to go to settings, advanced settings and find clipboard for sanity)
Updates error message to be more helpful when copy pasting is being blocked in the studio due to lack of permissions.
> fix(core): update error tooltip for copypaste

- .github/workflows/release-next.yml
Realized after merging #9654 that since we bump and publish packages in the same operation, uploaded modules will not get the right version. Moving the bundle uploading to after version bump + npm release instead. As noted in a comment,        ideally, the flow here should be 1) bump packages using `lerna version`, 2) upload to module cdn, 3) publish packages to npm using `lerna publish from-packages`, but think it's less important for `next`-releases. This won't be an issue for the workflow that publishes to `latest`, since packages already have been bumped when that happens.
Tricky to test, but we'll se if it works after merging :)
N/a
> fix(ci): upload modules after releasing next

- dev/studio-e2e-testing/README.md
- packages/@sanity/cli/src/actions/init-project/initProject.ts
- packages/@sanity/cli/templates/blog/README.md
- packages/@sanity/cli/templates/clean/README.md
- packages/@sanity/cli/templates/ecommerce/README.md
- packages/@sanity/cli/templates/get-started/README.md
- packages/@sanity/cli/templates/moviedb/README.md
- packages/@sanity/cli/templates/quickstart/README.md
- packages/sanity/README.md
Readme's had the correct community link for Discord, but outdated link text.
> chore: update slack to discord in readmes

- packages/sanity/src/core/store/_legacy/document/isNewDocument.test.ts
- packages/sanity/src/core/store/_legacy/document/isNewDocument.ts
Some small refinements around the `isNewDocument` function, based on the feedback shared in #9734.
> feat(sanity): refine `isNewDocument`

- dev/test-studio/sanity.config.ts
- packages/@sanity/types/src/assets/types.ts
- packages/sanity/src/core/form/inputs/files/FileInput/FileAsset.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FileInput.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FileInputAssetSource.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/FilePreview.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/__tests__/fileInput.test.tsx
- packages/sanity/src/core/form/inputs/files/FileInput/types.ts
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInput.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAsset.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAssetMenu.tsx
- packages/sanity/src/core/form/inputs/files/ImageInput/ImageInputAssetSource.tsx
- packages/sanity/src/core/form/inputs/files/common/UploadDestinationPicker.tsx
- packages/sanity/src/core/form/inputs/files/common/UploadPlaceholder.tsx
- packages/sanity/src/core/form/studio/assetSourceDataset/createAssetSource.tsx
- packages/sanity/src/core/form/studio/assetSourceDataset/uploader.ts
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/createAssetSource.tsx
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/hooks/usePluginPostMessage.ts
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/shared/MediaLibraryAssetSource.tsx
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/shared/UploadAssetDialog.tsx
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/uploader.ts
- packages/sanity/test/form/renderFileInput.tsx
This will improve subscription and state handling in Media Library uploading from the File and Image input.
It also changes how the AssetSourceUploader is initialized. Previously, it was initialized on the asset source level and shared across the various inputs using it. This made uploading to multiple fields in parallel more challenging. It's safer and easier to have the uploader instance in the field itself, encapsulating everything for that field without worrying about subscribers to the uploader in other fields.
This fixes a critical bug where an upload in a field could overwrite adjacent image and file fields in that document.
There are still things to improve here, but I think this should be done in a more holistic approach later.
That the code changes look all right.
A schema like …
> fix(core): fix issues with ML uploads

- packages/sanity/package.json
- pnpm-lock.yaml
Fixes #9774, the `scrollmirror` dependency is no longer GPL, it's MIT, so we can use it with a standard semver range once again 🥳 
It makes sense?
If the is green we're good 👍 
Fixes an issue where a dependency of `sanity` could get flagged as GPL licensed in license scanners. The dependency is `scrollmirror`, and the author @hirasso have gracefully relicensed it as MIT for us 💖
> fix(deps): unpin `scrollmirror` now that it's MIT licensed

- packages/sanity/src/core/form/inputs/PortableText/text/constants.ts
Before this change, a numbered list item indented to the 10th level would have count `0`. Now, it has the correct count, `1`.
Before:
After:
Try it out!
n/a
The Portable Text Editor now displays the correct list count for numbered list items outdented to the 10th level.
> fix(core): add 10th text level in PTE

- packages/sanity/src/core/form/inputs/PortableText/Editor.styles.tsx
Calculating the correct list index using CSS is extremely tricky. Therefore, PTE now ships a `data-list-index` on each list block (a block with both `listItem` and `level`) by default. (Notice how the blocks now also have `data-level` as well.)
While a "list index" isn't a part of the stored Portable Text nor the protocol itself, it's universally understood that a block with `listItem` and `level` *is* a list item. At the same time, we want to make it as seamless as possible to adopt and style the Portable Text Editor, and thus, `data-list-index` came into play.
Under the hood, PTE does an efficient calculation of where a list block is positioned in its current list. This not only simplifies the CSS needed to keep track of the CSS counters. It also fixes tricky edge cases like this one: …
> fix(core): use `data-list-index` on PTE blocks to improve list counts

- packages/@repo/test-dts-exports/test/fixtures/@sanity.cli.test-d.ts
- packages/@repo/test-dts-exports/test/fixtures/sanity.cli.test-d.ts
- packages/@sanity/cli/src/cliClient.ts
Follows up on #9826 and the generated typings of getCliClient.
The source of `getCliClient` [is](https://github.com/sanity-io/sanity/blob/de51f4535d9b3d059a359c90f101ca6884ca2764/packages/%40sanity/cli/src/cliClient.ts#L16-L61):
```ts
export function getCliClient(options: CliClientOptions = {}): SanityClient {
// ...
}
/**
* @internal
* @deprecated This is only for INTERNAL use, and should not be relied upon outside of official Sanity modules
* @returns A token to use when constructing a client without a `token` explicitly defined, or undefined
*/
getCliClient.__internal__getToken = (): string | undefined => undefined
```
Though `getCliClient.__internal__getToken` has a `@internal` tag and other doc blocks it's lost during dts generation, looking at `./@sanity/cli/lib/index.d.ts` shows: …
> refactor: improve generated typings for `getCliClient`

- .github/workflows/create-release-pr.yml
- .github/workflows/pkg-pr-new.yml
- .github/workflows/release-latest.yml
- .github/workflows/release-next.yml
- dev/test-create-integration-studio/package.json
- test/e2e/scripts/cleanup.ts
After merging the new check for `packageManager` we have some GitHub actions that are failing:
- https://github.com/sanity-io/sanity/actions/runs/15968782681/job/45035024167
- https://github.com/sanity-io/sanity/actions/runs/15968782693/job/45035024276
Did I miss anything?
Not sure we can test without merging to main.
N/A
> chore: fix `npx` sites that failed after adding packageManager checks

- packages/sanity/src/core/components/documentStatus/DocumentStatus.tsx
- packages/sanity/src/core/components/documentStatusIndicator/DocumentStatusIndicator.tsx
- packages/sanity/src/core/config/configPropertyReducers.ts
- packages/sanity/src/core/config/prepareConfig.tsx
- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/perspective/GlobalPerspectiveProvider.tsx
- packages/sanity/src/core/perspective/PerspectiveProvider.tsx
- packages/sanity/src/core/perspective/isPerspectiveWriteable.ts
- packages/sanity/src/core/perspective/navbar/GlobalPerspectiveMenuItem.tsx
- packages/sanity/src/core/perspective/navbar/PerspectiveLayerIndicator.tsx
- packages/sanity/src/core/perspective/navbar/ReleasesList.tsx
- packages/sanity/src/core/perspective/useSetPerspective.tsx
- packages/sanity/src/core/releases/hooks/__tests__/utils.test.ts
- packages/sanity/src/core/releases/hooks/utils.ts
- packages/sanity/src/structure/components/paneHeaderActions/PaneHeaderActions.tsx
- packages/sanity/src/structure/components/paneHeaderActions/PaneHeaderCreateButton.tsx
- packages/sanity/src/structure/components/paneItem/helpers.tsx
- packages/sanity/src/structure/diffView/versionMode/components/VersionModeHeader.tsx
- packages/sanity/src/structure/hasObsoleteDraft.test.ts
- packages/sanity/src/structure/hasObsoleteDraft.ts
- packages/sanity/src/structure/hooks/useDocumentIdStack.ts
- packages/sanity/src/structure/i18n/resources.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/ChooseNewDocumentDestinationBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/ObsoleteDraftBanner.tsx
- packages/sanity/src/structure/panes/document/documentPanel/header/perspective/DocumentPerspectiveList.tsx
This branch introduces the `document.drafts.enabled` configuration option for controlling whether the draft model is enabled. By default, this option is `true`.
[Video walkthrough](https://supercut.ai/share/ash/DlDFlTPlQyfkgITZk5_lTa).
When the draft model is switched off:
- Studio will display the published perspective by default.
- The drafts (latest) perspective is removed from the global perspective switcher.
- The drafts chip is removed from the document version chips.
- Draft documents are not shown in the document comparison view.
- Draft documents will not be loaded in document lists.
- Draft document status indicators will not appear in document previews.
If the user views a document that has an obsolete draft, they are presenting with a banner allowing them to compare it, and …
> feat(sanity): allow draft model to be switched off

- packages/sanity/src/_internal/cli/actions/app/devAction.ts
- packages/sanity/src/_internal/cli/actions/dev/devAction.ts
- packages/sanity/src/_internal/cli/server/devServer.ts
This PR refactors the dev server startup process to pass the spinner instance to the `startDevServer` function, allowing it to control when the spinner succeeds. This change ensures the spinner is closed at the appropriate time after the server has fully started.
- Check how the spinner is now passed from both `devAction.ts` and `appDevAction.ts` to the `startDevServer` function
- Review the updated type definition in `getDevServerConfig` to omit the spinner from the returned options
- Verify that the spinner is now closed inside the `startDevServer` function after the server has started
Tested by running both `sanity dev` and `sanity app dev` commands to ensure the spinner behavior works correctly in both contexts.
N/A
> fix(cli): fixes dev command message

- packages/@sanity/cli/src/CommandRunner.ts
- packages/@sanity/cli/src/util/printNewMajorMessage.ts
- packages/@sanity/cli/test/dataset.test.ts
- packages/@sanity/cli/test/dev.test.ts
- packages/@sanity/cli/test/exec.test.ts
- packages/@sanity/cli/test/graphql.test.ts
- packages/@sanity/cli/test/init.test.ts
> [!NOTE]
> Copy approved by docs 
Add cli message warning of the upcoming major version (4) on every command
Should the style be different?
> [!Warning]
> A flag has been added but we don't want to make that be widely used (this will run for a very little time anyway), we want this in order to make the tests run smoothly since it is not something that should impact anything
This will be removed in 2 weeks once we have it out, no tests have been added. 
To manually test:
- open branch
- pnpm build
- ~/[path-to-monorepo-root]/packages/@sanity/cli/bin/sanity init (or any other command)
This will have to be aligned with docs for this release on how we want to say it. We might just want to add the same sort of messaging as we were given by docs
The `sanity` package is moving to v4 on July 15 …
> refactor(@cli): add new major version message 

- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
When copying or creating a new version document it will set the `_updatedAt` value to the moment of creation, rather to the previous `_updatedAt` showing an outdated value.
Copy a document to a version, the `_updatedAt` value should be the moment of copying.
Add a document to a version, the `_updatedAt` value should be the moment of creation.
> fix(core): set `_updatedAt` to the creation time in version documents

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/commands/functions/testFunctionsCommand.ts
- pnpm-lock.yaml
See: [RUN-610](https://linear.app/sanity/issue/RUN-610/do-not-automatically-pass-authenticated-token-to-functions-devtest)
The Sanity CLI does not automatically add the live user token to commands unless the user specifies it using the --with-user-token flag. This PR adds this flag to the sanity functions test command and a toggle switch to the dev server.
- Run the sanity functions test command with a function that prints out the context. You should not see context.clientOptions.token.
- Run the sanity functions test --with-user-token command with a function that prints out the context. You should see context.clientOptions.token.
- Fire up the dev server and test the some function toggling the "with token" switch.
> fix: add with user token option to functions test command

- .github/workflows/docReport.yml
- .github/workflows/efps.yml
Fixes issue seen here https://github.com/sanity-io/sanity/actions/runs/16075387820/job/45450694517?pr=9891
```
Run thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
Error: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#update-an-issue-comment
```
> fix(actions): add write permissions to actions

- packages/@sanity/schema/package.json
- packages/@sanity/schema/src/_exports/_internal.ts
- packages/@sanity/schema/src/descriptors/sync.ts
- packages/sanity/src/core/config/prepareConfig.tsx
- packages/sanity/src/core/config/types.ts
- packages/sanity/src/core/config/uploadSchema.ts
- pnpm-lock.yaml
This adds support for the Studio to automatically send the serialized schema when it loads (**when an environment variable is enabled**).
Probably run it locally and see that it behaves as expected?
I've tested this locally in the dev studio. I've verified that it works both in staging and the production workspace.
N/A. Not user facing yet.
> feat: synchronize schema to the server

- packages/sanity/src/core/components/hookCollection/defineHookStateComponent.tsx
Fixes https://github.com/sanity-io/sanity/issues/9863
This PR removes the cleanup step for the hook states that is happening on every change.
Now the following is happening:
-  Actions are rendered.
1) User types on input, 
2) This causes an update to `hookState`, triggering the cleanup part of the hook.
3) Actions are removed because of the state update, this happens immediately. And will schedule the [`requestSnapshotUpdate` ](https://github.com/sanity-io/sanity/blob/fix-action-flickering/packages/sanity/src/core/components/hookCollection/useHookCollectionStates.tsx#L75) function , but this function is [throttled ](https://github.com/sanity-io/sanity/blob/fix-action-flickering/packages/sanity/src/core/components/hookCollection/useHookCollectionStates.tsx#L53-L57) so it waits at least …
> fix(core): actions flickering- remove cleanup step for hook states on change

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/releases/hooks/useVersionOperations.tsx
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/plugin/documentActions/UnpublishVersionAction.tsx
- packages/sanity/src/core/releases/store/__tests__/__mocks/createReleaseOperationsStore.mock.ts
- packages/sanity/src/core/releases/store/__tests__/__mocks/useReleaseOperations.mock.ts
- packages/sanity/src/core/releases/store/__tests__/createReleaseOperationsStore.test.ts
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
Allow for a document that has been slated for unpublishing in a release to be returned to its original version state
https://github.com/user-attachments/assets/ee3fe5c2-16bc-41b8-9cf0-280b73d987a4
The code and especially if there is a different method we should use in the [createReleaseOperationStore.ts](https://github.com/sanity-io/sanity/compare/main...sapp-2837#diff-093681b737c63cd3c2db92540b2c90f7340c442f77ab4ac5f51b24649b206eb6)
Also any naming / method titles, suggestions are welcome
Added new automated tests
We now allow for versions that were slated for unpublishing in a release to be returned to its original version state
> feat(core): add way to revert unpublishing in a release

- .github/workflows/create-release-pr.yml
Currently, we are creating commit messages using the default from the github action:
But we really want to customise this - which this PR does.
Previously this was done by lerna-lite with `lerna version` where it would generate the commit, but now we have to generate that ourselves since we use lerna full.
N/A
> fix: add commit-message field to release PR workflow

- packages/@sanity/cli/test/tokens.test.ts
Remove unneeded tags that are adding noise to other PRs related to CLI
Tests should still pass
Tests should still pass
N/A
> test: remove flag from cli token tests

- .npmrc
We've been plagued [with strange install/build issues recently](https://vercel.com/sanity-sandbox/test-studio/G3nEaKuGVfJ8tanXUmbqkishypco?filter=errors):
```bash
@sanity/diff:build: /vercel/path1/node_modules/.pnpm/recast@0.23.9/node_modules/recast/parsers/babel.js:17
@sanity/diff:build:             throw new Error("Install @babel/parser to use the `typescript`, `flow`, or `babel` parsers");
@sanity/diff:build:                   ^
@sanity/diff:build: 
@sanity/diff:build: Error: Install @babel/parser to use the `typescript`, `flow`, or `babel` parsers
@sanity/diff:build:     at /vercel/path1/node_modules/.pnpm/recast@0.23.9/node_modules/recast/parsers/babel.js:17:19
@sanity/diff:build:     at Object.<anonymous> (/vercel/path1/node_modules/.pnpm/recast@0.23.9/node_modules/recast/parsers/bab …
```
> chore: fix vercel pnpm install issues with recast

- packages/sanity/src/core/releases/components/dialog/CreateReleaseDialog.tsx
- packages/sanity/src/core/releases/components/dialog/ReleaseForm.tsx
- packages/sanity/src/core/releases/components/dialog/TitleDescriptionForm.tsx
- packages/sanity/src/core/releases/components/dialog/__tests__/ReleaseForm.test.tsx
- packages/sanity/src/core/releases/components/documentHeader/dialog/CopyToNewReleaseDialog.tsx
- packages/sanity/src/core/releases/hooks/useReleaseFormStorage.ts
> [!NOTE]
> Highly suggest reviewing and merging #9862 before this for ease of testing
https://github.com/user-attachments/assets/a55bfc1e-27ea-4695-91d0-e2a274d624a0
You should still be able to write, delete, etc do much of anything as before on the dialog.
The form is saved:
- When you click outside of the dialog and close the dialog
The form is cleared (as well as localstorage)
- When the cross at the top of the dialog is clicked, 
- When the cancel button is used (in the copy release dialog)
Added some automated tests 
When clicking outside of the creating a release dialog, now the content will persist when re-opening the modal
> feat(core): keep values when clicking off create release modal

- package.json
- pnpm-lock.yaml
`conventional-changelog-conventionalcommits` v9.0.0+ are ES modules. Lerna 8.2.3 uses CommonJS, so need to pin `conventional-changelog-conventionalcommits` to v7.x.x which is still CommonJS-compatible.
N/A
> fix: pinning conventional-commits to v7 for CJS compatibility with lerna@8

- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/hooks/useLinkAssets.tsx
It is only possible to link a video asset from Media Library to the dataset after it has transitioned to a `"ready"` state. This was previously handled by polling the Media Library HTTP API to get the asset's state. Unfortunately, we later realised Media Library does not support CORS, and therefore is unusable for this purpose.
This branch changes the approach to simply attempt the linking process, retrying after a short delay if the linking failed because the asset isn't ready. Fortunately, this is a state we can identify based on the response to the linking request. The linking request is configured to retry every two seconds, with a maximum of ten retries. If multiple assets have been selected, linking will be executed with a concurrency of five.
Note: in the interest of expediency, I …
> fix(sanity): poll asset state after linking without failing cors

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/tool/components/releaseCTAButtons/ReleaseRevertButton/ReleaseRevertButton.tsx
[note: the red warning card in the screenshot has always been there if the history of the document has other translog entries]
* Does this adjusted copy make more sense that it's current state
* Any suggestions on how to make the staging process clearer for editors?
Improved clarity on the reverting process for content releases
> chore: adjusting copy for staging revert content release

- packages/sanity/src/core/releases/hooks/__tests__/useVersionOperations.test.tsx
- packages/sanity/src/core/releases/hooks/useVersionOperations.tsx
- packages/sanity/src/core/releases/store/__tests__/createReleaseOperationsStore.test.ts
- packages/sanity/src/core/releases/store/createReleaseOperationStore.ts
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/documentPanel/banners/DocumentNotInReleaseBanner.tsx
With the new version of sanity/client (7.8.0) it's now possible to pass a `baseId` to the `version.create` action rather than a `document`. This is the preferred approach as content lake will then find and create a new version of the provided `baseId`
(not sure if this is necessary for release notes, but added if it is):
Creating new versions of documents provides a `baseId` in the action call
> feat: swapping to use baseId for createVersion server actions

- packages/sanity/src/core/search/common/deriveSearchWeightsFromType2024.ts
- packages/sanity/src/core/search/groq2024/createSearchQuery.test.ts
Previously, configuring a preview selection that has no weighting mapped (e.g. `media`) would result in that field being boosted by `undefined` in the resulting GROQ query when performing a search for a cross dataset reference, which is invalid GROQ.
To resolve this issue, the weighting now falls back to `0`, which is ultimately omitted from the resulting GROQ query altogether because it's unnecessary to boost by a neutral value when using the groq2024 strategy.
Cross dataset reference search when the target schema has a `media` preview field selected.
- Tested in Test Studio.
- Added unit tests.
- Fixes cross dataset reference search issue affecting the groq2024 search strategy when the target schema type defined a `media` preview.
> fix(sanity): prevent undefined weights occurring in groq2024 search query

- packages/sanity/src/core/search/groq2024/createGroq2024Search.ts
It's no longer necessary to use the experimental GROQ API when using the `groq2024` search strategy is switched on, as the required functionality has now been rolled out to all stable GROQ API versions.
Searching with the `groq2024` strategy.
Tested in Test Studio, and verified existing tests pass.
The `groq2024` search strategy no longer uses the experimental GROQ API.
> feat(sanity): adopt stable GROQ API for `groq2024` search strategy

- .github/workflows/release-stable.yml
Adds a new workflow for releasing the stable tag.
This flow will accept a version semver and will:
1. update the npm syslink tag for stable to point to the version
2. update the module-server manifest to tag stable with the new version
These are setup as jobs that can be rerun if there are any errors or issues with running the first time.
Testing this by running this with a branch trigger, verified this was working fine.
Also tested each individual job and verified these work fine also in isolation
N/A
> chore: add GitHub Actions workflow for stable release

- .github/workflows/generate-dts-tests-if-needed.yml
- .github/workflows/lint-fix-if-needed.yml
- .github/workflows/pnpm-if-needed.yml
- .github/workflows/react-compiler.yml
We have auto merge enabled for renovatebot prs, but not for these chore prs. This leads to us often forgetting to merge them after they've been approved. Enabling auto merge doesn't override the review rules, a human has to approve the PR for it to actually merge.
Makes sense?
Can't really test it before merging 😅 
N/A
> chore: enable auto merge on chore prs

- .github/workflows/generate-dts-tests-if-needed.yml
- .github/workflows/lint-fix-if-needed.yml
- .github/workflows/pnpm-if-needed.yml
- .github/workflows/react-compiler.yml
#9983 introduced a regression where checks fail if no PR was made, as `steps.create-pull-request.outputs.pull-request-number` will be null, and GH doesn't like running `gh pr merge --squash --auto ""`:
- https://github.com/sanity-io/sanity/actions/runs/16348781503/job/46189644004
- https://github.com/sanity-io/sanity/actions/runs/16348781536/job/46189644011
It's fixed by adding a guard that only runs the auto merge command if a PR was created in the previous step.
Makes sense?
Have to merge to test 😬 
N/A
> chore: only set auto merge if a pr was created

- packages/sanity/src/core/studio/components/navbar/search/contexts/search/reducer.ts
Search results were previously only deduplicated when merging subsequent pages of results into the aggregated local state.
This was incorrect; the `groq2024` search strategy yields a result for every version of the document, and therefore must be deduplicated.
| --- | --- |
| <img width="848" height="412" alt="Screenshot 2025-07-18 at 16 18 19" src="https://github.com/user-attachments/assets/ce3be928-3c6d-4b71-8ef5-453270b7ba5c" /> | <img width="848" height="412" alt="Screenshot 2025-07-18 at 16 19 13" src="https://github.com/user-attachments/assets/4a93ceab-6406-4497-ba97-8cb5bf95b4b8" /> |
Global search, particularly with the `groq2024` search strategy switched on.
Tested in Test Studio, and verified existing tests pass.
Fixes a bug that could cause duplicate results …
> fix(sanity): deduplicate global search results

- packages/@repo/test-dts-exports/.depcheckrc.json
- packages/@repo/test-dts-exports/eslint.config.mjs
- packages/@repo/test-dts-exports/package.json
- packages/@repo/test-dts-exports/test/lib-check.test.ts
- packages/@repo/test-dts-exports/tsconfig.json
- pnpm-lock.yaml
The purpose of this PR is to add a new check that ensures that the `.d.ts` files we generate are valid and don't have type errors.
It's needed in order to land these PRs with confidence:
- https://github.com/sanity-io/sanity/pull/9714
- https://github.com/sanity-io/sanity/pull/8999
Unfortunately the code we ship on `main` already has issues when running type checking with `skipLibCheck: false`.
The `skipLibCheck` flag is a wide net, either it will type check all `.d.ts` and follow all rabbit holes through `node_modules`, or it will check none of them. 
This is a problem since some of the failing checks come from third party code that we have no way of "fixing", so we have to filter out expected errors from the unexpected.
Errors that are not actionable are already being filtered out, and …
> chore(test-dts-exports): disable skipLibCheck

- .github/workflows/release-latest.yml
This makes improvements to the latest release flow by allowing for individual segments of the workflow to be rerun in isolation.
Jobs are now
`build-and-validate` to create the bundles to release
`git-operations` which includes tagging the new release
`npm-publish` which allows for rerunning the npm publish step if this fails
`bundle-upload` which contains everything related to updating the module-server manifest for auto-update studios, and can be rerun if it fails
Other updates include:
* scoping only relevant write and read permissions and env vars to each job
* caching the earlier `build-and-validate` step so that the artifacts can be reused if jobs are rerun
N/A
> chore: using workflow jobs in latest release 

- packages/sanity/src/core/tasks/components/form/fields/DateEditFormField.tsx
Fixes https://github.com/sanity-io/sanity/issues/9792
When opening a task with no due date assigned it should not crash.
https://github.com/user-attachments/assets/758f1da6-1637-4218-a2b8-2bf0e148a0fa 
https://github.com/user-attachments/assets/179028f7-e4a1-4fb6-a13b-3c0bcbbd6c1c 
Fixes an issue in where tasks with no due dates crash to open
> fix(core): handle tasks with undefined dates

- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/__tests__/MediaLibrary.test.tsx
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/hooks/useEnsureMediaLibrary.ts
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/shared/EnsureMediaLibrary.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
Users are no longer permitted to provision a media library themselves. Therefore, Studio must not attempt to provision a media library for users on the fly.
Instead, a warning is shown when attempting to interact with a Media Library asset source should no media library exist for the current organisation.
Media Library asset sources, particularly when no media library exists for the current organisation.
Updated unit tests.
> fix(sanity): do not attempt to provision media library

- packages/@repo/test-dts-exports/test/lib-check.test.ts
- packages/sanity/src/core/i18n/hooks/useTranslation.ts
Doing so allows us to get rid of a `@ts-expect-error` directive, and one less exception to the DTS test suite (closes #9987).
Enough context on the inline?
If all is green we're good to go.
N/A
> refactor: inline `$Tuple` type helper

- dev/test-studio/schema/standard/images.ts
- packages/@sanity/types/src/schema/definition/type/file.ts
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/shared/SelectAssetsDialog.tsx
- packages/sanity/src/router/utils/jsonParamsEncoding.ts
This PR adds file schema options to configure GROQ filters for the Media Library selection dialog.
Do we have any Media Library field options already? I added a new type `MediaLibraryOptions`.
When using the `'Image with Media Library filter'` field in Dev Studio > Standard inputs > Images test, you should see the filters encoded and appended to the iframe url.
Adds new schema options to file and image fields for Media Library asset selection, to allow a field to specific a groq filter that is applied to the assets shown in the selection dialog. Example:
```js
{
name: 'imageWithMediaLibraryFilters',
title: 'Image with Media Library filter',
type: 'image',
options: {
mediaLibrary: {
filters: [
{
name: 'Has colourDetails aspect',
query: 'defined(aspects.colourDetails)',
},
{
name: 'Greater …
```
> feat(core): add media library field groq filters

- packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
- packages/sanity/src/core/store/_legacy/history/history/getJsonStream.ts
- packages/sanity/src/core/studio/addonDataset/AddonDatasetProvider.tsx
- packages/sanity/src/core/studioClient.ts
- test/e2e/helpers/sanityClient.ts
New version of `sanity/client` supports passing custom headers to all client requests.
It would be useful for us to have the studio version attached in these headers - this PR attached the `x-sanity-studio-version` header to all requests (both through the client and a few that use other means, eg [for translog](packages/sanity/src/core/store/_legacy/history/history/getJsonStream.ts))
Verified all network requests to sanity API include the studio-version header, and that the header is correct.
Downloaded a few HAR files from journeys through studio to ensure no requests were missing
N/A
> feat: add default headers for studio client requests

- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/studio/components/navbar/resources/ResourcesButton.tsx
- packages/sanity/src/core/studio/components/navbar/resources/StudioInfoDialog.tsx
This PR adds visual improvements and fixes to the Studio version dialog.
**Before**
**After**
Notes:
- "Enable auto-updates" now only show in non-dev environments when auto-updates has not been enabled
- We now treat prereleases ahead of latest as "up to date", so if you're on e.g. next, you won't see "How to upgrade"-affordances (if you're on a prerelease that's behind latest on npm, it will tell you)
Future work:
- If auto-updates is enabled, we should be able to detect that a new version is available, and show a reload-button in this dialog (also, possibly with a subtle indicatior on the "Help and resources" menu button).
- Easiest way to test manually is by checking out this branch and changing the version number in `packages/sanity/src/core/version.ts`
- Can also be tested by …
> refactor(core): improve studio version info dialog

- packages/@sanity/cli/src/commands/blueprints/addBlueprintsCommand.ts
Small fix for an invalid example in the help for `blueprints add`
Verify help text is now correct
Tested locally on the existing CLI
n/a
> fix(cli): Add missing flag to blueprints add example

- dev/test-studio/schema/debug/allFieldsGroupHidden.ts
- dev/test-studio/schema/index.ts
- dev/test-studio/structure/constants.ts
- packages/@sanity/schema/src/_exports/_internal.ts
- packages/@sanity/schema/src/legacy/types/constants.ts
- packages/@sanity/schema/src/legacy/types/object.ts
- packages/sanity/src/core/form/store/constants.ts
- packages/sanity/src/core/form/store/formState.ts
- packages/sanity/src/core/form/store/index.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/test/__snapshots__/exports.test.ts.snap
Fixes: https://github.com/sanity-io/sanity/issues/3142
This feature has been requested by multiple users. 
It will allow users to hide the `all-fields` group if they want to. While we keep the option to render it if we think it's necessary.
When do we need to render it:
- A field path is focused and the field is not part of any group defined.
- Review changes panel is open.
**How can you select a field that is not part of any group?**
By deep linking to a field, for example from presentation.
By clicking on a comment which points to a field that is not part of any group.
**How do we know this?**
We can detect this by checking the `props.fieldGroupState?.value` property in the `prepareObjectInputState` function. [See code here ](https://github.com/sanity-io/sanity/compare/all-fields-tab?exp …
> feat(core): allow all fields group customizations

- packages/@sanity/cli/package.json
- pnpm-lock.yaml
Was looking into an issue with installilng next-tagged versions failing due to an attempt at installing a version of `@sanity/util` that didn't exist. Seems to have been caused by the version specifier here. Did a journey back in the version history, and it does not seem like it was intentional to specify version here. It started happening after it was set to `workspace:` (note the missing `*`) here: https://github.com/sanity-io/sanity/commit/97c3b32940f2324a9f0fc25097c33f1813374644#diff-6d67d183f0cfde1b995377d627f65ae08e2f2e6ee6a8ea061e447f4e80d1613aR66-R69
> fix(cli): remove workspace version specifier

- .github/workflows/release-next.yml
- .github/workflows/release-stable.yml
We have this enabled in `release-latest` and it currently silently fails because we don't support tagging in production yet. 
Best to have this in place for when we do.
N/A
> chore: enable manifest update with tags in production

- .github/workflows/tag-latest.yml
Adds a workflow for tagging a specific version as `latest`
Almost a verbatim copy of the workflow that tags as `stable` – we can (and should) unify these later.
Needs to be in the main branch in order to use workflow dispatc
n/a
> fix(ci): add workflow to tag as latest

- packages/sanity/.depcheckrc.json
- packages/sanity/package.json
- pnpm-lock.yaml
Since the [fix in `rollup@4.46.2`](https://github.com/rollup/rollup/releases/tag/v4.46.2) it's no longer necessary to pin `rollup` to `4.45.3` ✨ 
This rolls back #10099 without reintroducing the #10096 regress.
Missed anything?
Existing tests are enough.
N/A
> fix: unpin rollup

- packages/sanity/src/_internal/cli/actions/app/devAction.ts
This PR fixes an issue with the App Dev Server where the spinner would print in between the "View your app in the Sanity dashboard here:" and the app URL causing the app URL to be malformed and unclickable.
Review that the spinner.stop() is placed correctly
Ensure that the spinner stops once the dev server has started
> fix(app server): stop spinner before printing url

- .github/workflows/release-latest.yml
- .github/workflows/release-next.yml
- packages/@repo/package.bundle/src/package.bundle.ts
Currently, bulding esm bundles for staging does not define the `__SANITY_STAGING__` global variable used by this check:
https://github.com/sanity-io/sanity/blob/a44fd5b3a7e534e93ee0dfa95c6c382e952dafac/packages/sanity/src/core/studio/packageVersionStatus/checkForLatestVersions.ts#L7
As a consequence, esm bundles loaded from staging will call production to check what latest version is, which gives confusing behavior. This PR fixes the issue by defining `__SANITY_STAGING__` based on the value of the `SANITY_INTERNAL_ENV` env var.
Does it make sense? A drawback here is that we now need to build bundles twice, but don't think there's any way around it.
I've tested locally that running `SANITY_INTERNAL_ENV=staging pnpm run build:bundle` makes the `__SANITY_STAGING__` variable to be rewritten …
> fix(ci): set SANITY_INTERNAL_ENV=staging when building esm bundles for staging

- packages/sanity/src/core/form/useDocumentForm.ts
Previously, `useDocumentForm` retrieved the current release id from context, short circuiting any consumer explicitly providing a release id parameter. This caused an issue in the split screen diff view in which the document panes would sometimes reflect the globally selected perspective, instead of the version selected locally in the pane.
Now, `useDocumentForm` respects the release id parameter again. Existing consumers already pass the globally selected perspective where relevant, so reaching up to the context from inside the hook is unnecessary.
The document version shown in the document editor pane and the split screen diff view.
- Verified existing tests work.
- Verified the change this was introduced for (#8759) still works correctly.
- Verified the correct versions are displayed …
> fix(sanity): ensure `useDocumentForm` uses provided release id

- package.json
- pnpm-lock.yaml
Only the v3 version of `@sanity/ui` should be overriden on the monorepo. The override is there to allow the `e2e-ui.yml` to work.
The `e2e-ui.yml` workflow isn't used by this monorepo directly, it's used by the `@sanity/ui` repo to ensure that PRs [run the Studio E2E testing suite and have tests pass](https://github.com/sanity-io/ui/blob/791cf985a0786b6d8d1dcf1b9048dbafd4c80586/.github/workflows/main.yml#L103) before it's allowed to merge and release.
[The way that workflow is setup is that it runs `pnpm pack` on a checkout of the PR branch on `sanity-io/ui`](https://github.com/sanity-io/sanity/blob/febbbeec6171e17dfb50a82bb7b216c65a847a39/.github/workflows/e2e-ui.yml#L34), then it [installs this tarball in the monorepo root using `pnpm add -w …
> chore: only override ui v3 for e2e tests

- packages/@repo/test-dts-exports/test/lib-check.test.ts
TypeScript reports reported these errors from `@sanity/sdk` when setting `skipLibCheck: false`:
```bash
node_modules/.pnpm/@sanity+sdk@2.1.0_@types+react@19.1.8_debug@4.4.1_immer@10.1.1_react@18.3.1_use-sync-external-store@1.5.0_react@18.3.1_/node_modules/@sanity/sdk/dist/index.d.ts:1:50 - error TS2307: Cannot find module './authStore' or its corresponding type declarations.
1 import {AuthStoreState as AuthStoreState_2} from './authStore'
~~~~~~~~~~~~~
node_modules/.pnpm/@sanity+sdk@2.1.0_@types+react@19.1.8_debug@4.4.1_immer@10.1.1_react@18.3.1_use-sync-external-store@1.5.0_react@18.3.1_/node_modules/@sanity/sdk/dist/index.d.ts:2:32 - error TS2307: Cannot find module '../store/createActionBinder' or its corresponding type declarations.
2 import {BoundStoreAction} from …
```
> chore: remove `@sanity/sdk` dts check exception

- packages/sanity/src/core/studio/components/navbar/resources/StudioInfoDialog.tsx
Fixes a small issue introduced with #10158:
If auto updates is enabled, and your studio version is up to date, we show current version as "New version".
Looks sane? I additionally removed the `+sha` part of the version here
n/a
n/a
> fix(sanity): hide new version if up to date

- dev/test-studio/sanity.config.ts
- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
Fixes an issue in where in live edit documents, if only 1 action was defined then the side menu was not rendered.
This is because we were giving the responsibility on deciding if we show the menu or not to the parent component, rather than checking in `DocumentStatusBarActionsInner` by using the `showMenu` prop.
However, in some cases the `actions.length` is equal to 1 and given we are not rendering the first action for live edits we need to render the action in the menu.
That is correctly calculated [here](https://github.com/sanity-io/sanity/compare/sapp-2875?expand=1#diff-03d1032a11101b44f7b434187bc60b3ab28590fb41259a719f358e4d2fe11094R62-R64)
```ts
const sideMenuItems = useMemo(() => {
return showFirstActionButton ? menuActionStates : [firstActionState, ...menuActionStates]
}, …
```
> fix(structure): render actions menu if sideMenuItems has actions

- packages/sanity/src/_internal/cli/actions/app/buildAction.ts
- packages/sanity/src/_internal/cli/actions/build/buildAction.ts
- packages/sanity/src/_internal/cli/actions/dev/devAction.ts
When building for auto-updates, we use the `version` from `sanity`'s  package.json  as resolved from the current project. We use this both as `minVersion` when generating import maps, but also for checking if runtime version is different from local version. Using `semver.coerce` with the resovled version doesn't work with prereleases as it will then try to find an unreleased minor version, e.g. `4.5.0-next.10` will build with `^4.5.0` as minVersion before `4.5.0` is actually released.
Does it make sense? It's not entirely clear to me why we used `semver.coerce` here in the first place - it would make sense if we read the sanity version from current studio's package.json => dependencies section, but can't see why it's needed when we get the exact version from node_modules.
I'm assuming we …
> fix(cli): don't coerce sanity version during build/dev

- packages/sanity/src/core/releases/tool/components/Table/Table.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
- Adds virtualisation to the list, changed the implementation because initially the issue was related to the scrolling, but when fixing the scrolling issue, it was giving problems with janky scrolling and "white" ghosts components
- The way that I went ahead to fix this was to make the structure closer to what we do in the `CommandList` (which is a list we use in the document list in the structure): Each virtual row is now absolutely positioned within the container, just like CommandList items.
https://github.com/user-attachments/assets/7cbf7f6d-a712-415f-b142-f0c99e28dfce
Before making this refactor, if the items were virtualised as they were, we would be re-rendering and recreating the table and rows. With the virtual container, only the absolutely positioned divs (rows) are …
> feat: virtualising release documents table

- dev/test-studio/schema/standard/portableText/allTheBellsAndWhistles.ts
- packages/sanity/src/core/form/inputs/PortableText/object/modals/PopoverModal.tsx
A hard one to debug with a simple fix
Adds `tabIndex=-1` to the Focus Lock first container div. 
This is to let `FocusLock` know that this element is focusable, so if the user clicks in the popover it can lose the input focus while keeping the popover open and not scrolling to the input
See video for details:
https://github.com/user-attachments/assets/227a103c-aa84-4694-9ef2-11f3de2a10dc
Open the all bells and whistles document, it should be possible to click outside of an input in a popover while the input loses focus.
> fix(core): allow losing focus inside popover modals, fix scroll in popover issue

- dev/test-studio/preview/InitialValues.tsx
- dev/test-studio/preview/main.tsx
- packages/sanity/src/core/form/useDocumentForm.ts
- packages/sanity/src/presentation/PresentationContent.tsx
- packages/sanity/src/presentation/PresentationNavigateProvider.tsx
- packages/sanity/src/presentation/PresentationTool.tsx
- packages/sanity/src/presentation/document/LocationsBanner.tsx
- packages/sanity/src/presentation/editor/ContentEditor.tsx
- packages/sanity/src/presentation/editor/DocumentListPane.tsx
- packages/sanity/src/presentation/editor/DocumentPane.tsx
- packages/sanity/src/presentation/editor/DocumentPanel.tsx
- packages/sanity/src/presentation/paneRouter/ChildLink.tsx
- packages/sanity/src/presentation/paneRouter/PresentationPaneRouterProvider.tsx
- packages/sanity/src/presentation/paneRouter/ReferenceChildLink.tsx
- packages/sanity/src/presentation/types.ts
- packages/sanity/src/presentation/useMainDocument.ts
- packages/sanity/src/presentation/useParams.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
This PR fixes missing support for editing references in Presentation Tool's pane router implementation. This should resolve [SAPP-2916](https://linear.app/sanity/issue/SAPP-2916/presentation-tool-create-action-generates-module-without-initial).
To support this change I've refactored/reworked Presentation's navigation handling so we aren't simply relying on debouncing all navigation calls. This was always an unpleasant workaround and was implemented before Presentation was migrated to the monorepo and changes to the imports from Structure we are using was trickier.
This should mean some cases where navigation events were being overridden, such as blur events not registering when clicking on a button that also triggered a navigation event (e.g. viewport switching) are now no longer present. …
> fix(sanity): presentation navigation issues and initial value handling

- packages/sanity/src/presentation/paneRouter/PresentationPaneRouterProvider.tsx
- packages/sanity/src/structure/panes/document/useDocumentPaneInspector.ts
Small change to fix an issue we've been working around in Presentation which I think makes sense to fix upstream.
When closing the legacy inspector panel, instead of using `omit` to remove the `inspect` parameter from the params object, we now explicitly set it to `undefined`. This just means that Presentation doesn't have to check if the parameter is present each time its pane router receives new params.
- Check the change in `useDocumentPaneInspector.ts` where `inspect: undefined` is set instead of omitting the property is correct.
The inspector functionality should be unchanged, ensure it opens and closes as before.
N/A
> fix(sanity): explicitly unset legacy inspect parameter

- dev/auto-updating-studio/.gitignore
- dev/auto-updating-studio/package.json
- dev/auto-updating-studio/sanity.cli.ts
- dev/auto-updating-studio/sanity.config.ts
- dev/auto-updating-studio/schemaTypes/index.ts
- dev/auto-updating-studio/static/.gitkeep
- pnpm-lock.yaml
Adds a dev/testing studio for auto updates so we have a canonical example project to look at during development.
> chore: add auto-updating dev studio

- package.json
Seems related to https://nodejs.org/en/blog/release/v22.18.0#2025-07-31-version-22180-jod-lts-aduh95 and an issue in tsx https://github.com/privatenumber/tsx/issues/694
With the new native type scripting we might no longer need tsx anyway, I can chase in a follow up
> chore: fix etl script

- packages/sanity/src/presentation/editor/PostMessageRefreshMutations.tsx
Fixes an issue in where presentation was not refreshing the documents values on changes for version documents. 
Fixes an issue in where presentation was not refreshing the documents values on changes for version documents.
> fix(presentation): send presentation/refresh events for version documents changes

- packages/@sanity/cli/test/tokens.test.ts
Skipping tests because they are failing when running with the test runner.
Running it locally by triggering the commands with the terminal the action works as expected.
> chore(cli): skip sanity tokens tests

- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
- packages/sanity/src/core/releases/tool/detail/__tests__/ReleaseSummary.test.tsx
- packages/sanity/src/core/releases/tool/detail/components/ReleaseActionBadges.tsx
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx
- packages/sanity/src/core/releases/tool/detail/releaseDocumentActions.ts
Releases now show a summary count of all documents, group by action in the release.
> feat: adding chips to release summary to show count of release actions

- packages/sanity/src/core/config/defineConfig.ts
While adding a new `boolean` configuration option to Studio, I noticed an odd behaviour when providing an array of workspaces to `defineConfig`. When setting the boolean option to `false`, TypeScript seemed to narrow the allowed type to `false`, yielding this type error:
```
The types of <some boolean option> are incompatible between these types. Type 'boolean' is not assignable to type 'false'. (ts2322)
``` 
Bizarrely, this issue only seems to manifest when passing an array of four items or longer to `defineConfig`, regardless of the content of the items.
One way to fix this in userland is to cast the value to a constant:
```
defineConfig([
{
someBooleanOption: false as const
},
// ...
```
However, we can solve this for our users by making `defineConfig`'s configuration type parameter …
> fix(sanity): unexpected type narrowing when array passed to `defineConfig`

- packages/sanity/src/_internal/cli/actions/app/devAction.ts
- packages/sanity/src/_internal/cli/actions/dev/devAction.ts
- packages/sanity/src/_internal/cli/server/devServer.ts
- packages/sanity/src/_internal/cli/server/getViteConfig.ts
This PR improves on the port selection for apps. If the default port (3333) is conflicting it would select a new port automatically and print that. Note: This is only done for apps as for studios using cookie auth you would have to have CORS setup for the new port.
Note that the Starting Dev server for apps is not a spinner anymore because we cannot control when Vite logs so it showed weird overlap. Studio dev server is unchanged
Existing tests should suffice, we have hard time testing app in the current tests
Automatically select a new port when running `sanity dev` on **apps** if the default port is occupied
> feat(cli): choses a new port if dev server is conflicted for apps

- packages/sanity/src/_internal/cli/actions/media/exportAssetsAction.ts
- packages/sanity/src/_internal/cli/commands/media/exportMediaCommand.ts
This change filters out video assets when exporting assets and asset documents from an Media Library with the `sanity media export` CLI command. The background for this is that we currently don't store the the source video files, and so we can't download the original when exporting.
Documentation has been updated to mention this caveat.
Fixes SAPP-2947
- That the video assets are skipped when exporting
Test by running the [CLI command](https://www.sanity.io/docs/media-library/media#d799c241f960) `sanity media export`
- N/a
> refactor: filter out video assets when exporting media library assets

- packages/sanity/src/structure/panes/document/documentPanel/banners/OpenReleaseToEditBanner.tsx
| <img width="533" height="68" alt="Screenshot 2025-08-13 at 16 08 56" src="https://github.com/user-attachments/assets/2911d32e-672b-4b21-a922-193ffd08cdff" /> | <img width="551" height="81" alt="Screenshot 2025-08-13 at 16 08 26" src="https://github.com/user-attachments/assets/3cb31617-8727-46ff-a9cb-a8f73ecd0c64" /> |
1. Open up a release perspective
2. Create a new document in this release
3. Change to draft perspective
4. See the banner at the top of the document
5. Reduce the width of the document pane -> see that the banner splits text awkwardly
Fixes an issue where text in document pane banners would split on narrow screens.
> fix: long release titles in open release to edit banner correctly flexed

- .github/renovate.json
We no longer need these workarounds: https://github.com/sanity-io/renovate-config/blob/main/workarounds-esm.json  Since we now have node 20.19 as the baseline
> chore(renovate): ignore ESM workarounds

- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/config/configPropertyReducers.ts
- packages/sanity/src/core/config/prepareConfig.tsx
- packages/sanity/src/core/config/types.ts
- packages/sanity/test/__snapshots__/exports.test.ts.snap
This is an internal only config property to allow for dev testing of new releases features.
This will be used both inside the release's document actions resolver, and inside the releases' tool components to feature flag views and logic.
N/A
> refactor(core): adding internal feature symbol for single document releases

- package.json
- packages/sanity/package.json
- pnpm-lock.yaml
[Renovatebot flagged these deps as deprecated](https://github.com/sanity-io/sanity/issues/4030):
I checked them out and in this PR I'm removing the ones we no longer need/use :)
> chore: remove unused `@types/*` deps

- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/plugin/documentActions/SchedulePublishAction.tsx
- packages/sanity/src/core/releases/plugin/documentActions/ScheduleUnpublishAction.tsx
- packages/sanity/src/core/releases/plugin/documentActions/index.ts
When the quota config flag is turned on:
When the quota config flag is not given in `sanity.config`:
N/A
> feat: add schedule publish and unpublish noop actions for draft documents

- packages/@sanity/types/src/schema/definition/type/block.ts
- packages/sanity/playwright-ct/tests/formBuilder/inputs/PortableText/Decorators.spec.tsx
The default decorator is called `'strike-through'`.
> fix(types): remove `'strike'`/`'strike-through'` decorator confusion

- dev/test-studio/package.json
- dev/test-studio/sanity.config.ts
- pnpm-lock.yaml
This PR sets up a reproduction for an issue with asset sources not being able to upload images from URLs if `directUploads` are disabled. 
Because of this, this snippet [from our docs](https://www.sanity.io/docs/studio/custom-asset-sources) doesn't actually work:
```ts
{
form: {
image: {
assetSources: () => [unsplashAssetSource],
directUploads: false,
},
},
}
```
This PR doesn't fix the issue, it just lands the repro so that whoever works on a fix has a better starting point.
Is it clear?
You can select images with unsplash in the regular workspace just fine: https://test-studio-git-sapp-2995.sanity.dev/test/structure/input-standard;imagesTest;9dd0abad-970e-48cd-8318-3b802bf91f1e%2Ctemplate%3DimagesTest
While the unsplash workspace demonstrates the issue: …
> chore: setup unsplash asset source, and workspace with repro

- packages/@sanity/schema/src/_exports/index.ts
- packages/@sanity/schema/src/legacy/Rule.ts
- packages/sanity/src/core/validation/Rule.ts
Move the schema Rule definition to the Schema package. This is done to support adding serializing schemas (specifically validations) in the @sanity/schema/descriptors package.
Refactor makes sense and nothing breaks.
Existing tests should be sufficient.
* Not required
> refactor(schema): move schema Rule to schema package

- packages/sanity/src/_internal/cli/actions/app/buildAction.ts
- packages/sanity/src/_internal/cli/actions/build/buildAction.ts
- packages/sanity/src/_internal/cli/actions/dev/devAction.ts
- packages/sanity/src/_internal/cli/util/__tests__/compareDependencyVersions.test.ts
- packages/sanity/src/_internal/cli/util/__tests__/getAutoUpdateImportMap.test.ts
- packages/sanity/src/_internal/cli/util/compareDependencyVersions.ts
- packages/sanity/src/_internal/cli/util/getAutoUpdatesImportMap.ts
Refactors how we generate import maps for auto updating studios. This is a foundation for follow-up work to support a new module url that includes app-id.
- This should not cause any observed changes in the CLI commands that relies on import map generation, e.g. `sanity build`, `sanity deploy`, `sanity app build` and `sanity app deploy`
Most touched code paths had tests already, added new tests for `getAutoUpdatesImportMap`, so overall test coverage should increase a little.
n/a – internal only
> refactor(sanity): generalize import map generation

- packages/@sanity/cli/test/__fixtures__/app/package.json
- packages/sanity/src/core/studio/components/navbar/search/definitions/operators/arrayOperators.ts
- packages/sanity/src/core/studio/components/navbar/search/definitions/operators/assetOperators.ts
- packages/sanity/src/core/studio/components/navbar/search/definitions/operators/definedOperators.ts
- packages/sanity/src/core/studio/components/navbar/search/definitions/operators/operatorTypes.ts
- packages/sanity/src/core/studio/components/navbar/search/definitions/operators/slugOperators.ts
- packages/sanity/src/presentation/preview/Preview.tsx
- pnpm-lock.yaml
- pnpm-workspace.yaml
Upgrades typescript to v5.9.2 and fixes compile errors that came after the upgrade (see #10157).
It seems like TypeScript is now able to catch more precise issues, revealing that a bunch of `defineSearchOperator()` calls was passing extra/invalid properties.
Also removed a `@ts-expect-error` directive that is no longer in effect
n/a
n/a – internal only
> chore(deps): update dependency typescript to v5.9.2

- package.json
- packages/@sanity/migrate/package.json
- pnpm-lock.yaml
Reverts sanity-io/sanity#10433 as this fails the export build step blocking our build process
> fix: revert "fix(deps): update dependency @sanity/mutate to ^0.12.5"

- .github/workflows/auto-retry-failed-jobs.yml
- packages/@sanity/util/test/createSafeJsonParser.test.ts
This PR should add auto-retrying of our test workflows.
This needs to be merged to main to be tested. If it doesn't work as expected the I can revert.
This can only be tested once this change and new workflow is in main.
Once merged then I will:
1. create a new feature branch PR
2. modify a unit test to fail
3. run `gh run list --workflow="Auto-rerun failed jobs (once)" --branch=<branch-name>` to verify that the retry is being run
N/A
> chore(ci): retry tests in ci

- packages/sanity/src/core/releases/tool/components/Table/Table.tsx
- packages/sanity/src/core/releases/tool/overview/__tests__/ReleasesOverview.test.tsx
The releasesOverviews test, specifically the ones related to loading were very flaky and it's likely due to some improvements on the performance done on the table.
- Fixed some linting issues which made the document harder to read
```
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser
in TestApp
```
````
Warning: validateDOMNesting(...): <div> cannot appear as a child of <tr>.
at div
````
It's on the tin
This PR is all tests!
> test: update unit tests for the releasesOverview to reduce flakiness

- packages/sanity/src/core/studio/telemetry/StudioTelemetryProvider.tsx
Adds the react version to telemetry, so we can get a handle on how many studios are on react 18 vs 19.
Is this the correct place for adding it? I assume it is since it tracks the studio version in the same `useEffect`.
Used telemetry debug techniques to test locally that it's sending the version, and that the version is usable (on the test studio `reactVersion` is `19.1.1`).
Telemetry now collects the react version in addition to the sanity version. [See Telemetry for more information on what we data we collect, how to opt-out and more.](https://www.sanity.io/telemetry)
> fix(telemetry): include react version

- packages/sanity/src/_internal/cli/server/getEntryModule.ts
Subject-verb disagreement.
"Modifications" (plural) needs "are" not "is".
This PR corrects a grammatical error in auto-generated warning comments from 
> Modifications to this file _is_ automatically discarded  
to 
> Modifications to this file _are_ automatically discarded  
This is a minor grammar correction in developer-facing comments and should not affect any functionality.
> fix: corrects tense in auto-generated comment

- packages/sanity/src/presentation/__tests__/useMainDocument.test.ts
- packages/sanity/src/presentation/types.ts
- packages/sanity/src/presentation/useMainDocument.ts
Presentation provides a helper context object as part of its Main Document Resolver API.
For example, when providing a resolve function:
```ts
presentationTool({
mainDocuments: defineDocuments([
{
route: "/pages/:type/:slug",
resolve(ctx) {
const { params } = ctx;
return {
filter: `_type == $type && slug.current == $slug}`,
params: {
type: params.type,
slug: params.slug.replaceAll("_", "-"),
},
};
},
},
]),
});
```
Currently, the `origin` property of the context object is only defined if the `route` property provided in the resolver is an absolute URL. This isn't strictly necessary, as we can fallback to using the `targetOrigin` value for relative URLs.
This PR updates `getRouteContext` to always return an origin, even for relative routes.
Confirm the new origin fallback is correct and …
> fix(presentation): always include origin in document resolver context

- packages/@sanity/cli/src/commands/blueprints/addBlueprintsCommand.ts
- packages/@sanity/cli/src/commands/blueprints/blueprints.telemetry.ts
RUN-696 requests added telemetry for the usage of --example. 
typically, traces and logs are set up in "actions" but the blueprints commands are adapters for the "cores" in runtime-cli, so this adds a simple telemetry.log directly to the command interface.
> chore(cli): telemetry.log blueprints add --example

- packages/sanity/src/_internal/cli/actions/app/undeployAction.ts
This PR updates the output of `npx sanity undeploy` for apps:
- Refers to the application by `title` in addition to `id` when confirming execution of the command
- Removes the mention of a hostname as this isn't currently a factor for custom apps
- Visually structures to output for better clarity
- Refers to the application by `title` in the summary of the command's execution
Before & after screenshots:
Is the new output clear and correct?
Tested with local builds and deploying/undeploying an app.
- The `sanity undeploy` command output has been improved for custom apps. It should now be clearer which application will be undeployed, as applications will be referenced by both their title and their ID.
> feat(cli): Improve undeploy output for apps

- packages/@sanity/cli/src/types.ts
This PR adds and updates the docstrings for the `AppConfig` type, by user request. These should help to clarify the purpose of each field in the `AppConfig` object.
Are the additions and updates correct and clear?
N/A, reference docs update only
None
> feat(cli): Add & update docstrings to AppConfig type

- package.json
- packages/@repo/test-dts-exports/package.json
- packages/@sanity/cli/package.json
- packages/sanity/package.json
- perf/tests/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Multiple majors of `@types/node` in a monorepo is bad, it leads to duplicated `vite`, `vitest` and many other deps. It's best to have everything on 1 version.
To make it easier to keep it that way I've moved `@types/node` into the pnpm catalog.
The new baseline is v24 since the dts testing suite requires it, as we're using `URLPattern` in Presentation Tool, and v22 doesn't have typings for it.
The version of `@types/node` we use doesn't have a consequence for how we ship code to npm, dts or esm/cjs, which is why this is a `chore` and doesn't have release notes 🙌
> chore(deps): upgrade `@types/node` to v24 using pnpm catalog

- packages/@repo/test-dts-exports/turbo.json
- packages/@repo/test-exports/turbo.json
Only the required `build` steps should be cached, running `vitest` and what not should not be cached, as turborepo isn't setup to understand the graph for how we run tests so it'll fail to expire the cache in some cases, and lead to PRs that should fail, randomly fail a later PR.
Makes sense?
If it's green we're good.
N/A
> chore(ci): dts and export tests suites shouldn't be cached

- packages/@repo/test-dts-exports/test/fixtures/sanity.test-d.ts
- packages/sanity/src/core/index.ts
- packages/sanity/src/core/perspective/PerspectiveProvider.tsx
- packages/sanity/src/core/perspective/getSelectedPerspective.ts
- packages/sanity/src/core/perspective/isPerspectiveWriteable.ts
- packages/sanity/src/core/perspective/navbar/currentGlobalPerspectiveLabel.tsx
- packages/sanity/src/core/perspective/types.ts
- packages/sanity/src/core/releases/components/dialog/DiscardVersionDialog.tsx
- packages/sanity/src/core/releases/util/getReleaseTone.ts
- packages/sanity/src/core/releases/util/util.ts
- packages/sanity/src/core/util/draftUtils.ts
- packages/sanity/src/structure/panes/document/documentPanel/banners/ChooseNewDocumentDestinationBanner.tsx
This change graduates the `SelectedPerspective` type to a public API.  The name *`SelectedPerspective`* is somewhat meaningless in wider contexts, so it has been renamed to `TargetPerspective`, which better describes what this type is: the name of a system bundle, or a document describing a release, that can be the target of some perspective selection.
I intend to use `TargetPerspective` in a new public API, so this type must graduate to a public API.
`SelectedPerspective` remains, but has been marked as deprecated.
- Does the name `TargetPerspective` make sense?
- Do you anticipate any issues in adding this to the public API?
- Do you anticipate any issues in deprecating `SelectedPerspective`?
Type check passes.
The beta `SelectedPerspective` type has been deprecated in favour of the …
> feat(sanity): graduate `SelectedPerspective` to public type `TargetPerspective`

- packages/sanity/src/core/util/draftUtils.ts
Fixes ETL occurring due to inferring union type from constant array:
```
Internal Error: Unable to follow symbol for "const"
```
Union type change.
ETL and type check passing.
> fix(sanity): ETL errors caused by inferring union types from constant arrays

- packages/sanity/src/core/field/diff/components/ChangeList.tsx
- packages/sanity/src/core/field/diff/components/FieldChange.tsx
- packages/sanity/src/core/field/diff/components/GroupChange.tsx
- packages/sanity/src/core/store/_legacy/document/document-pair/operations/restore.ts
- packages/sanity/src/core/store/_legacy/document/document-pair/serverOperations/restore.ts
- packages/sanity/src/core/store/_legacy/history/createHistoryStore.ts
This Pr fixes two different issues present in version document in where reverting changes and restoring revisions were not working correctly by passing the correct document id to the actions.
Are changes ok?
Create a version document, apply changes to it and try to revert them using the review changes inspector, it should work.
Create a version document, apply changes to it and try to restore a previous revision, it should work.
Fixes issues when restoring documents to revisions in version document and reverting document changes.
> fix: version document restore revision and revert changes actions

- packages/sanity/package.json
- packages/sanity/src/core/store/_legacy/document/getPairListener.ts
- packages/sanity/src/core/store/_legacy/document/utils/dedupeListenerEvents.ts
- pnpm-lock.yaml
We currently do some deduping as part of `sequentializeListenerEvents`, but this could still lead to problems if duplicates are received at either edge of the buffer we maintain to check for gaps in mutation events. This makes sure we dedupe listener events on the listener stream level.
I considered using `distinct(() => event.id)`, but that only supports flushing the set of already seen entries at discrete points in time, which could lead to duplicates coming in right before and after flushing. So instead I've opted for a ttlcache which clears entries after a while.  The assumption is that any duplicates would come relatively close to each other, either in time or in space.
n/a
> fix: dedupe listener events

- packages/sanity/src/core/store/_legacy/document/getPairListener.ts
- packages/sanity/src/core/store/_legacy/document/types.ts
- packages/sanity/src/core/store/_legacy/document/utils/__test__/sequentializeEvents.test.ts
- packages/sanity/src/core/store/_legacy/document/utils/sequentializeListenerEvents.ts
Adds a few improvements to our gap detection:
Currently, gap detection is based on when _a_ gap was first detected. However, there can be multiple gaps in our buffer, and if one gap resolves, we can allow for a little more time to let the next in line resolve. This could lead to gap recovery being triggered more often than needed, especially if there is latency in message delivery. 
This PR address this by adding a `messageReceivedAt ` property to listener events that reflects when the message was received by the client (this matches the `messageDispatchedAt` property on events sent from the server).
When we have a broken chain, we use this `messageReceivedAt` to check whether we have been out of sync for more than the deadline allows.
Existing tests updated
n/a
> refactor(core): make sequentializeListenerEvents more robust

- packages/sanity/src/core/components/popoverDialog/PopoverContainer.tsx
- packages/sanity/src/structure/panes/document/documentPanel/DocumentPanel.tsx
- packages/sanity/src/structure/panes/document/timeline/events/EventsTimelineMenu.tsx
- packages/sanity/src/structure/panes/document/timeline/timelineMenu.tsx
- Speeds up `<PortalProvider>` instances by making sure `__unstable_elements` are memoized.
- Removes `useArrayProp` from `<PopoverContainer>` and instead lets React Compiler handle the array conversion memo ([before](https://playground.react.dev/#N4Igzg9grgTgxgUxALhASwLYAcIwC4AEwAOgHYEED6MCYOpYaAbggDRkUDCEpeAhmlIIY7cgTwBPLAgLdeAoTAAKMCFjCiKNDJvFSZAJVr1GLAOpoAJngAWAZUkAbBCrUaOBKGAQBBGDD4JVyxRAF8CADNVDAIAcgABMD5SNEkAeig0WLJMHHwiSNwAdz4YSyMI1j1pAiM+ODwAOQhLNmrDBAiCcKiIGNiaerxslOxcQmACMCcES27I6LjpiWdLAFo4PvoEXjARsjS0ggAVGzQwAnOCPgIi3ABrUuhSObwIAgw+e5kwWBlbPiEWwyOT8QTCAgAcwQeAuwIIm38CAatystluNh2nm8c0EjFa1wIOBwLBgADoDkdTjJWhE+FBHIRQQoIV5aAQAAafAAeFmsNg5GLQcBsBEsEFopFihDuMHutwQjkcqPRxIgpIuACNkfTvOJMUS1OrhJSEXxHHAGYD2akLkU0aLNXwcQQePqZJteDsZQ6KaRPdMCA4VrNmeCYAQALxTGaWAAUYcUAEoCAAeWrGHimBB82zB5zBC …
> fix: improve PortalProvider and PopoverContainer perf

- packages/sanity/src/structure/panes/document/statusBar/DocumentStatusBarActions.tsx
There was an issue where trying to revert to an older revision was opening two dialogues and preventing you from actually being able to revert to that revision
Before
https://github.com/user-attachments/assets/3e49e1e4-3f3d-4465-bd31-e12052c5a0ff
After
https://github.com/user-attachments/assets/5c37b66a-4d28-42c4-904c-2d5eee7d1835
Does it make sense? is there a better solution?
Existing tests should be enough
Fixes issue where reverting to old revision in a document version was not possible
> fix: issue where trying to revert revision would open two dialogs 

- packages/@sanity/schema/src/descriptors/convert.ts
- packages/@sanity/schema/src/descriptors/types.ts
- packages/sanity/test/descriptors/schema.test.tsx
Adds serialization of i18n properties to a descriptor.
Mainly the conversion of the i18n struct the schema uses to the urn the descriptor seems to expect.
👍 
Not required.
> feat(descriptors): serialize i18n properties

- packages/sanity/src/core/form/inputs/files/common/assetSource.ts
This will ensure all query params for the upload API are correctly set.
We had a problem yesterday where someone using a Bynder asset source started getting 400 errors because changes in the Bynder API caused it to start emitting empty strings for the asset description.
So, if the `description` and similar properties are empty strings, they should not be passed to the upload API.
That the changes are correct.
N/A
> fix(core): make sure empty strings aren't passed to the upload API

- packages/sanity/src/core/releases/tool/components/ReleaseDocumentPreview.tsx
- packages/sanity/src/core/releases/tool/detail/documentTable/DocumentTableColumnDefs.tsx
Document was showing up as undefined if it was to unpublish in a release.
Thought we had fixed this but probably something that we did in between messed up the fetches or something, in any case this fixes it!
Does the code make sense? Any concerns
Existing tests should suffice 
Fixes issue where a document that will be unpublished was showing as undefined in the document list
> fix: issue where an unpublished documentwas howing up as undefined in the document list in a release detail

- packages/sanity/src/core/releases/tool/components/Table/Table.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseDetail.tsx
- packages/sanity/src/core/releases/tool/detail/ReleaseSummary.tsx
- packages/sanity/src/core/releases/tool/detail/ValidationProgressIndicator.tsx
- packages/sanity/src/core/releases/tool/detail/useBundleDocuments.ts
- packages/sanity/src/core/releases/tool/overview/ReleasesOverview.tsx
- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
- packages/sanity/src/core/releases/tool/overview/columnCells/ReleaseColumnValidationLoading.tsx
- packages/sanity/src/core/util/postYield.ts
- packages/sanity/src/core/util/schedulerYield.ts
Changed the fetching of the documents and validations so that they are grouped into requests versus attempting to send them off all in the a single way. I have attempted different solutions (both with rxjs and thought about workers) but came to the conclusion that for the work that we are currently this was the best approach. The largest deterrer for works is the overhead of work and the fact that we know we will have incoming work coming to these pages in the nearer future which might impact the structure of this feature anyway.
This is a good amount of juice for the squeeze.
**Overall**
- Added a method for caching the requests in the useBundleDocuments, this means that when navigating between the overview and the details will reuse the already existing data. It is also robust enough …
> feat: add validation per release on the release overview + add caching

- dev/test-studio/sanity.config.ts
- packages/sanity/src/core/form/components/formField/styles.ts
- packages/sanity/src/core/form/inputs/PortableText/PortableTextInput.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInput.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputBasic/StringInputBasic.test.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputBasic/StringInputBasic.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/StringInputPortableText.test.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/StringInputPortableText.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/diff/computeRangeDecorations.test.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/diff/computeRangeDecorations.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/diff/segments.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/diff/useOptimisticDiff.tsx
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/packageValue.test.ts
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/packageValue.ts
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/styles.ts
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/unpackageValue.test.ts
- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/unpackageValue.ts
- packages/sanity/test/__snapshots__/exports.test.ts.snap
- packages/sanity/test/form/renderStringInput.tsx
This branch introduces the new, Portable Text Editor based, primitive input component: `StringInputPortableText`.
This input component is used instead of the basic implementation when inline diffs are switched on. This is currently controlled by setting the `advancedVersionControl.enabled` Studio configuration option to `true`.
> [!TIP]
> I've switched this on in the Test Studio Playground workspace. Try navigating to `/playground/structure/input-standard;stringsTest;038a77b8-1a4c-4be7-8db6-79ac1612ae43%2Ctemplate%3DstringsTest?perspective=rAREWsMhm` to see inline diffs in action. [Vercel preview link](https://test-studio-git-feat-primitive-pte-fields.sanity.dev/playground/structure/input-standard;stringsTest;038a77b8-1a4c-4be7-8db6-79ac1612ae43?perspective=rAREWsMhm).
The Portable Text …
> feat(sanity): add `StringInputPortableText` with inline diff support

- packages/@sanity/types/src/assets/types.ts
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/shared/UploadAssetDialog.tsx
- packages/sanity/src/core/form/studio/assetSourceMediaLibrary/uploader.ts
- packages/sanity/src/core/i18n/bundles/studio.ts
This will handle uploads through the studio to the Media Library where a file already exists.
It will instead use the current ML asset and notify the user through a toast:
Is the toast sufficient for user feedback?
Is the text ok?
* Fix an error that occurred when uploading assets to the Media Library that already exists in the library.
> fix: handle uploading assets already existing in the ML

- packages/sanity/src/core/releases/tool/overview/ReleasesOverviewColumnDefs.tsx
Add the loading for validation for scheduled releases.
Scheduled requests will not need to run and won't require validation to be run since you can't edit or add new documents unless you make the release active again. This can't be done via the API either so it's a safe approach that doesn't add to the load
N/A
> chore: add validation to scheduled releases

- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/commands/functions/testFunctionsCommand.ts
- pnpm-lock.yaml
This PR adds new flags that allow user to simulate different event types like create, update and delete.
Ensure flags and example follow proper format.
Verified manually during development.
This change enables support for testing with Delta GROQ function. When the `event` flag is set to update and before and after data is provided via one of the new flags (`data-before/after`, `file-before/after`, `document-id-before/after`), then delta functions in the filter will work as they do in the deployed functions.
> feat(cli): Add delta flags to functions test command

- packages/sanity/src/core/releases/hooks/__tests__/useHasCardinalityOneReleaseVersions.test.tsx
- packages/sanity/src/core/releases/hooks/index.ts
- packages/sanity/src/core/releases/hooks/useHasCardinalityOneReleaseVersions.ts
- packages/sanity/src/core/releases/i18n/resources.ts
- packages/sanity/src/core/releases/plugin/documentActions/SchedulePublishAction.tsx
This PR adds on 2 conditions to the `ScheduledPublishAction` which is the action shown on draft documents to allow for a Scheduled Draft (cardinality 'one' release) to be created to publish them.
The 2 conditions when the action might be disabled are:
1. When there is already a version of the document that exists within a cardinality 'one' release
2. When the draft document has validation errors (in which case we should not be allowing for scheduling of an invalid document
Verified with manual testing since there are currently no tests of this action.
WIll add tests as fast-follow once scheduled drafts is released.
N/A - not currently public
> feat: can only create a single concurrent scheduled draft per document

- packages/sanity/src/core/error/__tests__/isKnownError.test.ts
- packages/sanity/src/core/store/_legacy/authStore/createAuthStore.ts
- packages/sanity/src/core/store/_legacy/cors/CorsOriginError.ts
- packages/sanity/src/core/studio/StudioErrorBoundary.tsx
- packages/sanity/src/core/studio/StudioRootErrorHandler.tsx
- packages/sanity/src/core/studio/components/navbar/navDrawer/ManageMenu.tsx
- packages/sanity/src/core/studio/components/navbar/presence/PresenceMenu.tsx
- packages/sanity/src/core/studio/components/navbar/resources/StudioInfoDialog.tsx
- packages/sanity/src/core/studio/components/navbar/userMenu/ManageMenu.tsx
- packages/sanity/src/core/studio/hooks/useEnvAwareSanityWebsiteUrl.ts
- packages/sanity/src/core/studio/screens/CorsOriginErrorScreen.tsx
Addresses a few common tripwires when running a studio against a staging workspace:
- Various links to manage goes to production, where the staging project does not exist
- The CORS error handler/dialog takes you to production, where the project does not exist.
This PR fixes this by adding an internal hook `useEnvAwareSanityWebsiteUrl()` which return sanity.work if the current workspace is configured to use `sanity.work` as as its apiUrl.
Makes sense? I focused on links to manage for now, and left links to docs etc. to point to production as it does not seem like we'd want docs links to take us to sanity.work.
Navigate to one of the staging dataset configured for test studio, click the menu items that takes you to manage (e.g. invite users, manage project)
n/a – internal
> fix: make links to manage staging aware

- packages/sanity/src/core/releases/plugin/index.ts
- packages/sanity/src/core/scheduled-publishing/tool/Tool.tsx
Adds a new warning banner when Scheduled Drafts is enabled, inside the Scheduled Publishing plugin:
Banner includes a link directly to the scheduled drafts list in content releases.
* Trying to get the link to work was a nightmare, settled on creating a new intent for the releases tool... thoughts?
* The banner only shows when scheduled drafts is enabled. if `releases.scheduledDrafts.enabled: false` then the banner won't show - the customer has explicitly opted out, so avoid noise
Go here - https://test-studio-git-feat-sapp-3081-scheduled-drafts-banner-s-790ac1.sanity.dev/test/schedules/state/scheduled
To test the case that scheduled drafts is turned off, set this in `test-studio/sanity.config.ts`:
```
...
[QUOTA_EXCLUDED_RELEASES_ENABLED]: false,
...
```
N/A
> feat: when scheduled drafts is enabled, showing banner in scheduled pub plugin

- packages/sanity/src/core/index.ts
- packages/sanity/src/structure/hooks/useDocumentIdStack.ts
- packages/sanity/src/structure/hooks/useFilteredReleases.ts
- packages/sanity/src/structure/panes/document/DocumentPaneProvider.tsx
- packages/sanity/src/structure/types.ts
- packages/sanity/test/__snapshots__/exports.test.ts.snap
By default, version layering includes all document versions, regardless of their expected publication time—or lack thereof. For example, it includes all ASAP and undecided versions, despite ASAP and undecided versions having no fixed chronology. There is no way to determine which ASAP or undecided version is expected to be published before another.
It also includes any existing draft, which has no fixed chronology, either.
This functionality is useful for listing all document versions in a deterministic order, but doesn't accurately portray the upstream and downstream versions based on expected publication time.
In strict mode, version layering instead only includes versions that have a fixed chronology. **Cross-version layering is only effective for scheduled versions, with all other …
> feat(sanity): add strict version layering

- packages/sanity/src/_singletons/context/PackageVersionInfoContext.tsx
- packages/sanity/src/core/i18n/bundles/studio.ts
- packages/sanity/src/core/studio/components/navbar/resources/StudioInfoDialog.tsx
- packages/sanity/src/core/studio/packageVersionStatus/PackageVersionStatusProvider.tsx
- packages/sanity/src/core/studio/packageVersionStatus/fetchLatestVersions.ts
Fixes a couple of minor issues with the studio version checker:
- It currently adds a console.warn in dev when it doesn't find an import map (this was an unindended change introduced in #10637)
- Simplifies "current version" check in case no appId is configured (saves a request since fetching the current `latest` version and the current auto-updating version is the same request if no appId is configured.
- Passes import map info through context down to the verison info dialog so we can tell if appId is missing, and show a configuration warning. This should clear up some confusion in cases where the studio doesn't load the version configured in sanity.io/manage
Makes sense?
Easiest way to test is by changing the debug values here: …
> fix(sanity): add a warning for version info dialog if appId is missing

- packages/sanity/src/core/comments/hooks/useResolveCommentsEnabled.ts
- packages/sanity/src/core/comments/plugin/studio-layout/CommentsStudioLayout.tsx
- packages/sanity/src/core/form/inputs/CrossDatasetReferenceInput/CrossDatasetReferenceInput.tsx
- packages/sanity/src/core/hooks/useFeatureEnabled.ts
- packages/sanity/src/core/releases/contexts/upsell/ReleasesUpsellProvider.tsx
- packages/sanity/src/core/releases/hooks/useIsReleasesPlus.ts
- packages/sanity/src/core/releases/plugin/documentActions/SchedulePublishAction.tsx
- packages/sanity/src/core/releases/store/useReleasePermissions.ts
- packages/sanity/src/core/scheduledPublishing/contexts/ScheduledPublishingEnabledProvider.test.tsx
- packages/sanity/src/core/scheduledPublishing/contexts/ScheduledPublishingEnabledProvider.tsx
- packages/sanity/src/core/tasks/context/enabled/TasksEnabledProvider.test.tsx
- packages/sanity/src/core/tasks/context/enabled/TasksEnabledProvider.tsx
- packages/sanity/src/core/tasks/plugin/TasksFooterOpenTasks.test.tsx
Releases might be disabled in `sanity.config` or because the releases feature is not enabled for the project. In both of these cases the new 'Schedule Publish' action on a draft document should not be available. This PR adds this conditionality in.
When on a free project:
With `releases.enabled: false` in `sanity.config` NOTE: 'Schedule' is the scheduled publish plugin action - I didn't touch the logic here:
* Adds on constants for use with the `useFeatureFlagEnabled`
* Uses the new constants in `ScheduledPublishAction` to ensure that the action returns null JSX with the releases feature is not enabled
Manually tested with a free project
Manually tested with a project with `sanity.config` `releases.enabled: false`
N/A
> fix: scheduled pub action only shows when releases enabled

- packages/@repo/test-dts-exports/test/fixtures/@sanity.cli.test-d.ts
- packages/@sanity/cli/package.json
- packages/@sanity/cli/src/types.ts
- pnpm-lock.yaml
[`@sanity/pkg-utils` now ship `ReactCompilerOptions` that use the typings exported by `babel-plugin-react-compiler`](https://github.com/sanity-io/pkg-utils/pull/1853). This PR makes the same change to `@sanity/cli`. The reason we used manual types were that `babel-plugin-react-compiler` did not export its typings in the early beta stage when we started using it.
Missed anything?
If type checks on the CI pass we good.
The `reactCompiler` typings in `sanity.cli.ts` now re-export the typings from the `babel-plugin-react-compiler` package you have installed in your project. The React Compiler has shipped new features since we started supporting it, for example [Runtime Feature Flags with Gating](https://react.dev/learn/react-compiler/incremental-adoption#runtime-feature-flags-with-gating), …
> fix: use generated react compiler typings

- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/diff/segments.tsx
Inline diff markers in drafts were being given the incorrect colour. This branch adds an exception to make sure drafts are handled the same way as ASAP and undecided versions. This makes sense from a temporal point of view, because all such versions have the published document as the upstream, and could be published at any time.
It'd be nice to do a refactor here eventually, but for now, this gets the job done.
The colours applied to inline diff markers.
Verified in Test Studio.
Inline diff markers in drafts now use the correct color.
> fix(sanity): use the correct colour for diffs in draft versions

- packages/sanity/src/core/form/inputs/StringInput/StringInputPortableText/StringInputPortableText.tsx
Pasting Portable Text data into `StringInputPortableText` breaks the input. Although it appears to reflect the pasted value, and the user can edit it, the updated value is never correctly emitted and the changes are not saved. This is because the structure of the pasted Portable Text data conflicts with the expected data structure.
This branch ensures Portable Text data is converted to text on paste. It also replaces each sequence of new line characters in inserted text with a single space character, to make sure new line characters cannot be inserted by pasting multi-line Portable Text data.
The new behaviours in `StringInputPortableText`.
Tested by pasting various instances of Portable Text data into `StringInputPortableText`. We should add a test for this if we're able to add Vitest …
> fix(sanity): pasting Portable Text data into `StringInputPortableText`

- packages/sanity/src/core/studio/components/navbar/workspace/ManageMenu.tsx
Similar to #10638, this uses the env aware links to manage so projects using staging will link to manage at sanity.work instead of sanity.io
Makes sense?
Go to a staging workspace in preview build, open the workspaces menu and check that manage links takes you to sanity.work/…
> fix(sanity): make new manage links staging aware

- packages/sanity/src/core/hooks/useReferringDocuments.ts
Fixes an issue with `useReferringDocuments` causing providing a field selection to produce an invalid query.
Not much test coverage here unfortunately, but I've manually tested that passing fields now generates a valid query and works as expected.
- Fixes an issue with `useReferringDocuments` causing providing a field selection to produce an invalid query.
> fix(core): wrap useReferringDocuments projection in curly braces

- packages/sanity/src/core/store/_legacy/project/projectStore.ts
Fixes an issue that could cause repeated request being issued to the `/projects/<projectId>` endpoint in case of a non 2xx status code (e.g. after session expiry)
- Makes sense?
- Also took the liberty of adding missing tags other requests in here as well
For now, this requires manually checking if the issue is fixed.
- Fixes an issue that could trigger repeated failing requests from the Studio to the `/projects/<projectId>` endpoint
> fix(core): avoid repeated failing org id requests

- dev/efps/sanity.cli.ts
eFPS should always use the workspace version of sanity, not follow autoupdating
N/A
> chore: turn off autoupdating on eFPS studio

- packages/sanity/src/core/form/studio/inputResolver/fieldResolver.tsx
Custom input types that extend the `datetime` input are not correctly being recognised by `isDateTimeSchemaType`. This means they fall-through to `PrimitiveField` and this causes the title to be rendered twice:
Now it renders once:
The test-studio doesn't have the correct schema setup to test this, but in `datetime.ts`:
```
export const customDateTime = defineType({
title: 'Published At Custom Field',
name: 'published_at',
type: 'datetime',
validation: (Rule) => Rule.required(),
})
export default defineType({
...,
fields: [
defineField({name: 'pub_at', type: 'published_at'}),
]
})
```
Fixes an issue where creating a custom `datetime` field type would cause the field title to appear twice.
> fix: datetime custom types resolves field wrapper
